### ISSUE TITLE
Kucoin fetch open orders doesn't seem to work

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#1000]
Kucoin fetch open orders doesn't seem to work. I can't fetch them all at once, which I can deal with, but when fetching a specific symbol it doesn't work either.

- OS: Windows
- Programming Language: Python sync
- CCXT version: 512
- Exchange: Kucoin
- Method: fetchOpenOrders

```
import ccxt
import test2_config as config


e = ccxt.kucoin()
e.verbose = True
e.apiKey = config.exchange_keys['kucoin']['key']
e.secret = config.exchange_keys['kucoin']['secret']
e.timeout = 60000
e.proxies = {'http': 'http://localhost:8080',
             'https': 'http://localhost:8080'}
e.fetchOpenOrders('PRL/NEO')

C:\Users\gaardiolor\Anaconda3\python.exe C:/Users/gaardiolor/PycharmProjects/Test2/_test/test_kucoin.py
GET https://api.kucoin.com/v1/market/open/symbols 
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/market/open/symbols 
Response: {'Date': 'Fri, 29 Dec 2017 21:09:02 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'ip-172-24-2-97.ap-northeast-1.compute.internal', 'Set-Cookie': '<snip>; Path=/; HttpOnly', 'Content-Length': '43918'} {"success":true,"code":"OK","msg":"<sniplooksgood>
GET https://api.kucoin.com/v1/market/open/coins 
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/market/open/coins 
Response: {'Date': 'Fri, 29 Dec 2017 21:09:05 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'kc-kitchen-ap3', 'Set-Cookie': '<snip>; Path=/; HttpOnly', 'Content-Length': '17325'} {"success":true,"code":"OK","msg":"Operation succeeded."<snip looks good>
GET https://api.kucoin.com/v1/order/active-map?symbol=PRL-NEO 
Request: {'KC-API-KEY': '<snip>', 'KC-API-NONCE': '1514581745232', 'KC-API-SIGNATURE': '<snip>', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/order/active-map?symbol=PRL-NEO 
Response: {'Date': 'Fri, 29 Dec 2017 21:09:06 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'kc-kitchen-ap3', 'Content-Length': '330'} 
{"success":true,"code":"OK","msg":"Operation succeeded.","timestamp":1514581746717,"data":
{"SELL":
[{"oid":"5a46a90d7c178f235433e8e3","userOid":null,"coinType":"PRL","coinTypePair":"NEO",
"direction":"SELL","price":0.007687,"dealAmount":0.5192,"pendingAmount":84.4779,
"createdAt":1514580238000,"updatedAt":1514580238000}],"BUY":[]}}
Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/Test2/_test/test_kucoin.py", line 12, in <module>
    e.fetchOpenOrders('PRL/NEO')
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 273, in fetch_open_orders
    return self.parse_orders(orders, market, since, limit)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 981, in parse_orders
    array = [self.parse_order(order, market) for order in array]

  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 981, in <listcomp>
    array = [self.parse_order(order, market) for order in array]
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 244, in parse_order
    side = order['type'].lower()
KeyError: 'type'
```

**Comment by kroitor** [comment]
Will fix shortly, thx for a nice report ;)

**Comment by kroitor** [comment]
This should work normally now in 514.

**Comment by gaardiolor** [comment]
Great, just wanted to tell you how I've fixed it but I see you did exactly the same. It works!
