### ISSUE TITLE
How to Withdraw USDT-TRC20 in EXMO?

### ISSUE THREAD

**Issue by 7menos0** [ccxt/ccxt#10016]
- OS: Linux
- Programming Language version: Python 3.8
- CCXT version: 1.56,60

I've tried using these parameters
```


import ccxt

exchange = ccxt.exmo({
    'apiKey': 'API_KEY 123',
    'secret': 'SECRET 123',

})



asd = exchange.withdraw('USDT', 50, 'MY_DESTINATION_TRX_ADDRESS','TRC20' )

```

```
Traceback (most recent call last):
  File "/home/oi/PycharmProjects/biblioteca/rascunho2.py", line 11, in <module>
    asd = corretora_B.withdraw('USDT', 50, 'TMuVgaHJkm8UYZYqaxmVrJf3yxEbKWam9e','TRC20' )
  File "/usr/local/lib/python3.8/dist-packages/ccxt/exmo.py", line 1119, in withdraw
    response = self.privatePostWithdrawCrypt(self.extend(request, params))
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 506, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 654, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/exmo.py", line 1379, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: exmo {"result":false,"error":"Error 10269: Provider temporarily unavailable due to technical problems","task_id":0}

Process finished with exit code 1
```
Thanks,

**Comment by drsavant-pub** [comment]
You need to add these parameters:  {'transport': 'TRC20'}  [API Doc Link](https://documenter.getpostman.com/view/10287440/SzYXWKPi#97f1becd-7aad-4e0e-babe-7bbe09e33706) >> Search for the word 'transport' and you'll see a description.
