### ISSUE TITLE
binance does not have a testnet/sandbox URL for sapi endpoints

### ISSUE THREAD

**Issue by alesha1488** [ccxt/ccxt#10033]
after updating to 1.56.24 and newer:

$binance->urls['api'] = $binance->urls['test'];

[Exchange Error] binance does not have a testnet/sandbox URL for sapi endpoints

#0 /ccxt/ccxt/php/Exchange.php(1425): ccxt\binance->sign('capital/config/...', 'sapi', 'GET', Array, NULL, NULL)
#1 /ccxt/ccxt/php/binance.php(4453): ccxt\Exchange->fetch2('capital/config/...', 'sapi', 'GET', Array, NULL, NULL, Array, Array)
#2 [internal function]: ccxt\binance->request('capital/config/...', 'sapi', 'GET', Array, NULL, NULL, Array, Array)
#3 /ccxt/ccxt/php/Exchange.php(2554): call_user_func_array(Array, Array)
#4 /ccxt/ccxt/php/binance.php(870): ccxt\Exchange->__call('sapiGetCapitalC...', Array)
#5 /ccxt/ccxt/php/Exchange.php(1753): ccxt\binance->fetch_currencies()
#6 /ccxt/ccxt/php/binance.php(2447): ccxt\Exchange->load_markets()
#7 [internal function]: ccxt\binance->fetch_open_orders('ETH/USDT')
#8 /ccxt/ccxt/php/Exchange.php(2557): call_user_func_array(Array, Array)
#9 ccxt\Exchange->__call('fetchOpenOrders', Array)

**Comment by alesha1488** [comment]
<?php
date_default_timezone_set ('UTC');

echo "CCXT v." . \ccxt\Exchange::VERSION . "\n";

$exchange = new \ccxt\binance (array (
                'apiKey' => $API_key,
                'secret' => $API_secret,
                'timeout' => 30000,
                'enableRateLimit' => true,
                'options'=>array('defaultType'=>'future'),
                'verbose'=>true,
                ));

$exchange->set_sandbox_mode(true);

try {

    $exchange->load_markets ();

} catch (\ccxt\BaseError $e) {
    echo 'Failed to load markets: ' . $e->getMessage () . "\n";
} catch (Exception $e) {
    echo '[Error] ' . $e->getMessage () . "\n";
}

$symbol = 'ETH/USDT';
$market = null;


try {
    $market = $exchange->market ($symbol);
} catch (\ccxt\BaseError $e) {
    echo $exchange->id . ' does not have market symbol ' . $symbol . "!\n";
    echo 'Markets symbols supported by ' . $exchange->id . ":\n";
    echo print_r ($exchange->symbols, true) . "\n";
    exit ();
}

if ($market['active']) {

    try {

                $result = $exchange->fetch_ticker ($symbol);
                var_dump ($result);

            } catch (\ccxt\NetworkError $e) {
                        echo '[Network Error] ' . $e->getMessage () . "\n";
                    } catch (\ccxt\ExchangeError $e) {
                                echo '[Exchange Error] ' . $e->getMessage () . "\n";
                            } catch (Exception $e) {
                                        echo '[Error] ' . $e->getMessage () . "\n";
                                    }

} else {

    echo $exchange->id . ' market ' . $symbol . " is inactive!\n";
    exit ();
}
?>


CCXT v.1.56.81
Failed to load markets: binance does not have a testnet/sandbox URL for sapi endpoints
binance does not have market symbol ETH/USDT!
Markets symbols supported by binance:

**Comment by kroitor** [comment]
Indeex, Binance does not have a sandbox testnet for SAPI-endpoints.
Try initializing your exchange like so:

```PHP
$exchange = new \ccxt\binanceusdm (array (
    'apiKey' => $API_key,
    'secret' => $API_secret,
    'options' => array(
        'fetchCurrencies': false,
    ),
));

$exchange->set_sandbox_mode(true);
```

↑ That should work, let us know if you still have issues with it.

**Comment by alesha1488** [comment]
Thank you! Close issue

**Comment by ugur1yildiz** [comment]
The following python code gives the error:
_ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints_
Just spot endpoint is required.

```python
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': API_KEY,    
    'secret': SECRET,
})
exchange.set_sandbox_mode(True)
exchange.verbose = True
print(exchange.fetch_status())
```
**Log:**
```Text
 File "G:\Program Files\Python310\lib\site-packages\ccxt\binance.py", line 1769, in fetch_status
    response = self.sapiGetSystemStatus(params)
  File "G:\Program Files\Python310\lib\site-packages\ccxt\base\exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "G:\Program Files\Python310\lib\site-packages\ccxt\binance.py", line 4554, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "G:\Program Files\Python310\lib\site-packages\ccxt\base\exchange.py", line 505, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "G:\Program Files\Python310\lib\site-packages\ccxt\binance.py", line 4430, in sign
    raise NotSupported(self.id + ' does not have a testnet/sandbox URL for ' + api + ' endpoints')
ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints
```

**Comment by kroitor** [comment]
> ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints

It literally tells the reason for the exception. `fetchStatus` is also an endpoint of Binance sapi.

You can disable the fetchCurrencies endpoint to skip it:

```Python
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': API_KEY,    
    'secret': SECRET,
    'options': {
         'fetchCurrencies': False,
    }
})
exchange.set_sandbox_mode(True)
exchange.verbose = True
exchange.iso8601(exchange.fetchTime())
```

**Comment by ugur1yildiz** [comment]
> 

It didn't work. I got the same error

**Comment by kroitor** [comment]
> > 
> 
> It didn't work. I got the same error.
> 
> Are you also suggesting to use fetchTime instead of fetchStatus?

Yes, fetchStatus is not supported by their testnet, cause their testnet does not support sapi endpoints, and fetchStatus is a sapi endpoint with Binance.
