### ISSUE TITLE
Typeerror with kucoin fetchopenorders

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#1003]
Typeerror with kucoin fetchopenorders , maybe because kucoin.py:255 filled is None.
`            'cost': price * filled,`

- OS: Windows
- Programming Language: python
- CCXT version: 516
- Exchange: Kucoin
- Method: fetchOpenOrders

```
import ccxt
import test2_config as config

e = ccxt.kucoin()
e.apiKey = config.exchange_keys['kucoin']['key']
e.secret = config.exchange_keys['kucoin']['secret']
e.timeout = 60000
e.verbose = True
e.proxies = {'http': 'http://localhost:8080', 'https': 'http://localhost:8080'}
e.load_markets()
e.fetchOpenOrders('DBC/NEO')

C:\Users\gaardiolor\Anaconda3\python.exe C:/Users/gaardiolor/PycharmProjects/test2/_test/test2.py
GET https://api.kucoin.com/v1/market/open/symbols 
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/market/open/symbols 
Response: {'Date': 'Fri, 29 Dec 2017 23:56:30 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'ip-172-24-2-125.ap-northeast-1.compute.internal', 'Set-Cookie': 'SESSION=<snip>; Path=/; HttpOnly', 'Content-Length': '43944'} {"success":true,"code":"OK","msg":"Operation succeeded.","timestamp":1514591790234,"data":<sniplooksgood>
GET https://api.kucoin.com/v1/market/open/coins 
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/market/open/coins 
Response: {'Date': 'Fri, 29 Dec 2017 23:56:32 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'ip-172-24-2-251.ap-northeast-1.compute.internal', 'Set-Cookie': 'SESSION=<snip>; Path=/; HttpOnly', 'Content-Length': '17325'} {"success":true,"code":"OK","msg":"Operation succeeded.","timestamp":1514591792125,"data":<sniplooksgood>
GET https://api.kucoin.com/v1/order/active-map?symbol=DBC-NEO 
Request: {'KC-API-KEY': ''<snip>', 'KC-API-NONCE': '1514591792214', 'KC-API-SIGNATURE': '<snip>', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/order/active-map?symbol=DBC-NEO 
Response: {'Date': 'Fri, 29 Dec 2017 23:56:33 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'close', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'localhost', 'Content-Length': '326'} {"success":true,"code":"OK","msg":"Operation succeeded.","timestamp":1514591793628,"data":{"SELL":[],"BUY":[{"oid":"5a46d2ac2572c3668a78bc5e","userOid":null,"coinType":"DBC","coinTypePair":"NEO","direction":"BUY","price":0.00126,"dealAmount":0.0,"pendingAmount":159.2001,"createdAt":1514590893000,"updatedAt":1514590893000}]}}

Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/test2/_test/test2.py", line 12, in <module>
    e.fetchOpenOrders('DBC/NEO')
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 273, in fetch_open_orders
    return self.parse_orders(orders, market, since, limit)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 981, in parse_orders
    array = [self.parse_order(order, market) for order in array]
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 981, in <listcomp>
    array = [self.parse_order(order, market) for order in array]

  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 255, in parse_order
    'cost': price * filled,
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

Process finished with exit code 1
```

**Comment by gaardiolor** [comment]
unfortunately the fix introduced another bug; 

```
  File "/usr/lib/python3.6/site-packages/ccxt/async/kucoin.py", line 241, in parse_order
    amount = order['amount']
KeyError: 'amount'
```
When reverting that line back to `amount = self.safe_float(order, 'amount')` it works

**Comment by kroitor** [comment]
@gaardiolor let me know if you have any more issues with it! Thx!
