### ISSUE TITLE
[wavesexchange] ccxt/wavesexchange.py", line 810 - Error: "unsupported operand type(s) for +: 'int' and 'NoneType'"

### ISSUE THREAD

**Issue by Maxximiliann** [ccxt/ccxt#10091]
- OS: Ubuntu 20.04.3 LTS
- Programming Language version: Python 3.9.6
- CCXT version: 1.55.12

```
#waves_exchange_config
import os
import ccxt


def connection():
    wallet_id = os.environ.get('WALLET_ID')
    wallet_key = os.environ.get('WALLET_KEY')

    waves_exch = ccxt.wavesexchange({
        'apiKey': wallet_id,
        'secret': wallet_key,
    })
    return waves_exch


if __name__ == '__connection__':
    connection()



import sys
import time
import simplejson as json
from loguru import logger
from erlastic import Atom as atom
import waves_exchange_config as we
from erlastic import port_connection
from requests.exceptions import HTTPError, ConnectTimeout
from urllib3.exceptions import MaxRetryError, ConnectTimeoutError, NewConnectionError
from ccxt.base.errors import RequestTimeout, NetworkError, AuthenticationError


logger.add('Logs/wallet_balances_stream.py_log_{time}.log',
           format="{time:HH:mm:ss!UTC} {message}",
           rotation="100 MB")

_mailbox, port = port_connection()


@logger.catch
def submit_report(success_status, report):
    full_report_json = json.dumps(report)
    try:
        port.send((atom(success_status), (full_report_json)))
    except (BrokenPipeError) as error:
        logger.exception(error)
        sys.exit()


@logger.catch
def get_balances():
    waves_exch = we.connection()
    waves_exch.load_markets()
    waves_exch.verbose = True
    try:
        balances = waves_exch.fetchBalance()
    except (MaxRetryError, ConnectTimeoutError, RequestTimeout, NewConnectionError,
            NetworkError, HTTPError, AuthenticationError, ConnectTimeout) as error:
        submit_report('error', {'error': str(error)})
    except Exception as crash_report:
        logger.exception(crash_report)
        submit_report('fatal_error', {'fatal_error': str(crash_report)})
    else:
        submit_report('ok', balances)


@logger.catch
def main():
    get_balances()
    time.sleep(.5)
    main()


if __name__ == '__main__':
    main()

```

```
01:25:42 unsupported operand type(s) for +: 'int' and 'NoneType'
Traceback (most recent call last):

  File "/home/apps/priv/python/wallet_balances_stream.py", line 57, in <module>
    main()
    └ <function main at 0x7f876cc18ee0>

  File "/home/apps/priv/python/wallet_balances_stream.py", line 51, in main
    get_balances()
    └ <function get_balances at 0x7f876cc18b80>

> File "/home/apps/priv/python/wallet_balances_stream.py", line 37, in get_balances
    balances = waves_exch.fetchBalance()
               │          └ <function wavesexchange.fetch_balance at 0x7f876cc625e0>
               └ ccxt.wavesexchange()

  File "/home/machinima/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 1340, in fetch_balance
    result[code]['total'] = self.from_precision(balance, decimals)
    │      │                │    │              │        └ None
    │      │                │    │              └ '1310409140'
    │      │                │    └ <function wavesexchange.from_precision at 0x7f876cc5de50>
    │      │                └ ccxt.wavesexchange()
    │      └ 'SWOP'
    └ {'CRV': {'free': None, 'used': None, 'total': '0.0000002'}, 'WEST': {'free': None, 'used': None, 'total': '0.00000086'}, 'USD...
  File "/home/machinima/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 810, in from_precision
    precise.decimals = precise.decimals + scale
    │       │          │       │          └ None
    │       │          │       └ 0
    │       │          └ <ccxt.base.precise.Precise object at 0x7f876cc1f430>
    │       └ 0
    └ <ccxt.base.precise.Precise object at 0x7f876cc1f430>
```

**Comment by kroitor** [comment]
This issue has been addressed in CCXT 1.57, do you have this issue with the most recent version 1.57.23?

**Comment by Maxximiliann** [comment]
Issue persists even after replacing 1.55.12 with 1.57.23: 

```
01:55:48 unsupported operand type(s) for +: 'int' and 'NoneType'
Traceback (most recent call last):

  File "/home/machinima/apps/priv/python/wallet_balances_stream.py", line 57, in <module>
    main()
    └ <function main at 0x7f15b4988ca0>

  File "/home/machinima/apps/priv/python/wallet_balances_stream.py", line 51, in main
    get_balances()
    └ <function get_balances at 0x7f15b4988940>

> File "/home/machinima/apps/priv/python/wallet_balances_stream.py", line 37, in get_balances
    balances = waves_exch.fetchBalance()
               │          └ <function wavesexchange.fetch_balance at 0x7f15b49d7280>
               └ ccxt.wavesexchange()

  File "/home/machinima/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 1296, in fetch_balance
    result[code]['total'] = self.from_precision(balance, decimals)
    │      │                │    │              │        └ None
    │      │                │    │              └ '1310409140'
    │      │                │    └ <function wavesexchange.from_precision at 0x7f15b49d5af0>
    │      │                └ ccxt.wavesexchange()
    │      └ 'SWOP'
    └ {'CRV': {'free': None, 'used': None, 'total': '0.0000002'}, 'WEST': {'free': None, 'used': None, 'total': '0.00000086'}, 'USD...
  File "/home/machinima/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 786, in from_precision
    precise.decimals = precise.decimals + scale
    │       │          │       │          └ None
    │       │          │       └ 0
    │       │          └ <ccxt.base.precise.Precise object at 0x7f15b49a5040>
    │       └ 0
    └ <ccxt.base.precise.Precise object at 0x7f15b49a5040>
```

**Comment by kroitor** [comment]
@Maxximiliann will get this resolved tonight, thx for reporting.

**Comment by ttodua** [comment]
Might be related to inexistent pair: https://github.com/ccxt/ccxt/issues/10613#issuecomment-987881770
