### ISSUE TITLE
RaspberryPi Error When Windows 10 Working

### ISSUE THREAD

**Issue by iMichaelM** [ccxt/ccxt#10142]
- OS: RaspberryPi - latest raspbian
- Programming Language version: 3.7
- CCXT version: 1.56.63

Hey guys, could you please kindly help me out here? I've been running the below code on a Windows PC for a week straight, no issues but when I switched to a RaspberryPi, all of a sudden, I'm getting this long error msessage. Not right away either, sometimes after a few mins, sometimes a few hours...

Many thanks!

```
import ccxt
import pandas_ta as ta
import config
import schedule
import pandas as pd
from datetime import datetime
import time
import socket

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 250)

exchange = ccxt.binance({
    'apiKey': config.BINANCE_API_KEY,
    'secret': config.BINANCE_API_SECRET,
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future'
    },
})

in_position = False
free_balance = exchange.fetch_free_balance()
used_balance = exchange.fetch_used_balance()
free_usd = (free_balance['USDT'])
used_usd = (used_balance['USDT'])
amount = ((free_usd + used_usd) * 0.99)
quantity = 0
new_quantity = 0


def trigger(df):
    global in_position
    global amount
    global quantity
    global new_quantity

    df = df.assign(rsi=ta.rsi(df['close']).values)
    df.ta.stoch(high='high', low='low', k=10, append=True)
    df.ta.macd(close='close', fast=18, slow=25, signal=15, append=True)
    df.drop('STOCHd_10_3_3', axis=1, inplace=True)
    df.drop('MACDh_18_25_15', axis=1, inplace=True)
    df.columns.values[7] = "stoch"
    df.columns.values[8] = "macd"
    df.columns.values[9] = "macd_signal"

    print("Checking for buy & sell signals")
    print(df.tail(5))
    for current in range(1, len(df.index)):
        prev = current - 1

    if df['macd'][prev] > df['macd_signal'][prev] and df['rsi'][prev] > 50 and df['stoch'][prev] > 50:
        if not in_position:
            quantity = amount / df['close'][current]
            order = exchange.create_market_buy_order('SOL/USDT', quantity)
            new_quantity = quantity
            print(order)
            in_position = True
        else:
            print("Long")
    if df['macd'][prev] < df['macd_signal'][prev]:
        if in_position:
            order = exchange.create_market_sell_order('SOL/USDT', new_quantity)
            print(order)
            in_position = False
        else:
            print("Not in position.")


def algo():
    print(f"Loading data as of {datetime.now().isoformat()}")
    bars = exchange.fetch_ohlcv('SOL/USDT', timeframe='4h', limit=100)
    df = pd.DataFrame(bars, columns=['time', 'open', 'high', 'low', 'close', 'volume'])
    df['time'] = pd.to_datetime(df['time'], unit='ms')
    df.set_index(pd.DatetimeIndex(df['time']), inplace=True)

    trigger(df)


try:
    schedule.every(1).minute.at(":00").do(algo)

    while True:
        schedule.run_pending()
        time.sleep(0.1)
except ConnectionResetError:
    schedule.every(1).minute.at(":00").do(algo)

    while True:
        schedule.run_pending()
        time.sleep(0.1)
except socket.timeout:
    schedule.every(1).minute.at(":00").do(algo)

    while True:
        schedule.run_pending()
        time.sleep(0.1)
except ccxt.NetworkError:
    schedule.every(1).minute.at(":00").do(algo)

    while True:
        schedule.run_pending()
        time.sleep(0.1)
```

```
Traceback (most recent call last):
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1352, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='fapi.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 594, in fetch
    verify=self.verify
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='fapi.binance.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/PycharmProjects/Algo/SOL.py", line 85, in <module>
    schedule.run_pending()
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/schedule/__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/home/pi/PycharmProjects/Algo/SOL.py", line 73, in algo
    bars = exchange.fetch_ohlcv('SOL/USDT', timeframe='4h', limit=100)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/binance.py", line 1789, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/binance.py", line 4281, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 617, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://fapi.binance.com/fapi/v1/klines?interval=4h&limit=100&symbol=SOLUSDT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xb23152b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=4h&limit=100&symbol=SOLUSDT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb23152b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 594, in fetch
    verify=self.verify
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/klines?interval=4h&limit=100&symbol=SOLUSDT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb23152b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/PycharmProjects/Algo/SOL.py", line 103, in <module>
    schedule.run_pending()
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/schedule/__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/home/pi/PycharmProjects/Algo/SOL.py", line 73, in algo
    bars = exchange.fetch_ohlcv('SOL/USDT', timeframe='4h', limit=100)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/binance.py", line 1789, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/binance.py", line 4281, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/pi/PycharmProjects/Algo/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 639, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://fapi.binance.com/fapi/v1/klines?interval=4h&limit=100&symbol=SOLUSDT
```

**Comment by frosty00** [comment]
@iMichaelM you need to handle the error like so

```
try:
    await exchange.fetch
except ccxt.NetworkError:
    print('a network error happened')
```

**Comment by iMichaelM** [comment]
Maybe it's simple but how do you suggest it I wrap the code with it, given it currently runs as per below? In other words, where exactly should I put it?

try:
    schedule.every(1).minute.at(":00").do(algo)

    while True:
        schedule.run_pending()
        time.sleep(0.1)

**Comment by iMichaelM** [comment]
Anybody, please?

**Comment by ttodua** [comment]
@iMichaelM
The question you ask (how to wrap code within try/catch) is not much ccxt-related in this case, but it depends on your desire. You can wrap the whole code or either the 'while' part only. However, in this case I think it's better wrapping all code in try/catch.

Please let us know if you find any bug in ccxt again, and don't forget to use latest CCXT updated version.
