### ISSUE TITLE
In the exchange LBank, market buy order still needs param 'amount' even if it has been provided.

### ISSUE THREAD

**Issue by 0x11111111** [ccxt/ccxt#10170]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 11 / Ubuntu 21.4
- Programming Language version: Python 3.9
- CCXT version: 1.57.68

```
lbank = exchange_market = ccxt.lbank({
                'apiKey': api_key,
                'secret': secret_key,
                'enableRateLimit': True,
 })
lbank.create_market_buy_order(symbol='SHIB/USDT', amount=1000000)
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\DYPro\PycharmProjects\style-rotation-trader\venv\lib\site-packages\ccxt\base\exchange.py", line 2052, in create_market_order
    return self.create_order(symbol, 'market', side, amount, price, params)
  File "C:\Users\DYPro\PycharmProjects\style-rotation-trader\venv\lib\site-packages\ccxt\lbank.py", line 457, in create_order
    response = self.privatePostCreateOrder(self.extend(order, params))
  File "C:\Users\DYPro\PycharmProjects\style-rotation-trader\venv\lib\site-packages\ccxt\base\exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\DYPro\PycharmProjects\style-rotation-trader\venv\lib\site-packages\ccxt\base\exchange.py", line 506, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\DYPro\PycharmProjects\style-rotation-trader\venv\lib\site-packages\ccxt\base\exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\DYPro\PycharmProjects\style-rotation-trader\venv\lib\site-packages\ccxt\base\exchange.py", line 654, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\DYPro\PycharmProjects\style-rotation-trader\venv\lib\site-packages\ccxt\lbank.py", line 621, in handle_errors
    raise ErrorClass(message)
ccxt.base.errors.InvalidOrder: Market orders can not be missing the amount of the order
```

**Comment by kroitor** [comment]
Ok, this is a misleading error message from the Lbank's docs.
As you can see from your own output above, the `amount` is correctly passed to Lbank in the request:

```
Request: POST https://api.lbank.info/v1/create_order.do
Request headers:
{
   'Content-Type': 'application/x-www-form-urlencoded',
    'User-Agent': 'python-requests/2.26.0',
    'Accept-Encoding': 'gzip, deflate'
} 
Request params:
amount=1000000&api_key=819f4194-f363-47ce-a7bf-da9626105653&symbol=shib_usdt&type=buy_market&sign=qxpTSahgR6QeXMKuZvjaBUuP10r8fM3ZGgOm7xViK0X20IiUELUl7OLME1%2BS%2FLinSCv2YnHcP%2FfD0sBRXsLCIiWAIlCz2gdaDBv6WdsS03UrLNkuduEh2n2760Doi%2Fh3KwgkF0c65U4uW7TDOvu1UZeguij1M5XbnPkrq%2BzGmU0%3D

^^ here
```

I think, what they actually want is a price for a market-buy order to calculate the cost of the order. This is explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#market-buys

Please, paste your output if this does not help:

```Python
lbank = exchange_market = ccxt.lbank({
    'apiKey': api_key,
    'secret': secret_key,
})
markets = lbank.load_markets()
lbank.verbose = True
price = 0.00002204  # YOUR PRICE HERE
lbank.create_market_order(symbol='SHIB/USDT', amount=1000000, price=price)
```

**Comment by 0x11111111** [comment]
It seems still not work out.
Other setup remains unchanged.
Code:
```
price = 0.00002204
lbank.create_market_buy_order(symbol='SHIB/USDT', amount=1000000, price=price)
```
Error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: create_market_buy_order() got an unexpected keyword argument 'price'
```

**Comment by 0x11111111** [comment]
> @0x11111111 thanks for your feedback! Appreciate it! We will add workarounds to handle the above in a user-friendly way in the lib.

Thanks for your patience in helping me out. I'd like to assist if you need translation of the Chinese documents.
