### ISSUE TITLE
bitfinex2 throws currency: invalid on fetchTransactions

### ISSUE THREAD

**Issue by steebchen** [ccxt/ccxt#10172]
- OS: MacOS
- Programming Language version: node v16.8.0
- CCXT version: ccxt@1.57.68

Basically `bitfinex2` fetchTransactions does not seem to work. 

```js
const exchange = new ccxt.bitfinex2({
  // ...
})
const currencies = await exchange.fetchCurrencies()
for (const currency in currencies) {
	const code = currencies[currency].code
	await exchange.fetch(code, since, limit)
}
```

Throws this, e.g. with parameter AAVE or BTC or really any currency code:

```
Bitfinex fetchTransactions BTC 1420070400000 2015-01-01T00:00:00.000Z 100 BadRequest: bitfinex2 currency: invalid
    at bitfinex2.throwExactlyMatchedException (/Users/luca/projects/exchanges/node_modules/ccxt/js/base/Exchange.js:595:19)
    at bitfinex2.handleErrors (/Users/luca/projects/exchanges/node_modules/ccxt/js/bitfinex2.js:1648:18)
    at /Users/luca/projects/exchanges/node_modules/ccxt/js/base/Exchange.js:657:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/Users/luca/projects/exchanges/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async bitfinex2.fetchTransactions (/Users/luca/projects/exchanges/node_modules/ccxt/js/bitfinex2.js:1476:26) {
  constructor: [class BadRequest extends ExchangeError]
}

```

I'm using `bitfinex2` as it seems that the opposite behaviour applies to `bitfinex` as I can fetch the transactions but not the trades. Is this a known issue? Or am I doing something wrong? The same code works for other exchanges.

**Comment by kroitor** [comment]
```JavaScript
const exchange = new ccxt.bitfinex2({
  // ...
})
const currencies = await exchange.fetchCurrencies()
for (const currency in currencies) {
	const code = currencies[currency].code
	await exchange.fetch(code, since, limit) // <--------- this line looks wrong to me, no fetchTransactions here
}
```

**Comment by ttodua** [comment]
I've reproduced the issue. It's bug in ccxt and fix will be submitted shortly.
