### ISSUE TITLE
'ndax' object has no attribute 'login'

### ISSUE THREAD

**Issue by noHomoRey** [ccxt/ccxt#10187]
- OS: Windows 10
- Programming Language version: Python 3.8.5
- CCXT version: 1.57.82

```
import ccxt
exchange = ccxt.ndax({
       'apiKey':
       'secret':
       'uid':
       'enableRateLimit': True,})
symbol = 'XRP/CAD'
type = 'Limit'
side = 'buy'
amount = 10
price = 1.440

order = exchange.create_order(symbol, type, side, amount, price)
print(order)
```

```
Traceback (most recent call last):
  File "C:/Users/~/Desktop/Python_examples/~.py", line 45, in <module>
    ndax_order = exchange.create_order(symbol, type, side, amount, price)
  File "C:\Users\~\Desktop\Python_examples\venv\lib\site-packages\ccxt\ndax.py", line 1159, in create_order
    self.load_accounts()
  File "C:\Users\~\Desktop\Python_examples\venv\lib\site-packages\ccxt\base\exchange.py", line 1422, in load_accounts
    self.accounts = self.fetch_accounts(params)
  File "C:\Users\~\Desktop\Python_examples\venv\lib\site-packages\ccxt\ndax.py", line 835, in fetch_accounts
    if not self.login:
AttributeError: 'ndax' object has no attribute 'login'
```

**Comment by taylornielson** [comment]
@kroitor So to use the ccxt NDAX api we must provide an API Key/secret AND the login credentials (login and password)?

**Comment by kroitor** [comment]
@taylornielson yes, you can see how those credentials are used from the source code in this repo: https://github.com/ccxt/ccxt/blob/master/python/ccxt/ndax.py
