### ISSUE TITLE
fapiPrivate_post_leverage not working

### ISSUE THREAD

**Issue by memory942** [ccxt/ccxt#10192]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: win10
- Programming Language version: python 3.9
- CCXT version: latest

```
binance_client = ccxt.binanceusdm({
    'apiKey': public_key,
    'secret': secret_key,
    'timeout': 30000,
    'enableRateLimit': True,
    'rateLimit': 250,
    'options': {'defaultType': 'future', },
})

binance_client.fapiPrivate_post_leverage({
    "symbol": "BTCUSDT",
    "leverage": 10,
})
```

```
Traceback (most recent call last):
  File "C:\Users\01\PycharmProjects\codetest\venv\lib\site-packages\ccxt\base\exchange.py", line 597, in fetch
    response.raise_for_status()
  File "C:\Users\01\PycharmProjects\codetest\venv\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/leverage

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\01\PycharmProjects\codetest\main.py", line 17, in <module>
    binance_client.fapiPrivate_post_leverage({
  File "C:\Users\01\PycharmProjects\codetest\venv\lib\site-packages\ccxt\base\exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\01\PycharmProjects\codetest\venv\lib\site-packages\ccxt\binance.py", line 4123, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\01\PycharmProjects\codetest\venv\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\01\PycharmProjects\codetest\venv\lib\site-packages\ccxt\base\exchange.py", line 613, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\01\PycharmProjects\codetest\venv\lib\site-packages\ccxt\binance.py", line 4117, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Users\01\PycharmProjects\codetest\venv\lib\site-packages\ccxt\base\exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: binanceusdm {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
```

Worked fine until yesterday. No changes made to the code.

**Comment by kroitor** [comment]
@memory942 do not override the `rateLimit`. If you have the most recent version, this should work with a fresh keypair:

```Python
print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binanceusdm({
    'apiKey': public_key,
    'secret': secret_key,
    'enableRateLimit': True,
})

response = exchange.setLeverage(10, 'BTC/USDT')
print(response)
```

Let us know if the above does not help.

**Comment by memory942** [comment]
nvm, checked out your link and resynced my time, it works fine again. I don't know why the time desynced.

**Comment by kroitor** [comment]
@memory942 thanks for your feedback, good to know you have it resolved. 

>  I don't know why the time desynced.

Windows is notoriously bad at time synching with default settings – make sure to read more of the above links.
