### ISSUE TITLE
When trying to fetch_positions i get this error: ZeroDivisionError: integer division or modulo by zero. 

### ISSUE THREAD

**Issue by alvoz** [ccxt/ccxt#10217]
```
exchange.fetch_positions(symbols=ticker)
```

```
  File "C:/Users/tests.py", line 26, in <module>
    exchange.fetch_positions(symbols=ticker)
  File "C:\Users\lib\site-packages\ccxt\binance.py", line 3616, in fetch_positions
    result = self.parse_account_positions(account)
  File "C:\Users\Desktop\lib\site-packages\ccxt\binance.py", line 3272, in parse_account_positions
    }), market)
  File "C:\Users\Desktop\lib\site-packages\ccxt\binance.py", line 3381, in parse_position
    marginRatio = self.parse_number(Precise.string_div(maintenanceMarginString, collateralString, 4))
  File "C:\Users\Desktop\lib\site-packages\ccxt\base\precise.py", line 116, in string_div
    return str(Precise(string1).div(Precise(string2), precision))
  File "C:\Users\Desktop\lib\site-packages\ccxt\base\precise.py", line 53, in div
    result, mod = divmod(numerator, other.integer)
ZeroDivisionError: integer division or modulo by zero
```

Code was working fine and then all of a sudden stopped.

**Comment by alvoz** [comment]
Hi thanks for the reply

```
CCXT Version: 1.58.7

Traceback (most recent call last):
  File "C:/Users/tests.py", line 23, in <module>
    exchange.fetch_positions(symbols=ticker)
  File "C:\Users\Desktop\lib\site-packages\ccxt\binance.py", line 4151, in fetch_positions
    result = self.parse_account_positions(account)
  File "C:\Users\Desktop\lib\site-packages\ccxt\binance.py", line 3806, in parse_account_positions
    }), market)
  File "C:\Users\Desktop\lib\site-packages\ccxt\binance.py", line 3915, in parse_position
    marginRatio = self.parse_number(Precise.string_div(maintenanceMarginString, collateralString, 4))
  File "C:\Users\Desktop\lib\site-packages\ccxt\base\precise.py", line 151, in string_div
    return str(Precise(string1).div(Precise(string2), precision))
  File "C:\Users\desktop\lib\site-packages\ccxt\base\precise.py", line 49, in div
    result, mod = divmod(numerator, other.integer)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by kroitor** [comment]
@alvoz can you please add the verbose switch before the failing call? (as shown in my previous comment here: https://github.com/ccxt/ccxt/issues/10217#issuecomment-942792231)

**Comment by alvoz** [comment]
Hi @kroitor this error seems to have reoccurred for me when trying to `fetch_positions`
