### ISSUE TITLE
FTX client.fetch_positions() not showing recentPnl when 'showAvgPrice':True

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#10211]
- OS: Windows 10
- Programming Language version: Python 3.8.10
- CCXT version: 1.57.98

```
import ccxt
import pandas as pd
client = ccxt.ftx({'apiKey': 'public', 'secret': 'private','headers': {'FTX-SUBACCOUNT': 'sub'}})
positions = pd.DataFrame(client.fetch_positions(params={'showAvgPrice':True}))
totalPnl = positions['recentPnl'].sum()

```

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\X\AppData\Local\Temp/ipykernel_1232/2406792295.py", line 2, in <module>
    totalPnl = positions['recentPnl'].sum()

  File "C:\Users\X\anaconda3\lib\site-packages\pandas\core\frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)

  File "C:\Users\X\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err

KeyError: 'recentPnl'
```
In the older versions (1.56.41) it still works so I am not sure what causes this problem.

**Comment by frosty00** [comment]
closed in #10213

**Comment by kroitor** [comment]
@Tomas-MP we have switched back to FTX's positions endpoint in CCXT 1.57.99+
However, since the response of `fetch_positions` will return the unified structure to you, you want to either adjust the lookup to dive into the exchange-specific `info` for each position, or just switch to the implicit method called `privateGetPositions` and that will return the same response as it did in your older version 1.56.41.

**Comment by Tomas-MP** [comment]
@kroitor I'll figure it out, thank you for fixing it!
