### ISSUE TITLE
Binance cancel_order does not work

### ISSUE THREAD

**Issue by jkim-96** [ccxt/ccxt#10245]
- OS: windows
- Programming Language version: python 3.8.8
- CCXT version: ccxt 1.58.25

```
symbol="BTC/USDT"
def cancleopen(symbol):
    open_order=binance.fetch_open_orders(symbol)
    if len(open_order) ==0:
        pass
    else:
        open_order_id=open_order[0]['info']['orderId']
        binance.cancel_order(open_order_id, symbol)
        print("cancle open order", symbol)

cancelopen(symbol)
```

in most case, this 'cancelopen' code does work and it normally cancel open order. however sometimes, this 'cancleopen' code does not work and makes unnecessary trade. I'm a high frequency trader, so I often use cancleopen code very quickly. Is there any possibility that retrieving an open order is not possible within a fast operation? If I change the code, can I cancel all open orders without missing out? I bought the ccxtpro version and haven't used it yet, but if I make a code with the ccxtpro version, is it a problem that can be solved?

```

**Comment by kroitor** [comment]
> however sometimes, this 'cancleopen' code does not work and makes unnecessary trade.

Can you elaborate on that please? What is the verbose output of the failing call? Please, enable the verbose mode switch on the exchange instance and copy-paste your request+response body of the cancel_order call.

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

You're missing the error handling in your code, you have to wrap it with try/except clauses:
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

**Comment by jkim-96** [comment]
답변
As I was just manipulating the code, I realized the most essential problem with my code. It was because I wrote the code wrong. It seems that it was not the problem of cancel open order, but that the position search was not repeated in the infinite loop code made with while. The situation in which the short position off is to enter the long position as much as the margin entered in the short position. It was because position inquiry was not repeated, it did short position off twice and it enters long position. There seems to be no problem with cancel open order. If there are any other problems, I will post again. I'll put the error result in case you need it. Thank you for your kind reply!

Below is result of this trade. 
```
Response: POST https://fapi.binance.com/fapi/v1/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sun, 17 Oct 2021 01:06:56 GMT', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '1163', 'X-MBX-ORDER-COUNT-10S': '1', 'X-MBX-ORDER-COUNT-1M': '2', 'x-response-time': '6ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 b4d3f424b1e6960b9f71e8cf3b9e1a57.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN51-C1', 'X-Amz-Cf-Id': 'Gv9-nRutx1LKy1LB4p_lX0XSwYUCxA9KkLBz7qFIKSNbOuJzMkZ4QA=='} {"orderId":13970573605,"symbol":"MATICUSDT","status":"FILLED","clientOrderId":"x-xcKtGhcud1591394d8117342911c3e","price":"0","avgPrice":"1.49490","origQty":"811","executedQty":"811","cumQty":"811","cumQuote":"1212.36390","timeInForce":"GTC","type":"MARKET","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"MARKET","updateTime":1634432816783}
“”short position market off MATIC/USDT 
I got much margin in MATIC/USDT””

Request: GET https://fapi.binance.com/fapi/v1/openOrders?timestamp=1634432816964&recvWindow=5000&symbol=MATICUSDT&signature=6f92e1d4f0d8c9e2172965ae4b017cabef447062256baadf181885f6c012684b {'X-MBX-APIKEY': 'PbLUqWuHPiH9d5CWCF1UIJc1j7Dht9ExDwhOxcleRpNc1IbXHTtQzOmLbC2Pd13L', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://fapi.binance.com/fapi/v1/openOrders?timestamp=1634432816964&recvWindow=5000&symbol=MATICUSDT&signature=6f92e1d4f0d8c9e2172965ae4b017cabef447062256baadf181885f6c012684b 200 {'Content-Type': 'application/json', 'Content-Length': '2', 'Connection': 'keep-alive', 'Date': 'Sun, 17 Oct 2021 01:06:57 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '1164', 'x-response-time': '0ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 b4d3f424b1e6960b9f71e8cf3b9e1a57.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN51-C1', 'X-Amz-Cf-Id': 'JJRkmpq9H01zsc62QH3j9WdOZV7fDaJw-UGaR6Ngt99j_EiUgb3j3Q=='} []

Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'PbLUqWuHPiH9d5CWCF1UIJc1j7Dht9ExDwhOxcleRpNc1IbXHTtQzOmLbC2Pd13L', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1634432817171&recvWindow=5000&symbol=MATICUSDT&type=MARKET&side=BUY&newClientOrderId=x-xcKtGhcu506ba24b0bc2b85dd987a1&newOrderRespType=RESULT&quantity=811&signature=6b1d9b873d9acd5674ea01b106765f548e77c3ab4a790bccc7463696486c68fc

Response: POST https://fapi.binance.com/fapi/v1/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sun, 17 Oct 2021 01:06:57 GMT', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '1164', 'X-MBX-ORDER-COUNT-10S': '2', 'X-MBX-ORDER-COUNT-1M': '3', 'x-response-time': '5ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 b4d3f424b1e6960b9f71e8cf3b9e1a57.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN51-C1', 'X-Amz-Cf-Id': 'qgLyQvl9eJYFuZtNCx3gyViKY4EZubkXawrjPohPhkz-bW3nbsj8vg=='} {"orderId":13970573661,"symbol":"MATICUSDT","status":"FILLED","clientOrderId":"x-xcKtGhcu506ba24b0bc2b85dd987a1","price":"0","avgPrice":"1.49490","origQty":"811","executedQty":"811","cumQty":"811","cumQuote":"1212.36390","timeInForce":"GTC","type":"MARKET","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"MARKET","updateTime":1634432817603}
“”short position market off MATIC/USDT 
I got much margin in MATIC/USDT””

Request: GET https://fapi.binance.com/fapi/v1/openOrders?timestamp=1634432817785&recvWindow=5000&symbol=MATICUSDT&signature=ebcf07de4c2f30fa89f7216e95c1f99d78b6508f4c0494738c02d12a6e70c7ce {'X-MBX-APIKEY': 'PbLUqWuHPiH9d5CWCF1UIJc1j7Dht9ExDwhOxcleRpNc1IbXHTtQzOmLbC2Pd13L', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://fapi.binance.com/fapi/v1/openOrders?timestamp=1634432817785&recvWindow=5000&symbol=MATICUSDT&signature=ebcf07de4c2f30fa89f7216e95c1f99d78b6508f4c0494738c02d12a6e70c7ce 200 {'Content-Type': 'application/json', 'Content-Length': '2', 'Connection': 'keep-alive', 'Date': 'Sun, 17 Oct 2021 01:06:58 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '1165', 'x-response-time': '2ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 b4d3f424b1e6960b9f71e8cf3b9e1a57.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN51-C1', 'X-Amz-Cf-Id': 'jxvH8Ws1eY120q1Kv2H1ViCSoInzTYbQnTrovOFbyL6Y-vNwwGMImw=='} []

Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'PbLUqWuHPiH9d5CWCF1UIJc1j7Dht9ExDwhOxcleRpNc1IbXHTtQzOmLbC2Pd13L', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1634432817992&recvWindow=5000&symbol=MATICUSDT&type=MARKET&side=BUY&newClientOrderId=x-xcKtGhcuedc71827789fa66dd5562a&newOrderRespType=RESULT&quantity=811&signature=be94e60eb82d97be9d6a9e86ecec4b6cf34dfe17287d9aad126110244078b61c
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 613, in fetch
    response.raise_for_status()
  File "C:\Anaconda3\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:/Users/biancetrading.py", line 219, 
    binance.create_market_buy_order(symbol, -positionAmt)
  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 2071, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "C:\Anaconda3\lib\site-packages\ccxt\binance.py", line 2408, in create_order
    response = getattr(self, method)(self.extend(request, params))

Response: POST https://fapi.binance.com/fapi/v1/order 400 {'Content-Type': 'application/json', 'Content-Length': '46', 'Connection': 'keep-alive', 'Date': 'Sun, 17 Oct 2021 01:06:58 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '1165', 'X-MBX-ORDER-COUNT-10S': '3', 'X-MBX-ORDER-COUNT-1M': '4', 'x-response-time': '4ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 b4d3f424b1e6960b9f71e8cf3b9e1a57.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN51-C1', 'X-Amz-Cf-Id': 'wzaxqTIa3-pYAeTVznVG0zwJS2oLEI5gQyCyy9ROB9wf0he7OGndCA=='} {"code":-2019,"msg":"Margin is insufficient."}
  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Anaconda3\lib\site-packages\ccxt\binance.py", line 4401, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 629, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Anaconda3\lib\site-packages\ccxt\binance.py", line 4381, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 520, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance {"code":-2019,"msg":"Margin is insufficient."}
```
