### ISSUE TITLE
ByBit fetch_orders inverse symbol causing "Param validation for 'symbol' failed on the 'linear_symbol'" error

### ISSUE THREAD

**Issue by viper7882** [ccxt/ccxt#10249]
- OS: Windows 11
- Programming Language version: Python 3.9
- CCXT version: 1.58.49
- Exchange: ByBit

```
import ccxt
import time

exchange = ccxt.bybit({
    'apiKey': api_key,
    'secret': api_secret,
    'nonce': lambda: str(int(time.time() * 1000)),
    'enableRateLimit': True,
})
exchange.set_sandbox_mode(True)

markets = exchange.load_markets()

symbol = 'ETHUSD'
print(exchange.fetch_orders(symbol=symbol))
```

```
D:\Issue\ccxt\venv\Scripts\python.exe D:/Wecoz/Issue/ccxt/inverse_symbols_as_linear.py
Traceback (most recent call last):
  File "D:\Issue\ccxt\inverse_symbols_as_linear.py", line 23, in <module>
    print(exchange.fetch_orders(symbol=symbol))
  File "D:\Issue\ccxt\venv\lib\site-packages\ccxt\bybit.py", line 1783, in fetch_orders
    response = getattr(self, method)(self.extend(request, query))
  File "D:\Issue\ccxt\venv\lib\site-packages\ccxt\base\exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "D:\Issue\ccxt\venv\lib\site-packages\ccxt\base\exchange.py", line 506, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "D:\Issue\ccxt\venv\lib\site-packages\ccxt\base\exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\Issue\ccxt\venv\lib\site-packages\ccxt\base\exchange.py", line 654, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "D:\Issue\ccxt\venv\lib\site-packages\ccxt\bybit.py", line 2439, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "D:\Issue\ccxt\venv\lib\site-packages\ccxt\base\exchange.py", line 520, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: bybit {"ret_code":10001,"ret_msg":"Param validation for 'symbol' failed on the 'linear_symbol' tag","ext_code":"","ext_info":"","result":null,"time_now":"1634555341.494770","rate_limit_status":599,"rate_limit_reset_ms":1634555341493,"rate_limit":600}
```
The issue is that despite ETHUSD is Inverse symbol, the error message suggested that it failed validation for "linear_symbol".

I've traced the code @ https://github.com/ccxt/ccxt/blob/master/python/ccxt/bybit.py and highly suspect the problematic area is as following:
```
    def fetch_orders(self, symbol=None, since=None, limit=None, params={}):
        .
        .
        .
        defaultType = self.safe_string(self.options, 'defaultType', 'linear')
        marketTypes = self.safe_value(self.options, 'marketTypes', {})
        marketType = self.safe_string(marketTypes, symbol, defaultType)
        defaultMethod = None
        marketDefined = (market is not None)
        **linear = (marketDefined and market['linear']) or (marketType == 'linear')**
        inverse = (marketDefined and market['swap'] and market['inverse']) or (marketType == 'inverse')
        futures = (marketDefined and market['futures']) or (marketType == 'futures')
        if linear:
            defaultMethod = 'privateLinearGetOrderList'
        elif inverse:
            defaultMethod = 'v2PrivateGetOrderList'
        elif futures:
            defaultMethod = 'futuresPrivateGetOrderList'
```
where both **linear** and **inverse** are set as True whereas futures are set as False. The expectation is **linear** variable should be set to False.

Due to the ETHUSD is treated as linear, hence defaultMethod is assigned with 'privateLinearGetOrderList' instead of 'v2PrivateGetOrderList'.

The workaround is to swap the order of inverse and linear below but I'm not certain if it would break anything.
```
        if inverse:
            defaultMethod = 'v2PrivateGetOrderList'
        elif linear:
            defaultMethod = 'privateLinearGetOrderList'
        elif futures:
            defaultMethod = 'futuresPrivateGetOrderList'
```

**Comment by ttodua** [comment]
@viper7882 
I think the issue is that you are calling the symbol whatever does that particular exchange uses in its interface. 
You should familiarize, that ccxt doesn't use exchange-specific namings, instead the unified approach:

BaseCurrency/QuoteCurrency  (notice slash).

However, recently, there has been other change too, which address the total unification of future/contract/derivatives pari-namings, and you should switch to using them.  Please read this: https://github.com/ccxt/ccxt/issues/10931

If you have other issues, feel free to reopen the issue.
(@kroitor I think your above comment doesn't need further action/investigation from your side, or am I wrong?)
