### ISSUE TITLE
TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by mathchq** [ccxt/ccxt#10277]
```
import ccxt
from line_profiler import LineProfiler

binance = ccxt.binance()
exchangeInfo = binance.fapiPublic_get_exchangeinfo()
```

Exception ignored in: <function Exchange.__del__ at 0x7f96f9af93a0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 399, in __del__
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 747, in close
  File "/opt/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 327, in close
  File "/opt/anaconda3/lib/python3.8/site-packages/urllib3/poolmanager.py", line 222, in clear
  File "/opt/anaconda3/lib/python3.8/site-packages/urllib3/_collections.py", line 100, in clear
  File "/opt/anaconda3/lib/python3.8/site-packages/urllib3/poolmanager.py", line 173, in <lambda>
  File "/opt/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 494, in close
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by mathchq** [comment]
python 3.8.8
ccxt 1.58.74

**Comment by ttodua** [comment]
I've tested this and didn't get the issue.
If you have been try/catch-ing your code (which you havent posted), then the issue might happen and to fix that, take a look into this: This https://stackoverflow.com/a/53512213/2377343
Please update the CCXT to latest version (two months has passed since) and as #kroitor mentioned, include verbose logs and re-open the issue, and we can answer better.
