### ISSUE TITLE
kraken requires `apiKey`even with correct API keys

### ISSUE THREAD

**Issue by dbzalpha** [ccxt/ccxt#1037]
Hi guys, 
On Kraken, I manage to query my balance, but not to PUT order using create_limit_buy_order.
It seems I have an apiKey problem. 
I checked that my credentials allow to put order, and I did override the nonce, in milliseconds.
Some ideas?
I'm very newbie, but with your lib, I'm learning/practicing Python and it's great!
Thanks

- OS: MacOS
- Programming Language: Python3
- CCXT version: 1.10.545
- Exchange: kraken
- Method: create_limit_buy_order

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

MUST_READ_THIS https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

REPLACE_WITH_YOUR_CODE_TO_REPRODUCE_THE_BUG_HERE
kraken = ccxt.kraken ({
'apiKey': 'YOUR_API_KEY',
'secret': 'YOUR_SECRET_KEY',
'nonce': lambda: int(time.time() * 1000),
'verbose' : True
}) 
exchange = getattr(ccxt, exchange_name)({'verbose': False})
result = await exchange.create_limit_buy_order('BTC/EUR', 0.01, 1000)

==========================
Traceback (most recent call last):
  File "test_orders2.py", line 181, in a_put_order
    result = await exchange.create_limit_buy_order(symbol,amount, price)
  File "/usr/local/lib/python3.6/site-packages/ccxt/async/kraken.py", line 526, in create_order
    response = await self.privatePostAddOrder(self.extend(order, params))
  File "/usr/local/lib/python3.6/site-packages/ccxt/async/kraken.py", line 745, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/async/base/exchange.py", line 85, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/async/kraken.py", line 724, in sign
    self.check_required_credentials()
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 744, in check_required_credentials
    raise AuthenticationError(self.id + ' requires `' + key + '`')
ccxt.base.errors.AuthenticationError: kraken requires `apiKey`

↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

**Comment by kroitor** [comment]
**First of, NEVER EVER show your secret key in public if you don't want to lose it. This is a friendly advice.**

You're not using the correct Python language constructs for instantiating it properly...

```Python
import ccxt
exchange = ccxt.kraken ({  # ←---------- you create the `exchange` here
    'apiKey': 'YOUR_API_KEY',  # ←------------------- replace with your apiKey
    'secret': 'YOUR_SECRET_KEY',  # ←------------------- replace with your secret
    'verbose' : True
})
# you use the ↓ `exchange` here
result = exchange.create_limit_buy_order('BTC/EUR', 0.01, 1000)
print(result)
```

Read the Manual and look at the examples for more info:
- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/tree/master/examples

Hope it helps. I'm closing this for now, if you don't mind.
