### ISSUE TITLE
fetch_open_orders problem on Ascendex

### ISSUE THREAD

**Issue by svax974** [ccxt/ccxt#10371]
Hello,

I have a problem with Ascendex and fetch_open_orders which cause "TypeError: '>=' not supported between instances of 'NoneType' and 'int'" error in ccxt/base/exchange.py line 1943 (full output below) and I'm lost with that one.

The exact same code does work with Binance and Gate.io.
I tried different values for the "since" parameter (0, 86400000 , 1000000000, ...) but it gives the same result.
Note that the problem is specific to fetch_open_order, it does not occur with fetch_closed_order if I just replace the fetch_open_order call with the "closed" one.

I'm calling the function just like this, after checking support for fetchOpenOrders of course :
EX.getOrders( symbol="CRWNY/USDT", otype='open', tsfrom=1000000000)
where EX is an instance of a class containing a "self.exchange" ccxt instance.
The error occurs on the first call of fetch_open_orders.
The code for my function is just below and is heavily inspired from the code found in the doc about paginating order fetching. The only modification I did is to add 1 to the last order timestamp because I think I had some issue where it would loop on the last order fetched if I remember well.

Any help will be appreciated, regards.

- OS: Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
- Programming Language version: Python 3.9.7
- CCXT version: 1.59.4

```
    def getOrders( self, symbol="BTC/USDT", otype='all', tsfrom=None):
        orders = []
        if otype=='all':
            if not self.exchange.has['fetchOrders']:
                print( "WARNING : exchange '"+self.name+"' has not fetchOrders capability !!!!!!!!!!!!!!!")
                sys.exit()
        elif otype=='open':
            if not self.exchange.has['fetchOpenOrders']:
                print( "WARNING : exchange '"+self.name+"' has not fetchOpenOrders capability !!!!!!!!!!!!!!!")
                sys.exit()
        elif otype=='closed':
            if not self.exchange.has['fetchClosedOrders']:
                print( "WARNING : exchange '"+self.name+"' has not fetchClosedOrders capability !!!!!!!!!!!!!!!")
                sys.exit()
        else:
            print( "ERROR : unhandled order type = '"+type+"'")
            sys.exit()
        while tsfrom < self.exchange.milliseconds (): 
            limit = 20  # change for your limit
            print( "Get '"+otype+"' Orders : "+symbol+" tsfrom="+str(tsfrom)+" limit="+str(limit)+" / ",end='')
            tmporders = []
            if otype=='all':
                tmporders = self.exchange.fetch_orders(symbol, tsfrom, limit)
            elif otype=='open':
                tmporders = self.exchange.fetch_open_orders(symbol, tsfrom, limit)
            elif otype=='closed':
                tmporders = self.exchange.fetch_closed_orders(symbol, tsfrom, limit)
            if len(tmporders):
                tsfrom = tmporders[len(tmporders) - 1]['timestamp']+1
                orders += tmporders
            else:
                break
        print( " nb="+str(len(orders)))
        return orders
```
Here is the full output with verbose = True
```
Exchange 'BitMax/Ascendex'
	Trade CRWNY/USDT
Get 'open' Orders : CRWNY/USDT tsfrom=1000000000 limit=20 / 
Request: GET https://ascendex.com/api/pro/v1/info {'x-auth-key': 'XGtX3tEvXGFABgZjJtFjjGta7qBOKJ35', 'x-auth-timestamp': '1635435717918', 'x-auth-signature': 'nQCO4EJgkZmm3t3FNKjUcmZrUXdGifZWY5+C1TefX0I=', 'User-Agent': 'python-requests/2.25.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://ascendex.com/api/pro/v1/info 200 {'Date': 'Thu, 28 Oct 2021 15:41:58 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'instance': '_-_-2', 'referrer-policy': 'strict-origin-when-cross-origin', 'content-security-policy': "frame-ancestors 'self';", 'Permissions-Policy': 'accelerometer=(),geolocation=(),gyroscope=(),interest-cohort=(),magnetometer=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),usb=()', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '6a5545752c5a4f9f-JNB', 'Content-Encoding': 'gzip'} {"code":0,"data":{"email":"svax@free.fr","accountGroup":1,"viewPermission":true,"tradePermission":true,"transferPermission":false,"cashAccount":["cshrnrduz1s81QN6ZjbqYo83Jsidhqi4"],"marginAccount":["marciS2nrTGf8cvDCWi75fT7kwFP5uUp"],"futuresAccount":["futT8Nt5b7iKfKKBpP3Xh2ZsdEfyHrPR"],"userUID":"U7503352963","expireTime":1656514467051,"allowedIps":[],"limitQuota":1000}}

Request: GET https://ascendex.com/1/api/pro/v1/cash/order/open {'x-auth-key': ', 'x-auth-timestamp': '1635435718418', 'x-auth-signature': '', 'User-Agent': 'python-requests/2.25.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://ascendex.com/1/api/pro/v1/cash/order/open 200 {'Date': 'Thu, 28 Oct 2021 15:41:59 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'instance': '1-_-2', 'referrer-policy': 'strict-origin-when-cross-origin', 'content-security-policy': "frame-ancestors 'self';", 'Permissions-Policy': 'accelerometer=(),geolocation=(),gyroscope=(),interest-cohort=(),magnetometer=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),usb=()', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '6a55457849354f9f-JNB'} {"code":0,"accountId":"cshrnrduz1s81QN6ZjbqYo83Jsidhqi4","ac":"CASH","data":[ {"seqNum":23399855482,"orderId":"a17cc6ef390fU7503352963sbtmx7PEP","symbol":"ASD/USDT","orderType":"Limit","lastExecTime":1635425139160,"price":"2.12","orderQty":"70","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23399691192,"orderId":"a17cc6d9a75aU7503352963sylduwSnY","symbol":"YLD/USDT","orderType":"Limit","lastExecTime":1635423725606,"price":"1.04","orderQty":"96","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23399689603,"orderId":"a17cc6d97f8eU7503352963suosuzlJg","symbol":"UOS/USDT","orderType":"Limit","lastExecTime":1635423715401,"price":"1","orderQty":"16","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23399688210,"orderId":"a17cc6d948b2U7503352963stvkuqrmY","symbol":"TVK/USDT","orderType":"Limit","lastExecTime":1635423701435,"price":"0.7236","orderQty":"119","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23399685501,"orderId":"a17cc6d8ea37U7503352963somiu9f66","symbol":"OMI/USDT","orderType":"Limit","lastExecTime":1635423677151,"price":"0.0096","orderQty":"1976","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23399681716,"orderId":"a17cc6d856a9U7503352963smixuMrDw","symbol":"MIX/USDT","orderType":"Limit","lastExecTime":1635423639400,"price":"0.0116","orderQty":"8620","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23399680297,"orderId":"a17cc6d818b1U7503352963skinuIKkO","symbol":"KIN/USDT","orderType":"Limit","lastExecTime":1635423623546,"price":"0.00034","orderQty":"294117","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23399679179,"orderId":"a17cc6d7ea8bU7503352963sjuldksjr","symbol":"JULD/USDT","orderType":"Limit","lastExecTime":1635423611743,"price":"0.096","orderQty":"1041","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23399678039,"orderId":"a17cc6d7b818U7503352963scrwnOs7L","symbol":"CRWNY/USDT","orderType":"Limit","lastExecTime":1635423598782,"price":"0.244","orderQty":"148","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23399675796,"orderId":"a17cc6d77294U7503352963sbepr6g9V","symbol":"BEPRO/USDT","orderType":"Limit","lastExecTime":1635423581030,"price":"0.029","orderQty":"2674","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23399569919,"orderId":"a17cc6c87ad1U7503352963saktuxAIJ","symbol":"AKT/USDT","orderType":"Limit","lastExecTime":1635422600078,"price":"11","orderQty":"2","side":"Sell","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23240636603,"orderId":"r17c74b66de3U7503352963bltou9wsi","symbol":"LTO/USDT","orderType":"Limit","lastExecTime":1634045686208,"price":"0.2","orderQty":"100","side":"Buy","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"},{"seqNum":23240612301,"orderId":"r17c74b48112U7503352963bzeeuDIPO","symbol":"ZEE/USDT","orderType":"Limit","lastExecTime":1634045560040,"price":"0.35","orderQty":"285","side":"Buy","status":"New","avgPx":"0","cumFilledQty":"0","stopPrice":"","errorCode":"","cumFee":"0","feeAsset":"USDT","execInst":"NULL_VAL"}]}
Traceback (most recent call last):
  File "/home/pywww/ccCenter/./batch_tptrades.py", line 56, in <module>
    syncTPOrders()
  File "/home/pywww/ccCenter/./batch_tptrades.py", line 37, in syncTPOrders
    exorders = ex.getOrders( mksymbol, 'open', 1000000000)
  File "/home/pywww/ccCenter/sources/CcxtExchange.py", line 264, in getOrders
    tmporders = self.exchange.fetch_open_orders(symbol, tsfrom, limit)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/ascendex.py", line 1188, in fetch_open_orders
    return self.filter_by_symbol_since_limit(orders, symbol, since, limit)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 1949, in filter_by_symbol_since_limit
    return self.filter_by_value_since_limit(array, 'symbol', symbol, since, limit, 'timestamp', tail)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 1943, in filter_by_value_since_limit
    array = [entry for entry in array if entry[key] >= since]
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 1943, in <listcomp>
    array = [entry for entry in array if entry[key] >= since]
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**Comment by ttodua** [comment]
I don't think it should use `lastTradeTimestamp` in any way (either for sorting or for setting that as `timestamp`) as that will definitely cause unexpected scenarios and inconsistencies.  As I've mentioned idea in #10689 somehow it might be applied here too, adding 'emulatedTimestamp` property where 'timestamp' values are not available, so users will have more consistent logic (i.e. in userland codes `myTS = obj['timestamp'] ? obj['timestamp'] : obj['emulatedTimestamp']` ) and they will be aware of what they are doing (when they want to use even less-precise 'emulated' timestamp , which is better than nothing).

@surfdargent about your issue, in this code, at first you should check if 'timestamp' property has value
```
if len(tmporders):
    tsfrom = tmporders[len(tmporders) - 1]['timestamp']+1
```
Otherwise you will surely get error as @frosty00 said.

@kroitor any thought about the status of this matter, or should we close this issue for now?

**Comment by Tdmain** [comment]
I’m not okay with using my stuff
aaray { owner=ross Nicholas oneil thomas
Domain owner GitHub.com OWNER=ross Nicholas oneil thomas

**Comment by ttodua** [comment]
this issue should have been fixed in the past. 
if anyone still has any problems, let us know
