### ISSUE TITLE
Asyncio issue after 1.10.538 

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#1040]
When I upgraded ccxt from 1.10.538 to 1.10.545 I have issue with aiohttp.

I have 2 threads with different asyncio event_loops 

- OS: macOS 10.11.6
- Programming Language: python 3.6 
- CCXT version: 1.10.545
- Exchange: 
- Method: fetch_balance

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

Traceback (most recent call last):
  File "/Users/kas/Documents/Bitcoin/proj/DataRecieverThread.py", line 54, in processConnector
    await request.processRequest(connector)
  File "/Users/kas/Documents/Bitcoin/proj/IExchangeConnector.py", line 83, in processRequest
    self.setresult(await connector.p_accountsbalances())
  File "/Users/kas/Documents/Bitcoin/proj/IExchangeConnector.py", line 114, in p_accountsbalances
    return await self.__ccxtexchange.fetch_balance()
  File "/Users/kas/Documents/Bitcoin/proj/ccxt/async/cex.py", line 118, in fetch_balance
    await self.load_markets()
  File "/Users/kas/Documents/Bitcoin/proj/ccxt/async/base/exchange.py", line 128, in load_markets
    markets = await self.fetch_markets()
  File "/Users/kas/Documents/Bitcoin/proj/ccxt/async/cex.py", line 83, in fetch_markets
    markets = await self.publicGetCurrencyLimits()
  File "/Users/kas/Documents/Bitcoin/proj/ccxt/async/cex.py", line 390, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "/Users/kas/Documents/Bitcoin/proj/ccxt/async/base/exchange.py", line 86, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/kas/Documents/Bitcoin/proj/ccxt/async/base/exchange.py", line 106, in fetch
    async with session_method(url, data=encoded_body, headers=headers, timeout=(self.timeout / 1000), proxy=self.aiohttp_proxy) as response:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 402, in connect
    proto = yield from self._create_connection(req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 749, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 813, in _create_direct_connection
    hosts = yield from self._resolve_host(req.url.raw_host, req.port)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 727, in _resolve_host
    loop=self._loop)
RuntimeError: Task <Task pending coro=<DataReceiverThread.processConnector() running at /Users/kas/Documents/Bitcoin/proj/DataRecieverThread.py:54> cb=[_chain_future.<locals>._call_set_state() at /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/futures.py:415]> got Future <Future pending> attached to a different loop


↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

**Comment by alexsith** [comment]
I guess you should pass loop to  aiohttp.TCPConnector(ssl_context=context)

    connector  = CccxtConnector(exchid,  self._results, self._dataReceiver._loop, config, redefined)
  File "/Users/kas/Documents/Bitcoin/proj/IExchangeConnector.py", line 105, in __init__
    self.__ccxtexchange = getattr(ccxt, id_exchange)(extraconfig)    #{'asyncio_loop':loop}
  File "/Users/kas/Documents/Bitcoin/proj/ccxt/async/base/exchange.py", line 53, in __init__
    self.session = aiohttp.ClientSession(loop=self.asyncio_loop, connector=connector)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 75, in __init__
    "Session and connector has to use same event loop")
RuntimeError: Session and connector has to use same event loop

**Comment by alexsith** [comment]
Thank you so much!

**Comment by kroitor** [comment]
@alexsith thanks for reporting!
