### ISSUE TITLE
Binance US - Signature for this request is not valid

### ISSUE THREAD

**Issue by vilorel** [ccxt/ccxt#10426]
- OS: Ubuntu 20.04.3 LTS
- Programming Language version: NodeJS v16.13.0
- CCXT version: 1.59.87

```
const ccxtpro = require('ccxt.pro');
const client = new ccxtpro.binanceus({
            apiKey: XXX,
            secret: YYY,
            enableRateLimit: true,
            hostname: 'binance.us',
            newUpdates: true,
            verbose: true,
        });
const res = await client.privateGetAccount();

```

```
CCXT Pro Version: 0.9.13
CCXT Version: 1.59.87
fetch:
 binanceus GET https://api.binance.us/api/v3/account?timestamp=1635812525890&recvWindow=5000&signature=ZZZ 
Request:
 {
  'X-MBX-APIKEY': 'XXX'
} 
 undefined 

handleRestResponse:
 binanceus GET https://api.binance.us/api/v3/account?timestamp=1635812525890&recvWindow=5000&signature=ZZZ 400 Bad Request 
Response:
 {
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Length': '63',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Tue, 02 Nov 2021 00:22:06 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  Via: '1.1 8455bcb2c0203b0c4ee93b610d75e69b.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'm_7dO_OkD-3Z4EKRMecCNbQTlQukxpmeGyCd-By48IFCodZgsS9E1w==',
  'X-Amz-Cf-Pop': 'ZRH50-C1',
  'X-Cache': 'Error from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Mbx-Used-Weight': '10',
  'X-Mbx-Used-Weight-1m': '10',
  'X-Mbx-Uuid': '0673b263-6601-4d6f-bdf5-8a9fe55a7c5f',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
} 
 {"code":-1022,"msg":"Signature for this request is not valid."} 

AuthenticationError: binanceus {"code":-1022,"msg":"Signature for this request is not valid."}
    at binanceus.throwExactlyMatchedException (/node_modules/ccxt/js/base/Exchange.js:595:19)
    at binanceus.handleErrors (/node_modules/ccxt/js/binance.js:4731:18)
    at /node_modules/ccxt/js/base/Exchange.js:657:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async binanceus.request (/node_modules/ccxt/js/binance.js:4758:26)
  constructor: [class AuthenticationError extends ExchangeError]
}

```

I don't know if it makes any difference, but the code I used successfully to compute the signature is the following:
```
console.log(crypto.createHmac('sha256', my_secret_key).update(my_req_body).digest('hex').toString());
```

Worth pointing out is also that I use ccxt.pro as a proxy to instanciate the ccxt BinanceUS client. The code was working just fine until a few days ago (last tested). After poking around, I discovered that the signatured produced by the ccxt client is not matching what I'm producing (and works) for the same request body/string so maybe it's a good place to start? Unless I'm missing something :) 

No private request that required signing worked for me (I tried spot trading, account balance, and fetching the deposit wallet addresses). All are producing the same error.

**Comment by kroitor** [comment]
@vilorel what is your output for this:

```JavaScript
// ...
const string = 'timestamp=1635812525890&recvWindow=5000'
const ccxt = client.hmac(string, my_secret_key, 'sha256')
const alt = crypto.createHmac('sha256',my_secret_key).update(my_req_body).digest('hex').toString()
console.log ({ ccxt, alt }) 
// ...
```

**Comment by vilorel** [comment]
@kroitor They're a match.

**Comment by vilorel** [comment]
OK just checked again because this didn't make sense and traced the problem (it's on my end). Very very sorry to bug you with this.

**Comment by kroitor** [comment]
@vilorel thanks for your feedback, good to know you figured it out.
