### ISSUE TITLE
exception in watch_orders, problem with scheduling watch_orders task

### ISSUE THREAD

**Issue by emacasa** [ccxt/ccxt#10511]
Hi, I have two questions:
1) when I run the code below, the exception below arises
2) when calling asyncio.gather, if I put   _listen_orders_updates(exchange, [c]) at the beginning of the list, everything works (and the exception of point 1) comes up), if I put it at the end, this function is never called and the orders are never watched. It does not make sense to me, am I doing anything wrong with asyncio or there is a problem with watch_orders? 

Thanks

```
import asyncio
from typing import List

import ccxtpro


class Consumer:
    def __init__(self):
        pass

    async def order_update(self, order):
        print(order)

    async def orderbook_update(self, orderbook):
        print(orderbook)


async def _listen_orderbook(exchange: ccxtpro.Exchange, symbol: str, queue: asyncio.Queue):
    while True:
        orderbook = await exchange.watch_order_book(symbol)
        await queue.put(orderbook['bids'][0])


async def _listen_orders_updates(exchange: ccxtpro.Exchange, orders_consumers: List[Consumer]):
    while True:
        orders = await exchange.watch_orders()
        for order in orders:
            for order_consumer in orders_consumers:
                await order_consumer.order_update(order)


async def _read_queue(queue: asyncio.Queue, consumer: Consumer):
    while True:
        orderbook = await queue.get()
        await consumer.orderbook_update(orderbook)
        await asyncio.sleep(2)


async def main():
    exchange = ccxtpro.poloniex({
        'apiKey': 'MY API KEY',
        'secret': 'MY SECRET',
    })
    q = asyncio.Queue()
    c = Consumer()
    tasks = [
        _listen_orders_updates(exchange, [c]),
        _listen_orderbook(exchange, 'BTC/USDT', q),
        _read_queue(q, c),
    ]
    await asyncio.gather(*tasks)


asyncio.run(main())

```

```
Exception in callback FastClient.receive_loop.<locals>.handler() at /Users/ema/Documents/AvcCryptoTrading/venv/lib/python3.8/site-packages/ccxtpro/base/fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at /Users/ema/Documents/AvcCryptoTrading/venv/lib/python3.8/site-packages/ccxtpro/base/fast_client.py:20>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ema/Documents/AvcCryptoTrading/venv/lib/python3.8/site-packages/ccxtpro/base/fast_client.py", line 25, in handler
    self.handle_message(message)
  File "/Users/ema/Documents/AvcCryptoTrading/venv/lib/python3.8/site-packages/ccxtpro/base/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/Users/ema/Documents/AvcCryptoTrading/venv/lib/python3.8/site-packages/ccxtpro/base/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/Users/ema/Documents/AvcCryptoTrading/venv/lib/python3.8/site-packages/ccxtpro/poloniex.py", line 776, in handle_message
    method(client, message)
  File "/Users/ema/Documents/AvcCryptoTrading/venv/lib/python3.8/site-packages/ccxtpro/poloniex.py", line 437, in handle_account_notifications
    callback(client, entry)
  File "/Users/ema/Documents/AvcCryptoTrading/venv/lib/python3.8/site-packages/ccxtpro/poloniex.py", line 689, in handle_order
    symbolSpecificMessageHash = messageHash + ':' + symbol
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by kroitor** [comment]
@emacasa hi! What is your version of CCXT Pro? Do you have this issue with the most recent version of CCXT and CCXT Pro?

**Comment by emacasa** [comment]
Hi, thanks for the quick reply. I am using ccxt~=1.57.69 and ccxtpro~=0.8.89. Is there an automated way to check/update ccxt and ccxtpro?

Thanks

**Comment by kroitor** [comment]
@emacasa nope, but you can make a bash-script for that with `git tag`. Let us know if you have the same issue with the most recent version of the lib.

**Comment by emacasa** [comment]
Hi, I tried using ccxt version:  1.60.78 and ccxtpro version:  0.9.18 but the issue is still the same. Any solution?

**Comment by kroitor** [comment]
@emacasa i'll try to reproduce using your code, will debug it and will post my results here asap.

**Comment by emacasa** [comment]
Hi @kroitor, any news on this? Thanks, Emanuele

**Comment by emacasa** [comment]
Hello?

**Comment by kroitor** [comment]
@emacasa pardon for the delay on my side, will get to it soon and will post my findings here within 24-48h.

**Comment by kroitor** [comment]
Hello @emacasa 👋

Closing this with actual test results rather than just age — and owning that "within 24–48h" in Nov 2021 missed by a few years. Sorry.

I've re-tested both of your points against current ccxt (4.5.70). (1) The original `TypeError` in poloniex's `handle_order` is gone — that handler was fully rewritten for Poloniex's new websocket API and handles symbol-less messages gracefully. (2) The `asyncio.gather` ordering behavior doesn't reproduce: with your exact three-task structure, all watchers get scheduled regardless of position in the gather list. What you observed in 2021 was a consequence of (1) — the exception killed the shared websocket callback, which silenced whichever watchers shared that connection, and looked like gather-order weirdness.

Testing this did surface a present-day cousin of your bug — a crash on fill events for orders missing from the local cache — which is now fixed in #29389. So your report ended up being useful twice, four years apart. Thanks for the patience, and a fresh issue will get a much faster response if anything else comes up. 🙏
