### ISSUE TITLE
Binance create_market_sell_order: Illegal characters found in parameter 'quantity'

### ISSUE THREAD

**Issue by allenfrostline** [ccxt/ccxt#1054]
Here is a simple example of this problem. `a` is created as a Binance exchange object and the markets are already fetched. However,

```{bash}
>>> a.create_market_sell_order('BTC/USDT', 0.000096)
Traceback (most recent call last):
  File "/Users/Allen_Frostline/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 346, in fetch
    response.raise_for_status()
  File "/Users/Allen_Frostline/anaconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Allen_Frostline/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1010, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)
  File "/Users/Allen_Frostline/anaconda3/lib/python3.6/site-packages/ccxt/binance.py", line 545, in create_order
    response = self.privatePostOrder(self.extend(order, params))
  File "/Users/Allen_Frostline/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 296, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Users/Allen_Frostline/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 293, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/Allen_Frostline/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 358, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "/Users/Allen_Frostline/anaconda3/lib/python3.6/site-packages/ccxt/binance.py", line 707, in handle_errors
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: binance {"code":-1100,"msg":"Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'."}
>>> 
```

Can anybody explain or solve this?

**Comment by kroitor** [comment]
@allenfrostline it's a bug, will be fixed very soon.

**Comment by allenfrostline** [comment]
@kroitor Cool. I thought so :)

**Comment by allenfrostline** [comment]
Hi @kroitor, can you give me an ETA of this bug being fixed? I don't mean to urge it but I can focus on other stuff if it won't happen today.

**Comment by kroitor** [comment]
@allenfrostline it will happen today, the ETA is 4-6 hours from now, I didn't get to it yet. But I will.

**Comment by kroitor** [comment]
This issue is fixed in ccxt as of version 1.10.559. Let us know if you have any difficulties with it. Thx!

**Comment by allenfrostline** [comment]
Thanks. Will test it right away:)

**Comment by akaniklaus** [comment]
`binance.exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.`

@kroitor Can you please let me know why this is happening, I have the same problem over another application that I am trying to develop.

**Comment by kroitor** [comment]
@akaniklaus can you please post a minimal snippet of code to reproduce it?

**Comment by akaniklaus** [comment]
```
buy_price = tickers.loc[markets[x]]['bidPrice'] + float(exchange_info[markets[x]][0]['tickSize'])
buy_quantitiy = apply_lot_size(buy_value/buy_price, float(exchange_info[markets[x]][1]['stepSize']))
client.order_limit_buy(symbol=markets[x], quantity=buy_quantitiy, price=buy_price)
```

Note: I am using https://github.com/binance-exchange/python-binance

**Comment by kroitor** [comment]
@akaniklaus this is a formatting error, float() will put scientific notation in your code:

```Python
>>> float(0.00000001)
1e-08
>>> float(0.0000001)
1e-07
>>> float(0.000001)
1e-06
>>> float(0.00001)
1e-05
>>> float(0.0001)
0.0001
>>>
```

Those 1e-N numbers are not supported. Only fixed-point decimals are accepted. Hope it helps.

**Comment by akaniklaus** [comment]
@kroitor Thanks, this is indeed very helpful.

**Comment by DexHunter** [comment]
@akaniklaus You can use `'{:.8f}'.format(float(1e-8))` to get `0.00000001`

**Comment by akaniklaus** [comment]
@DexHunter Already did, thanks. I am using the following function:
```
def format_value(val, ss):
	precision = ss.find('1') - 1
	return "{:0.0{}f}".format(val, precision)
```

**Comment by hivemall** [comment]
this error also appears if since= is a float, ensure its an int() or use exchange.milliseconds().
fin.
