### ISSUE TITLE
kucoin Invalid KC-API-TIMESTAMP

### ISSUE THREAD

**Issue by mdmiko** [ccxt/ccxt#10556]
I get the error on fetchBalance() (connection and getTickers works) 

- OS: Debian 10
- Programming Language version: nodejs 14.11.0
- CCXT version: 1.60.88

```
                exchange = new ccxt[gConfig.exchange.name] ({
                        // add at least some rate-limiting as required by the Manual:
                        // https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
                        'enableRateLimit': true,
                        'apiKey': gConfig.exchange.apiKey,
                        'secret': gConfig.exchange.secret,
                        'password': gConfig.exchange.password
                });
                exchange.verbose = true;
                console.log("Connected to exchange:", exchange.name)
                //---------------------------------------------------
                const mk = new MarketInfo(exchange);
                const pf = new Portfolio();

                mk.tickers = await exchange.fetchTickers();
                pf.balances = await exchange.fetchBalance();

```

```
VERBOSE:

fetch:
 kucoin GET https://openapi-v2.kucoin.com/api/v1/accounts?type=trade
Request:
 {
  'KC-API-KEY-VERSION': '2',
  'KC-API-KEY': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'KC-API-TIMESTAMP': '1636638160456',
  'KC-API-PASSPHRASE': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'KC-API-SIGN': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
}
 undefined

handleRestResponse:
 kucoin GET https://openapi-v2.kucoin.com/api/v1/accounts?type=trade 400 Bad Request
Response:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '6ac7feadb886631b-ORD',
  Connection: 'keep-alive',
  'Content-Length': '50',
  'Content-Type': 'application/json',
  Date: 'Thu, 11 Nov 2021 13:51:21 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': 'xxxxxxxxxxxxxxx; Expires=Thu, 18 Nov 2021 13:51:21 GMT; Path=/, AWSALBCORS=HO94r0kRH0/GLv63I8IkJLx7VzpFQFcHB1jaeOKb+wi83rJ8nn7iRBwAxwStognk0M/SPOSs88nI1tsxvguW/SX05/ak5ZOoBU/73Um62wy6X9F8Ubv2CO/Eqaez; Expires=Thu, 18 Nov 2021 13:51:21 GMT; Path=/; SameSite=None; Secure, __cfruid=23d2e6d5130bb63531cb58b5abfd4b5a250960f5-1636638681; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None'
}
 {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}


OUTPUT:
InvalidNonce: kucoin Invalid KC-API-TIMESTAMP
    at kucoin.throwExactlyMatchedException (/home/mdmiko/nodejs_cryptobalancer/node_modules/ccxt/js/base/Exchange.js:591:19)
    at kucoin.handleErrors (/home/mdmiko/nodejs_cryptobalancer/node_modules/ccxt/js/kucoin.js:2496:14)
    at /home/mdmiko/nodejs_cryptobalancer/node_modules/ccxt/js/base/Exchange.js:668:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timeout (/home/mdmiko/nodejs_cryptobalancer/node_modules/ccxt/js/base/functions/time.js:206:24)
    at async kucoin.fetchBalance (/home/mdmiko/nodejs_cryptobalancer/node_modules/ccxt/js/kucoin.js:2016:30)
    at async run (/home/mdmiko/nodejs_cryptobalancer/index.js:69:31) {
  constructor: [class InvalidNonce extends NetworkError]
}

```

**Comment by kroitor** [comment]
@mdmiko make sure that your system clock is in synch with the UTC time. If that does not help, try a fresh new keypair.

**Comment by mdmiko** [comment]
@kroitor thanks a lot.
I set UTC and new keys, but issue was sync with UTC time.

sudo systemctl start systemd-timesyncd
