### ISSUE TITLE
FTX - how to open position using leverage

### ISSUE THREAD

**Issue by drodval** [ccxt/ccxt#10575]
Hi, I am trying to open a new position with margin in ftx but there is no way... always returning **ftx {"success":false,"error":"Account does not have enough margin for order."}**

Does any one can help me with this please?

Thank you so much!!!

David

- OS: ubuntu
- Programming Language version: Python 3.6.9
- CCXT version: 1.61.16

```
self.ftx = ccxt.ftx({
            'enableRateLimit': True,
            "apiKey": api_key,
            "secret": api_secret,
            'headers': {
                'FTX-SUBACCOUNT': subaccount_name,
            },
            "hostname": "ftx.com"
        })
response = self.ftx.set_leverage(3)
print('set_leverage - ', response)
self.ftx.create_order('ETH-PERP', 'market', 'buy', 2)

```

```
set_leverage -  {'success': True, 'result': None}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 613, in fetch
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: https://ftx.com/api/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 66, in <module>
    {'leverage': 3}
  File "/home/ALQUIMIA/core/connectors/ftx_connector.py", line 26, in open_trade
    order = self.ftx.create_order(symbol, trade_type, side, quantity) #, price, params)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/ftx.py", line 1199, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 506, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 629, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/ftx.py", line 1901, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 525, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.InsufficientFunds: ftx {"success":false,"error":"Account does not have enough margin for order."}
```

**Comment by samgermain** [comment]
Hi @drodval ,

Can you run 

```
balance = ftx.privateGetWalletAllBalances()
pprint(balance)
```

and paste the response into here?

**Comment by drodval** [comment]
Hi,
already solved. Please feel free to close the ticket.

Thanks!
