### ISSUE TITLE
Invalid api url formed

### ISSUE THREAD

**Issue by SauravKumal** [ccxt/ccxt#10601]
- OS: Ubuntu 20.04.3 LTS (Focal Fossa)
- Programming Language version: js, nodejs v15.12.0
- CCXT version: 1.61.16

```
const bybit = require('./js/bybit')
let b = new bybit()
b.apiKey = '...'
b.secret = '...'
b.setSandboxMode(true)
b.spotPrivateGetAccount(
).then(resp=>console.log(resp))
```

```
ExchangeNotAvailable: bybit GET https://api-testnet.bybit.com/spot/private/v1/account 404 Not Found {"ret_code":0,"ret_msg":"","ext_code":null,"ext_info":null,"result":"\u003chtml\u003e\u003cbody\u003e\u003ch2\u003e404 Not found\u003c/h2\u003e\u003c/body\u003e\u003c/html\u003e"}
    at bybit.handleHttpStatusCode (/home/saurav/PhpstormProjects/ccxt/js/base/Exchange.js:622:19)
    at /home/saurav/PhpstormProjects/ccxt/js/base/Exchange.js:669:18
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async timeout (/home/saurav/PhpstormProjects/ccxt/js/base/functions/time.js:198:20) {
  constructor: [class ExchangeNotAvailable extends NetworkError]
}

```
The actual GET url should have been `https://api-testnet.bybit.com/spot/v1/account`
The unified method `b.fetchBalance()` returns balance of other accounts like inverse and futures. I am trying to get the balance of spot account.

**Comment by ttodua** [comment]
Bybit had been updated & released a while ago, so, this issue is no longer valid.
let us know if you face any problem with CCXT.
