### ISSUE TITLE
Cryptopia create_limit_buy_order failing with an exception

### ISSUE THREAD

**Issue by maltium** [ccxt/ccxt#1070]
When using the Python version of the library, create_limit_buy_order() fails with the following exception:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.2\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "D:\Development\crypto-p1\venv\lib\site-packages\ccxt\base\exchange.py", line 1009, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "D:\Development\crypto-p1\venv\lib\site-packages\ccxt\cryptopia.py", line 354, in create_order
    'Amount': self.amount_to_precision(symbol, amount),
  File "D:\Development\crypto-p1\venv\lib\site-packages\ccxt\base\exchange.py", line 780, in amount_to_precision
    return self.truncate(amount, self.markets[symbol]['precision']['amount'])
  File "D:\Development\crypto-p1\venv\lib\site-packages\ccxt\base\exchange.py", line 436, in truncate
    return '{0:f}'.format(Decimal(num).quantize(math.pow(10, -precision)))
TypeError: conversion from float to Decimal is not supported
```

The issue is that the *precision* argument in Decimal.quantize(precision) should be of Decimal type rather than a float.

I'm not sure if this issue affects other exchanges, seeing that it is present in exchange.py.

**Comment by maltium** [comment]
I see that someone else has reported the same issue a few minutes ago.

**Comment by maltium** [comment]
Please note that the latest commit does not fix the issue. The cryptopia exchange uses the truncate(num, precision=0) method rather than truncate_to_string(num, precision=0).

**Comment by kroitor** [comment]
@maltium will fix for Cryptopia as well, thx for pointing that out.

**Comment by kroitor** [comment]
@maltium which version of Python do you have?

**Comment by kroitor** [comment]
Related to #1069

**Comment by maltium** [comment]
I'm using Python 3.6.2

**Comment by maltium** [comment]
I confirm that it works.

Thank you for the prompt fix.

**Comment by kroitor** [comment]
Awesome! Thx! Let us know if you have any other difficulties with it! Cheers!
