### ISSUE TITLE
createMarketBuyOrder Uses Cryptocurrency Amount Instead of Fiat Amount

### ISSUE THREAD

**Issue by JohnSmithyy** [ccxt/ccxt#10723]
So I'm trying to place a market order on coinbasepro using the createMarketBuyOrder function. However, whenever I specify the amount of FIAT I want to spend (in this case $20 USD), it tries to buy 20 bitcoins instead? 

Am I using this function incorrectly or is this the intended behavior? How do I go about purchasing as much bitcoin with my $20 instead?

Here are all the details below:

- OS: Ubuntu WSL
- Programming Language version: Python3.8
- CCXT version: 1.62.38

```
import ccxt
exchange_id = "coinbasepro"
trading_pair = "BTC/USD
amount = 20
exchange_class = getattr(ccxt, exchange_id)
exchange_class_set = exchange_class(
            {'apiKey': api_key, 'secret': api_secret, 'password': api_pass ,
            'enableRateLimit': True,
             'options': {
                 'createMarketBuyOrderRequiresPrice': False,
            },
             })
exchange_class_set.set_sandbox_mode(True)
if exchange_class_set.has['createMarketOrder']:
            order = exchange_class_set.createMarketBuyOrder(trading_pair, amount)
            print("Made Market Order", order)
```

Here is the verbose output. It shows that a USD volume of $99.8 was used to make the purchase which is also the amount I had left in my coinbase pro in USD. So it appears that it's attempting to purchase 20 bitcoins with the FIAT value I have left in my account. When in reality, I want the opposite behavior where we want to buy as much bitcoin with the set amount of $20 at market price.
```
Request: GET https://api-public.sandbox.pro.coinbase.com/currencies {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api-public.sandbox.pro.coinbase.com/currencies 200 {'Date': 'Sun, 28 Nov 2021 14:23:26 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'Cache-Control': 'public, max-age=30, must-revalidate', 'Etag': 'W/"121d-Xh0ARApkiVqygTvT93kg+D4X8DA"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-Dns-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'EXPIRED', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '6b54410bfa4f18a1-EWR', 'Content-Encoding': 'gzip'} [{"id":"XRP","name":"XRP","min_size":"1","status":"delisted","message":"","max_precision":"1","convertible_to":[],"details":{"type":"crypto","symbol":"$","network_confirmations":null,"sort_order":21,"crypto_address_link":"https://bithomp.com/explorer/{{address}}","crypto_transaction_link":"https://bithomp.com/explorer/{{txId}}","push_payment_methods":["crypto"],"group_types":[],"display_name":null,"processing_time_seconds":4,"min_withdrawal_amount":22,"max_withdrawal_amount":100000}},{"id":"USD","name":"United States Dollar","min_size":"0.01","status":"online","message":"","max_precision":"0.01","convertible_to":["USDC"],"details":{"type":"fiat","symbol":"$","network_confirmations":null,"sort_order":0,"crypto_address_link":null,"crypto_transaction_link":null,"push_payment_methods":["bank_wire","swift_bank_account","intra_bank_account"],"group_types":["fiat","usd"],"display_name":"US Dollar","processing_time_seconds":null,"min_withdrawal_amount":null,"max_withdrawal_amount":null}},{"id":"GBP","name":"British Pound","min_size":"0.01","status":"online","message":"","max_precision":"0.01","convertible_to":[],"details":{"type":"fiat","symbol":"£","network_confirmations":null,"sort_order":2,"crypto_address_link":null,"crypto_transaction_link":null,"push_payment_methods":["uk_bank_account","swift_lhv"],"group_types":["fiat","gbp"],"display_name":null,"processing_time_seconds":null,"min_withdrawal_amount":null,"max_withdrawal_amount":null}},{"id":"EUR","name":"Euro","min_size":"0.01","status":"online","message":"","max_precision":"0.01","convertible_to":[],"details":{"type":"fiat","symbol":"€","network_confirmations":null,"sort_order":1,"crypto_address_link":null,"crypto_transaction_link":null,"push_payment_methods":["sepa_bank_account"],"group_types":["fiat","eur"],"display_name":null,"processing_time_seconds":null,"min_withdrawal_amount":null,"max_withdrawal_amount":null}},{"id":"BTC","name":"Bitcoin","min_size":"0.00000001","status":"online","message":"","max_precision":"0.00000001","convertible_to":[],"details":{"type":"crypto","symbol":"","network_confirmations":6,"sort_order":3,"crypto_address_link":"https://live.blockcypher.com/btc/address/{{address}}","crypto_transaction_link":"https://live.blockcypher.com/btc/tx/{{txId}}","push_payment_methods":["crypto"],"group_types":["btc","crypto"],"display_name":null,"processing_time_seconds":null,"min_withdrawal_amount":0.0001,"max_withdrawal_amount":2400}},{"id":"LINK","name":"Chainlink","min_size":"1","status":"online","message":"","max_precision":"0.00000001","convertible_to":[],"details":{"type":"crypto","symbol":"Ξ","network_confirmations":35,"sort_order":67,"crypto_address_link":"https://etherscan.io/token/0x514910771af9ca656af840dff83e8264ecf986ca?a={{address}}","crypto_transaction_link":"https://etherscan.io/tx/0x{{txId}}","push_payment_methods":["crypto"],"group_types":[],"display_name":null,"processing_time_seconds":null,"min_withdrawal_amount":0.01,"max_withdrawal_amount":136000}},{"id":"USDC","name":"USD Coin","min_size":"0.000001","status":"online","message":"","max_precision":"0.000001","convertible_to":["USD"],"details":{"type":"crypto","symbol":"$","network_confirmations":35,"sort_order":9,"crypto_address_link":"https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48?a={{address}}","crypto_transaction_link":"https://etherscan.io/tx/0x{{txId}}","push_payment_methods":["crypto"],"group_types":["stablecoin","usdc","crypto"],"display_name":null,"processing_time_seconds":null,"min_withdrawal_amount":0.001,"max_withdrawal_amount":15000000}},{"id":"BAT","name":"Basic Attention Token","min_size":"1","status":"online","message":"","max_precision":"1","convertible_to":[],"details":{"type":"crypto","symbol":"","network_confirmations":35,"sort_order":10,"crypto_address_link":"https://etherscan.io/token/0x0d8775f648430679a709e98d2b0cb6250d2887ef?a={{address}}","crypto_transaction_link":"https://etherscan.io/tx/0x{{txId}}","push_payment_methods":["crypto"],"group_types":[],"display_name":null,"processing_time_seconds":null,"min_withdrawal_amount":0.01,"max_withdrawal_amount":365000}},{"id":"ETH","name":"Ether","min_size":"0.00000001","status":"online","message":"","max_precision":"0.00000001","convertible_to":[],"details":{"type":"crypto","symbol":"","network_confirmations":35,"sort_order":7,"crypto_address_link":"https://etherscan.io/address/{{address}}","crypto_transaction_link":"https://etherscan.io/tx/0x{{txId}}","push_payment_methods":["crypto"],"group_types":["eth","crypto"],"display_name":null,"processing_time_seconds":null,"min_withdrawal_amount":0.001,"max_withdrawal_amount":7450}}]

Request: GET https://api-public.sandbox.pro.coinbase.com/products {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api-public.sandbox.pro.coinbase.com/products 200 {'Date': 'Sun, 28 Nov 2021 14:23:26 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'Cache-Control': 'public, max-age=5, must-revalidate', 'Etag': 'W/"1408-KbbxsNt30UZfmkXfIEk3EcMuv5Y"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-Dns-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'EXPIRED', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '6b54410c7b0c18a1-EWR', 'Content-Encoding': 'gzip'} [{"id":"BAT-USDC","base_currency":"BAT","quote_currency":"USDC","base_min_size":"1","base_max_size":"300000","quote_increment":"0.000001","base_increment":"0.000001","display_name":"BAT/USDC","min_market_funds":"1","max_market_funds":"100000","margin_enabled":false,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":false,"status":"online","status_message":"","auction_mode":false},{"id":"BTC-USD","base_currency":"BTC","quote_currency":"USD","base_min_size":"0.000021","base_max_size":"10000","quote_increment":"0.01","base_increment":"0.00000001","display_name":"BTC/USD","min_market_funds":"1","max_market_funds":"1000000","margin_enabled":true,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":false,"status":"online","status_message":"","auction_mode":false},{"id":"LINK-USDC","base_currency":"LINK","quote_currency":"USDC","base_min_size":"1","base_max_size":"800000","quote_increment":"0.000001","base_increment":"1","display_name":"LINK/USDC","min_market_funds":"10","max_market_funds":"100000","margin_enabled":false,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":false,"status":"online","status_message":"","auction_mode":false},{"id":"LINK-USD","base_currency":"LINK","quote_currency":"USD","base_min_size":"0.03","base_max_size":"800000","quote_increment":"0.000001","base_increment":"1","display_name":"LINK/USD","min_market_funds":"1","max_market_funds":"100000","margin_enabled":false,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":false,"status":"online","status_message":"","auction_mode":false},{"id":"BTC-GBP","base_currency":"BTC","quote_currency":"GBP","base_min_size":"0.000021","base_max_size":"10000","quote_increment":"0.01","base_increment":"0.00000001","display_name":"BTC/GBP","min_market_funds":"0.72","max_market_funds":"200000","margin_enabled":false,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":false,"status":"online","status_message":"","auction_mode":false},{"id":"BTC-EUR","base_currency":"BTC","quote_currency":"EUR","base_min_size":"0.000021","base_max_size":"10000","quote_increment":"0.01","base_increment":"0.00000001","display_name":"BTC/EUR","min_market_funds":"0.84","max_market_funds":"600000","margin_enabled":false,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":false,"status":"online","status_message":"","auction_mode":false},{"id":"ETH-BTC","base_currency":"ETH","quote_currency":"BTC","base_min_size":"0.00029","base_max_size":"1000000","quote_increment":"0.00001","base_increment":"0.00000001","display_name":"ETH/BTC","min_market_funds":"0.00002","max_market_funds":"80","margin_enabled":false,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":false,"status":"online","status_message":"","auction_mode":false},{"id":"XRP-BTC","base_currency":"XRP","quote_currency":"BTC","base_min_size":"1","base_max_size":"500000","quote_increment":"0.00000001","base_increment":"1","display_name":"XRP/BTC","min_market_funds":"0.001","max_market_funds":"30","margin_enabled":false,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":true,"status":"delisted","status_message":"","auction_mode":false},{"id":"XRP-GBP","base_currency":"XRP","quote_currency":"GBP","base_min_size":"1","base_max_size":"500000","quote_increment":"0.0001","base_increment":"0.000001","display_name":"XRP/GBP","min_market_funds":"10","max_market_funds":"100000","margin_enabled":false,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":true,"status":"delisted","status_message":"","auction_mode":false},{"id":"XRP-USD","base_currency":"XRP","quote_currency":"USD","base_min_size":"1","base_max_size":"500000","quote_increment":"0.0001","base_increment":"1","display_name":"XRP/USD","min_market_funds":"10","max_market_funds":"100000","margin_enabled":false,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":true,"status":"delisted","status_message":"","auction_mode":false},{"id":"XRP-EUR","base_currency":"XRP","quote_currency":"EUR","base_min_size":"1","base_max_size":"500000","quote_increment":"0.0001","base_increment":"1","display_name":"XRP/EUR","min_market_funds":"10","max_market_funds":"100000","margin_enabled":false,"fx_stablecoin":false,"max_slippage_percentage":"0.10000000","post_only":false,"limit_only":false,"cancel_only":false,"trading_disabled":true,"status":"delisted","status_message":"","auction_mode":false}]

Request: GET https://api-public.sandbox.pro.coinbase.com/accounts {'CB-ACCESS-KEY': 'a02dc850b5ed4cbbdf3a20a3e1d95e40', 'CB-ACCESS-SIGN': 'gQGe+jroMgYehLgqPSmPDJMvxZS6+i5lrdmm1EhCUBo=', 'CB-ACCESS-TIMESTAMP': '1638109407', 'CB-ACCESS-PASSPHRASE': '3vn3v0c3flb', 'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api-public.sandbox.pro.coinbase.com/accounts 200 {'Date': 'Sun, 28 Nov 2021 14:23:26 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'Cache-Control': 'no-store', 'Etag': 'W/"6c6-eSC+VrNOgS8fT/fkeTLQGw9Z+KE"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-Dns-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'MISS', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '6b54410d1c5618a1-EWR', 'Content-Encoding': 'gzip'} [{"id":"3124f35c-e7df-4fbe-9353-de0b9f19de21","currency":"BAT","balance":"0.0000000000000000","hold":"0.0000000000000000","available":"0","profile_id":"9d54ccf5-899d-45d6-9045-f953ffb50bfe","trading_enabled":true},{"id":"a8a8c813-cb41-4cb6-ab3d-65be35ece7ab","currency":"BTC","balance":"0.0442187300000000","hold":"0.0000000000000000","available":"0.04421873","profile_id":"9d54ccf5-899d-45d6-9045-f953ffb50bfe","trading_enabled":true},{"id":"7f656ca5-6d07-4807-b6ce-10272fdf25bd","currency":"ETH","balance":"0.0000000000000000","hold":"0.0000000000000000","available":"0","profile_id":"9d54ccf5-899d-45d6-9045-f953ffb50bfe","trading_enabled":true},{"id":"e4aec905-ac9c-407d-9af6-388809b22065","currency":"EUR","balance":"0.0000000000000000","hold":"0.0000000000000000","available":"0","profile_id":"9d54ccf5-899d-45d6-9045-f953ffb50bfe","trading_enabled":true},{"id":"99a4531c-3771-46a8-9a11-988d8eb041ec","currency":"GBP","balance":"0.0000000000000000","hold":"0.0000000000000000","available":"0","profile_id":"9d54ccf5-899d-45d6-9045-f953ffb50bfe","trading_enabled":true},{"id":"dab1b6a5-ddef-4ad4-beef-f258db60e4bd","currency":"LINK","balance":"0.0000000000000000","hold":"0.0000000000000000","available":"0","profile_id":"9d54ccf5-899d-45d6-9045-f953ffb50bfe","trading_enabled":true},{"id":"9065917a-411a-4b0a-82bb-575b6f693ae7","currency":"USD","balance":"100.0004883591992000","hold":"0.0000000000000000","available":"100.0004883591992","profile_id":"9d54ccf5-899d-45d6-9045-f953ffb50bfe","trading_enabled":true},{"id":"9946a82d-dbe7-452c-b16a-f96a67151cf6","currency":"USDC","balance":"0.0000000000000000","hold":"0.0000000000000000","available":"0","profile_id":"9d54ccf5-899d-45d6-9045-f953ffb50bfe","trading_enabled":true}]

Request: POST https://api-public.sandbox.pro.coinbase.com/orders {'CB-ACCESS-KEY': 'a02dc850b5ed4cbbdf3a20a3e1d95e40', 'CB-ACCESS-SIGN': 'H5/62DlbL5w+NcSft5duaS7eWIKPl2Zu7pi7scQyhzs=', 'CB-ACCESS-TIMESTAMP': '1638109407', 'CB-ACCESS-PASSPHRASE': '3vn3v0c3flb', 'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} {"type":"market","side":"buy","product_id":"BTC-USD","size":"20"}

Response: POST https://api-public.sandbox.pro.coinbase.com/orders 200 {'Date': 'Sun, 28 Nov 2021 14:23:26 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'Cache-Control': 'no-store', 'Etag': 'W/"124-WoJMRxmNAwWF3kGc0OFzeVjYMZA"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-Dns-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '6b54410eefd618a1-EWR', 'Content-Encoding': 'gzip'} {"id":"0f67cabf-9504-4d9e-b50f-8f6c5e4ebdb7","size":"20","product_id":"BTC-USD","side":"buy","stp":"dc","funds":"99.80088658","type":"market","post_only":false,"created_at":"2021-11-28T14:23:26.60209Z","fill_fees":"0","filled_size":"0","executed_value":"0","status":"pending","settled":false}
Made Market Order {'id': '0f67cabf-9504-4d9e-b50f-8f6c5e4ebdb7', 'clientOrderId': None, 'info': {'id': '0f67cabf-9504-4d9e-b50f-8f6c5e4ebdb7', 'size': '20', 'product_id': 'BTC-USD', 'side': 'buy', 'stp': 'dc', 'funds': '99.80088658', 'type': 'market', 'post_only': False, 'created_at': '2021-11-28T14:23:26.60209Z', 'fill_fees': '0', 'filled_size': '0', 'executed_value': '0', 'status': 'pending', 'settled': False}, 'timestamp': 1638109406602, 'datetime': '2021-11-28T14:23:26.602Z', 'lastTradeTimestamp': None, 'status': 'open', 'symbol': 'BTC/USD', 'type': 'market', 'timeInForce': None, 'postOnly': False, 'side': 'buy', 'price': None, 'stopPrice': None, 'cost': 0.0, 'amount': 20.0, 'filled': 0.0, 'remaining': 20.0, 'fee': {'cost': 0.0, 'currency': 'USD', 'rate': None}, 'average': None, 'trades': [], 'fees': [{'cost': 0.0, 'currency': 'USD', 'rate': None}]}

Request: GET https://api-public.sandbox.pro.coinbase.com/fills?order_id=0f67cabf-9504-4d9e-b50f-8f6c5e4ebdb7 {'CB-ACCESS-KEY': 'a02dc850b5ed4cbbdf3a20a3e1d95e40', 'CB-ACCESS-SIGN': 'veKizoPjgEHzDxE/T8jmN5j92dmUqGjF8TUCkzl1OQM=', 'CB-ACCESS-TIMESTAMP': '1638109407', 'CB-ACCESS-PASSPHRASE': '3vn3v0c3flb', 'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api-public.sandbox.pro.coinbase.com/fills?order_id=0f67cabf-9504-4d9e-b50f-8f6c5e4ebdb7 200 {'Date': 'Sun, 28 Nov 2021 14:23:26 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'Cache-Control': 'no-store', 'Cb-After': '36102655', 'Cb-Before': '36102655', 'Etag': 'W/"17b-xe2IPGLWKbRlZa5YA5jpC6Td1Jg"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-Dns-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'MISS', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '6b54410f88e718a1-EWR', 'Content-Encoding': 'gzip'} [{"created_at":"2021-11-28T14:23:26.608374Z","trade_id":36102655,"product_id":"BTC-USD","order_id":"0f67cabf-9504-4d9e-b50f-8f6c5e4ebdb7","user_id":"5a6e32460686b3048899b51b","profile_id":"9d54ccf5-899d-45d6-9045-f953ffb50bfe","liquidity":"T","price":"64308.94000000","size":"0.00155189","fee":"0.1996008017932000","side":"buy","settled":true,"usd_volume":"99.8004008966000000"}]
```

**Comment by kroitor** [comment]
Use this method instead:

```Python
if exchange_class_set.has['createMarketOrder']:
    order = exchange_class_set.createMarketBuyOrder(trading_pair, amount, {'funds': 20})
    print("Made Market Order", order)
```

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-parameters

Hope that answers your question, let us know if not.

**Comment by JohnSmithyy** [comment]
Awesome thank you! 

So this works for coinbase pro but what about other exchanges? Is there any unified format for this or will it vary from exchange to exchange?

**Comment by kroitor** [comment]
@JohnSmithyy some exchanges don't support amounts in quote currency, for those exchanges that support quote amounts, you can place orders as described in the manual: https://github.com/ccxt/ccxt/wiki/Manual#market-buys

**Comment by JohnSmithyy** [comment]
@kroitor For sure thank you! The last question I had was regarding the amount and price variables for the market buy found here:

`const order = await exchange.createOrder (symbol, 'market', 'buy', amount, price)`

Let's say bitcoin is trading at $50. I put in my price at $100. Do I need to modify the amount to match the total amount of bitcoins I can buy (in this case 2) or can I leave it at just 1 and will the price automatically attempt to purchase as many bitcoins with $100?

**Comment by kroitor** [comment]
@JohnSmithyy Most of the exchanges will require the `amount` in base currency for market orders.

> Do I need to modify the amount to match the total amount of bitcoins I can buy (in this case 2) or can I leave it at just 1 and will the price automatically attempt to purchase as many bitcoins with $100?

You can leave just `1`, the total will be calculated as `amount` * `price`.

> Also is the check to see if we can place market orders the same as just using this function below?

It's this specific check:

```Python
if exchange.options.get('createMarketBuyOrderRequiresPrice', False):
```

**Comment by JohnSmithyy** [comment]
Sorry to comment on an old issue but this seems to fail for kraken. It throws me an error for not meeting the minimum order size.

Here is the error message:

```
Traceback (most recent call last):
  File "/app/project/services/ccxtHelper.py", line 66, in place_market_order
    order = exchange.createOrder(trading_pair, 'market', 'buy', 1, dcaAmount)
  File "/app/.heroku/python/lib/python3.9/site-packages/ccxt/kraken.py", line 1105, in create_order
    response = self.privatePostAddOrder(self.extend(request, params))
  File "/app/.heroku/python/lib/python3.9/site-packages/ccxt/base/exchange.py", line 459, in inner
    return entry(_self, **inner_kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/ccxt/base/exchange.py", line 508, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/app/.heroku/python/lib/python3.9/site-packages/ccxt/base/exchange.py", line 504, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/app/.heroku/python/lib/python3.9/site-packages/ccxt/base/exchange.py", line 656, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/app/.heroku/python/lib/python3.9/site-packages/ccxt/kraken.py", line 1901, in handle_errors
    raise InvalidOrder(self.id + ' ' + body)
 ccxt.base.errors.InvalidOrder: kraken {"error":["EGeneral:Invalid arguments:volume"]}
```

In this case, should I fetch the minimum order size for each exchange and put that in the amount field? Or is there another approach to this.

**Comment by kroitor** [comment]
@JohnSmithyy as far as i see, the amount is always in the base currency for Kraken.

**Comment by JohnSmithyy** [comment]
So how would I modify the following code below to make it work for kraken and other exchanges in general? I want to buy $5 of cardano for example. I hope I understood you comment on createMarketBuyOrderRequiresPrice correctly.

```
import ccxt
exchange_id = "kraken"
trading_pair = "ADA/USD
price = 5
amount = 1
exchange_class = getattr(ccxt, exchange_id)

exchange_class_set = exchange_class(
            {'apiKey': api_key, 'secret': api_secret, 'password': api_pass ,
            'enableRateLimit': True})

if exchange_class_set.has['createMarketOrder']:
    if exchange.options.get('createMarketBuyOrderRequiresPrice', False):
        order = exchange.createOrder(trading_pair, 'market', 'buy', price)
    else:
        order = exchange.createOrder(trading_pair, 'market', 'buy', amount, price)
    print("Made Market Order", order)

```

**Comment by kroitor** [comment]
@JohnSmithyy you should set the amount for Kraken, not the price. Most of the exchanges will require the amount in base currency for market orders and for limit orders. This is covered here:

- https://docs.ccxt.com/en/latest/manual.html#consistency-of-base-and-quote-currencies
- https://github.com/ccxt/ccxt/wiki/Manual#market-buys

So a proper code is:

```Python
import ccxt
exchange_id = "kraken"
trading_pair = "ADA/USD
exchange_class = getattr(ccxt, exchange_id)

exchange_class_set = exchange_class(
            {'apiKey': api_key, 'secret': api_secret, 'password': api_pass ,
            'enableRateLimit': True})

if exchange_class_set.has['createMarketOrder']:
    if exchange.options.get('createMarketBuyOrderRequiresPrice', False):
        # cost = price * amount = how much USD you want to spend for buying 
        amount = 1 
        price = 5
        order = exchange.createOrder(trading_pair, 'market', 'buy', amount, price)
    else:
        amount = 5  # how much ADA you want to market-buy, change for your value here
        order = exchange.createOrder(trading_pair, 'market', 'buy', amount)
    print("Made Market Order", order)
```

↑ Change for your values above.

**Comment by JohnSmithyy** [comment]
Regarding line `if exchange.options.get('createMarketBuyOrderRequiresPrice', False):`, does createMarketBuyOrderRequiresPrice change depending on the exchange we use? I know it's defined as true by default but will it be false for other exchanges?

**Comment by kroitor** [comment]
@JohnSmithyy 

> does createMarketBuyOrderRequiresPrice change depending on the exchange we use? 

Yes, it is meant to help you distinguish one type of exchanges from the other.

>  I know it's defined as true by default but will it be false for other exchanges?

It is not defined by default and therefore it's usually `False` by default, and it will only be set to `True` on the exchanges that require the market-buy price as explained in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#market-buys

**Comment by JohnSmithyy** [comment]
And I'm guessing all this applies to exchanges that don't have `.has['createMarketOrder']` as well. As in the snippet you posted above would also apply to exchanges without a market order ability.

**Comment by kroitor** [comment]
@JohnSmithyy 

> As in the snippet you posted above would also apply to exchanges without a market order ability.

Not really, if you follow the code above carefully.

I think you're missing the explanation from the Manual.

**Comment by JohnSmithyy** [comment]
Yep, I totally misunderstood and misread. I think this clears everything up. For exchanges that support market orders, follow the snippet and for those that don't, place limit buy orders to simulate a market order. 

I think that answers all my questions. Thanks again for everything :)
