### ISSUE TITLE
Amount Error with mexc.com market order: (node:37718) UnhandledPromiseRejectionWarning: Error: NaN: invalid number (contains an illegal character 'N')

### ISSUE THREAD

**Issue by franklee00** [ccxt/ccxt#10728]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: macOS
- Programming Language version: node.js v14.15.3
- CCXT version: ^1.58.25

```
async function main (){
    let pair = 'ETH_USDT';
    let amount = 10.0;
    let x = await mexc.createMarketBuyOrder (pair, amount);
    console.log(x);
}
main();
```

```
(node:37718) UnhandledPromiseRejectionWarning: Error: NaN: invalid number (contains an illegal character 'N')
    at decimalToPrecision (/Users/priest/node_modules/ccxt/js/base/functions/number.js:190:19)
    at decimalToPrecision (/Users/priest/node_modules/ccxt/js/base/functions/number.js:123:27)
    at mexc.priceToPrecision (/Users/priest/node_modules/ccxt/js/base/Exchange.js:1462:16)
    at mexc.createSpotOrder (/Users/priest/node_modules/ccxt/js/mexc.js:1526:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async mexc.createOrder (/Users/priest/node_modules/ccxt/js/mexc.js:1504:20)
    at async main (/Users/priest/Documents/GitHub/BSC/arb/biarb/mexc.js:58:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37718) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
the same code works well with binance API !!!!

**Comment by kroitor** [comment]
@franklee00 mexc does not support market orders: https://mxcdevelop.github.io/APIDoc/ Only limit orders are supported. Hope that answers your question, let us know if not.

**Comment by franklee00** [comment]
> @franklee00 mexc does not support market orders: https://mxcdevelop.github.io/APIDoc/ Only limit orders are supported. Hope that answers your question, let us know if not.

Got it! thx.
