### ISSUE TITLE
IDEX v3 create_limit_buy_order AuthenticationError: idex Invalid wallet signature

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#10787]
- OS: Ubuntu
- Programming Language version: Python 3.6.9
- CCXT version: 1.63.1

Not sure if CCXT is supposed to be ready for IDEX v3 or not, but I'm getting following error when placing an order:

```
import ccxt

exchange = ccxt.idex({'apiKey': api_key, 'secret': secret, 'walletAddress': wallet_address, 'privateKey': private_key})
exchange.create_limit_buy_order('MATIC/ETH', '0.00044999', '20')
```

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 617, in fetch
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api-matic.idex.io/v1/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 37, in <module>
    exchange.create_limit_buy_order('MATIC/ETH', '0.00044999', '20')
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 2078, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', amount, price, params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/idex.py", line 1029, in create_order
    response = self.privatePostOrders(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 510, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 506, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 633, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/idex.py", line 1110, in handle_errors
    raise Exception(self.id + ' ' + message)
ccxt.base.errors.AuthenticationError: idex Invalid wallet signature
```

I was able to successfully place orders with this method in IDEX v2 using CCXT. I used following format in the initialization (that has been working with IDEX v2):

api_key -> lower case dashed hex string
secret -> mixed case alphanumeric string
wallet_address -> lower case hex string beginning with '0x' (also tried mixed case)
private_key -> lower case hex string beginning with '0x'

Also generated new api key and secret, did not change a thing. 

Am I using wrong format, is there a bug or is the library not yet ready?

**Comment by frosty00** [comment]
We haven't finished integrating idex v3, hope to do it soon!
