### ISSUE TITLE
Invalid API KEY error even though I have tested the key via postman and it should work.

### ISSUE THREAD

**Issue by zaWarudo99** [ccxt/ccxt#10864]
- OS: macOS Monterey
- Programming Language version: JS, node js 17.2.0
- CCXT version: newest

```
const config = require('./config');
const Binance = require('node-binance-api');

const binance = new Binance().options({
    APIKEY: config.binance.credentials.apiKey,
    APISECRET: config.binance.credentials.apiSecret
});

module.exports.getCurrentPrice = async function() {
    let ticker = await binance.prices();

    return ticker[config.binance.tradingPair];
};

module.exports.purchase = async function(amountsObj, cb) {
    let finalCoinAmount = amountsObj.coinAmount;

    if (amountsObj.usdAmount) {
        let ticker = await binance.prices();

        finalCoinAmount = parseFloat((amountsObj.usdAmount / ticker[config.binance.tradingPair]).toFixed(config.binance.floatPrecision));
    }
    
    binance.marketBuy(config.binance.tradingPair, finalCoinAmount, (err, res) => { // The second parameter is the amount of the coin being purchased, not USD
        if (err) {
            return cb(new Error(`Failed to make purchase: ${err.body}`));
        }
    
        return cb(null, res);
    });
}
```

```
(node:55500) UnhandledPromiseRejectionWarning: Error: signedRequest: Invalid API Key!
at requireApiSecret (/Users/diktator/Desktop/crypto-tweet-bot/node_modules/node-binance-api/node-binance-api.js:287:37)
at signedRequest (/Users/diktator/Desktop/crypto-tweet-bot/node_modules/node-binance-api/node-binance-api.js:327:9)
at order (/Users/diktator/Desktop/crypto-tweet-bot/node_modules/node-binance-api/node-binance-api.js:403:9)
at Object.marketBuy (/Users/diktator/Desktop/crypto-tweet-bot/node_modules/node-binance-api/node-binance-api.js:2911:17)
at Object.module.exports.purchase (/Users/diktator/Desktop/crypto-tweet-bot/binance.js:24:13)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use node --trace-warnings ... to show where the warning was created)
(node:55500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:55500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
Unfortunately, we cannot consult you on the 3rd-party packages, since in your code you're not using CCXT at all. We cannot really fix all the software packages in the world, especially, if the software is not our own. I would recommend switching to CCXT.

You can find docs and examples on how to use CCXT here:

- https://docs.ccxt.com/
- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/tree/master/examples/js
- https://github.com/ccxt/ccxt/tree/master/examples#see-also

You can also forward this question to the author of the package you are using, in this case, `node-binance-api`. Hope that helps.
