### ISSUE TITLE
Exception in callback FastClient.receive_loop

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#10867]
OS:Windows 10
Programming Language version: Python 3.7
CCXT version: CCXT version: CCXT Pro Version: 0.8.13
Exchange bitmex
watch orderbook L2

as in your example https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-streams.py
```
async def symbol_loop(self, exchange, symbol):
        print('Starting the', exchange.id, 'symbol loop with', symbol)
        print('Starting the', exchange, 'symbol loop with', symbol)        
        while not self.__stopped:
            # while True:
            try:
                ordbook = await exchange.watch_order_book(symbol)
                ------------my logic
```
Exchange is instantiate like
```
bitmex_test = ccxtpro.bitmex({'verbose': False,
                                      'enableRateLimit': False,
                                      'apiKey': '---------',
                                      # always write your credentials in single quotes, not double quotes
                                      'secret': '-----------',
                                      'newUpdates': True,
                                      # solo ultimo update ma se faccio cancel all ovviamente li ricevo tutti
                                      # con options modifico la cache posso anche variare limit nel metodo
                                      'options': {
                                          'tradesLimit': 1000,
                                          'OHLCVLimit': 1000,
                                          'ordersLimit': 1000,
                                      },
                                      })
```
I have this error
```
Exception in callback FastClient.receive_loop.<locals>.handler() at C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxtpro\base\fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxtpro\base\fast_client.py:20>
Traceback (most recent call last):
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxtpro\base\fast_client.py", line 25, in handler
    self.handle_message(message)
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxtpro\base\aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxtpro\base\aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxtpro\bitmex.py", line 1224, in handle_message
    return method(client, message)
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxtpro\bitmex.py", line 1075, in handle_order_book
    messageHash = table + ':' + marketId
TypeError: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "C:\ShieldTrade\Python_Code\Avellanada.py", line 2308, in <module>
    loop.run_until_complete(main())
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 783, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
```

**Comment by ttodua** [comment]
late reply, but i've researched and this issue seems to be addressed in the past.
