### ISSUE TITLE
TypeError when trying to fetch conditional orders on FTX

### ISSUE THREAD

**Issue by DemoFD** [ccxt/ccxt#10880]
I am getting the following error when trying to fetch my trigger orders history on FTX. I dont think this issue is due to my code.

- OS: Ubuntu 20.04
- Programming Language version: Python 2.7.18
- CCXT version: 1.63.71

However my actual goal is to just get my whole order history. Fetch_orders() works perfectly for market and limit orders, however since I added a stop order this is getting very tedious. I finally managed to find out how to place the stop market order using the following:
```
self.exchange.create_order(symbol, type=stop, side=sell, quantity, price=None, params={'triggerPrice': price})
```
I wish this was properly documented.

After placing the order I need to be able to check if the order got filled and therefore I try to use the fetch_orders method. I understand conditional orders arent part of it, so I need to check the conditional orders history separately. This I tried with the following code: 
```
self.exchange.fetch_orders(self.symbol, {'method':'privateGetConditionalOrders'}) OR self.exchange.fetch_orders(self.symbol, {'type': 'stop'})
```
, as mentioned here: https://github.com/ccxt/ccxt/issues/8498

And when trying to
```
fetch_open_orders(symbol, since=None, limit=None, {'method':'privateGetConditionalOrders'})
```
I am got the following Error after the third execution (the first and second execution got me an empty list -> worked):
```
1|WizardWalter  | Traceback (most recent call last):
1|WizardWalter  |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
1|WizardWalter  |
1|WizardWalter  | self.run()
1|WizardWalter  |   File "/home/bots/WizardWalter/MPGBot/classes/GridStrategy.py", line 56, in run
1|WizardWalter  |
1|WizardWalter  | self.account.update_all_orders_status()
1|WizardWalter  |   File "/home/bots/WizardWalter/MPGBot/classes/Account.py", line 172, in update_all_orders_status
1|WizardWalter  |
1|WizardWalter  | orders = self.exchange.get_order_history()
1|WizardWalter  |   File "/home/bots/WizardWalter/MPGBot/classes/Exchange.py", line 153, in get_order_history
1|WizardWalter  |     print(self.exchange.fetch_open_orders(self.symbol, {'method':'privateGetConditionalOrders'}))
1|WizardWalter  |   File "/usr/local/lib/python3.8/dist-packages/ccxt/ftx.py", line 1550, in fetch_open_orders
1|WizardWalter  |
1|WizardWalter  | return self.parse_orders(result, market, since, limit)
1|WizardWalter  |   File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 1892, in parse_orders
1|WizardWalter  |
1|WizardWalter  | return self.filter_by_symbol_since_limit(array, symbol, since, limit, tail)
1|WizardWalter  |   File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 1949, in filter_by_symbol_since_limit
1|WizardWalter  |     return self.filter_by_value_since_limit(array, 'symbol', symbol, since, limit, 'timestamp', tail)
1|WizardWalter  |   File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 1943, in filter_by_value_since_limit
1|WizardWalter  |     array = [entry for entry in array if entry[key] >= since]
1|WizardWalter  |   File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 1943, in <listcomp>
1|WizardWalter  |     array = [entry for entry in array if entry[key] >= since]
1|WizardWalter  | TypeError: '>=' not supported between instances of 'int' and 'dict'
```
Although, the following is why I have opened this issue. Executing the following leads to a TypeError inside the ccxt script.
```
    def __init__(self):
        self.historical_data = []
        self.exchange_data = []
        self.open_orders = []
        self.symbol = config.SYMBOL
        coins = self.symbol.split("/")
        self.base_coin = coins[0]
        self.quote_coin = coins[1]

        exchange_class = getattr(ccxt, config.EXCHANGE)
        self.exchange = exchange_class({
            'apiKey': config.API_KEY,
            'secret': config.API_SECRET,
            'enableRateLimit': True
        })
        if config.EXCHANGE == 'ftx' and not config.SUBACCOUNT == '':
            self.exchange.headers = {
                'FTX-SUBACCOUNT': config.SUBACCOUNT
            }

        self.exchange.load_markets()

.
.
.

print(self.exchange.fetch_orders(self.symbol, {'type': 'stop'}))
```

```
1|WizardWalter  | Exception in thread
1|WizardWalter  | Thread-1
1|WizardWalter  | :
1|WizardWalter  | Traceback (most recent call last):
1|WizardWalter  |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
1|WizardWalter  |
1|WizardWalter  | self.run()
1|WizardWalter  |   File "/home/bots/WizardWalter/MPGBot/classes/GridStrategy.py", line 42, in run
1|WizardWalter  |     self.account.sync_db_to_exchange()
1|WizardWalter  |   File "/home/bots/WizardWalter/MPGBot/classes/Account.py", line 178, in sync_db_to_exchange
1|WizardWalter  |     for order in self.exchange.get_order_history():
1|WizardWalter  |   File "/home/bots/WizardWalter/MPGBot/classes/Exchange.py", line 153, in get_order_history
1|WizardWalter  |     print(self.exchange.fetch_orders(self.symbol, {'type': 'stop'}))
1|WizardWalter  |   File "/usr/local/lib/python3.8/dist-packages/ccxt/ftx.py", line 1604, in fetch_orders
1|WizardWalter  |     request['start_time'] = int(since / 1000)
1|WizardWalter  | TypeError: unsupported operand type(s) for /: 'dict' and 'int'

```
I hope we can get this straight. Thanks in advance.

**Comment by frosty00** [comment]
> print(self.exchange.fetch_orders(self.symbol, {'type': 'stop'}))

this code is incorrect, you need to do

```
print(self.exchange.fetch_orders(self.symbol, params={'type': 'stop'}))
```

instead
