### ISSUE TITLE
Error from binance on createOrder using isolated margin account

### ISSUE THREAD

**Issue by dptashny1** [ccxt/ccxt#10890]
- OS: Windows 11
- Programming Language version: Python 3.9 
- CCXT version: 1.63.71

```
import ccxt
exchange = ccxt.binance({**KEY INFO HERE **})

exchange.verbose=True
params = {'isIsolated': 'TRUE'}
my_order = exchange.createOrder('COTI/BTC', 'limit', 'buy', 50, 0.00000633, params)
```

```
Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': '***MY API KEY WAS HERE****', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1639449786995&recvWindow=5000&symbol=COTIBTC&type=LIMIT&side=BUY&newClientOrderId=x-R4BD3S82d71ef19de015598db95b43&newOrderRespType=FULL&quantity=50&price=0.00000633&timeInForce=GTC&isIsolated=TRUE&signature=b9ebaa1e16d1e6fac2ffad106fdcf0237ee0b2a71a224433f35e58f966550e19
Response: POST https://api.binance.com/api/v3/order 400 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '99', 'Connection': 'keep-alive', 'Date': 'Tue, 14 Dec 2021 02:43:07 GMT', 'Server': 'nginx', 'x-mbx-uuid': '7527b5b8-ebb1-4518-956a-576aaf3c577d', 'x-mbx-used-weight': '1', 'x-mbx-used-weight-1m': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 31119c39c5a6dc62dfa1fe940afd7be3.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'SEA73-P1', 'X-Amz-Cf-Id': 'LiOvyN0KcRCslAPV4wOKQniHIlrLPNiewvINMe3KmZ2wSKhHSSB9TA=='} {"code":-1104,"msg":"Not all sent parameters were read; read '11' parameter(s) but was sent '12'."}
Traceback (most recent call last):
  File "C:\Users\david\anaconda3\envs\HelloWorld\lib\site-packages\ccxt\base\exchange.py", line 614, in fetch
    response.raise_for_status()
  File "C:\Users\david\anaconda3\envs\HelloWorld\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\david\anaconda3\envs\HelloWorld\lib\site-packages\ccxt\binance.py", line 2440, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\david\anaconda3\envs\HelloWorld\lib\site-packages\ccxt\base\exchange.py", line 458, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\david\anaconda3\envs\HelloWorld\lib\site-packages\ccxt\binance.py", line 4526, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\david\anaconda3\envs\HelloWorld\lib\site-packages\ccxt\base\exchange.py", line 503, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\david\anaconda3\envs\HelloWorld\lib\site-packages\ccxt\base\exchange.py", line 630, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\david\anaconda3\envs\HelloWorld\lib\site-packages\ccxt\binance.py", line 4506, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Users\david\anaconda3\envs\HelloWorld\lib\site-packages\ccxt\base\exchange.py", line 521, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1104,"msg":"Not all sent parameters were read; read '11' parameter(s) but was sent '12'."}

```

**Comment by ttodua** [comment]
I've found out that you are missing one parameter:
`params = {'type':'margin', 'isIsolated': 'TRUE'}`
