### ISSUE TITLE
Binance US exchange fetch_deposit failing with {"code":-1100,"msg":"Illegal characters found in a parameter."} 

### ISSUE THREAD

**Issue by varunbhat** [ccxt/ccxt#10939]
CCXT failing with {"code":-1100,"msg":"Illegal characters found in a parameter."} 

The endpoint when run directly using _get_ request within the time window passes and returns the result. but using the API returns a failure -1100

- OS: MacOS
- Programming Language version: nodejs v17.0.1
- CCXT version: 1.64.15

```
        for (const e of exchanges) {
            if (e.has['fetchDeposits']) {
                let bk = [
                    "LTC",
                    "BTC",
                    "ETH",
                    "USD",
                    "USDT",
                    "ADA",
                    "USDC"
                ]
                for (const curr of bk) {
                    let params = undefined;
                    if (e.name.includes("Binance")) {
                        e.verbose = true
                        params = {
                            recvWindow: 60000,
                            coin: curr,
                            limit: 1000,
                            // offset: 0,
                            // 'endTime': endTime - 2 * 24 * 60 * 60,
                            // 'startTime': endTime - page_time // defaults to 90 days
                        }
                    }
                    console.log("Fetching deposits curr: ", e.name, curr, startTime.toString(), 300, params)
                    deposits.push(...await e.fetchDeposits(curr, undefined, undefined, params))
                }
            } else {
                console.log(`exchange ${e.name} does not have fetch deposits`)
            }
        }
        console.log(JSON.stringify(deposits))
        return deposits;
    }
```

```
fetch Request:
 binanceus GET https://api.binance.us/sapi/v1/capital/deposit/hisrec?timestamp=1639790938638&recvWindow=60000&coin=LTC&limit=1000&signature=<signature> 
RequestHeaders:
 {
  'X-MBX-APIKEY': '<api_key>'
} 
RequestBody:
 undefined 

handleRestResponse:
 binanceus GET https://api.binance.us/sapi/v1/capital/deposit/hisrec?timestamp=1639790938638&recvWindow=60000&coin=LTC&limit=1000&signature=<signature> 400 Bad Request 
ResponseHeaders:
 {
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Length': '63',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Sat, 18 Dec 2021 01:28:58 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  Via: '1.1 0a30e0595e3f5a11dbd4d77734c2e735.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'RUFq42CUxiVA4A4fOId9dmuxzevnlDTX9SbzZF8hJisEEkJdr5o91A==',
  'X-Amz-Cf-Pop': 'LAX3-C3',
  'X-Cache': 'Error from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
} 
ResponseBody:
 {"code":-1100,"msg":"Illegal characters found in a parameter."} 

/Users/varunbhat/workspace/personal/coinman/server/node_modules/ccxt/js/base/Exchange.js:597
            throw new exact[string] (message)
                  ^

BadRequest: binanceus {"code":-1100,"msg":"Illegal characters found in a parameter."}
    at binanceus.throwExactlyMatchedException (/Users/varunbhat/workspace/personal/coinman/server/node_modules/ccxt/js/base/Exchange.js:597:19)
    at binanceus.handleErrors (/Users/varunbhat/workspace/personal/coinman/server/node_modules/ccxt/js/binance.js:4834:18)
    at /Users/varunbhat/workspace/personal/coinman/server/node_modules/ccxt/js/base/Exchange.js:674:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/Users/varunbhat/workspace/personal/coinman/server/node_modules/ccxt/js/base/functions/time.js:203:20)
    at async binanceus.request (/Users/varunbhat/workspace/personal/coinman/server/node_modules/ccxt/js/binance.js:4861:26)
    at async binanceus.fetchDeposits (/Users/varunbhat/workspace/personal/coinman/server/node_modules/ccxt/js/binance.js:3028:24)
    at async CoinManager.fetch_deposits (/Users/varunbhat/workspace/personal/coinman/server/coinmanager.js:199:38) {
  constructor: [class BadRequest extends ExchangeError]
}

Node.js v17.0.1

```

**Comment by samgermain** [comment]
Hi @varunbhat 

Could you also add the code that you use that creates this issue?

Also, in case you haven't seen it yet, there's a section on [troubleshooting in the CCXT docs](https://docs.ccxt.com/en/latest/manual.html#troubleshooting) that you might find useful

**Comment by ttodua** [comment]
Strange, I've tested and neither in request there appears anything wrong. 
Can you confirm you are still receiving the same error ? maybe there was some exceptional server-side bug on binance API (low chances, but still I doubt, as there is no other explanation).

Lastly, can you double-check, are you sharing the exact code  you use & request/responses, or modified some parts ? (I dont mean removing sensitive info, as you have to do that, but I mean altering any parameter/logic or alike from actual picture)

**Comment by kroitor** [comment]
@varunbhat do you have this issue without the params-overrides?

```JavaScript
                    if (e.name.includes("Binance")) {
                        e.verbose = true
                        params = {
                            // recvWindow: 60000,
                            // coin: curr,
                            // limit: 1000,
                            // offset: 0,
                            // 'endTime': endTime - 2 * 24 * 60 * 60,
                            // 'startTime': endTime - page_time // defaults to 90 days
                        }
                    }
                    console.log("Fetching deposits curr: ", e.name, curr, startTime.toString(), 300, params)
                    deposits.push(...await e.fetchDeposits(curr, undefined, limit)

**Comment by ttodua** [comment]
There have been many updates since then, and at this moment, I can't still reproduce the issue. Neither reporter has ever responded back. Closing this issue for now. 
if anyone has any issue with CCXT, let us know
