### ISSUE TITLE
ExchangeNotAvailable: bitget GET https://api.bitget.com/data/v1/common/currencys 403 Forbidden 

### ISSUE THREAD

**Issue by Orangat** [ccxt/ccxt#10953]
- OS: Mac OS
- Programming Language version: JavaScript
- CCXT version: "ccxt": "^1.64.42",

```
import ccxt from 'ccxt';

//
const exchangeId = 'bitget', exchangeClass = ccxt[exchangeId], bitget = new exchangeClass ({
    'apiKey': 'my_key',
    'secret': 'my_secret_key',
})

// bitget.setSandboxMode(true)

bitget.fetchTicker ('BTC/USDT').then((res => {
    console.log('res', res)
}))

const markets = async () => {
    return await bitget.loadMarkets()
}


console.log(markets())

```

```
throw new ErrorClass ([ this.id, method, url, code, reason, body ].join (' '))
                  ^

ExchangeNotAvailable: bitget GET https://api.bitget.com/data/v1/common/currencys 403 Forbidden 
    at bitget.handleHttpStatusCode (/Users/orangatable/Projects/orang-trader-bot/node_modules/ccxt/js/base/Exchange.js:658:19)
    at /Users/orangatable/Projects/orang-trader-bot/node_modules/ccxt/js/base/Exchange.js:705:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/Users/orangatable/Projects/orang-trader-bot/node_modules/ccxt/js/base/functions/time.js:203:20)
    at async bitget.fetchCurrencies (/Users/orangatable/Projects/orang-trader-bot/node_modules/ccxt/js/bitget.js:910:26)
    at async bitget.loadMarketsHelper (/Users/orangatable/Projects/orang-trader-bot/node_modules/ccxt/js/base/Exchange.js:773:26) {
  constructor: [class ExchangeNotAvailable extends NetworkError]
}

```

**Comment by kroitor** [comment]
We will update it asap, see this related issue: https://github.com/ccxt/ccxt/issues/9871

**Comment by Orangat** [comment]
What about futures, it's working now?

**Comment by kroitor** [comment]
@Orangat unfortunately, not, it's broken at this time cause bitget has changed their API completely. Will try to fix it as soon as we can.

**Comment by Orangat** [comment]
Okay, thanks, will wait :)
