### ISSUE TITLE
Kucoin initialization

### ISSUE THREAD

**Issue by speggos** [ccxt/ccxt#1096]
This reeks of something really simple I'm missing, but can't seem to figure out why this isn't working. Here's the code:

ccxtKucoin = ccxt.kucoin({'apiKey': kucoinKey, 'secret': kucoinSecret})
ccxtKucoin.loadMarkets()

Same syntax as every other market I've tried which works. Any ideas?

- OS: MAC OSX El Captain
- Programming Language: Python
- CCXT version: 1.10.579
- Exchange: Kucoin
- Method: Initialize ccxt object

```
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    import apiCalls as api
  File "/Users/spencercox/Documents/code/flipBot/apiCalls.py", line 47, in <module>
    ccxtKucoin = ccxt.kucoin({'apiKey': kucoinKey, 'secret': kucoinSecret})
AttributeError: 'module' object has no attribute 'kucoin'
```

**Comment by kroitor** [comment]
- What is the output of `pip list | grep ccxt`?
- What is your Python version?
- What is the value of ccxt.__version__ if you print it just before `ccxt.kucoin({...` ?
- How do you link against ccxt in apiCalls.py ?

**Comment by speggos** [comment]
ccxt (1.10.263)
Python 2.7.10

When calling ccxt.version or ccxt.version() I get this response:

  File "main.py", line 30, in <module>
    import apiCalls as api
  File "/Users/spencercox/Documents/code/flipBot/apiCalls.py", line 45, in <module>
    print ccxt.version()
AttributeError: 'module' object has no attribute 'version'

I don't know what your final question is asking.

Other exchanges (hitbtc, bittrex, binance) have been working fine

**Comment by kroitor** [comment]
> ccxt (1.10.263)

Too old. That version is a month old or maybe even older. We are under active development therefore we ask our user to update frequently. Kucoin was not implemented back then )) Just update your ccxt version and you will be fine.

> AttributeError: 'module' object has no attribute 'version'

```Python
import ccxt
print(ccxt.__version__)
```

↑ Not necessary anymore because the reason is now obvious.

**Comment by speggos** [comment]
As I expected it was a silly mistake on my part. You're the man!

**Comment by speggos** [comment]
How to update?

**Comment by speggos** [comment]
typing the following: "pip install ccxt --upgrade" I get the following response:

```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/var/folders/64/nb5cb6c546d0f3g4lvw2dr740000gp/T/pip-tUgp9q-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/var/folders/64/nb5cb6c546d0f3g4lvw2dr740000gp/T/pip-tUgp9q-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/var/folders/64/nb5cb6c546d0f3g4lvw2dr740000gp/T/pip-tUgp9q-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/var/folders/64/nb5cb6c546d0f3g4lvw2dr740000gp/T/pip-tUgp9q-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/var/folders/64/nb5cb6c546d0f3g4lvw2dr740000gp/T/pip-tUgp9q-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/var/folders/64/nb5cb6c546d0f3g4lvw2dr740000gp/T/pip-tUgp9q-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/var/folders/64/nb5cb6c546d0f3g4lvw2dr740000gp/T/pip-tUgp9q-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/var/folders/64/nb5cb6c546d0f3g4lvw2dr740000gp/T/pip-tUgp9q-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/var/folders/64/nb5cb6c546d0f3g4lvw2dr740000gp/T/pip-tUgp9q-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/var/folders/64/nb5cb6c546d0f3g4lvw2dr740000gp/T/pip-tUgp9q-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
```

**Comment by kroitor** [comment]
@speggos `sudo pip install ccxt --upgrade` ?

**Comment by speggos** [comment]
Also does not work

**Comment by kroitor** [comment]
@speggos how did you install it?
