### ISSUE TITLE
Unable to fetch my account balance from BitPanda 

### ISSUE THREAD

**Issue by SergeySypalo** [ccxt/ccxt#10986]
Hey folks, I'm unable o fetch my account balance from BitPanda

- OS: Windows 11
- Programming Language version: Python 3.10.1
- CCXT version: 1.64.57

Here is my code:
```
import ccxt
exchange = ccxt.bitpanda({'apiKey': my_api_key, 'enableRateLimit': True })
print(exchange.fetch_balance())
```

And the error I'm getting:
```
Traceback (most recent call last):
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 656, in fetch
    response.raise_for_status()
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.exchange.bitpanda.com/public/v1/account/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\repos\trading-bot\bitpanda.py", line 17, in <module>
    balances = exchange.fetch_balance()['free']
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bitpanda.py", line 844, in fetch_balance
    response = self.privateGetAccountBalances(params)
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 672, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bitpanda.py", line 1660, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], message, feedback)
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 563, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: bitpanda {"error":"INVALID_CREDENTIALS"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\repos\trading-bot\bitpanda.py", line 62, in <module>
    time.sleep(30)
KeyboardInterrupt
```
Any ideas?

**Comment by kroitor** [comment]
@SergeySypalo my api key for bitpanda is 843 chars, is your key also that long? (Is it correct?)

**Comment by frosty00** [comment]
make sure you are using bitpanda**pro** not bitpanda, they are two different websites: https://www.bitpanda.com/en/pro

**Comment by kroitor** [comment]
Feel free to reopen it if the above does not help.
