### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url and ccxt.base.errors.AuthenticationError: ftx

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#10983]
My code as follows:
ftx = ccxt.ftx({
    'apiKey': 'yPP8VSEXiwo6XrqjZnBG......',
    'secret': 'U9eWWcRFFNOPf5-uI2......',
})

ftx.proxies = ({
    'http': 'sock5://127.0.0.1:1080',
    'https': 'socks5h://127.0.0.1:1080',
})
ftx_balance = ftx.fetch_balance()
print(ftx_balance)

It shows error as follows:
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 655, in fetch
    response.raise_for_status()
  File "D:\anaconda\envs\pythonProject\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://ftx.com/api/wallet/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/pythonProject/new.py", line 13, in <module>
    ftx_balance = ftx.fetch_balance()
  File "C:\Users\Administrator\PycharmProjects\pythonProject\ccxt\ftx.py", line 1082, in fetch_balance
    response = self.privateGetWalletBalances(params)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 499, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 548, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 544, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Administrator\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 671, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\ccxt\ftx.py", line 2070, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 567, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.AuthenticationError: ftx {"success":false,"error":"Not logged in: Timestamp too far from current time"}

Process finished with exit code 1

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/10943
