### ISSUE TITLE
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway

### ISSUE THREAD

**Issue by ZooM3000** [ccxt/ccxt#11005]
- OS: Windows 10 Home
- Programming Language version: Python
- CCXT version: 1.58.84

```
config = {'apiKey': BINANCE.get("key"),
            'secret': BINANCE.get("secret"),
            'enableRateLimit': True,
            'nonce': lambda: str(int(time.time() * 1000)),
            'adjustForTimeDifference': True, #добавил из за ошибки
            
        }
store = CCXTStore(exchange='binance', currency=COIN_REFER, config=config,  retries=7)

data7 = store.getdata(dataname='DOT/USDT', name="DOTUSDT", 
                        timeframe=bt.TimeFrame.Minutes, fromdate=datetime(2021, 12, 16, 0, 0),
                        compression=30 )
```

```
Traceback (most recent call last):
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 613, in fetch
    response.raise_for_status()
  File "D:\Programs\Python\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.binance.com/api/v3/klines?interval=30m&limit=20&symbol=DOTUSDT&startTime=1640318400000&endTime=1640319988429

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\трейдинг\BT\QuikPy-master\backtraderquik\main_binance_2.py", line 774, in <module>
    cerebro.run()
  File "D:\Programs\Python\lib\site-packages\backtrader\cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "D:\Programs\Python\lib\site-packages\backtrader\cerebro.py", line 1298, in runstrategies
    self._runnext(runstrats)
  File "D:\Programs\Python\lib\site-packages\backtrader\cerebro.py", line 1542, in _runnext
    drets.append(d.next(ticks=False))
  File "D:\Programs\Python\lib\site-packages\backtrader\feed.py", line 407, in next
    ret = self.load()
  File "D:\Programs\Python\lib\site-packages\backtrader\feed.py", line 479, in load
    _loadret = self._load()
  File "D:\Programs\Python\lib\site-packages\ccxtbt\ccxtfeed.py", line 111, in _load
    self._fetch_ohlcv()
  File "D:\Programs\Python\lib\site-packages\ccxtbt\ccxtfeed.py", line 170, in _fetch_ohlcv
    data = sorted(self.store.fetch_ohlcv(self.p.dataname, timeframe=granularity,
  File "D:\Programs\Python\lib\site-packages\ccxtbt\ccxtstore.py", line 160, in retry_method
    return method(self, *args, **kwargs)
  File "D:\Programs\Python\lib\site-packages\ccxtbt\ccxtstore.py", line 223, in fetch_ohlcv
    return self.exchange.fetch_ohlcv(symbol, timeframe=timeframe, since=since, limit=limit, params=params)
  File "D:\Programs\Python\lib\site-packages\ccxt\binance.py", line 1881, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "D:\Programs\Python\lib\site-packages\ccxt\binance.py", line 4390, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 630, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 666, in handle_http_status_code
    raise Exception(' '.join([self.id, method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/klines?interval=30m&limit=20&symbol=DOTUSDT&startTime=1640318400000&endTime=1640319988429 502 Bad Gateway <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>502 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: hhWuW2OXbBXHgladxsbvq0QJ9SVcU1s8GY9kfGeRLb0Q6_6N_26N2A==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by kroitor** [comment]
Binance API was down for a short period this morning. Hope that answers your question.
