### ISSUE TITLE
Failures with side SELL  STOP_LOSS_LIMIT 

### ISSUE THREAD

**Issue by gmartino542** [ccxt/ccxt#11139]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: python 3.10
- CCXT version:    1.65.65

```
import ccxt
import config
import schedule
import pandas as pd
from binance.client import Client
from datetime import datetime
import time
import warnings

warnings.filterwarnings('ignore')

# pd.set_option('display.max_rows', None)


client = Client(config.API_KEY, config.API_SECRET, tld='com')

exchange = ccxt.binance({'apiKey': config.API_KEY, 'secret': config.API_SECRET})

'''
#  inside a while
if not in position generate a buy market order , never fail that,
then once the buy order is set  , right after that I set a sell  STOP_LOSS_LIMIT order and sometime fails not always but could not underestand the reason.
I you could help me it is very apreciated

'''
        if not verify_in_position():
   
            print('  ****   COMPRAR   ****  ')
            buy_qty = round((balance / (df['close'][last_row_index] * 10)), 5)   # Orden MARKET valor tomado puede variar
            print("CANTIDAD DE MONEDA A COMPRAR= ", buy_qty)
            # ************  Mater Buy Order  *************


            order = exchange.create_market_buy_order(symbol, buy_qty)
            print(order)
            print(" ")
            contador = contador + 1
            print("Contador de compras= ", contador)
            buyed_qty = order['amount']     # Obtengo la cantidad de moneda comprada
            buyed_price = order['price']    # Obtengo a que precio se compro
            print("Cantidad de moneda comprada= ", buyed_qty, "  Al precio de: ", order['price'])



            balance = balance - buyed_price * buyed_qty - comision   # Corregir desde la orden mejor
            buy_price = df['close'][last_row_index]
            print("Balance= ", balance)
            print("Buy Price= ", buyed_price)

            # in_position = True

            print("*******    Vender con stop-limit a precio de la EMA15   ******")

    
            stop_price = df['EMA_15'][last_row_index]
            limit_price = stop_price * 0.99997
            qty = buyed_qty      # Ver si con la orden de compra este valor corresponde
            print("Cantidad de MONEDA a vender= ", qty)

            orden = exchange.createOrder(symbol, 'STOP_LOSS_LIMIT', side='sell', amount=qty, price=limit_price,
                                         params={'stopPrice': stop_price})  # OK   Funca OK !!!!!

            sell_count = sell_count + 1
            print("***   Sell Order   ***", "     Cantidad de renovaciones de ventas Stop-loss-limit= ", sell_count)
			
```

```
			 ****   COMPRAR   ****
CANTIDAD DE MONEDA A COMPRAR=  0.00036
{'info': {'symbol': 'BTCUSDT', 'orderId': '8874356969', 'orderListId': '-1', 'clientOrderId': 'x-R4BD3S82443413b9eeb362ac8eaf14', 'transactTime': '1641425419608', 'price': '0.00000000', 'origQty': '0.00036000', 'executedQty': '0.000360
00', 'cummulativeQuoteQty': '15.68493000', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'BUY', 'fills': [{'price': '43569.25000000', 'qty': '0.00036000', 'commission': '0.00002468', 'commissionAsset': 'BNB', 'tra
deId': '1212470582'}]}, 'id': '8874356969', 'clientOrderId': 'x-R4BD3S82443413b9eeb362ac8eaf14', 'timestamp': 1641425419608, 'datetime': '2022-01-05T23:30:19.608Z', 'lastTradeTimestamp': None, 'symbol': 'BTC/USDT', 'type': 'market', 't
imeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': 43569.25, 'stopPrice': None, 'amount': 0.00036, 'cost': 15.68493, 'average': 43569.25, 'filled': 0.00036, 'remaining': 0.0, 'status': 'closed', 'fee': {'currency': 'BNB', '
cost': 2.468e-05}, 'trades': [{'info': {'price': '43569.25000000', 'qty': '0.00036000', 'commission': '0.00002468', 'commissionAsset': 'BNB', 'tradeId': '1212470582'}, 'timestamp': None, 'datetime': None, 'symbol': 'BTC/USDT', 'id': '1
212470582', 'order': '8874356969', 'type': 'market', 'side': 'buy', 'takerOrMaker': None, 'price': 43569.25, 'amount': 0.00036, 'cost': 15.68493, 'fee': {'cost': 2.468e-05, 'currency': 'BNB'}, 'fees': [{'currency': 'BNB', 'cost': '0.00
002468'}]}], 'fees': [{'currency': 'BNB', 'cost': 2.468e-05}]}

Contador de compras=  2
Cantidad de moneda comprada=  0.00036   Al precio de:  43569.25
Balance=  139.37199749999996
Buy Price=  43569.25
*******    Vender con stop-limit a precio de la EMA15   ******
Cantidad de MONEDA a vender=  0.00036
Traceback (most recent call last):
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 656, in fetch
    response.raise_for_status()
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\Inversiones\robotendesarrollo.py", line 264, in <module>
    schedule.run_pending()
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\schedule\__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
    ret = self.job_func()
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\Inversiones\robotendesarrollo.py", line 258, in run_bot
    check_buy_sell_signals(strategy_data)
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\Inversiones\robotendesarrollo.py", line 165, in check_buy_sell_signals
    orden = exchange.createOrder(symbol, 'STOP_LOSS_LIMIT', side='sell', amount=qty, price=limit_price,
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\ccxt\binance.py", line 2476, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\ccxt\binance.py", line 4630, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 672, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\ccxt\binance.py", line 4595, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], message, self.id + ' ' + message)
  File "D:\Users\gmart\Programs\JetBrains\pythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 563, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderImmediatelyFillable: binance Stop price would trigger immediately.
			
			
```

**Comment by gmartino542** [comment]
I am using Pycharm 2021.2.3 and what bring my attentin is a warning:    
**Unresolved attribute reference 'createOrder' for class 'binance'**

but as I mentioned is not always fail

**Comment by kroitor** [comment]
Let us know if this does not answer your question:

- https://github.com/ccxt/ccxt/issues/8194
- https://dev.binance.vision/t/order-would-trigger-immediately-error/245
- https://dev.binance.vision/t/stop-price-would-trigger-immediately/3210
- https://stackoverflow.com/questions/62317102/ccxt-base-errors-invalidorder-binance-order-would-trigger-immediately
- https://www.google.com/search?q=Stop+price+would+trigger+immediately
