### ISSUE TITLE
bl3p error fetching balances with python async

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#1114]
Error fetching balances with python async. It works in sync. 

- OS: Windows
- Programming Language: Python sync
- CCXT version: 527
- Exchange: bl3p
- Method: fetch_balance()

```
import ccxt.async as ccxt
import test2_config as config
from pprint import pprint
import asyncio


async def main():
    e = ccxt.bl3p()
    e.verbose = True
    e.apiKey = config.exchange_keys['bl3p']['key']
    e.secret = config.exchange_keys['bl3p']['secret']
    pprint(await e.fetch_balance())


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())


C:\Users\gaardiolor\Anaconda3\python.exe C:/Users/gaardiolor/PycharmProjects/test2/_test/testbl3p.py
https://api.bl3p.eu/1/GENMKT/money/info POST https://api.bl3p.eu/1/GENMKT/money/info 
Request: {'Content-Type': 'application/x-www-form-urlencoded', 'Rest-Key': '<snip>', 'Rest-Sign': b'<snip>', 'Accept-Encoding': 'gzip, deflate'} nonce=1515351135
Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/test2/_test/testbl3p.py", line 17, in <module>
    loop.run_until_complete(main())
  File "C:\Users\gaardiolor\Anaconda3\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:/Users/gaardiolor/PycharmProjects/test2/_test/testbl3p.py", line 12, in main
    pprint(await e.fetch_balance())
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\async\bl3p.py", line 64, in fetch_balance
    response = await self.privatePostGENMKTMoneyInfo()
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\async\base\exchange.py", line 84, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\async\base\exchange.py", line 104, in fetch
    async with session_method(url, data=encoded_body, headers=headers, timeout=(self.timeout / 1000), proxy=self.aiohttp_proxy) as response:
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\aiohttp\client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\aiohttp\client.py", line 275, in _request
    resp = req.send(conn)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\aiohttp\client_reqrep.py", line 463, in send
    writer.write_headers(status_line, self.headers)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\aiohttp\http_writer.py", line 247, in write_headers
    [k + SEP + v + END for k, v in headers.items()])
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\aiohttp\http_writer.py", line 247, in <listcomp>
    [k + SEP + v + END for k, v in headers.items()])
TypeError: must be str, not bytes
Unclosed connection
client_connection: Connection<ConnectionKey(host='api.bl3p.eu', port=443, ssl=True)>

Process finished with exit code 1
```

**Comment by kroitor** [comment]
Fixed in 1.10.590. Thank you!
