### ISSUE TITLE
Thousands of "getaddrinfo ENOTFOUND" errors if returning from sleep mode

### ISSUE THREAD

**Issue by frzsombor** [ccxt/ccxt#11150]
I guess this bug(?) is not urgent to fix, and maybe a very special edge case, but I decided to report it anyway. 

The Macbook I'm working on is set to turn off the monitor and even go to energy saving sleep(?) mode after X minutes.
I found that if my CCXT NodeJS project is RUNNING and I'm leaving the notebook for a few hours (and it turns off the monitor, logs me out and maybe the computer even goes to this energy saving sleep(?) mode), when I turn on the computer again, CCXT throws so many errors, that makes the notebook unusable as the RAM usage jumps to ~100%. In my project I'm logging any error that occurs, and below you can see that when I log in again to my computer, these errors are getting thrown at full CPU+RAM usage with ~0.005s difference. I've used CCXT in a couple of projects but I think this only happened when I've connected to WS endpoints. Also it seems like the more time passes (between the sleep and re-login), the more errors are generated and the higher the RAM usage will jump. It's also strange that these are "ENOTFOUND" errors, but these are only thrown when I logged-in again to the system, not during the "sleep" (of course).

Unfortunately that's all I know about this issue. If this is too little info to get started with, or you think this is only caused by this negligible edge case (computer going to sleep mode with CCXT running), just close the issue anytime.

Errors:

```
[...]
[2022-01-06T14:55:43.774Z] ERROR: getaddrinfo ENOTFOUND fstream.binance.com
    [...]
[2022-01-06T14:55:43.787Z] ERROR: getaddrinfo ENOTFOUND fstream.binance.com
    [...]
[2022-01-06T14:55:43.790Z] ERROR: getaddrinfo ENOTFOUND fstream.binance.com
    [...]
[2022-01-06T14:55:43.797Z] ERROR: getaddrinfo ENOTFOUND fstream.binance.com
    object: {
      "err": {
        "type": "NetworkError",
        "message": "getaddrinfo ENOTFOUND fstream.binance.com",
        "stack": "NetworkError: getaddrinfo ENOTFOUND fstream.binance.com
            at WsClient.onError (/project/node_modules/ccxt.pro/js/base/Client.js:214:21)
            at WebSocket.onError (/project/node_modules/ws/lib/event-target.js:140:16)
            at WebSocket.emit (events.js:400:28)
            at emitErrorAndClose (/project/node_modules/ws/lib/websocket.js:835:13)
            at ClientRequest.<anonymous> (/project/node_modules/ws/lib/websocket.js:697:5)
            at ClientRequest.emit (events.js:400:28)
            at TLSSocket.socketErrorListener (_http_client.js:475:9)
            at TLSSocket.emit (events.js:400:28)
            at emitErrorNT (internal/streams/destroy.js:106:8)
            at emitErrorCloseNT (internal/streams/destroy.js:74:3)",
        "name": "NetworkError"
      }
    }
[2022-01-06T14:55:43.798Z] ERROR: getaddrinfo ENOTFOUND fstream.binance.com
    [...]
[2022-01-06T14:55:43.805Z] ERROR: getaddrinfo ENOTFOUND fstream.binance.com
    [...]
[2022-01-06T14:55:43.806Z] ERROR: getaddrinfo ENOTFOUND fstream.binance.com
    [...]
[...]
```

- OS: MacOS v10
- Programming Language version: NodeJS v14
- CCXT version: v1.63.100
- CCXT Pro version: v0.8.58

**Comment by ttodua** [comment]
late reply here, but if anyone still experiences similar till date, let us know

**Comment by kroitor** [comment]
Hello @frzsombor 👋

Closing this during a cleanup of older issues — as explained above, the `ENOTFOUND` burst on wake is expected behavior: during the sleep/wake transition the OS has no network connectivity for several seconds, so every in-flight and reconnecting request fails DNS resolution until the interface is back up. The right way to handle it in a long-running bot is to catch `NetworkError` and retry with backoff, which ccxt's error hierarchy is designed for.

Since nobody has reported the accompanying CPU/RAM growth since we asked in 2024, we're assuming that part was resolved along the way as well. If anyone still sees resource growth after wake on a recent version, please open a fresh issue with a heap snapshot or memory timeline and we'll dig in. Thanks for the report! 🙏
