### ISSUE TITLE
Using KUCOIN when coin is not on my asset.

### ISSUE THREAD

**Issue by nosborbr** [ccxt/ccxt#11175]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Cloud Function
- Programming Language version: Python
- CCXT version: Only Version or last

``` EVERY TIME I SEND A NEW COIN OR SOME COIN I NEVER GET ON MY WALLET IS GIVING ME ERROR AND I CANT MOVE ON ON THIS ```
     _symbolF = request.get_json().get("ticker").upper()
     try:
            position = exchange.fetch_balance()[_symbol]['free']
        except (ccxt.ExchangeError, ccxt.NetworkError) as error:
            position = 0
            print('Got an error', type(error).__name__, error.args)
            raise
``` HERE IS THE ERROR ON CLOUD FUNCTIONS ```
2022-01-08T16:33:24.106Zkucoin_tradepxzsjolmlf72 Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 99, in view_func return function(request._get_current_object()) File "/workspace/main.py", line 83, in run position = exchange.fetch_balance()[_symbol]['free'] KeyError: 'FTM3S'
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/layers/google.p

**Comment by kroitor** [comment]
It is documented in the Manual, the the fetch_balance response will contain the currencies you have, and is not guaranteed to contain the currencies you don't have.

- https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance

This will work:

```Python
     exchange.load_markets()
     try:
            balance = exchange.fetch_free_balance()
            for currency, balance in balance.items():
                print(currency, balance)
            print('-----------------------------------------------')
            for code, currency in exchange.currencies.items():
                print(code, balance.get(code, 0.0)
            print('-----------------------------------------------')
        except (ccxt.ExchangeError, ccxt.NetworkError) as error:
            position = 0
            print('Got an error', type(error).__name__, error.args)
            raise
```

We highly recommend reading the entire Manual from top to bottom, it will save your time:

- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/
- https://docs.ccxt.com

Hope that answers your question.
