### ISSUE TITLE
"Tick size check failed, Symbol sBTCUSDT tick size: 1000000","code":39102}

### ISSUE THREAD

**Issue by CloudTrauma** [ccxt/ccxt#11354]
- OS:Windows 11
- Programming Language version:Python
- CCXT version:1.67.31

```python
import time,ccxt,constants
auth_client = ccxt.phemex({
        'apiKey': constants.key,
        'secret': constants.secret,
})
print(ccxt.__version__)
auth_client.load_markets()
#print(auth_client.id, markets)
def getMarket(market,side,ammount,price):
    params = {
        'timeInForce': 'PostOnly'
    }
    return auth_client.create_order(market,'Limit',side,ammount,price,params)
def findCurrencyPrice(market):
    return auth_client.fetch_ticker(market)['last']
def getLastTrade(symbol):
    return auth_client.fetch_my_trades(symbol)[-1]
def checkMarketOrder():
    if auth_client.has['createMarketOrder']:
        return 'yes'
    else:
        return 'no'
def getBalance(symbol):
    balance = auth_client.fetch_balance()['free']
    if balance == {}:
        return 0
    else:
        return balance[symbol]
market = 'BTC'
symbol = 'sBTCUSDT'
bought = sold = 0
orderPrice = getLastTrade('BTC/USDT')['price']
marketPrice = findCurrencyPrice(symbol)
print(getMarket(symbol,'buy',10/marketPrice,orderPrice+(orderPrice*0.001)))
```

```
1.67.31
Traceback (most recent call last):
  File "D:\TradingBot\ccxt\main.py", line 34, in <module>
    print(getMarket(symbol,'buy',10/marketPrice,orderPrice+(orderPrice*0.001)))
  File "D:\TradingBot\ccxt\main.py", line 13, in getMarket
    return auth_client.create_order(market,'Limit',side,ammount,price,params)
  File "C:\Users\gglc1\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\phemex.py", line 1804, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\gglc1\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\gglc1\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\gglc1\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\gglc1\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 697, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\gglc1\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\phemex.py", line 2639, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: phemex {"msg":"Tick size check failed, Symbol sBTCUSDT tick size: 1000000","code":39102}
```

**Comment by CloudTrauma** [comment]
Turns out because BTC only has up to 2 decimal points and i was trying to make a limit order with 4, it didnt like it
