### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by ZooM3000** [ccxt/ccxt#11389]
Could you help me, I'm getting an error {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}. I know that it is necessary to synchronize local time. I made frequent updates to the registry via time.nist.gov. But the error still crashes, for example yesterday at 11.30 A.M.
It may be that the host forcibly breaks
existing connection?
And now I have this error {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
But time is in sync

- OS: Windows 10 Home
- Programming Language version: Python
- CCXT version: 1.67.39

 config = {'apiKey': BINANCE.get("key"),
            'secret': BINANCE.get("secret"),
            'enableRateLimit': True,
            'nonce': lambda: str(int(time.time() * 1000)),
            'adjustForTimeDifference': True, 
            
        }
    store = CCXTStore(exchange='binance', currency=COIN_REFER, config=config,  retries=7, debug=True) #, debug=True 

    broker = CCXTBroker() 
    cerebro.setbroker(broker)

    data0 = store.getdata(dataname='ETH/USDT', name="ETHUSDT", 
                        timeframe=bt.TimeFrame.Minutes, fromdate=datetime(2022, 1, 6, 0, 0),
                        compression=30 )

Traceback (most recent call last):
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 656, in fetch
    response.raise_for_status()
  File "D:\Programs\Python\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1642483224334&recvWindow=5000&signature=630229e5aa813299a185352e883ac92c71df3fc5a05bd94943adaa3187f03739

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\трейдинг\AlgoTrading\Work_Script\binance_test.py", line 295, in <module>
    cerebro.run()
  File "D:\Programs\Python\lib\site-packages\backtrader\cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "D:\Programs\Python\lib\site-packages\backtrader\cerebro.py", line 1210, in runstrategies
    data._start()
  File "D:\Programs\Python\lib\site-packages\backtrader\feed.py", line 203, in _start
    self.start()
  File "D:\Programs\Python\lib\site-packages\ccxtbt\ccxtfeed.py", line 96, in start
    self._fetch_ohlcv(self.p.fromdate)
  File "D:\Programs\Python\lib\site-packages\ccxtbt\ccxtfeed.py", line 170, in _fetch_ohlcv
    data = sorted(self.store.fetch_ohlcv(self.p.dataname, timeframe=granularity,
  File "D:\Programs\Python\lib\site-packages\ccxtbt\ccxtstore.py", line 160, in retry_method
    return method(self, *args, **kwargs)
  File "D:\Programs\Python\lib\site-packages\ccxtbt\ccxtstore.py", line 223, in fetch_ohlcv
    return self.exchange.fetch_ohlcv(symbol, timeframe=timeframe, since=since, limit=limit, params=params)
  File "D:\Programs\Python\lib\site-packages\ccxt\binance.py", line 2058, in fetch_ohlcv
    self.load_markets()
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 1484, in load_markets
    currencies = self.fetch_currencies()
  File "D:\Programs\Python\lib\site-packages\ccxt\binance.py", line 1177, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "D:\Programs\Python\lib\site-packages\ccxt\binance.py", line 4818, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 672, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, 
request_body)
  File "D:\Programs\Python\lib\site-packages\ccxt\binance.py", line 4796, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "D:\Programs\Python\lib\site-packages\ccxt\base\exchange.py", line 563, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

**Comment by kroitor** [comment]
Please, read these duplicate issues carefully: 

- https://github.com/ccxt/ccxt/search?q=binance+timestamp+1000ms&type=issues

Let us know if that does not help.
