### ISSUE TITLE
ccxt.base.errors.NetworkError okex GET https://www.okex.com/api/v5/asset/currencies

### ISSUE THREAD

**Issue by sunxi0428** [ccxt/ccxt#11465]
- OS:windows
- Programming Language version:python3
- CCXT version:1.68.31

`# -*-  coding:utf-8 -*-#

import ccxt
import time
exchange=ccxt.okex({
    'apiKey':'*******************************************************************',
    'secret':'********************************************************************',
    'password':'*********************',
    'timeout':30000,
    'enableRateLimit':True,
})
exchange.proxies={
   'http': "http://127.0.0.1:1080",
   'https': "https://127.0.0.1:1080",
}
print(ccxt.exchanges)
balance = exchange.fetch_balance()
print(balance)

The error is：

['aax', 'ascendex', 'bequant', 'bibox', 'bigone', 'binance', 'binancecoinm', 'binanceus', 'binanceusdm', 'bit2c', 'bitbank', 'bitbay', 'bitbns', 'bitcoincom', 'bitfinex', 'bitfinex2', 'bitflyer', 'bitforex', 'bitget', 'bithumb', 'bitmart', 'bitmex', 'bitpanda', 'bitrue', 'bitso', 'bitstamp', 'bitstamp1', 'bittrex', 'bitvavo', 'bl3p', 'blockchaincom', 'btcalpha', 'btcbox', 'btcmarkets', 'btctradeua', 'btcturk', 'buda', 'bw', 'bybit', 'bytetrade', 'cdax', 'cex', 'coinbase', 'coinbaseprime', 'coinbasepro', 'coincheck', 'coinex', 'coinfalcon', 'coinmate', 'coinone', 'coinspot', 'crex24', 'cryptocom', 'currencycom', 'delta', 'deribit', 'digifinex', 'eqonex', 'equos', 'exmo', 'flowbtc', 'fmfwio', 'ftx', 'ftxus', 'gateio', 'gemini', 'hitbtc', 'hitbtc3', 'hollaex', 'huobi', 'huobijp', 'huobipro', 'idex', 'independentreserve', 'indodax', 'itbit', 'kraken', 'kucoin', 'kucoinfutures', 'kuna', 'latoken', 'latoken1', 'lbank', 'liquid', 'luno', 'lykke', 'mercado', 'mexc', 'ndax', 'novadax', 'oceanex', 'okcoin', 'okex', 'okex3', 'okex5', 'paymium', 'phemex', 'poloniex', 'probit', 'qtrade', 'ripio', 'stex', 'therock', 'tidebit', 'tidex', 'timex', 'upbit', 'vcc', 'wavesexchange', 'wazirx', 'whitebit', 'xena', 'yobit', 'zaif', 'zb', 'zipmex', 'zonda']
Traceback (most recent call last):
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /api/v5/asset/currencies (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 630, in fetch
    response = self.session.request(
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /api/v5/asset/currencies (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunxi\PycharmProjects\pythonProject1\src\stratey002\strategy.py", line 19, in <module>
    balance = exchange.fetch_balance()
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\okex.py", line 1511, in fetch_balance
    self.load_markets()
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 1484, in load_markets
    currencies = self.fetch_currencies()
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\okex.py", line 908, in fetch_currencies
    response = self.privateGetAssetCurrencies(params)
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\sunxi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 682, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: okex GET https://www.okex.com/api/v5/asset/currencies

**Comment by kroitor** [comment]
If you're using proxies, make sure they work.
