### ISSUE TITLE
Ascendex fetch_markets error

### ISSUE THREAD

**Issue by leastchaos** [ccxt/ccxt#11503]
- OS: linux
- Programming Language version: Python 3.10.0
- CCXT version: 1.68.65

```
import ccxt
ascendex=ccxt.ascendex()
ascendex.load_markets()
```

```
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 656, in fetch
    response.raise_for_status()
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://ascendex.com/api/pro/v2/futures/contract

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1485, in load_markets
    markets = self.fetch_markets(params)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/ascendex.py", line 455, in fetch_markets
    perpetuals = self.v2PublicGetFuturesContract(params)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 672, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/ascendex.py", line 2163, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 563, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: ascendex {"code":100004,"message":"HTTP method is not allowed."}
```

**Comment by kroitor** [comment]
@leastchaos please, let us know if you have this issue with CCXT 1.68.66+, the new build will arrive in ~20 minutes.

**Comment by leastchaos** [comment]
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 656, in fetch
    response.raise_for_status()
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://ascendex.com/api/pro/v2/futures/contract

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1485, in load_markets
    markets = self.fetch_markets(params)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/ascendex.py", line 455, in fetch_markets
    perpetuals = self.v2PublicGetFuturesContract(params)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 672, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/ascendex.py", line 2166, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 563, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: ascendex {"code":100004,"message":"HTTP method is not allowed."}
```
>>> ccxt.__version__
'1.68.67'

I am still having this issue on 1.68.67.

**Comment by kroitor** [comment]
@leastchaos please, post your verbose output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange=ccxt.ascendex()
exchange.load_markets()
```

**Comment by leastchaos** [comment]
the log file is too large to paste here. i uploaded at this link https://filebin.net/lkdjcihuvn0id185

**Comment by kroitor** [comment]
> sometimes it does work, so maybe a rate limit issue? This is only run once at the start of the script though.

Yes, could be a rate limit issue. It is working intermittently. I will make that endpoint optional.

**Comment by kroitor** [comment]
@leastchaos i've pushed an option that controls loading the swaps for ascendex, it defaults to `false`. Please, let me know if you still have this problem with CCXT 1.68.70+ (the new build will arrive in 20 minutes).

**Comment by leastchaos** [comment]
ok thank you.

**Comment by ndubel** [comment]
after this update perpetual markets mark as spot markets 
```
{
  limits: {
    leverage: { min: undefined, max: undefined },
    amount: { min: undefined, max: undefined },
    price: { min: 0.0001, max: undefined },
    cost: { min: 0, max: 1000000 }
  },
  precision: { amount: 1, price: 0.0001 },
  tierBased: true,
  percentage: true,
  taker: 0.001,
  maker: 0.001,
  feeSide: 'get',
  id: 'ADA-PERP',
  symbol: 'ADAUSDT/USDT',
  base: 'ADAUSDT',
  quote: 'USDT',
  settle: undefined,
  baseId: 'ADAUSDT',
  quoteId: 'USDT',
  settleId: undefined,
  type: 'spot',
  spot: true,
  margin: false,
  swap: false,
  future: false,
  option: false,
  active: true,
  contract: false,
  linear: undefined,
  inverse: undefined,
  contractSize: undefined,
  expiry: undefined,
  expiryDatetime: undefined,
  strike: undefined,
  optionType: undefined,
  info: {
    symbol: 'ADA-PERP',
    displayName: 'ADAUSDT',
    baseAsset: 'ADAUSDT',
    quoteAsset: 'USDT',
    status: 'Normal',
    minNotional: '0',
    maxNotional: '1000000',
    marginTradable: false,
    commissionType: 'Quote',
    commissionReserveRate: '0.001',
    tickSize: '0.0001',
    lotSize: '1'
  }
}
```

**Comment by kroitor** [comment]
@ndubel will refix it shortly, thx for pointing it out.
