### ISSUE TITLE
DigiFinex load_markets() TypeError: '>' not supported between instances of 'str' and 'int

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#11619]
- OS: Ubuntu
- Programming Language version: Python 3.6.9
- CCXT version: 1.70.9

```
exchange = ccxt.digifinex({...})
exchange.load_markets()
```

```
Traceback (most recent call last):
...
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1484, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ccxt/digifinex.py", line 277, in fetch_currencies
    deposit = depositStatus > 0
TypeError: '>' not supported between instances of 'str' and 'int'
```

Probably both depositStatus and withdrawStatus in lines 275 and 276 in digifinex.py are in need of int conversions.

**Comment by kroitor** [comment]
Will fix shortly.
