### ISSUE TITLE
Why can't I use The OKEX Demo Trading Services？

### ISSUE THREAD

**Issue by plumblow** [ccxt/ccxt#11644]
- OS:win 10
- Programming Language version:python 3.6
- CCXT version:1.70.48

The issues is that:
```
import ccxt

exchange = ccxt.okex()

exchange.apiKey = "******************************"
exchange.secret = "*******************************"
exchange.password = "******"

exchange.set_sandbox_mode(True)

balance = exchange.fetch_balance()
```
Error:
```
ExchangeError:okex GET https://www.okex.com/api/v5/asset/currencies
```
The API is Demo Trading API.So what'my problem?
thanks

**Comment by kroitor** [comment]
@plumblow please, paste your verbose output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt

exchange = ccxt.okex()

exchange.apiKey = "******************************"
exchange.secret = "*******************************"
exchange.password = "******"

exchange.set_sandbox_mode(True)

exchange.load_markets()

exchange.verbose = True

balance = exchange.fetch_balance()
```

**Comment by plumblow** [comment]
@kroitor sry.The verbose output is:
```
CCXT Version: 1.70.48
Traceback (most recent call last):

  File "<ipython-input-35-fa3a8e9dc190>", line 1, in <module>
    runfile('C:/Users/HP/Desktop/bitcoin/okex.py', wdir='C:/Users/HP/Desktop/bitcoin')

  File "C:\Users\HP\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\HP\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/HP/Desktop/bitcoin/okex.py", line 50, in <module>
    exchange.load_markets()

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1484, in load_markets
    currencies = self.fetch_currencies()

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\okex.py", line 938, in fetch_currencies
    response = self.privateGetAssetCurrencies(params)

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 695, in fetch
    raise ExchangeError(details) from e

ExchangeError: okex GET https://www.okex.com/api/v5/asset/currencies
```

**Comment by kroitor** [comment]
@plumblow ok, please, move the verbose switch one line above loadMarkets(), like this, and paste it here again: 

```Python
exchange.set_sandbox_mode(True)
exchange.verbose = True
exchange.load_markets()
```

**Comment by plumblow** [comment]
@kroitor Here‘s the result.
```
CCXT Version: 1.70.48

fetch Request: okex GET https://www.okex.com/api/v5/asset/currencies RequestHeaders: {'OK-ACCESS-KEY': 'ecbf1197-d448-4458-a2f6-6ef5ad2f7d68', 'OK-ACCESS-PASSPHRASE': '123456', 'OK-ACCESS-TIMESTAMP': '2022-01-25T10:49:22.490Z', 'OK-ACCESS-SIGN': 'QFOP4+mgUYWHHjJcwiNNp4vczGJHqayh5Hmxj0p5/zo=', 'x-simulated-trading': 1, 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None
Traceback (most recent call last):

  File "<ipython-input-36-fa3a8e9dc190>", line 1, in <module>
    runfile('C:/Users/HP/Desktop/bitcoin/okex.py', wdir='C:/Users/HP/Desktop/bitcoin')

  File "C:\Users\HP\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\HP\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/HP/Desktop/bitcoin/okex.py", line 50, in <module>
    exchange.load_markets()

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1484, in load_markets
    currencies = self.fetch_currencies()

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\okex.py", line 938, in fetch_currencies
    response = self.privateGetAssetCurrencies(params)

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 695, in fetch
    raise ExchangeError(details) from e

ExchangeError: okex GET https://www.okex.com/api/v5/asset/currencies
```

**Comment by kroitor** [comment]
@plumblow what does it say in the response section? It should have printed both the request and the response.

**Comment by plumblow** [comment]
![图片](https://user-images.githubusercontent.com/95160509/150964484-0ae256fb-db34-44cb-9e20-de8bdf972e1d.png)

**Comment by kroitor** [comment]
@plumblow interesting, I can't reproduce it on my side with the above code. Does it work for you in an unauthorized way, just to rule out networking configuration problems on your side?

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.okex()

exchange.set_sandbox_mode(True)
exchange.verbose = True
markets = exchange.load_markets()
print(markets)
```

**Comment by kroitor** [comment]
@plumblow i think i found the cause of this bug, pushed a new version of CCXT 1.70.52 (it will arrive in ~20 minutes). Let me know if you have the same issue after upgrading.

**Comment by plumblow** [comment]
@kroitor source code
```
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.okex()

exchange.apiKey = 'ecbf1197-d448-4458-a2f6-6ef5ad2f7d68'
exchange.secret = '7DDBA7A787E622CC60722D26987CB80C'
exchange.password = '123456'

exchange.set_sandbox_mode(True)
exchange.verbose = True
exchange.load_markets()



balance = exchange.fetch_balance()
```
Here‘s the result.
```
CCXT Version: 1.70.55
Traceback (most recent call last):

  File "<ipython-input-37-fa3a8e9dc190>", line 1, in <module>
    runfile('C:/Users/HP/Desktop/bitcoin/okex.py', wdir='C:/Users/HP/Desktop/bitcoin')

  File "C:\Users\HP\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\HP\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/HP/Desktop/bitcoin/okex.py", line 42, in <module>
    exchange = ccxt.okex()

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 402, in __init__
    settings = self.deep_extend(self.describe(), config)

  File "C:\Users\HP\Anaconda3\lib\site-packages\ccxt\okex.py", line 42, in describe
    return self.deep_extend(super(okex, self).describe(), {

TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by kroitor** [comment]
@plumblow i cannot reproduce it, your code works on my side with your keys. I don't use spyder though, that might be the cause. I'm running it in pure python3.

**Comment by kroitor** [comment]
@plumblow how do you launch that script?

**Comment by plumblow** [comment]
@kroitor when i reboot the spyder,it works.Thank you very much!
