### ISSUE TITLE
RuntimeError: throttle queue is over maxCapacity

### ISSUE THREAD

**Issue by daviidarr** [ccxt/ccxt#11645]
Is there a way to throttle large asyncio.gather queries ?

**Comment by kroitor** [comment]
@daviidarr please, paste your code for reference, how do you reproduce it?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by arbynacosta** [comment]
I also encountered this issue 😐 Here are my details:

**Machine Specifications:**
- OS Edition: Windows 10 Enterprise
- OS Version: 21H2
- OS Build: 19044.1645
- Programming Language: Python 3.7.9
- CCXT Version: 1.81.81
- Exchanges Encountered Issue: `binance`, `ftx`, 

**Code To Reproduce Issue:**
```python
import asyncio
import ccxt.async_support as ccxt  # noqa: E402


async def fetch():
    exchange = ccxt.binance(
        {
            "enableRateLimit": True,
            "timeout": 60_000,
            "verbose": True,
        }
    )
    await exchange.load_markets()

    coroutines = []
    for i in range(3000):
        coroutines.append(exchange.fetch_ohlcv("BTC/USDT", "1m", limit=900))

    await asyncio.gather(*coroutines)
    await exchange.close()


def main():
    asyncio.get_event_loop().run_until_complete(fetch())


if __name__ == "__main__":
    main()

```

**Issue Output:**
```shell

fetch Request: binance GET https://api.binance.com/api/v3/exchangeInfo RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: binance GET https://api.binance.com/api/v3/exchangeInfo 200 ResponseHeaders: {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '70650', 'Connection': 'keep-alive', 'Date': 'Mon, 09 May 2022 05:16:23 GMT', 'Server': 'nginx', 'x-mbx-uuid': '6cbc2c97-003d-4191-ad80-7625544c3c06', 'x-mbx-used-weight': '10', 'x-mbx-used-weight-1m': '10', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', ...'Pragma': 'no-cache', 'Expires': '0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 acfb1cd944f7bc93838f5d68a454df62.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'HKG62-C2', 'X-Amz-Cf-Id': 'E8FtN8i1i76QrIvXuXkb6XwV4-uNE-jWkADxrfkmQsR9zlJL-mpDJA=='} ResponseBody: {"timezone":"UTC","serverTime":1652073383214,"rateLimits":[{"rateLimitType":"REQUEST_WEIGHT","interval":"MINUTE","intervalNum":1,"limit":1200},{"rateLimitType":"ORDERS","interval":"SECOND","intervalNum":10,"limit":50},{"rateLimitType":"ORDERS","interval":"DAY","intervalNum":1,"limit":160000},{"rateLimitType":"RAW_REQUESTS","interval":"MINUTE","intervalNum":5,"limit":6100}],"exchangeFilters":[],"symbols":[{"symbol":"ETHBTC","status":"TRADING","baseAsset":"ETH","baseAssetPrecision":8,"quoteAsset":"BTC","quotePrecision":8,"quoteAssetPrecision":8,"baseCommissionPrecision":8,"quoteCommissionPrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":true,"ocoAllowed":true,"quoteOrderQtyMarketAllowed":true,"allowTrailingStop":false,"isSpotTradingAllowed":true,"isMarginTradingAllowed":true,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00000100","maxPrice":"922327.00000000","tickSize":"0.00000100"},{"filterType":"PERCENT_PRICE","multiplierUp":"5","multiplierDown":"0.2","avgPriceMins":5},{"filterType":"LOT_SIZE","minQty":"0.00010000","maxQty":"100000.00000000","stepSize":"0.00010000"},{"filterType":"MIN_NOTIONAL","minNotional":"0.00010000","applyToMarket":true,"avgPriceMins":5},{"filterType":"ICEBERG_PARTS","limit":10},{"filterType":"MARKET_LOT_SIZE","minQty":"0.00000000","maxQty":"1855.77379861","stepSize":"0.00000000"},{"filterType":"TRAILING_DELTA","minTrailingAboveDelta":10,"maxTrailingAboveDelta":2000,"minTrailingBelowDelta":10,"maxTrailingBelowDelta":2000},{"filterType":"MAX_NUM_ORDERS","maxNumOrders":200},{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}],"permissions":["SPOT","MARGIN"]},{"symbol":"LTCBTC","status":"TRADING","baseAsset":"LTC","baseAssetPrecision":8,"quoteAsset":"BTC","quotePrecision":8,"quoteAssetPrecision":8,"baseCommissionPrecision":8,"quoteCommissionPrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":true,"ocoAllowed":true,"quoteOrderQtyMarketAllowed":true,"allowTrailingStop":false,"isSpotTradingAllowed":true,"isMarginTradingAllowed":true,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00000100","maxPrice":"100000.00000000","tickSize":"0.00000100"},{"filterType":"PERCENT_PRICE","multiplierUp":"5","multiplierDown":"0.2","avgPriceMins":5},{"filterType":"LOT_SIZE","minQty":"0.00100000","maxQty":"100000.00000000","stepSize":"0.00100000"},{"filterType":"MIN_NOTIONAL","minNotional":"0.00010000","applyToMarket":true,"avgPriceMins":5},{"filterType":"ICEBERG_PARTS","limit":10},{"filterType":"MARKET_LOT_SIZE","minQty":"0.00000000","maxQty":"9873.28760111","stepSize":"0.00000000"},{"filterType":"TRAILING_DELTA","minTrailingAboveDelta":10,"maxTrailingAboveDelta":2000,"minTrailingBelowDelta":10,"maxTrailingBelowDelta":2000},{"filterType":"MAX_NUM_ORDERS","maxNumOrders":200},{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}],"permissions":["SPOT","MARGIN"]},{"symbol":"BNBBTC","status":"TRADING","baseAsset":"BNB","baseAssetPrecision":8,"quoteAsset":"BTC","quotePrecision":8,"quoteAssetPrecision":8,"baseCommissionPrecision":8,"quoteCommissionPrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":true,"ocoAllowed":true,"quoteOrderQtyMarketAllowed":true,"allowTrailingStop":false,"isSpotTradingAllowed":true,"isMarginTradingAllowed":true,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00000100","maxPrice":"100000.00000000","tickSize":"0.00000100"},{"filterType":"PERCENT_PRICE","multiplierUp":"5","multiplierDown":"0.2","avgPriceMins":5},{"filterType":"LOT_SIZE","minQty":"0.00100000","maxQty":"100000.00000000","stepSize":"0.00100000"},{"filterType":"MIN_NOTIONAL","minNotional":"0.00010000","applyToMarket":true,"avgPriceMins":5},{"filterType":"ICEBERG_PARTS","limit":10},{"filterType":"MARKET_LOT_SIZE","minQty":"0.00000000","maxQty":"10831.38244097","stepSize":"0.00000000"},{"filterType":"TRAILING_DELTA","minTrailingAboveDelta":10,"maxTrailingAboveDelta":2000,"minTrailingBelowDelta":10,"maxTrailingBelowDelta":2000},{"filterType":"MAX_NUM_ORDERS","maxNumOrders":200},{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}],"permissions":["SPOT","MARGIN"]},{"symbol":"NEOBTC","status":"TRADING","baseAsset":"NEO","baseAssetPrecision":8,"quoteAsset":"BTC","quotePrecision":8,"quoteAssetPrecision":8,"baseCommissionPrecision":8,"quoteCommissionPrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":true,"ocoAllowed":true,"quoteOrderQtyMarketAllowed":true,"allowTrailingStop":false,"isSpotTradingAllowed":true,"isMarginTradingAllowed":true,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00000100","maxPrice":"100000.00000000","tickSize":"0.00000100"},{"filterType":"PERCENT_PRICE","multiplierUp":"5","multiplierDown":"0.2","avgPriceMins":5},{"filterType":"LOT_SIZE","minQty":"0.01000000","maxQty":"100000.00000000","stepSize":"0.01000000"},{"filterType":"MIN_NOTIONAL","minNotional":"0.00010000","applyToMarket":true,"avgPriceMins":5},{"filterType":"ICEBERG_PARTS","limit":10},{"filterType":"MARKET_LOT_SIZE","minQty":"0.00000000","maxQty":"6303.09987500","stepSize":"0.00000000"},{"filterType":"TRAILING_DELTA","minTrailingAboveDelta":10,"maxTrailingAboveDelta":2000,"minTrailingBelowDelta":10,"maxTrailingBelowDelta":2000},{"filterType":"MAX_NUM_ORDERS","maxNumOrders":200},{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}],"permissions":["SPOT","MARGIN"]},{"symbol":"QTUMETH",...

Traceback (most recent call last):
  File "dev_test.py", line 27, in <module>
    main()
  File "dev_test.py", line 23, in main
    asyncio.get_event_loop().run_until_complete(fetch())
  File "c:\users\arbynacosta\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "dev_test.py", line 19, in fetch
    await asyncio.gather(*coroutines)
  File "D:\.virtualenvs\ohlcv\lib\site-packages\ccxt\async_support\binance.py", line 2222, in fetch_ohlcv
    response = await getattr(self, method)(self.extend(request, params))
  File "D:\.virtualenvs\ohlcv\lib\site-packages\ccxt\async_support\binance.py", line 5064, in request
    response = await self.fetch2(path, api, method, params, headers, body, config, context)
  File "D:\.virtualenvs\ohlcv\lib\site-packages\ccxt\async_support\base\exchange.py", line 102, in fetch2
    await self.throttle(cost)
  File "D:\.virtualenvs\ohlcv\lib\site-packages\ccxt\async_support\base\throttler.py", line 45, in __call__
    raise RuntimeError('throttle queue is over maxCapacity')
RuntimeError: throttle queue is over maxCapacity
```

**Comment by crypto-only** [comment]
I have the same issue too. Will increase `'maxCapacity'` in `throttle.py` to 200000 from 2000 be helpful? I guess no because It  it's 1 when initialize in 
```
        self.tokenBucket = self.extend({
            'refillRate': 1.0 / self.rateLimit if self.rateLimit > 0 else float('inf'),
            'delay': 0.001,
            'capacity': 1.0,
            'defaultCost': 1.0,
        }, getattr(self, 'tokenBucket', {}))
    def init_rest_rate_limiter(self):
        self.throttle = Throttler(self.tokenBucket, self.asyncio_loop)
```

**Comment by frosty00** [comment]
you cannot have more than 2000 pending tasks with the current design, make less pending tasks and change the design of your code. it's a bad practise to wait for more than 2000 tasks because if you make a new request you will need to wait until after those 2000 tasks finish for it to be scheduled

**Comment by ttodua** [comment]
I hope @frosty00 's answer clarified the issue. 
Let us know if you have additional issue/questions.

**Comment by ttodua** [comment]
some ppl, who still wants to use inefficient design of app, and just want to test things quickly on thy fly (despite the disadvantages mentioned above), you might override `maxCapacity`:
```
ex = new binance(); 
ex.throttle.config['maxCapacity'] = 10000; //instead of default 2000
...
```

**Comment by WillPCowan** [comment]
is maxCapacity just for exchange requests waiting to be sent? I want to set this to 0 because I don't want requests to get queued (should be sent quickly), but wondering if I set this to 0 the client will just be non-concurrent....?

**Comment by nokados** [comment]
You can use semaphore to limit the concurrency:

```python
import asyncio

async def process_with_concurrency_limit(coroutines, concurrency=100):
    semaphore = asyncio.Semaphore(concurrency)
    async def limited_task(cor):
        async with semaphore:
            return await cor
    tasks = [limited_task(cor) for cor in coroutines]
    return await asyncio.gather(*tasks)

# for example:
coroutines = []
for i in range(3000):
    coroutines.append(exchange.fetch_ohlcv("BTC/USDT", "1m", limit=900))
await process_with_concurrency_limit(coroutines)
```
