### ISSUE TITLE
ccxt.base.errors.AuthenticationError: bybit {"ret_code":10003,"ret_msg":"invalid api_key","ext_code":"","ext_info":"","result":null,"time_now":"1643232324.67 0083"}

### ISSUE THREAD

**Issue by byoenghoonmoon** [ccxt/ccxt#11671]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: widow10
- Programming Language version: phthon
- CCXT version: ccxtpro1.0.1

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
import ccxt
import time
import pandas as pd
import pprint
       
import myBybit

import line_alert 

'''

bybitX = ccxt.bybit(config={
    'apiKey': 'Access', 
    'secret': 'Scret',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future'
    }
})



Target_Coin_Ticker = "BTC/USDT"
Target_Coin_Symbol = "BTCUSDT"

ticker = bybitX.fetch_ticker('BTC/USDT')
print(ticker['open'], ticker['high'], ticker['low'], ticker['close'])

time.sleep(0.1)
df_up = myBybit.GetOhlcv(bybitX,Target_Coin_Ticker, '5m')

ma5_up_before2 = myBybit.GetMA(df_up, 5, -3)
ma5_up = myBybit.GetMA(df_up, 5, -2)


df = myBybit.GetOhlcv(bybitX,Target_Coin_Ticker, '5m')


print("Price: ",df['close'][-3], "->",df['close'][-2], "->",df['close'][-1] )

print("5ma: ",myBybit.GetMA(df, 5, -3), "->",myBybit.GetMA(df, 5, -2), "->",myBybit.GetMA(df, 5, -1))

print("RSI14: ",myBybit.GetMA(df, 14, -3), "->",myBybit.GetMA(df, 14, -2), "->",myBybit.GetMA(df, 14, -1))


ma5_before4 = myBybit.GetMA(df, 5, -5)
ma5_before3 = myBybit.GetMA(df, 5, -4)
ma5_before2 = myBybit.GetMA(df, 5, -3)
ma5 = myBybit.GetMA(df, 5, -2)


ma20 = myBybit.GetMA(df, 20, -2)


rsi14 = myBybit.GetMA(df, 14, -1)

balance = bybitX.fetch_balance(params={"type": "future"})

pprint(balance)

print(balance['USDT'])
print("Total Money:",float(balance['USDT']['total']))
print("Remain Money:",float(balance['USDT']['free']))

balance2 = bybitX.private_linear_get_position_list()['result']
time.sleep(0.1)

pprint(balance2)

amt = 0 
entryPrice = 0 
leverage = 1  
unrealizedProfit = 0



if Already_Short == False:
    for posi in balance2:
        if posi['data']['symbol'] == Target_Coin_Symbol and posi['data']['side'] == "Buy":

            amt = float(posi['data']['size'])

            entryPrice = float(posi['data']['entry_price'])
            leverage = float(posi['data']['leverage'])
            unrealizedProfit = float(posi['data']['unrealised_pnl'])
            break
            

        

print("amt:",amt)
print("entryPrice:",entryPrice)
print("leverage:",leverage)
print("unrealizedProfit:",unrealizedProfit)

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```Traceback (most recent call last):
  File "/var/bybit/bybit_auto_BTC.py", line 160, in <module>
    balance = bybitX.fetch_balance(params={"type": "future"})
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/bybit.py", line 1474, in fetch_balance
    response = self.v2PrivateGetWalletBalance(self.extend(request, params))
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 697, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/bybit.py", line 2909, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 563, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: bybit {"ret_code":10003,"ret_msg":"invalid api_key","ext_code":"","ext_info":"","result":null,"time_now":"1643232324.67
0083"}

**Comment by kroitor** [comment]
@byoenghoonmoon have you checked your API key in verbose mode?

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

```Python

# ...

rsi14 = myBybit.GetMA(df, 14, -1)

exchange.verbose = True
balance = bybitX.fetch_balance(params={"type": "future"})

pprint(balance)

# ...

```

**Comment by byoenghoonmoon** [comment]
I don't know about verbose mode.

**Comment by kroitor** [comment]
Feel free to reopen this issue or just ask further questions here if any.
