### ISSUE TITLE
Intermittent issue

### ISSUE THREAD

**Issue by birk151** [ccxt/ccxt#11743]
- OS: Win 10
- Programming Language version: 3.10
- CCXT version: 1.65.78

```
Cut Positions: 
Switch Positions: 
Wait 0.08 mins for updated market data. Time: 02:53:51 UTC. [60]/[60]
Top Bulls:
Top Bears:
<<<>>>
Traceback (most recent call last):

  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1273, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1129, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:





Traceback (most recent call last):
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='ftx.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 630, in fetch
    response = self.session.request(
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='ftx.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\christopherburk\Desktop\Python Griffin scripts\Python Griffin scripts\Py3c_triggers.py", line 348, in <module>
    all_open_positions = get_positions()
  File "C:\Users\christopherburk\Desktop\Python Griffin scripts\Python Griffin scripts\Py3c_triggers.py", line 205, in get_positions
    all_positions = ftx.private_get_positions({"showAvgPrice": True})['result']
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 545, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\christopherburk\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 660, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: ftx GET https://ftx.com/api/positions?showAvgPrice=true

**Comment by kroitor** [comment]
Just add a try-catch-retry logic to it. Unfortunately, we can't address connectivity issues between your end and FTX, cause when using CCXT you're talking to the exchange directly. 

See the Manual on error handling: https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Also, check the examples on how to implement a retry logic here: https://github.com/ccxt/ccxt/tree/master/examples

Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.
