### ISSUE TITLE
gateio priceToPrecision is broken

### ISSUE THREAD

**Issue by HartS** [ccxt/ccxt#11755]
- OS: Mac OS Big Sur, and Ubuntu 20.04
- Programming Language version: javascript
- CCXT version: 1.71.46

The price precision info in the market data is a string instead of a number, which breaks the `priceToPrecision` function. In addition, the number (for at least some of these) appears to be wrong. Note that the gateio precisonMode is `TICK_SIZE`; I compared the gateio precision data with bitmex (which also uses `TICK_SIZE`) precision data and found that gateio was using strings, whereas bitmex (which works) was using numbers.

Code for an easy repro and partial fix included in comments (we're using the orderbook data to get a midpoint price)

```
const ccxt = require('ccxt');

const exchangeClient = new ccxt.gateio();
const market = 'ZIL/ETH';

const main = async () => {
  await exchangeClient.loadMarkets();
  const ob = await exchangeClient.fetchOrderBook(market, 100);
  const bestBid = Math.max(...ob.bids.map((b)=>b[0]))
  const bestAsk = Math.max(...ob.asks.map((b)=>b[0]))
  const midpoint = (bestBid + bestAsk)/2;
  console.log(midpoint)
  // uncomment the following line to avoid errors, but the parsed price is still wrong for ZIL/ETH:
  // exchangeClient.markets[market].precision.price = parseFloat(exchangeClient.markets[market].precision.price)
  const preciseMidpoint = exchangeClient.priceToPrecision(market, price);
  console.log('finished', preciseMidpoint);
};

main();
```

error:
```
(node:54759) UnhandledPromiseRejectionWarning: Error: 1e-2: invalid number (contains an illegal character 'e')
    at decimalToPrecision (/private/tmp/npm/node_modules/ccxt/js/base/functions/number.js:191:19)
    at decimalToPrecision (/private/tmp/npm/node_modules/ccxt/js/base/functions/number.js:120:39)
    at gateio.priceToPrecision (/private/tmp/npm/node_modules/ccxt/js/base/Exchange.js:1571:16)
    at main (/private/tmp/npm/test.js:14:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:54759) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:54759) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If the line which resolves the above error is uncommented, the midpoint price is then returned as `0` due to the price precision property of `'1e-2'` for this market, which is too high since the actual trading price is ~ `0.0001005` (at the time of this issue)

**Comment by HartS** [comment]
Works great now, thanks for the quick fix!
