### ISSUE TITLE
ccxt time out after some time for ftx code stops playing orders 

### ISSUE THREAD

**Issue by vensilver** [ccxt/ccxt#11757]
how do I fix his error?

need my code to run 24 /7 in rest api ftx excahnge 

 `socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='ftx.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 587, in fetch
    response = self.session.request(
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='ftx.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "v12.py", line 466, in <module>
    main()
  File "v12.py", line 452, in main
    checkLoop()
  File "v12.py", line 223, in checkLoop
    info = order_info(order_dict[i][0])
  File "v12.py", line 161, in order_info
    info = exchange.fetchOrder(order_id)["info"]
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/ftx.py", line 1403, in fetch_order
    response = getattr(self, method)(self.extend(request, params))
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 506, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 617, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: ftx GET https://ftx.com/api/orders/117671759690
`

**Comment by kroitor** [comment]
Add a try-catch-retry error handling around the code that is failing. See this duplicate issue: https://github.com/ccxt/ccxt/issues/11751
Let us know if that does not help.
