### ISSUE TITLE
error: ['EAPI:Invalid key'] doing fetchBalance for Kraken Futures

### ISSUE THREAD

**Issue by pedruntu** [ccxt/ccxt#11793]
Hi, I'm working with ccxt version 1.62.29 in python, having similar API authentication troubles with different exchanges. In this case, with Kraken, where I'm getting "EAPI:Invalid key". 
I attach my code and output, you'll see that I can succesfully execute some functions like "exchange.fetch_order_book(symbol)" and "exchange.markets[symbol] ['taker']", but when I try to do "exchange.fetch_balance()" or "exchange.fetch_order_book(symbol)" I get "EAPI:Invalid key" . I've already generated a fresh pair of API keys, but I continue getting that error.
Thanks in advance.

```
import sys
import numpy as np
import ccxt


#from sandapi01 import *  #sandbox futures
from config_01 import *  #real futures

print('ccxt version:',ccxt.__version__ )

# from variable id
exchange_id = 'kraken'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
   "apiKey": API[exchange_id],
    "secret": SECRET[exchange_id],
    "password": PASSWORD[exchange_id],
    "adjustForTimeDifference": True,
    "enableRateLimit": True,     
    "options": {
        'defaultType': 'future',
    },
})

print('nombre:', exchange.name)
#exchange.set_sandbox_mode(True) #genera error de autenticación con fetch_balance


markets = exchange.load_markets()
for symbol in exchange.symbols:
    print(symbol,' ',exchange.markets[symbol]['taker'])

exchange.verbose = True  # uncomment for debugging purposes


#balances= exchange.fetch_balance()  #en binance da error cuando sandbox true
#print('Hay USD:',balances['USD'])
#for balance in balances:
#    print( balance)

symbol = 'BTC/USD'
book = exchange.fetch_order_book(symbol)
print('ASK',symbol,book['asks'][0][0])
print('BID',symbol,book['bids'][0][0])
print('Spread (USD):',symbol,book['asks'][0][0]-book['bids'][0][0])
feea= exchange.markets[symbol] ['taker']
print('Fee:', feea)

# Vamos a generar una orden
type = 'market'  # 'limit' or 'market'
side = 'buy'  # 'buy' or 'sell'
amount = 0.01
#price = 0.060154  # or None
price= None
# extra params and overrides if needed

params = {

    #'test': True,  # test if it's valid, but don't actually place it
}

order = exchange.create_order(symbol, type, side, amount, price, params)

print(order['product'])
print(order['size'])
```

```
ccxt version: 1.62.29
nombre: Kraken
1INCH/EUR   0.0026
1INCH/USD   0.0026
AAVE/AUD   0.0026
AAVE/BTC   0.0026
AAVE/ETH   0.0026
AAVE/EUR   0.0026
AAVE/GBP   0.0026
AAVE/USD   0.0026
ACA/EUR   0.0026
ACA/USD   0.0026
ADA/AUD   0.0026
ADA/BTC   0.0026
ADA/ETH   0.0026
ADA/EUR   0.0026
ADA/GBP   0.0026
ADA/USD   0.0026
ADA/USDT   0.0026
ALGO/BTC   0.0026
ALGO/ETH   0.0026
ALGO/EUR   0.0026
ALGO/GBP   0.0026
ALGO/USD   0.0026
ANKR/BTC   0.0026
ANKR/EUR   0.0026
ANKR/GBP   0.0026
ANKR/USD   0.0026
ANT/BTC   0.0026
ANT/ETH   0.0026
ANT/EUR   0.0026
ANT/USD   0.0026
ASTR/EUR   0.0026
ASTR/USD   0.0026
ATLAS/EUR   0.0026
ATLAS/USD   0.0026
ATOM/AUD   0.0026
ATOM/BTC   0.0026
ATOM/ETH   0.0026
ATOM/EUR   0.0026
ATOM/GBP   0.0026
ATOM/USD   0.0026
AUD/JPY   0.002
AUD/USD   0.002
AVAX/EUR   0.0026
AVAX/USD   0.0026
AXS/EUR   0.0026
AXS/USD   0.0026
BADGER/EUR   0.0026
BADGER/USD   0.0026
BAL/BTC   0.0026
BAL/ETH   0.0026
BAL/EUR   0.0026
BAL/USD   0.0026
BAND/EUR   0.0026
BAND/USD   0.0026
BAT/BTC   0.0026
BAT/ETH   0.0026
BAT/EUR   0.0026
BAT/JPY   0.0026
BAT/USD   0.0026
BCH/AUD   0.0026
BCH/BTC   0.0026
BCH/ETH   0.0026
BCH/EUR   0.0026
BCH/GBP   0.0026
BCH/JPY   0.0026
BCH/USD   0.0026
BCH/USDT   0.0026
BNC/EUR   0.0026
BNC/USD   0.0026
BNT/BTC   0.0026
BNT/EUR   0.0026
BNT/GBP   0.0026
BNT/USD   0.0026
BTC/AUD   0.0026
BTC/CAD   0.0026
BTC/CHF   0.0026
BTC/DAI   0.0026
BTC/EUR   0.0026
BTC/GBP   0.0026
BTC/JPY   0.0026
BTC/USD   0.0026
BTC/USDC   0.0026
BTC/USDT   0.0026
CHZ/EUR   0.0026
CHZ/USD   0.0026
COMP/BTC   0.0026
COMP/ETH   0.0026
COMP/EUR   0.0026
COMP/USD   0.0026
CQT/EUR   0.0026
CQT/USD   0.0026
CRV/BTC   0.0026
CRV/ETH   0.0026
CRV/EUR   0.0026
CRV/USD   0.0026
CTSI/EUR   0.0026
CTSI/USD   0.0026
DAI/EUR   0.002
DAI/USD   0.002
DAI/USDT   0.002
DASH/BTC   0.0026
DASH/EUR   0.0026
DASH/USD   0.0026
DOGE/BTC   0.0026
DOGE/EUR   0.0026
DOGE/USD   0.0026
DOGE/USDT   0.0026
DOT/AUD   0.0026
DOT/BTC   0.0026
DOT/ETH   0.0026
DOT/EUR   0.0026
DOT/GBP   0.0026
DOT/USD   0.0026
DOT/USDT   0.0026
DYDX/EUR   0.0026
DYDX/USD   0.0026
ENJ/BTC   0.0026
ENJ/EUR   0.0026
ENJ/GBP   0.0026
ENJ/USD   0.0026
EOS/BTC   0.0026
EOS/ETH   0.0026
EOS/EUR   0.0026
EOS/USD   0.0026
EOS/USDT   0.0026
ETC/BTC   0.0026
ETC/ETH   0.0026
ETC/EUR   0.0026
ETC/USD   0.0026
ETH/AUD   0.0026
ETH/BTC   0.0026
ETH/CAD   0.0026
ETH/CHF   0.0026
ETH/DAI   0.0026
ETH/EUR   0.0026
ETH/GBP   0.0026
ETH/JPY   0.0026
ETH/USD   0.0026
ETH/USDC   0.0026
ETH/USDT   0.0026
ETH2.S/ETH   0.0026
EUR/AUD   0.002
EUR/CAD   0.002
EUR/CHF   0.002
EUR/GBP   0.002
EUR/JPY   0.002
EUR/USD   0.002
EWT/BTC   0.0026
EWT/EUR   0.0026
EWT/GBP   0.0026
EWT/USD   0.0026
FIDA/EUR   0.0026
FIDA/USD   0.0026
FIL/AUD   0.0026
FIL/BTC   0.0026
FIL/ETH   0.0026
FIL/EUR   0.0026
FIL/GBP   0.0026
FIL/USD   0.0026
FLOW/BTC   0.0026
FLOW/ETH   0.0026
FLOW/EUR   0.0026
FLOW/GBP   0.0026
FLOW/USD   0.0026
GBP/USD   0.002
GHST/BTC   0.0026
GHST/EUR   0.0026
GHST/GBP   0.0026
GHST/USD   0.0026
GLMR/EUR   0.0026
GLMR/USD   0.0026
GNO/BTC   0.0026
GNO/ETH   0.0026
GNO/EUR   0.0026
GNO/USD   0.0026
GRT/AUD   0.0026
GRT/BTC   0.0026
GRT/ETH   0.0026
GRT/EUR   0.0026
GRT/GBP   0.0026
GRT/USD   0.0026
ICX/BTC   0.0026
ICX/ETH   0.0026
ICX/EUR   0.0026
ICX/USD   0.0026
INJ/EUR   0.0026
INJ/USD   0.0026
KAR/EUR   0.0026
KAR/USD   0.0026
KAVA/BTC   0.0026
KAVA/ETH   0.0026
KAVA/EUR   0.0026
KAVA/USD   0.0026
KEEP/BTC   0.0026
KEEP/ETH   0.0026
KEEP/EUR   0.0026
KEEP/USD   0.0026
KILT/EUR   0.0026
KILT/USD   0.0026
KIN/EUR   0.0026
KIN/USD   0.0026
KINT/EUR   0.0026
KINT/USD   0.0026
KNC/BTC   0.0026
KNC/ETH   0.0026
KNC/EUR   0.0026
KNC/USD   0.0026
KSM/AUD   0.0026
KSM/BTC   0.0026
KSM/DOT   0.0026
KSM/ETH   0.0026
KSM/EUR   0.0026
KSM/GBP   0.0026
KSM/USD   0.0026
LINK/AUD   0.0026
LINK/BTC   0.0026
LINK/ETH   0.0026
LINK/EUR   0.0026
LINK/GBP   0.0026
LINK/JPY   0.0026
LINK/USD   0.0026
LINK/USDT   0.0026
LPT/BTC   0.0026
LPT/EUR   0.0026
LPT/GBP   0.0026
LPT/USD   0.0026
LRC/EUR   0.0026
LRC/USD   0.0026
LSK/BTC   0.0026
LSK/ETH   0.0026
LSK/EUR   0.0026
LSK/USD   0.0026
LTC/AUD   0.0026
LTC/BTC   0.0026
LTC/ETH   0.0026
LTC/EUR   0.0026
LTC/GBP   0.0026
LTC/JPY   0.0026
LTC/USD   0.0026
LTC/USDT   0.0026
LUNA/EUR   0.0026
LUNA/USD   0.0026
MANA/BTC   0.0026
MANA/ETH   0.0026
MANA/EUR   0.0026
MANA/USD   0.0026
MATIC/BTC   0.0026
MATIC/EUR   0.0026
MATIC/GBP   0.0026
MATIC/USD   0.0026
MINA/BTC   0.0026
MINA/EUR   0.0026
MINA/GBP   0.0026
MINA/USD   0.0026
MIR/EUR   0.0026
MIR/USD   0.0026
MKR/BTC   0.0026
MKR/EUR   0.0026
MKR/GBP   0.0026
MKR/USD   0.0026
MLN/BTC   0.0026
MLN/ETH   0.0026
MLN/EUR   0.0026
MLN/USD   0.0026
MNGO/EUR   0.0026
MNGO/USD   0.0026
MOVR/EUR   0.0026
MOVR/USD   0.0026
NANO/BTC   0.0026
NANO/ETH   0.0026
NANO/EUR   0.0026
NANO/USD   0.0026
OCEAN/BTC   0.0026
OCEAN/EUR   0.0026
OCEAN/GBP   0.0026
OCEAN/USD   0.0026
OGN/EUR   0.0026
OGN/USD   0.0026
OMG/BTC   0.0026
OMG/ETH   0.0026
OMG/EUR   0.0026
OMG/JPY   0.0026
OMG/USD   0.0026
ORCA/EUR   0.0026
ORCA/USD   0.0026
OXT/BTC   0.0026
OXT/ETH   0.0026
OXT/EUR   0.0026
OXT/USD   0.0026
OXY/EUR   0.0026
OXY/USD   0.0026
PAXG/BTC   0.0026
PAXG/ETH   0.0026
PAXG/EUR   0.0026
PAXG/USD   0.0026
PERP/EUR   0.0026
PERP/USD   0.0026
PHA/EUR   0.0026
PHA/USD   0.0026
POLIS/EUR   0.0026
POLIS/USD   0.0026
QTUM/BTC   0.0026
QTUM/ETH   0.0026
QTUM/EUR   0.0026
QTUM/USD   0.0026
RARI/BTC   0.0026
RARI/EUR   0.0026
RARI/GBP   0.0026
RARI/USD   0.0026
RAY/EUR   0.0026
RAY/USD   0.0026
REN/BTC   0.0026
REN/EUR   0.0026
REN/GBP   0.0026
REN/USD   0.0026
REP/BTC   0.0026
REP/ETH   0.0026
REP/EUR   0.0026
REP/USD   0.0026
REPV1/BTC   0.0026
REPV1/ETH   0.0026
REPV1/EUR   0.0026
REPV1/USD   0.0026
SAND/BTC   0.0026
SAND/EUR   0.0026
SAND/GBP   0.0026
SAND/USD   0.0026
SBR/EUR   0.0026
SBR/USD   0.0026
SC/BTC   0.0026
SC/ETH   0.0026
SC/EUR   0.0026
SC/USD   0.0026
SDN/EUR   0.0026
SDN/USD   0.0026
SHIB/EUR   0.0026
SHIB/USD   0.0026
SNX/AUD   0.0026
SNX/BTC   0.0026
SNX/ETH   0.0026
SNX/EUR   0.0026
SNX/GBP   0.0026
SNX/USD   0.0026
SOL/BTC   0.0026
SOL/EUR   0.0026
SOL/GBP   0.0026
SOL/USD   0.0026
SRM/BTC   0.0026
SRM/EUR   0.0026
SRM/GBP   0.0026
SRM/USD   0.0026
STEP/EUR   0.0026
STEP/USD   0.0026
STORJ/BTC   0.0026
STORJ/ETH   0.0026
STORJ/EUR   0.0026
STORJ/USD   0.0026
SUSHI/BTC   0.0026
SUSHI/EUR   0.0026
SUSHI/GBP   0.0026
SUSHI/USD   0.0026
TBTC/BTC   0.0026
TBTC/ETH   0.0026
TBTC/EUR   0.0026
TBTC/USD   0.0026
TRX/BTC   0.0026
TRX/ETH   0.0026
TRX/EUR   0.0026
TRX/USD   0.0026
UNI/BTC   0.0026
UNI/ETH   0.0026
UNI/EUR   0.0026
UNI/USD   0.0026
USD/CAD   0.002
USD/CHF   0.002
USD/JPY   0.002
USDC/AUD   0.002
USDC/EUR   0.002
USDC/GBP   0.002
USDC/USD   0.002
USDC/USDT   0.002
USDT/AUD   0.002
USDT/CAD   0.002
USDT/CHF   0.002
USDT/EUR   0.002
USDT/GBP   0.002
USDT/JPY   0.002
USDT/USD   0.002
WAVES/BTC   0.0026
WAVES/ETH   0.0026
WAVES/EUR   0.0026
WAVES/USD   0.0026
WBTC/BTC   0.0026
WBTC/EUR   0.0026
WBTC/USD   0.0026
XLM/AUD   0.0026
XLM/BTC   0.0026
XLM/EUR   0.0026
XLM/GBP   0.0026
XLM/USD   0.0026
XMR/BTC   0.0026
XMR/EUR   0.0026
XMR/USD   0.0026
XRP/AUD   0.0026
XRP/BTC   0.0026
XRP/CAD   0.0026
XRP/ETH   0.0026
XRP/EUR   0.0026
XRP/GBP   0.0026
XRP/JPY   0.0026
XRP/USD   0.0026
XRP/USDT   0.0026
XTZ/AUD   0.0026
XTZ/BTC   0.0026
XTZ/ETH   0.0026
XTZ/EUR   0.0026
XTZ/GBP   0.0026
XTZ/USD   0.0026
YFI/AUD   0.0026
YFI/BTC   0.0026
YFI/ETH   0.0026
YFI/EUR   0.0026
YFI/GBP   0.0026
YFI/USD   0.0026
ZEC/BTC   0.0026
ZEC/EUR   0.0026
ZEC/USD   0.0026
ZRX/BTC   0.0026
ZRX/EUR   0.0026
ZRX/GBP   0.0026
ZRX/USD   0.0026

Request: GET https://api.kraken.com/0/public/Depth?pair=XXBTZUSD {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.kraken.com/0/public/Depth?pair=XXBTZUSD 200 {'Date': 'Tue, 01 Feb 2022 15:08:48 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'strict-transport-security': 'max-age=15768000', 'cache-control': 'public,max-age=5,smaxage=5', 'content-encoding': 'gzip', 'referrer-policy': 'no-referrer-when-downgrade', 'Last-Modified': 'Tue, 01 Feb 2022 15:08:47 GMT', 'CF-Cache-Status': 'HIT', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Set-Cookie': '__cf_bm=zYmSxhHGDRz1kNBHU6rRZFCw3DPnh.6eW_dAjq8rTEc-1643728128-0-AUDmX9692BKFfZy4qirmygCrVc27eGVk7e+aA2H2YB6i+Ujfndi/pmDCozs798S8KmPfwX/gsUo76c8WKj+xTx4=; path=/; expires=Tue, 01-Feb-22 15:38:48 GMT; domain=.kraken.com; HttpOnly; Secure; SameSite=None', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '6d6c18e34fa0f7e6-EZE'} {"error":[],"result":{"XXBTZUSD":{"asks":[["38338.10000","3.838",1643728127],["38342.00000","0.136",1643728124],["38342.70000","0.144",1643728123],["38342.80000","0.599",1643728120],["38345.10000","0.004",1643728121],["38346.10000","0.770",1643728127],["38346.20000","0.137",1643728123],["38346.30000","6.524",1643728121],["38347.50000","0.367",1643728120],["38348.10000","0.062",1643728125],["38349.10000","0.386",1643728127],["38351.00000","0.100",1643728125],["38351.10000","0.144",1643728126],["38351.20000","0.146",1643728123],["38351.30000","3.997",1643728120],["38353.00000","3.366",1643728125],["38353.30000","0.147",1643728123],["38353.40000","6.523",1643728119],["38354.70000","0.299",1643728109],["38354.80000","0.020",1643728125],["38354.90000","0.136",1643728105],["38355.50000","0.001",1643728057],["38356.00000","0.004",1643728124],["38356.50000","2.125",1643728122],["38357.30000","0.119",1643728121],["38357.40000","0.322",1643728120],["38357.60000","0.004",1643728126],["38358.00000","0.003",1643728079],["38359.30000","0.136",1643728104],["38363.60000","0.001",1643728037],["38364.90000","0.136",1643728097],["38366.50000","0.351",1643728104],["38368.80000","0.136",1643728097],["38370.30000","0.004",1643728104],["38372.70000","0.136",1643728097],["38374.60000","0.040",1643728124],["38376.60000","0.136",1643728097],["38377.20000","0.300",1643728120],["38380.50000","0.136",1643728097],["38384.40000","0.136",1643728097],["38384.90000","0.040",1643728119],["38387.40000","0.028",1643728085],["38388.30000","0.136",1643728097],["38388.70000","0.006",1643728126],["38388.80000","0.995",1643728119],["38389.70000","0.040",1643728089],["38390.00000","0.076",1643728121],["38392.20000","0.136",1643728097],["38394.40000","0.494",1643728093],["38396.10000","0.136",1643728102],["38397.30000","0.657",1643728110],["38397.40000","2.512",1643728079],["38397.60000","0.028",1643728105],["38398.90000","0.055",1643728104],["38401.50000","0.136",1643728104],["38401.60000","1.992",1643728079],["38403.00000","0.079",1643728101],["38403.30000","0.003",1643728099],["38404.80000","0.815",1643728101],["38405.20000","3.778",1643728116],["38405.30000","6.524",1643728047],["38405.40000","0.136",1643728104],["38405.50000","0.001",1643728032],["38410.00000","6.523",1643728119],["38415.40000","0.004",1643728052],["38416.50000","0.101",1643728120],["38419.60000","1.310",1643728102],["38422.60000","0.085",1643728107],["38423.50000","0.812",1643728063],["38423.70000","0.079",1643728061],["38424.10000","0.502",1643728030],["38424.20000","1.259",1643728104],["38426.80000","0.059",1643728114],["38430.00000","0.101",1643728118],["38430.90000","0.003",1643727729],["38433.50000","0.001",1643727704],["38454.40000","0.012",1643728092],["38454.60000","6.528",1643728014],["38454.90000","0.033",1643728127],["38455.00000","17.972",1643728057],["38455.50000","0.001",1643727849],["38456.20000","0.106",1643728019],["38456.70000","0.502",1643728079],["38465.40000","0.131",1643728093],["38465.60000","0.083",1643728080],["38468.40000","0.005",1643727852],["38471.50000","2.755",1643728085],["38472.00000","6.526",1643728016],["38472.60000","1.003",1643728094],["38473.00000","0.886",1643728093],["38476.30000","3.144",1643728084],["38484.60000","0.099",1643728029],["38484.70000","0.500",1643728027],["38484.80000","0.001",1643727624],["38491.70000","0.079",1643728117],["38492.90000","0.011",1643728105],["38493.60000","0.965",1643728073],["38495.10000","6.523",1643728026],["38496.20000","3.142",1643728025],["38497.90000","0.722",1643728035]],"bids":[["38338.00000","0.262",1643728127],["38322.40000","0.653",1643728127],["38320.70000","0.028",1643728121],["38320.40000","0.009",1643728127],["38319.20000","0.007",1643728127],["38319.10000","0.131",1643728118],["38318.50000","0.136",1643728120],["38314.40000","0.136",1643728097],["38314.20000","6.522",1643728124],["38310.60000","0.133",1643728126],["38310.50000","0.787",1643728116],["38307.60000","0.274",1643728125],["38307.50000","6.522",1643728118],["38306.60000","0.136",1643728097],["38305.30000","0.124",1643728123],["38302.70000","0.136",1643728097],["38301.50000","0.770",1643728127],["38301.40000","0.004",1643728120],["38299.70000","0.001",1643728126],["38298.90000","0.116",1643728122],["38298.80000","0.176",1643728113],["38297.60000","0.078",1643728123],["38296.00000","0.692",1643728125],["38295.40000","0.205",1643728121],["38294.90000","0.136",1643728097],["38289.70000","0.300",1643728120],["38289.50000","0.131",1643728091],["38289.00000","0.136",1643728098],["38287.90000","0.080",1643728102],["38285.10000","0.136",1643728098],["38284.40000","0.262",1643728113],["38284.20000","0.300",1643728073],["38283.10000","0.005",1643728126],["38283.00000","1.000",1643728113],["38281.00000","0.020",1643728124],["38279.50000","0.136",1643728113],["38279.30000","0.006",1643728050],["38275.60000","0.136",1643728113],["38275.50000","0.014",1643728114],["38271.70000","0.136",1643728119],["38270.80000","0.056",1643728119],["38269.80000","0.055",1643728098],["38269.20000","0.079",1643728125],["38268.60000","0.028",1643728125],["38265.70000","0.055",1643728119],["38265.60000","0.028",1643728108],["38264.70000","0.027",1643728124],["38263.10000","0.101",1643728120],["38262.80000","0.483",1643728119],["38261.60000","0.006",1643728126],["38261.50000","6.521",1643728118],["38255.50000","0.005",1643728119],["38255.40000","0.774",1643728110],["38255.30000","2.499",1643728104],["38255.00000","0.004",1643728120],["38254.00000","3.600",1643728120],["38253.90000","6.524",1643728090],["38250.90000","0.021",1643728087],["38249.40000","0.316",1643728091],["38248.70000","0.818",1643728033],["38244.10000","0.628",1643728076],["38244.00000","0.080",1643728040],["38239.40000","0.041",1643728124],["38239.30000","17.791",1643728034],["38238.10000","2.019",1643728093],["38236.10000","0.954",1643728079],["38228.60000","2.550",1643728079],["38226.60000","0.496",1643728079],["38217.10000","6.531",1643728011],["38216.50000","2.876",1643728040],["38207.60000","2.000",1643727979],["38205.90000","0.107",1643728040],["38200.90000","3.167",1643728092],["38200.70000","13.108",1643728104],["38199.80000","0.054",1643728124],["38197.30000","6.521",1643728118],["38195.70000","0.270",1643728091],["38193.20000","0.342",1643728032],["38189.30000","0.001",1643727937],["38184.30000","6.537",1643727984],["38183.70000","7.857",1643728029],["38181.90000","0.009",1643728109],["38181.20000","0.002",1643727898],["38176.80000","0.002",1643727822],["38176.60000","0.003",1643727866],["38173.30000","2.214",1643728119],["38172.60000","0.006",1643727963],["38172.50000","0.001",1643727954],["38162.80000","0.500",1643728022],["38162.40000","0.003",1643727962],["38158.70000","0.001",1643727982],["38149.40000","2.881",1643728028],["38149.10000","3.171",1643728028],["38140.50000","2.882",1643728040],["38138.90000","3.172",1643728032],["38138.80000","1.039",1643728072],["38134.70000","0.100",1643727841],["38133.90000","0.001",1643727862],["38132.50000","0.002",1643714213],["38130.50000","0.886",1643728093]]}}}
ASK BTC/USD 38338.1
BID BTC/USD 38338.0
Spread (USD): BTC/USD 0.09999999999854481
Fee: 0.0026

Request: POST https://api.kraken.com/0/private/AddOrder {'API-Key': 'fdMu6RrZIB8gOWpSy4K8s+uTVY6Kg18CjKU1x3a3ENVP+L2XtG+4dKlm', 'API-Sign': 'mSwakHOtf2PFB2A+MLUA+yAnvzm5QSRDPqHagFkECKupjX4CRxMjbq89e6NaqwaLMDuaLmXt9Am+nSaLYG+TYw==', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} nonce=1643728128758&pair=XXBTZUSD&type=buy&ordertype=market&volume=0.01

Response: POST https://api.kraken.com/0/private/AddOrder 200 {'Date': 'Tue, 01 Feb 2022 15:08:49 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'strict-transport-security': 'max-age=15768000', 'expires': '-1', 'cache-control': 'no-cache, private, max-age=0', 'content-encoding': 'gzip', 'referrer-policy': 'no-referrer-when-downgrade', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Set-Cookie': '__cf_bm=c77e8900b5a8e1fefacb568ee1157e6b064070c2-1643728129-0-AbtZLIvU57FvPQWrC6Yjxm4I9D4CW8Eu0wdG8ksXoJVFqt0TGDTaZhuOs3XXto/FXIhOwhBq8LjcFplIT2Ee/MU=; path=/; expires=Tue, 01-Feb-22 15:38:49 GMT; domain=.kraken.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '6d6c18e55c16f7e6-EZE'} {"error":["EAPI:Invalid key"]}
Traceback (most recent call last):
  File "open_trade01.py", line 62, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\kraken.py", line 1105, in create_order
    response = self.privatePostAddOrder(self.extend(request, params))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 459, in inner
    return entry(_self, **inner_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 508, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 504, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 656, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\kraken.py", line 1914, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 522, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: kraken {"error":["EAPI:Invalid key"]}
```

**Comment by pedruntu** [comment]
New information, I changed the API keys again and now its working.
Best regards
