### ISSUE TITLE
ascendex perpetual fetch balance error

### ISSUE THREAD

**Issue by leastchaos** [ccxt/ccxt#11827]
- OS:
- Programming Language version:
- CCXT version: 1.71.96

```
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.ascendex(
    {
        'enableRateLimit': True,
        'apiKey': '',
        'secret': '',
        'options': {
            'defaultType': 'swap'
        }
    }
)
exchange.verbose = True
exchange.fetch_balance()
```

```
fetch Response: ascendex GET https://ascendex.com/2/api/pro/v1/futures/collateral-balance 404 ResponseHeaders: {'Date': 'Thu, 03 Feb 2022 10:46:47 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'instance': '2-_-2', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '6d7b13d34f5d6a1a-SYD', 'Content-Encoding': 'gzip'} ResponseBody: {"code":404,"message":"URL requested was not found","reason":"/2/api/pro/v1/futures/collateral-balance"}
Traceback (most recent call last):
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 658, in fetch
    response.raise_for_status()
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ascendex.com/2/api/pro/v1/futures/collateral-balance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/wc/tracker_v2/test2.py", line 14, in <module>
    exchange.fetch_balance()
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/ascendex.py", line 662, in fetch_balance
    response = getattr(self, method)(self.extend(request, query))
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 551, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 547, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 674, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/ascendex.py", line 2225, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: ascendex {"code":404,"message":"URL requested was not found","reason":"/2/api/pro/v1/futures/collateral-balance"}
(tracker_v2) root@Alibaba-1:~/wc/tracker_v2# /root/miniconda3/envs/tracker_v2/bin/python3.10 /root/wc/tracker_v2/test2.py
Traceback (most recent call last):
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 658, in fetch
    response.raise_for_status()
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ascendex.com/2/api/pro/v1/futures/collateral-balance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/wc/tracker_v2/test2.py", line 20, in <module>
    exchange.fetch_balance()
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/ascendex.py", line 662, in fetch_balance
    response = getattr(self, method)(self.extend(request, query))
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 551, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 547, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/base/exchange.py", line 674, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/miniconda3/envs/tracker_v2/lib/python3.10/site-packages/ccxt/ascendex.py", line 2225, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: ascendex {"code":404,"message":"URL requested was not found","reason":"/2/api/pro/v1/futures/collateral-balance"}

```

[ccxtlog.txt](https://github.com/ccxt/ccxt/files/7993887/ccxtlog.txt)

how do I get the swap balance?

**Comment by Dan-krm** [comment]
It looks like the v1 endpoint we were using to get the swap balance isn't functioning and is probably deprecated. I've submitted a pull request to fix this issue and fetch the swap balance using a v2 alternative endpoint. fetchBalance uses private endpoints that will require your apiKey and secret to be filled out, as well as setting defaultType to swap. Your current approach will work once the PR is merged.
