### ISSUE TITLE
Bybit fetch funding doesnt work for linear contracts (e.g. BTCUSDT)

### ISSUE THREAD

**Issue by lamhochit** [ccxt/ccxt#11861]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows
- Programming Language version: Python 3.9
- CCXT version: Latest

import ccxtpro
import asyncio
import time

exchange = ccxtpro.bybit()

async def main():
    # resp = await exchange.fetch_markets()
    resp = await exchange.fetch_funding_rate('BTC/USDT')
    return resp

x = asyncio.run(main())

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-242af66b527f>", line 1, in <module>
    runfile('C:/Users/lamho/Documents/ats/test/ftx_funding.py', wdir='C:/Users/lamho/Documents/ats/test')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/lamho/Documents/ats/test/ftx_funding.py", line 30, in <module>
    x = asyncio.run(main())
  File "C:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:/Users/lamho/Documents/ats/test/ftx_funding.py", line 27, in main
    resp = await exchange.fetch_funding_rate('BTC/USDT')
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\async_support\bybit.py", line 1238, in fetch_funding_rate
    fundingTime = self.safe_integer(result, 'funding_rate_timestamp') * 1000
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by carlosmiei** [comment]
Hi @lamhochit, 
Thanks for reporting it. I'll analyze and fix it asap.
