### ISSUE TITLE
Okx getBalance causing Cannot convert a BigInt value to a number for npm build

### ISSUE THREAD

**Issue by Brian679** [ccxt/ccxt#11898]
Occurs after running `npm run build` and using OKx to getBalance. Producing the following:

```
  Uncaught (in promise) TypeError: Cannot convert a BigInt value to a number
      at Math.pow (<anonymous>)
      at e.value (2.eb030928.chunk.js:2:58127)
      at Function.value (2.eb030928.chunk.js:2:60075)
      at r.value [as parse_balance] (2.eb030928.chunk.js:2:34003)
      at r.value [as parse_trading_balance] (2.eb030928.chunk.js:2:1264692)
      at r.value [as parse_balance_by_type] (2.eb030928.chunk.js:2:1264145)
      at r.<anonymous> (2.eb030928.chunk.js:2:1265638)
      at d (2.eb030928.chunk.js:2:1571787)
      at Generator._invoke (2.eb030928.chunk.js:2:1571540)
      at Generator.next (2.eb030928.chunk.js:2:1572150)
```

I am working on a browser extension using react, so I run `npm run build` and then load the extension into edge. This error doesn't occur when using `npm start` and also occurs on older versions.

**Comment by kroitor** [comment]
What is your version of CCXT ?

```JavaScript
console.log ('CCXT Version:', ccxt.version)
```

Can you please provide your code and your verbose request and response console log (enable verbose mode) ?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by Brian679** [comment]
In newly created npx create-react-app tester: ccxt version 1.72.55
```
import React from 'react';
import logo from './logo.svg';
import './App.css';
const ccxt = require ('ccxt');

function App() {
  (async () => {
    console.log (ccxt.version);
    let okx = new ccxt.okex ({'proxy': 'http://127.0.0.1:8080/', 'verbose': true});
    // let okx = new ccxt.okex ();
    okx.password = '<pass>';
    okx.apiKey = '<key>';
    okx.secret = '<secret>';
    let okx_balance = await okx.fetchBalance ();
    console.log(okx_balance)
  }) ();

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;

```

Showing error:
```
fetch Request:
 okex GET http://127.0.0.1:8080/https://www.okx.com/api/v5/account/balance 
RequestHeaders:
 {OK-ACCESS-KEY: '<KEY>', OK-ACCESS-PASSPHRASE: '<PASS>', OK-ACCESS-TIMESTAMP: '2022-02-09T04:08:17.669Z', OK-ACCESS-SIGN: '<signature>'} 
RequestBody:
 undefined 

2.b9b53002.chunk.js:1 handleRestResponse:
 okex GET http://127.0.0.1:8080/https://www.okx.com/api/v5/account/balance 200 OK 
ResponseHeaders:
 {Access-Control-Allow-Origin: '*', Cf-Cache-Status: 'DYNAMIC', Cf-Ray: '6daa3c5c090e02be-MIA', Connection: 'close', Content-Encoding: 'gzip', …}Access-Control-Allow-Origin: "*"Cf-Cache-Status: "DYNAMIC"Cf-Ray: "6daa3c5c090e02be-MIA"Connection: "close"Content-Encoding: "gzip"Content-Type: "application/json"Date: "Wed, 09 Feb 2022 04:08:18 GMT"Expect-Ct: "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""Server: "cloudflare"Strict-Transport-Security: "max-age=63072000; includeSubdomains; preload"Transfer-Encoding: "chunked"Vary: "Accept-Encoding"X-Brokerid: "0"X-Final-Url: "https://www.okx.com/api/v5/account/balance"[[Prototype]]: Object 
ResponseBody:
 {"code":"0","data":[{"adjEq":"","details":[{"availBal":"1.83625107157124","availEq":"","cashBal":"1.83625107157124","ccy":"USDT","crossLiab":"","disEq":"1.8378669725142225","eq":"1.83625107157124","eqUsd":"1.8378669725142225","frozenBal":"0","interest":"","isoEq":"","isoLiab":"","isoUpl":"","liab":"","maxLoan":"","mgnRatio":"","notionalLever":"","ordFrozen":"0","stgyEq":"0","twap":"0","uTime":"1642941740038","upl":"","uplLiab":""},{"availBal":"0.0000008312","availEq":"","cashBal":"0.0000008312","ccy":"MINA","crossLiab":"","disEq":"0.00000121563","eq":"0.0000008312","eqUsd":"0.00000243126","frozenBal":"0","interest":"","isoEq":"","isoLiab":"","isoUpl":"","liab":"","maxLoan":"","mgnRatio":"","notionalLever":"","ordFrozen":"0","stgyEq":"0","twap":"0","uTime":"1631399161573","upl":"","uplLiab":""},{"availBal":"0.0000003308","availEq":"","cashBal":"0.0000003308","ccy":"THETA","crossLiab":"","disEq":"0.00000054378558","eq":"0.0000003308","eqUsd":"0.00000108757116","frozenBal":"0","interest":"","isoEq":"","isoLiab":"","isoUpl":"","liab":"","maxLoan":"","mgnRatio":"","notionalLever":"","ordFrozen":"0","stgyEq":"0","twap":"0","uTime":"1631448567041","upl":"","uplLiab":""},{"availBal":"0.000000009","availEq":"","cashBal":"0.000000009","ccy":"SOL","crossLiab":"","disEq":"0.0000009051831","eq":"0.000000009","eqUsd":"0.000001005759","frozenBal":"0","interest":"","isoEq":"","isoLiab":"","isoUpl":"","liab":"","maxLoan":"","mgnRatio":"","notionalLever":"","ordFrozen":"0","stgyEq":"0","twap":"0","uTime":"1642941922331","upl":"","uplLiab":""},{"availBal":"0.0000000026","availEq":"","cashBal":"0.0000000026","ccy":"AVAX","crossLiab":"","disEq":"0.00000020407842","eq":"0.0000000026","eqUsd":"0.0000002267538","frozenBal":"0","interest":"","isoEq":"","isoLiab":"","isoUpl":"","liab":"","maxLoan":"","mgnRatio":"","notionalLever":"","ordFrozen":"0","stgyEq":"0","twap":"0","uTime":"1631448955588","upl":"","uplLiab":""},{"availBal":"0.000000005218","availEq":"","cashBal":"0.000000005218","ccy":"ADA","crossLiab":"","disEq":"0.0000000054384814","eq":"0.000000005218","eqUsd":"0.0000000060427571","frozenBal":"0","interest":"","isoEq":"","isoLiab":"","isoUpl":"","liab":"","maxLoan":"","mgnRatio":"","notionalLever":"","ordFrozen":"0","stgyEq":"0","twap":"0","uTime":"1642941786009","upl":"","uplLiab":""},{"availBal":"0.0000000068","availEq":"","cashBal":"0.0000000068","ccy":"CSPR","crossLiab":"","disEq":"0.00000000031042","eq":"0.0000000068","eqUsd":"0.00000000062084","frozenBal":"0","interest":"","isoEq":"","isoLiab":"","isoUpl":"","liab":"","maxLoan":"","mgnRatio":"","notionalLever":"","ordFrozen":"0","stgyEq":"0","twap":"0","uTime":"1642941858677","upl":"","uplLiab":""}],"imr":"","isoEq":"","mgnRatio":"","mmr":"","notionalUsd":"","ordFroz":"","totalEq":"1.8378717305217795","uTime":"1644379698699"}],"msg":""} 

2.b9b53002.chunk.js:1 
        
       Uncaught (in promise) TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at e.value (2.b9b53002.chunk.js:1:58231)
    at Function.value (2.b9b53002.chunk.js:1:60179)
    at r.value [as safe_balance] (2.b9b53002.chunk.js:1:31720)
    at r.value [as parse_trading_balance] (2.b9b53002.chunk.js:1:753875)
    at r.value [as parse_balance_by_type] (2.b9b53002.chunk.js:1:753328)
    at r.<anonymous> (2.b9b53002.chunk.js:1:755794)
    at d (2.b9b53002.chunk.js:1:921875)
    at Generator._invoke (2.b9b53002.chunk.js:1:921663)
    at Generator.next (2.b9b53002.chunk.js:1:922300)
```
@kroitor

**Comment by kroitor** [comment]
@Brian679 when you use CCXT in a react-app, you have to configure your bundling correctly, so that it would work properly, check these related issues:

- https://github.com/ccxt/ccxt/search?q=react+BigInt&type=issues
- https://github.com/ccxt/ccxt/issues/9786
- https://github.com/ccxt/ccxt/issues/1916
- https://github.com/ccxt/ccxt/search?q=create-react-app&type=issues
- https://github.com/ccxt/ccxt/issues/2955
- https://github.com/ccxt/ccxt/issues/299
- https://github.com/ccxt/ccxt/issues/11054
- https://github.com/ccxt/ccxt/issues/5589
- https://github.com/ccxt/ccxt/issues/9482

Let me know if that does not help.

**Comment by kroitor** [comment]
Do you have this issue if you link against one of these files ?  (they're equivalent)

- https://github.com/ccxt/ccxt/blob/master/dist/ccxt.browser.js
- https://cdn.jsdelivr.net/npm/ccxt@1.72.55/dist/ccxt.browser.js
- https://unpkg.com/ccxt@1.72.55/dist/ccxt.browser.js

**Comment by kroitor** [comment]
It's not really an issue with the CCXT code, it's more like an issue with how `create-react-app` treats JavaScript's operators: https://github.com/facebook/create-react-app/issues/10785

**Comment by Brian679** [comment]
Seems its browser compatibility settings for production. Using the following in package.json resolved it:

```
"browserslist": {
    "production": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

**Comment by jaimindp** [comment]
Having a very similar issue with both exchange.fetchTicker('BTC/USDT') and exchange.createOrder() (binance btw)

It seems to be the same with different exchanges and we're also using an extension. The {browsersList : ..} solution didn't fix it and I've looked at the proposed solutions, none of these work. Would love to get your thoughts on potential fixes!
