### ISSUE TITLE
I can't understand this error message 

### ISSUE THREAD

**Issue by smartbh** [ccxt/ccxt#12068]
Finally I made my trading bot.

I made my PNL/ROE function too.

It worked well but suddenly this bot shut downed.

I don't know why because it worked well till yesterday

I can't understand what error message said.

why ccxt.base.errors.RequestTimeout error has occured?

if i have to paste my whole code, then i will please help.

Why requestTimeout error has occured?

I run this trading bot on Google cloud's compute engine(VM).

Thank you

- OS: linux (google compute engine)
- Programming Language version: python3
- CCXT version:  1.72.74

```
Traceback (most recent call last):
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='fapi.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 633, in fetch
    response = self.session.request(
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='fapi.binance.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dlqudgjs12/binance/binanceFutureApiPer15Test.py", line 170, in <module>
    balance  = binance.fetch_balance(params={"type": "future"})
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1717, in fetch_balance
    response = getattr(self, method)(query)
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 501, in inner
    return entry(_self, **inner_kwargs)
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4952, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 548, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 663, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://fapi.binance.com/fapi/v2/account?timestamp=1645539644266&recvWindow=5000&signature=cd77fe133af02eba9f43c18a5a34592f92dfa18defc4496a1c620c4dea423f5c
```

**Comment by frosty00** [comment]
it means you have bad internet https://docs.python-requests.org/en/latest/api/#requests.ReadTimeout

**Comment by kroitor** [comment]
@smartbh add a try-catch clause for RequestTimeout and handle it as you want (you can handle it by ignoring it and passing on it):

- https://docs.ccxt.com/en/latest/manual.html#error-handling
- https://github.com/ccxt/ccxt/blob/master/examples/py/tickers.py#L117
- https://github.com/ccxt/ccxt/blob/master/examples/py/arbitrage-pairs.py#L93
- https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-fetch-ticker-continuously.py
