### ISSUE TITLE
tiers[symbol] should be tiers['symbol']

### ISSUE THREAD

**Issue by richardjozsa** [ccxt/ccxt#12120]
Hi,

I'm using Freqtrade, and testing the future capabilities with it, what is using CCXT.

When we call this method I got an error, and when I looked through the code there is a problem. That tiers[symbol] should be ['symbol'].
I believe the problem comes from here. Could you please check it? 

`

    if ((market is not None) and market['contract'] and (symbols_length == 0 or symbols.includes(symbol))):
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4588, in fetch_leverage_tiers

    return self.parse_leverage_tiers(response, symbols, 'symbol')

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2787, in parse_leverage_tiers

    if ((market is not None) and market['contract'] and (symbols_length == 0 or symbols.includes(symbol))):

KeyError: 'contract'
`
https://github.com/ccxt/ccxt/blob/1bd6ca5f76abe59dc52c8148f4f4bea3cdd080ae/python/ccxt/base/exchange.py#L2788

**Comment by kroitor** [comment]
@richardjozsa please, paste your code and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by richardjozsa** [comment]
> > 
> 
> What exchange are you using?

Binance- Futures-Isolated

**Comment by samgermain** [comment]
> > @richardjozsa please, paste your code and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
> 
> Will do!

Whats your CCXT version?
Run `pip install ccxt -U` and see if the problem is still there

**Comment by richardjozsa** [comment]
working on the verbose, but here you can see:
`2022-02-26 10:56:43,431 - freqtrade.exchange.exchange - INFO - Using CCXT 1.74.31

2022-02-26 10:56:43,432 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True, 'verify': True}

2022-02-26 10:56:43,443 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}, 'enableRateLimit': True, 'verify': True}

2022-02-26 10:56:43,453 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"

2022-02-26 10:56:46,563 - freqtrade.commands.trade_commands - ERROR - 'contract'

2022-02-26 10:56:46,564 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

Traceback (most recent call last):

  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading

    worker = Worker(args)

  File "/freqtrade/freqtrade/worker.py", line 35, in __init__

    self._init(False)

  File "/freqtrade/freqtrade/worker.py", line 52, in _init

    self.freqtrade = FreqtradeBot(self._config)

  File "/freqtrade/freqtrade/freqtradebot.py", line 66, in __init__

    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)

  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange

    exchange = ExchangeResolver._load_exchange(exchange_name,

  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange

    exchange = ex_class(**kwargs)

  File "/freqtrade/freqtrade/exchange/exchange.py", line 187, in __init__

    self.fill_leverage_tiers()

  File "/freqtrade/freqtrade/exchange/exchange.py", line 1882, in fill_leverage_tiers

    leverage_tiers = self.load_leverage_tiers()

  File "/freqtrade/freqtrade/exchange/common.py", line 130, in wrapper

    return f(*args, **kwargs)

  File "/freqtrade/freqtrade/exchange/binance.py", line 260, in load_leverage_tiers

    return self._api.fetch_leverage_tiers()

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4588, in fetch_leverage_tiers

    return self.parse_leverage_tiers(response, symbols, 'symbol')

  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2787, in parse_leverage_tiers

    if ((market is not None) and market['contract'] and (symbols_length == 0 or symbols.includes(symbol))):

KeyError: 'contract'
`

**Comment by samgermain** [comment]
> 

I can't reproduce the output, how familiar are you with the debugger of whatever IDE/text editor your using?

**Comment by samgermain** [comment]
@richardjozsa 

Do you think you can try going to `.env/lib/python3.9/site-packages/ccxt/base/exchange.py` within freqtrade and adding 
```
print('response')
print(response)
print('symbol')
print(symbol)
print('market')
print(market)
print('id')
print(id)
print('item')
print(item)
print('market_id_key')
print(market_id_key)
``` 


on line `2787` and copying the output to here?

- replace `python3.9` in the path with your python version

**Comment by richardjozsa** [comment]
now I'm trying to give a try for your request! I'm using docker+visual studio code

> @richardjozsa
> 
> Do you think you can try going to `.env/lib/python3.9/site-packages/ccxt/base/exchange.py` within freqtrade and adding
> 
> ```
> print('response')
> print(response)
> print('symbol')
> print(symbol)
> print('market')
> print(market)
> print('id')
> print(id)
> print('item')
> print(item)
> print('market_id_key')
> print(market_id_key)
> ```
> 
> on line `2787` and copying the output to here?
> 
> * replace `python3.9` in the path with your python version

**Comment by richardjozsa** [comment]
I couldn't copy paste it unfortunately v env stops and restarts always.  But you are right tiers[symbol] is okay, but as mentioned in Discord, the contract might not be the part of market.

I used it with live run, with dry run, it won't come up in case of freqtrade, cuz it loads the tiers from the json and doesn't fetch it live from market.

**Comment by xmatthias** [comment]
This is pretty easily recreatable with 1.74.31

``` python
import ccxt
ct = ccxt.binance({'key': '', 'secret: '', 'options': {'defaultType': 'future'}})
_ = ct.loadMarkets()
ct.verbose = True
ct.fetch_leverage_tiers()
```

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_121573/661042562.py in <module>
      1 ct.verbose = True
----> 2 ct.fetch_leverage_tiers()

~/.pyenv/versions/3.9.7/envs/trade_397/lib/python3.9/site-packages/ccxt/binance.py in fetch_leverage_tiers(self, symbols, params)
   4586         #    ]
   4587         #
-> 4588         return self.parse_leverage_tiers(response, symbols, 'symbol')
   4589 
   4590     def parse_market_leverage_tiers(self, info, market):

~/.pyenv/versions/3.9.7/envs/trade_397/lib/python3.9/site-packages/ccxt/base/exchange.py in parse_leverage_tiers(self, response, symbols, market_id_key)
   2785             if (symbols is not None):
   2786                 symbols_length = symbols.length
-> 2787             if ((market is not None) and market['contract'] and (symbols_length == 0 or symbols.includes(symbol))):
   2788                 tiers[symbol] = self.parse_market_leverage_tiers(item, market)
   2789         return tiers

KeyError: 'contract'
```

**Comment by richardjozsa** [comment]
Lovely, thanks! and sorry for the inconvinience, I'm not faimiliar yet with your system :D
