### ISSUE TITLE
Uncaught exceptions in handleOrderBookMessage in latest ccxt.pro

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#12209]
Hi Fellows,
upgraded from 

-- ccxt.pro@1.0.2 (git+ssh://git@github.com/kroitor/ccxt.pro.git#106c68e78ccb5443675954cbee19c6a71b530654)
-- ccxt@1.73.17 deduped
-- ccxt@1.73.17

to
-- ccxt.pro@1.0.21 (git+ssh://git@github.com/kroitor/ccxt.pro.git#1b07839b0239b9749372ce9a2f58544148796b99)
-- ccxt@1.75.13 deduped
-- ccxt@1.75.13

got plenty of Uncaught Exceptions like these:

```
  TypeError: Cannot set properties of undefined (setting '1')
    at Asks.storeArray (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/base/OrderBookSide.js:59:32)
    at Asks.store (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/base/OrderBookSide.js:85:14)
    at okex.handleDelta (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/okex.js:242:18)
    at okex.handleDeltas (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/okex.js:247:18)
    at okex.handleOrderBookMessage (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/okex.js:270:14)
    at okex.handleOrderBook (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/okex.js:376:26)
    at okex.handleMessage (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/okex.js:747:31)
    at WsClient.onMessage (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/base/Client.js:277:14)
    at WebSocket.onMessage (/home/koco/projects/arbitrage/node_modules/ccxt.pro/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:390:28)

TypeError: Cannot set properties of undefined (setting '1')
    at Bids.storeArray (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/base/OrderBookSide.js:59:32)
    at Bids.store (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/base/OrderBookSide.js:85:14)
    at kucoin.handleDelta (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/kucoin.js:424:26)
    at kucoin.handleDeltas (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/kucoin.js:431:18)
    at kucoin.handleOrderBookMessage (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/kucoin.js:474:18)
    at kucoin.handleOrderBook (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/kucoin.js:521:18)
    at kucoin.handleSubject (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/kucoin.js:938:27)
    at kucoin.handleMessage (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/kucoin.js:977:31)
    at WsClient.onMessage (/home/koco/projects/arbitrage/node_modules/ccxt.pro/js/base/Client.js:277:14)
    at WebSocket.onMessage (/home/koco/projects/arbitrage/node_modules/ccxt.pro/node_modules/ws/lib/event-target.js:132:16)

```
Could you please take a look?

Thanks.

**Comment by frosty00** [comment]
by any chance are you modifying the orderbook object?

**Comment by krychla1** [comment]
After digging deep, the limit parameter seems to cause a problem, incorrectly cutting the orderbook
```JavaScript
    const exchange = new ccxtpro[exchangeName](params);       //okex
    //  with
    // 'options': {
    //     'watchOrderBook': {
    //         'depth': 'books' }}
    await exchange.loadMarkets();
    await exchange.watchOrderBook("GODS/USDT",100)
    await exchange.sleep(2000);
    await exchange.watchOrderBook("GODS/USDT",100)
```

Resulting in this in the storeArray function:
![image](https://user-images.githubusercontent.com/33096727/157133382-8a9f2f9c-b786-42c3-8636-e9c6e9d0aa88.png)

I simulated this in the okex exchange, however it occurs on multiple different exchanges.

**Comment by kroitor** [comment]
@krychla1 please, let us know if you have this issue with CCXT Pro 1.0.23+. Thanks for your feedback!

**Comment by frosty00** [comment]
https://github.com/kroitor/ccxt.pro/pull/259
