### ISSUE TITLE
timeframe unit k is not supported

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#12229]
Hi,
The "timeframe" is not working for a kucoin case.

```
        const kucoin = new ccxt.kucoin()

        console.log(kucoin.timeframes)

        try {
            const ohlcvList = await kucoin.fetchOHLCV('MHC/USDT', '1week')
        } catch (err) {
            console.log(err)
        }
```

Result : 

```
{
  '1m': '1min',
  '3m': '3min',
  '5m': '5min',
  '15m': '15min',
  '30m': '30min',
  '1h': '1hour',
  '2h': '2hour',
  '4h': '4hour',
  '6h': '6hour',
  '8h': '8hour',
  '12h': '12hour',
  '1d': '1day',
  '1w': '1week'
}
NotSupported: timeframe unit k is not supported
    at kucoin.parseTimeframe (/node_modules/ccxt/js/base/functions/misc.js:29:15)
    at kucoin.fetchOHLCV (/node_modules/ccxt/js/kucoin.js:943:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  constructor: [class NotSupported extends ExchangeError]
}
```

I'm using ccxt 1.62.84 in TypeScript.

**Comment by kroitor** [comment]
@dawadam first, please, upgrade your version to 1.75+. Second, see the values on the left? `1w` should be used instead for `1week` timeframes.

```JavaScript
        const kucoin = new ccxt.kucoin()

        console.log(kucoin.timeframes)

        try {
            const ohlcvList = await kucoin.fetchOHLCV('MHC/USDT', '1w')
        } catch (err) {
            console.log(err)
        }
```

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

**Comment by dawadam** [comment]
Oops, sorry for this big mistake.
