### ISSUE TITLE
CCXT.pro Issue with Coinbasepro watchOrderBook with limit

### ISSUE THREAD

**Issue by lostless13** [ccxt/ccxt#12227]
- OS: Windows
- Programming Language version: node.js V14.16
- CCXT version: CCXT.pro 1.0.21

Watching coinbasepro orderbook with a limit defined causes an error handling updates from coinbase. This was not an issue in ccxt.pro version 1.0.15.

```
const ccxtpro = require('ccxt.pro');
console.log(ccxtpro.version);

(async () => {
    const exchange = new ccxtpro.coinbasepro()
    const orderbook = await exchange.watchOrderBook('BTC/USD', 25)
    console.log(new Date(), orderbook['asks'][0], orderbook['bids'][0])
}
)()
```

```
Exception has occurred: TypeError: Cannot set property '1' of undefined
  at Bids.storeArray ([c:\Users\sb\Documents\code\scratchPad\node_modules\ccxt.pro\js\base\OrderBookSide.js:59:32]())
    at Bids.store ([c:\Users\sb\Documents\code\scratchPad\node_modules\ccxt.pro\js\base\OrderBookSide.js:85:14]())
    at coinbasepro.handleOrderBook ([c:\Users\sb\Documents\code\scratchPad\node_modules\ccxt.pro\js\coinbasepro.js:650:26]())
    at coinbasepro.handleMessage ([c:\Users\sb\Documents\code\scratchPad\node_modules\ccxt.pro\js\coinbasepro.js:698:27]())
    at WsClient.onMessage ([c:\Users\sb\Documents\code\scratchPad\node_modules\ccxt.pro\js\base\Client.js:277:14]())
    at WebSocket.onMessage ([c:\Users\sb\Documents\code\scratchPad\node_modules\ws\lib\event-target.js:132:16]())
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage ([c:\Users\sb\Documents\code\scratchPad\node_modules\ws\lib\websocket.js:1047:20]())
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage ([c:\Users\sb\Documents\code\scratchPad\node_modules\ws\lib\receiver.js:517:14]())
```

**Comment by frosty00** [comment]
okay, I guess i haven't tested it enough with the limit argument, will try to debug it asap

**Comment by frosty00** [comment]
can confirm this issue arises when using the limit argument to watchOrderBook

**Comment by frosty00** [comment]
#12209

**Comment by kroitor** [comment]
@lostless13 please, let us know if you have this issue with CCXT Pro 1.0.23+. Thanks for your feedback!

**Comment by lostless13** [comment]
@kroitor in my quick test, everything looks good. If any issues arise I'll circle back.

**Comment by lostless13** [comment]
```

**Comment by frosty00** [comment]
https://github.com/kroitor/ccxt.pro/pull/259

**Comment by lostless13** [comment]
I have been receiving the following error intermittently.

This would have been initiated with:
```
    const exchange = new ccxtpro.coinbasepro()
    const orderbook = await exchange.watchOrderBook('BTC/USD:BTC', 25)
```



```
C:\Users\sb\Documents\code\Markets\node_modules\ccxt.pro\js\base\OrderBookSide.js:295
                this.length--
                           ^

RangeError: Invalid array length
    at IndexedBids.storeArray (C:\Users\sb\Documents\code\Markets\node_modules\ccxt.pro\js\base\OrderBookSide.js:295:28)
    at IndexedBids.store (C:\Users\sb\Documents\code\Markets\node_modules\ccxt.pro\js\base\OrderBookSide.js:224:14)
    at bitmex.handleOrderBook (C:\Users\sb\Documents\code\Markets\node_modules\ccxt.pro\js\bitmex.js:1135:26)
    at bitmex.handleMessage (C:\Users\sb\Documents\code\Markets\node_modules\ccxt.pro\js\bitmex.js:1277:31)
    at WsClient.onMessage (C:\Users\sb\Documents\code\Markets\node_modules\ccxt.pro\js\base\Client.js:277:14)
    at WebSocket.onMessage (C:\Users\sb\Documents\code\Markets\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\sb\Documents\code\Markets\node_modules\ws\lib\websocket.js:1047:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\sb\Documents\code\Markets\node_modules\ws\lib\receiver.js:517:14)
```
