### ISSUE TITLE
[binance] [python] fetch_positions broken in latest version

### ISSUE THREAD

**Issue by aidanjbailey** [ccxt/ccxt#12303]
Fatal error when fetching positions from the Binance client.

- OS: MonjaroLinux 21.2.4
- Programming Language version: Python 3.8.2
- CCXT version: 1.75.78
- Exchange: binance
- Problematic Method: fetch_positions()

```
import ccxt
client = ccxt.binance(
            {
                "apiKey": api_key,
                "secret": api_secret,
            }
        )
client.verbose = True
client.fetch_positions()
```

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    client.fetch_positions()
  File "/home/aidanb/Work/temp/venv/lib/python3.8/site-packages/ccxt/binance.py", line 4627, in fetch_positions
    return self.fetch_positions_risk(symbols, params)
  File "/home/aidanb/Work/temp/venv/lib/python3.8/site-packages/ccxt/binance.py", line 4658, in fetch_positions_risk
    self.load_leverage_brackets()
  File "/home/aidanb/Work/temp/venv/lib/python3.8/site-packages/ccxt/binance.py", line 4540, in load_leverage_brackets
    raise NotSupported(self.id + ' loadLeverageBrackets() supports linear and inverse contracts only')
ccxt.base.errors.NotSupported: binance loadLeverageBrackets() supports linear and inverse contracts only
```

**Comment by frosty00** [comment]
you need to set this:

```
binance.options['defaultType'] = 'future'  # usdm contracts

or 

binance.options['defaultType'] = 'delivery'  # coinm contracts
```
---
```
binance.fetch_positions()
```

**Comment by barresoft** [comment]
if you want to view some pair position you can use 

`pprint(exchange.fetch_positions(['SAND/BUSD']))`

This example is for SAND/BUSD pair
