### ISSUE TITLE
[binanceusdm] [python] fetch_positions broken in latest version

### ISSUE THREAD

**Issue by aidanjbailey** [ccxt/ccxt#12304]
Fatal error when fetching positions from the Binance usdm client.

- OS: MonjaroLinux 21.2.4
- Programming Language version: Python 3.8.2
- CCXT version: 1.75.78
- Exchange: binanceusdm
- Problematic Method: fetch_positions()

```
import ccxt
print("CCXT Version:", ccxt.__version__)
client = ccxt.binanceusdm(
            {
                "apiKey": api_key,
                "secret": api_secret,
            }
        )
client.verbose = True
client.fetch_positions()
```

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    client.fetch_positions()
  File "/home/aidanb/Work/temp/venv/lib/python3.8/site-packages/ccxt/binance.py", line 4627, in fetch_positions
    return self.fetch_positions_risk(symbols, params)
  File "/home/aidanb/Work/temp/venv/lib/python3.8/site-packages/ccxt/binance.py", line 4728, in fetch_positions_risk
    parsed = self.parse_position_risk(response[i])
  File "/home/aidanb/Work/temp/venv/lib/python3.8/site-packages/ccxt/binance.py", line 4462, in parse_position_risk
    collateralString = Precise.string_div(Precise.string_mul(leftSide, contractsAbs), '1', quotePrecision)
  File "/home/aidanb/Work/temp/venv/lib/python3.8/site-packages/ccxt/base/precise.py", line 154, in string_div
    return str(Precise(string1).div(string2_precise, precision))
  File "/home/aidanb/Work/temp/venv/lib/python3.8/site-packages/ccxt/base/precise.py", line 40, in div
    distance = precision - self.decimals + other.decimals
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**Comment by kroitor** [comment]
@aidanjbailey thank you for reporting this bug, pushed a fix for it in CCXT 1.75.81 (the new version will arrive in ~20 minutes). Please, let us know if you still have issues with it after upgrading to the new version. Thanks again!

**Comment by aidanjbailey** [comment]
You're most welcome, thanks!

**Comment by frosty00** [comment]
cause of bug https://github.com/ccxt/ccxt/pull/12248
