### ISSUE TITLE
is it just simple Network Error?

### ISSUE THREAD

**Issue by smartbh** [ccxt/ccxt#12375]
the program worked well but

these days it broke often

what should I do?

I run it on server that

google cloud platform's VM

And then If I run it on that server,

My pc network, it doesn't matter on that running program.

because it is running during my computer shudown even thou.

Am I understanding right?

but I don't understand why network error happen

```

```

```
Traceback (most recent call last):               
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen                                                                                           
    httplib_response = self._make_request(       
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request                                                                                     
    six.raise_from(e, None)                                                                        
  File "<string>", line 3, in raise_from                                                                                                                                                               
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request                                                                                     
    httplib_response = conn.getresponse()                                                                                                                                                              
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse                              
    response.begin()                                                                                                                                                                                   
  File "/usr/lib/python3.9/http/client.py", line 307, in begin                                     
    version, status, reason = self._read_status()                                                  
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status                                                                                                                                  
    raise RemoteDisconnected("Remote end closed connection without"                                
http.client.RemoteDisconnected: Remote end closed connection without response                      
                                                 
During handling of the above exception, another exception occurred:                                
                                                                                                   
Traceback (most recent call last):                                                                 
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send                                                                                                   
    resp = conn.urlopen(                                                                                                                                                                               
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen                                                                                           
    retries = retries.increment(                                                                   
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment                                                                                             
    raise six.reraise(type(error), error, _stacktrace)                                             
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise                                                                                             
    raise value.with_traceback(tb)               
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen                                                                                           
    httplib_response = self._make_request(       
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request                                                                                     
    six.raise_from(e, None)                      
  File "<string>", line 3, in raise_from                                                                                                                                                               
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request                                                                                     
    httplib_response = conn.getresponse()                                                                                                                                                              
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse                              
    response.begin()                                                                               
  File "/usr/lib/python3.9/http/client.py", line 307, in begin                                     
    version, status, reason = self._read_status()                                                  
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status                              
    raise RemoteDisconnected("Remote end closed connection without"                                
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))                                                                         
                                                                                                   
During handling of the above exception, another exception occurred:

Traceback (most recent call last):                                                                 
  File "/home/dlqudgjs12/binance/binanceFutureApiPer15Test.py", line 180, in <module>              
    ticker = binance.fetch_ticker(symbol)                                                          
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2043, in fetch_ticker                                                                                               
    response = getattr(self, method)(self.extend(request, params))                                 
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 501, in inner                                                                                                 
    return entry(_self, **inner_kwargs)          
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4952, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)                                                                                                                  
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 548, in fetch2                                                                                                
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])                                                                                                          
  File "/home/dlqudgjs12/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 686, in fetch                                                                                                 
    raise NetworkError(details) from e                                                                                                                                                                 
ccxt.base.errors.NetworkError: binance GET https://fapi.binance.com/fapi/v1/ticker/24hr?symbol=BTCUSDT                                                                                                 
```

**Comment by kroitor** [comment]
Network errors are intermittent, you can catch them and ignore or handle them as documented in the Manual, using the built-in syntax for your programming language: https://github.com/ccxt/ccxt/wiki/Manual#error-handling
See how that is done in the examples: https://github.com/ccxt/ccxt/tree/master/examples/
Hope that answers your question, let us know if not.
