### ISSUE TITLE
Stop order on Deribit placed but ccxt crashes with "Cannot convert mark to a BigInt" error

### ISSUE THREAD

**Issue by tomav** [ccxt/ccxt#12409]
- OS: OSX
- Programming Language version: node v16.10.0
- CCXT version: 1.76.61

```
deribit.createOrder("BTC-PERPETUAL", "stop_market", "sell", 10, 35000, { "trigger_price": 35000, "trigger": "mark_price" })
```

```
> node order.js
/Users/thomas/Documents/Development/docker-tradingview-trader/node_modules/ccxt/js/base/Precise.js:19
            this.integer = BigInt (integerString)
                           ^

SyntaxError: Cannot convert mark to a BigInt
    at BigInt (<anonymous>)
    at new Precise (/Users/thomas/Documents/Development/docker-tradingview-trader/node_modules/ccxt/js/base/Precise.js:19:28)
    at Function.stringEquals (/Users/thomas/Documents/Development/docker-tradingview-trader/node_modules/ccxt/js/base/Precise.js:230:17)
    at deribit.safeOrder (/Users/thomas/Documents/Development/docker-tradingview-trader/node_modules/ccxt/js/base/Exchange.js:2071:61)
    at deribit.parseOrder (/Users/thomas/Documents/Development/docker-tradingview-trader/node_modules/ccxt/js/deribit.js:1176:21)
    at deribit.createOrder (/Users/thomas/Documents/Development/docker-tradingview-trader/node_modules/ccxt/js/deribit.js:1341:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
On top of the unexpected crash, can someone tell me:
- Is this the right way to set a stop order?
- How can I add a reduce only arg in params?

Thanks.

**Comment by tomav** [comment]
Found answers:

```
const emptyPrice = (price === undefined) || Precise.stringEquals (price, '0');
```

This fails for market orders for "Precise.stringEquals" method because `price` is set to `market_price`.
I would add this check, but looking for a better idea:

```
const emptyPrice = (price === "market_price") || (price === undefined) || Precise.stringEquals (price, '0');
```

This is the way I set the order (including reduce only):

```
deribit.createOrder("BTC-PERPETUAL", "stop_market", "sell", 10, null, { "trigger_price": 30000, "trigger": "mark_price", "reduce_only": true })
```

**Comment by tomav** [comment]
Pushed it that way, let me know what you think. Thanks!
