### ISSUE TITLE
Cannot import ccxtpro: exchange "equos" is missing from ccxt.async_support

### ISSUE THREAD

**Issue by quirkion** [ccxt/ccxt#12414]
- OS: macOS High Sierra 10.13.6
- Programming Language version: python3.9
- CCXT version: 1.76.64
- CCXT Pro version: 1.0.32

```
import ccxtpro
```

```
Traceback (most recent call last):
  File "/path/to/project/scratch.py", line 1, in <module>
    import ccxtpro
  File "/path/to/project/ccxtpro/__init__.py", line 103, in <module>
    from ccxt.async_support.equos import equos                                # noqa: F401
ModuleNotFoundError: No module named 'ccxt.async_support.equos'
```

Commenting the line
```
from ccxt.async_support.equos import equos                                # noqa: F401
```
in `ccxtpro.__init__.py` solves the issue.

**Comment by quirkion** [comment]
Looks like `equos.io` exchange has moved to `eqonex.com`:
https://github.com/ccxt/ccxt/pull/9415

Probably we can just delete the offending line or make an alias for the former exchange name.

**Comment by quirkion** [comment]
Version 1.0.33 works, thanks!
