### ISSUE TITLE
MEXC Swap, Error Code: 7002

### ISSUE THREAD

**Issue by fahad-here** [ccxt/ccxt#12458]
When trying to create a swap order on MEXC Global exchange, I'm facing an issue where im getting this error code: 7002, with the message "Position mode mis match"

```
const exchange = new ccxt['mexc']({
  apiKey,
  secret,
});
exchange.options.defaultType = 'swap';
await exchange.createOrder('XRP_USDT', 5, 3, 10, undefined, {
openType: 1, leverage: 15,
})
```

This is Error Output
```
{"success":false,"code":7002,"message":"Position mode mis match"} {"name":"ExchangeError","stack":"ExchangeError: mexc {\"success\":false,\"code\":7002,\"message\":\"Position mode mis match\"}\n    at mexc.handleErrors (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\mexc.js:2316:19)\n    at C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\base\\Exchange.js:716:51\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async timeout (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\base\\functions\\time.js:203:20)\n    at async mexc.createSwapOrder (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\mexc.js:1820:26)\n    at async mexc.createOrder (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\mexc.js:1721:20)\n    at async placeOrder (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\src\\services\\exchange.service.js:121:19)\n    at async Trader.buy (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\src\\services\\scraper.service.js:218:27)","timestamp":"2022-03-23 23:56:23"}
```

This is Verbose output
```
fetch Request:
 mexc POST https://contract.mexc.com/api/v1/private/order/submit
RequestHeaders:
 {
  ApiKey: 'apiKey',
  'Request-Time': '1648065383488',
  'Content-Type': 'application/json',
  Signature: 'signature'
}
RequestBody:
 {"symbol":"XRP_USDT","vol":10,"side":3,"type":5,"openType":1,"leverage":15}

handleRestResponse:
 mexc POST https://contract.mexc.com/api/v1/private/order/submit 200 OK
ResponseHeaders:
 {
  'Cache-Control': 'max-age=0, no-cache, no-store',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Length': '88',
  'Content-Type': 'application/json',
  Date: 'Wed, 23 Mar 2022 19:56:23 GMT',
  Expires: 'Wed, 23 Mar 2022 19:56:23 GMT',
  Pragma: 'no-cache',
  'Server-Timing': 'cdn-cache; desc=MISS, edge; dur=296, origin; dur=37',
  Vary: 'Accept-Encoding'
}
ResponseBody:
 {"success":false,"code":7002,"message":"Position mode mis match"}

```

Could you please help out with this bug?

**Comment by Dan-krm** [comment]
> Could you please help out with this bug?

I've opened a PR that should fix the issue you're having with createOrder. For mexc you can also call createSwapOrder directly instead of createOrder and it should work properly in the meantime.

**Comment by fahad-here** [comment]
Hi, I have already tried to call the createSwapOrder directly, it gives me the same result. Under the hood it looks like the createOrder calls the createSwapOrder function when the mode is set to swap.

```
    async createOrder (symbol, type, side, amount, price = undefined, params = {}) {
        await this.loadMarkets ();
        const market = this.market (symbol);
        if (market['spot']) {
            return await this.createSpotOrder (symbol, type, side, amount, price, params);
        } else if (market['swap']) {
            return await this.createSwapOrder (symbol, type, side, amount, price, params);
        }
    }
```

**Comment by kroitor** [comment]
@fahad-here hi! Make sure your CCXT version is up to date (1.77+). Please, paste your versions, enable the verbose mode and also paste your verbose request and verbose response: 

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```JavaScript
console.log ('CCXT Version:', ccxt.version)
const exchange = new ccxt['mexc']({
  apiKey,
  secret,
});
exchange.options.defaultType = 'swap';
await exchange.loadMarkets()
exchange.verbose = true
await exchange.createOrder('XRP_USDT', 5, 3, 10, undefined, {
openType: 1, leverage: 15,
})
```

**Comment by fahad-here** [comment]
Hey, I've faced this issue even after updating to the latest version of ccxt.

Here is the output

```
CCXT Version: 1.77.2
fetch Request:
 mexc POST https://contract.mexc.com/api/v1/private/order/submit
RequestHeaders:
 {
  ApiKey: 'apikey',
  'Request-Time': '1648121575867',
  'Content-Type': 'application/json',
  Signature: 'signature'
}
RequestBody:
 {"symbol":"XRP_USDT","vol":10,"side":3,"type":5,"openType":1,"leverage":15}

handleRestResponse:
 mexc POST https://contract.mexc.com/api/v1/private/order/submit 200 OK

ResponseHeaders:
 {
  'Cache-Control': 'max-age=0, no-cache, no-store',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Length': '88',
  'Content-Type': 'application/json',
  Date: 'Thu, 24 Mar 2022 11:32:56 GMT',
  Expires: 'Thu, 24 Mar 2022 11:32:56 GMT',
  Pragma: 'no-cache',
  'Server-Timing': 'cdn-cache; desc=MISS, edge; dur=322, origin; dur=26',
  Vary: 'Accept-Encoding'
}
ResponseBody:
 {"success":false,"code":7002,"message":"Position mode mis match"}
```

These are the error details
```
error: mexc {"success":false,"code":7002,"message":"Position mode mis match"} {"name":"ExchangeError","stack":"ExchangeError: mexc {\"success\":false,\"code\":7002,\"message\":\"Position mode mis match\"}\n    at mexc.handleErrors (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\mexc.js:2335:19)\n    at C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\base\\Exchange.js:716:51\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async timeout (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\base\\functions\\time.js:203:20)\n    at async mexc.createSwapOrder (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\mexc.js:1835:26)\n    at async mexc.createOrder (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\node_modules\\ccxt\\js\\mexc.js:1722:20)\n    at async placeOrder (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\src\\services\\exchange.service.js:122:19)\n    at async Trader.buy (C:\\Users\\fahad.Hussain\\VS Code Projects\\binance-scraper-bot\\backend\\src\\services\\scraper.service.js:218:27)","timestamp":"2022-03-24 15:32:56"}
```

**Comment by Dan-krm** [comment]
> Hi, I have already tried to call the createSwapOrder directly, it gives me the same result. Under the hood it looks like the createOrder calls the createSwapOrder function when the mode is set to swap.

This implementation of createOrder that you pasted has been adjusted because it wasn't working properly for swap orders. It should look like this:
```
    async createOrder (symbol, type, side, amount, price = undefined, params = {}) {
        await this.loadMarkets ();
        const market = this.market (symbol);
        const [ marketType, query ] = this.handleMarketTypeAndParams ('createOrder', market, params);
        if (marketType === 'spot') {
            return await this.createSpotOrder (symbol, type, side, amount, price, query);
        } else if (marketType === 'swap') {
            return await this.createSwapOrder (symbol, type, side, amount, price, query);
        }
    }
```

'Position Mode Mismatch' makes me think it's something to do with setting your margin mode on mexc or in your program isolated vs. cross or linear vs. inverse. Or maybe having other positions open on the same trading pair might be causing some issues. 'Position Mode Mismatch' kind of sounds like having a cross margin position open while trying to open an isolated position or opening a long and a short at the same time or something like that, I'm not sure if that's allowed on mexc.

Maybe setting this could help:
exchange.options.defaultSubType = 'linear';
or
exchange.options.defaultMarginType = 'isolated';

It's difficult to say what the issue is because I tried recreating your error and it's working properly for me:
```
node examples/js/cli mexc createOrder XRP_USDT 5 3 1 undefined '{"openType":"1","leverage":"10"}' --verbose
2022-03-24T23:43:28.307Z
Node.js: v16.9.1
CCXT v1.77.10
mexc.createOrder (XRP_USDT, 5, 3, 1, , [object Object])
fetch Request:
 mexc POST https://contract.mexc.com/api/v1/private/order/submit
RequestHeaders:
 {
  ApiKey: 'apiKey',
  'Request-Time': '1648165409746',
  'Content-Type': 'application/json',
  Signature: 'signature'
}
RequestBody:
 {"symbol":"XRP_USDT","vol":1,"side":3,"type":5,"openType":"1","leverage":"10"}

handleRestResponse:
 mexc POST https://contract.mexc.com/api/v1/private/order/submit 200 OK
ResponseHeaders:
 {
  'Cache-Control': 'max-age=0, no-cache, no-store',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Length': '77',
  'Content-Type': 'application/json',
  Date: 'Thu, 24 Mar 2022 23:43:30 GMT',
  Expires: 'Thu, 24 Mar 2022 23:43:30 GMT',
  Pragma: 'no-cache',
  'Server-Timing': 'cdn-cache; desc=MISS, edge; dur=101, origin; dur=44',
  Vary: 'Accept-Encoding'
}
ResponseBody:
 {"success":true,"code":0,"data":263168593711507967}

2022-03-24T23:43:29.959Z iteration 0 passed in 316 ms

{
  id: '263168593711507967',
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  status: undefined,
  symbol: 'XRP/USDT:USDT',
  type: undefined,
  timeInForce: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  average: undefined,
  amount: undefined,
  cost: undefined,
  filled: undefined,
  remaining: undefined,
  fee: undefined,
  trades: [],
  info: { success: true, code: '0', data: '263168593711507967' },
  fees: []
}
```

**Comment by fahad-here** [comment]
Hey @Dan-krm, thanks for the heads up. But it looks like it was due to the position mode on MEXC Global itself.

![image](https://user-images.githubusercontent.com/49499280/160557852-35091852-d140-4baf-a8d0-8976f32ebd5a.png)

As you can see in the picture attached. When selecting the 'One-way Mode' it was giving me the position mismatch error. 
When I switched to the Hedged mode, it all worked smoothly.
