### ISSUE TITLE
Uncaught ccxt\RequestTimeout

### ISSUE THREAD

**Issue by TomAshley303** [ccxt/ccxt#1245]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubuntu 16.04
- Programming Language version: PHP 7.0
- CCXT version: 1.10.1 2017-11-06
- Exchange: BINANCE
- Method: fetch_ticker()

Simple `fetch_ticker` requests do this as what seems like (But of course probably isn't) random:

```
PHP Fatal error:  Uncaught ccxt\RequestTimeout: binance GET https://api.binance.com/api/v1/ticker/24hr?symbol=ETHBTC 28 Operation timed out after 10001 milliseconds with 0 bytes received in /var/www/clients/client1/web1/web/includes/ccxt/php/Exchange.php:682
Stack trace:
#0 /var/www/clients/client1/web1/web/includes/ccxt/php/Exchange.php(840): ccxt\Exchange->raise_error('RequestTimeout', 'https://api.bin...', 'GET', 28, 'Operation timed...')
#1 /var/www/clients/client1/web1/web/includes/ccxt/php/Exchange.php(703): ccxt\Exchange->fetch('https://api.bin...', 'GET', Array, NULL)
#2 /var/www/clients/client1/web1/web/includes/ccxt/php/Exchange.php(707): ccxt\Exchange->fetch2('ticker/24hr', 'public', 'GET', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('ticker/24hr', 'public', 'GET', Array)
#4 /var/www/clients/client1/web1/web/includes/ccxt/php/Exchange.php(646): call_user_func(Array, 'ticker/24hr', 'public', 'GET', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#6 /var/www/clients/client1/we in /var/www/clients/client1/web1/web/includes/ccxt/php/Exchange.php on line 682
```

Code is like this:

```
$binance = new \ccxt\binance (array (
    'apiKey' => 'fZ8...', // ←------------ replace with your keys
    'secret' => 'CoC...',
    'verbose' => false,
));

while(1){
  $binanceTicker = $binance->fetch_ticker('BTG/BTC');
  $lastPrice = $binanceTicker['last'];
  echo $lastPrice;
  usleep($binance->rateLimit * 1000);
  $binanceTicker = $binance->fetch_ticker('ETH/BTC');
  $lastPrice = $binanceTicker['last'];
  echo $lastPrice;
  usleep($binance->rateLimit * 1000);
}
```

**Comment by TomAshley303** [comment]
Updated with codes.

**Comment by TomAshley303** [comment]
Updated code to show that I'm using `fetch_ticker()` multiple times in a loop similar to as shown.

**Comment by kroitor** [comment]
1. Increase the `$binance->timeout`
2. Add exception handling: https://github.com/kroitor/ccxt/wiki/Manual#error-handling
3. Try a public CORS proxy, `$binance->proxy = 'https://cors-anywhere.herokuapp.com/'`
4. Try setting `$binance->userAgent = 'YOUR_STRING'` to see if it makes a difference

```PHP
$binance = new \ccxt\binance (array (
    'apiKey' => 'fZ8...', // ←------------ replace with your keys
    'secret' => 'CoC...',
    'verbose' => false,

    //------------------------------------------------------------
    // enable these lines one by one to catch the difference
    // 'timeout' => 20000,
    // 'proxy' => 'https://cors-anywhere.herokuapp.com/',
    // 'userAgent' => 'foobar',
    //------------------------------------------------------------
));

while(1){
  $binanceTicker = $binance->fetch_ticker('BTG/BTC');
  $lastPrice = $binanceTicker['last'];
  echo $lastPrice;
  usleep($binance->rateLimit * 1000);
}
```

**Comment by kroitor** [comment]
I hope the above answer helps you debug it, closing it for now, if you don't mind, feel free to reopen if needed, or just ask questions, if any. Thx!

**Comment by stephensilber** [comment]
I have also seen the Gemini API time out even though the request technically succeeds on the Gemini side of things. For example, we will call withdraw via a Gemini API call, and our response looks like this even though the withdraw is completed:

```
gemini POST https://api.gemini.com/v1/withdraw/ETH request timeout
```

It seems like our issues could be related?
