### ISSUE TITLE
Coinbase Pro fetch_positions

### ISSUE THREAD

**Issue by rajeshaddison** [ccxt/ccxt#12514]
Hi,

I know that fetch_positions is not supported in Coinbase Pro. Is there any hack to get the current open position of a crypto and its average entry price.

I had looked into the all the examples and but didn't get any concrete idea. My strategy is to scale-in position when price goes down and sell it with 0.012% profit. I have the whole code block working till buying. For scale-in I need to get the current position and average entry price for the crypto to determine the correct price. 

Please guide me.

**Comment by kroitor** [comment]
Have you checked the implicit API?

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api
- https://docs.cloud.coinbase.com/exchange/docs/welcome

```
~/ccxt $ node examples/js/cli coinbasepro | grep private
  privateKey: undefined,
  private_key: undefined,
    privateAPI: true,
      private: 'https://api.{hostname}'
      private: 'https://api-public.sandbox.pro.coinbase.com'
    private: { get: [Array], post: [Array], delete: [Array] }
    privateKey: false,
  privateGetAccounts: [AsyncFunction: partial],
  private_get_accounts: [AsyncFunction: partial],
  privateGetAccountsId: [AsyncFunction: partial],
  private_get_accounts_id: [AsyncFunction: partial],
  privateGetAccountsIdHolds: [AsyncFunction: partial],
  private_get_accounts_id_holds: [AsyncFunction: partial],
  privateGetAccountsIdLedger: [AsyncFunction: partial],
  private_get_accounts_id_ledger: [AsyncFunction: partial],
  privateGetAccountsIdTransfers: [AsyncFunction: partial],
  private_get_accounts_id_transfers: [AsyncFunction: partial],
  privateGetCoinbaseAccounts: [AsyncFunction: partial],
  private_get_coinbase_accounts: [AsyncFunction: partial],
  privateGetFills: [AsyncFunction: partial],
  private_get_fills: [AsyncFunction: partial],
  privateGetFunding: [AsyncFunction: partial],
  private_get_funding: [AsyncFunction: partial],
  privateGetFees: [AsyncFunction: partial],
  private_get_fees: [AsyncFunction: partial],
  privateGetMarginProfileInformation: [AsyncFunction: partial],
  private_get_margin_profile_information: [AsyncFunction: partial],
  privateGetMarginBuyingPower: [AsyncFunction: partial],
  private_get_margin_buying_power: [AsyncFunction: partial],
  privateGetMarginWithdrawalPower: [AsyncFunction: partial],
  private_get_margin_withdrawal_power: [AsyncFunction: partial],
  privateGetMarginWithdrawalPowerAll: [AsyncFunction: partial],
  private_get_margin_withdrawal_power_all: [AsyncFunction: partial],
  privateGetMarginExitPlan: [AsyncFunction: partial],
  private_get_margin_exit_plan: [AsyncFunction: partial],
  privateGetMarginLiquidationHistory: [AsyncFunction: partial],
  private_get_margin_liquidation_history: [AsyncFunction: partial],
  privateGetMarginPositionRefreshAmounts: [AsyncFunction: partial],
  private_get_margin_position_refresh_amounts: [AsyncFunction: partial],
  privateGetMarginStatus: [AsyncFunction: partial],
  private_get_margin_status: [AsyncFunction: partial],
  privateGetOracle: [AsyncFunction: partial],
  private_get_oracle: [AsyncFunction: partial],
  privateGetOrders: [AsyncFunction: partial],
  private_get_orders: [AsyncFunction: partial],
  privateGetOrdersId: [AsyncFunction: partial],
  private_get_orders_id: [AsyncFunction: partial],
  privateGetOrdersClientClientOid: [AsyncFunction: partial],
  private_get_orders_client_client_oid: [AsyncFunction: partial],
  privateGetOtcOrders: [AsyncFunction: partial],
  private_get_otc_orders: [AsyncFunction: partial],
  privateGetPaymentMethods: [AsyncFunction: partial],
  private_get_payment_methods: [AsyncFunction: partial],
  privateGetPosition: [AsyncFunction: partial],
  private_get_position: [AsyncFunction: partial],
  privateGetProfiles: [AsyncFunction: partial],
  private_get_profiles: [AsyncFunction: partial],
  privateGetProfilesId: [AsyncFunction: partial],
  private_get_profiles_id: [AsyncFunction: partial],
  privateGetReportsReportId: [AsyncFunction: partial],
  private_get_reports_report_id: [AsyncFunction: partial],
  privateGetTransfers: [AsyncFunction: partial],
  private_get_transfers: [AsyncFunction: partial],
  privateGetTransfersTransferId: [AsyncFunction: partial],
  private_get_transfers_transfer_id: [AsyncFunction: partial],
  privateGetUsersSelfExchangeLimits: [AsyncFunction: partial],
  private_get_users_self_exchange_limits: [AsyncFunction: partial],
  privateGetUsersSelfHoldBalances: [AsyncFunction: partial],
  private_get_users_self_hold_balances: [AsyncFunction: partial],
  privateGetUsersSelfTrailingVolume: [AsyncFunction: partial],
  private_get_users_self_trailing_volume: [AsyncFunction: partial],
  privateGetWithdrawalsFeeEstimate: [AsyncFunction: partial],
  private_get_withdrawals_fee_estimate: [AsyncFunction: partial],
  privatePostConversions: [AsyncFunction: partial],
  private_post_conversions: [AsyncFunction: partial],
  privatePostDepositsCoinbaseAccount: [AsyncFunction: partial],
  private_post_deposits_coinbase_account: [AsyncFunction: partial],
  privatePostDepositsPaymentMethod: [AsyncFunction: partial],
  private_post_deposits_payment_method: [AsyncFunction: partial],
  privatePostCoinbaseAccountsIdAddresses: [AsyncFunction: partial],
  private_post_coinbase_accounts_id_addresses: [AsyncFunction: partial],
  privatePostFundingRepay: [AsyncFunction: partial],
  private_post_funding_repay: [AsyncFunction: partial],
  privatePostOrders: [AsyncFunction: partial],
  private_post_orders: [AsyncFunction: partial],
  privatePostPositionClose: [AsyncFunction: partial],
  private_post_position_close: [AsyncFunction: partial],
  privatePostProfilesMarginTransfer: [AsyncFunction: partial],
  private_post_profiles_margin_transfer: [AsyncFunction: partial],
  privatePostProfilesTransfer: [AsyncFunction: partial],
  private_post_profiles_transfer: [AsyncFunction: partial],
  privatePostReports: [AsyncFunction: partial],
  private_post_reports: [AsyncFunction: partial],
  privatePostWithdrawalsCoinbase: [AsyncFunction: partial],
  private_post_withdrawals_coinbase: [AsyncFunction: partial],
  privatePostWithdrawalsCoinbaseAccount: [AsyncFunction: partial],
  private_post_withdrawals_coinbase_account: [AsyncFunction: partial],
  privatePostWithdrawalsCrypto: [AsyncFunction: partial],
  private_post_withdrawals_crypto: [AsyncFunction: partial],
  privatePostWithdrawalsPaymentMethod: [AsyncFunction: partial],
  private_post_withdrawals_payment_method: [AsyncFunction: partial],
  privateDeleteOrders: [AsyncFunction: partial],
  private_delete_orders: [AsyncFunction: partial],
  privateDeleteOrdersClientClientOid: [AsyncFunction: partial],
  private_delete_orders_client_client_oid: [AsyncFunction: partial],
  privateDeleteOrdersId: [AsyncFunction: partial],
  private_delete_orders_id: [AsyncFunction: partial],
```

**Comment by rajeshaddison** [comment]
Hi, Thanks for the info. I used privateGetPosition and got the following error:

Error
2022-04-04T11:37:46.635Zbuycryptosandbox62mqznnsqzaa Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/base/exchange.py", line 647, in fetch response.raise_for_status() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.pro.coinbase.com/position?symbol=FET%2FUSD
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/base/exchange.py", line 647, in fetch response.raise_for_status() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.pro.coinbase.com/position?symbol=FET%2FUSD

Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 99, in view_func return function(request._get_current_object()) File "/workspace/main.py", line 16, in trade_crypto get_position = coinbase.privateGetPosition({'symbol': data['ticker']}) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/base/exchange.py", line 489, in inner return entry(_self, **inner_kwargs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/coinbasepro.py", line 1353, in request response = self.fetch2(path, api, method, params, headers, body, config, context) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/base/exchange.py", line 536, in fetch2 return self.fetch(request['url'], request['method'], request['headers'], request['body']) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/base/exchange.py", line 663, in fetch skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/coinbasepro.py", line 1349, in handle_errors raise ExchangeError(feedback) # unknown message ccxt.base.errors.ExchangeError: coinbasepro Route not found


The below is the source code

`import ccxt, time
import config

coinbase = ccxt.coinbasepro({
  'apiKey': config.API_KEY,
  'secret': config.API_SECRET,
  'password': config.PASSPHRASE
})

def trade_crypto(request):
  data = request.get_json()

  ticker_data = coinbase.fetch_ticker(data['ticker'])
  ticker_size = int(data['ticker_size'])
  balance_data = coinbase.fetch_balance()
  get_position = coinbase.privateGetPosition({'symbol': data['ticker']})
  size_float = (balance_data['free']['USD'] - (balance_data['free']['USD'] * 0.05))/ticker_data['close']
  size = int(size_float)
  print("ticker_size:", ticker_size, " symbol:", data['ticker'], " size:", size, " balance_data:", balance_data['free']['USD'], " ticker_data:", ticker_data['close'])

  if get_position is not None:
    return get_position

  return "Nothing"`
