### ISSUE TITLE
Is it possible to support bitbankcc？ - https://bitbank.cc/app/trade

### ISSUE THREAD

**Issue by zlq4863947** [ccxt/ccxt#1252]
api: https://docs.bitbank.cc/

**Comment by Deathamns** [comment]
Anyone working on this?

**Comment by kroitor** [comment]
@Deathamns not yet ))

**Comment by dttung-mario** [comment]
Hope we get this done soon

**Comment by tuyet130953** [comment]
Is there an approximate timeframe for release? Appreciate the hard work and I believe there are many eager users who are itching to get connected to this exchange.

**Comment by kroitor** [comment]
@tuyet130953 will merge for testing in a couple of days

**Comment by holim** [comment]
@kroitor sounds great, looking forward to getting bitbank to work with ccxt

**Comment by k31ww475** [comment]
Hi I can't sell and buy order using bitbank.
the command line is follow
`exchange.create_limit_sell_order('BTC/JPY', 0.001, 1000000)`

the error occured like that 
`OSError: [Errno 22] Invalid argument`

detail
```
Traceback (most recent call last):
  File "C:/pythonfiles//pr2.py", line 80, in <module>
    exchange.create_limit_sell_order(target_currency, amount, bid_price)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 1258, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitbank.py", line 312, in create_order
    order = self.parse_order(response['data'], market)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitbank.py", line 281, in parse_order
    'datetime': self.iso8601(timestamp),
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 669, in iso8601
    utc = datetime.datetime.utcfromtimestamp(int(round(timestamp / 1000)))
OSError: [Errno 22] Invalid argument

Process finished with exit code 1
```

**Comment by kroitor** [comment]
@k31ww475 hi, can you post you verbose output as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue (without yout keys) ?

**Comment by k31ww475** [comment]
What do you mean by?you mean should I post new issue as bitbank on github?

**Comment by kroitor** [comment]
@k31ww475 no, i mean follow the link that i posted and read the text there very carefully ) It tells how to post your output here properly in order for us to be able to help you. You can post your verbose output in this issue, or as a new issue, whatever you like.

**Comment by k31ww475** [comment]
Thanx lots.ok.guy.I read the link and posted as new issue like that.
https://github.com/ccxt/ccxt/issues/2775



2018-05-07 15:51 GMT+09:00 Igor Kroitor <notifications@github.com>:
