### ISSUE TITLE
yobit fetch_tickers URI too large

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#1264]
- OS: windows
- Programming Language version: python
- CCXT version: 708
- Exchange: Yobit
- Method: fetch_tickers()

The URI fetch_tickers() (without symbol param) generates is too large. I've tested in making it smaller:
- At first you get a cloudflare error
- After making it smaller Yobit generates a 403
- After making it even smaller Yobit says {"success":0,"error":"Empty pair list"}
- After removing symbols until the URI was 526 characters (URI only, so after https://yobit.net/) it works

Is it possible in the library to slice the fetch_tickers generated uri in multiples of let's say 512 bytes, and do multiple requests ?

```
import ccxt

e = ccxt.yobit()
e.verbose = True
e.fetch_tickers()

"max_price":10000,"min_amount":0.0001,"min_total":0.0001,"hidden":0,"fee":0.2,"fee_buyer":0.2,"fee_seller":0.2},"orly_eth":{"decimal_places":8,"min_price":0.00000001,"max_price":10000,"min_amount":0.0001,<snip many more>
GET https://yobit.net/api/3/ticker/007_btc-007_doge-007_eth-007_rur-007_usd-007_waves-1337_btc-1337_doge-1337_eth-1337_rur-1337_usd-1337_waves-2015_btc-2015_doge-2015_eth-2015_rur-<snip many more>
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 349, in fetch
    response.raise_for_status()
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 414 Client Error: Request-URI Too Large for url: https://yobit.net/api/3/ticker/007_btc-007_doge-007_eth-007_rur-007_usd-007_waves-1337_btc-1337_doge-1337_eth-<snip many more>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/Carousel2/_test/test3.py", line 5, in <module>
    e.fetch_tickers()
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\liqui.py", line 244, in fetch_tickers
    }, params))
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\yobit.py", line 173, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 296, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 363, in fetch
    self.raise_error(ExchangeError, url, method, e, self.last_http_response)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 278, in raise_error
    details,
ccxt.base.errors.ExchangeError: yobit GET https://yobit.net/api/3/ticker/007_btc-007_doge-007_eth-007_rur-007_usd-007_waves-1337_btc-1337_doge-1337_eth-1337_rur-1337_usd-1337_waves-2015_btc-2015_doge-<snip many more>
<head><title>414 Request-URI Too Large</title></head>
<body bgcolor="white">
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>


Process finished with exit code 1

```

**Comment by kroitor** [comment]
This issue is fixed in version 1.10.711.

> Is it possible in the library to slice the fetch_tickers generated uri in multiples of let's say 512 bytes, and do multiple requests ?

We have a policy on the amount of requests: one call = one request. Explained here: https://github.com/ccxt/ccxt/issues/1175#issuecomment-356831009

**Comment by gaardiolor** [comment]
Yeah I understand, I'll do it in my script. Thanks!

**Comment by gaardiolor** [comment]
@kroitor I think you need to fix the exception though.

```
Traceback (most recent call last):
  File "C:/Users/guardi/PycharmProjects/Carousel2/_test/test3.py", line 6, in <module>
    e.fetch_tickers()
  File "C:\Users\guardi\Anaconda3\lib\site-packages\ccxt\liqui.py", line 242, in fetch_tickers
    raise ExchangeError(self.id + ' has ' + numIds.toSring() + ' symbols exceeding max URL length, you are required to specify a list of symbols in the first argument to fetchTickers')
AttributeError: 'int' object has no attribute 'toSring'
```
