### ISSUE TITLE
`bitfinex2.fetchPositions()` constructs v1 style endpoint, resulting in 404

### ISSUE THREAD

**Issue by josh-renton** [ccxt/ccxt#12781]
- OS: OSX 10.15.7
- Programming Language version: Node 12.22.10
- CCXT version: 1.78.78

The constructed endpoint (`https://api.bitfinex.com/v2/positions`) looks like a [bitfinex v1 positions endpoint](https://docs.bitfinex.com/v1/reference#rest-auth-active-positions).

The [endpoint for v2](https://docs.bitfinex.com/reference#rest-auth-positions) should look like: `https://api.bitfinex.com/v2/auth/r/positions`

I see that the correct style is defined in `ccxt/js/bitfinex2.js:186`, but I'm guessing the code is falling back to the v1 as `bitfinex2` extends `bitfinex`.

I tried adding `fetchPositions: true` to the `has` object in the class description (`bitfinex2.js:21`) - but that didn't seem to fix it.

Here's a complete output.

```
const ccxt = require('ccxt')
const bfx = new ccxt.bitfinex2({ apiKey: XXXXX, secret: XXXXX })
bfx.verbose = true
bfx.fetchPositions()
```

```
fetch Request:
 bitfinex2 POST https://api.bitfinex.com/v2/positions 
RequestHeaders:
 {
  'bfx-nonce': '1649862839072',
  'bfx-apikey': XXXXXXX,
  'bfx-signature': XXXXXXXX,
  'Content-Type': 'application/json'
} 
RequestBody:
 {} 

handleRestResponse:
 bitfinex2 POST https://api.bitfinex.com/v2/positions 404 Not Found 
ResponseHeaders:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '6fb526188e144912-SIN',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Security-Policy': "default-src 'none'",
  'Content-Type': 'text/html; charset=utf-8',
  Date: 'Wed, 13 Apr 2022 15:13:59 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  'Referrer-Policy': 'same-origin',
  Server: 'cloudflare',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains;',
  'Transfer-Encoding': 'chunked',
  'X-Content-Type-Options': 'nosniff',
  'X-Download-Options': 'noopen',
  'X-Frame-Options': 'sameorigin',
  'X-Permitted-Cross-Domain-Policies': 'none',
  'X-Xss-Protection': '1; mode=block'
} 
ResponseBody:
 <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /api/v2/positions</pre>
</body>
</html>
 

(node:43445) UnhandledPromiseRejectionWarning: ExchangeNotAvailable: bitfinex2 POST https://api.bitfinex.com/v2/positions 404 Not Found <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /api/v2/positions</pre>
</body>
</html>

    at bitfinex2.handleHttpStatusCode (/Users/josh/Documents/work/oscar-sheet-rewrite/node_modules/ccxt/js/base/Exchange.js:671:19)
    at /Users/josh/Documents/work/oscar-sheet-rewrite/node_modules/ccxt/js/base/Exchange.js:719:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by josh-renton** [comment]
@kroitor hi, can you support with this at all?

**Comment by kroitor** [comment]
@josh-renton pardon for the long wait, will get it fixed asap!

**Comment by josh-renton** [comment]
> @josh-renton pardon for the long wait, will get it fixed asap!

Thank you :) 👍

**Comment by kroitor** [comment]
@josh-renton the new build will arrive in CCXT 1.80.47 in ~15 minutes. It will still return the exchange-specific response format for now, to be unified soon. Please, let us know if you have any issues with it. Thanks for your feedback!
