### ISSUE TITLE
Okex5 Sandbox Mode : Internal Server Error. Re-Open Issue - #12774

### ISSUE THREAD

**Issue by RtjShreyD** [ccxt/ccxt#12828]
Following is my code - 

```
import ccxt
import os
from dotenv import load_dotenv
load_dotenv()

exchange = ccxt.okex5({
    'apiKey': os.getenv('API_KEY'),
    'secret': os.getenv('SECRET'),
    'password': os.getenv('PASSPHRASE'),
})
exchange.set_sandbox_mode(True)

balances = exchange.fetch_balance()
print(balances['total'])
```

Following are my error logs - 

```
Traceback (most recent call last):
  File "/home/rtj/TecE/CCXT-Eval/ccxt-env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 648, in fetch
    response.raise_for_status()
  File "/home/rtj/TecE/CCXT-Eval/ccxt-env/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://www.okx.com/api/v5/asset/currencies

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gola.py", line 13, in <module>
    balances = exchange.fetch_balance()
  File "/home/rtj/TecE/CCXT-Eval/ccxt-env/lib/python3.8/site-packages/ccxt/okx.py", line 1636, in fetch_balance
    self.load_markets()
  File "/home/rtj/TecE/CCXT-Eval/ccxt-env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1513, in load_markets
    currencies = self.fetch_currencies()
  File "/home/rtj/TecE/CCXT-Eval/ccxt-env/lib/python3.8/site-packages/ccxt/okx.py", line 1035, in fetch_currencies
    response = self.privateGetAssetCurrencies(params)
  File "/home/rtj/TecE/CCXT-Eval/ccxt-env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 490, in inner
    return entry(_self, **inner_kwargs)
  File "/home/rtj/TecE/CCXT-Eval/ccxt-env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 541, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/rtj/TecE/CCXT-Eval/ccxt-env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 537, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/rtj/TecE/CCXT-Eval/ccxt-env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 664, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/rtj/TecE/CCXT-Eval/ccxt-env/lib/python3.8/site-packages/ccxt/okx.py", line 4551, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: okex5 {"code":500,"data":{},"detailMsg":"java.lang.IllegalStateException: global config not exists\n\tat com.google.common.base.Preconditions.checkState(Preconditions.java:456)\n\tat com.okcoin.ex.wallet.service.IGlobalConfigServiceImpl.getGlobalConfig$original$esdhLTPK(IGlobalConfigServiceImpl.java:48)\n\tat com.okcoin.ex.wallet.service.IGlobalConfigServiceImpl.getGlobalConfig$original$esdhLTPK$accessor$RbfAWL9Q(IGlobalConfigServiceImpl.java)\n\tat com.okcoin.ex.wallet.service.IGlobalConfigServiceImpl$auxiliary$WFZQVLY4.call(Unknown Source)\n\tat org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)\n\tat com.okcoin.ex.wallet.service.IGlobalConfigServiceImpl.getGlobalConfig(IGlobalConfigServiceImpl.java)\n\tat com.okcoin.ex.wallet.service.BrokerWithdrawLimitServiceImpl.getDailyWithdrawLimit$original$5XD66GCe(BrokerWithdrawLimitServiceImpl.java:96)\n\tat com.okcoin.ex.wallet.service.BrokerWithdrawLimitServiceImpl.getDailyWithdrawLimit$original$5XD66GCe$accessor$rKf8HqlK(BrokerWithdrawLimitServiceImpl.java)\n\tat com.okcoin.ex.wallet.service.BrokerWithdrawLimitServiceImpl$auxiliary$qUvVGG6k.call(Unknown Source)\n\tat org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)\n\tat com.okcoin.ex.wallet.service.BrokerWithdrawLimitServiceImpl.getDailyWithdrawLimit(BrokerWithdrawLimitServiceImpl.java)\n\tat com.okcoin.ex.wallet.service.IWithdrawTransactionServiceImpl.getDailtotal$original$pVabVlPd(IWithdrawTransactionServiceImpl.java:961)\n\tat com.okcoin.ex.wallet.service.IWithdrawTransactionServiceImpl.getDailtotal$original$pVabVlPd$accessor$ao8GkfCS(IWithdrawTransactionServiceImpl.java)\n\tat com.okcoin.ex.wallet.service.IWithdrawTransactionServiceImpl$auxiliary$cehahpCC.call(Unknown Source)\n\tat org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)\n\tat com.okcoin.ex.wallet.service.IWithdrawTransactionServiceImpl.getDailtotal(IWithdrawTransactionServiceImpl.java)\n\tat com.okcoin.ex.wallet.service.IWithdrawTransactionServiceImpl$$FastClassBySpringCGLIB$$d9fac803.invoke(<generated>)\n\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\n\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)\n\tat com.okcoin.ex.wallet.service.IWithdrawTransactionServiceImpl$$EnhancerBySpringCGLIB$$8639a1a6.getDailtotal(<generated>)\n\tat com.okcoin.ex.controller.v5.AssetV5Controller.currencies$original$4m45iHdk(AssetV5Controller.java:290)\n\tat com.okcoin.ex.controller.v5.AssetV5Controller.currencies$original$4m45iHdk$accessor$HnCP6GPF(AssetV5Controller.java)\n\tat com.okcoin.ex.controller.v5.AssetV5Controller$auxiliary$xKsLKHyO.call(Unknown Source)\n\tat org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)\n\tat com.okcoin.ex.controller.v5.AssetV5Controller.currencies(AssetV5Controller.java)\n\tat com.okcoin.ex.controller.v5.AssetV5Controller$$FastClassBySpringCGLIB$$cb12f187.invoke(<generated>)\n\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\n\tat org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n\tat com.okcoin.commons.rate.limit.aop.RateLimitAspect.around(RateLimitAspect.java:58)\n\tat sun.reflect.GeneratedMethodAccessor371.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)\n\tat org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)\n\tat org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\n\tat org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\n\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)\n\tat com.okcoin.ex.controller.v5.AssetV5Controller$$EnhancerBySpringCGLIB$$68a509a3.currencies(<generated>)\n\tat sun.reflect.GeneratedMethodAccessor547.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:634)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:741)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat com.okcoin.commons.okex.open.api.filter.OKOpenApiRequestReplaceFilter.doFilterInternal(OKOpenApiRequestReplaceFilter.java:19)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat com.okcoin.commons.sign.filter.SignRequestInputStreamCacheFilter.doFilterInternal(SignRequestInputStreamCacheFilter.java:17)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat com.okcoin.commons.okcoin.error.trace.OKTracingLogRequestIDFilter.doFilter(OKTracingLogRequestIDFilter.java:36)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)\n\tat org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)\n\tat org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\tat org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\tat org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\tat org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\tat org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\tat org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\tat org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\tat org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)\n\tat org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\tat org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\tat org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)\n\tat org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)\n\tat org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)\n\tat org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)\n\tat org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat com.okcoin.redirect.filter.RedirectComponentFilter.doFilter$original$nFLNFRLs(RedirectComponentFilter.java:42)\n\tat com.okcoin.redirect.filter.RedirectComponentFilter.doFilter$original$nFLNFRLs$accessor$5UuvFYtQ(RedirectComponentFilter.java)\n\tat com.okcoin.redirect.filter.RedirectComponentFilter$auxiliary$jvh8CI4G.call(Unknown Source)\n\tat org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)\n\tat com.okcoin.redirect.filter.RedirectComponentFilter.doFilter(RedirectComponentFilter.java)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)\n\tat org.apache.catalina.core.StandardHostValve.invoke$original$RFwQIt5Q(StandardHostValve.java:139)\n\tat org.apache.catalina.core.StandardHostValve.invoke$original$RFwQIt5Q$accessor$cf7gWJ1Y(StandardHostValve.java)\n\tat org.apache.catalina.core.StandardHostValve$auxiliary$xUyF8VXu.call(Unknown Source)\n\tat org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:748)\n","error_code":"500","error_message":"server error 2087730992","msg":"server error 2087730992"}

```

**Comment by RtjShreyD** [comment]
its working now, i don't know how, maybe this was an issue from OKX backends, let me test it out for 24 hrs then i'd close this.

**Comment by RtjShreyD** [comment]
Closing this, its working fine now, it was arising from OKX backends probably.
