### ISSUE TITLE
Kucoin order failure

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#1298]
- OS: Windows, Linux
- Programming Language version: Python sync, async
- CCXT version: 727. It worked in 712. 
- Exchange: Kucoin
- Method: create_limit_buy_order

create_limit_buy_order fails, see below. It worked in version 712. 
```
C:\Users\gaardiolor\Anaconda3\python.exe C:/Users/gaardiolor/PycharmProjects/Test2/_test/test3.py
GET https://api.kucoin.com/v1/market/open/symbols 
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/market/open/symbols 
Response: {'Date': 'Mon, 15 Jan 2018 21:31:43 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'Set-Cookie': 'SESSION=<snip>; Path=/; HttpOnly'} {"success":true,"code":"OK","msg":"Operation succeeded.",<snipok>
GET https://api.kucoin.com/v1/market/open/coins 
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.kucoin.com/v1/market/open/coins 
Response: {'Date': 'Mon, 15 Jan 2018 21:31:44 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'Set-Cookie': 'SESSION=<snip>; Path=/; HttpOnly'} {"success":true,"code":"OK","msg":"Operation succeeded.",<snipok>
POST https://api.kucoin.com/v1/order?amount=0.0001&price=0.00000001&symbol=RPX-BTC&type=BUY 
Request: {'KC-API-KEY': '<snip>', 'KC-API-NONCE': '1516051904610', 'KC-API-SIGNATURE': '<snip>', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} amount=0.0001&price=0.00000001&symbol=RPX-BTC&type=BUY
POST https://api.kucoin.com/v1/order?amount=0.0001&price=0.00000001&symbol=RPX-BTC&type=BUY 
Response: {'Date': 'Mon, 15 Jan 2018 21:31:44 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400'} {"success":false,"code":"ERROR","msg":"Min amount each order:1.0","timestamp":1516051904779,"data":null}

Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/Test2/_test/test3.py", line 9, in <module>
    e.create_limit_buy_order('RPX/BTC', float(0.0001), float(0.00000001))
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1016, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 382, in create_order
    'id': self.safe_string(response['data'], 'orderOid'),
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 425, in safe_string
    return str(dictionary[key]) if key is not None and (key in dictionary) and dictionary[key] else default_value
TypeError: argument of type 'NoneType' is not iterable

Process finished with exit code 1
```

So what I'm expecting (to grab the min order amount) is:
```
Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/test2/_test/test3.py", line 9, in <module>
    e.create_limit_buy_order('RPX/BTC', float(0.0001), float(0.00000001))
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1015, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 379, in create_order
    response = self.privatePostOrder(self.extend(order, params))
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 583, in request
    self.throw_exception_on_error(response)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 574, in throw_exception_on_error
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: kucoin {"success":false,"code":"ERROR","msg":"Min amount each order:1.0","timestamp":1516052456235,"data":null}
```

**Comment by gaardiolor** [comment]
ccxt-1.10.724: Latest version where this works
ccxt-1.10.725: doesn't seem to exist (pip is unable to find it)
ccxt-1.10.726: not working
ccxt-1.10.727: not working

**Comment by Fcl69** [comment]
Still got this error:

POST https://api.kucoin.com/v1/order?amount=0.28&price=1.93046590&symbol=BCH-ETH&type=BUY
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'KC-API-KEY': 'key', 'KC-API-SIGNATUR
E': 'sign', 'KC-API-NONCE': '1516166257490', 'Accept-Encoding': 'gzip, deflate'} amount=0.28&price=1.93046590&symbol=BCH-ETH&type=BUY
POST https://api.kucoin.com/v1/order?amount=0.28&price=1.93046590&symbol=BCH-ETH&type=BUY
Response: {'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Transfer-Encoding': 'chunked', 'Access-Control-Max-Age':
'86400', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Wed, 17 Jan 2018 05:17:37 GMT', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Credentials': 'true', 'Connection': 'keep-alive'} {"success":false,"code":"ERROR","msg":"The precision of price(ETH) is incorrect. **The precision of ETH is 6**","timestamp":1516166257545,"data":null}


>pip3 list | grep ccxt
ccxt (1.10.738)
