### ISSUE TITLE
i cant get balances for huobi

### ISSUE THREAD

**Issue by superquantum** [ccxt/ccxt#13064]
**Hi everybody im new in ccxt. i cant find parameters for huobi. firslty in this codes what is my problem second. where i can learn ccxt more. thanks.**

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: win11
- Programming Language version: pyth 3.9
- CCXT version: 1.80.52

```
import ccxt
import anahtar

huobix = ccxt.huobipro({
    'apiKey': anahtar.hub_anhtr,
    'secret': anahtar.hub_guv,
 
})


x=huobix.fetch_balance()
```

```
Traceback (most recent call last):
  File "c:\Users\Deneme\OneDrive\Python\huobi_hesap_bilgi.py", line 11, in <module>
    x=huobix.fetch_balance()
  File "C:\Users\Deneme\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ccxt\huobi.py", line 2338, in fetch_balance
    self.load_accounts()
  File "C:\Users\Deneme\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ccxt\base\exchange.py", line 1532, in load_accounts
    self.accounts = self.fetch_accounts(params)
  File "C:\Users\Deneme\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ccxt\huobi.py", line 2169, in fetch_accounts
    response = self.spotPrivateGetV1AccountAccounts(params)
  File "C:\Users\Deneme\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ccxt\base\exchange.py", line 496, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Deneme\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ccxt\base\exchange.py", line 547, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\Deneme\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ccxt\base\exchange.py", line 542, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "C:\Users\Deneme\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ccxt\huobi.py", line 4552, in sign
    signature = self.hmac(self.encode(payload), self.encode(self.secret), hashlib.sha256, 'base64')
  File "C:\Users\Deneme\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ccxt\base\exchange.py", line 1347, in encode
    return string.encode('latin-1')
AttributeError: 'tuple' object has no attribute 'encode'
```

**Comment by kroitor** [comment]
The apiKey and the `secret` must be a string, not a tuple.

```Python
import ccxt
from pprint import pprint
exchange = ccxt.huobi({
    'apiKey': 'YOUR_API_KEY_HERE',
    'secret': 'YOUR_API_SECRET_HERE',
})
balance = exchange.fetch_balance()
pprint(balance)
```

> where i can learn ccxt more. thanks.

I would recommend reading the Manual from top to bottom and checking the examples:

- https://docs.ccxt.com/
- https://github.com/ccxt/ccxt/tree/master/examples/
- https://github.com/ccxt/ccxt/tree/master/examples/#see-also

Hope that helps, let us know if not. Feel free to reopen it if necessary or just ask further questions if any.

**Comment by superquantum** [comment]
@kroitor Thanks for your biggest help. its worked.  Я умею разговориват Руский Язык. огоромное спасибо. я новичок поэтему не понял где моя ошибка. Благодарю вам.
