### ISSUE TITLE
Parameter side error when creating order in Okex sandbox

### ISSUE THREAD

**Issue by jurab** [ccxt/ccxt#13167]
Hey, I can't place a limit order to Okex in sandbox mode. It returns a `Parameter side  error` from their API. I've tried sending in `side='short'` as that's what they document, but had the same issue.

A side question - from the ccxt documentation it seems that the side values of `sell` and `buy` are universal, is that true, or do I need to investigate and make that parameter exchange specific? Thanks.

- OS: Mac
- Programming Language version: Python 3.10.2
- CCXT version: 1.81.77

```
import ccxt

okex = ccxt.bybit({'apiKey': '<key>, 'secret': '<secret>', 'password': '<pass>'})
okex.set_sandbox_mode(True)

def place_order(exchange, symbol, order_type, side, quantity=10, price=None):

    if not price:
        bid, ask = get_price(exchange, symbol)
        price = ask if side == 'buy' else bid

    getattr(exchange, 'createOrder')(symbol, order_type, side, quantity, price, params={'tdMode': 'isolated', 'lever': 1})

place_order(okex, 'CVC-USDT-SWAP', 'limit', 'sell')
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    perpetuum()
  File "main.py", line 87, in perpetuum
    order = place_order(exchange, symbol, 'limit', side)
  File "main.py", line 76, in place_order
    getattr(exchange, 'createOrder')(symbol, order_type, side, quantity, price, params={'tdMode': 'isolated', 'lev
er': 1})
  File "/Users/jurabrazdil/Venvs/perpetuum/lib/python3.10/site-packages/ccxt/okx.py", line 1879, in create_order
    response = getattr(self, defaultMethod)(extendedRequest)
  File "/Users/jurabrazdil/Venvs/perpetuum/lib/python3.10/site-packages/ccxt/base/exchange.py", line 496, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/jurabrazdil/Venvs/perpetuum/lib/python3.10/site-packages/ccxt/base/exchange.py", line 548, in reque
st
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/Users/jurabrazdil/Venvs/perpetuum/lib/python3.10/site-packages/ccxt/base/exchange.py", line 544, in fetch
2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/jurabrazdil/Venvs/perpetuum/lib/python3.10/site-packages/ccxt/base/exchange.py", line 699, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, req
uest_headers, request_body)
  File "/Users/jurabrazdil/Venvs/perpetuum/lib/python3.10/site-packages/ccxt/okx.py", line 4561, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/Users/jurabrazdil/Venvs/perpetuum/lib/python3.10/site-packages/ccxt/base/exchange.py", line 562, in throw
_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: okex {"code":"1","data":[{"clOrdId":"e847386590ce4dBC4cb1a9d866499137","ordId":"","sC
ode":"51000","sMsg":"Parameter side  error","tag":""}],"msg":""}
```

**Comment by jurab** [comment]
Ah, sorry for the mistake - Okex requires `ask` and `sell`. My side question still stands - do I have to deal with that on individual basis for every exchange?
