### ISSUE TITLE
okex fetch_ohlcv symbol error

### ISSUE THREAD

**Issue by alanshalem** [ccxt/ccxt#13197]
OS: Windows 10
Programming Language version: python
CCXT version: ccxt==1.44.7
Exchange: okex
Method: fetch_ohlcv()

```
import ccxt

print(ccxt.exchanges)

kucoin = ccxt.kucoin()
okex = ccxt.okex()
bitmex = ccxt.bitmex()
huobipro = ccxt.huobipro()

exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class()

symbol = 'BTC/USDT'
timeframe = '1h'

binance_ohlcv = exchange.fetch_ohlcv(symbol, timeframe)
kucoin_ohlcv = kucoin.fetch_ohlcv(symbol, timeframe)
okex_ohlcv = okex.fetch_ohlcv(symbol, timeframe)
huobipro_ohlcv = huobipro.fetch_ohlcv(symbol, timeframe)
```

```
[Running] python -u "c:\Users\root\Downloads\de-cero-a-quant\tempCodeRunnerFile.py"
['aax', 'acx', 'aofex', 'ascendex', 'bequant', 'bibox', 'bigone', 'binance', 'binanceus', 'bit2c', 'bitbank', 'bitbay', 'bitcoincom', 'bitfinex', 'bitfinex2', 'bitflyer', 'bitforex', 'bitget', 'bithumb', 'bitkk', 'bitmart', 'bitmax', 'bitmex', 'bitpanda', 'bitso', 'bitstamp', 'bitstamp1', 'bittrex', 'bitvavo', 'bitz', 'bl3p', 'bleutrade', 'braziliex', 'btcalpha', 'btcbox', 'btcmarkets', 'btctradeua', 'btcturk', 'buda', 'bw', 'bybit', 'bytetrade', 'cdax', 'cex', 'chilebit', 'coinbase', 'coinbaseprime', 'coinbasepro', 'coincheck', 'coinegg', 'coinex', 'coinfalcon', 'coinfloor', 'coingi', 'coinmarketcap', 'coinmate', 'coinone', 'coinspot', 'crex24', 'currencycom', 'delta', 'deribit', 'digifinex', 'equos', 'eterbase', 'exmo', 'exx', 'fcoin', 'fcoinjp', 'flowbtc', 'foxbit', 'ftx', 'gateio', 'gemini', 'gopax', 'hbtc', 'hitbtc', 'hollaex', 'huobijp', 'huobipro', 'idex', 'independentreserve', 'indodax', 'itbit', 'kraken', 'kucoin', 'kuna', 'lakebtc', 'latoken', 'lbank', 'liquid', 'luno', 'lykke', 'mercado', 'mixcoins', 'ndax', 'novadax', 'oceanex', 'okcoin', 'okex', 'paymium', 'phemex', 'poloniex', 'probit', 'qtrade', 'rightbtc', 'ripio', 'southxchange', 'stex', 'surbitcoin', 'therock', 'tidebit', 'tidex', 'timex', 'upbit', 'vbtc', 'vcc', 'wavesexchange', 'whitebit', 'xbtce', 'xena', 'yobit', 'zaif', 'zb']
Traceback (most recent call last):
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 594, in fetch
    response.raise_for_status()
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://www.okex.com/api/spot/v3/instruments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\root\Downloads\de-cero-a-quant\tempCodeRunnerFile.py", line 19, in <module>
    okex_ohlcv = okex.fetch_ohlcv(symbol, timeframe)
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\ccxt\okex.py", line 1376, in fetch_ohlcv
    self.load_markets()
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 1365, in load_markets
    markets = self.fetch_markets(params)
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\ccxt\okex.py", line 736, in fetch_markets
    markets = self.fetch_markets_by_type(types[i], params)
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\ccxt\okex.py", line 918, in fetch_markets_by_type
    response = getattr(self, method)(params)
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 468, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 493, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 489, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 610, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\root\AppData\Roaming\Python\Python39\site-packages\ccxt\okex.py", line 3468, in handle_errors
    raise ExchangeNotAvailable(feedback)
ccxt.base.errors.ExchangeNotAvailable: okex {"message":"failure to get a peer from the ring-balancer"}

[Done] exited with code=1 in 14.344 seconds
```

**Comment by alanshalem** [comment]
Similar to this issue, couldn't solve it with the info provided there
https://github.com/ccxt/ccxt/issues/5410
Thank you very much in advance!

**Comment by ttodua** [comment]
The first thing you have to do, is to update CCXT - you are using too old version, and the issue should be gone. feel free to reopen the issue if that doesnt help.

**Comment by alanshalem** [comment]
Sorry to re-open this issue, feel free to close it if it's a dumb question, I'm still a beginner. 
I need to install [pyjuqye](https://github.com/tudorelu/pyjuque), which is an algo trading engine, as I see, executing
`pip install --user pyjuque`
outputs me the next:
`Successfully installed aiohttp-3.7.4.post0 async-timeout-3.0.1 **_ccxt-1.44.7_** yarl-1.1.0`
Is there a way to use this version and not have that error? Thanks again!

**Comment by kroitor** [comment]
@alanshalem after installing pyjuque, you can `pip3 install -U ccxt` to upgrade ccxt to the most recent version (1.82+). The pyjuque package is just somewhat outdated: https://github.com/tudorelu/pyjuque/blob/master/requirements.txt#L2

**Comment by alanshalem** [comment]
> @alanshalem after installing pyjuque, you can `pip3 install -U ccxt` to upgrade ccxt to the most recent version (1.82+). The pyjuque package is just somewhat outdated: https://github.com/tudorelu/pyjuque/blob/master/requirements.txt#L2

@kroitor Thank you very much for your help! :D This helped a lot.
