### ISSUE TITLE
[COINEX] Can't get order status / method fetch_order() raises exception

### ISSUE THREAD

**Issue by Djusk8** [ccxt/ccxt#13216]
- OS: independent
- Programming Language version: Python 3.7
- CCXT version: latest (1.82.19)

```
import ccxt

ex = ccxt.coinex({ 'apiKey': 'XXX', 'secret': 'XXX', })

open_orders = ex.fetch_open_orders('BNT/BTC')

# open_orders:
# [{'id': '66188943662', 'clientOrderId': None, 'datetime': '2022-...........]}, 
# {'id': '70870835708', 'clientOrderId': None, 'datetime': '2022-..............}]

order_status = ex.fetch_order('70870835708', symbol='BNT/BTC')
```

```
Traceback (most recent call last):
  File "/Users/............lib/python3.7/site-packages/ccxt/base/exchange.py", line 655, in fetch
    response.raise_for_status()
  File "/Users/............../lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.coinex.com/v1/order?access_id=XXXXXX&id=70870835708&market=BNTBTC&tonce=1652368915940

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/............/lib/python3.7/site-packages/ccxt/base/exchange.py", line 673, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/Users/.........../lib/python3.7/site-packages/ccxt/base/exchange.py", line 709, in handle_http_status_code
    raise Exception(' '.join([self.id, method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: coinex GET https://api.coinex.com/v1/order?access_id=XXXXXXXX&id=70870835708&market=BNTBTC&tonce=1652368915940 404 Not Found <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

I think the part of the URL is lost.
Now we have:
```https://api.coinex.com/v1/order?access_id=.....```
But to get order status URL should be:
```https://api.coinex.com/v1/order/status?access_id=.....``` (```/status``` part is lost)

To solve this problem I have edited fetch_order() method in coinex.py
I'm not shure it's the right solution but it works for me. 

```
    def fetch_order(self, id, symbol=None, params={}):
        if symbol is None:
            raise ArgumentsRequired(self.id + ' fetchOrder() requires a symbol argument')
        self.load_markets()
        market = self.market(symbol)
        swap = market['swap']
        stop = self.safe_value(params, 'stop')
        request = {
            'market': market['id'],
            # 'id': id,  # SPOT
            # 'order_id': id,  # SWAP
        }
        idRequest = 'order_id' if swap else 'id'
        request[idRequest] = id
        method = None
        if swap:
            method = 'perpetualPrivateGetOrderStopStatus' if stop else 'perpetualPrivateGetOrderStatus'
        else:
--            method = 'privateGetOrder'
++           method = 'privateGetOrderStatus'
        params = self.omit(params, 'stop')
        response = getattr(self, method)(self.extend(request, params))
        data = self.safe_value(response, 'data')
        return self.parse_order(data, market)
```

**Comment by carlosmiei** [comment]
Hello @Djusk8, thanks for letting us know. I'll add a fix to it shortly
