### ISSUE TITLE
Waves.Exchange fetch_open_orders() KeyError

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#13224]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 1.82.19

```
exchange = ccxt.wavesexchange({...})
exchange.fetch_open_orders()
```

```
Traceback (most recent call last):
...
    exchange.fetch_open_orders()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/wavesexchange.py", line 1347, in fetch_open_orders
    return self.parse_orders(response, market, since, limit)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2107, in parse_orders
    array = [self.extend(self.parse_order(order, market), params) for order in orders]
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2107, in <listcomp>
    array = [self.extend(self.parse_order(order, market), params) for order in orders]
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/wavesexchange.py", line 1466, in parse_order
    price = self.price_from_precision(symbol, priceString)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/wavesexchange.py", line 1076, in price_from_precision
    market = self.markets[symbol]
KeyError: 'B3UGHFRPSUUGEDWJQB9LWWXAFQJ8VTVPMUCEYOXZWS5H/BTC'
```

It looks like in the KeyError key above there is a currency id on the left side of '/' character, whereas the right side is a currency symbol. 

If I use `verbose=True` setting, I can see that the reply dictionary from the exchange, that is being parsed, contains
```
"assetPair":{"amountAsset":"B3uGHFRpSUuGEDWjqB9LWWxafQj8VTvpMucEyoxzws5H","priceAsset":"8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS}
```
which should correspond to the KeyError pair. Therefore I suspect that the problem happens somewhere deep within `get_symbol_from_asset_pair` function. 

If you need more clues for this bug, I can give you more output if you tell me what to look at.

**Comment by kroitor** [comment]
Hi! 

Please, always paste your verbose output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
exchange = ccxt.wavesexchange({...})
markets = exchange.load_markets()
exchange.verbose = True
exchange.fetch_open_orders()
```

**Comment by JovianMoon** [comment]
@kroitor Usually I try to avoid posting the verbose outputs, because they can contain pretty identifiable information. In this case, there even seems to be such things as `username` and `password` in the urls. Would it really be safe to post full uncensored `verbose=True` outputs here?

Here's the output from the code you suggested, but I have replaced some parts with '...' for safety:

```
fetch Request: wavesexchange POST https://api.waves.exchange/v1/oauth2/token?grant_type=password&scope=general&username=...&password=...&client_id=waves.exchange RequestHeaders: {'Accept': '*/*', 'content-type': 'application/json', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: wavesexchange POST https://api.waves.exchange/v1/oauth2/token?grant_type=password&scope=general&username=...&password=...&client_id=waves.exchange 200 ResponseHeaders: {'Date': 'Fri, 13 May 2022 10:07:00 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'vary': 'Accept-Encoding', 'x-request-id': '...', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'access-control-allow-methods': 'PUT, GET, POST, OPTIONS', 'access-control-allow-headers': 'origin,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization', 'access-control-expose-headers': 'grpc-status,grpc-message,grpc-errors-bin', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=..."}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '.', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: {"access_token":"...","token_type":"bearer","expires_in":560490,"refresh_token":"...","scope":"general"}

fetch Request: wavesexchange GET https://nodes.waves.exchange/addresses/publicKey/... RequestHeaders: {'content-type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: wavesexchange GET https://nodes.waves.exchange/addresses/publicKey/... 200 ResponseHeaders: {'Date': 'Fri, 13 May 2022 10:07:00 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'vary': 'Accept-Encoding', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE', 'access-control-allow-headers': 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,signature,timestamp', 'access-control-expose-headers': 'Content-Length,Content-Range', 'backend': 'unknown', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=..."}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '...', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: {"address":"..."}

fetch Request: wavesexchange GET https://waves.exchange/api/v1/forward/matcher/matcher/orders/...?activeOnly=true RequestHeaders: {'Accept': '*/*', 'Authorization': 'Bearer ...', 'content-type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: wavesexchange GET https://waves.exchange/api/v1/forward/matcher/matcher/orders/...?activeOnly=true 200 ResponseHeaders: {'Date': 'Fri, 13 May 2022 10:07:00 GMT', 'Content-Type': 'application/json', 'Content-Length': '540', 'Connection': 'keep-alive', 'set-cookie': 'INGRESSCOOKIE=...; Path=/api; Secure; HttpOnly', 'access-control-allow-credentials': 'true', 'access-control-allow-headers': 'origin,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization,x-analytics-key,x-api-key,geetest-challenge,geetest-validate,geetest-seccode,x-amz-target,x-amz-user-agent,x-application,WFP', 'access-control-allow-methods': 'PUT, GET, POST, OPTIONS, DELETE', 'access-control-allow-origin': '*', 'access-control-expose-headers': 'Content-Length,Content-Range', 'backend': 'unknown', 'Content-Encoding': 'gzip', 'matcher-http-server': 'matcher-1', 'vary': 'Accept-Encoding', 'x-span-id': '...', 'x-trace-id': '...', 'x-cache-status-frontend': 'MISS', 'x-request-id': '...', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=..."}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '...', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: [{"id":"...","type":"sell","orderType":"limit","amount":...,"filled":0,"price":...,"fee":...,"filledFee":0,"feeAsset":"3KhNcHo4We1G5EWps7b1e5DTdLgWDzctc8S6ynu37KAb","timestamp":...,"status":"Accepted","assetPair":{"amountAsset":"3KhNcHo4We1G5EWps7b1e5DTdLgWDzctc8S6ynu37KAb","priceAsset":"8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS"},"avgWeighedPrice":0,"version":3,"totalExecutedPriceAssets":0},{"id":"...","type":"sell","orderType":"limit","amount":...,"filled":0,"price":...,"fee":...,"filledFee":0,"feeAsset":"WAVES","timestamp":...,"status":"Accepted","assetPair":{"amountAsset":"zMFqXuoyrn5w17PFurTqxB7GsS71fp9dfk6XFwxbPCy","priceAsset":"8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS"},"avgWeighedPrice":0,"version":3,"totalExecutedPriceAssets":0},{"id":"...","type":"sell","orderType":"limit","amount":...,"filled":0,"price":...,"fee":...,"filledFee":0,"feeAsset":"WAVES","timestamp":...,"status":"Accepted","assetPair":{"amountAsset":"B3uGHFRpSUuGEDWjqB9LWWxafQj8VTvpMucEyoxzws5H","priceAsset":"8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS"},"avgWeighedPrice":0,"version":3,"totalExecutedPriceAssets":0}]
Traceback (most recent call last):
...
    exchange.fetch_open_orders()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/wavesexchange.py", line 1347, in fetch_open_orders
    return self.parse_orders(response, market, since, limit)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2107, in parse_orders
    array = [self.extend(self.parse_order(order, market), params) for order in orders]
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2107, in <listcomp>
    array = [self.extend(self.parse_order(order, market), params) for order in orders]
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/wavesexchange.py", line 1466, in parse_order
    price = self.price_from_precision(symbol, priceString)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/wavesexchange.py", line 1076, in price_from_precision
    market = self.markets[symbol]
KeyError: 'B3UGHFRPSUUGEDWJQB9LWWXAFQJ8VTVPMUCEYOXZWS5H/BTC'
```

**Comment by JovianMoon** [comment]
@kroitor After some further investigation I found out that "B3UGHFRPSUUGEDWJQB9LWWXAFQJ8VTVPMUCEYOXZWS5H" id belongs to DASH, which Waves.Exchange has recently delisted. It means I have an order in a market that does not exist anymore. I'm guessing it's not then possible to figure out the price of this order, because ccxt would need to know where to put the decimal point in the received number, and market dictionary containing that information cannot be obtained.

I can probably fix this problem by just manually canceling the order. However, every time Waves decides to delist coin, this could happen again if the `parse_order` code is not changed somehow. Maybe in case of such orders the price and other problematic numbers could be replaced with None:s. I dunno

I also noticed that `fetch_balance` return object contained some None:s for DASH and used id instead of symbol for it:
```{..., 'B3UGHFRPSUUGEDWJQB9LWWXAFQJ8VTVPMUCEYOXZWS5H': {'free': None, 'used': ..., 'total': None}, 'timestamp': None, 'datetime': None, 'free': {..., 'B3UGHFRPSUUGEDWJQB9LWWXAFQJ8VTVPMUCEYOXZWS5H': None}, 'used': {..., 'B3UGHFRPSUUGEDWJQB9LWWXAFQJ8VTVPMUCEYOXZWS5H': ...}, 'total': {..., B3UGHFRPSUUGEDWJQB9LWWXAFQJ8VTVPMUCEYOXZWS5H': None}}```

Perhaps there is some hope that in this case the balances could be figured out as there is this kind of stuff in totalBalance dictionary obtained in line 1534 of wavesexchange.py:
`{'assetId': 'B3uGHFRpSUuGEDWjqB9LWWxafQj8VTvpMucEyoxzws5H', 'reissuable': False, 'minSponsoredAssetFee': None, 'sponsorBalance': None, 'quantity': '...', 'issueTransaction': {'type': '3', 'id': 'B3uGHFRpSUuGEDWjqB9LWWxafQj8VTvpMucEyoxzws5H', 'sender': '...', 'senderPublicKey': '...', 'fee': '...', 'feeAssetId': None, 'timestamp': '...', 'proofs': ['...'], 'signature': '...', 'version': '1', 'assetId': 'B3uGHFRpSUuGEDWjqB9LWWxafQj8VTvpMucEyoxzws5H', 'name': 'DASH', 'quantity': '...', 'reissuable': False, 'decimals': '8', 'description': 'DASH token'}, 'balance': '...'}`

 Most notably, name DASH and the number of decimals are included.

**Comment by JovianMoon** [comment]
Just wanted to make an update here that `fetch_open_orders` started working for me again some days ago. I have no idea what happened to the problematic DASH/BTC order, but I can tell that I can't see that order anymore on the waves exchange website on my account. Unfortunately I can't really be sure if the underlying issue got actually resolved or not.

**Comment by ttodua** [comment]
closing an old issue, as it seems the last time it was working.
if anyone still has any issues, let us know.
