### ISSUE TITLE
kucoinfutures fetch_open_orders

### ISSUE THREAD

**Issue by leastchaos** [ccxt/ccxt#13274]
Hi,
I am encountering the following error when using order functions for kucoinfutures

- OS: Linux
- Programming Language version: Python 3.10
- CCXT version: 1.1.29

```
import asyncio
import ccxtpro
from pprint import pprint
import sys
# sys.stdout = open('error', 'w')
print(ccxtpro.__version__)
symbol = 'BTC/USDT:USDT'
exchange: ccxtpro.Exchange = getattr(ccxtpro, 'kucoinfutures')({
    'enableRateLimit': True,
    'apiKey': '',
    'secret': '',
    'password': '',
    'options': {
        'defaultType': 'future', #future / swap
    }
})
# exchange.set_sandbox_mode(True)
# exchange.verbose=True
async def main():
    try:
        response = await exchange.fetch_closed_orders(symbol)
        pprint(response)
    finally:
        await exchange.close()

asyncio.run(main())
```

```
Traceback (most recent call last):
  File "/root/wc/ccxt_fetcher/experiment/kucoinfutures_fetch_open_orders.py", line 33, in <module>
    asyncio.run(main())
  File "/root/miniconda3/envs/ccxtfetcher/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/ccxtfetcher/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/wc/ccxt_fetcher/experiment/kucoinfutures_fetch_open_orders.py", line 29, in main
    response = await exchange.fetch_closed_orders()
  File "/root/miniconda3/envs/ccxtfetcher/lib/python3.10/site-packages/ccxt/async_support/kucoinfutures.py", line 1120, in fetch_closed_orders
    return await self.fetch_orders_by_status('done', symbol, since, limit, params)
  File "/root/miniconda3/envs/ccxtfetcher/lib/python3.10/site-packages/ccxt/async_support/kucoinfutures.py", line 1103, in fetch_orders_by_status
    response = await getattr(self, method)(self.extend(request, params))
  File "/root/miniconda3/envs/ccxtfetcher/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 105, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/miniconda3/envs/ccxtfetcher/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 170, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/miniconda3/envs/ccxtfetcher/lib/python3.10/site-packages/ccxt/async_support/kucoin.py", line 2446, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/root/miniconda3/envs/ccxtfetcher/lib/python3.10/site-packages/ccxt/base/exchange.py", line 560, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: kucoinfutures error.field.endAt.invalidValue
kucoinfutures requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0f7ba0bd30>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f0f7b851600>, 6528835.413531557)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f0f7ba0bdc0>
```
verbose

[verb.txt](https://github.com/ccxt/ccxt/files/8701377/verb.txt)

**Comment by samgermain** [comment]
I think the problem is that your using a `fetch` method within a never ending loop. While this is what you are supposed to do for the `watch` methods, which use sockets, the fetch methods access the rest api and aren't meant to be called continuously, the line `    await exchange.close()` is actually never getting executed because your while loop never ends

**Comment by leastchaos** [comment]
Hi, I think it should be ok to do this for ccxt as I remembered seeing one of the example mentioned by kroitor which places the fetch directly in the while loop and letting the throttler adjust the call rate.

https://github.com/ccxt/ccxt/blob/master/examples/py/binance-poll-balance.py

The issue is with this error I think
`ccxt.base.errors.InvalidOrder: kucoinfutures error.field.endAt.invalidValue`
This code works on other exchanges.

I understand the await exchange.close() is not executed as there is no break, this is a sample template on the code that does not work but i forgot to remove it. i removed the unnecessary loop in the example

**Comment by samgermain** [comment]
So the code above can't be your full program, I'm getting `Name "account_infos" is not defined` with it
`

**Comment by leastchaos** [comment]
Hi account_infos is just a helper method for me to get my credentials, need to replaced those parts with a valid API key or based on comments i placed at the side. 

i updated the code to remove it.

**Comment by leastchaos** [comment]
any updates on this issue?
