### ISSUE TITLE
Issue while trying to call bitfinex funding offer submit API bitfinex2 symbol: invalid

### ISSUE THREAD

**Issue by GatsbyHuang** [ccxt/ccxt#13353]
Hi , 
I am trying to call bitfinex funding offer submit endpoint (auth/w/funding/offer/submit) and got  bitfinex2 symbol: invalid error.

1) API permission is OK , I've already turn on the funding offer permission
2) I can successfully call public API (wallet balance), cancel funding offer orders API (private)
3) submitFundingOffer("fUSD",150,0.012,2)
   My input symbol is fUSD should be an correct symbol.
4) I found that in exchange.py method fetch2
   the last line return self.fetch function , in that line request['body'] is already empty, I guess it might cause this issue? 
   But I try to append that correct body json and pass to fecth2 still got errors. Please help on this case.
5) my full body json string: 
   {'type': 'LIMIT', 'symbol': 'fUSD', 'amount': '150', 'rate': '0.012', 'period': 2, 'flags': 4096}

- OS: Windows 10
- Programming Language version: Python 3
- CCXT version: latest

```
def submitFundingOffer(sym,amount,rate,period,type="LIMIT"):
    print("in submitFundingOffer")
    path = "auth/w/funding/offer/submit"
    body = { 'type': str(type), 'symbol':str(sym),'amount':str(amount),'rate':str(rate),'period':period, 'flags':4096}

    print(body)

    result = bitfinex.request(path, api='private', method='POST', params={}, headers=None, body=str(body))
    print(result)
```

```
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 666, in fetch
    response.raise_for_status()
  File "C:\Users\User\PycharmProjects\pythonProject\venv\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.bitfinex.com/v2/auth/w/funding/offer/submit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/pythonProject/bitfinexfunding.py", line 217, in <module>
    submitFundingOffer("fUSD",150,0.012,2)
  File "C:/Users/User/PycharmProjects/pythonProject/bitfinexfunding.py", line 169, in submitFundingOffer
    result = bitfinex.request(path, api='private', method='POST', params={}, headers=None, body=str(body))
  File "C:\Users\User\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 556, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\User\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 552, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\User\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 682, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\User\PycharmProjects\pythonProject\ccxt\bitfinex2.py", line 1887, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "C:\Users\User\PycharmProjects\pythonProject\ccxt\base\exchange.py", line 570, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.PermissionDenied: bitfinex2 symbol: invalid
```

**Comment by ttodua** [comment]
You are doing in a hard-way. There is already simplified functionality in CCXT for any endpoint, with [Implicit API](https://docs.ccxt.com/en/latest/manual.html#implicit-api). Please spend few mins to read it to use CCXT better. 

so, it can be done i.e.:
```
var res = await e.privatePostAuthWFundingOfferSubmit( {'type': 'LIMIT', .......}  ); 
```

Let us know if you have any further issue with CCXT.
