### ISSUE TITLE
ccxt.base.errors.ExchangeNotAvailable: gateio {"label":"INTERNAL","detail":"thread-sync"}

### ISSUE THREAD

**Issue by achow113** [ccxt/ccxt#13375]
- OS: window 10
- Programming Language version:
- CCXT version: CCXT Version: 1.83.25

Not sure how to solve this  gateio {"label":"INTERNAL","detail":"thread-sync"}

```
Traceback (most recent call last):
  File "c:/Users/A/Desktop/Bybit/BTCUSDT/0.cctxpro_btcusdt_call_v2.py", line 69, in <module>
    retry(main(), max_tries=100)
  File "c:/Users/A/Desktop/Bybit/BTCUSDT/0.cctxpro_btcusdt_call_v2.py", line 46, in main
    asyncio.get_event_loop().run_until_complete(btcusdt_call_us(timezone_now))
  File "C:\Users\A\anaconda3\envs\p37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\Users\A\Desktop\Bybit\BTCUSDT\cctxpro_btcusdt_call_US.py", line 223, in btcusdt_call_us
    bid_ask_orderbook = await exchange.fetch_order_book(symbol)
  File "C:\Users\A\anaconda3\envs\p37\lib\site-packages\ccxt\async_support\gateio.py", line 1695, in fetch_order_book
    response = await getattr(self, method)(self.extend(request, query))
  File "C:\Users\A\anaconda3\envs\p37\lib\site-packages\ccxt\async_support\base\exchange.py", line 106, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\A\anaconda3\envs\p37\lib\site-packages\ccxt\async_support\base\exchange.py", line 171, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\A\anaconda3\envs\p37\lib\site-packages\ccxt\async_support\gateio.py", line 3991, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], label, feedback)
  File "C:\Users\A\anaconda3\envs\p37\lib\site-packages\ccxt\base\exchange.py", line 562, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeNotAvailable: gateio {"label":"INTERNAL","detail":"thread-sync"}
gateio requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000221AB7BC3C8>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000221AB8B4908>, 122911.218)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000221AB7BC408>
```

**Comment by sc0Vu** [comment]
I think that means python runtime was going to remove the gateio exchange object, and the connection wasn't closed. Would you like to close the connection?

**Comment by achow113** [comment]
@sc0Vu You mean the error of `ccxt.base.errors.ExchangeNotAvailable: gateio {"label":"INTERNAL","detail":"thread-sync"}`
is due to the closing of connection?
but i have added `await exchange.close()` at the end.

**Comment by ttodua** [comment]
@achow113 you should provide some demonstrational snippet/code. 
https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by frosty00** [comment]
```
ccxt.base.errors.ExchangeNotAvailable: gateio {"label":"INTERNAL","detail":"thread-sync"}
```

this error seems to be a gateway error specific to gateio - not much we can do about that on the client side
