### ISSUE TITLE
Bitget fetch_tickers() 'symbol' parsed incorrectly?

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#13388]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 1.83.47

```
exchange = ccxt.bitget()
print(exchange.fetch_tickers())
```

```
{'LINKUSDT': {'symbol': 'LINKUSDT', 'timestamp': 1653161452048, 'datetime': '2022-05-21T19:30:52.048Z', 'high': 7.1182, 'low': 7.0119, 'bid': 7.0102, 'bidVolume': None, 'ask': 7.026, 'askVolume': None, 'vwap': 6.9666219371018165, 'open': None, 'close': 7.0151, 'last': 7.0151, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': 48568.175, 'quoteVolume': 338356.1134, 'info': {'symbol': 'LINKUSDT', 'high24h': '7.1182', 'low24h': '7.0119', 'close': '7.0151', 'quoteVol': '338356.1134', ...}
```

By default `fetch_tickers` seems to fetch tickers for the spot markets. Also, `fetch_markets` returns this kind of stuff: 
```
...
{'info': {'symbol': 'LINKUSDT_SPBL', 'symbolName': 'LINKUSDT', 'baseCoin': 'LINK', 'quoteCoin': 'USDT', 'minTradeAmount': '0', 'maxTradeAmount': '0', 'takerFeeRate': '0.002', 'makerFeeRate': '0.002', 'priceScale': '4', 'quantityScale': '4', 'status': 'online'}, 'id': 'LINKUSDT_SPBL', 'symbol': 'LINK/USDT', 'quoteId': 'USDT', 'baseId': 'LINK', 'quote': 'USDT', 'base': 'LINK', 'type': 'spot', 'spot': True, 'swap': False, 'future': False, 'option': False, 'margin': False, 'contract': False, 'contractSize': None, 'linear': None, 'inverse': None, 'settleId': None, 'settle': None, 'expiry': None, 'expiryDatetime': None, 'optionType': None, 'strike': None, 'active': True, 'maker': 0.002, 'taker': 0.002, 'precision': {'price': 0.0001, 'amount': 0.0001}, 'limits': {'amount': {'min': 0.0, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}}
...
{'info': {'symbol': 'LINKUSDT_UMCBL', 'makerFeeRate': '0.0002', 'takerFeeRate': '0.0006', 'feeRateUpRatio': '0.005', 'openCostUpRatio': '0.01', 'quoteCoin': 'USDT', 'baseCoin': 'LINK', 'buyLimitPriceRatio': '0.02', 'sellLimitPriceRatio': '0.02', 'supportMarginCoins': ['USDT'], 'minTradeNum': '1', 'priceEndStep': '1', 'volumePlace': '0', 'pricePlace': '3'}, 'id': 'LINKUSDT_UMCBL', 'symbol': 'LINK/USDT:USDT', 'quoteId': 'USDT', 'baseId': 'LINK', 'quote': 'USDT', 'base': 'LINK', 'type': 'swap', 'spot': False, 'swap': True, 'future': False, 'option': False, 'margin': False, 'contract': True, 'contractSize': None, 'linear': True, 'inverse': False, 'settleId': 'USDT', 'settle': 'USDT', 'expiry': None, 'expiryDatetime': None, 'optionType': None, 'strike': None, 'active': None, 'maker': 0.0002, 'taker': 0.0006, 'precision': {'price': 0.001, 'amount': 1.0}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}},
...
```
It would therefore seem that the returned ticker symbol in this case should be 'LINK/USDT' instead of 'LINKUSDT'.

Swap markets have similar problem:
```
exchange = ccxt.bitget()
print(exchange.fetch_tickers(params={'type': 'swap'}))
```

```
'LINKUSDT_UMCBL': {'symbol': 'LINKUSDT_UMCBL', 'timestamp': 1653162064919, 'datetime': '2022-05-21T19:41:04.919Z', 'high': 7.114, 'low': 7.005, 'bid': 7.038, 'bidVolume': None, 'ask': 7.041, 'askVolume': None, 'vwap': 6.957877856073359, 'open': 7.06194714, 'close': 7.039, 'last': 7.039, 'previousClose': None, 'change': -0.02294714, 'percentage': -0.326, 'average': None, 'baseVolume': 236426.0, 'quoteVolume': 1645023.23, 'info': {'symbol': 'LINKUSDT_UMCBL', 'last': '7.039', 'bestAsk': '7.041', 'bestBid': '7.038', 'high24h': '7.114', 'low24h': '7.005', 'timestamp': '1653162064919', 'priceChangePercent': '-0.00326', 'baseVolume': '236426', 'quoteVolume': '1645023.23', 'usdtVolume': '1645023.23'}},
```

I assume 'symbol' is supposed to be 'LINK/USDT:USDT' in there.

I did not check any other exchange methods involving symbols, but maybe it would be worth a while to take a look at those too?

**Comment by kroitor** [comment]
Works for me with CCXT version 1.83.53:

```Python
import ccxt


def table(values):
    first = values[0]
    keys = list(first.keys()) if isinstance(first, dict) else range(0, len(first))
    widths = [max([len(str(v[k])) for v in values]) for k in keys]
    string = ' | '.join(['{:<' + str(w) + '}' for w in widths])
    return "\n".join([string.format(*[str(v[k]) for k in keys]) for v in values])


exchange = ccxt.bitget()
markets = exchange.load_markets()
print(table(list(exchange.markets.values())))
```

-----------------------

```
node examples/js/cli bitget markets --table | less -S -R
```

```
2022-05-22T14:50:23.647Z
Node.js: v16.13.2
CCXT v1.83.52
               id |             symbol |          base | quote |   baseId | quoteId | active | type | linear | inverse |  spot |  swap | future | option | margin | contract | contractSize | expiry | expiryDatetime | optionType | strike | settle | settle
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    CUSDUSDT_SPBL |          CUSD/USDT |          CUSD |  USDT |     CUSD |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
   ALPHAUSDT_SPBL |         ALPHA/USDT |         ALPHA |  USDT |    ALPHA |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    QRDOUSDT_SPBL |          QRDO/USDT |          QRDO |  USDT |     QRDO |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     SLPUSDT_SPBL |           SLP/USDT |           SLP |  USDT |      SLP |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    BRWLUSDT_SPBL |          BRWL/USDT |          BRWL |  USDT |     BRWL |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    GALAUSDT_SPBL |          GALA/USDT |          GALA |  USDT |     GALA |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    WAXPUSDT_SPBL |          WAXP/USDT |          WAXP |  USDT |     WAXP |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
BABYDOGEUSDT_SPBL |      BABYDOGE/USDT |      BABYDOGE |  USDT | BABYDOGE |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    DERCUSDT_SPBL |          DERC/USDT |          DERC |  USDT |     DERC |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
   MULTIUSDT_SPBL |         MULTI/USDT |         MULTI |  USDT |    MULTI |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     JUVUSDT_SPBL |           JUV/USDT |           JUV |  USDT |      JUV |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    SANDUSDT_SPBL |          SAND/USDT |          SAND |  USDT |     SAND |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    KLAYUSDT_SPBL |          KLAY/USDT |          KLAY |  USDT |     KLAY |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
   ALICEUSDT_SPBL |         ALICE/USDT |         ALICE |  USDT |    ALICE |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    USDCUSDT_SPBL |          USDC/USDT |          USDC |  USDT |     USDC |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     TLMUSDT_SPBL |           TLM/USDT |           TLM |  USDT |      TLM |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
   AUDIOUSDT_SPBL |         AUDIO/USDT |         AUDIO |  USDT |    AUDIO |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     C98USDT_SPBL |           C98/USDT |           C98 |  USDT |      C98 |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    TLOSUSDT_SPBL |          TLOS/USDT |          TLOS |  USDT |     TLOS |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    LINAUSDT_SPBL |          LINA/USDT |          LINA |  USDT |     LINA |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     ENJUSDT_SPBL |           ENJ/USDT |           ENJ |  USDT |      ENJ |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    MANAUSDT_SPBL |          MANA/USDT |          MANA |  USDT |     MANA |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     XRPUSDT_SPBL |           XRP/USDT |           XRP |  USDT |      XRP |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     BTCUSDT_SPBL |           BTC/USDT |           BTC |  USDT |      BTC |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     ETHUSDT_SPBL |           ETH/USDT |           ETH |  USDT |      ETH |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
      ETHBTC_SPBL |            ETH/BTC |           ETH |   BTC |      ETH |     BTC |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     LTCUSDT_SPBL |           LTC/USDT |           LTC |  USDT |      LTC |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     BCHUSDT_SPBL |           BCH/USDT |           BCH |  USDT |      BCH |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     ILVUSDT_SPBL |           ILV/USDT |           ILV |  USDT |      ILV |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
   WEMIXUSDT_SPBL |         WEMIX/USDT |         WEMIX |  USDT |    WEMIX |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    EDENUSDT_SPBL |          EDEN/USDT |          EDEN |  USDT |     EDEN |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
 JUSTICEUSDT_SPBL |       JUSTICE/USDT |       JUSTICE |  USDT |  JUSTICE |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
      FILBTC_SPBL |            FIL/BTC |           FIL |   BTC |      FIL |     BTC |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     TRXUSDT_SPBL |           TRX/USDT |           TRX |  USDT |      TRX |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    RSS3USDT_SPBL |          RSS3/USDT |          RSS3 |  USDT |     RSS3 |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     SMGUSDT_SPBL |           SMG/USDT |           SMG |  USDT |      SMG |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    LINKUSDT_SPBL |          LINK/USDT |          LINK |  USDT |     LINK |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     ANTUSDT_SPBL |           ANT/USDT |           ANT |  USDT |      ANT |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     UNIUSDT_SPBL |           UNI/USDT |           UNI |  USDT |      UNI |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    ARPAUSDT_SPBL |          ARPA/USDT |          ARPA |  USDT |     ARPA |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
   SUSHIUSDT_SPBL |         SUSHI/USDT |         SUSHI |  USDT |    SUSHI |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    BUSDUSDT_SPBL |          BUSD/USDT |          BUSD |  USDT |     BUSD |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    COMPUSDT_SPBL |          COMP/USDT |          COMP |  USDT |     COMP |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    REALUSDT_SPBL |          REAL/USDT |          REAL |  USDT |     REAL |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    AAVEUSDT_SPBL |          AAVE/USDT |          AAVE |  USDT |     AAVE |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    DUSKUSDT_SPBL |          DUSK/USDT |          DUSK |  USDT |     DUSK |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     YFIUSDT_SPBL |           YFI/USDT |           YFI |  USDT |      YFI |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    DOGEUSDT_SPBL |          DOGE/USDT |          DOGE |  USDT |     DOGE |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     CHZUSDT_SPBL |           CHZ/USDT |           CHZ |  USDT |      CHZ |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     ETCUSDT_SPBL |           ETC/USDT |           ETC |  USDT |      ETC |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     EOSUSDT_SPBL |           EOS/USDT |           EOS |  USDT |      EOS |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    SHIBUSDT_SPBL |          SHIB/USDT |          SHIB |  USDT |     SHIB |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
   MATICUSDT_SPBL |         MATIC/USDT |         MATIC |  USDT |    MATIC |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
   1INCHUSDT_SPBL |         1INCH/USDT |         1INCH |  USDT |    1INCH |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     MKRUSDT_SPBL |           MKR/USDT |           MKR |  USDT |      MKR |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     RENUSDT_SPBL |           REN/USDT |           REN |  USDT |      REN |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     UMAUSDT_SPBL |           UMA/USDT |           UMA |  USDT |      UMA |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     ZRXUSDT_SPBL |           ZRX/USDT |           ZRX |  USDT |      ZRX |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    TORNUSDT_SPBL |          TORN/USDT |          TORN |  USDT |     TORN |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    X2Y2USDT_SPBL |          X2Y2/USDT |          X2Y2 |  USDT |     X2Y2 |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
   ATLASUSDT_SPBL |         ATLAS/USDT |         ATLAS |  USDT |    ATLAS |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     FTMUSDT_SPBL |           FTM/USDT |           FTM |  USDT |      FTM |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     WOOUSDT_SPBL |           WOO/USDT |           WOO |  USDT |      WOO |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    AURYUSDT_SPBL |          AURY/USDT |          AURY |  USDT |     AURY |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     TAPUSDT_SPBL |           TAP/USDT |           TAP |  USDT |      TAP |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     1SQUSDT_SPBL |           1SQ/USDT |           1SQ |  USDT |      1SQ |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     FTTUSDT_SPBL |           FTT/USDT |           FTT |  USDT |      FTT |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
    GODSUSDT_SPBL |          GODS/USDT |          GODS |  USDT |     GODS |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     WINUSDT_SPBL |           WIN/USDT |           WIN |  USDT |      WIN |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     UFOUSDT_SPBL |           UFO/USDT |           UFO |  USDT |      UFO |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
     SUNUSDT_SPBL |           SUN/USDT |           SUN |  USDT |      SUN |    USDT |   true | spot |        |         |  true | false |  false |  false |  false |    false |              |        |                |            |        |        |
...
```

Check these links:

- https://docs.ccxt.com/en/latest/manual.html#symbols-and-market-ids
- https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions

Let us know if the above does not answer your question.

**Comment by JovianMoon** [comment]
@kroitor The problem is with `fetch_tickers` symbols not with `fetch_markets` symbols

**Comment by JovianMoon** [comment]
@kroitor Spot market ticker symbols look good now with 1.83.55. There are some weird abominations in swap tickers though (but most look fine):

```
exchange = ccxt.bitget()
exchange.load_markets()
print(exchange.fetch_tickers(params={'type': 'swap'}))
```
```
...
'GALUSDT_UMCBL_SPBL': {'symbol': 'GALUSDT_UMCBL_SPBL', 'timestamp': 1653239580882, 'datetime': '2022-05-22T17:13:00.882Z', 'high': 6.971, 'low': 6.623, 'bid': 6.933, 'bidVolume': None, 'ask': 6.942, 'askVolume': None, 'vwap': 6.227649544209432, 'open': 6.8785491, 'close': 6.935, 'last': 6.935, 'previousClose': None, 'change': 0.0564509, 'percentage': 0.814, 'average': None, 'baseVolume': 132886.69, 'quoteVolume': 827571.73441, 'info': {'symbol': 'GALUSDT_UMCBL', 'last': '6.935', 'bestAsk': '6.942', 'bestBid': '6.933', 'high24h': '6.971', 'low24h': '6.623', 'timestamp': '1653239580882', 'priceChangePercent': '0.00814', 'baseVolume': '132886.69', 'quoteVolume': '827571.73441', 'usdtVolume': '827571.73441'}}
...
```
Not sure what they are about.

Also, probably `self.load_markets` should be added somewhere in `fetch_tickers`, because if I'm not using `exchange.load_markets()` I get an error:

```
Traceback (most recent call last):
  File "/home/xyz/test.py", line 5, in <module>
    print(exchange.fetch_tickers(params={'type': 'swap'}))
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bitget.py", line 1304, in fetch_tickers
    return self.parse_tickers(data, symbols)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2111, in parse_tickers
    result.append(self.extend(self.parse_ticker(values[i]), params))
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bitget.py", line 1164, in parse_ticker
    if not (marketId in self.markets_by_id):
TypeError: argument of type 'NoneType' is not iterable

```
