### ISSUE TITLE
 Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, ccxt\huobi given in repos/huobi-bot/vendor/ccxt/ccxt/php/Exchange.php:1821

### ISSUE THREAD

**Issue by Layn** [ccxt/ccxt#13400]
Hello,

I'm trying to make ccxt works but I think I get a very basic error.

- OS: Debian Bookworm
- Programming Language version: PHP 8.1.5
- CCXT version:         "ccxt/ccxt": "^1.16"

```
<?php
require_once __DIR__.'/vendor/autoload.php';

$exchange = new \ccxt\huobi(
    [
        'apiKey' => 'aaaaaaaaaaaaaa',
        'secret' => 'ssssssssssssss',
    ]
);
$exchange->load_markets();
print_r($exchange->fetch_markets());

print_r($
```

```
Array
(
    [0] => Array
        (
            [precision] => Array
                (
                )

            [limits] => Array
                (
                )

            [id] => btc
            [symbol] => BTC/CNY
            [base] => BTC
            [quote] => CNY
            [type] => staticmarket
            [coinType] => 1
        )

    [1] => Array
        (
            [precision] => Array
                (
                )

            [limits] => Array
                (
                )

            [id] => ltc
            [symbol] => LTC/CNY
            [base] => LTC
            [quote] => CNY
            [type] => staticmarket
            [coinType] => 2
        )

)
PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, ccxt\huobi given in /repos/huobi-bot/vendor/ccxt/ccxt/php/Exchange.php:1821
Stack trace:
#0 /repos/huobi-bot/vendor/ccxt/ccxt/php/Exchange.php(1821): array_key_exists()
#1 /repos/huobi-bot/vendor/ccxt/ccxt/php/huobi.php(91): ccxt\Exchange->__call()
#2 /repos/huobi-bot/bot.php(13): ccxt\huobi->fetch_balance()
#3 {main}
  thrown in /repos/huobi-bot/vendor/ccxt/ccxt/php/Exchange.php on line 1821
```

There are two problems there, beside the PHP Fatal, I also find weird that the load_markets() only returns 2 markets.

**Comment by Layn** [comment]
Sorry, about that, that was just the print of fetch_balance():

`print_r($exchange->fetch_balance());`

But also, check this more simple code, I get the same error:


```
<?php
require_once __DIR__.'/vendor/ccxt/ccxt/ccxt.php';

$exchange_id = 'binance';
$exchange_class = "\\ccxt\\$exchange_id";
$exchange = new $exchange_class (array (
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
));

$exchange->load_markets();
```

Output:

```
PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, ccxt\binance given in /repos/huobi-bot/vendor/ccxt/ccxt/php/Exchange.php:1821
Stack trace:
#0 /repos/huobi-bot/vendor/ccxt/ccxt/php/Exchange.php(1821): array_key_exists()
#1 /repos/huobi-bot/vendor/ccxt/ccxt/php/binance.php(299): ccxt\Exchange->__call()
#2 /repos/huobi-bot/vendor/ccxt/ccxt/php/Exchange.php(1164): ccxt\binance->fetch_markets()
#3 /repos/huobi-bot/bot.php(11): ccxt\Exchange->load_markets()
#4 {main}
  thrown in /repos/huobi-bot/vendor/ccxt/ccxt/php/Exchange.php on line 1821
```

The error is the same.

**Comment by Layn** [comment]
Not sure why it installed this version, I'll try to install the last one. And come back with the verbose output, may be that.

**Comment by Layn** [comment]
All good, for some reason when I did:
`composer require ccxt/ccxt`
It installed that old version.
With the new version all is good. Thanks.
