### ISSUE TITLE
AuthenticationError - Unable to use Kucoin sandbox with valid credentials

### ISSUE THREAD

**Issue by parliament718** [ccxt/ccxt#13447]
- OS: MacOS 11.6
- Programming Language version: node v16.10.0
- CCXT version: 1.1.42

```
const exchangeRef = new ccxt.kucoin({
   apiKey: "...",
   secret: "...",
   password: "..."
});

exchangeRef.setSandboxMode(true);

if (exchangeRef.has.fetchClosedOrders) {
   try {
      const closedOrders = await exchangeRef.fetchClosedOrders()
      console.log('API closedOrders', closedOrders);
   } catch (e) {
      console.log(e)
   }
}
```

```
AuthenticationError: kucoin KC-API-KEY not exists
    at kucoin.throwExactlyMatchedException (/Users/admin/code/ccxt-test/node_modules/ccxt/js/base/Exchange.js:648:19)
    at kucoin.handleErrors (/Users/admin/code/ccxt-test/node_modules/ccxt/js/kucoin.js:2654:14)
    at /Users/admin/code/ccxt-test/node_modules/ccxt/js/base/Exchange.js:725:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/Users/admin/code/ccxt-test/node_modules/ccxt/js/base/functions/time.js:203:20)
    at async kucoin.fetchOrdersByStatus (/Users/admin/code/ccxt-test/node_modules/ccxt/js/kucoin.js:1388:26)
    at async kucoin.fetchClosedOrders (/Users/admin/code/ccxt-test/node_modules/ccxt/js/kucoin.js:1452:16)
    at async main (/Users/admin/code/ccxt-test/index.js:33:34) {
  constructor: [class AuthenticationError extends ExchangeError]
}
```

**Comment by kroitor** [comment]
@parliament718 do you use the kucoin API keys with it or the kucoin testnet API keys?

**Comment by parliament718** [comment]
My apologies, I was indeed using the sandbox API keys, same ones that I used a couple days ago to successfully fetch balances, but it turns out those keys were magically deleted from my Kucoin account. 

Do you know if Kucoin regularly deletes sandbox keys?

I just created new sandbox keys and no auth error, but for some reason I still cant fetch closed orders.
I have filled orders from just 10 days ago in my Orders History shown below, do I need to provide additional parameters to fetchClosedOrders() to retreive these? 


![Screen Shot 2022-05-27 at 10 34 41 AM](https://user-images.githubusercontent.com/3580270/170652905-dc6b3692-f118-42bf-8c78-e3fb98153d8b.png)
