### ISSUE TITLE
CoinEx fetch_markets() ccxt.base.errors.AuthenticationError: coinex requires `apiKey`

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#13489]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 1.84.39

CoinEx seems to be the only exchange that requires 'apiKey' and 'secret' for `fetch_markets`:

```
exchange = ccxt.coinex()
print(exchange.fetch_markets())
```

```
Traceback (most recent call last):
  File "/home/xyz/test.py", line 4, in <module>
    print(exchange.fetch_markets())
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/coinex.py", line 378, in fetch_markets
    result = self.fetch_spot_markets(query)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/coinex.py", line 386, in fetch_spot_markets
    response = self.publicGetMarketInfo(params)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 498, in inner
    return entry(_self, **inner_kwargs)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 549, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 544, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/coinex.py", line 3593, in sign
    self.check_required_credentials()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1488, in check_required_credentials
    raise AuthenticationError(self.id + ' requires `' + key + '`')
ccxt.base.errors.AuthenticationError: coinex requires `apiKey`
```
However, if one sets nonsense values '...' for these, the call works perfectly fine:

```
exchange = ccxt.coinex({'apiKey': '...', 'secret': '...'})
print(exchange.fetch_markets())
```

```
[{'id': 'PSPUSDT', 'symbol': 'PSP/USDT', 'base': 'PSP', 'quote': 'USDT', 'settle': None, 'baseId': 'PSP', 'quoteId': 'USDT', 'settleId': None, 'type': 'spot', 'spot': True, 'margin': None, 'swap': False, 'future': False, 'option': False, 'active': None, 'contract': False, 'linear': None, 'inverse': None, 'taker': 0.003, 'maker': 0.003, 'contractSize': None, 'expiry': None, 'expiryDatetime': None, 'strike': None, 'optionType': None, 'precision': {'amount': 8, 'price': 6}, 'limits': {'leverage': {'min': None, 'max': None}, 'amount': {'min': 50.0, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'info': {'name': 'PSPUSDT', 'min_amount': '50', 'maker_fee_rate': '0.003', 'taker_fee_rate': '0.003', 'pricing_name': 'USDT', 'pricing_decimal': '6', 'trading_name': 'PSP', 'trading_decimal': '8'}},
...
```

I think ccxt uses https://api.coinex.com/v1/market/info for fetching this information, and it does not seem to require any keys. So maybe the requirement for 'apiKeys' and 'secret' could be revoked?

**Comment by pcriadoperez** [comment]
Hi @JovianMoon  Thanks for point this out. We were checking for credentials on both public and private endpoints.
I opened a PR to solve the issue (https://github.com/ccxt/ccxt/pull/13672)
