### ISSUE TITLE
[Python] Fetch OHLCV for perpetual futures on Kucoin

### ISSUE THREAD

**Issue by YuxinSUN89** [ccxt/ccxt#13537]
- OS: Mac OS
- Programming Language version: Python
- CCXT version: 1.84.70

I can fetch OHLCV for any spot. It works perfect. 
However, I CANNOT fetch OHLCV for perpetual futures. I thought the only difference between spot and Perpetual future is

spot -> "BTC/USDT"
Perpetual future ->  "BTC/USDT:USDT"

```
import pandas as pd
import numpy
import config
import ccxt
import datetime
import time
import schedule
import logging
from math import ceil, floor
pd.set_option('display.max_rows', None)
 

exchange = ccxt.kucoin({
    'apiKey' : 'my_api_key',
    'secret' : 'my_secret_key,
    'enableRateLimit': True, 
    'password': '123456',
    'options': {'defaultType': 'swap'}
})

basket = [["BTC", "BTC/USDT:USDT"]]

markets = exchange.load_markets()

def get_data(basket, limit=10, timeframe='1m'):
    for i, name in basket:
        i = exchange.fetchOHLCV(name, limit=limit, timeframe=timeframe)
        df = pd.DataFrame(i, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
    return df

new_df = get_data(basket, limit=10, timeframe='1m')
print(new_df)
```

```
Traceback (most recent call last):
  File "/Users/user/Desktop/projects/kucoin_bot/src/draft.py", line 43, in <module>
    new_df = get_data(basket, limit=10, timeframe='1m')
  File "/Users/user/Desktop/projects/kucoin_bot/src/draft.py", line 39, in get_data
    i = exchange.fetchOHLCV(name, limit=limit, timeframe=timeframe)
  File "/Users/user/Desktop/projects/kucoin_bot/venv/lib/python3.10/site-packages/ccxt/kucoin.py", line 977, in fetch_ohlcv
    market = self.market(symbol)
  File "/Users/user/Desktop/projects/kucoin_bot/venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2293, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: kucoin does not have market symbol BTC/USDT:USDT
```
I can easily fetch OHLCV for spot and I also want to fetch perpetual future. Can anyone please advise ? Thank you !

**Comment by carlosmiei** [comment]
Hello @YuxinSUN89, Kucoin has a dedicated futures class named kucoinfutures that should be used when dealing with swaps/futures. 

So for your particular case, you will need two different instances one for kucoin and another for kucoinfutures.

Example
```Python

spot_exchange = ccxt.kucoin({
    'apiKey' : 'my_api_key',
    'secret' : 'my_secret_key,
    'enableRateLimit': True, 
    'password': '123456',
})

futures_exchange = ccxt.kucoinfutures({
    'apiKey' : 'my_api_key',
    'secret' : 'my_secret_key,
    'enableRateLimit': True, 
    'password': '123456',
})

ohlcv1 = spot_exchange.fetch_ohlcv('BTC/USDT')
ohlcv2 = futures_exchange.fetch_ohlcv('BTC/USDT:USDT')
```

Feel free to reopen this issue if anything!

**Comment by YuxinSUN89** [comment]
Thank you @carlosmiei  ! 
It works like a charm !
