### ISSUE TITLE
Bitmart  - Error: invalid stored block lengths

### ISSUE THREAD

**Issue by kvlknctk** [ccxt/ccxt#13532]
Hi, Every market is running but I getting error for bitmart connect. 

```javascript 
error: Error: invalid stored block lengths
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
    at processChunkSync (node:zlib:456:12)
    at zlibBufferSync (node:zlib:178:12)
    at syncBufferWrapper (node:zlib:791:14)
    at inflate (/Users/volkancatak/Projects/sharedconfig_api/node_modules/ccxt.pro/js/base/functions.js:6:12)
    at WsClient.onMessage (/Users/volkancatak/Projects/sharedconfig_api/node_modules/ccxt.pro/js/base/Client.js:260:23)
    at WebSocket.onMessage (/Users/volkancatak/Projects/sharedconfig_api/node_modules/ccxt.pro/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:520:28)
    at Receiver.receiverOnMessage (/Users/volkancatak/Projects/sharedconfig_api/node_modules/ccxt.pro/node_modules/ws/lib/websocket.js:1047:20)
    at Receiver.emit (node:events:520:28)
    at Receiver.dataMessage (/Users/volkancatak/Projects/sharedconfig_api/node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/Users/volkancatak/Projects/sharedconfig_api/node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/Users/volkancatak/Projects/sharedconfig_api/node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/Users/volkancatak/Projects/sharedconfig_api/node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)

```

- OS: MacOS
- Programming Language version: node: v16.14.0
- CCXT version: ^1.83.69
- CCXT Pro version: 1.1.41

**Comment by carlosmiei** [comment]
Hello @kvlknctk thanks for reporting it we have already a fix for this hopefully will be merged soon

**Comment by carlosmiei** [comment]
@kvlknctk the merge was fixed. If you update your ccxt.pro to the latest the issue should be solved now. Please let us not if anything!
