### ISSUE TITLE
cancel order for kucoinfutures bug

### ISSUE THREAD

**Issue by leastchaos** [ccxt/ccxt#13541]
- OS: linux
- Programming Language version: python 3.10
- CCXT version: 1.1.53

```
import asyncio

import ccxtpro
print(ccxtpro.__version__)
exchange: ccxtpro.Exchange = getattr(ccxtpro, 'kucoinfutures')(
    {
        "enableRateLimit": True,
        "apiKey": '',
        "secret": '',
        "password": '',
        "newUpdates": False,
    }
)
async def main():
    try:
        exchange.verbose = False
        await exchange.load_markets()
        exchange.verbose = True
        order = await exchange.create_limit_buy_order('LUNA/USDT:USDT', amount=10, price=6.9)
        print(order)
        cancel_order = await exchange.cancel_order(order['id']) # does not work also with symbol = "LUNA/USDT:USDT"
        print(cancel_order)
    finally:
        await exchange.close()

asyncio.run(main())

```

```
1.1.53

fetch Request: kucoinfutures POST https://api-futures.kucoin.com/api/v1/orders RequestHeaders: {'KC-API-KEY-VERSION': '2', 'KC-API-KEY': '62993dd3b823800001db27e7', 'KC-API-TIMESTAMP': '1654221284878', 'Content-Type': 'application/json', 'KC-API-PASSPHRASE': 'V7MwXWXij3Z6WwhW5s2NjZw2zSfD6w+uIzZe/JjFCpQ=', 'KC-API-SIGN': 'k1VAzqamofemAauYc1V46Ci9PnloCv3a1ocXhE+O/nU=', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: {"clientOid":"92fbd3e1-142c-42ba-b63a-e8a58e225bb0","side":"buy","symbol":"LUNAUSDTM","type":"limit","size":10,"leverage":1,"price":"6.9"}

fetch Response: kucoinfutures POST https://api-futures.kucoin.com/api/v1/orders 200 ResponseHeaders: {'Date': 'Fri, 03 Jun 2022 01:54:45 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALB=gmCrzZCdTwfi56t7vWLTdld0x5j5lcNmX82Biwj/g89zACsKTuGkk0Jb8HwdJFAbC4uky7SkoIXCdit/jG1yQARFtx0Y+y0ti0kqg2MsWfJgWiCGe2ZBf+NmiYT6; Expires=Fri, 10 Jun 2022 01:54:44 GMT; Path=/, AWSALB=gmCrzZCdTwfi56t7vWLTdld0x5j5lcNmX82Biwj/g89zACsKTuGkk0Jb8HwdJFAbC4uky7SkoIXCdit/jG1yQARFtx0Y+y0ti0kqg2MsWfJgWiCGe2ZBf+NmiYT6; Expires=Fri, 10 Jun 2022 01:54:44 GMT; Path=/', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Strict-Transport-Security': 'max-age=9800; includeSubDomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '7154cd767a4c34f3-NRT', 'Content-Encoding': 'gzip'} ResponseBody: {"code":"200000","data":{"orderId":"629969e475470d0001c3b995"}}
{'id': '629969e475470d0001c3b995', 'clientOrderId': None, 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'symbol': None, 'type': None, 'side': None, 'price': None, 'amount': None, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None, 'timeInForce': None, 'postOnly': None, 'stopPrice': None, 'info': {'code': '200000', 'data': {'orderId': '629969e475470d0001c3b995'}}}

fetch Request: kucoinfutures DELETE https://api-futures.kucoin.com/api/v1/orders/{order-id}?orderId=629969e475470d0001c3b995 RequestHeaders: {'KC-API-KEY-VERSION': '2', 'KC-API-KEY': '62993dd3b823800001db27e7', 'KC-API-TIMESTAMP': '1654221285095', 'KC-API-PASSPHRASE': 'V7MwXWXij3Z6WwhW5s2NjZw2zSfD6w+uIzZe/JjFCpQ=', 'KC-API-SIGN': 'ShZ2y6qYtnOtljf8W2Eh8hIJ9p4aZjXsWiTkohF6aeU=', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: kucoinfutures DELETE https://api-futures.kucoin.com/api/v1/orders/{order-id}?orderId=629969e475470d0001c3b995 400 ResponseHeaders: {'Date': 'Fri, 03 Jun 2022 01:54:45 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALB=sS2h0aIdF69ei+2/cSPCN4oBJuOtc0yq4jpFcULLyJCaOlyfJhH5c9fR6VCQy5m3KawRs8Jv5j+DXXSJuzK9owTJEEl9YZTDhF1zsEIwjq/wTNXlwMlapzbL9xh8; Expires=Fri, 10 Jun 2022 01:54:45 GMT; Path=/, AWSALB=sS2h0aIdF69ei+2/cSPCN4oBJuOtc0yq4jpFcULLyJCaOlyfJhH5c9fR6VCQy5m3KawRs8Jv5j+DXXSJuzK9owTJEEl9YZTDhF1zsEIwjq/wTNXlwMlapzbL9xh8; Expires=Fri, 10 Jun 2022 01:54:45 GMT; Path=/', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '7154cd77db8734f3-NRT'} ResponseBody: 
Traceback (most recent call last):
  File "/root/marketmaking/experiment/exp_check_trade.py", line 30, in <module>
    asyncio.run(main())
  File "/root/miniconda3/envs/marketmaking/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/marketmaking/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/marketmaking/experiment/exp_check_trade.py", line 25, in main
    cancel_order = await exchange.cancel_order(order['id'], symbol='LUNA/USDT:USDT')
  File "/root/miniconda3/envs/marketmaking/lib/python3.10/site-packages/ccxt/async_support/kucoinfutures.py", line 1052, in cancel_order
    response = await self.futuresPrivateDeleteOrdersOrderId(self.extend(request, params))
  File "/root/miniconda3/envs/marketmaking/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 106, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/miniconda3/envs/marketmaking/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 172, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/root/miniconda3/envs/marketmaking/lib/python3.10/site-packages/ccxt/base/exchange.py", line 712, in handle_http_status_code
    raise Exception(' '.join([self.id, method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: kucoinfutures DELETE https://api-futures.kucoin.com/api/v1/orders/{order-id}?orderId=629969e475470d0001c3b995 400 Bad Request 
```

**Comment by leastchaos** [comment]
I think line 254 and line 274 in https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/kucoin.py needs to replace order-id to orderId
