### ISSUE TITLE
Can't get markets from bitmex

### ISSUE THREAD

**Issue by jl2035** [ccxt/ccxt#13603]
- OS: Ubuntu 20.04
- Programming Language version: python 3.8.10
- CCXT version: 1.84.42

The code:
```
import ccxt

bitmex   = ccxt.bitmex()
print(bitmex.id, bitmex.load_markets())
```

The output:
```
Traceback (most recent call last):
  File "getmarkets.py", line 4, in <module>
    print(bitmex.id, bitmex.load_markets())
  File "/home/user/project/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1629, in load_markets
    markets = self.fetch_markets(params)
  File "/home/user/project/venv/lib/python3.8/site-packages/ccxt/bitmex.py", line 363, in fetch_markets
    symbol = base + '/' + quote + ':' + settle
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by carlosmiei** [comment]
Hello @jl2035,

Thanks for your report, this bug was indeed fixed a few days ago, can you please update your ccxt version and try again?
