### ISSUE TITLE
bitfinex api in ccxt.pro cannot be used.

### ISSUE THREAD

**Issue by TraderWithPython** [ccxt/ccxt#13600]
- OS: win11
- Programming Language version: python3.9
- CCXT version: 1.82.43
- CCXT.pro version: 1.1.27

I know that the ccxt.pro do not have bitfinex2 api.
But the bitfinex1 api cannot use when I want to get perpetual contract info like ETH/USDT:FUSTF0.

```
# -*- coding: utf-8 -*-

import asyncio
import ccxtpro


async def __test():

    exchange = ccxtpro.bitfinex()

    orderbook = await exchange.watch_order_book("ETH/USDT:FUSTF0")
    print(orderbook)


asyncio.run(__test())
```
The error is
```
Traceback (most recent call last):
  File "C:\Users\12782\Desktop\crypto_trader\instruments\bfx\try.py", line 17, in <module>
    asyncio.run(__test())
  File "C:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\12782\Desktop\crypto_trader\instruments\bfx\try.py", line 12, in __test
    orderbook = await exchange.watch_order_book("ETH/USDT:FUSTF0")
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxtpro\bitfinex.py", line 240, in watch_order_book
    orderbook = await self.subscribe('book', symbol, self.deep_extend(request, params))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxtpro\bitfinex.py", line 46, in subscribe
    market = self.market(symbol)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 2323, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: bitfinex does not have market symbol ETH/USDT:FUSTF0
bitfinex requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000025BBBABD550>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000025BBBAA45E0>, 73019.593)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000025BBBABD520>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000025BBBABD460>
transport: <_ProactorSocketTransport fd=696 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000025BBA347DC0>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\ProgramData\Anaconda3\lib\asyncio\sslproto.py", line 316, in close
  File "C:\ProgramData\Anaconda3\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\ProgramData\Anaconda3\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\ProgramData\Anaconda3\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\ProgramData\Anaconda3\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

If I use bitfinex2 api in ccxt, we can see the symbol is existed.
```
# -*- coding: utf-8 -*-

import asyncio
import ccxtpro


async def __test():

    exchange = ccxtpro.bitfinex2()
    tickers = await exchange.fetch_tickers()
    print(tickers)
    await exchange.close()


asyncio.run(__test())

```

```
'ETC/USDT:FUSTF0': {'symbol': 'ETC/USDT:FUSTF0', 'timestamp': 1654421138721, 'datetime': '2022-06-05T09:25:38.721Z', 'high': 22.037, 'low': 21.56, 'bid': 21.785, 'bidVolume': None, 'ask': 21.816, 'askVolume': None, 'vwap': None, 'open': 21.966, 'close': 21.817, 'last': 21.817, 'previousClose': None, 'change': -0.149, 'percentage': -0.68, 'average': None, 'baseVolume': 944.80391373, 'quoteVolume': None, 'info': ['tETCF0:USTF0', '21.785', '6443.01504449', '21.816', '2986.27104551', '-0.149', '-0.0068', '21.817', '944.80391373', '22.037', '21.56']}
```

**Comment by carlosmiei** [comment]
Hello @TraderWithPython I'm pretty sure that is a bug in bitfinex2 markets structure (I've already opened a PR to fix it). The correct unified symbol, in this case, should be `ETC/USDT:USDT` however ccxt.pro is not yet using bitfinex2 that supports derivative markets and bitfinex v1 supports spot only so you can't use it with swaps for now. I intend to upgrade it very soon.

**Comment by TraderWithPython** [comment]
> Hello @TraderWithPython I'm pretty sure that is a bug in bitfinex2 markets structure (I've already opened a PR to fix it). The correct unified symbol, in this case, should be `ETC/USDT:USDT` however ccxt.pro is not yet using bitfinex2 that supports derivative markets and bitfinex v1 supports spot only so you can't use it with swaps for now. I intend to upgrade it very soon. 

Thank you very much.

**Comment by Kinzowa** [comment]
Hi @carlosmiei, an news about this update ? 

Thanks!

> Hello @TraderWithPython I'm pretty sure that is a bug in bitfinex2 markets structure (I've already opened a PR to fix it). The correct unified symbol, in this case, should be `ETC/USDT:USDT` however ccxt.pro is not yet using bitfinex2 that supports derivative markets and bitfinex v1 supports spot only so you can't use it with swaps for now. I intend to upgrade it very soon.
