### ISSUE TITLE
Errors with modified async-basic.py

### ISSUE THREAD

**Issue by HeinrichKg** [ccxt/ccxt#13719]
OS: Windows 10
Programming Language version: Python 3.10.
CCXT version: 1.85.85
Exchange: Binance

Hi, I am stuck with async on Binance. I get wanted result, but also I get toooo many errors. What I don't do well?

I use code from one of examples https://github.com/ccxt/ccxt/blob/master/examples/py/async-basic.py

I have changed line : 
    markets = await exchange.load_markets()
with line 
    orderbook = await exchange.fetch_order_book('LTC/BTC', limit=1)

and also return markets with return orderbook.

Here is my code, and result I get:

```
# -*- coding: utf-8 -*-

import asyncio
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async_support as ccxt  # noqa: E402


async def test_binance():
    exchange = ccxt.binance()
    orderbook = await exchange.fetch_order_book('LTC/BTC', limit=1)
    await exchange.close()
    return orderbook


if __name__ == '__main__':
    print(asyncio.run(test_binance()))
```

Result:

```
C:\Users\Nikola\vepython310\Scripts\python.exe D:/Programiranje/Python/Projekti/Bahamas/Test3.py
{'symbol': 'LTC/BTC', 'bids': [[0.002029, 23.166]], 'asks': [[0.00203, 40.914]], 'timestamp': None, 'datetime': None, 'nonce': 1681599231}
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021F9E5F9F30>
Traceback (most recent call last):
  File "C:\Users\Nikola\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Nikola\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Nikola\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\Nikola\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Process finished with exit code 0
```

**Comment by kroitor** [comment]
This is a known issue when running from Visual Studio on Windows, change it like this:

```Python
# -*- coding: utf-8 -*-

import asyncio
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async_support as ccxt  # noqa: E402


async def test_binance():
    exchange = ccxt.binance()
    orderbook = await exchange.fetch_order_book('LTC/BTC', limit=1)
    await exchange.close()
    return orderbook


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    print(loop.run_until_complete(test_binance()))
```

Let us know if that does not help.
Feel free to reopen this issue or just ask further questions here if any.

**Comment by HeinrichKg** [comment]
Tnx for quick answer. Now it is much better. Only before result I get this warning:

```
DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
```

I don't understand why I get this one?

**Comment by kroitor** [comment]
> There is no current event loop

Please, check here: https://www.google.com/search?q=asyncio+There+is+no+current+event+loop

**Comment by HeinrichKg** [comment]
Tnx a lot :)

You are doing great job
