### ISSUE TITLE
ccxt.base.errors.ExchangeNotAvailable: binance {"code":-1001,"msg":"Internal error; unable to process your request. Please try again."}

### ISSUE THREAD

**Issue by euphrates85** [ccxt/ccxt#13767]
-OS: Windows
-Programming Language version: Python 3.10
-CCXT version: 1.77.62

Hello

I received below error while my script is trying to open short position with create_market_sell_order

Why did i receive this error? (ccxt.base.errors.ExchangeNotAvailable: binance {"code":-1001,"msg":"Internal error; unable to process your request. Please try again."})
Thank you

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/ccxt/base/exchange.py", line 655, in fetch
    response.raise_for_status()
  File "/opt/conda/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ETH_5_30_post10_T4_Au.py", line 344, in <module>
    exchange_f.create_market_sell_order(coin, np.sum(buy_short_1))
  File "/opt/conda/lib/python3.7/site-packages/ccxt/base/exchange.py", line 2398, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)
  File "/opt/conda/lib/python3.7/site-packages/ccxt/binance.py", line 2788, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/opt/conda/lib/python3.7/site-packages/ccxt/base/exchange.py", line 495, in inner
    return entry(_self, **inner_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ccxt/binance.py", line 5070, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/opt/conda/lib/python3.7/site-packages/ccxt/base/exchange.py", line 542, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/opt/conda/lib/python3.7/site-packages/ccxt/base/exchange.py", line 671, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/opt/conda/lib/python3.7/site-packages/ccxt/binance.py", line 5048, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/opt/conda/lib/python3.7/site-packages/ccxt/base/exchange.py", line 560, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeNotAvailable: binance {"code":-1001,"msg":"Internal error; unable to process your request. Please try again."}
```

**Comment by kroitor** [comment]
@euphrates85 i'm not sure what your question is, the error message means what it says, you can simply wrap your code in a try-catch and retry on exceptions as you would do with any other software. Can you elaborate a bit on what is your question?

**Comment by euphrates85** [comment]
I just wanted to know what this error means.  Sorry I am a beginner in coding and I thought it was related with ccxt.

**Comment by euphrates85** [comment]
Iunderstood. Thanks alot again for you help.

**Comment by euphrates85** [comment]
Sorry for taking your time again but one more question i have. I also received "ConnectionResetError: [Errno 104] Connection reset by peer" error. Does your answer to try several times solve this error as well? 
I am asking because here [https://github.com/sammchardy/python-binance/issues/389#issuecomment-1100835511](url) they said that i have to reinitialize binance client object.
Again thank you in advance for your help.
