### ISSUE TITLE
Huobi (Pro) fetch_balance() TypeError

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#13770]
- OS: Ubuntu
- Programming Language version: Python 3.10
- CCXT version: 1.86.28

```
exchange = huobipro({...})
exchange.fetch_balance()
```

```
Traceback (most recent call last):
...
    exchange.fetch_balance()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/huobi.py", line 2694, in fetch_balance
    self.load_accounts()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2537, in load_accounts
    self.accounts = self.fetch_accounts(params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/huobi.py", line 2505, in fetch_accounts
    return self.parse_accounts(data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2450, in parse_accounts
    account = self.extend(self.parse_account(accounts[i], None), params)
TypeError: huobi.parse_account() takes 2 positional arguments but 3 were given
```

**Comment by kroitor** [comment]
@JovianMoon Thanks for your feedback, it will be fixed in CCXT 1.86.30 in ~20 minutes.
