### ISSUE TITLE
Bitfinex v2 can't use string type amounts for sell orders

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#13797]
- OS: Ubuntu
- Programming Language version: Python 3.10
- CCXT version: 1.86.83

```
exchange = ccxt.bitfinex2({...})
exchange.create_limit_sell_order('PNK/ETH', '100', '0.00002555')
```

```
Traceback (most recent call last):
...
    exchange.create_limit_sell_order('PNK/ETH', '100', '0.00002555')
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2871, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', amount, price, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/bitfinex2.py", line 1468, in create_order
    amount = amount if (side == 'buy') else -amount
TypeError: bad operand type for unary -: 'str'
```

Placing buy orders using string prices and amount works, so probably sell orders should work too?

**Comment by kroitor** [comment]
@JovianMoon thx for reporting it. Fixed in CCXT 1.86.88.
