### ISSUE TITLE
Problematic line in commit of version 1.87.2, python: "self.number = String"

### ISSUE THREAD

**Issue by AprilGrimoire** [ccxt/ccxt#13813]
- OS: Linux
- Programming Language version: Python 3.9
- CCXT version: 1.87.2 or 1.87.3

[this commit](https://github.com/ccxt/ccxt/commit/22ef4fbc23a8883a387bbe4647e2efc62821795e) seems problematic: `self.number = String` seems unreasonable. Was this a typo translating from other languages to python? It causes a runtime error.

The problem was resolved after downgrading to 1.87.1.

```
#!/usr/bin/env python3

import pdb
import ccxt

ITS_A_SECRET = None

exchange = ccxt.ftx(ITS_A_SECRET)
symbol = ITS_A_SECRET
leverage_limit = 10
ideal_leverage = 5
market_close_threshold = 2
market_close_ratio = 0.4
adjust_ratio = 0.1

exchange.checkRequiredCredentials()
exchange.load_markets()

def net_position():
    positions = exchange.fetch_positions()
    res = 0
    for i in positions:
        if i["symbol"] != symbol:
            continue
        res += i["contracts"] * (1 if i["side"] == "long" else -1)
        leverage_limit = 1 / i["initialMarginPercentage"]
    return res

def balance_usd():
    balance = exchange.fetch_balance()
    return balance["USD"]["total"]

#pdb.set_trace()

ticker = exchange.fetch_ohlcv(symbol, limit=10)[-1]
mid = (ticker[2] + ticker[3]) / 2
pos = net_position()
bal = balance_usd()

assert(pos <= 0)

exchange.cancel_all_orders()
target_leverage = min(ideal_leverage, leverage_limit)
current_leverage = abs(pos) * mid / bal
if abs(target_leverage - current_leverage) > target_leverage * 0.25:
    if (target_leverage > current_leverage):
        amount = (target_leverage - current_leverage) * adjust_ratio * bal / ticker[2]
        exchange.create_order(symbol, "limit", "sell", amount, ticker[2])
    else:
        if current_leverage < target_leverage * market_close_threshold:
            amount = (current_leverage - target_leverage) * adjust_ratio * bal / ticker[3]
            exchange.create_order(symbol, "limit", "buy", amount, ticker[3])
        else:
            amount = (current_leverage - target_leverage) * market_close_ratio * bal / mid
            exchange.create_order(symbol, "market", "buy", amount)

print('Yay')

```
The following output was got with cctx 1.87.2:

```
aprilgrimoire@aprilgrimoire-HLYL-WXX9:~/Development/Bot$ ./bot.py 
Traceback (most recent call last):
  File "/home/aprilgrimoire/Development/Bot/./bot.py", line 53, in <module>
    exchange.create_order(symbol, "limit", "buy", amount, ticker[3])
  File "/usr/local/lib/python3.9/dist-packages/ccxt/ftx.py", line 1689, in create_order
    return self.parse_order(result, market)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/ftx.py", line 1511, in parse_order
    return self.safe_order({
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 1949, in safe_order
    self.number = String
NameError: name 'String' is not defined
```

**Comment by AprilGrimoire** [comment]
Sorry, the issue was posted twice accidentally.
