### ISSUE TITLE
How to set market take profit

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#13853]
the code as follows:
```
import ccxt
import time
from pprint import pprint
ftx = ccxt.ftx({
    'apiKey': 'my_apikey',
    'secret': 'my_secret',
})

symbol = 'BTC/USD:USD'
ftx.load_markets()
market = ftx.market(symbol)
btc_maket_price = float(market['info']['price'])
btc_amount = 20 / btc_maket_price
create_order = ftx.create_order(symbol, 'market', 'buy', btc_amount)

type = 'takeProfit'
side = 'sell'
rise_btc_price = btc_maket_price + btc_maket_price * 0.015
params = {
    'stopPrice': rise_btc_price,
}
order = ftx.create_order(symbol, type, side, btc_amount, params)
The errors as follows:
Traceback (most recent call last):
File "C:\Users\fxu50\PycharmProjects\pythonProject1\contract.py", line 26, in
order = ftx.create_order(symbol, type, side, btc_amount, params)
File "C:\Users\fxu50\PycharmProjects\pythonProject1\ccxt\ftx.py", line 1625, in create_order
raise InvalidOrder(self.id + ' createOrder() does not support order type ' + type + ', only limit, market, stop, trailingStop, or takeProfit orders are supported')
ccxt.base.errors.InvalidOrder: ftx createOrder() does not support order type takeProfit, only limit, market, stop, trailingStop, or takeProfit orders are supported
```

**Comment by frosty00** [comment]
@qwe231cvb please make sure you are using the latest version of ccxt

**Comment by kroitor** [comment]
Duplicate, answered here: https://github.com/ccxt/ccxt/issues/13831#issuecomment-1155659014
