### ISSUE TITLE
yobit fetchbalance requests.exceptions.HTTPError

### ISSUE THREAD

**Issue by hippylover** [ccxt/ccxt#1385]
Ccxt need new exception to catch? ccxt-1.10.780

```
exchange = {}
exchange['yobit'] = ccxt.yobit()
exchange['yobit'].apiKey = "fake"
exchange['yobit'].secret = "fake"
print(exchange['yobit'].fetchBalance()))
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 351, in fetch
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://yobit.net/api/3/info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kris/exchangescripts/ccex_examples/instantiate-all-at-once.py", line 77, in <module>
    pprint(exchange['yobit'].fetchBalance())
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 107, in fetch_balance
    self.load_markets()
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 834, in load_markets
    markets = self.fetch_markets()
  File "/usr/lib/python3.6/site-packages/ccxt/liqui.py", line 148, in fetch_markets
    response = self.publicGetInfo()
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 172, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 298, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 363, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "/usr/lib/python3.6/site-packages/ccxt/liqui.py", line 593, in handle_errors
    if (not isinstance(body, basestring)) or len((body) < 2):
TypeError: '<' not supported between instances of 'str' and 'int'

```

**Comment by hippylover** [comment]
Hmm, well this is the newest error message i get(ccxt-1.10.802):

```
exchange = {}
exchange['yobit'] = ccxt.yobit()
exchange['yobit'].apiKey = "fake"
exchange['yobit'].secret = "fake"
exchange['yobit'].verbose
print(exchange['yobit'].fetchBalance())
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 352, in fetch
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://yobit.net/api/3/info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kris/exchangescripts/ccex_examples/instantiate-all-at-once.py", line 79, in <module>
    pprint(exchange['yobit'].fetchBalance())
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 111, in fetch_balance
    self.load_markets()
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 840, in load_markets
    markets = self.fetch_markets()
  File "/usr/lib/python3.6/site-packages/ccxt/liqui.py", line 139, in fetch_markets
    response = self.publicGetInfo()
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 176, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 299, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 365, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 396, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 281, in raise_error
    details,
ccxt.base.errors.DDoSProtection: yobit GET https://yobit.net/api/3/info 503 Server Error: Service Temporarily Unavailable for url: https://yobit.net/api/3/info <!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px; border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; animation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:both; animation-fill-mode:both; display:inline-block; }
  </style>

    <script type="text/javascript">
  //<![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, nfyjUYN={"Oiqu":!+[]+!![]+!![]+!![]+!![]};
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;nfyjUYN.Oiqu-=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]));nfyjUYN.Oiqu+=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));a.value = parseInt(nfyjUYN.Oiqu, 10) + t.length; '; 121'
        f.action += location.hash;
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
</script>


</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">
    
    <div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> yobit.net.</h1>
    
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>
   
  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="jschl_vc" value="e57d9bb555504f4281cb20273be034fa"/>
    <input type="hidden" name="pass" value="1516626414.005-fhVY4ZxIvX"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
</div>

          
          <div class="attribution">
            <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iuam" target="_blank" style="font-size: 12px;">DDoS protection by Cloudflare</a>
            <br>
            Ray ID: 3e12bb968ffa4279
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>
```

**Comment by kroitor** [comment]
Have you tried this?

https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare.py

**Comment by hippylover** [comment]
I had not tried that but it seems i get the same error:
```
exchange = ccxt.yobit()
exchange.apiKey = "fake"
exchange.secret = "fake"
exchange = getattr(ccxt, "yobit")({
    'timeout': 20000,
    'session': cfscrape.create_scraper(),
})
print(exchange.fetchBalance())
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 352, in fetch
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://yobit.net/api/3/info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kris/exchangescripts/ccex_examples/instantiate-all-at-once.py", line 83, in <module>
    print(exchange.fetchBalance())
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 111, in fetch_balance
    self.load_markets()
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 840, in load_markets
    markets = self.fetch_markets()
  File "/usr/lib/python3.6/site-packages/ccxt/liqui.py", line 139, in fetch_markets
    response = self.publicGetInfo()
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 176, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 299, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 365, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 396, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 281, in raise_error
    details,
ccxt.base.errors.DDoSProtection: yobit GET https://yobit.net/api/3/info 503 Server Error: Service Temporarily Unavailable for url: https://yobit.net/api/3/info <!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px; border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; animation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:both; animation-fill-mode:both; display:inline-block; }
  </style>

    <script type="text/javascript">
  //<![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, qvtEysm={"fkwnrWY":+((!+[]+!![]+!![]+!![]+!![]+[])+(+[]))};
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;qvtEysm.fkwnrWY*=+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]));qvtEysm.fkwnrWY*=+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));qvtEysm.fkwnrWY+=+((!+[]+!![]+!![]+!![]+[])+(+!![]));qvtEysm.fkwnrWY+=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]));a.value = parseInt(qvtEysm.fkwnrWY, 10) + t.length; '; 121'
        f.action += location.hash;
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
</script>


</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">
    
    <div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> yobit.net.</h1>
    
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>
   
  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="jschl_vc" value="ec71ae7dc87b586d3a667b95b0d425fe"/>
    <input type="hidden" name="pass" value="1516634371.991-dQHSsPbCR5"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
</div>

          
          <div class="attribution">
            <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iuam" target="_blank" style="font-size: 12px;">DDoS protection by Cloudflare</a>
            <br>
            Ray ID: 3e137ddfeb544273
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>
```

**Comment by bklnf** [comment]
Same for me. Can fetch markets via cfscrape, but had cloudflare error for fetching balance. This started on Sunday. Other exchanges work fine, only Yobit.

**Comment by bklnf** [comment]
Pip3 install ccxt — update didn’t help

**Comment by hippylover** [comment]
it's --upgrade. Anyway, it's working for me now :S (i still think there's something weird with the lib kroitor. i never used to have these kinds of issues with my admittedly simple scripts)

**Comment by kroitor** [comment]
@hippylover the 503 error is a server-side error, we can't really workaround it, unless you put cloudflare credentials there properly and stay below their rate limit.

**Comment by hippylover** [comment]
I did stay below their rate limit and i did credentials correctly. i was just trying the command and seeing it fail, not calling it in a loop or something.

Oh well. Bittrex having problems today too :/ 4 times slower than normal according to people in slack. Getting timeouts on cancel order and selllimitorder even though the commands still go through... hitbtc just started randomly not giving high and low on fetchorder on certain pairs which made the script crash... i can submit a pr for this if you want but they fixed it now. don't know if will happen again.

**Comment by cimp43** [comment]
can you please give me yobit bot like this one that you use it so i can buy and sell faster please
