### ISSUE TITLE
Regression: `deribit.fetchPositions('BTC')` fails with `deribit does not have market symbol B`

### ISSUE THREAD

**Issue by josh-renton** [ccxt/ccxt#13961]
- OS: OSX 10.15.7
- Programming Language version: Node v16.14.2
- CCXT version: 1.84.100 -> 1.88.16

Repro code
```
const ccxt = require('ccxt')
const keys = { apiKey: 'XXXXX', secret: 'XXXXX' }
const deribit = new ccxt.deribit(keys)
deribit.verbose = true
deribit.fetchPositions('BTC').then(ps => console.log(ps))
```

**1.83.99** has expected behaviour
**1.84.100**: `Uncaught TypeError: symbols.map is not a function`
**1.88.16**: `BadSymbol: deribit does not have market symbol B`

I dug into the **1.88.16** code a bit, and found that:

- The for loop in Exchange.js:1525 is what leads to the `does not have market symbol B`
- It seems to assume `this.parsePositions()` (deribit.js:2320) will only pass a `symbols` array, though the function itself supports `symbols` as type string
- When I manually wrapped symbols in an array on that line (i.e. `return this.parsePositions (result, [symbols])` the error becomes: `BadSymbol: deribit does not have market symbol BTC`
- So it appears at least 2 issues are at play here

Hope that helps.

Condensed verbose error output - removed verbose precursor API request responses as they seem irrelevant.
```
> fetch Request:
 deribit GET https://www.deribit.com/api/v2/public/get_currencies
RequestHeaders:
 {}
RequestBody:
 undefined

......

fetch Request:
 deribit GET https://www.deribit.com/api/v2/private/get_positions?currency=BTC
RequestHeaders:
 {
  Authorization: 'deri-hmac-sha256 id=XXXXXXX,ts=1655723799234,sig=XXXXXXX,nonce=1655723799234'
}
RequestBody:
 undefined

handleRestResponse:
 deribit GET https://www.deribit.com/api/v2/private/get_positions?currency=BTC 200 OK
ResponseHeaders:
 {
  'Access-Control-Allow-Headers': 'Authorization,User-Agent,Range,X-Requested-With,Content-Type,Partner',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-store',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Length': '443',
  'Content-Type': 'application/json',
  Date: 'Mon, 20 Jun 2022 11:16:39 GMT',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=15768000',
  Vary: 'Origin,Authorization,Partner',
  'X-Frame-Options': 'SAMEORIGIN'
}
ResponseBody:
 {"jsonrpc":"2.0","result":[{"vega":18.93625,"total_profit_loss":-0.28249907,"theta":-8.47839,"size":3.0,"settlement_price":0.00352162,"realized_profit_loss":0.0,"open_orders_margin":0.0,"mark_price":0.00383364,"maintenance_margin":0.0,"kind":"option","instrument_name":"BTC-30SEP22-60000-C","initial_margin":0.0,"index_price":20723.59,"gamma":0.00002,"floating_profit_loss_usd":-13380.2,"floating_profit_loss":0.000936081,"direction":"buy","delta":0.07385,"average_price_usd":4539.52,"average_price":0.098},{"vega":22.64381,"total_profit_loss":-0.301954258,"theta":-10.7475,"size":5.0,"settlement_price":0.00249991,"realized_profit_loss":0.0,"open_orders_margin":0.0,"mark_price":0.00260915,"maintenance_margin":0.0,"kind":"option","instrument_name":"BTC-30SEP22-70000-C","initial_margin":0.0,"index_price":20723.59,"gamma":0.00002,"floating_profit_loss_usd":-14310.63,"floating_profit_loss":0.000546207,"direction":"buy","delta":0.0832,"average_price_usd":2916.2,"average_price":0.063}],"usIn":1655723799395227,"usOut":1655723799396036,"usDiff":809,"testnet":false}

Uncaught:
BadSymbol: deribit does not have market symbol B
    at deribit.market (/Users/josh/Documents/work/oscar-sheet-rewrite/node_modules/ccxt/js/base/Exchange.js:2235:15)
    at deribit.symbol (/Users/josh/Documents/work/oscar-sheet-rewrite/node_modules/ccxt/js/base/Exchange.js:1770:29)
    at deribit.marketSymbols (/Users/josh/Documents/work/oscar-sheet-rewrite/node_modules/ccxt/js/base/Exchange.js:1526:31)
    at deribit.parsePositions (/Users/josh/Documents/work/oscar-sheet-rewrite/node_modules/ccxt/js/base/Exchange.js:1675:24)
    at deribit.fetchPositions (/Users/josh/Documents/work/oscar-sheet-rewrite/node_modules/ccxt/js/deribit.js:2320:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  constructor: [class BadSymbol extends BadRequest]
}
```

**Comment by kroitor** [comment]
@josh-renton thanks for reporting, will fix this asap!
