### ISSUE TITLE
Quote order on FTX error

### ISSUE THREAD

**Issue by aghering23** [ccxt/ccxt#13960]
I'm getting an error when trying to create an order with the amount in quote on the FTX exchange. I searched for a solution here and google and found that adding params solved it for some (binance exchange). But this doesn't work for FTX.

Exchange: FTX
Pair: ETH/BTC (SPOT)
Balance BTC: 0.002

Desired result: Market trade all BTC on balance for ETH (and vice versa)

```
PYTHON
-----
import ccxt
import time
import decimal

ftx = ccxt.ftx({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
})
subaccount= "SUBACCOUNTNAME"

def getfreebalancepair(account, pair, subaccount=None):
    if subaccount:
        fetchbalances = account.fetch_balance({"FTX-SUBACCOUNT": subaccount})
    else:
        fetchbalances = account.fetch_balance()
    balances = fetchbalances['info']['result']

    coinbalance= 0.0
    for balance in balances:
        if (balance['coin'] == pair):
            coinbalance = balance['free']
    print(coinbalance)
    return coinbalance

def submitorder(ftx, subaccount= None):
    amount = getfreebalancepair(ftx, "BTC", subaccount)
    if subaccount:
        result = ftx.create_order('ETH/BTC', 'market', 'buy', None, None, {"FTX-SUBACCOUNT": subaccount, "quoteAmount": amount, })
    else:
        result = ftx.create_order('ETH/BTC', 'market', 'buy', None, None, {"quoteAmount": amount, })
    print(result)

submitorder(ftx, subaccount)
```

```
ERROR
---
0.00190196
Traceback (most recent call last):
  File "c:\main.py", line 94, in <module>
    submitorder(ftx)
  File "c:\main.py", line 81, in submitorder
    result = ftx.create_order('ETH/BTC', 'market', 'buy', None, None, {"FTX-SUBACCOUNT": "DevFrostyBot", "quoteAmount": amount, })
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\ftx.py", line 1404, in create_order
    'size': float(self.amount_to_precision(symbol, amount)),
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 1434, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, market['precision']['amount'], self.precisionMode, self.paddingMode)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by aghering23** [comment]
It's a shame that this functionality isn't supported. makes it very difficult to trade these pairs. I also created a ticket with FTX if they can confirm it.
