### ISSUE TITLE
Crypto.com fetch_tickers() fails both with and without 'symbols' argument

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#14085]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 1.89.13

`fetch_tickers` returns and empty dictionary for Crypto.com exchange when `symbols` argument is not defined:
```
exchange = ccxt.cryptocom()
exchange.load_markets()
exchange.verbose = True
print(exchange.fetch_tickers())
```

```
fetch Request: cryptocom GET https://api.crypto.com/v2/public/get-ticker RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: cryptocom GET https://api.crypto.com/v2/public/get-ticker 200 ResponseHeaders: {'Date': 'Sun, 26 Jun 2022 20:31:28 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'CF-Ray': '7218b4e79a3395f0-ARN', 'Strict-Transport-Security': 'max-age=31536000', 'CF-Cache-Status': 'DYNAMIC', 'content-security-policy': "default-src 'self' https: wss: data: 'unsafe-inline' 'unsafe-eval'", 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Referrer-Policy': 'same-origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'sameorigin', 'X-Permitted-Cross-Domain-Policies': 'master-only', 'X-XSS-Protection': '1; mode=block', 'Set-Cookie': '__cf_bm=e1epDQzmtmqKLoelDHpzyvmHWarkr6WJPbHRVx0lvwk-1656275488-0-AXvMR7ehedw+JIW5vwpO1GvYT13eEZ4b1xJjxnAFDIPUVlrnVMDWShz9L6LvvXa/fMWCwZiLxcR/eY1V8TmF3AQ=; path=/; expires=Sun, 26-Jun-22 21:01:28 GMT; domain=.crypto.com; HttpOnly; Secure; SameSite=None', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'Content-Encoding': 'gzip'} ResponseBody: {"code":0,"method":"public/get-ticker","result":{"data": [ {"i":"PYR_USDT","b":3.347,"k":3.359,"a":3.353,"t":1656275488085,"v":3582.799,"h":3.668,"l":3.338,"c":-0.092}, {"i":"VET_BTC","b":0.0000011772,"k":0.0000011789,"a":0.0000011786,"t":1656275488063,"v":9649582,"h":0.0000012318,"l":0.0000011699,"c":-0.0000000344}, {"i":"IMX_BTC","b":0.000040036,"k":0.000040148,"a":0.000040148,"t":1656275486692,"v":11599.94,"h":0.000042787,"l":0.000039608,"c":-0.000000870}, {"i":"IOTX_USDC","b":0.029598,"k":0.029658,"a":0.029623,"t":1656275488012,"v":164511,"h":0.031494,"l":0.028870,"c":0.000633}, {"i":"ZIL_BTC","b":0.0000022449,"k":0.0000022470,"a":0.0000022470,"t":1656275488097,"v":406167.6,"h":0.0000023949,"l":0.0000021925,"c":-0.0000000323}, ...
{}
```
When `symbols` argument is defined there's an error:
```
exchange = ccxt.cryptocom()
exchange.load_markets()
exchange.verbose = True
print(exchange.fetch_tickers(['BCH/BTC']))
```
```
fetch Request: cryptocom GET https://api.crypto.com/v2/public/get-ticker RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: cryptocom GET https://api.crypto.com/v2/public/get-ticker 200 ResponseHeaders: {'Date': 'Sun, 26 Jun 2022 20:37:45 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'CF-Ray': '7218be1f8fd598f6-ARN', 'Strict-Transport-Security': 'max-age=31536000', 'CF-Cache-Status': 'DYNAMIC', 'content-security-policy': "default-src 'self' https: wss: data: 'unsafe-inline' 'unsafe-eval'", 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Referrer-Policy': 'same-origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'sameorigin', 'X-Permitted-Cross-Domain-Policies': 'master-only', 'X-XSS-Protection': '1; mode=block', 'Set-Cookie': '__cf_bm=8EOu1Iro7sXsh04_vyWjxdQ60Nsyo2OJDynu8g6MyPg-1656275865-0-AdK7YSBCMPrgIswz1EE7jC/JnfCarfbg1xuJlFyNLak7EG0LkZbQYOOJwQa0+vNFInS5usoiq2tIpOBvsJtf6xU=; path=/; expires=Sun, 26-Jun-22 21:07:45 GMT; domain=.crypto.com; HttpOnly; Secure; SameSite=None', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'Content-Encoding': 'gzip'} ResponseBody: {"code":0,"method":"public/get-ticker","result":{"data": [ {"i":"EPX_BTC","b":0.0000000270,"k":0.0000000277,"a":0.0000000273,"t":1656275860658,"v":908191,"h":0.0000000291,"l":0.0000000265,"c":-0.0000000002}, {"i":"XTZ_USDT","b":1.5066,"k":1.5086,"a":1.5062,"t":1656275865560,"v":205993.59,"h":1.5958,"l":1.4794,"c":0.0020}, {"i":"KP3R_USDT","b":134.36,"k":134.85,"a":134.39,"t":1656275865051,"v":595.9221,"h":146.63,"l":131.47,"c":-5.21}, {"i":"XLM_USDT","b":0.12347,"k":0.12362,"a":0.12341,"t":1656275865676,"v":1448718.9,"h":0.12830,"l":0.12204,"c":-0.00193}, ...
Traceback (most recent call last):
  File "/home/xyz/test.py", line 6, in <module>
    print(exchange.fetch_tickers(['BCH/BTC']))
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/cryptocom.py", line 522, in fetch_tickers
    return self.filter_by_array(data, 'symbol', symbols)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2604, in filter_by_array
    if self.in_array(objects[i][key], values):
KeyError: 'symbol'
```

**Comment by kroitor** [comment]
@JovianMoon thanks for your feedback, as always! Please, let me know if this issue persists after upgrading to 1.89.14+. Thank you!

**Comment by JovianMoon** [comment]
@kroitor No prob and thanks for the fix! Seems to be working now both ways
