### ISSUE TITLE
Coinbase Pro, historical data issue

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#14202]
- OS: Windows 10
- Programming Language version: 3.8.10
- CCXT version: 1.89.19

```
import ccxt
import time
exchange = ccxt.coinbasepro()

since = time.time() - 15 * 60 * 500

h = exchange.fetch_ohlcv("BTC-USDT", '15m', since, 500)
```

```
Traceback (most recent call last):

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 617, in fetch
    response.raise_for_status()

  File "C:\Users\Tomas\anaconda3\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error: Bad Request for url: https://api.pro.coinbase.com/products/BTC-USDT/candles?granularity=900&start=None&end=None


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Tomas\AppData\Local\Temp/ipykernel_18932/2140911438.py", line 7, in <module>
    h = exchange.fetch_ohlcv("BTC-USDT", '15m', since, 500)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\coinbasepro.py", line 870, in fetch_ohlcv
    response = self.publicGetProductsIdCandles(self.extend(request, params))

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 497, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\coinbasepro.py", line 1575, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 2614, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 633, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\coinbasepro.py", line 1571, in handle_errors
    raise ExchangeError(feedback)  # unknown message

ExchangeError: coinbasepro Invalid start
```

Unfortunately, when trying to get historical data from Coinbase pro, it is not possible to fill in a timestamp.

**Comment by kroitor** [comment]
@Tomas-MP your `since` timestamp must be in milliseconds as documented in the CCXT manual:

- https://docs.ccxt.com/en/latest/manual.html#pagination

Let us know if this does not help:

```Python
import ccxt
exchange = ccxt.coinbasepro()
since = exchange.milliseconds() - 15 * 60 * 500 * 1000
h = exchange.fetch_ohlcv("BTC-USDT", '15m', since, 500)
```

**Comment by Tomas-MP** [comment]
Hey @kroitor, 

Indeed this works, and when I refer to a UNIX timestamp variable I need to make sure that it is an integer.
