### ISSUE TITLE
After update to 1.90.40 cannot place order for binance

### ISSUE THREAD

**Issue by pratikm121** [ccxt/ccxt#14289]
After updating to the latest version of ccxt JavaScript , I am not able to place any limit order or normal orders via Binance exchange.
Searched for the error code but could not find anything . Noticed this error started coming after the update was done. 
Same method call was working fine till today 3 PM UTC.

- OS: Windows
- Programming Language version: Javascript (Node version :- v14.15.4)
- CCXT version: 1.90.40

Updated ccxt version from "^1.84.72"  to "1.90.40"
Updated @binance/connector from "^1.10.0"  to "^1.11.0"

None of the calls below are not working as expected any more

```await binanceClient.createOrder('BNB/BUSD', 'limit', 'buy', qty, buyPrice);```
```await binanceClient.createLimitOrder('BNB/BUSD',"buy", qty, buyPrice);```
```await binanceClient.createLimitSellOrder('BNB/BUSD', myLastTrade.amount, stopLossSellPrice);```

For all the calls being made to Binance like (createOrder, createLimitSellOrder ,createLimitBuyOrder, createLimitOrder)
below error is being thrown :- 

```
(node:13860) UnhandledPromiseRejectionWarning: ExchangeError: binance {"code":-1018,"msg":"A parameter caused overflow."}
    at binance.handleErrors (G:\WORK\Coding\GitHubRepos\crypto_binance_ccxt\node_modules\ccxt\js\binance.js:5747:19)
    at G:\WORK\Coding\GitHubRepos\crypto_binance_ccxt\node_modules\ccxt\js\base\Exchange.js:601:51
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timeout (G:\WORK\Coding\GitHubRepos\crypto_binance_ccxt\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async binance.fetch2 (G:\WORK\Coding\GitHubRepos\crypto_binance_ccxt\node_modules\ccxt\js\base\Exchange.js:1806:16)
    at async binance.request (G:\WORK\Coding\GitHubRepos\crypto_binance_ccxt\node_modules\ccxt\js\binance.js:5775:26)
    at async binance.createOrder (G:\WORK\Coding\GitHubRepos\crypto_binance_ccxt\node_modules\ccxt\js\binance.js:2998:26)
    at async trade (G:\WORK\Coding\GitHubRepos\crypto_binance_ccxt\live_trading_script.js:84:9)
```

**Comment by kroitor** [comment]
@pratikm121 please, paste your complete code and your complete verbose output from this snippet:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt.async_support as ccxt
from asyncio import run
from pprint import pprint


print('CCXT Pro Version:', ccxtpro.__version__)


async def main():
    exchange = ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
    })
    markets = await exchange.load_markets()
    exchange.verbose = True  # after loading the markets
    symbol = 'BNB/BUSD'
    try:
        order = await exchange.create_order(symbol, 'limit', 'buy', YOUR_AMOUNT, YOUR_PRICE)
        pprint(order)
    except Exception as e:
        print(exchange.iso8601(exchange.milliseconds()), exchange.id, type(e).__name__, str(e))
    await exchange.close()


run(main())
```

**Comment by ttodua** [comment]
@pratikm121 please post your follow-up if you see any issue or not. otherwise, we will consider this as not-an-issue and close the topic.

**Comment by pratikm121** [comment]
Its working now as expected .. so I guess it was an issue when the new upgrade was deployed. Sorry for the delayed response.
Will open a new ticket if something else comes up. Thanks.
