### ISSUE TITLE
Cannot submit order on Kucoin Papertrading Futures (New, different than testnet)

### ISSUE THREAD

**Issue by tebzzz** [ccxt/ccxt#14296]
- OS: MAC OS Monterrey 
- Programming Language version: Python 3.9.12
- CCXT version:ccxt-1.90.41

Cannot submit an order through paper trading on Kucoin futures. I only get a timeout.  

It is relatively new (release date says June 26th 2022 so I imagine it has not been implemented yet. The following code works fine if I take out the exhcange.set_sandbox_mode(True) line. This is different from the testnet and uses the same API keys as futures. 

```

exchange_id = 'kucoinfutures'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({

    'apiKey': 'X',
    'secret': 'Y',
    'password': 'Z',
     'options': {
        'defaultType': 'future',
    },
})
exchange.set_sandbox_mode(True)
order = exchange.create_order('XBTUSDTM', 'limit', 'buy', 100,20000)
```

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api-sandbox-futures.kucoin.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 593, in fetch
    response = self.session.request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api-sandbox-futures.kucoin.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/ccxt/kucoinfutures.py", line 1034, in create_order
    response = self.futuresPrivatePostOrders(self.extend(request, params))
  File "/usr/local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 499, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2619, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/usr/local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2616, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 623, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: kucoinfutures POST https://api-sandbox-futures.kucoin.com/api/v1/orders
```

**Comment by ttodua** [comment]
After checking all announcements and details, I'd label it with 'new exchange implementation' as it entails completely new API/engine. (more info [here](https://www.kucoin.com/news/kucoin-futures-api-update-notice) and [here](https://docs.kucoin.com/futures/new/#sandbox-test-environment) )

**Comment by sc0Vu** [comment]
I've checked with their service, turns out they didn't open v2 api yet, and will focus on tuning v1 api.
