### ISSUE TITLE
How to create stop limit order on bybit below mark price? (ccxt.base.errors.InvalidOrder)

### ISSUE THREAD

**Issue by Kamkuczpol** [ccxt/ccxt#14352]
Hello. :)

I have a problem with creat a stop limit order when I want to short it below actual price. 

It means if price of ETH is 1083 USDT I can create conditional order above this price for example 1090 USDT, but I can't create below this price for example 1080 USDT. 

On the exchange I can make it without any problem.

- OS: Window
- Programming Language version: Python
- CCXT version: 1.9

actual price on market = 1083
short_price = 1080
exchange.create_stop_limit_order(
    symbol=symbol,
    side='sell',
    amount=amount,
    price=short_price,
    stopPrice=short_price,
    params={
        'leverage': 3
    }
)

```
```
Traceback (most recent call last):
  File "D:\Python\Trading Bot\ccxt\ccxt_bot_bybit.py", line 45, in <module>
    exchange.create_stop_limit_order(
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 3069, in create_stop_limit_order
    return self.create_order(symbol, 'limit', side, amount, price, query)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 2625, in create_order
    return self.create_contract_order(symbol, type, side, amount, price, params)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 2866, in create_contract_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 496, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2616, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 658, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 4672, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2834, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: bybit {"ret_code":130074,"ret_msg":"expect Rising, but trigger_price[10798000] \u003c= current[10820000]??LastPrice","ext_code":"","ext_info":"","result":null,"time_now":"1657789703.277387","rate_limit_status":99,"rate_limit_reset_ms":1657789703275,"rate_limit":100}
```

```

**Comment by Kamkuczpol** [comment]
Thank you. It is working with a short price. 

But I noticed now that a long position has the same problem.
```
long_price = 1250

exchange.create_stop_market_order(
    symbol=symbol,
    side='buy',
    amount=amount,
    # price=1090,
    stopPrice=long_price,
    params={
        'leverage': 3,
        'base_price': long_price
    }
)```


```Traceback (most recent call last):
  File "D:\Python\Trading Bot\ccxt\ccxt_bot_bybit.py", line 84, in <module>
    exchange.create_stop_market_order(
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 3075, in create_stop_market_order
    return self.create_order(symbol, 'market', side, amount, None, query)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 2625, in create_order
    return self.create_contract_order(symbol, type, side, amount, price, params)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 2866, in create_contract_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 496, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2616, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 658, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 4674, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bybit {"ret_code":130075,"ret_msg":"expect Falling, but trigger_price[12184500] \u003e= current[12094000]??LastPrice","ext_code":"","ext_info":"","result":null,"time_now":"1657870964.924113","rate_limit_status":99,"rate_limit_reset_ms":1657870964921,"rate_limit":100}```

And similar to the short position if I set up a long price below market price all is ok. But if the price is set up above the market price it doesn't work.

Greetings

**Comment by carlosmiei** [comment]
Hello again @Kamkuczpol, please bear in mind that you have to comply with this Bybit rule when placing conditional Orders:
![image](https://user-images.githubusercontent.com/43336371/179184264-d52ba17d-2110-44d0-ac1d-4edadd393968.png)

Meaning that if you want to place a long conditional order you expect it to increase so `stop_px` has to be bigger than `max(price, base_price)`


More info here: https://bybit-exchange.github.io/docs/linear/#t-placecond

**Comment by Kamkuczpol** [comment]
Thank you for response. 

If I understand well stop_px is a trigger price:
![image](https://user-images.githubusercontent.com/101928167/179309071-a14394eb-5017-47d5-ba8e-347355bf74dc.png)

In this moment price of ETH is 1260, and I want to create my conditional order on 1270 so it is higher than actual price.

**Comment by Kamkuczpol** [comment]
Thank you. After your text I have made it:

```
long_position = exchange.create_stop_market_order(
    symbol=symbol,
    side='buy',
    amount=amount,
    # price=1090,
    stopPrice=long_price,
    params={
        'leverage': 3,
        'base_price': long_price-1,
        'stop_px': long_price+1,
        'stop_loss': int(long_price * 0.98),
        'trailing_stop': 10
    }
)
```
