### ISSUE TITLE
How to fetch open orders on ByBit?

### ISSUE THREAD

**Issue by Kamkuczpol** [ccxt/ccxt#14378]
Hi

I can't fetch open orders on bybit since one hour.

- OS: Windows
- Programming Language version: Python
- CCXT version: 1.90.68

```
exchange = ccxt.bybit({
    'apiKey': config.bybit_apiKey,
    'secret': config.bybit_secretKey,
    'enableRateLimit': True
})

symbol = 'ETHUSDT'
amount = 0.01
pprint(exchange.fetch_open_orders('ETHUSDT'))

Traceback (most recent call last):
  File "D:\Python\Trading Bot\ccxt\ccxt_bot_bybit.py", line 21, in <module>
    pprint(exchange.fetch_open_orders('ETHUSDT'))
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 3430, in fetch_open_orders
    market = self.market(symbol)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2947, in market
    raise ExchangeError(self.id + ' markets not loaded')
ccxt.base.errors.ExchangeError: bybit markets not loaded
Process finished with exit code 1
```

**Comment by ttodua** [comment]
I confirm the issue. Will be submitting fix asap.

**Comment by marianturchyn** [comment]
I had a similar issue but I was receivong an empty list with orders. So the solution is to add default params:

// for the last ~12 monts
fetchOpenOrders(undefined, Date.now() - 12 * 30 * 24 * 60 * 60 * 1000, 100, { type: 'spot' });
