### ISSUE TITLE
How to close position in ByBit?

### ISSUE THREAD

**Issue by Kamkuczpol** [ccxt/ccxt#14385]
Hi

I have tried to close position on ByBit by simply reduce only, because I didn't see another option. 

But I always get error that size is zero what is impossible. Can you help?

- OS: Window
- Programming Language version: Python
- CCXT version: 1.9

```
exchange.create_order(symbol=symbol,
                  amount= 0.01,
                  type='Market',
                  side='sell',
                  price=actual_bid_price ,
                  params={'reduce_only': True})
```
I have tried with capital "S", different form of price and nothing work.

```
Traceback (most recent call last):
  File "D:\Python\Trading Bot\ccxt\ccxt_bot_bybit.py", line 87, in <module>
    exchange.create_order(symbol=symbol,
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 2625, in create_order
    return self.create_contract_order(symbol, type, side, amount, price, params)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 2866, in create_contract_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 496, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2616, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 658, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 4674, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bybit {"ret_code":130125,"ret_msg":"current position is zero, cannot fix reduce-only order qty","ext_code":"","ext_info":"","result":null,"time_now":"1658055949.243428","rate_limit_status":99,"rate_limit_reset_ms":1658055949240,"rate_limit":100}
```
Thank you for help and your job.

**Comment by carlosmiei** [comment]
Hello @Kamkuczpol can you please post the full request-response log?

**Comment by Kamkuczpol** [comment]
Hi Carlosmiei.

Do you mean this:
```
exchange = ccxt.bybit({
    'apiKey': config.bybit_apiKey,
    'secret': config.bybit_secretKey,
    'enableRateLimit': True
})
exchange.load_markets()
```

or this
```
url_testnet =  'https://api-testnet.bybit.com'
base_url = 'https://api.bybit.com'

session_auth = usdt_perpetual.HTTP(
    endpoint=base_url,
    api_key=config.bybit_apiKey,
    api_secret=config.bybit_secretKey
)
```
I am using ccxt and Bybit api because there is bug in ccxt.

**Comment by carlosmiei** [comment]
@Kamkuczpol I mean setting verbose = True and copy paste the log here

**Comment by Kamkuczpol** [comment]
Thank you for helping.

This time was working. Maybe I had some problem in the code.

**Comment by ysj16** [comment]
> Thank you for helping.
> 
> This time was working. Maybe I had some problem in the code.

I also ran into this issue. Can you explain how you resolved it?
