### ISSUE TITLE
How to change stop loss in the Bybit on open positions?

### ISSUE THREAD

**Issue by Kamkuczpol** [ccxt/ccxt#14433]
- OS: Window
- Programming Language version: Python
- CCXT version: 1.90.89

```
if actual_bid_price > long_entry_price * 1.004:
        exchange.edit_order(id=2622388,
                            side="buy",
                            symbol=symbol,
                            type="market",
                            params={
                                'stop_loss': int(actual_bid_price * 0.99)
                            })
```

```
Traceback (most recent call last):
  File "D:\Python\Trading Bot\ccxt\ccxt_bot_bybit.py", line 164, in <module>
    exchange.edit_order(id=2622388,
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 3025, in edit_order
    return self.edit_contract_order(id, symbol, type, side, amount, price, params)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 2979, in edit_contract_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 496, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2616, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 658, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 4681, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2834, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: bybit {"ret_code":20001,"ret_msg":"order not exists or too late to replace","ext_code":"","ext_info":"","result":null,"time_now":"1658392828.376058","rate_limit_status":88,"rate_limit_reset_ms":1658392828374,"rate_limit":100}
```
What I am looking Bybit doesn't have id in their order.

**Comment by ttodua** [comment]
have you tried to provide the id  as string format instead of numeric. let me know then

**Comment by Kamkuczpol** [comment]
> have you tried to provide the id as string format instead of numeric. let me know then

Thank you for your response. 

I have tried and I have still an error:
```
fetch Request: bybit POST https://api.bybit.com/private/linear/order/replace RequestHeaders: {'Content-Type': 'application/json', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"ETHUSDT","order_id":"2622388","stop_loss":1476,"api_key":"iYcb6hFAme9L33acIa","recv_window":5000,"timestamp":"1658405303718","sign":"c65a99c0d1572ce1a29aa3894f7f168fbc9120fdddd423747480666e7b1a12be"}
Traceback (most recent call last):
  File "D:\Python\Trading Bot\ccxt\ccxt_bot_bybit.py", line 156, in <module>
    exchange.edit_order(id="2622388",
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 3025, in edit_order
    return self.edit_contract_order(id, symbol, type, side, amount, price, params)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 2979, in edit_contract_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 496, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2616, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 658, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 4681, in handle_errors

fetch Response: bybit POST https://api.bybit.com/private/linear/order/replace 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '219', 'Server': 'T-GATEWAY', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Thu, 21 Jul 2022 12:08:23 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 21 Jul 2022 12:08:23 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":20001,"ret_msg":"order not exists or too late to replace","ext_code":"","ext_info":"","result":null,"time_now":"1658405302.951573","rate_limit_status":88,"rate_limit_reset_ms":1658405302950,"rate_limit":100}
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "C:\Users\kuczy\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2834, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: bybit {"ret_code":20001,"ret_msg":"order not exists or too late to replace","ext_code":"","ext_info":"","result":null,"time_now":"1658405302.951573","rate_limit_status":88,"rate_limit_reset_ms":1658405302950,"rate_limit":100}
```
There are parameters for the long position:  
`{'user_id': 2622388, 'symbol': 'ETHUSDT', 'side': 'Buy', 'size': 0.01, 'position_value': 14.89, 'entry_price': 1489, 'liq_price': 1000.15, 'bust_price': 992.7, 'leverage': 3, 'auto_add_margin': 0, 'is_isolated': True, 'position_margin': 4.96333324, 'occ_closing_fee': 0.0059562, 'realised_pnl': -0.1003701, 'cum_realised_pnl': 458.48459275, 'free_qty': -0.01, 'tp_sl_mode': 'Partial', 'unrealised_pnl': 0.0341, 'deleverage_indicator': 2, 'risk_id': 11, 'stop_loss': 0, 'take_profit': 0, 'trailing_stop': 0, 'position_idx': 1, 'mode': 'BothSide'}
`

Greetings

**Comment by ttodua** [comment]
Please see this answer, to the same problem: https://github.com/ccxt/ccxt/issues/14423
let us know if you have any issue (in next cases, you'd better to use search feature to find similar issues, as it will save time).
