### ISSUE TITLE
Kucoin Futures error retrieving data

### ISSUE THREAD

**Issue by ysonitis5** [ccxt/ccxt#14457]
- OS: Windows 10
- Programming Language version: Python 3.1
- CCXT version: 1.91.2

trying to fetch my current positing contractsize, amount of contracts and current margin value:

```
def open_positions():
    params = {'type':'swap', 'code':'USD'}
    symbol = 'BTC/USDT:USDT'
    ku_bal = kucoin.fetch_positions(symbols=[symbol], params=params)
    open_positions = ku_bal[0]
    open_positions = ku_bal['info']['data']['maintMargin']
    openpos_side = open_positions[0]['contracts']
    openpos_size = open_positions[0]['contractSize']
```

```
Traceback (most recent call last):
  File "reeee", line 310, in <module>
    bot()
  File "reeeee", line 251, in bot
    pnl_close() #checking if we hit pnl
  File "reeeeee", line 233, in pnl_close
    kill_switch()
  File "reeeeeee", line 136, in kill_switch
    openposi = open_positions()[1]
  File "reeeeee", line 112, in open_positions
    open_positions = ku_bal['info']['data']['maintMargin']
TypeError: list indices must be integers or slices, not str

```

**Comment by carlosmiei** [comment]
Hello @ysonitis5,

You're trying to access a non-existent field in the raw response, which is why it's crashing.

To fix it you can either search for the unified `maintenanceMargin` field, like this:
```Python
positions = kucoin.fetch_positions(symbols=[symbol], params=params)
maintenance_margin = positions['maintenanceMargin'] # the advisable way to get it
```
or access the correct raw value inside `info`, 

```Python
positions = kucoin.fetch_positions(symbols=[symbol], params=params)
maintenance_margin = positions['info']['posMaint'] # not recommended because APIs are always changing
```

**Comment by ysonitis5** [comment]
thank you very much  @carlosmiei

**Comment by carlosmiei** [comment]
@ysonitis5  You're welcome, since the problem seems resolved I will close the issue, let us know if anything!
