### ISSUE TITLE
Huobi swap linear fetchBalance error

### ISSUE THREAD

**Issue by WoosubLeee** [ccxt/ccxt#14464]
- OS: macOS
- Programming Language version: Node 14.10.0
- CCXT version: 1.90.89

I wanna get my balance in Huobi swap usdt-m account but it's not working. My API keys and proxy setting are okay because I can get my deposits with same ccxt exchange(using fetchDeposits()). But only fetchBalance() isn't working. Could you help me?

There is a parent class 'CcxtExchange' which has a common getBalance method for other exchanges. But I've overridden it with the child Huobi class method.

```ts
const proxy = "http://localhost:8080/";

class CcxtExchange {
  ccxtInst;

  constructor() {
    this.ccxtInst = new ccxt.Exchange();
  }

  async getBalance(ticker: string) {
    const res = await this.ccxtInst.fetchBalance();
    return res[ticker].total;
  }
}

export class Huobi extends CcxtExchange {
  ccxtInst;

  constructor(apiKey: string, secretKey: string) {
    super();
    this.ccxtInst = new ccxt.huobi({
      apiKey,
      secret: secretKey,
      options: {
        defaultType: "swap",
        defaultSubType: "linear",
        marginMode: "cross",
      },
      proxy,
    });
  }

  async getBalance(ticker: string): Promise<number> {
    this.ccxtInst.verbose = true;
    const res = await this.ccxtInst.fetchBalance();
    return 0;
  }
}
```

```
fetch Request:
 huobi POST http://localhost:8080/https://api.hbdm.com/linear-swap-api/v1/swap_cross_account_info?AccessKeyId=accessKeyId&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2022-07-24T05%3A43%3A41&Signature=signature
RequestHeaders:
 {Content-Type: 'application/json'} 
RequestBody:
 {} 

handleRestResponse:
 huobi POST http://localhost:8080/https://api.hbdm.com/linear-swap-api/v1/swap_cross_account_info?AccessKeyId=accessKeyId&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2022-07-24T05%3A43%3A41&Signature=signature 200 OK 
ResponseHeaders:
 {Access-Control-Allow-Origin: '*', Cache-Control: 'no-cache, no-store', Cf-Cache-Status: 'DYNAMIC', Cf-Ray: '72fa56f8a898c05d-ICN', Connection: 'close', …} 
ResponseBody:
 {"status":"error","err_code":1000,"err_msg":"System error.","ts":1658641422218} 

huobi.js:5549 Uncaught (in promise) ExchangeError: huobi {"status":"error","err_code":1000,"err_msg":"System error.","ts":1658641422218}
    at huobi.handleErrors (huobi.js:5549:1)
    at Exchange.js:598:1
    at async timeout (time.js:181:1)
    at async huobi.fetch2 (Exchange.js:1801:1)
    at async huobi.request (Exchange.js:1805:1)
    at async huobi.fetchBalance (huobi.js:2844:1)
    at async Huobi.getBalance (exchangeTool.ts:130:1)
    at async index.tsx:40:1
```

**Comment by carlosmiei** [comment]
Hello @WoosubLeee,

I just tested it on my end and seems to be working fine as you can see below. Could you try to fetch it again without the proxy? might be interfering with it.

```
2022-07-24T09:59:57.063Z
Node.js: v18.4.0
CCXT v1.91.20
huobi.fetchBalance ([object Object])
2022-07-24T09:59:57.063Z
Node.js: v18.4.0
CCXT v1.91.20
huobi.fetchBalance ([object Object])
RequestBody:
handleRestResponse:
 huobi POST https://api.hbdm.com/linear-swap-api/v1/swap_cross_account_info?AccessKeyId=REMOVED&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2022-07-24T09%3A59%3A58&Signature=HpX66IYwfMjtQH7Dyg7Fsgpl%2FnSxPT2r5Kr6pcReeCY%3D 200 OK 
ResponseHeaders:
2022-07-24T09:59:59.094Z iteration 0 passed in 422 ms

{
  info : {...}
  USDT: { free: 13.018546789524596, used: 0, total: 13.018546789524596 },
  free: { USDT: 13.018546789524596 },
  used: { USDT: 0 },
  total: { USDT: 13.018546789524596 }
}
2022-07-24T09:59:59.094Z iteration 1 passed in 422 ms

```

**Comment by ttodua** [comment]
The issue was answered by @carlosmiei and it seems correct to me, also the topic hasn't got any follow ups, so I'm closing this issue.
Let us know if you have any problems with CCXT.

**Comment by ttodua** [comment]
Also, note that your proxy does redirect `POST` request correctly, as your mentioned `fetchDeposits` worked because it uses `GET` method in the backgrounds, while `fetchBalance` uses `POST` method.
