### ISSUE TITLE
ModuleNotFoundError: No module named 'ccxt.async_support.vcc'

### ISSUE THREAD

**Issue by GemarPetere** [ccxt/ccxt#14501]
- OS: Windows 10
- Programming Language version: Python 3.10.1
- CCXTPRO version: 1.1.65

```
 #!/usr/bin/env python
 
import asyncio

import websockets
import ccxtpro
 
CONNECTIONS = set()
 
async def register(websocket):
    CONNECTIONS.add(websocket)
    try:
        await websocket.wait_closed()
    finally:
        CONNECTIONS.remove(websocket)

async def show_time():
    exchange = ccxtpro.binanceusdm({
        'apiKey': '',
        'secret': '',
    })

    exchange.set_sandbox_mode(True) 
    exchange.verbose = True
    
    while True:
        try:
            symbol ='BTC/USDT'
            orders = await exchange.watch_orders(symbol)
            websockets.broadcast(CONNECTIONS, str(orders))
            print(orders)
            print('---------------------------------------------------------------')
        except Exception as e:
            pass
            print(e)

    await exchange.close()

async def main():
    async with websockets.serve(register, "localhost", 5678):
        await show_time()

if __name__ == "__main__":
    asyncio.run(main())
```

```
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\CopyTrading\server.py", line 6, in <module>
    import ccxtpro
  File "d:\ccxt.pro-master\python\ccxtpro\__init__.py", line 130, in <module>
    from ccxt.async_support.vcc import vcc                                    # noqa: F401
ModuleNotFoundError: No module named 'ccxt.async_support.vcc'
```

**Comment by GemarPetere** [comment]
the first copy of the code is good but when I try to make a duplicate of it the error arised.

**Comment by kroitor** [comment]
@GemarPetere please, let us know if you have this issue with the most recent version of CCXT Pro (1.2+)

**Comment by GemarPetere** [comment]
ok do I need to update the library

**Comment by GemarPetere** [comment]
what should I do to stay updated? because I only have a downloaded ccxtpro file.

**Comment by ttodua** [comment]
You will no longer face the similar issue, as ccxt pro is now integrated in ccxt.
