### ISSUE TITLE
Not able to place stop_limit order in wazirx 

### ISSUE THREAD

**Issue by rahuljauhari3** [ccxt/ccxt#14514]
Hi, devs,

I am not able to place stop-limit order in wazir using ccxt. 
CCXT version 1.88.26 
macOS
I am trying 
```
self.order = self.exchange.create_order(
                                    symbol, 'stop_limit', 'sell', self.sell_amount, sellprice*0.99, params={"stopPrice": sellprice}) 
```
Error 
```
Traceback (most recent call last):
  File "/Users/rahuljauhari/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 617, in fetch
    response.raise_for_status()
  File "/Users/rahuljauhari/opt/anaconda3/lib/python3.9/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wazirx.com/sapi/v1/order?price=1342.6&quantity=0.003&recvWindow=10000&side=sell&stopPrice=1356.16&symbol=ethusdt&timestamp=1659014167223&type=stop_limit&signature=a5c92df005ba4c697b30d678028c4c57a129948d592f3b3c287e1792ed238a6b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rahuljauhari/Documents/GitHub/Wazirx-AWS-DEPLOYED/run_sell.py", line 26, in <module>
    obj3.sell_module(symbol[i], sellprice)
  File "/Users/rahuljauhari/Documents/GitHub/Wazirx-AWS-DEPLOYED/sell.py", line 78, in sell_module
    self.order = self.exchange.create_order(
  File "/Users/rahuljauhari/opt/anaconda3/lib/python3.9/site-packages/ccxt/wazirx.py", line 696, in create_order
    response = self.privatePostOrder(self.extend(request, params))
  File "/Users/rahuljauhari/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 497, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/rahuljauhari/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2616, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/Users/rahuljauhari/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/rahuljauhari/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 633, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/rahuljauhari/opt/anaconda3/lib/python3.9/site-packages/ccxt/wazirx.py", line 794, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/Users/rahuljauhari/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2834, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: wazirx {"message":"Stop price not found.","code":94001}


```

**Comment by carlosmiei** [comment]
Hey @rahuljauhari3 



That is weird because as you can see `stopPrice` is there

> https://api.wazirx.com/sapi/v1/order?                                        ↓ Here ↓
price=1342.6&quantity=0.003&recvWindow=10000&side=sell&stopPrice=1356.16&symbol=ethusdt&timestamp=1659014167223&type=stop_limit&signature=a5c92df005ba4c697b30d678028c4c57a129948d592f3b3c287e1792ed238a6b

We will take a look

**Comment by rahuljauhari3** [comment]
Hi @carlosmiei any updates on this.

**Comment by carlosmiei** [comment]
Hey @rahuljauhari3 sorry for the delay, we're having some difficulties with our test account but I'll let you know as soon as I get more information.

**Comment by carlosmiei** [comment]
Hello @rahuljauhari3 sorry for the delay, we finally managed to get a working account.

As you can see, I successfully placed a stop-limit "sell" order at Wazirx. Can you please double-check your parameters and try again?

```
 p wazirx createOrder "LTC/USDT" "stop_limit" "sell" 0.1 40 '{"stopPrice":40.12}' --verbose
Python v3.9.13
CCXT v1.91.72
wazirx.createOrder(LTC/USDT,stop_limit,sell,0.1,40,{'stopPrice': 40.12})

fetch Request: wazirx POST https://api.wazirx.com/sapi/v1/order?price=40&quantity=0.1&recvWindow=10000&side=sell&stopPrice=40.12&symbol=ltcusdt&timestamp=1659603428562&type=stop_limit&signature=8869bee5f42acb6c183bd8b0d07db2c78dfab21378223fc6b947a0fe4bfdb731 RequestHeaders: {'Content-Type': 'application/x-www-form-urlencoded', 'X-Api-Key': 't5Rl9IeZLf9sScEYGyBuctcd4IbvS73o3SzkiEY3jcoeXiv7p5GapvdnscJWrJfB', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: wazirx POST https://api.wazirx.com/sapi/v1/order?price=40&quantity=0.1&recvWindow=10000&side=sell&stopPrice=40.12&symbol=ltcusdt&timestamp=1659603428562&type=stop_limit&signature=8869bee5f42acb6c183bd8b0d07db2c78dfab21378223fc6b947a0fe4bfdb731 201 ResponseHeaders: {'Date': 'Thu, 04 Aug 2022 08:57:08 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '224', 'Connection': 'keep-alive', 'Server': 'openresty', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Max-Age': '1728000', 'Access-Control-Allow-Headers': 'User-Agent,Keep-Alive,Content-Type,access-key,api-key,signature,tonce,username,Recaptcha-Token,Recaptcha-Type,fingerPrint,timezone,platform,isBrowser', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, DELETE, PUT, PATCH'} ResponseBody: {"id":3308637499,"symbol":"ltcusdt","type":"stop_limit","side":"sell","status":"idle","price":"40","stopPrice":"40.12","origQty":"0.1","executedQty":"0","avgPrice":"0","createdTime":1659603428000,"updatedTime":1659603428000}
{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': 0.0,
 'datetime': '2022-08-04T08:57:08.000Z',
 'fee': None,
 'fees': [],
 'filled': 0.0,
 'id': '3308637499',
 'info': {'avgPrice': '0',
          'createdTime': '1659603428000',
          'executedQty': '0',
          'id': '3308637499',
          'origQty': '0.1',
          'price': '40',
          'side': 'sell',
          'status': 'idle',
          'stopPrice': '40.12',
          'symbol': 'ltcusdt',
          'type': 'stop_limit',
          'updatedTime': '1659603428000'},
 'lastTradeTimestamp': 1659603428000,
 'postOnly': None,
 'price': 40.0,
 'remaining': None,
 'side': 'sell',
 'status': 'idle',
 'symbol': 'LTC/USDT',
 'timeInForce': None,
 'timestamp': 1659603428000,
 'trades': [],
 'type': 'stop_limit'}
```

**Comment by rahuljauhari3** [comment]
Thanks @carlosmiei yes it is working fine now. Thankyou

**Comment by carlosmiei** [comment]
@rahuljauhari3 no problem, let us know if anything!
