### ISSUE TITLE
Bitget private Api currentTrack issue

### ISSUE THREAD

**Issue by twiGGx** [ccxt/ccxt#14533]
Hello,

I once dared to use the implicit private api and failed^^ - when I execute the following command:

`    currentTrack = bitget.privateMixGetTraceCurrentTrack({
        'symbol': 'BTC/USDT:USDT',
        'productType': 'umcbl',
        'pageSize': 1,
        'pageNo': 1
    })`

comes the error message:

`ccxt.base.errors.ExchangeError: bitget {"code":"40017","msg":"Parameter verification failed {0},User idNot currently a trader","requestTime":1658576985420,"data":null}`

Although I am registered as a trader and when I use the Bitget api directly, it works.

All other functions work too (order/close order etc).

What have I missed?

**Comment by carlosmiei** [comment]
Hello @twiGGx,

I'm unsure about the "not currently a trader" error, but I noticed an issue in your code. Since you're using the implicit API, you should use the exchange-specific `symbol` instead of the unified one; in this case, it would be `BTCUSDT_UMCBL`.

```Javascript
currentTrack = bitget.privateMixGetTraceCurrentTrack({ 'symbol': 'BTCUSDT_UMCBL', 'productType': 'umcbl', 'pageSize': 1, 'pageNo': 1 })
```
Can you check if this makes a difference for you?

**Comment by twiGGx** [comment]
Hello @carlosmiei,
thank you for your reply - in this case i get an empty list:

```
{
  "test": [
    "code", 
    "msg", 
    "requestTime", 
    "data"
  ]
}
```

although a follow position is currently open :/

**Comment by carlosmiei** [comment]
@twiGGx I would suggest contacting Bitget's support then, they might be able to clarify it.

**Comment by twiGGx** [comment]
@carlosmiei 
already done, unfortunately they couldn't help me either. The api-telegram admin said he only had a short briefing about ccxt. I fixed the problem by using the bitget-api itself, but I'd be interested to know why, as I like working with ccxt^^

**Comment by sc0Vu** [comment]
Hi @twiGGx

I think `BTC/USDT:USDT` is symbol for ccxt. In bitnet, the id of `BTC/USDT:USDT` is `BTCUSDT_UMCBL`, would you like to test with `'symbol': 'BTCUSDT_UMCBL'`?

**Comment by carlosmiei** [comment]
@kevinroku Can you share with us the request made by bitget SDK? If you can successfully make it using their adapter, you can certainly do the same using CCXT

**Comment by kevinroku** [comment]
@carlosmiei of course:

```
from localpackage.mix import trace_api as trace
traceApi = trace.TraceApi(config.API_KEY, config.API_SECRET, config.PASSPHRASE, use_server_time=False, first=False)

def trade_crypto(request):

    symbol = 'BTCUSDT_UMCBL'
    productType = 'umcbl'
    currentTracks = traceApi.current_track(symbol, productType, 20, 1)['data']
...
    return {
        "test": list(currentTracks)
    }
```

**Comment by carlosmiei** [comment]
@kevinroku it is very weird, the request above made with ccxt seems exactly the same: 🤔 
![image](https://user-images.githubusercontent.com/43336371/182673270-df984c9f-9a65-4710-87b4-87381f5b8ddb.png)

**Comment by TranQuangMinh** [comment]
I have the same problem
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/10704241/203265500-de3c917c-6bbe-4e5b-bbfd-3a4188952674.png">

**Comment by fridary** [comment]
@carlosmiei @kroitor 
Can you check please why I get this error below? I checked all other issues and can not figure out.
I also noticed ccxt requests `/api/mix/v1/market/fills` instead `/api/mix/v1/market/fills-history` (https://bitgetlimited.github.io/apidoc/en/mix/#get-recent-fills)
```python
import ccxt
print(ccxt.__version__)

exchange = ccxt.bitget()
exchange.options['defaultType'] = 'swap' # futures market
# exchange.options['productType'] = 'umcbl'
# exchange.options['pageSize'] = 1
# exchange.options['pageNo'] = 1

symbol = 'EOSUSDT_UMCBL'

markets = exchange.load_markets()
market = exchange.market(symbol)
exchange.verbose = True
since = exchange.parse8601('2023-08-01T00:00:00')
trades = exchange.fetch_trades(symbol, since)
print(len(trades), 'trades')
```

```
4.0.57

fetch Request: bitget GET https://api.bitget.com/api/mix/v1/market/fills?symbol=EOSUSDT_UMCBL&limit=1690848000000 RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitget GET https://api.bitget.com/api/mix/v1/market/fills?symbol=EOSUSDT_UMCBL&limit=1690848000000 400 ResponseHeaders: {'Date': 'Sat, 12 Aug 2023 16:38:25 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Request-ID': '018547480bbd4ff79a5081eac8b6e4dc', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'requestTime': '1691858304961', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=vGJXxDItyQfAHeB1lhHKu9AldQwqzh9Ch0WpPL8VvUs-1691858305-0-AUdbavKCuhD3SR9NJBwPwilBeqI1wZGVJObD2f/h1bkABnBOcNLFv7gP2eUrT96WKz8EQ5xkZbPAjWWOFgdR5sk=; path=/; expires=Sat, 12-Aug-23 17:08:25 GMT; domain=.bitget.com; HttpOnly; Secure; SameSite=None, _cfuvid=Q5a5vVZ6T3Y4SoiCLw3j6IQgj5EKmza0N1UuWPzXE1Y-1691858305105-0-604800000; path=/; domain=.bitget.com; HttpOnly; Secure; SameSite=None', 'X-Frame-Options': 'SAMEORIGIN', 'Server': 'cloudflare', 'CF-RAY': '7f5a2604ebfc7b33-DME'} ResponseBody: {"code":"400172","msg":"Parameter verification failed","requestTime":1691858304961,"data":null}
Traceback (most recent call last):
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/base/exchange.py", line 600, in fetch
    response.raise_for_status()
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitget.com/api/mix/v1/market/fills?symbol=EOSUSDT_UMCBL&limit=1690848000000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test5.py", line 17, in <module>
    trades = exchange.fetch_trades(symbol, since)
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/bitget.py", line 2185, in fetch_trades
    response = self.publicMixGetMarketFills(extended)
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3019, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3016, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/base/exchange.py", line 616, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/bitget.py", line 4638, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bitget {"code":"400172","msg":"Parameter verification failed","requestTime":1691858304961,"data":null}
```

**Comment by fridary** [comment]
@carlosmiei @kroitor I found bug, wrong `since` param converting. `since = exchange.parse8601('..')` converts to `1690848000000` instead `1690848000`

**Comment by ttodua** [comment]
closing this old issue, the private / implicit methods seem to work correctly, you just need to look into the lib which implicit methods are supported : https://docs.ccxt.com/#/README?id=view-implicit-methods-list

let us know if anyone has any further issues. if issue is different, please open a new topic.
