### ISSUE TITLE
Can't withdraw asset from idex

### ISSUE THREAD

**Issue by KaitaoQiu** [ccxt/ccxt#14530]
- OS: Linux
- Programming Language version: python
- CCXT version: 1.90.36

I tried to withdraw some asset from idex, but it failed.
code is simple like `idex_client.withdraw(quote_asset, 100, idex_client.walletAddress)`

```
Traceback (most recent call last):
  File "/home/azureuser/anaconda3/envs/sci_common/lib/python3.8/site-packages/ccxt/base/exchange.py", line 619, in fetch
    response.raise_for_status()
  File "/home/azureuser/anaconda3/envs/sci_common/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api-matic.idex.io/v1/withdrawals

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/azureuser/anaconda3/envs/sci_common/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "ccxt_wash.py", line 60, in main
    idex_client2.withdraw(quote_asset, 100, idex_client2.walletAddress)
  File "/home/azureuser/anaconda3/envs/sci_common/lib/python3.8/site-packages/ccxt/idex.py", line 1292, in withdraw
    response = self.privatePostWithdrawals(request)
  File "/home/azureuser/anaconda3/envs/sci_common/lib/python3.8/site-packages/ccxt/base/exchange.py", line 499, in inner
    return entry(_self, **inner_kwargs)
  File "/home/azureuser/anaconda3/envs/sci_common/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2619, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/azureuser/anaconda3/envs/sci_common/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2616, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/azureuser/anaconda3/envs/sci_common/lib/python3.8/site-packages/ccxt/base/exchange.py", line 635, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/azureuser/anaconda3/envs/sci_common/lib/python3.8/site-packages/ccxt/idex.py", line 1385, in handle_errors
    raise ExchangeError(self.id + ' ' + message)
ccxt.base.errors.ExchangeError: idex The API Key used does not have "withdraw" scope, but is required to access the endpoint requested
```

**Comment by carlosmiei** [comment]
Hello @KaitaoQiu Just looking at the error message, I would say you need to add 'withdraw' permission to your API keys

You need to select this withdraw checkbox ↓
![image](https://user-images.githubusercontent.com/43336371/181784016-2d2505cb-6059-4bdc-82dd-a55be21394c4.png)
