### ISSUE TITLE
gateio does not check volume for 'nan' in fetch_tickers for future 

### ISSUE THREAD

**Issue by ulturgashev** [ccxt/ccxt#14611]
- OS: Ubuntu 20.04
- Programming Language version: Python 3.8.10
- CCXT version: 1.91.71

```
import ccxt

gate = ccxt.gate()
gate.options['defaultType'] = 'future'
x = gate.fetch_tickers()
```

exception:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    x = gate.fetch_tickers()
  File "/home/yc-user/dropstab-cex-loader/.env/lib/python3.8/site-packages/ccxt/gate.py", line 1943, in fetch_tickers
    return self.parse_tickers(response, symbols)
  File "/home/yc-user/dropstab-cex-loader/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3123, in parse_tickers
    ticker = self.extend(self.parse_ticker(tickers[i]), params)
  File "/home/yc-user/dropstab-cex-loader/.env/lib/python3.8/site-packages/ccxt/gate.py", line 1903, in parse_ticker
    return self.safe_ticker({
  File "/home/yc-user/dropstab-cex-loader/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2293, in safe_ticker
    vwap = Precise.string_div(quoteVolume, baseVolume)
  File "/home/yc-user/dropstab-cex-loader/.env/lib/python3.8/site-packages/ccxt/base/precise.py", line 199, in string_div
    string2_precise = Precise(string2)
  File "/home/yc-user/dropstab-cex-loader/.env/lib/python3.8/site-packages/ccxt/base/precise.py", line 28, in __init__
    self.integer = int(number)
ValueError: invalid literal for int() with base 10: 'nan'
```

**Comment by sc0Vu** [comment]
Thanks for report, I didn't see this (nan) in documentation. Anyway, we'll fix this.
