### ISSUE TITLE
Error: too much request weight used; IP banned until ...

### ISSUE THREAD

**Issue by h0o0bA** [ccxt/ccxt#14639]
- OS: Google Cloud Functions
- Programming Language version: Python 3.8
- CCXT version: not sure

Error: ``` ccxt.base.errors.DDoSProtection: binance 418 I'm a teapot {"code":-1003,"msg":"Way too much request weight used; IP banned until 1660090423228. Please use the websocket for live updates to avoid bans." ```

I am getting the error quite often recently, which wasn't the case for a long time using the same code.
Does anyone know any solution for this, and what causing it?

The full error code on the log:
```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 100, in view_func
    return function(request._get_current_object())
  File "/workspace/main.py", line 22, in trade_crypto
    order = binance.create_order(markets_by_id, 'market', side, quantity)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/binance.py", line 2827, in create_order
    self.load_markets()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1445, in load_markets
    markets = self.fetch_markets(params)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/binance.py", line 1448, in fetch_markets
    response = getattr(self, method)(query)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/base/exchange.py", line 497, in inner
    return entry(_self, **inner_kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/binance.py", line 5471, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2617, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/base/exchange.py", line 633, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/ccxt/binance.py", line 5398, in handle_errors
    raise DDoSProtection(self.id + ' ' + str(code) + ' ' + reason + ' ' + body)
ccxt.base.errors.DDoSProtection: binance 418 I'm a teapot {"code":-1003,"msg":"Way too much request weight used; IP banned until 1660090423228. Please use the websocket for live updates to avoid bans."}
 ```
 
 Here is my Python code for CCXT:
 ```
import ccxt, config

binance = ccxt.binance ({
    'apiKey': config.API_KEY,
    'secret': config.API_SECRET
    })

def trade_crypto(request):
    data = request.get_json()
    if 'passphrase' not in data or data['passphrase'] != config.PASSPHRASE:
        return {
            "code": "error",
            "message": "Invalid pass"
        }

    price = data['strategy']['order_price']
    side = data['strategy']['order_action']
    quantity = data['strategy']['order_contracts']
    symbol = data['ticker']
    markets_by_id = data['ticker']
    order = binance.create_order(markets_by_id, 'market', side, quantity)

    return order
```

I really appreciate any help anyone can provide!

**Comment by sc0Vu** [comment]
This rate limit is binded with IP, it works on my single computer (without others calling binance api). Is that possible that api call sent from the same IP?

**Comment by h0o0bA** [comment]
Not understanding what that means.
And if there is a workaround to work with this change?

Source: https://binance-docs.github.io/apidocs/spot/en/#change-log
<img width="572" alt="Screen Shot 2022-08-10 at 5 11 16 PM" src="https://user-images.githubusercontent.com/47971028/184029513-a20e0b21-ceb5-4b3a-bf24-ef4dd8f08720.png">

**Comment by kroitor** [comment]
@h0o0bA make sure you're not violating this rule: https://docs.ccxt.com/en/latest/manual.html#notes-on-rate-limiter

**Comment by bugsbunny110** [comment]
I also have the same error, any help on fixing that?

**Comment by carlotestor** [comment]
The likely cause is visible in your traceback: `create_order` calls `self.load_markets()`, and on Google Cloud Functions **every invocation constructs a fresh exchange instance**, so the markets cache is empty and each request re-downloads the full `exchangeInfo` (weight 20 on spot). A few hundred invocations and you're over the IP weight budget → `-1003` and a temporary ban. `enableRateLimit` can't help, because each new instance starts with an empty throttler and they all share one egress IP.

Two fixes, both worth doing:

1. **Hoist the exchange to module scope** so warm instances reuse it:
```python
import ccxt
binance = ccxt.binance({'apiKey': ..., 'secret': ..., 'enableRateLimit': True})
markets = binance.load_markets()          # runs once per cold start, not per request

def trade_crypto(request):
    return binance.create_order(symbol, 'market', side, quantity)
```

2. **Pre-load markets from cache** if cold starts are frequent — persist `binance.markets` to GCS/Redis and restore with `binance.set_markets(cached)` to skip the call entirely.

Also relevant: on serverless, many concurrent instances share the same NAT IP, so their weight sums together — see https://docs.ccxt.com/#/README?id=notes-on-rate-limiter (the note @kroitor linked). Fixing the per-invocation `load_markets()` removes the bulk of the weight.
