### ISSUE TITLE
Set Trailing-Stop on Bybit

### ISSUE THREAD

**Issue by arelysfajardo** [ccxt/ccxt#14636]
I have been trying to define a trailing_stop when creating a limit order in the following way:

bybit.create_limit_buy_order(symbol, size, price, params = {'post_only': True, 'trailing_stop': atr})

I get no error but the order is created without the associated trailing_stop value.

Thank you in advance for your help.

**Comment by carlosmiei** [comment]
Hello @arelysfajardo,

I'm not sure yet if this can be done upon placing the order, I will confirm with bybit's support and revert asap. 

Looking at their docs, I see it can be set after placing it, using this endpoint:https://bybit-exchange.github.io/docs/linear/#t-tradingstop

**Comment by carlosmiei** [comment]
@arelysfajardo As I suspected, we can't do it in one step, but we can set the trailing stop immediately after opening the position. 

Please check these examples demonstrating it: https://github.com/ccxt/ccxt/pull/14646/files

**Comment by arelysfajardo** [comment]
Thank you very much for your prompt response.

I understand that it is not possible to create the order with the trailing stop in a single step, but it is possible to configure it once the position is opened. 

The only doubt I have is regarding this function: privatePostPrivateLinearPositionTradingStop

I don't see it available in the ccxt library.

**Comment by arelysfajardo** [comment]
It already worked! Thank you very much!

**Comment by mawildcat** [comment]
> It already worked! Thank you very much!

How did you get the asfa method: privatePostPrivateLinearPositionTradingStop ??

**Comment by mawildcat** [comment]
> @arelysfajardo As I suspected, we can't do it in one step, but we can set the trailing stop immediately after opening the position.
> 
> Please check these examples demonstrating it: https://github.com/ccxt/ccxt/pull/14646/files


How did you get the asfa method: privatePostPrivateLinearPositionTradingStop ??

**Comment by IsaTTeN** [comment]
Hello I am interested in this as well. How do you configure the trailer stop price and offset?

**Comment by LuCeHe** [comment]
Hi, the examples did not change since a year ago, and I think there's conflicts with new parts of the code. The example above https://github.com/ccxt/ccxt/blob/master/examples/py/bybit-trailling.py fails at line 73

```trailing_response = await exchange.privatePostPrivateLinearPositionTradingStop(params)```

with this error

```
Traceback (most recent call last):
  File "C:\Users\PlasticDiscobolus\work\kiwano_discoveries\automate_youtubers_strats\ccxt_example.py", line 96, in <module>
    asyncio.run(main())
  File "C:\Users\PlasticDiscobolus\miniconda3\envs\denv2\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\PlasticDiscobolus\miniconda3\envs\denv2\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\PlasticDiscobolus\work\kiwano_discoveries\automate_youtubers_strats\ccxt_example.py", line 93, in main
    await example_2()
  File "C:\Users\PlasticDiscobolus\work\kiwano_discoveries\automate_youtubers_strats\ccxt_example.py", line 73, in example_2
    trailing_response = await exchange.privatePostPrivateLinearPositionTradingStop(params)
  File "C:\Users\PlasticDiscobolus\miniconda3\envs\denv2\lib\site-packages\ccxt\async_support\base\exchange.py", line 1839, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
  File "C:\Users\PlasticDiscobolus\miniconda3\envs\denv2\lib\site-packages\ccxt\async_support\base\exchange.py", line 1836, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\PlasticDiscobolus\miniconda3\envs\denv2\lib\site-packages\ccxt\async_support\base\exchange.py", line 221, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\PlasticDiscobolus\miniconda3\envs\denv2\lib\site-packages\ccxt\async_support\bybit.py", line 8524, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bybit {"ret_code":130001,"ret_msg":"position idx not match position mode","result":{},"ext_code":"","ext_info":"","time_now":"1694181556.581052","rate_limit_status":74,"rate_limit":75,"rate_limit_reset_ms":1694181556579}
bybit requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021F4DC41DF0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000021F4DE28100>, 2117.578), (<aiohttp.client_proto.ResponseHandler object at 0x0000021F4DC51D00>, 2117.703), (<aiohttp.client_proto.ResponseHandler object at 0x0000021F4DC83D60>, 2117.734), (<aiohttp.client_proto.ResponseHandler object at 0x0000021F4DE28A00>, 2117.937), (<aiohttp.client_proto.ResponseHandler object at 0x0000021F4DE28760>, 2118.062), (<aiohttp.client_proto.ResponseHandler object at 0x0000021F4DE36160>, 2120.0)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000021F4DC41D60>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000021F4DE23C70>
transport: <_ProactorSocketTransport fd=632 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\PlasticDiscobolus\miniconda3\envs\denv2\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\PlasticDiscobolus\miniconda3\envs\denv2\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\PlasticDiscobolus\miniconda3\envs\denv2\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000021F4AB83C10>
```

**Comment by Crypto1Nerd** [comment]
> It already worked! Thank you very much!

How did you manage to make it work please
