### ISSUE TITLE
PHP: Gemini nonce impl is broken

### ISSUE THREAD

**Issue by GittyGitGitGitty** [ccxt/ccxt#14693]
- OS: Arch Linux
- Programming Language version: PHP 8.1.9
- CCXT version: Introduced in `1.91.84` via c1f4f4e2944ed2732a662ddca456f31bb3a5c9d3, affects current version

```
$gemini = new \ccxt\gemini(array(
        'apiKey' => 'XXXXXXX',
        'secret' =>  'XXXXXXX',
        'enableRateLimit' => true));

// Calling API request function directly for various reasons (not using fetch_my_trades)
$gemini->request('v1/mytrades', 'private', 'POST', ['symbol' => $symbol, 'timestamp' => $timestamp, 'limit_trades' => $limit], null, null, array(), array());
```

```
PHP Fatal error:  Uncaught ccxt\InvalidNonce: gemini Nonce 'XXXXXXXXXX' has not increased since your last call to the Gemini API. in /ccxt/ccxt/php/Exchange.php:3754
Stack trace:
#0 /ccxt/ccxt/php/gemini.php(1471): ccxt\Exchange->throw_exactly_matched_exception()
#1 /ccxt/ccxt/php/Exchange.php(1823): ccxt\gemini->handle_errors()
#2 /ccxt/ccxt/php/Exchange.php(3454): ccxt\Exchange->fetch()
#3 /ccxt/ccxt/php/Exchange.php(3458): ccxt\Exchange->fetch2()
```

Rolling back https://github.com/ccxt/ccxt/commit/c1f4f4e2944ed2732a662ddca456f31bb3a5c9d3 to `1.91.83` fixes the problem. May be relevant for https://github.com/ccxt/ccxt/issues/13949.

**Comment by carlosmiei** [comment]
Hi @GittyGitGitGitty, we will apply a patch very soon, thanks for reporting it!
