### ISSUE TITLE
Issue with gateio future fetch_balance

### ISSUE THREAD

**Issue by deFang** [ccxt/ccxt#14694]
```
## initialize
exchange = ccxt.gateio({
            'apiKey': apikeys['gate']['apikey'],
            'secret': apikeys['gate']['secret'],
            'options': {
                'defaultType': 'future',
            }

## fetch balance
exchange.fetch_balance()
```

it'll throw out an error:
```
2022-08-16 05:26:12,805 [ERROR] Exception on /get_balance [GET]
Traceback (most recent call last):
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.gateio.ws/api/v4/delivery/btc/accounts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 64, in get_balance
    balance = bot.getBalance(exchange)
  File "/home/daniel/deploy/flashquant-flask/bot.py", line 175, in getBalance
    balance = self.exchanges[exchange_str].fetch_balance()
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ccxt/gate.py", line 1983, in fetch_balance
    response = getattr(self, method)(self.extend(request, requestQuery))
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2627, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2624, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ccxt/gate.py", line 4413, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], label, feedback)
  File "/home/daniel/miniconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2867, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.PermissionDenied: gateio {"label":"FORBIDDEN","message":"Request API key does not have delivery permission"}
```

**Comment by carlosmiei** [comment]
Hello @deFang,

> "Request API key does not have delivery permission"

Please double check your API key permissions

**Comment by samgermain** [comment]
If you're tying to use perpetual futures, the `defaultType` should be set to `swap`

**Comment by ttodua** [comment]
issue closed.
