### ISSUE TITLE
problem with idex watch_order_book !@ccxt.base.errors.InvalidNonce: idex failed to synchronize WebSocket feed with the snapshot for symbol ETH/USDC in 10 attempts

### ISSUE THREAD

**Issue by ivancomp0000** [ccxt/ccxt#14701]
continue https://github.com/ccxt/ccxt/issues/14681

- OS: macOS Monterey 12.4
- Programming Language version: Python 3.10.4
- CCXT version: 1.2.14

```
import ccxtpro
from asyncio import run

async def main():
    exchange3 = ccxtpro.idex({'newUpdates': False})
    for i in range (100):
        orderbook5 = await exchange3.watch_order_book('ETH-USDC')
        print(orderbook5['asks'][0], orderbook5['bids'][0])
    await exchange3.close()
run(main())
```

```
Traceback (most recent call last):
  File "/Users/sergey/PycharmProjects/pythonProject/pythonProject2/Trade_1/test_ccxtpro_websocket.py", line 44, in <module>
    run(main())
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/sergey/PycharmProjects/pythonProject/pythonProject2/Trade_1/test_ccxtpro_websocket.py", line 23, in main
    orderbook5 = await exchange3.watch_order_book('ETH-USDC')
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/idex.py", line 371, in watch_order_book
    orderbook = await self.subscribe(subscribeObject, messageHash, subscription)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/idex.py", line 52, in subscribe
    return await self.watch(url, messageHash, request, messageHash, subscription)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/idex.py", line 347, in fetch_order_book_snapshot
    raise InvalidNonce(self.id + ' failed to synchronize WebSocket feed with the snapshot for symbol ' + symbol + endpart)
ccxt.base.errors.InvalidNonce: idex failed to synchronize WebSocket feed with the snapshot for symbol ETH/USDC in 10 attempts
idex requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
```

**Comment by carlosmiei** [comment]
Hello @ivancomp0000 yes our default "re-try" values won't work especially when the liquidity is low and Idex takes too long to send the data.

As a temporary workaround and can you try to increase `fetchOrderBookSnapshotMaxAttempts` and `fetchOrderBookSnapshotMaxDelay` to much higher values?

Example:

```Python
exchange.options['fetchOrderBookSnapshotMaxAttempts'] = 100 # default is 20
exchange.options['fetchOrderBookSnapshotMaxDelay'] = 100000 # default is 10000 (10 seconds)
```
