### ISSUE TITLE
binanceus {"code":-1100,"msg":"Illegal characters found in a parameter."}

### ISSUE THREAD

**Issue by Salz0** [ccxt/ccxt#14819]
- OS: Windows 11
- Programming Language version: python 3.10
- CCXT version: 1.92.87

Hi, booted some code I didn't use for 1-2 weeks, and it suddenly stopped working, I'll be grateful if you take a look at it

```
for exchange_ in exchange_dict.values():
    exchange_.verbose = True
    if exchange_.has.get("fetchTransactionFees", False):
        exchange_.fetchTransactionFee(
            "USDT", params={"type": "withdraw", "network": "ERC20"}
        )
        logger.success(f"💸 Loaded {exchange_} fees")
```

verbose output:
```
fetch Request: binanceus GET https://api.binance.us/sapi/v1/capital/config/getall?timestamp=1661790039582&recvWindow=10000&signature=db771e8f2e687e63c81008005bc2a58c40bdf5c688ffe390c63a28bac37fc5c9 RequestHeaders: {'X-MBX-APIKEY': '', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: binanceus GET https://api.binance.us/sapi/v1/capital/config/getall?timestamp=1661790039582&recvWindow=10000&signature=db771e8f2e687e63c81008005bc2a58c40bdf5c688ffe390c63a28bac37fc5c9 400 ResponseHeaders: {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '63', 'Connection': 'keep-alive', 'Date': 'Mon, 29 Aug 2022 16:20:40 GMT', 'Server': 'nginx', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 13914648531ab1415de27d094b270f72.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MIA3-P1', 'X-Amz-Cf-Id': '-c1E_PvJPumOxWldjRV1zHrciioj2bB7M6ZvDXtgOY0uryJ6S_pDpg=='} ResponseBody: {"code":-1100,"msg":"Illegal characters found in a parameter."}

Traceback (most recent call last):
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 620, in fetch
    response.raise_for_status()
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.us/sapi/v1/capital/config/getall?timestamp=1661790039582&recvWindow=10000&signature=db771e8f2e687e63c81008005bc2a58c40bdf5c688ffe390c63a28bac37fc5c9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dimon\Desktop\crypto_arbitrage_alpha\main.py", line 123, in <module>
    main()
  File "C:\Users\dimon\Desktop\crypto_arbitrage_alpha\main.py", line 35, in main
    exchange_.fetchTransactionFee(
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2794, in fetch_transaction_fee
    return self.fetch_transaction_fees([code], params)
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\binance.py", line 4073, in fetch_transaction_fees
    self.load_markets()
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 1430, in load_markets
    currencies = self.fetch_currencies()
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\binance.py", line 1304, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\binance.py", line 5512, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2607, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\binance.py", line 5490, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Users\dimon\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2853, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binanceus {"code":-1100,"msg":"Illegal characters found in a parameter."}
```

**Comment by carlosmiei** [comment]
Hello @Salz0, thanks for reporting it, we will investigate it

**Comment by carlosmiei** [comment]
@Salz0 Which location are you using to access `binanceus`?

**Comment by Salz0** [comment]
> @Salz0 Which location are you using to access `binanceus`?

From the US

**Comment by Salz0** [comment]
Hey @carlosmiei, any updates?

**Comment by carlosmiei** [comment]
Hello @Salz0 , sorry I missed the last message, that is indeed very weird, we only get that error when accessing binanceus from exotic locations, but if you're accessing it directly from the US it should not be related to your location. Do you have this error for every private endpoint or only `fetchTransactionFees`?

**Comment by Salz0** [comment]
> Hello @Salz0 , sorry I missed the last message, that is indeed very weird, we only get that error when accessing binanceus from exotic locations, but if you're accessing it directly from the US it should not be related to your location. Do you have this error for every private endpoint or only `fetchTransactionFees`?

Unfortunately, from every private endpoint, f.e. loading the market

**Comment by Salz0** [comment]
> Hello @Salz0 , sorry I missed the last message, that is indeed very weird, we only get that error when accessing binanceus from exotic locations, but if you're accessing it directly from the US it should not be related to your location. Do you have this error for every private endpoint or only `fetchTransactionFees`?

Hey @carlosmiei, any updates, maybe you have some hint how I would be able to handle this issue myself

**Comment by Salz0** [comment]
Hey @carlosmiei , any updates, maybe you have some hint how I would be able to handle this issue myself

**Comment by carlosmiei** [comment]
hey @Salz0 sorry for the delay, unfortunately no so I'd suggest reaching out to Binance directly

**Comment by ttodua** [comment]
@Salz0 have you considered to check the api keys, like this user? https://github.com/ccxt/ccxt/issues/14651

**Comment by ttodua** [comment]
topic didn't get further updates since last post. If anyone still experiences this issue, let us know again.
