### ISSUE TITLE
Binance market orders not working.

### ISSUE THREAD

**Issue by Sevaltair** [ccxt/ccxt#14854]
- OS: Windows 10
- Programming Language version: Python 3.10.5
- CCXT version: 1.92.97

Tried closing a short trade using a market order. error showed parameter 'quantity' is required. the code used to work couple of days before, suddenly stopped working. 

```
binance.create_order(symbol='BTC/USDT', type='MARKET', side='buy', amount=open_pos, params={'reduceOnly':True})
```

```

fetch Request: binanceusdm POST https://fapi.binance.com/fapi/v1/order RequestHeaders: {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: timestamp=1662138989719&symbol=BTCUSDT&type=MARKET&side=BUY&newClientOrderId=x-xcKtGhcu86d3115f0515b729056315&newOrderRespType=RESULT&quantity=-0.025&reduceOnly=true&recvWindow=60000&signature=fc7dbc3da090213449b8c9de60d3de78cb277861bab531244a90add86a43069a

fetch Response: binanceusdm POST https://fapi.binance.com/fapi/v1/order 400 ResponseHeaders: {'Content-Type': 'application/json', 'Content-Length': '97', 'Connection': 'keep-alive', 'Date': 'Fri, 02 Sep 2022 17:16:38 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '1', 'X-MBX-ORDER-COUNT-10S': '0', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '4ms',
'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 5ad6862c6ee7084c2d40949298dbad76.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN54-C1', 'X-Amz-Cf-Id': 'YcqZuPv54mp2eoZoIBF2NugGQ76IMkf1xRLxcQrWXwH-1nEBBDB63w=='} ResponseBody: {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or malformed."}

Traceback (most recent call last):
  File "C:\Users\Sev\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 620, in fetch
    response.raise_for_status()
  File "C:\Users\Sev\anaconda3\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Sev\Trading Bot\Live Bot\Prototype\CCXT\issue.py", line 16, in <module>
    binance.create_order(symbol='BTC/USDT', type='MARKET', side='buy', amount=-0.025, params={'reduceOnly':True})
  File "C:\Users\Sev\anaconda3\lib\site-packages\ccxt\binance.py", line 2970, in create_order
    response = getattr(self, method)(self.extend(request, requestParams))
  File "C:\Users\Sev\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Sev\anaconda3\lib\site-packages\ccxt\binance.py", line 5557, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\Sev\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 2607, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Sev\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Sev\anaconda3\lib\site-packages\ccxt\binance.py", line 5535, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Users\Sev\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 2853, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binanceusdm {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or malformed."}
```

**Comment by samgermain** [comment]
Is `open_pos` undefined? We can't really answer your question without seeing more of your code. Could you write a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Sevaltair** [comment]
Hi, sorry open_pos is the open positions I have, because I'm using the create_order as a stop loss. But, its working now so I don't think its a code problem. I think its a problem with our IP address moving to the USA, or maybe my connection was too slow. Thanks.
