### ISSUE TITLE
recv_window error in bybit

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14870]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.90.94",
Exchange: bybit
Method: bybit

I work with Bybit exchange. Sometimes I get the following error in all functions:
{"ret_code":10002,"ret_msg":"invalid request,please check your server timestamp or recv_window param","ext_code":"","result":null,"ext_info":null,"time_now":1662312969541}

code :
            exchange = ccxt.bybit({
                'enableRateLimit': True,
                'apiKey': api_key,
                'secret': api_secret,
                'options': {
                    'adjustForTimeDifference': True,
                    'verbose': True,
                    'defaultType': 'spot',
                },
            })
            exchange.options['recvwindow'] = 10000

            obj = exchange.fetch_balance()

verbose output :
fetch Response: bybit GET https://api.bybit.com/asset/v1/private/coin-info/query?api_key=*******&recv_window=5000&timestamp=1662313308294&sign=*************** 200 
ResponseHeaders: {'Content-Type': 'application/json', 'Content-Length': '171', 'Server': 'Openresty', 'Expires': 'Sun, 04 Sep 2022 17:41:59 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 04 Sep 2022 17:41:59 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":10002,"ret_msg":"invalid request,please check your server timestamp or recv_window param","ext_code":"","result":null,"ext_info":null,"time_now":1662313319418}
bybit error account balance bybit {"ret_code":10002,"ret_msg":"invalid request,please check your server timestamp or recv_window param","ext_code":"","result":null,"ext_info":null,"time_now":1662313319418}

I try another value for recv_window, but this problem is not solved
and my system clock time sync to utc

@carlosmiei @kroitor 
please help me for solve this problem

**Comment by hosseinab** [comment]
how can i use this api "https://api.bybit.com/v2/public/time" for timestamp params ?
If we use this value for this parameter, the problem will be solved.

**Comment by carlosmiei** [comment]
Hello @hosseinab, the only alternative I see to replace the timestamp is by doing something like this: (patching bybit class and override nonce(), we can't do the API call directly inside it because it's not async)

```Python
import ccxt.async_support as ccxt  # noqa: E402

class Bybit(ccxt.bybit):
    def nonce(self):
        return self.safe_integer(self.options, 'customTimestamp')

async def test():
    bybit = Bybit({
    })
    # You HAVE to fetch and set this every time before calling any private method
    customTimestamp = await bybit.fetch_time()
    bybit.options['customTimestamp'] = customTimestamp
    ## YOUR CALL HERE
    balance = await bybit.fetch_balance()
    await bybit.close()

asyncio.run(test())
```

Can you check if this works for you?

**Comment by hosseinab** [comment]
@carlosmiei thank you for comment
this code has error :
`[2022-09-05 17:21:02,008] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\async_support\base\exchange.py", line 119, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\aiohttp\client.py", line 466, in _request
    with timer:
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\aiohttp\helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Hosein\PycharmProjects\pump\views\mainViews.py", line 30, in home
    asyncio.run(test())
  File "C:\Users\Hosein\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Hosein\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Hosein\PycharmProjects\pump\views\mainViews.py", line 20, in test
    customTimestamp = await bybit.fetch_time()
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\async_support\bybit.py", line 598, in fetch_time
    response = await self.publicGetV2PublicTime(params)
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\async_support\base\exchange.py", line 1125, in request
    return await self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\async_support\base\exchange.py", line 1122, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\async_support\base\exchange.py", line 153, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: bybit GET https://api.bybit.com/v2/public/time
`

**Comment by carlosmiei** [comment]
Hello @hosseinab, sorry we can't just blindly override `nonce` because it will be needed for some requests (markets, time, etc)

Can you try this new version?

```Python
class Bybit(ccxt.bybit):
    def nonce(self):
        timestamp = self.safe_integer(self.options, 'customTimestamp')
        if timestamp is None:
            timestamp = self.milliseconds()
        return timestamp

async def test():
    bybit = Bybit({
    })
    bybit.set_sandbox_mode(True)
    # You HAVE do set this every time before calling any private method
    customTimestamp = await bybit.fetch_time()
    bybit.options['customTimestamp'] = customTimestamp
    ## YOUR CALL HERE
    balance = await bybit.fetch_balance()
    ## reset value
    bybit.options['customTimestamp'] = None
    print(balance)
    await bybit.close()

asyncio.run(test())
```

**Comment by hosseinab** [comment]
@carlosmiei thank you .

get this error when run code : 
   self.check_required_credentials()
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\async_support\base\exchange.py", line 1259, in check_required_credentials
    raise AuthenticationError(self.id + ' requires "' + key + '" credential')
ccxt.base.errors.AuthenticationError: bybit requires "apiKey" credential



when run this code with api key and secret :
        bybit = Bybit({
                'apiKey': "rsFXwWaMRaSOJC2DPO",
                'secret': "****",
            })
get this error :
ccxt.base.errors.AuthenticationError: bybit {"ret_code":10003,"ret_msg":"invalid api_key","ext_code":"","result":null,"ext_info":null,"time_now":1662460341224}

my api key and secret is valid

**Comment by ttodua** [comment]
@hosseinab just remove `bybit.set_sandbox_mode(True)` and it should work.

**Comment by hosseinab** [comment]
@carlosmiei 
run your code in a loop . often time returns recv_window error

@ttodua 
run your code in a loop . output :
295
300
294
291
299
331
295
293
297
335
297
290
295
300

**Comment by ttodua** [comment]
this seems really weird and exceptional issue. As the time doesn't seem to differ from exchange's time significantly (to consider also the roundtrip time, your and exchange's time might not differ at all), So, one of the two possible things that might cause issue:
- exchange is misbehaving
- somewhere in your codes `.options['recvwindow']` being set to a very low edge value.

@carlosmiei have you any more thoughts?

**Comment by emorling** [comment]
Any news on this? Seems to be a recurring issue which pops up quite often

**Comment by hosseinab** [comment]
@ttodua @carlosmiei @emorling 
It is the same for me

**Comment by carlosmiei** [comment]
@hosseinab @emorling Have you tried to synchronize your clocks with UTC using NTP?https://www.baeldung.com/linux/sync-time-with-network

**Comment by emorling** [comment]
> @hosseinab @emorling Have you tried to synchronize your clocks with UTC using NTP?https://www.baeldung.com/linux/sync-time-with-network

I'm not using a managed environment where I can set clock. Is that a requirement?

**Comment by carlosmiei** [comment]
@emorling most of the time, that's what causes the timestamps errors

**Comment by hosseinab** [comment]
@carlosmiei 
I use Windows

**Comment by kroitor** [comment]
@hosseinab you will need to configure system clock sync on windows, just enabling the timesync checkbox in your time settings does not solve the trick, cause it skews. You will have to edit your registry as described in these issues:
- https://github.com/ccxt/ccxt/issues/850
- https://github.com/ccxt/ccxt/issues/936
Let us know if that does not help.

**Comment by hosseinab** [comment]
@kroitor 
thank you for response . I have done the following items , but still the problem occurs sometimes (Very few) :
1 - run this commands in cmd :
- net stop w32time
- w32tm /unregister
- w32tm /register
- net start w32time
- w32tm /resync
2 - from control panel > date and time > internet time change the server to >>>> time.nist.gov

What else should be done?

**Comment by Rengated** [comment]
from pybit.unified_trading import HTTP
session = HTTP(
    testnet=True,
    api_key="XXXXX",
    api_secret="XXXXX",
    enable_time_sync=true,
)

      enable_time_sync should solve your problem

**Comment by ttodua** [comment]
this error has not been reported for 2 years in this thread, so i'll consider this as closed.
however, if anyone faces this issue still (with latest CCXT version), let us know again
