### ISSUE TITLE
Btcturk createOrder's path is wrong

### ISSUE THREAD

**Issue by ialpay** [ccxt/ccxt#1490]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: IOS
- Programming Language version: javascript
- CCXT version:  1.10.840
- Exchange: BTCTRY
- Method: createOrder

this is my code:

const request = require('request');
const ccxt      = require ('ccxt')

;(async () => {

    let btcturk = new ccxt.btcturk  ({
        'apiKey': <Api Key>,
        'secret': <Secret Key>,
        'password': <password>,
      })

      let btcturkBalance = await btcturk.createOrder ('BTCTRY','limit','buy',10000,0.0001);
      console.log ('balance', btcturkBalance)
}

) ()
Same code is working for binance. It seems URI 'https://www.btcturk.com/api/buy' should be changed to URI 'https://www.btcturk.com/api/exchange'

and the result on the console is:

------------------------------------------------------------------------------
(node:17089) UnhandledPromiseRejectionWarning: Error: btcturk POST https://www.btcturk.com/api/buy 404 Not Found {"Message":"No HTTP resource was found that matches the request URI 'https://www.btcturk.com/api/buy'."}
    at btcturk.defaultErrorHandler (/Users/mac/Desktop/node/mybot/node_modules/ccxt/js/base/Exchange.js:410:15)
    at response.text.then.text (/Users/mac/Desktop/node/mybot/node_modules/ccxt/js/base/Exchange.js:426:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:17089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17089) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

----------------------------------------------------------

**Comment by ialpay** [comment]
this is my code:

const request = require('request');
const ccxt      = require ('ccxt')

;(async () => {


    let btcturk = new ccxt.btcturk  ({
        'apiKey': <Api Key>,
        'secret': <Secret Key>,
        'password': <password>,
      })

      let btcturkBalance = await btcturk.createOrder ('BTCTRY','limit','buy',10000,0.0001);
      console.log ('balance', btcturkBalance)
}

) ()


Same code is working for binance. It seems URI 'https://www.btcturk.com/api/buy' should be changed to URI 'https://www.btcturk.com/api/exchange'

and the result on the console is: 

------------------------------------------------------------------------------
(node:17089) UnhandledPromiseRejectionWarning: Error: btcturk POST https://www.btcturk.com/api/buy 404 Not Found {"Message":"No HTTP resource was found that matches the request URI 'https://www.btcturk.com/api/buy'."}
    at btcturk.defaultErrorHandler (/Users/mac/Desktop/node/mybot/node_modules/ccxt/js/base/Exchange.js:410:15)
    at response.text.then.text (/Users/mac/Desktop/node/mybot/node_modules/ccxt/js/base/Exchange.js:426:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:17089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17089) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

----------------------------------------------------------
