### ISSUE TITLE
Invalid API-key, IP, or permissions for action for binance, error code: -2015 (python)

### ISSUE THREAD

**Issue by JonathanAhrenkiel-Frellsen** [ccxt/ccxt#14993]
I'm using windows 11 and I have tried python version 3.10/3,9/3,8 and ccxt package 1.93.43 and 1.50.55. When I try to execute an order, it gives me the following error
```
fetch Request: binance POST https://fapi.binance.com/fapi/v1/order RequestHeaders: {'X-MBX-APIKEY': '<key>', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: timestamp=1663145559604&symbol=SOLUSDT&type=MARKET&side=BUY&newClientOrderId=x-xcKtGhcu193f85908660d115c04b76&newOrderRespType=RESULT&quantity=0&recvWindow=10000&signature=a351c41a5b655445fdd71b1070e4e72e87d41f5700f94d3726bd31e80ac7c110

fetch Response: binance POST https://fapi.binance.com/fapi/v1/order 401 ResponseHeaders: {'Content-Type': 'application/json', 'Content-Length': '69', 'Connection': 'keep-alive', 'Date': 'Wed, 14 Sep 2022 08:52:39 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '7', 'x-response-time': '2ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 e5438140b3bc19de0435cd47ff9426dc.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'CPH50-C1', 'X-Amz-Cf-Id': 'sZcqHRRMeGeceaSEEVhKdDugcrkwFrZwprfzb_BGY4XqUO-SmeThBQ=='} ResponseBody: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 620, in fetch
    response.raise_for_status()
  File "C:\Users\jola1\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\jola1\Desktop\Firma\Trendy\MarketMaker\mm_test.py", line 46, in <module>
    ex_priv.createMarketOrder(symbol="SOL/USDT",side='buy',amount=0.05)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 2990, in create_market_order
    return self.create_order(symbol, 'market', side, amount, price, params)
  File "C:\Python39\lib\site-packages\ccxt\binance.py", line 2971, in create_order
    response = getattr(self, method)(self.extend(request, requestParams))
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Python39\lib\site-packages\ccxt\binance.py", line 5558, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 2607, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Python39\lib\site-packages\ccxt\binance.py", line 5536, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 2853, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}
```
I have replaced my public key with <key> for obvious reasons. I am able to make a market trade with my account on the binance website so I assume I have set up my binance futures account correctly. The API key has the following permissions:
![image](https://user-images.githubusercontent.com/23343592/190111425-362c0222-8e7f-4997-9294-2f4d124ddee7.png)
The code is pretty generic but here it is:
```
exchange_class = getattr(ccxt, "binance")
ex_priv = exchange_class({
                        # finance
                        "apiKey": "***",
                        "secret": "***",
                        "enableRateLimit": True,
                        "options": {
                            "defaultType": "future",
                        },
                    })

ex_priv.load_markets()
ex_priv.verbose = True
print(ex_priv.fetch_balance()) # works fine

ex_priv.createMarketOrder(symbol="SOL/USDT",side='buy',amount=0.05) # gives -2015 error
```

**Comment by JonathanAhrenkiel-Frellsen** [comment]
1.

**Comment by carlosmiei** [comment]
Hello @JonathanAhrenkiel-Frellsen 

First and foremost, you should immediately revoke the keys you posted above.

Regarding your question, this really seems to be an authorization issue, so I'm afraid there is nothing we can do, have you tried to contact Binance's support?

**Comment by samgermain** [comment]
@JonathanAhrenkiel-Frellsen Even if I have the correct apiKeys and all permissions turned on and give any ip access, I still get this error if trying to access the Binance futures API in a restricted area like the U.S. or Ontario. You should probably check with Binance support to see exactly what is going on

**Comment by ttodua** [comment]
@JonathanAhrenkiel-Frellsen please post a follow-up, so we would know if that was solved for you or not. Also, you should note that binance UI had a bug, and you needed to click "edit" to actually see which permission checkboxes were checked really.
