### ISSUE TITLE
fetch_deposits & fetch_withdrawals error in hitbtc3

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#15024]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.93.59",
Exchange: hitbtc3
Method: fetch_deposits & fetch_withdrawals

hi
my code :

since = None
limit = 10
params = {}
deposits = connection.fetch_deposits(symbol, since, limit, params)

error :
Traceback (most recent call last):
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Hosein\PycharmProjects\pump\views\mainViews.py", line 18, in home
    Test.test()
  File "C:\Users\Hosein\PycharmProjects\pump\Test.py", line 64, in test
    data = exchange.fetchDeposits("TRX")
  File "C:\Users\Hosein\PycharmProjects\pump\objects\Exchange.py", line 107, in fetchDeposits
    return fetchDeposits.fetch(self.exchange_id, self.connection, symbol)
  File "C:\Users\Hosein\PycharmProjects\pump\exchange\fetchDeposits.py", line 17, in fetch
    deposits = connection.fetch_deposits(symbol, since, limit, params)
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\hitbtc3.py", line 1119, in fetch_deposits
    return self.fetch_transactions_helper('DEPOSIT', code, since, limit, params)
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\hitbtc3.py", line 1006, in fetch_transactions_helper
    return self.parse_transactions(response, currency, since, limit, params)
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 2540, in parse_transactions
    return self.filter_by_currency_since_limit(result, code, since, limit, tail)
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 3104, in filter_by_currency_since_limit
    return self.filter_by_value_since_limit(array, 'currency', code, since, limit, 'timestamp', tail)
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 1537, in filter_by_value_since_limit
    array = [entry for entry in array if entry[field] == value]
  File "C:\Users\Hosein\PycharmProjects\pythonProject\venv\lib\site-packages\ccxt\base\exchange.py", line 1537, in <listcomp>
    array = [entry for entry in array if entry[field] == value]
KeyError: 'currency'

verbose output :
fetch Response: hitbtc3 GET https://api.hitbtc.com/api/3/wallet/transactions?types=DEPOSIT&currencies=TRX&limit=10 200 ResponseHeaders: {'Server': 'nginx', 'Date': 'Fri, 16 Sep 2022 13:27:05 GMT', 'Content-Type': 'application/json; charset=UTF-8', 'Content-Length': '920', 'Connection': 'keep-alive', 'Request-ID': '**', 'Referrer-Policy': 'strict-origin-when-cross-origin'} ResponseBody: [{"id":200003725,"created_at":"2022-09-16T10:19:49.452Z","updated_at":"2022-09-16T10:20:01.932Z","status":"SUCCESS","type":"DEPOSIT","subtype":"BLOCKCHAIN","native":{"tx_id":"d9a59e06-9f50-475f-bd19-7d76b9cd4326","index":10751595853,"currency":"TRX","amount":"0.000001","hash":"cf5b80cd31a73e3b2a28983433bb4c20827c867e2f32dbd1e694021506874871","address":"TAptC5HKAvNyhbckqNvDzQNDijbW7odjJh","confirmations":5,"senders":["TBjmxr47qb4SPYekE42y2QCWbnV7BnMbgi"]}},{"id":200003719,"created_at":"2022-09-16T10:19:43.301Z","updated_at":"2022-09-16T10:19:55.937Z","status":"SUCCESS","type":"DEPOSIT","subtype":"BLOCKCHAIN","native":{"tx_id":"52db07f2-8476-4986-ac0d-65e0c2edeb05","index":10751595375,"currency":"TRX","amount":"47.442835","hash":"d396982222b8e21d5671be65d95f43f1e61290b4fb356623bd61cae0d782f230","address":"TAptC5HKAvNyhbckqNvDzQNDijbW7odjJh","confirmations":5,"senders":["TKpn4QSQ6Q1fKkF67Ljz2qmnskrLXGi9tP"]}}]

**Comment by ttodua** [comment]
@hosseinab In different issues you've opened, we have replied the same, that you should update the CCXT lib to latest version.
If you will still experience this issue after update, let us know back.

**Comment by hosseinab** [comment]
@ttodua 
my ccxt version is update to last version.
All the problems I have raised have been correct.

@cabanossi @kroitor

**Comment by hosseinab** [comment]
and this hitbtc exchange . previous exchnage is lbank

**Comment by ttodua** [comment]
> 1.90.94

is not up-to-date ccxt version. currently it's 1.93.xx +.

**Comment by hosseinab** [comment]
@ttodua 
i'm sorry . I edited the main comment

**Comment by ttodua** [comment]
@hosseinab thanks for bringing this issue up to us. I've found the bug and I can confirm it now. 
Will submit fix shortly.

**Comment by ttodua** [comment]
@hosseinab the PR is linked to this issue. when you get notification of closing this issue by completion, update your CCXT lib again and this issue will be gone away on your side.
