### ISSUE TITLE
error while fetching pair volume on Binance futures

### ISSUE THREAD

**Issue by ericfly02** [ccxt/ccxt#15072]
- OS: Windows
- Programming Language version: python
- CCXT version: 1.89.86

Hi, I'm looping through all the pairs on binance futures getting its volume. The thing is that after going through 20 pairs, I get an error with fetching the volume (doesn't make sense if I've got it right before)

```
volume = float(exchange.fetch_ticker(coin)['info']['quoteVolume'])
```

```
Traceback (most recent call last):
  File ".\axon_syncronous.py", line 98, in <module>
    main()
  File ".\axon_syncronous.py", line 69, in main
    axon_strategy(i, exchange, vars, count)
  File "C:\Users\speed\Documents\GitHub\Axon\strategy_syncronous.py", line 323, in axon_strategy
    volume = float(exchange.fetch_ticker(coin)['info']['quoteVolume'])
KeyError: 'quoteVolume'
```

**Comment by ericfly02** [comment]
trying to fetch info from delisted token "BTCSTUSDT"
