### ISSUE TITLE
market sell order causing ccxt.base.errors.ExchangeNotAvailable: ftx {"success":false,"error":"Please try again later"}

### ISSUE THREAD

**Issue by shivdarshan1020** [ccxt/ccxt#15129]
- OS: Windows Server 2012 R2 Standard
- Programming Language version: Python 3.8.10
- CCXT version: 1.93.76

```
import asyncio
import ccxt.async_support as ccxt
exchange_id = 'ftx'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': 'XXXXXXXXXXXXXXXXXX',
    'secret': 'XXXXXXXXXXXX',
})

exchange.headers = {
    'FTX-SUBACCOUNT': 'Sub_account_name',
}
ticker="BTC-PERP"
order=asyncio.get_event_loop().run_until_complete(exchange.create_market_sell_order(ticker, amount))
```

```
Traceback (most recent call last):
  File "btc.py", line 741, in <module>
    abc.strat(data)
  File "btc.py", line 571, in strat
    order=asyncio.get_event_loop().run_until_complete(exchange.create_market_sell_order(ticker, amount))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 1535, in create_market_sell_order
    return await self.create_order(symbol, 'market', 'sell', amount, None, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\async_support\ftx.py", line 1655, in create_order
    response = await getattr(self, method)(self.extend(request, params))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 1125, in request
    return await self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 1122, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 163, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\async_support\ftx.py", line 2624, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 1391, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.ExchangeNotAvailable: ftx {"success":false,"error":"Please try again later"}
```

Here I am trying to call a market sell order for BTC-PERP on FTX. Sometimes the order goes through just fine, but once in a while I have the above error. Can someone point me to what is this error caused by?

**Comment by carlosmiei** [comment]
Hello @shivdarshan1020, that looks like an issue on the exchange side, they might be unavailable in periods of high load, for instance. If you get this often, I'd suggest contacting FTX directly because there's nothing CCXT can do since we're "only" a middleware between traders and exchanges.
