### ISSUE TITLE
Cannot connect to Binance

### ISSUE THREAD

**Issue by neversleep007** [ccxt/ccxt#15178]
I have trouble connecting to Binance. I have to use vpn, which might be the issue. Any idea how to fix this?

# Code

```
import ccxt
exchange = ccxt.binance()
markets = exchange.load_markets()
print(markets)
```

# Errors

```
Traceback (most recent call last):
  File "C:\Users\Zeng\anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Zeng\anaconda3\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\Zeng\anaconda3\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zeng\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Zeng\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Zeng\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\Zeng\anaconda3\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\Users\Zeng\anaconda3\lib\site-packages\urllib3\connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000288C14B8880>, 'Connection to api.binance.com timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zeng\anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\Zeng\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\Zeng\anaconda3\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000288C14B8880>, 'Connection to api.binance.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zeng\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 594, in fetch
    response = self.session.request(
  File "C:\Users\Zeng\anaconda3\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Zeng\anaconda3\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Zeng\anaconda3\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000288C14B8880>, 'Connection to api.binance.com timed out. (connect timeout=10)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Zeng\Desktop\Python\Crypto\test.py", line 3, in <module>
    markets = exchange.load_markets()
  File "C:\Users\Zeng\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1431, in load_markets
    markets = self.fetch_markets(params)
  File "C:\Users\Zeng\anaconda3\lib\site-packages\ccxt\binance.py", line 1459, in fetch_markets
    response = getattr(self, method)(query)
  File "C:\Users\Zeng\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Zeng\anaconda3\lib\site-packages\ccxt\binance.py", line 5571, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\Zeng\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 2609, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Zeng\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 624, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v3/exchangeInfo
```

**Comment by samgermain** [comment]
Depending on where you live you will need to use a VPN. Make sure you use a decent vpn also, and not a free vpn that you download from the chrome extension marketplace or something.

**Comment by zhubiaogg** [comment]
exchange.proxies = {
            "http": "127.0.0.1:7890",
            "https": "127.0.0.1:7890"
        }

![image](https://user-images.githubusercontent.com/43566543/194270090-4dab7e11-ebf8-40c8-aaf5-b754ce3bd324.png)

**Comment by samgermain** [comment]
@neversleep007 Are you still having problems?

**Comment by 1LLZ** [comment]
I have the same issue, and I run the code below
exchange.proxies = {
"http": "127.0.0.1:7890",
"https": "127.0.0.1:7890"
}
It didn't work
any suggestions, plz?
