### ISSUE TITLE
fetchPositions() Error: TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by ViktorKov** [ccxt/ccxt#15181]
- OS: Ubuntu 18.04 LTS within WSL of Windows 10 
- Programming Language version: 3.8.10 
- CCXT version: 1.92.88 
- Exchange: Bitmex 
- Method: fetch_positions()

Hi Igor,

This issue has been occurred 2nd time, it was already fixed once not long time ago. 
What is reason of this recurring issue? Am I doing something what's causing this?

Can you have a look please. 
Thanks.

```
>>> exchange.verbose=True
>>> print(exchange.verbose)
True

>>>
>>> print( exchange.fetchPositions() )

fetch Request: bitmex GET https://testnet.bitmex.com/api/v1/position RequestHeaders: {'Content-Type': 'application/json', 'api-key': '4fDlD4UxANM_0-z_N69sx_7i', 'api-expires': '1664821964', 'api-signature': '5abc13521bcf2f6a325719669691707255f09
5b207c0de61277d95392f55d001', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitmex GET https://testnet.bitmex.com/api/v1/position 200 ResponseHeaders: {'Date': 'Mon, 03 Oct 2022 18:32:38 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', '
Set-Cookie': 'AWSALBTG=KrKYXNj2zUifmM0UhtJBw913YiB+eiCQKPRL9yI8qcYlQ8lYdOSwpBRTZ4mnSa/1ikhx7KtjIv81Sg7mqgyog8fb9hhIXePzFEq2cPqtCESA452btGrGAZxMA3RemQjB3Hnjm3m/6Z16NQ9kTzN/bzMxdNAsM+bLWiVRK8mdjD68; Expires=Mon, 10 Oct 2022 18:32:38 GMT; Path=/, A
WSALBTGCORS=KrKYXNj2zUifmM0UhtJBw913YiB+eiCQKPRL9yI8qcYlQ8lYdOSwpBRTZ4mnSa/1ikhx7KtjIv81Sg7mqgyog8fb9hhIXePzFEq2cPqtCESA452btGrGAZxMA3RemQjB3Hnjm3m/6Z16NQ9kTzN/bzMxdNAsM+bLWiVRK8mdjD68; Expires=Mon, 10 Oct 2022 18:32:38 GMT; Path=/; SameSite=Non
e; Secure, __cf_bm=OMT5gyEI8bKG.GIetygw2IxNJS.iRKZIcKvquskL90s-1664821958-0-AX+r8xMvOnJC1ASBn4jt/ZeFRJGjXlsmPzSOoHBHayiCJAddYK3bKC9BFVLeNetLymPq3MT4JsbeMUDSrMhN7O0=; path=/; expires=Mon, 03-Oct-22 19:02:38 GMT; domain=.bitmex.com; HttpOnly; Secu
re; SameSite=None', 'X-User-ID': '397420', 'X-RateLimit-Limit': '120', 'X-RateLimit-Remaining': '119', 'X-RateLimit-Reset': '1664821959', 'X-Powered-By': 'Profit', 'ETag': 'W/"2a1c-pzjDrw+vrHPY4UJtpMJrlW5t5dI"', 'CF-Cache-Status': 'DYNAMIC', 'Se
rver': 'cloudflare', 'CF-RAY': '7547c2f77e0f136e-YVR', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: [{"account":397420,"symbol":"XBTH23","currency":"XBt","underlying":"XBT","quoteCurrency":"
USD","commission":0.00075,"initMarginReq":0.01,"maintMarginReq":0.0035,"riskLimit":7500000000,"leverage":100,"crossMargin":true,"deleveragePercentile":1,"rebalancedPnl":44,"prevRealisedPnl":-22239,"prevUnrealisedPnl":0,"prevClosePrice":21274.82,
"openingTimestamp":"2022-10-03T18:00:00.000Z","openingQty":-100,"openingCost":449620,"openingComm":0,"openOrderBuyQty":0,"openOrderBuyCost":0,"openOrderBuyPremium":0,"openOrderSellQty":0,"openOrderSellCost":0,"openOrderSellPremium":0,"execBuyQty
":0,"execBuyCost":0,"execSellQty":0,"execSellCost":0,"execQty":0,"execCost":0,"execComm":0,"currentTimestamp":"2022-10-03T18:32:35.305Z","currentQty":-100,"currentCost":449620,"currentComm":0,"realisedCost":0,"unrealisedCost":449620,"grossOpenCo
st":0,"grossOpenPremium":0,"grossExecCost":0,"isOpen":true,"markPrice":21318.7,"markValue":469072,"riskValue":469072,"homeNotional":-0.00469072,"foreignNotional":100,"posState":"","posCost":449620,"posCost2":449620,"posCross":0,"posInit":4497,"p
osComm":341,"posLoss":0,"posMargin":4838,"posMaint":1915,"posAllowance":0,"taxableMargin":0,"initMargin":0,"maintMargin":24290,"sessionMargin":0,"targetExcessMargin":0,"varMargin":0,"realisedGrossPnl":0,"realisedTax":0,"realisedPnl":0,"unrealise
dGrossPnl":19452,"longBankrupt":0,"shortBankrupt":0,"taxBase":0,"indicativeTaxRate":null,"indicativeTax":0,"unrealisedTax":0,"unrealisedPnl":19452,"unrealisedPnlPcnt":0.0433,"unrealisedRoePcnt":4.3263,"simpleQty":null,"simpleCost":null,"simpleVa
lue":null,"simplePnl":null,"simplePnlPcnt":null,"avgCostPrice":22241,"avgEntryPrice":22241,"breakEvenPrice":22243,"marginCallPrice":22899,"liquidationPrice":22899,"bankruptPrice":22981.5,"timestamp":"2022-10-03T18:32:35.305Z","lastPrice":21318.7
,"lastValue":469072},{"account":397420,"symbol":"XBTZ22","currency":"XBt","underlying":"XBT","quoteCurrency":"USD","commission":0.00075,"initMarginReq":0.01,"maintMarginReq":0.0035,"riskLimit":7500000000,"leverage":100,"crossMargin":true,"deleve
ragePercentile":1,"rebalancedPnl":-354,"prevRealisedPnl":-25856,"prevUnrealisedPnl":0,"prevClosePrice":20303.41,"openingTimestamp":"2022-10-03T18:00:00.000Z","openingQty":-100,"openingCost":472601,"openingComm":0,"openOrderBuyQty":0,"openOrderBu
yCost":0,"openOrderBuyPremium":0,"openOrderSellQty":0,"openOrderSellCost":0,"openOrderSellPremium":0,"execBuyQty":0,"execBuyCost":0,"execSellQty":0,"execSellCost":0,"execQty":0,"execCost":0,"execComm":0,"currentTimestamp":"2022-10-03T18:32:35.30
5Z","currentQty":-100,"currentCost":472601,"currentComm":0,"realisedCost":0,"unrealisedCost":472601,"grossOpenCost":0,"grossOpenPremium":0,"grossExecCost":0,"isOpen":true,"markPrice":20345.31,"markValue":491514,"riskValue":491514,"homeNotional":
-0.00491514,"foreignNotional":100,"posState":"","posCost":472601,"posCost2":472601,"posCross":0,"posInit":4727,"posComm":358,"posLoss":0,"posMargin":5085,"posMaint":2013,"posAllowance":0,"taxableMargin":0,"initMargin":0,"maintMargin":23998,"sess
ionMargin":0,"targetExcessMargin":0,"varMargin":0,"realisedGrossPnl":0,"realisedTax":0,"realisedPnl":0,"unrealisedGrossPnl":18913,"longBankrupt":0,"shortBankrupt":0,"taxBase":0,"indicativeTaxRate":null,"indicativeTax":0,"unrealisedTax":0,"unreal
isedPnl":18913,"unrealisedPnlPcnt":0.04,"unrealisedRoePcnt":4.0019,"simpleQty":null,"simpleCost":null,"simpleValue":null,"simplePnl":null,"simplePnlPcnt":null,"avgCostPrice":21159.5,"avgEntryPrice":21159.5,"breakEvenPrice":21143.5,"marginCallPri
ce":21761,"liquidationPrice":21761,"bankruptPrice":21839.5,"timestamp":"2022-10-03T18:32:35.305Z","lastPrice":20345.31,"lastValue":491514},{"account":397420,"symbol":"XBTU22","currency":"XBt","underlying":"XBT","quoteCurrency":"USD","commission"
:0.00075,"initMarginReq":0.01,"maintMarginReq":0.0035,"riskLimit":7500000000,"leverage":100,"crossMargin":true,"deleveragePercentile":null,"rebalancedPnl":15641,"prevRealisedPnl":-15590,"prevUnrealisedPnl":0,"prevClosePrice":19465.24,"openingTim
estamp":"2022-09-30T12:00:00.000Z","openingQty":0,"openingCost":0,"openingComm":0,"openOrderBuyQty":0,"openOrderBuyCost":0,"openOrderBuyPremium":0,"openOrderSellQty":0,"openOrderSellCost":0,"openOrderSellPremium":0,"execBuyQty":0,"execBuyCost":0
,"execSellQty":0,"execSellCost":0,"execQty":0,"execCost":0,"execComm":0,"currentTimestamp":"2022-09-30T12:00:00.000Z","currentQty":0,"currentCost":0,"currentComm":0,"realisedCost":0,"unrealisedCost":0,"grossOpenCost":0,"grossOpenPremium":0,"gros
sExecCost":0,"isOpen":false,"markPrice":null,"markValue":0,"riskValue":0,"homeNotional":0,"foreignNotional":0,"posState":"","posCost":0,"posCost2":0,"posCross":0,"posInit":0,"posComm":0,"posLoss":0,"posMargin":0,"posMaint":0,"posAllowance":0,"ta
xableMargin":0,"initMargin":0,"maintMargin":0,"sessionMargin":0,"targetExcessMargin":0,"varMargin":0,"realisedGrossPnl":0,"realisedTax":0,"realisedPnl":0,"unrealisedGrossPnl":0,"longBankrupt":0,"shortBankrupt":0,"taxBase":0,"indicativeTaxRate":n
ull,"indicativeTax":0,"unrealisedTax":0,"unrealisedPnl":0,"unrealisedPnlPcnt":0,"unrealisedRoePcnt":0,"simpleQty":null,"simpleCost":null,"simpleValue":null,"simplePnl":null,"simplePnlPcnt":null,"avgCostPrice":null,"avgEntryPrice":null,"breakEven
Price":null,"marginCallPrice":null,"liquidationPrice":null,"bankruptPrice":null,"timestamp":"2022-09-30T12:00:00.000Z","lastPrice":null,"lastValue":0},{"account":397420,"symbol":"XBTUSD","currency":"XBt","underlying":"XBT","quoteCurrency":"USD",
"commission":0.00075,"initMarginReq":0.01,"maintMarginReq":0.0035,"riskLimit":20000000000,"leverage":100,"crossMargin":true,"deleveragePercentile":null,"rebalancedPnl":0,"prevRealisedPnl":-76075,"prevUnrealisedPnl":0,"prevClosePrice":19254.98,"o
peningTimestamp":"2022-10-03T18:00:00.000Z","openingQty":0,"openingCost":0,"openingComm":0,"openOrderBuyQty":0,"openOrderBuyCost":0,"openOrderBuyPremium":0,"openOrderSellQty":0,"openOrderSellCost":0,"openOrderSellPremium":0,"execBuyQty":0,"execB
uyCost":0,"execSellQty":0,"execSellCost":0,"execQty":0,"execCost":0,"execComm":0,"currentTimestamp":"2022-10-03T18:00:00.015Z","currentQty":0,"currentCost":0,"currentComm":0,"realisedCost":0,"unrealisedCost":0,"grossOpenCost":0,"grossOpenPremium
":0,"grossExecCost":0,"isOpen":false,"markPrice":null,"markValue":0,"riskValue":0,"homeNotional":0,"foreignNotional":0,"posState":"","posCost":0,"posCost2":0,"posCross":0,"posInit":0,"posComm":0,"posLoss":0,"posMargin":0,"posMaint":0,"posAllowan
ce":0,"taxableMargin":0,"initMargin":0,"maintMargin":0,"sessionMargin":0,"targetExcessMargin":0,"varMargin":0,"realisedGrossPnl":0,"realisedTax":0,"realisedPnl":0,"unrealisedGrossPnl":0,"longBankrupt":0,"shortBankrupt":0,"taxBase":0,"indicativeT
axRate":null,"indicativeTax":0,"unrealisedTax":0,"unrealisedPnl":0,"unrealisedPnlPcnt":0,"unrealisedRoePcnt":0,"simpleQty":null,"simpleCost":null,"simpleValue":null,"simplePnl":null,"simplePnlPcnt":null,"avgCostPrice":null,"avgEntryPrice":null,"
breakEvenPrice":null,"marginCallPrice":null,"liquidationPrice":null,"bankruptPrice":null,"timestamp":"2022-10-03T18:00:00.015Z","lastPrice":null,"lastValue":0},{"account":397420,"symbol":"XBTV22","currency":"XBt","underlying":"XBT","quoteCurrenc
y":"USD","commission":0.00075,"initMarginReq":0.01,"maintMarginReq":0.0035,"riskLimit":7500000000,"leverage":100,"crossMargin":true,"deleveragePercentile":1,"rebalancedPnl":-365,"prevRealisedPnl":-28457,"prevUnrealisedPnl":0,"prevClosePrice":195
51.35,"openingTimestamp":"2022-10-03T18:00:00.000Z","openingQty":-100,"openingCost":486914,"openingComm":0,"openOrderBuyQty":0,"openOrderBuyCost":0,"openOrderBuyPremium":0,"openOrderSellQty":0,"openOrderSellCost":0,"openOrderSellPremium":0,"exec
BuyQty":0,"execBuyCost":0,"execSellQty":0,"execSellCost":0,"execQty":0,"execCost":0,"execComm":0,"currentTimestamp":"2022-10-03T18:32:35.305Z","currentQty":-100,"currentCost":486914,"currentComm":0,"realisedCost":0,"unrealisedCost":486914,"gross
OpenCost":0,"grossOpenPremium":0,"grossExecCost":0,"isOpen":true,"markPrice":19591.88,"markValue":510416,"riskValue":510416,"homeNotional":-0.00510416,"foreignNotional":100,"posState":"","posCost":486914,"posCost2":486914,"posCross":0,"posInit":
4870,"posComm":369,"posLoss":0,"posMargin":5239,"posMaint":2074,"posAllowance":0,"taxableMargin":0,"initMargin":0,"maintMargin":28741,"sessionMargin":0,"targetExcessMargin":0,"varMargin":0,"realisedGrossPnl":0,"realisedTax":0,"realisedPnl":0,"un
realisedGrossPnl":23502,"longBankrupt":0,"shortBankrupt":0,"taxBase":0,"indicativeTaxRate":null,"indicativeTax":0,"unrealisedTax":0,"unrealisedPnl":23502,"unrealisedPnlPcnt":0.0483,"unrealisedRoePcnt":4.8267,"simpleQty":null,"simpleCost":null,"s
impleValue":null,"simplePnl":null,"simplePnlPcnt":null,"avgCostPrice":20537.5,"avgEntryPrice":20537.5,"breakEvenPrice":20522,"marginCallPrice":21108,"liquidationPrice":21108,"bankruptPrice":21184,"timestamp":"2022-10-03T18:32:35.305Z","lastPrice
":19591.88,"lastValue":510416},{"account":397420,"symbol":"XBTM23","currency":"XBt","underlying":"XBT","quoteCurrency":"USD","commission":0.00075,"initMarginReq":0.01,"maintMarginReq":0.0035,"riskLimit":7500000000,"leverage":100,"crossMargin":tr
ue,"deleveragePercentile":1,"rebalancedPnl":-340,"prevRealisedPnl":21584,"prevUnrealisedPnl":0,"prevClosePrice":19551.35,"openingTimestamp":"2022-10-03T18:00:00.000Z","openingQty":-100,"openingCost":453731,"openingComm":0,"openOrderBuyQty":0,"op
enOrderBuyCost":0,"openOrderBuyPremium":0,"openOrderSellQty":0,"openOrderSellCost":0,"openOrderSellPremium":0,"execBuyQty":0,"execBuyCost":0,"execSellQty":0,"execSellCost":0,"execQty":0,"execCost":0,"execComm":0,"currentTimestamp":"2022-10-03T18
:32:35.305Z","currentQty":-100,"currentCost":453731,"currentComm":0,"realisedCost":0,"unrealisedCost":453731,"grossOpenCost":0,"grossOpenPremium":0,"grossExecCost":0,"isOpen":true,"markPrice":19591.88,"markValue":510416,"riskValue":510416,"homeN
otional":-0.00510416,"foreignNotional":100,"posState":"","posCost":453731,"posCost2":453731,"posCross":0,"posInit":4538,"posComm":344,"posLoss":0,"posMargin":4882,"posMaint":1933,"posAllowance":0,"taxableMargin":0,"initMargin":0,"maintMargin":61
567,"sessionMargin":0,"targetExcessMargin":0,"varMargin":0,"realisedGrossPnl":0,"realisedTax":0,"realisedPnl":0,"unrealisedGrossPnl":56685,"longBankrupt":0,"shortBankrupt":0,"taxBase":0,"indicativeTaxRate":null,"indicativeTax":0,"unrealisedTax":
0,"unrealisedPnl":56685,"unrealisedPnlPcnt":0.1249,"unrealisedRoePcnt":12.4931,"simpleQty":null,"simpleCost":null,"simpleValue":null,"simplePnl":null,"simplePnlPcnt":null,"avgCostPrice":22039.5,"avgEntryPrice":22039.5,"breakEvenPrice":22022.5,"m
arginCallPrice":22686.5,"liquidationPrice":22686.5,"bankruptPrice":22768.5,"timestamp":"2022-10-03T18:32:35.305Z","lastPrice":19591.88,"lastValue":510416}]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/iquantdev/venv/lib/python3.8/site-packages/ccxt/bitmex.py", line 1940, in fetch_positions
    return self.parse_positions(response, symbols)
  File "/iquantdev/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2508, in parse_positions
    position = self.extend(self.parse_position(positions[i], None), params)
  File "/iquantdev/venv/lib/python3.8/site-packages/ccxt/bitmex.py", line 2068, in parse_position
    'maintenanceMargin': self.convert_value(maintenanceMargin, market),
  File "/iquantdev/venv/lib/python3.8/site-packages/ccxt/bitmex.py", line 2087, in convert_value
    currency = self.currency(market['quote'])
  File "/iquantdev/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2962, in currency
    raise ExchangeError(self.id + ' does not have currency code ' + code)
TypeError: can only concatenate str (not "NoneType") to str
>>>
```

**Comment by ViktorKov** [comment]
Hey, 

The issue was announced two days ago. 
The latest occurrence of the same issue was at 2022-08-29 and Igor fixed it with no time.
Ask him if you are unable to cope with it.
