### ISSUE TITLE
NDAX fetch_deposits expects an array, string given

### ISSUE THREAD

**Issue by daniel-lucio** [ccxt/ccxt#15192]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Linux
- Programming Language version: PHP 8.1
- CCXT version: 1.94.17

```
$since = strtotime('2010-01-01 -1 year') * 1000;
$e->fetch_deposits('DOGE', $since, null, []));
```

```
PHP Fatal error:  Uncaught TypeError: array_values(): Argument #1 ($array) must be of type array, string given in /root/trademinator-client/trunk/vendor/ccxt/ccxt/php/Exchange.php:814
Stack trace:
#0 /root/trademinator-client/trunk/vendor/ccxt/ccxt/php/Exchange.php(814): array_values()
#1 /root/trademinator-client/trunk/vendor/ccxt/ccxt/php/Exchange.php(3352): ccxt\Exchange::to_array()
#2 /root/trademinator-client/trunk/vendor/ccxt/ccxt/php/ndax.php(2014): ccxt\Exchange->parse_transactions()
#3 /root/trademinator-client/trunk/test/test-exchange-deposits.php(26): ccxt\ndax->fetch_deposits()
#4 {main}
  thrown in /root/trademinator-client/trunk/vendor/ccxt/ccxt/php/Exchange.php on line 814
```

**Comment by daniel-lucio** [comment]
Hello

This bug is still present.

PHP Fatal error:  Uncaught TypeError: array_values(): Argument #1 ($array) must be of type array, string given in /root/trademinator-client/trunk/vendor/ccxt/ccxt/php/Exchange.php:847
Stack trace:
#0 /root/trademinator-client/trunk/vendor/ccxt/ccxt/php/Exchange.php(847): array_values()
#1 /root/trademinator-client/trunk/vendor/ccxt/ccxt/php/Exchange.php(3625): ccxt\Exchange::to_array()
#2 /root/trademinator-client/trunk/vendor/ccxt/ccxt/php/ndax.php(2006): ccxt\Exchange->parse_transactions()
#3 /root/trademinator-client/trunk/test/test-exchange-deposits.php(26): ccxt\ndax->fetch_deposits()
#4 {main}
  thrown in /root/trademinator-client/trunk/vendor/ccxt/ccxt/php/Exchange.php on line 847


PHP 8.1
CCXT 2.6.56
Exchange: NDAX
