### ISSUE TITLE
Bybit.parseWsTicker TypeError: this.parseInt is not a function

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#15201]
We've noticed that on Bybit throws `TypeError: this.parseInt is not a function` exception in `parseWsTicker` method.
Here is full error description:

```
TypeError: this.parseInt is not a function 
                at bybit.parseWsTicker (/var/www/project/corejs/node_modules/ccxt.pro/js/bybit.js:427:62)
                at bybit.handleTicker (/var/www/project/corejs/node_modules/ccxt.pro/js/bybit.js:277:33)
                at bybit.handleMessage (/var/www/project/corejs/node_modules/ccxt.pro/js/bybit.js:1843:18)
                at WsClient.onMessage (/var/www/project/corejs/node_modules/ccxt.pro/js/base/Client.js:280:14)
                at WebSocket.onMessage (/var/www/project/corejs/node_modules/ws/lib/event-target.js:132:16)
                at WebSocket.emit (events.js:315:20)
                at Receiver.receiverOnMessage (/var/www/project/corejs/node_modules/ws/lib/websocket.js:1047:20)
                at Receiver.emit (events.js:315:20)
                at Receiver.dataMessage (/var/www/project/corejs/node_modules/ws/lib/receiver.js:517:14)
                at /var/www/project/corejs/node_modules/ws/lib/receiver.js:468:23
```

- OS: Debian (Docker)
- Programming Language version: NodeJS, JavaScript
- CCXT version: PRO 1.2.36

**Comment by carlosmiei** [comment]
@wunderb1t, actually I've noticed you're using the "old" ccxt.pro package, can you please uninstall it and update your `ccxt` version to 1.95.0+ ? 

After updating, you should be able to import `pro` functions doing this:

```Javascript
const ccxt = require('ccxt').pro

const bybit = new ccxt.bybit({})
while (true) {
   const tickers = await bybit.watchTickers(...)
}
```

**Comment by wunderb1t** [comment]
@carlosmiei thank for answer, we updated all up to `1.95.12` version but still issue exist.

```
TypeError: this.parseInt is not a function
    at bybit.parseWsTicker (/var/www/project/corejs/node_modules/ccxt/js/pro/bybit.js:427:62)
    at bybit.handleTicker (/var/www/project/corejs/node_modules/ccxt/js/pro/bybit.js:277:33)
    at bybit.handleMessage (/var/www/project/corejs/node_modules/ccxt/js/pro/bybit.js:1843:18)
    at WsClient.onMessage (/var/www/project/corejs/node_modules/ccxt/js/pro/base/Client.js:283:14)
    at WebSocket.onMessage (/var/www/project/corejs/node_modules/ccxt/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/var/www/project/corejs/node_modules/ccxt/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/var/www/project/corejs/node_modules/ccxt/node_modules/ws/lib/receiver.js:528:14)
    at /var/www/project/corejs/node_modules/ccxt/node_modules/ws/lib/receiver.js:479:23
```

**Comment by carlosmiei** [comment]
@wunderb1t which symbol leads to this error?

**Comment by wunderb1t** [comment]
@carlosmiei ETHUSDH23

**Comment by wunderb1t** [comment]
@carlosmiei Looks like this is a old ticker that stayed in our system we will remove it. 
But still maybe better to check this issue, because some future contracts can be outdated and rise that exception on runtime.

**Comment by carlosmiei** [comment]
@wunderb1t I managed to reproduce the issue, will fix it asap

**Comment by carlosmiei** [comment]
@wunderb1t if you update to the latest version, it should be solved now

**Comment by wunderb1t** [comment]
@carlosmiei all works, thank you.
