### ISSUE TITLE
[okx] handleOrderBookMessage - invalid array member accessed

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#15206]
Hi fellows!
okx throws for a lot of pairs on handleOrderBookMessage.
Try this pair:
```JavaScript
exchange.watchOrderBook("KNC/BTC")
```
you should get this.
```
path\node_modules\ccxt\js\pro\okx.js:317
                payloadArray.push (this.numberToString (storedBids[i][0]));
                                                                     ^

TypeError: Cannot read property '0' of undefined
    at okex.handleOrderBookMessage (path\node_modules\ccxt\js\pro\okx.js:317:70)
    at okex.handleOrderBook (path\node_modules\ccxt\js\pro\okx.js:443:22)
    at okex.handleMessage (path\node_modules\ccxt\js\pro\okx.js:824:31)
    at WsClient.onMessage (path\node_modules\ccxt\js\pro\base\Client.js:283:14)
    at WebSocket.onMessage (path\node_modules\ccxt\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (path\node_modules\ccxt\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (path\node_modules\ccxt\node_modules\ws\lib\receiver.js:528:14)
    at path\node_modules\ccxt\node_modules\ws\lib\receiver.js:479:23

```
CCXT version: 1.95.12
Please take a look, thanks!

**Comment by carlosmiei** [comment]
Hi @krychla1, we will take a look, thanks!
