### ISSUE TITLE
How to fix the timestamp ahead of server’s time error?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15282]
- OS: Windows 10 (Version 21H2)
- Programming Language version: Node JS: v18.10.0
- CCXT version: 2.0.1

Hello:
I want to load one symbol markets for Binance, the following is my Node JS code:

```JavaScript
'use strict';
const ccxt = require('ccxt');

(async function () {
    console.log(ccxt.version)
    const exchange = new ccxt.binance({
        apiKey: 'My_API_Key',
        secret: 'My_Secrey_Key',
        verbose: false,
        defaultType: 'spot'
    })
    console.log ((await exchange.loadMarkets ())['BTC/USDT'])
})();
```

When I run the above code, I got the following output:

```
D:\nodejs\CCXT>node BinanceLoad1CoinMarkets.js
2.0.1
(node:6544) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
D:\nodejs\CCXT\node_modules\ccxt\js\base\Exchange.js:2142
            throw new exact[string] (message);
                  ^

InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
    at binance.throwExactlyMatchedException (D:\nodejs\CCXT\node_modules\ccxt\js\base\Exchange.js:2142:19)
    at binance.handleErrors (D:\nodejs\CCXT\node_modules\ccxt\js\binance.js:5964:18)
    at D:\nodejs\CCXT\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async binance.fetch2 (D:\nodejs\CCXT\node_modules\ccxt\js\base\Exchange.js:1803:16)
    at async binance.request (D:\nodejs\CCXT\node_modules\ccxt\js\binance.js:5993:26)
    at async binance.fetchCurrencies (D:\nodejs\CCXT\node_modules\ccxt\js\binance.js:1304:26)
    at async binance.loadMarketsHelper (D:\nodejs\CCXT\node_modules\ccxt\js\base\Exchange.js:624:26)
    at async D:\nodejs\CCXT\BinanceLoad1CoinMarkets.js:12:19 {
  constructor: [class InvalidNonce extends NetworkError]
}
```

I am in Timezone (GMT+2 – Madrid), and I setup my windows 10 PC to synchronize time automatically.  But the error is kind of rather restrictive, as it is only 1 second ahead of server time.
Anyway, please advise on how to fix this issue.

Thanks,

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail, please check out this thread: https://github.com/ccxt/ccxt/issues/936

**Comment by zydjohnHotmail** [comment]
Hello:
I didn't test this, but another way seems working:
await exchange.load_time_difference()
