### ISSUE TITLE
AAX (ccxtpro) error during watch_orders

### ISSUE THREAD

**Issue by ekleinsqs** [ccxt/ccxt#15336]
Hello,

I'm facing an error when calling the watch_orders method for AAX (ccxtpro). Seems to be stemming from the handle_balance method where a NoneType is passing through. Further context: watch_orders starts up successfully, but once I place my first order as a test, it crashes resulting in this error.

OS: Windows 10
Programming Language version: Python 3.10.7
CCXT version: 2.0.36

My code is calling watch_orders in an infinite loop.

```
Exception in callback FastClient.receive_loop.<locals>.handler() at Python\Python310\lib\site-packages\ccxt\pro\base\fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at Python\Python310\lib\site-packages\ccxt\pro\base\fast_client.py:20>
Traceback (most recent call last):
  File "Python\Python310\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "Python\Python310\lib\site-packages\ccxt\pro\base\fast_client.py", line 25, in handler
    self.handle_message(message)
  File "Python\Python310\lib\site-packages\ccxt\pro\base\aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "Python\Python310\lib\site-packages\ccxt\pro\base\aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "Python\Python310\lib\site-packages\ccxt\pro\aax.py", line 756, in handle_message
    self.handle_notification(client, data)
  File "Python\Python310\lib\site-packages\ccxt\pro\aax.py", line 594, in handle_notification
    return method(client, message)
  File "Python\Python310\lib\site-packages\ccxt\pro\aax.py", line 386, in handle_balance
    messageHash = accountType + ':balance'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Thanks!

**Comment by carlosmiei** [comment]
Hello @ekleinsqs, thanks for reporting it we will take a look
