### ISSUE TITLE
The latest CCXT verion (2.0.34) of JavaScript has issue with binance

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15334]
- OS: Windows 10 (21H2)
- Programming Language version: Node.js (ver 18.10.0)
- CCXT version: 2.0.34

```JavaScript
'use strict';
const ccxt = require('ccxt');
console.log(ccxt.version);

const deposit1Currency = async () => {
    try {
        const exchange = new ccxt.binance({
            apiKey: 'My_API_Key',
            secret: 'My_Secret_Key',
            'options': {
            'adjustForTimeDifference': true,
            'verbose': false,
            'recvWindow': 10000,
           }
        });
        await exchange.loadMarkets();
        const deposits = await exchange.fetchDepositAddress('USDT', {'network': 'BEP20'});
        console.log(deposits);
    }
    catch (err) {
        console.log(err);
    }
};

deposit1Currency();
```

```
InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
```

Hello:
After I upgraded to latest version of CCXT, npm version 2.0.34, my  code did NOT work any more, I got the error like above.
But if I downgrade to CCXT npm version 2.0.31, my code works:

```
D:\nodejs\CCXT_Binance>node Binance1CoinAddress.js USDT
2.0.31
(node:26528) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{
  currency: 'USDT',
  address: '0xacc......',
  tag: undefined,
  network: 'BSC',
  info: {
    coin: 'USDT',
    address: '0xacc......',
    tag: '',
    url: 'https://bscscan.com/address/0xacc......'
  }
}
```

**Comment by carlosmiei** [comment]
@zydjohnHotmail Can you please send us a verbose log of when it works and when it doesn't?

**Comment by zydjohnHotmail** [comment]
Hello:
I found there are more issues now. For old version: 2.0.31: I have done testing for 20 times, it worked for 4 times, but failed for 16 times.
The following is the output for both working and not-working cases:
D:\nodejs\CCXT_Binance>node Binance1CoinAddress.js USDT
2.0.31
(node:39252) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
    at binance.throwExactlyMatchedException (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\Exchange.js:2142:19)
    at binance.handleErrors (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\binance.js:5966:18)
    at D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async binance.fetch2 (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\Exchange.js:1803:16)
    at async binance.request (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\binance.js:5995:26)
    at async binance.fetchCurrencies (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\binance.js:1306:26)
    at async binance.loadMarketsHelper (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\Exchange.js:624:26)
    at async deposit1Currency (D:\nodejs\CCXT_Binance\Binance1CoinAddress.js:22:25) {
  constructor: [class InvalidNonce extends NetworkError]
}

D:\nodejs\CCXT_Binance>node Binance1CoinAddress.js USDT
2.0.31
(node:11580) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{
  currency: 'USDT',
  address: '0xacc......',
  tag: undefined,
  network: 'BSC',
  info: {
    coin: 'USDT',
    address: '0xacc......',
    tag: '',
    url: 'https://bscscan.com/address/0xacc......'
  }
}

D:\nodejs\CCXT_Binance>
For a new version: 2.0.37, I have done testing for 20 times, it worked for 3 times, but failed for 17 times.
The following is the output for both working and not-working cases:
D:\nodejs\CCXT_Address>node Binance1CoinAddress.js USDT
2.0.37
(node:21536) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{
  currency: 'USDT',
  address: '0xacc......',
  tag: undefined,
  network: 'BSC',
  info: {
    coin: 'USDT',
    address: '0xacc.....',
    tag: '',
    url: 'https://bscscan.com/address/0xacc......'
  }
}

D:\nodejs\CCXT_Address>node Binance1CoinAddress.js USDT
2.0.37
(node:36504) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
    at binance.throwExactlyMatchedException (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:2142:19)
    at binance.handleErrors (D:\nodejs\CCXT_Address\node_modules\ccxt\js\binance.js:5966:18)
    at D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async binance.fetch2 (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:1803:16)
    at async binance.request (D:\nodejs\CCXT_Address\node_modules\ccxt\js\binance.js:5995:26)
    at async binance.fetchCurrencies (D:\nodejs\CCXT_Address\node_modules\ccxt\js\binance.js:1306:26)
    at async binance.loadMarketsHelper (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:624:26)
    at async deposit1Currency (D:\nodejs\CCXT_Address\Binance1CoinAddress.js:22:25) {
  constructor: [class InvalidNonce extends NetworkError]
}

It seems it has stability issue for library.
Please check!

**Comment by frosty00** [comment]
@zydjohnHotmail make sure you computer clock is synchronised properly

**Comment by zydjohnHotmail** [comment]
Hello:
I believe that the clock of my PC is synchronised, but may be less than one second difference; however, in my Node.js code, I put 'recvWindow': 10000, it means for Binance exchange, if the time difference is less than 10 seconds, the signature will still be valid.
Anyway, what you can do to synchroinse clock of PC, which tools you can use?
Thanks,
