### ISSUE TITLE
Total 10 exchanges have issues with support of fetchDepositAddress for version 2.0.37

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15337]
- OS: Windows 10 (21H2)
- Programming Language version: node.js (ver 18.10.0)
- CCXT version: 2.0.37

There are total 6 exchanges, where function fetchDepositAddress is not supported yet.
bitforex,  bitrue,  bkex,  coinbase,  latoken, lbank.

There are total 4 exchanges, where function fetchDepositAddress is supported, but have different kinds of issues:
bigone (Access Denied),   bkex (returned information is empty),  cryptocom ( INVALID_NONCE), poloniex(Permission denied.)

Hello:
I have done a few tests to know if I can get deposit address for BTC or USDT.  The following is my code:

```JavaScript
const coin1_address = async (exchange1, coin1, apiKey, secretKey) => {
    try {
        let exchange = new ccxt[exchange1]({
            apiKey: apiKey,
            secret: secretKey,
            defaultType: 'spot',
            adjustForTimeDifference: true,
           verbose: false,
        });
        await exchange.loadMarkets();
        const deposits = await exchange.fetchDepositAddress(coin1);
        const json_deposits = JSON.stringify(deposits);
        console.log(json_deposits);
        return json_deposits;
    } 
    catch (err) {
        console.log(err);
        return '{}';
    }
};
```
From my testing, many exchanges don’t support fetchDepositAddress yet, and some of them have different kinds of issues.
```
D:\nodejs\CCXT_Address>node Exchanges1CoinAddress.js bigone BTC
2.0.37
bigone
(node:21560) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ExchangeNotAvailable: bigone GET https://big.one/api/v3/asset_pairs 403 Forbidden <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;big&#46;one&#47;api&#47;v3&#47;asset&#95;pairs" on this server.<P>
Reference&#32;&#35;18&#46;c5f9645f&#46;1666118157&#46;174e5adb
</BODY>
</HTML>

D:\nodejs\CCXT_Address>node Exchanges1CoinAddress.js bitforex BTC
2.0.37
bitforex
(node:14816) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
NotSupported: bitforex fetchDepositAddress() is not supported yet
    at bitforex.fetchDepositAddress (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:2257:19)
    at coin1_address (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:31:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async get1CoinAddress (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:166:36) {
  constructor: [class NotSupported extends ExchangeError]
}


D:\nodejs\CCXT_Address>node Exchanges1CoinAddress.js bitrue BTC
2.0.37
bitrue
(node:33072) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
NotSupported: bitrue fetchDepositAddress() is not supported yet
    at bitrue.fetchDepositAddress (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:2257:19)
    at coin1_address (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:31:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async get1CoinAddress (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:166:36) {
  constructor: [class NotSupported extends ExchangeError]
}

D:\nodejs\CCXT_Address>node Exchanges1CoinAddress.js bkex USDT
2.0.37
bkex
(node:18388) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{"currency":"USDT","info":[]}
{"currency":"USDT","info":[]}

D:\nodejs\CCXT_Address>node Exchanges1CoinAddress.js coinbase USDT
2.0.37
coinbase
(node:25364) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
NotSupported: coinbase fetchDepositAddress() is not supported yet
    at coinbase.fetchDepositAddress (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:2257:19)
    at coin1_address (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:31:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async get1CoinAddress (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:166:36) {
  constructor: [class NotSupported extends ExchangeError]
}

D:\nodejs\CCXT_Address>node Exchanges1CoinAddress.js cryptocom USDT
2.0.37
cryptocom
(node:14600) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
InvalidNonce: cryptocom {"id":1666118538402,"method":"private/get-deposit-address","code":10007,"message":"INVALID_NONCE"}

D:\nodejs\CCXT_Address>node Exchanges1CoinAddress.js latoken USDT
2.0.37
latoken
(node:29452) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
NotSupported: latoken fetchDepositAddress() is not supported yet
    at latoken.fetchDepositAddress (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:2257:19)
    at coin1_address (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:31:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async get1CoinAddress (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:166:36) {
  constructor: [class NotSupported extends ExchangeError]
}

D:\nodejs\CCXT_Address>node Exchanges1CoinAddress.js lbank USDT
2.0.37
lbank
(node:39732) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
NotSupported: lbank fetchDepositAddress() is not supported yet
    at lbank.fetchDepositAddress (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:2257:19)
    at coin1_address (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:31:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async get1CoinAddress (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:166:36) {
  constructor: [class NotSupported extends ExchangeError]
}

D:\nodejs\CCXT_Address>node Exchanges1CoinAddress.js poloniex BTC
2.0.37
poloniex
(node:35540) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ExchangeNotAvailable: poloniex GET https://api.poloniex.com/wallets/addresses?currency=BTC 400 Bad Request {
  "code" : "FORBIDDEN",
  "message" : "Permission denied."
}
    at poloniex.handleHttpStatusCode (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:753:19)
    at D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:600:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async poloniex.fetch2 (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:1803:16)
    at async poloniex.request (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:1807:16)
    at async poloniex.fetchDepositAddress (D:\nodejs\CCXT_Address\node_modules\ccxt\js\poloniex.js:1454:26)
    at async coin1_address (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:31:26)
    at async get1CoinAddress (D:\nodejs\CCXT_Address\Exchanges1CoinAddress.js:166:36) {
  constructor: [class ExchangeNotAvailable extends NetworkError]
}
```

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail 

There are some authentication errors, have checked the api key and secret? Sometimes, we set different credentials for the exchange convention. For some exchanges, they didn't support retrieve deposit address from api yet. I can take a look at those exchanges, and update.

**Comment by zydjohnHotmail** [comment]
Hello:
I think most of the exchanges, the credentials are correct, since most of those exchanges, I can use CCXT to get account balance.
Now, kucoin is OK, as I didn't create addresses first, but for other exchanges, please check, at least for 6 exchanges, where fetchDepositAddress are not supported yet.
Thanks,

**Comment by dugusanfeng** [comment]
The lbank exchange I tested：

`
const agent = new HttpsProxyAgent('http://127.0.0.1:1087');
const exchange = new ccxt.lbank2({
        'apiKey': 'e905421f-xxxx-xxxx-xxxx-c5af76162a5a',
        'secret': 'xxxxxxx',
        agent
    })

const depositAddr = await exchange.fetchDepositAddress('USDT', {network: 'ERC20'})
console.log('addr: ', depositAddr)
`
 
response:  { result: 'false', error_code: '10022', ts: '1666333434661' }
(node:37283) UnhandledPromiseRejectionWarning: PermissionDenied: Invalid authorization

**Comment by ttodua** [comment]
came across to this old issue.
There have been multiple updates since then, and let us know if anyone experiences issues currently.
