### ISSUE TITLE
{"code":-2014,"msg":"API-key format invalid."} ISs there anyone who can tell me why I  can not get the order_book?

### ISSUE THREAD

**Issue by Clairewangxiaotong** [ccxt/ccxt#15398]
my code:

os.environ["http_proxy"]  = "http://127.0.0.1:10809"
os.environ["https_proxy"] = "http://127.0.0.1:10809"
binance = ccxt.binance({  'timeout': 60000, 'enableRateLimit': True,})
binance.apiKey = ''
binance.secret = ''

symbol = 'BTC/USDT'
while 1:
    print(binance.account())
    print(binance.fetch_order_book(symbol=symbol))

bug:

{'free': None, 'used': None, 'total': None}
Traceback (most recent call last):
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\urllib3\connection.py", line 176, in _new_conn
    conn = connection.create_connection(
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\urllib3\connection.py", line 360, in connect
    self.sock = conn = self._new_conn()
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\urllib3\connection.py", line 188, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002210135C2E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /sapi/v1/capital/config/getall?timestamp=1666669244634&recvWindow=10000&signature=58f97c70cee0b3f1b1f0db255efedcc897cc0acc2f30403c699255f2dfe1ff4d (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002210135C2E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\ccxt\base\exchange.py", line 594, in fetch
    response = self.session.request(
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /sapi/v1/capital/config/getall?timestamp=1666669244634&recvWindow=10000&signature=58f97c70cee0b3f1b1f0db255efedcc897cc0acc2f30403c699255f2dfe1ff4d (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002210135C2E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/112233/Desktop/NN/低频/new.py", line 28, in <module>
    print(binance.fetch_order_book(symbol=symbol))
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\ccxt\binance.py", line 2095, in fetch_order_book
    self.load_markets()
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\ccxt\base\exchange.py", line 1430, in load_markets
    currencies = self.fetch_currencies()
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\ccxt\binance.py", line 1315, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\ccxt\binance.py", line 5572, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\ccxt\base\exchange.py", line 2609, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\Anaconda\envs\tqsdk\lib\site-packages\ccxt\base\exchange.py", line 647, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1666669244634&recvWindow=10000&signature=58f97c70cee0b3f1b1f0db255efedcc897cc0acc2f30403c699255f2dfe1ff4d

Process finished with exit code 1

**Comment by carlosmiei** [comment]
Hello @Clairewangxiaotong,

Seems something related to your proxy, assuming that your using the sync version, can add this option? `requests_trust_env=True` 

```Python
binance = ccxt.binance({  'timeout': 60000, 'enableRateLimit': True,requests_trust_env=True})
```

**Comment by Clairewangxiaotong** [comment]
Hi Carlos，Thanks for your help.

Carlos Gonçalves ***@***.***> 于2022年10月25日周二 21:14写道：
