### ISSUE TITLE
CCXT Pro's `fetch_trades` is returning cached trades in some exchanges

### ISSUE THREAD

**Issue by MinsungKim-BlockCrafters** [ccxt/ccxt#15392]
- OS: MacOS Monterey 12.6
- Programming Language version: Python 3.9.6
- CCXT version: 2.0.58

About `exchange.fetch_trades`, I expect this method will return new data which is not available in last returned data. However, it returned the cached data in some exchanges.

Run following program with providing inputs as `bitmex, xbtusd` or `binance, btcusdt`, then you will be able to reproduce the result.

```python
import asyncio
from pprint import pprint

import ccxt
import ccxt.pro


async def main():

    print(ccxt.__version__)
    exchange: ccxt.pro.Exchange = getattr(
        ccxt.pro, input("Enter exchange name: ").strip().lower()
    )()
    # exchange.verbose = True
    symbol = input("Enter symbol: ").strip().upper()

    try:
        while True:
            trades = await exchange.watch_trades(symbol)
            for trade in trades:
                del trade["info"]
            pprint(trades)
    except BaseException as err:
        await exchange.close()
        pprint(trades)
        raise err


if __name__ == "__main__":
    asyncio.run(main())
```

```shell
(systra-common) minsungkim@Minsungui-MacBookPro systra-common % PYTHONPATH=src python examples/ccxt_watch_trades.py
2.0.58
Enter exchange name: bitmex
Enter symbol: xbtusd
[{'timestamp': 1666602526811, 'datetime': '2022-10-24T09:08:46.811Z', 'symbol': 'BTC/USD:BTC', 'id': 'dcc68f18-ee4d-ed8e-fea4-0ffdc718c68b', 'order': None, 'type': None, 'takerOrMaker': None, 'side': 'sell', 'price': 19323.0, 'cost': -9832841.69124867, 'amount': 1900.0, 'fee': None, 'fees': []}]
[{'timestamp': 1666602526811, 'datetime': '2022-10-24T09:08:46.811Z', 'symbol': 'BTC/USD:BTC', 'id': 'dcc68f18-ee4d-ed8e-fea4-0ffdc718c68b', 'order': None, 'type': None, 'takerOrMaker': None, 'side': 'sell', 'price': 19323.0, 'cost': -9832841.69124867, 'amount': 1900.0, 'fee': None, 'fees': []}, {'info': {'timestamp': '2022-10-24T09:08:58.408Z', 'symbol': 'XBTUSD', 'side': 'Sell', 'size': 200, 'price': 19323, 'tickDirection': 'ZeroMinusTick', 'trdMatchID': 'ef17d1fd-87e2-3ab8-c2ba-f7bed7a63bab', 'grossValue': 1035036, 'homeNotional': 0.01035036, 'foreignNotional': 200}, 'timestamp': 1666602538408, 'datetime': '2022-10-24T09:08:58.408Z', 'symbol': 'BTC/USD:BTC', 'id': 'ef17d1fd-87e2-3ab8-c2ba-f7bed7a63bab', 'order': None, 'type': None, 'takerOrMaker': None, 'side': 'sell', 'price': 19323.0, 'cost': -1035035.96749986, 'amount': 200.0, 'fee': None, 'fees': []}]
Traceback (most recent call last):
  File "/Users/minsungkim/.../examples/ccxt_watch_trades.py", line 30, in <module>
    asyncio.run(main())
  File "/Users/minsungkim/.../lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/minsungkim/.../lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/minsungkim/.../examples/ccxt_watch_trades.py", line 26, in main
    raise err
  File "/Users/minsungkim/.../examples/ccxt_watch_trades.py", line 21, in main
    del trade["info"]
KeyError: 'info'
```

**Comment by MinsungKim-BlockCrafters** [comment]
I realized I have to set `{"newUpdates": True}` in exchange, however the issue still persists.

**Comment by carlosmiei** [comment]
Hello @MinsungKim-BlockCrafters thanks for letting us know, we will take a look

**Comment by pcriadoperez** [comment]
Hi @MinsungKim-BlockCrafters , thanks for bringing this up. I found the issue was the we were only filtering correctly the new updates when passing in the unified exchange and not the exchange market id for some exchanges.
I'll open a PR to fix this issue.

**Comment by ttodua** [comment]
old issue, was addressed by PcriadoPerez in the past. closing this. 
let us know if anyone has any issue
