### ISSUE TITLE
Unable to build example ccxt/examples/ts/fetch-tickers/

### ISSUE THREAD

**Issue by AClotfelter** [ccxt/ccxt#15409]
Downloaded a zip copy of the repository, and attempted to build the TypeScript example in ccxt/examples/ts/fetch-tickers/

At first, running `npm i` in the example directory yielded the following error, saying that the requisite version of ccxt could not be found:

```
fetch-tickers % npm i
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN old lockfile ccxt: No matching version found for ccxt@1.18.1147.
npm WARN old lockfile     at module.exports (/opt/homebrew/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/opt/homebrew/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
npm WARN old lockfile     at async Array.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:738:24)
npm WARN old lockfile  Could not fetch metadata for ccxt@1.18.1147 ccxt: No matching version found for ccxt@1.18.1147.
npm WARN old lockfile     at module.exports (/opt/homebrew/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/opt/homebrew/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
npm WARN old lockfile     at async Array.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:738:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '1.18.1147',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '1.40.1',  '1.40.2',  '1.40.3',  '1.40.4',  '1.40.5',  '1.40.6',
npm WARN old lockfile     '1.40.7',  '1.40.8',  '1.40.9',  '1.40.10', '1.40.11', '1.40.12',
npm WARN old lockfile     '1.40.13', '1.40.14', '1.40.15', '1.40.16', '1.40.17', '1.40.18',
npm WARN old lockfile     '1.40.19', '1.40.20', '1.40.21', '1.40.22', '1.40.23', '1.40.24',
npm WARN old lockfile     '1.40.25', '1.40.26', '1.40.27', '1.40.28', '1.40.29', '1.40.30',
npm WARN old lockfile     '1.40.31', '1.40.32', '1.40.33', '1.40.34', '1.40.35', '1.40.36',
npm WARN old lockfile     '1.40.37', '1.40.38', '1.40.39', '1.40.40', '1.40.41', '1.40.42',
npm WARN old lockfile     '1.40.43', '1.40.44', '1.40.45', '1.40.46', '1.40.47', '1.40.48',
npm WARN old lockfile     '1.40.49', '1.40.50', '1.40.51', '1.40.52', '1.40.53', '1.40.54',
npm WARN old lockfile     '1.40.55', '1.40.56', '1.40.57', '1.40.58', '1.40.59', '1.40.60',
npm WARN old lockfile     '1.40.61', '1.40.62', '1.40.63', '1.40.64', '1.40.65', '1.40.66',
npm WARN old lockfile     '1.40.67', '1.40.68', '1.40.69', '1.40.70', '1.40.71', '1.40.72',
npm WARN old lockfile     '1.40.73', '1.40.74', '1.40.75', '1.40.76', '1.40.77', '1.40.78',
npm WARN old lockfile     '1.40.79', '1.40.80', '1.40.81', '1.40.82', '1.40.83', '1.40.84',
npm WARN old lockfile     '1.40.85', '1.40.86', '1.40.87', '1.40.88', '1.40.89', '1.40.90',
npm WARN old lockfile     '1.40.91', '1.40.92', '1.40.93', '1.40.94', '1.40.95', '1.40.96',
npm WARN old lockfile     '1.40.97', '1.40.98', '1.40.99', '1.41.1',
npm WARN old lockfile     ... 5362 more items
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '2.0.68' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ccxt/-/ccxt-1.18.1147.tgz - Not found
npm ERR! 404 
npm ERR! 404  'ccxt@https://registry.npmjs.org/ccxt/-/ccxt-1.18.1147.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-10-26T06_44_13_910Z-debug-0.log
```

I tried it without the package-lock.json file, and the `npm i` command  completed:

```
fetch-tickers % npm i

added 46 packages, and audited 47 packages in 10s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

But got the following when trying to build/compile:

```
fetch-tickers % npm run build

> fetch-tickers@0.1.0 build
> tsc -p .

node_modules/ccxt/ccxt.d.ts:720:47 - error TS1036: Statements are not allowed in ambient contexts.

720         class Exchange  extends ExchangePro {};
                                                  ~
Found 2 errors.
```

**Comment by carlosmiei** [comment]
@AClotfelter can you upgrade to the latest version and try again? ⬆️

**Comment by AClotfelter** [comment]
@carlosmiei Thank you for your prompt look at this issue.


With the new version, `npm i` completes, but the build issue remains:

```
fetch-tickers % npm run build

> fetch-tickers@0.1.0 build
> tsc -p .

node_modules/ccxt/ccxt.d.ts:718:47 - error TS1036: Statements are not allowed in ambient contexts.

718         class Exchange  extends ExchangePro {};
                                                  ~


Found 2 errors.
```

I was able to fix the error by editing the `node_modules/ccxt/ccxt.d.ts` file, to remove the semicolons within `export namespace pro`, found on line 716.

I forked, and went to make a PR, but found that the repo version of the file did not have these semicolons.
It appears that either the npm-published version (2.0.70) was from source prior to the change (repo version appears to be 2.0.71), or something in the npm publish chain is adding the semicolons.

**Comment by carlosmiei** [comment]
@AClotfelter what if inside `fetchTickers` you run `npm run update ccxt` ? Don't know if you might have an outaded package inside `node_modules`

**Comment by AClotfelter** [comment]
@carlosmiei `npn update ccxt` did not resolve the issue. I also have been removing the `node_modules` folder between attempts. It really does seem that the nom published version 2.0.70 has the semicolons.

**Comment by carlosmiei** [comment]
@AClotfelter hum that's weird, I just installed the latest version and I don't see it.

![image](https://user-images.githubusercontent.com/43336371/198093859-15832110-30ab-49b4-aa50-f17b9ebd27aa.png)

**Comment by carlosmiei** [comment]
@AClotfelter can you delete your node_modules and `npm i` again?

**Comment by AClotfelter** [comment]
@carlosmiei Unfortunately, same issue:

```
fetch-tickers % rm -rf ./node_modules 
fetch-tickers % ls
package-lock.json	package.json		prettier.config.js	src			tsconfig.json
fetch-tickers % npm i

added 47 packages, and audited 48 packages in 1s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
fetch-tickers % npm run build

> fetch-tickers@0.1.0 build
> tsc -p .

node_modules/ccxt/ccxt.d.ts:718:47 - error TS1036: Statements are not allowed in ambient contexts.

718         class Exchange  extends ExchangePro {};
                                                  ~


Found 2 errors.
```

**Comment by AClotfelter** [comment]
Forcing download does not change outcome:

```
uberg@Si1 fetch-tickers % rm -rf ./node_modules
uberg@Si1 fetch-tickers % ls
package-lock.json	package.json		prettier.config.js	src			tsconfig.json
uberg@Si1 fetch-tickers % npm i --force        
npm WARN using --force Recommended protections disabled.

added 47 packages, and audited 48 packages in 1s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
uberg@Si1 fetch-tickers % npm run build        

> fetch-tickers@0.1.0 build
> tsc -p .

node_modules/ccxt/ccxt.d.ts:718:47 - error TS1036: Statements are not allowed in ambient contexts.

718         class Exchange  extends ExchangePro {};
                                                  ~


Found 2 errors.
```

**Comment by AClotfelter** [comment]
@carlosmiei It's worth noting that the section of code in your screenshot is not the block in question; the screenshot code is a block starting on line 16, and the problem code is a block starting on line 716.

**Comment by carlosmiei** [comment]
@AClotfelter actually I think you're right (sorry about the screenshot, clearly was showing the wrong section) I'll try to figure it out because this is really strange as you can see here https://github.com/ccxt/ccxt/blob/master/ccxt.d.ts `;` are not there anymore

**Comment by AClotfelter** [comment]
@carlosmiei Thanks!

**Comment by carlosmiei** [comment]
@AClotfelter, can you try again, please? I don't know if npm was somehow caching that file or something like that but  in the latest version seems to be fixed now: 
![image](https://user-images.githubusercontent.com/43336371/198543262-e09fc8b0-5f2f-4b1e-9ffb-4a7311be94a2.png)

**Comment by AClotfelter** [comment]
@carlosmiei Building with the latest NPM versions now works correctly. Thanks for your efforts!
