### ISSUE TITLE
How to fix Cryptocom INVALID_NONCE error?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15403]
- OS: Window 10 (21H2)
- Programming Language version: Node.js (ver 18.10.0)
- CCXT version: 2.0.66

```JavaScript
const ccxt = require('ccxt')
console.log(ccxt.version);

var account_balance = async () => {
	const exchange = new ccxt.cryptocom
		({
			apiKey: 'My_API_Key',
			secret: 'My_Secret_Key',
			'options': {
				'adjustForTimeDifference': true,
				'verbose': true,
			}
		});
	try {
		const balance = await exchange.fetchBalance()
		console.log(balance);
	}
	catch (err)
	{
		console.error(err)
    }
}
account_balance();
```

```JavaScript
D:\nodejs\CCXT_Address>node cryptocom_balance.js
2.0.66
(node:19988) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
InvalidNonce: cryptocom {"id":1666704829185,"method":"private/get-account-summary","code":10007,"message":"INVALID_NONCE"}
    at cryptocom.throwExactlyMatchedException (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:2142:19)
    at cryptocom.handleErrors (D:\nodejs\CCXT_Address\node_modules\ccxt\js\cryptocom.js:2431:18)
    at D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async cryptocom.fetch2 (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:1803:16)
    at async cryptocom.request (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:1807:16)
    at async cryptocom.fetchBalance (D:\nodejs\CCXT_Address\node_modules\ccxt\js\cryptocom.js:867:26)
    at async json_address (D:\nodejs\CCXT_Address\cryptocom_balance.js:15:19) {
  constructor: [class InvalidNonce extends NetworkError]
}
```

Hello

I want to use ccxt to get account balance for exchange cryptocom

The code did NOT work.
Pleas advise on how I can change my code to avoid INVALID_NONCE error, I think my PC is synchronized with time server, it should be OK.
But I remember that the same code worked a few weeks ago.

Please advise!

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail

How was your network environment? Maybe the connection was too slow or ntp went behind. Would you like to sync the ntp first?

(https://exchange-docs.crypto.com/spot/index.html#invalid_nonce-on-all-requests)

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I think the article suggest one good solution for my issue:
If the issue persists, you can try deliberately subtracting 5 seconds from the nonce to force it to be 5 seconds in the past, which is still within the 30-second past tolerance.
But how can I write some JavaScript in CCXT to subtract 5 seconds from the nonce, please advise!
Thanks,

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail 

We use `nonce()` function, you probably can rewrite the prototype function in javascript. eg.

```JS
cryptocom.nonce = () => {
  return this.milliseconds() - 5000
}
```

Let me know if you have other questions.

**Comment by zydjohnHotmail** [comment]
Hello:
Thank you very much for your reply. I changed my code, so it looks like this now:

`const ccxt = require('ccxt')
const fs = require('fs')
const fsPromises = fs.promises
const keys = require('./keys.local.json');
console.log('CCXT Version:', ccxt.version);

const cryptocom = new ccxt.cryptocom({
    'apiKey': keys.cryptocom.apiKey,
    'secret': keys.cryptocom.secret,
    'options': {
        'adjustForTimeDifference': true,
        'verbose': true,
    }
});

cryptocom.nonce = () => 
{
	return this.milliseconds() - 5000
}

var exchange_balance = async () => 
{
try 
{
	cryptocom.nonce();
	const balance = await cryptocom.fetchBalance()
	console.log(balance);
}
catch (err)
{
console.error(err)
}
}
exchange_balance();
`
But when I run this code, I got the errors:
D:\nodejs\CCXT_Address>node cryptocom_balance.js
CCXT Version: 2.0.77
TypeError: this.milliseconds is not a function
    at cryptocom.nonce (D:\nodejs\CCXT_Address\cryptocom_balance.js:18:14)
    at exchange_balance (D:\nodejs\CCXT_Address\cryptocom_balance.js:25:12)
    at Object.<anonymous> (D:\nodejs\CCXT_Address\cryptocom_balance.js:34:1)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

D:\nodejs\CCXT_Address>

First, let me know if I made any mistake in my code, then why I got this error.
Thanks,

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail

I forgot binding `this` object. You can try this:

```JS
  cryptocom.nonce =  function () {
    return this.milliseconds () - 5000
  }.bind(bybit)
```

**Comment by zydjohnHotmail** [comment]
Hello:
I changed my code, the following is the related part:

`
cryptocom.nonce =  function () 
{
   return this.milliseconds () - 5000
}.bind(bybit)
  
var exchange_balance = async () => 
{
try 
{
	cryptocom.nonce();
	const balance = await cryptocom.fetchBalance()
	console.log(balance);
}
catch (err)
{
console.error(err)
}
}
exchange_balance();
`
But when I run this, I got error:
D:\nodejs\CCXT_Address>node cryptocom_balance.js
CCXT Version: 2.0.77
D:\nodejs\CCXT_Address\cryptocom_balance.js:19
}.bind(bybit)
       ^

ReferenceError: bybit is not defined
    at Object.<anonymous> (D:\nodejs\CCXT_Address\cryptocom_balance.js:19:8)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.10.0
