### ISSUE TITLE
Calling two fetch_open_orders in a row causes an error

### ISSUE THREAD

**Issue by kosmodromov** [ccxt/ccxt#1540]
- OS: Linux CenOS 7 & Mac OS High Sierra 10.13.2
- Programming Language version: Python 3.6.4
- CCXT version: 1.10.878
- Exchange: YoBit
- Method: fetch_open_orders()

```
import ccxt
from pprint import pprint

yo = ccxt.yobit({'enableRateLimit': True,})
yo.apiKey = 'key'
yo.secret = 'secret'

pprint(yo.fetch_open_orders('SEL/BTC'))
pprint(yo.fetch_open_orders('SQL/BTC'))
```

Output:

```
[{'amount': None,
  'cost': None,
  'datetime': '2018-01-27T21:43:28.000Z',
  'fee': None,
  'filled': None,
  'id': '201039411626774',
  'info': {'amount': 0.9859133,
           'id': '201039411626774',
           'pair': 'sel_btc',
           'rate': 0.00024343,
           'status': 0,
           'timestamp_created': '1517089408',
           'type': 'sell'},
  'price': 0.00024343,
  'remaining': 0.9859133,
  'side': 'sell',
  'status': 'open',
  'symbol': 'SEL/BTC',
  'timestamp': 1517089408000,
  'type': 'limit'}]
Traceback (most recent call last):
  File "/Users/dd/python/ttt.py", line 33, in <module>
    pprint(yo.fetch_open_orders('SQL/BTC'))
  File "/Users/dd/python/venv/lib/python3.6/site-packages/ccxt/liqui.py", line 503, in fetch_open_orders
    orders = self.fetch_orders(symbol, since, limit, params)
  File "/Users/dd/python/venv/lib/python3.6/site-packages/ccxt/liqui.py", line 490, in fetch_orders
    'cost': order['amount'] * order['price'],
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

What method returns if call these orders by one:
```
[{'amount': None,
  'cost': None,
  'datetime': '2018-01-27T21:43:28.000Z',
  'fee': None,
  'filled': None,
  'id': '201039411626774',
  'info': {'amount': 0.9859133,
           'id': '201039411626774',
           'pair': 'sel_btc',
           'rate': 0.00024343,
           'status': 0,
           'timestamp_created': '1517089408',
           'type': 'sell'},
  'price': 0.00024343,
  'remaining': 0.9859133,
  'side': 'sell',
  'status': 'open',
  'symbol': 'SEL/BTC',
  'timestamp': 1517089408000,
  'type': 'limit'}]
```

```
[{'amount': None,
  'cost': None,
  'datetime': '2018-01-27T21:43:21.000Z',
  'fee': None,
  'filled': None,
  'id': '200292411626532',
  'info': {'amount': 2.0624638,
           'id': '200292411626532',
           'pair': 'sql_btc',
           'rate': 0.00011637,
           'status': 0,
           'timestamp_created': '1517089401',
           'type': 'sell'},
  'price': 0.00011637,
  'remaining': 2.0624638,
  'side': 'sell',
  'status': 'open',
  'symbol': 'SQL/BTC',
  'timestamp': 1517089401000,
  'type': 'limit'}]
```

**Comment by glasreiniger07** [comment]
I have almost the same issue with fetch_open_orders() on yobit.
It works for me if I edit line
https://github.com/ccxt/ccxt/blob/9ea97d98cf7bf3b879ebf17c381ad2c185fc0693/python/ccxt/liqui.py#L539
 to
```python
result = self.filter_orders_by_symbol(self.orders.values(), symbol)
```
I don' t know if this implies a change in logic on the recent changes, but it doesn't seem so.

It is great to see how much progress is under way in this repo. Thank You!

**Comment by kroitor** [comment]
This issue should be fixed by recent fixes to Liqui and derived exchanges and to their .orders cache inner workings. 

https://github.com/ccxt/ccxt/pull/1830

Documented here: https://github.com/ccxt/ccxt/wiki/Manual#orders-cache

Let us know if you still have any difficulties with it. Closing it for now, feel free to reopen it if needed, or just ask questions, if any. Thx!
