### ISSUE TITLE
bitget sandbox mode make error

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#15414]
Hi, this lines :

```
       const bitget = new ccxt.bitget()
       bitget.setSandboxMode(true)
       await bitget.loadMarkets()
```
make this :

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at bitget.implodeParams (/node_modules/ccxt/js/base/functions/misc.js:97:33)
    at bitget.implodeHostname (/node_modules/ccxt/js/base/Exchange.js:2405:21)
    at bitget.sign (/node_modules/ccxt/js/bitget.js:3525:24)
    at bitget.fetch2 (/node_modules/ccxt/js/base/Exchange.js:1802:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bitget.request (/node_modules/ccxt/js/base/Exchange.js:1807:16)
```

**Comment by dawadam** [comment]
Where is the original duplicate ?
