### ISSUE TITLE
ModuleNotFoundError: No module named 'ccxt.async_support.eqonex'

### ISSUE THREAD

**Issue by csotto** [ccxt/ccxt#15416]
- OS: Windows 11 Home Version 22H2, compilation aversion: 22621.674
- Programming Language version: Python 3.10.7
- CCXT version:  ccxt    2.0.71
- CCXTPRO version : ccxtpro       1.2.36

```
#!/usr/bin/env python
import asyncio
import ccxtpro 

```

```
$ python minimal.py
Traceback (most recent call last):
  File "D:\_GIT_sources\cryptoinvestccxt\python\minimal.py", line 3, in <module>
    import ccxtpro
  File "D:\Python310\lib\site-packages\ccxtpro\__init__.py", line 99, in <module>
    from ccxt.async_support.eqonex import eqonex                              # noqa: F401
ModuleNotFoundError: No module named 'ccxt.async_support.eqonex'

```

**Comment by frosty00** [comment]
you can use

```
import ccxt.pro as ccxtpor
```

now

**Comment by csotto** [comment]
@frosty00  Thanks! The fix worked fine!
