### ISSUE TITLE
qty error for bybit

### ISSUE THREAD

**Issue by belqit** [ccxt/ccxt#15430]
- OS: windows
- Node.js version: 16.13.2
- CCXT version: 2.0.73

```
const ccxt = require('ccxt');
const exchangeClass = ccxt.bybit;

async function run() {
    var exchange_ob = {
        timeout: 30000,
        enableRateLimit: true,
        apiKey: '---',
        secret: '---',
        options: {
            warnOnFetchOpenOrdersWithoutSymbol: false
        }
    }
    var ex = new exchangeClass(exchange_ob)

    var r = await ex.createOrder('BTCUSDT', 'limit', 'buy', '0.0002', '12605');
    console.log(r)

}

run()
```

```
C:\Users\user\progetti\trader\node_modules\ccxt2\js\base\Exchange.js:2142
            throw new exact[string] (message);
                  ^

BadRequest: bybit {"ret_code":10001,"ret_msg":"Param validation for 'qty' failed on the 'required' tag","ext_code":"","ext_info":"","result":null,"time_now":"1666883953.690982","rate_limit_status":99,"rate_limit_reset_ms":1666883953689,"rate_limit":100}
    at bybit.throwExactlyMatchedException (C:\Users\user\progetti\trader\node_modules\ccxt2\js\base\Exchange.js:2142:19)
    at bybit.handleErrors (C:\Users\user\progetti\trader\node_modules\ccxt2\js\bybit.js:5499:18)
    at C:\Users\user\progetti\trader\node_modules\ccxt2\js\base\Exchange.js:598:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (C:\Users\user\progetti\trader\node_modules\ccxt2\js\base\functions\time.js:181:20)
    at async bybit.fetch2 (C:\Users\user\progetti\trader\node_modules\ccxt2\js\base\Exchange.js:1803:16)
    at async bybit.request (C:\Users\user\progetti\trader\node_modules\ccxt2\js\base\Exchange.js:1807:16)
    at async bybit.createContractOrder (C:\Users\user\progetti\trader\node_modules\ccxt2\js\bybit.js:3042:26)
    at async bybit.createOrder (C:\Users\user\progetti\trader\node_modules\ccxt2\js\bybit.js:2759:20)
    at async run (C:\Users\user\progetti\trader\test.js:16:13) {
  constructor: [class BadRequest extends ExchangeError]
}
```

i've noticed this:
`amount = this.amountToPrecision (symbol, amount);`
is rouding amount to 0

**Comment by sc0Vu** [comment]
Hi @belqit,

I can reproduce this when `createOrder` with string parameter, always had qty validation error. However, I think it works with number parameters:

```
$ node examples/js/cli bybit createOrder BTCUSDT limit buy 0.0002 12605 --spot         
Node.js: v16.13.2
CCXT v2.0.73
bybit.createOrder (BTCUSDT, limit, buy, 0.0002, 12605)
ExchangeError bybit {"ret_code":-1131,"ret_msg":"Balance insufficient ","result":{},"ext_code":"","ext_info":null}
```

Before we fix this issue, you can set price and amount as number.

**Comment by sc0Vu** [comment]
Hi @belqit 

I think that's the market and precision issue. In bybit, it depends on what market you want to trade, looks like they have same id for spot and swap market pair, eg `BTCUSDT`.

So we used `defaultType` to handle different market. The default type is `swap`, the market you loaded is swap market (the precision for swap is 0.001).

If you want to buy spot, please set `defaultType` to `spot`.

```JS
  const bybit = new ccxt.bybit({
    "apiKey": "",
    "secret": "",
    'options': {
      'defaultType': 'spot'
    }
  })
```

Let me know if you have other questions.
