### ISSUE TITLE
bybit fetchOrders is not supported while hasFetchOrders is true

### ISSUE THREAD

**Issue by danieltorscho** [ccxt/ccxt#15462]
`exchange.fetchOrders` is not supported on Bybit exchange.

- OS: Win 10 x64
- Programming Language version: Node.js 18
- CCXT version: 2.0.67

```JavaScript
exchange.hasFetchOrders      // <-- true
exchange.has['fetchOrders']  // <-- true

exchange.fetchOrders('BTCUSDT') // <-- error
```

```JavaScript
/home/user/www/node-trading-bot/node_modules/ccxt/js/bybit.js:3447
            throw new NotSupported (this.id + ' fetchOrders() does not support ' + market['type'] + ' markets or USDC markets, use exchange.fetchOpenOrders () and exchange.fetchClosedOrders () instead');
                  ^

NotSupported: bybit fetchOrders() does not support spot markets or USDC markets, use exchange.fetchOpenOrders () and exchange.fetchClosedOrders () instead
    at bybit.fetchOrders (/home/user/www/node-trading-bot/node_modules/ccxt/js/bybit.js:3447:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/home/user/www/node-trading-bot/src/testing.js:70:14) {
  constructor: [class NotSupported extends ExchangeError]
}
```

**Comment by sc0Vu** [comment]
Hi @danieltorscho 

The error is that bybit didn't support spot and usdc settled trading pairs. Please make sure the pair is not one of them. In the mean time, I'll check whether they open api endpoint for the spot.

**Comment by danieltorscho** [comment]
@sc0Vu 
Yeah you are right, I was using a spot trading pair.

**Comment by carlosmiei** [comment]
@danieltorscho `fetchOrders` is now fully supported.
