### ISSUE TITLE
"Balance insufficient" error in Bybit once an order is Partially Filled

### ISSUE THREAD

**Issue by danieltorscho** [ccxt/ccxt#15516]
I randomly receives an error when creating a BUY or SELL order on Bybit.
It happens only when an order is partially filled, at random time.

Each time an order is Partially Filled - I get an error.

Both methods `createLimitBuyOrder` and `createLimitSellOrder` are working fine if an order is Filled.
If it is PARTIALLY_FILED, then it throws an error.

Did anyone experienced the same errors ?

- OS: Win 10 x64
- Programming Language version: Node.js 18
- CCXT version: 2.0.102

```JavaScript
exchange.createLimitBuyOrder(quantity, price)

exchange.createLimitSellOrder(quantity, price)
```

```JavaScript
ExchangeError: bybit {"ret_code":-1131,"ret_msg":"Balance insufficient ","result":{},"ext_code":"","ext_info":null,"time_now":"1667339430.526475"}
    at bybit.handleErrors (/home/user/www/node-trading-bot/node_modules/ccxt/js/bybit.js:5505:19)
    at /home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:598:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/functions/time.js:181:20)
    at async bybit.fetch2 (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:1803:16)
    at async bybit.request (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:1807:16)
    at async bybit.createSpotOrder (/home/user/www/node-trading-bot/node_modules/ccxt/js/bybit.js:2810:26)
    at async bybit.createOrder (/home/user/www/node-trading-bot/node_modules/ccxt/js/bybit.js:2756:20)
    at async bybit.createLimitSellOrder (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:2334:16)
    at async Exchange.createLimitSellOrder (/home/user/www/node-trading-bot/src/services/exchange.js:58:19) {
  constructor: [class ExchangeError extends BaseError]
}
```

**Comment by ttodua** [comment]
late reply to an old issue, but bybit API has been updated since then, if anyone still experiences any issue, let us know
