### ISSUE TITLE
Problem with Bitbay fetch_order_book()

### ISSUE THREAD

**Issue by netdodger** [ccxt/ccxt#1553]
- OS: Ubuntu 16.04
- Programming Language version: Python 2.7
- CCXT version: 1.10.888
- Exchange: Bitbay
- Method: fetch_order_book()

When requesting BitBays order book, `ccxt.bitbay().fetch_order_book('BTC/USD')`, I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ccxt/bitbay.py", line 167, in fetch_order_book
    }, params))
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 303, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 300, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 375, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/bitbay.py", line 283, in handle_errors
    if (not isinstance(body, basestring)) or len((body) < 2):
TypeError: object of type 'bool' has no len()
```

It worked before I updated ccxt to version 1.10.888. I do not recall exactly which was the previous version I had, but it was pretty old (pre 2018).

**Comment by kroitor** [comment]
This is fixed in 1.10.890. Let us know if you have any other difficulties with it. Thx!
