### ISSUE TITLE
Can NOT get BTC deposit address for cex for CCXT version 2.1.14

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15541]
- OS: Windows 10 PRO (21H2)
- Programming Language version: Node.js (Ver 19.0.0)
- CCXT version: 2.1.4

```JavaScript
const ccxt = require('ccxt')
const keys = require ('./keys.local.json');
console.log ('CCXT Version:', ccxt.version);

if (process.argv.length != 3)
{
        console.error('Usage: USDT');
        console.error('Get [coin1] deposit address at [cex]');
        console.error('Please try again!');
        process.exit(1);
}
const [nodejs, script1, coin1] = process.argv;

const exchange = new ccxt.cex ({
    'apiKey': keys.cex.apiKey,
    'secret': keys.cex.secret,
    'uid': 'My_UID',
    adjustForTimeDifference: true,
    defaultType: 'spot',
    verbose: false,
});

const deposit1CoinAddress = async (coin1) => {
try
{
        const deposits = await exchange.fetchDepositAddress(coin1);
        if (typeof deposits !== 'undefined')
        {
                const json_deposits = JSON.stringify(deposits);
                console.log(json_deposits);
        }
        else
        {
                const obj_deposit0 = ({ 'Symbol': coin1, 'Data': [] });
                const json_deposit0 = JSON.stringify(obj_deposit0);
                console.log(obj_deposit0);
        }
}
catch (err)
{
        console.error(err)
}
};
deposit1CoinAddress(coin1);
```

```
D:\nodejs\CCXT_Address>node cex_deposit1CoinAddress.js BTC
CCXT Version: 2.1.14
(node:27568) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ExchangeError: cex {"e":"get_address","error":"System error","ok":"error"}
    at cex.handleErrors (D:\nodejs\CCXT_Address\node_modules\ccxt\js\cex.js:1572:19)
    at D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async cex.fetch2 (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:1811:16)
    at async cex.request (D:\nodejs\CCXT_Address\node_modules\ccxt\js\base\Exchange.js:1815:16)
    at async cex.fetchDepositAddress (D:\nodejs\CCXT_Address\node_modules\ccxt\js\cex.js:1510:26)
    at async deposit1CoinAddress (D:\nodejs\CCXT_Address\cex_deposit1CoinAddress.js:27:19) {
  constructor: [class ExchangeError extends BaseError]
}
```

Hello:
I want to use CCXT to get some currency deposit address, for USDT and ETH, my code works, but for BTC and others not.
How to fix this strange issue?  Some works, some not.
Please advise!
Thanks,

**Comment by zydjohnHotmail** [comment]
Hello:
I did some tests, it worked. Thanks for your work.
I have another minor issue, not for this exchange specifically.  But for some exchanges, if I use CCXT to get deposit address, most of the time (90%+) I got only one address, for USDT I can get multiple addresses.  But if I login to web pages, some exchanges, like: gate. For single currency, it may have 2 or 3 or even more addresses on different networks.  
Can I use CCXT to get most of those multi-chain addresses?
Please advise,
Thanks,

**Comment by ttodua** [comment]
@zydjohnHotmail 
good question. you have to refer [`network` parameter](https://docs.ccxt.com/en/latest/manual.html#deposit-and-withdrawal-networks).
