### ISSUE TITLE
FetchTransactionFee not supported yet for CCXT version 2.1.24 for at least 19 exchanges.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15568]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 Pro (21H2)
- Programming Language version: Node.js (19.0.0)
- CCXT version: 2.1.24

```
'use strict';
const ccxt = require('ccxt');
console.log(ccxt.version);

const exchange = new ccxt.bigone
({
    adjustForTimeDifference: true,
    defaultType: 'spot',
   verbose: false,
})

const withdrawFees = async () => 
{
try 
{
    const transaction_fees = await exchange.fetchTransactionFee();
    console.log(transaction_fees);
}
catch (err) 
{
	console.log(err);
}
};

withdrawFees();
```

```
D:\nodejs\CCXT_Binance>node BigoneFetchTransactionFee.js
2.1.24
NotSupported: bigone fetchTransactionFee() is not supported yet
    at bigone.fetchTransactionFee (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\Exchange.js:2054:19)
    at withdrawFees (D:\nodejs\CCXT_Binance\BigoneFetchTransactionFee.js:17:17)
    at Object.<anonymous> (D:\nodejs\CCXT_Binance\BigoneFetchTransactionFee.js:26:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  constructor: [class NotSupported extends ExchangeError]
}
```
I have tested more than 20 exchanges, only 2 of them have this function supported: 
Binance and Whitebit, another one: lbank2 seems has this function, but the returned result seems empty:

D:\nodejs\CCXT_Binance>node Lbank2FetchTransactionFee.js
2.1.24
(node:26420) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{
  withdraw: {},
  deposit: {},
  info: { result: 'true', data: [], code: '0' }
}

The following 19 exchanges don’t have this function yet:
AAX, BIGONE, BITFOREX, BITMART, BITRUE, BKEX, cex, COINEX, CRYPTOCOM, Digifinex
Gate, HITBTC, Huobi, Kucoin, LATOKEN, mexc3, OKEX, POLONIEX, PROBIT

Please let me know do you have plan to implement this function for the above 19 exchanges?
Thanks,

**Comment by carlosmiei** [comment]
@zydjohnHotmail Yes we plan to implement it on all of them

**Comment by carlosmiei** [comment]
fyi @AlgoQ

**Comment by samgermain** [comment]
`okx.has['fetchTransactionFees']` is equal to `false` meaning that the okx api does not provide this functionality

**Comment by AlgoQ** [comment]
Hi @zydjohnHotmail,

`lbank2`only returns information for currencies with non-zero balances.

I'm working on integrating the other exchanges.

**Comment by AlgoQ** [comment]
Hi @zydjohnHotmail,

We added all the `fetchDepositWithdrawalFees` for the exchanges that support this function
