### ISSUE TITLE
Transfering (withdrawal) coins to another KYC account (email, phone or UID)

### ISSUE THREAD

**Issue by danieltorscho** [ccxt/ccxt#15563]
I'm trying to send USDT to another account on the same exchange platform (Bybit).
In [Transfer section](https://github.com/ccxt/ccxt/wiki/Manual#account-types), it's written following:

*Some exchanges allow transfers to email addresses, phone numbers or to other users by user id.*

I'm not sure what should I use, a `transfer()` function or a `withdraw()` function ?

When using `exchange.withdraw()` it gives me an error. What am I doing wrong here ? I didn't found any similiar case in issues.

- OS: Win 10 x64
- Programming Language version: Node.js 18
- CCXT version: 2.1.18

```
// Gives me an error
exchange.withdraw('USDT', 10, 'someUserMail@gmail.com')

// Not sure how to send to an email or UID
exchange.transfer('USDT', 10, 'sender@gmail.com', 'receiver@gmail.com')
```

```
// Error for .withdraw
BadRequest: bybit {"ret_code":10001,"ret_msg":"Illegal parameter: Coin \u0026 Chain \u0026 Address \u0026 Amount all must not be empty.","ext_code":"","result":null,"ext_info":null,"time_now":1667544222988}
    at bybit.throwExactlyMatchedException (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:2153:19)
    at bybit.handleErrors (/home/user/www/node-trading-bot/node_modules/ccxt/js/bybit.js:5505:18)
    at /home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:598:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/functions/time.js:181:20)
    at async bybit.fetch2 (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:1814:16)
    at async bybit.request (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:1818:16)
    at async bybit.withdraw (/home/user/www/node-trading-bot/node_modules/ccxt/js/bybit.js:4421:26) {
  constructor: [class BadRequest extends ExchangeError]
}

// Error for .transfer
BadRequest: bybit {"ret_code":10001,"ret_msg":"invalid parameter","ext_code":"","result":null,"ext_info":null,"time_now":1667545064555}
    at bybit.throwExactlyMatchedException (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:2153:19)
    at bybit.handleErrors (/home/user/www/node-trading-bot/node_modules/ccxt/js/bybit.js:5505:18)
    at /home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:598:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/functions/time.js:181:20)
    at async bybit.fetch2 (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:1814:16)
    at async bybit.request (/home/user/www/node-trading-bot/node_modules/ccxt/js/base/Exchange.js:1818:16)
    at async bybit.transfer (/home/user/www/node-trading-bot/node_modules/ccxt/js/bybit.js:5149:26) {
  constructor: [class BadRequest extends ExchangeError]
}
```

**Comment by sc0Vu** [comment]
Hi @danieltorscho 

I think you mean withdraw to another KYC account. The `transfer` function is to make internal transfer between your own account.

For withdraw, you need to set address and network. To fetch deposit address, you can call `fetchDepositAddress('USDT')`.

Let me kno if you have other questions.

**Comment by danieltorscho** [comment]
I wanted to avoid fees by using transfer to another KYC account. I've made an Internal Withdraw via Bybit website by using an email, and fetched that withdraw transaction `exchange.fetchWithdrawals('USDT').then(console.log)` and here what I got:

```
[
  {
    info: {
      id: '9596904',
      user_id: '39148494',
      coin: 'USDT',
      status: 'Success',
      amount: '10',
      fee: '0',
      address: 'daniel.torscho@gmail.com',
      tx_id: '',
      submited_at: '2022-11-04T06:30:17Z',
      updated_at: '2022-11-04T06:30:31Z'
    },
    id: '9596904',
    txid: undefined,
    timestamp: 1667543417000,
    datetime: '2022-11-04T06:30:17.000Z',
    network: undefined,
    address: 'akim.torscho@gmail.com',
    addressTo: undefined,
    addressFrom: undefined,
    tag: undefined,
    tagTo: undefined,
    tagFrom: undefined,
    type: 'withdrawal',
    amount: 10,
    currency: 'USDT',
    status: 'ok',
    updated: 1667543431000,
    fee: { cost: 0, currency: 'USDT' }
  }
]
```

Can we reproduce the same scenario but via CCXT ?

Thank you

**Comment by sc0Vu** [comment]
Hi @danieltorscho 

Did you try `withdraw ('USDT', amount, email)`? I didn't see this in there documentation (https://bybit-exchange.github.io/docs/account_asset/v1/#t-withdraw_info), not sure whether it work.

**Comment by danieltorscho** [comment]
> Hi @danieltorscho
> 
> Did you try `withdraw ('USDT', amount, email)`? I didn't see this in there documentation (https://bybit-exchange.github.io/docs/account_asset/v1/#t-withdraw_info), not sure whether it work.

Yes, sure, it didn't work either. Someone from the chat group confirmed that it's still under the development, so I will close this issue. Thank you for your informations. 🙏
