### ISSUE TITLE
AuthenticationError: kucoin KC-API-KEY not exists  

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#15629]
Hello, sadly I have another Issue again. 
I created API KEY at FUTURES API on Kucoin.

I created new API Keys several times. But always the same issue. 

- OS: Windows 10
- Programming Language version: Python Spyder 3.9
- CCXT version: 2.1.13

```
import ccxt
import pandas as pd
import numpy as np

kucoin = ccxt.kucoin({'enableRateLimit': True,
                       'apiKey': my_api_key,
                       'secret': my_api_secret,
                       'password' : 'my PW',
                       })


symbol = 'ETH/USDT'

ob = kucoin.fetch_order_book(symbol)
print(ob)

```
HTTPError: 401 Client Error: Unauthorized for url: https://api.kucoin.com/api/v3/market/orderbook/level2?symbol=ETH-USDT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\dell\desktop\bybit\kucointest.py", line 55, in <module>
    ob = kucoin.fetch_order_book(symbol)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\kucoin.py", line 1169, in fetch_order_book
    response = getattr(self, method)(self.extend(request, params))

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2618, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2615, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\kucoin.py", line 3063, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2888, in throw_exactly_matched_exception
    raise exact[string](message)

AuthenticationError: kucoin KC-API-KEY not exists

**Comment by carlosmiei** [comment]
Hello @Nitrix321, since you handling derivatives can you try to instantiate `kucoinfutures` instead?

**Comment by Nitrix321** [comment]
Thank u again for your support :)  @carlosmiel

kucoin = ccxt.kucoinfutures({'enableRateLimit': True,
                       'apiKey': ---------,
                       'secret': -----------,
                       'password' : '--------',
                       })

symbol = 'ETH/USDT:USDT'

ob = kucoin.fetch_order_book(symbol)
print(ob)

now its working :)

**Comment by carlosmiei** [comment]
@Nitrix321 no problem 🙂 
I'll close this issue feel free to re-open it if needed!
