### ISSUE TITLE
load_markets error on pro 

### ISSUE THREAD

**Issue by myehrajat** [ccxt/ccxt#15640]
async function  yy(){
    const kucoinExtra =   new ccxt.pro.kucoin();
    const markets =   await kucoinExtra.load_markets();
    console.log(markets);
}
yy()

this code to load market by pro cause an error!!!!!!!!!!!!!!!!!!

D:\nodejs\MyProject2\node_modules\ccxt\js\base\Exchange.js:658
        return new Promise ((resolve, reject) => resolve (Object.values (this.markets)))
                                                                 ^

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at D:\nodejs\MyProject2\node_modules\ccxt\js\base\Exchange.js:658:66
    at new Promise (<anonymous>)
    at kucoin.fetchMarkets (D:\nodejs\MyProject2\node_modules\ccxt\js\base\Exchange.js:658:16)
    at kucoin.loadMarketsHelper (D:\nodejs\MyProject2\node_modules\ccxt\js\base\Exchange.js:626:36)
    at kucoin.loadMarkets (D:\nodejs\MyProject2\node_modules\ccxt\js\base\Exchange.js:634:40)
    at yy (D:\nodejs\MyProject2\app.js:14:41)
    at Object.<anonymous> (D:\nodejs\MyProject2\app.js:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by carlosmiei** [comment]
Hello @myehrajat I just tested and seems to be working fine on my end, can you share with us a verbose log, please?

**Comment by ttodua** [comment]
stale issue, closed.
let us know if anyone sees any issue
