### ISSUE TITLE
Binance options API returning "Invalid data sent for a parameter"

### ISSUE THREAD

**Issue by shep-analytics** [ccxt/ccxt#15659]
- OS: linux
- Programming Language version: python 3.9
- CCXT version: 2.21

All of the binance options requests are returning the same issue for me:

```
b = ccxt.binance(keys)
acct = b.eapiPrivateGetAccount()
```

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://eapi.binance.com/eapi/v1/account?timestamp=1668300116474&recvWindow=10000&signature=<my-signature>

ccxt.base.errors.BadRequest: binance {"code":-1130,"msg":"Invalid data sent for a parameter."}
```

Thank you for the help

**Comment by shep-analytics** [comment]
@sc0Vu is this an error on CCXT's side?

**Comment by sc0Vu** [comment]
Hi @shep-analytics 

That's weird. Can you call other european option account routes, eg, `eapiPrivateGetPosition`?

**Comment by shep-analytics** [comment]
@sc0Vu I just tried it, I get the same error - everything else works great for futures and spot. Is it possible that I need to initialize a binanceoptions object? instead of ccxt.binance?

**Comment by shep-analytics** [comment]
it says invalid data sent for a parameter - I don't understand though.

The only info we are passing for a parameter is "timestamp recvWindow signature"

right?

**Comment by sc0Vu** [comment]
@shep-analytics You don't have to create another instance for binanceoptions.

**Comment by shep-analytics** [comment]
> @shep-analytics You don't have to create another instance for binanceoptions.

does my code to call b.eapiPrivateGetAccount() work for you?

**Comment by sc0Vu** [comment]
@shep-analytics it worked for me

```
$ node examples/js/cli binance eapiPrivateGetAccount
2022-11-15T02:34:46.277Z
Node.js: v14.16.0
CCXT v2.1.80
binance.eapiPrivateGetAccount ()
{ asset: [], time: '1668479687482' }
```

**Comment by shep-analytics** [comment]
> @shep-analytics it worked for me
> 
> ```
> $ node examples/js/cli binance eapiPrivateGetAccount
> 2022-11-15T02:34:46.277Z
> Node.js: v14.16.0
> CCXT v2.1.80
> binance.eapiPrivateGetAccount ()
> { asset: [], time: '1668479687482' }
> ```

I'm using python, would that make any difference?

**Comment by sc0Vu** [comment]
@shep-analytics it worked for me too.

```
$ python3 examples/py/cli.py binance eapiPrivateGetAccount
Python v3.10.7
CCXT v2.1.69
binance.eapiPrivateGetAccount()
{'asset': [], 'time': '1668487424872'}
```

**Comment by shep-analytics** [comment]
Here is my full code with initialization and everything:

```
	import ccxt
	key =  {
	                                                        "apiKey": 'key',
	                                                        "secret": 'secret',
	                                                        'options': {
	                                                        'adjustForTimeDifference': True
	                                                        },
	                                                        'enableRateLimit': True
	                                                        }



	b = ccxt.binance(key)
	acct = b.eapiPrivateGetAccount()
	print(acct)
```
Maybe I'm setting up the key for ccxt incorrectly?

**Comment by kroitor** [comment]
@shep-analytics please, paste your verbose output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
key =  {
    "apiKey": 'key',
    "secret": 'secret',
    'options': {
        'adjustForTimeDifference': True
    },
    'enableRateLimit': True
}

b = ccxt.binance(key)
b.load_markets()
b.verbose = True
acct = b.eapiPrivateGetAccount()
print(acct)
```

**Comment by shep-analytics** [comment]
> @shep-analytics please, paste your verbose output:
> 
>     * https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
> 
> 
> ```python
> import ccxt
> print('CCXT Version:', ccxt.__version__)
> key =  {
>     "apiKey": 'key',
>     "secret": 'secret',
>     'options': {
>         'adjustForTimeDifference': True
>     },
>     'enableRateLimit': True
> }
> 
> b = ccxt.binance(key)
> b.load_markets()
> b.verbose = True
> acct = b.eapiPrivateGetAccount()
> print(acct)
> ```

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://eapi.binance.com/eapi/v1/account?timestamp=1668497947623&recvWindow=10000&signature=<mysignature>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 85, in <module>
    get_account_info()
  File "test.py", line 81, in get_account_info
    acct = b.eapiPrivateGetAccount()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/binance.py", line 5583, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2617, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/binance.py", line 5561, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2890, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1130,"msg":"Invalid data sent for a parameter."}
```

**Comment by Dan-krm** [comment]
@shep-analytics can you sign into Binance and make sure the options account is enabled?

**Comment by shep-analytics** [comment]
Solved, it seems that binance has an options api issue where you can only use keys generated after the enabling of your options account
