### ISSUE TITLE
ccxt.base.errors.ArgumentsRequired: binance fetchOrder() requires a symbol argument

### ISSUE THREAD

**Issue by abdellah9** [ccxt/ccxt#15652]
I running this python code and i get this error tired to solve this
OS: win7
Programming Language version: Python 3.8
CCXT version: 2.0.12

Issue
```
Traceback (most recent call last):
  File "gridbot.py", line 34, in <module>
    order = exchange.fetch_order(buy_order['orderId'])
  File "C:\Users\t\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\binance.py", line 2993, in fetch_order
    raise ArgumentsRequired(self.id + ' fetchOrder() requires a symbol argument')
ccxt.base.errors.ArgumentsRequired: binance fetchOrder() requires a symbol argument```


Code python
`import ccxt, config, time, sys

exchange = ccxt.binance({
    'apiKey': config.API_KEY,
    'secret': config.SECRET_KEY
})

ticker = exchange.fetch_ticker(config.SYMBOL)

buy_orders = []
sell_orders = []

# initial_buy_order = exchange.create_market_buy_order(config.SYMBOL, config.POSITION_SIZE * config.NUM_SELL_GRID_LINES)

for i in range(config.NUM_BUY_GRID_LINES):
    price = ticker['bid'] - (config.GRID_SIZE * (i+1))
    print("submitting market limit buy order at {}".format(price))
    order = exchange.create_limit_buy_order(config.SYMBOL, config.POSITION_SIZE, price)
    buy_orders.append(order['info'])

# for i in range(config.NUM_SELL_GRID_LINES):
    # price = ticker['bid'] + (config.GRID_SIZE * (i+1))
    # print("submitting market limit sell order at {}".format(price))
    # order = exchange.create_limit_sell_order(config.SYMBOL, config.POSITION_SIZE, price)
    # sell_orders.append(order['info'])

while True:
    closed_order_ids = []

    for buy_order in buy_orders:
        print("checking buy order {}".format(buy_order['orderId']))
        order = exchange.fetch_order(buy_order['orderId'])
           
        order_info = order['info']

        if order_info['status'] == config.CLOSED_ORDER_STATUS:
            closed_order_ids.append(order_info['id'])
            print("buy order executed at {}".format(order_info['price']))
            new_sell_price = float(order_info['price']) + config.GRID_SIZE
            print("creating new limit sell order at {}".format(new_sell_price))
            new_sell_order = exchange.create_limit_sell_order(config.SYMBOL, config.POSITION_SIZE, new_sell_price)
            sell_orders.append(new_sell_order)

        time.sleep(config.CHECK_ORDERS_FREQUENCY)`

**Comment by pcriadoperez** [comment]
Hi @abdellah9 ,
In binance the method `fetch_order` requires a symbol argument.
You can fix this in your code by changing:
 From: `order = exchange.fetch_order(buy_order['orderId'])` To: `order = exchange.fetch_order(buy_order['orderId'], config.SYMBOL)`
 
For now I'll close this issue, but feel free to ask any more questions.
