### ISSUE TITLE
Failed build on new setup

### ISSUE THREAD

**Issue by ccxdev** [ccxt/ccxt#15693]
I have following output after runing `npm run build` inside docker container.

Steps:
- Install docker
- Clone repo
- run `docker-compose run --rm ccxt`
- run `npm run build` when container started

- OS: MacOS Ventura 13.0
- Docker version: Latest
- CCXT version: Latest

```
PHP Fatal error:  Uncaught Error: Class "React\Promise\Deferred" not found in /ccxt/php/pro/Future.php:8
```

```
Stack trace:
#0 /ccxt/ccxt.php(128): require_once()
#1 /ccxt/php/test/syntax.php(18): include_once('...')
#2 {main}
  thrown in /ccxt/php/pro/Future.php on line 8
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! ccxt@2.1.80 check-rest-php-syntax: `php -f php/test/syntax.php`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the ccxt@2.1.80 check-rest-php-syntax script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-15T08_31_50_900Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! ccxt@2.1.80 check-php-syntax: `npm run check-rest-php-syntax && npm run check-ws-php-syntax`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the ccxt@2.1.80 check-php-syntax script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-15T08_31_50_912Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! ccxt@2.1.80 post-transpile: `npm run check-python-syntax && npm run check-php-syntax`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the ccxt@2.1.80 post-transpile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-15T08_31_50_926Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! ccxt@2.1.80 build: `npm run pre-transpile && npm run transpile && npm run post-transpile && npm run update-badges`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the ccxt@2.1.80 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-15T08_31_50_941Z-debug.log
```

**Comment by carlosmiei** [comment]
Hello @ccxdev, can you try to run `composer update` before the `npm run build` ?

**Comment by ccxdev** [comment]
After `composer update` it work perfectly. Thanks! @carlosmiei
