### ISSUE TITLE
Failed to locate the coins to borrow only when it is done in group

### ISSUE THREAD

**Issue by ddplaycoin** [ccxt/ccxt#15753]
i try to create a dataframe containing price, funding rate and interest rate of a list of symbols with below code.

the code works with each individual coin when only one coin is in the list each time.  It also works when I put them in pair so the dataframe contain the information of two symbols.  However, when I do it with three of more symbols or when the entire list of 10 symbols, it gives below error code: 

```
Traceback (most recent call last):
  File "C:/Users/dicky/PycharmProjects/Production/get_data_interest_funding_rate_bybit.py", line 130, in <module>
    df    = bybit_download_price_funding_interest_realtime(bybit_list, save_path)
  File "C:/Users/dicky/PycharmProjects/Production/get_data_interest_funding_rate_bybit.py", line 105, in bybit_download_price_funding_interest_realtime
    df = bybit_fetch_price_funding_interest_realtime(coin_id)
  File "C:/Users/dicky/PycharmProjects/Production/get_data_interest_funding_rate_bybit.py", line 51, in bybit_fetch_price_funding_interest_realtime
    interest       = exchange_spot.fetchBorrowRate(coin_id, params={})['info']
  File "C:\Users\dicky\PycharmProjects\Production\lib\site-packages\ccxt\bybit.py", line 5176, in fetch_borrow_rate
    response = self.privateGetSpotV3PrivateCrossMarginLoanInfo(self.extend(request, params))
  File "C:\Users\dicky\PycharmProjects\Production\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\dicky\PycharmProjects\Production\lib\site-packages\ccxt\base\exchange.py", line 2620, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\dicky\PycharmProjects\Production\lib\site-packages\ccxt\base\exchange.py", line 2617, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\dicky\PycharmProjects\Production\lib\site-packages\ccxt\base\exchange.py", line 662, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\dicky\PycharmProjects\Production\lib\site-packages\ccxt\bybit.py", line 5650, in handle_errors
    raise ExchangeError(feedback)  # unknown message
**ccxt.base.errors.ExchangeError: bybit {"retCode":12610,"retMsg":"Failed to locate the coins to borrow","result":{},"retExtInfo":{},"time":1668969989553}**

Process finished with exit code 1
```

it seems to be weird when the code works when each symbol is done individually but it 'Failed to locate the coins to borrow' when it is done in group.

Grateful for your advice please.

```
bybit_list  = ['SLP', 'HOT', 'DOGE', 'GALA', 'XRP', 'ZIL', 'TRX', 'CHZ', 'GMT', 'ADA']

def bybit_fetch_price_funding_interest_realtime(coin_id):

    exchange_spot = ccxt.bybit({
        'apiKey': bybit_ddplaycoin_api,
        'secret': bybit_ddplaycoin_secret,
    })
    exchange_spot.options['defaultType'] = 'spot'

    exchange_linear = ccxt.bybit({
        'apiKey': bybit_ddplaycoin_api,
        'secret': bybit_ddplaycoin_secret,
    })

    tickers_linear = exchange_linear.fetchTicker(coin_id + 'USDT')['info']
    tickers_spot   = exchange_spot.fetchTicker(coin_id + 'USDT')['info']
    interest       = exchange_spot.fetchBorrowRate(coin_id, params={})['info']

    df_linear      = pd.DataFrame.from_dict([tickers_linear])
    df_spot        = pd.DataFrame.from_dict([tickers_spot])
    df_interest    = pd.DataFrame.from_dict([interest])

    df_linear.columns     = coin_id + 'USDT_linear_' + df_linear.columns
    df_spot.columns       = coin_id + 'USDT_' + df_spot.columns
    df_interest.columns   = coin_id + '_' + df_interest.columns

    df_linear['data_time'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    df_spot['data_time'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    df_interest['data_time'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    df_linear   = df_linear.set_index('data_time')
    df_spot     = df_spot.set_index('data_time')
    df_interest = df_interest.set_index('data_time')

    df = pd.merge(df_linear, df_spot, how='left', left_index=True, right_index=True)
    df = pd.merge(df, df_interest, how='left', left_index=True, right_index=True)

    # df = df.set_index('data_time')

    df = df[[coin_id + 'USDT_linear_bid_price', coin_id + 'USDT_linear_ask_price', coin_id + 'USDT_linear_last_price', coin_id + 'USDT_linear_funding_rate', coin_id + 'USDT_linear_next_funding_time', coin_id + 'USDT_lp', coin_id + 'USDT_bp', coin_id + 'USDT_ap', coin_id + '_interestRate']]

    df.rename(columns={coin_id + 'USDT_bp': coin_id + 'USDT_spot_bid_price', coin_id + 'USDT_ap': coin_id + 'USDT_spot_ask_price', coin_id + 'USDT_lp': coin_id + 'USDT_spot_last_price'}, inplace=True)

    return df

def bybit_download_price_funding_interest_realtime(bybit_list, save_path):
    first_coin_id = bybit_list[0]
    df_init = bybit_fetch_price_funding_interest_realtime(first_coin_id)

    merged_df: pd.DataFrame = pd.DataFrame(index=df_init.index)

    for coin_id in bybit_list:
        logger.info('fetch price, funding, interest data, id={}', coin_id)
        df = bybit_fetch_price_funding_interest_realtime(coin_id)

        time.sleep(1.3)

        merged_df = pd.merge(merged_df, df, how='left', left_index=True, right_index=True)

    merged_df = merged_df.dropna()

    return merged_df
```

**Comment by ttodua** [comment]
late reply, but bybit API had been updated since then.
If anyone still experiences any issues, let us kno
