### ISSUE TITLE
[bug] Unable to fetch currencies from Bybit

### ISSUE THREAD

**Issue by holinov** [ccxt/ccxt#15788]
- OS: ubuntu 20.04 LST
- Programming Language version: python 3.8
- CCXT version: 2.2.7

```py
import ccxt
print(ccxt.__version__)
exc = ccxt.bybit({
    'apiKey': '--KEY--',
    'secret': '--SECRET--',
})
print(exc.fetch_currencies())
```

```
2.2.7
Traceback (most recent call last):
  File "/home/user/src/experiments/src/bots/freqtrade/ccxt_tes.py", line 65, in <module>
    print(exc.fetch_currencies())
  File "/home/user/.miniconda/envs/tvoyfrut/lib/python3.8/site-packages/ccxt/bybit.py", line 740, in fetch_currencies
    response = self.privateGetAssetV3PrivateCoinInfoQuery(params)
  File "/home/user/.miniconda/envs/tvoyfrut/lib/python3.8/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/user/.miniconda/envs/tvoyfrut/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2637, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/user/.miniconda/envs/tvoyfrut/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2634, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/user/.miniconda/envs/tvoyfrut/lib/python3.8/site-packages/ccxt/base/exchange.py", line 662, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/user/.miniconda/envs/tvoyfrut/lib/python3.8/site-packages/ccxt/bybit.py", line 5649, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/user/.miniconda/envs/tvoyfrut/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2907, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: bybit {"retCode":10002,"retMsg":"invalid request, please check your server timestamp or recv_window param","result":null,"retExtInfo":{},"time":1669128032906}
```

**Comment by carlosmiei** [comment]
Hello @holinov,
This is not an issue with `fetchCurrencies` per se, but a sign that your clock might be out of sync.
Please check out this thread: https://github.com/ccxt/ccxt/issues/14870

**Comment by holinov** [comment]
Thx. This helped
