### ISSUE TITLE
Bibox fetch_tickers() should be updated to v3?

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#15859]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 2.2.36

```
exchange = ccxt.bibox()
exchange.fetch_tickers()
```

```
Traceback (most recent call last):
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/home/xyz/.local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.bibox.com/v1/mdata?cmd=marketAll

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xyz/test.py", line 4, in <module>
    exchange.fetch_tickers()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bibox.py", line 582, in fetch_tickers
    response = self.v1PublicGetMdata(self.extend(request, params))
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2690, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2687, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 638, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1724, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: bibox GET https://api.bibox.com/v1/mdata?cmd=marketAll 503 Service Unavailable 
```

Bibox `fetch_tickers` has been working very unreliably for a couple of days now. Most of the times it doesn't manage to fetch anything, but occasionally it does. Going directly to the api url gives the same result: https://api.bibox.com/v1/mdata?cmd=marketAll

v3 version of this endpoint does seem to be available and working much more reliably at least at this moment:
https://biboxcom.github.io/v3/spot/en/#query-market-of-all-pairs
https://api.bibox.com/v3/mdata/marketAll

If there is no good reason to hold back, perhaps now would be a good time to update `fetch_tickers` to use v3 endpoint instead of v1?

**Comment by ndubel** [comment]
the similar issue for me for `fetchCurrenciesPrivate`
`RequestTimeout: bibox POST https://api.bibox.com/v1/transfer request timed out (30000 ms)`

**Comment by carlosmiei** [comment]
Hello @ndubel  @JovianMoon sure we will upgrade it asap. FYI: @samgermain
