### ISSUE TITLE
Connection Error??

### ISSUE THREAD

**Issue by janstrw13** [ccxt/ccxt#15882]
I run my trading bot 24/7 and started it yesterday now it gets this error: 

Traceback (most recent call last):
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.bybit.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 594, in fetch
    response = self.session.request(
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.bybit.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 173, in <module>
    cur = exchange.fetch_ticker(symbol)
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/ccxt/bybit.py", line 1459, in fetch_ticker
    response = getattr(self, method)(self.extend(request, params))
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2718, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2715, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/runner/HedgeBot/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 624, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: bybit GET https://api.bybit.com/v2/public/tickers?symbol=BTCUSDT

Is this a connection timeout error? U know something to fix it? I let it run on repl.it

**Comment by carlosmiei** [comment]
Hello @janstrw13 the error does not seem related to ccxt itself but the network, so I'd suggest double-checking that.

**Comment by janstrw13** [comment]
> Hello @janstrw13 the error does not seem related to ccxt itself but the network, so I'd suggest double-checking that.

So maybe there are problems from repl.it server? Thank you!

**Comment by ttodua** [comment]
topic closed.
