### ISSUE TITLE
BadSymbol: binance does not have market symbol BTC/USDT

### ISSUE THREAD

**Issue by ChenLi0830** [ccxt/ccxt#15889]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3.

- OS: Linux
- Programming Language version: NodeJS
- CCXT version: 2.2.45

```
const ccxt = require("ccxt");

async function test() {
  const exchange = new ccxt["binance"]();

  const fetchSince = Date.now() - 5 * 60 * 1000;

  const result = await exchange.fetchOHLCV("BTC/USDT", "1m", fetchSince, 5);
  console.log("result", result);
}

test();
```

```
BadSymbol: binance does not have market symbol BTC/USDT
    at binance.market (/DeepTrade_keras/nodeScripts/temp/node_modules/ccxt/js/base/Exchange.js:2437:15)
    at binance.fetchOHLCV (/DeepTrade_keras/nodeScripts/temp/node_modules/ccxt/js/binance.js:2472:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async test (/DeepTrade_keras/nodeScripts/temp/test.js:8:18) {
  constructor: [class BadSymbol extends BadRequest]
}

```

**Comment by carlosmiei** [comment]
Hello @ChenLi0830 can you please provide a verbose log? `exchang.verbose=true` ?

**Comment by ChenLi0830** [comment]
```
root@pred:/DeepTrade_keras/nodeScripts/temp# node test.js 
fetch Request:
 binance GET https://api.binance.com/api/v3/exchangeInfo 
RequestHeaders:
 {} 
RequestBody:
 undefined 

handleRestResponse:
 binance GET https://api.binance.com/api/v3/exchangeInfo 451 Unavailable For Legal Reasons 
ResponseHeaders:
 {
  Connection: 'keep-alive',
  'Content-Length': '224',
  'Content-Type': 'application/json',
  Date: 'Wed, 30 Nov 2022 14:57:49 GMT',
  Server: 'CloudFront',
  Via: '1.1 e9c8cd6cad69627cb7c9d88123e6e2cc.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'IDgfDTwWvtqAJZsUKQA5mUrPNOFTnlCRFwC8SH6uUZhPf6dQwyf-Ew==',
  'X-Amz-Cf-Pop': 'HIO50-C2',
  'X-Cache': 'Error from cloudfront'
} 
ResponseBody:
 {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
} 

/DeepTrade_keras/nodeScripts/temp/node_modules/ccxt/js/base/Exchange.js:2437
        throw new BadSymbol (this.id + ' does not have market symbol ' + symbol);
              ^

BadSymbol: binance does not have market symbol BTC/USDT
    at binance.market (/DeepTrade_keras/nodeScripts/temp/node_modules/ccxt/js/base/Exchange.js:2437:15)
    at binance.fetchOHLCV (/DeepTrade_keras/nodeScripts/temp/node_modules/ccxt/js/binance.js:2472:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async test (/DeepTrade_keras/nodeScripts/temp/test.js:8:18) {
  constructor: [class BadSymbol extends BadRequest]
}
```
Oh, I see. This might be caused by the fact that my code is running in the us-west-2 region, but Binance has stopped be available for the US.

**Comment by carlosmiei** [comment]
@ChenLi0830 exactly,  We were also impacted by this, and yeah was a recent change from Binance. Basically, you will need to reallocate the instance or route the requests out of the US using a proxy

**Comment by ChenLi0830** [comment]
Thanks that makes sense. I am closing this issue since the root cause is not from ccxt. You might want to consider using a more explicit error message though. Thanks for the good work.

**Comment by AdolfoVillalobos** [comment]
Hello to everyone. I'm having a similar problem with the binance api (my code also runs on a US based cluster). I haven't been able to find any official source

> @ChenLi0830 exactly, We were also impacted by this, and yeah was a recent change from Binance. Basically, you will need to reallocate the instance or route the requests out of the US using a proxy

Hello to everyone. Do you have any official source for this event? I experimenting a similar problem in my USA-based cluster, and haven't been able to find any official statement. I would greatly appreciate it if you could share it. Thanks!

**Comment by gldstrrbt** [comment]
Any workaround for client side other than connecting my device to a vpn/proxy or is serverside the only solution?
