### ISSUE TITLE
Gemini calls resulting in ExchangeNotAvailable error

### ISSUE THREAD

**Issue by mariaimcoding** [ccxt/ccxt#15890]
- OS: Mac OS
- Programming Language version: NodeJS
- CCXT version: 2.2.45

The following code:
```
const exchangeClass = ccxt['gemini'],
          exchange = new exchangeClass({
            apiKey: process.env[`GEMINI_API_KEY`]!,
            secret: process.env[`GEMINI_SECRET`]!,
          });

let ticker = await exchange.fetchTicker(`ETH/USD`);

```
Produces the following error:

```
ExchangeNotAvailable: gemini GET https://docs.gemini.com/rest-api  fetch failed
     at /app/node_modules/ccxt/js/base/Exchange.js:429:35
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
     at timeout (/app/node_modules/ccxt/js/base/functions/time.js:181:20)
     at gemini.fetch2 (/app/node_modules/ccxt/js/base/Exchange.js:1919:16)
     at gemini.request (/app/node_modules/ccxt/js/base/Exchange.js:1923:16)
     at gemini.fetchMarketsFromWeb (/app/node_modules/ccxt/js/gemini.js:274:26)
     at gemini.fetchMarkets (/app/node_modules/ccxt/js/gemini.js:270:16)
     at gemini.loadMarketsHelper (/app/node_modules/ccxt/js/base/Exchange.js:626:25)
     at gemini.fetchTickerV1 (/app/node_modules/ccxt/js/gemini.js:468:9)
     at gemini.fetchTicker (/app/node_modules/ccxt/js/gemini.js:536:16) {
   constructor: [class ExchangeNotAvailable extends NetworkError]
 }
```
The Gemini status page shows the REST API is operational. Not sure what the issue could be. Appreciate any help.

**Comment by carlosmiei** [comment]
Hello @mariaimcoding 
Can you try to change how markets are fetched to see if solves the issue, please?

Example:
```Javascript
exchange.options["fetchMarketsMethod"] = "fetch_markets_from_api"
let ticker = await exchange.fetchTicker(`ETH/USD`);
```

**Comment by carlosmiei** [comment]
fyi: @pcriadoperez

**Comment by mariaimcoding** [comment]
@carlosmiei Thanks a ton for the help, that solved the issue.
