### ISSUE TITLE
binance does not have market symbol BTC/AUD

### ISSUE THREAD

**Issue by gmkbenjamin** [ccxt/ccxt#15896]
- OS: Debian/Windows
- Programming Language version: Python 3.10.8
- CCXT version: 2.2.46

```
exchange = exchange_class({
    'apiKey': binance_apikey,
    'secret': binance_apisecret,
    'options': {'defaultType': 'spot' },
})
exchange.fetchOpenOrders('BTC/AUD')
```

```
Traceback (most recent call last):
  File "g:\My Drive\gridbotccxt.py", line 111, in <module>
    exchange.fetchOpenOrders('BTC/AUD')
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\binance.py", line 3130, in fetch_open_orders
    market = self.market(symbol)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 3012, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: binance does not have market symbol BTC/AUD
```

**Comment by sc0Vu** [comment]
uh, I didn't find it in binance web. Would you like to explain this more?

**Comment by gmkbenjamin** [comment]
> @gmkbenjamin
> 
> uh, I didn't find it in binance web. Would you like to explain this more?

That's odd, should be available on Binance international (non-US) 
Here's a link to it https://www.binance.com/en/trade/BTC_AUD?_from=markets&theme=dark&type=spot

**Comment by frosty00** [comment]
```
handleRestResponse:
 binance GET https://api.binance.com/api/v3/openOrders?timestamp=1669884770939&symbol=BTCAUD&recvWindow=10000&signature=___ 200 OK 
ResponseHeaders:
 {
  'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'close',
  'Content-Length': '2',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Thu, 01 Dec 2022 08:52:52 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  Via: '1.1 00f66bc6263192200d1a0cdb83e969f8.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': '671Lu3pPV-8ooXG8QoYjYCUOQxzo59oUN381A2yZ-SFQKbGtvRNAgQ==',
  'X-Amz-Cf-Pop': 'AMS1-P1',
  'X-Cache': 'Miss from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Mbx-Used-Weight': '39',
  'X-Mbx-Used-Weight-1m': '39',
  'X-Mbx-Uuid': 'ad5c4654-e128-41ac-aa03-3a249d2fcd10',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
} 
ResponseBody:
 [] 

[]
```

it works for me...

**Comment by frosty00** [comment]
the latest version...

**Comment by frosty00** [comment]
ah i found the bug in python, was using js, will investigate now

**Comment by frosty00** [comment]
i think it's probably due to #15891 if I had to guess

**Comment by gmkbenjamin** [comment]
> i think it's probably due to #15891 if I had to guess

I'm not so sure. I'm not in the U.S. It works for BTCBUSD just not BTCAUD.

**Comment by gmkbenjamin** [comment]
Found the problem. BTC/AUD pair is not available in sandbox mode (testnet). Closing issue.
