### ISSUE TITLE
ccxt.base.errors.ExchangeError: binance GET working local but not remote

### ISSUE THREAD

**Issue by dylan-carter** [ccxt/ccxt#15893]
I have been running a script for a number of months but all of a sudden last night my remote server is returning the following error when simply connecting to the exchange. Have tried replacing the API keys, creating a new EC2 instance with a different IP and googling the below error with no success!

When I run locally it works, remote does not so its something happening on the remote server.

For a simple test I'm just running the following command - locally it works and returns no errors however when trying to launch from my remote EC2 instance it does not work and returns the traceback error at the end of this note:

**_CODE RUNNING:_**

```
import ccxt

exchange = ccxt.binance({
        "apiKey": config.API_KEY,
        "secret": config.API_SECRET
})

exchange.load_markets()
exchange.verbose = True
```

**_ERROR TRACEBACK:_**

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 451 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1669847299345&recvWindow=10000&signature=XXXX [have removed signature for security]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/application.py", line 124, in <module>
    exchange.load_markets()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1446, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1340, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/binance.py", line 5629, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2717, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 639, in fetch
    raise ExchangeError(details) from e
ccxt.base.errors.ExchangeError: binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1669847299345&recvWindow=10000&signature=XXX [have removed signature for security]
```

**Comment by dylan-carter** [comment]
Resolution: the United States has become a restricted country for Binance API. Changing server location to a non-restricted country resolves the error.
