### ISSUE TITLE
(Unannounced publicly by Binance) Binance read-only public API endpoints are no longer available in the US / restricted locations

### ISSUE THREAD

**Issue by gldstrrbt** [ccxt/ccxt#15891]
Up until today, the Binance public read-only data API has been available for all to use and access. But now, any device not connected to a VPN / proxy server outside of restricted areas is getting 451 errors.

The customer service rep I spoke with assured me that they (Binance) put in their "best efforts" to notify those who would be affected by this cut off of their read-only data endpoints... by email. Email? Really? They're surely aware that many devs from all over the world (restricted and non-restricted alike) make use of the read-only API endpoints that they've provided up until today. They're also likely aware that many folks have products (charting/analytics/etc) which rely on this read-only data they provide, considering they're one of, if not THE, top exchange(s) in the world, meaning their data paints a better picture of global trading activity.

Binance should have been responsible and should have given all devs a heads up through a public announcement, stating how they're cutting off their access to their read-only data in "restricted" locations, such as the US. It makes zero sense why they would pull this, especially considering that this read-only data is still accessible for all to read around the world through the tables and advanced charts provided on their core website... just not through their public API.

The customer service rep insisted that I use the Binance US API, but again, the previously publicly available read-only data provided by the main Binance is much more robust and paints a clearer picture of international trading activity, and doesn't limit devs to data from one region. They also insisted that I create a ticket speaking to this, knowing that it would require me to create a Binance account... which I'm restricted from doing.

So after being fed up with all the corporate speak, mental gymnastics, and gaslighting the rep pulled, I decided to write here in hopes of letting those using the API in the US and other now restricted areas, know that their access to the core read-only Binance public API has been cutoff as of today. Also wrote this in hopes of catching any of the Binance dev's attention and maybe reversing this cutoff or at least encourage their team to reverse the decision should they have any actual in this.

Yes, a proxy server / VPN can be connected to in a non-restricted area to side step this, but for those (such as myself) in situations where their project or product is purely client side, this is negatively affecting my livelihood/progression of my business/offerings.

**Comment by tkddlf4209** [comment]
There was a problem that the price of Binance ticker could not be retrieved from the server in the US region. Thanks for sharing information. I plan to use a proxy server for now.

**Comment by tkddlf4209** [comment]
I am using heroku us server and the server's region was the United States.

Solved the problem through proxy settings.

>>>>>>>>>>>>>>>>>>>>>>>

let ccxt = require ('ccxt')
HttpsProxyAgent = require ('https-proxy-agent')
const proxy = "http://{username}:{password}@{IP}:{PORT}"
const agent = new HttpsProxyAgent (proxy)

let binance = new ccxt.binance({agent});

>>>>>>>>>>>>>>>>>>>>>>>

**Comment by frosty00** [comment]
there's no free category for heroku anymore

**Comment by samgermain** [comment]
> Oh thought Heroku went under. Didn't know they got acquired though. Interesting.
> 
> Trying to keep it on the client side but worst case may have to resort to this or a similar solution. Thanks for the tip

I haven't checked on this in a while, but I created [instructions on how to set up freqtrade (which uses ccxt) on an AWS server](https://github.com/samgermain/freqtrade-ec2-instructions) if that's useful to you

**Comment by frosty00** [comment]
#15872

**Comment by businessengine** [comment]
> 



> let ccxt = require ('ccxt') HttpsProxyAgent = require ('https-proxy-agent') const proxy = "http://{username}:{password}@{IP}:{PORT}" const agent = new HttpsProxyAgent (proxy)
> 
> let binance = new ccxt.binance({agent});

This doesn't work for me, can you please help?
Test code
```
let ccxt = require("../../ccxt");
const log = require("ololog").configure({ locate: false });
const HttpsProxyAgent = require('https-proxy-agent');

const proxy = "http://user:pass@hongkong.myproxyserver.xyz:1111"
const agent = new HttpsProxyAgent(proxy);

async function main() {
  console.log("CCXT Version: ", ccxt.version);
  
  const exchange = new ccxt.binanceusdm();
  exchange.agent = agent;
  let markets = await exchange.loadMarkets();
  console.log("Number of markets: " + Object.keys(markets).length);
}
main();
```

Result:
```
CCXT Version:  2.2.55
(node:33461) UnhandledPromiseRejectionWarning: ExchangeNotAvailable: binanceusdm GET https://fapi.binance.com/fapi/v1/exchangeInfo 403 Forbidden Forbidden

    at binanceusdm.handleHttpStatusCode (/Volumes/NDATA/HeroBot/Github/ccxt/js/base/Exchange.js:754:19)
    at /Volumes/NDATA/HeroBot/Github/ccxt/js/base/Exchange.js:601:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async timeout (/Volumes/NDATA/HeroBot/Github/ccxt/js/base/functions/time.js:181:20)
    at async binanceusdm.fetch2 (/Volumes/NDATA/HeroBot/Github/ccxt/js/base/Exchange.js:1967:16)
    at async binanceusdm.request (/Volumes/NDATA/HeroBot/Github/ccxt/js/binance.js:6054:26)
    at async binanceusdm.fetchMarkets (/Volumes/NDATA/HeroBot/Github/ccxt/js/binance.js:1508:26)
    at async binanceusdm.loadMarketsHelper (/Volumes/NDATA/HeroBot/Github/ccxt/js/base/Exchange.js:627:25)
    at async main (/Volumes/NDATA/HeroBot/Github/ccxt/examples/js/binance-fetch-trades-pagination.js:25:17)
```

**Comment by ttodua** [comment]
closing this topic.
let us know if anyone has any issues
