### ISSUE TITLE
Binance Error Loading Markets in fetchTickers()

### ISSUE THREAD

**Issue by SudheendraSoftionik** [ccxt/ccxt#15917]
Hi,
Getting below error please suggest what i need to change in my code 

Python = 3.8
CCXT = 2.2.50

**Code**

```
import ccxt
exchange = ccxt.binance()
#tickers = exchange.fetchTickers()
if (exchange.has['fetchTickers']):
    print(exchange.fetch_tickers())
```

**ERROR**

```
Traceback (most recent call last):
  File "/home/ubuntu/test/test_ccxt/test/lib/python3.8/site-packages/ccxt/base/exchange.py", line 621, in fetch
    response.raise_for_status()
  File "/home/ubuntu/test/test_ccxt/test/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 451 Client Error:  for url: https://api.binance.com/api/v3/exchangeInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    print(exchange.fetch_tickers())
  File "/home/ubuntu/test/test_ccxt/test/lib/python3.8/site-packages/ccxt/binance.py", line 2344, in fetch_tickers
    self.load_markets()
  File "/home/ubuntu/test/test_ccxt/test/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1448, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ubuntu/test/test_ccxt/test/lib/python3.8/site-packages/ccxt/binance.py", line 1507, in fetch_markets
    response = getattr(self, method)(query)
  File "/home/ubuntu/test/test_ccxt/test/lib/python3.8/site-packages/ccxt/base/exchange.py", line 501, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ubuntu/test/test_ccxt/test/lib/python3.8/site-packages/ccxt/binance.py", line 5629, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ubuntu/test/test_ccxt/test/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2756, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/test/test_ccxt/test/lib/python3.8/site-packages/ccxt/base/exchange.py", line 639, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/home/ubuntu/test/test_ccxt/test/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1741, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo 451  {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
```

**Comment by carlosmiei** [comment]
Hello @SudheendraSoftionik please check out this similar issue: https://github.com/ccxt/ccxt/issues/15891
