### ISSUE TITLE
OKX Error Loading Markets in fetchTickers()

### ISSUE THREAD

**Issue by drsavant-pub** [ccxt/ccxt#15916]
### Please note this was working in ccxt v2.0.90

- OS: win 8.1
- Programming Language version: nodejs v16.14.2
- CCXT version: 2.2.47

### Code:
```
let ccxt = require('ccxt')
let ex = new ccxt.okx({verbose: true})
let markets = [
  'AVAX/USDT',
  'DOT/USDT',
  'SOL/USDT',
  'TRX/USDT',
  'XLM/USDT',
  'XRP/USDT'
]

async function run(){
  ex.fetchTickers(markets).then( (results)=>{
    console.log(ex.name, `fetchTickers finished ts:`, Date.now() / 1000)
    console.log('results', results)
  })
}

run()
```

### Error:
```
D:\_dev\nodejs\cc-arbitration\OM\node_modules\ccxt\js\base\Exchange.js:2426
            throw new ExchangeError (this.id + ' markets not loaded');
                  ^

ExchangeError: okx markets not loaded
    at okx.market (D:\_dev\nodejs\cc-arbitration\OM\node_modules\ccxt\js\base\Exchange.js:2426:19)
    at okx.symbol (D:\_dev\nodejs\cc-arbitration\OM\node_modules\ccxt\js\base\Exchange.js:1887:29)
    at okx.marketSymbols (D:\_dev\nodejs\cc-arbitration\OM\node_modules\ccxt\js\base\Exchange.js:1549:31)
    at okx.fetchTickers (D:\_dev\nodejs\cc-arbitration\OM\node_modules\ccxt\js\okx.js:1454:24)
    at run (D:\_dev\nodejs\cc-arbitration\OM\lib\_tmp\tests\okx.error1.js:14:6)
    at Object.<anonymous> (D:\_dev\nodejs\cc-arbitration\OM\lib\_tmp\tests\okx.error1.js:20:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  constructor: [class ExchangeError extends BaseError]
}
```

**Comment by carlosmiei** [comment]
Hello @drsavant-pub, thanks for reporting it, will be fixed very soon!
