### ISSUE TITLE
aws ccxt error

### ISSUE THREAD

**Issue by seosms** [ccxt/ccxt#15924]
When I running "binance.fetch_ohlcv(Ticker, period)" this code to get the data of OHLCV, below message occurs on ubuntu server.
Does anyone know how to resolve it?
I use python language, my server is linux(ubuntu)
Actually when I run this code on local's IDE, that message never happen.

> Traceback (most recent call last):
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 621, in fetch
>     response.raise_for_status()
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1669975857061&recvWindow=10000&signature=621cf3af044013e1e26f12c90618a5ebae234bfee015301ced00b9cfd4cb4dee
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/autobot/sell.py", line 47, in <module>
>     df_ETH = myBinance.GetOhlcv(binanceX,ETH_Coin_Ticker, '30m')
>   File "/var/autobot/myBinance.py", line 202, in GetOhlcv
>     btc_ohlcv = binance.fetch_ohlcv(Ticker, period)
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/binance.py", line 2415, in fetch_ohlcv
>     self.load_markets()
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1447, in load_markets
>     currencies = self.fetch_currencies()
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1340, in fetch_currencies
>     response = self.sapiGetCapitalConfigGetall(params)
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 501, in inner
>     return entry(_self, **inner_kwargs)
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/binance.py", line 5629, in request
>     response = self.fetch2(path, api, method, params, headers, body, config, context)
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 2756, in fetch2
>     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 637, in fetch
>     skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/binance.py", line 5607, in handle_errors
>     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
>   File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 3042, in throw_exactly_matched_exception
>     raise exact[string](message)
> ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by carlosmiei** [comment]
Hello @seosms,

If you have the API keys for the exchange, ccxt will use them to load the currencies upon loading the markets, so even though you only called a public endpoint internally, ccxt made a private request. If you don't have valid keys, you can always remove them from the instance, letting ccxt infer the currencies using a different method.

Alternatively, you can double-check the validity of the keys.

**Comment by samgermain** [comment]
> When I running "binance.fetch_ohlcv(Ticker, period)" this code to get the data of OHLCV, below message occurs on ubuntu server. Does anyone know how to resolve it? I use python language, my server is linux(ubuntu) Actually when I run this code on local's IDE, that message never happen.
> 
> > Traceback (most recent call last):
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 621, in fetch
> > response.raise_for_status()
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
> > raise HTTPError(http_error_msg, response=self)
> > requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1669975857061&recvWindow=10000&signature=621cf3af044013e1e26f12c90618a5ebae234bfee015301ced00b9cfd4cb4dee
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/var/autobot/sell.py", line 47, in 
> > df_ETH = myBinance.GetOhlcv(binanceX,ETH_Coin_Ticker, '30m')
> > File "/var/autobot/myBinance.py", line 202, in GetOhlcv
> > btc_ohlcv = binance.fetch_ohlcv(Ticker, period)
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/binance.py", line 2415, in fetch_ohlcv
> > self.load_markets()
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1447, in load_markets
> > currencies = self.fetch_currencies()
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/binance.py", line 1340, in fetch_currencies
> > response = self.sapiGetCapitalConfigGetall(params)
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 501, in inner
> > return entry(_self, **inner_kwargs)
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/binance.py", line 5629, in request
> > response = self.fetch2(path, api, method, params, headers, body, config, context)
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 2756, in fetch2
> > return self.fetch(request['url'], request['method'], request['headers'], request['body'])
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 637, in fetch
> > skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/binance.py", line 5607, in handle_errors
> > self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
> > File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 3042, in throw_exactly_matched_exception
> > raise exact[string](message)
> > ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

Whats the location of your ec2 server? I think those at american ips won't work.

Also please provide your ccxt version, ubuntu version, and python version in the future, it will help if we need to recreate the environment to test this out

**Comment by ttodua** [comment]
closing the stale topic
