### ISSUE TITLE
Bitfinex2.py - handle_my_trade error

### ISSUE THREAD

**Issue by SiloDilo** [ccxt/ccxt#15942]
pro/bitfinex2.py
handle_my_trade is missing - subscription - parameter

- OS: Win
- Programming Language version: Python
- CCXT version: latest

```
def handle_my_trade(self, client, message):

```

```
Exception in callback FastClient.receive_loop.<locals>.handler() at C:\Users\A\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ccxt\pro\base\fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at C:\Users\A\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ccxt\pro\base\fast_client.py:20>
Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\A\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ccxt\pro\base\fast_client.py", line 25, in handler
    self.handle_message(message)
  File "C:\Users\A\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ccxt\pro\base\aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "C:\Users\A\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ccxt\pro\base\aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "C:\Users\A\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ccxt\pro\bitfinex2.py", line 1051, in handle_message
    return method(client, message, subscription)
TypeError: handle_my_trade() takes 3 positional arguments but 4 were given
```

**Comment by carlosmiei** [comment]
Hello @SiloDilo,
thanks for reporting it, will be fixed shortly!
