### ISSUE TITLE
I got this Error when Script wants to create a new Order. On Windows Client it works... on windows server dont

### ISSUE THREAD

**Issue by janstrw13** [ccxt/ccxt#15989]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Bybit_MA_Bot\HedgeBot with Market Orders2.py", line 144, in <module>
    order=exchange.create_order(symbol=symbol, type='market', side='sell', amount=Size, params={'leverage': 1})
  File "C:\Program Files (x86)\Thonny\lib\site-packages\ccxt\bybit.py", line 3336, in create_order
    return self.create_contract_v3_order(symbol, type, side, amount, price, params)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\ccxt\bybit.py", line 3561, in create_contract_v3_order
    response = self.privatePostContractV3PrivateOrderCreate(self.extend(request, params))
  File "C:\Program Files (x86)\Thonny\lib\site-packages\ccxt\base\exchange.py", line 501, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\ccxt\base\exchange.py", line 2759, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\ccxt\base\exchange.py", line 2756, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Program Files (x86)\Thonny\lib\site-packages\ccxt\base\exchange.py", line 663, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\ccxt\bybit.py", line 6749, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\ccxt\base\exchange.py", line 3042, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1670344578694}

**Comment by janstrw13** [comment]
Hey  @carlosmiei just in all my createorder params?

**Comment by janstrw13** [comment]
order=exchange.create_order(symbol=symbol, type='market', side='buy', amount=Size, params={'leverage': 1, positionIdx = 1})

Like this?

**Comment by carlosmiei** [comment]
@janstrw13 You just need to find the correct value for `positionIdx`
Check this:
![image](https://user-images.githubusercontent.com/43336371/205982472-d0e8eb46-99d0-41a3-8d36-59e16d12851f.png)

**Comment by janstrw13** [comment]
> @janstrw13 You just need to find the correct value for `positionIdx` Check this: ![image](https://user-images.githubusercontent.com/43336371/205982472-d0e8eb46-99d0-41a3-8d36-59e16d12851f.png)

0/1/2 does not work...

**Comment by ttodua** [comment]
late reply here, but bybit was updated since then, there should not be that problem anymore.
let us know if any issues
