### ISSUE TITLE
AssertionError: decimal_to_precision.py: assert(isinstance(precision, numbers.Integral))

### ISSUE THREAD

**Issue by majal** [ccxt/ccxt#16000]
- OS: Ubuntu 22.04
- Programming Language version: Python
- CCXT version: 2.2.79

This bug was not there before, script ran fine for months. So it looks like a regression error. Errors on two codes below:

(1)
```
exchange.sapi_post_futures_transfer({ 'asset': currency['id'], 'amount': exchange.currency_to_precision(code, amount), 'type': 2 })
```

(2)
```
exchange.transfer(code, amount, 'future', 'spot')
```

Here is the sample code for (2):

```
import os
import sys
from pprint import pprint

import json
import re

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt

exchange = ccxt.binance({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
    'verbose': False,
    'options': {
        'defaultType': 'future',
    },
})

markets = exchange.load_markets()

futures_balance = exchange.fetch_balance()
futures_balance_total = futures_balance['total']

for code, amount in futures_balance_total.items():
    if amount > 0:
        currency = exchange.currency(code)
        response = exchange.transfer(code, amount, 'future', 'spot')
```

Traceback:

```
Traceback (most recent call last):
  File "/home/ubuntu/crypto/scripts/binance-ccxt-move-futures-to-spot-v2", line 41, in <module>
    response = exchange.transfer(code, amount, 'future', 'spot')
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/binance.py", line 4000, in transfer
    'amount': self.currency_to_precision(code, amount),
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1305, in currency_to_precision
    return self.decimal_to_precision(fee, TRUNCATE, self.currencies[code]['precision'], self.precisionMode, self.paddingMode)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/decimal_to_precision.py", line 41, in decimal_to_precision
    assert(isinstance(precision, numbers.Integral))
AssertionError
```

**Comment by carlosmiei** [comment]
Hello @majal,
After some investigation, I found what is causing this error. It will be fixed soon. 

Thanks for reporting it!
