### ISSUE TITLE
Bitstamp incorrectly claims balance is too low to withdraw

### ISSUE THREAD

**Issue by mariaimcoding** [ccxt/ccxt#16012]
- OS: Mac OS
- Programming Language version: NodeJS
- CCXT version: 2.2.79

The following code:

```
const exchangeClass = ccxt['bitstamp'],
      exchange = new exchangeClass({
        apiKey:
          process.env.BITSTMAP_API_KEY,
        secret:
          process.env.BITSTAMP_SECRET,
      });

await exchange.withdraw(
      'ETH',
      0.01210379,
      '0xB8ea48B7989dC8dCc7Da0287566b6746493Ec5b1',
      undefined,
      undefined
    );

```

Leads to the following error:

```
ExchangeError: bitstamp {"status": "error", "reason": {"amount": ["You have only 0.01210383 ETH available. Check your account balance for details."]}}
     at bitstamp.handleErrors (/app/node_modules/ccxt/js/bitstamp.js:2117:19)
     at /app/node_modules/ccxt/js/base/Exchange.js:599:51
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
     at timeout (/app/node_modules/ccxt/js/base/functions/time.js:181:20)
     at bitstamp.fetch2 (/app/node_modules/ccxt/js/base/Exchange.js:1967:16)
     at bitstamp.request (/app/node_modules/ccxt/js/base/Exchange.js:1971:16)
     at bitstamp.withdraw (/app/node_modules/ccxt/js/bitstamp.js:2018:26) {
   constructor: [class ExchangeError extends BaseError]
}
```

This does not make sense to me because the error message is saying I have more than what I am trying to withdraw, yet the withdraw is still not going through. Also verified the balance was accurate on Bitstamp. Any idea what the issue could be? Thanks!

**Comment by mariaimcoding** [comment]
Nevermind, the issue is that you have to subtract Bitstamp's withdraw fees from the amount you want to withdraw. These fees can be found [here](https://www.bitstamp.net/fee-schedule/)
