### ISSUE TITLE
coincheck : create_order market buy error

### ISSUE THREAD

**Issue by fisherman2018** [ccxt/ccxt#16029]
- OS: Windows 10
- Programming Language version: Python 3.11.0
- CCXT version: ccxt 2.2.55
- exchange: coincheck
- method: create_order

```
import ccxt

coincheck = ccxt.coincheck({
'apiKey': '',
'secret': '',
'timeout': 5000
})

coincheck.create_order(symbol='BTC/JPY', type='market', side='buy', amount=0.01)
```

```
Traceback (most recent call last):
  File "\Lib\site-packages\ccxt\base\exchange.py", line 621, in fetch
    response.raise_for_status()
  File "\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://coincheck.com/api/exchange/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\coincheck_test.py", line 15, in <module>
    coincheck_order = coincheck.create_order(symbol='BTC/JPY', type='market', side='buy', amount=0.01)

  File "\Lib\site-packages\ccxt\coincheck.py", line 559, in create_order
    response = self.privatePostExchangeOrders(self.extend(request, params))
  File "\Lib\site-packages\ccxt\base\exchange.py", line 501, in inner
    return entry(_self, **inner_kwargs)

  File "\Lib\site-packages\ccxt\base\exchange.py", line 2759, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File "\Lib\site-packages\ccxt\base\exchange.py", line 2756, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "\Lib\site-packages\ccxt\base\exchange.py", line 637, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "\Lib\site-packages\ccxt\coincheck.py", line 783, in handle_errors
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: coincheck {"success":false,"error":"Amount \u91cf\u304c\u6700\u4f4e\u91cf(0.005 BTC)\u3092\u4e0b\u56de\u3063\u3066\u3044\u307e\u3059\nThe minimum order amount is 500 JPY."}
```

**Comment by carlosmiei** [comment]
Hello @fisherman2018,

Coincheck requires the amount in the quote currency (JPY in this case) for market-buy orders. Usually, we throw an informative warning but yeah, we're missing it here.

Can you try to provide the `cost`/JPY value as the amount? 

For instance let's say you want to buy 0.01 BTC with JPY, that would be around 23 402 JPY so that should be the amount

**Comment by fisherman2018** [comment]
Hi @carlosmiei
'success': True, 'jpy': '48175.24485096'

I have enough jpy.

**Comment by fisherman2018** [comment]
@carlosmiei
- limit sell --- success
- limit buy --- success
- market sell --- success
- market buy --- failure

These are trading with enough BTC and JPY.
Isn't it a bug?
