### ISSUE TITLE
Kraken can not get currency deposit address.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16034]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 Pro (Version 22H2)
- Programming Language version: Node.js (Version 19.2.0)
- CCXT version: 2.2.91

```
const ccxt = require('ccxt');
console.log(ccxt.version);

if (process.argv.length != 3)
{
console.error('Usage: USDT');
console.error('Get Coin1 deposit address');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, coin1] = process.argv;

let exchange = new ccxt.kraken
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': true, }
});


const deposit1CoinAddress = async (coin1) => {
try
{
const deposits = await exchange.fetchDepositAddress(coin1);
if (typeof deposits !== 'undefined')
{
const json_deposits = JSON.stringify(deposits);
console.log(json_deposits);
}
else
{
const obj_deposit0 = ({ 'Symbol': coin1, 'Data': [] });
const json_deposit0 = JSON.stringify(obj_deposit0);
console.log(obj_deposit0);
}
}
catch (err)
{
console.error(err)
}
};
deposit1CoinAddress(coin1);

```

```
C:\ArbitApps\CCXT\CCXTNodeByFunctions>node kraken_deposit1CoinAddress.js BTC
2.2.91
InvalidAddress: kraken address is undefined
    at kraken.checkAddress (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:394:19)
    at kraken.parseDepositAddress (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\kraken.js:2247:14)
    at kraken.fetchDepositAddress (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\kraken.js:2233:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deposit1CoinAddress (C:\ArbitApps\CCXT\CCXTNodeByFunctions\kraken_deposit1CoinAddress.js:27:18) {
  constructor: [class InvalidAddress extends ExchangeError]
}
```

Hello:
I just open an account with Kraken and create my API keys.
I did some testing, for get exchange account balance for all tokens, it is working; to get account balance for one token, working.
But when I tried to get one token deposit address, I got some errors, look at the log for details.
By the way, I believe exchange AAX is shutdown and possibly bankrupt, therefore, from next release, it is better to not keep AAX in the repo., even AAX may go back to business later, but it may change the name.  I see a lot of people in Telegram lost all their money in AAX exchange, but nobody can help.
Thanks,

**Comment by zydjohnHotmail** [comment]
I  figured it out, have to create address first, then can get the address!
