### ISSUE TITLE
Gemini get exchange balance got errors

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16036]
- OS: Windows 10 PRO (22H2)
- Programming Language version: Node.js (Ver 19.2.0)
- CCXT version: 2.2.91

```js
const ccxt = require('ccxt');
console.log(ccxt.version);

let exchange = new ccxt.gemini({
    apiKey: 'My_Account_API_Key',
    secret: 'My_Account_Secret_Key',
    'options': {
        'adjustForTimeDifference': true,
        'fetchCurrencies': true,
        'verbose': true,
    }
});

async function getExchangeBalance() {
    try {
        const balance = await exchange.fetchBalance();
        console.log(balance);
    } catch (err) {
        console.error(err)
    }
};
getExchangeBalance();
```

```
C:\ArbitApps\CCXT\CCXTNodeByFunctions>node gemini_getExchangeBalance.js
2.2.91
InvalidNonce: gemini Nonce '1670623439828' is not within 30 seconds of server time '1670623440''
    at gemini.throwExactlyMatchedException (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:2351:19)
    at gemini.handleErrors (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\gemini.js:1503:18)
    at C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:600:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async gemini.fetch2 (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:1995:16)
    at async gemini.request (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:1999:16)
    at async gemini.fetchBalance (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\gemini.js:847:26)
    at async getExchangeBalance (C:\ArbitApps\CCXT\CCXTNodeByFunctions\gemini_getExchangeBalance.js:18:17) {
  constructor: [class InvalidNonce extends NetworkError]
```

Hello,
I just open an account with gemini and create my account API keys.
I did some testing, to get exchange account balance for all tokens, I got some errors.
I synchronize my PC clock with NTP time server.
But I still got the same error.
Any idea on how to fix this?

Thanks

**Comment by samgermain** [comment]
Thanks for letting  us know about this bug! It should be fixed when #16066 gets merged.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply and your effort.
If you release a bug fix, please let me know.
Thanks,

**Comment by samgermain** [comment]
> Hello: Thanks for your reply and your effort. If you release a bug fix, please let me know. Thanks,

The only way it would be fixed would be if gemini release an API V2 or something, that returned more information about whether the market was active or not
