### ISSUE TITLE
Market conditional order stop-loss take-profit error.

### ISSUE THREAD

**Issue by saiooo** [ccxt/ccxt#16049]
Hello, I am facing an issue that I cannot place conditional market order. I am using createMarketBuyOrder command.

Here is code sample:

```
    const params={
        'leverage': 5,
        'base_price': "17160.0",
        'stopLossPrice': "16800.0"
    }
    


    const promise = bybitConnect().createMarketBuyOrder(symbol, amount, params) 
    const observable = from(promise);

    return observable;
```

I am using observables too, but I don't think that that's the issue because other methods seemed working.

Error: BadRequest: bybit {"retCode":10001,"retMsg":"expect Rising, but trigger_price[168000000]}

Any ideas? https://github.com/ccxt/ccxt/issues/14342 I tried to follow this solution by adding 'base_price' param, but did not help.

Thank you

**Comment by carlosmiei** [comment]
Hello @znarf 
We will need a few more details, such as the ccxt version, the symbol used, and a verbose log of the request.

**Comment by saiooo** [comment]
> Hello @znarf We will need a few more details, such as the ccxt version, the symbol used, and a verbose log of the request.

Thank you for quick response for now.

I am using "ccxt": "^2.2.91",
Symbol passed from (app.js): Bybit.placeMarketBuyOrder('BTCUSDT', 0.1, so symbol: BTCUSDT
Verbose log:

```
BadRequest: bybit {"retCode":10001,"retMsg":"expect Rising, but trigger_price[168000000] \u003c= current[171530000]??1","result":{},"retExtInfo":{},"time":1670758388070}
    at bybit.throwExactlyMatchedException (C:\sayhello\node\botukas\node_modules\ccxt\js\base\Exchange.js:2351:19)
    at bybit.handleErrors (C:\sayhello\node\botukas\node_modules\ccxt\js\bybit.js:7167:18)
    at C:\sayhello\node\botukas\node_modules\ccxt\js\base\Exchange.js:600:51
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async timeout (C:\sayhello\node\botukas\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async bybit.fetch2 (C:\sayhello\node\botukas\node_modules\ccxt\js\base\Exchange.js:1995:16)
    at async bybit.request (C:\sayhello\node\botukas\node_modules\ccxt\js\base\Exchange.js:1999:16)
    at async bybit.createContractV3Order (C:\sayhello\node\botukas\node_modules\ccxt\js\bybit.js:3691:26)
    at async bybit.createOrder (C:\sayhello\node\botukas\node_modules\ccxt\js\bybit.js:3440:20) {
  constructor: [class BadRequest extends ExchangeError]
```

**Comment by Vamaka12** [comment]
I had similiar problem but I was getting upstream server error. And now I can't even open position.

**Comment by saiooo** [comment]
Still having an issue right now if I add parameters manually I am getting upstream server error:

code:

```
    const params2 = {
        'time_in_force': 'GoodTillCancel',
        'reduce_only': true,
        'close_on_trigger': true,
        'stop_loss': 16800,
        'position_idx': 0,
        'reduce_only': true
    }
    
    const promise = bybitConnect().createOrder(symbol, type, side, amount, undefined, params2)
    const observable = from(promise);
```

Error:

```
ExchangeError: bybit {"retCode":10016,"retMsg":"upstream server error","result":{},"retExtInfo":{},"time":1670785010377}
    at bybit.throwExactlyMatchedException (C:\sayhello\node\botukas\node_modules\ccxt\js\base\Exchange.js:2351:19)
    at bybit.handleErrors (C:\sayhello\node\botukas\node_modules\ccxt\js\bybit.js:7167:18)
    at C:\sayhello\node\botukas\node_modules\ccxt\js\base\Exchange.js:600:51
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async timeout (C:\sayhello\node\botukas\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async bybit.fetch2 (C:\sayhello\node\botukas\node_modules\ccxt\js\base\Exchange.js:1995:16)
    at async bybit.request (C:\sayhello\node\botukas\node_modules\ccxt\js\base\Exchange.js:1999:16)
    at async bybit.createContractV3Order (C:\sayhello\node\botukas\node_modules\ccxt\js\bybit.js:3691:26)
    at async bybit.createOrder (C:\sayhello\node\botukas\node_modules\ccxt\js\bybit.js:3440:20) {
  constructor: [class ExchangeError extends BaseError]
}
```

**Comment by Vamaka12** [comment]
Can you try 2.2.92 version of ccxt?

**Comment by carlosmiei** [comment]
@saiooo that's not a verbose log yet, can you please add `exchange.verbose=true` before creating the order?

**Comment by saiooo** [comment]
> @saiooo that's not a verbose log yet, can you please add `exchange.verbose=true` before creating the order?

Hey, I found some interesting solution ( I think you should provide more info about how to set stop losses on order/position?)

So right now I am using this method to set stop and take profit:

```
const placeSlOrder = (symbol, type, side, slPrice, tpPrice) => {

    const params = {
        'symbol': symbol,
        'side': side,
        'take_profit': tpPrice,
        'stop_loss': slPrice,
        'position_idx': 0,
        'reduce_only': true
    }

    const promise = bybitConnect().privatePostPrivateLinearPositionTradingStop(params);
    const observable = from(promise);

    return observable;
}
```

Not sure why this (missing this method in documentation): privatePostPrivateLinearPositionTradingStop(params);  but it helped.

**Comment by ttodua** [comment]
bybit api version had been updated in the past since then, so there should not be that problem anymore with stop orders.
let us know if anyone faces any issues.
