### ISSUE TITLE
Binance) how to transfer USDT from spot to isolated margin?

### ISSUE THREAD

**Issue by chaedongyoon** [ccxt/ccxt#16048]
```python
exchange1 = ccxt.binance(config={    
                    'api_key' : '',
                    'secret' : '})
a = exchange1.borrow_margin(code="XRP",amount="1",symbol="XRP/USDT",params={"marginMode": "isolated"})
```

above, it works very well

but do that before, I want to transfer USDT from spot to isolated margin

case1)

```python
b = exchange1.transfer(code="USDT",amount=1.5,fromAccount="spot",toAccount="ISOLATED_MARGIN",params={'symbol':'XRP/USDT'})
```

then it doesn't work. and 

During handling of the above exception, another exception occurred:
```python
Traceback (most recent call last):
  File "c:\coding\bn_margin.py", line 65, in <module>
    a= exchange1.transfer(code="USDT",amount=1.5,fromAccount="spot",toAccount="ISOLATED_MARGIN",params={'symbol':'XRP/USDT'})
  File "C:\Python310\lib\site-packages\ccxt\binance.py", line 3788, in transfer
    response = self.sapiPostAssetTransfer(self.extend(request, params))
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 497, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Python310\lib\site-packages\ccxt\binance.py", line 5366, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 633, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Python310\lib\site-packages\ccxt\binance.py", line 5344, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 2834, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."}
```
case2)
```python
b= exchange1.transfer(code="USDT", amount=10,fromAccount="spot",toAccount="isolated",params={'symbol':'XRP/USDT'})`
```
then, it's error is below
During handling of the above exception, another exception occurred:
```python
Traceback (most recent call last):
  File "c:\coding\bn_margin.py", line 65, in <module>
    b= exchange1.transfer(code="USDT", amount=10,fromAccount="spot",toAccount="isolated",params={'symbol':'XRP/USDT'})
  File "C:\Python310\lib\site-packages\ccxt\binance.py", line 3788, in transfer
    response = self.sapiPostAssetTransfer(self.extend(request, params))
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 497, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Python310\lib\site-packages\ccxt\binance.py", line 5366, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 633, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Python310\lib\site-packages\ccxt\binance.py", line 5344, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 2834, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."}
```
please help  thanks

**Comment by carlosmiei** [comment]
Hello @chaedongyoon, yeah case 2 should work, we will take a look asap. Thanks for letting us know

**Comment by samgermain** [comment]
> b= exchange1.transfer(code="USDT", amount=10,fromAccount="spot",toAccount="isolated",params={'symbol':'XRP/USDT'})

Just do 
```python
b = exchange1.transfer(code="USDT",  amount=10, fromAccount="spot", toAccount="XRP/USDT")
```

**Comment by chaedongyoon** [comment]
> > b= exchange1.transfer(code="USDT", amount=10,fromAccount="spot",toAccount="isolated",params={'symbol':'XRP/USDT'})
> 
> Just do
> 
> ```python
> b = exchange1.transfer(code="USDT",  amount=10, fromAccount="spot", toAccount="XRP/USDT")
> thanks for your kindly response, but it did not work
error msg is below

C:\coding>C:/Python310/python.exe c:/coding/bn_margin.py
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 617, in fetch
    response.raise_for_status()
  File "C:\Python310\lib\site-packages\requests\models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/asset/transfer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\coding\bn_margin.py", line 65, in <module>
    b= exchange1.transfer(code="USDT", amount=10,fromAccount="spot",toAccount="XRP/USDT")
  File "C:\Python310\lib\site-packages\ccxt\binance.py", line 3788, in transfer
    response = self.sapiPostAssetTransfer(self.extend(request, params))
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 497, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Python310\lib\site-packages\ccxt\binance.py", line 5366, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 633, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Python310\lib\site-packages\ccxt\binance.py", line 5344, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 2834, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."}

**Comment by samgermain** [comment]
@chaedongyoon 

Are you still having this problem?

**Comment by samgermain** [comment]
I'm closing this issue, reopen if you have any more questions
