### ISSUE TITLE
Deribit Issue with USDC Perp contract order

### ISSUE THREAD

**Issue by meokoken** [ccxt/ccxt#16073]
- OS: Windows 11
- Programming Language version:  python 3,9
- CCXT version: ccxt-2.2.98

There seems to be an issue with placing orders for USDC based perp contract. Tried with LINK/USDC:USDC and it failed. However the order for ETH/USD:ETH works fine.

Tried catching the exception but it was not any of ccxt error. It flows down to the final catch all Exception.

```
deribit = ccxt.deribit ({
    'apiKey': accountConfig.deribit_apiKey,
    'secret': accountConfig.deribit_secret,
    'enableRateLimit': True,
})

markets = exchange.load_markets()
symbol =  "LINK/USDC:USDC"  # "ETH/USD:ETH"
market = exchange.market(symbol)

tickerResult = deribit.fetch_ticker(symbol)
print(f"{symbol}: {exchange.name} l:{tickerResult['last']} b:{tickerResult['bid']} a:{tickerResult['ask']}")
# fetch_ticker works fine

exchange = deribit

 try:
      order = exchange.create_order('LINK/USDC:USDC', 'market', 'buy', 20, None,params)   # fails
      # order = exchange.create_market_order('LINK/USDC:USDC', 'buy', 20.0)    # fails
      # order = exchange.create_order('ETH/USD:ETH', 'market', 'buy', 20, None,params)  # can work for ETH based symbol
      pprint(order)

  except ccxt.InsufficientFunds as e:
      print(f"InsufficientFunds {e}")
  except ccxt.AuthenticationError as e:
      print(f"AuthenticationError {e}")
  except ccxt.ArgumentsRequired as e:
      print(f"ArgumentsRequired {e}")
  except ccxt.BadRequest as e:
      print(f"BadRequest {e}")
  except ccxt.InvalidAddress as e:
      print(f"InvalidAddress {e}")
  except ccxt.InvalidOrder as e:
      print(f"InvalidOrder {e}")
  except ccxt.OrderNotFound as e:
      print(f"OrderNotFound {e}")
  except ccxt.NotSupported as e:
      print(f"NotSupported {e}")
  except ccxt.ExchangeNotAvailable as e:
      print(f"ExchangeNotAvailable {e}")
  except ccxt.OnMaintenance as e:
      print(f"OnMaintenance {e}")
  except ccxt.ExchangeError as e:
      print(f"ExchangeError {e}")
  except ccxt.PermissionDenied as e:
      print(f"PermissionDenied {e}")
  except Exception as e:
      print(f'testTrade Exception: {e}')


```

```
LINK/USDC:USDC: Deribit l:6.707 b:6.719 a:6.728
testTrade Exception: 'LINK/USDC:USDC'
```

**Comment by meokoken** [comment]
I test with the raw deribit ws api and the order is able to go thru.

**Comment by carlosmiei** [comment]
Hello @meokoken,
We can't understand what the error was, can you please provide a verbose log (`exchange.verbose=True` before placing the order)?

**Comment by meokoken** [comment]
> Hello @meokoken, We can't understand what the error was, can you please provide a verbose log (`exchange.verbose=True` before placing the order)?

Hi carlosmiei, I tried that and it returns nothing also

**Comment by meokoken** [comment]
```
deribit = ccxt.deribit ({
    'apiKey': accountConfig.deribit_apiKey,
    'secret': accountConfig.deribit_secret,
    'enableRateLimit': True,
})

markets = deribit.load_markets()
while not markets:
    print('market not ready')
    time.sleep(10)

tickerResult = deribit.fetch_ticker("LINK_USDC-PERPETUAL")
print(f"LINK_USDC-PERPETUAL: {deribit.name} l:{tickerResult['last']} b:{tickerResult['bid']} a:{tickerResult['ask']}")
tickerResult1 = deribit.fetch_ticker('LINK/USDC:USDC')
print(f"LINK/USDC:USDC: {deribit.name} l:{tickerResult1['last']} b:{tickerResult1['bid']} a:{tickerResult1['ask']}")

deribit.verbose=True

# market = deribit.market("LINK_USDC-PERPETUAL")
# order = deribit.create_order("LINK_USDC-PERPETUAL", 'market', 'buy', 10.0, None,{})
# print(order)

market = deribit.market("LINK/USDC:USDC")
order1 = deribit.create_order("LINK/USDC:USDC", 'market', 'buy', 10.0, None,{})
print(order1)
```

when i run this with verbose turned on, i see: 

```
ccxt version: 2.2.103
LINK_USDC-PERPETUAL: Deribit l:6.903 b:6.884 a:6.898
LINK/USDC:USDC: Deribit l:6.903 b:6.884 a:6.898
Traceback (most recent call last):
  File "C:\Users\Meo\Desktop\Meo\Code\cryptoctarb\alfredsaytryderibit.py", line 41, in <module>
    order1 = deribit.create_order("LINK/USDC:USDC", 'market', 'buy', 10.0, None,{})
  File "C:\ProgramData\Anaconda3\envs\py39_ccxt\lib\site-packages\ccxt\deribit.py", line 1583, in create_order
    amount = self.currency_to_precision(symbol, amount)
  File "C:\ProgramData\Anaconda3\envs\py39_ccxt\lib\site-packages\ccxt\base\exchange.py", line 3243, in currency_to_precision
    currency = self.currencies[code]
KeyError: 'LINK/USDC:USDC'
```

there is a KeyError

**Comment by meokoken** [comment]
I manage to execute the order with ccxt version 1.60.38

```
import time
import ccxt  # noqa: E402+

import accountConfig

if __name__ == "__main__":

    print(ccxt.__version__)

    deribit = ccxt.deribit ({
        'apiKey': accountConfig.deribit_apiKey,
        'secret': accountConfig.deribit_secret,
        'enableRateLimit': True,
    })


    markets = deribit.load_markets()

    while not deribit.markets:
        print('market not ready')
        time.sleep(2)

    try:
        params = {}
        order = deribit.create_order('LINK_USDC-PERPETUAL', 'market', 'buy', 20, None,params)
        print(order)
    except Exception as e:
        print(f'die liao {e}')

```

cannot execute order with ccxt version 2.2

**Comment by meokoken** [comment]
Hi, another difference i found was that when using ccxt version 2.2+, the ordersize was in quote ccy. e.g. for BTCUSD:BTC, it would be in USD.

but when i used ccxt version 1.60.38, the ordersize was in base ccy. e.g. for LINKUSDC:USDC, it would be in LINK.

**Comment by Dan-krm** [comment]
It looks like the amount should be in the base currency for perpetual pairs settled in USDC:
```
CCXT v2.4.24
deribit.createOrder (LINK/USDC:USDC, market, buy, 1)

{
  info: {
    web: false,
    time_in_force: 'good_til_cancelled',
    risk_reducing: false,
    replaced: false,
    reduce_only: false,
    profit_loss: '0.0',
    price: '6.028',
    post_only: false,
    order_type: 'market',
    order_state: 'filled',
    order_id: 'USDC-3560237816',
    mmp: false,
    max_show: '1.0',
    last_update_timestamp: '1671231171202',
    label: '',
    is_liquidation: false,
    instrument_name: 'LINK_USDC-PERPETUAL',
    filled_amount: '1.0',
    direction: 'buy',
    creation_timestamp: '1671231171202',
    commission: '0.002975',
    average_price: '5.95',
    api: true,
    amount: '1.0',
    trades: [
      {
        trade_seq: '58502',
        trade_id: 'USDC-6607633',
        timestamp: '1671231171202',
        tick_direction: '0',
        state: 'filled',
        self_trade: false,
        risk_reducing: false,
        reduce_only: false,
        profit_loss: '0.0',
        price: '5.95',
        post_only: false,
        order_type: 'market',
        order_id: 'USDC-3560237816',
        mmp: false,
        matching_id: null,
        mark_price: '5.9366',
        liquidity: 'T',
        instrument_name: 'LINK_USDC-PERPETUAL',
        index_price: '5.9263',
        fee_currency: 'USDC',
        fee: '0.002975',
        direction: 'buy',
        api: true,
        amount: '1.0'
      }
    ]
  },
  id: 'USDC-3560237816',
  clientOrderId: undefined,
  timestamp: 1671231171202,
  datetime: '2022-12-16T22:52:51.202Z',
  lastTradeTimestamp: 1671231171202,
  symbol: 'LINK/USDC:USDC',
  type: 'market',
  timeInForce: 'GTC',
  postOnly: false,
  side: 'buy',
  price: 6.028,
  stopPrice: undefined,
  amount: 1,
  cost: 5.95,
  average: 5.95,
  filled: 1,
  remaining: 0,
  status: 'closed',
  fee: { cost: '0.002975', currency: 'LINK' },
  trades: [
    {
      id: 'USDC-6607633',
      info: {
        trade_seq: '58502',
        trade_id: 'USDC-6607633',
        timestamp: '1671231171202',
        tick_direction: '0',
        state: 'filled',
        self_trade: false,
        risk_reducing: false,
        reduce_only: false,
        profit_loss: '0.0',
        price: '5.95',
        post_only: false,
        order_type: 'market',
        order_id: 'USDC-3560237816',
        mmp: false,
        matching_id: null,
        mark_price: '5.9366',
        liquidity: 'T',
        instrument_name: 'LINK_USDC-PERPETUAL',
        index_price: '5.9263',
        fee_currency: 'USDC',
        fee: '0.002975',
        direction: 'buy',
        api: true,
        amount: '1.0'
      },
      timestamp: 1671231171202,
      datetime: '2022-12-16T22:52:51.202Z',
      symbol: 'LINK/USDC:USDC',
      order: 'USDC-3560237816',
      type: 'market',
      side: 'buy',
      takerOrMaker: 'taker',
      price: 5.95,
      amount: 1,
      cost: 5.95,
      fee: { cost: 0.002975, currency: 'USDC' },
      fees: [ { currency: 'USDC', cost: '0.002975' } ]
    }
  ],
  fees: [ { currency: 'USDC', cost: 0.002975 } ]
}
```

**Comment by meokoken** [comment]
Hi @Dan-krm ,

I upgraded to ccxt version 2.4.24 and got a KeyError

Code
```
import os
import sys
from pprint import pprint

import asyncio
import ccxt  # noqa: E402+

import accountConfig

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

print(f"ccxt version: {ccxt.__version__}")


deribit = ccxt.deribit ({
    'apiKey': accountConfig.deribit_apiKey,
    'secret': accountConfig.deribit_secret,
    'enableRateLimit': True,
})

exchange = deribit
markets = exchange.load_markets()

symbol = "LINK/USDC:USDC"   # 'LINK_USDC-PERPETUAL' "LINK/USDC:USDC" "ETH/USD:ETH"  "BTC/USD:BTC"
market = exchange.market(symbol)  # market is info for the symbol. market['id'] is different from symbol

exchange.verbose = True

order = exchange.createOrder(symbol, 'market', 'buy', 1)   # does not work
# order = exchange.create_order(symbol, 'market', 'buy', 1, None, {})   # does not work
pprint(order)
```

output:
```
ccxt version: 2.4.24
Traceback (most recent call last):
  File "C:\Users\meo\Desktop\meo\Code\cryptoctarb\errorsubmission_deribit.py", line 38, in <module>
    order = exchange.create_order(symbol, 'market', 'buy', 1, None, {})
  File "C:\Users\meo\.conda\envs\py39_ccxt\lib\site-packages\ccxt\deribit.py", line 1583, in create_order
    amount = self.currency_to_precision(symbol, amount)
  File "C:\Users\meo\.conda\envs\py39_ccxt\lib\site-packages\ccxt\base\exchange.py", line 3244, in currency_to_precision
    currency = self.currencies[code]
KeyError: 'LINK/USDC:USDC'
```

**Comment by yunwei17** [comment]
@Dan-krm, I tried create_order, there seems to be a missing symbol to code conversion for function currency_to_precision

**Comment by Dan-krm** [comment]
@meokoken @yunwei17 I recreated the error in python and opened a pull request that should resolve the issue #16139

**Comment by meokoken** [comment]
thanks a lot @Dan-krm!
