### ISSUE TITLE
Bybit watchMyTrades and watchOrders not returning anything

### ISSUE THREAD

**Issue by dptashny1** [ccxt/ccxt#16106]
watchOrderBook works fine and I can send out an order. I see the order filled on the website, but  neither watchMyTrades nor WatchOrders returns anything, so I can't see when the order gets filled in my program.

Is there some bybit parameter I'm missing ? This is a SPOT order on the live bybit system. BTW, same problem on their testnet.

- OS: Windows
- Programming Language version: Python 3.10.0
- CCXT version: 2.1.33

```

from asyncio import gather, run, create_task, sleep
import logging
import ccxt.pro as ccxtpro

import datetime

import os
import json

import traceback


class TradingEngine:

    def __init__(self):
        self.shutdown_flag = False
        self.sent_orders = False

        logging.info("Reading config file")

        with open("config.json", "r") as jsonfile:
            self.config = json.load(jsonfile)
            logging.info("Read config.json successful")

        exchanges = {

            'bybit': {
                'watchOrderBook': ['BTCUSDT'],
                'watchMyTrades': ['BTCUSDT'],
                'watchOrders': ['BTCUSDT']
            }
        }

        for exchange_id, methods in exchanges.items():
            create_task(self.exchange_loop(exchange_id, methods))

    async def process_watchOrderBook(self, exchange, symbol, response):
        buy_price = response['bids'][0][0]
        order_amount = self.config['order_size']

        if not self.sent_orders:
            try:
                order_info = await exchange.createOrder(symbol, 'limit', 'buy', order_amount,
                                                              buy_price)
                logging.info(
                    f"Buy order created on bybit for symbol {symbol} id: {order_info['id']} price: {buy_price} ")
                self.sent_orders = True

            except Exception as e:
                logging.info(f"createOrder on bybit sell  failed: {e} ")


    async def symbol_loop(self, exchange, method, symbol):
        logging.info(f"Starting {exchange.id} {method} {symbol}")
        while not self.shutdown_flag:
            try:
                response = await getattr(exchange, method)(symbol)
                if method == 'watchOrderBook':
                    await self.process_watchOrderBook(exchange, symbol, response)
                elif method == 'watchOrders':
                    logging.info(f"bybit {response}")
                elif method == 'watchMyTrades':
                    logging.info(f"bybit {response}")

            except Exception as e:
                logging.info(f"Exception in symbol_loop: {e}. Method: {method} Symbol: {symbol}")
                logging.info(traceback.format_exc())


    async def method_loop(self, exchange, method, symbols):
        logging.info(f"Starting  {exchange.id} {method} {symbols}")
        loops = [self.symbol_loop(exchange, method, symbol) for symbol in symbols]
        await gather(*loops)


    async def exchange_loop(self, exchange_id, methods):
        logging.info(f"Starting {exchange_id} {methods}")
        exchange = getattr(ccxtpro, exchange_id)({

            'secret': self.config[exchange_id + '_secret'],
            'apiKey': self.config[exchange_id + '_api_key'],
            'newUpdates': True,
            'verbose': True,
            'options': {
                'adjustForTimeDifference': True,
                'defaultType': 'spot'
            }}

        )
        if 'testmode' in self.config and self.config['testmode']:
            exchange.set_sandbox_mode(True)

        task_list = []
        for method, symbols in methods.items():
            this_task = create_task(self.method_loop(exchange, method, symbols))
            task_list.append(this_task)

        while not os.path.exists('shared/stop.txt') :
            await sleep(1)

    async def shutdown(self):
        while not self.shutdown_flag:
            await sleep(1)


async def init():
    start_time = datetime.datetime.now()
    logging.basicConfig(filename='shared/logs/logfile_' + start_time.strftime("%Y%m%d_%H%M%S") + ".log",
                        format='%(asctime)s %(message)s', level=logging.INFO)

    if not os.path.exists('shared/stop.txt'):
        tradingInstance = TradingEngine()
        await tradingInstance.shutdown()
    else:
        logging.info("stop.txt was detected. Trading not started")

    logging.info("Exiting program")


if __name__ == "__main__":
    run(init())

```

```

fetch Request: bybit GET https://api.bybit.com/asset/v1/private/coin-info/query?api_key=hxnDXog00s5H6xRHZg&recv_window=5000&timestamp=1671168169324&sign=a4ddf953fa96b7fef983b6843a61246d9814056c0b3bd69bb9c1020ab9ee4d9b RequestHeaders: {'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/asset/v1/private/coin-info/query?api_key=hxnDXog00s5H6xRHZg&recv_window=5000&timestamp=1671168169324&sign=a4ddf953fa96b7fef983b6843a61246d9814056c0b3bd69bb9c1020ab9ee4d9b 200 ResponseHeaders: {'Content-Type': 'application/json', 'Server': 'Openresty', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'Expires': 'Fri, 16 Dec 2022 05:22:49 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Fri, 16 Dec 2022 05:22:49 GMT', 'Content-Length': '6124', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"OK","ext_code":"","result":{"rows":[{"name":"MOVR", "coin":"MOVR", "remain_amount":"10000", "chains":[{"chain_type":"MOVR", "confirmation":"30", "withdraw_fee":"0.005", "deposit_min":"0", "withdraw_min":"0.005", "chain":"MOVR"}]}, {"name":"FIDA", "coin":"FIDA", "remain_amount":"300000", "chains":[{"chain_type":"SOL", "confirmation":"200", "withdraw_fee":"1", "deposit_min":"0", "withdraw_min":"1", "chain":"SOL"}]}, {"name":"OBX", "coin":"OBX", "remain_amount":"25000000", "chains":[{"chain_type":"AVAXC", "confirmation":"120", "withdraw_fee":"10", "deposit_min":"0", "withdraw_min":"10", "chain":"CAVAX"}]}, {"name":"LUNC", "coin":"LUNC", "remain_amount":"3500000000", "chains":[{"chain_type":"Terra Classic", "confirmation":"30", "withdraw_fee":"0", "deposit_min":"0", "withdraw_min":"5000", "chain":"LUNA"}]}, {"name":"SAND", "coin":"SAND", "remain_amount":"1336850", "chains":[{"chain_type":"ERC20", "confirmation":"12", "withdraw_fee":"17", "deposit_min":"0", "withdraw_min":"34", "chain":"ETH"}]}, {"name":"FTM", "coin":"FTM", "remain_amount":"555550", "chains":[{"chain_type":"FTM", "confirmation":"10", "withdraw_fee":"0.01", "deposit_min":"0", "withdraw_min":"1", "chain":"FTM"}, {"chain_type":"ERC20", "confirmation":"12", "withdraw_fee":"14.5", "deposit_min":"0", "withdraw_min":"29", "chain":"ETH"}]}, {"name":"BTT", "coin":"BTT", "remain_amount":"250000000000", "chains":[{"chain_type":"TRC20", "confirmation":"20", "withdraw_fee":"320000", "deposit_min":"0", "withdraw_min":"320000", "chain":"TRX"}]}, {"name":"ACH", "coin":"ACH", "remain_amount":"10000000", "chains":[{"chain_type":"ERC20", "confirmation":"12", "withdraw_fee":"550", "deposit_min":"0", "withdraw_min":"550", "chain":"ETH"}, {"chain_type":"BSC (BEP20)", "confirmation":"15", "withdraw_fee":"5", "deposit_min":"0", "withdraw_min":"5", "chain":"BSC"}]}, 

[TRUNCATED]

**Comment by sc0Vu** [comment]
Hi @dptashny1

I use the latest version of ccxt, and your script works for me.

**Comment by dptashny1** [comment]
Thank you, that did help, and I do get a response from watchOrders, but after a few seconds I get a new error:

2022-12-16 13:39:04,442 Traceback (most recent call last):
  File "C:\Users\david\PycharmProjects\CryptoTrading\exchange_arb_trader_test.py", line 59, in symbol_loop
    response = await getattr(exchange, method)(symbol)
  File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\site-packages\ccxt\pro\bybit.py", line 837, in watch_orders
    orders = await self.watch_topics(url, messageHash, topics, params)
  File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\site-packages\ccxt\pro\bybit.py", line 1249, in watch_topics
    return await self.watch(url, messageHash, message, messageHash)
  File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\site-packages\ccxt\pro\base\exchange.py", line 82, in spawn_async
    await method(*args)
ccxt.base.errors.NetworkError: 1006

2022-12-16 13:39:04,506 Unclosed connection
client_connection: Connection<ConnectionKey(host='stream.bybit.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None)>
2022-12-16 13:39:36,070 Exception in symbol_loop: 1006. Method: watchOrders Symbol: BTCUSDT
2022-12-16 13:39:36,072 Traceback (most recent call last):
  File "C:\Users\david\PycharmProjects\CryptoTrading\exchange_arb_trader_test.py", line 59, in symbol_loop
    response = await getattr(exchange, method)(symbol)
  File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\site-packages\ccxt\pro\bybit.py", line 837, in watch_orders
    orders = await self.watch_topics(url, messageHash, topics, params)
  File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\site-packages\ccxt\pro\bybit.py", line 1249, in watch_topics
    return await self.watch(url, messageHash, message, messageHash)
  File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\site-packages\ccxt\pro\base\exchange.py", line 82, in spawn_async
    await method(*args)
ccxt.base.errors.NetworkError: 1006

**Comment by dptashny1** [comment]
I'll close the issue. It generates a lot of these Network Error: 1006, but the program recovers.
