### ISSUE TITLE
Bybit "position idx not match position mode"

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#16102]
- OS: Windows 10
- Programming Language version: Python Spyder 3.9
- CCXT version: 2.2.95

---------------------------

Hello again :-), 

suddenly an Error occured on bybit exchange. It worked well for weeks but today suddenly the following error appeared.
What could that be?

```python
BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1671136959287}
```

```python
bybit = ccxt.bybit({'enableRateLimit': True,
                       'apiKey': config.api_key,
                       'secret': config.api_secret,})

# I also tried this but the same error occured


bybit = ccxt.bybit({'enableRateLimit': True,
                       'apiKey': config.api_key,
                       'secret': config.api_secret,
                       'options': {'defaultType': 'swap',
                                   'defaultPositionMode': False 
                                   }})


bybit.verbose = True

symbol = 'ETH/USDT:USDT'
pos_size = 0.1


bybit.create_market_sell_order(symbol, amount=pos_size)
```

```python
fetch Request: bybit GET https://api.bybit.com/asset/v3/private/coin-info/query?api_key=XQbmFGlpbxyyZyIMOU&recv_window=5000&timestamp=1671136946148&sign=0c689092c8733464b11cac3c15f939ecd4403ae488f95e2ebb40d255641da485 RequestHeaders: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/asset/v3/private/coin-info/query?api_key=XQbmFGlpbxyyZyIMOU&recv_window=5000&timestamp=1671136946148&sign=0c689092c8733464b11cac3c15f939ecd4403ae488f95e2ebb40d255641da485 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '73781', 'X-Bapi-Limit': '2', 'X-Bapi-Limit-Status': '1', 'X-Bapi-Limit-Reset-Timestamp': '1671136946267', 'Ret_code': '0', 'Traceid': '0a9dc2b8220c3d634cf888dfc8140c45', 'Timenow': '1671136946307', 'Server': 'Openresty', 'Expires': 'Thu, 15 Dec 2022 20:42:26 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 15 Dec 2022 20:42:26 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":0,"retMsg":"OK","result":{"rows":[{"name":"AGLD","coin":"AGLD","remainAmount":"256400","chains":[{"chainType":"ERC20","confirmation":"12","withdrawFee":"6.76","depositMin":"0","withdrawMin":"13","chain":"ETH","chainDeposit":"1","chainWithdraw":"0","minAccuracy":"8"}]},{"name":"MATIC","coin":"MATIC","remainAmount":"1652850","chains"


-------------------------------------



fetch Request: bybit GET https://api.bybit.com/derivatives/v3/public/instruments-info?category=option&limit=1000&cursor=9000%2C10000 RequestHeaders: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/derivatives/v3/public/instruments-info?category=option&limit=1000&cursor=9000%2C10000 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '205', 'Ret_code': '0', 'Traceid': '65c48a2ba5b7240812bac4af67142716', 'Timenow': '1671136951981', 'Server': 'Openresty', 'Expires': 'Thu, 15 Dec 2022 20:42:32 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 15 Dec 2022 20:42:32 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":0,"retMsg":"success","result":{"resultTotalSize":9294,"cursor":"10000%2C11000","dataList":[],"category":"option","nextPageCursor":"10000%2C11000","list":[]},"retExtInfo":{},"time":1671136951981}

fetch Request: bybit GET https://api.bybit.com/user/v3/private/query-api?api_key=XQbmFGlpbxyyZyIMOU&recv_window=5000&timestamp=1671136959100&sign=18f0c5a81936241fdb610df46c5b77aeb4fcb79440ba9f84a5aafa21da65dcd8 RequestHeaders: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/user/v3/private/query-api?api_key=XQbmFGlpbxyyZyIMOU&recv_window=5000&timestamp=1671136959100&sign=18f0c5a81936241fdb610df46c5b77aeb4fcb79440ba9f84a5aafa21da65dcd8 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '612', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1671136959113', 'Traceid': '2dba95c09976a18b5fd206863d2ccaa7', 'Timenow': '1671136959116633754', 'Server': 'Openresty', 'Expires': 'Thu, 15 Dec 2022 20:42:39 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 15 Dec 2022 20:42:39 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":0,"retMsg":"OK","result":{"id":"15131916","note":"Veritas1981","apiKey":"XQbmFGlpbxyyZyIMOU","readOnly":0,"secret":"","permissions":{"ContractTrade":["Order","Position"],"Spot":["SpotTrade"],"Wallet":["AccountTransfer","SubMemberTransfer","Withdraw"],"Options":["OptionsTrade"],"Derivatives":["DerivativesTrade"],"CopyTrading":["CopyTrading"],"BlockTrade":[],"Exchange":["ExchangeHistory"],"NFT":["NFTQueryProductList"]},"ips":["217.238.89.82"],"type":1,"deadlineDay":-2,"expiredAt":"1970-01-01T00:00:00Z","createdAt":"2022-12-08T15:37:14Z","unified":0,"uta":0},"retExtInfo":null,"time":1671136959116}

fetch Request: bybit POST https://api.bybit.com/contract/v3/private/order/create RequestHeaders: {'Content-Type': 'application/json', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"ETHUSDT","side":"Sell","orderType":"Market","timeInForce":"GoodTillCancel","qty":"0.1","api_key":"XQbmFGlpbxyyZyIMOU","recv_window":5000,"timestamp":"1671136959278","sign":"211e920f28e62846ae8c32a3ac5437d54c971eca4eb9dfb33f6f6d84c6da0d87"}

fetch Response: bybit POST https://api.bybit.com/contract/v3/private/order/create 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '114', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1671136959285', 'Ret_code': '10001', 'Traceid': '06ed51f04d8387dd524e7e07e33b51e8', 'Timenow': '1671136959287', 'Server': 'Openresty', 'Expires': 'Thu, 15 Dec 2022 20:42:39 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 15 Dec 2022 20:42:39 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1671136959287}
Traceback (most recent call last):

  File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\dell\desktop\bybit\bybittest1.py", line 32, in <module>
    bybit.create_market_sell_order(symbol, amount=pos_size)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 3218, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\bybit.py", line 3294, in create_order
    return self.create_contract_v3_order(symbol, type, side, amount, price, params)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\bybit.py", line 3519, in create_contract_v3_order
    response = self.privatePostContractV3PrivateOrderCreate(self.extend(request, params))

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 501, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2785, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2782, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 663, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\bybit.py", line 6708, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 3068, in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1671136959287}







```

**Comment by samgermain** [comment]
Can you upgrade to the latest CCXT version and see if you still get the issue?

**Comment by frosty00** [comment]
I think this happens when the positions mode is hedge mode

**Comment by Nitrix321** [comment]
> Can you upgrade to the latest CCXT version and see if you still get the issue?

Hello @samgermain ,

sorry, I just upgraded to (2.4.18),
but still the same issue.

**Comment by Nitrix321** [comment]
> I think this happens when the positions mode is hedge mode


Hello @frosty00 ,

I tried it also with this settings:

bybit = ccxt.bybit({'enableRateLimit': True,
                       'apiKey': config.api_key,
                       'secret': config.api_secret,
                       'options': {'defaultType': 'swap',
                                   'defaultPositionMode': False 
                                   }})

This should be one way mode or not?
Or how could I disable hedge mode and set one way mode?
I never used/changed those settings on bybit. 
As I said it worked well before for weeks.

**Comment by Nitrix321** [comment]
With  symbol = 'ETH/USD:ETH'  it's working but not with  symbol = 'ETH/USDT:USDT'.

**Comment by Dan-krm** [comment]
@Nitrix321 to set the position mode you can try:
```
bybit.set_position_mode(0, 'ETH/USDT:USDT') // 0 is one-way mode and 3 is hedge mode
```
You can also set the position mode on the website, click the hexagon to open those settings:

![image](https://user-images.githubusercontent.com/83686770/208206086-8bcb0343-921d-4949-af04-6129deb54224.png)

**Comment by Nitrix321** [comment]
Hi @Dan-krm ,
thank you so much, this   bybit.set_position_mode(0, 'ETH/USDT:USDT')
has fixed it!

Issue can be closed. Thanks

**Comment by Nitrix321** [comment]
Ahh sorry i was too hasty. It worked the first time but then this error occured.

  File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\dell\desktop\bybit\bbmini.py", line 30, in <module>
    bybit.set_position_mode(1, 'ETH/USDT:USDT')

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\bybit.py", line 6083, in set_position_mode
    return self.privatePostContractV3PrivatePositionSwitchMode(self.extend(request, params))

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 502, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2786, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2783, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 664, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\bybit.py", line 6710, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 3069, in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: bybit {"retCode":140025,"retMsg":"position mode not modified","result":{},"retExtInfo":{},"time":1671275523747}

**Comment by Dan-krm** [comment]
> bybit.set_position_mode(1, 'ETH/USDT:USDT')

The acceptable arguments for set_position_mode are ether 0 or 3, 1 is invalid
0 is one-way mode
3 is hedge mode

**Comment by Nitrix321** [comment]
It's working now without  this position mode setting again      bybit.set_position_mode(0, 'ETH/USDT:USDT') 
Like before. I changed nothing :-).
