### ISSUE TITLE
BKEX fetch_tickers() ccxt.base.errors.BadSymbol: bkex does not have market symbol BDC_USDT

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#16138]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 2.4.33

```
exchange = ccxt.bkex()
exchange.load_markets()
exchange.verbose=True
exchange.fetch_tickers()
```

```
fetch Request: bkex GET https://api.bkex.com/v2/q/tickers RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bkex GET https://api.bkex.com/v2/q/tickers 200 ResponseHeaders: {'Date': 'Mon, 19 Dec 2022 21:57:02 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '30182', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-CAT-ROOT-ID': ..., 'Content-Encoding': 'gzip', 'old-length': '172347', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=...; path=/; expires=Mon, 19-Dec-22 22:27:02 GMT; domain=.bkex.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': ...} ResponseBody: {
	"code":0,
	"data":[
		{
			"change":-3.16,
			"close":0.0153,
			"high":0.0162,
			"low":0.0151,
			"open":0.0158,
			"quoteVolume":20418.8867,
			"symbol":"T_USDT",
			"tradeSet":"USDT",
			"ts":1671487021878,
			"volume":1312264.0123
		},
		{
			"change":0,
			"close":0,
			"high":0,
			"low":0,
			"open":0,
			"quoteVolume":0,
			"symbol":"BDC_USDT",
			"ts":1669824000000,
			"volume":0
		},
...
	],
	"msg":"success",
	"status":0
}
Traceback (most recent call last):
  File "/home/xyz/test.py", line 6, in <module>
    exchange.fetch_tickers()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bkex.py", line 732, in fetch_tickers
    return self.parse_tickers(tickers, symbols, query)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3369, in parse_tickers
    ticker = self.extend(self.parse_ticker(tickers[i]), params)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bkex.py", line 768, in parse_ticker
    market = self.market(symbol)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3206, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: bkex does not have market symbol BDC_USDT
```

Feels pretty dirty to ask bug fixes when this exchange has such issues as #15486. I wonder if there has been any updates on that...

**Comment by carlosmiei** [comment]
Hey @JovianMoon,
We will fix it because we don't like broken code, but as always, we advise all the users to DYOR and be very careful with their money.
