### ISSUE TITLE
Unable to use CCXT, module 'datetime' has no attribute 'date'

### ISSUE THREAD

**Issue by Gladi-iwnl** [ccxt/ccxt#16137]
Hi,

I'm trying to run a simple CCXT script in python 3.10.6 but I'm directly get an error related to the 'datetime' module. I restarted my pc, also my clock is up to date. I never had this issue before

Can you guys help me?

- OS: Ubuntu 22.04.1 LTS
- Programming Language version: Python 3.10.6
- CCXT version: 2.4.33

```python
import ccxt

connection = ccxt.binance(
    {
        "apiKey": "xxx", 
        "secret": "xxx"
    }
)
connection.verbose = True

limitOrder = connection.create_limit_buy_order('ETH/USDT', 0.0114, 1000)
```

```
Traceback (most recent call last):
  File "/media/gladi/D/PARA_Projects/dualMomentum/test/createLimitOrder.py", line 2, in <module>
    import ccxt
  File "/home/gladi/.local/lib/python3.10/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/home/gladi/.local/lib/python3.10/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/home/gladi/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 64, in <module>
    import calendar
  File "/usr/lib/python3.10/calendar.py", line 52, in <module>
    class _localized_month:
  File "/usr/lib/python3.10/calendar.py", line 54, in _localized_month
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
  File "/usr/lib/python3.10/calendar.py", line 54, in <listcomp>
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
AttributeError: module 'datetime' has no attribute 'date'
Error in sys.excepthook:
Traceback (most recent callTraceback (most recent call last):
  File "/media/kobe/D/PARA_Projects/dualMomentum/test/createLimitOrder.py", line 2, in <module>
    import ccxt
  File "/home/kobe/.local/lib/python3.10/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/home/kobe/.local/lib/python3.10/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/home/kobe/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 64, in <module>
    import calendar
  File "/usr/lib/python3.10/calendar.py", line 52, in <module>
    class _localized_month:
  File "/usr/lib/python3.10/calendar.py", line 54, in _localized_month
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
  File "/usr/lib/python3.10/calendar.py", line 54, in <listcomp>
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
AttributeError: module 'datetime' has no attribute 'date'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
    from urllib.request import urlopen
  File "/usr/lib/python3.10/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/lib/python3.10/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.10/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.10/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.10/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.10/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python3.10/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/usr/lib/python3.10/calendar.py", line 52, in <module>
    class _localized_month:
  File "/usr/lib/python3.10/calendar.py", line 54, in _localized_month
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
  File "/usr/lib/python3.10/calendar.py", line 54, in <listcomp>
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
AttributeError: module 'datetime' has no attribute 'date'

Original exception was:
Traceback (most recent call last):
  File "/media/kobe/D/PARA_Projects/dualMomentum/test/createLimitOrder.py", line 2, in <module>
    import ccxt
  File "/home/kobe/.local/lib/python3.10/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/home/kobe/.local/lib/python3.10/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/home/kobe/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 64, in <module>
    import calendar
  File "/usr/lib/python3.10/calendar.py", line 52, in <module>
    class _localized_month:
  File "/usr/lib/python3.10/calendar.py", line 54, in _localized_month
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
  File "/usr/lib/python3.10/calendar.py", line 54, in <listcomp>
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
AttributeError: module 'datetime' has no attribute 'date' last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
    from urllib.request import urlopen
  File "/usr/lib/python3.10/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/lib/python3.10/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.10/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.10/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.10/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.10/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python3.10/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/usr/lib/python3.10/calendar.py", line 52, in <module>
    class _localized_month:
  File "/usr/lib/python3.10/calendar.py", line 54, in _localized_month
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
  File "/usr/lib/python3.10/calendar.py", line 54, in <listcomp>
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
AttributeError: module 'datetime' has no attribute 'date'

Original exception was:
Traceback (most recent call last):
  File "/media/gladi/D/PARA_Projects/dualMomentum/test/createLimitOrder.py", line 2, in <module>
    import ccxt
  File "/home/gladi/.local/lib/python3.10/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/home/gladi/.local/lib/python3.10/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/home/gladi/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 64, in <module>
    import calendar
  File "/usr/lib/python3.10/calendar.py", line 52, in <module>
    class _localized_month:
  File "/usr/lib/python3.10/calendar.py", line 54, in _localized_month
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
  File "/usr/lib/python3.10/calendar.py", line 54, in <listcomp>
    _months = [datetime.date(2001, i+1, 1).strftime for i in range(12)]
AttributeError: module 'datetime' has no attribute 'date'
```

**Comment by carlosmiei** [comment]
Hello @Gladi-iwnl,
That's very weird I'm using roughly the same python version (3.10.8), and it's working fine on my end.

Did you update something recently? (python or some other package)

```
p binanceusdm create_limit_buy_order "BTC/USDT" 0.1 10000 --sandbox
Python v3.10.8
CCXT v2.4.42
binanceusdm.create_limit_buy_order(BTC/USDT,0.1,10000)
{'amount': 0.1,
 'average': None,
 'clientOrderId': 'x-xcKtGhcu6d419b1f9de67b12a94ec3',
 'cost': 0.0,
 'datetime': '2022-12-20T15:44:21.626Z',
 'fee': None,
 'fees': [],
 'filled': 0.0,
 'id': '3265824380',
 'info': {'avgPrice': '0.00000',
          'clientOrderId': 'x-xcKtGhcu6d419b1f9de67b12a94ec3',
          'closePosition': False,
          'cumQty': '0',
          'cumQuote': '0',
          'executedQty': '0',
          'orderId': '3265824380',
          'origQty': '0.100',
          'origType': 'LIMIT',
          'positionSide': 'BOTH',
          'price': '10000',
          'priceProtect': False,
          'reduceOnly': False,
          'side': 'BUY',
          'status': 'NEW',
          'stopPrice': '0',
          'symbol': 'BTCUSDT',
          'timeInForce': 'GTC',
          'type': 'LIMIT',
          'updateTime': '1671551061626',
          'workingType': 'CONTRACT_PRICE'},
 'lastTradeTimestamp': None,
 'postOnly': False,
 'price': 10000.0,
 'reduceOnly': False,
 'remaining': 0.1,
 'side': 'buy',
 'status': 'open',
 'stopPrice': None,
 'symbol': 'BTC/USDT',
 'timeInForce': 'GTC',
 'timestamp': 1671551061626,
 'trades': [],
 'type': 'limit'}
```

**Comment by Gladi-iwnl** [comment]
I replaced my api-keys with newly generated once and it works as intended. My api-keys were probably expired, sorry!
