### ISSUE TITLE
AscendEX fetch_markets() TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#16162]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 2.4.43

```
exchange = ccxt.ascendex()
exchange.fetch_markets()
```

```
Traceback (most recent call last):
  File "/home/xyz/test.py", line 4, in <module>
    exchange.fetch_markets()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/ascendex.py", line 573, in fetch_markets
    symbol = base + '/' + quote
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by carlosmiei** [comment]
Hello @JovianMoon thanks, we are on it
