### ISSUE TITLE
Bigone can not find price data for specific one trading pair.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16194]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 PRO
- Programming Language version: node.js (ver 19.2.0)
- CCXT version: 2.4.55

```
const ccxt = require('ccxt');
console.log(ccxt.version);

if (process.argv.length != 4)
{
console.error('Usage: BTC/USDT 0.5');
console.error('Get Aggregrated Order book for [pair1] with step1');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, pair1, step1] = process.argv;

let exchange = new ccxt.bigone
({
adjustForTimeDifference: true,
defaultType: 'spot',
'fetchCurrencies': true,
'verbose': true,
'userAgent': {
'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
}
});

const aggregateOrderBookSide = function (orderbookSide, precision = undefined)
{
const result = [];
const amounts = {};
for (let i = 0; i < orderbookSide.length; i++)
{
const ask = orderbookSide[i];
let price = ask[0];
if (precision !== undefined)
{
price = ccxt.decimalToPrecision(price, ccxt.ROUND, precision, ccxt.TICK_SIZE);
}
amounts[price] = (amounts[price] || 0) + ask[1]; }
Object.keys(amounts).forEach(price =>
{
result.push([parseFloat(price), amounts[price]])
})
return result
}

const aggregateOrderBook = function (orderbook, precision = undefined)
{
let asks = aggregateOrderBookSide(orderbook['asks'], precision);
let bids = aggregateOrderBookSide(orderbook['bids'], precision);
return {'asks': ccxt.sortBy(asks, 0), 'bids': ccxt.sortBy(bids, 0, true),
'timestamp': orderbook['timestamp'],'datetime': orderbook['datetime'],
'nonce': orderbook['nonce'],};
};

async function aggPair1Orderbook(pair1, step1)
{
await exchange.loadMarkets();
const orderbook = await exchange.fetchOrderBook(pair1);
const step = step1;
const agg_order_book = aggregateOrderBook(orderbook, step);
if (typeof agg_order_book !== 'undefined')
{
const json_orderbook = JSON.stringify(agg_order_book);
console.log(json_orderbook);
}
else
{
const obj_orderbook0 = ({ 'Symbol': pair1, 'Data': [] });
const json_orderbook0 = JSON.stringify(obj_orderbook0);
console.log(json_orderbook0);
}};

aggPair1Orderbook(pair1, step1);

```

```
C:\ArbitApps\CCXT\CCXTNodeByFunctions>node bigone_aggPair1OrderBook.js ONE/USDT 0.00001
2.4.55
fetch Request:
 bigone GET https://big.one/api/v3/asset_pairs
RequestHeaders:
 { 'User-Agent': 'ccxt/bigone-v3' }
RequestBody:
 undefined

handleRestResponse:
 bigone GET https://big.one/api/v3/asset_pairs 200 OK
ResponseHeaders:
......
ResponseBody:
 {"code":0,"data":[{"id":"007b24e6-1e27-4a2f-b4a0-247b4b1f39ee","name":"MOB-BTC","quote_scale":6,"quote_asset":{"id":"0df9c3c3-255a-46d7-ab82-dedae169fba9","symbol":"BTC","name":"Bitcoin"},"base_asset":{"id":"3327b9e8-8a25-4e51-bd41-8e6d1b007280","symbol":"MOB","name":"Mobilecoin"},"base_scale":2,"min_quote_value":"0.0001","max_quote_value":"35"},{"id":"0086647a-30fc-43e0-8843-ce627d085b71","name":"FTM5S-USDT","quote_scale":5,"quote_asset":{"id":"17082d1c-0195-4fb6
......
b4fd-8051b2655406","name":"GALA3S-USDT","quote_scale":5,"quote_asset":{"id":"17082d1c-0195-4fb6-8779-2cdbcb9eeb3c","symbol":"USDT","name":"TetherUS"},"base_asset":{"id":"99fa6705-85d9-4d33-8e12-8d054225e6ee","symbol":"GALA3S","name":"GALA3S"},"base_scale":2,"min_quote_value":"10","max_quote_value":"500000"},{"id":"ffff7b8c-ad20-4ced-a356-c5e785b40322","name":"LOOKS-USDT","quote_scale":4,"quote_asset":{"id":"17082d1c-0195-4fb6-8779-2cdbcb9eeb3c","symbol":"USDT","name":"TetherUS"},"base_asset":{"id":"a1622cca-242b-4a18-938f-f58468d84454","symbol":"LOOKS","name":"LooksRare Token"},"base_scale":3,"min_quote_value":"10","max_quote_value":"500000"}]}


C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:2540
        throw new BadSymbol (this.id + ' does not have market symbol ' + symbol);
              ^

BadSymbol: bigone does not have market symbol ONE/USDT
    at bigone.market (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:2540:15)
    at bigone.fetchOrderBook (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\bigone.js:457:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async aggPair1Orderbook (C:\ArbitApps\CCXT\CCXTNodeByFunctions\bigone_aggPair1OrderBook.js:56:19) {
  constructor: [class BadSymbol extends BadRequest]
}

Node.js v19.2.0

C:\ArbitApps\CCXT\CCXTNodeByFunctions>node bigone_fetch1Currency.js ONE
{"id":"ONE","code":"BigONE Token","precision":0.01}
```

Hello:
I used CCXT aggregrate price function to get one pair trading price for ONE/USDT, but I got nothing.  For some big trading pairs, like: BTC/USDT, ETH/USDT, the code works well. And I can get some information about the symbol 'ONE', besides, I logon to web site, I can see the pair ONE/USDT seems very actively trading pair. So, it should have some price data.
But I can't find any data returned by my code.
Please advise how to fix this.
Thanks,

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail 

Unfortunately, the `ONE` id clashes with another token:

https://www.binance.com/en/trade/ONE_USDT?theme=dark&type=spot
https://www.bybit.com/en-US/trade/spot/ONE/USDT

For that reason, we had to make an alias here for the unified symbols, so if you want to fetch the native `ONE` token you can do:

```Javascript
const ob1 = bigone.fetchOrderBook("BigONE Token/USDT") // unified symbol
const ob2 = bigone.fetchOrderBook("ONE-USDT") // exchange-specific id
```

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your information. I want to know if there is one web page where I can find most of those unified symbols?
Please advise,
Thanks,

**Comment by ttodua** [comment]
late reply here, but unified symbols can be seen with `instance.markets` (or `instance.symbols`)
