### ISSUE TITLE
When withdraw funds from exchange gate, I got error: TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16301]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.5.5

### Description

Hello:
I want to withdraw or send one token from my account in gate exchange to my wallet via CCXT node.js package. I got the following errors:
D:\CCXT>node gate_send1CoinChain1.js BTCST 1.99 0x56073fb7c776abF41A09fB0831fB8fcA53f582A2 undefined BEP20
TypeError: Cannot read properties of undefined (reading '0')
    at gate.parseTransaction (D:\CCXT\node_modules\ccxt\js\gate.js:3027:15)
    at gate.withdraw (D:\CCXT\node_modules\ccxt\js\gate.js:2976:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async send1Coin (D:\CCXT\gate_send1CoinChain1.js:26:19)

I used the same JavaScript to withdraw fund from Binance, the code works without any issue, the wallet address is the same, only the token and amount are different.
Please advise on if there is any issue with my code or with code in CCXT, remember the same code works for Binance.
Thanks,

### Code

```
const ccxt = require('ccxt');

if (process.argv.length != 7)
{
console.error('Usage: Coin1 Amount Address (Tag|undefined) (Network|undefined)');
console.error('Send Coin1 to an address with full network data');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, coin1, amount1, address1, tag1, chain1] = process.argv;

let exchange = new ccxt.gate
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': false, }
});

const send1Coin = async (coin1, amount1, address1, tag1, chain1) =>
{
try
{
const transfer1 = await exchange.withdraw(coin1, amount1, address1, tag1, {'network': chain1});
const json_transfer = JSON.stringify(transfer1);
console.log(json_transfer);
}
catch (err)
{
console.error(err);
}
};
send1Coin(coin1, amount1, address1, tag1, chain1); 

```

**Comment by sc0Vu** [comment]
@zydjohnHotmail would you like to paste the response from exchange `verbose: true`?

**Comment by zydjohnHotmail** [comment]
Hello:
I don't need to withdraw funds now, but I will try to do some withdraw maybe tomorrow.
However, there is another, what I should call it, a new exchange, actually, not so new exchange, I hope CCXT will create a new exchange library.
The following was an email from Coinbase support to me on 2022-12-31:
Please note that Coinbase Pro (including Pro APIs) will be fully sunsetted in early 2023, after all customers have been migrated.

We highly suggest using the new Advance Trade feature in Coinbase Exchange. If you want to access the BTC-USDT trading pair, go to Trade on the left-hand side, then click on Advanced, then type BTC in the search bar. If the BTC/USDT trading pair is not showing it is not supported in your region. 

For more information about Advance Trade API, please check out this link: https://docs.cloud.coinbase.com/advanced-trade-api/docs/welcome

According to their email, the old Coinbase, Coinbase PRO will be phrased out at the earily of 2023, they will merge all the exchanges to make a new one, called "advanced trade", and they have new API.
I created a new exchange request, but I can't find it any more.
Can someone from CCXT library spend some time to study the new API and create a new exchange for CCXT?
I think since CCXT had Coinbase and Coinbase PRO before, to make a new one is not very difficult.
Thanks!

**Comment by ttodua** [comment]
closing old issue.
let us know if anyone still experiences any problems.
