### ISSUE TITLE
Handling error responses in createOrder and fetchTrades for Kucoin

### ISSUE THREAD

**Issue by hippylover** [ccxt/ccxt#1633]
on kucoin when buying with ETH:
```
Traceback (most recent call last):
  File "orderbook_qt11.py", line 2967, in buyStuff
    result = runCcxt(Sharedvars.exchange, "createLimitBuyOrder", Sharedvars.coin, float(amount), float(price))
  File "orderbook_qt11.py", line 81, in runCcxt
    orderResult = exchanges[ex].createLimitBuyOrder(symbol, amount, price)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1033, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "/usr/lib/python3.6/site-packages/ccxt/kucoin.py", line 383, in create_order
    'id': self.safe_string(response['data'], 'orderOid'),
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 436, in safe_string
    return str(dictionary[key]) if key is not None and (key in dictionary) and dictionary[key] is not None else default_value
TypeError: argument of type 'NoneType' is not iterable
```

on kucoin just when fetching trades. only happens when it doesn't get response i guess.
```
Traceback (most recent call last):
  File "orderbook_qt11.py", line 2579, in getOrderBookAndTrades
    trades = self.getTrades(ex, symbol)
  File "orderbook_qt11.py", line 2526, in getTrades
    trades = runCcxt(ex, "fetchTrades", symbol)
  File "orderbook_qt11.py", line 178, in runCcxt
    trades = exchanges[ex].fetchTrades(Sharedvars.coin)
  File "/usr/lib/python3.6/site-packages/ccxt/kucoin.py", line 478, in fetch_trades
    market = self.market(symbol)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 962, in parse_trades
    array = [self.parse_trade(trade, market) for trade in array]
TypeError: 'NoneType' object is not iterable
```

I can work on these if noone else is working on it? kroitor?

**Comment by kroitor** [comment]
> on kucoin just when fetching trades. only happens when it doesn't get response i guess.

Would be helpful if you could show verbose output with their reply as [described here](
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue).

> I can work on these if noone else is working on it? kroitor?

Sure! Just make sure it is consistent with the `handleErrors()` callchain – see other exchanges as well for examples on that. Thx!
