### ISSUE TITLE
bittrex load_markets fails 

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#16335]
### Operating System

linux

### Programming Languages

python

### CCXT Version

 2.5.30

### Description

with the update of ccxt from 2.4.60 to 2.5.30 (actually already to 2.5.5 ) - we're now seeing CI failures on bittrex (active tests).

https://api.bittrex.com/v3/markets?settle=usdt is clearly not a valid request against the bittrex API - but the interesting thing is - that's not happening on my system (europe/asia IP's). 
this request is never made in this form - only without the "settle" parameter.

CI however runs in the US, so it might be relevant to that.

```
ERROR    freqtrade.exchange.exchange:exchange.py:493 Unable to initialize markets.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ccxt/base/exchange.py", line 622, in fetch
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bittrex.com/v3/markets?settle=usdt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/freqtrade/freqtrade/freqtrade/exchange/exchange.py", line 486, in _load_markets
    self._markets = self._api.load_markets()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1457, in load_markets
    markets = self.fetch_markets(params)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ccxt/bittrex.py", line 319, in fetch_markets
    response = self.publicGetMarkets(params)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in inner
    return entry(_self, **inner_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2813, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2810, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ccxt/base/exchange.py", line 638, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ccxt/bittrex.py", line 2009, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3108, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: bittrex {"code":"BAD_REQUEST","detail":"Refer to the data field for specific field validation failures.","data":{"invalidRequestParameter":"settle"}}
```

### Code

A simple reproduction of the code that's running is the following - though it doesn't raise this error locally.

``` python
import ccxt
exchange = ccxt.bittrex()
_ = exchange.load_markets()
```

**Comment by Sewake** [comment]
We have the exact same issue on our server, and we figured out what was the problem, we discovered the issue with Binance.

In **ccxt/async_support/base/exchange.py** there is this function:
    `async def load_markets_helper(self, reload=False, params={}):`
    
As you can see, there is a mutable as a default parameter in the function, which can lead into unexpected behaviors. If you do a request with another exchange it might change the state of the mutable object.

Here a way to reproduce it at 100% (even locally):
```
import ccxt.pro as ccxtpro
import asyncio
asyncio_loop = asyncio.get_event_loop()

for exch_id in ["gateio", "binance", "bittrex"]:
    exchange = getattr(ccxtpro, exch_id)()
    exchange.verbose = True
    m = asyncio_loop.run_until_complete(exchange.load_markets())
```


The logs (with `verbose=True`)

```
fetch Request: binance GET https://api.binance.com/api/v3/exchangeInfo?settle=usdt RequestHeaders: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: binance GET https://api.binance.com/api/v3/exchangeInfo?settle=usdt 400 ResponseHeaders: {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '97', 'Connection': 'keep-alive', 'Date': 'Fri, 06 Jan 2023 17:50:27 GMT', 'Server': 'nginx', 'x-mbx-uuid': '26fa6111-aa63-4bc1-b270-3d427e154859', 'x-mbx-used-weight': '1', 'x-mbx-used-weight-1m': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 6d865250c628e9708a223a07778aa5b8.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'CDG52-P1', 'X-Amz-Cf-Id': 'vXVsorON1OWOc6pA34W3xOOOlvmxF9k3pxBCPyFrP1ak_kuTnFW7tA=='} ResponseBody: {"code":-1104,"msg":"Not all sent parameters were read; read '0' parameter(s) but was sent '1'."}

---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
Cell In[1], line 8
      6 exchange = getattr(ccxtpro, exch_id)()
      7 exchange.verbose = True
----> 8 m = asyncio_loop.run_until_complete(exchange.load_markets())

File /usr/local/lib/python3.8/asyncio/base_events.py:616, in BaseEventLoop.run_until_complete(self, future)
    613 if not future.done():
    614     raise RuntimeError('Event loop stopped before Future completed.')
--> 616 return future.result()

File ~/venv/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py:194, in Exchange.load_markets(self, reload, params)
    192     self.reloading_markets = False
    193     self.markets_loading = None
--> 194     raise e
    195 self.reloading_markets = False
    196 return result

File ~/venv/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py:190, in Exchange.load_markets(self, reload, params)
    188     self.markets_loading = asyncio.ensure_future(coroutine)
    189 try:
--> 190     result = await self.markets_loading
    191 except Exception as e:
    192     self.reloading_markets = False

File ~/venv/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py:180, in Exchange.load_markets_helper(self, reload, params)
    178 if self.has['fetchCurrencies'] is True:
    179     currencies = await self.fetch_currencies()
--> 180 markets = await self.fetch_markets(params)
    181 return self.set_markets(markets, currencies)

File ~/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py:1614, in binance.fetch_markets(self, params)
   1612 elif delivery:
   1613     method = 'dapiPublicGetExchangeInfo'
-> 1614 response = await getattr(self, method)(query)
   1615 #
   1616 # spot / margin
   1617 #
   (...)
   1762 #     }
   1763 #
   1764 if self.options['adjustForTimeDifference']:

File ~/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py:6042, in binance.request(self, path, api, method, params, headers, body, config, context)
   6041 async def request(self, path, api='public', method='GET', params={}, headers=None, body=None, config={}, context={}):
-> 6042     response = await self.fetch2(path, api, method, params, headers, body, config, context)
   6043     # a workaround for {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
   6044     if (api == 'private') or (api == 'wapi'):

File ~/venv/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py:1299, in Exchange.fetch2(self, path, api, method, params, headers, body, config, context)
   1297 self.lastRestRequestTimestamp = self.milliseconds()
   1298 request = self.sign(path, api, method, params, headers, body)
-> 1299 return await self.fetch(request['url'], request['method'], request['headers'], request['body'])

File ~/venv/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py:163, in Exchange.fetch(self, url, method, headers, body)
    160     details = ' '.join([self.id, method, url])
    161     raise ExchangeError(details) from e
--> 163 self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    164 self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
    165 if json_response is not None:

File ~/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py:6020, in binance.handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   6013     if message == 'No need to change margin type.':
   6014         # not an error
   6015         # https://github.com/ccxt/ccxt/issues/11268
   6016         # https://github.com/ccxt/ccxt/pull/11624
   6017         # POST https://fapi.binance.com/fapi/v1/marginType 400 Bad Request
   6018         # binanceusdm {"code":-4046,"msg":"No need to change margin type."}
   6019         raise MarginModeAlreadySet(feedback)
-> 6020     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
   6021     raise ExchangeError(feedback)
   6022 if not success:

File ~/venv/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py:1597, in Exchange.throw_exactly_matched_exception(self, exact, string, message)
   1595 def throw_exactly_matched_exception(self, exact, string, message):
   1596     if string in exact:
-> 1597         raise exact[string](message)

BadRequest: binance {"code":-1104,"msg":"Not all sent parameters were read; read '0' parameter(s) but was sent '1'."}
```


@xmatthias You are probably loading markets with another exchange (such as gate.io) before loading bittrex markets.

**Comment by KevinBaudin** [comment]
Just to add something, here in ccxt/async_support/gate.py:

```
    async def fetch_contract_markets(self, params):
        result = []
        swapSettlementCurrencies = self.get_settlement_currencies('swap', 'fetchMarkets')
        futureSettlementCurrencies = self.get_settlement_currencies('future', 'fetchMarkets')
        for c in range(0, len(swapSettlementCurrencies)):
            settleId = swapSettlementCurrencies[c]
            query = params
            query['settle'] = settleId
            response = await self.publicFuturesGetSettleContracts(query)
            for i in range(0, len(response)):
                parsedMarket = self.parse_contract_market(response[i], settleId)
                result.append(parsedMarket)
        for c in range(0, len(futureSettlementCurrencies)):
            settleId = futureSettlementCurrencies[c]
            query = params
            query['settle'] = settleId
            response = await self.publicDeliveryGetSettleContracts(query)
            for i in range(0, len(response)):
                parsedMarket = self.parse_contract_market(response[i], settleId)
                result.append(parsedMarket)
        return result
```

I'm pretty sure you do a mutation on params when doing query=params then query["settle"] = ...

See @Sewake example, we see the binance receive a `settle=usdt` in its query, which is not supported and then returns an error.

@frosty00 Since I see you are working on gate, please consider this

Again, thanks for your great job :pray:

**Comment by leastchaos** [comment]
I also faced this unexpected error after updating to latest. I think this should be fixed.

**Comment by xmatthias** [comment]
That's a nice spot!

in general, i found using mutable objects in function headers to be pretty dangerous in python in general (i ran into this several times in the past), as they are only read once at import time - and it's content may change over time.

I don't think it's limited to gate - but can potentially occur with every method / exchange combination.

> To fix this, I would replace all the places in the code that use a mutable as a default parameter (like: params={}) with params=None.

This will work if done from within ccxt - but in user code this may not be possible in it's entirety, as there's multiple "empty" `self.load_markets()` calls within the ccxt codebase, which is called implicitly when calling other functions.
