### ISSUE TITLE
Crypto.com private requests timeout for subaccounts

### ISSUE THREAD

**Issue by Sebastiaan240** [ccxt/ccxt#16362]
### Operating System

Windows 11

### Programming Languages

python

### CCXT Version

2.5.32

### Description

All private requests using a subaccount on crypto.com, result in a timeout.
Public requests and private requests to the master account work fine.

An example is the fetch_balance() method, where I get the balances as expected from the master account but the subaccount gives a timeout.

### Code

Code:
```
import ccxt

master_key = [INSERT KEY]
master_secret = [INSERT SECRET]

sub_key = [INSERT KEY]
sub_secret = [INSERT SECRET]

master_client = ccxt.cryptocom({'apiKey': master_key,
                                'secret': master_secret,
                                'verbose': True})
sub_client = ccxt.cryptocom({'apiKey': sub_key,
                             'secret': sub_secret,
                             'verbose': True})

print("Loading master markets")
master_client.load_markets()
print("Loading client markets")
sub_client.load_markets()

# No problems so far

print("Getting master balances")
master_client.fetch_balance()
print("Getting sub balances")
sub_client.fetch_balance()
```

Output:
```
Loading master markets

fetch Request: cryptocom GET https://api.crypto.com/v2/public/get-instruments RequestHeaders: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: cryptocom GET https://api.crypto.com/v2/public/get-instruments 200 ResponseHeaders: {'Date': 'Fri, 06 Jan 2023 13:48:01 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'CF-Ray': '7854e8ad3ee30be3-AMS', 'Strict-Transport-Security': 'max-age=31536000', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Accept-Encoding', 'Via': 'kong/2.8.1', 'CF-Cache-Status': 'DYNAMIC', 'referrer-policy': 'same-origin', 'x-content-type-options': 'nosniff', 'x-frame-options': 'sameorigin', 'x-kong-proxy-latency': '6', 'x-kong-upstream-latency': '4', 'Set-Cookie': '__cf_bm=gRHcV03j7_c22kdNI1gXPDIiRRXNzrUTG_5P7l9RTJk-1673012881-0-AYX0t0QqzcqygtDgXA5/BX91UqrzhDCuglGHPgNqeXs44pyn3XbB/gBvU0a7ts1xn/MlTKRAeNUUUMJPnOt83zM=; path=/; expires=Fri, 06-Jan-23 14:18:01 GMT; domain=.crypto.com; HttpOnly; Secure; SameSite=None, _cfuvid=dAKx8VK3xhWjmW_ngZa4ovnooUQyIOknAXDUHv1MJdU-1673012881696-0-604800000; path=/; domain=.crypto.com; HttpOnly; Secure; SameSite=None', 'Server-Timing': 'cf-q-config;dur=5.9999999848515e-06', 'Server': 'cloudflare', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: 

fetch Request: cryptocom GET https://deriv-api.crypto.com/v1/public/get-instruments RequestHeaders: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: cryptocom GET https://deriv-api.crypto.com/v1/public/get-instruments 200 ResponseHeaders: {'Date': 'Fri, 06 Jan 2023 13:48:03 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'CF-Ray': '7854e8b90ed30e3d-AMS', 'Access-Control-Allow-Origin': 'https://crypto.com', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Accept-Encoding', 'CF-Cache-Status': 'DYNAMIC', 'content-security-policy': "default-src 'self' https: wss: data: 'unsafe-inline' 'unsafe-eval'", 'X-Permitted-Cross-Domain-Policies': 'master-only', 'X-XSS-Protection': '1; mode=block', 'Set-Cookie': '__cf_bm=xA6w2Vlum_a2yejuN4pX.OD93VDh9pS0tjcBSnO73zU-1673012883-0-AX5xAtW1gFJKWFHyP+Hz/36GaJP7GmVTnddaDTXNEYg1xpWlF2WRzGJ0rSfFjyoeo/uasdqZlFA3J4aLkzdDxU8=; path=/; expires=Fri, 06-Jan-23 14:18:03 GMT; domain=.crypto.com; HttpOnly; Secure; SameSite=None, __cfruid=7670964986225a204b0efea5c291a411b505f93e-1673012883; path=/; domain=.crypto.com; HttpOnly; Secure; SameSite=None, _cfuvid=BGFXRSn6lGsgb6Cav1rUrjAAaiPCw5mYH_yG9fVCG28-1673012883587-0-604800000; path=/; domain=.crypto.com; HttpOnly; Secure; SameSite=None', 'Server-Timing': 'cf-q-config;dur=6.0000002122251e-06', 'Server': 'cloudflare', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: 
Loading client markets

fetch Request: cryptocom GET https://api.crypto.com/v2/public/get-instruments RequestHeaders: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: cryptocom GET https://api.crypto.com/v2/public/get-instruments 200 ResponseHeaders: {'Date': 'Fri, 06 Jan 2023 13:48:06 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'CF-Ray': '7854e8c949580bb9-AMS', 'Strict-Transport-Security': 'max-age=31536000', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Accept-Encoding', 'Via': 'kong/2.8.1', 'CF-Cache-Status': 'DYNAMIC', 'referrer-policy': 'same-origin', 'x-content-type-options': 'nosniff', 'x-frame-options': 'sameorigin', 'x-kong-proxy-latency': '5', 'x-kong-upstream-latency': '3.9999980926514', 'Set-Cookie': '__cf_bm=xHWXqaNls1CiKbs7zy96ZERlEKfV2ZiWuRdLStZQ3IM-1673012886-0-AVMxykmdWQ6MqWgmjAjphLicmaFGGLyEfkWNmNBiwZQYontlg7v9ZpQAXtO9MGI0k2nCPFiO5dvZXNiqa5kShJk=; path=/; expires=Fri, 06-Jan-23 14:18:06 GMT; domain=.crypto.com; HttpOnly; Secure; SameSite=None, _cfuvid=BYNcgnDK284yeLJTtr4i89ETyOexSbNQJVJbhP8DLig-1673012886197-0-604800000; path=/; domain=.crypto.com; HttpOnly; Secure; SameSite=None', 'Server-Timing': 'cf-q-config;dur=7.0000023697503e-06', 'Server': 'cloudflare', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: 

fetch Request: cryptocom GET https://deriv-api.crypto.com/v1/public/get-instruments RequestHeaders: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: cryptocom GET https://deriv-api.crypto.com/v1/public/get-instruments 200 ResponseHeaders: {'Date': 'Fri, 06 Jan 2023 13:48:08 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'CF-Ray': '7854e8d518890ae3-AMS', 'Access-Control-Allow-Origin': 'https://crypto.com', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Accept-Encoding', 'CF-Cache-Status': 'DYNAMIC', 'content-security-policy': "default-src 'self' https: wss: data: 'unsafe-inline' 'unsafe-eval'", 'X-Permitted-Cross-Domain-Policies': 'master-only', 'X-XSS-Protection': '1; mode=block', 'Set-Cookie': '__cf_bm=_j8m7wjXpyiYgDTsGQdl6bm47KcEmHxGyJuMmWpIK_U-1673012888-0-AUFNE9HrU7c3J1B07vxAGc6VOKXwIZ8pJNbMpS14b8zWCJY7nPOYlE7DW+hT6089hquqA1uLfZeMpPHhYWovnlo=; path=/; expires=Fri, 06-Jan-23 14:18:08 GMT; domain=.crypto.com; HttpOnly; Secure; SameSite=None, __cfruid=98768b258698fac95feeb06612ee305774a6fd5d-1673012888; path=/; domain=.crypto.com; HttpOnly; Secure; SameSite=None, _cfuvid=1_XW8gn.cRwVlRyXUuGr1Ssy6s5bQrXduFbt6tdg4R8-1673012888091-0-604800000; path=/; domain=.crypto.com; HttpOnly; Secure; SameSite=None', 'Server-Timing': 'cf-q-config;dur=1.2000004062429e-05', 'Server': 'cloudflare', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: 
Getting master balances

fetch Request: cryptocom POST https://api.crypto.com/v2/private/get-account-summary RequestHeaders: {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"id":"1673012890510","method":"private/get-account-summary","params":{},"api_key":"fohZijnDaMqHF6r3G9bZwP","sig":"ac0bd7143e30a3c9b46d9b9b944f94c27f492761887b05499d1a0d9ea30cc571","nonce":"1673012890510"}

fetch Response: cryptocom POST https://api.crypto.com/v2/private/get-account-summary 200 ResponseHeaders: {'Date': 'Fri, 06 Jan 2023 13:48:10 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'CF-Ray': '7854e8e64d700be3-AMS', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Expires': '0', 'Set-Cookie': 'AWSALB=vUbnos56LoMyjKaTbzgkdtXe5SWBipP+mLCXDr7nl1zAiGdvrU3xONk1woyaBh2sKYSgj/+g2tanhsyMtbpV7q3nAzKjSOAotO+UEVgGSJPBQLI/U0c1gs9QGmNj; Expires=Fri, 13 Jan 2023 13:48:10 GMT; Path=/, AWSALBCORS=vUbnos56LoMyjKaTbzgkdtXe5SWBipP+mLCXDr7nl1zAiGdvrU3xONk1woyaBh2sKYSgj/+g2tanhsyMtbpV7q3nAzKjSOAotO+UEVgGSJPBQLI/U0c1gs9QGmNj; Expires=Fri, 13 Jan 2023 13:48:10 GMT; Path=/; SameSite=None, __cf_bm=wQ0D.r.IYgs5CZgEBDCCCoEzAX4Fq2IAv5PEPTBg5Nw-1673012890-0-Ab4focLPKCkyXuMlbmr6gEuRVb2geqBzvggWLo4fZeSNJITOAd+Lw/NNeaOq83iYikfKG4uD56oahDvHqoEEr+E=; path=/; expires=Fri, 06-Jan-23 14:18:10 GMT; domain=.crypto.com; HttpOnly; Secure; SameSite=None, _cfuvid=0UaGtK4jL8fGL_jpI1snP43.zgtNIubseE8LY0KhxJM-1673012890839-0-604800000; path=/; domain=.crypto.com; HttpOnly; Secure; SameSite=None', 'Strict-Transport-Security': 'max-age=31536000', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Accept-Encoding', 'Via': 'kong/2.8.1', 'CF-Cache-Status': 'DYNAMIC', 'pragma': 'no-cache', 'referrer-policy': 'no-referrer', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-kong-proxy-latency': '6', 'x-kong-upstream-latency': '8', 'x-xss-protection': '1 ; mode=block', 'Server-Timing': 'cf-q-config;dur=7.9999999798019e-06', 'Server': 'cloudflare', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: 
Getting sub balances

fetch Request: cryptocom POST https://api.crypto.com/v2/private/get-account-summary RequestHeaders: {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"id":"1673012891137","method":"private/get-account-summary","params":{},"api_key":"X7oy6XgaQQo9ApNQMSTnCL","sig":"06ea73c0d2e7ca8184170fd072fe07f0fa145408811987860daad52cbf43e557","nonce":"1673012891137"}
Traceback (most recent call last):
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.crypto.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 596, in fetch
    response = self.session.request(
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.crypto.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\swach\Dropbox\Zakelijk\WCM\Code\small_tests\cryptocom_bug\catch_cryptocom_bug.py", line 32, in <module>
    sub_client.fetch_balance()
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\cryptocom.py", line 881, in fetch_balance
    response = getattr(self, method)(query)
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 502, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 2813, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 2810, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\swach\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 626, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: cryptocom POST https://api.crypto.com/v2/private/get-account-summary
```

**Comment by carlosmiei** [comment]
Hello @Sebastiaan240,
Weird I just tested and managed to get the sub-account balance correctly. Is there anything else you can share with us that could help us reproduce the issue? Are you sure your sub-account API keys are valid and have the right permissions? 

```     
cryptocom.fetchBalance ()
2023-01-06T16:11:57.794Z iteration 0 passed in 407 ms

{
  info: {
    id: '121517324234416',
    method: 'private/get-account-summary',
    code: '0',
    result: {
      accounts: [
        {
          stake: '0',
          balance: '6',
          available: '6',
          currency: 'USDT',
          order: '0'
        }
      ]
    }
  },
  USDT: { free: 6, used: 0, total: 6 },
  free: { USDT: 6 },
  used: { USDT: 0 },
  total: { USDT: 6 }
}
```

**Comment by Sebastiaan240** [comment]
Hello @carlosmiei,

Thank you for looking into this. I discussed this with crypto.com and it turned out to be a bug on their side that made it seems like our subaccounts don’t exist. They have fixed it now.
