### ISSUE TITLE
Bkex fetch tickers not working for version 2.5.90

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16445]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.5.90

### Description

Hello:
I used to be able to fetch all tickers for many exchanges, including bkex.  But suddenly, the new version stops working for bkex.
The following is the output for my code:
C:\CCXT>node bkex_fetchTickers.js
2.5.90
fetch Request:
 bkex GET https://api.bkex.com/v2/common/currencys
RequestHeaders:
 {}
RequestBody:
 undefined

RequestTimeout: bkex GET https://api.bkex.com/v2/common/currencys request timed out (10000 ms)
    at C:\CCXT\node_modules\ccxt\js\base\Exchange.js:441:27
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
    at async bkex.fetch2 (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2023:16)
    at async bkex.request (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2027:16)
    at async bkex.fetchCurrencies (C:\CCXT\node_modules\ccxt\js\bkex.js:404:26)
    at async bkex.loadMarketsHelper (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:629:26)
    at async bkex.fetchTickers (C:\CCXT\node_modules\ccxt\js\bkex.js:692:9)
    at async fetchTickers (C:\CCXT\bkex_fetchTickers.js:15:17) {
  constructor: [class RequestTimeout extends NetworkError]
}

C:\CCXT>

### Code

```
const ccxt = require('ccxt');
console.log(ccxt.version);

let exchange = new ccxt.bkex
({'adjustForTimeDifference': true,
defaultType: 'spot',
'verbose': true });

const fetchTickers = async() => 
{
try
{
if (exchange.has['fetchTickers'])
{
const tickers = await exchange.fetchTickers();
if (typeof tickers !== 'undefined')
{
const json_tickers = JSON.stringify(tickers);
console.log(json_tickers);
}
else
{
const obj_jsonTicker0 = ({ 'Data': []});
const json_ticker0 = JSON.stringify(obj_jsonTicker0);
console.log(json_ticker0);
}
}
}
catch (err)
{
console.error(err)
}
};
fetchTickers();
```

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail 

Looks like there was network issue (timeout error). Would you like to check your network settings and test again?
