### ISSUE TITLE
Api key not found for phemex

### ISSUE THREAD

**Issue by jbarber2016** [ccxt/ccxt#16501]
### Operating System

MacOS

### Programming Languages

python

### CCXT Version

2.6.22

### Description

I am doing basic test with Phemex.  I created an API Key and secret, but when I do that I get the following error (I removed the key stated in the error:

What am I doing wrong?

CCXT Version: 2.6.22
Traceback (most recent call last):
  File "/Users/jonathanbarber/tmp/trading/phemex.py", line 15, in <module>
    balance = exchange.fetch_balance()
  File "/Users/jonathanbarber/Library/Python/3.9/lib/python/site-packages/ccxt/phemex.py", line 1565, in fetch_balance
    response = getattr(self, method)(self.extend(request, params))
  File "/Users/jonathanbarber/Library/Python/3.9/lib/python/site-packages/ccxt/base/exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/jonathanbarber/Library/Python/3.9/lib/python/site-packages/ccxt/base/exchange.py", line 2816, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/Users/jonathanbarber/Library/Python/3.9/lib/python/site-packages/ccxt/base/exchange.py", line 2813, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/jonathanbarber/Library/Python/3.9/lib/python/site-packages/ccxt/base/exchange.py", line 667, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/jonathanbarber/Library/Python/3.9/lib/python/site-packages/ccxt/phemex.py", line 3483, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], message, feedback)
  File "/Users/jonathanbarber/Library/Python/3.9/lib/python/site-packages/ccxt/base/exchange.py", line 3121, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.AuthenticationError: phemex {"msg":"Api key not found XXXXXX","code":10500}

### Code

```
import ccxt
import config as cfg

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.phemex({
    'enableRateLimit': True,
    'apiKey': cfg.PHEMEX_API_KEY,
    'secret': cfg.PHEMEX_SECRET_KEY
})

#ob = cb.fetch_order_book('ETH/USDT')

balance = exchange.fetch_balance()
print(balance)

```

**Comment by sc0Vu** [comment]
Hi @jbarber2016,

It worked for me, would you like do check your config or api key?

**Comment by jbarber2016** [comment]
@sc0Vu Here's what I am doing in Phemex.  First I use google authentication to login.  Second, I bind to google authenticator because that's where I get the secret key.  Third, I generate the api key under api maanagement.  I use the default option, give it trading permissions, enter the binding ip (my public ip), and create.  I copied the api key from that window into python.  So, apparently I am doing something wrong, does any of this match with what you did?

**Comment by tb00723** [comment]
> @sc0Vu Here's what I am doing in Phemex. First I use google authentication to login. Second, I bind to google authenticator because that's where I get the secret key. Third, I generate the api key under api maanagement. I use the default option, give it trading permissions, enter the binding ip (my public ip), and create. I copied the api key from that window into python. So, apparently I am doing something wrong, does any of this match with what you did?

i have the same problem did u fix it?
