### ISSUE TITLE
Gateio market order issue

### ISSUE THREAD

**Issue by cagriKarakulak** [ccxt/ccxt#16506]
### Operating System

windows 10

### Programming Languages

python

### CCXT Version

2.6.25

### Description

I keep getting this issue even if I increase the amount:

version: 2.6.25
qty: 0.012968570668983718
Traceback (most recent call last):
  File "C:\Users\cagri\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 625, in fetch
    response.raise_for_status()
  File "C:\Users\cagri\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.gateio.ws/api/v4/spot/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\cagri\Desktop\Gateio\hunter.py", line 51, in <module>
    order = exchange.create_order("ETH/USDT", "market", "buy", qty)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cagri\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\gate.py", line 3095, in create_order
    response = getattr(self, method)(self.deep_extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cagri\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cagri\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 2816, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cagri\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 2813, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cagri\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 641, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cagri\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\gate.py", line 4698, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], label, feedback)
  File "C:\Users\cagri\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 3116, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: gateio {"label":"INVALID_PARAM_VALUE","message":"Your order size 0.0000 ETH is too small. The minimum is 0.001 ETH"}

### Code

```
print("version:",ccxt.__version__)
currentPrice = float(exchange.fetch_ticker("ETH/USDT")["info"]["last"])
qty = 20 / currentPrice
print("qty:", qty)
order = exchange.create_order("ETH/USDT", "market", "buy", qty)
print(order)

```

**Comment by carlosmiei** [comment]
Hello @cagriKarakulak, that is, in fact, weird, we will take a look. Thanks for letting us know

**Comment by cagriKarakulak** [comment]
hello, i solved the problem. interestingly, gateio seems to work differently from other exchanges. In the "amount" parameter, not the amount of the coin to be purchased, but how many USDt to purchase is entered. for example:
exchange.create_market_buy_order("TRX/USDT", 10)  = 10 trx won't buy, will buy 10 usdt worth of trx

**Comment by carlosmiei** [comment]
@cagriKarakulak yeah exactly, I will add several fixes in the linked PR shortly so the other fields, like cost,amount,price, etc are correctly calculated in these cases.

Basically, from now you have two options to place a spot market buy

Option 1:
```Python
exchange.options['createMarketBuyOrderRequiresPrice'] = False # disable the option
exchange.create_order("LTC/USDT", "market", "buy", 5) # provide the cost as the amount
```

Option 2:
```Python
exchange.create_order("LTC/USDT", "market", "buy", 0.1, 50) # by providing the amount and price ccxt calculates the cost by doing price*amount, in this case = 5 USDT

exchange.create_order("LTC/USDT", "market", "buy", 0.2 25) # this will produce the exact same order because 0.1*50 = 0.2*25. = 5 USDT so you don't need to specify the "real" price to calculate the cost you can even do amount = 5 price = 1 = 5*1 =5
```
