### ISSUE TITLE
AssertionError - watchMyTrades, watchOrders

### ISSUE THREAD

**Issue by andrewRaad94** [ccxt/ccxt#16536]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

2.2.40

### Description

Python 3.8

I keep on getting this error when using websocket channel "watchOrders" for binance. 

This started happening after i updated my ccxt version.

Sometimes it works and no error is printed, and sometimes it doesnt. I wasn't able to check whether it was for a specific instrument or not.

### Code

```

  async def method_loop(self, method):
        while True:
            try:
                response = await getattr(self.exchangeClient, method)()
                asyncio.create_task(self.on_response(method, response))
            except Exception as e:
                logging.critical(str(e))

    async def on_response(self, method, response):
            if method == 'watchMyTrades':
                try:
                    for item in response:
                        asyncio.create_task(self.safeUpload(item,'trades', item['id']))
                except Exception as e:
                    logging.warning(e)

            elif method == 'watchOrders':
                try:
                    for item in response:
                        asyncio.create_task(self.safeUpload(item,'orders'))
                except Exception as e:
                    logging.warning(e)
            return




async def main():
        methods = ['watchMyTrades','watchOrders']
        loops = [self.method_loop(method) for method in self.methods]
        await asyncio.gather(*loops)


if __name__ == '__main__':
           asyncio.run(main())


```
[2023-01-10 12:17:13,798] ERROR: default_exception_handler : Exception in callback FastClient.receive_loop.<locals>.handler() at /usr/local/lib/python3.8/site-packages/ccxt/pro/base/fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at /usr/local/lib/python3.8/site-packages/ccxt/pro/base/fast_client.py:20>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/site-packages/ccxt/pro/base/fast_client.py", line 25, in handler
    self.handle_message(message)
  File "/usr/local/lib/python3.8/site-packages/ccxt/pro/base/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/usr/local/lib/python3.8/site-packages/ccxt/pro/base/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/usr/local/lib/python3.8/site-packages/ccxt/pro/binance.py", line 1380, in handle_message
    return method(client, message)
  File "/usr/local/lib/python3.8/site-packages/ccxt/pro/binance.py", line 1237, in handle_order_update
    self.handle_my_trade(client, message)
  File "/usr/local/lib/python3.8/site-packages/ccxt/pro/binance.py", line 1296, in handle_my_trade
    order['fee']['cost'] = float(self.currency_to_precision(tradeFee['currency'], feeCost))
  File "/usr/local/lib/python3.8/site-packages/ccxt/async_support/binance.py", line 1296, in currency_to_precision
    return self.decimal_to_precision(fee, TRUNCATE, self.currencies[code]['precision'], self.precisionMode, self.paddingMode)
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/decimal_to_precision.py", line 41, in decimal_to_precision
    assert(isinstance(precision, numbers.Integral))
AssertionError

**Comment by sc0Vu** [comment]
@andrewRaad94 

That's weird, we have checked whether the `precision` is `None`. Would you like to give more detail about the `trade`, probably the fee currency?

**Comment by andrewRaad94** [comment]
Hey @sc0Vu, 

I am using these methods for an ETL project and when I look at the error time  on my database i see that the order seems to be processed. I went back into the logs and saw that this specific order was processed. It doesn't seem like the instrument is anything exotic (BTC/USDT)


![log](https://user-images.githubusercontent.com/91156153/213456662-622eb0f5-8ede-4127-b7f9-4c4dcda43f27.PNG)

![error](https://user-images.githubusercontent.com/91156153/213456102-4307d542-efe1-47c6-8934-f30f21d626d5.PNG)

![order](https://user-images.githubusercontent.com/91156153/213456871-b23d3ae4-a3fe-4bde-bb9e-9d91c80da058.PNG)



I find it somewhat strange that an order made on the same symbol had no problems 40 mins later

![second order](https://user-images.githubusercontent.com/91156153/213458990-2793e3a4-21ff-41aa-a114-52fcb20f16da.PNG)
![second log](https://user-images.githubusercontent.com/91156153/213459082-22bfe55a-fd7e-4580-8bc8-6ac23c3130f1.PNG)

**Comment by andrewRaad94** [comment]
Hey @sc0Vu @frosty00, I think i might have found the problem 

![image](https://user-images.githubusercontent.com/91156153/215162691-01bc0e12-ac75-4dad-b2d3-b5b8593c0034.png)

It seems that 

counting_mode = 2
TICK_SIZE = 4
precision = 8.0 

so when the code doesnt pass through the "IF" condition, and the its tries ASSERT(8.0, numbers.integral) which gives an error.  if you add an "or  ASSERT(precision, float)", it seems like there will be no more errors

![image](https://user-images.githubusercontent.com/91156153/215164075-ffb67a35-6d61-4e15-87f7-02c882455559.png)

**Comment by ttodua** [comment]
@andrewRaad94 
a late reply here, but can you tell, in what case `precision` could have been `8.0` (not an integer, but float)?
