### ISSUE TITLE
How to use CCXT function to send funds to uncommon network address with tag.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16573]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.6.36

### Description

Hello:
I want to send some fund (ASTRO) from my mexc3 account to another wallet address, which has both address and tag in TERRACLASSIC network.

The following was the output for the operations:
C:\CCXT>node mexc3_getCoin1Balance.js ASTRO
{"Ticker":"ASTRO","Amount":3320}

C:\CCXT>node mexc3_send1CoinChain1.js ASTRO 3319.8  terra17f0cp50wnzdgzfuqrq8qganqqkmhe2kvguw759 EAPZZqCA7QiPjn undefined
ExchangeError: mexc3 {"msg":"This withdrawal address is not on the commonly used address list or has been invalidated","code":10212}
    at mexc3.handleErrors (C:\CCXT\node_modules\ccxt\js\mexc3.js:4904:19)
    at C:\CCXT\node_modules\ccxt\js\base\Exchange.js:603:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (C:\CCXT\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async mexc3.fetch2 (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2023:16)
    at async mexc3.request (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2027:16)
    at async mexc3.withdraw (C:\CCXT\node_modules\ccxt\js\mexc3.js:4474:26)
    at async send1Coin (C:\CCXT\mexc3_send1CoinChain1.js:26:19) {
  constructor: [class ExchangeError extends BaseError]
}

C:\CCXT>node mexc3_getCoin1Balance.js ASTRO
{"Ticker":"ASTRO","Amount":3000.2}

I can send the funds from Mexc3 web page by hand without any issue.
Let me know if my code is not correct or do I have to setup something like white list address for sending such funds?
By the way, since TERRACLASSIC is not supported by CCXT, can I simply omit the network name in my Node.js script?
Please advise,
Thanks,

### Code

```
const ccxt = require('ccxt');

if (process.argv.length != 7)
{
console.error('Usage: Coin1 Amount Address (Tag|undefined) (Network|undefined)');
console.error('Send Coin1 to an address with full network data');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, coin1, amount1, address1, tag1, chain1] = process.argv;

let exchange = new ccxt.mexc3
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': false, }
});

const send1Coin = async (coin1, amount1, address1, tag1, chain1) =>
{
try
{
const transfer1 = await exchange.withdraw(coin1, amount1, address1, tag1, {'network': chain1});
const json_transfer = JSON.stringify(transfer1);
console.log(json_transfer);
}
catch (err)
{
console.error(err);
}
};
send1Coin(coin1, amount1, address1, tag1, chain1);

```

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail 

> This withdrawal address is not on the commonly used address list or has been invalidated"

⬆️ As you can see in the error message looks like the exchange is not accepting this address for some reason, you might need to whitelist it or something like that needs to be done directly in the exchange, there's nothing ccxt can do about it

**Comment by ttodua** [comment]
as question was answered already, closing this.
if anyone has any issues, let us know
