### ISSUE TITLE
Binance future websocket watch_order raise KeyError

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#16605]
### Operating System

ubuntu22.04

### CCXT Version

2.6.47

### Description

After some time, with this infinite loop:

```
while True:
        try:
            orders = await exchange.watch_orders(symbol, params={'type':'future'})
        except Exception as e:
            print(type(e), e, "watch_orders")
```

It raises that error:

```
Exception in callback FastClient.receive_loop.<locals>.handler() at /python3.9/site-packages/ccxt/pro/base/fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at /python3.9/site-packages/ccxt/pro/base/fast_client.py:20>
Traceback (most recent call last):
  File "/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/python3.9/site-packages/ccxt/pro/base/fast_client.py", line 25, in handler
    self.handle_message(message)
  File "/python3.9/site-packages/ccxt/pro/base/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/python3.9/site-packages/ccxt/pro/base/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/python3.9/site-packages/ccxt/pro/binance.py", line 1572, in handle_message
    return method(client, message)
  File "/python3.9/site-packages/ccxt/pro/binance.py", line 1416, in handle_order_update
    self.handle_order(client, message)
  File "/python3.9/site-packages/ccxt/pro/binance.py", line 1527, in handle_order
    cachedOrders.append(parsed)
  File "/python3.9/site-packages/ccxt/pro/base/cache.py", line 145, in append
    del self.hashmap[delete_item['symbol']][delete_item['id']]
KeyError: 'BTC/USDT'
```

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @nikky78,

Binance was updated recently, so it works better with unified symbols. Assuming that you want to watch the linear swap BTC/USDT market I would suggest doing this:

```Python
exchange = ccxt.pro.binance({"defaultType":"swap"})
while True:
     orders = await exchange.watch_orders("BTC/USDT:USDT")
```
Let us know if that does not fix it!

**Comment by nikky78** [comment]
Thank you. You wrote {"defaultType":"swap"} though, while I was talking about future market. Should I use swap too ?

**Comment by carlosmiei** [comment]
> Thank you. You wrote {"defaultType":"swap"} though, while I was talking about future market. Should I use swap too ?

@nikky78 Yeah you can use `swap` too, the important thing here is to disambiguate between spot and futures/perpetual swaps and `swap` is the most used term in the ccxt world

**Comment by nikky78** [comment]
I don't get that error but now I have an exception <class 'ccxt.base.errors.NetworkError'> 1006 watch_orders. How should I handle that error please? I did exchange.close() but then how to open it up again and relaunch watch_order please?

**Comment by carlosmiei** [comment]
> I don't get that error but now I have an exception <class 'ccxt.base.errors.NetworkError'> 1006 watch_orders. How should I handle that error please? I did exchange.close() but then how to open it up again and relaunch watch_order please?

@nikky78 For how long was the stream running? Binance requires a restart after 24h hours.

After the `await exchange.close()` you just need to call `watch_orders` again to re-connect

**Comment by nikky78** [comment]
Binance does not say you need to restart your streams. It says you need to send a ping every 60 mintes but that's it. My stream on the spot market does not disconnect.

**Comment by ttodua** [comment]
late reply here, but as answered above, it's generally preferred for any exchange, to restart WS connection once in a while, eg. 24 hours or shorter timespan, that's better for user to ensure more stability, because, even though exchanges' API docs might not state that, in real-world scenarios many unexpected nuances happen. so, refreshing connection once-in-a-while is a good approach.

let us know if any problems.
