### ISSUE TITLE
Invalid API-Key ID for Binance but i created a right API Key

### ISSUE THREAD

**Issue by janstrw13** [ccxt/ccxt#16616]
### ؜

Traceback (most recent call last):
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\base\exchange.py", line 625, in fetch
    response.raise_for_status()
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1674571483886&recvWindow=10000&signature=2a5e92b5f16b449d6bfe7023cea27a1779dbe27fbc6c9525d96311899acc34de

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jan\Desktop\Bots\DCABOTBinance.py", line 73, in <module>
    order = exchange.create_market_buy_order(pair, amount)
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\base\exchange.py", line 3284, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\binance.py", line 3295, in create_order
    self.load_markets()
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\base\exchange.py", line 1459, in load_markets
    currencies = self.fetch_currencies()
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\binance.py", line 1525, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\base\exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\binance.py", line 6190, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\base\exchange.py", line 2830, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\base\exchange.py", line 641, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\binance.py", line 6168, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Users\Jan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ccxt\base\exchange.py", line 3133, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}

![image](https://user-images.githubusercontent.com/119401920/214325768-d7837e35-6d9a-49b1-bdd1-c791c2efd83c.png)

**Comment by kroitor** [comment]
@janstrw13 make sure the API key is correct and your key permissions are set properly (on the exchange website).

**Comment by yuchiu503** [comment]
I have the same problem as you. Is it solved now? My API key is absolutely correct and the permissions are correct

**Comment by ttodua** [comment]
@yuchiu503 unless you provide verbose log of failed request, it's hard to help. also, take a look in: https://docs.ccxt.com/#/README?id=api-key-permissions

**Comment by ttodua** [comment]
an old topic, with no follow-up.
i'll close this and if anyone faces any issues, let us know
