### ISSUE TITLE
Strange error when sending tokens to an address already in whitelist.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16621]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.6.36

### Description

Hi,
As failed last time, so I add the target address in whitelist, and try again, but this time, I saw even more strange errors:
C:\ArbitApps\CCXT\CCXTNodeByFunctions>node mexc3_getCoin1Balance.js ASTRO
{"Ticker":"ASTRO","Amount":3000.2}

C:\ArbitApps\CCXT\CCXTNodeByFunctions>node mexc3_send1CoinChain1.js
Usage: Coin1 Amount Address (Tag|undefined) (Network|undefined)
Send Coin1 to an address with full network data
Please try again!

C:\ArbitApps\CCXT\CCXTNodeByFunctions>node mexc3_send1CoinChain1.js ASTRO 3000.2 terra17f0cp50wnzdgzfuqrq8qganqqkmhe2kvguw759 EAPZZqCA7QiPjn undefined
ExchangeError: mexc3 {"msg":"The currency not exist. Please check coin name and chain is correct.","code":10232}
    at mexc3.handleErrors (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\mexc3.js:4904:19)
    at C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:603:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async mexc3.fetch2 (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:2023:16)
    at async mexc3.request (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:2027:16)
    at async mexc3.withdraw (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\mexc3.js:4474:26)
    at async send1Coin (C:\ArbitApps\CCXT\CCXTNodeByFunctions\mexc3_send1CoinChain1.js:26:19) {
  constructor: [class ExchangeError extends BaseError]
}

My code did not change, see the code below.
Please advise what could go wrong?
Thanks,

### Code

```
const ccxt = require('ccxt');

if (process.argv.length != 7)
{
console.error('Usage: Coin1 Amount Address (Tag|undefined) (Network|undefined)');
console.error('Send Coin1 to an address with full network data');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, coin1, amount1, address1, tag1, chain1] = process.argv;

let exchange = new ccxt.mexc3
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': false, }
});

const send1Coin = async (coin1, amount1, address1, tag1, chain1) =>
{
try
{
const transfer1 = await exchange.withdraw(coin1, amount1, address1, tag1, {'network': chain1});
const json_transfer = JSON.stringify(transfer1);
console.log(json_transfer);
}
catch (err)
{
console.error(err);
}
};
send1Coin(coin1, amount1, address1, tag1, chain1);  
```

**Comment by ttodua** [comment]
@carlosmiei I think it will be hard to apply any fix to mexc without merging the networks-pr at first, because whatever is being explained here, depends on `chain` value, and I wouldnt guide user to use some soon-out-of-date approaches, because networks unification will change things, and I have already a pending PR to apply for MEXC too. 
Anyway, i'll test this out soon and post my findings about mentioned issue.

**Comment by ttodua** [comment]
I've been looking into the issue, and in addition to unification problem, there is also problem on MEXC API side, I've sent them a note and will wait for their answer, then I'll post an update here.

**Comment by ttodua** [comment]
closing the stale issue.
i didn't get any follow-up so can't tell if it happens still or not.
Users should update CCXT to latest version and if the issue still persist, please let us know again and I will take a look again.
