### ISSUE TITLE
binance - WS limitations

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#16620]
### Operating System

W11

### CCXT Version

2.6.52

### Description

When we subscribe to WS endpoints with ccxt (i.e. watchOrderBook) after around 200 symbols, it throws : 
```
DDoSProtection: binance 429 Too Many Requests {"code":-1003,"msg":"Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use WebSocket Streams for live updates to avoid polling the API."}`
    at handleErrors (\node_modules\ccxt\js\binance.js:6519:19)
    at <anonymous> (\node_modules\ccxt\js\base\Exchange.js:603:51)
```

However, natively binance seems to accept around 1000 symbols subscription. Here i've made a snippet to easily test our and see the differences. 
just set the first variable to `true` , so it will subscribe to binance with raw WS approach, then on another test, set it to `false` and script will use CCXT approach. difference is around 1000 subscribed symbols vs 200.

### Code

```
const nativeWsSubscription = true; 

const ccxt = require ('ccxt');
const WebSocket = require ('ws');
function c(...args){console.log(...args);}
 
class WsTest1 {

    constructor (){ }

    async init (exchangeName, nativeWsSubscription) {
        this.ex = new ccxt.pro[exchangeName]();
        await this.ex.loadMarkets();
        this.markets = Object.entries (this.ex.markets).filter(([symbol, market]) => market.spot && market.active);
        if (!nativeWsSubscription) {
            this.watchCcxt();
        } else {
            this.watchNative();
        }
        setInterval ( () => {c("Confirmed symbols:", Object.keys(this.receivedUniqueSymbols).length);}, 1000);
    }

    receivedUniqueSymbols = {};
    async watchCcxt() {
        const subMethod = async (exch, symbol, methodName) => {
            while (true) {
                try {
                    const res = await exch[methodName](symbol);
                    this.receivedUniqueSymbols[symbol] = 1;
                } catch (e) {
                    c('Error: ', symbol, e.message);
                    await exch.sleep(1000);
                }
            }
        }
    
        const symbols = this.markets.map(([symbol, market]) => market['symbol']);
        for (let i = 0; i < symbols.length; i++) {
            this.subMethod(exch, market['symbol'], 'watchOrderBook');
        }
    }


    async watchNative () {
        this.wsc = new WebSocket('wss://data-stream.binance.com/ws');
        
        const all_ids = this.markets.map(([symbol, market]) => market['id'].toLowerCase() + '@depth');
        const symbolsPacketLength = 200;

        const trigger = async ()=> {
            for (let i = 0; i < all_ids.length / symbolsPacketLength; i++) {
                const ids = all_ids.slice(i *symbolsPacketLength, (i+1) *symbolsPacketLength);
                this.wsc.send(
                    JSON.stringify({
                        "method": "SUBSCRIBE",
                        "params": ids,
                        "id": i + 1
                    })
                ); 
                await this.ex.sleep(3000); // to my surprise, this matter. setting it to lower causes to return less symbols actually
            }
        };

        this.wsc.on('open', (ws) =>{ c('Opened'); trigger(); });
        this.wsc.on('message', (data) => {
            try {
                const parsed = JSON.parse(data);
                if (parsed.s) this.receivedUniqueSymbols[parsed.s] = 1;
                else c('Unknown data:', data);
            } catch (exc) {
                c(exc.stack, data);
            }
        });
    }

}

(new WsTest1()).init('binance', nativeWsSubscription);
```

**Comment by pcriadoperez** [comment]
Hi, the "DDoSProtection: binance 429 Too Many Requests" error doesn't happen due to the websockets, it is because when we subscribe to a watchOrderBook, we due a call to the Rest api `fetchOrderBookSnapshot` so if we have `enableRateLimit = false` binace throws a too many requests error.

**Comment by pcriadoperez** [comment]
Id say the solution for this is to throttle new connections as proposed here: https://github.com/ccxt/ccxt/pull/16113

**Comment by ttodua** [comment]
yes, right, the DOS rate limit issue comes from REST requests, but the thing (the point of this issue) is to show that users cant subscribe normally and get 1/5th of the possible data. that's what we need to fix somehow.

**Comment by nautonk** [comment]
i'm facing this problem too.

**Comment by pcriadoperez** [comment]
@ttodua  I agree with you, thanks for this test. I ran it using the PR #16113 and it solves the issue correctly in JS. But I am having some issues with php and python. I might ask @ttodua or @carlosmiei  for some help to finish that part up.

**Comment by ttodua** [comment]
I'm closing this issue, because with the top-post code I've posted, I no longer see the issue with latest CCXT.
