### ISSUE TITLE
Can not withdraw funds from Huobipro even the address already in white list.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16652]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.6.36

### Description

Hello:
I want to withdraw some USDT from my Huobipro exchange account, learned from last time lesson, I added the TRC20 address in the white list, but I still got the following errors:
C:CCXT>node huobipro_getCoin1Balance.js USDT
{"Ticker":"USDT","Amount":74.76}

C:CCXT>
C:CCXT>node huobipro_send1CoinChain1.js USDT 73.75 TLj3GQJGMg6bfn42NhSsqg6Y86hdACGuNQ undefined TRC20
PermissionDenied: huobipro {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null}
    at huobipro.throwExactlyMatchedException (C:CCXT\node_modules\ccxt\js\base\Exchange.js:2400:19)
    at huobipro.handleErrors (C:CCXT\node_modules\ccxt\js\huobi.js:5739:22)
    at C:CCXT\node_modules\ccxt\js\base\Exchange.js:603:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (C:CCXT\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async huobipro.fetch2 (C:CCXT\node_modules\ccxt\js\base\Exchange.js:2023:16)
    at async huobipro.request (C:CCXT\node_modules\ccxt\js\base\Exchange.js:2027:16)
    at async huobipro.withdraw (C:CCXT\node_modules\ccxt\js\huobi.js:5084:26)
    at async send1Coin (C:CCXT\huobipro_send1CoinChain1.js:26:19) {
  constructor: [class PermissionDenied extends AuthenticationError]
}

Please advise what could go wrong again.
By the way, it has been nearly one week now, the latest NPM version for CCXT is still 2.6.36.  If I can not install new version, then how to fix the old bugs?
Please advise,
Thanks,

### Code

```
const ccxt = require('ccxt');

if (process.argv.length != 7)
{
console.error('Usage: Coin1 Amount Address (Tag|undefined) (Network|undefined)');
console.error('Send Coin1 to an address with full network data');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, coin1, amount1, address1, tag1, chain1] = process.argv;

let exchange = new ccxt.mexc3
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': false, }
});

const send1Coin = async (coin1, amount1, address1, tag1, chain1) =>
{
try
{
const transfer1 = await exchange.withdraw(coin1, amount1, address1, tag1, {'network': chain1});
const json_transfer = JSON.stringify(transfer1);
console.log(json_transfer);
}
catch (err)
{
console.error(err);
}
};
send1Coin(coin1, amount1, address1, tag1, chain1);    

```

**Comment by kroitor** [comment]
@zydjohnHotmail in the post subject you mention Huobi, while in your code you're using MEXC v3. Which one is it?

**Comment by zydjohnHotmail** [comment]
Hi,
It was Huobipro, since I didn't want to change my API key showing in the code, so I copied my last issue's code.  But all my codes for withdraw are the same, only exchange name and API key and Secret key.
Sorry for the confusion.  Please investiage

**Comment by ttodua** [comment]
late reply, but https://alphaex-api.github.io/openapi/spot/v1/en/#order-and-trade:~:text=Q1%EF%BC%9A-,Why%20the%20API%20returns%20error,-%27api%2Dnot%2Dsupport says that address should be added in whitelist and also note that `uppercase/lowercase` might also need to match.
let us know if anyone still has any issues
