### ISSUE TITLE
When placing limit order in CoinEX exchange, I got strange error.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16686]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.6.36

### Description

C:\CCXT>node coinex_getCoin1Balance.js ASTROC
{"Ticker":"ASTROC","Amount":3319.6}

[C:\CCXT](https://github.com/CCXT)>node coinex_actPair1LimitOrder.js sell ASTROC/USDT 0.0027 3319.6
Place a limit sell oder!
TypeError: this[method] is not a function
    at coinex.createOrder (C:\CCXT\node_modules\ccxt\js\coinex.js:1885:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async actPair1LimitOrder (C:\CCXT\coinex_actPair1LimitOrder.js:37:21)

C:\CCXT>

I want to place a limit order for testing, but I got strange errors.
Please advise on what could go wrong.
Thanks,

### Code

```
const ccxt = require('ccxt');
if (process.argv.length != 6)
{
console.error('Usage: buy|sell BTC/USDT Price Amount');
console.error('Buy|Sell Pair1 at price with amount');
console.error('Please try again!');
process.exit(1);
 }
const [nodejs, script1, act1, pair1, price1, amount1] = process.argv;

let exchange = new ccxt.coinex
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': false, }
});


const actPair1LimitOrder = async (act1, pair1, price1, amount1) =>
{
try
{
await exchange.loadMarkets();
switch (act1)
{
case 'buy':
console.log('Place a limit buy oder!');
const buy_limit1 = await exchange.createOrder(pair1, 'LIMIT', 'buy', amount1, price1);
const json_buy = JSON.stringify(buy_limit1);
console.log(json_buy);
break;
case 'sell':
console.log('Place a limit sell oder!');
const sell_limit1 = await exchange.createOrder(pair1, 'LIMIT', 'sell', amount1, price1);
const json_sell = JSON.stringify(sell_limit1);
console.log(json_sell);
break;
}
}
catch (err)
{
console.error(err);
}
};
actPair1LimitOrder(act1, pair1, price1, amount1);
```

**Comment by ttodua** [comment]
as I check now, this problem should be gone.
let us know if anyone has any issues still.
