### ISSUE TITLE
Digifinex missing a number of tickers.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16723]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.6.36

### Description

I found there are quite some trading pairs data are missing for Exchange digifinex.
The following is the error messages, for BTC/USDT, it is OK.
But for the following pairs, it is not OK, I can find their trading from web page, but using CCXT, no live data.

The pairs are: 

- APE/USDT
- NEAR/USDT
- COMP/USDT
- CRV/USDT
- KNC/USDT
- KSM/USDT
- SUSHI/USDT
- VET/USDT
- SOL/USDT
- CHZ/USDT
- ENS/USDT
- LRC/USDT

```js
C:\CCXT>node digifinex_fetch1Ticker.js BTC/USDT
{"symbol":"BTC/USDT","timestamp":1675326417000,"datetime":"2023-02-02T08:26:57.000Z","high":24250.69,"low":22775.11,"bid":23825.08,"ask":23825.3,"vwap":23487.124758601378,"close":23823.14,"last":23823.14,"percentage":3.64,"baseVolume":1528.08143,"quoteVolume":35890239.187712,"info":{"date":1675326417,"vol":"1528.08143","change":"3.64","base_vol":"35890239.187712","sell":"23825.3","last":"23823.14","symbol":"btc_usdt","low":"22775.11","buy":"23825.08","high":"24250.69"}}
```
```js
C:\CCXT>node digifinex_aggPair1OrderBook.js BTC/USDT 10
{"asks":[[23835.9,0.00068],[23835.95,0.00429],[23835.97,0.00053],[23835.98,0.00845],[23836,0.00086],[23836.98,11.24148],[23839.8,27.77457],[23841.9,36.24096],[23848.25,3.5673123],[23849.02,115.3430977]],"bids":[[23835.7,0.6094],[23835.6,1.26961],[23835.2,0.22296],[23835.1,0.10368],[23834.85,0.00206],[23834.82,0.0595],[23834.81,0.00004],[23834.8,0.00304],[23834.7,0.5574],[23834.42,0.00171]],"timestamp":1675326436000,"datetime":"2023-02-02T08:27:16.000Z"}
```
```js
C:\CCXT>node digifinex_fetch1Currency.js APE
{"id":"APE","code":"APE","info":{"deposit_status":"1","min_withdraw_fee":"0.004","withdraw_fee_currency":"ETH","chain":"ERC20","withdraw_fee_rate":"0","min_withdraw_amount":"0.5","currency":"APE","withdraw_status":"0","min_deposit_amount":"0.5"},"active":false,"deposit":true,"withdraw":false,"fee":0.004,"precision":0.004,"limits":{"amount":{},"withdraw":{"min":0.5},"deposit":{"min":0.5}},"networks":{"ERC20":{"info":{"deposit_status":"1","min_withdraw_fee":"0.004","withdraw_fee_currency":"ETH","chain":"ERC20","withdraw_fee_rate":"0","min_withdraw_amount":"0.5","currency":"APE","withdraw_status":"0","min_deposit_amount":"0.5"},"id":"ERC20","network":"ERC20","active":false,"fee":0.004,"precision":0.004,"deposit":true,"withdraw":false,"limits":{"amount":{},"withdraw":{"min":0.5},"deposit":{"min":0.5}}}}}
```
```js
C:\CCXT>node digifinex_fetch1Ticker.js APE/USDT
BadSymbol: digifinex does not have market symbol APE/USDT
    at digifinex.market (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2567:15)
    at digifinex.fetchTicker (C:\CCXT\node_modules\ccxt\js\digifinex.js:1048:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetch1Ticker (C:\CCXT\digifinex_fetch1Ticker.js:23:17) {
  constructor: [class BadSymbol extends BadRequest]
}
```
```js
C:\CCXT>node digifinex_aggPair1OrderBook.js APE/USDT 1
C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2567
        throw new BadSymbol (this.id + ' does not have market symbol ' + symbol);
              ^

BadSymbol: digifinex does not have market symbol APE/USDT
    at digifinex.market (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2567:15)
    at digifinex.fetchOrderBook (C:\CCXT\node_modules\ccxt\js\digifinex.js:883:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async aggPair1Orderbook (C:\CCXT\digifinex_aggPair1OrderBook.js:45:19) {
  constructor: [class BadSymbol extends BadRequest]
}

Node.js v19.5.0

C:\CCXT>
```
### Detailed verbose output for Fetch1Ticker.js for APE/USDT on digifinex: (truncated)
```js
C:\CCXT>node digifinex_fetch1Ticker.js APE/USDT
fetch Request:
 digifinex GET https://openapi.digifinex.com/v3/currencies
RequestHeaders:
 {}
RequestBody:
 undefined

handleRestResponse:
 digifinex GET https://openapi.digifinex.com/v3/currencies 200 OK
ResponseHeaders:
 {
  'Access-Control-Allow-Headers': 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '793198fe28a811bf-BCN',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Thu, 02 Feb 2023 08:36:11 GMT',
  Expires: 'Thu, 02 Feb 2023 08:36:09 GMT',
  Server: 'cloudflare',
  'Server-Timing': 'cf-q-config;dur=6.9999987317715e-06',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Content-Type-Options': 'nosniff'
}
ResponseBody:
 {"data":[{"deposit_status":0,"min_withdraw_fee":5,"withdraw_fee_currency":"USDT","chain":"OMNI","withdraw_fee_rate":0,"min_withdraw_amount":10,"currency":"USDT","withdraw_status":0,"min_deposit_amount":10},{"deposit_status":1,"min_withdraw_fee":5,"withdraw_fee_currency":"USDT","chain":"ERC20","withdraw_fee_rate":0,"min_withdraw_amount":10,"currency":"USDT","withdraw_status":1,"min_deposit_amount":10},{"deposit_status":1,"min_withdraw_fee":1,"withdraw_fee_currency":"USDT","chain":"TRC20","withdraw_fee_rate":0,"min_withdraw_amount":10,"currency":"USDT","withdraw_status":1,"min_deposit_amount":10},{"deposit_status":1,"min_withdraw_fee":1,"withdraw_fee_currency":"USDC","chain":"TRC20","withdraw_fee_rate":0,"min_withdraw_amount":10,"currency":"USDC","withdraw_status":1,"min_deposit_amount":10},{"deposit_status":1,"min_withdraw_fee":10,"withdraw_fee_currency":"USDC","chain":"ERC20","withdraw_fee_rate":0,"min_withdraw_amount":10,"currency":"USDC","withdraw_status":1,"min_deposit_amount":10},{"deposit_status":1,"min_withdraw_fee":1,"withdraw_fee_currency":"USDT","chain":"BEP20","withdraw_fee_rate":0,"min_withdraw_amount":10,"currency":"USDT","withdraw_status":1,"min_deposit_amount":10},{"deposit_status":1,"min_withdraw_fee":0,"withdraw_fee_currency":"ETH","chain":"ERC20","withdraw_fee_rate":0,"min_withdraw_amount":0.01,"currency":"TEST2","withdraw_status":0,"min_deposit_amount":0.01},
......
{"deposit_status":1,"min_withdraw_fee":0.004,"withdraw_fee_currency":"ETH","chain":"","withdraw_fee_rate":0,"min_withdraw_amount":0.0001,"currency":"XMON","withdraw_status":1,"min_deposit_amount":0.0001}],"code":200}

fetch Request:
 digifinex GET https://openapi.digifinex.com/v3/trades/symbols
RequestHeaders:
 {}
RequestBody:
 undefined

handleRestResponse:
 digifinex GET https://openapi.digifinex.com/v3/trades/symbols 200 OK
ResponseHeaders:
 {
  'Access-Control-Allow-Headers': 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '793199073fe511bf-BCN',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Thu, 02 Feb 2023 08:36:12 GMT',
  Expires: 'Thu, 02 Feb 2023 08:36:11 GMT',
  Server: 'cloudflare',
  'Server-Timing': 'cf-q-config;dur=4.000001354143e-06',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Content-Type-Options': 'nosniff'
}
ResponseBody:
 {"symbol_list":[{"order_types":["LIMIT","MARKET"],"quote_asset":"USDT","minimum_value":2,"amount_precision":5,"status":"TRADING","minimum_amount":5e-05,"symbol":"BTC_USDT","is_allow":1,"zone":"MAIN","base_asset":"BTC","price_precision":2},{"order_types":......
["LIMIT"],"quote_asset":"USDT","minimum_value":2,"amount_precision":4,"status":"TRADING","minimum_amount":1e-05,"symbol":"XMON_USDT","is_allow":0,"zone":"INNOVATE","base_asset":"XMON","price_precision":4}],"code":0}

fetch Request:
 digifinex GET https://openapi.digifinex.com/swap/v2/public/instruments
RequestHeaders:
 {}
RequestBody:
 undefined

handleRestResponse:
 digifinex GET https://openapi.digifinex.com/swap/v2/public/instruments 200 OK
ResponseHeaders:
 {
  'Cache-Control': 'no-cache',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '7931990cca4a11bf-BCN',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Thu, 02 Feb 2023 08:36:13 GMT',
  Expires: 'Thu, 02 Feb 2023 08:36:12 GMT',
  'Ip-Weight-Minute-Remain': '5995',
  'Ip-Weight-Minute-Use': '5',
  Server: 'cloudflare',
  'Server-Timing': 'cf-q-config;dur=8.000002708286e-06',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'sameorigin',
  'X-Xss-Protection': '1; mode=block'
}
ResponseBody:
 {"code":0,"data":[{"instrument_id":"BTCUSDTPERP","type":"REAL","contract_type":"PERPETUAL","base_currency":"BTC","quote_currency":"USDT","clear_currency":"USDT","contract_value":"0.001","contract_value_currency":"BTC","is_inverse":false,"is_trading":true,"status":"ONLINE","price_precision":1,"tick_size":"0.1","min_order_amount":1,"open_max_limits":[{"leverage":"50","max_limit":"1000000"}]},{"instrument_id":"ETHUSDTPERP","type":"REAL","contract_type":"PERPETUAL","base_currency":"ETH","quote_currency":"USDT","clear_currency":"USDT","contract_value":"0.01","contract_value_currency":"ETH","is_inverse":false,"is_trading":true,"......{"instrument_id":"LINKPERP","type":"REAL","contract_type":"PERPETUAL","base_currency":"LINK","quote_currency":"USD","clear_currency":"LINK","contract_value":"1","contract_value_currency":"USD","is_inverse":true,"is_trading":true,"status":"ONLINE","price_precision":4,"tick_size":"0.0001","min_order_amount":1,"open_max_limits":[{"leverage":"3","max_limit":"20000"},{"leverage":"10","max_limit":"10000"},{"leverage":"50","max_limit":"5000"}]}]}

BadSymbol: digifinex does not have market symbol APE/USDT
    at digifinex.market (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2567:15)
    at digifinex.fetchTicker (C:\CCXT\node_modules\ccxt\js\digifinex.js:1048:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetch1Ticker (C:\CCXT\digifinex_fetch1Ticker.js:23:17) {
  constructor: [class BadSymbol extends BadRequest]
}
```

### Code

```js
const ccxt = require ('ccxt');

if (process.argv.length != 3) {
    console.error ('Usage: BTC/USDT');
    console.error ('Fetch 1 ticker price');
    console.error ('Please try again!');
    process.exit (1);
}
const [nodejs, script1, pair1] = process.argv;

let exchange = new ccxt.digifinex ({
    'adjustForTimeDifference': true,
    defaultType: 'spot',
    'verbose': false
});

const fetch1Ticker = async (pair1) => {
    try {
        if (exchange.has['fetchTicker']) {
            const ticker1 = await exchange.fetchTicker (pair1);
            if (typeof ticker1 !== 'undefined') {
                const json_ticker1 = JSON.stringify (ticker1);
                console.log (json_ticker1);
            } else {
                const obj_jsonTicker0 = ({ 'Data': [] });
                const json_ticker0 = JSON.stringify (obj_jsonTicker0);
                console.log (json_ticker0);
            }
        }
    } catch (err) {
        console.error (err)
    }
};
fetch1Ticker (pair1);
```

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail,
Thanks for letting us know, we will take a look

**Comment by samgermain** [comment]
It looks like the spot market for ape_usdt is only returned with `fetchMarketsV!`

```js
% digifinex fetchMarkets | grep 'APE' 
    APEUSDTPERP |    APE/USDT:USDT |         APE |  USDT |   USDT |        APE |    USDT |     USDT | swap | false |        |  true |  false |  false |   true |     true |   true |   false |          0.1 |        |                |        |            |                     {"price":0.0001} |      {"leverage":{},"amount":{"min":1},"price":{"min":0.0001},"cost":{}}
```
```js
% digifinex fetchMarketsV1 | grep 'APE'             
       ape_usdt |         APE/USDT |         APE |  USDT |        |        ape |    usdt |          | spot | true |        | false |  false |  false |        |    false |        |         |              |        |                |        |            |     {"price":0.0001,"amount":0.0001} |         {"leverage":{},"amount":{"min":0.2},"price":{},"cost":{"min":2}}
```

you can set what fetchMarkets method is used by setting the param `options` of your exchange object as

```js
{ 
      'options': {
            'fetchMarkets': {
                'method': 'fetchMarketsV2'
             }
}
```

-----------------------------------------------

I'm going to check if maybe we should combine these methods to get the best of both

**Comment by zydjohnHotmail** [comment]
Hi,
I changed my code, so it looks like this:
const ccxt = require('ccxt');
console.log(ccxt.version);

if (process.argv.length != 3)
{
console.error('Usage: BTC/USDT');
console.error('Fetch 1 ticker price');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, pair1] = process.argv;

let exchange = new ccxt.digifinex
({'adjustForTimeDifference': true,
defaultType: 'spot',
'verbose': false,
'options': {
            'fetchMarkets': {
                'method': 'fetchMarketsV2'
});

const fetch1Ticker = async(pair1) =>
{
try
{
if (exchange.has['fetchTicker'])
{
const ticker1 = await exchange.fetchTicker(pair1);
if (typeof ticker1 !== 'undefined')
{
const json_ticker1 = JSON.stringify(ticker1);
console.log(json_ticker1);
}
else
{
const obj_jsonTicker0 = ({ 'Data': []});
const json_ticker0 = JSON.stringify(obj_jsonTicker0);
console.log(json_ticker0);
}
}
}
catch (err)
{
console.error(err)
}
};
fetch1Ticker(pair1);
But it is not working, something wrong with the syntax:
C:\CCXT>node digifinex_fetch1Ticker.js APE/USDT
C:\CCXT\digifinex_fetch1Ticker.js:20
});
 ^

SyntaxError: Unexpected token ')'
←[90m    at internalCompileFunction (node:internal/vm:73:18)←[39m
←[90m    at wrapSafe (node:internal/modules/cjs/loader:1176:20)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1218:27)←[39m
←[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:1117:32)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:958:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:23:47←[39m

Node.js v18.14.2

C:\CCXT>
Let me know how to fix this.
By the way, if you can combine different methods, then it is better.

**Comment by samgermain** [comment]
You have a syntax error because you're missing two `}` at the end of your exchange instantiation

I don't know what you're writing your code in, but you'll receive less syntax errors if you have a code formatter/**eslint** in vscode, or something equivalent in other IDEs like intelliJ

This is getting off topic from CCXT though

**Comment by samgermain** [comment]
@zydjohnHotmail Was everything resolved regarding this issue?
