### ISSUE TITLE
create_limit_buy_order on Bleutrade says "'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by jaovssilva** [ccxt/ccxt#1672]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.10.909
- Exchange: Bleutrade
- Method: create_limit_buy_order

When i try use create_limit_buy_order on bleutrade exchange return this error:

```
> Traceback (most recent call last):
  File "E:/test/test.py", line 29, in <module>
    bleutrade.create_limit_buy_order('ETH/BTC', 0.001, 0.011029989)
  File "C:\Python36\lib\site-packages\ccxt\base\exchange.py", line 1033, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "C:\Python36\lib\site-packages\ccxt\bittrex.py", line 429, in create_order
    'id': response['result'][orderIdField],
TypeError: 'NoneType' object is not subscriptable
```

my code:

```
  bleutrade = ccxt.bleutrade()
  bleutrade.apiKey = 'apiKey'
  bleutrade.secret = 'secret'
  bleutrade.create_limit_buy_order('ETH/BTC', 0.001, 0.011029989)
```

**Comment by kroitor** [comment]
Can you please change your code like this and post verbose output here (excluding your keys)

```
  bleutrade = ccxt.bleutrade({'verbose': True})  # ←-------------------- add this
  bleutrade.apiKey = 'apiKey'
  bleutrade.secret = 'secret'
  bleutrade.create_limit_buy_order('ETH/BTC', 0.001, 0.011029989)
```

?

**Comment by jaovssilva** [comment]
@kroitor, thanks for your attention. Reading HTTP exchange details i found my error.
