### ISSUE TITLE
Bitget fetchOrderBook ExchangeError: XXXX cannot be empty

### ISSUE THREAD

**Issue by zhangxf55** [ccxt/ccxt#16765]
### Operating System

CentOS7.6

### Programming Languages

JS

### CCXT Version

2.6.36

### Description

My test code below for specified symbols such as MTL/USDT:USDT and FOOTBALL/USDT:USDT:
```javascript
async function testBitGet() {
    const bitget = new ccxt.bitget();
    while(true) {
        const orderbook = await bitget.fetchOrderBook("MTL/USDT:USDT");
        console.log(JSON.stringify(orderbook))
    }
}
```

### Code

```bash
ExchangeError: bitget {"code":"40019","msg":"Parameter MTLUSDT cannot be empty","requestTime":1675739072763,"data":null}
    at bitget.handleErrors (/root/workspace/cexhub/node_modules/ccxt/js/bitget.js:3755:19)
    at /root/workspace/cexhub/node_modules/ccxt/js/base/Exchange.js:603:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/root/workspace/cexhub/node_modules/ccxt/js/base/functions/time.js:181:20)
    at async bitget.fetch2 (/root/workspace/cexhub/node_modules/ccxt/js/base/Exchange.js:2023:16)
    at async bitget.request (/root/workspace/cexhub/node_modules/ccxt/js/base/Exchange.js:2027:16)
    at async bitget.fetchOrderBook (/root/workspace/cexhub/node_modules/ccxt/js/bitget.js:1505:26)
    at async testBitGet (/root/workspace/cexhub/test/test.js:87:27) {
  constructor: [class ExchangeError extends BaseError]
}

```

**Comment by carlosmiei** [comment]
Hello @zhangxf55,
You get that error because you're trying to access a delisted/inactive market. 
You can check it beforehand by doing:

```Javascript
const market = this.market (symbol);
const isActive = market['active']
```

**Comment by zhangxf55** [comment]
It seems that market.active is undefined in swap market in bitget:
```javascript
const bitget = new ccxt.bitget();
await bitget.loadMarkets();
const market = bitget.market("MTL/USDT:USDT");
console.log(market['active']);
```
Terminal Output:
```bash
[root@zhangxf55 cexhub]# node test/test.js 
undefined
```
while in spot market:
```js
```javascript
const bitget = new ccxt.bitget();
await bitget.loadMarkets();
const market = bitget.market("MTL/USDT");
console.log(market['active']);
```
Terminal output:
```bash
[root@zhangxf55 cexhub]# node test/test.js 
true
```

> Hello @zhangxf55, You get that error because you're trying to access a delisted/inactive market. You can check it beforehand by doing:
> 
> ```js
> const market = exchange.market (symbol);
> const isActive = market['active']
> ```
