### ISSUE TITLE
Binance watchOrderBook uncaught exception in sub coroutine

### ISSUE THREAD

**Issue by zhangxf55** [ccxt/ccxt#16766]
### Operating System

CentOS 7.6

### Programming Languages

JS

### CCXT Version

2.6.36

### Description

In ccxt.pro(2.6.36) line 381, binance create a sub coroutine to fetch the snapshot of the orderbook by fetchOrderBookSnapshot method, it will cause an uncaught Exception and abnormal program exit:
```javascript
372.     handleOrderBookSubscription (client, message, subscription) {
373.         const defaultLimit = this.safeInteger (this.options, 'watchOrderBookLimit', 1000);
374.         const symbol = this.safeString (subscription, 'symbol');
375.         const limit = this.safeInteger (subscription, 'limit', defaultLimit);
376.         if (symbol in this.orderbooks) {
377.             delete this.orderbooks[symbol];
378.         }
379.         this.orderbooks[symbol] = this.orderBook ({}, limit);
380.         // fetch the snapshot in a separate async call
381.         this.spawn (this.fetchOrderBookSnapshot, client, message, subscription);
382.     }
```
Test code below:
```javascript
async function testBinanceWatchOrderBook() {
    const binance = new ccxt.binance({});
    try {
        const ret = await binance.watchOrderBook('T/USDT:USDT');
        console.log(JSON.stringify(ret));
    }
    catch(err) {
        console.log('Exception Caught!!!!!', err);
    }
}
```

Terminal Output:
```bash
[root@zhangxf55 cexhub]# node test/test.js 
/root/workspace/cexhub/node_modules/ccxt/js/binance.js:6631
            throw new ExchangeError (feedback);
                  ^

ExchangeError: binance {"code":-4108,"msg":"Symbol is on delivering or delivered or settling or closed or pre-trading."}
    at binance.handleErrors (/root/workspace/cexhub/node_modules/ccxt/js/binance.js:6631:19)
    at /root/workspace/cexhub/node_modules/ccxt/js/base/Exchange.js:603:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/root/workspace/cexhub/node_modules/ccxt/js/base/functions/time.js:181:20)
    at async binance.fetch2 (/root/workspace/cexhub/node_modules/ccxt/js/base/Exchange.js:2023:16)
    at async binance.request (/root/workspace/cexhub/node_modules/ccxt/js/binance.js:6659:26)
    at async binance.fetchOrderBook (/root/workspace/cexhub/node_modules/ccxt/js/binance.js:2421:26)
    at async binance.fetchOrderBookSnapshot (/root/workspace/cexhub/node_modules/ccxt/js/pro/binance.js:216:26) {
  constructor: [class ExchangeError extends BaseError]
}
```
ExchangeError is thrown from the sub coroutine and can not be caught and handled correctly

### Code

```
  

```

**Comment by goznauk** [comment]
The makeshift quick fix:

```
    handleOrderBookSubscription (client, message, subscription) {
        const defaultLimit = this.safeInteger (this.options, 'watchOrderBookLimit', 1000);
        const symbol = this.safeString (subscription, 'symbol');
        const limit = this.safeInteger (subscription, 'limit', defaultLimit);
        if (symbol in this.orderbooks) {
            delete this.orderbooks[symbol];
        }
        this.orderbooks[symbol] = this.orderBook ({}, limit);
        // fetch the snapshot in a separate async call
        this.spawn (this.fetchOrderBookSnapshot, client, message, subscription)
            .catch(e => console.error(e))  // <<<<<<<<<<<
    }
```

**Comment by pcriadoperez** [comment]
hi @goznauk , I am not able to reproduce this error, I tried both version 2.6.36 and the latest version and both are able to fetch the order snapshot without any issues. 
Also I wouldn't recommend ignoring catching and ignoring the error as binance only returns the deltas in it's feed so it need the snapshot to return the full order book.

**Comment by goznauk** [comment]
Hi @pcriadoperez! I've just raise an exception inside coroutine because I can't reproduce this error too :) However, I think there is any code to handle some exception inside co-routine `fetchOrderBookSnapshot`, so when you raise an exception inside it

**Comment by kroitor** [comment]
Hello @zhangxf55, closing this during a cleanup — the snapshot fetch path this described was reworked very recently: orderbook snapshot failures no longer escape as uncaught exceptions from the background coroutine, the loading was routed through guarded error handling in all languages and the infinite retry on failure was removed as well, see https://github.com/ccxt/ccxt/pull/29398 and https://github.com/ccxt/ccxt/pull/29400. If an uncaught path still surfaces from watchOrderBook on a current version, a fresh issue with the traceback would be very welcome. Thanks for the report back then!
