### ISSUE TITLE
Binance Testnet connection error.

### ISSUE THREAD

**Issue by Kesanov** [ccxt/ccxt#16827]
linux opc, python 3.9

### CCXT Version

latest

### Description

Hi, I am trying to use the binance testnet, but I am receiving connection errors:
```
...
ccxt.base.errors.NetworkError: binance GET https://testnet.binanceops.com/eapi/v1/exchangeInfo`
```

### Code

```python
>>> b = ccxt.binance({'apiKey': api_key, 'secret': sec_key})
>>> b.set_sandbox_mode(True)   
>>> b.fetch_balance()
Traceback (most recent call last):
  File "/home/opc/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/opc/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/opc/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/opc/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/opc/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/opc/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/opc/.local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa0bdcfb160>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/opc/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/opc/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/opc/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='testnet.binanceops.com', port=443): Max retries exceeded with url: /eapi/v1/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa0bdcfb160>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/opc/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 599, in fetch
    response = self.session.request(
  File "/home/opc/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/opc/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/opc/.local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='testnet.binanceops.com', port=443): Max retries exceeded with url: /eapi/v1/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa0bdcfb160>: Failed to establish a new connection: [Errno -2] Name or service not known'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/opc/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2153, in fetch_balance
    self.load_markets()
  File "/home/opc/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1460, in load_markets
    markets = self.fetch_markets(params)
  File "/home/opc/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1690, in fetch_markets
    promises.append(self.eapiPublicGetExchangeInfo(params))
  File "/home/opc/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "/home/opc/.local/lib/python3.9/site-packages/ccxt/binance.py", line 6258, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/opc/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2830, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/opc/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 652, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://testnet.binanceops.com/eapi/v1/exchangeInfo
```

**Comment by Dan-krm** [comment]
We have a pull request opened to resolve this issue, it should be merged soon
