### ISSUE TITLE
Can't find my orders

### ISSUE THREAD

**Issue by SequoiaB** [ccxt/ccxt#16880]
### ؜

So, as the titile says, I am unable to find my orders...
The script is self explanatory

code
```
symbol = 'BTC/USDT:USDT'
myBook = {}


def executeOrder(symbol='BTC/USDT:USDT', side='sell', tpPrice=23000, slPrice=25000, size=0.01, myBook=myBook):
    print("order executer activated")
    print('sl = ' + str(slPrice))
    print('tp = ' + str(tpPrice))
    params = {'reduce_only': True}
    order = exchange.create_market_order(symbol, side, size, params)
    if side == 'buy':
        stopSide = 'sell'
        sl = exchange.create_stop_market_order(
            symbol, stopSide, size, slPrice, {})
        tp = exchange.create_limit_order(symbol, stopSide, size, tpPrice)
    else:
        stopSide = 'buy'
        sl = exchange.create_stop_market_order(
            symbol, stopSide, size, slPrice, {})
        tp = exchange.create_limit_order(symbol, stopSide, size, tpPrice)

    orderID = order['id']
    slID = sl['id']
    tpID = tp['id']
    myBook[orderID] = {'sl': slID, 'tp': tp}


def check_triggered_order():
    for order in myBook.keys():
        slID = myBook[order]['sl']
        tpID = myBook[order]['tp']
        sl = exchange.fetch_order(slID, symbol)
        tp = exchange.fetch_order(tpID, symbol)


executeOrder()
check_triggered_order()

```

error encountered:

```
`order executer activated
sl = 25000
tp = 23000
Traceback (most recent call last):
  File "c:\Users\edoza\OneDrive\Università condivisa\Trading bot\prima prova\SmartBot\pezzi\fetchOrder.py", line 60, in <module>
    check_triggered_order()
  File "c:\Users\edoza\OneDrive\Università condivisa\Trading bot\prima prova\SmartBot\pezzi\fetchOrder.py", line 55, in check_triggered_order
    sl = exchange.fetch_order(slID, symbol)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ccxt\bybit.py", line 3337, in fetch_order
    raise OrderNotFound('Order ' + id + ' does not exist.')
ccxt.base.errors.OrderNotFound: Order d5208f0b-eb22-4892-841e-ecef25c6a3e4 does not exist.`
```

**Comment by SequoiaB** [comment]
I am doing some tetst and discovered that works once in a while... wtf

**Comment by carlosmiei** [comment]
Hello @SequoiaB hum that's weird, after returning the order once, did subsequent calls fail?

**Comment by Cala3len** [comment]
Yeah it is happening more and more often on bybit API… hope it will works better with V5.
Currently being incorporated in ccxt : #16699

**Comment by SequoiaB** [comment]
I think this is the best error example of what's happening



> Yeah it happens more and more often on bybit API… hope it will works better with V5. Currently being incorporated in ccxt : #16699

what do you suggest to do?

**Comment by Cala3len** [comment]
> I think this is the best error example of what's happening
> 
> > Yeah it happens more and more often on bybit API… hope it will works better with V5. Currently being incorporated in ccxt : #16699
> 
> what do you suggest to do?

I’m afraid there is nothing to do. Other than help for the test on V5

**Comment by SequoiaB** [comment]
@Cala3len okay then... I am not very competent, but I'll try

**Comment by Cala3len** [comment]
@SequoiaB same for me X)

**Comment by gaugau3000** [comment]
Hi,

Here a workaround (use fetchOpenOrders):
https://github.com/freqtrade/freqtrade/issues/8175#issuecomment-1435403623

The fact that fetch_order work sometimes and sometimes not seems to be link to bybit. Some persons work with bybit tech team (see if the v5 fix will fix this problem) to explain this issue ?

**Comment by SequoiaB** [comment]
hey thanks @gaugau3000!
I also was able to find a workaround, maybe less efficient...
```
slID = myBook[orderID]['sl']
        tpID = myBook[orderID]['tp']
        print('id formati')
        while True:
            try:
                order = exchange.fetch_order(str(orderID), symbol)
                print('order formato')
                sl = exchange.fetch_order(str(slID), symbol)
                print('sl formato')
                tp = exchange.fetch_order(str(tpID), symbol)
                print('tp formato')
                break  # exit cycle if no exception is thrown
            except:
                pass  # ignore exceptions and try again
        print(sl, tp)
```

**Comment by ttodua** [comment]
users are recommended to check [`exchange.features`](https://docs.ccxt.com/#/README?id=features) to see if any method needs `trigger:true` param to be present in `fetchOrder/s`. in such case, it means that conditional orders need that param to obtain info from specific endpoint (instead of regular orders endpoint).

let us know if anyone still faces issues.
