### ISSUE TITLE
wavesexchange - createLimitBuyOrder - wavesexchange requires apiKey credential

### ISSUE THREAD

**Issue by david00z** [ccxt/ccxt#16913]
OS: Windows 10
Programming Language version: Node.js v18.13.0
CCXT version: latest
Exchange: wavesexchange
Method: createLimitBuyOrder

Hi there, I want to create an order, but it gives an error -wavesexchange requires apiKey credential.
log output:
D:\buxartest\node_modules\ccxt\js\wavesexchange.js:627
            throw new AuthenticationError (this.id + ' requires apiKey credential');
                  ^
AuthenticationError: wavesexchange requires apiKey credential
    at wavesexchange.checkRequiredKeys (D:\buxartest\node_modules\ccxt\js\wavesexchange.js:627:19)
    at wavesexchange.createOrder (D:\buxartest\node_modules\ccxt\js\wavesexchange.js:1275:14)
    at wavesexchange.createLimitBuyOrder (D:\buxartest\node_modules\ccxt\js\base\Exchange.js:2613:27)
    at D:\buxartest\index.js:97:50
    at new Promise (<anonymous>)
    at D:\buxartest\index.js:91:13
    at Array.map (<anonymous>)
    at D:\buxartest\index.js:89:38
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  constructor: [class AuthenticationError extends ExchangeError]
}

So I gave the keys:
const ccxt = require ('ccxt');
const { wavesexchange } = require('ccxt');
const we = new wavesexchange({
    apiKey: 'exampleKey',
    secret: 'exampleKey',
});

So I tried to create an order:
const BuyOrder = async (chatId) => {
    (async () => {
        await we.loadMarkets();
        const exchanges = [
            'wavesexchange',
        ]
    
        const symbol = 'BTC/USDT'
        const orders = {}
    
        await Promise.all (exchanges.map (exchangeId =>
    
            new Promise (async (resolve, reject) => {
                const exchange = new ccxt[exchangeId] ()
                    const order = await exchange.createLimitBuyOrder(symbol,1,0.5)
                    orders[exchangeId] = order
    
                    Object.keys (orders).map (exchangeId => {
                        const order = orders[exchangeId]
                        console.log (order)
                    })
            })
        ))
    }) ()
}

apiKeys are 100% valid.

Thanks in anticipation
Maks

**Comment by david00z** [comment]
i solved the issue
