### ISSUE TITLE
Gate.io fetch_ohlcv works incorrectly

### ISSUE THREAD

**Issue by Beherithh** [ccxt/ccxt#17053]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

2.7.45

### Description

This issue was raised 1 year ago, but it was resloved 
https://github.com/ccxt/ccxt/issues/11162
But now I see the same issue  - fetch_ohlc with limit=1000 trhows an error, but it works with limit<1000

### Code

```
import ccxt
exchange = ccxt.gateio()
pair = "ETH/USDT"
timeframe = '1h'
since_int = 1641314340000
candles = exchange.fetch_ohlcv(
                        pair,
                        timeframe,
                        since=since_int,
                        limit=1000
                        )  

```
------------------
fetch Request: gateio GET https://api.gateio.ws/api/v4/spot/candlesticks?currency_pair=ETH_USDT&interval=1h&from=1641314340&to=1644914339 RequestHeaders: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Gate-Channel-Id': 'ccxt'} RequestBody: None
Traceback (most recent call last):
  File "D:\My Docs (NAS synced)\PYTHON\Benders_logic\venv-new\lib\site-packages\ccxt\base\exchange.py", line 625, in fetch
    response.raise_for_status()
  File "D:\My Docs (NAS synced)\PYTHON\Benders_logic\venv-new\lib\site-packages\requests\models.py", line 1021, in raise_for_status

fetch Response: gateio GET https://api.gateio.ws/api/v4/spot/candlesticks?currency_pair=ETH_USDT&interval=1h&from=1641314340&to=1644914339 400 ResponseHeaders: {'Date': 'Sat, 04 Mar 2023 18:39:59 GMT', 'Content-Type': 'application/json', 'Content-Length': '121', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[e36ef3e3-2022833659]'} ResponseBody: {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.gateio.ws/api/v4/spot/candlesticks?currency_pair=ETH_USDT&interval=1h&from=1641314340&to=1644914339

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\My Docs (NAS synced)\PYTHON\Benders_logic\test3.py", line 9, in <module>
    candles = exchange.fetch_ohlcv(
  File "D:\My Docs (NAS synced)\PYTHON\Benders_logic\venv-new\lib\site-packages\ccxt\gate.py", line 2336, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))
  File "D:\My Docs (NAS synced)\PYTHON\Benders_logic\venv-new\lib\site-packages\ccxt\base\exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "D:\My Docs (NAS synced)\PYTHON\Benders_logic\venv-new\lib\site-packages\ccxt\base\exchange.py", line 2833, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "D:\My Docs (NAS synced)\PYTHON\Benders_logic\venv-new\lib\site-packages\ccxt\base\exchange.py", line 2830, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\My Docs (NAS synced)\PYTHON\Benders_logic\venv-new\lib\site-packages\ccxt\base\exchange.py", line 641, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "D:\My Docs (NAS synced)\PYTHON\Benders_logic\venv-new\lib\site-packages\ccxt\gate.py", line 4820, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], label, feedback)
  File "D:\My Docs (NAS synced)\PYTHON\Benders_logic\venv-new\lib\site-packages\ccxt\base\exchange.py", line 3133, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}

**Comment by samgermain** [comment]
From the [gate docs](https://www.gate.io/docs/developers/apiv4/en/#market-candlesticks) 

![](https://i.imgur.com/HW2tDtT.png)

This means that you can't pass both `since` and `limit` to gate's `fetch_ohlcv`  method, which you are doing. The method should work if you remove one of them.

--------------------------------------

I added [a PR](https://github.com/ccxt/ccxt/pull/17089) to specify this restriction in the `fetchOHLCV` docstring

**Comment by Beherithh** [comment]
But when I use a limit less than 1000 together with "since", for example:
```
candles = exchange.fetch_ohlcv(
    pair,
    timeframe,
    since=since_int,
    limit=999
)
```
it works correctly and returns exactly 999 candles starting from "since" timestamp. That means taht both "since" and "limit" to gate's fetch_ohlcv method can be used.

**Comment by Beherithh** [comment]
@kroitor - please read my last comment

**Comment by samgermain** [comment]
> 

I guess the gate docs are wrong then, you can try to contact gate about it, but it looks like this is the reason for the problem
