### ISSUE TITLE
watchOrderBookSnapshot has error in ascendex

### ISSUE THREAD

**Issue by fotrosi** [ccxt/ccxt#17114]
### Operating System

windows 64bit

### Programming Languages

JS

### CCXT Version

2.8.75

### Description

```js
Error in watchOrderBookSnapshot method in the ascendex:

C:\Bots\jsTest\node_modules\ccxt\js\pro\ascendex.js:270
        orderbook.reset (snapshot);
                  ^

TypeError: Cannot read properties of undefined (reading 'reset')
    at ascendex.handleOrderBookSnapshot (C:\Bots\jsTest\node_modules\ccxt\js\pro\ascendex.js:270:19)
    at ascendex.handleMessage (C:\Bots\jsTest\node_modules\ccxt\js\pro\ascendex.js:892:20)
    at WsClient.onMessage (C:\Bots\jsTest\node_modules\ccxt\js\pro\base\Client.js:283:14)
    at callListener (C:\Bots\jsTest\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\Bots\jsTest\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:512:28)
    at Receiver.receiverOnMessage (C:\Bots\jsTest\node_modules\ws\lib\websocket.js:1180:20)
    at Receiver.emit (node:events:512:28)
    at Receiver.dataMessage (C:\Bots\jsTest\node_modules\ws\lib\receiver.js:541:14)
    at Receiver.getData (C:\Bots\jsTest\node_modules\ws\lib\receiver.js:459:17)

Node.js v19.7.0
```

### Code

```js
const ccxt = require('ccxt')

const exchange = new ccxt.pro.ascendex({
    'apiKey': apiKey,
    'secret': secret,
    'options': {
        'account-category': 'margin', // 'cash', 'margin', 'futures' // obsolete
        'account-group': accountGroup,
        'defaultType': 'margin', // 'spot', 'margin', 'swap'
        'accountCategories': {
            'margin': 'margin',
        }
    },
})

exchange.verbose = false

async function watchOrderBookSnapshot(symbol) {
    while (true) {
        try {
            const orderbook = await exchange.watchOrderBookSnapshot(symbol)
            console.log(new Date(), exchange.id, symbol, orderbook)
        } catch (e) {
            console.log(symbol, e)
        }
    }
}

watchOrderBookSnapshot('MATIC/USDT') 

```

**Comment by carlosmiei** [comment]
Hello @fotrosi,
`watchOrderBookSnaphot` is an internal method and not meant to be used by independently. You should be using `watchOrderBook` instead.

**Comment by fotrosi** [comment]
Thanks a lot.
