### ISSUE TITLE
using in node.js  but lose file

### ISSUE THREAD

**Issue by BonecapitalMorpheus** [ccxt/ccxt#17144]
### Operating System

MacOS 13.2.1 (22D68)

### Programming Languages

JS

### CCXT Version

2.9.14

### Description

node.js version: 18.14.1
npm version: 9.3.1
use npm install ccxt, there is no problem in install progress, but when i run my server, it show the follow error

And I really can't find any documents for that.

```
2023-03-13 16:06:39,506 ERROR 94339 nodejs.MODULE_NOT_FOUNDError: [egg-core] load file: /Users/drowsyflesh/github/boneBackendEggJS/app/controller/ccxt.ts, error: Cannot find module './ccxt.bundle.cjs'
Require stack:
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/ccxt@2.9.14/node_modules/ccxt/dist/ccxt.cjs
- /Users/drowsyflesh/github/boneBackendEggJS/app/controller/ccxt.ts
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-core@5.3.0/node_modules/egg-core/lib/utils/index.js
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-core@5.3.0/node_modules/egg-core/lib/egg.js
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-core@5.3.0/node_modules/egg-core/index.js
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg@3.15.0/node_modules/egg/lib/application.js
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg@3.15.0/node_modules/egg/index.js
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-cluster@2.0.1/node_modules/egg-cluster/lib/app_worker.js
Require stack:
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/ccxt@2.9.14/node_modules/ccxt/dist/ccxt.cjs
- /Users/drowsyflesh/github/boneBackendEggJS/app/controller/ccxt.ts
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-core@5.3.0/node_modules/egg-core/lib/utils/index.js
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-core@5.3.0/node_modules/egg-core/lib/egg.js
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-core@5.3.0/node_modules/egg-core/index.js
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg@3.15.0/node_modules/egg/lib/application.js
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg@3.15.0/node_modules/egg/index.js
- /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-cluster@2.0.1/node_modules/egg-cluster/lib/app_worker.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._resolveFilename (/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/tsconfig-paths@4.1.2/node_modules/tsconfig-paths/src/register.ts:115:36)
    at Function.Module._resolveFilename (/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/tsconfig-paths@4.1.2/node_modules/tsconfig-paths/src/register.ts:115:36)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/ccxt@2.9.14/node_modules/ccxt/dist/ccxt.cjs:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/ts-node@10.9.1_uayvamxqnl5yeiojjysxwopmsy/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/drowsyflesh/github/boneBackendEggJS/app/controller/ccxt.ts:6:14)
code: "MODULE_NOT_FOUND"
requireStack: ["/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/ccxt@2.9.14/node_modules/ccxt/dist/ccxt.cjs","/Users/drowsyflesh/github/boneBackendEggJS/app/controller/ccxt.ts","/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-core@5.3.0/node_modules/egg-core/lib/utils/index.js","/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-core@5.3.0/node_modules/egg-core/lib/egg.js","/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-core@5.3.0/node_modules/egg-core/index.js","/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg@3.15.0/node_modules/egg/lib/application.js","/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg@3.15.0/node_modules/egg/index.js","/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/egg-cluster@2.0.1/node_modules/egg-cluster/lib/app_worker.js"]
name: "MODULE_NOT_FOUNDError"
```
<img width="1375" alt="QQ20230313-161746@2x" src="https://user-images.githubusercontent.com/127584144/224645221-1ae4ae4c-bc35-424f-9053-5acfc1d5ee44.png">

### Code

```
  

```

**Comment by BonecapitalMorpheus** [comment]
It seem not run bundle script when publish to npm?

**Comment by BonecapitalMorpheus** [comment]
Very glad to see the new release 2.9.15, but thsere is still a install problem.

It seems to build js from ts

```
Progress: resolved 1181, reused 1181, downloaded 0, added 1, done
node_modules/.pnpm/ccxt@2.9.15/node_modules/ccxt: Running postinstall script, failed in 73ms
.../.pnpm/ccxt@2.9.15/node_modules/ccxt postinstall$ node postinstall.cjs
│ node:internal/modules/cjs/loader:1078
│   throw err;
│   ^
│ Error: Cannot find module './ts/src/static_dependencies/fetch-ponyfill/fetch-node.cjs'
│ Require stack:
│ - /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/ccxt@2.9.15/node_modules/ccxt/posti
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
│     at Module._load (node:internal/modules/cjs/loader:920:27)
│     at Module.require (node:internal/modules/cjs/loader:1141:19)
│     at require (node:internal/modules/cjs/helpers:110:18)
│     at Object.<anonymous> (/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/ccxt@2.9.1
│     at Module._compile (node:internal/modules/cjs/loader:1254:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
│     at Module.load (node:internal/modules/cjs/loader:1117:32)
│     at Module._load (node:internal/modules/cjs/loader:958:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     '/Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/ccxt@2.9.15/node_modules/ccxt/po
│   ]
│ }
│ Node.js v18.14.1
└─ Failed in 73ms at /Users/drowsyflesh/github/boneBackendEggJS/node_modules/.pnpm/ccxt@2.9.15/node_modules/ccxt
 ELIFECYCLE  Command failed with exit code 1.
```
<img width="835" alt="image" src="https://user-images.githubusercontent.com/127584144/224738512-8a472de9-0e80-4725-b198-6d94f634189a.png">

**Comment by carlosmiei** [comment]
Hello @BonecapitalMorpheus,

> It seem not run bundle script before publish to npm?
Yeah we had a small issue in the deployment process but it should be ok.


I will check the postinstall report now. 

Thanks a lot for all the details!

**Comment by carlosmiei** [comment]
@BonecapitalMorpheus You're right, we're referencing a file from the `ts` folder however, TS files are not packed into the npm package, so we should point to the `js` correspondent instead.


It will be fixed very soon, thanks once again for reporting it!

**Comment by carlosmiei** [comment]
@BonecapitalMorpheus it should be fixed now (from version 2.9.16)

Thanks once again.
