### ISSUE TITLE
i meet this problem when i using bot

### ISSUE THREAD

**Issue by tien204** [ccxt/ccxt#17158]
### ؜

ArgumentsRequired: binance amount of BNB/USDT must be greater than minimum amount precision of 3

what can i do with this?

**Comment by samgermain** [comment]
That means you need to use a larger number with your `amount` argument, a precision of **x** means that your number must be greater than **10^-x**

In your example, the amount must be greater than **0.001**

-------------------------------

Btw, in the future, it helps if you provide some code that produces the error your talking about, so that we can reproduce the error ourselves and identify a way to solve it. I'm familiar with this error though so I was able to figure it out anyway.

**Comment by tien204** [comment]
`            const direction = directions[0]  // buy or sell
            const TRADE_SIZE = 0.034
            const quantity = TRADE_SIZE / marketPrice

            await binance.createMarketOrder('BNB/USDT', direction, quantity)
            console.log(`${moment().format()}: ${direction} ${quantity} BNB at ${marketPrice}`)`

I had set the quantity > 0.001, and that error occurred

**Comment by tien204** [comment]
#samgermain

**Comment by tien204** [comment]
@samgermain

**Comment by jefjef10w** [comment]
Hello , I have the exact same issue with my bot, also on binance 

`
$symbol = "STMX/BTC";
$price = 0.00000025;
$quantity = "103957;
$value_order = $quantity * $price; #0.02598925[
$value_order = $binance->amountToPrecision($symbol,$value_order);`

result: 

`PHP Fatal error:  Uncaught ccxt\ArgumentsRequired: binance $amount of STMX/BTC must be greater than minimum $amount precision of 0 in /home/billy/ccxt/php/Exchange.php:4346
Stack trace:
#0 [internal function]: ccxt\Exchange->amount_to_precision()
#1 /home/billy/ccxt/php/Exchange.php(1997): call_user_func_array()
#2 /home/billy/test.php(22): ccxt\Exchange->__call()
#3 {main}
  thrown in /home/billy/ccxt/php/Exchange.php on line 4346
`

Any help will be apprecied.
thanks
