### ISSUE TITLE
Typescript error - Cannot use import statement outside a module

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#17175]
### Operating System

windows 11 pro

### Programming Languages

JS

### CCXT Version

3.0.6

### Description

Doesn't work typescript code from examples.  (https://github.com/ccxt/ccxt/blob/master/examples/ts/fetch-tickers/src/index.ts) 

Error

```
ws_ohlcv-api-1  | (node:54) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
ws_ohlcv-api-1  | (Use `node --trace-warnings ...` to show where the warning was created)
ws_ohlcv-api-1  | /usr/src/app/dist/index.js:19
ws_ohlcv-api-1  | import * as ccxt from 'ccxt';
ws_ohlcv-api-1  | ^^^^^^
ws_ohlcv-api-1  |
ws_ohlcv-api-1  | SyntaxError: Cannot use import statement outside a module
ws_ohlcv-api-1  |     at internalCompileFunction (node:internal/vm:73:18)
ws_ohlcv-api-1  |     at wrapSafe (node:internal/modules/cjs/loader:1176:20)
ws_ohlcv-api-1  |     at Module._compile (node:internal/modules/cjs/loader:1218:27)
ws_ohlcv-api-1  |     at Module._compile (/usr/src/app/node_modules/source-map-support/source-map-support.js:568:25)
ws_ohlcv-api-1  |     at Module.m._compile (/tmp/ts-node-dev-hook-12566845747142086.js:111:37)
ws_ohlcv-api-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
ws_ohlcv-api-1  |     at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-12566845747142086.js:114:20)
ws_ohlcv-api-1  |     at Object.nodeDevHook [as .js] (/usr/src/app/node_modules/ts-node-dev/lib/hook.js:63:13)
ws_ohlcv-api-1  |     at Module.load (node:internal/modules/cjs/loader:1117:32)
ws_ohlcv-api-1  |     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
ws_ohlcv-api-1  | [ERROR] 17:40:17 SyntaxError: Cannot use import statement outside a module
```

package.json file 

```
{
  "name": "ws_ohlcv",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "ts-node-dev --poll src/index.ts",
    "build": "rimraf ./dist && tsc --inlineSources --sourceMap",
    "start": "npm run build && ts-node-dev --inspect=0.0.0.0:9229 dist/index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ccxt": "^3.0.6",
    "express": "^4.18.2",
    "fetch-blob": "^3.2.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.17",
    "@types/node": "^18.15.0",
    "rimraf": "^4.3.1",
    "ts-node-dev": "^2.0.0",
    "typescript": "^4.9.5"
  }
}

```

tsconfi.json 

```
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig to read more about this file */

    /* Projects */
    // "incremental": true,                              /* Save .tsbuildinfo files to allow for incremental compilation of projects. */
    // "composite": true,                                /* Enable constraints that allow a TypeScript project to be used with project references. */
    // "tsBuildInfoFile": "./.tsbuildinfo",              /* Specify the path to .tsbuildinfo incremental compilation file. */
    // "disableSourceOfProjectReferenceRedirect": true,  /* Disable preferring source files instead of declaration files when referencing composite projects. */
    // "disableSolutionSearching": true,                 /* Opt a project out of multi-project reference checking when editing. */
    // "disableReferencedProjectLoad": true,             /* Reduce the number of projects loaded automatically by TypeScript. */

    /* Language and Environment */
    "target": "ESNext",                                     /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    // "lib": [],                                        /* Specify a set of bundled library declaration files that describe the target runtime environment. */
    // "jsx": "preserve",                                /* Specify what JSX code is generated. */
    // "experimentalDecorators": true,                   /* Enable experimental support for TC39 stage 2 draft decorators. */
    // "emitDecoratorMetadata": true,                    /* Emit design-type metadata for decorated declarations in source files. */
    // "jsxFactory": "",                                 /* Specify the JSX factory function used when targeting React JSX emit, e.g. 'React.createElement' or 'h'. */
    // "jsxFragmentFactory": "",                         /* Specify the JSX Fragment reference used for fragments when targeting React JSX emit e.g. 'React.Fragment' or 'Fragment'. */
    // "jsxImportSource": "",                            /* Specify module specifier used to import the JSX factory functions when using 'jsx: react-jsx*'. */
    // "reactNamespace": "",                             /* Specify the object invoked for 'createElement'. This only applies when targeting 'react' JSX emit. */
    // "noLib": true,                                    /* Disable including any library files, including the default lib.d.ts. */
    // "useDefineForClassFields": true,                  /* Emit ECMAScript-standard-compliant class fields. */
    // "moduleDetection": "auto",                        /* Control what method is used to detect module-format JS files. */

    /* Modules */
    "module": "ESNext",
    "rootDir": "./src",                                  /* Specify the root folder within your source files. */
    "moduleResolution": "node",                       /* Specify how TypeScript looks up a file from a given module specifier. */
    // "baseUrl": "./",                                  /* Specify the base directory to resolve non-relative module names. */
    // "paths": {},                                      /* Specify a set of entries that re-map imports to additional lookup locations. */
    // "rootDirs": [],                                   /* Allow multiple folders to be treated as one when resolving modules. */
    // "typeRoots": [],                                  /* Specify multiple folders that act like './node_modules/@types'. */
    // "types": [],                                      /* Specify type package names to be included without being referenced in a source file. */
    // "allowUmdGlobalAccess": true,                     /* Allow accessing UMD globals from modules. */
    // "moduleSuffixes": [],                             /* List of file name suffixes to search when resolving a module. */
    // "resolveJsonModule": true,                        /* Enable importing .json files. */
    // "noResolve": true,                                /* Disallow 'import's, 'require's or '<reference>'s from expanding the number of files TypeScript should add to a project. */

    /* JavaScript Support */
    // "allowJs": true,                                  /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get errors from these files. */
    // "checkJs": true,                                  /* Enable error reporting in type-checked JavaScript files. */
    // "maxNodeModuleJsDepth": 1,                        /* Specify the maximum folder depth used for checking JavaScript files from 'node_modules'. Only applicable with 'allowJs'. */

    /* Emit */
    // "declaration": true,                              /* Generate .d.ts files from TypeScript and JavaScript files in your project. */
    // "declarationMap": true,                           /* Create sourcemaps for d.ts files. */
    // "emitDeclarationOnly": true,                      /* Only output d.ts files and not JavaScript files. */
    // "sourceMap": true,                                /* Create source map files for emitted JavaScript files. */
    // "outFile": "./",                                  /* Specify a file that bundles all outputs into one JavaScript file. If 'declaration' is true, also designates a file that bundles all .d.ts output. */
    "outDir": "./dist",                                   /* Specify an output folder for all emitted files. */
    // "removeComments": true,                           /* Disable emitting comments. */
    // "noEmit": true,                                   /* Disable emitting files from a compilation. */
    // "importHelpers": true,                            /* Allow importing helper functions from tslib once per project, instead of including them per-file. */
    // "importsNotUsedAsValues": "remove",               /* Specify emit/checking behavior for imports that are only used for types. */
    // "downlevelIteration": true,                       /* Emit more compliant, but verbose and less performant JavaScript for iteration. */
    //"sourceRoot": "./src/",                                 /* Specify the root path for debuggers to find the reference source code. */
    //"mapRoot": "./dist/",                                    /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,                          /* Include sourcemap files inside the emitted JavaScript. */
    // "inlineSources": true,                            /* Include source code in the sourcemaps inside the emitted JavaScript. */
    // "emitBOM": true,                                  /* Emit a UTF-8 Byte Order Mark (BOM) in the beginning of output files. */
    // "newLine": "crlf",                                /* Set the newline character for emitting files. */
    // "stripInternal": true,                            /* Disable emitting declarations that have '@internal' in their JSDoc comments. */
    // "noEmitHelpers": true,                            /* Disable generating custom helper functions like '__extends' in compiled output. */
    // "noEmitOnError": true,                            /* Disable emitting files if any type checking errors are reported. */
    // "preserveConstEnums": true,                       /* Disable erasing 'const enum' declarations in generated code. */
    // "declarationDir": "./",                           /* Specify the output directory for generated declaration files. */
    // "preserveValueImports": true,                     /* Preserve unused imported values in the JavaScript output that would otherwise be removed. */

    /* Interop Constraints */
    // "isolatedModules": true,                          /* Ensure that each file can be safely transpiled without relying on other imports. */
    "allowSyntheticDefaultImports": true,             /* Allow 'import x from y' when a module doesn't have a default export. */
    //"esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    // "preserveSymlinks": true,                         /* Disable resolving symlinks to their realpath. This correlates to the same flag in node. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */

    /* Type Checking */
    "strict": true,                                      /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                            /* Enable error reporting for expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,                         /* When type checking, take into account 'null' and 'undefined'. */
    // "strictFunctionTypes": true,                      /* When assigning functions, check to ensure parameters and the return values are subtype-compatible. */
    // "strictBindCallApply": true,                      /* Check that the arguments for 'bind', 'call', and 'apply' methods match the original function. */
    // "strictPropertyInitialization": true,             /* Check for class properties that are declared but not set in the constructor. */
    // "noImplicitThis": true,                           /* Enable error reporting when 'this' is given the type 'any'. */
    // "useUnknownInCatchVariables": true,               /* Default catch clause variables as 'unknown' instead of 'any'. */
    // "alwaysStrict": true,                             /* Ensure 'use strict' is always emitted. */
    // "noUnusedLocals": true,                           /* Enable error reporting when local variables aren't read. */
    // "noUnusedParameters": true,                       /* Raise an error when a function parameter isn't read. */
    // "exactOptionalPropertyTypes": true,               /* Interpret optional property types as written, rather than adding 'undefined'. */
    // "noImplicitReturns": true,                        /* Enable error reporting for codepaths that do not explicitly return in a function. */
    // "noFallthroughCasesInSwitch": true,               /* Enable error reporting for fallthrough cases in switch statements. */
    // "noUncheckedIndexedAccess": true,                 /* Add 'undefined' to a type when accessed using an index. */
    // "noImplicitOverride": true,                       /* Ensure overriding members in derived classes are marked with an override modifier. */
    // "noPropertyAccessFromIndexSignature": true,       /* Enforces using indexed accessors for keys declared using an indexed type. */
    // "allowUnusedLabels": true,                        /* Disable error reporting for unused labels. */
    // "allowUnreachableCode": true,                     /* Disable error reporting for unreachable code. */

    /* Completeness */
    // "skipDefaultLibCheck": true,                      /* Skip type checking .d.ts files that are included with TypeScript. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  }
}

```

### Code

Code from CCXT examples for TS.

```
 import * as ccxt from 'ccxt';
const log = require('ololog');

const symbol = 'BTC/USDT';
const exchanges = ['binance', 'gemini', 'kraken'];

const fetchTickers = async (symbol: string) => {
    const result = await Promise.all(exchanges.map(async (id: string): Promise<ccxt.Exchange> => {
        const CCXT = ccxt as any; // Hack!
        const exchange = new CCXT[id]({ 'enableRateLimit': true }) as ccxt.Exchange;
        const ticker = await exchange.fetchTicker(symbol);
        const exchangeExtended = exchange.extend({ 'exchange': id }, ticker) as ccxt.Exchange;
        return exchangeExtended;
    }));
    log(result);
};

fetchTickers(symbol); 

```

**Comment by kingkong404** [comment]
Also having this issue when I try to run my tests with ts-jest

**Comment by YuriyTigiev** [comment]
Error code below. 
Could you share the correct config for tsconfig.jsnon  file  and should I use additional parameters to compile script ? 

```
import ccxt from 'ccxt';
const log = require('ololog');

const symbol = 'BTC/USDT';
const exchanges = ['binance', 'gemini', 'kraken'];

const fetchTickers = async (symbol: string) => {
    const result = await Promise.all(exchanges.map(async (id: string): Promise<ccxt.Exchange> => {
        const CCXT = ccxt as any; // Hack!
        const exchange = new CCXT[id]({ 'enableRateLimit': true }) as ccxt.Exchange;
        const ticker = await exchange.fetchTicker(symbol);
        const exchangeExtended = exchange.extend({ 'exchange': id }, ticker) as ccxt.Exchange;
        return exchangeExtended;
    }));
    log(result);
};

fetchTickers(symbol);


ws_ohlcv-api-1  | Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/dist/index.js not supported.
ws_ohlcv-api-1  | Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
ws_ohlcv-api-1  |     at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5496890336820204.js:114:20)
ws_ohlcv-api-1  |     at Object.nodeDevHook [as .js] (/usr/src/app/node_modules/ts-node-dev/lib/hook.js:63:13)
ws_ohlcv-api-1  |     at Object.<anonymous> (/usr/src/app/node_modules/ts-node-dev/lib/wrap.js:104:1)
ws_ohlcv-api-1  |     at Module._compile (/usr/src/app/node_modules/source-map-support/source-map-support.js:568:25)
 => ERROR [development 6/6] RUN npm run build                                                                                                2.9s 
------
 > [development 6/6] RUN npm run build:
#0 0.942
#0 0.942 > ws_ohlcv@1.0.0 build
#0 0.942 > rimraf ./dist && tsc --inlineSources --sourceMap
#0 0.942
#0 2.849 src/index.ts(28,80): error TS2503: Cannot find namespace 'ccxt'.
#0 2.849 src/index.ts(30,71): error TS2503: Cannot find namespace 'ccxt'.
#0 2.850 src/index.ts(32,81): error TS2503: Cannot find namespace 'ccxt'.
------
```

**Comment by YuriyTigiev** [comment]
Can you share the correct code and configuration?
I'm a novice with a typescript.

**Comment by carlosmiei** [comment]
> Can you share the correct code and configuration? I'm a novice with a typescript. From: Carlos Gonçalves ***@***.***> Sent: Wednesday, March 15, 2023 6:57 PM To: ccxt/ccxt ***@***.***> Cc: YuriyTigiev ***@***.***>; Mention ***@***.***> Subject: Re: [ccxt/ccxt] Typescript error - Cannot use import statement outside a module (Issue #17175) @YuriyTigiev<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FYuriyTigiev&data=05%7C01%7C%7C73700333139c4fa57f4608db25657afa%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638144890009240544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=he9S2LwllutRmxYZONWCFHJUaBkKFKSGuybVKD%2Bftxo%3D&reserved=0> oh ok, You're mixing the modules system, which is not valid. If you are using CJS you should import ccxt as usual const ccxt require('ccxt'). Only ESM projects can make use of the import x syntax. - Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fccxt%2Fccxt%2Fissues%2F17175%23issuecomment-1470158604&data=05%7C01%7C%7C73700333139c4fa57f4608db25657afa%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638144890009240544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3h2liFSX7I4Y3tz8Monm6r4Ovs3OjcgjjN1gDPPvKk8%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFNSYQTS7RETFQFKHTDDDXTW4HKCNANCNFSM6AAAAAAV2YWR74&data=05%7C01%7C%7C73700333139c4fa57f4608db25657afa%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638144890009240544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dWvnLlps3mTMvrp4kwheL2bJFwu%2B7THxaRcblf0jw38%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

@YuriyTigiev sorry I deleted that message and forgot to post the update, actually I think the problem is related to the typescript version, can you try to update the typescript version to 4.7.4 and build again? that worked for me

**Comment by YuriyTigiev** [comment]
Should I downgrade ? Now I have typescript version 4.9.5 
Should I use this syntax ? 
import * as ccxt from 'ccxt';

```
  "devDependencies": {
    "@types/express": "^4.17.17",
    "@types/node": "^18.15.0",
    "rimraf": "^4.3.1",
    "ts-node-dev": "^2.0.0",
    "typescript": "^4.9.5"
  }
```

**Comment by carlosmiei** [comment]
> Should I downgrade ? Now I have typescript version 4.9.5 Should I use this syntax ? import * as ccxt from 'ccxt';
> 
> ```
>   "devDependencies": {
>     "@types/express": "^4.17.17",
>     "@types/node": "^18.15.0",
>     "rimraf": "^4.3.1",
>     "ts-node-dev": "^2.0.0",
>     "typescript": "^4.9.5"
>   }
> ```

@YuriyTigiev no you don't need to downgrade it has to be >= 4.X.X

 > import * as ccxt from 'ccxt';

Regarding the syntax yeah works on my end. Can you zip your project

**Comment by robkaandorp** [comment]
I had to set `"module": "CommonJS"` in tsconfig.json to make it work.

**Comment by carlosmiei** [comment]
@robkaandorp Yes, if you're using `require() and module.exports` syntax, you have to tell typescript that you intend to use `CJS`. however, in our examples, we already have that: https://github.com/ccxt/ccxt/blob/master/examples/ts/fetch-tickers/tsconfig.json#L12, so I'm not sure this would fix @YuriyTigiev issue

**Comment by YuriyTigiev** [comment]
Hello, 

Today I have cloned  ccxt library.

In VSC open folder `C:\Temp\ccxt\examples\ts\fetch-futures `
run `npm install `
run 'npm run build' and got a lot of errors. 
I'm sharing a few of them. 

Did I build correctly the example ?


```
node_modules/ccxt/js/src/yobit.d.ts:39:5 - error TS2416: Property 'sign' in type 'yobit' is not assignable to the same property in base type 'Exchange'.
  Type '(path: any, api?: string | undefined, method?: string | undefined, params?: {} | undefined, headers?: any, body?: any) => { url: any; method: string; body: any; headers: any; }' is not assignable to type '(path: any, api: string | object, method?: string | undefined, params?: {} | undefined, headers?: any, body?: any) => {}'.
    Types of parameters 'api' and 'api' are incompatible.
      Type 'string | object' is not assignable to type 'string | undefined'.
        Type 'object' is not assignable to type 'string | undefined'.
          Type 'object' is not assignable to type 'string'.

39     sign(path: any, api?: string, method?: string, params?: {}, headers?: any, body?: any): {
       ~~~~

node_modules/ccxt/js/src/zaif.d.ts:63:5 - error TS2416: Property 'sign' in type 'zaif' is not assignable to the same property in base type 'Exchange'.
  Type '(path: any, api?: string | undefined, method?: string | undefined, params?: {} | undefined, headers?: any, body?: any) => { url: string; method: string; body: any; headers: any; }' is not assignable to type '(path: any, api: string | object, method?: string | undefined, params?: {} | undefined, headers?: any, body?: any) => {}'.
    Types of parameters 'api' and 'api' are incompatible.
      Type 'string | object' is not assignable to type 'string | undefined'.
        Type 'object' is not assignable to type 'string | undefined'.
          Type 'object' is not assignable to type 'string'.

63     sign(path: any, api?: string, method?: string, params?: {}, headers?: any, body?: any): {
       ~~~~

node_modules/ccxt/js/src/zb.d.ts:219:5 - error TS2416: Property 'sign' in type 'zb' is not assignable to the same property in base type 'Exchange'.
  Type '(path: any, api?: string | undefined, method?: string | undefined, params?: {} | undefined, headers?: any, body?: any) => { url: any; method: string; body: any; headers: any; }' is not assignable to type '(path: any, api: string | object, method?: string | undefined, params?: {} | undefined, headers?: any, body?: any) => {}'.
    Types of parameters 'api' and 'api' are incompatible.
      Type 'string | object' is not assignable to type 'string | undefined'.
        Type 'object' is not assignable to type 'string | undefined'.
          Type 'object' is not assignable to type 'string'.

120     sign(path: any, api?: string, method?: string, params?: {}, headers?: any, body?: any): {
        ~~~~

Found 202 errors.
```

**Comment by YuriyTigiev** [comment]
Configs that solved the issue.

tsconfig.json

```
{
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "dist",
    "target": "es2019",
    "lib": [
      "es2019"
    ],
    "module": "commonjs",
    "esModuleInterop": true,
    "strict": true,
    "declaration": true,
    "sourceMap": true
  }
}
```

package.json 

```
{
  "type": "commonjs",
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "scripts": {
    "clean": "shx rm -rf dist/*",
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "tsc -p .",
    "start": "node ./dist/index.js"
  },
  "dependencies": {
    "ansicolor": "^1.1.92",
    "as-table": "^1.0.55",
    "ccxt": "^3.0.30",
    "dotenv": "^16.0.3",
    "ololog": "^1.1.146",
    "shx": "^0.3.4",
    "ts-node": "^10.9.1"
  },
  "devDependencies": {
    "@types/node": "^18.15.5",
    "typescript": "^5.0.2"
  },
  "engines": {
    "node": ">=7.6.0"
  }
}

```
