### ISSUE TITLE
Binance load futures markets returning spot information  

### ISSUE THREAD

**Issue by esteban2006** [ccxt/ccxt#17179]
### Operating System

windows 10

### Programming Languages

python

### CCXT Version

3.0.8

### Description

Loading Futures Markets data will return spot data  

### Code

Please check the last line of the response

```

binanceFuture=ccxt.binance({
  'apiKey': "aaa-",
  'secret': "bbb-",
  'enableRateLimit': True, # required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
  'options': {
      'defaultType': 'future',
      'defaultTimeInForce': 'GTC',
      'TimeInForce': 'GTC'
  },
})

pprint (binanceFuture.load_markets()['BTC/USDT'])

*----------------------------------
prints


{'active': True,
 'base': 'BTC',
 'baseId': 'BTC',
 'contract': False,
 'contractSize': None,
 'expiry': None,
 'expiryDatetime': None,
 'feeSide': 'get',
 'future': True,
 'id': 'BTCUSDT',
 'info': {'allowTrailingStop': True,
          'allowedSelfTradePreventionModes': ['NONE',
                                              'EXPIRE_TAKER',
                                              'EXPIRE_MAKER',
                                              'EXPIRE_BOTH'],
          'baseAsset': 'BTC',
          'baseAssetPrecision': '8',
          'baseCommissionPrecision': '8',
          'cancelReplaceAllowed': True,
          'defaultSelfTradePreventionMode': 'NONE',
          'filters': [{'filterType': 'PRICE_FILTER',
                       'maxPrice': '1000000.00000000',
                       'minPrice': '0.01000000',
                       'tickSize': '0.01000000'},
                      {'filterType': 'LOT_SIZE',
                       'maxQty': '9000.00000000',
                       'minQty': '0.00001000',
                       'stepSize': '0.00001000'},
                      {'applyToMarket': True,
                       'avgPriceMins': '5',
                       'filterType': 'MIN_NOTIONAL',
                       'minNotional': '10.00000000'},
                      {'filterType': 'ICEBERG_PARTS', 'limit': '10'},
                      {'filterType': 'MARKET_LOT_SIZE',
                       'maxQty': '154.43353509',
                       'minQty': '0.00000000',
                       'stepSize': '0.00000000'},
                      {'filterType': 'TRAILING_DELTA',
                       'maxTrailingAboveDelta': '2000',
                       'maxTrailingBelowDelta': '2000',
                       'minTrailingAboveDelta': '10',
                       'minTrailingBelowDelta': '10'},
                      {'askMultiplierDown': '0.2',
                       'askMultiplierUp': '5',
                       'avgPriceMins': '5',
                       'bidMultiplierDown': '0.2',
                       'bidMultiplierUp': '5',
                       'filterType': 'PERCENT_PRICE_BY_SIDE'},
                      {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': '200'},
                      {'filterType': 'MAX_NUM_ALGO_ORDERS',
                       'maxNumAlgoOrders': '5'}],
          'icebergAllowed': True,
          'isMarginTradingAllowed': True,
          'isSpotTradingAllowed': True,
          'ocoAllowed': True,
          'orderTypes': ['LIMIT',
                         'LIMIT_MAKER',
                         'MARKET',
                         'STOP_LOSS_LIMIT',
                         'TAKE_PROFIT_LIMIT'],
          'permissions': ['SPOT',
                          'MARGIN',
                          'TRD_GRP_004',
                          'TRD_GRP_005',
                          'TRD_GRP_006'],
          'quoteAsset': 'USDT',
          'quoteAssetPrecision': '8',
          'quoteCommissionPrecision': '8',
          'quoteOrderQtyMarketAllowed': True,
          'quotePrecision': '8',
          'status': 'TRADING',
          'symbol': 'BTCUSDT'},
 'inverse': None,
 'limits': {'amount': {'max': 9000.0, 'min': 1e-05},
            'cost': {'max': None, 'min': 10.0},
            'leverage': {'max': None, 'min': None},
            'market': {'max': 154.43353509, 'min': 0.0},
            'price': {'max': 1000000.0, 'min': 0.01}},
 'linear': None,
 'lowercaseId': 'btcusdt',
 'maker': 0.001,
 'margin': True,
 'option': False,
 'optionType': None,
 'percentage': True,
 'precision': {'amount': 5, 'base': 8, 'price': 2, 'quote': 8},
 'quote': 'USDT',
 'quoteId': 'USDT',
 'settle': 'USDT',
 'settleId': 'USDT',
 'spot': True,
 'strike': None,
 'swap': False,
 'symbol': 'BTC/USDT',
 'taker': 0.001,
 'tierBased': False,
 'type': 'spot'}

```

**Comment by sc0Vu** [comment]
Hi @esteban2006 

`loadMarkets()` returns markets with unified symbol. You should use `binanceFuture.market(symbol)` or use unified symbol `BTC/USDT:USDT` for the future.

**Comment by esteban2006** [comment]
@sc0Vu Thank you 
your suggestion binanceFuture.market(symbol) produced the following error 
```

Traceback (most recent call last):
  File "C:\Users\xxxxxxxxxxxxx\Documents\gits\app.py", line 984, in <module>
    pprint (binanceFuture.market('BTC/USDT'))
  File "C:\Users\*****************\site-packages\ccxt\binance.py", line 1520, in market
    raise ExchangeError(self.id + ' markets not loaded')
ccxt.base.errors.ExchangeError: binance markets not loaded
```

but using unified symbol 

`binanceFuture.load_markets()['BTC/USDT:USDT']` loaded the correct information 

so, for user that used to load the markets like this `binanceFuture.load_markets()` assuming that by loading your future account, you will now load the future markets, go ahead and make an adjustment on your method retriaving the info, because `binanceFuture.load_markets()['BTC/USDT']`, by  doing this, seems to return the first value in the markets list, usually `SPOT` markets, thank you for clarifying the propper usage
