### ISSUE TITLE
Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#17228]
### Operating System

Ubuntu

### Programming Languages

JS

### CCXT Version

3.0.10

### Description

Since a few days, I'm getting the following error:

TypeError: Right-hand side of 'instanceof' is not an object
    at binance.fetch (/var/opt/balance-botv2/node_modules/ccxt/dist/ccxt.bundle.cjs:18397:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async binance.fetch2 (/var/opt/balance-botv2/node_modules/ccxt/dist/ccxt.bundle.cjs:20140:16)
    at async binance.request (/var/opt/balance-botv2/node_modules/ccxt/dist/ccxt.bundle.cjs:36733:26)
    at async binance.fetchBalance (/var/opt/balance-botv2/node_modules/ccxt/dist/ccxt.bundle.cjs:31584:26)

This happens every few hours or so. The only change I made on my side that may have triggered this (as far as I can tell) is that I updated to CCXT v3.0.10. Before that, I've never seen this error (in over 2 years).

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @hodlerhacks, can you show us the code triggering this error?

**Comment by hodlerhacks** [comment]
Yes, the different relevant parts:

`
    const exchangeClass = ccxt['binance'];

    const exchange = new exchangeClass({
        'apiKey': apiKey,
        'secret': apiSecret,
        'timeout': 30000,
        'enableRateLimit': true,
        'newUpdates': true,
    });

`

`
        try {
            const balance = await exchange.fetchBalance();
        } catch (e) {
            // Exception thrown here
            }
        }
`

**Comment by carlosmiei** [comment]
@hodlerhacks Ok I think I found the reason, I will patch it asap. Thanks for reporting it!!

**Comment by hodlerhacks** [comment]
Excellent, thanks for the fast response, as always! Not sure it's being said enough, but you guys do amazing work!!
