### ISSUE TITLE
CCXT latest version - ReferenceError: AbortController is not defined

### ISSUE THREAD

**Issue by JeromeErasmus** [ccxt/ccxt#17260]
### Operating System

LInux Node JS 14

### CCXT Version

3.0.22

### Description

When upgrading to the latest version of CCXT 3.0.22 I get the following error when trying to run `loadMarkets()`

```
ReferenceError: AbortController is not defined    at bybit.fetch (/var/task/node_modules/ccxt/dist/cjs/src/base/Exchange.js:700:28)    at processTicksAndRejections (internal/process/task_queues.js:95:5)    at async bybit.fetch2 (/var/task/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2457:16)    at async bybit.request (/var/task/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2460:16)    at async bybit.fetchCurrencies (/var/task/node_modules/ccxt/dist/cjs/src/bybit.js:1213:26)    at async bybit.loadMarketsHelper (/var/task/node_modules/ccxt/dist/cjs/src/base/Exchange.js:793:26)
```

In my package.json I have the following:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
  },
  "devDependencies": {
    "@types/node": "^18.15.3",
    "@types/node-fetch": "^2.6.2",
    "ts-loader": "^8.1.0",
    "typescript": "^4.7.4",
    "webpack": "^5.75.0",
  },
  "dependencies": {
    "ccxt": "^3.0.22",
    "moment-timezone": "^0.5.34",
    "node-fetch": "^3.3.1",
    "source-map-support": "^0.5.19"
  }
}
```

Any help on trying to figure out what is going wrong would be greatly appreciated. 

Thanks

### Code

```
  

```

**Comment by JeromeErasmus** [comment]
Okay I think I can see the issue. I needed NodeJS 18

In a few places the CCXT documentation says it requires Node JS 14. I think it may be time to update the documentation

Thanks

**Comment by pcriadoperez** [comment]
Thanks for bringing this up @JeromeErasmus . Correct AbortController is compatible in Node v15+, I'll update the docs
