### ISSUE TITLE
BITGET fetch trades ERROR 40019 Parameter x cannot be empty

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#17346]
### Operating System

Linux mint

### Programming Languages

JS

### CCXT Version

3.0.34

### Description

I'm trying fetch olds trades by using exemple on documentation : https://docs.ccxt.com/#/README?id=date-based-pagination
I'm trying with BitGet exchange.

Error is :

```
/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2808
            throw new exact[string](message);
                  ^
InvalidOrder: bitget {"code":"40019","msg":"Parameter 1679678987713 cannot be empty","requestTime":1679765389424,"data":null}
    at bitget.throwExactlyMatchedException (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2808:19)
    at bitget.handleErrors (/node_modules/ccxt/dist/cjs/src/bitget.js:4250:18)
    at /node_modules/ccxt/dist/cjs/src/base/Exchange.js:760:51
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bitget.fetch2 (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2450:16)
    at async bitget.request (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2453:16)
    at async bitget.fetchTrades (/node_modules/ccxt/dist/cjs/src/bitget.js:1876:26
```

### Code

```
    const exchange: Exchange = new ccxtPro.bitget()
    const symbol = 'BTC/USDT:USDT'
    const tradeList: any[] = []

    if (exchange.has['fetchTrades']) {
        let since = exchange.milliseconds() - 86400000 // -1 day from now
        const limit = 20 // change for your limit
        while (since < exchange.milliseconds()) {
            const trades = await exchange.fetchTrades(symbol, since, limit)
            if (trades.length) {
                since = trades[trades.length - 1]['timestamp'] + 1
                tradeList.push(...trades)
            } else {
                break
            }
        }
    }

```

**Comment by carlosmiei** [comment]
Hello @dawadam,
Is it possible to provide a verbose log? I ran it for a few minutes and seems to be working fine

**Comment by dawadam** [comment]
Hello @carlosmiei 
I'm trying a biggest code :

```
import ccxt from "ccxt"
import { Exchange } from "ccxt"

/**
 * Fetch
 * @param exchange 
 */
async function fetchTrades(exchange: Exchange) {
    console.log(exchange.id)
    const symbol = 'BTC/USDT:USDT'
    const tradeList: any[] = []

    if (exchange.has['fetchTrades']) {
        let since = exchange.milliseconds() - 86400000 // -1 day from now
        const limit = 100 // change for your limit
        while (since < exchange.milliseconds()) {
            const trades = await exchange.fetchTrades(symbol, since, limit)
            if (trades.length) {
                since = trades[trades.length - 1]['timestamp'] + 1
                tradeList.push(...trades)
                console.log(trades.length)
            } else {
                break
            }
        }
    }
}

/**
 * Start
 * @param exchange 
 */
async function start() {
    const bybit: Exchange = new ccxt.bybit()
    await fetchTrades(bybit)

    const binance: Exchange = new ccxt.binance()
    await fetchTrades(binance)

    const bitget: Exchange = new ccxt.bitget()
    await fetchTrades(bitget)

}

// GO !
console.log('ccxt.version', ccxt.version)
start()
```
**Work on bybit and binance.**
Same error on bitget, no more verbose.

On the other hand, a curious observation, **it does not seem to give me trades dating back to a whole day**.
Is this the correct way to use the "since" parameter?

**Comment by carlosmiei** [comment]
> Hello @carlosmiei I'm trying a biggest code :
> 
> ```
> import ccxt from "ccxt"
> import { Exchange } from "ccxt"
> 
> /**
>  * Fetch
>  * @param exchange 
>  */
> async function fetchTrades(exchange: Exchange) {
>     console.log(exchange.id)
>     const symbol = 'BTC/USDT:USDT'
>     const tradeList: any[] = []
> 
>     if (exchange.has['fetchTrades']) {
>         let since = exchange.milliseconds() - 86400000 // -1 day from now
>         const limit = 100 // change for your limit
>         while (since < exchange.milliseconds()) {
>             const trades = await exchange.fetchTrades(symbol, since, limit)
>             if (trades.length) {
>                 since = trades[trades.length - 1]['timestamp'] + 1
>                 tradeList.push(...trades)
>                 console.log(trades.length)
>             } else {
>                 break
>             }
>         }
>     }
> }
> 
> /**
>  * Start
>  * @param exchange 
>  */
> async function start() {
>     const bybit: Exchange = new ccxt.bybit()
>     await fetchTrades(bybit)
> 
>     const binance: Exchange = new ccxt.binance()
>     await fetchTrades(binance)
> 
>     const bitget: Exchange = new ccxt.bitget()
>     await fetchTrades(bitget)
> 
> }
> 
> // GO !
> console.log('ccxt.version', ccxt.version)
> start()
> ```
> 
> **Work on bybit and binance.** Same error on bitget, no more verbose.
> 
> On the other hand, a curious observation, **it does not seem to give me trades dating back to a whole day**. Is this the correct way to use the "since" parameter?

@dawadam If possible I would like to see a verbose log containing the HTTP request (`exchange.verbose = true`)

**Comment by dawadam** [comment]
Ok, only for bitget, request make error is :

```
fetch Request:
 bitget GET https://api.bitget.com/api/mix/v1/market/fills?symbol=BTCUSDT_UMCBL&limit=1679765764872 
RequestHeaders:
 {} 
RequestBody:
 undefined 

handleRestResponse:
 bitget GET https://api.bitget.com/api/mix/v1/market/fills?symbol=BTCUSDT_UMCBL&limit=1679765764872 400 Bad Request 
ResponseHeaders:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '7ae1276b1a31867e-MAD',
  Connection: 'keep-alive',
  'Content-Type': 'application/json',
  Date: 'Sun, 26 Mar 2023 17:36:07 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'cloudflare',
  'Set-Cookie': '__cf_bm=EOrAouEegYFNTr7vIzh4cAUbpniXe84t0WvnLZIkdGE-1679852167-0-ATE3QHdhFzlAt2OGH0zZTo9HY/iwhaSxmP8INuu1SucNGz6qeJSQR8ul7gTrDEN1ZhC1SdppfXWL2mX9UKI02FY=; path=/; expires=Sun, 26-Mar-23 18:06:07 GMT; domain=.bitget.com; HttpOnly; Secure; SameSite=None, _cfuvid=tOIv9Yxy8UbwN5UmxOkL3oxqMjogEj0khROm1SZ9dxI-1679852167158-0-604800000; path=/; domain=.bitget.com; HttpOnly; Secure; SameSite=None',
  'Transfer-Encoding': 'chunked',
  Vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Request-Id': '1a5d994038a246a6b68e61b2bfd1fdcd',
  'X-Xss-Protection': '1; mode=block'
} 
ResponseBody:
 {"code":"40019","msg":"Parameter 1679765764872 cannot be empty","requestTime":1679852167049,"data":null} 

/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2808
            throw new exact[string](message);
                  ^
InvalidOrder: bitget {"code":"40019","msg":"Parameter 1679765764872 cannot be empty","requestTime":1679852167049,"data":null}
    at bitget.throwExactlyMatchedException (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2808:19)
    at bitget.handleErrors (/node_modules/ccxt/dist/cjs/src/bitget.js:4250:18)
    at /node_modules/ccxt/dist/cjs/src/base/Exchange.js:760:51
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bitget.fetch2 (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2450:16)
    at async bitget.request (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2453:16)
    at async bitget.fetchTrades (/node_modules/ccxt/dist/cjs/src/bitget.js:1876:26)
```

**Comment by carlosmiei** [comment]
> Ok, only for bitget, request make error is :
> 
> ```
> fetch Request:
>  bitget GET https://api.bitget.com/api/mix/v1/market/fills?symbol=BTCUSDT_UMCBL&limit=1679765764872 
> RequestHeaders:
>  {} 
> RequestBody:
>  undefined 
> 
> handleRestResponse:
>  bitget GET https://api.bitget.com/api/mix/v1/market/fills?symbol=BTCUSDT_UMCBL&limit=1679765764872 400 Bad Request 
> ResponseHeaders:
>  {
>   'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
>   'Cf-Cache-Status': 'DYNAMIC',
>   'Cf-Ray': '7ae1276b1a31867e-MAD',
>   Connection: 'keep-alive',
>   'Content-Type': 'application/json',
>   Date: 'Sun, 26 Mar 2023 17:36:07 GMT',
>   Expires: '0',
>   Pragma: 'no-cache',
>   Server: 'cloudflare',
>   'Set-Cookie': '__cf_bm=EOrAouEegYFNTr7vIzh4cAUbpniXe84t0WvnLZIkdGE-1679852167-0-ATE3QHdhFzlAt2OGH0zZTo9HY/iwhaSxmP8INuu1SucNGz6qeJSQR8ul7gTrDEN1ZhC1SdppfXWL2mX9UKI02FY=; path=/; expires=Sun, 26-Mar-23 18:06:07 GMT; domain=.bitget.com; HttpOnly; Secure; SameSite=None, _cfuvid=tOIv9Yxy8UbwN5UmxOkL3oxqMjogEj0khROm1SZ9dxI-1679852167158-0-604800000; path=/; domain=.bitget.com; HttpOnly; Secure; SameSite=None',
>   'Transfer-Encoding': 'chunked',
>   Vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
>   'X-Content-Type-Options': 'nosniff',
>   'X-Frame-Options': 'SAMEORIGIN',
>   'X-Request-Id': '1a5d994038a246a6b68e61b2bfd1fdcd',
>   'X-Xss-Protection': '1; mode=block'
> } 
> ResponseBody:
>  {"code":"40019","msg":"Parameter 1679765764872 cannot be empty","requestTime":1679852167049,"data":null} 
> 
> /node_modules/ccxt/dist/cjs/src/base/Exchange.js:2808
>             throw new exact[string](message);
>                   ^
> InvalidOrder: bitget {"code":"40019","msg":"Parameter 1679765764872 cannot be empty","requestTime":1679852167049,"data":null}
>     at bitget.throwExactlyMatchedException (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2808:19)
>     at bitget.handleErrors (/node_modules/ccxt/dist/cjs/src/bitget.js:4250:18)
>     at /node_modules/ccxt/dist/cjs/src/base/Exchange.js:760:51
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async bitget.fetch2 (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2450:16)
>     at async bitget.request (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2453:16)
>     at async bitget.fetchTrades (/node_modules/ccxt/dist/cjs/src/bitget.js:1876:26)
> ```

@dawadam at first sight looks like your providing the timestamp as the limit argument

**Comment by ttodua** [comment]
closing the old issue, because bitget seems to work at this moment (please use latest version).
also, as noted, the `fetchTrades` signature is `fetchTrades (symbol:, since, limit, params = {})`
if anyone still sees any issues let us know.
