### ISSUE TITLE
Error after upgrading to 3.0.40 version

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#17380]
### Operating System

windows 10

### Programming Languages

python

### CCXT Version

3.0.40

### Description

After upgrading to latest version I have this error.

```
Future exception was never retrieved
future: <Future finished exception=TypeError('a coroutine was expected, got <Future pending>')>
Traceback (most recent call last):
  File "C:\ShieldTrade\Python_projects\venv\lib\site-packages\ccxt\pro\bitmex.py", line 566, in authenticate
    self.spawn(self.watch, url, action, request, action)
  File "C:\ShieldTrade\Python_projects\venv\lib\site-packages\ccxt\async_support\base\exchange.py", line 284, in spawn
    task = self.asyncio_loop.create_task(method(*args))
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got <Future pending>
```

Running the following code you can reproduce the issue. Books and orders seem to work correctly

### Code

```
# Watch_orderbook(), watch_orders()
# After 10 sec place a limit order at level 3 bid price . 
# After 20 sec the same order will be amended ( new price will be level 5 bid)
# After 30 sec the same order will be canceled.
  
import ccxt.pro
import ccxt.async_support
import asyncio

order_id = None
lmt_pr = 0  # set to bid 3 level every time a book is received
amnd_pr = 0  # set to bid 5 level every time a book is received

async def bitmex_test():
    bitmex_test = ccxt.pro.bitmex({'verbose': False,
                                  'enableRateLimit': False,
                                  'apiKey': '5TsTycPxxxxxxxxxxxxx79jwTiw',
                                  'secret': 'o-Q2LEHJgTWxxxxxxxxGJyKROc7yMKvVZnv10Gj6',
                                  'newUpdates': True,
                                  'options': {
                                      'tradesLimit': 1000,
                                      'OHLCVLimit': 1000,
                                      'ordersLimit': 1000,
                                  },
                                  })
    if bitmex_test.urls['test']:  # mi sposto sulla sandbox
        bitmex_test.urls['api'] = bitmex_test.urls['test']
    markets = await bitmex_test.load_markets()  # carica tutte le info relative al mercato. è possibile stamparle
    print("bitmex_test loaded")
    await bitmex_test.sleep(3000)
    return bitmex_test

async def ccxt_watch_order(exchange, symbol):
    print("ccxt_watch_orders", exchange.id, symbol)
    global order_id
    while True:
        try:
            order = await exchange.watch_orders(symbol)
            print()
            print('order', order)
            order_id = order[0]['id']
        except Exception as e:
            print('Exception', e)

async def ccxt_watch_book(exchange, symbol, limit):
    global lmt_pr
    global amnd_pr
    print ('ccxt_watch_book:', exchange.id, symbol, limit)
    while True:
        try:
            book = await exchange.watch_order_book(symbol, limit)
            print('book ', book['bids'][0][0], ' ', book['asks'][0][0])
            lmt_pr = book['bids'][2][0]
            amnd_pr = book['bids'][4][0]
        except Exception as e:
            print('Exception', e)

async def on_time_send_order(exchange, symbol, mls = 1000):
    cont = 0
    while True:
        cont = cont + 1
        if cont == 10:  # 10'  send lmt ord
            params = {'execInst': 'ParticipateDoNotInitiate'}
            await exchange.create_order(symbol, 'limit', 'buy', 100, lmt_pr, params= params)
        if cont == 20: # 20'  send amend_pr ord
            await exchange.private_put_order({"orderID": order_id, "price": amnd_pr})
        if cont == 30: # 30'  cancel order
            await exchange.cancel_order(order_id, symbol)
        print ('time ', cont)
        await asyncio.sleep(mls/1000)

async def main():
    exchange = await bitmex_test()
    symbol = 'BTC/USD:BTC'
    loops = [
        ccxt_watch_order(exchange, symbol),
        ccxt_watch_book(exchange, symbol, None),
        on_time_send_order(exchange, symbol)
    ]
    await asyncio.gather(*loops)

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())


asyncio.run(main())

```

**Comment by frosty00** [comment]
has been fixed in #faf28e61d83ed2b07519d31fb76bb3ed360a2da1
