### ISSUE TITLE
Typescript - TypeError: CCXT[exchangeid] is not a constructor

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#17405]
### Operating System

windows 11 pro

### Programming Languages

JS

### CCXT Version

3.0.43

### Description

Error during compilation 

```
> ws_ohlcv@1.0.0 start
> npm run build && ts-node-dev --inspect=0.0.0.0:9229 dist/index.js build


> ws_ohlcv@1.0.0 build
> rimraf ./dist && tsc --inlineSources --sourceMap

[INFO] 07:59:57 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.0.2)
Debugger listening on ws://0.0.0.0:9229/9208ca7d-aede-4edb-96b2-adb0b846867b
For help, see: https://nodejs.org/en/docs/inspector
TypeError: CCXT[exchangeid] is not a constructor
    at loadExchangeData (C:\Users\yuriy\Documents\VSC\adca2\ws_ohlcv\src\index.ts:27:20)
    at C:\Users\yuriy\Documents\VSC\adca2\ws_ohlcv\src\index.ts:109:52
    at Array.map (<anonymous>)
    at main (C:\Users\yuriy\Documents\VSC\adca2\ws_ohlcv\src\index.ts:109:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
PS C:\Users\yuriy\Documents\VSC\adca2\ws_ohlcv> 
```

```
{
  "name": "ws_ohlcv",
  "version": "1.0.0",
  "description": "",
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "type": "commonjs",
  "scripts": {
    "dev": "ts-node-dev --poll src/index.ts",
    "build": "rimraf ./dist && tsc --inlineSources --sourceMap",
    "start": "npm run build && ts-node-dev --inspect=0.0.0.0:9229 dist/index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/node-schedule": "^2.1.0",
    "ccxt": "^3.0.44",
    "csv-parser": "^3.0.0",
    "express": "^4.18.2",
    "node-schedule": "^2.1.1",
    "ololog": "^1.1.175"
  },
  "devDependencies": {
    "@types/express": "^4.17.17",
    "@types/node": "^18.15.0",
    "rimraf": "^4.3.1",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.0.2"
  }
}

```

### Code

Example from the github CCXT - https://github.com/ccxt/ccxt/blob/master/examples/ts/fetch-tickers/src/index.ts

P.S.
Please, add a TypeScript into menu -> Programming Languages Which language are you using?

```
  // Example code in typescript
// Based on /examples/js/fetch-from-many-exchanges-simultaneously.js

import * as ccxt from 'ccxt';
const log = require('ololog');

const symbol = 'BTC/USD';
const exchanges = ['coinbasepro', 'gemini', 'kraken'];

const fetchTickers = async (symbol: string) => {
    const result = await Promise.all(exchanges.map(async (id: string): Promise<ccxt.Exchange> => {
        const CCXT = ccxt as any; // Hack!
        const exchange = new CCXT[id]({ 'enableRateLimit': true }) as ccxt.Exchange;
        const ticker = await exchange.fetchTicker(symbol);
        const exchangeExtended = exchange.extend({ 'exchange': id }, ticker) as ccxt.Exchange;
        return exchangeExtended;
    }));
    log(result);
};

fetchTickers(symbol);

```

**Comment by olegtaranenko** [comment]
Hi @carlosmiei, @YuriyTigiev ! I got the example compiled without (almost) warnings. Only (cctx as any) has to be used :-)
If you are interested, will create a PR.

**Comment by frosty00** [comment]
thanks for the response @olegtaranenko, we will look into this
