### ISSUE TITLE
[huobi] WatchTickers regression

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#17413]
### Operating System

linux, windows

### Programming Languages

JS

### CCXT Version

3.0.45

### Description

Somewhere after 3.0.19 a bug has been introduced into huobi watch tickers, if 'watchTicker': {'name': 'market.{marketId}.ticker'}.

### Code

```Javascript
let params = {
...
    options: {
        'watchTicker': {'name': 'market.{marketId}.ticker'}
    },
...
        let exchange = new ccxt[exchangeName](params);
        await exchange.watchTicker("BTC/USDT");
        await exchange.watchTicker("ETH/USDT");  // both watchTickers have to be present
       // wait a few seconds for exception
```
```
2023-03-30T15:56:40.953Z onMessage JSON.parse SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at WsClient.onMessage (REDACTED\node_modules\ccxt\dist\cjs\src\base\ws\Client.js:255:32)
    at callListener (REDACTED\node_modules\ccxt\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (REDACTED\node_modules\ccxt\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (REDACTED\node_modules\ccxt\node_modules\ws\lib\websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (REDACTED\node_modules\ccxt\node_modules\ws\lib\receiver.js:526:14)
    at Receiver.getData (REDACTED\node_modules\ccxt\node_modules\ws\lib\receiver.js:459:17)
    at Receiver.startLoop (REDACTED\node_modules\ccxt\node_modules\ws\lib\receiver.js:158:22)
Waiting for the debugger to disconnect...
REDACTED\node_modules\ccxt\dist\cjs\src\pro\huobi.js:1815
            if ('id' in message) {
                     ^

TypeError: Cannot use 'in' operator to search for 'id' in {"ch":"market.btcusdt.ticker","ts":1680191801001,"tick":{"open":28405.15,"high":29179.99,"low":28108.92,"close":28255.51,"amount":4569.8462197417075,"vol":1.3031913888475694E8,"count":137768,"bid":28255.5,"bidSize":0.565,"ask":28255.51,"askSize":0.312935,"lastPrice":28255.51,"
    at huobi.handleMessage (REDACTED\node_modules\ccxt\dist\cjs\src\pro\huobi.js:1815:22)
    at WsClient.onMessage (REDACTED\node_modules\ccxt\dist\cjs\src\base\ws\Client.js:268:14)
    at callListener (REDACTED\node_modules\ccxt\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (REDACTED\node_modules\ccxt\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (REDACTED\node_modules\ccxt\node_modules\ws\lib\websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (REDACTED\node_modules\ccxt\node_modules\ws\lib\receiver.js:526:14)
    at Receiver.getData (REDACTED\node_modules\ccxt\node_modules\ws\lib\receiver.js:459:17)
    at Receiver.startLoop (REDACTED\node_modules\ccxt\node_modules\ws\lib\receiver.js:158:22)
```

**Comment by carlosmiei** [comment]
Hello @krychla1,
I just ran the exact same script and it worked fine, do you get this error deterministically?

**Comment by krychla1** [comment]
@carlosmiei 
anything new regarding this? This is quite a blocking issue for huobi

**Comment by carlosmiei** [comment]
@krychla1 not yet but we will try to speed this up

**Comment by pcriadoperez** [comment]
Hi @krychla1, thanks for bringing this up. It looks like there was a bug on how we were decoding the incoming message. I'll post a PR with a proposed solutuion shortly
