### ISSUE TITLE
TypeError: a coroutine was expected, got <Future pending> (deribit)

### ISSUE THREAD

**Issue by jukanntenn** [ccxt/ccxt#17532]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.0.61

### Description

```
Traceback (most recent call last):
  File "arbitrage/0.py", line 404, in <module>
    asyncio.run(main(asyncio.Event()))
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "arbitrage/0.py", line 199, in main
    order_book_a, order_book_b = await asyncio.gather(*aws)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/arbitrage-d4Uwjcm7-py3.8/lib/python3.8/site-packages/ccxt/pro/deribit.py", line 380, in watch_order_book
    await self.authenticate()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/arbitrage-d4Uwjcm7-py3.8/lib/python3.8/site-packages/ccxt/pro/deribit.py", line 783, in authenticate
    self.spawn(self.watch, url, messageHash, self.extend(request, params), messageHash)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/arbitrage-d4Uwjcm7-py3.8/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 280, in spawn
    task = self.asyncio_loop.create_task(method(*args))
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/asyncio/base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got <Future pending>
```

It seems the same issue as #17380

**Comment by carlosmiei** [comment]
Hello @jukanntenn,
Thanks for letting us know, we will take a look asap.

**Comment by yar-jul** [comment]
when the latest version will be available on pypi?

**Comment by carlosmiei** [comment]
> when the latest version will be available on pypi?

@yar-jul Yes of course 🙂

**Comment by yar-jul** [comment]
Thanks. I mean, when will that happen?
