### ISSUE TITLE
Use in reactjs, Uncaught (in promise) TypeError: _static_dependencies_qs_index_cjs__WEBPACK_IMPORTED_MODULE_2__.stringify is not a function

### ISSUE THREAD

**Issue by 2GEasy** [ccxt/ccxt#17544]
### Operating System

reactjs

### CCXT Version

3.0.61

### Description

I'm using ccxt in nestjs is OK.
But using in reactjs, some function is ok, other functions get Error
error:
encode.js:15 Uncaught (in promise) TypeError: _static_dependencies_qs_index_cjs__WEBPACK_IMPORTED_MODULE_2__.stringify is not a function
    at binanceusdm.urlencode (encode.js:15:1)
    at binanceusdm.sign (binance.js:7495:1)
    at binanceusdm.fetch2 (Exchange.js:2435:1)
    at async binanceusdm.request (binance.js:7598:1)
    at async binanceusdm.fetchOrderBook (binance.js:2650:1)
    at async App.js:91:1

OK functions are loadMarkets, fetchTickers. i'm checked.
Get Error functions are fetchTicker, fetchOrderbook.

### Code

import ccxt from 'ccxt';
// const ccxt = require('../node_modules/ccxt/js/ccxt');
const ccxtpro = ccxt.pro;

(async()=>{
    const exchangeId = 'binanceusdm'
      const exchangeClass = ccxt[exchangeId]
      const exchange = new exchangeClass ({
          'apiKey': dev_api_key,
          'secret': dev_api_secret_key,
          'options': {
              'fetchCurrencies': false,
          }
      })
      exchange.setSandboxMode(true);

    console.log("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@APP ORDERBOOK",await exchange.fetchOrderBook('BTCUSDT')) //get Error
})()

**Comment by gabrielrtakeda** [comment]
Hello, @2GEasy.

I had the exact same issue using `create-react-app`.
If you are using it either, I used this workaround to solve it.

https://github.com/facebook/create-react-app/issues/12700#issuecomment-1463040093

Before:
![image](https://github.com/ccxt/ccxt/assets/5435389/d91bc914-a394-4cc7-91c7-0cf7e816713d)

After:
![image](https://github.com/ccxt/ccxt/assets/5435389/dbd523ac-cc30-411a-8c24-94adb970d76c)

Hope it helps someone 🍻

**Comment by diamond-tiger** [comment]
The qt source code was not loaded。

**Comment by diamond-tiger** [comment]
The qt source code was not loaded!
![无标题](https://github.com/user-attachments/assets/7f755aef-a68a-4869-9daf-5c4dd9bb7e0b)
