### ISSUE TITLE
Phemex Missing parameter - to","data":null

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#17617]
### ؜

OS: Windows 10
Programming Language version: Python
CCXT version: 3.0.73

Hello,

after updating ccxt I get this issue again -->Phemex Missing parameter - to","data":null [#16896](https://github.com/ccxt/ccxt/issues/16896).    It has been fixed back then and worked well since ccxt update. If I am not wrong the last time this issue occurs was also after updating ccxt. 

symbol = 'USD/USD:ETH'
pos_size = 1
timeframe = '1m'
num_bars = 200

params = {"type":"swap","code":"ETH"}
bars = phemex.fetch_ohlcv(symbol, timeframe=timeframe, limit=num_bars)
#print(bars)

HTTPError: 400 Client Error: Bad Request for url: https://api.phemex.com/exchange/public/md/kline?symbol=cETHUSD&resolution=60&limit=1000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\dell\desktop\bybit\phemex2.py", line 589, in <module>
    bars = phemex.fetch_ohlcv(symbol, timeframe=timeframe, limit=num_bars)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\phemex.py", line 1111, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 507, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2889, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2886, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 643, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\phemex.py", line 3910, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 3195, in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: phemex {"code":412,"msg":"Missing parameter - to","data":null}

**Comment by carlosmiei** [comment]
Hello @Nitrix321, we will investigate and patch it as soon as possible. Thanks for letting us know.
