### ISSUE TITLE
watch_trades() broken for gateio options

### ISSUE THREAD

**Issue by mrpouley** [ccxt/ccxt#17627]
### Operating System

linux

### Programming Languages

python

### CCXT Version

3.0.74

### Code

```
# -*- coding: utf-8 -*-

import ccxt.pro
from asyncio import gather, run


async def symbol_loop(exchange, symbol):
    print('Starting the', exchange.id, 'symbol loop with', symbol)
    while True:
        trades = await exchange.watch_trades(symbol)
        now = exchange.milliseconds()
        print(exchange.iso8601(now), exchange.id, symbol, len(trades), trades[-1]['price'])


async def exchange_loop(exchange_id, symbols):
    print('Starting the', exchange_id, 'exchange loop with', symbols)
    exchange = getattr(ccxt.pro, exchange_id)({
        'newUpdates': True,  # https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#incremental-data-structures
    })
    loops = [symbol_loop(exchange, symbol) for symbol in symbols]
    await gather(*loops)
    await exchange.close()


async def main():
    exchanges = {"gateio": ['BTC/USDT:USDT-230428-31000-P']}
    loops = [exchange_loop(exchange_id, symbols) for exchange_id, symbols in exchanges.items()]
    await gather(*loops)


run(main())


```
Result:
```
Starting the gateio exchange loop with ['BTC/USDT:USDT-230428-31000-P']
Starting the gateio symbol loop with BTC/USDT:USDT-230428-31000-P
Traceback (most recent call last):
  File "/home/mrpouley/dev.py", line 35, in <module>
    run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/mrpouley/dev.py", line 32, in main
    await gather(*loops)
  File "/home/mrpouley/dev.py", line 21, in exchange_loop
    await gather(*loops)
  File "/home/mrpouley/dev.py", line 10, in symbol_loop
    trades = await exchange.watch_trades(symbol)
  File "/home/mrpouley/.local/lib/python3.10/site-packages/ccxt/pro/gate.py", line 365, in watch_trades
    url = self.get_url_by_market(market)
  File "/home/mrpouley/.local/lib/python3.10/site-packages/ccxt/pro/gate.py", line 950, in get_url_by_market
    return baseUrl['usdt'] if market['linear'] else baseUrl['btc']
TypeError: string indices must be integers
```

**Comment by carlosmiei** [comment]
Hello @mrpouley,
Thanks for letting us know, we will take a look asap

**Comment by carlosmiei** [comment]
@mrpouley Sorry I did not notice you were using an option's market. As of now, gate does not have options support but we will try to add it soon.

**Comment by mrpouley** [comment]
OK thanks I was not aware. Symbols appear in load_markets() results though, don't know if it's expected? Any chance binance options will be supported as well?

**Comment by Dan-krm** [comment]
> OK thanks I was not aware. Symbols appear in load_markets() results though, don't know if it's expected? Any chance binance options will be supported as well?

Binance options are basically fully supported through their REST API just a few more methods need support, fetchMarkets is the only method supporting options on gate so far but we will support the rest of the methods soon

**Comment by Dan-krm** [comment]
Closing because option support was added to websocket methods like watchTrades on gate.
