### ISSUE TITLE
Deribit load_markets() error

### ISSUE THREAD

**Issue by mrpouley** [ccxt/ccxt#17651]
### Operating System

linux

### Programming Languages

python

### CCXT Version

3.0.75

### Code

Code:

```
import ccxt

deribit = ccxt.deribit()
deribit.load_markets()  
```

Result:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrpouley/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1459, in load_markets
    markets = self.fetch_markets(params)
  File "/home/mrpouley/.local/lib/python3.10/site-packages/ccxt/deribit.py", line 667, in fetch_markets
    symbol = base + '/' + quote + ':' + settle
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by carlosmiei** [comment]
Hello @mrpouley, thanks for letting us know, we will take a look asap
