### ISSUE TITLE
decimal.ConversionSyntax error

### ISSUE THREAD

**Issue by jaszpol** [ccxt/ccxt#17767]
**OS: Ubuntu 20.04 LTS
Programming Language version: Python 3.8.10
CCXT version: 3.0.77**

Hello All, I have a little issue with 'decimal.ConversionSyntax'. My simple binance trading bot was written by Chat GPT-4, but him can't help me with fixing conversion issue.

Someone could check my code and tell my where and why I have a error in creating a order?

### Logs:
```
2023-04-30 23:13:42 - 2023-04-30 23:13:42.349360 Przeprowadzanie analizy technicznej dla EGLD/USDT
2023-04-30 23:13:42 - 2023-04-30 23:13:42.358235 Przeprowadzanie analizy fundamentalnej dla EGLD/USDT
2023-04-30 23:13:42 - 2023-04-30 23:13:42.663223 Generated signals for EGLD/USDT:
              timestamp  close  buy_signals  sell_signals
490 2023-04-30 14:00:00  41.91          NaN           NaN
491 2023-04-30 15:00:00  41.80          NaN           NaN
492 2023-04-30 16:00:00  41.85          NaN           NaN
493 2023-04-30 17:00:00  41.65          NaN           NaN
494 2023-04-30 18:00:00  41.70          NaN           NaN
495 2023-04-30 19:00:00  41.32          NaN           NaN
496 2023-04-30 20:00:00  41.08          NaN           NaN
497 2023-04-30 21:00:00  41.28          NaN           NaN
498 2023-04-30 22:00:00  41.43          NaN           NaN
499 2023-04-30 23:00:00  41.64        41.64           NaN
2023-04-30 23:13:42 - 2023-04-30 23:13:42.959015 Otwieranie pozycji buy dla EGLD/USDT o wielkości 10.47213229 USDT
2023-04-30 23:13:42 - 2023-04-30 23:13:42.959328 Error while opening buy position for EGLD/USDT: [<class 'decimal.ConversionSyntax'>]
2023-04-30 23:13:42 - Traceback (most recent call last):
  File "bot_binance_final.py", line 237, in open_position
    order = order_method(symbol, None, {'cost': float(position_size)})
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 3372, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/binance.py", line 3948, in create_order
    request['quantity'] = self.amount_to_precision(symbol, amount)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 3390, in amount_to_precision
    result = self.decimal_to_precision(amount, TRUNCATE, market['precision']['amount'], self.precisionMode, self.paddingMode)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/decimal_to_precision.py", line 58, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

### Python Code:

```python
import ccxt
import pandas as pd
import time
import hashlib
import hmac
import pytz
import datetime
import sys
import os
import asyncio
import math
import numpy as np
import sqlite3
import logging
import traceback
from talib import MACD, ATR
from decimal import Decimal, InvalidOperation, ROUND_DOWN


def setup_logging():
    log_file_path = os.path.join('/root/binance', f'bot_binance_{datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")}.log')
    logging.basicConfig(filename=log_file_path, level=logging.INFO, format='%(asctime)s - %(message)s', datefmt='%Y-%m-%d %H:%M:%S')


def log_message(message, print_to_console=True, level='info'):
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')
    log_line = f"{timestamp} {message}"
    
    if print_to_console:
        print(log_line)
    
    if level == 'error':
        logging.error(log_line)
    elif level == 'warning':
        logging.warning(log_line)
    else:
        logging.info(log_line)


def setup_exchange(api_key, api_secret):
    return ccxt.binance({
        'apiKey': api_key,
        'secret': api_secret,
        'enableRateLimit': True,
        'options': {
            'defaultType': 'future'
        }
    })


def setup_database():
    conn = sqlite3.connect('positions.db')
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS positions (
            id INTEGER PRIMARY KEY,
            symbol TEXT NOT NULL,
            entry_price REAL NOT NULL,
            stop_loss_price REAL NOT NULL,
            take_profit_price REAL NOT NULL,
            position_size REAL NOT NULL,
            position_closed INTEGER NOT NULL DEFAULT 0
        )
    """)

    conn.commit()
    return conn, cursor


setup_logging()
api_key = 'MyAPI'
api_secret = 'MyAPISecret'
exchange = setup_exchange(api_key, api_secret)
timeframe = '1h'
risk_level = 0.20
min_balance = 40  # Minimalne saldo dostępne dla inwestycji
conn, cursor = setup_database()



def risk_management(symbol, entry_price, atr_stop_loss_price):
    coin_balance = get_coin_balance('USDT')
    if coin_balance < min_balance:
        log_message(f"Nie wystarczające środki dla {symbol}: dostępne saldo: {coin_balance} USDT")
        return None

    price_difference = abs(entry_price - atr_stop_loss_price)
    max_position_size = coin_balance * 0.2
    if price_difference != 0:
        position_size = (coin_balance * risk_level) / price_difference
        position_size = min(position_size, max_position_size)

        # Dodajemy te dwie linie, aby uniknąć problemu z konwersją NaN na Decimal
        if math.isnan(position_size):
            log_message(f"Nieprawidłowa wartość position_size dla {symbol}")
            return None

        try:
            if isinstance(position_size, (float, int, str)) and not math.isnan(float(position_size)):
                position_size = Decimal(position_size).quantize(Decimal('0.00000001'), rounding=ROUND_DOWN)
        except (InvalidOperation, ValueError):
            log_message(f"Nieprawidłowa operacja podczas konwersji position_size dla {symbol}")
            return None

        return position_size

    else:
        log_message(f"Różnica między ceną wejścia a stop-loss dla {symbol} jest nieprawidłowa: {price_difference}")
        return None


def create_stop_loss_take_profit_order(symbol, side, stop_loss_price, take_profit_price, position_size):
    params = {
        'stopPrice': float(stop_loss_price),
        'stopLimitTimeInForce': 'GTC',
        'stopIcebergQty': float(position_size),
        'price': float(take_profit_price),
        'timeInForce': 'GTC',
        'icebergQty': float(position_size)
    }
    order_type = 'STOP_MARKET' if side == 'buy' else 'TAKE_PROFIT_MARKET'
    price_side = 'sell' if side == 'buy' else 'buy'
    return exchange.create_order(symbol, order_type, price_side, float(position_size), None, params)




def fetch_data(symbol, timeframe, start_date=None, end_date=None):
    if start_date and end_date:
        since = exchange.parse8601(start_date)
        now = exchange.parse8601(end_date)
        all_candles = []
        while since < now:
            candles = exchange.fetch_ohlcv(symbol, timeframe, since)
            if not candles:
                break
            since = candles[-1][0] + 1
            all_candles += candles
            time.sleep(exchange.rateLimit / 1000)
        data = all_candles
    else:
        data = exchange.fetch_ohlcv(symbol, timeframe)
    
    df = pd.DataFrame(data, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    return df

def get_coin_balance(coin):
    balance = exchange.fetch_balance()
    return balance['total'][coin]

def technical_analysis(df, symbol):
    log_message(f"Przeprowadzanie analizy technicznej dla {symbol}", print_to_console=False)
    df['ma5'] = df['close'].rolling(window=5).mean()
    df['ma20'] = df['close'].rolling(window=20).mean()

    delta = df['close'].diff()
    gain = (delta.where(delta > 0, 0)).fillna(0)
    loss = (-delta.where(delta < 0, 0)).fillna(0)
    
    df['avg_gain'] = gain.rolling(window=14).mean()
    df['avg_loss'] = loss.rolling(window=14).mean()
    df['rs'] = df['avg_gain'] / df['avg_loss']
    df['rsi'] = 100 - (100 / (1 + df['rs']))

    df['macd'], df['macdsignal'], df['macdhist'] = MACD(df['close'], fastperiod=12, slowperiod=26, signalperiod=9)

    # Dodane linie
    atr = ATR(df['high'], df['low'], df['close'], timeperiod=14)
    df['atr'] = atr
    df['atr_stoploss'] = df['close'] - 2 * df['atr']

    return df

def fundamental_analysis(symbol):
    log_message(f"Przeprowadzanie analizy fundamentalnej dla {symbol}", print_to_console=False)
    ticker = exchange.fetch_ticker(symbol)
    quote_volume = ticker['quoteVolume']
    volume = ticker['info']['volume']

    return quote_volume, volume




def generate_signals(df, quote_volume, volume, symbol):
    # Usuń ostatni wiersz z ramki danych przed obliczeniem sygnałów
    #df = df.iloc[:-1].copy()

    # Tworzenie nowych kolumn z wartościami NaN
    df['buy_signals'] = np.nan
    df['sell_signals'] = np.nan

    # Aktualizacja wartości kolumn za pomocą .loc[]
    if quote_volume != 0 and volume != 0:
        buy_condition = (df['close'] > df['ma5']) & (df['close'] > df['ma20']) & (df['rsi'] < 50) & (df['macd'] > df['macdsignal'])
        sell_condition = (df['close'] < df['ma5']) & (df['close'] < df['ma20']) & (df['rsi'] > 50) & (df['macd'] < df['macdsignal'])

        df.loc[buy_condition, 'buy_signals'] = df['close'][buy_condition]
        df.loc[sell_condition, 'sell_signals'] = df['close'][sell_condition]
    else:
        log_message(f"Nieprawidłowe wartości 'quote_volume' lub 'volume' dla {symbol}: quote_volume={quote_volume}, volume={volume}")

    log_message(f"Generated signals for {symbol}:\n{df[['timestamp', 'close', 'buy_signals', 'sell_signals']].tail(10)}", print_to_console=False)
    return df





def create_stop_loss_take_profit_order(symbol, side, stop_loss_price, take_profit_price, position_size):
    params = {
        'stopPrice': float(stop_loss_price),
        'stopLimitTimeInForce': 'GTC',
        'stopIcebergQty': float(position_size),
        'price': float(take_profit_price),
        'timeInForce': 'GTC',
        'icebergQty': float(position_size)
    }
    order_type = 'STOP_MARKET' if side == 'buy' else 'TAKE_PROFIT_MARKET'
    price_side = 'sell' if side == 'buy' else 'buy'
    return exchange.create_order(symbol, order_type, price_side, float(position_size), None, params)

async def open_position(symbol, position_size, entry_price, stop_loss_price, take_profit_price, position_type):
    log_message(f"Otwieranie pozycji {position_type} dla {symbol} o wielkości {position_size} USDT")
    
    try:
        # Sprawdzenie wartości zamówienia i dostosowanie do minimalnej wartości, jeśli jest konieczne
        try:
            position_size = Decimal(format(float(position_size), '.8f'))
        except decimal.ConversionSyntax as e:
            log_message(f"Błąd konwersji wartości '{position_size}': {e}")
            return

        min_notional = 5.0
        if position_size < min_notional:
            position_size = min_notional * 1.02
            log_message(f"Adjusted order value for {symbol} to {position_size} USDT as it was below the minimum required value ({min_notional}).")
        
        order_method = exchange.create_market_buy_order if position_type == 'buy' else exchange.create_market_sell_order
        order = order_method(symbol, None, {'cost': float(position_size)})
        create_stop_loss_take_profit_order(symbol, position_type, stop_loss_price, take_profit_price, float(position_size))

        cursor.execute("""
            INSERT INTO positions (symbol, entry_price, stop_loss_price, take_profit_price, position_size)
            VALUES (?, ?, ?, ?, ?)
        """, (symbol, entry_price, stop_loss_price, take_profit_price, position_size))
        conn.commit()
    except Exception as e:
        log_message(f"Error while opening {position_type} position for {symbol}: {str(e)}", print_to_console=True)
        logging.error(traceback.format_exc())




async def manage_open_positions(backtest=False):
    cursor.execute("""
        SELECT * FROM positions WHERE position_closed = 0
    """)
    open_positions = cursor.fetchall()

    for position in open_positions:
        position_id, symbol, entry_price, stop_loss_price, take_profit_price, position_size, position_closed = position
        current_price = exchange.fetch_ticker(symbol)['last']

        if current_price <= stop_loss_price or current_price >= take_profit_price:
            if current_price <= stop_loss_price:
                log_message(f"Closing position for {symbol} at Stop Loss price {current_price}")
            else:
                log_message(f"Closing position for {symbol} at Take Profit price {current_price}")

            try:
                # Zamykanie pozycji
                if entry_price > stop_loss_price:
                    exchange.create_market_sell_order(symbol, position_size)
                else:
                    exchange.create_market_buy_order(symbol, position_size)

                # Aktualizacja bazy danych, że pozycja została zamknięta
                cursor.execute("""
                    UPDATE positions
                    SET position_closed = 1
                    WHERE id = ?
                """, (position_id,))
                conn.commit()
            except Exception as e:
                log_message(f"Error while closing position for {symbol}: {str(e)}", print_to_console=True)
                logging.error(traceback.format_exc())


async def backtest_all(start_date, end_date):
    symbols = exchange.load_markets()
    futures_symbols = [s for s in symbols.keys() if s.endswith('USDT')]

    for symbol in futures_symbols:
        try:
            log_message(f"Backtesting for {symbol}")
            await backtest_strategy(symbol, start_date, end_date)
        except Exception as e:
            log_message(f"Error in backtest_all function for {symbol}: {str(e)}", print_to_console=True)
            logging.error(traceback.format_exc())

               
def is_position_open(symbol):
    cursor.execute("""
        SELECT * FROM positions WHERE symbol = ? AND position_closed = 0
    """, (symbol,))
    open_positions = cursor.fetchall()
    return len(open_positions) > 0
        


async def strategy(symbol=None, backtest=False, TestAll=False):
    if TestAll:
        await backtest_all(start_date, end_date)
        return

    else:
        futures_symbols = [symbol]

    for symbol in futures_symbols:
        try:
            df = fetch_data(symbol, timeframe)
            df = technical_analysis(df, symbol)
            quote_volume, volume = fundamental_analysis(symbol)
            df = generate_signals(df, quote_volume, volume, symbol)

            last_row = df.iloc[-1]
            if not is_position_open(symbol):
                entry_price = last_row['close']
                stop_loss_price = last_row['atr_stoploss']
                position_size = risk_management(symbol, entry_price, stop_loss_price)

                if position_size is not None and not math.isnan(float(position_size)):
                    position_size_decimal = Decimal(str(position_size).strip())
                    if not pd.isna(last_row['buy_signals']):
                        take_profit_price = entry_price * 1.04
                        await open_position(symbol, position_size_decimal, entry_price, stop_loss_price, take_profit_price, 'buy')
                    elif not pd.isna(last_row['sell_signals']):
                        take_profit_price = entry_price * 0.96
                        await open_position(symbol, position_size_decimal, entry_price, stop_loss_price, take_profit_price, 'sell')

        except Exception as e:
            log_message(f"Error in strategy function for {symbol}: {str(e)}", print_to_console=True)
            logging.error(traceback.format_exc())




async def backtest_strategy(symbol, start_date, end_date):
    df = fetch_data(symbol, timeframe, start_date, end_date)
    df = technical_analysis(df, symbol)
    quote_volume, volume = fundamental_analysis(symbol)
    df = generate_signals(df, quote_volume, volume, symbol)

    df['position'] = None
    df['pnl'] = 0

    position = 'none'
    entry_price = 0
    for index, row in df.iterrows():
        if not pd.isna(row['buy_signals']) and position == 'none':
            position = 'long'
            entry_price = row['buy_signals']
        elif not pd.isna(row['sell_signals']) and position == 'none':
            position = 'short'
            entry_price = row['sell_signals']
        elif position == 'long' and (not pd.isna(row['sell_signals']) or row['close'] <= row['low'] * 0.99 or row['close'] >= entry_price * 1.04):
            position = 'none'
            pnl = (row['close'] - entry_price) * 1.0  # Change the multiplier to adjust position size
            df.at[index, 'pnl'] = pnl
        elif position == 'short' and (not pd.isna(row['buy_signals']) or row['close'] >= row['high'] * 1.01 or row['close'] <= entry_price * 0.96):
            position = 'none'
            pnl = (entry_price - row['close']) * 1.0  # Change the multiplier to adjust position size
            df.at[index, 'pnl'] = pnl

    df['cumulative_pnl'] = df['pnl'].cumsum()
    log_message(f"Backtest results for {symbol}: invested: 100 USDT, final balance: {100 + df.iloc[-1]['cumulative_pnl']} USDT, gain/loss: {df.iloc[-1]['cumulative_pnl']} USDT")


async def main(backtest=False, start_date=None, end_date=None):
    symbols = ['MKR/USDT', 'ETH/USDT', 'BNB/USDT', 'LTC/USDT', 'BCH/USDT', 'ZEC/USDT', 'ZEN/USDT', 'EGLD/USDT', 'QNT/USDT', 'FXS/USDT', 'APT/USDT', 'SSV/USDT']

    if backtest:
        tasks = [backtest_strategy(symbol, start_date, end_date) for symbol in symbols]
        await asyncio.gather(*tasks)
    else:
        while True:
            tasks = [strategy(symbol, backtest) for symbol in symbols]
            tasks.append(manage_open_positions(backtest))
            await asyncio.gather(*tasks)
            await asyncio.sleep(600)

if __name__ == "__main__":
    backtest_mode = False  # Ustaw na True, aby uruchomić w trybie backtest
    start_date = "2023-01-01T00:00:00Z"  # Data rozpoczęcia backtestu
    end_date = "2023-03-31T23:59:59Z"  # Data zakończenia backtestu
    TestAll = False

    asyncio.run(main(backtest=backtest_mode, start_date=start_date, end_date=end_date))
    #loop = asyncio.get_event_loop() #URUCHAMIANIE TestAll
    #loop.run_until_complete(strategy(TestAll=True)) #URUCHAMIANIE TestAll
```

**Comment by carlosmiei** [comment]
Hello @jaszpol that is a huge amount of code, can you please isolate the failing part so it's easier for use to analyze?

**Comment by jaszpol** [comment]
> Hello @jaszpol that is a huge amount of code, can you please isolate the failing part so it's easier for use to analyze?


Hello error is in open position function. I try to fix it but it's still not working.

```
2023-05-04 14:55:16 - 2023-05-04 14:55:16.604840 Przeprowadzanie analizy technicznej dla ZEN/USDT
2023-05-04 14:55:16 - 2023-05-04 14:55:16.611673 Przeprowadzanie analizy fundamentalnej dla ZEN/USDT
2023-05-04 14:55:16 - 2023-05-04 14:55:16.874735 Generated signals for ZEN/USDT:
              timestamp  close  buy_signals  sell_signals
490 2023-05-04 05:00:00  9.548          NaN           NaN
491 2023-05-04 06:00:00  9.552          NaN           NaN
492 2023-05-04 07:00:00  9.574          NaN           NaN
493 2023-05-04 08:00:00  9.627          NaN           NaN
494 2023-05-04 09:00:00  9.675          NaN           NaN
495 2023-05-04 10:00:00  9.722          NaN           NaN
496 2023-05-04 11:00:00  9.659          NaN           NaN
497 2023-05-04 12:00:00  9.610          NaN           NaN
498 2023-05-04 13:00:00  9.546          NaN           NaN
499 2023-05-04 14:00:00  9.557          NaN         9.557
2023-05-04 14:55:17 - 2023-05-04 14:55:17.616102 Otwieranie pozycji sell dla ZEN/USDT o wielkości 10 USDT
2023-05-04 14:55:17 - 2023-05-04 14:55:17.616365 Error while opening sell position for ZEN/USDT: size: '10.0' [<class 'decimal.ConversionSyntax'>]
2023-05-04 14:55:17 - Traceback (most recent call last):
  File "bot_binance_final.py", line 242, in open_position
    order = order_method(symbol, None, {'cost': float(position_size)})
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 3375, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/binance.py", line 3948, in create_order
    request['quantity'] = self.amount_to_precision(symbol, amount)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 3390, in amount_to_precision
    result = self.decimal_to_precision(amount, TRUNCATE, market['precision']['amount'], self.precisionMode, self.paddingMode)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/base/decimal_to_precision.py", line 58, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

```python
async def open_position(symbol, position_size, entry_price, stop_loss_price, take_profit_price, position_type):
    log_message(f"Otwieranie pozycji {position_type} dla {symbol} o wielkości {position_size} USDT")

    try:
        # Sprawdzenie wartości zamówienia i dostosowanie do minimalnej wartości, jeśli jest konieczne
        try:
            position_size = float(position_size)
        except ValueError as e:
            log_message(f"Błąd konwersji wartości '{position_size}': {e}")
            return

        min_notional = 5.0
        if position_size < min_notional:
            position_size = min_notional * 1.02
            log_message(f"Adjusted order value for {symbol} to {position_size} USDT as it was below the minimum required value ({min_notional}).")

        order_method = exchange.create_market_buy_order if position_type == 'buy' else exchange.create_market_sell_order
        order = order_method(symbol, None, {'cost': float(position_size)})
        create_stop_loss_take_profit_order(symbol, position_type, stop_loss_price, take_profit_price, float(position_size))

        cursor.execute("""
            INSERT INTO positions (symbol, entry_price, stop_loss_price, take_profit_price, position_size)
            VALUES (?, ?, ?, ?, ?)
        """, (symbol, entry_price, stop_loss_price, take_profit_price, position_size))
        conn.commit()
    except Exception as e:
        log_message(f"Error while opening {position_type} position for {symbol}: size: '{position_size}' {str(e)}", print_to_console=True)
        logging.error(traceback.format_exc())

```

**Comment by carlosmiei** [comment]
@jaszpol Open position is still your function, I would  like to have only the ccxt function throwing the error and the parameters used please

**Comment by jaszpol** [comment]
> @jaszpol Open position is still your function, I would  like to have only the ccxt function throwing the error and the parameters used please 

usr/local/lib/python3.8/dist-packages/ccxt/base/decimal_to_precision.py

**Comment by spc789** [comment]
somewhere lookup the precision of the current pair, for example : 
```qtyPrecision = int(market['precision']['amount'])```

somewhere define a rounding function which rounds position_size rounded to the lowest amount of the exchange's precision for the symbol, like : (where qtyPrecision is the precision size of the exchange for that particular symbol)

```
def rounding(size, qtyPrecision):
        tmp = float(size)*(10**qtyPrecision)
        tmp = math.floor(tmp)
        tmp / (10**qtyPrecision)
        return tmp
```

change 

```order_method = exchange.create_market_buy_order if position_type == 'buy' else exchange.create_market_sell_order
        order = order_method(symbol, None, {'cost': float(position_size)})```
to 

```
side = 'buy' if position_type == 'buy' else 'sell'

order = exchange.create_order(
    symbol=symbol,
    type='market',
    side=side,
    amount=rounding(position_size, qtyPrecision)
)
```
