### ISSUE TITLE
AuthenticationError: gemini sign() requires an account-key, master-keys are not-supported

### ISSUE THREAD

**Issue by alpesh-parmar** [ccxt/ccxt#17773]
### Operating System

windows 11

### Programming Languages

JS

### CCXT Version

3.0.90

### Description

AuthenticationError: gemini sign() requires an account-key, master-keys are not-supported
    at gemini.sign (C:\Projects\fin-asset-mgmt\ccxt\node_modules\ccxt\dist\cjs\src\gemini.js:1552:23)
    at gemini.fetch2 (C:\Projects\fin-asset-mgmt\ccxt\node_modules\ccxt\dist\cjs\src\base\Exchange.js:2431:30)
    at gemini.request (C:\Projects\fin-asset-mgmt\ccxt\node_modules\ccxt\dist\cjs\src\base\Exchange.js:2435:16)
    at gemini.fetchBalance (C:\Projects\fin-asset-mgmt\ccxt\node_modules\ccxt\dist\cjs\src\gemini.js:944:26)
    at ExchangeService.fetchBalanceExchange (C:\Projects\fin-asset-mgmt\ccxt\src\exchange\exchange.service.ts:775:12)
    at ExchangeService.ValidateKey (C:\Projects\fin-asset-mgmt\ccxt\src\exchange\exchange.service.ts:768:18)
    at ExchangeService.fetchbalance (C:\Projects\fin-asset-mgmt\ccxt\src\exchange\exchange.service.ts:875:24)
    at ExchangeController.fetchbalance (C:\Projects\fin-asset-mgmt\ccxt\src\exchange\exchange.controller.ts:43:12)
    at C:\Projects\fin-asset-mgmt\ccxt\node_modules\@nestjs\microservices\context\rpc-proxy.js:11:32
    at ServerTCP.handleMessage (C:\Projects\fin-asset-mgmt\ccxt\node_modules\@nestjs\microservices\server\server-tcp.js:62:54)

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @alpesh-parmar,
As the error message suggests, `master-keys` are not supported, so upon creating an API key you should select `primary` 
![image](https://user-images.githubusercontent.com/43336371/236182106-4d0a2aa3-438d-4d8f-80db-5f83466b5c4d.png)

**Comment by alpesh-parmar** [comment]
Thanks team working fine, after your suggestions. 🥇👍
