### ISSUE TITLE
mexc fetchTickers throws disambiguate between different markets exception

### ISSUE THREAD

**Issue by dmatora** [ccxt/ccxt#17902]
### Operating System

Debian 11

### Programming Languages

JS

### CCXT Version

3.0.90

### Description

Was working fine for a while and then suddenly I started getting this exception

### Code

```
            ArgumentsRequired: mexc safeMarket() requires a fourth argument for BEP20(BSC)USDT to disambiguate between different markets with the same market id
            at mexc.safeMarket (/home/user/project/ccxt-lib/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2567:31)
            at mexc.parseTicker (/home/user/project/ccxt-lib/node_modules/ccxt/dist/cjs/src/mexc.js:1579:23)
            at mexc.parseTickers (/home/user/project/ccxt-lib/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3200:49)
            at mexc.fetchTickers (/home/user/project/ccxt-lib/node_modules/ccxt/dist/cjs/src/mexc.js:1502:21)
            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by carlosmiei** [comment]
Hello @dmatora,
Thanks for reporting it, we will take a look asap.

**Comment by dmatora** [comment]
Well it seems working again

**Comment by carlosmiei** [comment]
> Well it seems working again

@dmatora yeah I can't reproduce it locally, pls let us know if you have any extra information that could help debug the issue.

**Comment by moofone** [comment]
This is also happening on 4.1.51 on binance watchMyTrades(). Fills blow up.
4.1.20 working normally.

**Comment by ttodua** [comment]
we haven't seen this issue since then. I assume that could have been temporary issue or could have been fixed already.
for now, I'm closing this topic.
if anyone still sees any issue, let us know, so we can look into that again.
