### ISSUE TITLE
OSError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by 111111m** [ccxt/ccxt#17918]
### Operating System

Ubuntu

### CCXT Version

3.0.98

### Description

Can't establish connection
I have tried to downgrade urlib3 but the error persists. 

2023-05-15 10:58:37,826: loading name: lvtu, exchange name: binance,  pair name: ETHBUSD
2023-05-15 10:58:37,826: loading name: lvtu, exchange name: binance,  pair name: ETHUSDT
2023-05-15 10:58:37,826: loading name: lvtu, exchange name: binance,  pair name: BTCUSDT
2023-05-15 10:58:37,826: name: lvtu, exchange: binance
/home/ic/Desktop/worldbreak-dev514
2023-05-15 10:58:37,826: GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1684119517826&recvWindow=10000&signature=9cffa32deb8e553a54008e00b389c83a6c322ac66c9453bb96c819807f0e01ca, Request: {'X-MBX-APIKEY': 'QNX9wlHDJhEG5pbxuOmHo4Qp9DNU1H97EGVp4xYPre5OyJum3tgV1s9qg5DqmHz6', 'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} None
2023-05-15 10:58:37,826: Starting new HTTPS connection (1): api.binance.com:443
^CTraceback (most recent call last):
  File "/home/ic/Desktop/worldbreak-dev514/scripts/performance_report.py", line 614, in <module>
    balances = _exchange.fetch_balance(params={'type': 'future'})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/ccxt/binance.py", line 2287, in fetch_balance
    self.load_markets()
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1390, in load_markets
    currencies = self.fetch_currencies()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/ccxt/binance.py", line 1638, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/ccxt/base/types.py", line 25, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/ccxt/binance.py", line 7167, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/ccxt/base/exchange.py", line 2836, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/ccxt/base/exchange.py", line 533, in fetch
    response = self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ic/anaconda3/envs/trading/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
KeyboardInterrupt

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @111111m 

Would you like to run this command and see whether your machine can connect to binance.com?

```BASH
$ curl https://api.binance.com
```

**Comment by 111111m** [comment]
(trading) ➜  worldbreak-dev514 curl https://api.binance.com
<!DOCTYPE html><html><head><title>Test OK</title></head><body></body></html>

**Comment by 111111m** [comment]
> Hi @111111m
> 
> Would you like to run this command and see whether your machine can connect to binance.com?
> 
> ```shell
> $ curl https://api.binance.com
> ```

(trading) ➜ worldbreak-dev514 curl https://api.binance.com/

<title>Test OK</title>
Yes, it can.
