### ISSUE TITLE
Failed to fetch result mexc: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by tmnvvv** [ccxt/ccxt#17922]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.0.104

### Description

When working with the exchange **mexc**, began to receive this exception. I think that this problem is solved by adding a check for **none**.

### Code

```
[2023-05-15 12:22:46,615] ERROR: Failed to fetch result mexc: 'NoneType' object has no attribute 'keys'
Traceback (most recent call last):
  File "/app/src/workers/last_price.py", line 163, in run
    last_prices = task.result()
  File "/app/src/workers/last_price.py", line 54, in fetch_last_prices
    tickers_types = await loader.get_tickers(proxies)
  File "/app/src/loaders/base_loader.py", line 108, in get_tickers
    tickers = await loader.fetch_tickers()  # symbols=symbols
  File "/usr/local/lib/python3.8/site-packages/ccxt/async_support/mexc.py", line 1456, in fetch_tickers
    return self.parse_tickers(tickers, symbols)
  File "/usr/local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 2348, in parse_tickers
    marketIds = list(tickers.keys())
AttributeError: 'NoneType' object has no attribute 'keys'

```

**Comment by carlosmiei** [comment]
Hello @tmnvvv,
Can you please show me how you're calling `fetch_tickers` ?  Can't reproduce this issue locally

**Comment by carlosmiei** [comment]
> I can try to get tickers
> 
> ```
>     async def get_tickers(self, proxies):
>         results = {}
>         for loader_type, loader in self.ccxts.items():
>             if proxies:
>                 proxy = random.choice(proxies)
>                 loader.aiohttp_proxy = f'http://{str(proxy)}'
>             tickers = await loader.fetch_tickers()  # symbols=symbols
>             results[loader_type] = tickers
>         return results
> ```

@tmnvvv Do you mind sharing the location used? Not sure if it might be related to that

**Comment by tmnvvv** [comment]
I noticed such a pattern, when I rollback to version 2.*.*, the mexc exchange works, but after updating to the latest version, there are problems that I described above!
It's not clear what happened!
` else:
            marketIds = list(**tickers.keys()**) - it's problem
            for i in range(0, len(marketIds)):
                marketId = marketIds[i]
                market = self.safe_market(marketId)
                ticker = self.extend(self.parse_ticker(tickers[marketId], market), params)
                results.append(ticker)
        symbols = self.market_symbols(symbols)
        return self.filter_by_array(results, 'symbol', symbols)
`

**Comment by ttodua** [comment]
late reply in this old topic, but I no longer see/reproduce any issue with mexc.
if users are still experiencing smth, let us know again, so we can look into that.
