### ISSUE TITLE
Price in market order results in QuoteOrderQty market order

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#17932]
### Operating System

Windows

### Programming Languages

JS

### CCXT Version

3.0.103

### Description

The documentation says the following:

"price the price at which the order is to be fullfilled at in units of the quote currency (ignored in market orders)"

However, by coincidence I found out that this is not the case.

When placing a market order on Binance, with the price set, it seems to turn the order into a QuoteOrderQty market order. The way I found out is because a user of my software was placing a SHIB/USDT market order, which resulted in the following exception:

InvalidOrder: binance {"code":-1013,"msg":"Quote order qty market orders are not supported for this symbol."}
    at binance.throwExactlyMatchedException (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\cjs\src\base\Exchange.js:2803:19)
    at binance.handleErrors (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\cjs\src\binance.js:7566:18)
    at C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\cjs\src\base\Exchange.js:761:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async binance.fetch2 (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\cjs\src\base\Exchange.js:2445:16)
    at async binance.request (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\cjs\src\binance.js:7596:26)
    at async binance.createOrder (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\cjs\src\binance.js:4210:26)
    at async placeOrder (C:\code\node-apps\balance-bot\bb-v2\bot.js:3038:31)

When is set the price to undefined (or leave it out completely), this issue does not occur.

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @hodlerhacks 

There is `quoteOrderQty` in binance options, can turn this off by setting false.

Let me know if you have other issues.

**Comment by hodlerhacks** [comment]
Yes, I'm aware of that option, and I've worked around this in my code, so I'm good. Just wanted to share this in case you want to address this (in code or documentation).

**Comment by YuriyTigiev** [comment]
> 

Could you provide an example of how to disable it? I'm wondering if I should apply this specifically to Binance or to a particular symbol. My code has been functioning with over 20 pairs for a few years. However, starting last week, a hive began to receive errors for some pairs. I'm unsure of the cause. Any insights would be appreciated.

**Comment by SirZoX** [comment]
@YuriyTigiev when you instantiate the connection to binance you can set several options:

binance = getattr(ccxt, 'binance')({
    'apiKey':xxxx,
    'secret': yyyy,
    'timeout': 10000,
    'enableRateLimit': True,
    'adjustForTimeDifference':True,
    **'quoteOrderQty ': False,**
})

**Comment by YuriyTigiev** [comment]
The solution given doesn't seem to be effective for certain symbols in my particular scenario.

```

Python 3.11.1 (main, Feb  4 2023, 05:21:26) [GCC 8.5.0 20210514 (Red Hat 8.5.0-16)] on linux
ccxt==4.0.33

        if(self.exchange_name in ['binance']):
            self.exchange = getattr(ccxt, self.exchange_name)({
                'apiKey': self.api_key,
                'secret': self.secret,
                'password': self.password,
                'enableRateLimit': True,
                'asyncio_loop': self.loop,
                'quoteOrderQty ': False,
                'options': {
                    'defaultType': 'spot'
                }
            })
        else:
            self.exchange = getattr(ccxt, self.exchange_name)({
                'apiKey': self.api_key,
                'secret': self.secret,
                'password': self.password,
                'enableRateLimit': True,
                'asyncio_loop': self.loop,
                'options': {
                    'defaultType': 'spot'
                }
            })

      order: dict = await self.exchange.create_order(self.symbol, 'market', self.side, order_amount, current_price)
 

```

```
2023-07-21 19:47:48 :: INFO     :: Envirnoment: PROD	Exchange: binance	Owner: YuriyTigiev
2023-07-21 23:00:02 :: WARNING  :: ETH/BTC :: buy :: 1h :: buy_bbands_crypto_BTC_* :: Insufficient balance. Total balance: 0.00027087, used balance: 0.0, free balance: 0.00027087, currency: BTC, order cost: 0.000322575
2023-07-21 23:00:02 :: WARNING  :: XRP/BTC :: buy :: 1h :: buy_candels_volume_crypto_BTC_* :: Insufficient balance. Total balance: 0.00027087, used balance: 0.0, free balance: 0.00027087, currency: BTC, order cost: 0.00030888
2023-07-22 00:00:11 :: WARNING  :: binance {"code":-1013,"msg":"Quote order qty market orders are not supported for this symbol."}
2023-07-22 00:00:13 :: WARNING  :: binance {"code":-1013,"msg":"Quote order qty market orders are not supported for this symbol."}



```

**Comment by SirZoX** [comment]
Sorry @YuriyTigiev  for hearing this.
But i have another possible solution. Remove the 'quoteOrderQty' you puto before anda when you make the orden, remove the 'price' param if you are makin market operations. This works for me. Create order just sending symbol, type and amount params.

**Comment by YuriyTigiev** [comment]
> Sorry @YuriyTigiev for hearing this. But i have another possible solution. Remove the 'quoteOrderQty' you puto before anda when you make the orden, remove the 'price' param if you are makin market operations. This works for me. Create order just sending symbol, type and amount params.

Can you show me an example ? Does it work only for binance or ?

**Comment by SirZoX** [comment]
In my case, this solved my problem with error -1013

`binance.createOrder(symbol='BTC/USDT', type="market", side="buy", amount=0.015)`

**Comment by carlotestor** [comment]
This is documented behaviour on Binance rather than a docs bug — the "price is ignored in market orders" line is the *general* rule, but Binance is one of the exchanges that supports quote-denominated market orders, so CCXT uses `price` to compute `quoteOrderQty = amount * price` when both are given.

Three ways to get plain base-amount market orders:

```js
// 1. simply omit price (recommended)
await binance.createOrder ('SHIB/USDT', 'market', 'buy', amount);

// 2. disable the behaviour globally
const binance = new ccxt.binance ({
    'options': { 'createOrder': { 'quoteOrderQty': false } },
});

// 3. or per-call
await binance.createOrder ('SHIB/USDT', 'market', 'buy', amount, price,
                           { 'quoteOrderQty': false });
```

Note for @YuriyTigiev / @SirZoX: the option must live under `options.createOrder.quoteOrderQty` — a top-level `'quoteOrderQty': False` (and especially `'quoteOrderQty '` with a trailing space) is silently ignored, which is why it appeared not to work. That, plus dropping `price`, is why `createOrder(symbol, 'market', side, amount)` fixed it.

Conversely, if you *want* to spend an exact quote amount, that's what `createMarketBuyOrderWithCost()` is for.
