### ISSUE TITLE
AioHttp and event loop error.

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#17947]
### Operating System

windows 10

### Programming Languages

python

### CCXT Version

3.0.106

### Description

Please run the following code.

1) commented

```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000027D5120B3A0>
Traceback (most recent call last):
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
this is probably caused by aiohttp as documented [here](https://github.com/Azure/azure-sdk-for-python/issues/9060) and [here ](https://github.com/aio-libs/aiohttp/issues/4324). The error typically causes only a noisy shutdown.

2 ) uncommented.

we have the same error as above but `main()` is called twice. This could cause a lot of problems.

### Code

```
import ccxt.pro
import ccxt.async_support
import asyncio

print('CCXT Version:', ccxt.__version__)

async def bitmex_test():
    bitmex_test = ccxt.pro.bitmex({'verbose': False,
                                  'enableRateLimit': False,
                                   'apiKey': '5Txxxxxxxxxxxx9jwTiw',
                                   'secret': 'o-Q2LETxxxxxxxxxxxxwST82GZnv10Gj6',
                                  })
    if bitmex_test.urls['test']:
        bitmex_test.urls['api'] = bitmex_test.urls['test']
    markets = await bitmex_test.load_markets()
    print("bitmex_test loaded")
    await bitmex_test.sleep(3000)
    return bitmex_test

async def main():
    exchange = await bitmex_test()
    num_orders = 5
    symbol = 'BTC/USD:BTC'
    side = 'buy'
    amount = 100
    price = 24000
    try:
        print('Testing', symbol)
        results = []
        for i in range(0, num_orders):
            timestamp = exchange.milliseconds()
            order = await exchange.create_order(symbol, 'limit', side, amount, price)
            elapsed = exchange.milliseconds() - timestamp
            canceled = await exchange.cancel_order(order['id'], symbol)
            results.append(elapsed)
            print(elapsed, 'ms')
            await asyncio.sleep(1)
        await exchange.close()
        sum = exchange.sum(*results)
        average = sum / len(results)
        print('Average:', average, 'ms')
    except Exception as e:
        print(type(e).__name__, str(e))

# if uncommented main is run 2 times

# if __name__ == "__main__":
#     loop = asyncio.get_event_loop()
#     loop.run_until_complete(main())

asyncio.run(main())
  

```

**Comment by carlosmiei** [comment]
Hello @ShieldTrade 

Can you please reduce your code to the MRE? (minimal reproducible example)

**Comment by ShieldTrade** [comment]
@carlosmiei I do not really understand you. This is a short code inspired from your [example](https://github.com/ccxt/ccxt/blob/master/examples/py/measure-latency.py). Please. how do you aspect me to change it to a MRE?

**Comment by frosty00** [comment]
https://stackoverflow.com/a/65984358
