### ISSUE TITLE
Python Bittrex fetch_balance() authentication error

### ISSUE THREAD

**Issue by ballaj2001** [ccxt/ccxt#1796]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.10.738
- Exchange: Bittrex
- Method: fetch_balance()

I tried searching and I found a similar issue but not in Python, the fix doesn't seem to apply, or at least I didn't see how to make it. Basically I get **_ccxt.base.errors.AuthenticationError: bittrex requires `apiKey`_** but only when I use the **_fetch_balance()_** method. Everything else seems to work fine. I have not reached the ordering stages but my API keys were setup with all options.

**code snippet**
```
import ccxt
import csv
from operator import itemgetter
from APIkeys import *

#Instantiation **************************************************************************
my_exchange_1 = ccxt.bittrex({"apikey":bittrex_apikey, "secret":bittrex_secret, "verbose":True})
balances_1=my_exchange_1.fetch_balance()
print(balances_1)
```
**Verbose Error Snippet**
```
GET https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries 
Request: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None
GET https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries 
Response: {'Date': 'Tue, 06 Feb 2018 18:31:49 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '34513', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d937

[Edited to remove extra bit of auto market load in the middle and get to actual Errror]

B-H99Y-6PSGQ","Notice":null}]}
Traceback (most recent call last):
  File "c:\Python\Learning\Hello\bittrextest V2.py", line 22, in <module>
    balances_1=my_exchange_1.fetch_balance()
  File "C:\Users\Ballaj2001\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bittrex.py", line 210, in fetch_balance
    response = self.accountGetBalances()
  File "C:\Users\Ballaj2001\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bittrex.py", line 659, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Ballaj2001\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 296, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "C:\Users\Ballaj2001\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bittrex.py", line 618, in sign
    self.check_required_credentials()
  File "C:\Users\Ballaj2001\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 753, in check_required_credentials
    raise AuthenticationError(self.id + ' requires `' + key + '`')
ccxt.base.errors.AuthenticationError: bittrex requires `apiKey`
```
Also side note this is an amazing project and has probably saved me weeks of time.

Thanks in advance,

Josiah

**Comment by kroitor** [comment]
In your constructor make sure the letter *K* in api*K*ey is uppercase, not lowercase.

**Comment by ballaj2001** [comment]
Oh my haha, thanks.

Sorry, can't believe I didn't notice that. Works fine now.
