### ISSUE TITLE
Kucoin Futures watchTickers 'The socket was closed while data was being compressed' sockets error

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#17988]
### Operating System

Debian (Docker)

### Programming Languages

JS

### CCXT Version

3.0.79

### Description

We are using `kucoinfutures` `watchTickers` method to watch all tickers data 24/7.
Once per day we are close `ccxt.client` connection and resubscribe to all markets sockets again.

After 1-2 days multiple `watch` connections starts throwing error, that is inside `ccxt/node_modules`:
```
Error: The socket was closed while data was being compressed
	at /var/www/project/tickerjs/node_modules/ccxt/node_modules/ws/lib/sender.js:410:21
	at /var/www/project/tickerjs/node_modules/ccxt/node_modules/ws/lib/permessage-deflate.js:326:9
	at PerMessageDeflate.cleanup (/var/www/project/tickerjs/node_modules/ccxt/node_modules/ws/lib/permessage-deflate.js:143:9)
	at WebSocket.emitClose (/var/www/project/tickerjs/node_modules/ccxt/node_modules/ws/lib/websocket.js:253:57)
	at TLSSocket.socketOnClose (/var/www/project/tickerjs/node_modules/ccxt/node_modules/ws/lib/websocket.js:1264:15)
	at TLSSocket.emit (node:events:525:35)
	at node:net:301:12
	at Socket.done (node:_tls_wrap:588:7)
	at Object.onceWrapper (node:events:628:26)
	at Socket.emit (node:events:525:35)
```

After this error whole socket connection closes: `Ticker: triggered 'onClose' - socket closed [Code: 1000 | Reason: Bye].`.
But trying to resubscribe again after 'onClose' event was triggered - the `The socket was closed while data was being compressed` error will be thrown again, so we are in a loop and only what helping is to restart the application.
We are tried to do not close connection but suddenly this error happens again after 2 days.

Maybe you have any suggestions how to resolve this issue?

### Code

```
  

```

**Comment by respectabiggle** [comment]
Same, though I had a lot of sockets open (ccxt.pro), most probably including kucoin

**Comment by ttodua** [comment]
late follow-up on old issue, just wanted to say that kucoin API had an old engine by that time and they said in the past that they had updated engine, so maybe this issue should not be happening, but if still happens, let us know again.
