### ISSUE TITLE
CoinEx watchTicker(): maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by grozz97** [ccxt/ccxt#18015]
### Operating System

Ubuntu 20.04.5 LTS

### Programming Languages

python

### CCXT Version

3.1.6

### Description

The problem may occur a few minutes or a few hours after starting the program:

```
2023-05-25 11:37:39,543 ERROR maximum recursion depth exceeded while calling a Python object: Traceback (most recent call last):
  File "main.py", line 366, in watch_ticker
    await exchange.watch_ticker(symbol)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/coinex.py", line 375, in watch_ticker
    return await self.watch_tickers([symbol], params)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/coinex.py", line 405, in watch_tickers
    return await self.watch_tickers(symbols, params)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/coinex.py", line 405, in watch_tickers
    return await self.watch_tickers(symbols, params)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/coinex.py", line 405, in watch_tickers
    return await self.watch_tickers(symbols, params)
  [Previous line repeated 981 more times]
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/coinex.py", line 388, in watch_tickers
    type, params = self.handle_market_type_and_params('watchTickers', None, params)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 1925, in handle_market_type_and_params
    defaultType = self.safe_string_2(self.options, 'defaultType', 'type', 'spot')
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 706, in safe_string_2
    return Exchange.safe_either(Exchange.safe_string, dictionary, key1, key2, default_value)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 818, in safe_either
    value = method(dictionary, key1)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 645, in safe_string
    return str(dictionary[key]) if Exchange.key_exists(dictionary, key) else default_value
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 623, in key_exists
    if hasattr(dictionary, 'getitem') and not isinstance(dictionary, str):
RecursionError: maximum recursion depth exceeded while calling a Python object

2023-05-25 11:37:39,602 ERROR Task exception was never retrieved
future: <Task finished name='Task-5' coro=<exchange_loop() done, defined at main.py:305> exception=SystemExit(None)>
Traceback (most recent call last):
  File "main.py", line 366, in watch_ticker
    await exchange.watch_ticker(symbol)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/coinex.py", line 375, in watch_ticker
    return await self.watch_tickers([symbol], params)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/coinex.py", line 405, in watch_tickers
    return await self.watch_tickers(symbols, params)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/coinex.py", line 405, in watch_tickers
    return await self.watch_tickers(symbols, params)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/coinex.py", line 405, in watch_tickers
    return await self.watch_tickers(symbols, params)
  [Previous line repeated 981 more times]
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/coinex.py", line 388, in watch_tickers
    type, params = self.handle_market_type_and_params('watchTickers', None, params)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 1925, in handle_market_type_and_params
    defaultType = self.safe_string_2(self.options, 'defaultType', 'type', 'spot')
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 706, in safe_string_2
    return Exchange.safe_either(Exchange.safe_string, dictionary, key1, key2, default_value)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 818, in safe_either
    value = method(dictionary, key1)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 645, in safe_string
    return str(dictionary[key]) if Exchange.key_exists(dictionary, key) else default_value
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 623, in key_exists
    if hasattr(dictionary, 'getitem') and not isinstance(dictionary, str):
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/usr/lib/python3.8/asyncio/runners.py", line 62, in _cancel_all_tasks
    loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "main.py", line 328, in exchange_loop
    await asyncio.gather(watch_balance(exchange), *tickers_loops, *loops)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "main.py", line 375, in watch_ticker
    exit()
  File "/usr/lib/python3.8/_sitebuiltins.py", line 26, in call
    raise SystemExit(code)
SystemExit: None
```

### Code

```
     exchange = getattr(ccxt.pro, 'coinex')()
     symbol = 'NEXA/USDT'
   
   while True:
        try:
            await exchange.watch_ticker(symbol)

        except NetworkError as e:
            logging.error(f'Network error: {exchange} watch ticker {symbol}: {str(e)}: %s', traceback.format_exc())

        except Exception as e:
            logging.error(f'{exchange} watch ticker {symbol}: {str(e)}: %s', traceback.format_exc())

            exit()

```

**Comment by grozz97** [comment]
I don't understand what this is connected with, but the error began to occur noticeably more often.
