### ISSUE TITLE
CEX get address TypeError

### ISSUE THREAD

**Issue by adonayn** [ccxt/ccxt#1802]
Hi, again,

When I try to get the address of say, BTC from CEX, I get the error that the index must be an integer.

I just upgraded the version, and for other private requests works fine. 
Could you please take a look:

cex.privatePostGetAddress('BTC')

Traceback (most recent call last):

  File "<ipython-input-30-8cb3c95cebf8>", line 1, in <module>
    cex.privatePostGetAddress('BTC')

  File "/Users/adonay/anaconda/lib/python2.7/site-packages/ccxt/cex.py", line 440, in request
    response = self.fetch2(path, api, method, params, headers, body)

  File "/Users/adonay/anaconda/lib/python2.7/site-packages/ccxt/base/exchange.py", line 296, in fetch2
    request = self.sign(path, api, method, params, headers, body)

  File "/Users/adonay/anaconda/lib/python2.7/site-packages/ccxt/cex.py", line 419, in sign
    url = self.urls['api'] + '/' + self.implode_params(path, params)

  File "/Users/adonay/anaconda/lib/python2.7/site-packages/ccxt/base/exchange.py", line 561, in implode_params
    string = string.replace('{' + key + '}', str(params[key]))

TypeError: string indices must be integers, not str

Thanks

**Comment by kroitor** [comment]
You cannot call an implicit method like that.

`privatePostGetAddress()` is an implicit method of CEX, those are described here:
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

That method isn't a part of the unified API - https://github.com/ccxt/ccxt/wiki/Manual#overview

- All non-unified implicit methods accept a single argument (a dictionary of exchange-specific params).
- All unified methods accept standard exchange-independent params described in the manual

Let us know if this does not answer your question.
