### ISSUE TITLE
The problem with calling .close()

### ISSUE THREAD

**Issue by lisiotc** [ccxt/ccxt#18097]
### Operating System

CentOS Linux

### Programming Languages

python

### CCXT Version

3.1.16

### Description

/connector.py", line 439, in _close
    transport.abort()
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 247, in abort
    self._ssl_protocol._abort()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_abort'
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
kucoin requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2d6697df50>
okx requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).

I obviously have already dealt with it, why do I always have this problem?

### Code

printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} Starting program with parameters: {[n for n in sys.argv]}")
prec_time = '0000000'
min_ask_price = 0
async def symbol_loop(exchange, symbol):
    global crypto_per_transaction,i,z,prec_time,t,time1,bid_prices,ask_prices,total_absolute_profit_pct,min_ask_price,max_bid_price,prec_ask_price,prec_bid_price,timeout,profit_pct,profit_usd,total_crypto
    while time.time() <= timeout:
        try:
            orderbook = await exchange.watch_order_book(symbol)
            now = exchange.milliseconds()
            bid_prices[exchange.id] = orderbook["bids"][0][0]
            ask_prices[exchange.id] = orderbook["asks"][0][0]
            min_ask_ex = min(ask_prices, key=ask_prices.get)
            max_bid_ex = max(bid_prices, key=bid_prices.get)
            for u in echanges_str:
                if crypto[u] < crypto_per_transaction:
                    min_ask_ex = u
                if usd[u] <= 0: # should not happen
                    max_bid_ex = u
            min_ask_price = ask_prices[min_ask_ex] - amount_min_precision[min_ask_ex]
            max_bid_price = bid_prices[max_bid_ex] + amount_min_precision[max_bid_ex]
            profit_usd = (min_ask_price*((total_crypto/len(echanges_str)))*((max_bid_price-min_ask_price)/min_ask_price))
            profit_pct = profit_usd/(0.01*total_usd)
            profit_with_fees_usd = profit_usd - (((crypto_per_transaction) * max_bid_price)*(fees[max_bid_ex]['receive']) + ((crypto_per_transaction * min_ask_price)*(fees[min_ask_ex]['give'])))
            profit_with_fees_pct = ((profit_with_fees_usd/total_usd)*100)/2

            if max_bid_ex != min_ask_ex and profit_with_fees_usd > float(criteria_usd) and profit_with_fees_pct > float(criteria_pct) and prec_ask_price != min_ask_price and prec_bid_price != max_bid_price and usd[min_ask_ex] >= crypto_per_transaction * min_ask_price * (1+fees[min_ask_ex]['give']) and crypto[max_bid_ex] >= crypto_per_transaction * (1+fees[max_bid_ex]['give']):
                i+=1
                
                crypto[min_ask_ex] += crypto_per_transaction * (1-fees[min_ask_ex]['receive'])
                usd[min_ask_ex] -= crypto_per_transaction * min_ask_price * (1+fees[min_ask_ex]['give'])
                crypto[max_bid_ex] -= crypto_per_transaction * (1+fees[max_bid_ex]['give'])
                usd[max_bid_ex] += crypto_per_transaction * max_bid_price * (1+fees[max_bid_ex]['receive'])

                total_fees_crypto = crypto_per_transaction * (fees[max_bid_ex]['give']) + (crypto_per_transaction * (fees[min_ask_ex]['receive']))
                total_fees_usd = ((crypto_per_transaction) * max_bid_price)*(fees[max_bid_ex]['receive']) + ((crypto_per_transaction * min_ask_price)*(fees[min_ask_ex]['give']))

                total_absolute_profit_pct += profit_with_fees_pct

                sys.stdout.write("\033[F")
                sys.stdout.write("\033[K")
                print("-----------------------------------------------------\n")
                
                ex_balances = ""
                for exc in echanges_str:
                    ex_balances+=f"\n➝ {exc}: {round(crypto[exc],3)} {currentPair[:len(currentPair)-5]} / {round(usd[exc],2)} USDT"
                print(f"{Style.RESET_ALL}Opportunity n°{i} detected! ({min_ask_ex} {min_ask_price}   ->   {max_bid_price} {max_bid_ex})\n \nProfit: {Fore.GREEN}+{round(profit_with_fees_pct,4)} % (+{round(profit_with_fees_usd,4)} USD){Style.RESET_ALL}\n \nSession total profit: {Fore.GREEN}+{round(total_absolute_profit_pct,4)} %     (+{round((total_absolute_profit_pct/100)*howmuchusd,4)} USD){Style.RESET_ALL}\n \nFees: {Fore.RED}-{round(total_fees_usd,4)} USD      -{round(total_fees_crypto,4)} {currentPair[:len(currentPair)-5]}\n \n{Style.RESET_ALL}Current worth: {round((howmuchusd*(1+(total_absolute_profit_pct/100))),3)} USD{Style.RESET_ALL}{Style.DIM}\n {ex_balances}\n \nTime elapsed since the beginning of the session: {time.strftime('%H:%M:%S', time.gmtime(time.time()-st))}\n \n{Style.RESET_ALL}-----------------------------------------------------\n \n")
                send_to_telegram(f"[{indicatif} Trade n°{i}]\n \nOpportunity detected!\n \nProfit: {round(profit_with_fees_pct,4)} % ({round(profit_with_fees_usd,4)} USD)\n \n{min_ask_ex} {min_ask_price}   ->   {max_bid_price} {max_bid_ex}\nTime elapsed: {time.strftime('%H:%M:%S', time.gmtime(time.time()-st))}\nSession total profit: {round(total_absolute_profit_pct,4)} % ({round((total_absolute_profit_pct/100)*howmuchusd,4)} USDT)\nTotal fees paid on this session: {round(total_fees_usd,4)} USD      {round(total_fees_crypto,4)} {currentPair[:len(currentPair)-5]}\n \n--------BALANCES---------\n \nCurrent worth: {round((howmuchusd*(1+(total_absolute_profit_pct/100))),3)} USD\n {ex_balances}\n \n")

                ex[max_bid_ex].createLimitSellOrder(currentPair,crypto_per_transaction,max_bid_price)
                printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} Sell limit order sent to {max_bid_ex} for {crypto_per_transaction} {currentPair[:len(currentPair)-5]} at {max_bid_price}, waiting 3 minutes for fill.")

                ex[min_ask_ex].createLimitBuyOrder(currentPair,crypto_per_transaction,min_ask_price)
                printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} Buy limit order sent to {min_ask_ex} for {crypto_per_transaction} {currentPair[:len(currentPair)-5]} at {min_ask_price}, waiting 3 minutes for fill.")

                cancel_order_timeout = time.time() + 180
                already_filled = []
                while time.time()<cancel_order_timeout:
                    time.sleep(2)
                    buy_order = ex[min_ask_ex].fetchOpenOrders(symbol=currentPair)
                    sell_order = ex[max_bid_ex].fetchOpenOrders(symbol=currentPair)
                    if buy_order == [] and already_filled.count(min_ask_ex) == 0:
                        already_filled.append(min_ask_ex)
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} {min_ask_ex} buy order filled!")
                    if sell_order == []and already_filled.count(max_bid_ex) == 0:
                        already_filled.append(max_bid_ex)
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} {max_bid_ex} sell order filled!")
                    
                if buy_order != [] and sell_order == []:
                    try:
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} {min_ask_ex} buy order is not filled in 3 minutes.")
                        ex[min_ask_ex].cancelOrder(symbol=currentPair,id=buy_order[0]['id'])
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} {min_ask_ex} buy order successfully cancelled.")
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} Creating reverse market order...")
                        last_opposite_orders = ex[max_bid_ex].fetchClosedOrders(currentPair)
                        amount_usdt = last_opposite_orders[len(last_opposite_orders)-1]["cost"]
                        ex[max_bid_ex].createMarketBuyOrder(currentPair,amount_usdt)
                    except Exception as e:
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} Error while cancelling {min_ask_ex} sell order and creating the reverse {max_bid_ex} market order. Error: {e}")
                        sys.exit(1)
                if sell_order != [] and buy_order == []:
                    try:
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} {max_bid_ex} sell order is not filled in 3 minutes.")
                        ex[max_bid_ex].cancelOrder(symbol=currentPair,id=sell_order[0]['id'])
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} {max_bid_ex} sell order successfully cancelled.")
                        last_opposite_orders = ex[min_ask_ex].fetchClosedOrders(currentPair)
                        amount_crypto = last_opposite_orders[len(last_opposite_orders)-1]["filled"]
                        ex[min_ask_ex].createMarketSellOrder(currentPair,amount_crypto)
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} Reverse market order filled on {min_ask_ex}. Small losses to be taken into account.")
                    except Exception as e:
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} Error while cancelling {max_bid_ex} sell order and creating the reverse {min_ask_ex} market order. Error: {e}")
                        sys.exit(1)

                if sell_order != [] and buy_order != []:
                    try:
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} 2 orders not filled in 120 seconds. Cancel on his way.")
                        ex[min_ask_ex].cancelOrder(symbol=currentPair,id=buy_order[0]['id'])
                        ex[max_bid_ex].cancelOrder(symbol=currentPair,id=sell_order[0]['id'])
                    except Exception as e:
                        printandtelegram(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} A problem occured while trying to cancel the 2 orders. Exit. Error: {e}")
                        sys.exit(1)
                
                prec_ask_price = min_ask_price
                prec_bid_price = max_bid_price

                total_crypto = 0
                for exc in echanges_str:
                    total_crypto+=crypto[exc]
                crypto_per_transaction = total_crypto/len(echanges_str)
            
            else:
                for count in range(0,1):
                    sys.stdout.write("\033[F")
                    sys.stdout.write("\033[K")
                if profit_with_fees_usd < 0:
                    color = Fore.RED
                elif profit_with_fees_usd > 0:
                    color = Fore.GREEN
                elif profit_with_fees_usd == 0:
                    color = Fore.WHITE
                print(f"{Style.DIM}[{time.strftime('%H:%M:%S', time.gmtime(time.time()))}]{Style.RESET_ALL} Best opportunity: {color}{round(profit_with_fees_usd,4)} USD {Style.RESET_ALL}(with fees)       buy: {min_ask_ex} at {min_ask_price}     sell: {max_bid_ex} at {max_bid_price}")
            time1=exchange.iso8601(exchange.milliseconds())
            if time1[17:19] == "00" and time1[14:16] != prec_time:
                prec_time = time1[11:13]
                await exchange.close()
            z+=1

        except Exception as e:
            print(str(e))
            break  # you can break just this one loop if it fails

async def exchange_loop(exchange_id, symbols):
    exchange = getattr(ccxt.pro, exchange_id)()
    loops = [symbol_loop(exchange, symbol) for symbol in symbols]
    await gather(*loops)
    await exchange.close()

async def main():
    exchanges = {
        echanges_str[0]: [currentPair],
        echanges_str[1]: [currentPair],
        echanges_str[2]:[currentPair]
    }
    loops = [
        exchange_loop(exchange_id, symbols)
        for exchange_id, symbols in exchanges.items()
    ]
    await gather(*loops)

st = time.time()
print(" \n")
run(main())

with open('balance.txt', 'r+') as balance_file:
    balance = float(balance_file.read())
    balance_file.seek(0)
    balance_file.write(str(round(balance * (1 + (total_absolute_profit_pct/100)), 3)))
    balance = float(round(balance * (1 + (total_absolute_profit_pct/100)), 3))

**Comment by carlosmiei** [comment]
Hello @lisiotc, I see a lot of code and I'm not sure what the problem is precisely, can you please summarize it?

**Comment by lisiotc** [comment]
Thank you for your reply, I am very confused, because I have obviously added 'await exchange.close()' to the code, but it always stops running automatically and prompts me that 'after the exchange instance is completed, it should be explicitly called .close() coroutine to release all resources'
The error message is as follows:

SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/barbotine-arbitrage-bot/myenv/lib/python3.11/site-packages/aiohttp/client_ws.py", line 146, in pong
    await self._writer.pong(message)
  File "/root/barbotine-arbitrage-bot/myenv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 670, in pong
    await self._send_frame(message, WSMsgType.PONG)
  File "/root/barbotine-arbitrage-bot/myenv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/root/barbotine-arbitrage-bot/myenv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).

**Comment by carlosmiei** [comment]
> Thank you for your reply, I am very confused, because I have obviously added 'await exchange.close()' to the code, but it always stops running automatically and prompts me that 'after the exchange instance is completed, it should be explicitly called .close() coroutine to release all resources' The error message is as follows:
> 
> SystemExit: 1
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/barbotine-arbitrage-bot/myenv/lib/python3.11/site-packages/aiohttp/client_ws.py", line 146, in pong await self._writer.pong(message) File "/root/barbotine-arbitrage-bot/myenv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 670, in pong await self._send_frame(message, WSMsgType.PONG) File "/root/barbotine-arbitrage-bot/myenv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame self._write(header + mask + message) File "/root/barbotine-arbitrage-bot/myenv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 663, in _write raise ConnectionResetError("Cannot write to closing transport") ConnectionResetError: Cannot write to closing transport binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).

@lisiotc Are you sure you're calling `close` even when an exception is thrown? Can you add a `finally` clause doing that just to make sure you always close the connection?

**Comment by ttodua** [comment]
closing this topic, as it was answered and there was no follow-up thereafter.
let us know if anyone has any issues with CCXT.
