### ISSUE TITLE
Exception in ccxt while placing orders in Binance Future 

### ISSUE THREAD

**Issue by himanshu24x77** [ccxt/ccxt#18128]
### Operating System

ubuntu

### Programming Languages

python

### CCXT Version

3.1.2

### Description

Hi @kroitor @carlosmiei 

Found an exception while placing orders in Binance Future, logs as below:

fetch Request: binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1685989832017&recvWindow=10000&signature=c6f4e8c26bceafb42c91f53b1ce371914ca7ab5d4d31060c2191bf952132e2ff RequestHeaders: {'X-MBX-APIKEY': 'mj2d7BvJqEGgljNeCotp7KGTB55hecFNc6rBQxsucrZer1GEatwDEzIZYc7YP04u', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None
Unable to get the proper data  binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1685989832017&recvWindow=10000&signature=c6f4e8c26bceadfdfsfdsfa7ab5d4d31060c2191bf952132e2ff 10001
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 139, in fetch
    http_response = await response.text(errors='replace')
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1080, in text
    await self.read()
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1036, in read
^CKeyboardInterrupt ...
    self._body = await self.content.read()

### Code

```
  

```

**Comment by kroitor** [comment]
@himanshu24x77 please, post your code to reproduce it, we will check it out.

**Comment by carlosmiei** [comment]
Hello @himanshu24x77, Are you sure you got that exception from placing an order? Looking at the call stack is not clear, so yes, a minimal reproducible example would be very useful here.

**Comment by himanshu24x77** [comment]
Hi @kroitor @carlosmiei not exactly just before placing order but around the same time when i placed a NEW order i got above execption.

Pls check above error snippet, which suggest parsing error :

Unable to get the proper data binance GET [https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1685989832017&recvWindow=10000&signature=c6f4e8c26bceadfdfsfdsfa7ab5d4d31060c2191bf952132e2](https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1685989832017&recvWindow=10000&signature=c6f4e8c26bceadfdfsfdsfa7ab5d4d31060c2191bf952132e2ff)

**Comment by himanshu24x77** [comment]
Hi @kroitor @carlosmiei 

Also, got another error today, pls check logs:

fetch Request: binance POST https://fapi.binance.com/fapi/v1/order RequestHeaders: {'X-MBX-APIKEY': 'mj2d7BvJqEGgljNeCotp7KGTB55hecFNc6rddsfdfddsdssss04u', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: timestamp=1685992612162&symbol=XRPUSDT&side=BUY&newClientOrderId=10098&newOrderRespType=RESULT&type=LIMIT&quantity=12&price=0.4981&timeInForce=GTC&recvWindow=10000&signature=7da36sdasdasdasdsad4ba5eaae8sdsadsdfbad0f357

fetch Request: binance PUT https://fapi.binance.com/fapi/v1/listenKey RequestHeaders: {'X-MBX-APIKEY': 'mj2d7BvJqEGgljNeCotp7KGTB55hecFNc6rddsfdfddsdssss04u', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: listenKey=tWRVUYtKUfoltOjPjkt6wtgBYT12k2vRzrETdsadasdasdasOQMCb
Unable to get the proper data  binance POST https://fapi.binance.com/fapi/v1/order 10098
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 134, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)

fetch Response: binance PUT https://fapi.binance.com/fapi/v1/listenKey 200 ResponseHeaders: {'Date': 'Mon, 05 Jun 2023 19:17:06 GMT', 'Content-Type': 'application/json', 'Content-Length': '2', 'Connection': 'keep-alive', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '1', 'x-response-time': '1ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Expires': '0', 'Pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block'} ResponseBody: {}
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 913, in start
    self._continue = None
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jaimatadi/Desktop/toolkit_F_src/gw/binance_future/BinanceFutureGateway.py", line 276, in run
    new = await self.exchange.create_order(instrument_name, type, side, amount, price, {'clientOrderId': client_order_id})
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/ccxt/async_support/binance.py", line 4215, in create_order
    response = await getattr(self, method)(self.extend(request, requestParams))
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/ccxt/async_support/binance.py", line 7409, in request
    response = await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 1663, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/jaimatadi/.local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 168, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance POST https://fapi.binance.com/fapi/v1/order

**Comment by himanshu24x77** [comment]
@kroitor @carlosmiei 

Code written to place orders was working without any issues from last 1 week & i was able to place +2000 orders of both buy/sell , new/edit/cancel etc in binance futures, execption started coming since last 2 days. Also issue is not simulated everytime it happens only few item so not sure how to share minimal reproducible code.

Code written to place new order:

                          which_order, instrument_name, side, type, price, amount, client_order_id, order = queResponse
                          new = await self.exchange.create_order(instrument_name, type, side, amount, price, {'clientOrderId': client_order_id})

Code written to place edit order:

                           which_order, instrument_name, side, type, price, amount, client_order_id, order = queResponse
                           edit = await self.exchange.edit_order(order.exchangeorderId_, instrument_name, type, side, amount, price, {'clientOrderId': client_order_id})

**Comment by kroitor** [comment]
@himanshu24x77 it looks like you're getting a RequestTimeout error. That is a type of intermittent error that is documented in the Manual and you can handle it in the userland by adding a try-except-retry logic. Have you tried implementing an error handling strategy as described in the docs? 
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#requesttimeout

**Comment by ttodua** [comment]
closing this old issue, as seems it was covered.
let us know if anyone has any issues
