### ISSUE TITLE
when calling binance.fetchPositions() --> fetchPositionsRisk() requires an array argument for symbols

### ISSUE THREAD

**Issue by dorienh** [ccxt/ccxt#18131]
### Operating System

mac

### Programming Languages

JS

### CCXT Version

3.1.24

### Description

I had working javascript version of the following line: 

`const positions = await exchange.fetchPositions(symbols = [symbol], params = {});`

Then I converted my project to typescript. The compiler complained that I had to feed an array to the function, so I changed it to: 

`const symbol : string = 'ETH/USDT';`
`const positions = await exchange.fetchPositions({ symbols: [symbol], params: {} });`

Now, upon running, this function calls fetchPositionsRisk() which needs an array as input, somehow this is not relayed. 
```
ArgumentsRequired: binance fetchPositionsRisk() requires an array argument for symbols
    at binance.fetchPositionsRisk (/Users/x/Dropbox/webhooks/webhook-trader/server/node_modules/ccxt/dist/cjs/src/binance.js:7356:23)
    at binance.fetchPositions (/Users/x/Dropbox/webhooks/webhook-trader/server/node_modules/ccxt/dist/cjs/src/binance.js:7297:31)
    at Object.<anonymous> (/Users/x/Dropbox/webhooks/webhook-trader/server/dist/trades.js:94:50)
    at Generator.next (<anonymous>)
    at /Users/x/Dropbox/webhooks/webhook-trader/server/dist/trades.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/x/Dropbox/webhooks/webhook-trader/server/dist/trades.js:4:12)
    at Object.closeAllPositions (/Users/x/Dropbox/webhooks/webhook-trader/server/dist/trades.js:89:12)
    at /Users/x/Dropbox/webhooks/webhook-trader/server/dist/index.js:90:41
    at Generator.next (<anonymous>)
```

I came across [this issue](https://github.com/ccxt/ccxt/issues/14503#issuecomment-1204078135), but it seems to have been patched. I upgrade npm i ccxt@latest, so hopefully this is included? 

Admittedly, I am new at typescript so let me also put my `tsconfig` in case I messed up there somehow: 

```
{
  "compilerOptions": {
    "target" : "es6",
    "module": "CommonJS",
    "outDir":"./dist",
    "noEmit": false,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "sourceMap": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": true,
    "noLib": false,
    "preserveConstEnums": true,
    "allowJs": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules"]
}
```

I also just did `npm i ccxt`, not sure if there is a `@types/` version or another package I should use with `ts`.

**Comment by dorienh** [comment]
Found a solution by making my tsconfig a bit stricture, I noticed this works: 

```
let symbols = [symbol];
const positions = await exchange.fetchPositions(symbols = [symbol]);
```

For tsconfig I used: 

```
{
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "./dist",
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "declaration": true,
    "forceConsistentCasingInFileNames": true,
    "lib": [
      "es2016"
    ],
    "module": "commonjs",
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "pretty": true,
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "esModuleInterop": true
  },
  "include": [
    "src/**/*.ts",
    "test/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by carlosmiei** [comment]
Hello @dorienh, you seem to have found a solution so I would close this issue, let us know if anything.
