### ISSUE TITLE
php async: gzip response decoding

### ISSUE THREAD

**Issue by pkindruk** [ccxt/ccxt#18152]
### Operating System

Docker dev container (host Windows 10)

### Programming Languages

php

### CCXT Version

based on 3.1.27 code

### Description

Hi, I'm working on new exchange integration. While running php-async tests I noticed that they fail where sync php works. Further investigation showed that response body looks like a complete mess (probably gzip bytes turned to string in some way). If I remove request header `Accept-Encoding: gzip, deflate`, exchange returns HTTP error code 415.

Sorry if a duplicate, but searching for `php+gzip` in issues didn't help.

### Code

Code:
```php
    public function fetch_currencies($params = array ()) {
        return Async\async(function () use ($params) {
            /**
             * fetches all available $currencies on an exchange
             * @param {array} $params extra parameters specific to the exchange api endpoint
             * @return {array} an associative dictionary of ~@link https://docs.ccxt.com/#/?id=currency-structure currency structures~
             */
            $currencies = Async\await($this->publicGetCurrency ($params));
            // actually fails inside parse_currencies(). This line here is just to shorten code sample 
            echo count($currencies);
            return $this->parse_currencies($currencies);
        }) ();
    }
```

Code is launched like this:
```
root@a28b0d6e2eed:/ccxt# php -f ./examples/php/cli.php fxopen fetchCurrencies --test --verbose
PHP v8.1.18
CCXT version :3.1.27
fxopen->fetchCurrencies()
Array
(
    [0] => fetch Request:
    [1] => fxopen
    [2] => GET
    [3] => https://marginalttdemowebapi.fxopen.net:8443/api/v2/public/currency
    [4] => RequestHeaders:
    [5] => Array
        (
            [Content-Type] => application/json
            [Accept] => application/json
            [Accept-Encoding] => gzip, deflate
        )

    [6] => RequestBody:
    [7] =>
)
Array
(
    [0] => fetch Response:
    [1] => fxopen
    [2] => GET
    [3] => https://marginalttdemowebapi.fxopen.net:8443/api/v2/public/currency
    [4] => 200
    [5] => ResponseHeaders:
    [6] => Array
        (
            [Content-Length] => 7981
            [Content-Type] => application/json; charset=utf-8
            [Content-Encoding] => gzip
            [Server] => Microsoft-HTTPAPI/2.0
            [Date] => Wed, 07 Jun 2023 11:29:37 GMT
        )

    [7] => ResponseBody: /* Omitted since it breaks console output */
)
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /ccxt/php/async/fxopen.php:588
Stack trace:
#0 /ccxt/php/async/fxopen.php(588): count()
#1 /ccxt/vendor/react/async/src/functions.php(190): ccxt\async\fxopen->ccxt\async\{closure}()
#2 [internal function]: React\Async\{closure}()
#3 /ccxt/vendor/react/async/src/SimpleFiber.php(24): Fiber->resume()
#4 /ccxt/vendor/react/async/src/functions.php(296): React\Async\SimpleFiber->resume()
#5 /ccxt/vendor/react/promise/src/FulfilledPromise.php(28): React\Async\{closure}()
#6 /ccxt/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then()
#7 /ccxt/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#8 /ccxt/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#9 /ccxt/vendor/react/async/src/functions.php(190): React\Promise\Promise::React\Promise\{closure}()
#10 [internal function]: React\Async\{closure}()

// Omitted for brevity
```
Response Body look like this in console:
```
��)H��♣���K1��`�k���;H�\|J�☺◄���'�h�T�\]�����<↓c����P���8↕�e/☻��y^o���7H؋�6G�V�\�H�U�Q��↔<▼∟�s�@���↓�{t�(�˜���
↔<}����@‼U�& ���ds�yq[�³‼!+W���a♀lt�>�/��X�}x����?oͦ♫��n�:◄�*��♣A"9♀%=GJ!ZM���wj��˹�)��▼+�♫`�����fA�↓�Y���y�OB��~}�'�♦��
S↔l��|�a>1��i�F�a�I��>��k��d0������v��ȼ�o5,m♠▬pp�V�C:/�☻���m�[f�Mt/☺�9�Bo6���↓�►ζ�0�#���♀▲��)���Sg1|]��/1o�4캒[���t� ��k̲��KoZ�.�ofwhF"��6�(Ռ�{t<7�]׎;↕↑��<cth�;6֜♫J�▼E♦/f���¶.☺�"☼m����������#%�L�L3���g�!�♠��L4۬��.���♀x☼��`�xY
Y�♫►D�o�}"0F;������(;��l32�k♥�(
ό�!�a�vյ ��Q"^↨�'}���bgZ↑�8o6��♥�����iX◄��12�A�Nam¶�(�♠��r:�e�f�#�"Bt5]¶�.&�#�����d����|�1KB§/.♦~�3↕���8�m8b�▼7A�&�xXq�ec�.���↓�C��↓���6��,Չg�xW,��↓�H��↨,�m��GTq☻��l_m81Y>�o�L∟���&c���~}�⌂↓�S'§S�:{�Lh���'▬l�►�Ҍm}fK�w�v�‼�r�¶
'�Y�G�����▼��0�=�↕�[VT<#��K��=�↨�ܣ�c��S�§7x♂��☼=�f@����!'M�N��4�Q�♥���Y�t��Щg&�▬<�ē�6։��▲:z���?�T�T:D[��iXNY�t♦_=+▲▲X�'Ɨ�‼��Ko��}�m�7�cװx+��/�▼♫+�@m;Jᝦ�U �"��mB��Eۿ��x�-►A∟>I7�⌂�WO��♦☻Ic����ڊ�3מ�)↨�F�↑>�I��'�����Ri����ld��������~�4�☼�H�x6↔�|+2Y��B�N���AsV���4��J"�▲�g���(��X��♫�^����|R�ȯ��cG*�♫[♣�C��¶Q���♂���↨f�D됺g�nz?▬�bF�P��v��↓�kk{R�~ɸ�☼��-Du��▲�������/��↔�♦�☺ڜ�#xҚ�Tq4�Uۙ↑↕dߎ���6���pV▼�R����׈��<z`�m��5�-�-a_oC��֟o"�,k�]↨g߆h�q|�◄S↓⌂+5� ���𑡸iS� 
�C��♀�^'��♫��!��        :▼q��V���
xXp.J�o-�hoΔ�▼►�U��(ٗ§�↕�0�w�̯���♣��K���e��↓�;�Ol�,Ι���t���!�h�6��������s�?���R§l��Y��Y�᧠?�|����{3>�c��q���→▲↕�&►�&�FϚx�_�_�7��z�X%�4|�����Mp�U���♦��1�↑→�od]��t�Q�����Z��Ղ�ԣ.l���`��T◄h%-��0☼���i'♂��↨<�]�k▼!u�3JJ▬.:rn��$�b�Ӳ�↑
��zw��▬���b_¶������ D�IWh��x�ͱi��↔�&ܙHK���;xB�{yi▬♫/�٥w�N��↨�I��[�$��6q♦����;�پ|�A‼�►�]��}Ή��w�☺����▼{���ߢ���ؚ�☻��[^]H♥|q�Q�/�u♀���ZF!���↓▼�↓Z#}��↕↨�v_Rt��6*�d▲�9P�mx�̮��♥�eE����]→���}♫N�☼���¶}�"�
��5��▬i�▲�p���
8�:▼�܇�▲1}�r�8I�զ���↔�M��d!�▲/͍�/P��O→��OoS������sB������1ֺ0��h��z▼Gu��        �̍�8��ҿ↓6fԛh߯���k(TY�B^�:�5L|�◄�(�2)V��e�Y��`�▬�IO��♥�▼)��̊     |v�D▬Z�‼a�6▼�►,|�Yj��D��7�V�vL�▲�x�     &�j���o�k�������lk�i��r�&m♀�8k�
▼☺ri�y%��W����t¶�g>�G������↓u▼���""���Df�����\���3��☻͊��ɹ;�|�wtVڕb��Я���$���♂���d�����n☼z��⌂�∟����a�v�8↔c��c�jȟ���5�iS_�}��%1d��í�ѐ���~ �X�v<%@�∟����q��4�϶�6ES▼132�8↨�?�2r�߮sʇ�����Y��↕���ۯ�↕▼��2����������I��<}�7eK��⌂%Fz$ 
```

**Comment by ttodua** [comment]
sorry for late follow-up, I think this issue slipped me in the past. 
if anyone is still interested about this topic, please let us know, so I can get engaged in again.
