### ISSUE TITLE
php: safeNumber() issue after transpilation

### ISSUE THREAD

**Issue by pkindruk** [ccxt/ccxt#18155]
### Operating System

Docker dev container (host Windows 10)

### Programming Languages

php

### CCXT Version

based on 3.1.27 code

### Description

Hi, I'm working on new exchange integration. PHP tests are failing with: 
```
FAILED fxopen (PHP): (explain @ run-tests.js:308)

        string(10) "\nTESTING "
        string(3) "php"
        array(2) {
          ["exchange"]=>
          string(6) "fxopen"
          ["symbol"]=>
          string(3) "all"
        }
        string(2) "\n"
        Exchange loaded 622 symbols 
        Selected SWAP SYMBOL: BTC/USD:USD
        [INFO:SWAP TESTS]
        PHP Fatal error:  Uncaught TypeError: ccxt\Exchange::safe_number(): Argument #1 ($obj) must be of type array, null given, called in /ccxt/php/fxopen.php on line 698 and defined in /ccxt/php/Exchange.php:4250
        Stack trace:
        #0 /ccxt/php/fxopen.php(698): ccxt\Exchange->safe_number()
        #1 /ccxt/php/fxopen.php(673): ccxt\fxopen->parse_ticker()
        #2 /ccxt/php/test/sync/test_fetch_ticker.php(15): ccxt\fxopen->fetch_ticker()
        #3 /ccxt/php/test/test_sync.php(84): ccxt\test_fetch_ticker()
        #4 /ccxt/php/test/test_sync.php(294): ccxt\call_method()
        #5 /ccxt/php/test/test_sync.php(310): ccxt\testMainClass->test_method()
        #6 /ccxt/php/test/test_sync.php(350): ccxt\testMainClass->test_safe()
        #7 /ccxt/php/test/test_sync.php(593): ccxt\testMainClass->run_public_tests()
        #8 /ccxt/php/test/test_sync.php(716): ccxt\testMainClass->test_exchange()
        #9 /ccxt/php/test/test_sync.php(175): ccxt\testMainClass->start_test()
        #10 /ccxt/php/test/test_sync.php(722): ccxt\testMainClass->init()
        #11 {main}
          thrown in /ccxt/php/Exchange.php on line 4250 (explain @ run-tests.js:311)

INFO : (explain @ run-tests.js:314)

        [INFO:TESTING]            fxopen test_load_markets ()
        [INFO:TESTING]            fxopen test_fetch_currencies ()
        [INFO:TESTING]            fxopen test_fetch_ticker (BTC/USD:USD) (explain @ run-tests.js:315)
```

### Code

TS code
```ts
parseTicker (ticker, market = undefined) {
    const marketId = this.safeString (ticker, 'Symbol');
    const symbol = this.safeSymbol (marketId);
    const timestamp = this.milliseconds ();
    const bid = this.omitZero (this.safeString (ticker, 'BestBid'));
    const ask = this.omitZero (this.safeString (ticker, 'BestAsk'));
    // PHP fails on line below
    const baseVolume = this.safeNumber (ticker, 'DailyTradedTotalVolume');
```
Tests start to work when I remove PHP `array` type annotation from `Exchange.php`:
```php
public function safe_number(array $obj, int|string $key, ?float $defaultNumber = null) {
    $value = $this->safe_string($obj, $key);
    return $this->parse_number($value, $defaultNumber);
}
```

The strange part is that I have calls to `this.safeNumber` in `fetchMarkets` which is a requirement for `fetchTicker`.

Is that type annotation required? It is not consistent across `Exchange` class, take `safeNumber2` or `safeString` method family for example.

**Comment by carlosmiei** [comment]
Hello @pkindruk,
>  const baseVolume = this.safeNumber (ticker, 'DailyTradedTotalVolume');

Can you please double-check that `ticker` is not null here?

**Comment by pkindruk** [comment]
@carlosmiei, you are right it is actually null there.
How can I debug this? Since CLI is not available here because of #18152.

**Comment by pkindruk** [comment]
Ok I found where the problem is `fetchTicker` has a symbol param. The response is empty because a symbol is not imploded.
```php
     public function fetch_ticker(string $symbol, $params = array ()) {
        /**
         * fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
         * @param {string} $symbol unified $symbol of the market to fetch the ticker for
         * @param {array} $params extra parameters specific to the exchange api endpoint
         * @return {array} ~@link https://docs.ccxt.com/#/?id=ticker-structure Ticker structure~
         */
        $this->load_markets();
        $request = array();
        $this->add_symbol_filter($request, $symbol);
        $response = $this->publicGetTickerFilter (array_merge($request, $params));
        // $response === array of ticker objects
        var_dump($response);
        // echo $response[0];
        return $this->parse_ticker($this->safe_value($response, 0));
    }

    public function add_symbol_filter($request, string $symbol) {
        $marketId = $this->market_id($symbol);
        $request['filter'] = $marketId;
    }
```
`$request` var is modified inside method `add_symbol_filter`. But changes are not reflected on variable in caller method.
I'm not a PHP expert. Looks like it passes a copy of original variable. How can I change that?
Source TS code
```ts
    addSymbolFilter (request, symbol: string) {
        const marketId = this.marketId (symbol);
        request['filter'] = marketId;
    }

    addSymbolsFilter (request, symbols: string[] = undefined) {
        request['filter'] = '';
        if (symbols !== undefined) {
            const marketIds = this.marketIds (symbols);
            // param is injected in url space char has to be encoded
            request['filter'] = marketIds.join ('%20');
        }
    }
```

**Comment by pkindruk** [comment]
@ttodua
I was trying not to repeat myself with that method. It is counterintuitive to me that arrays are copied in PHP in case of modification inside a function, since it is opposite for Python and JavaScript, as well as C# you guys are adding right now.

Is it safe to return an value from a function instead? Like this:
```ts
createRequestWithSymbolFilter (symbol: string) {
    const request = {};
    const marketId = this.marketId (symbol);
    request['filter'] = marketId;
    return request;
}
```

**Comment by ttodua** [comment]
@pkindruk 
I understand what you try, you want to avoid few extra repeated lines, but it's not optimal in terms of performance, so it's better to avoid extra functions and passing objects back and forth, that's why I've shown the standard example how we do things. your code (if it is ever PR-ed) won't get merged the way you are doing, as it's against thumb rule.

**Comment by ttodua** [comment]
a late reply in this topic, but as it has been stale, I consider it for closing.
however, if OP or anyone is still interested and have any notes/questions that we can address, please let us know.
