### ISSUE TITLE
Getting IP bans with WebSocket.

### ISSUE THREAD

**Issue by ThisisAqib** [ccxt/ccxt#18217]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.1.37

### Description

Hi,

I am getting IP bans while using WebSocket API. The bot worked fine for about a week but recently I have started to get this error. My bot is deployed on Render.com and I have noticed that they have a limited number of IPs. The error would have made sense if I had got it while using the REST API but I don't know why this error is coming while I am already using the WebSockets.

Thanks, 
Aqib

### Code

```
Traceback (most recent call last):
File "/opt/render/project/src/bot/trading_bot.py", line 116, in watch_balance
self.balance = await self.exchange_websockets.watch_balance()
File "/opt/render/project/src/.venv/lib/python3.7/site-packages/ccxt/pro/binance.py", line 1052, in watch_balance
self.balance = await self.exchange_websockets.watch_balance()
File "/opt/render/project/src/.venv/lib/python3.7/site-packages/ccxt/pro/binance.py", line 961, in authenticate
await self.authenticate(params)
File "/opt/render/project/src/.venv/lib/python3.7/site-packages/ccxt/async_support/binance.py", line 7412, in request
response = await getattr(self, method)(params)
File "/opt/render/project/src/.venv/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 1663, in fetch2
response = await self.fetch2(path, api, method, params, headers, body, config)
File "/opt/render/project/src/.venv/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 178, in fetch
return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
File "/opt/render/project/src/.venv/lib/python3.7/site-packages/ccxt/async_support/binance.py", line 7338, in handle_errors
self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
raise DDoSProtection(self.id + ' ' + str(code) + ' ' + reason + ' ' + body)
ccxt.base.errors.DDoSProtection: binanceusdm 418 Client Error (418) {"code":-1003,"msg":"Way too many requests; IP(18.142.128.26) banned until 1686602517492. Please use the websocket for live updates to avoid bans."}

```

**Comment by RoninDisco** [comment]
i have the same issue while gathering many orderbooks via websocket

**Comment by kroitor** [comment]
@ThisisAqib @RoninDisco please, post your code and CCXT versions to reproduce it, follow these guidelines precisely:
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
Hello @ThisisAqib @RoninDisco 👋

Closing this during a cleanup — we never received the requested repro, but the traceback in the report actually shows the likely root cause, so let's put the explanation on record for anyone finding this later:

Binance's authenticated websocket streams require a `listenKey` that is obtained and kept alive via **REST** calls — so even a "pure websocket" bot still issues periodic REST requests (visible in your traceback: `watch_balance → authenticate → request`). And Binance enforces rate limits and bans **per IP**. On shared-egress platforms like Render (also Heroku and similar), your bot shares its outbound IP with other tenants — including other people's Binance bots — so the IP's request budget gets consumed by strangers and the whole IP gets 418-banned regardless of your own usage.

The fix is infrastructural, not a ccxt setting: run on a dedicated IP (a VPS, or your platform's static-egress add-on). If anyone sees IP bans on a *dedicated* IP with a recent ccxt version, that's worth a fresh issue with the verbose output.

Thanks for the reports! 🙏
