### ISSUE TITLE
Kraken Futures: fetch_ohlcv() gives KeyError: 'charts'

### ISSUE THREAD

**Issue by LinoxBE** [ccxt/ccxt#18311]
### Operating System

Windows 11

### Programming Languages

python

### CCXT Version

3.1.48

### Description

Hi,

I'm trying to get the OHLCV from Kraken Futures Demo. But the fetch_ohlcv gives the error:

KeyError: 'charts'

Here is the full Traceback:

Traceback (most recent call last):
  File "c:\FOLDER-dev\2_Bot\app.py", line 37, in <module>
    ohlcv = exchange.fetch_ohlcv('BTC/USD:USD', '1m', limit=100)
  File "C:\FOLDER-venv\lib\site-packages\ccxt\krakenfutures.py", line 581, in fetch_ohlcv       
    response = self.chartsGetPriceTypeSymbolInterval(self.extend(request, params))
  File "C:\FOLDER-venv\lib\site-packages\ccxt\base\types.py", line 26, in unbound_method        
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "C:\FOLDER-venv\lib\site-packages\ccxt\base\exchange.py", line 2836, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "C:\FOLDER-venv\lib\site-packages\ccxt\base\exchange.py", line 2832, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "C:\FOLDER-venv\lib\site-packages\ccxt\krakenfutures.py", line 1964, in sign
    url = self.urls['api'][api] + query
KeyError: 'charts'

I tried to find out in the code why I get this, but not being a Python expert, this isn't helping me.

When you check my code, it gets through the "if has_fetch_ohlcv is True" without issues.

### Code
```
import re
from datetime import datetime
import ccxt  # noqa: E402
from flask import Flask
import json
import asciichart

symbol = 'BTC/USD:USD'

print("CCXT Version:", ccxt.__version__)
exchange = ccxt.krakenfutures({
        'apiKey': "APIKEY HERE",
        'secret': "APISECRET HERE",
        'verbose': False,  # switch it to False if you don't want the HTTP log
    })
exchange.set_sandbox_mode(True)  # enable sandbox mode

print(exchange.name, "supports the following methods:")
print(exchange.has)

balance = exchange.fetch_balance()
#print(json.dumps(balance, indent=5))
print('--- Info - result:')
print(balance['info']['result'])
if balance['info']['result'] == 'success':
    print('--- Info - accounts - flex:')
    print(json.dumps(balance['info']['accounts']['flex'], indent=5))

print(exchange.timeframes)

has_fetch_ohlcv = exchange.has['fetchOHLCV']
print(f'\nExchange has fetchOHLCV? {has_fetch_ohlcv}\n')
if has_fetch_ohlcv is True:
    index = 4  # 4 == close price from each ohlcv candle
    height = 15
    length = 80
    ohlcv = exchange.fetch_ohlcv('BTC/USD:USD', '1m', limit=100)
    prices =[]
    [prices.append(x[index]) for x in ohlcv]
    print("\n" + asciichart.plot(prices[-length:], {'height': height}))  # print the chart


app = Flask(__name__)
```

**Comment by carlosmiei** [comment]
Hello @LinoxBE,
I don't think the issue is with ccxt, I just tested and seems to be working fine:
```
p krakenfutures fetchOHLCV "BTC/USD:USD" 1m None 100
Python v3.10.9
CCXT v3.1.45
krakenfutures.fetchOHLCV(BTC/USD:USD,1m,None,100)
[[1687445940000, 29739.0, 29786.0, 29739.0, 29760.0, 0.4943999999999999],
 [1687446000000, 29760.0, 29803.0, 29741.0, 29792.0, 7.0074],
 [1687446060000, 29792.0, 29847.0, 29791.0, 29818.0, 20.8854],
 [1687446120000, 29818.0, 29818.0, 29795.0, 29795.0, 0.6478],
 [1687446180000, 29795.0, 29847.0, 29795.0, 29814.0, 0.1268],
 [1687446240000, 29814.0, 29850.0, 29814.0, 29825.0, 0.2531],
 [1687446300000, 29825.0, 29961.0, 29825.0, 29934.0, 12.8328],
 [1687446360000, 29934.0, 29968.0, 29924.0, 29947.0, 1.9629],
 [1687446420000, 29947.0, 29947.0, 29885.0, 29897.0, 6.4061],
 [1687446480000, 29897.0, 29910.0, 29853.0, 29902.0, 4.1237],
 [1687446540000, 29902.0, 29902.0, 29873.0, 29882.0, 0.8967],
 [1687446600000, 29882.0, 29882.0, 29874.0, 29879.0, 0.742],
```

**Comment by LinoxBE** [comment]
I don't know what to say. When I minimize the codebase to only CCXT, I still have the error.

`import ccxt  # noqa: E402
exchange = ccxt.krakenfutures({
        'apiKey': "APIKEY HERE",
        'secret': "SECRET HERE",
        'verbose': False,  # switch it to False if you don't want the HTTP log
    })
exchange.set_sandbox_mode(True)  # enable sandbox mode

ohlcv = exchange.fetch_ohlcv('BTC/USD:USD', '1m', limit=100)`

**Comment by carlosmiei** [comment]
@LinoxBE I'm sorry you're right, I did not notice you were using the sandbox API, by using it I can also reproduce this issue. Thanks for letting us know I will fix it as soon as possible.
