### ISSUE TITLE
bitbay market order

### ISSUE THREAD

**Issue by netdodger** [ccxt/ccxt#1836]
Hi,

I'm trying to create market order using `bitbay.create_markert_buy_order(symbol, amount)`, however I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 1100, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/bitbay.py", line 231, in create_order
    }, params))
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 310, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 307, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 375, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 407, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 289, in raise_error
    details,
ccxt.base.errors.ExchangeNotAvailable: bitbay POST https://bitbay.net/API/Trading/tradingApi.php 500 Server Error: Internal Server Error for url: https://bitbay.net/API/Trading/tradingApi.php 
```
Other private API methods like `bitbay.fetch_balance()` work fine. I would appreciate your help, thanks.

Edit: Is it maybe that BitBay API only accepts limit orders and I also have to specify the price?

- OS: Ubuntu 16.04
- Programming Language version: Python 2.7
- CCXT version: 1.10.1056
- Exchange: bitbay
- Method: create_markert_buy_order

**Comment by netdodger** [comment]
Bitbay API does not support market trading.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/1664#issuecomment-361933241
