### ISSUE TITLE
Binance read time out error

### ISSUE THREAD

**Issue by pedrito87** [ccxt/ccxt#1842]
- OS: Windows 10
- Programming Language version: Python 3.6.4
- CCXT version: 1.10.1056
- Exchange: Binance
- Method: fetch_ticker, fetch_balance

Hi,
I recently installed ccxt and tested it out. I ran a simple loop that gets ETH/BTC asking and bidding prices and my ETH and BTC balance from Binance. I use time.sleep(10) between the loops. Sooner or later an error occurs and it breaks the loop. Quoted is the message I get: 

> Traceback (most recent call last):
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Python\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Python\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Python\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Python\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python\ccxt\base\exchange.py", line 359, in fetch
    proxies=self.proxies
  File "C:\Python\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python\lib\site-packages\requests\adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python\Binance_testing.py", line 76, in <module>
    ethAskBin = binance.fetch_ticker('ETH/BTC').get('ask')
  File "C:\Python\ccxt\binance.py", line 487, in fetch_ticker
    }, params))
  File "C:\Python\ccxt\base\exchange.py", line 310, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Python\ccxt\base\exchange.py", line 307, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python\ccxt\base\exchange.py", line 365, in fetch
    raise RequestTimeout(' '.join([self.id, method, url, 'request timeout']))
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v1/ticker/24hr?symbol=ETHBTC request timeout

What might be the issue? Previously, also at Binance I was getting a timestamp error, but I increased the recvWindow and it was fine for a while, but now this error occurs. I doubt that there is such a constant error on Binance side, so it must be a problem of mine, and maybe there is a known way to solve it? What do you think might cause this problem? And how do I solve it?  Any help would be very much appreciated :)

**Comment by pbosch** [comment]
Binance is currently in maintenance mode. I encountered something similar and opened a ticket, although it was not necessary. I think they are another 10 hours or so in maintenance. Something went wrong while syncing their databases.

**Comment by kroitor** [comment]
They have been on maintenance for 24 hours now.

- https://support.binance.com/hc/en-us/articles/360000710431-
- https://github.com/ccxt/ccxt/issues/1824
- https://github.com/ccxt/ccxt/issues/1821
- https://t.me/binance_api_english

Closing this as a duplicate if you don't mind.

**Comment by pedrito87** [comment]
Yes, I can confirm today it works fine.

**Comment by kroitor** [comment]
@pedrito87 their API still replies as offline to me (just checked it now)...

**Comment by kroitor** [comment]
Ok, now back up, indeed, thx!
