### ISSUE TITLE
What is the solution? bitget - ccxt

### ISSUE THREAD

**Issue by bebo12343** [ccxt/ccxt#18454]
```python
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 534, in fetch
    response = self.session.request(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\utils.py", line 1040, in check_header_validity
    _validate_header_part(header, value, 1)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\utils.py", line 1056, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' bg_56609f3c7ddf80cd361fbf075ada9904'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\user\Desktop\بوت منصات\order.py", line 122, in <module>
    exchange1.create_order(symbol="MATICUSDT_UMCBL", type="market", side="buy_single", amount=20)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\bitget.py", line 2642, in create_order
    response = getattr(self, method)(self.extend(request, omitted))
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\types.py", line 25, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 2822, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 2819, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 600, in fetch
    raise ExchangeError(details) from e
ccxt.base.errors.ExchangeError: bitget POST https://api.bitget.com/api/mix/v1/order/placeOrder
```

**Comment by samgermain** [comment]
based on the error that states `requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' bg_56609f3c7ddf80cd361fbf075ada9904'` it looks like you need to change the value of `' bg_56609f3c7ddf80cd361fbf075ada9904'` to `'bg_56609f3c7ddf80cd361fbf075ada9904'`

That's about as much as I can say because you didn't provide any code, but it looks like that should probably be the answer

**Comment by carlosmiei** [comment]
Hello again @bebo12343,
Are you adding things to the `headers` object upon instantiating the exchange?

**Comment by kroitor** [comment]
@bebo12343 why is the value of your `side` argument "buy_single"? That does not look right to me.

**Comment by carlosmiei** [comment]
> @bebo12343 why is the value of your `side` argument "buy_single"? That does not look right to me. Where would you get that value from? In general CCXT supports the following: https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitget.py#L2557

@kroitor It's an exchange-specific value 
![image](https://github.com/ccxt/ccxt/assets/43336371/ada66a50-0f84-4d2d-b6aa-7e7e1ebceb5c)

**Comment by kroitor** [comment]
> > @bebo12343 why is the value of your `side` argument "buy_single"? That does not look right to me. Where would you get that value from? In general CCXT supports the following: https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitget.py#L2557
> 
> @kroitor It's an exchange-specific value ![image](https://user-images.githubusercontent.com/43336371/250887235-ada66a50-0f84-4d2d-b6aa-7e7e1ebceb5c.png)

Ok, got it.

@bebo12343 please, paste your version of CCXT, your complete code to reproduce it (without your keys) and your verbose output, follow the instructions that we gave you precisely to get help quickly:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bitget({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_API_PASSWORD',
})

markets = exchange.load_markets()
exchange.verbose = True  # after loading the markets

symbol = 'MATIC/USDT:USDT'
order_type = 'market'
side = 'buy_single'
amount = 20

order = exchange.create_order(symbol, order_type, side, amount)
```

**Comment by bebo12343** [comment]
@carlosmiei 

Brother can you send my the normal formula to place order on future bitget please ?

**Comment by kroitor** [comment]
> @carlosmiei @kroitor
> 
> Brother can you send my the normal formula to place order on future bitget please ? With headers

The above code should work, please, post your code and verbose output and follow the instructions posted above precisely.

**Comment by bebo12343** [comment]
@carlosmiei 
@kroitor 

the symbol should be "MATICUSDT_UMCBL" or 
'MATIC/USDT:USDT'

**Comment by carlosmiei** [comment]
> @carlosmiei @kroitor
> 
> the symbol should be "MATICUSDT_UMCBL" or 'MATIC/USDT:USDT'

@bebo12343 The first is the exchange-specific id whereas the latter is our unified symbol, you can read more about it here: https://docs.ccxt.com/#/README?id=symbols-and-market-ids

**Comment by bebo12343** [comment]
@carlosmiei 
@kroitor 

Dear what is the formula for closing open order ( short or long ) on future ?
