### ISSUE TITLE
ccxt.base.errors.BadSymbol: binance does not have market symbol BTC/USDT

### ISSUE THREAD

**Issue by 0x30c4** [ccxt/ccxt#18586]
### Operating System

mac os 13

### Programming Languages

python

### CCXT Version

4.0.21

### Description

When I use binance futures I get the following error from today.
Error: binance does not have market symbol BTC/USDT
It looks like the symbol has changed.
I would appreciate it if you can check.

```

Traceback (most recent call last):
  File "/Users/***/scalp.py", line 88, in <module>
    print(exchange.fetch_ticker("BTC/TUSD"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/***/.venv/lib/python3.11/site-packages/ccxt/binance.py", line 2890, in fetch_ticker
    market = self.market(symbol)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/***/.venv/lib/python3.11/site-packages/ccxt/binance.py", line 1702, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: binance does not have market symbol BTC/TUSD
```

### Code

```python
import ccxt
...
API_KEY = getenv("API_KEY")
SECRET_KEY = getenv("SECRET_KEY")
IS_SANDBOX = getenv("IS_SANDBOX")
...
exchange = ccxt.binance({
    'apiKey': API_KEY,
    'secret': SECRET_KEY,
    "enableRateLimit": True
})
...
exchange.set_sandbox_mode(IS_SANDBOX)
   ... 
    symbol_info = exchange.fetch_ticker("BTC/TUSD")
   ...
```

**Comment by kroitor** [comment]
@0x30c4 in your question you're asking about BTC/USDT perpetual futures swap market, while in your code you're trying to fetch the TUSD market (not USDT).

First and foremost, please, read the following:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#contract-naming-conventions

We highly recommend reading the entire Manual from top to bottom – it will really save your time.

Second, Binance does not have a TUSD-margined perpetual futures swap yet:

<img width="1344" alt="Screenshot 2023-07-15 at 10 39 40" src="https://github.com/ccxt/ccxt/assets/1294454/742b0a42-0820-4785-a171-58e6286befa6">

Third, here's a complete list of sandbox USDT-margined future swap markets:

```
~/ccxt $ node examples/js/cli binance markets --table --sandbox --verbose --debug | grep BTC

       BTCBUSD |             BTC/BUSD |       BTC |  BUSD |       BTC |    BUSD |   true |   spot |        |         |  true | false |  false |  false |  false |    false |              |               |                          |            |        |        |          | {"amount":6,"price":2,"base":8,"quote":8} | [object Object] |     false |       true |  0.001 |  0.001 |     get |        btcbusd
       BTCUSDT |             BTC/USDT |       BTC |  USDT |       BTC |    USDT |   true |   spot |        |         |  true | false |  false |  false |  false |    false |              |               |                          |            |        |        |          | {"amount":6,"price":2,"base":8,"quote":8} | [object Object] |     false |       true |  0.001 |  0.001 |     get |        btcusdt
        BNBBTC |              BNB/BTC |       BNB |   BTC |       BNB |     BTC |   true |   spot |        |         |  true | false |  false |  false |  false |    false |              |               |                          |            |        |        |          | {"amount":2,"price":6,"base":8,"quote":8} | [object Object] |     false |       true |  0.001 |  0.001 |     get |         bnbbtc
        ETHBTC |              ETH/BTC |       ETH |   BTC |       ETH |     BTC |   true |   spot |        |         |  true | false |  false |  false |  false |    false |              |               |                          |            |        |        |          | {"amount":5,"price":6,"base":8,"quote":8} | [object Object] |     false |       true |  0.001 |  0.001 |     get |         ethbtc
        LTCBTC |              LTC/BTC |       LTC |   BTC |       LTC |     BTC |   true |   spot |        |         |  true | false |  false |  false |  false |    false |              |               |                          |            |        |        |          | {"amount":5,"price":6,"base":8,"quote":8} | [object Object] |     false |       true |  0.001 |  0.001 |     get |         ltcbtc
        TRXBTC |              TRX/BTC |       TRX |   BTC |       TRX |     BTC |   true |   spot |        |         |  true | false |  false |  false |  false |    false |              |               |                          |            |        |        |          | {"amount":1,"price":8,"base":8,"quote":8} | [object Object] |     false |       true |  0.001 |  0.001 |     get |         trxbtc
        XRPBTC |              XRP/BTC |       XRP |   BTC |       XRP |     BTC |   true |   spot |        |         |  true | false |  false |  false |  false |    false |              |               |                          |            |        |        |          | {"amount":1,"price":8,"base":8,"quote":8} | [object Object] |     false |       true |  0.001 |  0.001 |     get |         xrpbtc
     BTCSTUSDT |      BTCST/USDT:USDT |     BTCST |  USDT |     BTCST |    USDT |  false |   swap |   true |   false | false |  true |  false |  false |  false |     true |            1 |               |                          |            |        |   USDT |     USDT | {"amount":1,"price":3,"base":8,"quote":8} | [object Object] |     false |       true | 0.0004 | 0.0002 |     get |      btcstusdt
       BTCUSDT |        BTC/USDT:USDT |       BTC |  USDT |       BTC |    USDT |   true |   swap |   true |   false | false |  true |  false |  false |  false |     true |            1 |               |                          |            |        |   USDT |     USDT | {"amount":3,"price":1,"base":8,"quote":8} | [object Object] |     false |       true | 0.0004 | 0.0002 |     get |        btcusdt
        ETHBTC |          ETH/BTC:BTC |       ETH |   BTC |       ETH |     BTC |   true |   swap |   true |   false | false |  true |  false |  false |  false |     true |            1 |               |                          |            |        |    BTC |      BTC | {"amount":2,"price":5,"base":8,"quote":8} | [object Object] |     false |       true | 0.0004 | 0.0002 |     get |         ethbtc
    BTCDOMUSDT |     BTCDOM/USDT:USDT |    BTCDOM |  USDT |    BTCDOM |    USDT |   true |   swap |   true |   false | false |  true |  false |  false |  false |     true |            1 |               |                          |            |        |   USDT |     USDT | {"amount":3,"price":1,"base":8,"quote":8} | [object Object] |     false |       true | 0.0004 | 0.0002 |     get |     btcdomusdt
BTCUSDT_230929 | BTC/USDT:USDT-230929 |       BTC |  USDT |       BTC |    USDT |   true | future |   true |   false | false | false |   true |  false |  false |     true |            1 | 1695974400000 | 2023-09-29T08:00:00.000Z |            |        |   USDT |     USDT | {"amount":3,"price":1,"base":8,"quote":8} | [object Object] |     false |       true | 0.0004 | 0.0002 |     get | btcusdt_230929
       BTCBUSD |        BTC/BUSD:BUSD |       BTC |  BUSD |       BTC |    BUSD |   true |   swap |   true |   false | false |  true |  false |  false |  false |     true |            1 |               |                          |            |        |   BUSD |     BUSD | {"amount":3,"price":2,"base":8,"quote":8} | [object Object] |     false |       true | 0.0004 | 0.0002 |     get |        btcbusd
   BTCUSD_PERP |          BTC/USD:BTC |       BTC |   USD |       BTC |     USD |   true |   swap |  false |    true | false |  true |  false |  false |  false |     true |          100 |               |                          |            |        |    BTC |      BTC | {"amount":0,"price":1,"base":8,"quote":8} | [object Object] |     false |       true | 0.0005 | 0.0001 |     get |    btcusd_perp
 BTCUSD_230929 |   BTC/USD:BTC-230929 |       BTC |   USD |       BTC |     USD |   true | future |  false |    true | false | false |   true |  false |  false |     true |          100 | 1695974400000 | 2023-09-29T08:00:00.000Z |            |        |    BTC |      BTC | {"amount":0,"price":1,"base":8,"quote":8} | [object Object] |     false |       true | 0.0005 | 0.0001 |     get |  btcusd_230929
 BTCUSD_231229 |   BTC/USD:BTC-231229 |       BTC |   USD |       BTC |     USD |   true | future |  false |    true | false | false |   true |  false |  false |     true |          100 | 1703836800000 | 2023-12-29T08:00:00.000Z |            |        |    BTC |      BTC | {"amount":0,"price":1,"base":8,"quote":8} | [object Object] |     false |       true | 0.0005 | 0.0001 |     get |  btcusd_231229
   ETHBTC_PERP |          ETH/BTC:ETH |       ETH |   BTC |       ETH |     BTC |  false |   swap |  false |    true | false |  true |  false |  false |  false |     true |           10 |               |                          |            |        |    ETH |      ETH | {"amount":0,"price":6,"base":8,"quote":8} | [object Object] |     false |       true | 0.0005 | 0.0001 |     get |    ethbtc_perp
   BTCETH_PERP |          BTC/ETH:BTC |       BTC |   ETH |       BTC |     ETH |  false |   swap |  false |    true | false |  true |  false |  false |  false |     true |          100 |               |                          |            |        |    BTC |      BTC | {"amount":0,"price":2,"base":8,"quote":8} | [object Object] |     false |       true | 0.0005 | 0.0001 |     get |    btceth_perp
~/ccxt $
```

- https://testnet.binancefuture.com/dapi/v1/exchangeInfo

You're probably interested in the BTC/USDT:USDT perpetual futures swap, if that is the case, please, use the following code:

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

API_KEY = getenv("API_KEY")
SECRET_KEY = getenv("SECRET_KEY")
IS_SANDBOX = getenv("IS_SANDBOX")
...
exchange = ccxt.binance({
    'apiKey': API_KEY,
    'secret': SECRET_KEY,
    "enableRateLimit": True
})
...
exchange.set_sandbox_mode(IS_SANDBOX) 
   ... 
    symbol_info = exchange.fetch_ticker("BTC/USDT:USDT")
   ...
```

Hope that answers your question. Let us know if that helps or not.

Feel free to reopen this issue or just ask further questions here if any.

**Comment by 0x30c4** [comment]
Hello, @kroitor.
Thank you for your kind reply. After checking ```IS_SANDBOX``` I noticed it was a string instead of bool. And that's why ccxt was trying to connect to the testnet.

I'm really sorry I should've checked my code before creating an issue.
