### ISSUE TITLE
Bitso requires additional compliance field for withdrawals above $1K

### ISSUE THREAD

**Issue by GaminHostin** [ccxt/ccxt#18641]
### Operating System

Mac Os

### Programming Languages

python

### CCXT Version

Latest version

### Description

Bitso requires additional compliance field for withdrawals above $1K, how do i add this to the request on python. I saw a javascript documentation for this but i don't know how to implement it on ccxt python.
`{
   "compliance": {
      "travel_rule": {
      }
   }
}`

### Code

```
  

```

**Comment by GaminHostin** [comment]
Figured that out but here's the new error `Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/exchange.py", line 600, in fetch
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.bitso.com/v3/ether_withdrawal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxxxxx/ccxtw/try.py", line 22, in <module>
    withdraw = exchange.withdraw('ETH', 1, 'xxxxxxxxxxxxxxxxxx', params, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/bitso.py", line 1482, in withdraw
    response = getattr(self, classMethod)(self.extend(request, params))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2989, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2986, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/exchange.py", line 618, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1616, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: bitso POST https://api.bitso.com/v3/ether_withdrawal 500 Internal Server Error 
xxxxxxxxx-MacBook-Pro ccxtw % `

**Comment by GaminHostin** [comment]
Still getting the 500 server error. Is this a bug? please help

**Comment by samgermain** [comment]
I'm closing this issue because it looks like it was solved, and the new issue was opened in #https://github.com/ccxt/ccxt/issues/18654
