### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by GaminHostin** [ccxt/ccxt#18654]
### Operating System

Mac Os

### Programming Languages

python

### CCXT Version

4.03

### Description

here's my error
```python
fetch Response: bitso POST https://api.bitso.com/v3/ether_withdrawal 500 ResponseHeaders: {'Date': 'Tue, 25 Jul 2023 17:36:32 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'x-frame-options': 'sameorigin', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'x-permitted-cross-domain-policies': 'master-only', 'content-security-policy': "frame-ancestors 'self';", 'cache-control': 'no-cache, no-store, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-envoy-upstream-service-time': '951', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=VVSYHFvzbsP.k6eRWkVkwYIe7Bpv6FLBG3thd.a.hRI-1690306592-0-AaNYxz2sEV6pHvaNuOLdPbpTpO/sXrzj+gN7LCn7rwBXsP5nDQNLv36J412b62eJP0+3XtTAfhf9Pqt8aiSy7es=; path=/; expires=Tue, 25-Jul-23 18:06:32 GMT; domain=.bitso.com; HttpOnly; Secure; SameSite=None', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Server': 'cloudflare', 'CF-RAY': '7ec62a61fb1d21fd-MIA'} ResponseBody: 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/exchange.py", line 600, in fetch
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.bitso.com/v3/ether_withdrawal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxxxxx/ccxtw/try.py", line 40, in <module>
    withdraw = exchange.withdraw('ETH', 1, 'xxxxxxxxx', params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/bitso.py", line 1482, in withdraw
    response = getattr(self, classMethod)(self.extend(request, params))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2989, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2986, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/exchange.py", line 618, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1616, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: bitso POST https://api.bitso.com/v3/ether_withdrawal 500 Internal Server Error 
```

### Code

```python
  
# -*- coding: utf-8 -*-

import os
import sys
from pprint import pprint
import requests

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402
headers = {
           'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
           'Content-Type': 'application/json; charset=utf-8'
           
           }


exchange = ccxt.bitso({
    'apiKey': "xxxxxxxxxx",
    'secret': "xxxxxxxxxxxxx",
    'verbose': True,  # switch it to False if you don't want the HTTP log
    'timeout': 3000,
    'proxies': 'http://167.249.254.70:1080',
    
         # with authentication also supported
    
})


exchange.userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
params = {}
params = {'compliance': 'travel_rule'}
travel_rule = None


withdraw = exchange.withdraw('ETH', 1, 'xxxxxxxxxxx', params)

pprint(headers)
pprint('Withdraw:')
pprint(withdraw)
```

**Comment by samgermain** [comment]
@GaminHostin Usually that means that there's a problem on the side of the exchange server and it doesn't reflect a problem with your code. Can you try again and let me know if you're still getting problems?
