### ISSUE TITLE
ccxt.fechDepositWithdrawFees has a bug

### ISSUE THREAD

**Issue by joyngq** [ccxt/ccxt#18708]
### Operating System

debian linux

### Programming Languages

Python

### CCXT Version

4.0.43

### Description

I had upgrade to python, ccxt 4.0.43, but when run the bitfinex exhange=fetchDepositeWithdrawFees(), it prompt the error as below: Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "/root/ccxt/app.py", line 41, in run_arbitrage_analysis
ccxt_not_supported = ccxtFunc.calculate_analysis_arbitrage_opportunities(markets_set, symbols_set, currencies_set, stop_event)
File "/root/ccxt/ccxtFunc.py", line 266, in calculate_analysis_arbitrage_opportunities
base_currency_protocols = load_withdraw_with_error_handling(markets_set[pro_exchange], base_currency)
File "/root/ccxt/ccxtFunc.py", line 74, in load_withdraw_with_error_handling
base_currency_protocols = exchange.fetchDepositWithdrawFees(base_currency)
File "/usr/local/lib/python3.9/dist-packages/ccxt/bitfinex.py", line 456, in fetch_deposit_withdraw_fees
response = self.privatePostAccountFees(params)
File "/usr/local/lib/python3.9/dist-packages/ccxt/base/types.py", line 26, in unbound_method
return _self.request(self.path, self.api, self.method, params, config=self.config)
File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 2994, in request
return self.fetch2(path, api, method, params, headers, body, config)
File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 2990, in fetch2
request = self.sign(path, api, method, params, headers, body)
File "/usr/local/lib/python3.9/dist-packages/ccxt/bitfinex.py", line 1538, in sign
signature = self.hmac(payload, secret, hashlib.sha384)
File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 1235, in hmac
h = hmac.new(secret, request, algorithm)
File "/usr/lib/python3.9/hmac.py", line 170, in new
return HMAC(key, msg, digestmod)
File "/usr/lib/python3.9/hmac.py", line 93, in init
self.update(msg)
File "/usr/lib/python3.9/hmac.py", line 113, in update
self._inner.update(msg)
TypeError: Unicode-objects must be encoded before hashing

### Code

```
  

```
def load_withdraw_with_error_handling(exchange, base_currency):
    try:
        base_currency_protocols = exchange.fetchDepositWithdrawFees(base_currency)
        # pprint.pprint(f'base_currency_protocols-{exchange.id}-{base_currency}:', stream=sys.stdout)
        # pprint.pprint(base_currency_protocols, stream=sys.stdout)
        return base_currency_protocols
    except ccxt.NotSupported:
        # Handle the case when fetchDepositWithdrawFees() is not supported
        ccxt_not_supported.append(exchange.id)
        if exchange.id == 'bitcoincom':
            pass
        else:
            logger.error(f"获取交易所 {exchange.id} 的 {base_currency} protocol ccxt.NotSupported")
        # base_currency_protocols = fetch_withdraw_protocol(markets_set[pro_exchange], base_currency)
        return None
    except Exception as e:
        if exchange.id == 'bitfinex':
            import traceback
            traceback.print_exc()
            raise
        logger.error(f"Failed to load withdraw info for {exchange.id}: {e}")
        return None

**Comment by carlosmiei** [comment]
Hello @joyngq, the fix was only released in 4.0.44, please upgrade your ccxt version and try again.
