### ISSUE TITLE
for bitfinex exchang, when call exchange.fetchDepositWithdrawFees(base_currency), there seems a bug

### ISSUE THREAD

**Issue by joyngq** [ccxt/ccxt#18703]
### Programming Languages

Python

### CCXT Version

4.0.41

### Description

1. when call exchange.fetchDepositWithdrawFees(base_currency) for bitfinex exchange, there's error: Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/ccxt/app.py", line 41, in run_arbitrage_analysis
    ccxt_not_supported = ccxtFunc.calculate_analysis_arbitrage_opportunities(markets_set, symbols_set, currencies_set, stop_event)
  File "/root/ccxt/ccxtFunc.py", line 275, in calculate_analysis_arbitrage_opportunities
    base_currency_protocols = load_withdraw_with_error_handling(markets_set[pro_exchange], base_currency)
  File "/root/ccxt/ccxtFunc.py", line 82, in load_withdraw_with_error_handling
    base_currency_protocols = exchange.fetchDepositWithdrawFees(base_currency, {
  File "/usr/local/lib/python3.9/dist-packages/ccxt/bitfinex.py", line 456, in fetch_deposit_withdraw_fees
    response = self.privatePostAccountFees(params)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 2994, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 2990, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/bitfinex.py", line 1538, in sign
    signature = self.hmac(payload, secret, hashlib.sha384)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 1235, in hmac
    h = hmac.new(secret, request, algorithm)
  File "/usr/lib/python3.9/hmac.py", line 170, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.9/hmac.py", line 93, in __init__
    self.update(msg)
  File "/usr/lib/python3.9/hmac.py", line 113, in update
    self._inner.update(msg)
^Croot@localhost:~/ccxt# ^Cmust be encoded before hashing

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @joyngq,
Thanks for reporting it, we will check it asap

**Comment by joyngq** [comment]
Thank you so much for quick response



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Igor ***@***.***> |
| Date | 07/30/2023 22:27 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ccxt/ccxt] for bitfinex exchang, when call exchange.fetchDepositWithdrawFees(base_currency), there seems a bug (Issue #18703) |

Closed #18703 as completed via #18707.

**Comment by joyngq** [comment]
I have uprage the ccxt to 

> ### Operating System
> 
> _No response_
> ### Programming Languages
> 
> Python
> ### CCXT Version
> 
> 4.0.41
> ### Description
> 
>     1. when call exchange.fetchDepositWithdrawFees(base_currency) for bitfinex exchange, there's error: Traceback (most recent call last):
>        File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
>        self.run()
>        File "/usr/lib/python3.9/threading.py", line 892, in run
>        self._target(*self._args, **self._kwargs)
>        File "/root/ccxt/app.py", line 41, in run_arbitrage_analysis
>        ccxt_not_supported = ccxtFunc.calculate_analysis_arbitrage_opportunities(markets_set, symbols_set, currencies_set, stop_event)
>        File "/root/ccxt/ccxtFunc.py", line 275, in calculate_analysis_arbitrage_opportunities
>        base_currency_protocols = load_withdraw_with_error_handling(markets_set[pro_exchange], base_currency)
>        File "/root/ccxt/ccxtFunc.py", line 82, in load_withdraw_with_error_handling
>        base_currency_protocols = exchange.fetchDepositWithdrawFees(base_currency, {
>        File "/usr/local/lib/python3.9/dist-packages/ccxt/bitfinex.py", line 456, in fetch_deposit_withdraw_fees
>        response = self.privatePostAccountFees(params)
>        File "/usr/local/lib/python3.9/dist-packages/ccxt/base/types.py", line 26, in unbound_method
>        return _self.request(self.path, self.api, self.method, params, config=self.config)
>        File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 2994, in request
>        return self.fetch2(path, api, method, params, headers, body, config)
>        File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 2990, in fetch2
>        request = self.sign(path, api, method, params, headers, body)
>        File "/usr/local/lib/python3.9/dist-packages/ccxt/bitfinex.py", line 1538, in sign
>        signature = self.hmac(payload, secret, hashlib.sha384)
>        File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 1235, in hmac
>        h = hmac.new(secret, request, algorithm)
>        File "/usr/lib/python3.9/hmac.py", line 170, in new
>        return HMAC(key, msg, digestmod)
>        File "/usr/lib/python3.9/hmac.py", line 93, in **init**
>        self.update(msg)
>        File "/usr/lib/python3.9/hmac.py", line 113, in update
>        self._inner.update(msg)
>        ^Croot@localhost:~/ccxt# ^Cmust be encoded before hashing
> 
> 
> ### Code
> 
> ```
>   
> ```
I had upgrade to python, ccxt 4.0.43, but when run the bitfinex exhange=fetchDepositeWithdrawFees(), it prompt the error as below: Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/ccxt/app.py", line 41, in run_arbitrage_analysis
    ccxt_not_supported = ccxtFunc.calculate_analysis_arbitrage_opportunities(markets_set, symbols_set, currencies_set, stop_event)
  File "/root/ccxt/ccxtFunc.py", line 266, in calculate_analysis_arbitrage_opportunities
    base_currency_protocols = load_withdraw_with_error_handling(markets_set[pro_exchange], base_currency)
  File "/root/ccxt/ccxtFunc.py", line 74, in load_withdraw_with_error_handling
    base_currency_protocols = exchange.fetchDepositWithdrawFees(base_currency)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/bitfinex.py", line 456, in fetch_deposit_withdraw_fees
    response = self.privatePostAccountFees(params)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 2994, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 2990, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/bitfinex.py", line 1538, in sign
    signature = self.hmac(payload, secret, hashlib.sha384)
  File "/usr/local/lib/python3.9/dist-packages/ccxt/base/exchange.py", line 1235, in hmac
    h = hmac.new(secret, request, algorithm)
  File "/usr/lib/python3.9/hmac.py", line 170, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.9/hmac.py", line 93, in __init__
    self.update(msg)
  File "/usr/lib/python3.9/hmac.py", line 113, in update
    self._inner.update(msg)
TypeError: Unicode-objects must be encoded before hashing
