### ISSUE TITLE
Poloniex cancel_order() CancelPending error

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#18785]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.0.49

### Description

While canceling an existing order in Poloniex an error is thrown. The order does actually vanish from `fetch_open_orders` reply, so `cancel_order` seems to be doing it job properly otherwise. Throwing an error is just unnecessary.

### Code

```python
self.exchange = ccxt.poloniex({...})
self.exchange.load_markets()
self.exchange.verbose = True
self.exchange.cancel_order(..., 'MATIC/TRX')
```

```python
fetch Request: poloniex DELETE https://api.poloniex.com/orders/... RequestHeaders: {'Content-Type': 'application/json', 'key': ..., 'signTimestamp': ..., 'signature': ..., 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: poloniex DELETE https://api.poloniex.com/orders/... 200 ResponseHeaders: {'Date': ..., 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'RateLimit-Filter': 'updated', 'Web-Filter': 'authenticated', 'CF-Cache-Status': 'DYNAMIC', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': ..., 'Content-Encoding': 'gzip'} ResponseBody: {
  "orderId" : ...,
  "clientOrderId" : "",
  "state" : "PENDING_CANCEL",
  "code" : 200,
  "message" : ""
}
Traceback (most recent call last):
...
    self.exchange.cancel_order(..., 'MATIC/TRX')
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/poloniex.py", line 1271, in cancel_order
    return self.privateDeleteOrdersId(self.extend(request, params))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2994, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2991, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 644, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/poloniex.py", line 2097, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], codeInner, feedback)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3357, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.CancelPending: poloniex {
  "orderId" : ...,
  "clientOrderId" : "",
  "state" : "PENDING_CANCEL",
  "code" : 200,
  "message" : ""
}
```

**Comment by kroitor** [comment]
@JovianMoon to clarify, are you trying to cancel an order that has already been scheduled for canceling with a previous call to cancel_order(), or is it the first time you call cancel_order() on that specific order?

**Comment by JovianMoon** [comment]
@kroitor It's the first time calling cancel_order() for that specific order. 

I now tested it again and saw that the order disappeared from the orderbook in Poloniex website immediately after I called cancel_order(), and the call raised the same error again.

**Comment by kroitor** [comment]
> @kroitor It's the first time calling cancel_order() for that specific order.
> 
> I now tested it again and saw that the order disappeared from the orderbook in Poloniex website immediately after I called cancel_order(), and the call raised the same error again.

Got it, will address it asap, thank you!

**Comment by carlosmiei** [comment]
@JovianMoon Thanks for reporting it, we opened a PR to fix this issue, and it will be resolved shortly.
