### ISSUE TITLE
Strange string concatenation when using a proxy server in the request URL

### ISSUE THREAD

**Issue by StasToken** [ccxt/ccxt#18799]
### Operating System

Ubuntu 22.04.2 LTS

### Programming Languages

Python

### CCXT Version

4.0.21

### Description

I'm trying to make one specific request through a proxy server
however, the proxy server is added to the main URL
It seems to me that this is abnormal behavior, although I may be wrong

_ccxt.base.errors.ExchangeNotAvailable: binance GET http://your_proxy_here:porthttps://api.binance.com/api/v3/exchangeInfo_

Traceback (most recent call last):

```
  File "/home/master/soft/pycharm-2022.3.2/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 24, in <module>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "<input>", line 13, in main
  File "/home/master/PycharmProjects/project/venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 2890, in fetch_ticker
    await self.load_markets()
  File "/home/master/PycharmProjects/project/venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 251, in load_markets
    raise e
  File "/home/master/PycharmProjects/project/venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 247, in load_markets
    result = await self.markets_loading
  File "/home/master/PycharmProjects/project/venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 237, in load_markets_helper
    markets = await self.fetch_markets(params)
  File "/home/master/PycharmProjects/project/venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 1945, in fetch_markets
    promises = await asyncio.gather(*promisesRaw)
  File "/home/master/PycharmProjects/project/venv/lib/python3.10/site-packages/ccxt/async_support/binance.py", line 7482, in request
    response = await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/master/PycharmProjects/project/venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 1832, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/master/PycharmProjects/project/venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 214, in fetch
    raise ExchangeNotAvailable(details) from e
ccxt.base.errors.ExchangeNotAvailable: binance GET http://your_proxy_here:porthttps://api.binance.com/api/v3/exchangeInfo
```

### Code

```
import ccxt.async_support as ccxt
import asyncio

async def main():
    # Initialize the exchange
    exchange = ccxt.binance()

    # Now let's make a request with a proxy for just one function call
    original_proxy = exchange.proxy  # Save the original proxy setting
    exchange.proxy = 'http://your_proxy_here:port'

    # Make a request using the proxy
    ticker = await exchange.fetch_ticker('BTC/USDT')
    print(ticker)

    # Revert back to the original proxy setting
    exchange.proxy = original_proxy

    # Close the exchange session after using
    await exchange.close()

# Run the asynchronous function
loop = asyncio.get_event_loop()
loop.run_until_complete(main())  

```

**Comment by carlosmiei** [comment]
Hello @StasToken, `proxy` is meant to be a CORs proxy that is why it is appending the URL to the proxy. I believe you want to use a regular http/sProxy so you should use `httpsProxy/httpProxy` instead, example:

```Python
 exchange.httpsProxy = 'http://your_proxy_here:port'
```
