### ISSUE TITLE
BingX some functions throw AuthenticationError for certain symbols

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#18846]
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.0.55

### Description

`fetch_open_orders`, `fetch_closed_orders` and probably some other functions throw AuthenticationError when using certain symbols. At least using 'OTHR#99961', 'OTHR#14996' and 'MAYC#15186' cause this.

Perhaps this has something to do with `urlencode` in `sign` converting '#' into '%' symbol for the query?

### Code

```
exchange = ccxt.bingx(...)
exchange.load_markets()
exchange.verbose = True
exchange.fetch_open_orders('OTHR#99961/USDT')
```
```
 fetch Request: bingx GET https://open-api.bingx.com/openApi/spot/v1/trade/openOrders?symbol=OTHR%2399961-USDT&timestamp=1691624265507&signature=... RequestHeaders: {'X-BX-APIKEY': ..., 'X-SOURCE-KEY': 'CCXT', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bingx GET https://open-api.bingx.com/openApi/spot/v1/trade/openOrders?symbol=OTHR%2399961-USDT&timestamp=1691624265507&signature=... 200 ResponseHeaders: {'Date': 'Wed, 09 Aug 2023 23:37:45 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': ..., 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': ..., 'alt-svc': 'h3=":443"; ma=86400'} ResponseBody: {"code":100001,"msg":"Signature verification failed due to signature mismatch","success":false,"timestamp":1691624265622}
Traceback (most recent call last):
  File "/home/xyz/test.py", line 6, in <module>
    exchange.fetch_open_orders('OTHR#99961/USDT')
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bingx.py", line 1898, in fetch_open_orders
    response = self.spotV1PrivateGetTradeOpenOrders(self.extend(request, query))
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3008, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3005, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 644, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bingx.py", line 2666, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3371, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: bingx {"code":100001,"msg":"Signature verification failed due to signature mismatch","success":false,"timestamp":1691624265622}
```

**Comment by carlosmiei** [comment]
Hello @JovianMoon, thanks for reporting it, yeah I think you're right but we will patch it as soon as possible.
