### ISSUE TITLE
Binance: error when using Ed25519 private key for authentication: Ed25519PrivateKey.sign() takes 1 positional arguments but 3 were given

### ISSUE THREAD

**Issue by rthorndy** [ccxt/ccxt#18876]
### Operating System

Debian (built-in environment provided in Pixelbook Go ChromeOS)

### Programming Languages

Python

### CCXT Version

4.0.58

### Description

I'm using an Ed25519 symmetric key pair to authenticate to binance. The $BIANANCE_PRIVATE_KEY environment variable is a string set with:
```
export BINANCE_PRIVATE_KEY=$(cat my_private_key_file.pem)
```
I have used this private key in manual API calls, and the binance.check_required_credentials() seems to pass. But as soon as I try to issue a private request, I get the attached error.

### Code

CODE:
```
    print(ccxt.__version__)
    binance = ccxt.binance({
        'apiKey' : os.getenv('BINANCE_API'),
        'secret':os.getenv('BINANCE_PRIVATE_KEY')
    })
    binance.verbose = True
    binance.check_required_credentials()
    print(binance.fetchBalance())
```

OUTPUT:
```
4.0.58
Traceback (most recent call last):
  File "/home/rthorndy/Documents/arb.git/ccxt/test.py", line 39, in <module>
    print(binance.fetchBalance())
  File "/home/rthorndy/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2431, in fetch_balance
    self.load_markets()
  File "/home/rthorndy/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1433, in load_markets
    currencies = self.fetch_currencies()
  File "/home/rthorndy/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1782, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/rthorndy/.local/lib/python3.9/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/rthorndy/.local/lib/python3.9/site-packages/ccxt/binance.py", line 7484, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "/home/rthorndy/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3015, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/home/rthorndy/.local/lib/python3.9/site-packages/ccxt/binance.py", line 7391, in sign
    signature = self.encode_uri_component(self.rsa(query, self.secret, 'sha256'))
  File "/home/rthorndy/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1307, in rsa
    return Exchange.binary_to_base64(priv_key.sign(Exchange.encode(request), padding.PKCS1v15(), algorithm))
TypeError: Ed25519PrivateKey.sign() takes 1 positional arguments but 3 were given

```

**Comment by kroitor** [comment]
@rthorndy according to Binance changelogs, the support for Ed25519 keys is a relatively new feature, at this time CCXT supports just the RSA keys:

- https://www.binance.com/en/support/faq/how-to-generate-an-rsa-key-pair-to-send-api-requests-on-binance-2b79728f331e43079b27440d9d15c5db

We will add the support for Ed25519 asap:

- https://www.binance.com/en/support/announcement/binance-now-supports-ed25519-api-keys-2023-07-19-30372026b6af4fbbb9b38ab5c3f91755

**Comment by rthorndy** [comment]
Works for me. Thank you!
