### ISSUE TITLE
Binance VIP Loan API Invalid Signature

### ISSUE THREAD

**Issue by zhangxf55** [ccxt/ccxt#18881]
### Operating System

CentOS7.6

### Programming Languages

JavaScript

### CCXT Version

4.0.58

### Description

Binance VIP Loan API: POST /sapi/v1/loan/vip/borrow
(https://binance-docs.github.io/apidocs/spot/cn/#vip-trade-3)

The params: collateralAccountId and collateralCoin can be multiple accounts and tokens, like this:
{
  "loanAccountId": "12345678", 
  "requestId": "12345678",
  "loanCoin": "BTC", 
  "loanAmount": "100.55", 
  "collateralAccountId": "12345678,12345678,12345678",
  "collateralCoin": "BUSD,USDT,ETH",   
  "loanTerm": "30"
}
While using a comma in the params, Invalid Signature error will ocurr.

### Code

Test Code:
```
const ccxt = require('ccxt').pro;
const api = require('./config.json').api;

async function testBorrow() {
    const binance = new ccxt.binance(api);
    const params = {
        loanAccountId: 74840374,
        loanCoin: 'BTC',
        loanAmount: '5',
        collateralAccountId: '74840374,569581815',
        collateralCoin: '1INCH,AAVE,ACH,ADA,AERGO,AGIX,AGLD,ALCX,ALGO,ALPINE,AMP,ANKR,APE,APT,ARB,ARKM,ARPA,ASTR,ATOM,AVAX,AXS,BAKE,BAND,BCH,BETH,BNB,BOND,BTC,BTTC,BUSD,CAKE,CFX,CHZ,COMP,CRV,CTSI,CVC,DOGE,DOT,DYDX,EDU,EGLD,ENS,EOS,ERN,ETC,ETH,EUR,FARM,FDUSD,FET,FIL,FIS,FLOW,FLUX,FORTH,FTM,FXS,GAL,GALA,GLM,GMT,GRT,HBAR,HFT,HIGH,HOOK,ICP,ID,IDEX,ILV,IMX,INJ,JASMY,JOE,KSM,LDO,LINA,LINK,LOKA,LPT,LQTY,LTC,LUNA,LUNC,MAGIC,MANA,MASK,MATIC,MDT,MINA,MTL,NEAR,NMR,OCEAN,OG,ONE,OOKI,OP,OSMO,PAXG,PEOPLE,PHB,PLA,POLS,POND,PYR,QI,QNT,QUICK,RAD,RARE,RDNT,REQ,RNDR,ROSE,RSR,RUNE,SAND,SANTOS,SHIB,SNX,SOL,SSV,STG,STX,SUI,SUPER,SUSHI,SXP,SYS,THETA,TRU,TRX,TUSD,TVK,TWT,UNFI,UNI,USDC,USDP,USDT,VET,VOXEL,VTHO,WAVES,WBETH,XLM,XMR,XRP,ZEC,ZEN,ZIL',
        loanTerm: 30
    };
    const borrow = await binance.sapiPostLoanVipBorrow(params);
    console.log(JSON.stringify(borrow));
}
```
Exception:
```
/root/workspace/binance-price-delta/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3087
            throw new exact[string](message);
                  ^

AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."}
    at binance.throwExactlyMatchedException (/root/workspace/binance-price-delta/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3087:19)
    at binance.handleErrors (/root/workspace/binance-price-delta/node_modules/ccxt/dist/cjs/src/binance.js:8097:18)
    at /root/workspace/binance-price-delta/node_modules/ccxt/dist/cjs/src/base/Exchange.js:766:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async binance.fetch2 (/root/workspace/binance-price-delta/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2666:16)
    at async binance.request (/root/workspace/binance-price-delta/node_modules/ccxt/dist/cjs/src/binance.js:8128:26)
    at async testBorrow (/root/workspace/binance-price-delta/loan.js:14:20)
```

**Comment by ttodua** [comment]
late reply, but what i see in documentation https://developers.binance.com/docs/vip_loan/user-information/Get-VIP-Loan-Ongoing-Orders#request-parameters the `collateralAccountId` should be `LONG` (numeric, not string) in request (even though in response it seems to be string).

let us know if anyone experiences any issues
