### ISSUE TITLE
Bitget fetch_trades() replace market/fills to market/fills-history

### ISSUE THREAD

**Issue by fridary** [ccxt/ccxt#18888]
### Operating System

Mac

### Programming Languages

Python

### CCXT Version

4.0.57

### Description

Wrong `since` param converting. `since = exchange.parse8601('..')` converts to `1690848000000` instead `1690848000`
Because of this I get error `ccxt.base.errors.ExchangeError: bitget {"code":"400172","msg":"Parameter verification failed","requestTime":1691858304961,"data":null}`

But that's okey, the most problem is `since` param does not return correct past date:
```python
since = exchange.parse8601('2023-07-17T00:00:00Z') // 1000
trades = exchange.fetch_trades(symbol, since, 100)
print(len(trades), 'trades')
print(f"first date={datetime.fromtimestamp(trades[0]['timestamp']/1000)}, last date={datetime.fromtimestamp(trades[-1]['timestamp']/1000)}")
```
returns 
```
100 trades
first date=2023-08-14 23:59:50.208000, last date=2023-08-15 00:02:47.925000
```
date `2023-08-14` must be `2023-07-17`

I think because of this:
> I also noticed ccxt requests /api/mix/v1/market/fills instead /api/mix/v1/market/fills-history

So perhaps it needs to change `response = self.publicMixGetMarketFills(extended)` to `response = self.publicMixGetMarketFillsHistory(extended)` here https://github.com/ccxt/ccxt/blob/1f9b632ef9a8b28d97219ee91ec14d63f0fe8509/python/ccxt/bitget.py#L2185

### Code

```python
import ccxt
print(ccxt.__version__)

exchange = ccxt.bitget()
exchange.options['defaultType'] = 'swap' # futures market
# exchange.options['productType'] = 'umcbl'
# exchange.options['pageSize'] = 1
# exchange.options['pageNo'] = 1

symbol = 'EOSUSDT_UMCBL'

markets = exchange.load_markets()
market = exchange.market(symbol)
exchange.verbose = True
since = exchange.parse8601('2023-08-01T00:00:00')
trades = exchange.fetch_trades(symbol, since)
print(len(trades), 'trades')
```

```
fetch Request: bitget GET https://api.bitget.com/api/mix/v1/market/fills?symbol=EOSUSDT_UMCBL&limit=1690848000000 RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitget GET https://api.bitget.com/api/mix/v1/market/fills?symbol=EOSUSDT_UMCBL&limit=1690848000000 400 ResponseHeaders: {'Date': 'Sat, 12 Aug 2023 16:38:25 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Request-ID': '018547480bbd4ff79a5081eac8b6e4dc', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'requestTime': '1691858304961', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=vGJXxDItyQfAHeB1lhHKu9AldQwqzh9Ch0WpPL8VvUs-1691858305-0-AUdbavKCuhD3SR9NJBwPwilBeqI1wZGVJObD2f/h1bkABnBOcNLFv7gP2eUrT96WKz8EQ5xkZbPAjWWOFgdR5sk=; path=/; expires=Sat, 12-Aug-23 17:08:25 GMT; domain=.bitget.com; HttpOnly; Secure; SameSite=None, _cfuvid=Q5a5vVZ6T3Y4SoiCLw3j6IQgj5EKmza0N1UuWPzXE1Y-1691858305105-0-604800000; path=/; domain=.bitget.com; HttpOnly; Secure; SameSite=None', 'X-Frame-Options': 'SAMEORIGIN', 'Server': 'cloudflare', 'CF-RAY': '7f5a2604ebfc7b33-DME'} ResponseBody: {"code":"400172","msg":"Parameter verification failed","requestTime":1691858304961,"data":null}
Traceback (most recent call last):
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/base/exchange.py", line 600, in fetch
    response.raise_for_status()
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitget.com/api/mix/v1/market/fills?symbol=EOSUSDT_UMCBL&limit=1690848000000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test5.py", line 17, in <module>
    trades = exchange.fetch_trades(symbol, since)
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/bitget.py", line 2185, in fetch_trades
    response = self.publicMixGetMarketFills(extended)
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3019, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3016, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/base/exchange.py", line 616, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/sirjay/miniconda3/envs/rl/lib/python3.8/site-packages/ccxt/bitget.py", line 4638, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bitget {"code":"400172","msg":"Parameter verification failed","requestTime":1691858304961,"data":null}
```

**Comment by Dan-krm** [comment]
Thanks for pointing this out, I think you're right because the current endpoints don't support the since argument but the `publicMixGetMarketFillsHistory` endpoint does. I'll make some changes and open a pull request that will close this issue.
