### ISSUE TITLE
OKX RateLimitExceeded

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#18901]
### Operating System

Windows 10

### Programming Languages

JavaScript

### CCXT Version

4.0.64

### Description

D:\CCXTBaseLine\Node>node okxBestPrix.js 2
RateLimitExceeded: okx {"msg":"Too Many Requests","code":"50011"}
    at okx.throwExactlyMatchedException (file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/base/Exchange.js:3083:19)
    at okx.handleErrors (file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/okx.js:6737:18)
    at file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/base/Exchange.js:760:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async okx.fetch2 (file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/base/Exchange.js:2662:16)
    at async okx.request (file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/base/Exchange.js:2665:16)
    at async okx.fetchTicker (file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/okx.js:1736:26)
    at async Promise.all (index 40)

D:\CCXTBaseLine\Node> I have the similar JavaScript code for other exchanges, like Binanace, Kraken, Kucoin, Bitstamps, Bybit and others, they all work well.  Like Binance, it has even more pairs, the same code works well; but for okx it is not working. Let me know what is the limit on the number of pairs I can request for exchange OKX? If the limit is 30 pairs each time, then how can I rewrite the JavaScript to do the job?

### Code

```
import ccxt from 'ccxt';

const args = process.argv.slice(2);
const alertLevel = parseFloat(args[0]);
const previousPricesJson = args[1]; 
const pairs = ['BTC/USDT', 'MKR/USDT', 'ETH/USDT', 'BCH/USDT', 'XRP/USDT', 'XMR/USDT', 'ETH/BTC', 'LTC/USDT', 'SOL/USDT', 'USDC/USDT', 'DOGE/USDT', 'SHIB/USDT', 'LINK/USDT', 'OP/USDT', 'LTC/BTC', 'BCH/BTC', 'MATIC/USDT', 'AAVE/USDT', 'YFII/USDT', 'BNB/USDT', 'ADA/USDT', 'WLD/USDT', 'CRV/USDT', 'BTC/USDC', 'AVAX/USDT', 'ETC/USDT', 'TRX/USDT', 'DYDX/USDT', 'FIL/USDT', 'LDO/USDT', 'YGG/USDT', 'DOT/USDT', 'XLM/USDT', 'EOS/USDT', 'ATOM/USDT', 'BNT/USDT', 'UNI/USDT', 'SAND/USDT', 'OXT/USDT', 'PEPE/USDT', 'XRP/BTC', 'GRT/USDT', 'ETC/BTC', 'COMP/USDT', 'APE/USDT', 'GALA/USDT', 'RNDR/USDT', 'NEAR/USDT', 'ARB/USDT', 'FTM/USDT', 'SSV/USDT', 'HBAR/USDT', 'AXS/USDT', 'MASK/USDT', 'TRX/BTC', 'LQTY/USDT', 'DASH/BTC', 'ZEC/USDT', 'ETH/USDC', 'JST/USDT', 'MAGIC/USDT', 'MANA/USDT', 'ZEC/BTC', 'SNX/USDT', 'BAT/USDT', 'WAVES/USDT', 'LINK/BTC', 'ALGO/USDT'];

function fetchBestPrice() {
    const exchange = new ccxt.okx();
    const promises = pairs.map(pair => exchange.fetchTicker(pair));

    Promise.all(promises)
        .then(result => {
            let previousPrices = [];

            if (previousPricesJson) {
                try {
                    previousPrices = JSON.parse(previousPricesJson);
                } catch (error) {
                    console.error('Error parsing previous prices JSON:', error);
                }
            }
        })
        .catch(error => {
            console.error(error);
        });
}

fetchBestPrice();
```

**Comment by leonelos-dev** [comment]
I'm experiencing the same issue! Please ccxt Team we need your help

**Comment by ttodua** [comment]
OKX had this known-issue, we had recently merged an update to increase it, so users can retry with latest version.
users can also try to increase ratelimit by 5% or 10% and retry, eg:
```
ex = ccxt.okx()
originalRL =ex.rateLimit
ex.rateLimit = originalRL * 1.05
```

let us know if any issues.
