### ISSUE TITLE
huobipro BadSymbol

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#18902]
### Operating System

Windows 10

### Programming Languages

JavaScript

### CCXT Version

4.0.64

### Description

D:\CCXTBaseLine\Node>node huobiBestPrix.js 1
BadSymbol: huobipro {"ts":1692170952507,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}
    at huobipro.throwExactlyMatchedException (file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/base/Exchange.js:3083:19)
    at huobipro.handleErrors (file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/huobi.js:6490:22)
    at file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/base/Exchange.js:760:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async huobipro.fetch2 (file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/base/Exchange.js:2662:16)
    at async huobipro.request (file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/base/Exchange.js:2665:16)
    at async huobipro.fetchTicker (file:///D:/CCXTBaseLine/Node/node_modules/ccxt/js/src/huobi.js:1891:26)
    at async Promise.all (index 12)

D:\CCXTBaseLine\Node> => Hi, I try to fetch a group of Tickers from huobipro exchange, the funny thing is: at first, when I tested my code, I can see some error, like 'USDi/USD' does not exist for huobipro exchange, so I can simply delete the pair from the pair list; but after I tested the code a few times, I got the error message as above, but I have no idea what symbols are not correct.  Is there any way to find out?

### Code

```
import ccxt from 'ccxt';

const args = process.argv.slice(2);
const alertLevel = parseFloat(args[0]);
const previousPricesJson = args[1]; 
const pairs = 
['BTC/USDT', 'MKR/USDT', 'ETH/USDT', 'BTC/TUSD', 'BCH/USDT', 'XRP/USDT',
'XMR/USDT', 'ETH/BTC', 'LTC/USDT', 'SOL/USDT', 'USDC/USDT', 'DOGE/USDT',
'BTC/EUR', 'SHIB/USDT', 'LINK/USDT', 'TUSD/USDT',
'OP/USDT', 'LTC/BTC', 'BCH/BTC', 'MATIC/USDT', 'AAVE/USDT', 'YFII/USDT', 'BNB/USDT',
'ADA/USDT', 'WLD/USDT', 'CRV/USDT', 'BTC/USDC',
'AVAX/USDT', 'ETC/USDT', 'TRX/USDT', 'DYDX/USDT', 'FIL/USDT', 'LDO/USDT',
'YGG/USDT', 'DOT/USDT', 'XLM/USDT', 'EOS/USDT', 'ATOM/USDT', 'BNT/USDT',
'UNI/USDT', 'SAND/USDT', 'USDT/TRY', 'OXT/USDT', 'PEPE/USDT', 'XRP/BTC', 'GRT/USDT',
'ETC/BTC', 'COMP/USDT', 'APE/USDT', 'AKRO/USDT', 'GALA/USDT',
'RNDR/USDT', 'NEAR/USDT', 'ARB/USDT', 'DODO/USDT', 'FTM/USDT',
'INJ/USDT', 'SSV/USDT', 'HBAR/USDT', 'AXS/USDT', 'MASK/USDT', 'TRX/BTC',
'LQTY/USDT', 'DASH/BTC', 'ZEC/USDT', 'ETH/USDC', 'JST/USDT',
'MAGIC/USDT', 'MANA/USDT', 'ZEC/BTC', 'OXT/BTC', 
'SNX/USDT', 'BAT/USDT', 'WAVES/USDT', 'LINK/BTC',
'UNFI/USDT', 'ALGO/USDT', 'BNT/BTC'];

function fetchBestPrice() {
    const exchange = new ccxt.huobipro();
    const promises = pairs.map(pair => exchange.fetchTicker(pair));
    const maxChange = 1.0 + (alertLevel / 100.0);
    const minChange = 1.0 - (alertLevel / 100.0);

    Promise.all(promises)
        .then(result => {
            let previousPrices = [];

            if (previousPricesJson) {
                try {
                    previousPrices = JSON.parse(previousPricesJson);
                } catch (error) {
                    console.error('Error parsing previous prices JSON:', error);
                }
            }

        })
        .catch(error => {
            console.error(error);
        });
}

fetchBestPrice();


```

**Comment by carlosmiei** [comment]
@zydjohnHotmail Alternatively before calling `fetchTicker` you can check if the symbol exists in the exchange by doing `symbol in exchange.symbols` (you need to load the markets manually first to do this `await exchange.loadMarkets()`

**Comment by zydjohnHotmail** [comment]
'use strict';
const ccxt = require('ccxt');
console.log(ccxt.version);

const args = process.argv.slice(2);
const pairs = 
['BTC/USDT', 'MKR/USDT', 'ETH/USDT', 'BTC/TUSD', 'BCH/USDT', 'XRP/USDT',
'XMR/USDT', 'ETH/BTC', 'LTC/USDT', 'SOL/USDT', 'USDC/USDT', 'DOGE/USDT',
'BTC/EUR', 'SHIB/USDT', 'LINK/USDT', 'TUSD/USDT',
'OP/USDT', 'LTC/BTC', 'BCH/BTC', 'MATIC/USDT', 'AAVE/USDT', 'YFII/USDT', 'BNB/USDT',
'ADA/USDT', 'WLD/USDT', 'CRV/USDT', 'BTC/USDC',
'AVAX/USDT', 'ETC/USDT', 'TRX/USDT', 'DYDX/USDT', 'FIL/USDT', 'LDO/USDT',
'YGG/USDT', 'DOT/USDT', 'XLM/USDT', 'EOS/USDT', 'ATOM/USDT', 'BNT/USDT',
'UNI/USDT', 'SAND/USDT', 'USDT/TRY', 'OXT/USDT', 'PEPE/USDT', 'XRP/BTC', 'GRT/USDT',
'ETC/BTC', 'COMP/USDT', 'APE/USDT', 'AKRO/USDT', 'GALA/USDT',
'RNDR/USDT', 'NEAR/USDT', 'ARB/USDT', 'DODO/USDT', 'FTM/USDT',
'INJ/USDT', 'SSV/USDT', 'HBAR/USDT', 'AXS/USDT', 'MASK/USDT', 'TRX/BTC',
'LQTY/USDT', 'DASH/BTC', 'ZEC/USDT', 'ETH/USDC', 'JST/USDT',
'MAGIC/USDT', 'MANA/USDT', 'ZEC/BTC', 'OXT/BTC', 
'SNX/USDT', 'BAT/USDT', 'WAVES/USDT', 'LINK/BTC',
'UNFI/USDT', 'ALGO/USDT', 'BNT/BTC'];

(async function () {
    const exchange = new ccxt.huobipro({
        verbose: false,
        defaultType: 'spot',
        adjustForTimeDifference: true,
    });

    try {
        const loadedMarkets = await exchange.loadMarkets();
        const loadedPairSymbols = Object.keys(loadedMarkets);

        // Check and log pairs not available in loaded markets
        const missingPairs = pairs.filter(pair => !loadedPairSymbols.includes(pair));
        if (missingPairs.length > 0) {
            console.log('Pairs not available in loaded markets:', missingPairs);
        } else {
            console.log('All pairs in the list are available in loaded markets.');
        }
    } catch (error) {
        console.error('Error fetching markets:', error);
    }
})();
=> code output: D:\nodejs\CCXT>node huobiCheckPairs.js
4.0.64
All pairs in the list are available in loaded markets.

D:\nodejs\CCXT> => Let me know if I made any mistake in my JS code or something else, all the pairs seem in the loadMarkets(), but I when I run previous JS code, I still got the same error: BadSymbol: huobipro {"ts":1692170952507,"status":"error","err-code":"invalid-parameter","err-msg":"invalid symbol"}

**Comment by ttodua** [comment]
late reply in this topic, but when users want to fetch all available tickers from exchange, it's advised to use `.fetchTickers` and there would be all available symbols (by exchange) included, that way users can check whether some symbols (even if they appear in 'loadMarkets') might be unavailable from tickers.

to filter out such symbols, you might check whether that `market.active` status is not `false` for that "invalid symbol". I think that is problem in such situations (I remember htx behaved that way).

let us know if anyone has any issues
