### ISSUE TITLE
AttributeError: 'binance' object has no attribute 'fapiPublic_get_fundingrate'

### ISSUE THREAD

**Issue by fmccabe80** [ccxt/ccxt#18954]
### Operating System

Ubuntu 22.04.3 LTS / VSCode 1.81.1

### Programming Languages

Python

### CCXT Version

4.0.68

### Description

Look's like Binance 

computer@computer:~/Desktop/T_B$ /bin/python3 /home/computer/Desktop/T_B/Test.py
Traceback (most recent call last):
  File "/home/computer/Desktop/T_B/Test.py", line 54, in <module>
    funding_bot()
  File "/home/computer/Desktop/T_B/Test.py", line 26, in funding_bot
    response = exchange.fapiPublic_get_fundingrate({
AttributeError: 'binance' object has no attribute 'fapiPublic_get_fundingrate'

Why do I have this error message and how to fix it?

### Code

```
import ccxt
from pprint import pprint
import pytz, time
from datetime import datetime, timedelta
import schedule
import pandas as pd


#Create the Binance exchange instance
def funding_bot():
    exchange = ccxt.binance({
        'enableRateLimit': True,
        'options': {
        'defaultType': 'future',
    },})
    
    #Load the Market details
    markets = exchange.load_markets()

    sym1 = 'BTC/USDT'
    #sym2 = 'ETH/USDT'

    sym1_market = exchange.market(sym1)
    #sym2_market = exchange.market(sym2)

    response = exchange.fapiPublic_get_fundingrate({
        'symbol': sym1_market['id']
    })
    #print(response)
    #print(response[-2]['fundingRate'])

    last_funding_rate = float(response[-9]['fundingRate'])
    last_yrly_funding = ((last_funding_rate *3)*365)*100
    last_yrly_funding = round(last_yrly_funding,2)
    print(f'{last_yrly_funding}%')

    utc_time = datetime.now(pytz.utc)
    mountain_time = utc_time.astimezone(pytz.timezone('Canada/Edmonton'))
    formated_time = mountain_time.strftime('%m-%d-%y %H:%M:%S')

    temp_df = pd.DataFrame({'datetime': [formated_time], 'name': [sym1], 'output': [last_yrly_funding]})
    #temp_df2 = pd.DataFrame({'datetime': [formated_time], 'name': [sym2], 'output': [last_yrly_funding]})

    #grabs OG
    og_df = pd.read_csv('july23/signals.csv')

    df_combined = pd.concat([og_df, temp_df], ignore_index=True)
    df_combined.to_csv('july23/signals.csv', index=False)

    print(df_combined)



funding_bot()
schedule.every(300).seconds.do(funding_bot)

while True:
    try:
        schedule.run_pending()
        time.sleep(10)
    except Exception as e:
        print('*** Maybe internet connection lost? ***')
        print(e)
        time.sleep(10)


```

**Comment by sc0Vu** [comment]
Hi @fmccabe80 

It's might be `fapipublic_get_fundingrate`.

<img width="1233" alt="image" src="https://github.com/ccxt/ccxt/assets/10494397/55bff234-4253-4dff-a289-52b476dc4d38">

**Comment by arya-n-raj** [comment]
@so0Vu  then whats the final code
