### ISSUE TITLE
BingX fetch_ticker and fetch_tickers() spot endpoint should be public

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#19024]
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.0.77

### Description

The endpoint works without api keys: https://open-api.bingx.com/openApi/spot/v1/ticker/24hr?timestamp=1693225340851

### Code

```
exchange = ccxt.bingx()
exchange.load_markets()
exchange.verbose = True
print(exchange.fetch_ticker('BTC/USDT'))
```
```
Traceback (most recent call last):
  File "/home/xyz/test.py", line 6, in <module>
    print(exchange.fetch_ticker('BTC/USDT'))
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bingx.py", line 1072, in fetch_ticker
    response = self.spotV1PrivateGetTicker24hr(self.extend(request, params))
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3019, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3015, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bingx.py", line 2726, in sign
    self.check_required_credentials()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3220, in check_required_credentials
    raise AuthenticationError(self.id + ' requires "' + key + '" credential')
ccxt.base.errors.AuthenticationError: bingx requires "apiKey" credential

```

**Comment by carlosmiei** [comment]
Hello again @JovianMoon, sorry since I have the keys automatically loaded, I didn't notice they were considered private endpoints, will check it.
