### ISSUE TITLE
ccxt pro - Call to undefined function React\Promise\Timer\timeout( (and other issues)

### ISSUE THREAD

**Issue by carels** [ccxt/ccxt#19042]
### Operating System

Macos

### Programming Languages

PHP

### CCXT Version

4.0.78

### Description

I am trying to switch some of my code from fetch* functions to watch* function using ccxt pro, but running into some issues. Firstly, I've tried implementing the "one-exchange-many-streams.php" example, but what I find is that the code just sits at the following line:

```
$orderbook = yield $exchange->watch_order_book($symbol);
```

It never returns any data or proceeds from there.

I then decided to start a fresh installation of ccxt and run some very simple code (below), but this results in the following error:

```
Fatal error: Uncaught Error: Call to undefined function React\Promise\Timer\timeout() in /Users/carel/Sites/tim/vendor/ccxt/ccxt/php/pro/Client.php:150
Stack trace:
#0 /Users/carel/Sites/tim/vendor/ccxt/ccxt/php/pro/Client.php(195): ccxt\pro\Client->create_connection()
#1 /Users/carel/Sites/tim/vendor/ccxt/ccxt/php/pro/ClientTrait.php(98): ccxt\pro\Client->connect(0)
#2 /Users/carel/Sites/tim/vendor/ccxt/ccxt/php/pro/bybit.php(1355): ccxt\async\Exchange->watch('wss://stream.by...', 'orderbook:BTC/U...', Array, 'orderbook:BTC/U...')
#3 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(191): ccxt\pro\bybit->ccxt\pro\{closure}()
#4 [internal function]: React\Async\{closure}()
#5 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(202): Fiber->start()
#6 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(228): React\Async\{closure}(Object(Closure), Object(Closure), Object(Closure))
#7 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(25): React\Promise\Promise->call(NULL)
#8 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(188): React\Promise\Promise->__construct(NULL, NULL)
#9 /Users/carel/Sites/tim/vendor/ccxt/ccxt/php/pro/bybit.php(1356): React\Async\{closure}()
#10 /Users/carel/Sites/tim/vendor/ccxt/ccxt/php/pro/bybit.php(456): ccxt\pro\bybit->watch_topics('wss://stream.by...', 'orderbook:BTC/U...', Array, Array)
#11 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(191): ccxt\pro\bybit->ccxt\pro\{closure}()
#12 [internal function]: React\Async\{closure}()
#13 /Users/carel/Sites/tim/vendor/react/async/src/SimpleFiber.php(28): Fiber->resume(Array)
#14 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(299): React\Async\SimpleFiber->resume(Array)
#15 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(28): React\Async\{closure}(Array)
#16 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#17 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#18 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#19 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}(Array)
#20 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#21 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#22 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#23 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(191): React\Promise\Promise::React\Promise\{closure}(Array)
#24 [internal function]: React\Async\{closure}()
#25 /Users/carel/Sites/tim/vendor/react/async/src/SimpleFiber.php(28): Fiber->resume(Array)
#26 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(299): React\Async\SimpleFiber->resume(Array)
#27 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(28): React\Async\{closure}(Array)
#28 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#29 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#30 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#31 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(191): React\Promise\Promise::React\Promise\{closure}(Array)
#32 [internal function]: React\Async\{closure}()
#33 /Users/carel/Sites/tim/vendor/react/async/src/SimpleFiber.php(28): Fiber->resume(Array)
#34 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(299): React\Async\SimpleFiber->resume(Array)
#35 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(28): React\Async\{closure}(Array)
#36 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#37 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#38 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#39 /Users/carel/Sites/tim/vendor/react/promise/src/functions.php(262): React\Promise\Promise::React\Promise\{closure}(Array)
#40 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\{closure}(Array)
#41 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#42 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#43 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#44 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}(Array)
#45 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#46 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#47 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#48 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(191): React\Promise\Promise::React\Promise\{closure}(Array)
#49 [internal function]: React\Async\{closure}()
#50 /Users/carel/Sites/tim/vendor/react/async/src/SimpleFiber.php(28): Fiber->resume(Array)
#51 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(299): React\Async\SimpleFiber->resume(Array)
#52 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(28): React\Async\{closure}(Array)
#53 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#54 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#55 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#56 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(191): React\Promise\Promise::React\Promise\{closure}(Array)
#57 [internal function]: React\Async\{closure}()
#58 /Users/carel/Sites/tim/vendor/react/async/src/SimpleFiber.php(28): Fiber->resume(Array)
#59 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(299): React\Async\SimpleFiber->resume(Array)
#60 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(28): React\Async\{closure}(Array)
#61 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#62 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#63 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#64 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(191): React\Promise\Promise::React\Promise\{closure}(Array)
#65 [internal function]: React\Async\{closure}()
#66 /Users/carel/Sites/tim/vendor/react/async/src/SimpleFiber.php(28): Fiber->resume(Array)
#67 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(299): React\Async\SimpleFiber->resume(Array)
#68 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(28): React\Async\{closure}(Array)
#69 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#70 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#71 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#72 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(191): React\Promise\Promise::React\Promise\{closure}(Array)
#73 [internal function]: React\Async\{closure}()
#74 /Users/carel/Sites/tim/vendor/react/async/src/SimpleFiber.php(28): Fiber->resume(Object(RingCentral\Psr7\Response))
#75 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(299): React\Async\SimpleFiber->resume(Object(RingCentral\Psr7\Response))
#76 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(28): React\Async\{closure}(Object(RingCentral\Psr7\Response))
#77 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#78 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#79 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#80 /Users/carel/Sites/tim/vendor/react/promise/src/Deferred.php(36): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response))
#81 /Users/carel/Sites/tim/vendor/react/http/src/Io/Transaction.php(90): React\Promise\Deferred->resolve(Object(RingCentral\Psr7\Response))
#82 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(28): React\Http\Io\Transaction->React\Http\Io\{closure}(Object(RingCentral\Psr7\Response))
#83 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#84 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#85 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#86 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response))
#87 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#88 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#89 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#90 /Users/carel/Sites/tim/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response))
#91 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#92 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#93 /Users/carel/Sites/tim/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#94 /Users/carel/Sites/tim/vendor/react/http/src/Io/Transaction.php(193): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response))
#95 /Users/carel/Sites/tim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Http\Io\Transaction->React\Http\Io\{closure}()
#96 /Users/carel/Sites/tim/vendor/react/http/src/Io/ReadableBodyStream.php(50): Evenement\EventEmitter->emit('close')
#97 /Users/carel/Sites/tim/vendor/react/http/src/Io/ReadableBodyStream.php(151): React\Http\Io\ReadableBodyStream->close()
#98 /Users/carel/Sites/tim/vendor/react/http/src/Io/ReadableBodyStream.php(33): React\Http\Io\ReadableBodyStream->handleEnd()
#99 /Users/carel/Sites/tim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Http\Io\ReadableBodyStream->React\Http\Io\{closure}('t":"50000"},"pr...')
#100 /Users/carel/Sites/tim/vendor/react/http/src/Io/CloseProtectionStream.php(96): Evenement\EventEmitter->emit('data', Array)
#101 /Users/carel/Sites/tim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Http\Io\CloseProtectionStream->handleData('t":"50000"},"pr...')
#102 /Users/carel/Sites/tim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#103 /Users/carel/Sites/tim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}('t":"50000"},"pr...')
#104 /Users/carel/Sites/tim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit('data', Array)
#105 /Users/carel/Sites/tim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData(Resource id #186)
#106 /Users/carel/Sites/tim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity(58459056)
#107 /Users/carel/Sites/tim/vendor/react/event-loop/src/Loop.php(250): React\EventLoop\StreamSelectLoop->run()
#108 /Users/carel/Sites/tim/vendor/react/async/src/SimpleFiber.php(61): React\EventLoop\Loop::run()
#109 [internal function]: React\Async\SimpleFiber::React\Async\{closure}()
#110 /Users/carel/Sites/tim/vendor/react/async/src/SimpleFiber.php(71): Fiber->start()
#111 /Users/carel/Sites/tim/vendor/react/async/src/functions.php(357): React\Async\SimpleFiber->suspend()
#112 /Users/carel/Sites/tim/vendor/ccxt/ccxt/php/async/Exchange.php(75): React\Async\await(Object(React\Promise\Promise))
#113 /Users/carel/Sites/tim/test.php(15): ccxt\async\Exchange::execute_and_run(Object(Closure))
#114 {main}
  thrown in /Users/carel/Sites/tim/vendor/ccxt/ccxt/php/pro/Client.php on line 150
```

Any suggestions to overcome either issue? 

Thanks,
Carel

### Code

```
  <?php

        require 'vendor/autoload.php';

        $exchange = new \ccxt\pro\bybit();
        $symbol = 'BTC/USDT'; // Replace with the trading pair you want to monitor
        $limit = 10; // Number of order book levels to fetch
        $symbols = ['BTC/USDT:USDT'];
        $exchange->options['tradesLimit'] = 5;

        echo 'CCXT version ', \ccxt\pro\Exchange::VERSION, "\n";
        echo 'Supported exchanges: ', json_encode(\ccxt\pro\Exchange::$exchanges), "\n";

        if ($exchange->has['watchOrderBook']) {
            $exchange::execute_and_run(function() use ($exchange, $symbol, $limit) {
                while (true) {
                    try {
                        $orderbook = yield $exchange->watch_order_book($symbol, $limit);
                        echo date('c'), ' ', $symbol, ' ', json_encode(array($orderbook['asks'][0], $orderbook['bids'][0])), "\n";
                    } catch (Exception $e) {
                        echo get_class($e), ' ', $e->getMessage(), "\n";
                    }
                }
            });
        }


```

**Comment by sc0Vu** [comment]
Hey @carels 

It looks like the react/promise-timer was missing, before the fix merged, would you like to install this manually?

```
composer require react/promise-timer:^1.10
```

Sorry for you inconvenience.

**Comment by carels** [comment]
Thanks @sc0Vu - that fixed the problem :)

> Hey @carels
> 
> It looks like the react/promise-timer was missing, before the fix merged, would you like to install this manually?
> 
> ```
> composer require react/promise-timer:^1.10
> ```
> 
> Sorry for you inconvenience.
