### ISSUE TITLE
ccxt.base.errors.NetworkError: okx GET https://www.okx.com/api/v5/asset/currencies

### ISSUE THREAD

**Issue by Jiujiuwhoami** [ccxt/ccxt#19045]
### Operating System

windows

### Programming Languages

Python

### CCXT Version

4.0.78

### Description

when i try to connect okx，it dosn‘t work and get the error as follow：

`Traceback (most recent call last):
  File "D:\quant_ccxt\main.py", line 18, in <module>
    data()
  File "D:\quant_ccxt\main.py", line 8, in data
    data_acquisition = DataAcquisition(config.exchange_id, config.symbols, config.data_folder,config.interval)
  File "D:\quant_ccxt\data_acquisition.py", line 31, in __init__
    print(self.exchange.fetch_ohlcv('BTC/USDT', '5m',since='1504541580000', limit=200))
  File "D:\python\lib\site-packages\ccxt\okx.py", line 2005, in fetch_ohlcv
    self.load_markets()
  File "D:\python\lib\site-packages\ccxt\base\exchange.py", line 1433, in load_markets
    currencies = self.fetch_currencies()
  File "D:\python\lib\site-packages\ccxt\okx.py", line 1493, in fetch_currencies
    response = self.privateGetAssetCurrencies(params)
  File "D:\python\lib\site-packages\ccxt\base\types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "D:\python\lib\site-packages\ccxt\base\exchange.py", line 3019, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "D:\python\lib\site-packages\ccxt\base\exchange.py", line 3016, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\python\lib\site-packages\ccxt\base\exchange.py", line 627, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: okx GET https://www.okx.com/api/v5/asset/currencies`

i saw the history of issues，and i guess it maybe is about the vpn，but i don’t know how to solve it.

### Code

```
  

```

**Comment by Jiujiuwhoami** [comment]
this is the code of connect:

` self.exchange = getattr(ccxt, self.exchange_id)({
            'apiKey': config.OKEX_API_KEY,
            'secret': config.OKEX_SECRET_KEY,
            'password': config.OKEX_TEST_PASSPHRASE,
            'test': True,  
        })`

it is work when i use another vpn. And now i use the clash as vpn replace before，but the program is not work

**Comment by carlosmiei** [comment]
Hello @Jiujiuwhoami, yes this is not a CCXT problem per se but a network-related issue, it might be due to your location for instance.

One way to work around the issue is to use a proxy, CCXT supports different types of proxies, you can read more about it here: https://docs.ccxt.com/#/README?id=proxy

**Comment by qq984862387** [comment]
我也是这个问题，怎么解决？

**Comment by Jiujiuwhoami** [comment]
> Hello @Jiujiuwhoami, yes this is not a CCXT problem per se but a network-related issue, it might be due to your location for instance.
> 
> One way to work around the issue is to use a proxy, CCXT supports different types of proxies, you can read more about it here: https://docs.ccxt.com/#/README?id=proxy

Oh,i am sorry. i just see your answer.Thanks for your help. i try but it seems not work:

`def __init__(self, exchange_id, symbols, data_folder, interval):
        self.exchange_id = exchange_id
        self.symbols = symbols
        self.interval = interval
        self.exchange = getattr(ccxt, self.exchange_id)({
            'apiKey': config.OKEX_API_KEY,
            'secret': config.OKEX_SECRET_KEY,
            'password': config.OKEX_TEST_PASSPHRASE,
            'test': True,  
           # 'verbose': True,  
        })
        self.proxyUrl = 'http://127.0.0.1:7890'`

And when i debug,i get it:

`fetch Request: okx GET https://www.okx.com/api/v5/asset/currencies RequestHeaders: {'OK-ACCESS-KEY': '032a92-7ee-4512-a45b-39168855ef', 'OK-ACCESS-PASSPHRASE': '22222', 'OK-ACCESS-TIMESTAMP': '2023-09-03T03:07:34.380Z', 'OK-ACCESS-SIGN': 'tW9L6krUVeEMe1i6CUEkNqDPvZYA3BAofQ=', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None
Error initializing BTC/USDT data: okx GET https://www.okx.com/api/v5/asset/currencies`

**Comment by Jiujiuwhoami** [comment]
Oh,i am sorry. i just saw your answer.Thanks for your help. i try but it seems not work:

def __init__(self, exchange_id, symbols, data_folder, interval): self.exchange_id = exchange_id self.symbols = symbols self.interval = interval self.exchange = getattr(ccxt, self.exchange_id)({ 'apiKey': config.OKEX_API_KEY, 'secret': config.OKEX_SECRET_KEY, 'password': config.OKEX_TEST_PASSPHRASE, 'test': True,   # 'verbose': True,   }) self.exchange.proxyUrl = 'http://127.0.0.1:7890'

And when i debug,i get it:

fetch Request: okx GET https://www.okx.com/api/v5/asset/currencies RequestHeaders: {'OK-ACCESS-KEY': '032a92-7ee-4512-a45b-39168855ef', 'OK-ACCESS-PASSPHRASE': '22222', 'OK-ACCESS-TIMESTAMP': '2023-09-03T03:07:34.380Z', 'OK-ACCESS-SIGN': 'tW9L6krUVeEMe1i6CUEkNqDPvZYA3BAofQ=', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None Error initializing BTC/USDT data: okx GET https://www.okx.com/api/v5/asset/currencies

**Comment by Jiujiuwhoami** [comment]
> Hello @Jiujiuwhoami, yes this is not a CCXT problem per se but a network-related issue, it might be due to your location for instance.
> 
> One way to work around the issue is to use a proxy, CCXT supports different types of proxies, you can read more about it here: https://docs.ccxt.com/#/README?id=proxy

Oh,i am sorry. i just saw your answer.Thanks for your help. i try but it seems not work:

def init(self, exchange_id, symbols, data_folder, interval): self.exchange_id = exchange_id self.symbols = symbols self.interval = interval self.exchange = getattr(ccxt, self.exchange_id)({ 'apiKey': config.OKEX_API_KEY, 'secret': config.OKEX_SECRET_KEY, 'password': config.OKEX_TEST_PASSPHRASE, 'test': True, # 'verbose': True, }) self.exchange.proxyUrl = 'http://127.0.0.1:7890/'

And when i debug,i get it:

fetch Request: okx GET https://www.okx.com/api/v5/asset/currencies RequestHeaders: {'OK-ACCESS-KEY': '032a92-7ee-4512-a45b-39168855ef', 'OK-ACCESS-PASSPHRASE': '22222', 'OK-ACCESS-TIMESTAMP': '2023-09-03T03:07:34.380Z', 'OK-ACCESS-SIGN': 'tW9L6krUVeEMe1i6CUEkNqDPvZYA3BAofQ=', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '/', 'Connection': 'keep-alive'} RequestBody: None Error initializing BTC/USDT data: okx GET https://www.okx.com/api/v5/asset/currencies

**Comment by Jiujiuwhoami** [comment]
> 我也是这个问题，怎么解决？

没有解决

**Comment by Jiujiuwhoami** [comment]
i also set  ' self.exchange.httpProxy = 'http://127.0.0.1:7890/' '  ,but it also does not work .i can open pages in browser by this proxy .
