### ISSUE TITLE
Latoken fetch_open_orders() endpoint to fetch all open orders available

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#19106]
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.0.83

### Description

Currently Latoken's `fetch_open_orders` requires a symbol argument, but it looks like there is an endpoint available to fetch all open orders at once: https://api.latoken.com/doc/v2/#tag/Order/operation/getMyActiveOrders

### Code

```
exchange = ccxt.latoken(...)
print(exchange.fetch_open_orders())  
```
```
Traceback (most recent call last):
  File "/home/xyz/test.py", line 4, in <module>
    print(exchange.fetch_open_orders())
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/latoken.py", line 1010, in fetch_open_orders
    raise ArgumentsRequired(self.id + ' fetchOpenOrders() requires a symbol argument')
ccxt.base.errors.ArgumentsRequired: latoken fetchOpenOrders() requires a symbol argument
```

**Comment by samgermain** [comment]
We will need to update the Latoken api to V2 to implement this new method, so it requires a bit more work than just changing the endpoint used

**Comment by JovianMoon** [comment]
@samgermain Which part of the API is not v2 yet? Line 35 of latoken.py reads
```
'version': 'v2'
```
Also when I call `fetch_open_orders` with a symbol argument there is 'v2' in the url:
```
exchange = ccxt.latoken(...)
exchange.load_markets()
exchange.verbose = True
exchange.fetch_open_orders('GOL/USDT')
```

```
fetch Request: latoken GET https://api.latoken.com/v2/auth/order/pair/6b57e213-136c-4717-8b78-54026cd57bb7/0c3a106d-bde3-4c13-a26e-3fd2394529e5/active RequestHeaders: {'X-LA-APIKEY': ..., 'X-LA-SIGNATURE': ..., 'X-LA-DIGEST': 'HMAC-SHA512', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None
```
Am I missing something?

**Comment by samgermain** [comment]
> Which part of the API is not v2 yet? Line 35 of latoken.py reads

You're right, the class is using v2 of the API, sorry for the late reply.

When I add the method and try to use it on the latoken exchange class however, I receive the following error `latoken {"status":"FAILURE","message":"Unable to find matching target resource method","error":"NOT_FOUND","errors":null,"result":false}` so this will require some investigation to find out why it's not working

**Comment by JovianMoon** [comment]
@samgermain I understand, hopefully the endpoint is not broken at their side. I'm not sure if this matters, but I noticed that there is a difference between the headers in the call made in PR #19106 and the current symbol requiring endpoint. Namely these are missing from the PR call headers:
```
'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'
```

**Comment by ttodua** [comment]
> [@samgermain](https://github.com/samgermain) I understand, hopefully the endpoint is not broken at their side. I'm not sure if this matters, but I noticed that there is a difference between the headers in the call made in PR [#19266](https://github.com/ccxt/ccxt/pull/19266) and the current symbol requiring endpoint. Namely these are missing from the PR call headers:
> 
> ```
> 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'
> ```

it has been years, I've checked again and that endpoint still does not work. we can consider that as not-implemented in API.
