### ISSUE TITLE
How to use ccxt in typescript ( node js )

### ISSUE THREAD

**Issue by harishajdarevic** [ccxt/ccxt#1921]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubuntu
- Programming Language version: 8.9.4
- CCXT version: 1.10.0

Hello, 

I installed ccxt via

`npm install ccxt --save-dev`

In my app.ts I included it like:

`import ccxt = require ('ccxt');`

and when i type

`console.log(ccxt.exchanges); `

I'm getting error:

```
/home/haris/WebstormProjects/dynamodb/node_modules/ccxt/js/base/Exchange.js:328
                    let partial = async params => this[methodName] (path, type, uppercaseMethod, params || {})


```

**Comment by kroitor** [comment]
Hi!

> I'm getting error:

You've shown the line that triggers the error, but you haven't shown the actuall error itself, can you please paste more lines around the error (all of them, preferably) ?

**Comment by harishajdarevic** [comment]
@kroitor Sure...

```
/home/haris/WebstormProjects/dynamodb/node_modules/ccxt/js/base/Exchange.js:328
                    let partial = async params => this[methodName] (path, type, uppercaseMethod, params || {})
                                        ^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/haris/WebstormProjects/dynamodb/node_modules/ccxt/ccxt.js:33:19)
    at Module._compile (module.js:570:32)

npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/home/haris/.nvm/versions/node/v6.9.4/bin/node" "/home/haris/.nvm/versions/node/v6.9.4/lib/node_modules/npm/bin/npm-cli.js" "run" "run app" "--scripts-prepend-node-path=auto"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! dynamo-db@1.0.0 run app: `ts-node app/app.ts --timeout 120000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dynamo-db@1.0.0 run app script 'ts-node app/app.ts --timeout 120000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dynamo-db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ts-node app/app.ts --timeout 120000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dynamo-db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dynamo-db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/haris/WebstormProjects/dynamodb/npm-debug.log

```

**Comment by kroitor** [comment]
> npm ERR! node v6.9.4

You're running it in Node v6 that does not support the new ES6 `async` syntax at all. Your version of Node is outdated. Please, update it to the most recent Node9+ and retry the same code, should work normally. Let us know if it does not help.

**Comment by harishajdarevic** [comment]
@kroitor 

It works! Thanks!
