### ISSUE TITLE
Upbit Fetch balance not working

### ISSUE THREAD

**Issue by Mohdwaqas816** [ccxt/ccxt#19236]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.0.93

### Description

When I tried to connect upbit Private api Method Fetch Balance funtion it is giving me this error
```
 cxt\base\exchange.py", line 3415, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.AuthenticationError: upbit {"error":{"message":"Access key is incorrect.","name":"invalid_access_key"}}
```
But actually my api key and secret are correct I have tested it using their official doc endpoint and getting this response:

```
[{'currency': 'ADA', 'balance': '****', 'locked': '0', 'avg_buy_price': '0.9724275092936803', 'avg_buy_price_modified': False, 'unit_currency': 'USDT'}]
```

### Code

```
import ccxt
upbit = ccxt.upbit({
    'apiKey': API_KEY_UPBIT,
    'secret': SECRET_KEY_UPBIT,
    'enableRateLimit': True
})

def fetch_balance():
    balance = upbit.fetch_balance()
    print(balance)

fetch_balance()

getting this error:

cxt\base\exchange.py", line 3415, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.AuthenticationError: upbit {"error":{"message":"Access key is incorrect.","name":"invalid_access_key"}}
```

On the other hand 
same credentials working when connecting directly using upbit official doc

**Comment by Mohdwaqas816** [comment]
@carlosmiei  please look into this:

```
fetch Request: upbit GET https://api.upbit.com/v1/accounts RequestHeaders: {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5Ijoiem1MNGlpTDBvb0dVRW54cExveUZMNGtZRFc5S284TldSWmZneGtVOCIsIm5vbmNlIjoxNjk2OTIyNjU4MTQwfQ.9pRytTUOeH_tehNdI8xBKqFEFU2_x_qXq7UYNKjNuV4', 'User-Agent': 'python-requests/2.30.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: upbit GET https://api.upbit.com/v1/accounts 401 ResponseHeaders: {'Date': 'Tue, 10 Oct 2023 07:24:17 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Remaining-Req': 'group=default; min=899; sec=29', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers'} ResponseBody: {"error":{"message":"Access key is incorrect.","name":"invalid_access_key"}}
```

**Comment by Mohdwaqas816** [comment]
although my credentials is valid: 
I think this is wrong https://api.upbit.com/ 
instead of this use https://sg-api.upbit.com/ because using this url it is working fine

**Comment by Mohdwaqas816** [comment]
@carlosmiei see after changing to the above url:

```
fetch Request: upbit GET https://sg-api.upbit.com/v1/accounts RequestHeaders: {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiNGdmdnhueEV3YjBDd0hjVTJLOGF4Slg2N0tNZEZBYm9QcEdPYUVGMiIsIm5vbmNlIjoxNjk2OTI5NTQ2MzAyfQ.IR9k50mfdSbSe4loCTMIVgydYsjPBJJmDbgNALD4he8', 'User-Agent': 'python-requests/2.30.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: upbit GET https://sg-api.upbit.com/v1/accounts 200 ResponseHeaders: {'Date': 'Tue, 10 Oct 2023 09:19:05 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Remaining-Req': 'group=default; min=1800; sec=29', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate'} ResponseBody: [{"currency":"ADA","balance":"10.386546","locked":"0","avg_buy_price":"0.9724275092936803","avg_buy_price_modified":false,"unit_currency":"USDT"}]
{'info': [{'currency': 'ADA', 'balance': '10.386546', 'locked': '0', 'avg_buy_price': '0.9724275092936803', 'avg_buy_price_modified': False, 'unit_currency': 'USDT'}], 'timestamp': None, 'datetime': None, 'ADA': {'free': 10.386546, 'used': 0.0, 'total': 10.386546}, 'free': {'ADA': 10.386546}, 'used': {'ADA': 0.0}, 'total': {'ADA': 10.386546}}

fetch Request: upbit GET https://sg-api.upbit.com/v1/deposits RequestHeaders: {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiNGdmdnhueEV3YjBDd0hjVTJLOGF4Slg2N0tNZEZBYm9QcEdPYUVGMiIsIm5vbmNlIjoxNjk2OTI5NTQ3MzA0fQ.wfIqlGcyphZj74X1TpMr2qlaLuHPferp3gZDqHW28_I', 'User-Agent': 'python-requests/2.30.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: upbit GET https://sg-api.upbit.com/v1/deposits 200 ResponseHeaders: {'Date': 'Tue, 10 Oct 2023 09:19:06 GMT', 'Content-Type': 'application/json', 'Content-Length': '250', 'Connection': 'keep-alive', 'Remaining-Req': 'group=default; min=1800; sec=28', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Origin', 'X-Runtime': '0.075689', 'Access-Control-Allow-Headers': 'Authorization, Content-Type, Accept, *', 'X-Request-Id': '464db156-039d-47bb-9255-0d36919f3b66', 'Access-Control-Allow-Origin': '*', 'Server': 'Finatra', 'content-encoding': 'gzip', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate'} ResponseBody: [{"type":"deposit","uuid":"91ebd2b9-be6a-4442-9788-d3245ea6e92f","currency":"ADA","net_type":"ADA","txid":"27d395453e70a834fc3f33c0680b7f22d7cfb32e94fac05537d6d666ed4a3332","state":"ACCEPTED","created_at":"2023-05-30T20:41:45Z","done_at":"2023-05-30T20:50:18Z","amount":"10.386546","fee":"0.0","transaction_type":"default"}]
[{'info': {'type': 'deposit', 'uuid': '91ebd2b9-be6a-4442-9788-d3245ea6e92f', 'currency': 'ADA', 'net_type': 'ADA', 'txid': '27d395453e70a834fc3f33c0680b7f22d7cfb32e94fac05537d6d666ed4a3332', 'state': 'ACCEPTED', 'created_at': '2023-05-30T20:41:45Z', 'done_at': '2023-05-30T20:50:18Z', 'amount': '10.386546', 'fee': '0.0', 'transaction_type': 'default'}, 'id': '91ebd2b9-be6a-4442-9788-d3245ea6e92f', 'currency': 'ADA', 'amount': 10.386546, 'network': None, 'address': None, 'addressTo': None, 'addressFrom': None, 'tag': None, 'tagTo': None, 'tagFrom': None, 'status': 'pending', 'type': 'deposit', 'updated': 1685479818000, 'txid': '27d395453e70a834fc3f33c0680b7f22d7cfb32e94fac05537d6d666ed4a3332', 'timestamp': 1685479305000, 'datetime': '2023-05-30T20:41:45.000Z', 'fee': {'currency': 'ADA', 'cost': 0.0}}]
```

**Comment by ouoabcde** [comment]
I have same issue either.

**Operating System**
macOS Sonoma 14.0

**Programming Languages**
Python

**CCXT Version**
4.1.12

**Description**
Here is my error log.
```
Traceback (most recent call last):
  File "/Users/chunjunghyun/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ccxt/base/exchange.py", line 610, in fetch
    response.raise_for_status()
  File "/Users/chunjunghyun/.pyenv/versions/3.10.13/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.upbit.com/v1/accounts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chunjunghyun/junghyun/toy-projects/crypto-arbitrage-trading-bot/balance.py", line 15, in <module>
    balance = exchange.fetch_balance()
  File "/Users/chunjunghyun/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ccxt/upbit.py", line 502, in fetch_balance
    response = self.privateGetAccounts(params)
  File "/Users/chunjunghyun/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/Users/chunjunghyun/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3079, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/Users/chunjunghyun/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3076, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/chunjunghyun/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ccxt/base/exchange.py", line 626, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/chunjunghyun/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ccxt/upbit.py", line 1728, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], name, feedback)
  File "/Users/chunjunghyun/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3447, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.AuthenticationError: upbit {"error":{"name":"invalid_access_key","message":"Access key is incorrect."}}
```

**Comment by Dan-krm** [comment]
Here is how to point to Upbit in Singapore, you can change the base hostname, like this:

```Python
import ccxt
exchange = ccxt.upbit({
    'apiKey': 'GLOBAL_API_KEY',
    'secret': 'GLOBAL_SECRET',
    'enableRateLimit': True,
    'hostname': 'sg-api.upbit.com',  # ←----------------- HERE
})
print(exchange.fetch_balance())
```
