### ISSUE TITLE
Lack of txid in Kraken order response not handled

### ISSUE THREAD

**Issue by justinxjx** [ccxt/ccxt#1925]
- OS: Windows 10
- Programming Language version: Python 3.6.3 :: Anaconda custom (64-bit)
- CCXT version: 1.10.1128
- Exchange: Kraken
- Method: ```create_order```

It appears that kraken.py does not handle the case when txids are not returned in the response from Kraken. According to their API docs, the txid array is only added if an order was added successfully. In my case, I was sending the ```params = {'validate': 'true'}``` for testing my order configuration. Since this optional parameter is for input validation only, no order is actually submitted. You can see in the response posted below, that the 'descr' order info was received, but no txid was included. This resulted in the KeyError within kraken.py.

My call:
```
order_resp = my_exchange.create_order(my_pair, my_order_type, my_side,
                                              my_amount, limit_price, {'validate': 'true'})
```
Verbose output:
```
POST https://api.kraken.com/0/private/AddOrder
Request: {'API-Key': 'keykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeyke', 'API-Sign': 'signsignsignsignsignsignsignsignsignsignsignsignsignsignsignsignsignsignsignsignsignsign', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} nonce=1518815637482&pair=XXLMXXBT&type=sell&ordertype=market&volume=301.0&validate=true
POST https://api.kraken.com/0/private/AddOrder
Response: {'Date': 'Fri, 16 Feb 2018 21:13:58 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d0047edfafe0bc32a83d558b28d9cc63c1518815637; expires=Sat, 16-Feb-19 21:13:57 GMT; path=/; domain=.kraken.com; HttpOnly', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '3ee38388cc0452b4-MIA'} {"error":[],"result":{"descr":{"order":"sell 301.00000000 XLMXBT @ market"}}}
Traceback (most recent call last):
  File "S:\Crypto\Programming\Python\test_script.py", line 83, in <module>
    my_amount, limit_price, {'validate': 'true'})
  File "C:\Program Files\Python36\lib\site-packages\ccxt\kraken.py", line 563, in create_order
    length = len(response['result']['txid'])
KeyError: 'txid'
```

From kraken.py:
```
response = self.privatePostAddOrder(self.extend(order, params))
length = len(response['result']['txid'])
id = response['result']['txid'] if (length > 1) else response['result']['txid'][0]
return {
    'info': response,
    'id': id,
}
```

**Comment by justinxjx** [comment]
Awesome! Thanks for fixing that so quickly!
