### ISSUE TITLE
BitMart fetch_open_orders() and fetch_my_trades() have endpoints available that do not require symbol argument

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#19380]
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.0.106

### Description

ccxt currently requires `symbol` argument for `fetch_open_orders` and `fetch_my_trades` for BitMart. However, their v4 API offers endpoints that do not require it:

https://developer-pro.bitmart.com/en/spot/#current-open-orders-v4-signed
https://developer-pro.bitmart.com/en/spot/#account-trade-list-v4-signed

There's also this endpoint available for orders:

https://developer-pro.bitmart.com/en/spot/#account-orders-v4-signed

### Code

``` 
exchange = ccxt.bitmart()
exchange.fetch_open_orders()
```
``` 
Traceback (most recent call last):
  File "/home/xyz/test.py", line 4, in <module>
    exchange.fetch_open_orders()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bitmart.py", line 2211, in fetch_open_orders
    return self.fetch_orders_by_status('open', symbol, since, limit, params)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bitmart.py", line 2151, in fetch_orders_by_status
    raise ArgumentsRequired(self.id + ' fetchOrdersByStatus() requires a symbol argument')
ccxt.base.errors.ArgumentsRequired: bitmart fetchOrdersByStatus() requires a symbol argument
```
``` 
exchange = ccxt.bitmart()
exchange.fetch_my_trades()
```
``` 
Traceback (most recent call last):
  File "/home/xyz/test.py", line 4, in <module>
    exchange.fetch_my_trades()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bitmart.py", line 1544, in fetch_my_trades
    raise ArgumentsRequired(self.id + ' fetchMyTrades() requires a symbol argument')
ccxt.base.errors.ArgumentsRequired: bitmart fetchMyTrades() requires a symbol argument
```

**Comment by carlosmiei** [comment]
Hello @JovianMoon, thanks for letting us know, we will update it accordingly.
