### ISSUE TITLE
coinbase advanced trade API support?

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#19385]
### Operating System

ubuntu 22

### Programming Languages

python 3.8.10

### CCXT Version

CCXT Version: 4.0.105

### Description

Does ccxt support the Coinbase Advanced Trade API?   I've tried using ccxt.coinbase( ) with API key/secret but unable to retrieve basic information from coinbase account

### Code

```
#!/usr/bin/env python3

import ccxt

coinbase = ccxt.coinbase({
    'apiKey': 'valid_key',
    'secret': 'my_secret',
    'verbose': True
})

coinbase_markets = coinbase.load_markets()
print(coinbase_markets)

```

output:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    coinbase_markets = coinbase.load_markets()
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1443, in load_markets
    currencies = self.fetch_currencies()
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 1083, in fetch_currencies
    response = self.fetch_currencies_from_cache(params)
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 1070, in fetch_currencies_from_cache
    self.options['fetchCurrencies'] = self.extend(options, {
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 934, in extend
    result.update(arg)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

```

**Comment by jtashiro** [comment]
resolved - bad six installation on my system ...
