### ISSUE TITLE
CCXT PRO: OKX Websocket issue in handle_my_trades

### ISSUE THREAD

**Issue by jayburston** [ccxt/ccxt#19390]
### Operating System

Linux

### Programming Languages

PHP

### CCXT Version

4.0.107

### Description

An exception is raised each time a trade is received by the OKX websocket.

On line 1070 in ccxt/php/pro/okx.php (first line in the code snippet shown), the test is using $tradeId, which is a string, and is_empty() seems to want an object.

### Code

```
if (!$this->is_empty($tradeId)) {
        $order = $this->parse_order($rawOrder);
        $filteredOrders[] = $order;
}
```

**Comment by sc0Vu** [comment]
Hi @jayburston

Would like to paster verbose log?

**Comment by jayburston** [comment]
I've actually already patched my fork of CCXT, but this was the exception from the error log:

```
*hostname* [26-Sep-2023 03:22:17 UTC] PHP Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in *path*/vendor/ccxt/ccxt/php/Exchange.php:840
Stack trace:
*hostname* #0 *path*/vendor/ccxt/ccxt/php/Exchange.php(840): count()
*hostname* #1 *path*/vendor/ccxt/ccxt/php/pro/okx.php(1070): ccxt\Exchange::is_empty()
*hostname* #2 *path*/vendor/ccxt/ccxt/php/pro/okx.php(979): ccxt\pro\okx->handle_my_trades()
*hostname* #3 *path*/vendor/ccxt/ccxt/php/pro/okx.php(1481): ccxt\pro\okx->handle_orders()
*hostname* #4 *path*/vendor/ccxt/ccxt/php/pro/Client.php(266): ccxt\pro\okx->handle_message()
*hostname* #5 *path*/vendor/evenement/evenement/src/EventEmitterTrait.php(143): ccxt\pro\Client->on_message()
*hostname* #6 *path*/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit()
*hostname* #7 *path*/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}()
*hostname* #8 *path*/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
*hostname* #9 *path*/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData()
*hostname* #10 *path*/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
*hostname* #11 *path*/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}()
*hostname* #12 *path*/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit()
*hostname* #13 *path*/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData()
*hostname* #14 *path*/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
*hostname* #15 *path*/vendor/react/event-loop/src/Loop.php(55): React\EventLoop\StreamSelectLoop->run()
*hostname* #16 [internal function]: React\EventLoop\Loop::React\EventLoop\{closure}()
*hostname* #17 {main}
*hostname* thrown in *path*/vendor/ccxt/ccxt/php/Exchange.php on line 840
```
