### ISSUE TITLE
fetch_ohlcv failure on BitGet

### ISSUE THREAD

**Issue by svax974** [ccxt/ccxt#19443]
### Operating System

Debian 12 / macOS

### Programming Languages

Python

### CCXT Version

4.1.2 and 4.0.6 tested

### Description

I was simply trying to download a past "1m" candle that I missed between 2 sets on BTC/USDT spot on Bitget and got the error below. I added a print of the response in bitget.py around line 2502 (you'll see RESPONSE=... in the output below).

I tried with a code as simple as :
```
#test.py
exchange = ccxt.bitget()
exchange.apiKey = "XXX"
exchange.secret = "XXX"

candles = exchange.fetch_ohlcv('BTC/USDT', '1m', 1691606819 * 1000, 1)
print('CANDLES From ' + ccFullDate(begin) + ' :')
for candle in candles:
    candle[0] = candle[0]/1000
    print('\t\t@ ' + ccFullDate(candle[0]) + ' - ' + str(candle))
```

The output : 
```
  RESPONSE=b''
Traceback (most recent call last):
  File "/Users/steph/Dev/Projects/Twats/twats_services/./test.py", line 30, in <module>
    getCandles(begin)
  File "/Users/steph/Dev/Projects/Twats/twats_services/./test.py", line 22, in getCandles
    candles = exchange.fetch_ohlcv('BTC/USDT', '1m', begin * 1000, 1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steph/venv-twats/lib/python3.11/site-packages/ccxt/bitget.py", line 2502, in fetch_ohlcv
    data = self.safe_value(response, 'data', response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steph/venv-twats/lib/python3.11/site-packages/ccxt/base/exchange.py", line 748, in safe_value
    return dictionary[key] if Exchange.key_exists(dictionary, key) else default_value
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steph/venv-twats/lib/python3.11/site-packages/ccxt/base/exchange.py", line 680, in key_exists
    value = dictionary[key]
            ~~~~~~~~~~^^^^^
TypeError: byte indices must be integers or slices, not str
```

Any hint ? Thanks !

**Comment by sc0Vu** [comment]
Hi @svax974 

It works for me. Would you like to paste verbose log?

**Comment by svax974** [comment]
Output is quite huge, I put it there : https://file.io/cXUXrio6qoHU

**Comment by carlosmiei** [comment]
@svax974  file seems deleted now, but to avoid a huge output and having to put it in a file you can do this:

```Python
await exchange.load_markets() # pre-load the markets before enabling verbose mode
ohlcv = await bitget.fetch_ohlcv('BTC/USDT', X, Y)
```

**Comment by svax974** [comment]
Ok, great, here it is : 
```

fetch Request: bitget GET https://api.bitget.com/api/spot/v1/market/candles?symbol=BTCUSDT_SPBL&limit=1&period=1min&after=1691606819000&before=1691606879000 RequestHeaders: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitget GET https://api.bitget.com/api/spot/v1/market/candles?symbol=BTCUSDT_SPBL&limit=1&period=1min&after=1691606819000&before=1691606879000 200 ResponseHeaders: {'Date': 'Wed, 04 Oct 2023 10:02:16 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'X-Request-ID': '57fc244a41de43d49fdb5b87050298e2', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=ZEbBYvog0JPQTiyqCn0WwUjAQOMrdFMmUl1.jyBx3RI-1696413736-0-AU3qKU5hcwHoU1VbDsnYKQJ5BEBhlqYQMIOU1LjvB8m30mynJ1j9T1zJa5Kho+9TahpM6IOfH9fIz6zFGY647pA=; path=/; expires=Wed, 04-Oct-23 10:32:16 GMT; domain=.bitget.com; HttpOnly; Secure; SameSite=None, _cfuvid=Iw9M_OBKv8eI9AdQJm0UDixP82cvFeSKf1rltBEauI8-1696413736849-0-604800000; path=/; domain=.bitget.com; HttpOnly; Secure; SameSite=None', 'X-Frame-Options': 'SAMEORIGIN', 'Server': 'cloudflare', 'CF-RAY': '810c969d9d4c0d73-MRS'} ResponseBody: 
RESPONSE=b''
Traceback (most recent call last):
  File "/Users/steph/Dev/Projects/Twats/twats_services/./test.py", line 32, in <module>
    getCandles(begin)
  File "/Users/steph/Dev/Projects/Twats/twats_services/./test.py", line 24, in getCandles
    candles = exchange.fetch_ohlcv('BTC/USDT', '1m', begin * 1000, 1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steph/venv-twats/lib/python3.11/site-packages/ccxt/bitget.py", line 2502, in fetch_ohlcv
    data = self.safe_value(response, 'data', response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steph/venv-twats/lib/python3.11/site-packages/ccxt/base/exchange.py", line 748, in safe_value
    return dictionary[key] if Exchange.key_exists(dictionary, key) else default_value
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steph/venv-twats/lib/python3.11/site-packages/ccxt/base/exchange.py", line 680, in key_exists
    value = dictionary[key]
            ~~~~~~~~~~^^^^^
TypeError: byte indices must be integers or slices, not str
```

**Comment by carlosmiei** [comment]
@svax974 Are you using the sync `import ccxt` or the async `import ccxt.async_support` of ccxt?

**Comment by svax974** [comment]
Sync version

**Comment by carlosmiei** [comment]
@svax974 Ok I know what the problem is now, thanks for letting us know, will fix it asap.

**Comment by svax974** [comment]
Ok, thanks too :)
