### ISSUE TITLE
kraken.js TypeError on parseOrder resolving 'trades' attribute in safeOrder

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#19447]
### Operating System

Debian (Docker)

### Programming Languages

JavaScript

### CCXT Version

4.1.2

### Description

We found a bug that throws a error from `parseOrder` when safeOrder resolves `trades` parameter value.
Here is a error stack trace (xxxxxxx-xxxxxxx-xxxxxxxx -> trade id):
```
TypeError: Cannot use 'in' operator to search for 'info' in xxxxxxx-xxxxxxx-xxxxxxxx
	at kraken.safeOrder (/var/www/project/corejs/node_modules/ccxt/dist/cjs/src/base/Exchange.js:1673:76)
	at kraken.parseOrder (/var/www/project/corejs/node_modules/ccxt/dist/cjs/src/kraken.js:1458:21)
	at kraken.fetchOrder (/var/www/project/corejs/node_modules/ccxt/dist/cjs/src/kraken.js:1677:28)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code

We found a solution to get through this bug and here is our `parseOrder` code shortcut, maybe that helps to eliminate this issue:
```
parseOrder(order, market = undefined) {
        ......
        const clientOrderId = this.safeString(order, 'userref');
        const rawTrades = this.safeValue(order, 'trades');

        // #### OUR SOLUTION
        let trades = [];
        if (Array.isArray(rawTrades)) {
            for (const rawTrade of rawTrades) {
                if (typeof rawTrade === 'string') {
                    // rawTrade === trade id
                    trades.push({'info': {}, 'id': rawTrade});
                }
                else {
                    trades.push(rawTrade);
                }
            }
        }
        else {
            trades = rawTrades;
        }
        // #### OUR SOLUTION END

        stopPrice = this.safeNumber(order, 'stopprice', stopPrice);
        return this.safeOrder({
            'id': id,
            'clientOrderId': clientOrderId,
            'info': order,
            'timestamp': timestamp,
            'datetime': this.iso8601(timestamp),
            'lastTradeTimestamp': undefined,
            'status': status,
            'symbol': symbol,
            'type': type,
            'timeInForce': undefined,
            'postOnly': isPostOnly,
            'side': side,
            'price': price,
            'stopPrice': stopPrice,
            'triggerPrice': stopPrice,
            'cost': undefined,
            'amount': amount,
            'filled': filled,
            'average': average,
            'remaining': undefined,
            'fee': fee,
            'trades': trades, // before:  'trades': rawTrades
        }, market);
    }
```

**Comment by carlosmiei** [comment]
Hello @wunderb1t, thanks for letting us know. what's the best way to reproduce this issue?

**Comment by wunderb1t** [comment]
Hi @carlosmiei, 
we catch it by using `fetchOrder` method after creating market order using `createOrder` method

**Comment by carlosmiei** [comment]
@wunderb1t Thanks, do you know if it happens every time? Can't reproduce it locally yet

```
 p kraken fetchOrder "ODJ74I-LJ5EA-EOILG4" 
Python v3.11.5
CCXT v4.1.2
kraken.fetchOrder(ODJ74I-LJ5EA-EOILG4)
{'amount': 0.1,
 'average': 64.26487,
 'clientOrderId': '0',
 'cost': 6.426487,
 'datetime': '2023-10-04T13:29:00.055Z',
 'fee': {'cost': 0.016709, 'currency': 'USDT', 'rate': None},
 'fees': [{'cost': 0.016709, 'currency': 'USDT', 'rate': None}],
 'filled': 0.1,
 'id': 'ODJ74I-LJ5EA-EOILG4',
 'info': {'closetm': '1696426140.0586374',
          'cost': '6.426487',
          'descr': {'close': '',
                    'leverage': 'none',
                    'order': 'buy 0.10000000 LTCUSDT @ market',
                    'ordertype': 'market',
                    'pair': 'LTCUSDT',
                    'price': '0',
                    'price2': '0',
                    'type': 'buy'},
          'expiretm': '0',
          'fee': '0.016709',
          'id': 'ODJ74I-LJ5EA-EOILG4',
          'limitprice': '0.000000',
          'misc': '',
          'oflags': 'fciq',
          'opentm': '1696426140.05551',
          'price': '64.26487',
          'reason': None,
          'refid': None,
          'starttm': '0',
          'status': 'closed',
          'stopprice': '0.000000',
          'trades': ['TF5EVQ-JKTES-2ND2XF'],
          'userref': '0',
          'vol': '0.10000000',
          'vol_exec': '0.10000000'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': False,
 'price': 64.26487,
 'reduceOnly': None,
 'remaining': 0.0,
 'side': 'buy',
 'status': 'closed',
 'stopLossPrice': None,
 'stopPrice': 0.0,
 'symbol': 'LTC/USDT',
 'takeProfitPrice': None,
 'timeInForce': 'IOC',
 'timestamp': 1696426140055,
 'trades': [{'amount': None,
             'cost': None,
             'datetime': None,
             'fee': {'cost': None},
             'fees': [],
             'id': 'TF5EVQ-JKTES-2ND2XF',
             'info': 'TF5EVQ-JKTES-2ND2XF',
             'order': None,
             'price': None,
             'side': None,
             'symbol': 'LTC/USDT',
             'takerOrMaker': None,
             'timestamp': None,
             'type': None}],
 'triggerPrice': 0.0,
 'type': 'market'}
```
