### ISSUE TITLE
Why does the following code produce this error?

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#19478]
### Operating System

Ubuuntu 18.04

### Programming Languages

Python

### CCXT Version

Version: 4.1.4

### Description

the code shows errors as follows:
Traceback (most recent call last):
  File "roboot5.py", line 24, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "roboot5.py", line 16, in main
    order = await lbank.createOrder(symbol, 'market', 'buy', amount, price)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/lbank.py", line 591, in create_order
    response = self.privatePostCreateOrder(self.extend(order, params))
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 3068, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 3065, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 654, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/lbank.py", line 833, in handle_errors
    raise ErrorClass(message)
ccxt.base.errors.AuthenticationError: Invalid signature

### Code

```
  import ccxt
import time
from pprint import pprint
async def main():
    lbank = ccxt.lbank({
        'apiKey':'my_apikey',
        'secret':'my_secret',
        'enableRateLimit': True,
    })
    b = 0
    amount = 4
    price = 0.56
    symbol = 'XRP/USDT'
    order = await lbank.createOrder(symbol, 'market', 'buy', amount, price)
    order = lbank.fetch_order(order['id'], order['symbol'])
    order_status = order['status']
    while b == 0:
        order = lbank.fetch_order(order['id'], order['symbol'])
        order_status = order['status']
        print("Order status:", order_status)
        time.sleep(1)
asyncio.run(main())

```

**Comment by AdolfoVillalobos** [comment]
Hi! Just asking in order to discard the most obvious/likely reason: Are you actually passing the strings "mi_apikey" and "my_secret" as apikey/secrets? Or are those values chosen only for illustration purposes?.  

If you are using those strings, you might consider running the code with actual api keys and secrets obtained from the exchange and see if the error still persists.  

PD: do not share or commit those new api pairs

**Comment by carlotestor** [comment]
`AuthenticationError: Invalid signature` from LBank is a credentials/format issue, not a bug in the call. Two things commonly cause it:

**1. Key/secret type mismatch.** LBank issues either HmacSHA256 or **RSA** keys, and CCXT picks the signing method from the secret's length (RSA if longer than 32 chars). If you generated an RSA key pair, the `secret` must be the full RSA **private key** body — pasting a truncated copy, or leaving the `-----BEGIN...-----` header/newlines in, breaks the signature. Paste the raw base64 body only.

**2. Mixing sync and async.** Your traceback shows `await lbank.createOrder(...)` landing in `ccxt/lbank.py` (the **sync** module) — you imported `import ccxt` but are awaiting. Use the async module:

```python
import ccxt.async_support as ccxt

async def main():
    lbank = ccxt.lbank({'apiKey': API_KEY, 'secret': SECRET})
    try:
        order = await lbank.create_order(symbol, 'market', 'buy', amount)
        print(order)
    finally:
        await lbank.close()
```

Also worth checking, as @AdolfoVillalobos noted: confirm you're passing real credentials rather than the placeholder strings, and that the key is enabled for trading with your IP whitelisted. Please don't post real keys here — rotate them if any leaked.
