### ISSUE TITLE
why show this error?

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#19490]
### Operating System

Ubuntu 18.04 

### Programming Languages

Python

### CCXT Version

Version: 4.1.4 

### Description

It shows the error when i run the code,the error as follows:
Traceback (most recent call last):
File "roboot5.py", line 12, in <module>
order = btcalpha.createOrder(symbol, 'market', 'buy', amount)
File "/usr/local/lib/python3.7/dist-packages/ccxt/btcalpha.py", line 710, in create_order
'price': self.price_to_precision(symbol, price),
File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 3654, in price_to_precision
result = self.decimal_to_precision(price, ROUND, market['precision']['price'], self.precisionMode, self.paddingMode)
File "/usr/local/lib/python3.7/dist-packages/ccxt/base/decimal_to_precision.py", line 58, in decimal_to_precision
dec = decimal.Decimal(str(n)) 
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

The code as follows:

### Code

```
import ccxt
import time
from pprint import pprint

btcalpha = ccxt.btcalpha({
'apiKey': 'my_apikey',
'secret': 'my_secret',
})
b = 0
amount = 4
symbol = 'XRP/USDT'
order = btcalpha.createOrder(symbol, 'market', 'buy', amount)
order = btcalpha.fetch_order(order['id'], order['symbol'])
order_status = order['status']
print("Order status:", order_status)
while b == 0:
  order = btcalpha.fetch_order(order['id'], order['symbol'])
  order_status = order['status']
  print("Order status:", order_status)
  time.sleep(1)

```

**Comment by carlosmiei** [comment]
Hello @qwe231cvb, I will take a look and revert asap.

**Comment by carlosmiei** [comment]
@qwe231cvb BTCAlpha only allows limit orders through the API, so there's nothing ccxt can do about it. Nonetheless, I will add a warning to make things a bit more clear. Thanks for reporting it.
