### ISSUE TITLE
watch_trades broken on kraken futures

### ISSUE THREAD

**Issue by mrpouley** [ccxt/ccxt#19559]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.1.11

### Code

```python
import ccxt.pro as ccxt
import asyncio

kraken = ccxt.krakenfutures({"verbose": True})


asyncio.run(kraken.watch_trades("BTC/USD:USD"))
  

```

```
Traceback (most recent call last):
  File "/home/mrpouley/tmp/krakenfutures.py", line 7, in <module>
    asyncio.run(kraken.watch_trades("BTC/USD:USD"))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mrpouley/.local/lib/python3.11/site-packages/ccxt/pro/krakenfutures.py", line 177, in watch_trades
    trades = await self.subscribe_public(name, [symbol], params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrpouley/.local/lib/python3.11/site-packages/ccxt/pro/krakenfutures.py", line 114, in subscribe_public
    return await self.watch(url, messageHash, request, messageHash)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrpouley/.local/lib/python3.11/site-packages/ccxt/async_support/base/ws/fast_client.py", line 27, in handler
    self.handle_message(message)
  File "/home/mrpouley/.local/lib/python3.11/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/home/mrpouley/.local/lib/python3.11/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/home/mrpouley/.local/lib/python3.11/site-packages/ccxt/pro/krakenfutures.py", line 1219, in handle_message
    return method(client, message)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrpouley/.local/lib/python3.11/site-packages/ccxt/pro/krakenfutures.py", line 299, in handle_trade
    market = self.market(marketId)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrpouley/.local/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 2442, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: krakenfutures does not have market symbol pf_xbtusd
```

**Comment by bmolodan** [comment]
I have the same issue

**Comment by carlosmiei** [comment]
Hello @bmolodan, thanks for letting us know, we will check it asap.

**Comment by bmolodan** [comment]
Hello. First of all, thanks for your support!

I get your branch, but it's still not working for me.
Maybe I'm doing something wrong?

**package.json**
``` js
  "dependencies": {
    "ccxt": "github:carlosmiei/ccxt#krakenfutures-watchTrades"
  }
```
 **js**
``` js
const ccxt = require("ccxt")\
console.log(ccxt.version)

async function main() {
    const exchange = new ccxt.pro['krakenfutures']({ 'newUpdates': true })
    await exchange.loadMarkets()
    console.log(JSON.stringify(exchange.symbols))
    const symbol = 'BTC/USD:USD'
    console.log(exchange.markets[symbol])
    const trades = await exchange.watchTrades(symbol)
    console.log(trades)
}

main()
```

```
BadSymbol: krakenfutures does not have market symbol pf_xbtusd
    at krakenfutures.market (/Users/julfy/Desktop/bot/test/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3384:15)
    at krakenfutures.handleTrade (/Users/julfy/Desktop/bot/test/node_modules/ccxt/dist/cjs/src/pro/krakenfutures.js:320:33)
    at krakenfutures.handleMessage (/Users/julfy/Desktop/bot/test/node_modules/ccxt/dist/cjs/src/pro/krakenfutures.js:1281:31)
    at WsClient.onMessage (/Users/julfy/Desktop/bot/test/node_modules/ccxt/dist/cjs/src/base/ws/Client.js:288:18)
    at callListener (/Users/julfy/Desktop/bot/test/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/Users/julfy/Desktop/bot/test/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:511:28)
    at Receiver.receiverOnMessage (/Users/julfy/Desktop/bot/test/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:511:28)
    at Receiver.dataMessage (/Users/julfy/Desktop/bot/test/node_modules/ws/lib/receiver.js:560:14)
```
