### ISSUE TITLE
coinone order parsing error: string indices must be integers

### ISSUE THREAD

**Issue by devshjeon** [ccxt/ccxt#19596]
### Operating System

macOS Sonoma 14.0

### Programming Languages

Python

### CCXT Version

4.1.14

### Description

The response data after calling the create_order API is as follows.
```
{
  "result": "success",
  "errorCode": "0",
  "orderId": "8a82c561-40b4-4cb3-9bc0-9ac9ffc1d63b"
}
```
An error occurs while processing this data in parse_order.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ccxt/coinone.py", line 509, in create_order
    return self.parse_order(response, market)
  File "/usr/local/lib/python3.10/site-packages/ccxt/coinone.py", line 607, in parse_order
    base = self.safe_currency_code(baseId, market['base'])
  File "/usr/local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3793, in safe_currency_code
    return currency['code']
TypeError: string indices must be integers
```

I think that the first condition is executed in safe_currency and the str type currency is returned, and an error occurs when trying to access the code property in safe_currency_code.

coinone.py
```
def parse_order(self, order, market=None):
...
  id = self.safe_string(order, 'orderId')
  baseId = self.safe_string(order, 'baseCurrency')
  quoteId = self.safe_string(order, 'targetCurrency')
  base = self.safe_currency_code(baseId, market['base'])
  quote = self.safe_currency_code(quoteId, market['quote'])
```

exchange.py
```
def safe_currency_code(self, currencyId: Optional[str], currency: Optional[Any] = None):
    currency = self.safe_currency(currencyId, currency)
    return currency['code']

...

def safe_currency(self, currencyId: Optional[str], currency: Optional[Any] = None):
  if (currencyId is None) and (currency is not None):
      return currency
  if (self.currencies_by_id is not None) and (currencyId in self.currencies_by_id) and (self.currencies_by_id[currencyId] is not None):
      return self.currencies_by_id[currencyId]
  code = currencyId
  if currencyId is not None:
      code = self.common_currency_code(currencyId.upper())
  return {
      'id': currencyId,
      'code': code,
  }
```

**Comment by carlosmiei** [comment]
Hello @devshjeon,
We will take a look asap, thanks for letting us know.

**Comment by devshjeon** [comment]
I confirmed that the transpiler is working.

thank you

**Comment by carlosmiei** [comment]
@devshjeon Yeah both the Python and PHP versions derive from the Typescript file 🙂
