### ISSUE TITLE
Try catch doesn't work for watchOrderBookForSymbols. The socket was closed while data was being compressed.

### ISSUE THREAD

**Issue by suenot** [ccxt/ccxt#19614]
### Operating System

macOs Ventura 13.0.1

### Programming Languages

JavaScript

### CCXT Version

4.1.2

### Description

App crashed in watchOrderBookForSymbols() after 24 hours of work. Try catch doesn't work.

### Code

My code:
```
export const parseOrderBooksOne = async ({exchangeId, pairIds}: {exchangeId: string, pairIds: string[]}) => {
  const exchangeInstance = new (ccxt.pro as any)[exchangeId]({});
  if (exchangeId in ccxt.pro) {
    while (true) {
      try {
        const orderBookCcxt: CcxtOrderBookSubscription = await exchangeInstance.watchOrderBookForSymbols(pairIds);
        const orderBook = orderBookCcxtToCore({orderBookCcxt, exchangeId});
        upsertOrderBoook(orderBook);
      } catch (e) { log(e) };
    }
  }
}
```

Error:
```
Error: The socket was closed while data was being compressed
    at /root/suenot/intuition7/node_modules/ccxt/node_modules/ws/lib/sender.js:409:21
    at /root/suenot/intuition7/node_modules/ccxt/node_modules/ws/lib/permessage-deflate.js:326:9
    at /root/suenot/intuition7/node_modules/ccxt/node_modules/ws/lib/permessage-deflate.js:458:7
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)
    at Zlib.cb (node:internal/streams/transform:190:7)
    at Zlib.processCallback (node:zlib:613:8)
```

**Comment by carlosmiei** [comment]
Hello @suenot,
Thanks for reporting it, this issue does not seem specific to `watchOrderBookForSymbols` but to all ws methods, when an exception is thrown by the WS library. Not sure yet the best way to catch this error but we will take a look and report back.
