### ISSUE TITLE
Bitfinex fetchTransactions hmac encoding problem

### ISSUE THREAD

**Issue by d-makhlin** [ccxt/ccxt#19703]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.0.3

### Description

When I try to fetch transactions for bitfinex it gets an error with hmac encoding

### Code

```
Traceback (most recent call last):
  File "./exchanges.py", line 779, in __fetch_by_transactions
    txs = conn.fetchTransactions(code=ccy, since=since)
  File "/usr/local/lib/python3.7/site-packages/ccxt/bitfinex.py", line 1334, in fetch_transactions
    response = self.privatePostHistoryMovements(self.extend(query, params))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 2990, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 2986, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/bitfinex.py", line 1537, in sign
    signature = self.hmac(payload, secret, hashlib.sha384)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1228, in hmac
    h = hmac.new(secret, request, algorithm)
  File "/usr/local/lib/python3.7/hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/lib/python3.7/hmac.py", line 93, in __init__
    self.update(msg)
  File "/usr/local/lib/python3.7/hmac.py", line 102, in update
    self.inner.update(msg)
TypeError: Unicode-objects must be encoded before hashing  

```

**Comment by sc0Vu** [comment]
Hi @d-makhlin 

It works for me (4.1.9), but didn't work in 4.0.3. Please upgrade ccxt.
