### ISSUE TITLE
Waves.Exchange fetch_balances() NameError: name 'axolotl' is not defined

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#19741]
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.1.32

### Description

`fetch_balances` and other methods using signatures are throwing an error.

### Code

``` 
exchange = ccxt.wavesexchange({...})
exchange.fetch_balance()
```
``` 
Traceback (most recent call last):
  File "/home/xyz/test.py", line 4, in <module>
    exchange.fetch_balance()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/wavesexchange.py", line 1830, in fetch_balance
    signature = axolotl(self.binary_to_base16(binary), hexSecret, 'ed25519')
NameError: name 'axolotl' is not defined
```

**Comment by carlosmiei** [comment]
Hello @JovianMoon, 
thanks for letting us know, we will take a look asap.
