### ISSUE TITLE
 kucoin and kucoinfutures token expired

### ISSUE THREAD

**Issue by mrpouley** [ccxt/ccxt#19749]
Hello,

Unfortunately the problem is still there with version 4.1.18. Both kucoin and kucoinfutures exchange classes are impacted (other exchanges are fine).

I have hard time reproducing it locally since it happens so rarely. On my production server though the issue arises every three or four days, forcing me to restart the program.

_Originally posted by @mrpouley in https://github.com/ccxt/ccxt/issues/18872#issuecomment-1778443284_

**Comment by sc0Vu** [comment]
Hi @mrpouley 

Based on the log in previous issue, it looks like exchange used the cached expired token, we used the same token after expired error. I'm not sure what's the expiration for token.

Before we push updates for this, would you like to reset urls when catch the error?

Cached like this
```PYTHON3
// connectId public or private
urls[connectId] = self.spawn(self.negotiate_helper, privateChannel, params)
self.options['urls'] = urls
```

**Comment by ytang2718** [comment]
hi @sc0Vu this problem persists as of dec 20, 2023

**Comment by respectabiggle** [comment]
Confirming, still happening Dec 21 @sc0Vu

**Comment by sc0Vu** [comment]
Hi @respectabiggle,

Do you have any idea about the expiration time for the token? Not sure what's the expiration of the token.

BTW, I think we probably need to refresh the token if 401 error happened, or implement refresh mechanism based on timeout.

**Comment by respectabiggle** [comment]
@sc0Vu no mate, I don't.  It _seems_ like anywhere between 1-3 days for me, but I'm not sure.

I brought it up in the Discord, and mod there said they'd take a look at it.  Thanks for reopening the issue.

PS if you work out a workaround, would love to take a look.

**Comment by WillPCowan** [comment]
@sc0Vu I have observed this issue again haha, unfortunately do not have verbose logs:

```
2024-09-10 12:18:15,586 ERRO [lib.integrations.base.base_trading_streamer] - Stream error: on 'KUCOIN-MM-2 - Balance Streamer' kucoin token is expired
Traceback (most recent call last):
  File "/home/ubuntu/myproject/lib/integrations/base/base_trading_streamer.py", line 133, in _stream_with_sync_handler
    data = await watch_func()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myproject/lib/integrations/base/base_trading_streamer.py", line 82, in watch_without_timeout
    return await self.watch_function()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myproject/.venv/lib/python3.11/site-packages/ccxt/pro/kucoin.py", line 998, in watch_balance
    return await self.subscribe(url, messageHash, topic, self.extend(request, params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myproject/.venv/lib/python3.11/site-packages/ccxt/pro/kucoin.py", line 135, in subscribe
    return await self.watch(url, messageHash, message, subscriptionHash, subscription)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myproject/.venv/lib/python3.11/site-packages/ccxt/async_support/base/ws/fast_client.py", line 26, in handler
    self.handle_message(message)
  File "/home/ubuntu/myproject/.venv/lib/python3.11/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 34, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/home/ubuntu/myproject/.venv/lib/python3.11/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 29, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/home/ubuntu/myproject/.venv/lib/python3.11/site-packages/ccxt/pro/kucoin.py", line 1133, in handle_message
    method(client, message)
  File "/home/ubuntu/myproject/.venv/lib/python3.11/site-packages/ccxt/pro/kucoin.py", line 1119, in handle_error_message
    self.handle_errors(None, None, client.url, None, None, data, message, None, None)
  File "/home/ubuntu/myproject/.venv/lib/python3.11/site-packages/ccxt/async_support/kucoin.py", line 4515, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/ubuntu/myproject/.venv/lib/python3.11/site-packages/ccxt/base/exchange.py", line 4122, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: kucoin token is expired
```

I've not seen this for a long time. On version `4.3.40`.

**Comment by carlosmiei** [comment]
@WillPCowan thanks for reporting it again, we will take a look. cc/ @sc0Vu
