### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by zacra** [ccxt/ccxt#19859]
### Operating System

amazon linux 2

### Programming Languages

Python

### CCXT Version

From version 4.1.37 to the latest version

### Description

Traceback (most recent call last):
  File "/var/autobot/Binance_BTC_DOM_Bot.py", line 1, in <module>
    import ccxt
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 33, in <module>
    from ccxt.base.types import Balance, IndexType, OrderSide, OrderType, Trade, OrderRequest
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/types.py", line 73, in <module>
    class Position(TypedDict):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/types.py", line 100, in Position
    info: Dict[str, any]
TypeError: 'type' object is not subscriptable

The above error occurs. What should I do?

import ccxt
An error occurs from this first line.

### Code

```
  import ccxt

```

**Comment by carlosmiei** [comment]
Hello @zacra, what's your python version?

**Comment by carlosmiei** [comment]
@zacra Also is it possible to share a snippet with us that could help debug the issue?

**Comment by carlosmiei** [comment]
Ok I managed to reproduce the issue. It only happens when python version <= 3.7.  As a workaround, you can update your python version but we will try to fix it asap.

**Comment by zacra** [comment]
thanks :)
