### ISSUE TITLE
after updating from 4.1.39 to version ccxt 4.1.50 an error appears (in 4.1.39 everything works fine)

### ISSUE THREAD

**Issue by 89d55d5288** [ccxt/ccxt#19943]
### Operating System

Debian, Windows

### Programming Languages

Python

### CCXT Version

4.1.50

### Description

new problem
after updating from 4.1.39 to version ccxt 4.1.50 an error appears (in 4.1.39 everything works fine):
Future exception was never retrieved
future: <Future finished exception=DDoSProtection('binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}')>
Traceback (most recent call last):
File "/home//.local/lib/python3.12/site-packages/ccxt/pro/binance.py", line 2218, in load_positions_snapshot
positions = await self.fetch_positions(None, {'type': type})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7242, in fetch_positions
return await self.fetch_positions_risk(symbols, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7294, in fetch_positions_risk
await self.load_leverage_brackets(False, params)
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 6968, in load_leverage_brackets
response = await getattr(self, method)(query)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 8029, in request
response = await self.fetch2(path, api, method, params, headers, body, config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 1984, in fetch2
return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 220, in fetch
self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7989, in handle_errors
raise DDoSProtection(self.id + ' ' + body)
ccxt.base.errors.DDoSProtection: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @89d55d5288 

It works for me.

The error response was {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}. Can check whether the permission is set for the api key?

**Comment by zixiaozhihui** [comment]
num = 5  # 每个批量最多下单的数量
    all_order_info = []
    for i in range(0, len(symbol_order_params), num):
        order_list = symbol_order_params[i:i + num]
        params = {'batchOrders': exchange.json(order_list),
                  'timestamp': int(time.time() * 1000)}
        print(params)
        order_info = retry_wrapper(exchange.fapiPrivatePostBatchOrders, params=params, act_name='批量下单')
        all_order_info += order_info
        time.sleep(short_sleep_time)
    return all_order_info

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 613, in fetch
    response.raise_for_status()
  File "C:\ProgramData\anaconda3\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/batchOrders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\lianghua\zeshicelue\Functions.py", line 57, in retry_wrapper
    result = func(params=params)
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\base\types.py", line 28, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\binance.py", line 8028, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3195, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 629, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\binance.py", line 7997, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3570, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1130,"msg":"Data sent for parameter 'batchorders:\"[{\\\"symbol\\\":\\\"SOLUSDT\\\",\\\"side\\\":\\\"BUY\\\",\\\"price\\\":\\\"56.37\\\",\\\"type\\\":\\\"LIMIT\\\",\\\"timeInForce\\\":\\\"GTC\\\",\\\"quantity\\\":\\\"1.0\\\"},{\\\"symbol\\\":\\\"WAVESUSDT\\\",\\\"side\\\":\\\"BUY\\\",\\\"price\\\":\\\"2.2511\\\",\\\"type\\\":\\\"LIMIT\\\",\\\"timeInForce\\\":\\\"GTC\\\",\\\"quantity\\\":\\\"21.7\\\"}]\"' is not valid."}
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 613, in fetch
    response.raise_for_status()
  File "C:\ProgramData\anaconda3\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/batchOrders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\lianghua\zeshicelue\Functions.py", line 57, in retry_wrapper
    result = func(params=params)
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\base\types.py", line 28, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\binance.py", line 8028, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3195, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 629, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\binance.py", line 7997, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\ProgramData\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3570, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1130,"msg":"Data sent for parameter 'batchorders:\"\\\"[{\\\\\\\"symbol\\\\\\\":\\\\\\\"SOLUSDT\\\\\\\",\\\\\\\"side\\\\\\\":\\\\\\\"BUY\\\\\\\",\\\\\\\"price\\\\\\\":\\\\\\\"56.37\\\\\\\",\\\\\\\"type\\\\\\\":\\\\\\\"LIMIT\\\\\\\",\\\\\\\"timeInForce\\\\\\\":\\\\\\\"GTC\\\\\\\",\\\\\\\"quantity\\\\\\\":\\\\\\\"1.0\\\\\\\"},{\\\\\\\"symbol\\\\\\\":\\\\\\\"WAVESUSDT\\\\\\\",\\\\\\\"side\\\\\\\":\\\\\\\"BUY\\\\\\\",\\\\\\\"price\\\\\\\":\\\\\\\"2.2511\\\\\\\",\\\\\\\"type\\\\\\\":\\\\\\\"LIMIT\\\\\\\",\\\\\\\"timeInForce\\\\\\\":\\\\\\\"GTC\\\\\\\",\\\\\\\"quantity\\\\\\\":\\\\\\\"21.7\\\\\\\"}]\\\"\"' is not valid."}
批量下单 报错，报错内容：程序暂停（秒）： 3

**Comment by zixiaozhihui** [comment]
def cal_order_params(signal_type, symbol, symbol_info):
    """
    针对某个类型订单，计算下单参数。供cal_all_order_info函数调用
    :param signal_type:
    :param symbol:
    :param symbol_info:
    :param symbol_config_df:
    :return:
    """
    if signal_type == 'BUY':
        price = round(symbol_info.at[symbol, '当前价格'] * 1.02, symbol_info.at[symbol, '最小下单价精度'])
    else:
        price = round(symbol_info.at[symbol, '当前价格'] * 0.98, symbol_info.at[symbol, '最小下单价精度'])
    # 计算下单量
    quantity = abs(symbol_info.at[symbol, 'open_coin_num'])

    params = {
        'symbol': symbol,
        'side': signal_type,
        'price': price,
        'type': 'LIMIT',
        'timeInForce': 'GTC',
        'quantity': quantity,
    }

    return params


@cal_time
def place_binance_batch_order(exchange, symbol_order_params):
    """
    批量下单
    :param exchange:
    :param symbol_order_params:
    :return:
    """
    num = 5  # 每个批量最多下单的数量
    all_order_info = []
    for i in range(0, len(symbol_order_params), num):
        order_list = symbol_order_params[i:i + num]
        params = {'batchOrders': exchange.json(order_list),
                  'timestamp': int(time.time() * 1000)}
        print(params)
        order_info = retry_wrapper(exchange.fapiPrivatePostBatchOrders, params=params, act_name='批量下单')
        all_order_info += order_info
        time.sleep(short_sleep_time)
    return all_order_info

**Comment by 89d55d5288** [comment]
> Привет@89d55d5288
> 
> Меня устраивает.
> 
> Ответ об ошибке: {"code":-2015, "msg":"Неверный ключ API, IP-адрес или разрешения на действие"}. Можно ли проверить, установлено ли разрешение для ключа API?

Hi [sc0Vu](https://github.com/sc0Vu)
All permissions are installed and working.
In version 4.1.39 everything works fine.

**Comment by zixiaozhihui** [comment]
邮件已收到! 谢谢合作！我们会尽快给你回复！
