### ISSUE TITLE
bitmart - odd error handling in some cases

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#19941]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.1.50

### Description

Trying to post an order with an account that's not verified advanced get's odd error-handling by ccxt:

```

fetch Request: bitmart POST https://api-cloud.bitmart.com/spot/v2/submit_order RequestHeaders: {'X-BM-KEY': 'xxx', 'X-BM-TIMESTAMP': '1699896531951', 'X-BM-BROKER-ID': 'CCXTxBitmart000', 'Content-Type': 'application/json', 'X-BM-SIGN': 'xxx', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"ETH_USDT","side":"buy","type":"market","notional":"17"}

fetch Response: bitmart POST https://api-cloud.bitmart.com/spot/v2/submit_order 403 ResponseHeaders: {'Date': 'Mon, 13 Nov 2023 17:28:52 GMT', 'Content-Type': 'text/plain;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-BM-RateLimit-Limit': '60', 'X-BM-RateLimit-Remaining': '1', 'X-BM-RateLimit-Reset': '2', 'cache-control': 'no-store', 'Pragma': 'no-cache', 'X-Frame-Options': 'SAMEORIGIN', 'Via': '1.1 google', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=xxx-1699896532-0-AR/GoOitJ60GmgLFCxdAgyy9xl+xxx/sr/K2V7x38NCdbnp4f1Y=; path=/; expires=Mon, 13-Nov-23 17:58:52 GMT; domain=.bitmart.com; HttpOnly; Secure; SameSite=None, _cfuvid=xx-1699896532269-0-604800000; path=/; domain=.bitmart.com; HttpOnly; Secure; SameSite=None', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=xx%2FYcCwMCqOaTbGDyVf%xx%2FeChziinJipfaqVuWyvqxOFNJS9fZPil9Lw%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Server': 'cloudflare', 'CF-RAY': '8258bbccb8016d77-MUC', 'Content-Encoding': 'gzip'} ResponseBody: {"message":"Please complete your personal verification(Advanced).","code":53007,"trace":"6591fc7b508845359d5fa442e3b3a4fb.52.16998965321206647","data":{}}



Traceback (most recent call last):
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py", line 613, in fetch
    self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api-cloud.bitmart.com/spot/v2/submit_order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1149040/2637682716.py", line 2, in <module>
    o = ct.create_order('ETH/USDT', 'market', 'buy', 0.01, 1700)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/bitmart.py", line 2090, in create_order
    notional = self.parse_number(Precise.string_mul(amountString, priceString))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/types.py", line 28, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3198, in request
    def build_ohlcvc(self, trades: List[Trade], timeframe: str = '1m', since: float = 0, limit: float = 2147483647):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3195, in fetch2
    self.accountsById = self.index_by(self.accounts, 'id')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py", line 629, in fetch
    details = ' '.join([self.id, method, url])
                                  ^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/bitmart.py", line 3980, in handle_errors
ccxt.base.errors.ExchangeError: bitmart {"message":"Please complete your personal verification(Advanced).","code":53007,"trace":"6591fc7b508845359d5fa442e3b3a4fb.52.16998965321206647","data":{}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2105, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1428, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1319, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1172, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1087, in format_exception_as_a_whole
    frames.append(self.format_record(record))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/IPython/core/ultratb.py", line 969, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
    ^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/IPython/core/ultratb.py", line 792, in lines
    return self._sd.lines
           ^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/stack_data/core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
                             ^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/stack_data/core.py", line 660, in executing_piece
    return only(
           ^^^^^
  File "/home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/executing/executing.py", line 190, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

```

The message is quite clear - `"message":"Please complete your personal verification(Advanced).","code":53007,` - but the actual exception parsing seems to do ... "whatever".
Oddly, it works fine with a RO key, which simply gets "this key is not allowed to do this".

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @xmatthias, thanks for reporting it I think we're missing this specific error in the exception map, will add it asap.
