### ISSUE TITLE
Signature for this request is not valid 

### ISSUE THREAD

**Issue by moerben2021** [ccxt/ccxt#19966]
### Operating System

Windows

### CCXT Version

4.1.51

### Description

When deleting an order, using fapiPrivateDeleteOrder effectively completes the order deletion. However, when attempting to delete orders in bulk using cancelOrders or fapiPrivateDeleteBatchOrders, the error ccxt.base.errors.AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."} is returned

### Code

```
orders = exchange.fapiPrivateGetOpenOrders({
            'symbol': self.symbol,
            'timestamp': timestamp
        })
order_id_list = [d['orderId'] for d in orders ] 

# can work
for order_id in order_id_list:
                cancel_order = exchange.fapiPrivateDeleteOrder({
                    'symbol': self.symbol,
                    'orderId': order_id,
                    'timestamp': timestamp
                })
                print(f'delete order: {order_id} success！')

#2  Signature for this request is not valid 
cancel_orers = exchange.cancelOrders(order_id_list, symbol = self.symbol)

#3 Signature for this request is not valid 
cancel_order = exchange.fapiPrivateDeleteBatchOrders({
                 'symbol': self.symbol,
                 'orderIdList': order_id_list,
                'timestamp': timestamp
        })

```

**Comment by carlosmiei** [comment]
Hello @moerben2021, thanks for letting us know, we will check it and revert.

**Comment by carlosmiei** [comment]
@moerben2021 Locally I can't reproduce the issue, do you mind sharing a verbose log?

```
Python v3.11.5
CCXT v4.1.52
binanceusdm.cancelOrders(['653277220'],LTC/USDT:USDT)

fetch Request: binanceusdm DELETE https://testnet.binancefuture.com/fapi/v1/batchOrders?timestamp=1700043133951&symbol=LTCUSDT&recvWindow=10000&orderidlist=[653277220]&origclientorderidlist=[]&signature=500ed699c4f7cc163c33197dab0bbfc28399724f49a0485016e502d3655fa850 RequestHeaders: {'X-MBX-APIKEY': '227719da8d8499e8d3461587d19f259c0b39c2b462a77c9b748a6119abd74401', 'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: binanceusdm DELETE https://testnet.binancefuture.com/fapi/v1/batchOrders?timestamp=1700043133951&symbol=LTCUSDT&recvWindow=10000&orderidlist=[653277220]&origclientorderidlist=[]&signature=500ed699c4f7cc163c33197dab0bbfc28399724f49a0485016e502d3655fa850 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Wed, 15 Nov 2023 10:12:14 GMT', 'Server': 'Bengine', 'Vary': 'Accept-Encoding', 'x-mbx-used-weight-1m': '17', 'x-response-time': '47ms', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 a7a209acee14726bdc56f2b8600564e0.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'LHR3-C2', 'X-Amz-Cf-Id': 'jU4crUkuicDiFuglgRJYADUYcz6uTnErKLJ-b7_ZwaJZ8Bfqq3C5Yw=='} ResponseBody: [{"orderId":653277220,"symbol":"LTCUSDT","status":"CANCELED","clientOrderId":"x-xcKtGhcuf015e2573a694e64b02827","price":"50.00","avgPrice":"0.00","origQty":"0.200","executedQty":"0.000","cumQty":"0.000","cumQuote":"0.00000","timeInForce":"GTX","type":"LIMIT","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0.00","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"LIMIT","priceMatch":"NONE","selfTradePreventionMode":"NONE","goodTillDate":0,"updateTime":1700043134621}]
[{'amount': 0.2,
  'average': None,
  'clientOrderId': 'x-xcKtGhcuf015e2573a694e64b02827',
  'cost': 0.0,
  'datetime': '2023-11-15T10:12:14.621Z',
  'fee': {'cost': None, 'currency': None, 'rate': None},
  'fees': [{'cost': None, 'currency': None, 'rate': None}],
  'filled': 0.0,
  'id': '653277220',
  'info': {'avgPrice': '0.00',
           'clientOrderId': 'x-xcKtGhcuf015e2573a694e64b02827',
           'closePosition': False,
           'cumQty': '0.000',
           'cumQuote': '0.00000',
           'executedQty': '0.000',
           'goodTillDate': '0',
           'orderId': '653277220',
           'origQty': '0.200',
           'origType': 'LIMIT',
           'positionSide': 'BOTH',
           'price': '50.00',
           'priceMatch': 'NONE',
           'priceProtect': False,
           'reduceOnly': False,
           'selfTradePreventionMode': 'NONE',
           'side': 'BUY',
           'status': 'CANCELED',
           'stopPrice': '0.00',
           'symbol': 'LTCUSDT',
           'timeInForce': 'GTX',
           'type': 'LIMIT',
           'updateTime': '1700043134621',
           'workingType': 'CONTRACT_PRICE'},
  'lastTradeTimestamp': None,
  'lastUpdateTimestamp': 1700043134621,
  'postOnly': True,
  'price': 50.0,
  'reduceOnly': False,
  'remaining': 0.2,
  'side': 'buy',
  'status': 'canceled',
  'stopLossPrice': None,
  'stopPrice': None,
  'symbol': 'LTC/USDT:USDT',
  'takeProfitPrice': None,
  'timeInForce': 'PO',
  'timestamp': 1700043134621,
  'trades': [],
  'triggerPrice': None,
  'type': 'limit'}]
```

**Comment by moerben2021** [comment]
Traceback (most recent call last):
  File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 613, in fetch
    response.raise_for_status()
  File "C:\Users\Dell\anaconda3\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/batchOrders?timestamp=1700053765062&symbol=WLDUSDT&recvWindow=10000&orderidlist=%5B1763402623,1763402624%5D&origclientorderidlist=%5B%5D&signature=a5d498cdcdc187214f351b63b5240af4e8c5850e73f06200e995b09b52aaaf99

**Comment by moerben2021** [comment]
> fapiPrivateDeleteBatchOrders

Traceback (most recent call last):
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 613, in fetch
response.raise_for_status()
File "C:\Users\Dell\anaconda3\lib\site-packages\requests\models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/batchOrders?timestamp=1700053765062&symbol=WLDUSDT&recvWindow=10000&orderidlist=%5B1763402623,1763402622,1742977171,1760620832,1744087717,1763402626,1763402625,1763402624%5D&origclientorderidlist=%5B%5D&signature=a5d498cdcdc187214f351b63b5240af4e8c5850e73f06200e995b09b52aaaf99

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\workspace\Python\vscode\slowly\slowly_main.py", line 87, in
doSchedule()
File "D:\workspace\Python\vscode\slowly\slowly_main.py", line 79, in doSchedule
main_schedule.do_schedule()
File "D:\workspace\Python\vscode\slowly\main_schedule.py", line 45, in do_schedule
do_schedule_job(path, exchange)
File "D:\workspace\Python\vscode\slowly\main_schedule.py", line 60, in do_schedule_job
regular_invest(path, exchange)
File "D:\workspace\Python\vscode\slowly\strategy\regular.py", line 38, in regular_invest
strategy.run(exchange)
File "D:\workspace\Python\vscode\slowly\strategy\StrategyRegularArithmetic.py", line 38, in run
diff_set = self.get_order_prices(exchange)
File "D:\workspace\Python\vscode\slowly\strategy\StrategyRegularArithmetic.py", line 101, in get_order_prices
cancel_orers = exchange.cancelOrders(order_id_list, symbol = self.symbol)
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\binance.py", line 4852, in cancel_orders
response = self.fapiPrivateDeleteBatchOrders(self.extend(request, params))
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\types.py", line 28, in unbound_method
return _self.request(self.path, self.api, self.method, params, config=self.config)
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\binance.py", line 8028, in request
response = self.fetch2(path, api, method, params, headers, body, config)
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3195, in fetch2
return self.fetch(request['url'], request['method'], request['headers'], request['body'])
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 629, in fetch
skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\binance.py", line 7997, in handle_errors
self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3570, in throw_exactly_matched_exception
raise exact[string](https://github.com/ccxt/ccxt/issues/message)
ccxt.base.errors.AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."}

**Comment by moerben2021** [comment]
> @moerben2021 Locally I can't reproduce the issue, do you mind sharing a verbose log?
> 
> ```
> Python v3.11.5
> CCXT v4.1.52
> binanceusdm.cancelOrders(['653277220'],LTC/USDT:USDT)
> 
> fetch Request: binanceusdm DELETE https://testnet.binancefuture.com/fapi/v1/batchOrders?timestamp=1700043133951&symbol=LTCUSDT&recvWindow=10000&orderidlist=[653277220]&origclientorderidlist=[]&signature=500ed699c4f7cc163c33197dab0bbfc28399724f49a0485016e502d3655fa850 RequestHeaders: {'X-MBX-APIKEY': '227719da8d8499e8d3461587d19f259c0b39c2b462a77c9b748a6119abd74401', 'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None
> 
> fetch Response: binanceusdm DELETE https://testnet.binancefuture.com/fapi/v1/batchOrders?timestamp=1700043133951&symbol=LTCUSDT&recvWindow=10000&orderidlist=[653277220]&origclientorderidlist=[]&signature=500ed699c4f7cc163c33197dab0bbfc28399724f49a0485016e502d3655fa850 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Wed, 15 Nov 2023 10:12:14 GMT', 'Server': 'Bengine', 'Vary': 'Accept-Encoding', 'x-mbx-used-weight-1m': '17', 'x-response-time': '47ms', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 a7a209acee14726bdc56f2b8600564e0.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'LHR3-C2', 'X-Amz-Cf-Id': 'jU4crUkuicDiFuglgRJYADUYcz6uTnErKLJ-b7_ZwaJZ8Bfqq3C5Yw=='} ResponseBody: [{"orderId":653277220,"symbol":"LTCUSDT","status":"CANCELED","clientOrderId":"x-xcKtGhcuf015e2573a694e64b02827","price":"50.00","avgPrice":"0.00","origQty":"0.200","executedQty":"0.000","cumQty":"0.000","cumQuote":"0.00000","timeInForce":"GTX","type":"LIMIT","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0.00","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"LIMIT","priceMatch":"NONE","selfTradePreventionMode":"NONE","goodTillDate":0,"updateTime":1700043134621}]
> [{'amount': 0.2,
>   'average': None,
>   'clientOrderId': 'x-xcKtGhcuf015e2573a694e64b02827',
>   'cost': 0.0,
>   'datetime': '2023-11-15T10:12:14.621Z',
>   'fee': {'cost': None, 'currency': None, 'rate': None},
>   'fees': [{'cost': None, 'currency': None, 'rate': None}],
>   'filled': 0.0,
>   'id': '653277220',
>   'info': {'avgPrice': '0.00',
>            'clientOrderId': 'x-xcKtGhcuf015e2573a694e64b02827',
>            'closePosition': False,
>            'cumQty': '0.000',
>            'cumQuote': '0.00000',
>            'executedQty': '0.000',
>            'goodTillDate': '0',
>            'orderId': '653277220',
>            'origQty': '0.200',
>            'origType': 'LIMIT',
>            'positionSide': 'BOTH',
>            'price': '50.00',
>            'priceMatch': 'NONE',
>            'priceProtect': False,
>            'reduceOnly': False,
>            'selfTradePreventionMode': 'NONE',
>            'side': 'BUY',
>            'status': 'CANCELED',
>            'stopPrice': '0.00',
>            'symbol': 'LTCUSDT',
>            'timeInForce': 'GTX',
>            'type': 'LIMIT',
>            'updateTime': '1700043134621',
>            'workingType': 'CONTRACT_PRICE'},
>   'lastTradeTimestamp': None,
>   'lastUpdateTimestamp': 1700043134621,
>   'postOnly': True,
>   'price': 50.0,
>   'reduceOnly': False,
>   'remaining': 0.2,
>   'side': 'buy',
>   'status': 'canceled',
>   'stopLossPrice': None,
>   'stopPrice': None,
>   'symbol': 'LTC/USDT:USDT',
>   'takeProfitPrice': None,
>   'timeInForce': 'PO',
>   'timestamp': 1700043134621,
>   'trades': [],
>   'triggerPrice': None,
>   'type': 'limit'}]
> ```

cancel_order = exchange.fapiPrivateDeleteBatchOrders({
                 'symbol': self.symbol,
                 'orderIdList': order_id_list,
                'timestamp': timestamp
        })

Traceback (most recent call last):
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 613, in fetch
response.raise_for_status()
File "C:\Users\Dell\anaconda3\lib\site-packages\requests\models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/batchOrders?timestamp=1700053765062&symbol=WLDUSDT&recvWindow=10000&orderidlist=%5B1763402623,1763402622,1742977171,1760620832,1744087717,1763402626,1763402625,1763402624%5D&origclientorderidlist=%5B%5D&signature=a5d498cdcdc187214f351b63b5240af4e8c5850e73f06200e995b09b52aaaf99

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\workspace\Python\vscode\slowly\slowly_main.py", line 87, in
doSchedule()
File "D:\workspace\Python\vscode\slowly\slowly_main.py", line 79, in doSchedule
main_schedule.do_schedule()
File "D:\workspace\Python\vscode\slowly\main_schedule.py", line 45, in do_schedule
do_schedule_job(path, exchange)
File "D:\workspace\Python\vscode\slowly\main_schedule.py", line 60, in do_schedule_job
regular_invest(path, exchange)
File "D:\workspace\Python\vscode\slowly\strategy\regular.py", line 38, in regular_invest
strategy.run(exchange)
File "D:\workspace\Python\vscode\slowly\strategy\StrategyRegularArithmetic.py", line 38, in run
diff_set = self.get_order_prices(exchange)
File "D:\workspace\Python\vscode\slowly\strategy\StrategyRegularArithmetic.py", line 101, in get_order_prices
cancel_orers = exchange.cancelOrders(order_id_list, symbol = self.symbol)
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\binance.py", line 4852, in cancel_orders
response = self.fapiPrivateDeleteBatchOrders(self.extend(request, params))
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\types.py", line 28, in unbound_method
return _self.request(self.path, self.api, self.method, params, config=self.config)
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\binance.py", line 8028, in request
response = self.fetch2(path, api, method, params, headers, body, config)
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3195, in fetch2
return self.fetch(request['url'], request['method'], request['headers'], request['body'])
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 629, in fetch
skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\binance.py", line 7997, in handle_errors
self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
File "C:\Users\Dell\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3570, in throw_exactly_matched_exception
raise exact[string](https://github.com/ccxt/ccxt/issues/message)
ccxt.base.errors.AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."}

**Comment by moerben2021** [comment]
> @moerben2021 what's your python version?

Python 3.9.13

**Comment by carlotestor** [comment]
The `-1022` is almost certainly caused by passing your own `timestamp` into the params. CCXT already appends `timestamp` (and `recvWindow`) and signs the exact query string it builds — supplying a second one produces a query that no longer matches the signature Binance recomputes. The single-order case survives it by luck of ordering; the batch one doesn't.

Drop the manual timestamp and use the unified method:

```python
orders = exchange.fetch_open_orders(symbol)          # symbol = 'BTC/USDT:USDT' (unified)
ids = [str(o['id']) for o in orders]
canceled = exchange.cancel_orders(ids, symbol)
```

Checklist if it still fails:
- `symbol` must be the **unified** symbol (`'BTC/USDT:USDT'`), not `'BTCUSDT'`. `cancel_orders` on Binance is contract-only and requires the symbol argument.
- Pass ids as strings — Binance is picky about how the `orderidlist` array is serialized, and CCXT handles that for you when you go through `cancel_orders`.
- Never add `timestamp`, `signature`, or `recvWindow` yourself to any implicit `fapiPrivate*` call.
- Make sure your system clock is synced, or set `'options': {'adjustForTimeDifference': True}`.

Also prefer `fetch_open_orders()` over `fapiPrivateGetOpenOrders` so you get unified order structures back.
