### ISSUE TITLE
Freqtrade :   assert precision is not None

### ISSUE THREAD

**Issue by Johan1974** [ccxt/ccxt#19991]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

Version: 4.1.53

### Description

Hello,

I am using freqtrade and since yesterday i receive the error "freqtrade assert precision is not None"
Through some forums i got answers it might be related to CCXT 

As i undersand it has to do with the precison of a trade. So think it needs to be rounded down a few decimals. 
See the example below where the stake amont is 21.948299999999996 

Do you know what this might be and can you give me some clarity?

Thanks!

### Code

```
  2023-11-16 01:00:14,229 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for 1INCH/EUR with stake_amount: 21.948299999999996 ...
bot01_8080_real | 2023-11-16 01:00:14,230 - freqtrade.commands.trade_commands - ERROR - 
bot01_8080_real | 2023-11-16 01:00:14,231 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
bot01_8080_real | Traceback (most recent call last):
bot01_8080_real |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
bot01_8080_real |     worker.run()
bot01_8080_real |   File "/freqtrade/freqtrade/worker.py", line 75, in run
bot01_8080_real |     state = self._worker(old_state=state)
bot01_8080_real |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot01_8080_real |   File "/freqtrade/freqtrade/worker.py", line 116, in _worker
bot01_8080_real |     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
bot01_8080_real |   File "/freqtrade/freqtrade/worker.py", line 147, in _throttle
bot01_8080_real |     result = func(*args, **kwargs)
bot01_8080_real |              ^^^^^^^^^^^^^^^^^^^^^
bot01_8080_real |   File "/freqtrade/freqtrade/worker.py", line 180, in _process_running
bot01_8080_real |     self.freqtrade.process()
bot01_8080_real |   File "/freqtrade/freqtrade/freqtradebot.py", line 249, in process
bot01_8080_real |     self.enter_positions()
bot01_8080_real |   File "/freqtrade/freqtrade/freqtradebot.py", line 536, in enter_positions
bot01_8080_real |     trades_created += self.create_trade(pair)
bot01_8080_real |                       ^^^^^^^^^^^^^^^^^^^^^^^
bot01_8080_real |   File "/freqtrade/freqtrade/freqtradebot.py", line 598, in create_trade
bot01_8080_real |     return self.execute_entry(
bot01_8080_real |            ^^^^^^^^^^^^^^^^^^^
bot01_8080_real |   File "/freqtrade/freqtrade/freqtradebot.py", line 781, in execute_entry
bot01_8080_real |     order = self.exchange.create_order(
bot01_8080_real |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot01_8080_real |   File "/freqtrade/freqtrade/exchange/exchange.py", line 1075, in create_order
bot01_8080_real |     order = self._api.create_order(
bot01_8080_real |             ^^^^^^^^^^^^^^^^^^^^^^^
bot01_8080_real |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/bitvavo.py", line 1020, in create_order
bot01_8080_real |     request['amount'] = self.amount_to_precision(symbol, amount)
bot01_8080_real |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot01_8080_real |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/bitvavo.py", line 300, in amount_to_precision
bot01_8080_real |     return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], DECIMAL_PLACES)
bot01_8080_real |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot01_8080_real |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/decimal_to_precision.py", line 37, in decimal_to_precision
bot01_8080_real |     assert precision is not None
bot01_8080_real |            ^^^^^^^^^^^^^^^^^^^^^
bot01_8080_real | AssertionError
bot01_8080_real | 2023-11-16 01:00:14,235 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit

```

**Comment by sc0Vu** [comment]
Hi @Johan1974

Thanks for the report, we will fix asap.

**Comment by Johan1974** [comment]
Hello,

Could i use a workaround fro the time being and use an older version? 
How can i uninstall the new version and go back an old version?

Or is this not possible?

Thanks!

Johan

**Comment by Johan1974** [comment]
Found a way to run previous versions and ended with 4.1.39 that seems to be working fine for the moment.
