### ISSUE TITLE
watchOrders keep-alive causes errors with Binance

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#20034]
### Operating System

Windows

### Programming Languages

JavaScript

### CCXT Version

4.0.111

### Description

One of my applications is used by a larger community. Recently, several people started to report problems. Every 20 minutes, they're seeing error messages:

BadRequest: binance {"code":-1101,"msg":"Too many parameters; expected '1' and received '2'."}
    at binance.throwExactlyMatchedException (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3274:19)
    at binance.handleErrors (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:8690:18)
    at /var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:788:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async binance.fetch2 (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2889:16)
    at async binance.request (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:8732:26)
    at async binance.keepAliveListenKey (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/pro/binance.js:1324:13)

The exception is thrown here:

`const data = await exchange.watchOrders(symbol);`

For every symbol that is being watched.

When using `exchange.verbose = true`, I see that CCXT sends some keep-alive request to the exchange, every 20 minutes. So my assumption is that there is some correlation.

The interesting thing is: I don't get the same errors when running the application on my PC, even when I'm using their API key (so the verbose output looks fine on my end). The problem occurs on both Ubuntu and Windows, and with different nodejs versions (e.g. 18.3, 20.6). I' really stuck to be honest. Don't know where to go from here.

I hope you can help with this.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @hodlerhacks, is it possible to get a verbose log of the issue? We would like to check what is sent to the exchange and what is returned to see if we can infer something from there.

**Comment by hodlerhacks** [comment]
Hi @carlosmiei, the problem is that I cannot reproduce it on my side. And getting this from my users is challenging. If I enable verbose logging, the log size after 20 minutes is huge. But let me see what I can do. Will let you know.

**Comment by hodlerhacks** [comment]
In the meanwhile, I updated to the latest CCXT and when running on my computer, hoping that might solve it. But now I'm getting DDoS Protection errors. Never had those before. All I changed was update to the latest CCXT version. When I downgrade to 4.0.111, the problem disappears. Upgrading again to the latest, and the problem re-appears.

The verbose logs for this error:

```
fetch Request:
 binance GET https://api.binance.com/api/v3/openOrders?timestamp=1700309255533&symbol=BTCUSDT&recvWindow=10000&signature=342569925762c585911d5528b8e0da20247d8d1d3ca0ce3b92986f4f02e64a7b   
RequestHeaders:
 {
  'X-MBX-APIKEY': 'mykey'
}
RequestBody:
 undefined

handleRestResponse:
 binance GET https://fapi.binance.com/fapi/v1/leverageBracket?timestamp=1700309255279&recvWindow=10000&signature=087915186d7d44a0fd6d5b5f44e553c3a13eadfdb8994beb7d62f4784043b665 401 Unauthorized
ResponseHeaders:
 {
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  Connection: 'keep-alive',
  'Content-Length': '69',
  'Content-Type': 'application/json',
  Date: 'Sat, 18 Nov 2023 12:07:35 GMT',
  Server: 'Tengine',
  'X-Mbx-Used-Weight-1m': '4',
  'X-Response-Time': '3ms'
}
ResponseBody:
 {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}

2023/11/18 13:07:35: Bot 001 > [DEBUG] Exception thrown in uncaughtException
2023/11/18 13:07:35: Bot 001 > Binance blocked API (DDoS protection) - check if API key is enabled for spot trading - pausing bot for 5 minutes
2023-11-18T12:07:35.572Z onError WebSocket was closed before the connection was established
2023-11-18T12:07:35.573Z onClose CloseEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      message: [Function],
      error: [Function],
      close: [Function],
      ping: [Function: bound onPing],
      pong: [Function: bound onPong],
      upgrade: [Function: bound onUpgrade]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://stream.binance.com:9443/ws/W9rKFFXH8MIAhnqATvDEB7xXMEnGEocQIenmmMCBv670MnVjwQQMXDQmVwwA',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /ws/W9rKFFXH8MIAhnqATvDEB7xXMEnGEocQIenmmMCBv670MnVjwQQMXDQmVwwA HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: mhGBCMMp0cucsnpccSXEgg==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Host: stream.binance.com:9443\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/ws/W9rKFFXH8MIAhnqATvDEB7xXMEnGEocQIenmmMCBv670MnVjwQQMXDQmVwwA',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'stream.binance.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(kAborted)]: true,
      [Symbol(kError)]: undefined
    },
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'close',
  [Symbol(kCode)]: 1006,
  [Symbol(kReason)]: '',
  [Symbol(kWasClean)]: false
}
handleRestResponse:
 binance GET https://api.binance.com/api/v3/openOrders?timestamp=1700309255533&symbol=BTCUSDT&recvWindow=10000&signature=342569925762c585911d5528b8e0da20247d8d1d3ca0ce3b92986f4f02e64a7b 200 OK
ResponseHeaders:
 {
  'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Length': '2',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Sat, 18 Nov 2023 12:07:35 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  Via: '1.1 c337a55bb25a3540411fbbf6c8ad1b46.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'EM46uzYCCNCG4bhUhutE94YvSxnQKswjsR33PDHeIscwzOuqUQtC_Q==',
  'X-Amz-Cf-Pop': 'AMS1-P1',
  'X-Cache': 'Miss from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Mbx-Used-Weight': '262',
  'X-Mbx-Used-Weight-1m': '262',
  'X-Mbx-Uuid': '696473e9-033f-4549-92ff-d408c8c6aea8',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
}
ResponseBody:
 []

fetch Request:
 binance GET https://api.binance.com/api/v3/openOrders?timestamp=1700309255850&symbol=XRPUSDT&recvWindow=10000&signature=b525eb7ee3bec147782e683e444d2f9612bd433b494f5e6d89749ddeb5c10602   
RequestHeaders:
 {
  'X-MBX-APIKEY': 'mykey'
}
RequestBody:
 undefined

handleRestResponse:
 binance GET https://api.binance.com/api/v3/openOrders?timestamp=1700309255850&symbol=XRPUSDT&recvWindow=10000&signature=b525eb7ee3bec147782e683e444d2f9612bd433b494f5e6d89749ddeb5c10602 200 OK
ResponseHeaders:
 {
  'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Length': '2',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Sat, 18 Nov 2023 12:07:36 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  Via: '1.1 c337a55bb25a3540411fbbf6c8ad1b46.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'razpqUwNPoMIPtCfH1B6fX6MqURhk4g2rWwbSCZvmANTEy4_Ppz93Q==',
  'X-Amz-Cf-Pop': 'AMS1-P1',
  'X-Cache': 'Miss from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Mbx-Used-Weight': '268',
  'X-Mbx-Used-Weight-1m': '268',
  'X-Mbx-Uuid': 'e42b6b00-ca18-458f-885b-73e48dac49d9',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
}
ResponseBody:
 []
```

**Comment by hodlerhacks** [comment]
One additional piece of information: at least one of the people reporting this problem also get this error:

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit

Could there be a relation?

**Comment by hodlerhacks** [comment]
[verbose-logs.txt](https://github.com/ccxt/ccxt/files/13413553/verbose-logs.txt)

Hi @carlosmiei, I haven't managed to get verbose logs yet for the BadRequest issue, but I was doing some more tests on my side and I've run into another issue some of my users identified recently. Attached is a file with part of the verbose logging. The interesting thing here is that my application seems to connect with Binance using an API key that I've been using for my testing for like forever. And it mostly seems to work, I'm able to retrieve information about my portfolio for instance. But at two points in the logs, there is an 'invalid API-key' message. In both cases, it's linked to this request:

`https://fapi.binance.com/fapi/v1/leverageBracket`

I'm not familiar with this leverage bracket API, but please note my application uses spot trading only. I have no idea why anything related to leverage would be requested from Binance. Can you tell what is triggering this request?

This is certainly an issue that started to appear recently. But interestingly, I cannot 100% reproduce it. If I use the exact same API key on another machine, there is no problem.

This problem really puzzles me. Hope you can help.

**Comment by maoxiaoyun1963** [comment]
Hi, we ran into the same problem as well. Is this issue resolved yet?

**Comment by hodlerhacks** [comment]
It has been resolved. Are you on the latest version?

**Comment by carlotestor** [comment]
**Triage note — can be closed without further user input**

The original Binance `watchOrders` keep-alive `BadRequest` (`Too many parameters; expected '1' and received '2'`) was discussed in-thread, and the reporter later confirmed: **“It has been resolved. Are you on the latest version?”**

No further user repro is needed. Can be closed as **bug already fixed** (upgrade to a current release if anyone still sees the old behavior).
