### ISSUE TITLE
Binance Futures endpoint called for spot trading, causing API permission errors

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#20096]
### Operating System

Ubuntu

### CCXT Version

4.0.111

### Description

My application is used for spot trading only. It has worked with Binance for 2+ years without any problems. But recently, various users of my application have started to see issues. Here is one particular error message that I cannot explain:

```
DDoSProtection: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}
    at binance.handleErrors (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:8703:23)
    at /var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:789:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async binance.fetch2 (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2920:16)
    at async binance.request (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:8756:26)
    at async binance.loadLeverageBrackets (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:7534:30)
    at async binance.fetchPositionsRisk (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:7898:9)
    at async binance.fetchPositions (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:7831:20)
    at async binance.loadPositionsSnapshot (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/pro/binance.js:2412:27)
```

Why is this Futures endpoint being called? Can this be triggered by calling e.g. fetchBalance?

What makes it even more interesting, I see different results on different machines:

- Windows 11, node v16.20.2, local machine -> no problems
- Windows 11, node v18.18.2, local machine -> no problems
- Ubuntu, node v18.13.0, cloud server -> the above problem occurs

All of the above use the exact same API key. The IP whitelist includes the correct IP addresses.

Now, I just updated to the latest CCXT version, and then on Windows I'm getting the same error... When I downgrade to v4.0.111, the problem goes away.

Also, in my region, Binance Futures aren't available. So I cannot change the API key permissions to avoid this problem. 

As this is now affecting quite a number of people, I'm looking for a quick resolution.

Is there anything I can do to fix this?

### Code

```
  

```

**Comment by hodlerhacks** [comment]
Also:
- Windows 11, node v18.18.2 -> no problems

**Comment by hodlerhacks** [comment]
One more thing I've noticed, reproduced twice, on Ubuntu:

- The initial installation of the application uses CCXT v4.0.111
- When I update to the latest CCXT, the problem remains
- When I then downgrade again to v4.0.111, the problem goes away

This really puzzles me.

**Comment by sc0Vu** [comment]
@hodlerhacks 

Can you set this value to false and run script again?
```
'options': {
  'watchPositions': {
    'fetchPositionsSnapshot': false, // or false
    'awaitPositionsSnapshot': false, // whether to wait for the positions snapshot before providing updates
  },
}
```

**Comment by hodlerhacks** [comment]
Hi @sc0Vu, thanks for your quick response! Yes, that fixed it, that's great!

Out of curiosity, do you know why this issue appears now? My application has been used by hundreds of people with Binance, without any problems for 2.5 years. 

Now that this problem has been solved, the next appears:

BadRequest: binance {"code":-1101,"msg":"Too many parameters; expected '1' and received '2'."}
    at binance.throwExactlyMatchedException (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3317:19)
    at binance.handleErrors (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:8715:18)
    at /var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:789:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async binance.fetch2 (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2920:16)
    at async binance.request (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:8757:26)
    at async binance.keepAliveListenKey (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/pro/binance.js:1324:13)

This is something other users of my software have been reporting during the past weeks, and I was never able to reproduce it, until now. I reported it here: https://github.com/ccxt/ccxt/issues/20034.

I'm traveling today, but I will try to capture this with verbose logging as well, and communicate back in the other ticket.

**Comment by sc0Vu** [comment]
Hi @hodlerhacks,

That looks weird, would be great if you can provide verbose log or version.

**Comment by hodlerhacks** [comment]
[verbose-logs-2.txt](https://github.com/ccxt/ccxt/files/13452856/verbose-logs-2.txt)

Attached the verbose logs. This is with v4.0.111. These errors appear every 20 minutes.

Before, when I updated to the latest version, I would get the DDoSProtection errors, so I couldn't test if that would solve the BadRequest error. But now that the DDoSProtection errors are gone based on your suggestion, I could test with the latest CCXT version.

I've just updated, and ran another test, and the problem is still there.

Hope the verbose logs help understand what's going wrong.

**Comment by hodlerhacks** [comment]
And to be clear, these errors are triggered by watchOrders(symbol), and this is the stack trace:

BadRequest: binance {"code":-1101,"msg":"Too many parameters; expected '1' and received '2'."}
    at binance.throwExactlyMatchedException (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3274:19)
    at binance.handleErrors (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:8690:18)
    at /var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:788:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async binance.fetch2 (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2889:16)
    at async binance.request (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/binance.js:8732:26)
    at async binance.keepAliveListenKey (/var/opt/balance-botv2/node_modules/ccxt/dist/cjs/src/pro/binance.js:1324:13)

**Comment by sc0Vu** [comment]
Hi @hodlerhacks 

Is there request body for userDataStream request?

**Comment by hodlerhacks** [comment]
Hi @sc0Vu, it's not visible in the verbose logging, I noticed that as well, which is weird, isn't it?

**Comment by hodlerhacks** [comment]
@sc0Vu also, can you explain why this was never needed, but now it is:

'options': {
  'watchPositions': {
    'fetchPositionsSnapshot': false, // or false
    'awaitPositionsSnapshot': false, // whether to wait for the positions snapshot before providing updates
  },
}

I'd like to understand this, because I've created an online course on crypto programming using CCXT, and I'd like to be able to explain to my students why this is needed now.

**Comment by sc0Vu** [comment]
Hi @hodlerhacks,

Thanks for your help. I can reproduce this issue, will submit a PR to fix this.

**Comment by hodlerhacks** [comment]
That's great news @sc0Vu, thanks so much for following up on this!
