### ISSUE TITLE
okex withdraw error

### ISSUE THREAD

**Issue by xuanricheng** [ccxt/ccxt#2015]
It's execute well in 7 days ago!
withdraw always return the error like below:
okex {"result":false,"error_code":10012}
`exchange.password = '********'`
`params = {'chargefee': 0.1}`
`result = exchange.withdraw(“ETC",0.5, address, params=params)`

console output: 
Exception in thread Thread-97211: 
Traceback (most recent call last):
File "/home/xuanricheng/tools/anaconda2/envs/py3/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                             
    self.run()                                                                                                                                            
  File "/home/xuanricheng/tools/anaconda2/envs/py3/lib/python3.6/threading.py", line 864, in run                                                          
    self._target(*self._args, **self._kwargs)                                                                                                             
  File "do_transaction_ccxt.py", line 200, in wait_until_one_transfer                                                                                     
    , address[address_name][coin_type.lower()], params=params)                                                                                            
  File "/home/xuanricheng/tools/anaconda2/envs/py3/lib/python3.6/site-packages/ccxt/okcoinusd.py", line 588, in withdraw                                  
    response = self.privatePostWithdraw(self.extend(request, query))                                                                                      
  File "/home/xuanricheng/tools/anaconda2/envs/py3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 293, in request                               
    return self.fetch2(path, api, method, params, headers, body)                                                                                          
  File "/home/xuanricheng/tools/anaconda2/envs/py3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 290, in fetch2                                
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])                                                             
  File "/home/xuanricheng/tools/anaconda2/envs/py3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 370, in fetch                                 
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)                                                 
  File "/home/xuanricheng/tools/anaconda2/envs/py3/lib/python3.6/site-packages/ccxt/okcoinusd.py", line 627, in handle_errors                             
    raise ExchangeError(message)                                                                                                                          
ccxt.base.errors.ExchangeError: okex {"result":false,"error_code":10012}    

- OS: linux 
- Programming Language version: python
- CCXT version: 1.10.1178
- Exchange: okex
- Method: withdraw

**Comment by kroitor** [comment]
@xuanricheng can you please post a minimal but a complete snippet of code to reproduce your problem (avoid one-liners)? I don't really understand how you call the method, need to see it in a context, please post just the necessary things to reproduce it, remove all irrelevant code to rule out other causes. Please follow these instructions literally: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Standing by for more info form you. Thx!

**Comment by xuanricheng** [comment]
I see that okex API said: symbol parameter must be like this: 
 btc_usd:比特币    ltc_usd :莱特币    eth_usd :以太坊     etc_usd :以太经典    bch_usd :比特现金

but ccxt in version 1.10.1178, set this parameter as "etc" or "btc"

**Comment by kroitor** [comment]
Fixed in ccxt 1.10.1189. Thx for reporting!
