### ISSUE TITLE
 AuthenticationError / DDoSProtection exceptions being swallowed

### ISSUE THREAD

**Issue by quantitative-technologies** [ccxt/ccxt#20164]
### Operating System

Debian

### Programming Languages

Python

### CCXT Version

4.1.67

### Description

The `watch_orders` API call is swallowing the `AuthenticationError` and/or `DDoSProtection` exception and instead dumping to the terminal. 

For example, the following code:

```python
from asyncio import run
from ccxt.base.errors import DDoSProtection, AuthenticationError
import ccxt.pro as ccxtpro

api_key = <...>
api_secret = <...>

async def main():
    exchange = ccxtpro.binance(
        dict(
            apiKey=api_key, 
            secret=api_secret,
            newUpdates=True,
        )
    )
    exchange.set_sandbox_mode(True)

    try:
        orders = await exchange.watch_orders('BTC/USDT')
    except DDoSProtection as e:
        print(f"DDosProtection Exception thrown: {e}")
    except AuthenticationError as e:
        print(f"Authentication Error: {e}")
    except Exception as e:
        print(f"Other Exception thrown: {e}")

    await exchange.close()

run(main())
```

makes the following dump to the terminal and hangs (I recall also seeing `DDosProtection` instead of `AuthenticationError`):

```console
Future exception was never retrieved
future: <Future finished exception=AuthenticationError('binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}')>
Traceback (most recent call last):
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/pro/binance.py", line 2218, in load_positions_snapshot
    positions = await self.fetch_positions(None, {'type': type})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7262, in fetch_positions
    return await self.fetch_positions_risk(symbols, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7314, in fetch_positions_risk
    await self.load_leverage_brackets(False, params)
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 6988, in load_leverage_brackets
    response = await getattr(self, method)(query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 8051, in request
    response = await self.fetch2(path, api, method, params, headers, body, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 703, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 229, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 8020, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/base/exchange.py", line 3655, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}
```

Whereas, the `fetch_positions` handles the exception correctly. For example:

```python
    try: 
        positions = await exchange.fetch_positions(params={'type': 'spot'})
    except DDoSProtection as e:
        print(f"DDosProtection Exception thrown: {e}")
    except AuthenticationError as e:
        print(f"Authentication Error: {e}")
    except Exception as e:
        print(f"Other Exception thrown: {e}")
```

raises the `AuthenticalError` and exits with the console message:

```console
Authentication Error: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}
```

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @quantitative-technologies 

I think this issue is related: ccxt/ccxt#20138 for the permission error.

**Comment by quantitative-technologies** [comment]
Yes, I agree, and thanks for referencing it. 

But of course, my issue is with the exception handling rather than why there is an exception.

**Comment by sc0Vu** [comment]
It probably spawn another context to fetch data https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/base/exchange.py#L315

Can you catch any exception?

**Comment by quantitative-technologies** [comment]
Right.

As you can see from the first code example, it does not catch any exception, that is any exception derived from `Exception`.

**Comment by quantitative-technologies** [comment]
Thanks
