### ISSUE TITLE
Uncaught Error Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by gokuMaker** [ccxt/ccxt#20188]
### Operating System

ubuntu 20.01

### Programming Languages

JavaScript

### CCXT Version

4.1.73

### Description

node: 20.1.0

/home/gok123/.nvm/versions/node/v20.1.0/bin/node ./exchanges/Test.js
Uncaught Error Error: Cannot find module 'debug'
Require stack:
- /media/gok123/765844E85844A927/programowanie/javaScript/nodejs/node_modules/ccxt/dist/cjs/src/static_dependencies/proxies/http-proxy-agent/index.js
- /media/gok123/765844E85844A927/programowanie/javaScript/nodejs/node_modules/ccxt/dist/cjs/src/base/Exchange.js
- /media/gok123/765844E85844A927/programowanie/javaScript/nodejs/node_modules/ccxt/dist/cjs/ccxt.js
- /media/gok123/765844E85844A927/programowanie/javaScript/nodejs/node_modules/ccxt/dist/ccxt.cjs
- /media/gok123/765844E85844A927/programowanie/javaScript/Comparison/MakerComparision/exchanges/Test.js
    at Module._resolveFilename (internal/modules/cjs/loader:1082:15)
    at Module._load (internal/modules/cjs/loader:928:27)
    at Module.require (internal/modules/cjs/loader:1149:19)
    at require (internal/modules/helpers:121:18)
    at <anonymous> (/media/gok123/765844E85844A927/programowanie/javaScript/nodejs/node_modules/ccxt/dist/cjs/src/static_dependencies/proxies/http-proxy-agent/index.js:7:19)
    at Module._compile (internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (internal/modules/cjs/loader:1321:10)
    at Module.load (internal/modules/cjs/loader:1125:32)
    at Module._load (internal/modules/cjs/loader:965:12)
    at Module.require (internal/modules/cjs/loader:1149:19)
    at require (internal/modules/helpers:121:18)
    at <anonymous> (/media/gok123/765844E85844A927/programowanie/javaScript/nodejs/node_modules/ccxt/dist/cjs/src/base/Exchange.js:662:87)
No debugger available, can not send 'variables'
Process exited with code 1

Old CCXT works

### Code

```
  
const ccxt = require("../../../nodejs/node_modules/ccxt/dist/ccxt.cjs");


```

**Comment by carlosmiei** [comment]
@gametheatrics @iht76 we will take a look and revert.

**Comment by gokuMaker** [comment]
Code changed in typescript files but I had uncomment debug in dist/.../index.js 
When I comment stuff wityh debug // createDebug it will works. 

Btw in Exmo cannot editOrder? :/ I get err:
Uncaught BadRequest BadRequest: exmo editOrder() can only be used for isolated margin orders
I think that Exmo change some in their api so I should not create new issiu about it?

**Comment by ttodua** [comment]
> Code changed in typescript files but I had uncomment debug in dist/.../index.js When I comment stuff wityh debug // createDebug it will works.
> 
> Btw in Exmo cannot editOrder? :/ I get err: Uncaught BadRequest BadRequest: exmo editOrder() can only be used for isolated margin orders I think that Exmo change some in their api so I should not create new issiu about it?

1) about exmo, yes, please use new issues for unrelated problems to this topic.
2) so, do you confirm that the last update (where debug become commented in ccxt) work for you?
