### ISSUE TITLE
watchTrades() results in Binance closing the connection because of too many requests

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#20393]
### Operating System

Windows

### Programming Languages

JavaScript

### CCXT Version

4.1.72

### Description

Using exchange.watchTrades() with Binance is broken. As soon as I use that function, an exception is thrown:

```
NetworkError: connection closed by remote server, closing code 1008
    at WsClient.onClose (C:\balance-bot\node_modules\ccxt\dist\cjs\src\base\ws\Client.js:210:24)
    at callListener (C:\balance-bot\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onClose (C:\balance-bot\node_modules\ws\lib\event-target.js:220:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (C:\balance-bot\node_modules\ws\lib\websocket.js:264:10)
    at TLSSocket.socketOnClose (C:\balance-bot\node_modules\ws\lib\websocket.js:1283:15)
    at TLSSocket.emit (node:events:525:35)
    at node:net:301:12
    at TCP.done (node:_tls_wrap:588:7)
```

When downgrading to e.g. CCXT v4.0.111, the issue is gone. So something must have changed since then. 

Note: when starting with an earlier CCXT version and then upgrading to the latest, this problem doesn't seem appear. But when doing a clean installation of the latest CCXT (but also 4.1.72) the issues occurs. I had a similar experience with this issue that I reported a few weeks ago: https://github.com/ccxt/ccxt/issues/20096. The occurrence of that also seemed to be depending on the sequence of installing different versions of CCXT.

Attached are the verbose logs.
[verbose-log,txt](https://github.com/ccxt/ccxt/files/13682493/verbose-log.txt)

### Code

```
  

```

**Comment by hodlerhacks** [comment]
Update: I'd asked one of the people experiencing this problem with 4.1.72 to uninstall CCXT (using NPM uninstall) and then install 4.1.72 again. That solved the issue. This confirms my suspicion that something might be going wrong with updating / installing CCXT using NPM.

**Comment by hodlerhacks** [comment]
Hi @pcriadoperez, I was wondering if you have an update on this issue. I'm eager to have this resolved for the users of my application.

**Comment by hodlerhacks** [comment]
I've found the root cause: when calling watchTrades() on more than 5 symbols sequentially, this exception is thrown. This hasn't been a problem until very recently. Has something changed that is causing this?

I've seen the new watchTradesForSymbols() method, but the exchange support for this is far more limited than for watchTrades(). For instance, Kraken is not supported, which some of my users are using.

How can I solve this problem?

**Comment by hodlerhacks** [comment]
It seems that Binance has introduced some more restrictive limitations on their websocket API, only 5 messages per second: https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md

I've moved to watchTradesForSymbols() for those exchanges that support it, which solves the problem. Issue closed.
