### ISSUE TITLE
Inconsistent errors with Binance US

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#20436]
### Operating System

Windows

### CCXT Version

4.1.72

### Description

One of the users of my application tried to use Binance US. The application doesn't get beyond exchange.loadMarkets(). I asked him to run a simple application that only does just that, loadMarkets(), using verbose logging. This is the result:

```
fetch Request:
 binanceus GET https://api.binance.us/api/v1/exchangeInfo
RequestHeaders:
 {}
RequestBody:
 undefined

NetworkError: binanceus GET https://api.binance.us/api/v1/exchangeInfo fetch failed
    at binanceus.fetch (C:\balance-bot\node_modules\ccxt\dist\cjs\src\base\Exchange.js:805:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async binanceus.fetch2 (C:\balance-bot\node_modules\ccxt\dist\cjs\src\base\Exchange.js:3088:16)
    at async binanceus.request (C:\balance-bot\node_modules\ccxt\dist\cjs\src\binance.js:8758:26)
    at async Promise.all (index 0)
    at async binanceus.fetchMarkets (C:\balance-bot\node_modules\ccxt\dist\cjs\src\binance.js:2051:26)
    at async binanceus.loadMarketsHelper (C:\balance-bot\node_modules\ccxt\dist\cjs\src\base\Exchange.js:885:25)
    at async initExchange (C:\balance-bot\test-binanceus.js:27:19)
    at async init (C:\balance-bot\test-binanceus.js:12:5)
```

When I run the exact same code, using his API key, on my PC, then it works without problems. We're both using CCXT 4.1.72, both on Windows as well. I also asked him to uninstall CCXT and reinstall. That didn't help.

I've now seen and reported several problems with Binance that are only visible to some users. I cannot get my head around what might be different or cause this. Sometimes it helped if they'd uninstall and reinstall CCXT, or install an older version and then upgrade. So far all with Binance (non-US), but now also with Binance US.

For reference, here is one of those examples: https://github.com/ccxt/ccxt/issues/20393

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @hodlerhacks,

Can you try ping the domain or check the domain record? There are many reasons that network could have trouble, dns, isp or any other eles.

**Comment by hodlerhacks** [comment]
Connectivity is not the problem. This user is using the application with Kraken without any problems.

**Comment by ksamarin90** [comment]
Hi @sc0Vu,

I have the same issue with binance. What I recognized - error occurs only if I use Node.js 20. With 18 version it works fine. Are there any limitations regarding Node.js version?
According to package.json it should be ok:
https://github.com/ccxt/ccxt/blob/master/package.json#L14

**Comment by carlotestor** [comment]
`NetworkError: ... fetch failed` on a *public* endpoint (`exchangeInfo` needs no keys) means the request never reached Binance.US — so it's environment-specific, not an API-key or CCXT-version issue. @ksamarin90's observation is the key one: this is almost always Node 20's DNS resolution change.

Node 18 → 20 switched `dns.lookup` to no longer reorder results, so on hosts where the IPv6 record is unreachable Node now picks it first and the connection dies. Fix on the affected machine:

```js
// option A: force IPv4 for the whole process
import dns from 'node:dns';
dns.setDefaultResultOrder('ipv4first');

// option B: run node with the flag
// node --dns-result-order=ipv4first app.js
```

Other things that produce the identical symptom on one machine but not another: a corporate/AV TLS proxy, or Binance.US geo-blocking that IP (they block non-US IPs even for public data). Have the user try `curl https://api.binance.us/api/v1/exchangeInfo` — if curl also fails, it's network/geo, not Node.

If the `ipv4first` flag fixes it for your user, this can be closed.
