### ISSUE TITLE
binance requires to release all resources with an explicit call to the .close() coroutine.

### ISSUE THREAD

**Issue by brook-w** [ccxt/ccxt#20447]
### Operating System

windows

### Programming Languages

Python

### CCXT Version

 4.1.95

### Code

```python
# -*- coding: utf-8 -*-
# This example uses the implicit API, in the future we will have options unified which will make things easier.
# You can check if the unified methods are ready-to-use (createOrder, fetchOrder etc) by checking: `is_unified = exchange.has['option']`

import asyncio
import os
import sys
from pprint import pprint


import ccxt.async_support as ccxt  # noqa: E402


async def main():
   exchange = ccxt.binance({
       'apiKey': 'YOUR_API_KEY',
       'secret': 'YOUR_SECRET',
       # 'verbose': True,  # for debug output
   })
   await exchange.load_markets()
   market_id = 'ETH-221028-1700-C'
   symbol = 'ETH/USDT:USDT-221028-1700-C'
   try:
       response = await exchange.fetch_ticker(symbol)
       # Implicit API:
       # response = await exchange.eapiPublicGetTicker({
       #     # 'symbol': market_id,  # optional
       # })
       pprint(response)
   except Exception as e:
       print('fetch_ticker() failed')
       print(e)
   await exchange.close()


asyncio.run(main())

```

python-BaseException
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000027732AB4550>

**Comment by brook-w** [comment]
This is the official example code

**Comment by carlosmiei** [comment]
Hello @brook-w, I just ran the same snippet (with a different symbol only), and didn't get that warning.

**Comment by brook-w** [comment]
@carlosmiei Hello, could you please tell me your python version and cctx version and what platform is windows/linux/mac??

**Comment by brook-w** [comment]
My environment is conda python 3.10 ccxt 4.1.95 window 10-pro aiohttp and asyncio latest

**Comment by brook-w** [comment]
@carlosmiei But by the way, can you test it when using the network request proxy? It would be great if you could write your working code here. Thanks

**Comment by quantitative-technologies** [comment]
I was going to open a new bug report. However, I believe the bug is essentially the one here.

I am using ccxt 4.1.95 (on Linux). 

My application has a `TaskGroup` that makes some async watch_* calls.

After the TaskGroup is cancelled, and I call the `close()` method of the exchanges the following exception is _swallowed_ by ccxt:

```
Exception in callback Future.race.<locals>.callback(<Task cancell...tasks.py:425>>) at /home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/base/ws/future.py:20                   
handle: <Handle Future.race.<locals>.callback(<Task cancell...tasks.py:425>>) at /home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/base/ws/future.py:20>                        
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run                                                                                                                                             
    self._context.run(self._callback, *self._args)
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/base/ws/future.py", line 21, in callback
    exception = done.exception()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 454, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 540, in _wait
    await waiter
asyncio.exceptions.CancelledError
Exception in callback Future.race.<locals>.callback(<Task cancell...tasks.py:425>>) at /home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/base/ws/future.py:20
handle: <Handle Future.race.<locals>.callback(<Task cancell...tasks.py:425>>) at /home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/base/ws/future.py:20>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/home/user/.virtualenvs/binance-bot2/lib/python3.12/site-packages/ccxt/async_support/base/ws/future.py", line 21, in callback
    exception = done.exception()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 454, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 540, in _wait
    await waiter
asyncio.exceptions.CancelledError
binanceusdm requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7a4dbcec3e00>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7a4dbcee3290>, 1545.449824698)]']
connector: <aiohttp.connector.TCPConnector object at 0x7a4dbdbcd970>
Future exception was never retrieved
future: <Future finished exception=NetworkError(1006)>
ccxt.base.errors.NetworkError: 1006

```

**Comment by kroitor** [comment]
Hello @brook-w, closing this during a cleanup — this is the documented contract of the async python flavor rather than a bug: an async exchange instance owns an aiohttp session and event loop resources, and await exchange.close() at the end of the program is required to release them, the warning you saw is aiohttp reporting an unclosed session when that call is skipped. The close side behavior has also been hardened since this report. If close() itself leaves resources behind on a current version, a fresh issue with a reproduction would be very welcome. Thanks for the report!
