### ISSUE TITLE
fetch_positions() error with gate

### ISSUE THREAD

**Issue by williamvgam** [ccxt/ccxt#20445]
### Operating System

window

### CCXT Version

4.1.94

### Description

1. Position could be printed at first connection , and then  client.future  always be pending if position has no change . I think this may  not be consistent with  setting :  'newUpdates': False,
2. After changing position (by placing orders manuanlly ), client.future get return but come with TypeError: sequence index must be integer, not 'str'
for more details ,please check code and Traceback below

### Code
```
import ccxt.pro as ccxt
import asyncio
from asyncio import run,gather


print(ccxt.__version__)

exchange = getattr(ccxt, id)({
    'socksProxy': 'http://127.0.0.1:8001',
    'enableRateLimit': True,
    'newUpdates': False,
    'apiKey': api['apiKey'],
    'secret': api['secret'],
    'options': {'defaultType': 'swap'},
    'uid':str(uid)
    }) 
exchange.set_sandbox_mode(True)

async def main():
    symbols = ['BTC/USDT:USDT']  
    while (True):
        position = await exchanges[1].watch_positions(symbols)
        print(position)

if __name__=='__main__':
    run(main())
```

```
C:\Users\SAMSUNG\anaconda3\python.exe D:\ccxt_project230717\Arbitrage\test.py 
4.1.94
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000025F8D7D3700>
...
connector: <aiohttp_socks.connector.ProxyConnector object at 0x0000025F8D79EAF0>
[{'info': {'value': '392.59341', 'leverage': '0', 'mode': 'single', 'realised_point': '0', 'contract': 'BTC_USDT',  ...]
Traceback (most recent call last):
  File "D:\ccxt_project230717\Arbitrage\test.py", line 41, in <module>
    run(main())
  File "C:\Users\SAMSUNG\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\SAMSUNG\anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\ccxt_project230717\Arbitrage\test.py", line 37, in main
    a = await exchanges[1].watch_positions(symbols)
  File "C:\Users\SAMSUNG\anaconda3\lib\site-packages\ccxt\pro\gate.py", line 748, in watch_positions
    return self.filter_by_symbols_since_limit(self.positions, symbols, since, limit, True)
  File "C:\Users\SAMSUNG\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 4083, in filter_by_symbols_since_limit
    result = self.filter_by_array(array, 'symbol', symbols, False)
  File "C:\Users\SAMSUNG\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3313, in filter_by_array
    if self.in_array(objects[i][key], values):
  File "C:\Users\SAMSUNG\anaconda3\lib\site-packages\ccxt\async_support\base\ws\cache.py", line 48, in __getitem__
    return deque[item]
TypeError: sequence index must be integer, not 'str'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000025F8D79EE80>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000025F8D79ED90>

进程已结束，退出代码为 1  

```

**Comment by carlosmiei** [comment]
Hello @williamvgam, thanks for reporting it we will take a look asap.
