### ISSUE TITLE
how to close position in bingx exchange

### ISSUE THREAD

**Issue by tbehzad76** [ccxt/ccxt#20530]
### Operating System

ubuntu

### Programming Languages

Python

### CCXT Version

4.1.90

### Description

Please help me!
Function "close_all_positions()" works fine for me but "close_position()" not working
```python
Traceback (most recent call last):
  File "/$HOME/$USER/tradingBot/market.py", line 15, in <module>
    create = bingx.close_position(symbol=symbol, side='buy')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/$HOME/$USER/tradingBot/.venv/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3861, in close_position
    raise NotSupported(self.id + ' closePositions() is not supported yet')
ccxt.base.errors.NotSupported: bingx closePositions() is not supported yet
```

### Code

```python
import ccxt
import config


bingx = ccxt.bingx({
    'apiKey': config.BINGX_API_KEY,
    'secret': config.BINGX_SECRET_KEY,
    'proxies': {
        'https': '127.0.0.1:2081',
    },
})
symbol = 'DOGE/USDT:USDT'

close = bingx.close_position(symbol=symbol, side='buy')

print(close)
````

**Comment by carlosmiei** [comment]
Hello @tbehzad76, we just merged a PR that adds `closePosition` to bingx. It should be available soon!
