### ISSUE TITLE
TypeError in bitget.parseOrder due to Response String not being Parsed to Object

### ISSUE THREAD

**Issue by alxndalexeev** [ccxt/ccxt#20555]
### Operating System

Ubuntu

### Programming Languages

JavaScript

### CCXT Version

4.1.98

### Description

Call to **.fetchOrder()** leads to the following error.

```
TypeError: Cannot use 'in' operator to search for 'posSide' in undefined
    at bitget.parseOrder (/sampo/node_modules/ccxt/dist/cjs/src/bitget.js:3849:44)
    at bitget.fetchOrder (/sampo/node_modules/ccxt/dist/cjs/src/bitget.js:4984:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

### Code

**Proposed Solution:**

It appears that the **response** variable is a string and needs to be parsed into an object before accessing its properties. Modify **/dist/cjs/src/bitget.js** around line 5020 as follows:

```
let responseObject;

// Check if response is a string and parse it
if (typeof response === 'string') {
    try {
        responseObject = JSON.parse(response);
    } catch (error) {
        console.error('Error parsing JSON:', error);
        // TODO: Decide on how to handle parsing error
        return; // or other error handling
    }
} else {
    // If response is already an object
    responseObject = response;
}

// Now you can safely access the data property
const data = this.safeValue(responseObject, 'data');

```

This is fixed this issue for me.

**Comment by Dan-krm** [comment]
Hi @alxndalexeev I opened a pull request that should resolve this issue
