### ISSUE TITLE
Coinbase Advanced Trading integration question

### ISSUE THREAD

**Issue by mupett** [ccxt/ccxt#20583]
### Operating System

Linux 0a526f9203d2 5.14.0-391.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 28 20:35:49 UTC 2023 x86_64 GNU/Linux

### Programming Languages

Python

### CCXT Version

ccxt==4.1.98

### Description

Hello,
please advise if Coinbase Advanced Trading is implemented.
If I use coinbasepro it ask me for a passprase wich is anymore not requested
If I use coinbase it cannot open the orderbook.

Kind Regards

023-12-27 17:12:07,808 - freqtrade.exchange.exchange - INFO - Using CCXT 4.1.98
2023-12-27 17:12:07,812 - freqtrade.exchange.exchange - INFO - Using Exchange "Coinbase Pro"
2023-12-27 17:12:08,441 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Coinbasepro'...
2023-12-27 17:12:08,475 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential". Retrying still for 4 times.
2023-12-27 17:12:08,575 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential". Retrying still for 3 times.
2023-12-27 17:12:08,675 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential". Retrying still for 2 times.
2023-12-27 17:12:08,775 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential". Retrying still for 1 times.
2023-12-27 17:12:08,876 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential". Giving up.
2023-12-27 17:12:08,876 - freqtrade.commands.trade_commands - ERROR - Could not get balance due to AuthenticationError. Message: coinbasepro requires "password" credential
2023-12-27 17:12:08,876 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

OR ----------------------------------------------

2023-12-27 17:11:26,077 - freqtrade.exchange.exchange - INFO - Using CCXT 4.1.98
2023-12-27 17:11:26,083 - freqtrade.exchange.exchange - INFO - Using Exchange "Coinbase"
2023-12-27 17:11:29,990 - freqtrade.commands.trade_commands - ERROR - Orderbook not available for Coinbase.
2023-12-27 17:11:29,991 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

### Code

```
  

```

**Comment by mupett** [comment]
Python 3.11.6 (main, Nov 29 2023, 04:30:13) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
change.requiredCredentials)>>> exchange = ccxt.coinbasepro()
>>> print(exchange.requiredCredentials)
{'apiKey': True, 'secret': True, 'uid': False, 'login': False, 'password': True, 'twofa': False, 'privateKey': False, 'walletAddress': False, 'token': False}
>>> exchange.check_required_credentials()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3505, in check_required_credentials
    raise AuthenticationError(self.id + ' requires "' + key + '" credential')
ccxt.base.errors.AuthenticationError: coinbasepro requires "apiKey" credential

**Comment by Dan-krm** [comment]
Hi @mupett the advanced trade endpoints are supported through the coinbase class:
```
coinbase.fetchOrderBook (BTC/USDT, 3)
2024-01-03T04:04:43.096Z iteration 0 passed in 540 ms

{
  symbol: 'BTC/USDT',
  bids: [
    [ 45227.7, 0.0552517 ],
    [ 45226.88, 0.05525221 ],
    [ 45225.29, 0.22101863 ]
  ],
  asks: [
    [ 45232.04, 0.05524641 ],
    [ 45232.89, 0.04576791 ],
    [ 45232.9, 0.02103489 ]
  ],
  timestamp: 1704254683848,
  datetime: '2024-01-03T04:04:43.848Z'
}
```

Let me know if you have any other questions

**Comment by mupett** [comment]
Hello, did you use coinbase or coinbasepro profile in the output you sent earlier?

**Comment by Dan-krm** [comment]
> Hello, did you use coinbase or coinbasepro profile in the output you sent earlier?

coinbase

**Comment by Dan-krm** [comment]
@mupett coinbasepro works as well, unfortunately coinbase is deprecating coinbasepro so you can't create new API keys there while specifying a password. Private methods like the `get_balances` freqtrade method on coinbasepro require a password. 

So essentially if you didn't create an API key on coinbasepro before they started deprecating it you can't use the private methods on coinbasepro.

![image](https://github.com/ccxt/ccxt/assets/83686770/afab1398-884b-4f54-92c0-d32773327aa7)

![image](https://github.com/ccxt/ccxt/assets/83686770/e5fea440-b75a-4a24-bb83-86a03b371a13)

![image](https://github.com/ccxt/ccxt/assets/83686770/3911fb22-b81a-4d5f-81a0-488b5ccca1ec)

**Comment by mupett** [comment]
Thanks Dan-krm for the clarification. Do you have plan to fix this behaviour?

Regards

**Comment by Dan-krm** [comment]
> Thanks Dan-krm for the clarification. Do you have plan to fix this behaviour?
> 
> Regards

Unfortunately there is nothing CCXT can do to fix this behavior it's happening on the exchange side because coinbase is deprecating coinbase pro
