### ISSUE TITLE
CCXT generates its own errors and I cannot catch them in my exceptions

### ISSUE THREAD

**Issue by Ccon2r** [ccxt/ccxt#20638]
### Operating System

Ubuntu 20

### CCXT Version

4.1.96

### Description

I trade each ticker as a separate task. There is exception handling inside tasks. But when errors occur, CCXT generates its own errors and I cannot catch them in my exceptions, and running tasks are closed.

### Code

Running tasks:
```
async def update_ticker(exchange, strategy, symbols):
    
     data = [] # Initialize an empty list to store data
     tasks = [fetch_ticker(exchange, strategy, symbol, data) for symbol in symbols]
     await asyncio.gather(*tasks)
```
CCXT function in task:
     `trades = await exchange.watch_trades(symbol)`

Errors after which tasks stop working:

```
Exception in callback Future.race.<locals>.callback(<Task finishe...06)>}, set())>) at /usr/local/lib/python3.8/dist-packages/ccxt/async_support/ base/ws/future.py:20
handle: <Handle Future.race.<locals>.callback(<Task finishe...06)>}, set())>) at /usr/local/lib/python3.8/dist-packages/ccxt/async_support /base/ws/future.py:20>
Traceback (most recent call last):
   File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
     self._context.run(self._callback, *self._args)
   File "/usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py", line 24, in callback
     first_result = list(complete)[0].result()
   File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
     self._context.run(self._callback, *self._args)
   File "/usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py", line 24, in callback
     first_result = list(complete)[0].result()
ccxt.base.errors.NetworkError: 1006

```

**Comment by sc0Vu** [comment]
@Ccon2r

The error probably was swallowed. Can you paste more code snippet so we can reproduce?

**Comment by Ccon2r** [comment]
All calls have exceptions, that's how it is

```
async def get_last_price(exchange, symbol):
    try:
        trades = await exchange.watch_trades(symbol)
        if trades:
            return trades
    except Exception as e:
        print(f"{current_time()} {symbol} Error watch_ticker : {e}")
    
    return None
```

According to my observations, the error occurs when there are network errors (ccxt.base.errors.NetworkError: 1006). And error messages are displayed for each task cumulatively in this form:

```
Exception in callback Future.race.<locals>.callback(<Task finishe...06)>}, set())>) at /usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py:20
handle: <Handle Future.race.<locals>.callback(<Task finishe...06)>}, set())>) at /usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py:20>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py", line 24, in callback
    first_result = list(complete)[0].result()
ccxt.base.errors.NetworkError: 1006
Exception in callback Future.race.<locals>.callback(<Task finishe...06)>}, set())>) at /usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py:20
handle: <Handle Future.race.<locals>.callback(<Task finishe...06)>}, set())>) at /usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py:20>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py", line 24, in callback
    first_result = list(complete)[0].result()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py", line 24, in callback
    first_result = list(complete)[0].result()
ccxt.base.errors.NetworkError: 1006
Exception in callback Future.race.<locals>.callback(<Task finishe...06)>}, set())>) at /usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py:20
handle: <Handle Future.race.<locals>.callback(<Task finishe...06)>}, set())>) at /usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py:20>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py", line 24, in callback
    first_result = list(complete)[0].result()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py", line 24, in callback
    first_result = list(complete)[0].result()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/ccxt/async_support/base/ws/future.py", line 24, in callback
    first_result = list(complete)[0].result()
ccxt.base.errors.NetworkError: 1006
```

**Comment by Ccon2r** [comment]
@sc0Vu 
> @Ccon2r
> 
> The error probably was swallowed. Can you paste more code snippet so we can reproduce?

This code can show error

```
import ccxt.pro as ccxtpro
import asyncio

async def observe_trades(exchange, symbol):

    while True:
        try:
            trades = await exchange.watch_trades(symbol)
            print(">trades")

        except ccxtpro.NetworkError as e:
            print(f"Network error in watch_trades: {e}")
        except ccxtpro.ExchangeError as e:
            print(f"Exchange error in watch_trades: {e}")
        except ccxtpro.BaseError as e:
            print(f"CCXT base error in watch_trades: {e}")
        except Exception as e:
            print(f"Other error in watch_trades: {e}")

async def observe_orderbooks(exchange, symbol):

    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol)
            print(">orderbook")
                
        except ccxtpro.NetworkError as e:
            print(f"Network error in watch_order_book: {e}")
        except ccxtpro.ExchangeError as e:
            print(f"Exchange error in watch_order_book: {e}")
        except ccxtpro.BaseError as e:
            print(f"CCXT base error in watch_order_book: {e}")
        except Exception as e:
            print(f"Other error in watch_order_book: {e}")

async def main():

    exchange_name = 'binance'

    exchange_class = getattr(ccxtpro, exchange_name)
    exchange = exchange_class()    
    markets = await exchange.load_markets()
    symbollist = [symbol for symbol in markets if symbol.endswith('/USDT:USDT')]

    tasks = []
    
    for symbol in symbollist:
        tasks.append(observe_trades(exchange, symbol))
        tasks.append(observe_orderbooks(exchange, symbol))

    await asyncio.gather(*tasks)


asyncio.run(main())
```

**Comment by hi-bingo** [comment]
It's the same bug in this issue: https://github.com/ccxt/ccxt/issues/20412. 
I'm also waiting for the pr to be merged: https://github.com/ccxt/ccxt/pull/20563.

**Comment by Ccon2r** [comment]
As this bug fixed [completed](https://github.com/ccxt/ccxt/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/ccxt/ccxt/pull/20563
How can I get this fix in my version of CCXT?

**Comment by Ccon2r** [comment]
> It's the same bug in this issue: #20412. I'm also waiting for the pr to be merged: #20563.

As this bug fixed [completed](https://github.com/ccxt/ccxt/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/ccxt/ccxt/pull/20563
How can I get this fix in my version of CCXT?

**Comment by Ccon2r** [comment]
@carlosmiei
As this bug fixed [completed](https://github.com/ccxt/ccxt/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/ccxt/ccxt/pull/20563
How can I get this fix in my version of CCXT?

**Comment by carlosmiei** [comment]
@Ccon2r We will release a new version shortly, and you will need to update to the latest version.
