### ISSUE TITLE
Kraken "Too many requests" not caught 

### ISSUE THREAD

**Issue by tvb** [ccxt/ccxt#20648]
### Operating System

macOS 14.2.1 (23C71)

### Programming Languages

Python

### CCXT Version

4.1.98

### Description

When executing `fetch_ohlcv()` with pagination `True` Kraken at some point returns HTTP 200, but with the message `ResponseBody: {"error":["EGeneral:Too many requests"]}`. I believe this is an error ccxt should be catching.

### Code

```
    try:
        # Get data
        data = exchange.fetch_ohlcv(symbol=symbol, timeframe=timeframe, since=since, limit=limit, params={"paginate": True})
        # Convert ms to seconds, so we can use time.sleep() for multiple calls
        time.sleep(exchange.rateLimit / 1000)
    except ccxt.RequestTimeout as e:
        print(f"[{datetime.now()}] Request timeout: {type(e).__name__, str(e)}")
        time.sleep(exchange.rateLimit / 1000)
    except ccxt.DDoSProtection as e:
        print(f"[{datetime.now()}] DDoS Protection triggered: {type(e).__name__, str(e)}")
        time.sleep(exchange.rateLimit / 1000)
    except ccxt.ExchangeNotAvailable as e:
        print(f"[{datetime.now()}] Exchange not available: {type(e).__name__, str(e)}")
        time.sleep(60)
    except ccxt.NetworkError as e:
        print(f"[{datetime.now()}] Network error: {type(e).__name__, str(e)}")
        time.sleep(60)
    except Exception as e:
        print(f"[{datetime.now()}] Failed to load markets from {exchange.name}: {str(e)}")
        raise

```

Results in:

```
fetch Request: kraken GET https://api.kraken.com/0/public/OHLC?pair=1INCHEUR&interval=1&since=1704219374 RequestHeaders: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: kraken GET https://api.kraken.com/0/public/OHLC?pair=1INCHEUR&interval=1&since=1704219374 200 ResponseHeaders: {'Date': 'Wed, 03 Jan 2024 18:16:22 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'cache-control': 'public, max-age=2', 'vary': 'accept-encoding', 'x-trace-id': 'ac110004018cd08a6f9a001e26232118', 'content-encoding': 'gzip', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'pcnvkqd0d3sl-pad': 'a9wP#5MqnS9n-h*c&EP|RNslUP*Rwpj+%', 'x-proxy': 'gateway', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Last-Modified': 'Wed, 03 Jan 2024 18:16:22 GMT', 'CF-Cache-Status': 'MISS', 'Set-Cookie': '__cf_bm=KUZ6mP81IllpaNWTTUI6cGJcPL.Ajryv5ya0LUUI2e4-1704305782-1-AXFKmKJT++wc/WxLKE/Uxkh9iRlrlkYvMCvM6dVlvK7gQ56KmGj9MIchqyNHRiNi4AWWl3oyR8pxg4g9XPDgiwc=; path=/; expires=Wed, 03-Jan-24 18:46:22 GMT; domain=.kraken.com; HttpOnly; Secure; SameSite=None', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '83fd3b853a06b972-AMS'} ResponseBody: {"error":[],"result":{"1INCHEUR":[[1704262620,"0.435","0.435","0.435","0.435","0.000","0.00000000",0],[1704262680,"0.435","0.435","0.435","0.435","0.000","0.00000000",0],[1704262740,"0.435","0.435","0.435","0.435","0.000","0.00000000",0],[1704262800,"0.435","0.435","0.435","0.435","0.000","0.00000000",0],

<truncated>

[1704305700,"0.391","0.391","0.391","0.391","0.000","0.00000000",0],[1704305760,"0.391","0.391","0.391","0.391","0.000","0.00000000",0]],"last":1704305700}}

fetch Request: kraken GET https://api.kraken.com/0/public/OHLC?pair=1INCHEUR&interval=1&since=1704262574 RequestHeaders: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: kraken GET https://api.kraken.com/0/public/OHLC?pair=1INCHEUR&interval=1&since=1704262574 200 ResponseHeaders: {'Date': 'Wed, 03 Jan 2024 18:16:23 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'content-encoding': 'gzip', 'x-trace-id': 'ac110003018cd08a7386001e21e9f618', 'cache-control': 'no-store', 'vary': 'accept-encoding', 'e_r6biy9l-pad': 'exFb+dHYt8xDEd++rof6vm|6GQ|SU_a+t', 'x-proxy': 'gateway', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Last-Modified': 'Wed, 03 Jan 2024 18:16:23 GMT', 'CF-Cache-Status': 'MISS', 'Set-Cookie': '__cf_bm=xlRcXKNL8Iygk3qlvZJY9e7blmZJXamYxdIT_fcNeg0-1704305783-1-AbWLn5WuIhZPClx5UQOagTWqED4XBwbGipjUm9rzM9Gim+A3OgSFwLbFkBDo85BcKb9+tLPp/eZ8LgbZ1CmRGjU=; path=/; expires=Wed, 03-Jan-24 18:46:23 GMT; domain=.kraken.com; HttpOnly; Secure; SameSite=None', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '83fd3b8b7d77b972-AMS'} ResponseBody: {"error":["EGeneral:Too many requests"]}
[2024-01-03 19:16:23.808067] Failed to load markets from Kraken: can only concatenate list (not "NoneType") to list
Traceback (most recent call last):
  File "/<stripped>/get_ohlcv.py", line 249, in <module>
    main()
  File "/<stripped>/get_ohlcv.py", line 240, in main
    fetch_data(exchange=exchange, symbol=symbol, timeframe='1m', limit=500, file_name=file_name)
  File "/<stripped>/get_ohlcv.py", line 137, in fetch_data
    data = exchange.fetch_ohlcv(symbol=symbol, timeframe=timeframe, since=since, limit=limit, params={"paginate": True})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<stripped>/python3.12/site-packages/ccxt/kraken.py", line 949, in fetch_ohlcv
    return self.fetch_paginated_call_deterministic('fetchOHLCV', symbol, since, limit, timeframe, params, 720)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<stripped>/python3.12/site-packages/ccxt/base/exchange.py", line 4653, in fetch_paginated_call_deterministic
    result = self.array_concat(result, results[i])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<stripped>/python3.12/site-packages/ccxt/base/exchange.py", line 1010, in array_concat
    return a + b
           ~~^~~
TypeError: can only concatenate list (not "NoneType") to list
```

**Comment by samgermain** [comment]
Can you give your full code? It seems like the snippet that you provided might be within some sort of loop?

**Comment by rolandkofler** [comment]
Have the same problem here is the code
```
import ccxt
name = 'kraken'
exchange = getattr(ccxt, name)()


for i in range(1000000):
    try:
        ohlcv = exchange.fetch_ohlcv(symbol="BTC/EUR", timeframe='1m', since=None, limit=None)
        # print a dot for each call
        print(".", end="", flush=True)
    except Exception as e:
        print(f"At iteration {i} Error fetching OHLCV: {e}")
```
example output:
```
.......................................................................................................At iteration 103 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
....At iteration 108 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
....At iteration 113 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
....At iteration 118 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
At iteration 119 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
...At iteration 123 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
...................At iteration 143 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
....At iteration 148 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
....At iteration 153 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
....At iteration 158 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
..............At iteration 173 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
....At iteration 178 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
At iteration 179 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
...At iteration 183 Error fetching OHLCV: kraken {"error":["EGeneral:Too many requests"]}
..................
```

**Comment by rolandkofler** [comment]
How is this possible with API throtteling enabled?
