### ISSUE TITLE
Cannot gracefully interrupt/shutdown a script with ccxt and websockets

### ISSUE THREAD

**Issue by proschowsky** [ccxt/ccxt#20659]
### Programming Languages

Python

### CCXT Version

4.2.4

### Description

I have a script that is using ccxt.pro and watch_order_book_for_symbols function. 

The script is running fine, but when I interrupt it (CTRL-C), it creates exceptions that I am not able to catch. 
If I am only watching 5 symbols, then it just creates a few exceptions. But if I am watching 50-100 symbols, then it will create 4000+ lines of exceptions and stack traces. 

Is this an issue with CCXT or can my code be improved to catch the exceptions and do a graceful termination of the script?

### Code

```
import asyncio
import ccxt.pro


async def main():
    exchange = ccxt.pro.binance()
    markets = await exchange.load_markets()
    symbols = list(filter(lambda s: exchange.market(s)["spot"], markets.keys()))[:5]
    print(f"Watching {len(symbols)} symbols on {exchange.id}")
    try:
        await watch(exchange, symbols) 
    except Exception as e:
        print(f"Exception in main(): {e}")
    await exchange.close()

async def watch(exchange, symbols):
    while (True):
        try:
            orderbook = await exchange.watch_order_book_for_symbols(list(symbols), limit=20)
            print(f"New orderbook from {orderbook['symbol']}")
        except Exception as e:
            print(f"Exception in watch(): {e}")
            break

asyncio.run(main())
```

Output from running `python keyboardint.py >interrupt.run 2>&1`

```
Exception in callback Future.race.<locals>.callback(<Task cancell...tasks.py:394>>) at /home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py:20
handle: <Handle Future.race.<locals>.callback(<Task cancell...tasks.py:394>>) at /home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py:20>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/dev/projects/cbot/cbot/keyboardint.py", line 11, in main
    await watch(exchange, symbols)
  File "/home/dev/projects/cbot/cbot/keyboardint.py", line 19, in watch
    orderbook = await exchange.watch_order_book_for_symbols(list(symbols), limit=20)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/pro/binance.py", line 229, in watch_order_book_for_symbols
    orderbook = await self.watch_multiple(url, messageHashes, message, messageHashes, subscription)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 125, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py", line 21, in callback
    exception = done.exception()
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 423, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 530, in _wait
    await waiter
asyncio.exceptions.CancelledError
Watching 5 symbols on binance
New orderbook from ETH/BTC
New orderbook from LTC/BTC
New orderbook from ETH/BTC
New orderbook from BNB/BTC
New orderbook from NEO/BTC
New orderbook from BNB/BTC
New orderbook from QTUM/ETH
New orderbook from LTC/BTC
New orderbook from BNB/BTC
New orderbook from ETH/BTC
New orderbook from BNB/BTC
New orderbook from BNB/BTC
New orderbook from BNB/BTC
New orderbook from BNB/BTC
New orderbook from BNB/BTC
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/dev/projects/cbot/cbot/keyboardint.py", line 11, in main
    await watch(exchange, symbols) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/projects/cbot/cbot/keyboardint.py", line 19, in watch
    orderbook = await exchange.watch_order_book_for_symbols(list(symbols), limit=20)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/pro/binance.py", line 229, in watch_order_book_for_symbols
    orderbook = await self.watch_multiple(url, messageHashes, message, messageHashes, subscription)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/projects/cbot/cbot/keyboardint.py", line 25, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 125, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9157332090>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f915734c440>, 176873.784739893)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7f915734c2f0>, 176874.091063876)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7f91574ebe70>, 176875.913642884), (<aiohttp.client_proto.ResponseHandler object at 0x7f915734cad0>, 176875.982458022), (<aiohttp.client_proto.ResponseHandler object at 0x7f915734cd70>, 176876.058116976), (<aiohttp.client_proto.ResponseHandler object at 0x7f915734d010>, 176876.102329172), (<aiohttp.client_proto.ResponseHandler object at 0x7f915734d240>, 176876.140672968)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f9159fb5590>
```

**Comment by carlosmiei** [comment]
Hello @proschowsky, thanks for reporting it, we just merged a fix and that issue should be fixed in the next release in a few minutes.

**Comment by carlosmiei** [comment]
@proschowsky Can you please update to the latest version 4.2.5 and try again?

**Comment by proschowsky** [comment]
I tried the latest version. It is still giving me a lot of exceptions. 

```
Exception in callback Future.race.<locals>.callback(<Task cancell...tasks.py:394>>) at /home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py:20
handle: <Handle Future.race.<locals>.callback(<Task cancell...tasks.py:394>>) at /home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py:20>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/dev/projects/cbot/cbot/keyboardint.py", line 11, in main
    await watch(exchange, symbols)
  File "/home/dev/projects/cbot/cbot/keyboardint.py", line 19, in watch
    orderbook = await exchange.watch_order_book_for_symbols(list(symbols), limit=20)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/pro/binance.py", line 229, in watch_order_book_for_symbols
    orderbook = await self.watch_multiple(url, messageHashes, message, messageHashes, subscription)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 125, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py", line 21, in callback
    exception = done.exception()
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 423, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 530, in _wait
    await waiter
asyncio.exceptions.CancelledError
Watching 5 symbols on binance
New orderbook from ETH/BTC
New orderbook from LTC/BTC
New orderbook from ETH/BTC
New orderbook from NEO/BTC
New orderbook from ETH/BTC
New orderbook from QTUM/ETH
New orderbook from ETH/BTC
New orderbook from ETH/BTC
New orderbook from BNB/BTC
New orderbook from ETH/BTC
New orderbook from ETH/BTC
New orderbook from BNB/BTC
New orderbook from LTC/BTC
New orderbook from ETH/BTC
New orderbook from BNB/BTC
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/dev/projects/cbot/cbot/keyboardint.py", line 11, in main
    await watch(exchange, symbols) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/projects/cbot/cbot/keyboardint.py", line 19, in watch
    orderbook = await exchange.watch_order_book_for_symbols(list(symbols), limit=20)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/pro/binance.py", line 229, in watch_order_book_for_symbols
    orderbook = await self.watch_multiple(url, messageHashes, message, messageHashes, subscription)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/projects/cbot/cbot/keyboardint.py", line 25, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 125, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f70a37be1d0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f70a2de00c0>, 200027.999104985)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7f70a2de0280>, 200028.833907334)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7f70a377be00>, 200030.808180327), (<aiohttp.client_proto.ResponseHandler object at 0x7f70a2de0b40>, 200030.903823002), (<aiohttp.client_proto.ResponseHandler object at 0x7f70a2de0de0>, 200030.954531676), (<aiohttp.client_proto.ResponseHandler object at 0x7f70a2de1080>, 200030.982037768), (<aiohttp.client_proto.ResponseHandler object at 0x7f70a2de12b0>, 200031.060548032)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f70a37be0d0>
```

I tried to modify my script to also listen for the `asyncio.exceptions.CancelledError` :

```
import asyncio
import ccxt.pro


async def main():
    exchange = ccxt.pro.binance()
    markets = await exchange.load_markets()
    symbols = list(filter(lambda s: exchange.market(s)["spot"], markets.keys()))[:5]
    print(f"Watching {len(symbols)} symbols on {exchange.id}")
    try:
        await watch(exchange, symbols) 
    except Exception as e:
        print(f"Exception in main(): {e}")
    await exchange.close()

async def watch(exchange, symbols):
    while (True):
        try:
            orderbook = await exchange.watch_order_book_for_symbols(list(symbols), limit=20)
            print(f"New orderbook from {orderbook['symbol']}")
        except asyncio.exceptions.CancelledError as e:
            print(f"CancelledError in watch(): {e}")
            break
        except Exception as e:
            print(f"Exception in watch(): {e}")
            break

asyncio.run(main())
```

When running, it gives this result:

```
Exception in callback Future.race.<locals>.callback(<Task cancell...tasks.py:394>>) at /home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py:20
handle: <Handle Future.race.<locals>.callback(<Task cancell...tasks.py:394>>) at /home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py:20>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dev/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py", line 21, in callback
    exception = done.exception()
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 423, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 530, in _wait
    await waiter
asyncio.exceptions.CancelledError
Watching 5 symbols on binance
New orderbook from ETH/BTC
New orderbook from LTC/BTC
New orderbook from QTUM/ETH
New orderbook from ETH/BTC
New orderbook from BNB/BTC
New orderbook from ETH/BTC
New orderbook from NEO/BTC
New orderbook from ETH/BTC
New orderbook from BNB/BTC
New orderbook from QTUM/ETH
New orderbook from LTC/BTC
New orderbook from BNB/BTC
New orderbook from NEO/BTC
CancelledError in watch(): 
Future exception was never retrieved
future: <Future finished exception=NetworkError(1006)>
ccxt.base.errors.NetworkError: 1006
Future exception was never retrieved
future: <Future finished exception=NetworkError(1006)>
ccxt.base.errors.NetworkError: 1006
Future exception was never retrieved
future: <Future finished exception=NetworkError(1006)>
ccxt.base.errors.NetworkError: 1006
Future exception was never retrieved
future: <Future finished exception=NetworkError(1006)>
ccxt.base.errors.NetworkError: 1006
Future exception was never retrieved
future: <Future finished exception=NetworkError(1006)>
ccxt.base.errors.NetworkError: 1006
```

The amount of ´ccxt.base.errors.NetworkError´erros matches the number of symbols I am watching.

**Comment by carlosmiei** [comment]
@proschowsky But can you catch the error if you wrap .close() around a try-catch?

**Comment by proschowsky** [comment]
I tried with 
```
    try:
        await exchange.close()
    except:
        print("Exception while closing exchange...")
```
but it gives the same output.

I did another test where the script will stop after having received 10 orderbooks.  This eliminates the `asyncio.exceptions.CancelledError` exception but still gives me the `Future exception was never retrieved`
```
import asyncio
import ccxt.pro

async def main():
    try:
        exchange = ccxt.pro.binance()
        markets = await exchange.load_markets()
        symbols = list(filter(lambda s: exchange.market(s)["spot"], markets.keys()))[:5]

        print(f"Watching {len(symbols)} symbols on {exchange.id}")
        for i in range(10):
            orderbook = await exchange.watch_order_book_for_symbols(list(symbols), limit=20)
            print(f"New orderbook from {orderbook['symbol']}")

        await exchange.close()
    except:
        print("Exception in main()")
        
asyncio.run(main())
```

```
Watching 5 symbols on binance
New orderbook from ETH/BTC
New orderbook from LTC/BTC
New orderbook from BNB/BTC
New orderbook from BNB/BTC
New orderbook from NEO/BTC
New orderbook from QTUM/ETH
New orderbook from LTC/BTC
New orderbook from ETH/BTC
New orderbook from BNB/BTC
New orderbook from NEO/BTC
Future exception was never retrieved
future: <Future finished exception=NetworkError(1006)>
ccxt.base.errors.NetworkError: 1006
Future exception was never retrieved
future: <Future finished exception=NetworkError(1006)>
ccxt.base.errors.NetworkError: 1006
Future exception was never retrieved
future: <Future finished exception=NetworkError(1006)>
ccxt.base.errors.NetworkError: 1006
Future exception was never retrieved
future: <Future finished exception=NetworkError(1006)>
ccxt.base.errors.NetworkError: 1006
```

**Comment by carlosmiei** [comment]
@proschowsky Yeah so it's still not working as expected, we will check it again. Thanks.

**Comment by carlosmiei** [comment]
@proschowsky can you please update and try again? I think it's fully fixed now

**Comment by proschowsky** [comment]
If I don't cancel the script, then everything works fine and all the `ccxt.base.errors.NetworkError` are gone. 

If I cancel the script, then I get this error:

```
Watching 5 symbols on binance
New orderbook from ETH/BTC
New orderbook from ETH/BTC
New orderbook from LTC/BTC
New orderbook from ETH/BTC
New orderbook from BNB/BTC
New orderbook from NEO/BTC
New orderbook from QTUM/ETH
New orderbook from BNB/BTC
New orderbook from BNB/BTC
^CCancelledError in watch():
Exception in callback Future.race.<locals>.callback(<Task finishe...led>}, set())>) at /home/morten/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py:25
handle: <Handle Future.race.<locals>.callback(<Task finishe...led>}, set())>) at /home/morten/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py:25>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/morten/.cache/pypoetry/virtualenvs/cbot-iTQe90Lg-py3.11/lib/python3.11/site-packages/ccxt/async_support/base/ws/future.py", line 51, in callback
    first_result = first.result()
                   ^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

I had a quick look at the `ccxt/async_support/base/ws/future.py` and it seems like the code is attempting to call result() on a cancelled future. 
When the error occurs, all futures in `complete` are in `CANCELLED` state and the `future._state` is also `CANCELLED`.

**Comment by proschowsky** [comment]
The script is running in the terminal and cancelled/interrupted by using Ctrl + C

The script I shared is just an example, but I have a few longer scripts that I want to cancel/interrupt.

**Comment by pcriadoperez** [comment]
Hi @proschowsky , did this solve your issue?

**Comment by proschowsky** [comment]
I did not have a change to test it out. The previous changes to ccxt solved the majority of the bugs, so I can live with the single error message that is left

**Comment by cccchuck** [comment]
I use `asyncio.sleep(10)` to wait task done, it's so stupid but useful 😢

**Comment by kroitor** [comment]
Hello @proschowsky, closing this during a cleanup — the storm itself was fixed back in January 2024 within a day of your report and by your own follow up the remaining single message was livable, that residue is asyncio's cancelled task noise when SIGINT races the event loop teardown rather than a leak. For a fully clean exit the pattern from the thread stands: trap the interrupt, let the watch loop wind down, await exchange.close(), then stop the loop. The teardown path has also been hardened further since the 4.2 era. If an interrupt still produces an exception flood on a current version, a fresh issue with the traceback would be very welcome. Thanks for the patient back and forth back then!
