### ISSUE TITLE
bybit fetchTickers() failing. uncaught error

### ISSUE THREAD

**Issue by Eternal-Sunshine** [ccxt/ccxt#20679]
### Operating System

Multiple OS

### Programming Languages

JavaScript

### CCXT Version

4.1.58

### Description

There is an unhandled error inside bybit fetchTickers(). 
When I start the server it runs without issue for some days. but after few days it starts failing with unhandled error in ccxt. 
Attaching below the error stacktrace. 

I am calling fetchTickers() in interval for serveral other exchanges and none of the other exchanges throws this error.
My guess is after fews days when bybit ads/remove any coin pair then this error starts to happen and is related with bybit fetchTickers exchange response parsing logic. 

Please provide some help in this regard.

### Code

```
 Error Fetching tickers for bybit BadSymbol: bybit does not have market symbol ZKFUSDT
 at bybit.market (/var/www/...../node_modules/ccxt/dist/cjs/src/bybit.js:1256:15)
 at bybit.fetchTickers (/var/www/..../node_modules/ccxt/dist/cjs/src/bybit.js:2164:38)
 at runMicrotasks (<anonymous>)
 at processTicksAndRejections (node:internal/process/task_queues:96:5)  

```

**Comment by carlosmiei** [comment]
Hello @Eternal-Sunshine, yes I think it might be related to that (the addition of a new market), do you think that you occasionally run `await exchange.loadMarkets(true)` to refresh the cache with the markets?

**Comment by Eternal-Sunshine** [comment]
yes we do force reload of the market every 6 hours to automatically sync new coin's in all ccxt instances.

**Comment by carlosmiei** [comment]
@Eternal-Sunshine Does it always happen with the same (missing) market?

**Comment by Eternal-Sunshine** [comment]
No, It happens with different symbols at different point of time.
Here is another error stack of same signature. 

``
Error Fetching tickers for bybit BadSymbol: bybit does not have market symbol ACEUSDT
at bybit.market (/var/www/.../node_modules/ccxt/dist/cjs/src/bybit.js:1256:15)
at bybit.fetchTickers (/var/www/.../node_modules/ccxt/dist/cjs/src/bybit.js:2164:38)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
``

**Comment by Eternal-Sunshine** [comment]
Can someone look at it please.
My guess is it's fix is simple. Just ignore the symbol which is throwing error and parse other coins tickers which are parsable and present in markets dictionary. 
Failing entire fetchTickers() because it is unable to parse a single coin in it is the faulty logic.

**Comment by carlosmiei** [comment]
@Eternal-Sunshine We will try to deploy a fix

**Comment by carlosmiei** [comment]
@Eternal-Sunshine Actually, I can't reproduce this issue, are you calling fetchTickers with or without symbols?

**Comment by Eternal-Sunshine** [comment]
Without symbol. 
It happens when system keeps running for sometime. Probably when exchange adds or removes a symbol. Not sure.

**Comment by carlosmiei** [comment]
@Eternal-Sunshine Can you please try to upgrade your ccxt version to the latest to see if the issue persists? right now I can't reproduce it

**Comment by kroitor** [comment]
Hello @Eternal-Sunshine 👋

Closing this during a cleanup — it's resolved in current versions, and in exactly the way you proposed: ticker parsing in `fetchTickers` now resolves market ids tolerantly (`safeMarket`/`safeSymbol`), so a symbol that bybit just listed but that isn't in your cached markets yet no longer throws `BadSymbol` and no longer fails the whole call — it's returned with a best-effort symbol and the rest parse normally. Strict validation only applies to symbols you explicitly pass in, which is the intended behavior.

Your diagnosis (new listings vs. stale market cache) was spot on, and the periodic `loadMarkets(true)` refresh you already run remains good practice for picking the new markets up properly. Since we never heard back after the upgrade suggestion in Jan 2024, we're assuming a later version solved it for you — if anything similar resurfaces on a recent release, a fresh issue with the stack trace is welcome. Thanks for the clear report! 🙏
