### ISSUE TITLE
Wrong Exception type

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2072]
Hi again. Sometimes I catch this exceptions in different excnagers and I think it should be NetworkError, not a ExchangeError. I think so, because in case of NetworkError you can just re-request later, but if it ExchangeError, you have to investigate problem. If you think other way, just close this issue. Thank you

>>:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 819, in _create_direct_connection
    traces=traces)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 706, in _resolve_host
    loop=self._loop)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/Documents/Bitcoin/project/ccxt/async/base/exchange.py", line 114, in fetch
    proxy=self.aiohttp_proxy) as response:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 779, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 319, in _request
    traces=traces
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 418, in connect
    traces=traces
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 736, in _create_connection
    traces=None
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 823, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.tidex.com:443 ssl:True [nodename nor servname provided, or not known]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/Documents/Bitcoin/project/DataRecieverThread.py", line 64, in processConnector
    await request.processRequest(connector)
  File "/Users/user/Documents/Bitcoin/project/IExchangeConnector.py", line 158, in processRequest
    self.setresult(await connector.p_accountsbalances())
  File "/Users/user/Documents/Bitcoin/project/IExchangeConnector.py", line 240, in p_accountsbalances
    return await self.__ccxtexchange.fetch_balance()
  File "/Users/user/Documents/Bitcoin/project/ccxt/async/liqui.py", line 189, in fetch_balance
    response = await self.privatePostGetInfo()
  File "/Users/user/Documents/Bitcoin/project/ccxt/async/base/exchange.py", line 92, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/user/Documents/Bitcoin/project/ccxt/async/base/exchange.py", line 132, in fetch
    self.raise_error(ExchangeError, url, method, e, None)
  File "/Users/user/Documents/Bitcoin/project/ccxt/base/exchange.py", line 275, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: tidex https://api.tidex.com/tapi POST Cannot connect to host api.tidex.com:443 ssl:True [nodename nor servname provided, or not known]

Exception:  ('tidex https://api.tidex.com/tapi POST Cannot connect to host api.tidex.com:443 ssl:True [nodename nor servname provided, or not known]',)

**Comment by alexsith** [comment]
Hello. I have new issue, almost the same:

File "/home/user/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 823, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.bibox.com:443 ssl:True [Temporary failure in name resolution]

During handling of the above exception, another exception occurred:
File "/home/user/arb/ccxt/async/base/exchange.py", line 139, in fetch
    self.raise_error(ExchangeError, url, method, e, None)
  File "/home/user/arb/ccxt/base/exchange.py", line 273, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: bibox https://api.bibox.com/v1/transfer POST Cannot connect to host api.bibox.com:443 ssl:True [Temporary failure in name resolution]

It's also should be NetworkError

Thank you
