### ISSUE TITLE
AttributeError: 'virwox' object has no attribute 'symbol'

### ISSUE THREAD

**Issue by theolux** [ccxt/ccxt#2074]
OS: W10
    Programming Language version: Python 3.6.4
    CCXT version: 1.10.1237
    Exchange: Virwox
    Method: createLimitBuyOrder(symbol, amount, price)

Getting AttributeError: 'virwox' object has no attribute 'symbol' when trying to place an order.

**Comment by kroitor** [comment]
@theolux can you please paste the entire error message, following these steps: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
?

**Comment by kroitor** [comment]
Fixed in 1.10.1243. Thx for reporting!

**Comment by theolux** [comment]
Thanks, however I'm now getting a "NO_SUCH_INSTRUMENT" error from the exchange. It seems CCXT is converting the symbols into numbers (for ex. if I write BTC/SLL it sends 11 as instrument) while the exchange requires the actual symbol as instrument I believe.

**Comment by kroitor** [comment]
@theolux can you please post your verbose output according to https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
?

**Comment by theolux** [comment]
The method:
`virwox.createLimitBuyOrder ('BTC/SLL', AMOUNT, PRICE)`
The output:
```
Request: POST https://www.virwox.com/api/trading.php {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} {"method":"placeOrder","params":{"key":"KEY","user":"USER","pass":"PASS","instrument":"11","orderType":"BUY","amount":0.001,"price":"2700775.0"},"id":1519789163}

Response: POST https://www.virwox.com/api/trading.php 200 {'Server': 'nginx', 'Date': 'Wed, 28 Feb 2018 03:39:26 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '76', 'Connection': 'keep-alive', 'X-Rate-Limit-Minute': '60', 'X-Rate-Remaining-Minute': '55', 'X-Rate-Reset-Minute': '5', 'X-Rate-Limit-Hour': '600', 'X-Rate-Remaining-Hour': '595', 'X-Rate-Reset-Hour': '30', 'X-Rate-Cost': '5', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=15552000'} {"result":{"errorCode":"NO_SUCH_INSTRUMENT"},"error":null,"id":"1519789163"}
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\ccxt\virwox.py", line 38, in <module>
    virwox.createLimitBuyOrder ('BTC/SLL', AMOUNT, PRICE)
  File "C:\Users\USER\Desktop\ccxt\ccxt\base\exchange.py", line 1151, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "C:\Users\USER\Desktop\ccxt\ccxt\virwox.py", line 219, in create_order
    response = self.privatePostPlaceOrder(self.extend(order, params))
  File "C:\Users\USER\Desktop\ccxt\ccxt\base\exchange.py", line 291, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\USER\Desktop\ccxt\ccxt\base\exchange.py", line 288, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\USER\Desktop\ccxt\ccxt\base\exchange.py", line 368, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "C:\Users\USER\Desktop\ccxt\ccxt\virwox.py", line 262, in handle_errors
    raise ExchangeError(self.id + ' error returned: ' + body)
ccxt.base.errors.ExchangeError: virwox error returned: {"result":{"errorCode":"NO_SUCH_INSTRUMENT"},"error":null,"id":"1519789163"}
```

**Comment by theolux** [comment]
Now getting this:
```
Request: POST https://www.virwox.com/api/trading.php {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} {"method":"placeOrder","params":{"key":"KEY","user":"USER","pass":"PASS","instrument":"BTC/SLL","orderType":"SELL","amount":0.001,"price":2799799.0},"id":1519794329}

Response: POST https://www.virwox.com/api/trading.php 200 {'Server': 'nginx', 'Date': 'Wed, 28 Feb 2018 05:05:31 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '79', 'Connection': 'keep-alive', 'X-Rate-Limit-Minute': '60', 'X-Rate-Remaining-Minute': '54', 'X-Rate-Reset-Minute': '6', 'X-Rate-Limit-Hour': '600', 'X-Rate-Remaining-Hour': '594', 'X-Rate-Reset-Hour': '36', 'X-Rate-Cost': '5', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=15552000'} {"result":{"errorCode":"OK","orderID":93067857},"error":null,"id":"1519794329"}
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\ccxt\virwox.py", line 40, in <module>
    virwox.createLimitSellOrder ('BTC/SLL', 0.001, betterAsk)
  File "C:\Users\USER\Desktop\ccxt\ccxt\base\exchange.py", line 1154, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Users\USER\Desktop\ccxt\ccxt\virwox.py", line 222, in create_order
    'id': str(response['orderID']),
KeyError: 'orderID'
```
