### ISSUE TITLE
Proxy ConnectionResetError

### ISSUE THREAD

**Issue by CharlesFr** [ccxt/ccxt#20828]
### Operating System

Window 11 

### Programming Languages

Python

### CCXT Version

 4.2.15

### Description

If I run this code, 8 times out of 10 I will get the error printed below.

I suspect it's something do to with my rotating proxy but I need to understand exactly what's going on, can some point me in the right direction? 

The error points to an exception in the code without surfacing any proxy/response error which I find confusing.

### Code

```python
import aiohttp
import asyncio
from aiohttp_socks import ProxyType, ProxyConnector, ChainProxyConnector
from dotenv import load_dotenv
import os
import ccxt.async_support as ccxt
import traceback

load_dotenv()

async def load_market():
    connector = ProxyConnector.from_url("http://" + os.environ["PROXY_URL"])
    session = aiohttp.ClientSession(connector=connector)

    exchange = ccxt.okx(
        {
            "session": session
        }
    )

    await exchange.load_markets()  

    await exchange.close()  
    await session.close()  

if __name__ == "__main__":
    asyncio.run(load_market())

```

Logs:
```
Traceback (most recent call last):
  File "C:\Users\charles\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\charles\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\charles\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\checks\proxy\bright_data_check.py", line 44, in load_markets_many_times
    await load_market()
  File "D:\Documents\GitHub\mycelium\checks\proxy\bright_data_check.py", line 37, in load_market
    await exchange.load_markets()  # load all markets from the exchange
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\ccxt\async_support\base\exchange.py", line 276, in load_markets
    raise e
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\ccxt\async_support\base\exchange.py", line 272, in load_markets
    result = await self.markets_loading
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\ccxt\async_support\base\exchange.py", line 262, in load_markets_helper
    markets = await self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\ccxt\async_support\okx.py", line 1322, in fetch_markets
    promises = await asyncio.gather(*promises)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\ccxt\async_support\okx.py", line 1479, in fetch_markets_by_type
    promisesResult = await asyncio.gather(*promises)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\ccxt\async_support\base\exchange.py", line 753, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\ccxt\async_support\base\exchange.py", line 750, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\ccxt\async_support\base\exchange.py", line 199, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\aiohttp\client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\aiohttp\client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\aiohttp\connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\aiohttp\connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\aiohttp_socks\connector.py", line 85, in _wrap_create_connection
    stream = await proxy.connect(
             ^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\python_socks\async_\asyncio\v2\_proxy.py", line 70, in connect
    return await self._connect(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\python_socks\async_\asyncio\v2\_proxy.py", line 125, in _connect
    stream = await stream.start_tls(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\mycelium\venv311\Lib\site-packages\python_socks\async_\asyncio\v2\_stream.py", line 79, in start_tls
    await self._writer.start_tls(
  File "C:\Users\charles\AppData\Local\Programs\Python\Python311\Lib\asyncio\streams.py", line 387, in start_tls
    new_transport = await self._loop.start_tls(  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\charles\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1267, in start_tls
    await waiter
  File "C:\Users\charles\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 574, in _on_handshake_complete
    raise handshake_exc
ConnectionResetError
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000213CB502750>
okx requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
```

**Comment by sc0Vu** [comment]
Hi @CharlesFr

I think connection reset error happened when remote server close the connection, it's probably from tcp. Can you check your proxy server?

**Comment by CharlesFr** [comment]
I believe you're right, the following curl command fails (unexpected eof) about the same amount of time. If I add a top-level retry in my code for up to 10 times it will still fail all 10 on some occasions.

Are you able to recommend a few stable & reliable proxy providers?

![image](https://github.com/ccxt/ccxt/assets/16102087/64fb3205-ce89-487b-9f21-31928c9edc48)

**Comment by Fuk2828** [comment]
I DONT WANT UR DIRTY MONEY BUT GIVE TO CHILDRENS HOSPITAL OR NURSING HOME DO THAT IS A BLESSING FOR THE RICH THAT YOU PLAY DIRTY CHEAT ON STOCK EXCHANGE MARKET GIVE as mucg as u think is right from ur pocket

regards MR HONG CA LY UNIT 4 /8-10 CECILY ST BELFIELDS 2191 SYDNEY AUSTRALIA

**Comment by fl0wo** [comment]
I thinks sometimes it's fine to get connection errors from the proxy server, e.g. "RequestTimeout" for example.

Is there any way within CCXT to catch those requests and retry them if possibile?

**Comment by carlotestor** [comment]
`ConnectionResetError` is a raw TCP-level RST surfaced by aiohttp before any HTTP response exists, which is why you see no proxy/HTTP error — there is nothing to parse. With a rotating proxy this normally means the exit node was rotated/dropped mid-connection. Your own `curl` reproducing "unexpected eof" at the same rate confirms it's the proxy, not CCXT.

Two practical fixes:

1. Use CCXT's built-in proxy properties instead of injecting a session — they're supported and better tested:
```python
exchange = ccxt.okx()
exchange.httpsProxy = 'http://user:pass@host:port'   # or exchange.socksProxy = 'socks5://...'
await exchange.load_markets()
```

2. Wrap calls in a retry for `NetworkError` (which `ConnectionResetError` maps into) — this is expected behaviour with rotating proxies:
```python
for attempt in range(5):
    try:
        await exchange.load_markets()
        break
    except ccxt.NetworkError as e:
        if attempt == 4:
            raise
        await asyncio.sleep(2 ** attempt)
```

CCXT deliberately does not auto-retry: retrying is unsafe for order-placing calls, so it's left to userland. Sticky-session (session-persistent) datacenter proxies will cut these resets down a lot compared to per-request rotation.
