### ISSUE TITLE
Node version 20. NetworkError: fetch failed

### ISSUE THREAD

**Issue by ksamarin90** [ccxt/ccxt#20884]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

4.2.18

### Description

I'm running Node v20.2.0. Fetch request to binance fails with following error:
```
NetworkError: binance GET https://fapi.binance.com/fapi/v1/exchangeInfo fetch failed
    at binance.fetch (/ccxt-test/node_modules/ccxt/dist/cjs/src/base/Exchange.js:831:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async binance.fetch2 (/ccxt-test/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3241:16)
    at async binance.request (/ccxt-test/node_modules/ccxt/dist/cjs/src/binance.js:8772:26)
    at async Promise.all (index 1)
    at async binance.fetchMarkets (/ccxt-test/node_modules/ccxt/dist/cjs/src/binance.js:2077:26)
    at async binance.loadMarketsHelper (/ccxt-test/node_modules/ccxt/dist/cjs/src/base/Exchange.js:911:25)
    at async main (/ccxt-test/src/reproduce.ts:7:5)
```

If I'm using Node v18.9.0 the code executes without any error.

### Code

```
const ccxt = require('ccxt');
const dotenv = require('dotenv');
dotenv.config();

async function main() {
    const binance = new ccxt.binance({ apiKey: process.env.BINANCE_API_KEY, secret: process.env.BINANCE_API_SECRET });
    await binance.loadMarkets();
}

main().then(console.log).catch(console.error);

```

**Comment by pcriadoperez** [comment]
hi @ksamarin90 , I just tested v20.11.0 (LTS recommended) and v.21.6.0 and both work
I would recommend always using the LTS version.

I'll close the issue for now but feel free to reach out if you have any questions

**Comment by anteqkois** [comment]
I also have a problem with this. I have used 20.2.0v and don't work, when I try 20.11.1 it works. So probably there is a bug in this Node verison.
