### ISSUE TITLE
ccxt\Exchange::safe_number(): Argument #1 ($obj) must be of type array, string given

### ISSUE THREAD

**Issue by maddrid** [ccxt/ccxt#20991]
### Operating System

Windows 10 ( xampp ) 

### Programming Languages

PHP

### CCXT Version

 4.2.24

### Description

 order  is  placed ,  problem is on parse  the  response 
![Capture2](https://github.com/ccxt/ccxt/assets/5124319/4e65f4bc-e7d8-48e1-8805-a795d46e124e)

### Code

```
  TypeError: ccxt\Exchange::safe_number(): Argument #1 ($obj) must be of type array, string given, called in N:\\vendor\ccxt\ccxt\php\bingx.php on line 2205 in file N:\vendor\ccxt\ccxt\php\Exchange.php on line 5261

#0 N:\vendor\ccxt\ccxt\php\bingx.php(2205): ccxt\Exchange-&gt;safe_number(&#039;&#039;, &#039;stopLoss&#039;)
#1 N:\\vendor\ccxt\ccxt\php\bingx.php(1947): ccxt\bingx-&gt;parse_order(Array, Array)
#2 N:\Bot\Bingx.php(161): ccxt\bingx-&gt;create_order(&#039;XRP-USDT&#039;, &#039;market&#039;, &#039;BUY&#039;, 57.695813690364, NULL, Array)
#3 N:\app\Http\Controllers\Api\Controller.php(114): Bot\Bingx-&gt;listen(Array, Array)

```

**Comment by carlosmiei** [comment]
Hello @maddrid, thanks for letting us know. Which arguments were used to place the order? (so we can try to reproduce it locally)

**Comment by maddrid** [comment]
hello @carlosmiei 
 ```
  $ticker = $exchange->fetch_ticker($symbol);
                    $balance = $exchange->fetch_balance();
                    $toTrade = $balance['USDT'] ['total']* $equity / $ticker['last'] ;
                    try {
                        $type = 'MARKET';
                        $side = 'BUY';
                        $amount = $toTrade;
                        $price = null;
                        $params = ['positionSide' => 'LONG', 'reduceOnly' => true];
                        $create_order = $exchange->create_order($symbol, $type, $side, $amount, $price, $params);
                        Log::info('  BingX Long : ' . ['response' =>$create_order]);
                    } catch (RequestException $e) {
                        Log::error(' BingX Request Error: ' . $e->getMessage());
                        return response()->json(['message' => 'Request error: ' . $e->getMessage()], 500);
                    } catch (\ccxt\NetworkError $e) {
                        Log::error(' BingX Network Error: ' . $e->getMessage());
                        return response()->json(['message' => 'Network error: ' . $e->getMessage()], 500);
                    } catch (\ccxt\ExchangeError $e) {
                        Log::error(' BingX Exchange Error: ' . $e->getMessage());
                        return response()->json(['message' => 'Exchange error: ' . $e->getMessage()], 500);
                    } catch (\ccxt\InsufficientFunds $e) {
                        Log::error(' BingX Insufficient Funds: ' . $e->getMessage());
                        return response()->json(['message' => 'Insufficient funds: ' . $e->getMessage()], 500);
                    } catch (Exception $e) {
                        Log::error(' BingX General Error: ' . $e->getMessage());
                        return response()->json(['message' => 'General error: ' . $e->getMessage()], 500);
                    }
```

    resulting in 
```
             $exchange->create_order('XRP-USDT', 'market', 'BUY', 57.695813690364, null, $params);
```

**Comment by carlosmiei** [comment]
@maddrid Thank you, will open a PR to fix the issue ASAP
