### ISSUE TITLE
error while placing order on houbi

### ISSUE THREAD

**Issue by block98ct** [ccxt/ccxt#21000]
### Operating System

ubuntu

### Programming Languages

JavaScript

### CCXT Version

4.2.26

### Description

Error placing order on HTX: huobi {"status":"error","err-code":"invalid-type","err-msg":"Parameter `type` is invalid.","data":null}
Error: ExchangeError: huobi {"status":"error","err-code":"invalid-type","err-msg":"Parameter `type` is invalid.","data":null}
    at huobi.handleErrors (file:///home/palash/Public/test/node_modules/ccxt/js/src/htx.js:7253:23)
    at file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:919:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async huobi.fetch2 (file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:3279:16)
    at async huobi.request (file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:3282:16)
    at async huobi.createOrder (file:///home/palash/Public/test/node_modules/ccxt/js/src/htx.js:5402:24)
    at async huobi.createMarketOrder (file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:4230:16)
    at async executeTrade (file:///home/palash/Public/test/dir_arb.js:58:23)
    at async directArbitrage (file:///home/palash/Public/test/dir_arb.js:85:9)

### Code

```
  

```
async function executeTrade(exchange, symbol, price, amount, side) {
    try {
        const order = await exchange.createMarketOrder(symbol, side, amount);
        console.log(`Order placed successfully on ${exchange.name}: ${order.id}`);
        return order;
    } catch (error) {
        console.error(`Error placing order on ${exchange.name}:`, error.message);
        throw error;
    }
}

**Comment by carlosmiei** [comment]
Hello @block98ct,  thanks for reporting it.

Which symbol are you using here?

**Comment by carlosmiei** [comment]
@block98ct Placed some orders and worked, so I really need to know the symbol, side and amount used
```
Python v3.11.5
CCXT v4.2.27
huobi.createOrder(LTC/USDT:USDT,market,buy,1)
{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '1201663822988681216',
 'info': {'order_id': '1201663822988681216',
          'order_id_str': '1201663822988681216'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': None,
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'LTC/USDT:USDT',
 'takeProfitPrice': None,
 'timeInForce': None,
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': None}
```
```
p huobi createOrder "LTC/USDT" market buy 1 10 
Python v3.11.5
CCXT v4.2.27
huobi.createOrder(LTC/USDT,market,buy,1,10)
{'amount': 1.0,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '992699946509709',
 'info': {'data': '992699946509709', 'status': 'ok'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': 10.0,
 'reduceOnly': None,
 'remaining': None,
 'side': 'buy',
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
```
```
p huobi createOrder "LTC/USDT" market sell 0.2 
Python v3.11.5
CCXT v4.2.27
huobi.createOrder(LTC/USDT,market,sell,0.2)
{'amount': 0.2,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '992699963541108',
 'info': {'data': '992699963541108', 'status': 'ok'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': 'sell',
 'status': None,
```

**Comment by block98ct** [comment]
> Hello @block98ct, thanks for reporting it.
> 
> Which symbol are you using here?

ALGO/USDC

**Comment by block98ct** [comment]
> > Hello @block98ct, thanks for reporting it.
> > Which symbol are you using here?
> 
> ALGO/USDC

ALGO/USDT

it is because of that i am using javascript??

**Comment by carlosmiei** [comment]
@block98ct No the language is not relevant here. I will test this locally and circle back

**Comment by carlosmiei** [comment]
@block98ct `ALGO/USDC` does not seem to be a valid market at huobi, but `ALGO/USDT` worked fine
```
Node.js: v18.18.0
CCXT v4.2.28
huobi.createMarketOrder (ALGO/USDT, buy, 1, 10)
2024-01-30T14:07:58.679Z iteration 0 passed in 710 ms

{
  info: { status: 'ok', data: '992711565056186' },
  id: '992711565056186',
  type: 'market',
  side: 'buy',
  price: 10,
  amount: 1,
  trades: [],
  fees: [],
  timeInForce: 'IOC'
}
```

**Comment by block98ct** [comment]
> @block98ct `ALGO/USDC` does not seem to be a valid market at huobi, but `ALGO/USDT` worked fine
> 
> ```
> Node.js: v18.18.0
> CCXT v4.2.28
> huobi.createMarketOrder (ALGO/USDT, buy, 1, 10)
> 2024-01-30T14:07:58.679Z iteration 0 passed in 710 ms
> 
> {
>   info: { status: 'ok', data: '992711565056186' },
>   id: '992711565056186',
>   type: 'market',
>   side: 'buy',
>   price: 10,
>   amount: 1,
>   trades: [],
>   fees: [],
>   timeInForce: 'IOC'
> }
> ```

How you are testing locally ?? without using actual funds

**Comment by carlosmiei** [comment]
@block98ct I'm using real money to test, but a small amount (10 USDT)

**Comment by carlosmiei** [comment]
@block98ct It's very similar to yours, instead of using `createMarketOrder` can you try with `createOrder`?

Example:
`createOrder('XRP/USDT', 'market, 'buy', 20, 0.5)`

**Comment by block98ct** [comment]
> @block98ct It's very similar to yours, instead of using `createMarketOrder` can you try with `createOrder`?
> 
> Example: `createOrder('XRP/USDT', 'market, 'buy', 20, 0.5)`

does createOrder will work on cexs??

**Comment by carlosmiei** [comment]
@block98ct createOrder is widely available

**Comment by block98ct** [comment]
> @block98ct createOrder is widely available

ok thank you 
I have sent you a connect request on LinkedIn name of Palash Patil

**Comment by kroitor** [comment]
Hello @block98ct, closing this during a cleanup — the thread reached its conclusion back then: the invalid-type error came from the request parameters on the htx side rather than from the library, createOrder works on htx, and the discussion ended with that settled. If order placement fails on htx on a current version, a fresh issue with a verbose log would be very welcome. Thanks!

**Comment by kroitor** [comment]
Hello @block98ct, closing this during a cleanup — the thread ran its course back then: the invalid-type error came from the parameters sent to htx rather than a library defect, the discussion resolved the usage and you confirmed, and the htx order paths have been reworked since this 4.2 era report besides. If order placement on htx fails with correct parameters on a current version, a fresh issue with a verbose log would be very welcome. Thanks!
