### ISSUE TITLE
Kraken API 

### ISSUE THREAD

**Issue by taellinglin** [ccxt/ccxt#21063]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.1.76

### Description

Name: ccxt
Version: 4.1.76
Summary: A JavaScript / TypeScript / Python / C# / PHP cryptocurrency trading library with support for 130+ exchanges
Home-page: https://ccxt.com
Author: Igor Kroitor
Author-email: igor.kroitor@gmail.com
License: MIT
Location: c:\users\user\miniconda3\lib\site-packages
Requires: aiodns, aiohttp, certifi, cryptography, requests, setuptools, typing-extensions, yarl
Required-by: freqtrade
Metadata-Version: 2.1
Installer: pip
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Financial and Insurance Industry
  Intended Audience :: Information Technology
  Topic :: Software Development :: Build Tools
  Topic :: Office/Business :: Financial :: Investment
  License :: OSI Approved :: MIT License
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.7
  Programming Language :: Python :: 3.8
  Programming Language :: Python :: 3.9
  Programming Language :: Python :: 3.10
  Programming Language :: Python :: 3.11
  Programming Language :: JavaScript
  Programming Language :: PHP
  Operating System :: OS Independent
  Environment :: Console
Entry-points:
Project-URLs:
  Homepage, https://ccxt.com
  Documentation, https://github.com/ccxt/ccxt/wiki
  Discord, https://discord.gg/ccxt
  Twitter, https://twitter.com/ccxt_official
  Funding, https://opencollective.com/ccxt

### Code

```
  
2024-02-02 10:53:39,523 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 5
2024-02-02 10:53:39,523 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-02-02 10:53:39,526 - freqtrade.exchange.exchange - INFO - Using CCXT 4.1.76
2024-02-02 10:53:39,526 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2024-02-02 10:53:39,528 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2024-02-02 10:53:39,531 - freqtrade.exchange.exchange - INFO - Using Exchange "Kraken"
2024-02-02 10:53:42,187 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kraken'...
2024-02-02 10:53:46,755 - freqtrade.commands.trade_commands - ERROR - invalid literal for int() with base 10: '+50000%'
2024-02-02 10:53:46,756 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "D:\Apps\freqtrade\freqtrade\commands\trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "D:\Apps\freqtrade\freqtrade\worker.py", line 37, in __init__
    self._init(False)
  File "D:\Apps\freqtrade\freqtrade\worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "D:\Apps\freqtrade\freqtrade\freqtradebot.py", line 81, in __init__
    self.wallets = Wallets(self.config, self.exchange)
  File "D:\Apps\freqtrade\freqtrade\wallets.py", line 47, in __init__
    self.update()
  File "D:\Apps\freqtrade\freqtrade\wallets.py", line 177, in update
    self._update_live()
  File "D:\Apps\freqtrade\freqtrade\wallets.py", line 130, in _update_live
    balances = self._exchange.get_balances()
  File "D:\Apps\freqtrade\freqtrade\exchange\common.py", line 168, in wrapper
    return f(*args, **kwargs)
  File "D:\Apps\freqtrade\freqtrade\exchange\kraken.py", line 72, in get_balances
    orders = self._api.fetch_open_orders()
  File "C:\Users\User\miniconda3\lib\site-packages\ccxt\kraken.py", line 1945, in fetch_open_orders
    return self.parse_orders(orders, market, since, limit)
  File "C:\Users\User\miniconda3\lib\site-packages\ccxt\base\exchange.py", line 2607, in parse_orders
    order = self.extend(self.parse_order(self.extend({'id': id}, orders[id]), market), params)
  File "C:\Users\User\miniconda3\lib\site-packages\ccxt\kraken.py", line 1482, in parse_order
    if (price is None) or Precise.string_equals(price, '0'):
  File "C:\Users\User\miniconda3\lib\site-packages\ccxt\base\precise.py", line 245, in string_equals
    return Precise(string1).equals(Precise(string2))
  File "C:\Users\User\miniconda3\lib\site-packages\ccxt\base\precise.py", line 25, in __init__
    self.integer = int(number.replace('.', ''))
ValueError: invalid literal for int() with base 10: '+50000%'
```

**Comment by taellinglin** [comment]
I solved it by editing the source code to strip the percent sign

**Comment by sc0Vu** [comment]
Hi @taellinglin 

Which api did you use? I'm not sure why the price is `+50000%`.

**Comment by taellinglin** [comment]
I got it working, here's my edits:
ccxt/base/exchange.py
    def omit_zero(self, string_number):
        if string_number is None or string_number == '':
            return None

        # Handle both float and string input
        if isinstance(string_number, str):
            # Convert to string and handle '%' symbol
            number = re.sub(r'%$', '', string_number)
        else:
            number = str(string_number)

        if float(number) == 0:
            return None
        return string_number
ccxt/base/precise.py
    def __init__(self, number, decimals=None):
        if decimals is None:
            modifier = 0
            number = str(number).lower()

            # Handling percentage input
            percentage_match = re.match(r'^([\+\-]?\d*\.?\d+)%?$', number)
            if percentage_match:
                number = percentage_match.group(1)
                modifier = 2  # Two decimal places for percentage

            if 'e' in number:
                number, modifier = number.split('e')
                modifier = int(modifier)

            decimal_index = number.find('.')
            if decimal_index > -1:
                self.decimals = len(number) - decimal_index - 1
                self.integer = int(number.replace('.', ''))
            else:
                self.decimals = 0
                self.integer = int(number)

            self.decimals = self.decimals - modifier
        else:
            self.integer = number
            self.decimals = decimals
        self.base = 10

2024年2月2日(金) 15:43 Peter Lai ***@***.***>:

**Comment by carlosmiei** [comment]
@taellinglin Is it possible to share a verbose log? (`exchange.verbose = True`) before invoking the unified method.

**Comment by xmatthias** [comment]
@carlosmiei pretty simply accomplishable via a trailing stop order with relative distance.

![image](https://github.com/ccxt/ccxt/assets/5024695/54c5ae82-1782-437d-86d9-d70099457dba)

![image](https://github.com/ccxt/ccxt/assets/5024695/548739c4-55cc-40f8-bccf-472abd1e41e1)



formatted response body:

```
{
    "error": [],
    "result": {
        "open": {
            "OXVPSU-Q726F-L3SDEP": {
                "refid": null,
                "userref": 0,
                "status": "open",
                "opentm": 1706893367.4656649,
                "starttm": 0,
                "expiretm": 0,
                "descr": {
                    "pair": "XRPEUR",
                    "type": "sell",
                    "ordertype": "trailing-stop",
                    "price": "+50.0000%",
                    "price2": "0",
                    "leverage": "none",
                    "order": "sell 10.00000000 XRPEUR @ trailing stop +50.0000%",
                    "close": ""
                },
                "vol": "10.00000000",
                "vol_exec": "0.00000000",
                "cost": "0.00000000",
                "fee": "0.00000000",
                "price": "0.00000000",
                "stopprice": "0.23424000",
                "limitprice": "0.46847000",
                "misc": "",
                "oflags": "fciq",
                "trigger": "index"
            }
    }
}
```

Full, sanitized response (incl. the exception) below

<details><summary>Details</summary>

```
fetch Request: kraken POST https://api.kraken.com/0/private/OpenOrders RequestHeaders: {'API-Key': '', 'API-Sign': 'xx, 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: nonce=1706893392182

fetch Response: kraken POST https://api.kraken.com/0/private/OpenOrders 200 ResponseHeaders: {'Date': 'Fri, 02 Feb 2024 17:03:12 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'content-encoding': 'gzip', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-trace-id': '', 'cache-control': 'no-store', 'vary': 'accept-encoding', 'ktkh02xwt-pad': , 'x-proxy': 'gateway', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=-1706893392-1-+b+c=; path=/; expires=Fri, 02-Feb-24 17:33:12 GMT; domain=.kraken.com; HttpOnly; Secure; SameSite=None, __cfruid=-1706893392; path=/; domain=.kraken.com; HttpOnly; Secure; SameSite=None', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '84f401952d861bd5-MUC'} ResponseBody: {"error":[],"result":{"open":{"OXVPSU-Q726F-L3SDEP":{"refid":null,"userref":0,"status":"open","opentm":1706893367.4656649,"starttm":0,"expiretm":0,"descr":{"pair":"XRPEUR","type":"sell","ordertype":"trailing-stop","price":"+50.0000%","price2":"0","leverage":"none","order":"sell 10.00000000 XRPEUR @ trailing stop +50.0000%","close":""},"vol":"10.00000000","vol_exec":"0.00000000","cost":"0.00000000","fee":"0.00000000","price":"0.00000000","stopprice":"0.23424000","limitprice":"0.46847000","misc":"","oflags":"fciq","trigger":"index"}}}
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], [line 2](vscode-notebook-cell:?execution_count=7&line=2)
      [1](vscode-notebook-cell:?execution_count=7&line=1) ct.verbose = True
----> [2](vscode-notebook-cell:?execution_count=7&line=2) ct.fetch_open_orders()

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1979](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1979), in kraken.fetch_open_orders(self, symbol, since, limit, params)
   [1977](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1977) result = self.safe_value(response, 'result', {})
   [1978](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1978) orders = self.safe_value(result, 'open', [])
-> [1979](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1979) return self.parse_orders(orders, market, since, limit)

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:2636](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:2636), in Exchange.parse_orders(self, orders, market, since, limit, params)
   [2634](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:2634)     for i in range(0, len(ids)):
   [2635](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:2635)         id = ids[i]
-> [2636](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:2636)         order = self.extend(self.parse_order(self.extend({'id': id}, orders[id]), market), params)
   [2637](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:2637)         results.append(order)
   [2638](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:2638) results = self.sort_by(results, 'timestamp')

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1495](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1495), in kraken.parse_order(self, order, market)
   [1492](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1492) # kraken truncates the cost in the api response so we will ignore it and calculate it from average & filled
   [1493](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1493) # cost = self.safe_string(order, 'cost')
   [1494](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1494) price = self.safe_string(description, 'price', price)
-> [1495](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1495) if (price is None) or Precise.string_equals(price, '0'):
   [1496](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1496)     price = self.safe_string(description, 'price2')
   [1497](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/kraken.py:1497) if (price is None) or Precise.string_equals(price, '0'):

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:245](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:245), in Precise.string_equals(string1, string2)
    [243](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:243) if string1 is None or string2 is None:
    [244](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:244)     return None
--> [245](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:245) return Precise(string1).equals(Precise(string2))

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:25](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:25), in Precise.__init__(self, number, decimals)
     [23](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:23) if decimal_index > -1:
     [24](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:24)     self.decimals = len(number) - decimal_index - 1
---> [25](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:25)     self.integer = int(number.replace('.', ''))
     [26](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:26) else:
     [27](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/precise.py:27)     self.decimals = 0

ValueError: invalid literal for int() with base 10: '+500000%'
```




</details>

**Comment by carlosmiei** [comment]
@xmatthias Oh now that makes sense, thanks for your input, we will patch it asap.
