### ISSUE TITLE
PermissionDenied: htx

### ISSUE THREAD

**Issue by block98ct** [ccxt/ccxt#21065]
### Operating System

ubuntu

### Programming Languages

JavaScript

### CCXT Version

4.2.26

### Description

PermissionDenied: htx {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null}
    at htx.throwExactlyMatchedException (file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:3824:19)
    at htx.handleErrors (file:///home/palash/Public/test/node_modules/ccxt/js/src/htx.js:7253:22)
    at file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:926:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async htx.fetch2 (file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:3398:16)
    at async htx.request (file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:3401:16)
    at async htx.withdraw (file:///home/palash/Public/test/node_modules/ccxt/js/src/htx.js:6553:26)
    at async transferFund (file:///home/palash/Public/test/test.js:18:22)

### Code

```
   async function transferFund(){
     try {
       const order = await  huobiExchange.withdraw('ALGO', 20, "MWR7GSIW2VYSXXQ6METWOPZDWOTAXJCOL3OVL7PBJIGG5POXESLAT5QOQE")
       huobiExchange.t
       console.log(order)
      
     } catch (error) {
        console.log(error);
        
     }
 }


```

**Comment by sc0Vu** [comment]
@block98ct

You may need to add the address to whitelist. Details on their doc: https://huobiapi.github.io/docs/spot/v1/en/#error-code-4

![image](https://github.com/ccxt/ccxt/assets/10494397/4b6f999c-d0f4-460a-bb3a-7b9f600de5e1)

**Comment by block98ct** [comment]
> @block98ct
> 
> You may need to add the address to whitelist. Details on their doc: https://huobiapi.github.io/docs/spot/v1/en/#error-code-4
> 
> ![image](https://private-user-images.githubusercontent.com/10494397/301809997-4b6f999c-d0f4-460a-bb3a-7b9f600de5e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjkzNjQsIm5iZiI6MTcwNjg2OTA2NCwicGF0aCI6Ii8xMDQ5NDM5Ny8zMDE4MDk5OTctNGI2Zjk5OWMtZDBmNC00NjBhLWJiM2EtN2I5ZjYwMGRlNWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDEwMTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOTBkOWFiMTY1YzY5MjU2ZGY4M2NlOGJlZDIwNmJjODg5YWFkZTk3ZDcwZjcxYzJhZTMyMGNhMTJhNTljYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pU6ONG87GmrFw-_yfu4VYtsIpt766TTXAmbGslLTq4Y)

same for binance also??

**Comment by block98ct** [comment]
> ### Operating System
> ubuntu
> 
> ### Programming Languages
> JavaScript
> 
> ### CCXT Version
> 4.2.26
> 
> ### Description
> PermissionDenied: htx {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null} at htx.throwExactlyMatchedException (file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:3824:19) at htx.handleErrors (file:///home/palash/Public/test/node_modules/ccxt/js/src/htx.js:7253:22) at file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:926:51 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async htx.fetch2 (file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:3398:16) at async htx.request (file:///home/palash/Public/test/node_modules/ccxt/js/src/base/Exchange.js:3401:16) at async htx.withdraw (file:///home/palash/Public/test/node_modules/ccxt/js/src/htx.js:6553:26) at async transferFund (file:///home/palash/Public/test/test.js:18:22)
> 
> ```
> I am making arbitrage bot, to do that I need to transfer fund from one cex to another cex, while transferring fund I am getting error
> ```
> 
> ### Code
> ```
>    async function transferFund(){
>      try {
>        const order = await  huobiExchange.withdraw('ALGO', 20, "MWR7GSIW2VYSXXQ6METWOPZDWOTAXJCOL3OVL7PBJIGG5POXESLAT5QOQE")
>        huobiExchange.t
>        console.log(order)
>       
>      } catch (error) {
>         console.log(error);
>         
>      }
>  }
> ```

the address I mention here is from binance address

**Comment by sc0Vu** [comment]
Yes, you probably need to ask htx about the settings.

**Comment by kroitor** [comment]
Hello @block98ct, closing this during a cleanup — this is htx policy rather than a ccxt behavior: their API refuses withdrawals to any address that isn't saved in the account's address book first (`api-not-support-temp-addr` is exactly that refusal), and ccxt correctly surfaces it as `PermissionDenied`. The resolution is on the htx side: add the destination address to the withdrawal address list in your htx account settings (and note that verified-address requirements can also apply), then the same `withdraw` call goes through.

If a whitelisted address still gets rejected on a current version, a fresh issue with a verbose log would be welcome. Thanks!
