### ISSUE TITLE
ES6 export

### ISSUE THREAD

**Issue by kpgarrod** [ccxt/ccxt#2107]
- OS: Linux
- Programming Language version: Javascript ES6(2015)/Typescript
- CCXT version: 1.10.1265
- Exchange: N/A
- Method: exchanges

I am trying to create a webcomponent using the ccxt library. The code snippet below uses Ionic Stencil but I get similar problems with Polymer. I've tried importing the browser version of the code (`import *  as ccxt from 'ccxt/build/ccxt.browser.js'`)  with a similar result.

Code:

```
import { Component, Prop } from '@stencil/core';
import { MatchResults } from '@stencil/router';
import *  as ccxt from 'ccxt'

@Component({
  tag: 'app-profile',
  styleUrl: 'app-profile.css'
})
export class AppProfile {
  componentDidLoad() {
    this.getMarkets()
  }
  @Prop() match: MatchResults;

  render() {
    if (this.match && this.match.params.name) {
      return (
        <div class='app-profile'>
          <p>
            Hello world
          </p>
        </div>
      );
    }
  }
  async getMarkets(){
    console.log ("Exchanges", ccxt.exchanges)
  }
}
```
Error from compile process:

```
{ SyntaxError: Unexpected token (346:40) in /home/keith/Drive/Cryptobalance/Ionic/my-app/node_modules/ccxt/js/base/Exchange.js
    at error (/home/keith/Drive/Cryptobalance/Ionic/my-app/node_modules/rollup/dist/rollup.js:170:15)
    at Object.error (/home/keith/Drive/Cryptobalance/Ionic/my-app/node_modules/rollup/dist/rollup.js:17509:21)
    at /home/keith/Drive/Cryptobalance/Ionic/my-app/node_modules/rollup/dist/rollup.js:17518:29
    at <anonymous>
  pos: 12288,
  loc: Position { line: 346, column: 40 },
  raisedAt: 12294,
  code: 'PLUGIN_ERROR',
  plugin: undefined,
  id: '/home/keith/Drive/Cryptobalance/Ionic/my-app/node_modules/ccxt/js/base/Exchange.js' }

[ ERROR ]  Unexpected token (346:40) in
           /home/keith/Drive/Cryptobalance/Ionic/my-app/node_modules/ccxt/js/base/Exchange.js

[ ERROR ]  rollup died at
           /home/keith/Drive/Cryptobalance/Ionic/my-app/node_modules/@stencil/core/dist/compiler/index.js:2061:19 at
           Generator.throw (<anonymous>) at rejected
           (/home/keith/Drive/Cryptobalance/Ionic/my-app/node_modules/@stencil/core/dist/compiler/index.js:2017:65) at
           <anonymous>
```

**Comment by kpgarrod** [comment]
I think the issue is more specifically related to Rollup (which is being used to bundle the webcomponent) rather than webcomponents per se.

**Comment by kroitor** [comment]
We are not going to fallback to ES5, as we strongly believe those frameworks should finally update their codebase at last. Answered here: https://github.com/ccxt/ccxt/issues/1916. Hope it answers your question. Thanks!
