### ISSUE TITLE
Coinbase Cloud Advanced Trading API Format?

### ISSUE THREAD

**Issue by magentoman2009** [ccxt/ccxt#21226]
**My code**: 

```
import api_keys as k

# Connect to an exchange
import ccxt
coinbase = ccxt.coinbase ({
    'enableRateLimit': True,
    'apiKey': k.key,
    'secret': k.secret
})

balance = coinbase.fetch_balance()
print(balance)
```

**My api_keys.py file**:

```
key_name = 'organizations/hidden/apiKeys/hidden'
key = """-----BEGIN EC PUBLIC KEY-----\nhidden\nhidden==\n-----END EC PUBLIC KEY-----"""
secret = """-----BEGIN EC PRIVATE KEY-----\nhidden\nhidden==\n-----END EC PRIVATE KEY-----"""
```

**The error I get**:

```
Traceback (most recent call last):
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/exchange.py", line 598, in fetch
    response = self.session.request(
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/requests/models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/requests/utils.py", line 1040, in check_header_validity
    _validate_header_part(header, value, 1)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/requests/utils.py", line 1056, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: '-----BEGIN EC PUBLIC KEY-----\nhidden\nhidden==\n-----END EC PUBLIC KEY-----'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hidden/Development/Crypto/Bots/BootCamp/Algo/orders.py", line 13, in <module>
    balance = coinbase.fetch_balance()
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/coinbase.py", line 1688, in fetch_balance
    self.load_markets()
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1474, in load_markets
    markets = self.fetch_markets(params)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/coinbase.py", line 1012, in fetch_markets
    return getattr(self, method)(params)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/coinbase.py", line 1084, in fetch_markets_v3
    response = self.v3PrivateGetBrokerageProducts(params)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/types.py", line 34, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3521, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3518, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/exchange.py", line 666, in fetch
    raise ExchangeError(details) from e
ccxt.base.errors.ExchangeError: coinbase GET https://api.coinbase.com/api/v3/brokerage/products

```

What needs to be changed in order to get this to work? Here is the api info from the coinbase API downloaded file:

```
{
   "name": "organizations/hidden/apiKeys/hidden",
   "principal": "hidden",
   "principalType": "USER",
   "publicKey": "-----BEGIN EC PUBLIC KEY-----\nhidden\nhidden==\n-----END EC PUBLIC KEY-----\n",
   "privateKey": "-----BEGIN EC PRIVATE KEY-----\nhidden\nhidden\nhidden==\n-----END EC PRIVATE KEY-----\n",
   "createTime": "2024-02-14T17:51:50.171874057Z",
   "projectId": "hidden",
   "nickname": "Test",
   "scopes": [
      "rat/portfolio: hidden#view",
      "rat/portfolio: hidden#trade",
      "rat#view",
      "rat#trade"
   ],
   "allowedIps": [
      "hidden"
   ],
   "keyType": "TRADING_KEY",
   "enabled": true
} 
```

**Comment by samgermain** [comment]
I create my coinbase apiKey under the api section in settings on the coinbase website, you should probably create it here.

![](https://i.stack.imgur.com/SHKdL.png)
![](https://i.stack.imgur.com/2Ar5B.png)
![](https://i.stack.imgur.com/7hObY.png)

**Comment by magentoman2009** [comment]
> I create my coinbase apiKey under the api section in settings on the coinbase website, you should probably create it here.
> 
> ![](https://camo.githubusercontent.com/deeb684e8da82480f18ad6262d3b8b0d6af9771902792c11f8ce01c7f0260bd2/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f53484b644c2e706e67) ![](https://camo.githubusercontent.com/9c39c00bfe541ac8fdd088b0ac39137596008c2ddbca285b2ddf2ed92bce6f95/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f32417235422e706e67) ![](https://camo.githubusercontent.com/39a910b0d34d23fb1cf72b401f3a1e9b4e38814d196924b7d7d2d444d5c41810/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f37684f62592e706e67)

Thank you! I didn't know about that API section on the website. I was under the cloud advanced trading API section which provides a much more complex API as seen in my original post. 

<img width="1323" alt="Screenshot 2024-02-14 at 8 32 40 PM" src="https://github.com/ccxt/ccxt/assets/3162422/d7db7540-e140-4cb9-8f5f-8e03f6e804a1">


I created the new API under the section you shared on the website and my code still fails to run. Any thoughts as to why this is happening?

<img width="1020" alt="Screenshot 2024-02-14 at 8 38 24 PM" src="https://github.com/ccxt/ccxt/assets/3162422/2a402b23-2198-47ea-a10d-40e04417c5de">


Here is my code:

```
##### Coding Algo Orders #####

import api_keys as k
import ccxt

# Instantiate the connection
coinbase = ccxt.coinbase({
    'rateLimit': 1000,  # Example unified exchange property
    'apiKey': k.key,
    'secret': k.secret,
    #'verbose': True,
    # Include any other necessary options or configurations specific to Coinbase
})

# Use the exchange object as needed
balance = coinbase.fetch_balance()
print(balance)
```

Here is the error:

```
Traceback (most recent call last):
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/exchange.py", line 624, in fetch
    response.raise_for_status()
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.coinbase.com/v2/accounts?limit=250

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hidden/Development/Crypto/Bots/BootCamp/Algo/orders.py", line 16, in <module>
    balance = coinbase.fetch_balance()
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/coinbase.py", line 1699, in fetch_balance
    response = self.v2PrivateGetAccounts(self.extend(request, params))
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/types.py", line 34, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3521, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3518, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/exchange.py", line 642, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/Users/hidden/anaconda3/envs/BootCamp_AlgoTrading/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1656, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.AuthenticationError: coinbase GET https://api.coinbase.com/v2/accounts?limit=250 401 Unauthorized Unauthorized
```

**Comment by samgermain** [comment]
> I created the new API under the section you shared on the website and my code still fails to run. Any thoughts as to why this is happening?

That's a bug, it's fixed in the linked PR

**Comment by magentoman2009** [comment]
@samgermain You rock, thank you! That fixed my issue!
