### ISSUE TITLE
Await wait_for and watch_trades generates an error that cannot be caught in exceptions

### ISSUE THREAD

**Issue by algosfox** [ccxt/ccxt#21331]
### Operating System

Wndows 10

### Programming Languages

Python

### CCXT Version

 4.2.49

### Description

Await wait_for and watch_trades generates an error that cannot be caught in exceptions.

```
2024-02-22 19:47:42,510 [ERROR]: Exception in callback Future.race.<locals>.callback(<Task finishe...]}]>}, set())>) at ..\Python\Python311\site-packages\ccxt\async_support\base\ws\future.py:25
handle: <Handle Future.race.<locals>.callback(<Task finishe...]}]>}, set())>) at  ..\Python\Python311\site-packages\ccxt\async_support\base\ws\future.py:25>
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "...Python\Python311\site-packages\ccxt\async_support\base\ws\future.py", line 56, in callback
    future.set_result(first_result)
asyncio.exceptions.InvalidStateError: invalid state
```

### Code

```
import ccxt.pro as ccxtpro
import asyncio
import logging

logging.basicConfig(level=logging.INFO, 
                    format=f'%(asctime)s [%(levelname)s]: %(message)s',
                    handlers=[logging.StreamHandler(),
                    logging.FileHandler('my_log_file.log', mode='a')])


async def observe_trades(exchange, symbol, exit_flag):
    while not exit_flag[0]:
        try:
            trades = await asyncio.wait_for(exchange.watch_trades(symbol), timeout=5)
            if trades:
                pass    
            
            await asyncio.sleep(1)

        except asyncio.TimeoutError:
            logging.info(f"{symbol} asyncio.TimeoutError observe_trades")  
            
        except asyncio.exceptions.CancelledError  as e:
            logging.error(f"{symbol} CancelledError  in observe_trades: {e}")   

        except asyncio.exceptions.InvalidStateError as e:
            logging.error(f"{symbol} InvalidStateError in observe_trades: {e}")     
                    
        except Exception as e:
            logging.error(f"{symbol} Error in observe_trades: {e}")

        
    logging.info(f"{symbol} Exit observe_trades")
    return   

async def main():

    exit_flag = [False]
    exchange_class = getattr(ccxtpro, 'binance')
    exchange = exchange_class({
        'apiKey': '',
        'secret': '',
    })

    markets = await exchange.load_markets()
    symbols = [symbol for symbol in markets if '/USDT:USDT' in symbol]

    for symbol in symbols:
        asyncio.create_task(observe_trades(exchange, symbol, exit_flag))

    await asyncio.sleep(10)
    
    exit_flag[0] = True
    
    await asyncio.sleep(5)
    
    await exchange.close()
    logging.info(f"Close exchange object")  

    
asyncio.run(main())
  

```

**Comment by kroitor** [comment]
Hello @algosfox, closing this during a cleanup — this zero reply report is from the 4.2 era: cancelling a watch call from the outside with asyncio.wait_for interrupts a shared internal future, and the error routing around cancelled and rejected futures has been reworked since, including recent hardening of how stream errors are delivered to pending watchers. Note also that wait_for cancellation remains an abrupt way to time out a shared subscription, catching asyncio.TimeoutError around it and continuing the loop is the supported pattern. If an uncatchable error still escapes on a current version, a fresh issue with the traceback would be very welcome. Thanks for the report back then!
