### ISSUE TITLE
Bingx Failed to establish a new connection: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by rikhtehgaran** [ccxt/ccxt#21496]
### Operating System

Linux Mint 20.3

### CCXT Version

4.2.57

### Description

Hi, i want to open a limit order on bingx exchange so when I try  the exchange example it works successfully:
```python
import json
import time
import requests
import hmac
from hashlib import sha256

APIURL = "https://open-api-vst.bingx.com"
APIKEY = "3k....iQ"
SECRETKEY = "ZJ...ig"

def demo():
    payload = {}
    path = '/openApi/swap/v2/trade/order'
    method = "POST"
    paramsMap = {
        "symbol": "BTC-USDT",
        "side": "BUY",
        "positionSide": "LONG",
        "type": "LIMIT",
        "price":60540.0,
        "quantity": 0.2,
        "takeProfit": "{\"type\": \"TAKE_PROFIT_MARKET\",\"stopPrice\": 63204.0,\"workingType\":\"MARK_PRICE\"}"
    }
    paramsStr = parseParam(paramsMap)
    return send_request(method, path, paramsStr, payload)

def get_sign(api_secret, payload):
    signature = hmac.new(api_secret.encode("utf-8"), payload.encode("utf-8"), digestmod=sha256).hexdigest()
    print("sign=" + signature)
    return signature

def send_request(method, path, urlpa, payload):
    url = "%s%s?%s&signature=%s" % (APIURL, path, urlpa, get_sign(SECRETKEY, urlpa))
    print(url)
    headers = {
        'X-BX-APIKEY': APIKEY,
    }
    response = requests.request(method, url, headers=headers, data=payload)
    return response.text

def parseParam(paramsMap):
    sortedKeys = sorted(paramsMap)
    paramsStr = "&".join(["%s=%s" % (x, paramsMap[x]) for x in sortedKeys])
    if paramsStr != "":
        return paramsStr + "&timestamp=" + str(int(time.time() * 1000))
    else:
        return paramsStr + "timestamp=" + str(int(time.time() * 1000))

if __name__ == '__main__':
    demo = json.loads(demo())
    print("demo:", demo)
```
But when I try ccxt using this code:
```python
import ccxt
# create an instance of the exchange
exchange = ccxt.bingx({
   'apiKey': '3kK...iQ',
   'secret': 'ZJ...ig',
   'enableRateLimit': True,
})
exchange.set_sandbox_mode(True)

# define the trading parameters
symbol = 'BTC/USDT'
amount = 0.1
stop_loss = 0.95
take_profit = 1.05
min_price_diff = 50

order=exchange.create_limit_buy_order(symbol,amount,61314,{"takeProfitPrice":62965})
```

it returns this error:(I use proxy for both my script and condition is same for both scripts)
```
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
>>> import os
... os.environ['http_proxy'] = 'http://127.0.0.1:8118'
... os.environ['https_proxy'] = 'http://127.0.0.1:8118'
... runfile('/home/mrg/myProject/BingX/ccxt/buy.py', wdir='/home/mrg/myProject/BingX/ccxt')
... 
Traceback (most recent call last):
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f66d51273a0>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='open-api-vst.bingx.com', port=443): Max retries exceeded with url: /openApi/swap/v2/quote/contracts?timestamp=1709387089609 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f66d51273a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 598, in fetch
    response = self.session.request(
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='open-api-vst.bingx.com', port=443): Max retries exceeded with url: /openApi/swap/v2/quote/contracts?timestamp=1709387089609 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f66d51273a0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 4, in <module>
  File "/home/mrg/Program/Pycharm/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/mrg/Program/Pycharm/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/mrg/myProject/BingX/ccxt/buy.py", line 18, in <module>
    order=exchange.create_limit_buy_order(symbol,amount,61314,{"takeProfitPrice":62965})
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 4379, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', amount, price, params)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/bingx.py", line 1881, in create_order
    self.load_markets()
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1474, in load_markets
    markets = self.fetch_markets(params)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/bingx.py", line 694, in fetch_markets
    requests = [self.fetch_swap_markets(params)]
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/bingx.py", line 580, in fetch_swap_markets
    response = self.swapV2PublicGetQuoteContracts(params)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3536, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3533, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 651, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: bingx GET https://open-api-vst.bingx.com/openApi/swap/v2/quote/contracts?timestamp=1709387089609
```

### Code

```python
import ccxt
# create an instance of the exchange
exchange = ccxt.bingx({
   'apiKey': '3kK...iQ',
   'secret': 'ZJ...ig',
   'enableRateLimit': True,
})
exchange.set_sandbox_mode(True)

# define the trading parameters
symbol = 'BTC/USDT'
amount = 0.1
stop_loss = 0.95
take_profit = 1.05
min_price_diff = 50

order=exchange.create_limit_buy_order(symbol,amount,61314,{"takeProfitPrice":62965})

```

**Comment by carlosmiei** [comment]
Hello @rikhtehgaran, 
I think the problem is related to the proxy, I just tested locally and seems to be working.

Can you try to set the proxy explicitly by doing `exchange.https_proxy = 'url here'` ?


DEMO

```
bingx.createOrder (LTC/USDT:USDT, limit, buy, 0.15, 50)
fetch Request:
 bingx POST https://open-api-vst.bingx.com/openApi/swap/v2/trade/order?positionSide=LONG&price=50&quantity=0.1&side=BUY&symbol=LTC-USDT&timestamp=1709391987399&type=LIMIT&signature=5669714a5012716980b00cee7d2b6d7b2611c0a173d77a9d885b24187a8f74b3 
RequestHeaders:

ResponseBody:
 {"code":0,"msg":"","data":{"order":{"orderId":1763943961403068416,"symbol":"LTC-USDT","positionSide":"LONG","side":"BUY","type":"LIMIT","price":50,"quantity":0.1,"stopPrice":0,"workingType":"MARK_PRICE","clientOrderID":"","timeInForce":"GTC","priceRate":0,"stopLoss":"","takeProfit":"","reduceOnly":false,"activationPrice":0,"closePosition":""}}} 
```

**Comment by rikhtehgaran** [comment]
> Hello @rikhtehgaran, I think the problem is related to the proxy, I just tested locally and seems to be working.
> 
> Can you try to set the proxy explicitly by doing `exchange.https_proxy = 'url here'` ?
> 
> DEMO
> 
> ```
> bingx.createOrder (LTC/USDT:USDT, limit, buy, 0.15, 50)
> fetch Request:
>  bingx POST https://open-api-vst.bingx.com/openApi/swap/v2/trade/order?positionSide=LONG&price=50&quantity=0.1&side=BUY&symbol=LTC-USDT&timestamp=1709391987399&type=LIMIT&signature=5669714a5012716980b00cee7d2b6d7b2611c0a173d77a9d885b24187a8f74b3 
> RequestHeaders:
> 
> ResponseBody:
>  {"code":0,"msg":"","data":{"order":{"orderId":1763943961403068416,"symbol":"LTC-USDT","positionSide":"LONG","side":"BUY","type":"LIMIT","price":50,"quantity":0.1,"stopPrice":0,"workingType":"MARK_PRICE","clientOrderID":"","timeInForce":"GTC","priceRate":0,"stopLoss":"","takeProfit":"","reduceOnly":false,"activationPrice":0,"closePosition":""}}} 
> ```

It worked but another problem happened. it's my code:
```python
import ccxt
# create an instance of the exchange
exchange = ccxt.bingx({
   'apiKey': '3k...MiQ',
   'secret': 'ZJc...rAig',
   'enableRateLimit': True,
})
exchange.set_sandbox_mode(True)
exchange.https_proxy='http://127.0.0.1:8118'

# define the trading parameters
symbol = 'BTC-USDT'
amount = 0.1

order=exchange.create_limit_buy_order(symbol,amount,61314,{"takeProfitPrice":62965})
```
Error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/mrg/Program/Pycharm/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/mrg/Program/Pycharm/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/mrg/myProject/BingX/ccxt/buy.py", line 19, in <module>
    order=exchange.create_limit_buy_order(symbol,amount,61314,{"takeProfitPrice":62965})
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 4379, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', amount, price, params)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/bingx.py", line 1886, in create_order
    response = self.swapV2PrivatePostTradeOrder(request)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3536, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3533, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 668, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/bingx.py", line 3952, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
  File "/home/mrg/myProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3908, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: bingx {"code":80017,"msg":"position not exist","data":{}}
```

**Comment by carlosmiei** [comment]
@rikhtehgaran That's a different issue, if you have a `long` position opened, I think that your `takeProfit` order should be a sell, no (you're still creating a buy order) ?

**Comment by rikhtehgaran** [comment]
> @rikhtehgaran That's a different issue, if you have a `long` position opened, I think that your `takeProfit` order should be a sell, no (you're still creating a buy order) ?

I did it with direct API and it works:
```python
def demo():
    payload = {}
    path = '/openApi/swap/v2/trade/order'
    method = "POST"
    paramsMap = {
        "symbol": "BTC-USDT",
        "side": "BUY",
        "positionSide": "LONG",
        "type": "LIMIT",
        "price":60540.0,
        "quantity": 0.3,
        "takeProfit": "{\"type\": \"TAKE_PROFIT_MARKET\",\"stopPrice\": 63270.0,\"workingType\":\"MARK_PRICE\"}"
    }

    paramsStr = parseParam(paramsMap)
    return send_request(method, path, paramsStr, payload)
```

I did it with ccxt code with the same price and take profit price and it returns that error:
```python
exchange.set_sandbox_mode(True)
exchange.https_proxy='http://127.0.0.1:8118'

# define the trading parameters
symbol = 'BTC-USDT'
amount = 0.3

order=exchange.create_limit_buy_order(symbol,amount,60540,{"takeProfitPrice":63270})

```

**Comment by carlotestor** [comment]
`[Errno 101] Network is unreachable` is a connectivity failure before any request goes out — CCXT never reached BingX. Your raw-`requests` script works because it (unlike the CCXT instance) is picking up your system/env proxy.

Set the proxy explicitly on the exchange:

```python
exchange = ccxt.bingx({'apiKey': API_KEY, 'secret': SECRET_KEY})
exchange.https_proxy = 'http://user:pass@host:port'
# or: exchange.socks_proxy = 'socks5://user:pass@host:port'
```

If your proxy already lives in `HTTP_PROXY`/`HTTPS_PROXY` env vars, the sync client needs to be told to honour them:

```python
exchange.session.trust_env = True
```

Also note you were pointing at `open-api-vst.bingx.com`, which is the **demo/VST** host. In CCXT that's the sandbox:

```python
exchange.set_sandbox_mode(True)
```

Once connected, the order itself is straightforward — CCXT builds BingX's nested `takeProfit` JSON for you, no manual string construction needed:

```python
exchange.create_order('BTC/USDT:USDT', 'limit', 'buy', 0.2, 60540, {
    'positionSide': 'LONG',
    'takeProfit': {'triggerPrice': 63204, 'type': 'TAKE_PROFIT_MARKET', 'workingType': 'MARK_PRICE'},
})
```
