### ISSUE TITLE
[plugin:vite:import-analysis] Failed to resolve import "http-proxy-agent" from "node_modules/.vite/deps/ccxt.js?v=9c98d43a". Does the file exist?

### ISSUE THREAD

**Issue by Unchanged-Is-Changed** [ccxt/ccxt#21555]
### Programming Languages

JavaScript

### CCXT Version

4.2.60

### Description

Vue3.3+vite4.4.9 run error

[plugin:vite:import-analysis] Failed to resolve import "http-proxy-agent" from "node_modules/.vite/deps/ccxt.js?v=9c98d43a". Does the file exist?

### Code

```
  
import ccxt from "ccxt";

const ccxtInstance = ccxt
const exchange = ccxtInstance.binance
```

**Comment by sc0Vu** [comment]
Hi @Unchanged-Is-Changed 

http-proxy-agent plugin is for nodejs. Did you install ccxt with npm? I can take a look locally.

**Comment by Unchanged-Is-Changed** [comment]
> Hi @Unchanged-Is-Changed
> 
> http-proxy-agent plugin is for nodejs. Did you install ccxt with npm? I can take a look locally.

Yes, I used npm install ccxt

**Comment by carlosmiei** [comment]
@Unchanged-Is-Changed Do you get that error before invoking any ccxt method? Is there a way of reproducing it easily on our side?

**Comment by sc0Vu** [comment]
It works for me with vue3 cli, is there any way I can reproduce locally?

**Comment by Unchanged-Is-Changed** [comment]
> @Unchanged-Is-Changed Do you get that error before invoking any ccxt method? Is there a way of reproducing it easily on our side?

[plugin:vite:import-analysis] Failed to resolve import "http-proxy-agent" from "node_modules/.vite/deps/ccxt.js?v=e627be04". Does the file exist?
/Users/leo/WebstormProjects/untitled5/node_modules/.vite/deps/ccxt.js:6204:11
6202|          this.httpProxyAgentModule = await import(
6203|            /* webpackIgnore: true */
6204|            "http-proxy-agent"
   |            ^
6205|          );
6206|          this.httpProxyAgentModule = await import(
    at formatError (file:///Users/leo/WebstormProjects/untitled5/node_modules/vite/dist/node/chunks/dep-52909643.js:44062:46)
    at TransformContext.error (file:///Users/leo/WebstormProjects/untitled5/node_modules/vite/dist/node/chunks/dep-52909643.js:44058:19)
    at normalizeUrl (file:///Users/leo/WebstormProjects/untitled5/node_modules/vite/dist/node/chunks/dep-52909643.js:41844:33)
    at async file:///Users/leo/WebstormProjects/untitled5/node_modules/vite/dist/node/chunks/dep-52909643.js:41998:47
    at async Promise.all (index 3)
    at async TransformContext.transform (file:///Users/leo/WebstormProjects/untitled5/node_modules/vite/dist/node/chunks/dep-52909643.js:41914:13)
    at async Object.transform (file:///Users/leo/WebstormProjects/untitled5/node_modules/vite/dist/node/chunks/dep-52909643.js:44352:30)
    at async loadAndTransform (file:///Users/leo/WebstormProjects/untitled5/node_modules/vite/dist/node/chunks/dep-52909643.js:55026:29)
    at async viteTransformMiddleware (file:///Users/leo/WebstormProjects/untitled5/node_modules/vite/di


When I run it, it will appear

**Comment by Unchanged-Is-Changed** [comment]
> @Unchanged-Is-Changed Do you get that error before invoking any ccxt method? Is there a way of reproducing it easily on our side?

I created a Vue project using WebStorm, then installed ccxt using npm, and wrote this code

const instance=new ccxt. binance()

When running, it will appear

**Comment by marcustut** [comment]
Try ccxt@3.1.1, that worked for me

**Comment by WRadoslaw** [comment]
I managed to get the latest version to run on Vite (with Solid.js in this case).

1. `npm i https-proxy-agent`
2. For vite launch dev mode `optimizeDeps` seems to be required.
3. For a build to succeed it was necessary to add `build.rollupOptions`

I hope this saves you some time and nerves :v: 

Here is my vite config file:
```js
import { defineConfig } from "vite";
import solidPlugin from "vite-plugin-solid";

import { nodePolyfills } from "vite-plugin-node-polyfills";
export default defineConfig({
  optimizeDeps: {
    include: ["http-proxy-agent"],
  },
  plugins: [
    solidPlugin(),
    nodePolyfills({
      protocolImports: true,
    }),
  ],
  server: {
    port: 4000,
  },
  build: {
    target: "esnext",
    rollupOptions: {
      external: ["http-proxy-agent"],
    },
  },
});
```

**Comment by marcustut** [comment]
> I managed to get the latest version to run on Vite (with Solid.js in this case).
> 
> 1. `npm i https-proxy-agent`
> 2. For vite launch dev mode `optimizeDeps` seems to be required.
> 3. For a build to succeed it was necessary to add `build.rollupOptions`
> 
> I hope this saves you some time and nerves ✌️
> 
> Here is my vite config file:
> 
> ```js
> import { defineConfig } from "vite";
> import solidPlugin from "vite-plugin-solid";
> 
> import { nodePolyfills } from "vite-plugin-node-polyfills";
> export default defineConfig({
>   optimizeDeps: {
>     include: ["http-proxy-agent"],
>   },
>   plugins: [
>     solidPlugin(),
>     nodePolyfills({
>       protocolImports: true,
>     }),
>   ],
>   server: {
>     port: 4000,
>   },
>   build: {
>     target: "esnext",
>     rollupOptions: {
>       external: ["http-proxy-agent"],
>     },
>   },
> });
> ```

This does solves the 'http-proxy-agent' issue but then now I get this instead, I guess it's something wrong with the polyfills:

```
✘ [ERROR] No matching export in "node_modules/.pnpm/node-stdlib-browser@1.2.0/node_modules/node-stdlib-browser/esm/mock/empty.js" for import "isIP"

    node_modules/.pnpm/ccxt@4.3.60/node_modules/ccxt/js/src/static_dependencies/node-fetch/utils/referrer.js:7:9:
      7 │ import { isIP } from 'node:net';
        ╵          ~~~~
```

**Comment by marcustut** [comment]
This is what worked for me on ccxt@4.3.69

```ts
import { TanStackRouterVite as tanstackRouterVite } from '@tanstack/router-plugin/vite';
import react from '@vitejs/plugin-react-swc';
import process from 'process';
import unfonts from 'unplugin-fonts/vite';
import { defineConfig } from 'vite';
import nodePolyfills from 'vite-plugin-node-stdlib-browser';
import tsconfigPaths from 'vite-tsconfig-paths';

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    target: 'esnext',
    outDir: '../server/assets',
    rollupOptions: {
      external: ['http-proxy-agent', 'https-proxy-agent', 'socks-proxy-agent'],
    },
  },
  optimizeDeps: { include: ['http-proxy-agent', 'https-proxy-agent', 'socks-proxy-agent'] },
  plugins: [
    tanstackRouterVite(),
    react(),
    nodePolyfills(),
    tsconfigPaths(),
    unfonts({
      custom: {
        families: [
          { name: 'Geist', src: './public/fonts/Geist-*.woff2' },
          { name: 'GeistMono', src: './public/fonts/GeistMono-*.woff2' },
        ],
      },
    }),
  ],
  define: {
    __APP_NAME__: JSON.stringify(process.env.npm_package_name),
    __APP_VERSION__: JSON.stringify(process.env.npm_package_version),
  },
});

```

**Comment by WRadoslaw** [comment]
> > I managed to get the latest version to run on Vite (with Solid.js in this case).
> > 
> > 1. `npm i https-proxy-agent`
> > 2. For vite launch dev mode `optimizeDeps` seems to be required.
> > 3. For a build to succeed it was necessary to add `build.rollupOptions`
> > 
> > I hope this saves you some time and nerves ✌️
> > Here is my vite config file:
> > ```js
> > import { defineConfig } from "vite";
> > import solidPlugin from "vite-plugin-solid";
> > 
> > import { nodePolyfills } from "vite-plugin-node-polyfills";
> > export default defineConfig({
> >   optimizeDeps: {
> >     include: ["http-proxy-agent"],
> >   },
> >   plugins: [
> >     solidPlugin(),
> >     nodePolyfills({
> >       protocolImports: true,
> >     }),
> >   ],
> >   server: {
> >     port: 4000,
> >   },
> >   build: {
> >     target: "esnext",
> >     rollupOptions: {
> >       external: ["http-proxy-agent"],
> >     },
> >   },
> > });
> > ```
> 
> This does solves the 'http-proxy-agent' issue but then now I get this instead, I guess it's something wrong with the polyfills:
> 
> ```
> ✘ [ERROR] No matching export in "node_modules/.pnpm/node-stdlib-browser@1.2.0/node_modules/node-stdlib-browser/esm/mock/empty.js" for import "isIP"
> 
>     node_modules/.pnpm/ccxt@4.3.60/node_modules/ccxt/js/src/static_dependencies/node-fetch/utils/referrer.js:7:9:
>       7 │ import { isIP } from 'node:net';
>         ╵          ~~~~
> ```

I created a patch over `node-stdlib-browser`, in their index.js they export `empty.js` as net even though they have mock implementation for the net package. I just replaced the path and it's running.

**Comment by klgd** [comment]
> > > I managed to get the latest version to run on Vite (with Solid.js in this case).
> > > 
> > > 1. `npm i https-proxy-agent`
> > > 2. For vite launch dev mode `optimizeDeps` seems to be required.
> > > 3. For a build to succeed it was necessary to add `build.rollupOptions`
> > > 
> > > I hope this saves you some time and nerves ✌️
> > > Here is my vite config file:
> > > ```js
> > > import { defineConfig } from "vite";
> > > import solidPlugin from "vite-plugin-solid";
> > > 
> > > import { nodePolyfills } from "vite-plugin-node-polyfills";
> > > export default defineConfig({
> > >   optimizeDeps: {
> > >     include: ["http-proxy-agent"],
> > >   },
> > >   plugins: [
> > >     solidPlugin(),
> > >     nodePolyfills({
> > >       protocolImports: true,
> > >     }),
> > >   ],
> > >   server: {
> > >     port: 4000,
> > >   },
> > >   build: {
> > >     target: "esnext",
> > >     rollupOptions: {
> > >       external: ["http-proxy-agent"],
> > >     },
> > >   },
> > > });
> > > ```
> > 
> > 
> > This does solves the 'http-proxy-agent' issue but then now I get this instead, I guess it's something wrong with the polyfills:
> > ```
> > ✘ [ERROR] No matching export in "node_modules/.pnpm/node-stdlib-browser@1.2.0/node_modules/node-stdlib-browser/esm/mock/empty.js" for import "isIP"
> > 
> >     node_modules/.pnpm/ccxt@4.3.60/node_modules/ccxt/js/src/static_dependencies/node-fetch/utils/referrer.js:7:9:
> >       7 │ import { isIP } from 'node:net';
> >         ╵          ~~~~
> > ```
> 
> I created a patch over `node-stdlib-browser`, in their index.js they export `empty.js` as net even though they have mock implementation for the net package. I just replaced the path and it's running.

@WRadoslaw  hi, how to fix this?

**Comment by devbymak** [comment]
It fixed for me just by installing these packages:
`npm i -D http-proxy-agent https-proxy-agent socks-proxy-agent`

**Comment by I-Mortals** [comment]
> It fixed for me just by installing these packages: `npm i -D http-proxy-agent https-proxy-agent socks-proxy-agent` I use React + Vite, I hope it saves you time.

I really wish I could see your solution sooner, I spent a lot of time trying every solution, thank you

**Comment by MatheusKlauck** [comment]
> It fixed for me just by installing these packages: `npm i -D http-proxy-agent https-proxy-agent socks-proxy-agent` I use React + Vite, I hope it saves you time.
> 
> Update: During the build process, I realized that the `@emreerdogan/vite-plugin-node-stdlib-browser` package is also required.

This worked for me, thank you!
