### ISSUE TITLE
FileNotFoundError python3.10/site-packages/ccxt/static_dependencies/ethereum/utils/__json/eth_networks.json'

### ISSUE THREAD

**Issue by jiangxiaochuan** [ccxt/ccxt#21569]
### Operating System

macos m1

### Programming Languages

Python

### CCXT Version

4.2.61

### Description

Traceback (most recent call last):
  File "/Users/jiangxch/program/python/project/quant/main.py", line 6, in <module>
    import ccxt
  File "/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/base/exchange.py", line 57, in <module>
    from ccxt.static_dependencies.ethereum import abi
  File "/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/static_dependencies/ethereum/__init__.py", line 1, in <module>
    from .abi import *
  File "/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/static_dependencies/ethereum/abi/__init__.py", line 2, in <module>
    from .abi import (
  File "/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/static_dependencies/ethereum/abi/abi.py", line 1, in <module>
    from .codec import (
  File "/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/static_dependencies/ethereum/abi/codec.py", line 12, in <module>
    from ..utils import (
  File "/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/static_dependencies/ethereum/utils/__init__.py", line 100, in <module>
    from .network import (
  File "/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/static_dependencies/ethereum/utils/network.py", line 61, in <module>
    networks = initialize_network_objects()
  File "/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/static_dependencies/ethereum/utils/network.py", line 34, in initialize_network_objects
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jiangxch/anaconda3/envs/quant/lib/python3.10/site-packages/ccxt/static_dependencies/ethereum/utils/__json/eth_networks.json'

### Code

```
  

```

**Comment by yota-p** [comment]
Seeing same error, seems [ccxt/static_dependencies/ethereum/utils/__json/eth_networks.json](https://github.com/ccxt/ccxt/blob/45d8e269b931a311dd9469f9c196d8317d65d9e9/python/ccxt/static_dependencies/ethereum/utils/__json/eth_networks.json)  is not included in the package. 

Quick workaround is to create the eth_networks.json. 
```
mkdir /path/to/your/ccxt/static_dependencies/ethereum/utils/__json/
touch /path/to/your/ccxt/static_dependencies/ethereum/utils/__json/eth_networks.json
vi /path/to/your/ccxt/static_dependencies/ethereum/utils/__json/eth_networks.json
# paste the content of eth_networks.json
```

I'll wait for others to come up with permanent fix.

**Comment by wsicks** [comment]
@jiangxiaochuan You can download the file manually to the folder

**Comment by carlosmiei** [comment]
@wsicks @galal27 @yota-p @jiangxiaochuan Can you please update your ccxt version and try again?

**Comment by yota-p** [comment]
Updated to 4.2.62 and now it's working for me. Thank you!

**Comment by carlosmiei** [comment]
@yota-p Thanks for letting us know!
