### ISSUE TITLE
CCXT eth_networks.json error

### ISSUE THREAD

**Issue by durthui** [ccxt/ccxt#21574]
### Operating System

Ubuntu 22.04.4 LTS

### Programming Languages

Python

### CCXT Version

ccxt 4.2.63 

### Description

Traceback (most recent call last):
  File "/root/cct.py", line 1, in <module>
    import ccxt
  File "/usr/local/lib/python3.10/dist-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/usr/local/lib/python3.10/dist-packages/ccxt/base/exchange.py", line 57, in <module>
    from ccxt.static_dependencies.ethereum import abi
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/__init__.py", line 1, in <module>
    from .abi import *
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/abi/__init__.py", line 2, in <module>
    from .abi import (
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/abi/abi.py", line 1, in <module>
    from .codec import (
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/abi/codec.py", line 12, in <module>
    from ..utils import (
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/utils/__init__.py", line 100, in <module>
    from .network import (
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/utils/network.py", line 61, in <module>
    networks = initialize_network_objects()
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/utils/network.py", line 34, in initialize_network_objects
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/utils/__json/eth_networks.json'

### Code

```
  Traceback (most recent call last):
  File "/root/cct.py", line 1, in <module>
    import ccxt
  File "/usr/local/lib/python3.10/dist-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/usr/local/lib/python3.10/dist-packages/ccxt/base/exchange.py", line 57, in <module>
    from ccxt.static_dependencies.ethereum import abi
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/__init__.py", line 1, in <module>
    from .abi import *
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/abi/__init__.py", line 2, in <module>
    from .abi import (
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/abi/abi.py", line 1, in <module>
    from .codec import (
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/abi/codec.py", line 12, in <module>
    from ..utils import (
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/utils/__init__.py", line 100, in <module>
    from .network import (
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/utils/network.py", line 61, in <module>
    networks = initialize_network_objects()
  File "/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/utils/network.py", line 34, in initialize_network_objects
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ethereum/utils/__json/eth_networks.json'


```

**Comment by carlosmiei** [comment]
Hello @durthui can you please double-check you're using the latest version (4.2.63)? (we noticed the error but the lastest version should fix it)

If that does not work (and while we an alternative), you can also copy the file from here https://github.com/ccxt/ccxt/tree/master/python/ccxt/static_dependencies/ethereum/utils/__json and paste it the folder mentioned `ccxt/static_dependencies/ethereum/utils/__json/eth_networks.json'`

**Comment by telge1** [comment]
Hi,
i have the same issue and i paste the .json file in the right folder i had to create new folders but is not working i get the same error.

**Comment by carlosmiei** [comment]
@telge1 Did you update to the latest?

**Comment by sc0Vu** [comment]
@carlosmiei how do you think we remove the network ids from library (don't use in core for now)?
