### ISSUE TITLE
bitfinex ERR_RATE_LIMIT

### ISSUE THREAD

**Issue by nerdDan** [ccxt/ccxt#2166]
error `ERR_RATE_LIMIT` keeps popping up when fetching order book continuously.

test code
```python
import asyncio
import logging

import ccxt.async as ccxt


async def fetch_from_exchange(ex, pairs):
    for pair in pairs:
        while True:
            try:
                order_book = await ex.fetch_order_book(pair)
                break
            except (
                    ccxt.DDoSProtection, ccxt.ExchangeError, ccxt.ExchangeNotAvailable,
                    ccxt.RequestTimeout) as err:
                logging.exception(err)
                await asyncio.sleep(16)


async def main():
    logging.info('ccxt version is '+ccxt.__version__)
    pairs = ['ETH/BTC', 'EOS/BTC', 'EOS/ETH', 'XMR/BTC']
    ex = ccxt.bitfinex(dict(enableRateLimit=True, verbose=True))
    await ex.load_markets()
    while True:
        await fetch_from_exchange(ex, pairs)


if __name__ == '__main__':
    logging.basicConfig(
        format='%(asctime)s: %(levelname)s %(message)s',
        level=logging.INFO)
    asyncio.get_event_loop().run_until_complete(main())
```

output
```
➜  razor git:(master) ✗ python3 t.py
2018-03-08 05:53:01,211: INFO ccxt version is 1.11.41

Request: GET https://api.bitfinex.com/v1/symbols_details {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'} None

Response: GET https://api.bitfinex.com/v1/symbols_details 200 <CIMultiDictProxy('Date': 'Thu, 08 Mar 2018 05:53:01 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d809cb605a72c15128d8dfb5dd30c83dc1520488381; expires=Fri, 08-Mar-19 05:53:01 GMT; path=/; domain=.bitfinex.com; HttpOnly', 'Vary': 'Accept-Encoding', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'ETag': 'W/"a1835ba842eac6a3fca708f50d28548f"', 'Cache-Control': 'max-age=0, private, must-revalidate', 'X-Request-Id': '3791273c-a5a2-4330-885e-373eba06af44', 'X-Runtime': '0.234644', 'Strict-Transport-Security': 'max-age=31536000', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Encoding': 'gzip', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '3f8309fedaeb850e-HKG')> [{"pair":"btcusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.002","expiration":"NA","margin":true},{"pair":"ltcusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.08","expiration":"NA","margin":true},{"pair":"ltcbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.08","expiration":"NA","margin":true},{"pair":"ethusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.02","expiration":"NA","margin":true},{"pair":"ethbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.02","expiration":"NA","margin":true},{"pair":"etcbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"0.6","expiration":"NA","margin":true},{"pair":"etcusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"0.6","expiration":"NA","margin":true},{"pair":"rrtusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"190.0","expiration":"NA","margin":false},{"pair":"rrtbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"190.0","expiration":"NA","margin":false},{"pair":"zecusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"20000.0","minimum_order_size":"0.04","expiration":"NA","margin":true},{"pair":"zecbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"20000.0","minimum_order_size":"0.04","expiration":"NA","margin":true},{"pair":"xmrusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.06","expiration":"NA","margin":true},{"pair":"xmrbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.06","expiration":"NA","margin":true},{"pair":"dshusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.02","expiration":"NA","margin":true},{"pair":"dshbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"5000.0","minimum_order_size":"0.02","expiration":"NA","margin":true},{"pair":"btceur","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.002","expiration":"NA","margin":true},{"pair":"xrpusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"14.0","expiration":"NA","margin":true},{"pair":"xrpbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"14.0","expiration":"NA","margin":true},{"pair":"iotusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"6.0","expiration":"NA","margin":true},{"pair":"iotbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"6.0","expiration":"NA","margin":true},{"pair":"ioteth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"6.0","expiration":"NA","margin":true},{"pair":"eosusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"2.0","expiration":"NA","margin":true},{"pair":"eosbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"2.0","expiration":"NA","margin":true},{"pair":"eoseth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"2.0","expiration":"NA","margin":true},{"pair":"sanusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"8.0","expiration":"NA","margin":true},{"pair":"sanbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"8.0","expiration":"NA","margin":true},{"pair":"saneth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"8.0","expiration":"NA","margin":true},{"pair":"omgusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"1.0","expiration":"NA","margin":true},{"pair":"omgbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"1.0","expiration":"NA","margin":true},{"pair":"omgeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"1.0","expiration":"NA","margin":true},{"pair":"bchusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.02","expiration":"NA","margin":true},{"pair":"bchbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.02","expiration":"NA","margin":true},{"pair":"bcheth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.02","expiration":"NA","margin":true},{"pair":"neousd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"10000.0","minimum_order_size":"0.2","expiration":"NA","margin":true},{"pair":"neobtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"10000.0","minimum_order_size":"0.2","expiration":"NA","margin":true},{"pair":"neoeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"10000.0","minimum_order_size":"0.2","expiration":"NA","margin":true},{"pair":"etpusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"10000.0","minimum_order_size":"8.0","expiration":"NA","margin":true},{"pair":"etpbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"10000.0","minimum_order_size":"8.0","expiration":"NA","margin":true},{"pair":"etpeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"10000.0","minimum_order_size":"8.0","expiration":"NA","margin":true},{"pair":"qtmusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.4","expiration":"NA","margin":false},{"pair":"qtmbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.4","expiration":"NA","margin":false},{"pair":"qtmeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.4","expiration":"NA","margin":false},{"pair":"avtusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"6.0","expiration":"NA","margin":false},{"pair":"avtbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"6.0","expiration":"NA","margin":false},{"pair":"avteth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"6.0","expiration":"NA","margin":false},{"pair":"edousd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"6.0","expiration":"NA","margin":true},{"pair":"edobtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"6.0","expiration":"NA","margin":true},{"pair":"edoeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"6.0","expiration":"NA","margin":true},{"pair":"btgusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.2","expiration":"NA","margin":true},{"pair":"btgbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"2000.0","minimum_order_size":"0.2","expiration":"NA","margin":true},{"pair":"datusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"250000.0","minimum_order_size":"122.0","expiration":"NA","margin":false},{"pair":"datbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"250000.0","minimum_order_size":"122.0","expiration":"NA","margin":false},{"pair":"dateth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"250000.0","minimum_order_size":"122.0","expiration":"NA","margin":false},{"pair":"qshusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"14.0","expiration":"NA","margin":false},{"pair":"qshbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"14.0","expiration":"NA","margin":false},{"pair":"qsheth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"14.0","expiration":"NA","margin":false},{"pair":"yywusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"106.0","expiration":"NA","margin":false},{"pair":"yywbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"106.0","expiration":"NA","margin":false},{"pair":"yyweth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"50000.0","minimum_order_size":"106.0","expiration":"NA","margin":false},{"pair":"gntusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"32.0","expiration":"NA","margin":false},{"pair":"gntbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"32.0","expiration":"NA","margin":false},{"pair":"gnteth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"32.0","expiration":"NA","margin":false},{"pair":"sntusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"64.0","expiration":"NA","margin":false},{"pair":"sntbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"64.0","expiration":"NA","margin":false},{"pair":"snteth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"64.0","expiration":"NA","margin":false},{"pair":"ioteur","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"100000.0","minimum_order_size":"6.0","expiration":"NA","margin":true},{"pair":"batusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"32.0","expiration":"NA","margin":false},{"pair":"batbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"32.0","expiration":"NA","margin":false},{"pair":"bateth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"32.0","expiration":"NA","margin":false},{"pair":"mnausd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"114.0","expiration":"NA","margin":false},{"pair":"mnabtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"114.0","expiration":"NA","margin":false},{"pair":"mnaeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"114.0","expiration":"NA","margin":false},{"pair":"funusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"208.0","expiration":"NA","margin":false},{"pair":"funbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"208.0","expiration":"NA","margin":false},{"pair":"funeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"208.0","expiration":"NA","margin":false},{"pair":"zrxusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"14.0","expiration":"NA","margin":false},{"pair":"zrxbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"14.0","expiration":"NA","margin":false},{"pair":"zrxeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"14.0","expiration":"NA","margin":false},{"pair":"tnbusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"284.0","expiration":"NA","margin":false},{"pair":"tnbbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"284.0","expiration":"NA","margin":false},{"pair":"tnbeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"284.0","expiration":"NA","margin":false},{"pair":"spkusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"68.0","expiration":"NA","margin":false},{"pair":"spkbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"68.0","expiration":"NA","margin":false},{"pair":"spketh","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"68.0","expiration":"NA","margin":false},{"pair":"trxusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"1000000.0","minimum_order_size":"300.0","expiration":"NA","margin":false},{"pair":"trxbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"1000000.0","minimum_order_size":"300.0","expiration":"NA","margin":false},{"pair":"trxeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"1000000.0","minimum_order_size":"300.0","expiration":"NA","margin":false},{"pair":"rcnusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"80.0","expiration":"NA","margin":false},{"pair":"rcnbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"80.0","expiration":"NA","margin":false},{"pair":"rcneth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"80.0","expiration":"NA","margin":false},{"pair":"rlcusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"25000.0","minimum_order_size":"10.0","expiration":"NA","margin":false},{"pair":"rlcbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"25000.0","minimum_order_size":"10.0","expiration":"NA","margin":false},{"pair":"rlceth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"25000.0","minimum_order_size":"10.0","expiration":"NA","margin":false},{"pair":"aidusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"40.0","expiration":"NA","margin":false},{"pair":"aidbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"40.0","expiration":"NA","margin":false},{"pair":"aideth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"40.0","expiration":"NA","margin":false},{"pair":"sngusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"124.0","expiration":"NA","margin":false},{"pair":"sngbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"124.0","expiration":"NA","margin":false},{"pair":"sngeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"200000.0","minimum_order_size":"124.0","expiration":"NA","margin":false},{"pair":"repusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"1000.0","minimum_order_size":"0.2","expiration":"NA","margin":false},{"pair":"repbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"1000.0","minimum_order_size":"0.2","expiration":"NA","margin":false},{"pair":"repeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"1000.0","minimum_order_size":"0.2","expiration":"NA","margin":false},{"pair":"elfusd","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"25000.0","minimum_order_size":"12.0","expiration":"NA","margin":false},{"pair":"elfbtc","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"25000.0","minimum_order_size":"12.0","expiration":"NA","margin":false},{"pair":"elfeth","price_precision":5,"initial_margin":"30.0","minimum_margin":"15.0","maximum_order_size":"25000.0","minimum_order_size":"12.0","expiration":"NA","margin":false}]

Request: GET https://api.bitfinex.com/v1/book/ETHBTC {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'} None
2018-03-08 05:53:03,228: ERROR bitfinex {"error":"ERR_RATE_LIMIT"}
Traceback (most recent call last):
  File "t.py", line 11, in fetch_from_exchange
    order_book = await ex.fetch_order_book(pair)
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/bitfinex.py", line 375, in fetch_order_book
    orderbook = await self.publicGetBookSymbol(self.extend(request, params))
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/base/exchange.py", line 102, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/base/exchange.py", line 129, in fetch
    self.handle_errors(http_status_code, text, url, method, self.last_response_headers, text)
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/bitfinex.py", line 750, in handle_errors
    raise exact[message](feedback)
ccxt.base.errors.DDoSProtection: bitfinex {"error":"ERR_RATE_LIMIT"}

Request: GET https://api.bitfinex.com/v1/book/ETHBTC {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'} None
2018-03-08 05:53:19,255: ERROR bitfinex {"error":"ERR_RATE_LIMIT"}
Traceback (most recent call last):
  File "t.py", line 11, in fetch_from_exchange
    order_book = await ex.fetch_order_book(pair)
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/bitfinex.py", line 375, in fetch_order_book
    orderbook = await self.publicGetBookSymbol(self.extend(request, params))
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/base/exchange.py", line 102, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/base/exchange.py", line 129, in fetch
    self.handle_errors(http_status_code, text, url, method, self.last_response_headers, text)
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/bitfinex.py", line 750, in handle_errors
    raise exact[message](feedback)
ccxt.base.errors.DDoSProtection: bitfinex {"error":"ERR_RATE_LIMIT"}

Request: GET https://api.bitfinex.com/v1/book/ETHBTC {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'} None
2018-03-08 05:53:35,285: ERROR bitfinex {"error":"ERR_RATE_LIMIT"}
Traceback (most recent call last):
  File "t.py", line 11, in fetch_from_exchange
    order_book = await ex.fetch_order_book(pair)
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/bitfinex.py", line 375, in fetch_order_book
    orderbook = await self.publicGetBookSymbol(self.extend(request, params))
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/base/exchange.py", line 102, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/base/exchange.py", line 129, in fetch
    self.handle_errors(http_status_code, text, url, method, self.last_response_headers, text)
  File "/home/dan/.local/lib/python3.5/site-packages/ccxt/async/bitfinex.py", line 750, in handle_errors
    raise exact[message](feedback)
ccxt.base.errors.DDoSProtection: bitfinex {"error":"ERR_RATE_LIMIT"}
```

**Comment by mkutny** [comment]
Their rate limit varies depending on their load so it happens from time to time. The suggestion is to increase `rateLimit` when you start seeing this.

**Comment by nerdDan** [comment]
@mkutny 
I have been running this script for weeks, and the `ERR_RATE_LIMIT` error occurs all the time, not time to time, and it only occurs to bitfinex, other exchanges are fine. I wonder how does other users handle bitfinex. Is `rateLimit` necessary for bitfinex?

**Comment by mkutny** [comment]
> it only occurs to bitfinex, other exchanges are fine

That's because bitfinex has floating rate limit, they adjust it depending on their load.

> I wonder how do other users handle bitfinex

They increase `rateLimit` when they start seeing `DDoSProtection`.

**Comment by nerdDan** [comment]
> They increase rateLimit when they start seeing DDoSProtection.

Could this trick possibly be a part of ccxt?

**Comment by mkutny** [comment]
> Could this trick possibly be a part of ccxt?

Yeah, I think so... Still, not obvious what part of such back off algo should be integrated. You may do it yourself and see if it's possible to make a PR from that.

**Comment by npomfret** [comment]
Any idea how long bitfinex takes to remove your ERR_RATE_LIMIT errors?  I've been locked out for a few hours now.

**Comment by kroitor** [comment]
@npomfret it's usually from a few minutes to 24 hours depending on how aggressive they think you were... I would raise alarms if it doesn't self-resolve within that period.
