### ISSUE TITLE
In coinbase and okx how do I put StopLoss the key 

### ISSUE THREAD

**Issue by MP-AAMIR** [ccxt/ccxt#21675]
### Operating System

Linux

### CCXT Version

    "ccxt": "^4.2.64",

### Code

```
  

```

**Comment by MP-AAMIR** [comment]
![image](https://github.com/ccxt/ccxt/assets/146868617/7b56daff-e776-44e1-a62f-0d1a083c54e1)
I am using coinbase for stopLoss below is my code I am getting exchageerror 
(async () => {
  try {
    const coinbase = new ccxt.coinbase();
    coinbase.apiKey = "apiKey";
    coinbase.secret = "secretKey";
    // sell order for stop loss for 0.001 limit sell stopLoss
    const createOrder = await coinbase.createOrder('BTC/USD', 'limit', 'sell' ,'0.00001500' ,'67203.38', { stopPrice: '66536' }); 
    console.log(createOrder, "createOrder");
    
    // console.log("Converted balance:", balance.total);
  } catch (error) {
    console.log(error, "error");
  }
})();

ExchangeError
    at coinbase.createOrder (/home/mobileprogramming/JS/kraken/node_modules/ccxt/dist/cjs/src/coinbase.js:2494:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/mobileprogramming/JS/kraken/kraken.js:301:25 error
    
  This is exchangeError coming from coinbase please help me

**Comment by samgermain** [comment]
You use `stopPrice` in your code example, and `stopLossPrice` in your screenshot. They do different things. 

Please read the definitions on these issues

https://github.com/ccxt/ccxt/issues/12044
https://github.com/ccxt/ccxt/issues/13822

-----------------

Also, the price and amount arguments should be numbers, not strings

**Comment by MP-AAMIR** [comment]
Which is the correct key to use because I have used both the key and
getting same error exchange error.

**Comment by MP-AAMIR** [comment]
I have used stopLossPrice in number as suggested but it is giving me ExhangeError but when I am going for a simple limit sell or buy it's executing with coinbase 
![image](https://github.com/ccxt/ccxt/assets/146868617/50f65cfb-a30a-44e6-a158-a443e4f520c3)

**Comment by carlotestor** [comment]
`stopPrice` is deprecated — the unified param names decide *which kind* of order you get, and they're different things:

- **`triggerPrice`** — a plain trigger/conditional order (fires when price is touched, either direction)
- **`stopLossPrice`** — a stop-loss (closes/reduces a position)
- **`takeProfitPrice`** — a take-profit

For **Coinbase**, use `stopLossPrice` and pass numbers, not strings:

```js
const coinbase = new ccxt.coinbase ({ apiKey, secret });
await coinbase.loadMarkets ();

// stop-limit sell: trigger at 66536, limit price 67203.38
const order = await coinbase.createOrder ('BTC/USD', 'limit', 'sell', 0.000015, 67203.38, {
    'stopLossPrice': 66536,
});
```

CCXT derives Coinbase's `stop_direction` automatically from the side; override with `params['stop_direction']` (`'STOP_DIRECTION_STOP_UP'` / `'STOP_DIRECTION_STOP_DOWN'`) if you need the opposite.

For **OKX** it's the same unified names:

```js
await okx.createOrder ('BTC/USDT:USDT', 'limit', 'sell', 0.01, 67203, { 'stopLossPrice': 66536 });
await okx.createOrder ('BTC/USDT:USDT', 'market', 'sell', 0.01, undefined, { 'takeProfitPrice': 70000 });
```

If you still get an `ExchangeError` after switching to `stopLossPrice` with numeric args, it's almost certainly amount/notional: Coinbase rejects orders below its minimum size, and `0.000015 BTC` is very likely under it. Check `coinbase.markets['BTC/USD']['limits']` and round with `amountToPrecision`/`priceToPrecision`.

Background reading: https://github.com/ccxt/ccxt/issues/12044
