### ISSUE TITLE
Bingx: Bug in Websocket - Unstable when consuming order

### ISSUE THREAD

**Issue by nvrossett** [ccxt/ccxt#21685]
### Operating System

Debian

### Programming Languages

JavaScript

### CCXT Version

4.2.69

### Description

Bingx was returning this error in the orders websocket which was causing some instabilities here.
```
TypeError: Cannot set properties of undefined(setting 'info')
    at bingx.handleBalance(/home/nvieira/www/node_modules/ccxt/dist/cjs/src/pro/bingx.js: 1026: 36)
    at bingx.handleMessage(/home/nvieira/www/node_modules/ccxt/dist/cjs/src/pro/bingx.js: 1081: 18)
    at WsClient.onMessage(/home/nvieira/www/node_modules/ccxt/dist/cjs/src/base/ws/Client.js: 297: 18)
    at callListener(/home/nvieira/www/node_modules/ws/lib/event - target.js: 290: 14)
    at WebSocket.onMessage(/home/nvieira/www/node_modules/ws/lib/event - target.js: 209: 9)
    at WebSocket.emit(node: events: 514: 28)
    at Receiver.receiverOnMessage(/home/nvieira/www/node_modules/ws/lib/websocket.js: 1209: 20)
    at Receiver.emit(node: events: 514: 28)
at/home/nvieira/www/node_modules/ws/lib/receiver.js: 581: 16
    at node: internal/process/task_queues: 140: 7
```

Seeing this I went after the file:
**ccxt/dist/cjs/src/pro/bingx.js: 1026**

And there I found the function
**handleBalance(client, message)**

And I found this snippet of code:
```
    const a = this.safeValue(message, 'a', {});
    const data = this.safeValue(a, 'B', []);
    const timestamp = this.safeInteger2(message, 'T', 'E');
    const type = ('P' in a) ? 'swap' : 'spot';
    this.balance[type]['info'] = data;
    this.balance[type]['timestamp'] = timestamp;
    this.balance[type]['datetime'] = this.iso8601(timestamp);
```

When I found this excerpt it became easier to understand what was happening, and I fixed it here on my side by just adding:
**this.balance[type] ??= {}**
```
    const a = this.safeValue(message, 'a', {});
    const data = this.safeValue(a, 'B', []);
    const timestamp = this.safeInteger2(message, 'T', 'E');
    const type = ('P' in a) ? 'swap' : 'spot';
    this.balance[type] ??= {} // <----------- This line
    this.balance[type]['info'] = data;
    this.balance[type]['timestamp'] = timestamp;
    this.balance[type]['datetime'] = this.iso8601(timestamp);
```

And the problem is solved

From what I understand, apparently this caused a crash in something that was not processing order requests sent to the server, so it stopped listening to some channels.

When I added this line everything worked here

**Comment by sc0Vu** [comment]
Hi @nvrossett, can you paste code or verbose log that I can reproduce locally? We did initialize the balance cache, wonder whether it's async request issue or not.

**Comment by nvrossett** [comment]
Of course, below is my code and the verbose

I simply started the bot and let it connect to the websocket

If I submit an order through the broker itself, when it receives this information, this error appears

When it happens to several assets simultaneously, it stops receiving updates, I don't know why but it must generate a chain reaction of errors


Code:

 ```
while (true) {

                try {

                    const orders = await MYTH.EXCHANGE.CCXT.watchOrders()
                    // Internal function of my system
                    MYTH.PassiveMode.TRIGGER.orders(orders, 'watchOrders:' + describe, MYTH)
                    if (throttling >= 0) { await MYTH.EXCHANGE.CCXT.sleep(throttling) }

                } catch (error) {
                    // Internal function of my system
                    await MYTH.EXCHANGE.disconnect('Error in MYTH.PassiveMode.watchOrders - watchOrders()', error, MYTH)
                }
            }
```

Verbose:
```
2024-03-13T04:19:59.300Z onMessage {
  code: 0,
  dataType: 'DOT-USDT@ticker',
  data: {
    e: '24hTicker',
    E: 1710303599005,
    s: 'DOT-USDT',
    p: '-0.098',
    P: '-0.89',
    c: '10.854',
    L: '2.5',
    h: '10.971',
    l: '10.056',
    v: '4923153.3',
    q: '52313342.48',
    o: '10.952',
    O: 1710303597744,
    C: 1710303577416,
    A: '10.854',
    a: '684.3',
    B: '10.853',
    b: '4.5'
  }
}
handleRestResponse:
 bingx GET https://open-api.bingx.com/openApi/swap/v2/user/balance?timestamp=1710303598913&signature=e72d26a96c67eeee2c5d70121c9c0bf79a650dac328e9053cb05d10b36c266a0 200 OK 
ResponseHeaders:
 {
  'Alt-Svc': 'h3=":443"; ma=86400',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '86393a95387f6043-GRU',
  Connection: 'keep-alive',
  'Content-Encoding': 'br',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Wed, 13 Mar 2024 04:19:59 GMT',
  Server: 'cloudflare',
  'Set-Cookie': '__cf_bm=MThbhcg0Yps2f0KlS8aEEj1zH23MrcGjVKJB.qDMqak-1710303599-1.0.1.1-GbQac96klm159Rbh7EWDEUO3Zma3Tueb2cIuX9ahSqf.01p_Ma9km7VaoCqdsbfoTNpvfxwA5dgP._CwvjZesA; path=/; expires=Wed, 13-Mar-24 04:49:59 GMT; domain=.bingx.com; HttpOnly; Secure; SameSite=None, _cfuvid=2jz3zENa84Rmuq4SKVsadx9wWa7qNurkO35jdqfilGQ-1710303599288-0.0.1.1-604800000; path=/; domain=.bingx.com; HttpOnly; Secure; SameSite=None',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload',
  'Transfer-Encoding': 'chunked',
  Vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
  'X-Content-Type-Options': 'nosniff',
  'X-Source-Key': 'CCXT'
} 
ResponseBody:
 {"code":0,"msg":"","data":{"balance":{"userId":"1278607554777677827","asset":"USDT","balance":"404.0629","equity":"404.0623","unrealizedProfit":"-0.0006","realisedProfit":"-0.0044","availableMargin":"402.3137","usedMargin":"1.7486","freezedMargin":"0.0000"}}} 
DOT/USDT:USDT 10.854
fetch Request:
 bingx POST https://open-api.bingx.com/openApi/swap/v2/trade/order?clientOrderID=528n81-dpe3rTed50-a3d8165O2701&positionSide=BOTH&quantity=3&side=BUY&symbol=DOT-USDT&timestamp=1710303599612&type=MARKET&workingType=CONTRACT_PRICE&signature=cbb902ded359c650554fab23524752501cf1d6fde4425837035a740aed8b8a46
RequestHeaders:
 {
  'X-BX-APIKEY': 'pQiP0K4jp56oyv5FkuVb3h6GN0hdyRUR4I3svDvaFzVaIzeUtjoesrQI31gB5xclsoPntzbcFcGjigkt8CbRg',
  'X-SOURCE-KEY': 'CCXT'
} 
RequestBody:
 undefined 
2024-03-13T04:20:00.001Z onMessage {
  e: 'ACCOUNT_UPDATE',
  E: 1710303599591,
  a: { m: 'ORDER', B: [ [Object] ], P: [ [Object] ] }
}
Error in MYTH.PassiveMode.watchOrders - watchOrders()
TypeError: Cannot set properties of undefined (setting 'info')
    at bingx.handleBalance (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/pro/bingx.js:1026:36)
    at bingx.handleMessage (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/pro/bingx.js:1081:18)
    at WsClient.onMessage (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/base/ws/Client.js:297:18)
    at callListener (/home/nvieira/www/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/nvieira/www/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:514:28)
    at Receiver.receiverOnMessage (/home/nvieira/www/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:514:28)
    at /home/nvieira/www/node_modules/ws/lib/receiver.js:581:16
    at node:internal/process/task_queues:140:7
handleRestResponse:
 bingx POST https://open-api.bingx.com/openApi/swap/v2/trade/order?clientOrderID=528n81-dpe3rTed50-a3d8165O2701&positionSide=BOTH&quantity=3&side=BUY&symbol=DOT-USDT&timestamp=1710303599612&type=MARKET&workingType=CONTRACT_PRICE&signature=cbb902ded359c650554fab23524752501cf1d6fde4425837035a740aed8b8a46 200 OK
ResponseHeaders:
 {
  'Alt-Svc': 'h3=":443"; ma=86400',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '86393a9999dd6043-GRU',
  Connection: 'keep-alive',
  'Content-Encoding': 'br',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Wed, 13 Mar 2024 04:20:00 GMT',
  Server: 'cloudflare',
  'Set-Cookie': '__cf_bm=WxSxQr_QiBiz9Idtsz28j3bVmOa227CI52dL22L7GOs-1710303600-1.0.1.1-Cdi.mNmmghR0uEhHS1NQWqtGb6NYrKF.mEdOsu.GdkSN4t_wOVNIGepR5dRu1BvLPLEcdpJffqiYJWIljddpBg; path=/; expires=Wed, 13-Mar-24 04:50:00 GMT; domain=.bingx.com; HttpOnly; Secure; SameSite=None, _cfuvid=eoPb97mmx.mUIS7Tws5lvHaJAprKhWu4GwX53iYKYww-1710303600041-0.0.1.1-604800000; path=/; domain=.bingx.com; HttpOnly; Secure; SameSite=None',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload',
  'Transfer-Encoding': 'chunked',
  Vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
  'X-Content-Type-Options': 'nosniff',
  'X-Source-Key': 'CCXT'
} 
ResponseBody:
 {"code":0,"msg":"","data":{"order":{"orderId":1767767539943940096,"symbol":"DOT-USDT","positionSide":"BOTH","side":"BUY","type":"MARKET","price":0,"quantity":3,"stopPrice":0,"workingType":"MARK_PRICE","clientOrderID":"528n81-dpe3rTed50-a3d8165O2701","timeInForce":"GTC","priceRate":0,"stopLoss":"","takeProfit":"","reduceOnly":false,"activationPrice":0,"closePosition":"","stopGuaranteed":""}}} 
2024-03-13T04:20:00.065Z onMessage {
  e: 'ORDER_TRADE_UPDATE',
  E: 1710303599597,
  o: {
    s: 'BCH-USDT',
    c: '',
    i: '1767767539205742592',
    S: 'SELL',
    o: 'MARKET',
    q: '0.02000000',
    p: '437.12006772',
    sp: '0.00000000',
    ap: '437.10000000',
    x: 'TRADE',
    X: 'FILLED',
    N: 'USDT',
    n: '-0.00437100',
    T: 0,
    wt: 'MARK_PRICE',
    ps: 'BOTH',
    rp: '-0.00100000',
    z: '0.02000000'
  }
}
watchOrders:Realtime [
  {
    info: {
      s: 'BCH-USDT',
      c: '',
      i: '1767767539205742592',
      S: 'SELL',
      o: 'MARKET',
      q: '0.02000000',
      p: '437.12006772',
      sp: '0.00000000',
      ap: '437.10000000',
      x: 'TRADE',
      X: 'FILLED',
      N: 'USDT',
      n: '-0.00437100',
      T: 0,
      wt: 'MARK_PRICE',
      ps: 'BOTH',
      rp: '-0.00100000',
      z: '0.02000000'
    },
    id: '1767767539205742592',
    clientOrderId: undefined,
    symbol: 'BCH/USDT:USDT',
    timestamp: undefined,
    datetime: undefined,
    lastTradeTimestamp: 0,
    lastUpdateTimestamp: undefined,
    type: 'market',
    timeInForce: 'IOC',
    postOnly: undefined,
    side: 'sell',
    price: 437.12006772,
    stopPrice: undefined,
    triggerPrice: undefined,
    stopLossPrice: undefined,
    takeProfitPrice: undefined,
    average: 437.1,
    cost: 0.08742,
    amount: 0.02,
    filled: 0.02,
    remaining: 0,
    status: 'closed',
    fee: { currency: 'USDT', cost: '0.004371' },
    trades: [],
    reduceOnly: undefined,
    fees: [ [Object] ]
  }
]
2024-03-13T04:20:00.190Z onMessage {
  e: 'ACCOUNT_UPDATE',
  E: 1710303599769,
  a: { m: 'ORDER', B: [ [Object] ], P: [ [Object] ] }
}
Error in MYTH.PassiveMode.watchOrders - watchOrders()
TypeError: Cannot set properties of undefined (setting 'info')
    at bingx.handleBalance (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/pro/bingx.js:1026:36)
    at bingx.handleMessage (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/pro/bingx.js:1081:18)
    at WsClient.onMessage (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/base/ws/Client.js:297:18)
    at callListener (/home/nvieira/www/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/nvieira/www/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:514:28)
    at Receiver.receiverOnMessage (/home/nvieira/www/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:514:28)
    at /home/nvieira/www/node_modules/ws/lib/receiver.js:581:16
    at node:internal/process/task_queues:140:7
2024-03-13T04:20:00.194Z onMessage {
  e: 'ORDER_TRADE_UPDATE',
  E: 1710303599779,
  o: {
    s: 'DOT-USDT',
    c: '528n81-dpe3rTed50-a3d8165O2701',
    i: '1767767539943940096',
    S: 'BUY',
    o: 'MARKET',
    q: '3.00000000',
    p: '10.85436637',
    sp: '0.00000000',
    ap: '10.85400000',
    x: 'TRADE',
    X: 'FILLED',
    N: 'USDT',
    n: '-0.01628100',
    T: 0,
    wt: 'MARK_PRICE',
    ps: 'BOTH',
    rp: '0.00000000',
    z: '3.00000000'
  }
}
watchOrders:Realtime [
  {
    info: {
      s: 'DOT-USDT',
      c: '528n81-dpe3rTed50-a3d8165O2701',
      i: '1767767539943940096',
      S: 'BUY',
      o: 'MARKET',
      q: '3.00000000',
      p: '10.85436637',
      sp: '0.00000000',
      ap: '10.85400000',
      x: 'TRADE',
      X: 'FILLED',
      N: 'USDT',
      n: '-0.01628100',
      T: 0,
      wt: 'MARK_PRICE',
      ps: 'BOTH',
      rp: '0.00000000',
      z: '3.00000000'
    },
    id: '1767767539943940096',
    clientOrderId: '528n81-dpe3rTed50-a3d8165O2701',
    symbol: 'DOT/USDT:USDT',
    timestamp: undefined,
    datetime: undefined,
    lastTradeTimestamp: 0,
    lastUpdateTimestamp: undefined,
    type: 'market',
    timeInForce: 'IOC',
    postOnly: undefined,
    side: 'buy',
    price: 10.85436637,
    stopPrice: undefined,
    triggerPrice: undefined,
    stopLossPrice: undefined,
    takeProfitPrice: undefined,
    average: 10.854,
    cost: 3.2562,
    amount: 3,
    filled: 3,
    remaining: 0,
    status: 'closed',
    fee: { currency: 'USDT', cost: '0.016281' },
    trades: [],
    reduceOnly: undefined,
    fees: [ [Object] ]
  }
]
2024-03-13T04:20:00.242Z onMessage {
  code: 0,
  dataType: 'BCH-USDT@ticker',
  data: {
    e: '24hTicker',
    E: 1710303599947,
    s: 'BCH-USDT',
    p: '2.96',
    P: '0.68',
    c: '437.31',
    L: '0.10',
    h: '438.48',
    l: '408.90',
    v: '140803.84',
    q: '60394906.03',
    o: '434.35',
    O: 1710303598734,
    C: 1710303573739,
    A: '437.15',
    a: '3.11',
    B: '437.10',
    b: '7.55'
  }
}

```

**Comment by sc0Vu** [comment]
@nvrossett what does MYTH software do? Did you call `watchBalance` somewhere?

**Comment by nvrossett** [comment]
MYTH is the base structure of my application!!

I'm creating an object structure where I simply import functions into this object and it makes me gain levels of depth

When I have MYTH.EXCHANGE for example, my MYTH object has the EXCHANGE property that receives the require structure of which exchange I will use according to the selection I made in the database:

` MYTH.EXCHANGE = (MYTH.Enviroment === 'Backtest') ? require(`/CORE/exchanges/local/exchange`) : require(`${MYTH.CONFIG.exchangeData.integration}`)
`

Then I load the entire exchange structure I want dynamically into it and it is accessible through the object:

Then I connect to the exchange
`MYTH.EXCHANGE.setConfig(MYTH)`

```
setConfig: async (MYTH) => {

        let config = MYTH.CONFIG.operation.config
        let exchange = MYTH.CONFIG.exchangeData.ccxt_exchange

        EXCHANGE.CCXT = new ccxt[exchange]({
            apiKey: MYTH.CONFIG.api.apiKey,
            secret: MYTH.CONFIG.api.apiSecret,
            password: MYTH.CONFIG.api.apiPassword,
            enableRateLimit: config.rateLimit.enableRateLimit,
            rateLimit: config.rateLimit.rateLimit,
            options: { 'defaultType': config.market },
        })

        EXCHANGE.CCXT.verbose = false

        if (config.sandbox) { EXCHANGE.CCXT.set_sandbox_mode(config.sandbox) }

        // Define Padrões Internos para Quant Mythology
        MYTH.EXCHANGE.Pattern = require('./pattern.' + exchange)

        // Comunicação Ativa e Passiva
        MYTH.PassiveMode = require('./passiveMode/ccxt.passive')
        MYTH.ActiveMode = require('./activeMode/ccxt.active')

        // Inicia modo Passivo
        MYTH.PassiveMode.start(MYTH)

},
```

So when I do this:

```
         MYTH.PassiveMode = require('./passiveMode/ccxt.passive')
         MYTH.ActiveMode = require('./activeMode/ccxt.active')
```
  
In Passive Mode, everything will just capture data such as websocket and http requests
And Active Mode is all I'm going to do with requests to the exchange, which part of me


So, the entire connection is made once.

And the load.balance function simply listens to watchBalance or fetchBalance, depending on what I request in my bot's administrative panel:

If I'm going to use websocket or api, and what is the delay.

This way it is very customizable without having to change the code.

```
module.exports = async (MYTH) => {
     let allMarkets = MYTH.PassiveMode.allMarkets
     let allContracts = MYTH.PassiveMode.allContracts

     let throttling = (MYTH.CONFIG.operation.config.use.balances.delay) ? MYTH.CONFIG.operation.config.use.balances.delay : 'Realtime'
     let describe = (throttling >= 0) ? 'Throttling ' + throttling + 'ms' : 'Realtime'

     if (MYTH.CONFIG.operation.config.use.balances.type && MYTH.CONFIG.operation.config.use.balances.type.toLowerCase() === "ws") {

         if (MYTH.EXCHANGE.CCXT.has['watchBalance']) {

             while (true) {

                 try {

                     const balance = await MYTH.EXCHANGE.CCXT.watchBalance()
                     if (balance) {
                         MYTH.PassiveMode.TRIGGER.balances(balance, 'watchBalance:' + describe, MYTH)
                         if (throttling >= 0) { await MYTH.EXCHANGE.CCXT.sleep(throttling) }
                     }


                 } catch (error) {
                     console.log('Error in MYTH.PassiveMode.loadBalances - watchBalance()')
                     console.log('error')
                 }


             }


         }

     }

     if (MYTH.CONFIG.operation.config.use.balances.type && MYTH.CONFIG.operation.config.use.balances.type.toLowerCase() === "api") {

         if (MYTH.EXCHANGE.CCXT.has['fetchBalance']) {

             while (true) {

                 try {

                     const balance = await MYTH.EXCHANGE.CCXT.fetchBalance()
                     MYTH.PassiveMode.TRIGGER.balances(balance, 'fetchBalance:' + describe, MYTH)
                     if (throttling >= 0) { await MYTH.EXCHANGE.CCXT.sleep(throttling) }

                 } catch (error) {
                     console.log('Error in MYTH.PassiveMode.loadBalances - fetchBalance()')
                     console.log('error')
                 }

             }
         }


     }
}
```

And in the case of the function:
MYTH.PassiveMode.TRIGGER.balances(balance, 'watchBalance:' + describe, MYTH)

For example, it is simply a function for me to centralize the action of the common function, since the action of watchBalance and fetchBalance is the same, so I don't repeat code unnecessarily

```
         balances: async (balance, use, MYTH) => {

             const config = MYTH.CONFIG.operation.config

             MYTH.CORE.EXCHANGE = {
                 margin: {
                     total: balance.total[config.account.margin],
                     available: balance.free[config.account.margin],
                     locked: balance.used[config.account.margin]
                 },
                 leverage: {
                     type: config[config.market].marginMode,
                     hedge: config[config.market].hedgeMode,
                     value: config[config.market].leverage
                 }
             }

         },
```

So I don't disconnect the application at any time (until now)

I just receive the data.

**Comment by nvrossett** [comment]
Taking advantage, since I opened my structure with you, I'll separate it in another answer so as not to mix it up, but I'm working precisely on this point now, trying to disconnect and reconnect, I spent the whole day on this yesterday and I've already read the manual.

https://github.com/ccxt/ccxt/wiki/Manual#error-handling

But I still don't know how to deal with it:

After this correction that I sent to my local server, as I said, the application started to work perfectly

But after 30 minutes or more of being connected, I don't remember, BINGX simply starts returning this to me:

```
ExchangeNotAvailable: bingx PUT https://open-api.bingx.com/openApi/user/auth/userDataStream?listenKey=765581a1354ad7642abfe712c32b263ffdf119da3e4b114dca183f3f90efea11&timestamp=1710275038562&signature=15 6eed1c3e8c2289c47e84546dc5bab9c440bf7d881fbb6e1cf8de7ff4cb7590 404 Not Found
     at bingx.handleHttpStatusCode (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/base/Exchange.js:1088:19)
     at /home/nvieira/www/node_modules/ccxt/dist/cjs/src/base/Exchange.js:990:22
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async bingx.fetch2 (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3595:16)
     at async bingx.request (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3598:16)
     at async bingx.authenticate (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/pro/bingx.js:777:30)
     at async bingx.watchOrders (/home/nvieira/www/node_modules/ccxt/dist/cjs/src/pro/bingx.js:598:9)
     at async module.exports [as loadOrders] (/home/nvieira/www/CORE/exchanges/ccxt-pro/bingx/passiveMode/load.orders.js:16:36)
```

I'm trying to close the connection and open it again but I just don't know how to do that on CCXT

On my side I get to do one:
**await MYTH.EXCHANGE.CCXT.close()** // As I showed above, my connection is made through MYTH.EXCHANGE.CCXT

```
MYTH.EXCHANGE.CCXT = new ccxt[exchange]({
             apiKey: MYTH.CONFIG.api.apiKey,
             secret: MYTH.CONFIG.api.apiSecret,
             password: MYTH.CONFIG.api.apiPassword,
             enableRateLimit: config.rateLimit.enableRateLimit,
             rateLimit: config.rateLimit.rateLimit,
             options: { 'defaultType': config.market },
})
```

This closes the connection, so much so that it returns:
**NetworkError: connection closed by remote server, closing code 1006**

So I'm rebuilding my object:
MYTH.EXCHANGE.CCXT

For him to reconnect, it partly works but I don't like this solution, apart from the fact that any instability like this has rarely happened:

I force the disconnection for longer and it doesn't reconnect (I'll adjust this)

And in some cases it subscribes to the same channel twice, duplicating the websocket return

I stayed yesterday morning until dawn banging my head about it

As you recommend doing with CCXT in these moments of instability, because I can't resolve this, and I'm trying to find my way here, but I don't really like it.

It seems forced and heavy, I believe there are better ways to deal with it, but I really don't know how.

After many hours of this I sent it to the CCXT discord but I haven't had any response since yesterday afternoon
![Discord CCXT](https://github.com/ccxt/ccxt/assets/2110820/c8ec4d55-d73c-461f-b690-940f12acc468)

If you could give me an idea of how to get around this correctly I would be immensely grateful.

**Comment by nvrossett** [comment]
@sc0Vu 
Can you please just put this line in the project like I mentioned above?
`this.balance[type] ??= {}`

The system is saying that info is undefined

**TypeError: Cannot set properties of undefined(setting 'info')**

He's trying to create an 'info' property in the variable this.balance[type], but he doesn't even know that this.balance[type] is an object.

```
        const type = ('P' in a) ? 'swap' : 'spot';
        this.balance[type]['info'] = data;
        this.balance[type]['timestamp'] = timestamp;
        this.balance[type]['datetime'] = this.iso8601(timestamp);
```

I just downloaded the update here for Websocket Authentication that I reported and you adjusted it, and before I forget, thank you for your agility.

But I will need to make the change in my local lib again because it reported the error message again.

Thank you again

**Comment by toyolpit** [comment]
python also same that code ...


i get 



2025-04-07 15:16:56,212 - INFO - Websocket connected
2025-04-07 15:16:56,222 - INFO - WebSocket terhubung
2025-04-07 15:16:56,231 - INFO - Berlangganan ke: {"method": "SUBSCRIBE", "params": ["market/BNB-USDT"]}
2025-04-07 15:17:36,352 - ERROR - WebSocket Error: Connection to remote host was lost.
2025-04-07 15:17:36,364 - ERROR - Connection to remote host was lost. - goodbye
2025-04-07 15:17:36,383 - INFO - WebSocket ditutup dengan kode status: None, pesan: None
