### ISSUE TITLE
ccxt\pro\coinbaseinternational check-ws-php-syntax error 

### ISSUE THREAD

**Issue by DelAnt** [ccxt/ccxt#21774]
### Operating System

macos

ccxt % php --version
PHP 8.3.3 (cli) (built: Feb 13 2024 15:41:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.3, Copyright (c), by Zend Technologies

### Programming Languages

PHP

### CCXT Version

4.2.75

### Description

Checking PHP Syntax during compiling which seems to be related to `ccxt\pro\coinbaseinternational`

### Code

```
Checking PHP Syntax...
In case of failure, follow the rules: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md


> ccxt@4.2.75 check-ws-php-syntax
> php -f php/pro/test/custom/syntax.php

Checking PHP Syntax...
In case of failure, follow the rules: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

PHP Fatal error:  Uncaught ErrorException: Creation of dynamic property ccxt\pro\coinbaseinternational::$errors is deprecated in /Users/anton/code/ccxt/php/Exchange.php on line 1176 in /Users/anton/code/ccxt/php/pro/test/custom/syntax.php:8
Stack trace:
#0 /Users/anton/code/ccxt/php/Exchange.php(1176): on_error(8192, 'Creation of dyn...', '/Users/anton/co...', 1176)
#1 /Users/anton/code/ccxt/php/async/Exchange.php(70): ccxt\Exchange->__construct(Array)
#2 /Users/anton/code/ccxt/php/pro/test/custom/syntax.php(18): ccxt\async\Exchange->__construct(Array)
#3 {main}
  thrown in /Users/anton/code/ccxt/php/pro/test/custom/syntax.php on line 8

Fatal error: Uncaught ErrorException: Creation of dynamic property ccxt\pro\coinbaseinternational::$errors is deprecated in /Users/anton/code/ccxt/php/Exchange.php on line 1176 in /Users/anton/code/ccxt/php/pro/test/custom/syntax.php:8
Stack trace:
#0 /Users/anton/code/ccxt/php/Exchange.php(1176): on_error(8192, 'Creation of dyn...', '/Users/anton/co...', 1176)
#1 /Users/anton/code/ccxt/php/async/Exchange.php(70): ccxt\Exchange->__construct(Array)
#2 /Users/anton/code/ccxt/php/pro/test/custom/syntax.php(18): ccxt\async\Exchange->__construct(Array)
#3 {main}
  thrown in /Users/anton/code/ccxt/php/pro/test/custom/syntax.php on line 8

 *  The terminal process "/bin/zsh '-l', '-c', 'npm run build'" terminated with exit code: 255. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by sc0Vu** [comment]
@DelAnt thanks, will fix this asap.

**Comment by DelAnt** [comment]
Tested the change on my own local build and confirm it works. 
```diff --git a/ts/src/pro/coinbaseinternational.ts b/ts/src/pro/coinbaseinternational.ts
index 003dd52166..cc1f247495 100644
--- a/ts/src/pro/coinbaseinternational.ts
+++ b/ts/src/pro/coinbaseinternational.ts
@@ -53,7 +53,7 @@ export default class coinbaseinternational extends coinbaseinternationalRest {
                 'ordersLimit': 1000,
                 'myTradesLimit': 1000,
             },
-            'errors': {
+            'exceptions': {
                 'exact': {
                     'Unable to authenticate': AuthenticationError,
                 },
```

PHP syntax.
```ccxt % npm run check-php-syntax

> ccxt@4.2.75 check-php-syntax
> npm run check-rest-php-syntax && npm run check-ws-php-syntax


> ccxt@4.2.75 check-rest-php-syntax
> php -f php/test/custom/syntax.php

Checking PHP Syntax...
In case of failure, follow the rules: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md


> ccxt@4.2.75 check-ws-php-syntax
> php -f php/pro/test/custom/syntax.php

Checking PHP Syntax...
In case of failure, follow the rules: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md```
