### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by zacra** [ccxt/ccxt#21784]
### Operating System

Amazon Linux

### Programming Languages

Python

### CCXT Version

From ccxt version 4.2.59

### Description

Hi~ again..

Starting with ccxt version 4.2.59, the following error occurs. That lower version is fine.
Please give me feedback!!

[ec2-user@ip-172-31-37-161 ~]$ python3 /var/autobot/New_Binance_Alert.py
Traceback (most recent call last):
  File "/var/autobot/New_Binance_Alert.py", line 2, in <module>
    import ccxt
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 57, in <module>
    from ccxt.static_dependencies.ethereum import abi
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/static_dependencies/ethereum/__init__.py", line 1, in <module>
    from .abi import *
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/static_dependencies/ethereum/abi/__init__.py", line 2, in <module>
    from .abi import (
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/static_dependencies/ethereum/abi/abi.py", line 1, in <module>
    from .codec import (
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/static_dependencies/ethereum/abi/codec.py", line 8, in <module>
    from ..typing.abi import (
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/static_dependencies/ethereum/typing/__init__.py", line 1, in <module>
    from importlib.metadata import (
ModuleNotFoundError: No module named 'importlib.metadata'

So.. Try install importlib.metadata....

pip3 install importlib_metadata
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: importlib_metadata in ./.local/lib/python3.7/site-packages (6.7.0)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in ./.local/lib/python3.7/site-packages (from importlib_metadata) (4.4.0)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.7/site-packages (from importlib_metadata) (3.15.0)

python version is 3.7.16
I think I need to upgrade the Python version. Is there a solution if upgrading the Python version is not possible?

 pip3 install --user importlib_metadata

This installs importlib-metadata 6.7.0, but an error still occurs.

thanks :)

### Code

```
  

```

**Comment by samgermain** [comment]
Maybe you have different pythons installed? Can you try `python -m pip install importlib_metadata`

**Comment by birkschmithuesen** [comment]
I have the same problem. Although just typing `import importlib_metadata` works fine.

**Comment by BourneSuper** [comment]
importlib_metadata is already installed, but this error occurred.
```
>>> from importlib.metadata import ( version as __version, )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib.metadata'
>>> import importlib_metadata
```

**Comment by carlosmiei** [comment]
Hello @BourneSuper, what's the python version and OS used?

**Comment by BourneSuper** [comment]
> Hello @BourneSuper, what's the python version and OS used?

Python 3.7.9     windows 10



```
>>> from importlib.metadata import ( version as __version, )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib.metadata'
>>> import importlib_metadata
>>> from importlib_metadata import version as __version
```
`from importlib_metadata import version as __version` this one works, but other errors happens.

```
Traceback (most recent call last):
  File "tempDir\dataDownload.py", line 1, in <module>
    from copyt.exchange.BinanceExchange import BinanceExchange
  File "tempDir\copyt\exchange\BinanceExchange.py", line 4, in <module>
    import ccxt
  File "tempDir\.env\lib\site-packages\ccxt\__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "tempDir\.env\lib\site-packages\ccxt\base\__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "tempDir\.env\lib\site-packages\ccxt\base\exchange.py", line 58, in <module>
    from ccxt.static_dependencies.ethereum import abi
  File "tempDir\.env\lib\site-packages\ccxt\static_dependencies\ethereum\__init__.py", line 1, in <module>
    from .abi import *
  File "tempDir\.env\lib\site-packages\ccxt\static_dependencies\ethereum\abi\__init__.py", line 2, in <module>
    from .abi import (
  File "tempDir\.env\lib\site-packages\ccxt\static_dependencies\ethereum\abi\abi.py", line 1, in <module>
    from .codec import (
  File "tempDir\.env\lib\site-packages\ccxt\static_dependencies\ethereum\abi\codec.py", line 8, in <module>
    from ..typing.abi import (
  File "tempDir\.env\lib\site-packages\ccxt\static_dependencies\ethereum\typing\__init__.py", line 31, in <module>
    from .evm import (
  File "tempDir\.env\lib\site-packages\ccxt\static_dependencies\ethereum\typing\evm.py", line 1, in <module>
    from typing import (
ImportError: cannot import name 'Literal' from 'typing' (D:\Program Files\Python37\lib\typing.py)
```

**Comment by carlosmiei** [comment]
@BourneSuper Your python version is a bit outdated, is it possible to update it and try again?

**Comment by BourneSuper** [comment]
> @BourneSuper Your python version is a bit outdated, is it possible to update it and try again?

python 3.10.11 works. I used new virtual environment and newly installed CCXT.
It seems that python's version or packages cause this problem.

**Comment by carlosmiei** [comment]
@BourneSuper Yes seems related to the eth/abi dependencies, we will try to take a look.

**Comment by kroitor** [comment]
Hello @zacra, closing this during a cleanup — this was resolved at the packaging layer: ccxt now declares a minimum python version (`requires-python >= 3.10`, visible on PyPI), so pip on older interpreters resolves to the last compatible release instead of installing a build whose vendored dependencies need a newer stdlib, which is exactly what broke here on python 3.7. Python 3.7 itself reached end of life in mid-2023, so upgrading the interpreter is the path to current ccxt versions in any case.

If installation metadata misbehaves on a current setup, a fresh issue with the pip and python versions would be welcome. Thanks!
