### ISSUE TITLE
NullReferenceException during starting watching

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#21809]
### Operating System

Windows 10

### Programming Languages

C#

### CCXT Version

4.2.76

### Description

When I starting to watch multiple symbols, eg for trade, I got error:
```C#
System.NullReferenceException
 StackTrace:
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ccxt.Exchange.client(Object url2) in .\ccxt_source\cs\ccxt\ws\Exchange.WsBridge.cs:line 132
```
in line 
```C#
this.clients[url] = new WebSocketClient(url, proxy, handleMessage, ping, onClose, onError, this.verbose);
```

At this very moment there are two parallel threads attempting to insert new item in dictionary.

PS adding a lock helps solve this problem

### Code

Lib that contains the code below is targeted to **netstandard2.0**
```C#
public class Demo
{
    public void Run()
    {
        var symbols = new List<string>() { "BNB/BTC", "BTC/USDT", "ETH/BTC", "ETH/USDT", "LTC/BTC", "XRP/USDT" };
        var exchange = new ccxt.pro.binance();

        Task.Run(async () => await exchange.LoadMarkets()).Wait();

        foreach (var symbol in symbols)
        {
            var task1 = Task.Run(async () =>
            {
                while (true)
                {
                    try
                    {
                        var response = await exchange.WatchTrades(symbol, limit2: 1);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                        break;
                    }
                }
            });

            var task2 = Task.Run(async () =>
            {
                while (true)
                {
                    try
                    {
                        var response = await exchange.WatchTicker(symbol);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                        break;
                    }
                }
            });
        }
    }
}
```

when I run this lib under netframework4.8:
```C#
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ccxt.Exchange.client(Object url2)
   at ccxt.Exchange.<watchMultiple>d__1154.MoveNext()
```
when I run this lib under net6.0:
```C#
waiting
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at ccxt.pro.binance.stream(Object type, Object subscriptionHash, Object numSubscriptions)
   at ccxt.pro.binance.watchTicker(Object symbol, Object parameters)
   at ccxt.pro.binance.WatchTicker(String symbol, Dictionary`2 parameters)
   at DemoLib.Demo.<>c__DisplayClass0_1.<<Run>b__2>d.MoveNext() 
```

**Comment by carlosmiei** [comment]
Hello @skuvv, 
Thanks for letting us know, we will take a look. Your version is 4.76.0 ?

**Comment by skuvv** [comment]
Hello @carlosmiei 
My apologies, version is 4.2.76

**Comment by skuvv** [comment]
Simplified version for app without libs:

```
var symbols = new List<string>() { "AVAX/USDT", "BNB/BTC", "BNB/USDT", "BOME/USDT", "BTC/USDT", "DOGE/USDT", "ETH/BTC", "ETH/USDT", "LTC/BTC", "SOL/USDT", "XRP/USDT" };
var exchange = new ccxt.pro.binance();

Task.Run(async () => await exchange.LoadMarkets()).Wait();

if (exchange.symbols.Count == 0)
{
    throw new Exception("Symbols was not loaded");
}

foreach (var symbol in symbols)
{
    var task1 = Task.Run(async () =>
    {
        while (true)
        {
            try
            {
                var response = await exchange.WatchTrades(symbol, limit2: 1);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                break;
            }
        }
    });

    var task2 = Task.Run(async () =>
    {
        while (true)
        {
            try
            {
                var response = await exchange.WatchTicker(symbol);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                break;
            }
        }
    });
}


Console.WriteLine("waiting");
Console.ReadLine();
```

**Comment by carlosmiei** [comment]
@skuvv We just released a new version with a patch. Can you please update your ccxt version, try again, and let us know how that goes?

**Comment by skuvv** [comment]
Problem solved, tested on 4.2.79.
New errors are occured, relevant to this.

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at ccxt.pro.binance.stream(Object type, Object subscriptionHash, Object numSubscriptions)
   at ccxt.pro.binance.watchTicker(Object symbol, Object parameters)
   at ccxt.pro.binance.WatchTicker(String symbol, Dictionary`2 parameters)
```

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at ccxt.pro.binance.requestId(Object url)
   at ccxt.pro.binance.watchTicker(Object symbol, Object parameters)
   at ccxt.pro.binance.WatchTicker(String symbol, Dictionary`2 parameters)
```

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at ccxt.Exchange.SafeValueN(Object obj, Object keys2, Object defaultValue)
   at ccxt.Exchange.SafeStringN(Object obj, Object keys, Object defaultValue)
   at ccxt.pro.binance.stream(Object type, Object subscriptionHash, Object numSubscriptions)
   at ccxt.pro.binance.watchTradesForSymbols(Object symbols, Object since, Object limit, Object parameters)
   at ccxt.pro.binance.watchTrades(Object symbol, Object since, Object limit, Object parameters)
   at ccxt.pro.binance.WatchTrades(String symbol, Nullable`1 since2, Nullable`1 limit2, Dictionary`2 parameters)
```

**Comment by carlosmiei** [comment]
@skuvv What's the best way of reproducing the issue?

**Comment by carlosmiei** [comment]
@skuvv idon't think that's the correct link 😅

**Comment by skuvv** [comment]
link has strange behavior -)
https://github.com/ccxt/ccxt/issues/21809#issuecomment-2008053257

**Comment by carlosmiei** [comment]
@skuvv ahh got it, but after the latest fix I ran that snippet for a few minutes and did not get the crash, do you have to wait longer to reproduce it?

**Comment by skuvv** [comment]
> @skuvv ahh got it, but after the latest fix I ran that snippet for a few minutes and did not get the crash, do you have to wait longer to reproduce it?
Please try restart it several time. Not need to wait it for a long time - the problem occurs almost immediately.

**Comment by carlosmiei** [comment]
@skuvv Did that, even increased a lot the number of symbols but still can't reproduce. Can you create a small isolated project that I can compile and run just to make sure we're running the same thing under the same circumstances ?

**Comment by skuvv** [comment]
Sure, here is a demo project
[21089.zip](https://github.com/ccxt/ccxt/files/14724616/21089.zip)

**Comment by carlosmiei** [comment]
@skuvv after a lot of tries I managed to reproduced it
```
> dotnet run --project "./cs/cli/cli.csproj"

waiting
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at ccxt.Exchange.SafeValueN(Object obj, Object keys2, Object defaultValue) in /Users/cjg/Git/ccxt9/ccxt/cs/ccxt/base/Exchange.SafeMethods.cs:line 328
   at ccxt.Exchange.SafeIntegerN(Object obj, List`1 keys, Object defaultValue) in /Users/cjg/Git/ccxt9/ccxt/cs/ccxt/base/Exchange.SafeMethods.cs:line 202
   at ccxt.Exchange.SafeInteger(Object obj, Object key, Object defaultValue) in /Users/cjg/Git/ccxt9/ccxt/cs/ccxt/base/Exchange.SafeMethods.cs:line 81
   at ccxt.Exchange.safeInteger(Object obj, Object key, Object defaultValue) in /Users/cjg/Git/ccxt9/ccxt/cs/ccxt/base/Exchange.SafeMethods.cs:line 78
   at ccxt.pro.binance.stream(Object type, Object subscriptionHash, Object numSubscriptions) in /Users/cjg/Git/ccxt9/ccxt/cs/ccxt/exchanges/pro/binance.cs:line 152
   at ccxt.pro.binance.watchTradesForSymbols(Object symbols, Object since, Object limit, Object parameters) in /Users/cjg/Git/ccxt9/ccxt/cs/ccxt/exchanges/pro/binance.cs:line 573
   at ccxt.pro.binance.watchTrades(Object symbol, Object since, Object limit, Object parameters) in /Users/cjg/Git/ccxt9/ccxt/cs/ccxt/exchanges/pro/binance.cs:line 606
   at ccxt.pro.binance.WatchTrades(String symbol, Nullable`1 since2, Nullable`1 limit2, Dictionary`2 parameters) in /Users/cjg/Git/ccxt9/ccxt/cs/ccxt/exchanges/pro/wrappers/binance.cs:line 124
   at Example.Program.<>c__DisplayClass8_1.<<Concurrent>b__2>d.MoveNext() in /Users/cjg/Git/ccxt9/ccxt/cs/cli/Program.cs:line 224
```

I will analyze it, thanks for the detailed report

**Comment by carlosmiei** [comment]
@skuvv We just released a new version with the fix, can you please update to the latest version and try again?

Thank you for your patience and for helping us debug this issue 🙂

**Comment by skuvv** [comment]
@carlosmiei 
Tested on 4.2.80, all problem fixed.
Thanks.

**Comment by carlosmiei** [comment]
@skuvv Great, let us know if anything!
