### ISSUE TITLE
InvalidCastException C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#21812]
### Operating System

Windows 10

### CCXT Version

2.76.0

### Description

Error during WatchTrades for ccxt.pro.kraken

### Code

```
var exchange0 = new ccxt.pro.kraken();
await exchange0.LoadMarkets();
var response = await exchange0.WatchTrades("BTC/USDT", limit2: 1);
```

error:
```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.
  Source=ccxt
  StackTrace:
   at ccxt.Trade..ctor(Object trade2)
   at ccxt.pro.kraken.<>c.<WatchTrades>b__43_0(Object item)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at ccxt.pro.kraken.<WatchTrades>d__43.MoveNext()
```

**Comment by carlosmiei** [comment]
Hello again @skuvv, will take a look asap

**Comment by carlosmiei** [comment]
@skuvv If you update your ccxt version, this issue should be fixe
