### ISSUE TITLE
krakenfutures: watch_positions

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#21850]
Hi,

I had test the version 4.2.78.

Since the v4.2.77 I have an error with the watch_positions function of krakenfutures:
```
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   positions = await exchange_krakenfutres.watch_positions(['BTC/USD:USD'])
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "\venv\Lib\site-packages\ccxt\pro\krakenfutures.py", line 227, in watch_positions
    |     newPositions = await self.subscribe_private('open_positions', messageHash, params)
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "\venv\Lib\site-packages\ccxt\pro\krakenfutures.py", line 145, in subscribe_private
    |     'original_challenge': self.options['challenge'],
    |                           ~~~~~~~~~~~~^^^^^^^^^^^^^
    | KeyError: 'challenge'
```

I have an open position for this symbol. Work correctly with 4.2.76
Do you want any other informations?

Thanks

**Comment by sc0Vu** [comment]
@Hadevmin it works for me, could you paste verbose log or code we can reproduce?

**Comment by Hadevmin** [comment]
Hi @sc0Vu ,
It's in my code building. I need to call one time watch_positions before use asyncio task group.
Like that, the challenge for subscriptions work.

Sorry
