### ISSUE TITLE
"Illegal invocation" error and script exit on createOrderWs when trying to create a second order on Binance

### ISSUE THREAD

**Issue by gorcer** [ccxt/ccxt#21883]
### Operating System

PopOs (Ubuntu)

### Programming Languages

JavaScript

### CCXT Version

4.2.80

### Description

After the second order creation via createOrderWs on Binance  Testnet script exits with error:

```
TypeError: Illegal invocation
 at asyncResetHandle (node:_http_agent:550:47)
    at Agent.addRequest (node:_http_agent:280:5)
    at new ClientRequest (node:_http_client:337:16)
    at request (node:https:378:10)
    at initAsClient (/var/www/botnest/node_modules/ws/lib/websocket.js:867:28)
    at new WebSocket (/var/www/botnest/node_modules/ws/lib/websocket.js:85:7)
    
    
TypeError: Cannot read properties of undefined (reading 'readyState')
    at WsClient.isOpen (/var/www/botnest/node_modules/ccxt/dist/cjs/src/base/ws/WsClient.js:58:33)
    at WsClient.onConnectionTimeout (/var/www/botnest/node_modules/ccxt/dist/cjs/src/base/ws/Client.js:111:19)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
    
```

### Code

```
exchangeClass = ccxt['binance'];
    const api = new exchangeClass({
      apiKey,
      secret,
      password,
      options: { defaultType: 'spot' },
    });
    api.setSandboxMode(true);   
 api.verbose = true;    
  
  try {

    let order = await api.createOrderWs(
      symbol,
      type,
      side,
      api.amountToPrecision(symbol, amount),
      Number(api.priceToPrecision(symbol, price)),
    );
    
    } catch(e) {
     console.log('Trade error...wait 10 sec', e.message, e.stack);
await sleep(10);
    }
    
    
    
  try { 
// Illegal invocation and exit :((
    let order = await api.createOrderWs(
      symbol,
      type,
      side,
      api.amountToPrecision(symbol, amount),
      Number(api.priceToPrecision(symbol, price)),
    );
    
    } catch(e) {
     console.log('Trade error...wait 10 sec', e.message, e.stack);
     await sleep(10);
    }
    
```

1 order console output:

```

2024-03-24T10:14:39.685Z connecting to wss://testnet.binance.vision/ws-api/v3
2024-03-24T10:14:40.557Z onUpgrade
2024-03-24T10:14:40.559Z onOpen
2024-03-24T10:14:40.561Z sending {
  id: '1',
  method: 'order.place',
  params: {
    apiKey: 'lvnfUN0uTMWEJrqDf0JgnUYar0aD0B8h6COfnPSmekFLJiZNl8hns5cyyww0LWHO',
    newClientOrderId: 'x-R4BD3S8244502072246d4cd59f86e4',
    newOrderRespType: 'FULL',
    quoteOrderQty: '100',
    returnRateLimits: false,
    side: 'BUY',
    symbol: 'BTCUSDT',
    timestamp: 1711275279682,
    type: 'MARKET',
    signature: '0d4357e8ce88390626f368c6aec4d672cf13337eafc489a3e6221e9d624e51d7'
  }
}
2024-03-24T10:14:40.941Z onMessage {
  id: '1',
  status: 200,
  result: {
    symbol: 'BTCUSDT',
    orderId: 5172655,
    orderListId: -1,
    clientOrderId: 'x-R4BD3S8244502072246d4cd59f86e4',
    transactTime: 1711275280754,
    price: '0.00000000',
    origQty: '0.00154000',
    executedQty: '0.00154000',
    cummulativeQuoteQty: '99.98821140',
    status: 'FILLED',
    timeInForce: 'GTC',
    type: 'MARKET',
    side: 'BUY',
    workingTime: 1711275280754,
    fills: [ [Object] ],
    selfTradePreventionMode: 'EXPIRE_MAKER'
  }
}

```

2 order console output:

```

2024-03-24T10:14:51.006Z connecting to wss://testnet.binance.vision/ws-api/v3
e TypeError: Illegal invocation
    at asyncResetHandle (node:_http_agent:550:47)
    at Agent.addRequest (node:_http_agent:280:5)
    at new ClientRequest (node:_http_client:337:16)
    at request (node:https:378:10)
    at initAsClient (/var/www/botnest/node_modules/ws/lib/websocket.js:867:28)
    at new WebSocket (/var/www/botnest/node_modules/ws/lib/websocket.js:85:7)
    at WsClient.createConnection (/var/www/botnest/node_modules/ccxt/dist/cjs/src/base/ws/WsClient.js:26:31)
    at WsClient.connect (/var/www/botnest/node_modules/ccxt/dist/cjs/src/base/ws/WsClient.js:52:22)
    at binance.watch (/var/www/botnest/node_modules/ccxt/dist/cjs/src/base/Exchange.js:1302:34)
    at binance.createOrderWs (/var/www/botnest/node_modules/ccxt/dist/cjs/src/pro/binance.js:1702:27)
/var/www/botnest/node_modules/ccxt/dist/cjs/src/base/ws/WsClient.js:58
        return (this.connection.readyState === WebSocketPlatform.OPEN);
                                ^
TypeError: Cannot read properties of undefined (reading 'readyState')
    at WsClient.isOpen (/var/www/botnest/node_modules/ccxt/dist/cjs/src/base/ws/WsClient.js:58:33)
    at WsClient.onConnectionTimeout (/var/www/botnest/node_modules/ccxt/dist/cjs/src/base/ws/Client.js:111:19)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)

```

**Comment by gorcer** [comment]
After some experiments i found that the connection status doesn't matter.
Just make two createOrderWs request to Binance.
The first one is fine, the second one if fail with "Illegal invocation" and "Cannot read properties of undefined (reading 'readyState')"

**Comment by carlosmiei** [comment]
Hello @gorcer, I just ran this script locally and it worked as expected

```Javascript
    console.log('Will create first order:');
    const order1 = await exchange.createOrderWs('LTC/USDT',  'limit', 'buy', 0.25, 50);
    console.log('Order1 created:', order1['id']);
    await sleep(2000);
    console.log('Will create second order:');
    const order2 = await exchange.createOrderWs('LTC/USDT',  'limit', 'buy', 0.25, 50);
    console.log('Order2 created:', order2['id']);
    process.exit ()
```
 Can you please provide a small snippet that we can run locally to try to reproduce the aforementioned issue?

**Comment by gorcer** [comment]
It was my fall. I cached exchange object and it broke my object.
Thank you, Carlos, for your advise.

**Comment by gorcer** [comment]
there is no error

**Comment by carlosmiei** [comment]
@gorcer No problem, let us know if anything!
