### ISSUE TITLE
Bitget: WatchBalance error, C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#21960]
### Operating System

Windows 10

### CCXT Version

4.2.85

### Description

Error on WatchBalance for bitget

### Code

```
var exchange = new ccxt.pro.Bitget();
exchange.apiKey = "yourApiKey";
exchange.secret = "yourSecret";
exchange.password = "youPass";

await exchange.loadMarkets();

var response = await exchange.WatchBalance();

```
error:
```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'ccxt.pro.CustomConcurrentDictionary`2[System.String,System.Object]' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.
  Source=ccxt
  StackTrace:
   at ccxt.Exchange.omit(Object aa, Object k) in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\base\Exchange.Functions.cs:line 59
   at ccxt.Exchange.safeBalance(Object balance) in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\base\Exchange.BaseMethods.cs:line 1221
   at ccxt.pro.bitget.handleBalance(WebSocketClient client, Object message) in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\exchanges\pro\bitget.cs:line 1707

```

**Comment by carlosmiei** [comment]
Hello @skuvv, thanks once again for reporting it, will take a look

**Comment by carlosmiei** [comment]
@skuvv Can you update and try again please? I think it should be working now 🙂

**Comment by skuvv** [comment]
4.2.86 error is gone.
