### ISSUE TITLE
LoadMarkets problem for Bitget/Kraken C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22002]
### Operating System

Windows 10

### CCXT Version

4.2.87

### Description

Looks like some of exchange(Bitget and Kraken) are ban me - I don't receive a result when using LoadMarkets().

But It works with chrome browser and works after using VPN with ccxt.
Not sure that is a bug, but thing is crucial...

### Code

```
var bitget = new ccxt.pro.Bitget();
bitget.verbose = true;
bitget.apiKey = "xxx";
bitget.secret = "xxx";
bitget.password = "xxx";
var result = await bitget.authenticate();
await bitget.LoadMarkets();
```
output:
```
WebSocket connected to wss://ws.bitget.com/v2/ws/private
Sending message: {"op":"login","args":[{"apiKey":"xxx","passphrase":"xxx","timestamp":"1711887212","sign":"xxx"}]}
On message: {"event":"login","code":0}
fetch Request:
bitget GET https://api.bitget.com/api/v2/spot/public/coins
RequestHeaders:

RequestBody:


PingLoop: 2024-03-31T12:14:03.572Z
Sending message: ping
On message: pong
Sending message: ping
On message: pong
Sending message: ping
On message: pong
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ccxt.Exchange.LoadMarkets()
   at Program.<Main>$(String[] args) in D:\Dev\Z\CCXT\Demo\DemoFromNugetCCXT\Program.cs:line 14
   at Program.<Main>(String[] args)
```

output with VPN:
```
WebSocket connected to wss://ws.bitget.com/v2/ws/private
Sending message: {"op":"login","args":[{"apiKey":"xxx","passphrase":"xxx","timestamp":"1711887597","sign":"xxx"}]}
On message: {"event":"login","code":0}
fetch Request:
bitget GET https://api.bitget.com/api/v2/spot/public/coins
RequestHeaders:

RequestBody:


handleRestResponse:
bitget GET https://api.bitget.com/api/v2/spot/public/coins 200 OK
ResponseHeaders:

...
data next
```

**Comment by carlosmiei** [comment]
Hello @skuvv,

Maybe your location is restricted from the API standpoint? Have you tried to use an HTTP proxy with ccxt? By doing that, you don't need to have a VPN enabled as a whole, and only the ccxt requests are passed through the proxy.

**Comment by skuvv** [comment]
I have used these endpoints for about 3 weeks until this weekend's. 
Moreover authentication is working properly without VPN or proxy.

I think they can analyze the request header, because the endpoints work using web browser.
Perhaps adding headers can help.

**Comment by skuvv** [comment]
I think the problem not relevant to ccxt.
