### ISSUE TITLE
Exchange.Close does not close PingLoop. C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22003]
### Operating System

Windows 10

### CCXT Version

4.2.87

### Description

When I complete
```
Task.Run(async () => await _exchange.Close()).Wait()
```
then after some time based on following delay:
```
await Task.Delay(Convert.ToInt32(keepAlive));
```
I got unhandled error from ccxt.Exchange.WebSocketClient.PingLoop:
```
   at System.Net.WebSockets.WebSocket.ThrowOnInvalidState(WebSocketState state, WebSocketState[] validStates)
   at System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ccxt.Exchange.WebSocketClient.<sendAsyncWrapper>d__34.MoveNext() in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\ws\Client.cs:line 282
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ccxt.Exchange.WebSocketClient.<send>d__35.MoveNext() in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\ws\Client.cs:line 299
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ccxt.Exchange.WebSocketClient.<PingLoop>d__30.MoveNext() in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\ws\Client.cs:line 208

```

### Code

Please use following solution:

**Comment by skuvv** [comment]
[DemoForDebug.zip](https://github.com/ccxt/ccxt/files/14816492/DemoForDebug.zip)

**Comment by carlosmiei** [comment]
@skuvv We will take a look, thanks

**Comment by carlosmiei** [comment]
@skuvv Can you please check if the issue is gone now?

**Comment by skuvv** [comment]
Tested on 4.2.89. Fixed.
Thanks!
