### ISSUE TITLE
can't write to closing transport

### ISSUE THREAD

**Issue by nameOnStone** [ccxt/ccxt#22075]
### Operating System

ubuntu

### Programming Languages

Python

### CCXT Version

4.2.82

### Description

I don't know where is these code error from, not all Tasks will happen this raise error,  but some Tasks will be, So I don't know how to get example code

### Code

```python
  future: <Task finished name='Task-42162' coro=<AiohttpClient.ping_loop() done, defined at /home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/base/ws/aiohttp_client.py:104> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 123, in ping_loop
    await self.connection.ping()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/client_ws.py", line 157, in ping
    await self._writer.ping(message)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 715, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 675, in _send_frame
    self._write(header + mask + message)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 702, in _write
    raise ConnectionResetError("Cannot write to closing transport")
```

**Comment by sc0Vu** [comment]
@nameOnStone it looks like exchange had closed connection, and the client keep sending data to closed connection. How long the script been running? Is there any verbose log or script we can test?

**Comment by TristanThomas03** [comment]
Hello, similar error on my side. I'm on Windows 10 with ccxt 4.2.86. My code is based on [the binance-watch-ohlcv.py example](https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/binance-watch-ohlcv.py), modified in order to stream ADA/USDT on Bitget. The stream runs correctly until it encounters an error after a very variable time, ranging from 30 minutes to over 2 days.

Here is the full traceback :

```
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\VMWIN11\Desktop\bot_2024_v10\bot1\../framework\launch_stream.py", line 13, in _launch_stream
    ohlcv = await exchange.watch_ohlcv(self.asset, self.timeframe)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\pro\bitget.py", line 333, in watch_ohlcv
    ohlcv = await self.watch_public(messageHash, args, params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\pro\bitget.py", line 1491, in watch_public
    return await self.watch(url, messageHash, message, messageHash)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\async_support\base\ws\aiohttp_client.py", line 119, in ping_loop
    await self.send(self.ping(self))
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\async_support\base\ws\aiohttp_client.py", line 83, in send
    return await self.connection.send_str(message if isinstance(message, str) else json.dumps(message, separators=(',', ':')))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_ws.py", line 165, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\http_websocket.py", line 729, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\http_websocket.py", line 675, in _send_frame
    self._write(header + mask + message)
  File "C:\Users\VMWIN11\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\http_websocket.py", line 702, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by Mswwww** [comment]
I got same error. my useage:
```
    async def subscribe_orderbook(self):
        async def _subscribe_orderbook():
            while not self._shutdown:
                try:
                    ticker = await self.exchange.watch_ticker(self.symbol)
                    self.ask_price = ticker['ask']
                    self.bid_price = ticker['bid']
                    # logger.info(f'ticker=> {self.symbol}, {self.ask_price}, {self.bid_price}')
                except Exception as e:
                    logger.error(type(e).__name__, str(e))
                    continue

        task = self._loop.create_task(_subscribe_orderbook())
        self._loop_tasks.append(task)
```
my error log:
```
Traceback (most recent call last):
  File "/home/wangzhen/okx_test/./okx_twap.py", line 190, in _subscribe_orderbook
    ticker = await self.exchange.watch_ticker(self.symbol)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/ccxt/pro/okx.py", line 255, in watch_ticker
    ticker = await self.watch_tickers([symbol], params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/ccxt/pro/okx.py", line 271, in watch_tickers
    newTickers = await self.subscribe_multiple('public', channel, symbols, params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/ccxt/pro/okx.py", line 142, in subscribe_multiple
    return await self.watch(url, messageHash, request, messageHash)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 119, in ping_loop
    await self.send(self.ping(self))
  File "/usr/local/anaconda3/lib/python3.11/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 83, in send
    return await self.connection.send_str(message if isinstance(message, str) else json.dumps(message, separators=(',', ':')))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/site-packages/aiohttp/client_ws.py", line 151, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/anaconda3/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 690, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/anaconda3/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/anaconda3/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.11/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/logging/handlers.py", line 196, in shouldRollover
    msg = "%s\n" % self.format(record)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/wangzhen/okx_test/./okx_twap.py", line 638, in <module>
    asyncio.get_event_loop().run_until_complete(batch_execute_symbols())
  File "/usr/local/anaconda3/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/local/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/anaconda3/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/wangzhen/okx_test/./okx_twap.py", line 196, in _subscribe_orderbook
    logger.error(type(e).__name__, str(e))
Message: 'ConnectionResetError'
Arguments: ('Cannot write to closing transport',)
```

**Comment by Mswwww** [comment]
Is there an api for actively reopening the connection when “ConnectionResetError: Cannot write to closing transport” is caught？

**Comment by ShieldTrade** [comment]
I have the same problem with `bitmex.watch_book()`

**Comment by kroitor** [comment]
🙏 Thanks for the report and the clean traceback — and apologies this sat for over two years. It was real, and there were actually **two** defects behind it, both now fixed in https://github.com/ccxt/ccxt/pull/29735 (merged):

1. **Teardown ordering**: `close()` shut the transport down *before* cancelling the ping task, so a ping tick during the close could write into the closing transport — that's the `ConnectionResetError('Cannot write to closing transport')` escaping the `ping_loop` task as *"Task exception was never retrieved"* noise. The keepalive is now cancelled before the transport closes.
2. **Unguarded raw ping**: the aiohttp `connection.ping()` path had no guard (unlike the custom text-ping path right above it), so a server-initiated close or network drop mid-tick raised out of the task too. It's now guarded: a deliberate teardown exits silently, and a genuine transport death routes into the normal error path.

@Mswwww re *"is there an api for actively reopening the connection"* — you don't need one: after the error routes through, the next `watch_*` call redials automatically. Your loop as written is the right pattern.

@ShieldTrade — note bitmex in your case, but the fix is in the shared python ws base, so it applies to every exchange.

Upgrade to the next release (or install from master past `384e4ac`) and verify with:

```python
import asyncio
import ccxt.pro as ccxt

print('ccxt', ccxt.__version__)

async def main():
    exchange = ccxt.binance()
    await exchange.load_markets()
    # exchange.verbose = True  # uncomment for debugging
    for _ in range(50):
        ticker = await exchange.watch_ticker('BTC/USDT')
        print(ticker['bid'], ticker['ask'])
    await exchange.close()  # clean teardown - no transport noise anymore

asyncio.run(main())
```

If the noise resurfaces on the fixed version, drop a comment here and we'll reopen. 🙏
