### ISSUE TITLE
WatchOrderBook for Kraken does not return a result. C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22072]
### Operating System

Windows 10

### CCXT Version

4.2.89

### Description

Request for WatchOrderBook cause an error.

### Code

```
     var exchange = new ccxt.pro.Kraken();
     var result = await exchange.WatchOrderBook("XRP/USDT");
```
error:
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Value to add was out of range. Arg_ParamName_Name
  Source=System.Private.CoreLib
  StackTrace:
   at System.DateTime.<Add>g__ThrowOutOfRange|75_0()
   at System.DateTime.Add(Double value, Int32 scale)
   at System.DateTime.AddMilliseconds(Double value)
   at ccxt.Exchange.Iso8601(Object ts) in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\base\Exchange.Time.cs:line 76
   at ccxt.Exchange.iso8601(Object ts) in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\base\Exchange.Time.cs:line 83
   at ccxt.pro.kraken.handleOrderBook(WebSocketClient client, Object message, Object subscription) in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\exchanges\pro\kraken.cs:line 722
```

**Comment by sc0Vu** [comment]
@skuvv it works for me. Could you paste verbose log?

**Comment by skuvv** [comment]
@sc0Vu 
log:
```
WebSocket connected to wss://ws.kraken.com
Sending message: {"event":"subscribe","reqid":1,"pair":["XRP/USDT"],"subscription":{"name":"book"}}
On message: {"connectionID":17726087516760440743,"event":"systemStatus","status":"online","version":"1.9.2"}
On message: {"channelID":7536640,"channelName":"book-10","event":"subscriptionStatus","pair":"XRP/USDT","reqid":1,"status":"subscribed","subscription":{"depth":10,"name":"book"}}
On message: {"event":"heartbeat"}
On message: [7536640,{"as":[["0.59592000","421.87500000","1712478613.220183"],["0.59593000","9249.18788070","1712478611.616091"],["0.59597000","3314.61772082","1712478592.345259"],["0.59598000","800.00000000","1712478603.544696"],["0.59605000","421.87500000","1712478387.129278"],["0.59608000","3000.00000000","1712478523.233742"],["0.59612000","421.87500000","1712478579.561673"],["0.59614000","1582.65411094","1712478521.463620"],["0.59615000","8384.26503812","1712478522.094286"],["0.59619000","3011.74580865","1712478535.492546"]],"bs":[["0.59581000","8828.86804547","1712478606.419669"],["0.59579000","2262.93881569","1712478576.734225"],["0.59578000","8389.40557414","1712478546.465012"],["0.59575000","421.87500000","1712478600.979046"],["0.59569000","8390.61924213","1712478536.264092"],["0.59564000","1747.99966000","1712478536.260682"],["0.59563000","241.65839600","1712478573.964900"],["0.59561000","6011.74580865","1712478570.465642"],["0.59558000","421.87500000","1712478522.361567"],["0.59557000","524.51720792","1712478613.077290"]]},"book-10","XRP/USDT"]
```

![error](https://github.com/ccxt/ccxt/assets/39260996/f0c71eec-67f4-4c89-850a-611dd0fb4860)

**Comment by carlosmiei** [comment]
@skuvv Can you try with the latest version? I think it should be working now
