### ISSUE TITLE
Cannot download Binance Price Index of COIN-Margined Contracts 

### ISSUE THREAD

**Issue by AnthonyFJGarner** [ccxt/ccxt#22103]
### Operating System

Windows 11 

### Programming Languages

Python

### CCXT Version

4.2.89

### Description

The code will return mark prices but not index prices

### Code

```
import ccxt  # noqa: E402
exchange = ccxt.binancecoinm()
exchange.load_markets()

import time
if exchange.has['fetchOHLCV']:
    for symbol in exchange.markets:
        time.sleep (exchange.rateLimit / 1000) # time.sleep wants seconds
        print (symbol, exchange.fetch_ohlcv (symbol, '1d',params={'price':'index'})) # one day
```

```
Traceback (most recent call last):
  File "C:\Users\agarn\OneDrive\Documents\GitHub\ccxt\python\ccxt\base\exchange.py", line 629, in fetch
    response.raise_for_status()
  File "C:\Users\agarn\anaconda3\envs\ccxt\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://dapi.binance.com/dapi/v1/indexPriceKlines?interval=1d&limit=500&pair=BTCUSD_PERP

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\agarn\OneDrive\Documents\GitHub\ccxt\examples\my_exploration.py", line 30, in <module>
    print (symbol, exchange.fetch_ohlcv (symbol, '1d',params={'price':'index'})) # one day
  File "C:\Users\agarn\OneDrive\Documents\GitHub\ccxt\python\ccxt\binance.py", line 4139, in fetch_ohlcv
    response = self.dapiPublicGetIndexPriceKlines(self.extend(request, params))
  File "C:\Users\agarn\OneDrive\Documents\GitHub\ccxt\python\ccxt\base\types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "C:\Users\agarn\OneDrive\Documents\GitHub\ccxt\python\ccxt\binance.py", line 10279, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "C:\Users\agarn\OneDrive\Documents\GitHub\ccxt\python\ccxt\base\exchange.py", line 3616, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\agarn\OneDrive\Documents\GitHub\ccxt\python\ccxt\base\exchange.py", line 645, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\agarn\OneDrive\Documents\GitHub\ccxt\python\ccxt\binance.py", line 10246, in handle_errors
    self.throw_exactly_matched_exception(self.get_exceptions_by_url(url, 'exact'), error, feedback)
  File "C:\Users\agarn\OneDrive\Documents\GitHub\ccxt\python\ccxt\base\exchange.py", line 3986, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadSymbol: binancecoinm {"code":-4087,"msg":"Invalid pair."}

Process finished with exit code 1
```

**Comment by AnthonyFJGarner** [comment]
Also tried with 4.2.92

**Comment by carlosmiei** [comment]
@AnthonyFJGarner We just released a new version with the fix, can you please update your ccxt version and try again?

**Comment by AnthonyFJGarner** [comment]
I confirm it is now working. Many thanks, AG
