### ISSUE TITLE
Cannot connect to Binance

### ISSUE THREAD

**Issue by 190mc** [ccxt/ccxt#22115]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.2.93

### Description

I have trouble connecting to Binance. I have to use vpn(clash for  windows), which might be the issue. Any idea how to fix this?

### Code

```
import ccxt
exchange = ccxt.binance()
markets = exchange.load_markets()
print(markets)

```
Traceback (most recent call last):
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000017211ABA690>, 'Connection to api.binance.com timed out. (connect timeout=10.0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017211ABA690>, 'Connection to api.binance.com timed out. (connect timeout=10.0)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 603, in fetch
    response = self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017211ABA690>, 'Connection to api.binance.com timed out. (connect timeout=10.0)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\denmo\222.py", line 3, in <module>
    markets = exchange.load_markets()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 1516, in load_markets
    markets = self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\binance.py", line 2807, in fetch_markets
    promisesRaw.append(self.publicGetExchangeInfo(params))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\binance.py", line 10280, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 3643, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lz\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 633, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v3/exchangeInfo

**Comment by sc0Vu** [comment]
@190mc it looks like network issue, could you check your network?

**Comment by 190mc** [comment]
It's a VPN problem, I changed to a better VPN and solved it, thank you
