### ISSUE TITLE
coinbase exchange.load_markets is broken - unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by dakkusingh** [ccxt/ccxt#22158]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

CCXT Version: 4.2.98

### Description

```
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1516, in load_markets
    markets = self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ccxt/coinbase.py", line 1070, in fetch_markets
    return self.fetch_markets_v3(params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ccxt/coinbase.py", line 1197, in fetch_markets_v3
    result.append(self.parse_contract_market(futureData[i], expiringFeeTier))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ccxt/coinbase.py", line 1431, in parse_contract_market
    symbol = symbol + ':' + quote + '-' + self.yymmdd(contractExpire)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1200, in yymmdd
    return Exchange.ymd(timestamp, infix, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1195, in ymd
    utc_datetime = datetime.datetime.fromtimestamp(int(round(timestamp / 1000)), datetime.timezone.utc)
                                                             ~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

### Code

```
  

```

**Comment by dakkusingh** [comment]
also working fine in 4.2.95

**Comment by carlosmiei** [comment]
@dakkusingh Weird, but thanks a lot for reporting it, we will fix it asap

**Comment by GuillaumeDSM** [comment]
Also having the issue, thanks for the quick fix ! Looking forward to the next release :)

**Comment by carlosmiei** [comment]
@GuillaumeDSM @dakkusingh Thank you for your patience, can you please update your ccxt version and try again? I believe it should be working now

**Comment by albertwong08** [comment]
I also encounter similar error at the part when I try to fetch_balance: the code just breaks at the load_markets function, returns similar unsuppported operand types error as below:

Traceback (most recent call last):
  File "/Users/laichakwong/Documents/AWSdydxclient/dydxclient/app.py", line 330, in trade_cryptos_by_OI
    balance = exchange.fetch_balance()
  File "/Users/laichakwong/Documents/AWSdydxclient/venv/lib/python3.8/site-packages/ccxt/okx.py", line 2496, in fetch_balance
    self.load_markets()
  File "/Users/laichakwong/Documents/AWSdydxclient/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1502, in load_markets
    markets = self.fetch_markets(params)
  File "/Users/laichakwong/Documents/AWSdydxclient/venv/lib/python3.8/site-packages/ccxt/okx.py", line 1415, in fetch_markets
    promises.append(self.fetch_markets_by_type(types[i], params))
  File "/Users/laichakwong/Documents/AWSdydxclient/venv/lib/python3.8/site-packages/ccxt/okx.py", line 1615, in fetch_markets_by_type
    return self.parse_markets(dataResponse)
  File "/Users/laichakwong/Documents/AWSdydxclient/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2519, in parse_markets
    result.append(self.parse_market(markets[i]))
  File "/Users/laichakwong/Documents/AWSdydxclient/venv/lib/python3.8/site-packages/ccxt/okx.py", line 1491, in parse_market
    symbol = base + '/' + quote
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
