### ISSUE TITLE
exchange.fetchConvertTradeHistory - error when output has no longer traded tokens - on binance

### ISSUE THREAD

**Issue by egabosh** [ccxt/ccxt#22287]
### Operating System

Debian 12

### Programming Languages

Python

### CCXT Version

4.3.8

### Description

If there are tokens in the selected period that are no longer traded on Binance, I get the following error:
```
Traceback (most recent call last):
  File "/ccxt/examples/py/fetch-orders.py", line 57, in <module>
    print(exchange.fetchConvertTradeHistory(limit=200, since=1672527600000, params={'until': 1688248800000}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/binance.py", line 11886, in fetch_convert_trade_history
    return self.parse_conversions(rows, code, fromCurrencyKey, toCurrencyKey, since, limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 5698, in parse_conversions
    toCurrency = self.currency(toId)
                 ^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 4659, in currency
    raise ExchangeError(self.id + ' does not have currency code ' + code)
ccxt.base.errors.ExchangeError: binance does not have currency code TOMO
```

Here with verbose:
CCXT Version: 4.3.8

```
etch Request: binance GET https://api.binance.com/sapi/v1/convert/tradeFlow?timestamp=1714139039673&startTime=1685700951930&endTime=1685700951932&limit=200&recvWindow=10000&signature=bbc352b3d7a5bd012e5bc65b4ceaad676cfdb743ffd1c59211b7f4e89f149e86 RequestHeaders: {'X-MBX-APIKEY': 'VGN6q6EvYsLAuuEgzC1Ng64K88eFy40WxbpAuRJeqAuzEiA5tNqDz7dNa13Pa7kB', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: binance GET https://api.binance.com/sapi/v1/convert/tradeFlow?timestamp=1714139039673&startTime=1685700951930&endTime=1685700951932&limit=200&recvWindow=10000&signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 26 Apr 2024 13:43:59 GMT', 'Server': 'nginx', 'Vary': 'Accept-Encoding', 'X-SAPI-USED-UID-WEIGHT-1M': '3000', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 XXXXXXXXXXXXXXXXXXXXXXXXXXX.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': 'XXXXXXXXXXXXXXXXXXXXXXXXX'} ResponseBody: {"list":[{"quoteId":"XXXXXXXXXXXXXXX","orderId":1468577746614490518,"orderStatus":"SUCCESS","fromAsset":"USDT","fromAmount":"10.5","toAsset":"TOMO","toAmount":"7.66473859","ratio":"0.7299749618588082","inverseRatio":"1.3699100000000000","createTime":1685700951931,"orderType":"MARKET","side":"BUY"}],"startTime":1685700951930,"endTime":1685700951932,"limit":200,"moreData":false}
Traceback (most recent call last):
  File "/ccxt/examples/py/fetch-orders.py", line 62, in <module>
    print(exchange.fetchConvertTradeHistory(limit=200, since=1685700951930, params={'until': 1685700951932}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/binance.py", line 11886, in fetch_convert_trade_history
    return self.parse_conversions(rows, code, fromCurrencyKey, toCurrencyKey, since, limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 5698, in parse_conversions
    toCurrency = self.currency(toId)
                 ^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 4659, in currency
    raise ExchangeError(self.id + ' does not have currency code ' + code)
ccxt.base.errors.ExchangeError: binance does not have currency code TOMO
```
Is this a bug?

### Code

```
exchange.verbose = True
print('CCXT Version:', ccxt.__version__)
print(exchange.fetchConvertTradeHistory(limit=200, since=1672527600000, params={'until': 1688248800000}))

```

**Comment by sc0Vu** [comment]
@egabosh would you like to provide verbose log?

**Comment by carlosmiei** [comment]
@egabosh Thanks for letting us know, we will apply a patch asap

**Comment by egabosh** [comment]
@sc0Vu verbose log already posted.
@carlosmiei  great, thanks a lot"
