### ISSUE TITLE
BingX | edit_order, i need help

### ISSUE THREAD

**Issue by xerno0om** [ccxt/ccxt#22284]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

Last

### Description

I try to do edit_order to edit, change my Take Profit, but when I run the script it tells me that :

### Code

```
import ccxt

bingx_exchange = ccxt.bingx({
    'apiKey': '--',
    'secret': '--',
    'options': {
        'adjustForTimeDifference': True,
        'defaultType': 'swap',
    },
})

  order = bingx_exchange.edit_order(
    id='Yours', 
    symbol='BTC/USDT', 
    type='market', 
    side='sell', 
    amount='0.0200', 
    params={"takeProfit": {"triggerPrice": take_profit}}
)
print(order)

```

```

Traceback (most recent call last):
  File "c:\Users\gabri\OneDrive\Documents\za.py", line 14, in <module>
    trader = bingx_exchange.edit_order(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ccxt\bingx.py", line 4088, in edit_order
    response = self.spotV1PrivatePostTradeOrderCancelReplace(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ccxt\base\types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ccxt\base\exchange.py", line 3654, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ccxt\base\exchange.py", line 3651, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ccxt\base\exchange.py", line 673, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ccxt\bingx.py", line 4228, in handle_errors
    raise ExchangeError(feedback)  # unknown message
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ccxt.base.errors.ExchangeError: bingx {"code":100004,"msg":"Permission denied as the API key was created without the permission","timestamp":1714126674957}

```

**Comment by xerno0om** [comment]
@carlosmiei no, that's not exactly my problem, is that: I have already opened my position with my take profit, but my problem is that I want to move my take profit from this position a little higher, that's what I can't do it, what should I use? edit_order ?

**Comment by carlosmiei** [comment]
@xerno0om Oh ok the symbol confused me because `BTC/USDT` represents a spot market.

Well, in that case I'm not sure if it is possible to edit the sl/tp of a currently opened position (I'm not finding an API endpoint for that).

**Comment by carlosmiei** [comment]
We will ask bingx about it

**Comment by carlosmiei** [comment]
@xerno0om Bingx just confirmed that at the moment you can't edit it, you have to close + open a new position.

**Comment by masch** [comment]
@carlosmiei Hi! Do you know if Bingx can edit the order now?

**Comment by carlosmiei** [comment]
@masch Using `editOrder` you can edit regular spot/swap orders.

**Comment by masch** [comment]
I need to create and edit a future order. Is it possible do it?
I create it using BingX API, but then I can't edit it.

**Comment by carlosmiei** [comment]
@masch yes it should work

**Comment by masch** [comment]
@carlosmiei I tried to edit an order and I get the following error: 

 {"code":109500,"msg":"order is already filled, The order doesn't exist","data":{}} 

    const created_order = await exchange.createOrder(
      "BTC-USDT",
      "market",
      "buy",
      1,
      undefined,
      {
          "positionSide": "LONG"
      }
    );

    const edited_order = await exchange.editOrder(
      created_order.id,
      "BTC-USDT",
      "market",
      "buy",
      amount * 0.3,
      undefined
    );

What am I doing wrong?
Thank you

**Comment by carlosmiei** [comment]
@masch Looking at the error, it seems you're trying to edit an order that is not open anymore, so you can't edit it
