### ISSUE TITLE
[zaif] int is divided by str error at custom_nonce function

### ISSUE THREAD

**Issue by y-clps** [ccxt/ccxt#22388]
### Programming Languages

Python

### CCXT Version

4.3.15

### Description

Dear all,

I encountered a bug as below.
When creating a custom nonce, int is divided by str, so an error occurs.
I wonder if any other exchange using custom nonce has the same bug.
I would like to see the bug fixed and an investigation into its impact on other exchanges.

### Code

```
>>> zaif.privatePostActiveOrders({'is_token_both' : True})

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.pyenv/versions/3.10.9/lib/python3.10/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/ec2-user/.pyenv/versions/3.10.9/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3661, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/ec2-user/.pyenv/versions/3.10.9/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3654, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/home/ec2-user/.pyenv/versions/3.10.9/lib/python3.10/site-packages/ccxt/zaif.py", line 670, in sign
    nonce = self.custom_nonce()
  File "/home/ec2-user/.pyenv/versions/3.10.9/lib/python3.10/site-packages/ccxt/zaif.py", line 652, in custom_nonce
    num = (self.milliseconds() / str(1000))
TypeError: unsupported operand type(s) for /: 'int' and 'str'

```

**Comment by sc0Vu** [comment]
@y-clps it seems to be the issue when transpile code to python. We'll fix this asap.

**Comment by carlosmiei** [comment]
@y-clps Can you please update to the latest version and try again? It should be working

**Comment by y-clps** [comment]
@carlosmiei @sc0Vu
I have checked it is now working well, thank you for the quick fixing.
