### ISSUE TITLE
[Hyperliquid] cannot load_markets in sandbox mode

### ISSUE THREAD

**Issue by ChizhikovAlexey** [ccxt/ccxt#22390]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.15

### Description

I am working with `import ccxt.async_support.hyperliquid` in sandbox mode.

Code
```Python
exchange = ccxt.hyperliquid({
        'privateKey': '***',
        'walletAddress': '***'
    })
    exchange.set_sandbox_mode(enabled=True)
    markets = await exchange.load_markets()
```
causes error
```
Traceback (most recent call last):
  File "C:\Users\chizh\PycharmProjects\ExecutionLayer\main.py", line 52, in <module>
    run(main())
  File "C:\Users\chizh\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\chizh\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chizh\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\chizh\PycharmProjects\ExecutionLayer\main.py", line 16, in main
    markets = await exchange.load_markets()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chizh\PycharmProjects\ExecutionLayer\.venv\Lib\site-packages\ccxt\async_support\base\exchange.py", line 276, in load_markets
    raise e
  File "C:\Users\chizh\PycharmProjects\ExecutionLayer\.venv\Lib\site-packages\ccxt\async_support\base\exchange.py", line 272, in load_markets
    result = await self.markets_loading
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chizh\PycharmProjects\ExecutionLayer\.venv\Lib\site-packages\ccxt\async_support\base\exchange.py", line 262, in load_markets_helper
    markets = await self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chizh\PycharmProjects\ExecutionLayer\.venv\Lib\site-packages\ccxt\async_support\hyperliquid.py", line 273, in fetch_markets
    promises = await asyncio.gather(*rawPromises)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chizh\PycharmProjects\ExecutionLayer\.venv\Lib\site-packages\ccxt\async_support\hyperliquid.py", line 451, in fetch_spot_markets
    symbol = base + '/' + quote
             ~~~~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```
It can be fixed by editing source file hyperliquid.py
```Pyhton
async def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for hyperliquid
        :see: https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint#retrieve-asset-contexts-includes-mark-price-current-funding-open-interest-etc
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        rawPromises = [
            self.fetch_swap_markets(params),
            # self.fetch_spot_markets(params),
        ]
        promises = await asyncio.gather(*rawPromises)
        swapMarkets = promises[0]
        # spotMarkets = promises[1]
        return swapMarkets
```
(I've commented code that fethces spot markets and it works fine).

**Comment by sc0Vu** [comment]
@ChizhikovAlexey there is a weird spot market (name: `@1`) in the test spot market, it breaks code. We'll fix this asap.

**Comment by carlosmiei** [comment]
@ChizhikovAlexey Can you please update to the latest version and try again? It should be working
