### ISSUE TITLE
Coinegg: TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by wangjun92** [ccxt/ccxt#2239]
- OS:windows
- Programming Language version:python3.6
- CCXT version:1.11.77
- Exchange: Coinegg
- Method: fetchBalance() 

    coinegg = ccxt.coinegg({
        'apiKey': 'uzky3-2c1hj-4ru5r--------',
        'secret': '3HV44-mc]8p-H*VX)-X5Fri-}rLS%-----',               
            })
    coinegg.fetchBalance()   

TypeError: Unicode-objects must be encoded before hashing.

**Comment by kroitor** [comment]
Can you please post your verbose output according to these instructions: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

```Python
coinegg = ccxt.coinegg({
    'apiKey': 'uzky3-2c1hj-4ru5r--------',
    'secret': '3HV44-mc]8p-H*VX)-X5Fri-}rLS%-----',
    'verbose': True,
})
coinegg.fetchBalance()
```

Also, is it a new key?

**Comment by wangjun92** [comment]
@kroitor the key is applied about 5 hours before. It is new enouth.

**Comment by kroitor** [comment]
@wangjun92 I mean, have you used it with any different software or script before ccxt? Also, what about your verbose output?

**Comment by wangjun92** [comment]
@kroitor The key is not used before ccxt. And the verbose output like the folling: 

`Traceback (most recent call last):

  File "<ipython-input-95-4c16b4d75567>", line 6, in <module>
    coinegg.fetchBalance()

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\coinegg.py", line 301, in fetch_balance
    balances = self.privateGetBalance(params)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 292, in request
    return self.fetch2(path, api, method, params, headers, body)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 288, in fetch2
    request = self.sign(path, api, method, params, headers, body)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\coinegg.py", line 442, in sign
    secret = self.hash(self.secret)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 703, in hash
    h = hashlib.new(algorithm, request)

  File "C:\ProgramData\Anaconda3\lib\hashlib.py", line 149, in __hash_new
    return _hashlib.new(name, data)

TypeError: Unicode-objects must be encoded before hashing`
