### ISSUE TITLE
Bybit: cancelOrderWs results in permission denied

### ISSUE THREAD

**Issue by mjwvb** [ccxt/ccxt#22411]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

4.3.17

### Description

I'm getting the following error when cancelling orders using cancelOrderWs() on Bybit:
PermissionDenied: bybit {"retCode":10005,"retMsg":"Permission denied for current apikey","op":"auth","connId":"..."}

My api key has all permissions turned on. I even recreated the API key but to no avail. The normal cancelOrder() function still works. Is it an issue in how the request is made under the hood? Do I need to do something extra?

### Code

```typescript
exchange.cancelOrderWs(id, symbolName);
```

**Comment by pcriadoperez** [comment]
In the sandbox it does work for me correctly. I'll ask if someone in the team has production keys to test too.

**Comment by carlosmiei** [comment]
@mjwvb @pcriadoperez Yeah I can confirm this issue
```
 p bybit cancelOrderWs "77a249a9-6b2d-4ba6-8c73-2ea6c60997e3" "ADA/USDT:USDT"                          
Python v3.11.7
CCXT v4.3.17
bybit.cancelOrderWs(77a249a9-6b2d-4ba6-8c73-2ea6c60997e3,ADA/USDT:USDT)
Traceback (most recent call last):
  File "/Users/cjg/Git/ccxt9/ccxt/examples/py/cli.py", line 249, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/cjg/Git/ccxt9/ccxt/examples/py/cli.py", line 228, in main
    result = await result
             ^^^^^^^^^^^^
  File "/Users/cjg/Git/ccxt9/ccxt/python/ccxt/pro/bybit.py", line 282, in cancel_order_ws
    await self.authenticate(url)
  File "/Users/cjg/Git/ccxt9/ccxt/python/ccxt/pro/bybit.py", line 1723, in authenticate
    return await future
           ^^^^^^^^^^^^
  File "/Users/cjg/Git/ccxt9/ccxt/python/ccxt/pro/bybit.py", line 1773, in handle_error_message
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
  File "/Users/cjg/Git/ccxt9/ccxt/python/ccxt/base/exchange.py", line 4055, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.PermissionDenied: bybit {"retCode":10005,"retMsg":"Permission denied for current apikey","op":"auth","connId":"coqpl6ec0hv1u7f66lm0-3e7"}
```

@mjwvb Thanks for reporting it, we will take a look and revert asap.

**Comment by carlosmiei** [comment]
@mjwvb Can you please update your ccxt version and try again? I believe it should be working now.

**Comment by mjwvb** [comment]
I can confirm it works now. Thanks!
