### ISSUE TITLE
ccxt indodax fetch tickers error type

### ISSUE THREAD

**Issue by dtkid8** [ccxt/ccxt#22427]
### Operating System

windows

### CCXT Version

4.3.18

### Description

 at indodax.parseTickers (C:\Users\User\Desktop\project\node_modules\ccxt\dist\cjs\src\base\Exchange.js:5275:38)
    at indodax.fetchTickers (C:\Users\User\Desktop\projecte\node_modules\ccxt\dist\cjs\src\indodax.js:514:21)

### Code

```
      const currentExchange = new (ccxt as any)[exchangeId]({
        apiKey: apiKey as string,
        secret: secret as string
    });
    
       const mapTickers = await currentExchange.fetchTickers();

```

**Comment by sc0Vu** [comment]
@dtkid8 thanks, we'll fix this asap.
