### ISSUE TITLE
Error in `gdax.fetch_closed_orders`

### ISSUE THREAD

**Issue by ws2367** [ccxt/ccxt#2248]
I have encountered a problem in fetching closed orders from GDAX. See below for error message. This error did not happen for fetching closed orders from Binance. 

```
gdax.fetch_closed_orders('BTC/USD')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wenshaw/miniconda2/envs/ccxt/lib/python3.6/site-packages/ccxt/gdax.py", line 398, in fetch_closed_orders
    return self.parse_orders(response, market, since, limit)
  File "/Users/wenshaw/miniconda2/envs/ccxt/lib/python3.6/site-packages/ccxt/base/exchange.py", line 954, in parse_orders
    array = [self.parse_order(order, market) for order in array]
  File "/Users/wenshaw/miniconda2/envs/ccxt/lib/python3.6/site-packages/ccxt/base/exchange.py", line 954, in <listcomp>
    array = [self.parse_order(order, market) for order in array]
  File "/Users/wenshaw/miniconda2/envs/ccxt/lib/python3.6/site-packages/ccxt/gdax.py", line 338, in parse_order
    remaining = amount - filled
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

It looks like _market_ orders returned from gdax has no key `size`. However limit orders do have key `size`. 

OS:
OSX 10.13.3

Programming Language version:
Python 3.6.4

CCXT version:
1.10.760

Exchange:
binance
gdax

Method:
`fetch_closed_orders`

**Comment by kroitor** [comment]
Your version of ccxt is too old... This issue has been fixed already a few weeks ago. Please, update to the most recent version of ccxt and let us know if you still have difficulties with it. Hope it helps. Thx!
