### ISSUE TITLE
filter errors

### ISSUE THREAD

**Issue by wannesdemaeght** [ccxt/ccxt#2253]
How can I filter if an error is a timeout?

I log all errors to file, but would like to exclude request timeouts.

**Comment by kroitor** [comment]
@wannesdemaeght can you show a minimal snippet of your logging code?

**Comment by wannesdemaeght** [comment]
```
module.exports = async function (file, error, params = {}){
	let line		= "";
	let info		= (params.info) ? params.info : "";
	if (error){
		line		= error.stack.slice(error.stack.indexOf(file));
		line		= line.slice(0, line.indexOf(")"));
		line		= line.slice(line.indexOf(".js:") + 4);
	};
	
	file			= file.slice(file.indexOf("Logic\\")+6, file.indexOf(".js"));
	file			= file.replace("_", " ");
		
	let summary 	= {
		time:		FullDate(),
		file:		file,
		info:		info,
		line:		line,
		message:	(error) ? StandardError(error.message) : "",
		error:		(error) ? RemoveAPI(error.stack) : "",
	};
	
	for (let i in params){
		summary[i]		= params[i]
	};
	if (params.data) 	summary.data = JSON.stringify(params.data);
	
	let array 			= JSON.parse(await readFile("./Logic/Output/Errors.json"));
	array.unshift(summary);

	lock.writeLock(function(releaseLock) {
		fs.writeFile("./Logic/Output/Errors.json", JSON.stringify(array, null, "\t"), "utf-8", function(err) {
			releaseLock();
		});
	});
}
```

**Comment by wannesdemaeght** [comment]
basically giving me an output like this:

```
	{
		"time": "2018/03/13 - 23:10:47",
		"file": "Balance",
		"info": "Balance Call",
		"line": "",
		"message": "kraken timed out (4500 ms)",
		"error": "Error: kraken POST https://api.kraken.com/0/private/Balance request timed out (4500 ms)\n    at timeout.catch.e (C:\\Trader\\Logic\\node_modules\\ccxt\\js\\base\\Exchange.js:291:27)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
	},
```

**Comment by kroitor** [comment]
@wannesdemaeght in general you need to filter exceptions this way:

```JavaScript
try {
    const result = await exchange.fetchTicker ('ETH/BTC') // for example, let's say it throws a timeout error
} catch (e) {
    if (e instanceof ccxt.RequestTimeout) {
        // ignore it, filter it, or do whatever you want with it
    } else {
        // log it like you do
    }
}
```

Does this answer your question?

**Comment by wannesdemaeght** [comment]
Great, thanks!
