### ISSUE TITLE
Coinbase - removed symbols cause glitch with orders

### ISSUE THREAD

**Issue by thomasbs17** [ccxt/ccxt#22550]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

2.4.0

### Description

It looks like the 'fetch_orders' triggers an error when trying to retrieve orders that have been removed from Coinbase.

### Code

```
import ccxt

from utils.helpers import get_api_keys

test = ccxt.coinbase(dict(apiKey=key, secret=secret)

t = test.fetch_orders(limit=1000)
```

Full error log 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\Thomas Bouamoud\Code\crypto_station_front_end\venv\Lib\site-packages\ccxt\coinbase.py", line 2823, in fetch_orders
    return self.parse_orders(orders, market, since, limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Thomas Bouamoud\Code\crypto_station_front_end\venv\Lib\site-packages\ccxt\base\exchange.py", line 2847, in parse_orders
    order = self.extend(self.parse_order(orders[i], market), params)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Thomas Bouamoud\Code\crypto_station_front_end\venv\Lib\site-packages\ccxt\coinbase.py", line 2497, in parse_order
    market = self.market(symbol)
             ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Thomas Bouamoud\Code\crypto_station_front_end\venv\Lib\site-packages\ccxt\base\exchange.py", line 4456, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: coinbase does not have market symbol NMR/GBP
```

**Comment by carlosmiei** [comment]
@thomasbs17 Can you please update your ccxt version and try again? It should be working now

**Comment by thomasbs17** [comment]
Working like a charm now, thanks for the fix and the reactivity!

**Comment by carlosmiei** [comment]
@thomasbs17 No problem, let us know if anything! 🙂
