### ISSUE TITLE
Add Upbit private websocket connection

### ISSUE THREAD

**Issue by WillPCowan** [ccxt/ccxt#22696]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

Upbit for ccxt pro can only subscribe to public websocket channels. It now has useful private data channels. Would be great if we can authenticate and subscribe to those.

**Comment by sc0Vu** [comment]
Looks like they had myTrades topic (https://global-docs.upbit.com/v1.1.0/reference/websocket-mytrade). We'll support asap.

**Comment by WillPCowan** [comment]
Thanks man. Check out [this version 1.1.3](https://global-docs.upbit.com/reference/overall-account-inquiry) of the docs instead though and use the `myOrder` subscription in place of `myTrade` (`myAsset` also there now separately). 

Be aware that the WebSocket URI they tell you to use is incorrect (the pattern `wss://{sg|id|th}-api.upbit.com/websocket/v1/private` is wrong, just use `wss://api.upbit.com/websocket/v1/private`). If you were to use 1.1.0 and `myTrade` the correct URI is `wss://api.upbit.com/websocket/v1` (but this will be deprecated).

**Comment by sc0Vu** [comment]
@WillPCowan I think the region is required for private stream, try wss://api.upbit.com/websocket/v1/private but got 401 today. The PR was merged, you could use this feature in the latest version. Let us know if you find any issue.

**Comment by WillPCowan** [comment]
That's strange, I have the opposite experience and Upbit connector using `wss://api.upbit.com/websocket/v1/private` is in production now. Will check this out ASAP.

**Comment by WillPCowan** [comment]
@sc0Vu It seems the authentication does not work when I switch to the CCXT update (4.3.41). Confident this is to do with the URL notes.

```
2024-06-06 15:13:04,536 ERRO [lib.integrations.upbit.private_data_streamer] - Error in stream_private_data
Traceback (most recent call last):
  File "/home/ubuntu/project/lib/integrations/upbit/private_data_streamer.py", line 21, in run
    private_trades = await self.exchange_account_client.watch_my_trades(symbol=self.instrument_id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/project/.venv/lib/python3.11/site-packages/ccxt/pro/upbit.py", line 297, in watch_my_trades
    trades = await self.watch_private(symbol, channel, messageHash)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/project/.venv/lib/python3.11/site-packages/ccxt/pro/upbit.py", line 242, in watch_private
    await self.authenticate()
  File "/home/ubuntu/project/.venv/lib/python3.11/site-packages/ccxt/pro/upbit.py", line 226, in authenticate
    authenticated = self.options['ws']['token']
                    ~~~~~~~~~~~~^^^^^^
KeyError: 'ws'
```

```
2024-06-06 15:13:12,119 ERRO [lib.integrations.base.request_processor] - Cancel all request failed. Unkown error. CancelAllOrdersRequ
est(account_id='upbit', instrument_id='ETH/KRW', timestamp_ns=1717686790770549134)
Traceback (most recent call last):
  File "/home/ubuntu/project/app/mm/__main__.py", line 595, in run_app
    await asyncio.gather(*tasks)
  File "/home/ubuntu/project/app/mm/modular_market_maker.py", line 341, in run
    await asyncio.sleep(0.01)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 644, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/project/lib/integrations/base/request_processor.py", line 263, in process_cancel_all_orders_request
    order_results: List[Dict[str, Any]] = await self.exchange_account_client.cancel_all_orders(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/project/lib/integrations/upbit/exchange_account_client.py", line 320, in cancel_all_orders
    orders = await self.fetch_open_orders(symbol)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/project/.venv/lib/python3.11/site-packages/ccxt/async_support/upbit.py", line 1518, in fetch_open_orders
    return await self.fetch_orders_by_state('wait', symbol, since, limit, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/project/.venv/lib/python3.11/site-packages/ccxt/async_support/upbit.py", line 1484, in fetch_orders_by_state
    response = await self.privateGetOrders(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/project/.venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 832, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/project/.venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 829, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/project/.venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, reque
st_body)
  File "/home/ubuntu/project/.venv/lib/python3.11/site-packages/ccxt/async_support/upbit.py", line 1832, in handle_errors
    raise ExchangeError(feedback)  # unknown message
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ccxt.base.errors.ExchangeError: upbit {"error":{"message":"Failed to verify the query of Jwt.","name":"invalid_query_payload"}}
```

This is the exact `authenticate` implementation that is running for me in production now, using the URL `wss://api.upbit.com/websocket/v1/private`.

```python
    def authenticate(self, params={}):
        self.check_required_credentials()
        url = self.urls['api']['ws'] + '/private'
        
        # If the client is already authenticated, return early
        if (self.clients is not None) and (url in self.clients):
            return

        payload = {
            'access_key': self.apiKey,
            'nonce': str(uuid.uuid4()),
        }

        jwt_token = self.jwt(request=payload, secret=self.encode(self.secret), algorithm='sha256')
        authorization_token = f'Bearer {jwt_token}'

        defaultOptions = {
            'ws': {
                'options': {
                    'headers': {},
                },
            },
        }
        self.extend_exchange_options(defaultOptions)
        originalHeaders = self.options['ws']['options']['headers']
        
        headers = {
            'Authorization': authorization_token
        }

        self.options['ws']['options']['headers'] = headers
        self.client(url)
        self.options['ws']['options']['headers'] = originalHeaders
```

**Comment by WillPCowan** [comment]
Looking at those logs and investigating more, I don't think the URL is the issue and looks like the right URL is being used. I think `self.options` is getting overwritten somewhere, this is what it is before trying to authenticate:
`{'defaultNetworkCodeReplacements': {'ETH': {'ERC20': 'ETH'}, 'TRX': {'TRC20': 'TRX'}, 'CRO': {'
CRC20': 'CRONOS'}}, 'createMarketBuyOrderRequiresPrice': True, 'fetchTickersMaxLength': 4096, 'fetchOrderBooksMaxLength': 4096, 'tradingFeesByQuoteCurrency': {'KRW': 0.0005}, 'tradesLimit': 1000, 'networksById': {}}`

**Comment by sc0Vu** [comment]
@WillPCowan sorry for your inconvenience, we didn't set the default value of ws options. 

Before we fix this would you like to add these options when initialize exchange:
```py
    'options': {
                # default ws options for private stream
                'ws': {
                    'options': {},
                },
    },
```
