### ISSUE TITLE
C# Bitfinex2: System.InvalidCastException : Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'

### ISSUE THREAD

**Issue by wolfgang-s** [ccxt/ccxt#22726]
### Operating System

OSX

### CCXT Version

4.3.40 / master branch

### Description

Using C# and Bitfinex2, I cannot execute the following endpoint without this error:
```
System.InvalidCastException : Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.
  Stack Trace:
     at ccxt.Ticker..ctor(Object ticker2) in /Users/wolfgangsteuer/Documents/dotnet/ccxt/cs/ccxt/base/Exchange.Types.cs:line 329
   at ccxt.Exchange.FetchTicker(String symbol, Dictionary`2 parameters) in /Users/wolfgangsteuer/Documents/dotnet/ccxt/cs/ccxt/base/Exchange.Wrappers.cs:line 503
```

ccxt.Exchange.FetchTicker

My **Workaround** for now is to change: Exchange.Types.cs:line 329
```
info = ticker.ContainsKey("info") ? (Dictionary<string, object>)ticker["info"] : null;
```
to
```
info = ticker.ContainsKey("info") && ticker["info"] is Dictionary<string, object> ? (Dictionary<string, object>)ticker["info"] : null;
```
But this of course does not fill the property "info" anymore.

There are more errors to come, but I will create separate issues for all of them.

Verbose output of the last 2 requests:
```

fetch Request:
bitfinex2 GET https://api-pub.bitfinex.com/v2/conf/pub:list:pair:margin
RequestHeaders:

RequestBody:


handleRestResponse:
bitfinex2 GET https://api-pub.bitfinex.com/v2/conf/pub:list:pair:margin 200 OK
ResponseHeaders:

ResponseBody:
[["ADABTC","ADAUSD","ADAUST","ALGUSD","ALGUST","APEUSD","APEUST","APTUSD","APTUST","ATOUSD","ATOUST","AVAX:BTC","AVAX:USD","AVAX:UST","AXSUSD","AXSUST","BCHN:USD","BTCEUR","BTCEUT","BTCGBP","BTCJPY","BTCUSD","BTCUST","COMP:USD","COMP:UST","DAIUSD","DOGE:BTC","DOGE:USD","DOGE:UST","DOTBTC","DOTUSD","DOTUST","DSHBTC","DSHUSD","EGLD:USD","EGLD:UST","EOSBTC","EOSETH","EOSUSD","EOSUST","ETCBTC","ETCUSD","ETCUST","ETHBTC","ETHEUR","ETHEUT","ETHGBP","ETHJPY","ETHUSD","ETHUST","ETHW:USD","ETHW:UST","FILUSD","FILUST","FTMUSD","FTMUST","IOTBTC","IOTUSD","LEOUSD","LEOUST","LINK:USD","LINK:UST","LTCBTC","LTCUSD","LTCUST","MATIC:USD","MATIC:UST","MKRUSD","NEOBTC","NEOUSD","NEOUST","SHIB:USD","SHIB:UST","SOLBTC","SOLUSD","SOLUST","SUSHI:USD","SUSHI:UST","TESTADA:TESTUSD","TESTALGO:TESTUSD","TESTAPT:TESTUSD","TESTAVAX:TESTUSD","TESTBTC:TESTUSD","TESTBTC:TESTUSDT","TESTDOGE:TESTUSD","TESTDOT:TESTUSD","TESTEOS:TESTUSD","TESTETH:TESTUSD","TESTFIL:TESTUSD","TESTLTC:TESTUSD","TESTMATIC:TESTUSD","TESTNEAR:TESTUSD","TESTSOL:TESTUSD","TESTXAUT:TESTUSD","TESTXTZ:TESTUSD","TRXUSD","TRXUST","UNIUSD","UNIUST","USTUSD","XAUT:BTC","XAUT:USD","XAUT:UST","XLMBTC","XLMUSD","XMRBTC","XMRUSD","XMRUST","XRPBTC","XRPUSD","XRPUST","XTZBTC","XTZUSD","XTZUST","YFIUSD","YFIUST","ZECBTC","ZECUSD","ZRXUSD"]]

fetch Request:
bitfinex2 GET https://api-pub.bitfinex.com/v2/ticker/tTESTBTC:TESTUSD
RequestHeaders:

RequestBody:


handleRestResponse:
bitfinex2 GET https://api-pub.bitfinex.com/v2/ticker/tTESTBTC:TESTUSD 200 OK
ResponseHeaders:

ResponseBody:
[65647,173.1381688,65650,188.40780695,-3443,-0.04983932,65639,4005.54537102,69900,64192]
```

### Code

```
using ccxt;
var config = new Dictionary<string, object>() {
          { "enableRateLimit", true },
          { "apiKey", "API_KEY" },
          { "secret", "API_SECRET" },
          { "password", "" },
          { "uid", "" },
          { "proxy", "" },
          { "verbose", true }
      };
var exchange = Exchange.DynamicallyCreateInstance("bitfinex2", config);
await exchange.FetchTicker("TESTBTC/TESTUSD");
```

**Comment by wolfgang-s** [comment]
Environment:
- dotnet core 8

**Comment by carlosmiei** [comment]
Hello @wolfgang-s, thanks for reporting it, we will take a look asap.

**Comment by carlosmiei** [comment]
@wolfgang-s Can you please update your ccxt version to the latest (4.3.41) and try again? I believe it should be working

**Comment by wolfgang-s** [comment]
Ok I tested, but I think this happens at different locations as well. I don't use all endpoints, but this one fails as well:
```
  Error Message:
   System.InvalidCastException : Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.
  Stack Trace:
     at ccxt.Exchange.CancelAllOrders(String symbol, Dictionary`2 parameters) in /dotnet/ccxt/cs/ccxt/base/Exchange.Wrappers.cs:line 698
```
verbose output (no orders to cancel) return an empty list
```
fetch Request:
bitfinex2 POST https://api.bitfinex.com/v2/auth/w/order/cancel/multi
RequestHeaders:
bfx-nonce, 1717650379672
bfx-apikey, g8EzaC**NdAa
bfx-signature, 3309772857f***29c93a15893
Content-Type, application/json

RequestBody:
"{\"all\":1}"

handleRestResponse:
bitfinex2 POST https://api.bitfinex.com/v2/auth/w/order/cancel/multi 200 OK
ResponseHeaders:

ResponseBody:
[1712069893792,"oc_multi-req",null,null,[],null,"SUCCESS","Submitting 0 order cancellations."]
```
Thank you!

**Comment by carlosmiei** [comment]
@wolfgang-s checking it

**Comment by carlosmiei** [comment]
```
 ccxt@4.3.41 cli.cs
> dotnet run --project "./cs/cli/cli.csproj" bitfinex2 CancelAllOrders LTC/USDT

[
  "LTC/USDT"
]
[
  {
    "id": "156522905492",
    "clientOrderId": "1717587206653",
    "timestamp": 1717603200302,
    "datetime": "2024-06-05T16:00:00.302Z",
    "lastTradeTimestamp": null,
    "symbol": "LTC/USDT",
    "type": "limit",
    "side": "buy",
    "price": 50.0,
    "cost": 0.0,
    "average": null,
    "amount": 0.1,
    "filled": 0.0,
    "triggerPrice": null,
    "stopLossPrice": null,
    "takeProfitPrice": null,
    "remaining": 0.1,
    "status": "open",
    "reduceOnly": false,
    "postOnly": false,
    "fee": {
      "rate": null,
      "cost": null
    },
    "trades": [],
```
```
> dotnet run --project "./cs/cli/cli.csproj" bitfinex2 CancelAllOrders LTC/USDT

[
  "LTC/USDT"
]
[]
```
@wolfgang-s How can I reproduce this issue? locally I'm not seeing it

**Comment by carlosmiei** [comment]
@wolfgang-s the issue is related to the fact that the return type of `cancelALlOrders` is not unified yet. As a workaround, you can either call the untyped version `cancelAllOrders` or cast your instance to `ccxt.bitfinex2` instead of using it as `ccxt.Exchange`.

In the meantime, we will try to come up with a fix.

**Comment by wolfgang-s** [comment]
@carlosmiei 
Ok, ich pulled the latest version from master now, and the problem ist still here on all exchanges I test with:
- bitfinex
- kraken
- bitstamp
When do you think your Changes will be merged?
Thanks!

**Comment by carlosmiei** [comment]
@wolfgang-s Sorry for the delay, we're in the process of unifying that return type but might take a few days, in the meantime, can you use the workarounds mentioned above?  Alternatively you can use the untyped version of the method `cancelAllOrders` (instead of `CancelAllOrders`

**Comment by wolfgang-s** [comment]
@carlosmiei when do you think will you finish the typed versions of the c# version?

Would be nice to have it all typed ;) Thanks!

**Comment by carlosmiei** [comment]
@wolfgang-s Hello, we have a few `CancelOrder` methods typed, please bear in mind that the typed method in c# is the capitlzied one (`CreateOrder/CancelOrder/etc` instead of `createOrder/cancelOrder)`)

**Comment by wolfgang-s** [comment]
Thanks for your fast reply!

The last problem I have is the CancelAllOrders method. 
It throws this error:
`    public async Task<Dictionary<string, object>> CancelAllOrders(string symbol = null, Dictionary<string, object> parameters = null)
    {
        var res = await this.cancelAllOrders(symbol, parameters);
        return ((Dictionary<string, object>)res);
    }`
Errors:
`  Error Message:
   System.InvalidCastException : Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.
  Stack Trace:
     at ccxt.Exchange.CancelAllOrders(String symbol, Dictionary`2 parameters) in /ccxt/cs/ccxt/base/Exchange.Wrappers.cs:line 698`
Is there anything I'm doing wrong? I'm testing using:
- bitfinex2
- kraken
- bitstamp
They all have the same error.

**Comment by carlosmiei** [comment]
@wolfgang-s I ill check it and let you know, thanks once again

**Comment by carlosmiei** [comment]
@wolfgang-s btw what's your ccxt version? I tested it locally and seems to be working

```
dotnet run --project "./cs/cli/cli.csproj" kraken cancelAllOrders LTC/USDT

[
  "LTC/USDT"
]
[
  {
    "info": {
      "error": [],
      "result": {
        "count": 1
      }
    },
    "fees": [],
    "id": null,
    "clientOrderId": null,
    "timestamp": null,
    "datetime": null,
    "symbol": null,
    "type": null,
    "side": null,
    "lastTradeTimestamp": null,
    "lastUpdateTimestamp": null,
    "price": null,
    "amount": null,
    "cost": null,
    "average": null,
    "filled": null,
    "remaining": null,
    "timeInForce": null,
    "postOnly": null,
    "trades": [],
    "reduceOnly": null,
    "stopPrice": null,
    "triggerPrice": null,
    "takeProfitPrice": null,
    "stopLossPrice": null,
    "status": null,
    "fee": null
  }
]
```
```
npm run cli.cs -- bitstamp cancelAllOrders  "BTC/USDT"

> ccxt@4.3.89 cli.cs
> dotnet run --project "./cs/cli/cli.csproj" bitstamp cancelAllOrders BTC/USDT

[
  "BTC/USDT"
]
[]
```

**Comment by wolfgang-s** [comment]
Weird, I'm using ccxt 4.3.95. 

The **only difference** I see here is, I'm cancelling **ALL orders from ALL symbols**, without parameter:
```
await exchange.CancelAllOrders();
```

Can you test this as well? Most of the exchanges support this method.

Thanks!

Here is the verbose output:

Bitfinex2:
```
fetch Request:
bitfinex2 POST https://api.bitfinex.com/v2/auth/w/order/cancel/multi
RequestHeaders:
bfx-nonce, 1725418939329
bfx-apikey, g8EzaC**NdAa
bfx-signature, b787****b343
Content-Type, application/json

RequestBody:
"{\"all\":1}"

handleRestResponse:
bitfinex2 POST https://api.bitfinex.com/v2/auth/w/order/cancel/multi 200 OK
ResponseHeaders:

ResponseBody:
[1712069893792,"oc_multi-req",null,null,[],null,"SUCCESS","Submitting 0 order cancellations."]

[xUnit.net 00:00:22.87]    Test.CcxtServiceTest.TestCcxtBitfinex2 [FAIL]
  Failed Test.CcxtServiceTest.TestCcxtBitfinex2 [7 s]
  Error Message:
   System.InvalidCastException : Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.
  Stack Trace:
     at ccxt.Exchange.CancelAllOrders(String symbol, Dictionary`2 parameters)
`
``

Kraken:
```
fetch Request:
kraken POST https://api.kraken.com/0/private/CancelAll
RequestHeaders:
API-Key, LTKK***Jv0nM
API-Sign, 6emy***cU2Wiye/Q==
Content-Type, application/x-www-form-urlencoded

RequestBody:
"nonce=1725419046039"

handleRestResponse:
kraken POST https://api.kraken.com/0/private/CancelAll 200 OK
ResponseHeaders:

ResponseBody:
{"error":[],"result":{"count":0}}

[xUnit.net 00:00:13.76]     Test.CcxtServiceTest.TestCcxtKraken [FAIL]
  Failed Test.CcxtServiceTest.TestCcxtKraken [13 s]
  Error Message:
   System.InvalidCastException : Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.
  Stack Trace:
     at ccxt.Exchange.CancelAllOrders(String symbol, Dictionary`2 parameters)
```

Bitstamp:
```
fetch Request:
bitstamp POST https://www.bitstamp.net/api/v2/cancel_all_orders/
RequestHeaders:
X-Auth, BITSTAMP eI***ysi
X-Auth-Nonce, f3207a3e-5ff5-44f6-8ae2-8322fd7c91b8
X-Auth-Timestamp, 1725420812000
X-Auth-Version, v2
Content-Type, application/x-www-form-urlencoded
X-Auth-Signature, fd07***25d9

RequestBody:
"foo=bar"

handleRestResponse:
bitstamp POST https://www.bitstamp.net/api/v2/cancel_all_orders/ 200 OK
ResponseHeaders:

ResponseBody:
{"success": true, "canceled": [{"currency_pair": "BTC/USD", "market": "BTC/USD", "price": 57925, "amount": 0.001, "type": 1, "id": 1788253970563073}]}

[xUnit.net 00:00:02.43]     Test.CcxtServiceTest.TestCcxtBitstamp [FAIL]
  Failed Test.CcxtServiceTest.TestCcxtBitstamp [2 s]
  Error Message:
   System.InvalidCastException : Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.
  Stack Trace:
     at ccxt.Exchange.CancelAllOrders(String symbol, Dictionary`2 parameters)
```

**Comment by carlosmiei** [comment]
@wolfgang-s Sorry for the delay, I just tested it without `symbol` and still worked 🤔 

```
✗ npm run cli.cs --  bitfinex2 CancelAllOrders           
Debugger listening on ws://127.0.0.1:52902/79401f61-64fb-45eb-bb01-f3c67ada636e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> ccxt@4.4.0 cli.cs
> dotnet run --project "./cs/cli/cli.csproj" bitfinex2 CancelAllOrders

[]
[]
Waiting for the debugger to disconnect...
````
```
Debugger listening on ws://127.0.0.1:52928/9f636a43-eff5-45fc-87ec-f2ed5b01ecf0
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> ccxt@4.4.0 cli.cs
> dotnet run --project "./cs/cli/cli.csproj" kraken CancelAllOrders

[]
[
  {
    "id": null,
    "clientOrderId": null,
    "timestamp": null,
    "datetime": null,
    "lastTradeTimestamp": null,
    "symbol": null,
    "type": null,
    "side": null,
    "price": null,
    "cost": null,
    "average": null,
    "amount": null,
    "filled": null,
    "triggerPrice": null,
    "stopLossPrice": null,
    "takeProfitPrice": null,
    "remaining": null,
    "status": null,
    "reduceOnly": false,
    "postOnly": false,
    "fee": {
      "rate": null,
      "cost": null
    },
    "trades": [],
    "info": {
      "error": [],
      "result": {
        "count": 1
      }
    }
  }
]
```
```

> ccxt@4.4.0 cli.cs
> dotnet run --project "./cs/cli/cli.csproj" bitstamp CancelAllOrders

[]
[]
```

**Comment by kroitor** [comment]
Hello @wolfgang-s 👋

Closing this one during a cleanup of older issues — with good news: the typed C# unification that was in progress back then has landed. `bitfinex` (and the other exchanges) now expose a properly typed `CancelAllOrders` returning `Task<List<Order>>`, along with typed `CancelOrder`, so the `InvalidCastException` workarounds are no longer needed. Just remember the typed methods are the capitalized ones (`CancelAllOrders` vs the untyped `cancelAllOrders`).

If you upgrade to a recent ccxt version and still hit a casting issue anywhere, please open a fresh issue with the exchange and snippet and we'll fix it quickly. Thanks for the patience and the detailed reports! 🙏
