### ISSUE TITLE
C# Bitstamp CreateOrder Content-Type header is not accepted + wrong nonce generation

### ISSUE THREAD

**Issue by wolfgang-s** [ccxt/ccxt#22739]
### Operating System

OSX

### CCXT Version

4.3.40 / master branch

### Description

When trying to create an Order on Bitstamp, it fails with:

```
  Error Message:
   ccxt.ExchangeError : bitstamp {"status": "error", "reason": "Content-Type header is not accepted", "code": "API0019"}
  Stack Trace:
     at ccxt.bitstamp.handleErrors(Object httpCode, Object reason, Object url, Object method, Object headers, Object body, Object response, Object requestHeaders, Object requestBody) in /dotnet/ccxt/cs/ccxt/exchanges/bitstamp.cs:line 2501
   at ccxt.Exchange.fetch(Object url2, Object method2, Object headers2, Object body2) in /dotnet/ccxt/cs/ccxt/base/Exchange.cs:line 311
   at ccxt.Exchange.fetch2(Object path, Object api, Object method, Object parameters, Object headers, Object body, Object config) in /Users/wolfgangsteuer/Documents/dotnet/ccxt/cs/ccxt/base/Exchange.BaseMethods.cs:line 2966
   at ccxt.Exchange.callAsync(Object implicitEndpoint2, Object parameters) in /dotnet/ccxt/cs/ccxt/base/Exchange.cs:line 364
   at ccxt.bitstamp.privatePostBuyPair(Object parameters) in /dotnet/ccxt/cs/ccxt/api/bitstamp.cs:line 161
   at ccxt.bitstamp.createOrder(Object symbol, Object type, Object side, Object amount, Object price, Object parameters) in /dotnet/ccxt/cs/ccxt/exchanges/bitstamp.cs:line 1466
   at ccxt.Exchange.CreateOrder(String symbol, String type, String side, Double amount, Nullable`1 price2, Dictionary`2 parameters) in /dotnet/ccxt/cs/ccxt/base/Exchange.Wrappers.cs:line 564
```
Reason is you guys use:
Exchange.cs:234
```
var stringContent = body != null ? new StringContent(body, Encoding.UTF8, contentTypeHeader) : null;
```
which will append the Charset when calling ToString():
```
application/x-www-form-urlencoded; charset=utf-8
```
Solution (I guess) is to just remove the Charset at all, because I don't think any Exchange uses special chars within their API? For me, this solution works for Bitstamp, Bitfinex2, Kraken, Binance at least
```
var stringContent = body != null ? new StringContent(body, Encoding.UTF8, contentTypeHeader) : null;
stringContent.Headers.ContentType.CharSet = "";
```

**Another bug** fix is to generate the nonce differently. Currently you have this:
bitstamp.cs:2399
```
object xAuthNonce = this.uuid();
```
But it should be:
```
object xAuthNonce = this.uuid2();
```

The error here is just "invalid nonce" with your current implementation:
```
   ccxt.ExchangeError : bitstamp {"status": "error", "reason": "Invalid nonce", "code": "API0004"}
```
Verbose log before:
```
fetch Request:
bitstamp POST https://www.bitstamp.net/api/v2/buy/btcusd/
RequestHeaders:
X-Auth, BITSTAMP eI0***xysi
**X-Auth-Nonce, 7978be3c43e34109b71a2c4c51813558**
X-Auth-Timestamp, 1717596293787
X-Auth-Version, v2
Content-Type, application/x-www-form-urlencoded
X-Auth-Signature, 04de***df8a8

RequestBody:
"amount=0.001&price=69228"

INFO: Sending request: POST https://www.bitstamp.net/api/v2/buy/btcusd/
handleRestResponse:
bitstamp POST https://www.bitstamp.net/api/v2/buy/btcusd/ 403 Authentication Failed
ResponseHeaders:

ResponseBody:
{"status": "error", "reason": "Invalid nonce", "code": "API0004"}
```
Verbose log after nonce fix:
_Interesting enough you see, the content-type header only looks good, but the serialization in the verbose log is different_
```
fetch Request:
bitstamp POST https://www.bitstamp.net/api/v2/buy/btcusd/
RequestHeaders:
X-Auth, BITSTAMP eI0x****oxysi
X-Auth-Nonce, 950b2b18-5fd0-458e-988f-eb794b6b083d
X-Auth-Timestamp, 1717595976787
X-Auth-Version, v2
Content-Type, application/x-www-form-urlencoded
X-Auth-Signature, 2c69e75d****b99031cfa3

RequestBody:
"amount=0.001&price=69325"

INFO: Sending request: POST https://www.bitstamp.net/api/v2/buy/btcusd/
handleRestResponse:
bitstamp POST https://www.bitstamp.net/api/v2/buy/btcusd/ 403 Authentication Failed
ResponseHeaders:

ResponseBody:
```
ccxt.ExchangeError : bitstamp {"status": "error", "reason": "Invalid nonce", "code": "API0004"}
```

```
Verbose log after content-type header fix:
```
fetch Request:
bitstamp POST https://www.bitstamp.net/api/v2/buy/btcusd/
RequestHeaders:
X-Auth, BITSTAMP eI0xm***ysi
X-Auth-Nonce, 2e5da71c-2976-486e-bb3d-f7b00603f10e
X-Auth-Timestamp, 1717595766290
X-Auth-Version, v2
Content-Type, application/x-www-form-urlencoded
X-Auth-Signature, f91e838****7e6e90a5a

RequestBody:
"amount=0.001&price=69372"

INFO: Sending request: POST https://www.bitstamp.net/api/v2/buy/btcusd/
handleRestResponse:
bitstamp POST https://www.bitstamp.net/api/v2/buy/btcusd/ 200 OK
ResponseHeaders:

ResponseBody:
{"id": "1756204203130880", "market": "BTC/USD", "datetime": "2024-06-05 13:56:06.437000", "type": "0", "amount": "0.00100000", "price": "69372"}
```

### Code

```
using ccxt;
var config = new Dictionary<string, object>() {
          { "enableRateLimit", true },
          { "apiKey", "API_KEY" },
          { "secret", "API_SECRET" },
          { "password", "" },
          { "uid", "" },
          { "proxy", "" },
          { "verbose", true }
      };
var exchange = Exchange.DynamicallyCreateInstance("bitstamp", config);
await exchange.CreateOrder("BTC/USD", "limit", "buy", 0.001, 69372);
```

**Comment by carlosmiei** [comment]
Hello @wolfgang-s, interesting, we will check and revert asap.

**Comment by carlosmiei** [comment]
@wolfgang-s I also get the invalid nonce error but `this.uuid2` is not available across the other languages so we can't use it here. I will try to find an alternative.

**Comment by carlosmiei** [comment]
@wolfgang-s And here, this should be fixed as well.

**Comment by wolfgang-s** [comment]
Thanks, works!
