### ISSUE TITLE
Webpack: Can't not bundle exchange javascript 

### ISSUE THREAD

**Issue by mahapo** [ccxt/ccxt#2285]
I can not bundle cxchange files or the ccxt file with webpack 4.1.1. I tried all webpack issues in the ccxt issues section:
```
module.exports = {
  mode: 'development',
  entry: {
    // 'ccxt': './node_modules/ccxt/ccxt.js',
    'liqui': './node_modules/ccxt/js/liqui.js',
    // 'binance': './node_modules/ccxt/js/binance.js',
    // 'ccxt': ["babel-polyfill", './node_modules/ccxt/ccxt.js']
  },
  output: {
    filename: '[name].js',
    // library: 'ccxt',
    // libraryTarget: 'commonjs'
  },
  module: {
    rules: [
      {
        test: /node_modules\/ccxt\/(.+)\.js$/,
        loader: "babel-loader",
        options: {
          babelrc: false,
          cacheDirectory: false,
          presets: ["es2015"],
          plugins: ["syntax-async-functions", "transform-regenerator"]
        }
      }
    ]
  }
};
```
It print this error
```
webpack:///./node_modules/ccxt/node_modules/fetch-ponyfill/build/fetch-browser.js?:9
    var Promise = options && options.Promise || self.Promise;
                                                     ^

TypeError: Cannot read property 'Promise' of undefined
    at fetchPonyfill (webpack:///./node_modules/ccxt/node_modules/fetch-ponyfill/build/fetch-browser.js?:9:54)
    at Object.eval (webpack:///./node_modules/ccxt/js/base/Exchange.js?:47:144)
    at eval (webpack:///./node_modules/ccxt/js/base/Exchange.js?:1391:30)
    at Object.node_modulesCcxtJsBaseExchangeJs (/Users/ma/me/de/server/dist/liqui.js:82:1)
    at __webpack_require__ (/Users/ma/me/de/server/dist/liqui.js:20:30)
    at eval (webpack:///./node_modules/ccxt/js/liqui.js?:15:16)
    at Object.node_modulesCcxtJsLiquiJs (/Users/ma/me/de/server/dist/liqui.js:250:1)
    at __webpack_require__ (/Users/ma/me/de/server/dist/liqui.js:20:30)
    at /Users/ma/me/de/server/dist/liqui.js:69:18
    at Object.<anonymous> (/Users/ma/me/de/server/dist/liqui.js:1:10)
    at Module._compile (module.js:652:30)
    at loader (/Users/ma/me/de/server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ma/me/de/server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c babel-node --presets=es2015 ./app.js
Directory: /Users/ma/me/de/server
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ma/me/de/server/yarn-error.log".
```

**Comment by kroitor** [comment]
@mahapo we would be happy if you would share a solution to this, if you found one... thx!

**Comment by dgurudot** [comment]
@mahapo Can you please share the solution to this issue? 

It is closed without an appropriate solution.
