### ISSUE TITLE
Coinbase open order does not appear in balance "used" or "total"

### ISSUE THREAD

**Issue by ryancwalsh** [ccxt/ccxt#22878]
### Operating System

Ubuntu

### Programming Languages

JavaScript

### CCXT Version

"ccxt": "^4.3.50",

### Description

Thanks for your amazing library. I appreciate all of your hard work. 😀

My TypeScript Next.js app uses `"ccxt": "^4.3.50",`.

At https://github.com/ccxt/ccxt/wiki/Manual#account-balance , I see "used" defined as `float, money on hold, locked, frozen or pending`. That makes sense to me and is how I was hoping it would work.

However, when I query my Coinbase account (see code below), I see in `balance`:

```
  "NEAR": {
      "free": 0.720174069199334,
      "used": 0,
      "total": 0.720174069199334
    },
```

but `openOrders` shows a different amount of NEAR tokens (let's call it X), and I think that `balance.NEAR.used` should equal X, and I think "total" should equal X + 0.720174069199334.

Or am I misunderstanding something?

Thanks!

### Code

```typescript
  
import type { NextApiRequest, NextApiResponse } from 'next';
import { addCacheHeader } from '../../helpers/cachedQueries/cachedQueries';
import { cacheSeconds } from '../../helpers/config';
import { ExchangeCredentialsAndOptions, exchangesCredentials } from '../../constants/config';
import ccxt from 'ccxt';

export default async function handler(request: NextApiRequest, response: NextApiResponse<any>) {
  const exchangeId = 'coinbase';
  const exchangeDetails = exchangesCredentials.find((credential) => {
    return credential.id === exchangeId;
  }) as ExchangeCredentialsAndOptions;
  exchangeDetails.verbose = true;
  const exchangeClass = ccxt[exchangeId];

  const exchange = new exchangeClass(exchangeDetails);
  const balance = await exchange.fetchBalance();

  const openOrders = await exchange.fetchOpenOrders(); 

  addCacheHeader(response, cacheSeconds);
  response.status(200).json({ exchangeDetails, balance, openOrders });
}

```

**Comment by sc0Vu** [comment]
Hi @ryancwalsh,

Could you paste the verbose log for `fetchBalance`? I try locally and it worked (both v2 and v3).

**Comment by ryancwalsh** [comment]
@sc0Vu Thanks for your quick response!

The verbose output is _enormous_, and I feel uncomfortable pasting it here since it contains so much information, including my positions.

I see lines like `handleRestResponse:  coinbase GET https://api.coinbase.com/v2/accounts?limit=100 200 OK ` and `ResponseBody:` looks as I'd expect except what I mentioned in the issue above.

What was surprising about the verbose logging is that many _other_ fetches are happening too, even though they seem unrelated to my `exchange.fetchBalance()` call.

E.g.:

* `coinbase GET https://api.coinbase.com/v2/currencies 200 OK `
* `coinbase GET https://api.coinbase.com/v2/currencies/crypto 200 OK `
* `coinbase GET https://api.coinbase.com/api/v3/brokerage/market/products 200 OK `
* `coinbase GET https://api.coinbase.com/v2/exchange-rates 200 OK `
* `coinbase GET https://api.coinbase.com/api/v3/brokerage/transaction_summary 200 OK `
* `coinbase GET https://api.coinbase.com/api/v3/brokerage/market/products?product_type=FUTURE 200 OK `
* `coinbase GET https://api.coinbase.com/api/v3/brokerage/market/products?product_type=FUTURE&contract_expiry_type=PERPETUAL 200 OK `

My `exchangesCredentials` array looks like:

```
[
  {"id":"coinbase","apiKey":"_________","secret":"_________","options":{"accounts":["wallet","fiat","vault"]}},
  //...
]
```

I'm now noticing in the `GET` queries above, sometimes v2 is in the URL and sometimes v3. 

I'm not sure what settings lead to that or whether it matters.

If there is a sandbox mode or some safe way to test and paste verbose logs, I'd be happy to do it.

Thanks!

**Comment by sc0Vu** [comment]
@ryancwalsh that's fince, I want to see api urls.

In coinbase, we integrated their v2 and v3 api and the response would change. It seems there is no used value in v2 balance response.

Could you change to v3 api when initialize exchange?
```
        'options': {
            'fetchBalance': 'v3PrivateGetBrokerageAccounts'
        }
```

**Comment by ryancwalsh** [comment]
Thanks for this idea, @sc0Vu .

I tried:

```TypeScript
const exchange = new exchangeClass(exchangeDetails);
exchange.options = {
  fetchBalance: 'v3PrivateGetBrokerageAccounts',
};
```

(Did I understand correctly and do what you wanted me to do?)

Now I get an error:

```
error - TypeError: Cannot set properties of undefined (setting 'AED')
    at coinbase.fetchCurrencies (/home/rcwalsh/code/investments-next/node_modules/ccxt/dist/cjs/src/coinbase.js:1729:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async coinbase.loadMarketsHelper (/home/rcwalsh/code/investments-next/node_modules/ccxt/dist/cjs/src/base/Exchange.js:1068:26)
    at async coinbase.fetchBalance (/home/rcwalsh/code/investments-next/node_modules/ccxt/dist/cjs/src/coinbase.js:2159:9)
    at async handler (webpack-internal:///./pages/api/coinbase.ts:28:19)
    at async Object.apiResolver (/home/rcwalsh/code/investments-next/node_modules/next/dist/server/api-utils.js:101:9)
    at async DevServer.handleApiRequest (/home/rcwalsh/code/investments-next/node_modules/next/dist/server/next-server.js:770:9)
    at async Object.fn (/home/rcwalsh/code/investments-next/node_modules/next/dist/server/next-server.js:661:37)
    at async Router.execute (/home/rcwalsh/code/investments-next/node_modules/next/dist/server/router.js:205:32) 
```

Thanks.

**Comment by sc0Vu** [comment]
@ryancwalsh the error occurred because the options was rewritten.

eg.
```PY
exchangeDetails = {
  apiKey: 'xxxxx',
  secret: 'xxxxx',
  'options': {
    fetchBalance: 'v3PrivateGetBrokerageAccounts'
  }
}
```

**Comment by ryancwalsh** [comment]
@sc0Vu This worked! 

Free, used, and total are now what I expect.

Thanks!!

**Comment by carlotestor** [comment]
This can be closed without further user input.

Reporter confirmed the suggested Coinbase `fetchBalance` option fixed free/used/total:

> This worked! Free, used, and total are now what I expect. Thanks!!

Resolution path discussed: use the v3 brokerage accounts balance path via options when initializing the exchange (so options are not overwritten after construct).
