### ISSUE TITLE
bybit unable use watch_my_trades and watch_orders for SOL/USDC:USDC

### ISSUE THREAD

**Issue by guesshaha** [ccxt/ccxt#22884]
### Operating System

Linux guess 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Programming Languages

Python

### CCXT Version

4.3.51

### Description

I want to watch my trade and watch my order for SOL/USDC:USDC in bybit , but can not and will produce error, and for USDT this error will not occur, can you help me solve this

Traceback (most recent call last):
  File "/home/guess/project/work/beavo/task/grid/trade/remote/grid/grid_strategy.py", line 215, in watch_my_trade_loop
    trade_list = await self.exchange.watch_my_trades(self.symbol)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guess/miniconda3/envs/beavo_trading_env/lib/python3.11/site-packages/ccxt/pro/bybit.py", line 891, in watch_my_trades
    await self.authenticate(url)
  File "/home/guess/miniconda3/envs/beavo_trading_env/lib/python3.11/site-packages/ccxt/pro/bybit.py", line 1804, in authenticate
    return await future
           ^^^^^^^^^^^^
  File "/home/guess/miniconda3/envs/beavo_trading_env/lib/python3.11/site-packages/ccxt/async_support/base/ws/fast_client.py", line 26, in handler
    self.handle_message(message)
  File "/home/guess/miniconda3/envs/beavo_trading_env/lib/python3.11/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 34, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/home/guess/miniconda3/envs/beavo_trading_env/lib/python3.11/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 29, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/home/guess/miniconda3/envs/beavo_trading_env/lib/python3.11/site-packages/ccxt/pro/bybit.py", line 1927, in handle_message
    if topic.find(keys[i]) >= 0:
       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

### Code

```
  order_info_list = await self.exchange.watch_orders(self.symbol)
  trade_list = await self.exchange.watch_my_trades(self.symbol)

```

**Comment by carlosmiei** [comment]
Hello @guesshaha, thanks for reporting it we will take a look and let you know.

**Comment by dudalev** [comment]
similar (same?) problem with many other products

e.g. try

`res = await ccxtpro.bybit({'newUpdates': False}).watch_trades("BTC/USD:BTC-241227")`

version is '4.3.75'

**Comment by carlosmiei** [comment]
@dudalev can you please open a new issue? delivery futures are a different market type so I think we should handle them separately

**Comment by kroitor** [comment]
Hello @guesshaha 👋

We're doing a cleanup of older issues, and this one has been quiet for a while. Since it was reported, bybit's WS handling has been reworked quite a bit (including the inverse/delivery futures subscription fix in #23343), so there's a good chance this is already resolved in recent versions — the one in the report (4.3.51) is quite old by now.

I'll close this as inactive for now. If you're still seeing the error on the latest ccxt, please don't hesitate to reply or open a fresh issue with an updated traceback and we'll take another look — always happy to reopen. Thanks again for the report! 🙏
