### ISSUE TITLE
Hyperliquid - User or API Wallet 0x.. does not exist

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#22896]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.50

### Description

Hello, 

Hyperliquid `create_order` doesn't work for me, see below for the code. The hyperliquid discord suggests something is wrong with signing, and that they phased out an old signing method a couple of weeks ago. Or am I not configuring the private key properly? No hits on 'walletaddress' or 'privatekey' on https://github.com/ccxt/ccxt/wiki/Manual , so I'm not sure..

Thanks!

### Code

```
private_key = f'0x{mnemonic.Mnemonic.to_seed(phrase).hex()}'
e = ccxt.hyperliquid()
e.walletAddress = account
e.privateKey = private_key 
pprint(await e.fetch_balance())  # This works
pprint(await e.create_order('ETH/USDC:USDC', 'limit', 'buy', 0.004, 3200, {'leverage': 1}))

Traceback (most recent call last):
  File "C:\Users\test\PycharmProjects\Testproject\_test\test_hyperliquid.py", line 49, in tst
    pprint(await e.create_order('ETH/USDC:USDC', 'limit', 'buy', 0.004, 3200, {'leverage': 1}))
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\async_support\hyperliquid.py", line 1023, in create_order
    response = await self.create_orders([order], globalParams)
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\async_support\hyperliquid.py", line 1138, in create_orders
    response = await self.privatePostExchange(self.extend(request, params))
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\async_support\base\exchange.py", line 832, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\async_support\base\exchange.py", line 829, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\async_support\base\exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\async_support\hyperliquid.py", line 2430, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], message, feedback)
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\base\exchange.py", line 4127, in throw_broadly_matched_exception
    raise broad[broadKey](message)
ccxt.base.errors.InvalidOrder: hyperliquid {"status":"err","response":"L1 error: User or API Wallet <some 0x... address I don't recognize> does not exist."}

```

**Comment by sc0Vu** [comment]
Hi @gaardiolor, 

Uh, it didn't work with leverage settings. Looks like they changed the signing payload.

We'll fix this asap.

**Comment by sc0Vu** [comment]
@gaardiolor they don't support other parameters when createOrder, eg. leverage. To update leverage, please use `setLeverage` (they use another api in frontend as well). BTW, we'll prevent sending other parameters in exchange.

**Comment by gaardiolor** [comment]
Ok, thanks!

My method to get the private key from the mnemonic also wasn't good, I got a 512-bit key instead of a 256-bit key. 

Not working: 
```
import mnemonic
private_key = f'0x{mnemonic.Mnemonic.to_seed(phrase).hex()}'
```

Working:
```
from eth_account import Account
Account.enable_unaudited_hdwallet_features()
a = Account.from_mnemonic(phrase)
private_key = f'0x{a._private_key.hex()}'
```
