### ISSUE TITLE
timed out due to a ping-pong keepalive missing on time

### ISSUE THREAD

**Issue by iockx** [ccxt/ccxt#22959]
### Operating System

Ubuntu22

### Programming Languages

Python

### CCXT Version

4.3.42

### Description

Occasionally, this issue occurs when using ccxtpro to subscribe to transaction pair prices
I want to know, is there a probability that this problem is caused by a network problem?

ccxt  4.3.42
ccxtpro  1.0.1

```
exchange_app | ccxt.base.errors.RequestTimeout: Connection to wss://socket.coinex.com/ timed out due to a ping-pong keepalive missing on time
exchange_app | ERROR:    Exception in ASGI application
exchange_app | Traceback (most recent call last):
exchange_app |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
exchange_app |     result = await app(  # type: ignore[func-returns-value]
exchange_app |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
exchange_app |     return await self.app(scope, receive, send)
exchange_app |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 290, in __call__
exchange_app |     await super().__call__(scope, receive, send)
exchange_app |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
exchange_app |     await self.middleware_stack(scope, receive, send)
exchange_app |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
exchange_app |     raise exc
exchange_app |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
exchange_app |     await self.app(scope, receive, _send)
exchange_app |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
exchange_app |     raise exc
exchange_app |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
exchange_app |     await self.app(scope, receive, sender)
exchange_app |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
exchange_app |     raise e
exchange_app |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
exchange_app |     await self.app(scope, receive, send)
exchange_app |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
exchange_app |     await route.handle(scope, receive, send)
exchange_app |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
exchange_app |     await self.app(scope, receive, send)
exchange_app |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
exchange_app |     response = await func(request)
exchange_app |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 241, in app
exchange_app |     raw_response = await run_endpoint_function(
exchange_app |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
exchange_app |     return await dependant.call(**values)
exchange_app |   File "/code/app/controller/ws_sub_controller.py", line 34, in subscription
exchange_app |     return await ws_sub_service.subscription(json_list)
exchange_app |   File "/code/app/service/ws_sub_service.py", line 18, in subscription
exchange_app |     await asyncio.gather(*tasks)
exchange_app |   File "/code/app/service/ws_sub_service.py", line 36, in watch_order_book
exchange_app |     orderbook = await exchangeItem[exchange].watch_order_book(symbol=symbol)
exchange_app |   File "/usr/local/lib/python3.10/site-packages/ccxt/pro/coinex.py", line 509, in watch_order_book
exchange_app |     orderbook = await self.watch(url, messageHash, request, subscriptionHash, request)
```

### Code

```
  

```

**Comment by sc0Vu** [comment]
@iockx Probably. Have you closed unused connections?

**Comment by iockx** [comment]
> @iockx Probably. Have you closed unused connections?
I did not manually close the link
But during program execution, it is possible to repeatedly submit ws subscriptions, which could be the cause of the problem?

**Comment by kroitor** [comment]
Hello @iockx, closing this during a cleanup — occasional ping pong timeouts under many long lived subscriptions were a property of the keepalive scheduling of that era, and the ping handling and dead connection detection have been reworked since, note also that pruning subscriptions you no longer need via the unWatch methods and closing idle instances keeps the keepalive load down. If timeouts still occur regularly on a current version, a fresh issue naming the exchange with a verbose log would be very welcome. Thanks for the report back then!
