### ISSUE TITLE
Hyperliquid fetch_order for limit order: status is "closed" but "filled" is None

### ISSUE THREAD

**Issue by DumplingLife** [ccxt/ccxt#23014]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.3.57

### Description

Hi I was making limit orders using create_order/edit_order and fetching them with fetch_order, and I saw the result came back with: {..., 'filled': None, ..., 'status': 'closed', ...}
I expected it to be {..., 'filled': 200, ..., 'status': 'closed', ...}, according to the docs (https://docs.ccxt.com/#/?id=order-structure).

### Code

```
hyperliquid.create_order("DOGE/USDC:USDC", "limit", "sell", 200, price, params={'postOnly': True})
order_status = await hyperliquid.fetch_order(order_id, symbol, params={...})
print(order_status)
```

**Comment by sc0Vu** [comment]
Hi @DumplingLife, the value would not be empty if exchange provide. I also review the response of fetchOrder, not sure whether the sz or origSz is executed size of the given order.

**Comment by carlosmiei** [comment]
Hello @kjnh10 @DumplingLife This is fixed now, if you update your ccxt version you should be able to see `filled` with the correct value.

Will close this issue but feel free to reopen it if needed!

**Comment by kjnh10** [comment]
@carlosmiei

which version is this issue fixed?
I'm using 4.4.25, but the issue seems to remain.

**Comment by carlosmiei** [comment]
@kjnh10 Hum weird, you see this issue with `fetchOrder` or `createOrder` ?

**Comment by carlosmiei** [comment]
@kjnh10 Can you post a log?

**Comment by kjnh10** [comment]
```python
import ccxt
from pprint import pprint
exchange = ccxt.hyperliquid()
res = exchange.load_markets()

res = exchange.create_order('PURR/USDC:USDC', 'limit', 'sell', price='0.21', amount='50')
pprint(res)
res2 = exchange.fetch_order(id=res['id'], symbol='PURR/USDC:USDC')
pprint(res2)
```

output is below
```
{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '45017938300',
 'info': {'resting': {'oid': '45017938300'}},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': None,
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': None,
 'takeProfitPrice': None,
 'timeInForce': None,
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': None}
{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': None,
 'info': None,
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': None,
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': None,
 'takeProfitPrice': None,
 'timeInForce': None,
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': None}

```

**Comment by kjnh10** [comment]
It seems the oid is recognized as unknown.

```
fetch Request: hyperliquid POST https://api.hyperliquid.xyz/exchange RequestHeaders: {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate'} RequestBody: {"action":{"type":"order","orders":[{"a":152,"b":false,"p":"0.21","s":"50","r":false,"t":{"limit":{"tif":"Gtc"}}}],"grouping":"na","brokerCode":1},"nonce":1730895414689,"signature":{"r":"0x5d5fb5f6026d3eddad620430d60cd9623f405f5be6c7b33608054ae17e5d6603","s":"0x3872446553a0c5e4f64f503f47633e2d097ccd95d4fda80f4e441a6636f01405","v":27}}

fetch Response: hyperliquid POST https://api.hyperliquid.xyz/exchange 200 ResponseHeaders: {'Server': 'nginx/1.22.1', 'Date': 'Wed, 06 Nov 2024 12:16:56 GMT', 'Content-Type': 'application/json', 'Content-Length': '97', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Vary': 'origin, origin, origin', 'Access-Control-Expose-Headers': '*'} ResponseBody: {"status":"ok","response":{"type":"order","data":{"statuses":[{"resting":{"oid":45020063176}}]}}}
{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '45020063176',
 'info': {'resting': {'oid': '45020063176'}},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': None,
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': None,
 'takeProfitPrice': None,
 'timeInForce': None,
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': None}

fetch Request: hyperliquid POST https://api.hyperliquid.xyz/info RequestHeaders: {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate'} RequestBody: {"type":"orderStatus","oid":45020063176,"user":"0x68F30266842cf22C01A38cFC7610129814f73cE4"}

fetch Response: hyperliquid POST https://api.hyperliquid.xyz/info 200 ResponseHeaders: {'Server': 'nginx/1.22.1', 'Date': 'Wed, 06 Nov 2024 12:16:56 GMT', 'Content-Type': 'application/json', 'Content-Length': '23', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Vary': 'origin, origin, origin', 'Access-Control-Expose-Headers': '*'} ResponseBody: {"status":"unknownOid"}
{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': None,
 'info': None,
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': None,
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': None,
 'takeProfitPrice': None,
 'timeInForce': None,
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': None}

```

**Comment by carlosmiei** [comment]
@kjnh10 Hum exactly `{"status":"unknownOid"}`  let me run that on my end

**Comment by kjnh10** [comment]
I'm using an API key I have created here. 
https://app.hyperliquid.xyz/API

<img width="831" alt="image" src="https://github.com/user-attachments/assets/d6060e2b-6a27-497f-9ce5-a9897d707130">

I have to use my public key instead of API key for requesting info...?

**Comment by carlosmiei** [comment]
@kjnh10 Locally seems to be working fine

```
p hyperliquid fetchOrder "'16973744212'" "PURR/USDC:USDC" --sandbox
Python v3.12.3
CCXT v4.4.26
hyperliquid.fetchOrder(16973744212,PURR/USDC:USDC)
{'amount': 10.0,
 'average': None,
 'clientOrderId': None,
 'cost': 0.0,
 'datetime': '2024-11-06T12:31:59.107Z',
 'fee': None,
 'fees': [],
 'filled': 0.0,
 'id': '16973744212',
 'info': {'order': {'children': [],
                    'cloid': None,
                    'coin': 'PURR',
                    'isPositionTpsl': False,
                    'isTrigger': False,
                    'limitPx': '8.1',
                    'oid': '16973744212',
                    'orderType': 'Limit',
                    'origSz': '10.0',
                    'reduceOnly': False,
                    'side': 'B',
                    'sz': '10.0',
                    'tif': 'Gtc',
                    'timestamp': '1730896319107',
                    'triggerCondition': 'N/A',
                    'triggerPx': '0.0'},
          'status': 'open',
          'statusTimestamp': '1730896319107'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': False,
 'price': 8.1,
 'reduceOnly': False,
 'remaining': 10.0,
 'side': 'buy',
 'status': 'open',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'PURR/USDC:USDC',
 'takeProfitPrice': None,
 'timeInForce': 'GTC',
 'timestamp': 1730896319107,
 'trades': [],
 'triggerPrice': None,
 'type': 'limit'}
```

@kjnh10 If create_order is working as expected, then the keys are properly set

**Comment by kjnh10** [comment]
create_order is working fine. (I have checked it from web UI)

**Comment by carlosmiei** [comment]
@kjnh10 Can you try to set `hyperliquid.walletAddress = YOUR_PUBLIC_ADDRESS` ? 
I think that might be causing the issue

**Comment by kjnh10** [comment]
yes. working fine when I set my public one to walletAddress.

**Comment by carlosmiei** [comment]
@kjnh10 Cool, let us know if anything!

**Comment by kjnh10** [comment]
@carlosmiei 
I think some fix should be done. Is my understanding right?
fetchOrder should use public one instead of API key, so when initiating the exchange class, there should be property of 'publicWalletAddress' in addition to 'walletAddress' and 'privateKey'.

(Or add 'apiKey' and set API key to 'apiKey'.)

**Comment by carlosmiei** [comment]
@kjnh10 

I don't think any fix is needed. You just need to set `walletAddress` as the public address and `privateKey`, public endpoints use `walletAddress` whereas private ones use `privateKey`

**Comment by kjnh10** [comment]
@carlosmiei 
I think 3 types of info.

1. public wallet address
2. API wallet address
3. API wallet private key

2 and 3 is as below.
<img width="315" alt="image" src="https://github.com/user-attachments/assets/5f2462e5-8e17-4e2e-af54-2b5815634f1e">

Do you mean 2 to 'privateKey'?
If so, where 3 should be set?

**Comment by kjnh10** [comment]
@carlosmiei 
Thanks, I will try as you said.

But this error occurs from yesterday. this may be not related to the account setting.
```
fetch Request: hyperliquid POST https://api.hyperliquid.xyz/info RequestHeaders: {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate'} RequestBody: {"type":"orderStatus","oid":45023486311,"user":"future"}

fetch Response: hyperliquid POST https://api.hyperliquid.xyz/info 422 ResponseHeaders: {'Server': 'nginx/1.22.1', 'Date': 'Thu, 07 Nov 2024 10:14:36 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '56', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Vary': 'origin, origin, origin', 'Access-Control-Expose-Headers': '*'} ResponseBody: Failed to deserialize the JSON body into the target type
Traceback (most recent call last):
  File "/home/ubuntu/crtr/crypto_trading/user_scripts/samples/sandbox_for_async.py", line 67, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/crtr/crypto_trading/user_scripts/samples/sandbox_for_async.py", line 31, in main
    res2 = await exchange.fetch_order(id=oid, symbol='PURR/USDC:USDC')
  File "/home/ubuntu/crtr/.venv/lib/python3.10/site-packages/ccxt/async_support/hyperliquid.py", line 1718, in fetch_order
    response = await self.publicPostInfo(self.extend(request, params))
  File "/home/ubuntu/crtr/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 868, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/ubuntu/crtr/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 864, in fetch2
    raise e
  File "/home/ubuntu/crtr/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 855, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/crtr/.venv/lib/python3.10/site-packages/ccxt/async_support/base/exchange.py", line 255, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/home/ubuntu/crtr/.venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1680, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeError: hyperliquid POST https://api.hyperliquid.xyz/info 422 Unprocessable Entity Failed to deserialize the JSON body into the target type

```

**Comment by kjnh10** [comment]
@carlosmiei 
On your local env, fetchOrder is working?
Yesterday, in my env, it worked, but today the error occured.

**Comment by carlosmiei** [comment]
@kjnh10 Are you setting `walletAddress/privateKey` properly?

**Comment by carlosmiei** [comment]
@kjnh10  We don't have any document on our side regarding the authentication, but can you do `print(exchange.requiredCredentials)`  and check the required credentials for a particular exchange. Besides that you can check the code since it is open source to see how the signature is done. 


But what do you want to know specifically?

**Comment by kjnh10** [comment]
@carlosmiei 

Got it. Thank you very much. I’ve been looking directly at the code so far, but I thought having documentation would be convenient. For example, I wasn’t sure what to specify for 'walletAddress' this time either. For now, I’ll continue to refer to the code directly.

Anyway, thank you again!

**Comment by carlosmiei** [comment]
@kjnh10 No problem, we will take your suggestion into consideration because, yes with dexes might be tricker than regular exchanges that only require `apiKey/secret`

Btw, whenever we release a new exchange that uses a different authentication method, we try to highlight that in the announcement post, so you can follow that as well 🙂 

https://t.me/ccxt_announcements/59

**Comment by nikhil981228** [comment]
Hi @carlosmiei 
I have a question, anyone who knows please help
After placing limit order it gets filled after some time and I want to extract the fill price and "ccxt_obj.fetch_order(curr_order['id'])"
does not seems to return the filled price. Please let me know then how can I extract the fill price as it is important info.
Thanks

**Comment by nikhil981228** [comment]
{'info': {'order': {'coin': 'DOGE',
   'side': 'B',
   'limitPx': '0.33226',
   'sz': '0.0',
   'oid': '59968546452',
   'timestamp': '1735719184004',
   'triggerCondition': 'N/A',
   'isTrigger': False,
   'triggerPx': '0.0',
   'children': [],
   'isPositionTpsl': False,
   'reduceOnly': False,
   'orderType': 'Limit',
   'origSz': '47.0',
   'tif': 'Ioc',
   'cloid': None},
  'status': 'filled',
  'statusTimestamp': '1735719184004'},
 'id': '59968546452',
 'clientOrderId': None,
 'timestamp': 1735719184004,
 'datetime': '2025-01-01T08:13:04.004Z',
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'symbol': 'DOGE/USDC:USDC',
 'type': 'limit',
 'timeInForce': 'IOC',
 'postOnly': False,
 'reduceOnly': False,
 'side': 'buy',
 'price': 0.33226,
 'triggerPrice': None,
 'amount': 47.0,
 'cost': 15.61622,
 'average': None,
 'filled': 47.0,
 'remaining': 0.0,
 'status': 'closed',
 'fee': None,
 'trades': [],
 'fees': [],
 'stopPrice': None,
 'takeProfitPrice': None,
 'stopLossPrice': None}
 
 This is response example, 'price' is the limit price and 'average' should not be None 
 it should show the filled price

**Comment by kjnh10** [comment]
@carlosmiei 
I'm also wondering how to get filled price? is there any idea?
