### ISSUE TITLE
It suddenly doesn't work

### ISSUE THREAD

**Issue by chaedongyoon** [ccxt/ccxt#23063]
### Operating System

python

### CCXT Version

Name: ccxt Version: 4.3.59 Summary: A JavaScript / TypeScript / Python / C# / PHP cryptocurrency trading library with support for 100+ exchanges     Home-page: https://ccxt.com Author: Igor Kroitor

### Description

if sy == 1 : 
    exchange2 = ccxt.mexc({
        'apiKey': '',
        'secret': ''})

    currency2 = 'BTC'  
    amount2 = '0.5'    
    address2 = "ADDRESS"        

    result = exchange2.withdraw(currency2, amount2, address2, params={"network": "BEP20"})
    print(result)

Everything was working fine, but after upgrading ccxt, it suddenly doesn't work.

It even works fine on other computers.

error is bellow

PS C:\Users\CDY> & "C:/Program Files/Python311/python.exe" "e:/BTC withdraw.py"
Traceback (most recent call last):
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 651, in fetch
    response.raise_for_status()
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.mexc.com/api/v3/capital/withdraw?coin=BTC&address=&amount=&netWork=BNB%20Smart%20Chain%28BEP20%29&timestamp=1720742503848&recvWindow=5000&signature=

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\BTC withdraw.py", line 103, in <module>
    result = exchange2.withdraw(currency2, amount2, address2, params={"network": "BEP20"})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\mexc.py", line 4924, in withdraw
    response = self.spotPrivatePostCapitalWithdraw(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\types.py", line 35, in unbound_method      
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 3756, in request        
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 3752, in fetch2
    raise e
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 3743, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 667, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\mexc.py", line 5367, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], responseCode, feedback)
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 4138, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: mexc {"code":10232,"msg":"Coin is not exist","timestamp":1720742503865}

### Code

```
  

```

**Comment by sc0Vu** [comment]
@chaedongyoon Thanks for the report. It seems they changed the network id. We'll fix this asap.

**Comment by chaedongyoon** [comment]
> @chaedongyoon Thanks for the report. It seems they changed the network id. We'll fix this asap.

Is it fixed?

**Comment by chaedongyoon** [comment]
sorry It doesnt work now. in this time, I withdraw  XRP with BSC network

**Comment by carlosmiei** [comment]
Hello @chaedongyoon did you update your ccxt version?  Can you post a verbose log (omitting sensitive information) ?


enable verbose mode:
```Python
await exchange.load_markets()
exchange.verbose = True
```

**Comment by chaedongyoon** [comment]
> Hello @chaedongyoon did you update your ccxt version? Can you post a verbose log (omitting sensitive information) ?
> 
> enable verbose mode:
> 
> ```python
> await exchange.load_markets()
> exchange.verbose = True
> ```

Yes I update lateste but it doeset work too

so I had change my Cccxt to down grade
"pip install --upgrade ccxt==4.3.37 "
yes it does work well
very good
