### ISSUE TITLE
"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent

### ISSUE THREAD

**Issue by ahafh12** [ccxt/ccxt#23086]
### Operating System

window

### Programming Languages

Python

### CCXT Version

4.3.57

### Description

There is an error in tpsl order after short order

There is no error in long orders

the below is error code :

Traceback (most recent call last):
  File "D:\PYTHON312\Lib\site-packages\ccxt\base\exchange.py", line 651, in fetch
    response.raise_for_status()
  File "D:\PYTHON312\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pc\Desktop\시스템매매\merge.py", line 277, in <module>
    orders1 = binance.create_order(
  File "D:\PYTHON312\Lib\site-packages\ccxt\binance.py", line 5544, in create_order
    response = self.fapiPrivatePostOrder(request)
  File "D:\PYTHON312\Lib\site-packages\ccxt\base\types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "D:\PYTHON312\Lib\site-packages\ccxt\binance.py", line 10419, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "D:\PYTHON312\Lib\site-packages\ccxt\base\exchange.py", line 3752, in fetch2
    raise e
  File "D:\PYTHON312\Lib\site-packages\ccxt\base\exchange.py", line 3743, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\PYTHON312\Lib\site-packages\ccxt\base\exchange.py", line 667, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "D:\PYTHON312\Lib\site-packages\ccxt\binance.py", line 10387, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "D:\PYTHON312\Lib\site-packages\ccxt\base\exchange.py", line 4138, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or malformed."}

### Code

```
          elif state[-1] == 'short':# and pepe >= posiprice:
            order = binance.create_market_sell_order(
                symbol = '1000PEPE/USDT',
                amount = posiamt
                )
            print('SHORT!')
            side = 0
            amt = 0
            entryP = 0
            try:
                for posi1 in binance.fetch_positions():
                    side = posi1['side']
                    amt = posi1['info']['positionAmt']
                    entryP = posi1['entryPrice']
                    break
            except:
                time.sleep(0.5)
            order1 = binance.create_order(
                '1000PEPE/USDT', 'stop_market', 'buy', amt, None,
                {'stopPrice' : entryP * 1.0076,
                 'reduceOnly': True}
                )
            print('SL')
            order2 = binance.create_order(
                '1000PEPE/USDT', 'take_profit_market', 'buy', amt, None,
                {'stopPrice' : entryP * 0.99,
                 'reduceOnly': True}
                )
            print('TP')

```

**Comment by ahafh12** [comment]
amt -> -int(amt), so working good!
