### ISSUE TITLE
[OKX] websocket throws 1006 network error

### ISSUE THREAD

**Issue by yfeng997** [ccxt/ccxt#23249]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.0.88

### Description

OKX exchange throws 1006 Network Error after running watch_my_trades() for about 3 days. 

```
[dealer] 2024-07-24 20:07:01,505 Loop [monitor_trades((), {'exchange': <dealer.ccxt_lib.exchange.Exchange object at 0x7fb9a9f7d2e0>})] throws: 1006 
Traceback (most recent call last):
  File "/home/ubuntu/dev/dealer/dealer/async_util.py", line 39, in loop
    await async_func(
  File "/home/ubuntu/dev/dealer/dealer/strategy/strategy.py", line 243, in monitor_trades
    trades = await exchange.watch_my_trades(since=since)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dealer-Jojrf75e-py3.9/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dealer-Jojrf75e-py3.9/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dealer-Jojrf75e-py3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dealer-Jojrf75e-py3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/home/ubuntu/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/ubuntu/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dealer-Jojrf75e-py3.9/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/home/ubuntu/dev/dealer/dealer/ccxt_lib/exchange.py", line 118, in watch_my_trades
    trades = await self.exchange.watch_my_trades(symbol=symbol, since=since)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dealer-Jojrf75e-py3.9/lib/python3.9/site-packages/ccxt/pro/okx.py", line 727, in watch_my_trades
    orders = await self.subscribe('private', messageHash, channel, symbol, self.extend(request, params))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/dealer-Jojrf75e-py3.9/lib/python3.9/site-packages/ccxt/pro/okx.py", line 157, in subscribe
    return await self.watch(url, messageHash, request, messageHash)
ccxt.base.errors.NetworkError: 1006
```

My streaming setting for okx is
```
'streaming': {
      # okex does not support built-in ws protocol-level ping-pong
      # instead it requires a custom text-based ping-pong
      'ping': self.ping,
      'keepAlive': 18000,
  },
```

Thanks team for taking a look!

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @yfeng997 , it is normal for connections to maybe have an issue after several days. Do you have the watch functions wrapped in a try catch and a while true loop? So that it reconnects in case of any disconnect?

**Comment by kroitor** [comment]
Hello @yfeng997 👋

Closing this during a cleanup — as noted above, a `1006` after days of continuous streaming is an abnormal connection closure from the network/exchange side, not a ccxt bug: no websocket connection survives indefinitely (server maintenance, LB rotations, idle policies, transient network faults all terminate it eventually). The supported pattern for long-running consumers is a `while True` loop with `try/except` around the `watch_*` call — on error you simply continue, and the next call re-establishes the connection and resubscribes automatically. Judging by the traceback, the retries were handled by an outer `tenacity` wrapper that eventually re-raised instead of letting the loop re-enter the watch call.

If you ever see a reconnect *loop* that fails persistently on a recent version (i.e. re-entering `watch_my_trades` never recovers), that's worth a fresh issue with verbose output. Thanks for the report! 🙏
