### ISSUE TITLE
watchOrderBookForSymbols missing updates

### ISSUE THREAD

**Issue by jabranzahid-dev** [ccxt/ccxt#23251]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

 4.3.56

### Description

Hi,

ccxt ver : 4.3.56
python ver  Python 3.12.4 

I am subscribing to symbols on okx using watchOrderBookForSymbols and I have an issue with ccxt missing updates. It appear that ccxt is receiving and consuming all the updates but sometimes the updates are missed.

The following program subscribes to 'books' channel on okx and it will print the 'ccxt update : seqID/prevSeqID' of each update it has processed. So that means, each raw update will be followed by a ccxt update and once 2 updates are detected missing, it will exit. I have ran this program 
python missing_updates.py > terminal_output.txt
and within a few mins, the program will finish with 2 missing updates. Scroll to the end of terminal_output.txt and we can see 
missing updates details.

```exchange = ccxtpro.okx({})
btc_seqID = 0
missing = 0

async def exchange_loop():
    global  btc_seqID, missing
    while True:
            exchange.verbose = True
            orderbook = await exchange.watchOrderBookForSymbols(['BTC/USDT'], params='books')

            symbol = orderbook['symbol']
            if symbol == 'BTC/USDT':
                if orderbook['prevSeqID'] == btc_seqID:
                    missing_flag = 'not missing'
                else:
                    missing_flag = 'missing'
                    missing +=1
                    #    file.write('missing update')
                print('ccxt update: ', orderbook['seqID'], orderbook['prevSeqID'], missing_flag, missing, 'missed so far')
                if missing == 2:
                    print('2 missing updates detected, exiting....')
                    await exchange.close()
                    sys.exit()
                
            if symbol == 'BTC/USDT':
                btc_seqID = orderbook.get('seqID')

asyncio.run(exchange_loop())```

if you subscribe to more symbols, it will miss 2 updates quicker

 I have actually modified okx.py to include the seqID and prevSeqID received from the exchange in order to
troubleshoot the missing updates. I can provide the code changes if you need but its essentially just including the seqID and prevSeqID in the orderbook that was received from okx as per their documentation.
I suspected my trading logic is not using most up to date prices.
And now when I compare the raw update from exchange with what ccxt is showing, ccxt is indeed missing these updates somewhere. 
Each raw update should be followed by an update from ccxt
---------------------------------------------
Exchange update(verbose), seqID : 2 prevSeqID : 1
ccxt update: seqID : 2 prevSeqID : 1 , not missing
---------------------------------------------
Exchange update(verbose), seqID : 3 prevSeqID : 2
ccxt update: seqID : 3 prevSeqID : 2 , not missing
---------------------------------------------
Exchange update(verbose), seqID : 4 prevSeqID : 3
---------------------------------------------
Exchange update(verbose), seqID : 5 prevSeqID : 4
ccxt update: seqID : seqID : 5 prevSeqID : 4 missing update <<<<<<<
>>>> There is no ccxt update for seqID : 4 prevSeqID : 3

I understand there is checksum calculation being done in the background after each update is received from exchange to ensure consistency of updates but the output I get certainly has missing updates, from what I see in the test.

The current theory after our discussion on discord is, the order book is consuming all the updates, so the order book is correct, but the watch function might be skipping updates to the user, and there you see the skip.

thanks for your help !

### Code

```
  

```

**Comment by carlosmiei** [comment]
@jabranzahid-dev I was trying to run this snippet but some keys are not part of the orderbook (`prevSeqId/seqId`), usually only `nonce` is available in a unified way

**Comment by carlosmiei** [comment]
@carlosmiei One more question, do you think that this approach would be possible on your end? (https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-orderbooks-synchronized.py)

I think that instead of relying on the `watchOrderBook` return result, you could read the orderbook directly from the cache but of course that brings pros and cons.

**Comment by jabranzahid-dev** [comment]
> @jabranzahid-dev One more question, do you think that this approach would be possible on your end? (https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-orderbooks-synchronized.py)
> 
> I think that instead of relying on the `watchOrderBook` return result, you could read the orderbook directly from the cache but of course that brings pros and cons.

Sorry I am not sure if I understand, the approach you shared also uses `watch_order_book`, how is that different from what I was doing (other than that I am using `watchOrderBookForSymbols`)
Do you mean `watch_order_book` reads the orderbook from cache but `watchOrderBookForSymbols` doesn't ?

Thanks

**Comment by carlosmiei** [comment]
@jabranzahid-dev Sorry, I wasn't clear enough, the example uses `watch_order_book` but in this case we're interested in `watch_order_book_for_symbols` (they both work similarly, in fact, `watch_order_Book` internally calls` watch_order_book_for_symbols` in most implementations).


The thing is, I don't think the problem is related to the "adding updates to the cache" process but rather the speed of resolving and recreating the promises that makes `watch_order_book/for_symbols` return. That is why I was suggesting letting `watch_order_book_for_symbols` run in background and access the cache directly.

I just saw your update, saying this does not fix it, so please disregard this suggestion for now.

**Comment by jabranzahid-dev** [comment]
Right, ok, I will wait for further instructions, although I am still not sure how that approach accesses the cache directly or what you suggested.
If it helps, this is what I did to follow your suggestion (and it still misses updates)

```
orderbooks = {}

btc_seqID = 0
missing = 0

def handle_all_orderbooks(orderbooks):
    global  btc_seqID, missing
    for exchange_id, orderbooks_by_symbol in orderbooks.items():        
        for symbol in orderbooks_by_symbol.keys():
            if symbol == 'BTC/USDT':
                orderbook = orderbooks_by_symbol[symbol]
                print(ccxt.pro.Exchange.iso8601(orderbook['timestamp']), exchange_id, symbol, orderbook['asks'][0], orderbook['bids'][0], orderbook['seqID'], orderbook['prevSeqID'])

                symbol = orderbook['symbol']
                print(symbol)
                    
                if orderbook['prevSeqID'] == btc_seqID:
                    missing_flag = 'not missing'
                else:
                    missing_flag = 'missing'
                    missing +=1
                print('ccxt update: ', orderbook['seqID'], orderbook['prevSeqID'], missing_flag, missing, 'missed so far')                
            
                btc_seqID = orderbook['seqID']


async def symbol_loop(exchange, symbol):
    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol, params='books')
            orderbooks[exchange.id] = orderbooks.get(exchange.id, {})
            orderbooks[exchange.id][symbol] = orderbook
            handle_all_orderbooks(orderbooks)
        except Exception as e:
            print(str(e))
            break  # you can break just this one loop if it fails

async def exchange_loop(exchange_id, symbols):
    exchange = getattr(ccxt.pro, exchange_id)()
    loops = [symbol_loop(exchange, symbol) for symbol in symbols]
    await asyncio.gather(*loops)
    await exchange.close()

async def main():
    symbols = ['BTC/USDT']
    exchanges = {
        'okx': symbols,
        #'binance': symbols,
    }
    loops = [exchange_loop(exchange_id, symbols) for exchange_id, symbols in exchanges.items()]
    await asyncio.gather(*loops)

asyncio.run(main())
```

**Comment by carlosmiei** [comment]
@jabranzahid-dev in the suggested approach, you should not use the result of `watch_order_book_for_symbols` but rather access `exchange.orderbooks` directly in a fixed paced.

I'm sorry the example I posted does not illustrate that, I was suggesting something like this:

```Python
import ccxt.pro

async def handle_all_orderbooks(exchange):
    while True:
        for symbol, orderbook in exchange.orderbooks.items():
            orderbook.limit()
            if orderbook is not None and len(orderbook['asks']) > 0 and 'timestamp' in orderbook and orderbook['timestamp'] is not None:
                print(ccxt.pro.Exchange.iso8601(orderbook['timestamp']), symbol, orderbook['asks'][0], orderbook['bids'][0])
        await asyncio.sleep(0.1)


async def symbol_loop(exchange, symbol):
    while True:
        try:
            await exchange.watch_order_book(symbol)
        except Exception as e:
            print(str(e))
            break


async def exchange_loop(exchange_id, symbols):
    exchange = getattr(ccxt.pro, exchange_id)()
    loops = [handle_all_orderbooks(exchange)] + [symbol_loop(exchange, symbol) for symbol in symbols]
    await asyncio.gather(*loops)
    await exchange.close()

async def main():
    symbols = ['BTC/USDT', 'ETH/BTC']
    # symbols = []
    exchanges = {
        'okx': symbols + ['ETH/USDT'],
        'binance': symbols,
    }
    loops = [exchange_loop(exchange_id, symbols) for exchange_id, symbols in exchanges.items()]
    await asyncio.gather(*loops)


asyncio.run(main())
```

**Comment by jabranzahid-dev** [comment]
Thanks for clarifying, I just tried this (and added seqID, prevSeqID),
```
                print(ccxt.pro.Exchange.iso8601(orderbook['timestamp']), symbol, orderbook['asks'][0], orderbook['bids'][0], orderbook['seqID'], orderbook['prevSeqID'])
```

And now some updates are duplicated
```
2024-08-06T15:27:13.501Z BTC/USDT [56100.1, 0.10161] [56100.0, 0.21946049] 30241331497 30241331334
2024-08-06T15:27:13.601Z BTC/USDT [56100.1, 0.10161] [56100.0, 0.22036049] 30241331527 30241331497
2024-08-06T15:27:13.601Z BTC/USDT [56100.1, 0.10161] [56100.0, 0.22036049] 30241331527 30241331497 duplicate
2024-08-06T15:27:13.801Z BTC/USDT [56100.1, 0.03466] [56100.0, 0.38859564] 30241331714 30241331601
2024-08-06T15:27:13.901Z BTC/USDT [56100.1, 0.03016] [56100.0, 0.24609564] 30241331749 30241331714
2024-08-06T15:27:14.101Z BTC/USDT [56098.1, 0.05501] [56098.0, 0.33340145] 30241332441 30241332175
2024-08-06T15:27:14.201Z BTC/USDT [56098.1, 0.13871] [56098.0, 0.30942935] 30241332514 30241332441
2024-08-06T15:27:14.201Z BTC/USDT [56098.1, 0.13871] [56098.0, 0.30942935] 30241332514 30241332441 duplicate
2024-08-06T15:27:14.301Z BTC/USDT [56098.1, 0.02074] [56098.0, 0.30942935] 30241332601 30241332514
2024-08-06T15:27:14.401Z BTC/USDT [56104.0, 0.30899] [56103.9, 0.29796616] 30241332900 30241332601
```

**Comment by carlosmiei** [comment]
@jabranzahid-dev But that's "expected", because you're reading it at a fixed pace  (every x seconds) and not using an "event-driven" approach, that's one of the disadvantages of this approach.

**Comment by jabranzahid-dev** [comment]
Got it, I think in that case it will not work for me and I need event driven approach for updates.
I can actually handle duplicate updates on my side by simply discarding the update if the seqID is the same as SeqID for previous update but the problem this approach also has missing updates sometimes (I tested) which I think is also expected since I am essentially 'fetching orderbook from the cache' right ? and if there are two updates between my two 'fetches' then my program will see a missing update.
Any chance there can be a fix so I have a pure one-to-one update for each update received from the exchange (the updates shown in verbose output) ?

Thanks again for your help

**Comment by carlosmiei** [comment]
@jabranzahid-dev I see, right now the only alternative I see is to monkey patch the class and handle the raw updates on your end, but you would need to build and maintain the orderbook yourself (otherwise you only get snapshot + deltas)

Example:
```Python
class my_okx(ccxtpro.okx):
    def handle_order_book(self, client, message):
        print("got orderbook", message) # this is the raw update, first contains the snapshot then the deltas
        super().handle_order_book(client, message)
exchange = my_okx({})
````

Is this viable for you?

**Comment by carlosmiei** [comment]
@jabranzahid-dev Actually I think I found a hacky way of doing it, can you please edit the `handle_order_book` function inside `pro/okx.py` to `return orderbook` instead of `return message` and then do this?

```Python
class my_okx(ccxtpro.okx):
    def handle_order_book(self, client, message):
        res = super().handle_order_book(client, message)
        check_orderbook(res)
exchange = my_okx({})

btc_seqID = 0
missing = 0

def check_orderbook (orderbook):
    symbol = orderbook['symbol']
    if symbol == 'BTC/USDT':
        print('Current seqId:', orderbook['seqId'], 'prevSeqId:', orderbook['prevSeqId'])
        if orderbook['prevSeqId'] == btc_seqID:
            missing_flag = 'not missing'
        else:
            missing_flag = 'missing'
            missing +=1
            #    file.write('missing update')
        # print('ccxt update:  ', orderbook['seqId'], orderbook['prevSeqId'], missing_flag, missing, 'missed so far')
        if missing == 2:
            print('2 missing updates detected, exiting....')
            print('ccxt update:  ', orderbook['seqId'], orderbook['prevSeqId'], missing_flag, missing, 'missed so far')
            sys.exit()
    if symbol == 'BTC/USDT':
        btc_seqID = orderbook.get('seqId')

async def exchange_loop():
    global  btc_seqID, missing
    while True:
            orderbook = await exchange.watchOrderBookForSymbols(['BTC/USDT'], params='books')

asyncio.run(exchange_loop())
```

**Comment by jabranzahid-dev** [comment]
Right so if I get raw update as it is, it should be fine for me I think, I can parse the relevant information I need from the update.
So I amended the pro/okx.py as you suggested and ran the above code but it doesn't print anything for a while and then

```
Traceback (most recent call last):
  File "C:\Arb\live\OKX\missing updates issue\missing_updates4.py", line 36, in <module>
    asyncio.run(exchange_loop())
  File "C:\Users\jabra\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\jabra\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jabra\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Arb\live\OKX\missing updates issue\missing_updates4.py", line 34, in exchange_loop
    orderbook = await exchange.watchOrderBookForSymbols(['BTC/USDT'], params='books')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jabra\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\pro\okx.py", line 820, in watch_order_book_for_symbols
    orderbook = await self.watch_multiple(url, messageHashes, request, messageHashes)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jabra\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\async_support\base\ws\future.py", line 41, in callback
    f.result()
ccxt.base.errors.RequestTimeout: Connection to wss://ws.okx.com:8443/ws/v5/public timed out due to a ping-pong keepalive missing on time
okx requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022F1DFCB920>
[Finished in 76.9s]
```

**Comment by pcriadoperez** [comment]
Hi @jabranzahid-dev , I believe the issue might be related to how the ping is handled, as I see a timeout error when it fails.
However I have not been able to reproduce it yet consistently, so I can't say for sure. Can you see if calling `asyncio.run(client.send('ping'))` in the handle_order_book or seeting a smaller keepAlive `exchange['streaming']['keepAlive'] = 1000` fixes the issue for you?

**Comment by jabranzahid-dev** [comment]
Right, so I am not what went wrong there with pings and timeouts but when I ran the same program next day, it was working fine.
Coming back to the original issue of missing updates, the suggestion of using raw updates by Carlos seems to have worked for me and I am not seeing any missing updates. I will continue testing and get back to you guys next week.
Many thanks again !

**Comment by carlosmiei** [comment]
@jabranzahid-dev Just one small observation,  if you slightly edit `handle_order_book` as suggested to `return orderbook` instead of `return message` you get the unified orderbook instead of the raw update, which might be more convenient for you.

**Comment by jabranzahid-dev** [comment]
> @jabranzahid-dev Actually I think I found a hacky way of doing it, can you please edit the `handle_order_book` function inside `pro/okx.py` to `return orderbook` instead of `return message` and then do this?
> 
> ```python
> class my_okx(ccxtpro.okx):
>     def handle_order_book(self, client, message):
>         res = super().handle_order_book(client, message)
>         check_orderbook(res)
> exchange = my_okx({})

Hi, Sorry for the delay in getting back to you, I have been playing with it and although I don't see any missing updates but it doesn't seem to be scaling well. I need to subscribe to all (500 or so) symbols on okx and if the subscription is a lot of symbols, then the updates start getting delayed massively. 
When I receive an update from the exchange, I record it with the exchange timestamp and my local timestamp and calculate the difference, it seems my program starts introducing delay anywhere between 5 seconds to several mins (the longer the program run, the more delay is for the updates). Note, this delay is after taking into account latency & the time difference between my machine and exchange.
This delay has only started since I introduced the above custom class.

Any ideas how to fix this ? Thanks!

**Comment by carlosmiei** [comment]
@jabranzahid-dev I see, to try to mitigate the issue, do you think that it would be feasible to use n instances and subscribe 500/n symbols per instance?

**Comment by jabranzahid-dev** [comment]
Yes thats what I have in mind, if there is not an easy fix for this issue. The thing is, its hard to determine the optimal number of symbols per instance. Theoretically, any increase in the number of symbols per instance is resulting in small decrease in performance which is not ideal for what I am doing, and every millisecond counts. 

So lets say I have 25 instances for 500 symbols, i.e. 20 symbols per instance, the performance will be slightly worse than 1 symbol per instance, which is not what I am ideally looking for but I will still give it a go, I will try and max out the number of instances(connections?) I am allowed with the exchange and see.
But please see if there is a way to fix the underlying issue.

**Comment by jabranzahid-dev** [comment]
Hi, So I split into many instances and its been running fine ! No more delayed or missing updates.
I am now experiencing the same issue of missing updates in bitmart but the code in handle_order_book function seems to be a bit different, how do I implement the same solution for bitmart please ?
Thanks again for your help, much appreciated!

**Comment by jabranzahid-dev** [comment]
So I need to expand this to many other exchange but way of creating customer class doesn't seem to work with most other exchange like bybit, upbit, bitmart, ascendex etc because the the code inside handle_order_book function is quite different.
is there any way to expand this custom fix to all these exchanges ?
thanks

**Comment by jabranzahid-dev** [comment]
for bitmart I have managed to sort it by adding `return orderbook` under `handle_order_book` in bitmart.py which wasn't there before and created the custom class in my own program in the same way we did for okx and it seems to work fine. Going to try the same with other exchanges....

**Comment by jabranzahid-dev** [comment]
Ok that was my fluke by adding `return orderbook ` for bitmart as it had `client.resolve (orderbook, messageHashForMulti)` inside `handle_order_book` but I see now most exchanges have 
`client.resolve(orderbook, messageHash)` and this trick of just adding  `return orderbook `  doesn't work for these. please help

**Comment by pcriadoperez** [comment]
Hi @jabranzahid-dev, I'm sorry I didn't quite understand the error. When you say it doesn't work, you mean with the class above it does not return an orderbook? What exchange are you trying to implement?

**Comment by jabranzahid-dev** [comment]
Hi, the results are mixed with different exchanges, for example for bitstamp, asendex, gateio, it does not return the orderbook but it returns None
To be clear, this is what I am doing, I am adding `return orderbook` under the statement `client.resolve(orderbook, messageHash)` in `handle_order_book` function in <exchange>.py file and then following in my own program as discussed above
```
class my_okx(ccxtpro.<exchange name>):
    def handle_order_book(self, client, message):
        res = super().handle_order_book(client, message)
        check_orderbook(res)
exchange = my_okx({})

def check_orderbook(orderbook):
    print(orderbook)
```

However, for other exchanges like bybit and upbit, it works fine.

**Comment by kroitor** [comment]
🙏 @jabranzahid-dev — thank you for the seqID/prevSeqID instrumentation, that's the cleanest possible proof of a missed update (raw feed has it, ccxt-consumed stream doesn't).

Status: this matches a defect class we've now confirmed and fixed in the Go lane (https://github.com/ccxt/ccxt/pull/29719): an update resolved while the consumer is between `watch` calls could be dropped instead of retained, and multi-symbol subscriptions widen that window — more symbols, faster loss, exactly your observation. The Python client audit is next, and your seqID gap detector is the ideal acceptance test for it — yes please, share your okx.py modification here (or a PR), we'd like to fold seqID/prevSeqID exposure into the okx book payload properly so gap detection doesn't require patching.

One interim note: with `watchOrderBookForSymbols`, each returned book is the *current state* — a missed intermediate delta that's followed by later deltas self-heals in the book (OKX checksum guards corruption), so the practical impact is transient staleness rather than a permanently wrong book. Your trading-logic concern is still valid for latency-sensitive use, which is why the retention fix matters. We'll follow up here when the py-side fix lands. 🙏
