### ISSUE TITLE
bitget sign signature error 

### ISSUE THREAD

**Issue by limbusmine** [ccxt/ccxt#23258]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.3.67

### Description

I wrote a code to get my asset data from bitget using ccxt, and I made sure it worked well on Windows 10. However, if I write and run this program the same way on an Oracle cloud virtual server, I get the following error. The operating system of the Oracle virtual server is ubuntu 20.04.6 LTS and the python version is 3.8.10
>Traceback (most recent call last):
  File "arbitrage_trading.py", line 89, in <module>
    bg_s_bal = bitget.fetch_balance()
  File "/home/ubuntu/venv/myvenv/lib/python3.8/site-packages/ccxt/bitget.py", line 3353, in fetch_balance
    response = self.privateSpotGetV2SpotAccountAssets(self.extend(request, params))
  File "/home/ubuntu/venv/myvenv/lib/python3.8/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/ubuntu/venv/myvenv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3759, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/ubuntu/venv/myvenv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3755, in fetch2
    raise e
  File "/home/ubuntu/venv/myvenv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3746, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/venv/myvenv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 667, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ubuntu/venv/myvenv/lib/python3.8/site-packages/ccxt/bitget.py", line 8238, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/ubuntu/venv/myvenv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 4141, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: bitget {"code":"40009","msg":"sign signature error","requestTime":1722334251680,"data":null}

### Code

```
import ccxt
import config as conf

bitget = ccxt.bitget({
    'apiKey' : conf.G_API_KEY_BITGET,
    'secret' : conf.G_SECRET_KEY_BITGET,
    'password' : ''
})

bg_s_bal = bitget.fetch_balance()
bg_s_bal = float(bg_s_bal['USDT']['free'])
```

**Comment by carlosmiei** [comment]
Hello @limbusminm, are you sure that your APIKey/secret/etc  does not have any trailing spaces or something like that?

**Comment by carlosmiei** [comment]
@limbusmine Also python 3.8 is a bit outdated, is it possible to upgrade it to see if it makes a difference?

**Comment by limbusmine** [comment]
> @limbusmine또한 파이썬 3.8이 조금 오래되었는데, 차이가 나는지 확인하기 위해 업그레이드하는 것이 가능할까요?

I upgraded the Python version to 3.11.9, but I get the same error.

**Comment by limbusmine** [comment]
> 안녕하세요 @limbusminm, APIKey/비밀번호 등에 맨 뒤에 공백이나 그와 비슷한 것이 없는지 확인하셨나요?

In the original code, the password was not saved with the api key, so I deleted it and uploaded it.

**Comment by carlosmiei** [comment]
@limbusmine But you're populating the `password` field in your machine right? (password is mandatory for bitget)

**Comment by limbusmine** [comment]
> @limbusmine하지만 당신은 `password`당신의 머신에 필드를 채우고 있지 않나요? (bitget의 경우 비밀번호가 필수입니다)

I think I said something wrong. The original code has a password, and I deleted it only when I posted it here.

**Comment by carlosmiei** [comment]
@limbusmine I'm also running a similar unix-based setup and everythinh is working as expected here

**Comment by ttodua** [comment]
@limbusmine can you please mention, did you sort out the issue?

**Comment by autostat** [comment]
Hello !

I have the same issue on win11 (.net c# ccxt version 4.4.95).

```
var config = new Dictionary<string, object>
{
    {"apiKey", key.ApiKey},
    {"secret", key.Secret},
    {"password", key.Password}
};

var exchange = Exchange.DynamicallyCreateInstance("bitget", config);
```

I can **successfully** use following methods:

**exchange.FetchDepositAddress
exchange.CreateOrder
exchange.Withdraw
exchange.FetchBalance**

But I have error: 

{"code":"40009","msg":"sign signature error","requestTime":1755453539736,"data":null}

when use methods:

**exchange.FetchWithdrawals
exchange.FetchDeposits**

Can anyone know how to fix it ?

**Comment by carlosmiei** [comment]
@autostat can you please open a new issue?

**Comment by autostat** [comment]
[Created ](https://github.com/ccxt/ccxt/issues/27037)

**Comment by ttodua** [comment]
as new issue was created, closing this one.
