### ISSUE TITLE
testnet/sandbox mode on phemex seems not to work

### ISSUE THREAD

**Issue by egabosh** [ccxt/ccxt#23262]
### Operating System

Debian 12

### Programming Languages

Python

### CCXT Version

4.3.69

### Description

Moin,

trying to fetch orders in testnet/sandbox mode on phemex seems not to work. In "real" mode it works.
Only code difference is "exchange.set_sandbox_mode(True)"
Using same key/secret.

Error message:
```
Traceback (most recent call last):
  File "/ccxt/python/ccxt/base/exchange.py", line 549, in fetch
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://testnet-api.phemex.com/exchange/order/v2/orderList?symbol=BTCUSDT&currency=USDT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/fetch-orders.py", line 48, in <module>
    orders = exchange.fetch_orders('BTC/USDT:USDT')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/phemex.py", line 2863, in fetch_orders
    response = self.privateGetExchangeOrderV2OrderList(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 3972, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 3968, in fetch2
    raise e
  File "/ccxt/python/ccxt/base/exchange.py", line 3959, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 565, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/phemex.py", line 4497, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/ccxt/python/ccxt/base/exchange.py", line 4354, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: phemex {"code": "401","msg": "401 Failed to load API KEY."}

```
Any ideas whats going wrong?

Thank you!

### Code

```
import ccxt
exchange = ccxt.phemex({
    "apiKey": "XXXXXXXXXXXXXXXXX",
    "secret": "XXXXXXXXXXXXXXXXX",
    'options': {'defaultType': 'swap',},
    "enableRateLimit": False,
})
exchange.set_sandbox_mode(True)
orders = exchange.fetch_orders('BTC/USDT:USDT')
```

**Comment by egabosh** [comment]
Ah, sorry! My fault. Looks I need a separate account for this.
