### ISSUE TITLE
RequestTimeout: mexc POST https://contract.mexc.com/api/v1/private/order/submit

### ISSUE THREAD

**Issue by 8clever** [ccxt/ccxt#23320]
### Operating System

WSL2

### Programming Languages

Python

### CCXT Version

4.3.62

### Description

I have problem with MEXC exchange when placing SWAP order.
Request just timeouted.
I checked this error on different servers and on local machine, also on latest version of CCXT==4.3.73, it is does not fix my problem.
Orders with same code works well on other exchanges as Bybit, Kucoin etc.
Please help.

### Code

```
INFO:root:MARKET:MEXC Global - buy:XEM/USDT:USDT:0.02:98.00

fetch Request: mexc POST https://contract.mexc.com/api/v1/private/order/submit RequestHeaders: {'ApiKey': '***', 'Request-Time': '1722700202730', 'Content-Type': 'application/json', 'source': 'CCXT', 'Signature': '656add2977f6ff0a748bdbd029006c8e730556831423f4d0fa6162dac65d3d95', 'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate'} RequestBody: {"symbol":"XEM_USDT","vol":3967.0,"type":6,"openType":2,"side":1}
2024-08-03T15:50:04.851Z message {"symbol":"XEM_USDT","data":{"symbol":"XEM_USDT","lastPrice":0.0246,"riseFallRate":0.0040,"fairPrice":0.0246,"indexPrice":0.0247,"volume24":102343017,"amount24":2507849.1344,"maxBidPrice":0.0296,"minAskPrice":0.0197,"lower24Price":0.0234,"high24Price":0.0255,"timestamp":1722700207218,"bid1":0.0246,"ask1":0.0247,"holdVol":15112204,"riseFallValue":0.0001,"fundingRate":-0.00603,"zone":"UTC+8","riseFallRates":[0.0040,0.4385,0.7323,-0.3626,-0.3050,-0.1854],"riseFallRatesOfTimezone":[0.0123,0.0123,0.0040]},"channel":"push.ticker","ts":1722700207218}
2024-08-03T15:50:07.049Z message {"symbol":"XEM_USDT","data":{"symbol":"XEM_USDT","lastPrice":0.0246,"riseFallRate":0.0040,"fairPrice":0.0246,"indexPrice":0.0247,"volume24":102343017,"amount24":2507849.1344,"maxBidPrice":0.0296,"minAskPrice":0.0197,"lower24Price":0.0234,"high24Price":0.0255,"timestamp":1722700209222,"bid1":0.0246,"ask1":0.0247,"holdVol":15112204,"riseFallValue":0.0001,"fundingRate":-0.00603,"zone":"UTC+8","riseFallRates":[0.0040,0.4385,0.7323,-0.3626,-0.3050,-0.1854],"riseFallRatesOfTimezone":[0.0123,0.0123,0.0040]},"channel":"push.ticker","ts":1722700209222}
2024-08-03T15:50:09.268Z message {"symbol":"XEM_USDT","data":{"symbol":"XEM_USDT","lastPrice":0.0247,"riseFallRate":0.0081,"fairPrice":0.0246,"indexPrice":0.0247,"volume24":102343164,"amount24":2507852.7698,"maxBidPrice":0.0296,"minAskPrice":0.0197,"lower24Price":0.0234,"high24Price":0.0255,"timestamp":1722700212229,"bid1":0.0246,"ask1":0.0247,"holdVol":15112204,"riseFallValue":0.0002,"fundingRate":-0.00603,"zone":"UTC+8","riseFallRates":[0.0081,0.4444,0.7394,-0.3601,-0.3022,-0.1821],"riseFallRatesOfTimezone":[0.0164,0.0164,0.0081]},"channel":"push.ticker","ts":1722700212229}
2024-08-03T15:50:09.835Z sending {'method': 'ping'}
2024-08-03T15:50:10.050Z message {"channel":"pong","data":1722700213254,"ts":1722700213254}
2024-08-03T15:50:11.483Z message {"symbol":"XEM_USDT","data":{"symbol":"XEM_USDT","lastPrice":0.0247,"riseFallRate":0.0081,"fairPrice":0.0246,"indexPrice":0.0247,"volume24":102343164,"amount24":2507852.7698,"maxBidPrice":0.0296,"minAskPrice":0.0197,"lower24Price":0.0234,"high24Price":0.0255,"timestamp":1722700214219,"bid1":0.0246,"ask1":0.0247,"holdVol":15112204,"riseFallValue":0.0002,"fundingRate":-0.00603,"zone":"UTC+8","riseFallRates":[0.0081,0.4444,0.7394,-0.3601,-0.3022,-0.1821],"riseFallRatesOfTimezone":[0.0164,0.0164,0.0081]},"channel":"push.ticker","ts":1722700214219}
2024-08-03T15:50:13.098Z closing 1000
2024-08-03T15:50:13.099Z on_close 1000
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 199, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1344, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 675, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1009, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 702, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/com.docker.devenvironments.code/ex_crypto/actions.py", line 167, in <module>
    loop.run_until_complete(test_open_close_positions())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/com.docker.devenvironments.code/ex_crypto/actions.py", line 134, in test_open_close_positions
    await open_position(ex, symbol, 1)
  File "/com.docker.devenvironments.code/ex_crypto/actions.py", line 100, in open_position
    await ex.create_order(symbol, 'market', side, qty, None)
  File "/usr/local/lib/python3.9/site-packages/ccxt/async_support/mexc.py", line 2147, in create_order
    return await self.create_swap_order(market, type, side, amount, price, marginMode, query)
  File "/usr/local/lib/python3.9/site-packages/ccxt/async_support/mexc.py", line 2298, in create_swap_order
    response = await self.contractPrivatePostOrderSubmit(self.extend(request, params))
  File "/usr/local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 848, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
  File "/usr/local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 844, in fetch2
    raise e
  File "/usr/local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 835, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 233, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: mexc POST https://contract.mexc.com/api/v1/private/order/submit
```

**Comment by carlosmiei** [comment]
Hello @8clever,
Unfortunately Mexc disabled futures trading through the API more than 1 year ago.

**Comment by 8clever** [comment]
Ok. Thank you.

**Comment by melquiorz** [comment]
Is it still not possible to carry out futures via api on mexc?

**Comment by virtuman** [comment]
any updates on whether this might become re-activated any time soon? thank you

**Comment by carlosmiei** [comment]
@virtuman unfortunately we don't have any updates here

**Comment by passivewayout** [comment]
02:50:10 > ❌ Deploy error: mexc POST https://contract.mexc.com/api/v1/private/order/submit

same error for future auto trading bot


Any solution guys & Trading Gurus???
