### ISSUE TITLE
okcoincny RangeError: Invalid time value

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#2346]
Same Problem as in https://github.com/ccxt/ccxt/issues/2242

"RangeError: Invalid time value" in fetchTicker

**Comment by kroitor** [comment]
@Esc4pism can you please post the verbose output of it? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by Esc4pism** [comment]
heres the full Stack from the error thrown in ccxt

RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at okcoincny.Exchange.iso8601.timestamp [as iso8601] (..\ccxt\js\base\Exchange.js:178:117)
    at okcoincny.parseTicker (..\ccxt\js\okcoinusd.js:262:30)
    at okcoincny.fetchTicker (..\ccxt\js\okcoinusd.js:298:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)


Its just the same error again as back then in bleutrade, sometimes the timestamp in the ticker can be blank "" which throws an error in iso8601, this happens currently for the symbols BCH/CNY and ETC/CNY

**Comment by kroitor** [comment]
@Esc4pism no, not the stack, the verbose output...

```JavaScript
exchange.verbose = true
console.log (await exchange.fetchTicker (...))
```

Need to see their response...

**Comment by Esc4pism** [comment]
sorry misunderstood: http://textuploader.com/dg76m

I checked the response data in debugger and it seems to be not the same issue as in bleutrade, instead the response sometimes is just 'undefined' (or an empty Object?)

**Comment by Esc4pism** [comment]
https://www.okcoin.cn/api/v1/ticker.do?symbol=etc_cny

this returns empty {} too...

**Comment by kroitor** [comment]
Well if they respond with an empty reply there's little we can do apart from throwing an exception...

**Comment by kroitor** [comment]
OKCoinCNY has stopped trading due to PBoC regulation: https://www.okcoin.cn/t-2511348.html
We will probably remove it completely soon.
