### ISSUE TITLE
Bitmart Futures - watch_orders fails on KeyError

### ISSUE THREAD

**Issue by krasnyd** [ccxt/ccxt#23529]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.3.80

### Description

I am using the watch_orders function on Bitmart Futures and getting the `KeyError` when the CCXT tries to parse the order. New orders are parsed without a problem, but when I am closing an existing position, I get the following exception. I can try to make a more detailed example of this bug if you have trouble simulating it, but this error happens to me every time the close order is made.
```
Traceback (most recent call last):
  File "/opt/trading/L2/main_program/scripts/L2_script_v3.py", line 67, in main
    await self.watch_trades()
  File "/opt/trading/L2/main_program/scripts/L2_script_v3.py", line 90, in watch_trades
    await self.api.watch_trades()
  File "/opt/trading/L2/main_program/api/bitmart_api.py", line 64, in watch_trades
    return await self.ccxt_client.watch_orders(params={"type": "swap"})
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/pro/bitmart.py", line 354, in watch_orders
    await self.authenticate(type, params)
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/pro/bitmart.py", line 1318, in authenticate
    return await future
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/async_support/base/ws/fast_client.py", line 27, in handler
    self.handle_message(message)
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 34, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 29, in handle_text_or_binary_m>
    self.on_message_callback(self, decoded)
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/pro/bitmart.py", line 1450, in handle_message
    method(client, message)
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/pro/bitmart.py", line 443, in handle_orders
    order = self.parse_ws_order(orders[i])
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/pro/bitmart.py", line 558, in parse_ws_order
    return self.safe_order({
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2971, in safe_order
    trades = self.parse_trades(rawTrades, market)
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3898, in parse_trades
    trade = self.extend(self.parse_trade(trades[i], market), params)
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/async_support/bitmart.py", line 1604, in parse_trade
    timestamp = self.safe_integer_n(trade, ['createTime', 'create_time', 1])
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 782, in safe_integer_n
    value = Exchange.get_object_value_from_key_list(dictionary, key_list)
  File "/opt/trading/L2/env/lib/python3.10/site-packages/ccxt/base/exchange.py", line 828, in get_object_value_from_key_list
    if (key < len(dictionary_or_list)) and (dictionary_or_list[key] is not None) and (dictionary_or_list[key] != ''):
KeyError: 1
```

### Code

```python
await self.ccxt_client.watch_orders(params={"type": "swap"})

```

**Comment by sc0Vu** [comment]
Hi @krasnyd Thanks, we'll fix this asap.

**Comment by carlosmiei** [comment]
Hello @krasnyd, can you please upgrade your ccxt version and try again? I believe it should be working now but let us know if anything
