### ISSUE TITLE
hyperliquid unable to use/debug "set_margin_mode" and "set_leverage"

### ISSUE THREAD

**Issue by ggamer5555** [ccxt/ccxt#23666]
### Operating System

windows 10

### Programming Languages

Python

### CCXT Version

4.3.98

### Description

I'm trying to edit the margin mode and the leverage for the hyperliquid exchange and I would like any solutions as I have tried all of them I can think of using ccxt, hyperliquid SDK and the hyperliquid api. I could not get them to work.

I'm getting the error "An unexpected error occurred: (0, 32)" Does anyone know what this means? is it an error with json formatting to the api.

my API keys work as I can retrieve my balance and I have entered the correct symbol.

### Code

```
import ccxt  # Use the synchronous version of ccxt


def main():
    # Initialize the exchange
    exchange = ccxt.hyperliquid({
        'apiKey': api_key,
        'secret': secret,
        'walletAddress': wallet_address,
    })

    # Load markets
    exchange.load_markets()  # This should be synchronous

    # Print available markets
    markets = exchange.markets
    if markets is None:
        print("Failed to load markets")
    else:
        print("Available markets:", markets.keys())

    # Define the leverage you want to set
    leverage = 5
    symbol = 'BTC/USDC:USDC'  # Use the appropriate symbol format

    # Set leverage
    try:
        response = exchange.set_margin_mode('cross', symbol, {'leverage': leverage})
        print("Margin mode set successfully:", response)
    except ccxt.NetworkError as e:
        print("Network error:", str(e))
    except ccxt.ExchangeError as e:
        print("Exchange error:", str(e))
    except ccxt.BaseError as e:
        print("Base error:", str(e))
    except Exception as e:
        print("An unexpected error occurred:", str(e))

# Run the synchronous main function
main()

```

```
USDC: 59.84
Available markets: dict_keys(['PURR/USDC', 'HFUN/USDC', 'LICK/USDC', 'MANLET/USDC', 'JEFF/USDC', 'SIX/USDC', 'WAGMI/USDC', 'CAPPY/USDC', 'POINTS/USDC', 'TRUMP/USDC', 'GMEOW/USDC', 'PEPE/USDC', 'XULIAN/USDC', 'RUG/USDC', 'ILIENS/USDC', 'FUCKY/USDC', 'CZ/USDC', 'BAGS/USDC', 'ANSEM/USDC', 'TATE/USDC', 'PUMP/USDC', 'KOBE/USDC', 'HAPPY/USDC', 'SCHIZO/USDC', 'SELL/USDC', 'BIGBEN/USDC', 'CATNIP/USDC', 'HBOOST/USDC', 'SUCKY/USDC', 'GUP/USDC', 'FARMED/USDC', 'GPT/USDC', 'PURRPS/USDC', 'BID/USDC', 'HODL/USDC', 'VEGAS/USDC', 'ASI/USDC', 'VAPOR/USDC', 'PANDA/USDC', 'PILL/USDC', 'ADHD/USDC', 'FUN/USDC', 'LADY/USDC', 'MOG/USDC', 'HPEPE/USDC', 'JEET/USDC', 'DROP/USDC', 'MBAPPE/USDC', 'TEST/USDC', 'RAGE/USDC', 'FRAC/USDC', 'ATEHUN/USDC', 'COZY/USDC', 'ARI/USDC', 'WASH/USDC', 'ANT/USDC', 'NFT/USDC', 'RICH/USDC', 'LORA/USDC', 'CATBAL/USDC', 'TJIF/USDC', 'GUESS/USDC', 'MAXI/USDC', 'BTC/USDC:USDC', 'ETH/USDC:USDC', 'ATOM/USDC:USDC', 'MATIC/USDC:USDC', 'DYDX/USDC:USDC', 'SOL/USDC:USDC', 'AVAX/USDC:USDC', 'BNB/USDC:USDC', 'APE/USDC:USDC', 'OP/USDC:USDC', 'LTC/USDC:USDC', 'ARB/USDC:USDC', 'DOGE/USDC:USDC', 'INJ/USDC:USDC', 'SUI/USDC:USDC', 'kPEPE/USDC:USDC', 'CRV/USDC:USDC', 'LDO/USDC:USDC', 'LINK/USDC:USDC', 'STX/USDC:USDC', 'RNDR/USDC:USDC', 'CFX/USDC:USDC', 'FTM/USDC:USDC', 'GMX/USDC:USDC', 'SNX/USDC:USDC', 'XRP/USDC:USDC', 'BCH/USDC:USDC', 'APT/USDC:USDC', 'AAVE/USDC:USDC', 'COMP/USDC:USDC', 'MKR/USDC:USDC', 'WLD/USDC:USDC', 'FXS/USDC:USDC', 'HPOS/USDC:USDC', 'RLB/USDC:USDC', 'UNIBOT/USDC:USDC', 'YGG/USDC:USDC', 'TRX/USDC:USDC', 'kSHIB/USDC:USDC', 'UNI/USDC:USDC', 'SEI/USDC:USDC', 'RUNE/USDC:USDC', 'OX/USDC:USDC', 'FRIEND/USDC:USDC', 'SHIA/USDC:USDC', 'CYBER/USDC:USDC', 'ZRO/USDC:USDC', 'BLZ/USDC:USDC', 'DOT/USDC:USDC', 'BANANA/USDC:USDC', 'TRB/USDC:USDC', 'FTT/USDC:USDC', 'LOOM/USDC:USDC', 'OGN/USDC:USDC', 'RDNT/USDC:USDC', 'ARK/USDC:USDC', 'BNT/USDC:USDC', 'CANTO/USDC:USDC', 'REQ/USDC:USDC', 'BIGTIME/USDC:USDC', 'KAS/USDC:USDC', 'ORBS/USDC:USDC', 'BLUR/USDC:USDC', 'TIA/USDC:USDC', 'BSV/USDC:USDC', 'ADA/USDC:USDC', 'TON/USDC:USDC', 'MINA/USDC:USDC', 'POLYX/USDC:USDC', 'GAS/USDC:USDC', 'PENDLE/USDC:USDC', 'STG/USDC:USDC', 'FET/USDC:USDC', 'STRAX/USDC:USDC', 'NEAR/USDC:USDC', 'MEME/USDC:USDC', 'ORDI/USDC:USDC', 'BADGER/USDC:USDC', 'NEO/USDC:USDC', 'ZEN/USDC:USDC', 'FIL/USDC:USDC', 'PYTH/USDC:USDC', 'SUSHI/USDC:USDC', 'ILV/USDC:USDC', 'IMX/USDC:USDC', 'kBONK/USDC:USDC', 'GMT/USDC:USDC', 'SUPER/USDC:USDC', 'USTC/USDC:USDC', 'NFTI/USDC:USDC', 'JUP/USDC:USDC', 'kLUNC/USDC:USDC', 'RSR/USDC:USDC', 'GALA/USDC:USDC', 'JTO/USDC:USDC', 'NTRN/USDC:USDC', 'ACE/USDC:USDC', 'MAV/USDC:USDC', 'WIF/USDC:USDC', 'CAKE/USDC:USDC', 'PEOPLE/USDC:USDC', 'ENS/USDC:USDC', 'ETC/USDC:USDC', 'XAI/USDC:USDC', 'MANTA/USDC:USDC', 'UMA/USDC:USDC', 'ONDO/USDC:USDC', 'ALT/USDC:USDC', 'ZETA/USDC:USDC', 'DYM/USDC:USDC', 'MAVIA/USDC:USDC', 'W/USDC:USDC', 'PANDORA/USDC:USDC', 'STRK/USDC:USDC', 'PIXEL/USDC:USDC', 'AI/USDC:USDC', 'TAO/USDC:USDC', 'AR/USDC:USDC', 'MYRO/USDC:USDC', 'kFLOKI/USDC:USDC', 'BOME/USDC:USDC', 'ETHFI/USDC:USDC', 'ENA/USDC:USDC', 'MNT/USDC:USDC', 'TNSR/USDC:USDC', 'SAGA/USDC:USDC', 'MERL/USDC:USDC', 'HBAR/USDC:USDC', 'POPCAT/USDC:USDC', 'OMNI/USDC:USDC', 'EIGEN/USDC:USDC', 'REZ/USDC:USDC', 'NOT/USDC:USDC', 'TURBO/USDC:USDC', 'BRETT/USDC:USDC', 'IO/USDC:USDC', 'ZK/USDC:USDC', 'BLAST/USDC:USDC', 'LISTA/USDC:USDC', 'MEW/USDC:USDC', 'RENDER/USDC:USDC', 'kDOGS/USDC:USDC'])
An unexpected error occurred: (0, 32)
```

i get this more in-depth error on google colab

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-8-ca6579ed34a9>](https://localhost:8080/#) in <cell line: 1>()
----> 1 exchange.set_margin_mode('cross','BTC/USDC:USDC',{'leverage': 5})

5 frames
[/usr/local/lib/python3.10/dist-packages/ccxt/static_dependencies/ecdsa/keys.py](https://localhost:8080/#) in from_string(klass, string, curve, hashfunc)
    177     @classmethod
    178     def from_string(klass, string, curve=NIST192p, hashfunc=sha1):
--> 179         assert len(string) == curve.baselen, (len(string), curve.baselen)
    180         secexp = string_to_number(string)
    181         return klass.from_secret_exponent(secexp, curve, hashfunc)

AssertionError: (0, 32)
```

**Comment by carlosmiei** [comment]
setLeverage is also working on my end

```
 p hyperliquid setLeverage 6 "BTC/USDC:USDC"                            
Python v3.11.9
CCXT v4.3.97
hyperliquid.setLeverage(6,BTC/USDC:USDC)
{'response': {'type': 'default'}, 'status': 'ok'}
```

**Comment by ggamer5555** [comment]
> setLeverage is also working on my end
> 
> ```
>  p hyperliquid setLeverage 6 "BTC/USDC:USDC"                            
> Python v3.11.9
> CCXT v4.3.97
> hyperliquid.setLeverage(6,BTC/USDC:USDC)
> {'response': {'type': 'default'}, 'status': 'ok'}
> ```

am i dumb?  im using this simple version with no async   

```
import ccxt  # Use the synchronous version of ccxt

# Instantiate the Hyperliquid exchange
exchange = ccxt.hyperliquid({
    'apiKey': api_key,
    'secret': secret,
    'walletAddress': wallet_address,

})

symbol = 'BTC/USDC:USDC'
leverage = 2
params = {'marginMode': 'cross'}
response = exchange.set_leverage(symbol=symbol, leverage=leverage, params=params)
print("Leverage set successfully:", response)
```

```
  File "c:\Users\Ggjoj\OneDrive\hyperliquid ccxt\hyperliquid-python-sdk\examples\hyperliquid ccxt.py", line 194, in <module>
    response = exchange.set_leverage(symbol=symbol, leverage=leverage, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\hyperliquid.py", line 2261, in set_leverage
    signature = self.sign_l1_action(updateAction, nonce, vaultAddress)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\hyperliquid.py", line 1013, in sign_l1_action
    signature = self.sign_message(msg, self.privateKey)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\hyperliquid.py", line 951, in sign_message
    return self.sign_hash(self.hash_message(message), privateKey[-64:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\hyperliquid.py", line 943, in sign_hash
    signature = self.ecdsa(hash[-64:], privateKey[-64:], 'secp256k1', None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\base\exchange.py", line 1394, in ecdsa
    key = ecdsa.SigningKey.from_string(base64.b16decode(secret,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\static_dependencies\ecdsa\keys.py", line 179, in from_string
    assert len(string) == curve.baselen, (len(string), curve.baselen)
AssertionError: (0, 32)
```

**Comment by ggamer5555** [comment]
i have also tried on a separate window 10 pc and i have the same issues

**Comment by ggamer5555** [comment]
```
exchange.set_margin_mode('cross','BTC/USDC:USDC',{'leverage': 5})
```

```
  File "c:\Users\Ggjoj\OneDrive\hyperliquid ccxt\hyperliquid-python-sdk\examples\hyperliquid ccxt.py", line 199, in <module>
    exchange.set_margin_mode('cross','BTC/USDC:USDC',{'leverage': 5})
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\hyperliquid.py", line 2216, in set_margin_mode
    signature = self.sign_l1_action(updateAction, nonce, vaultAddress)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\hyperliquid.py", line 1013, in sign_l1_action
    signature = self.sign_message(msg, self.privateKey)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\hyperliquid.py", line 951, in sign_message
    return self.sign_hash(self.hash_message(message), privateKey[-64:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\hyperliquid.py", line 943, in sign_hash
    signature = self.ecdsa(hash[-64:], privateKey[-64:], 'secp256k1', None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\base\exchange.py", line 1394, in ecdsa
    key = ecdsa.SigningKey.from_string(base64.b16decode(secret,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ggjoj\miniconda3\Lib\site-packages\ccxt\static_dependencies\ecdsa\keys.py", line 179, in from_string
    assert len(string) == curve.baselen, (len(string), curve.baselen)
AssertionError: (0, 32)
```

**Comment by ggamer5555** [comment]
for the secret im using the secret from the initial API hyperliquid setup. the api_key is the API wallet address on hyperliquid that was created with the secret. the wallet address the wallet address of the hyperliquid account.  should I be including anything else in the setup?


```
# Instantiate the Hyperliquid exchange
exchange = ccxt.hyperliquid({
    'apiKey': api_key,
    'secret': secret,
    'walletAddress': wallet_address,

})
```

**Comment by ggamer5555** [comment]
> Hello @ggamer5555, hum weird, I just tested it and it worked
> 
> ```
> p hyperliquid setMarginMode "cross" "BTC/USDC:USDC"  '{"leverage": 5}'                 
> Python v3.11.9
> CCXT v4.3.97
> hyperliquid.setMarginMode(cross,BTC/USDC:USDC,{'leverage': 5})
> {'response': {'type': 'default'}, 'status': 'ok'}
> ```
> 
> Do you have positions currently opened using a different marginMode?

i dont have any orders or trades open live

**Comment by ggamer5555** [comment]
the issue was the inputs for the exchange wish i knew "requiredCredentials" was a thing 

```
# Instantiate the Hyperliquid exchange
exchange = ccxt.hyperliquid({
    'walletAddress': api_key,
    'privateKey': secret,
})

print(exchange.requiredCredentials)
```

this was incorrect 
```
    exchange = ccxt.hyperliquid({
        'apiKey': api_key,
        'secret': secret,
        'walletAddress': wallet_address,
    })
```
