### ISSUE TITLE
Error: self is not defined in Deno

### ISSUE THREAD

**Issue by vuau** [ccxt/ccxt#23692]
### Operating System

Debian

### Programming Languages

JavaScript

### CCXT Version

4.4.2

### Description

I ran the example from here https://github.com/ccxt/ccxt/blob/master/examples/js/binance-fetch-ohlcv-many-symbols-async-await.js
in Deno v1.46.3 and got this error:

```
error: Uncaught (in promise) ReferenceError: self is not defined
    at file:///home/au/.cache/deno/npm/registry.npmjs.org/ccxt/4.4.2/js/src/base/ws/WsClient.js:13:48
```

This error occurs starting from ccxt@4.3.21 because it works fine with ccxt@4.3.20. I think it might be related to this change: https://github.com/ccxt/ccxt/pull/22471

### Code

```
import ccxt from 'npm:ccxt@4.4.2';
console.log('CCXT Version:', ccxt.version)

async function symbolLoop (exchange, symbol, timeframe) {
    while (true) {
        try {
            const ohlcvs = await exchange.fetchOHLCV (symbol, timeframe)
            console.log (exchange.iso8601 (exchange.milliseconds ()), exchange.id, symbol, ohlcvs.length, 'OHLCV candles received')
            // await exchange.sleep (60 * 1000) // sleep if necessary, though not required
        } catch (e) {
            console.log (exchange.iso8601 (exchange.milliseconds ()), exchange.id, symbol, e.constructor.name, e.message)
        }
    }
}

async function main () {
    const exchange = new ccxt.binance ()
    await exchange.loadMarkets ()
    // exchange.verbose = true // uncomment for debugging purposes if necessary
    const symbols = [
        'BTC/USDT', // unified symbols used here as opposed to exchange-specific market ids
        'ETH/USDT', // more about unified symbols vs exchange-specific ids here:
        'ADA/USDT', // https://github.com/ccxt/ccxt/wiki/Manual#markets
    ]
    const timeframe = '1m'
    const loops = symbols.map (symbol => symbolLoop (exchange, symbol, timeframe))
    await Promise.all (loops)
}

main ()
```

**Comment by sc0Vu** [comment]
Hi @vuau, Thanks for the report. I'll take a look this issue.

**Comment by sc0Vu** [comment]
@vuau It works for me in 4.4.3. Can you upgrade and try it?

**Comment by vuau** [comment]
@sc0Vu same error occurs with ccxt@4.4.3

```
deno -A test.ts
error: Uncaught (in promise) ReferenceError: self is not defined
    at file:///home/au/.cache/deno/npm/registry.npmjs.org/ccxt/4.4.3/js/src/base/ws/WsClient.js:13:48
```

**Comment by sc0Vu** [comment]
@vuau You're right, it didn't work with npm module. As they mentioned in the comment https://github.com/denoland/deno/issues/24726#issuecomment-2264958966, Deno had followed the NodeJs behavior. So we shouldn't use `self.` after Deno 1.45.3.
