### ISSUE TITLE
Biance USA, error on startup

### ISSUE THREAD

**Issue by ronyrude** [ccxt/ccxt#23745]
### Operating System

ubuntu 24.04

### Programming Languages

Python

### CCXT Version

4.4.4

### Description

This is where it started and I was asked to contact CCXT

https://github.com/freqtrade/freqtrade/issues/10677

This is the output of last run
SORRY, MY FORMATTING NOT WORKING FOR UNKNOWN REASON

>>> import ccxt
>>>
>>> exchange = ccxt.binanceus({
...     'apiKey': 'MMMMMMY_KEY_REMOVED',
...     'secret': 'MY_SECRET_Removed',
... })
>>>
>>> _ = exchange.load_markets()
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/.venv/lib/python3.12/site-packages/ccxt/base/exchange.py", line 567, in fetch
    response.raise_for_status()
  File "/home/ubuntu/freqtrade/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: https://api.binance.us/sapi/v1/margin/allAssets?timestamp=1726681454890&recvWindow=10000&signature=a66fa58b9ee743dca5e62445a0783763a8db1dca5dfbf21c014d77c1584b40b6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/freqtrade/.venv/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1500, in load_markets
    currencies = self.fetch_currencies()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/.venv/lib/python3.12/site-packages/ccxt/binance.py", line 2653, in fetch_currencies
    promises = [self.sapiGetCapitalConfigGetall(params), self.sapiGetMarginAllAssets(params)]
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/.venv/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/.venv/lib/python3.12/site-packages/ccxt/binance.py", line 10763, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/.venv/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4065, in fetch2
    raise e
  File "/home/ubuntu/freqtrade/.venv/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4056, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/freqtrade/.venv/lib/python3.12/site-packages/ccxt/base/exchange.py", line 585, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/home/ubuntu/freqtrade/.venv/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1679, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: binanceus GET https://api.binance.us/sapi/v1/margin/allAssets?timestamp=1726681454890&recvWindow=10000&signature=a66fa58b9ee743dca5e62445a0783763a8db1dca5dfbf21c014d77c1584b40b6 404  {"timestamp":1726681455084,"status":404,"error":"Not Found","message":"No message available","path":"/sapi/v1/margin/allAssets"}
>>>

> 

"

### Code

```
  

```

**Comment by ronyrude** [comment]
I'm not an expert but the API documentation of Biance US does not match the urls produced by ccxt

**Comment by carlosmiei** [comment]
Hello @ronyrude, thanks a lot for reporting it, we will fix it asap, thank you

**Comment by carlosmiei** [comment]
@ronyrude Can you please upgrade your ccxt version and try again? It should be working now

**Comment by ronyrude** [comment]
Thank you for fixing, 4.4.5 seems to be working fine, I havent tried trades, but its logging in without issues
