### ISSUE TITLE
Close A Position In Phemex

### ISSUE THREAD

**Issue by majidt1984** [ccxt/ccxt#23778]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.15

### Description

Hi,
when i wrote this code to close position in Phemex :
```
  def closePosition(
    symbol=None,
    position=None,
):
    try:
        exchange.cancel_all_orders(symbol)

        amount = position["contracts"]
        side = position["side"]
        if side == "long":
            paramsOrder = {
                "reduceOnly": True,
                "hedged": True,
                "posSide": "Short",
            }
            exchange.create_order(
                symbol,
                type="market",
                side="sell",
                amount=amount,
                params=paramsOrder,
            )

        elif side == "short":
            paramsOrder = {
                "reduceOnly": True,
                "hedged": True,
                "posSide": "Long",
            }
            exchange.create_order(
                symbol,
                type="market",
                side="buy",
                amount=amount,
                params=paramsOrder,
            )
        logger.info(f"Closed position for {symbol}")
    except Exception as e:
        logger.error(f"Error closing position for {symbol}: {e}", exc_info=True)
        subject = f"Error closing position"
        body = f"Error closing position for {symbol}: {e}"
        send_email(subject, body)


position = fetchPositions(["TRXUSDT"])
# print(type(position["contracts"]))
symbol = "TRXUSDT"
closeposition = closePosition(symbol, position=position)
print(closeposition)

```
but got this error : 
```
2024-09-22 14:06:01,566 - INFO - Open position found for TRXUSDT
2024-09-22 14:06:02,177 - INFO - Fetched price for TRXUSDT: 0.15125
2024-09-22 14:06:04,915 - ERROR - Error closing position for TRXUSDT: phemex {"code":11011,"msg":"TE_REDUCE_ONLY_ABORT","data":null}
Traceback (most recent call last):
  File "g:\Py Project\Test Bot Final phemex\FinalMACDphemexseperate\orders.py", line 105, in closePosition
    exchange.create_order(
  File "G:\Py Project\.conda\lib\site-packages\ccxt\phemex.py", line 2509, in create_order
    response = self.privatePostGOrders(self.extend(request, params))
  File "G:\Py Project\.conda\lib\site-packages\ccxt\base\types.py", line 35, in unbound_method
  File "G:\Py Project\.conda\lib\site-packages\ccxt\base\exchange.py", line 3661, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "G:\Py Project\.conda\lib\site-packages\ccxt\base\exchange.py", line 3658, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "G:\Py Project\.conda\lib\site-packages\ccxt\base\exchange.py", line 677, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "G:\Py Project\.conda\lib\site-packages\ccxt\phemex.py", line 4402, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "G:\Py Project\.conda\lib\site-packages\ccxt\base\exchange.py", line 4055, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: phemex {"code":11011,"msg":"TE_REDUCE_ONLY_ABORT","data":null}
```
can u help me with this and how i can close a position in phemex?

### Code

```
2024-09-22 14:06:01,566 - INFO - Open position found for TRXUSDT
2024-09-22 14:06:02,177 - INFO - Fetched price for TRXUSDT: 0.15125
2024-09-22 14:06:04,915 - ERROR - Error closing position for TRXUSDT: phemex {"code":11011,"msg":"TE_REDUCE_ONLY_ABORT","data":null}
Traceback (most recent call last):
  File "g:\Py Project\Test Bot Final phemex\FinalMACDphemexseperate\orders.py", line 105, in closePosition
    exchange.create_order(
  File "G:\Py Project\.conda\lib\site-packages\ccxt\phemex.py", line 2509, in create_order
    response = self.privatePostGOrders(self.extend(request, params))
  File "G:\Py Project\.conda\lib\site-packages\ccxt\base\types.py", line 35, in unbound_method
  File "G:\Py Project\.conda\lib\site-packages\ccxt\base\exchange.py", line 3661, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "G:\Py Project\.conda\lib\site-packages\ccxt\base\exchange.py", line 3658, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "G:\Py Project\.conda\lib\site-packages\ccxt\base\exchange.py", line 677, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "G:\Py Project\.conda\lib\site-packages\ccxt\phemex.py", line 4402, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "G:\Py Project\.conda\lib\site-packages\ccxt\base\exchange.py", line 4055, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: phemex {"code":11011,"msg":"TE_REDUCE_ONLY_ABORT","data":null}
```

**Comment by majidt1984** [comment]
> Hello @majidt1984, in the `hedged` mode I don't think you need to provide `reduceOnly` because when you have 2 different legs (one with the long and one with the short), if you place a sell order targeting the `long` leg, it will always be a reduceOnly order.

no, in phemex you can have both long and short position at the same time

**Comment by carlosmiei** [comment]
@majidt1984 I know, that's the definition of hedged mode, and for that reason if you have to specify the "side" (long or short) your order will act on, you cannot place an opposite order that it is not a reduceOnly order.

**Comment by majidt1984** [comment]
> @majidt1984 I know, that's the definition of hedged mode, and for that reason if you have to specify the "side" (long or short) your order will act on, you cannot place an opposite order that it is not a reduceOnly order.

ok i try this code for closing my position but still get error :
```
for i in positions:
    side = i["side"]
    symbol1 = i["symbol"]
    amount = i["contracts"]
    if side == "long":

        exchange.create_order(
            symbol=symbol,
            side="sell",
            type="MARKET",
            amount=amount,
            params={
                "posSide": "LONG",
            },
        )

    elif side == "short":
        exchange.create_order(
            symbol=symbol,
            side="buy",
            type="MARKET",
            amount=amount,
            params={
                "posSide": "SHORT",
            },
        )

```
can u please correct the code , i am really confused.

**Comment by majidt1984** [comment]
ok i got it this work for phemex if anybody else have this problems : 

Closing a Position in Phemex with CCXT : 

```
exchange.load_markets()
symbol = "TRXUSDT"
positions = exchange.fetch_positions(symbols=[symbol])

for i in positions:
    side = i["side"]
    symbol1 = i["symbol"]
    amount = i["contracts"]
    if amount > 0:
        if side == "long":

            closePositionOrder = exchange.create_order(
                symbol=symbol1,
                side="sell",
                type="market",
                amount=amount,
                params={
                    "posSide": "Long",
                },
            )
        elif side == "short":
            closePositionOrder = exchange.create_order(
                symbol=symbol1,
                side="buy",
                type="market",
                amount=amount,
                params={
                    "posSide": "Short",
                },
            )
```

**Comment by carlotestor** [comment]
Thanks for posting the working Phemex close pattern.

In **hedged** mode you must target the position side explicitly (`posSide` / CCXT `side` of the position), not only flip buy/sell. Typical close:

```python
positions = exchange.fetch_positions([symbol])
pos = positions[0]
params = {'reduceOnly': True, 'hedged': True, 'posSide': pos['side']}  # long|short
side = 'sell' if pos['side'] == 'long' else 'buy'
exchange.create_order(symbol, 'market', side, pos['contracts'], None, params)
```

One-way mode is simpler (`reduceOnly` market opposite side). Since you already have a working snippet, this can be closed.
