### ISSUE TITLE
Bitmart create order fails Cannot convert [obj to a BigInt

### ISSUE THREAD

**Issue by shortthefomo** [ccxt/ccxt#23985]
### Programming Languages

JavaScript

### CCXT Version

4.4.18

### Description

create order is past these values iv tried with both a string and number, this Is using the exchange bitmart.
`createOrder('EVR_USDT', 'market', 'buy', 72.8621830441)`
`createOrder('EVR_USDT', 'market', 'buy', '72.8621830441')`

here is the stack trace to the issue some how BigInt is passed an object.

### Code

```
 errr SyntaxError: Cannot convert [obj to a BigInt
    at BigInt (<anonymous>)
    at new Precise (/Volumes/Dev/Web3/EXPERIMENTS/swap-backend/node_modules/ccxt/dist/cjs/src/base/Precise.js:21:28)
    at Precise.stringMul (/Volumes/Dev/Web3/EXPERIMENTS/swap-backend/node_modules/ccxt/dist/cjs/src/base/Precise.js:164:43)
    at bitmart.createSpotOrderRequest (/Volumes/Dev/Web3/EXPERIMENTS/swap-backend/node_modules/ccxt/dist/cjs/src/bitmart.js:2560:72)
    at bitmart.createOrder (/Volumes/Dev/Web3/EXPERIMENTS/swap-backend/node_modules/ccxt/dist/cjs/src/bitmart.js:2350:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 

```

**Comment by pcriadoperez** [comment]
hi @shortthefomo ,

I was not able to reproduce the error. Though the error seems because it's failing to convert either the amount of price to a BigInt.
Are you passing any other params to the function?
Are you passing in a cost or price?
Have you edited the option of `createMarketBuyOrderRequiresPrice`?

Also yes, you should pass the values as a number

**Comment by shortthefomo** [comment]
Hi @pcriadoperez 

nope im passing exactly as above.
<img width="757" alt="Screenshot 2024-10-14 at 6 14 30 PM" src="https://github.com/user-attachments/assets/607b4cf9-88cf-4007-90d0-8ccb4cf04837">

thanks for validating I should be passing the amount as a number.

**Comment by shortthefomo** [comment]
Thanks I will play around with that. The documentation says "the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders" 

I thought it would be ignored, thank you for your time. Ill close this once I have it working.

**Comment by shortthefomo** [comment]
works as @pcriadoperez described as soon as adding the price function works, possibly add that info to the documentation.
