### ISSUE TITLE
CoinEx errror: The endpoint has been deprecated

### ISSUE THREAD

**Issue by grozz97** [ccxt/ccxt#23990]
### Operating System

Ubuntu 22.04.4 LTS

### Programming Languages

PHP

### CCXT Version

4.3.5

### Description

2024-10-15 00:04:56,708 ERROR coinex **The endpoint has been deprecated. Please use the new version of this endpoint.**: Traceback (most recent call last):
  File ".../main.py", line 145, in handle_all_orderbooks
    start_order = await **coinex.create_limit_order**(symbol, start_side, amount, start_price)
  File "/usr/local/lib/python3.10/dist-packages/ccxt/async_support/base/exchange.py", line 1488, in create_limit_order
    return await self.create_order(symbol, 'limit', side, amount, price, params)
  File "/usr/local/lib/python3.10/dist-packages/ccxt/async_support/coinex.py", line 2226, in create_order
    response = await self.v1PrivatePostOrderLimit(request)
  File "/usr/local/lib/python3.10/dist-packages/ccxt/async_support/base/exchange.py", line 816, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
  File "/usr/local/lib/python3.10/dist-packages/ccxt/async_support/base/exchange.py", line 813, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.10/dist-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.10/dist-packages/ccxt/async_support/coinex.py", line 5373, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: coinex **The endpoint has been deprecated. Please use the new version of this endpoint.**

### Code

```
  

```

**Comment by grozz97** [comment]
Probably the problem is in the old version of CCXT?

**Comment by sc0Vu** [comment]
@grozz97 Can you upgrade ccxt and try?

**Comment by carlosmiei** [comment]
Hello @grozz97, correct that was updated in the meantime.

Can you please upgrade and try again?

**Comment by grozz97** [comment]
After the update everything works fine. Thank you.
