### ISSUE TITLE
Adding a proxy does not work in binance

### ISSUE THREAD

**Issue by tantaott** [ccxt/ccxt#24102]
### Operating System

windows

### CCXT Version

4.4.24

### Description

It works when I use version 1.72.1, but it doesn't work when I use version 4.4.24

Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\DELL\anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\DELL\anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\DELL\anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\DELL\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\DELL\anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\DELL\anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\DELL\anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 541, in fetch
    response = self.session.request(
  File "C:\Users\DELL\anaconda3\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\DELL\anaconda3\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\DELL\anaconda3\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b4f5d9f39b2a>", line 1, in <module>
    fb=exchange.fetch_balance()
  File "C:\Users\DELL\anaconda3\lib\site-packages\ccxt\binance.py", line 3455, in fetch_balance
    self.load_markets()
  File "C:\Users\DELL\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1500, in load_markets
    currencies = self.fetch_currencies()
  File "C:\Users\DELL\anaconda3\lib\site-packages\ccxt\binance.py", line 2696, in fetch_currencies
    promises = [self.sapiGetCapitalConfigGetall(params)]
  File "C:\Users\DELL\anaconda3\lib\site-packages\ccxt\base\types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "C:\Users\DELL\anaconda3\lib\site-packages\ccxt\binance.py", line 10931, in request
    response = self.fetch2(path, api, method, params, headers, body, config)
  File "C:\Users\DELL\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 4098, in fetch2
    raise e
  File "C:\Users\DELL\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 4089, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\DELL\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 594, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1730094968391&recvWindow=10000&signature=ceb940d42d7b0a3bbceff2db5e7fa0f5659c9b6a5144eca2eb

### Code

```
import    ccxt
import  time
api_key,api_secret=get_api_key11()
# 初始化Binance交易所
exchange=ccxt.binance({
'apiKey':api_key,
'secret':api_secret,
# 'enableRateLimit':True,
'options': {
        'defaultType': 'future',  
    }
})

exchange.httpProxy  = 'http://127.0.0.1:10809'
fb=exchange.fetch_balance()
```

**Comment by carlosmiei** [comment]
Hello @tantaott,

Can you try `httpsProxy` to see if it makes a difference?

**Comment by ttodua** [comment]
@tantaott  so, as @carlosmiei suggested, at first try `httpsProxy` and provide a follow-up, so we can tell something. also, I suspect it could be socks proxy (being tunneled) and if that's case, use
```
exchange.socksProxy  = 'socks://127.0.0.1:10809'
```

Other than that, our proxy implementations have been checked and they should be working as expected. 
Please let us know more details if you still experience an issue.
