### ISSUE TITLE
How can I get all orders, if the transaction does not support fetch_orders?

### ISSUE THREAD

**Issue by nashse** [ccxt/ccxt#2411]
- OS: win10
- Programming Language version: python3.6 
- CCXT version: ccxt-1.11.137
- Exchange: okex 、huobipro
- Method: fetch_orders

question:

> How can I get all orders, if the transaction does not support fetch_orders?

code:
```
exchange = ccxt.okex({
    'apiKey': OKEX_API_KEY,
    'secret': OKEX_SECRET,
})
markets = exchange.load_markets()
print(exchange.fetch_orders())
```
error:
```
Connected to pydev debugger (build 173.4674.37)
Traceback (most recent call last):
  File "E:\sorfware\PyCharm 2017.3.4\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "E:\sorfware\PyCharm 2017.3.4\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "E:\sorfware\PyCharm 2017.3.4\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\sorfware\PyCharm 2017.3.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/work/test/order_demo.py", line 16, in <module>
    print(exchange.fetch_orders())
  File "E:\sorfware\anaconda3.5\lib\site-packages\ccxt\okcoinusd.py", line 517, in fetch_orders
    raise ExchangeError(self.id + ' fetchOrders requires a symbol parameter')
ccxt.base.errors.ExchangeError: okex fetchOrders requires a symbol parameter

Process finished with exit code 1

```

**Comment by nashse** [comment]
I solved it.

code:
```
exchange = ccxt.okex({
    'apiKey': OKEX_API_KEY,
    'secret': OKEX_SECRET,
})
markets = exchange.load_markets()
print(exchange.fetch_orders(symbol=symbol, params={'status':1}))
```

result:

> [{'info': {'amount': 0.01, 'avg_price': 0.002091, 'create_date': 1522479934000, 'deal_amount': 0.01, 'order_id': 377074140, 'orders_id': 377074140, 'price': 0.1, 'status': 2, 'symbol': 'etc_btc', 'type': 'buy'}, 'id': '377074140', 'timestamp': 1522479934000, 'datetime': '2018-03-31T07:05:34.000Z', 'symbol': 'ETC/BTC', 'type': 'limit', 'side': 'buy', 'price': 0.1, 'average': 0.002091, 'cost': 2.091e-05, 'amount': 0.01, 'filled': 0.01, 'remaining': 0.0, 'status': 'closed', 'fee': None}, {'info': {'amount': 0.01, 'avg_price': 0.002095, 'create_date': 1522480145000, 'deal_amount': 0.01, 'order_id': 377077033, 'orders_id': 377077033, 'price': 0.01, 'status': 2, 'symbol': 'etc_btc', 'type': 'buy'}, 'id': '377077033', 'timestamp': 1522480145000, 'datetime': '2018-03-31T07:09:05.000Z', 'symbol': 'ETC/BTC', 'type': 'limit', 'side': 'buy', 'price': 0.01, 'average': 0.002095, 'cost': 2.095e-05, 'amount': 0.01, 'filled': 0.01, 'remaining': 0.0, 'status': 'closed', 'fee': None}, {'info': {'amount': 0.01, 'avg_price': 0, 'create_date': 1522480204000, 'deal_amount': 0, 'order_id': 377077772, 'orders_id': 377077772, 'price': 0.001, 'status': -1, 'symbol': 'etc_btc', 'type': 'buy'}, 'id': '377077772', 'timestamp': 1522480204000, 'datetime': '2018-03-31T07:10:04.000Z', 'symbol': 'ETC/BTC', 'type': 'limit', 'side': 'buy', 'price': 0.001, 'average': 0, 'cost': 0, 'amount': 0.01, 'filled': 0, 'remaining': 0.01, 'status': 'canceled', 'fee': None}]
