### ISSUE TITLE
Error: binance {"code":-1100,"msg":"Illegal characters found in parameter 'startTime'; legal range is '^[0-9]{1,20}$'."}

### ISSUE THREAD

**Issue by jeffryhartanto** [ccxt/ccxt#2415]
- OS: Windows 10
- Programming Language version: Javascript
- CCXT version: 1.12.50
- Exchange: Binance
- Method: fetchOHLCV

I execute the code below:
```
let symbol = 'SNT/ETH'
let tickers = await exchange.fetchOHLCV(symbol, '1m', '2018-03-31 00:00:00', 1);
```
then I got this error message:
```
Error: binance {"code":-1100,"msg":"Illegal characters found in parameter 'startTime'; legal range is '^[0-9]{1,20}$'."}
    at binance.handleErrors (C:\Users\Casper\node_modules\ccxt\js\binance.js:842:35)
    at response.text.then (C:\Users\Casper\node_modules\ccxt\js\base\Exchange.js:509:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
FYI, I don't get any problem when I use other exchanges. Any idea what is the issue?

**Comment by jeffryhartanto** [comment]
I just realized that the `since` parameter should be number. Though, it's weird that it doesn't thrown an exception when I pass a string.
