### ISSUE TITLE
fetchPositions: Does not fetch all existing positions on Bybit

### ISSUE THREAD

**Issue by jsilhan** [ccxt/ccxt#24159]
### Operating System

Fedora 38, Linux

### Programming Languages

Python

### CCXT Version

4.4.26

### Description

Hi,

when calling `fetchPositions` on Bybit while not specifying any symbol it shows just one position even though I have 3 opened positions on the exchange. On BitMEX it lists all correctly all my positions. `fetchPositionsHistory` method lists all trades within positions - I want the output to be agregated. Bybit should [support the listing of all the positions when no symbol given](https://bybit-exchange.github.io/docs/v5/position)

![Screenshot from 2024-11-03 16-52-35](https://github.com/user-attachments/assets/39da3ca9-f190-419c-a67a-ffe5fb2fe1c8)
It seems it lists just USDT perpetual future position and not USDC futures.

Is this expected behavior?

### Code

```python
        exchange = ccxt.bybit(
            {
                "apiKey": api_key,
                "secret": secret,
            }
        )
        exchange.load_markets()
        params = {"category": "linear"}
        positions = exchange.fetch_positions(params=params)
        # just one item: [{'info': {'symbol': 'LTCUSDT'... I would expect all positions
        positions = exchange.fetch_positions()
        # just one item: [{'info': {'symbol': 'LTCUSDT'... I would expect all positions
        positions = exchange.fetch_positions(symbols=["ETH/USDC:USDC-241227"])
        # correctly just one specified item: [{'info': {'symbol': 'ETH-27DEC24'...
```

**Comment by sc0Vu** [comment]
@jsilhan Yes, bybit supports the USDC positions in other api. You can call `fetchUsdcPositions` instead.

**Comment by jsilhan** [comment]
@sc0Vu thanks for the response. I haven't seen `fetch_usdc_positions` in `exchange.has` so I wasn't able to find the method. It's posible to call the method but it raises this error:
```
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.bybit.com/option/usdc/openapi/private/v1/query-position

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jsilhan/Projects/crypto-futures/asses_risk.py", line 167, in <module>
    positions = exchange.fetch_usdc_positions()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsilhan/.cache/pypoetry/virtualenvs/crypto-futures-U-j3Kg93-py3.12/lib/python3.12/site-packages/ccxt/bybit.py", line 6031, in fetch_usdc_positions
    response = self.privatePostOptionUsdcOpenapiPrivateV1QueryPosition(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsilhan/.cache/pypoetry/virtualenvs/crypto-futures-U-j3Kg93-py3.12/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsilhan/.cache/pypoetry/virtualenvs/crypto-futures-U-j3Kg93-py3.12/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4107, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsilhan/.cache/pypoetry/virtualenvs/crypto-futures-U-j3Kg93-py3.12/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4103, in fetch2
    raise e
  File "/home/jsilhan/.cache/pypoetry/virtualenvs/crypto-futures-U-j3Kg93-py3.12/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4094, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsilhan/.cache/pypoetry/virtualenvs/crypto-futures-U-j3Kg93-py3.12/lib/python3.12/site-packages/ccxt/base/exchange.py", line 586, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/home/jsilhan/.cache/pypoetry/virtualenvs/crypto-futures-U-j3Kg93-py3.12/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1680, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: bybit POST https://api.bybit.com/option/usdc/openapi/private/v1/query-position 404 Not Found
```
I haven't seen this URL in Bybit API and I don't think it should be related to "option" which is inside URL. I want positions of USDC marginated derivates but not specifically options but rather perpetuals.

Does the method work for you?

**Comment by jsilhan** [comment]
I have figured it out. `exchange.fetch_positions(params={"category": "linear", "settleCoin": "USDC"})` is needed to get the positions settled in USDC.
