### ISSUE TITLE
Indodax withdraw method

### ISSUE THREAD

**Issue by SilentMagic** [ccxt/ccxt#24167]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.4.25

### Description

i make a withdrawals with
**`indodax.withdraw(code='STRM', amount='2165.05767839', address='0x2b9A8cd5535D99b419aEfFBF1ae8D90a7eBdb24E', tag='')`**
and i got this error
`>>> asd = indodax.withdraw(code='STRM', amount='2165.05767839', address='0x2b9A8cd5535D99b419aEfFBF1ae8D90a7eBdb24E', tag='')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\indodax.py", line 1051, in withdraw
    response = self.privatePostWithdrawCoin(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 4102, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 4098, in fetch2
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 4089, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 611, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\indodax.py", line 1264, in handle_errors
    raise ExchangeError(self.id + ': malformed response: ' + self.json(response))
ccxt.base.errors.ExchangeError: indodax: malformed response: {"success":"1","status":"approved","withdraw_currency":"strm","withdraw_address":"0x2b9A8cd5535D99b419aEfFBF1ae8D90a7eBdb24E","withdraw_amount":"2165.05767839","fee":"21.11000000","amount_after_fee":"2143.94767839","submit_time":"1730759489","withdraw_id":"strm-3423","txid":""}`

**Comment by SilentMagic** [comment]
hii, i resolved this issue with adding
```
def handle_errors(self, code: int, reason: str, url: str, method: str, headers: dict, body: str, response, requestHeaders, requestBody):
        if response is None:
            return None
        # {success: 0, error: "invalid order."}
        # or
        # [{data, ...}, {...}, ...]
        if isinstance(response, list):
            return None  # public endpoints may return []-arrays
        error = self.safe_value(response, 'error', '')
        if not ('success' in response) and error == '':
            return None  # no 'success' property on public responses
        if self.safe_integer(response, 'success', 0) == 1:
            # {success: 1, return: {orders: []}}
            if not ('return' in response):
                **if ('withdraw_currency' in response):
                    return None**
                else:
                    raise ExchangeError(self.id + ': malformed response: ' + self.json(response))
            else:
                return None
        feedback = self.id + ' ' + body
        self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
        self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
        raise ExchangeError(feedback)  # unknown message
```
**if ('withdraw_currency' in response):
       return None**

**Comment by carlosmiei** [comment]
@SilentMagic Will update the rate limit value then. Thanks!

**Comment by SilentMagic** [comment]
@carlosmiei appreciate that 😊

**Comment by SilentMagic** [comment]
hi @carlosmiei this issue on new version of ccxt is not resolved well
```
Traceback (most recent call last):
  File "<stdin>", line 758, in update_execute_list
  File "<stdin>", line 648, in withdraw_async
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\indodax.py", line 1082, in withdraw
    response = self.privatePostWithdrawCoin(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 4125, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 4121, in fetch2
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 4112, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 612, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\indodax.py", line 1301, in handle_errors
    raise ExchangeError(self.id + ': malformed response: ' + self.json(response))
ccxt.base.errors.ExchangeError: indodax: malformed response: {"success":"1","status":"approved","withdraw_currency":"erg","withdraw_address":"9iMc5KyFmNghYFZbmTBYFGkgWmWP6QgKxpotngsdkxcAtKWuR6b","withdraw_amount":"21.90640000","fee":"0.21000000","amount_after_fee":"21.69640000","submit_time":"1731955947","withdraw_id":"erg-1776","txid":""}
```
