### ISSUE TITLE
Problem with function request in ccxt.bingx()

### ISSUE THREAD

**Issue by rmalvarezkai** [ccxt/ccxt#24171]
### Operating System

Debian 12.7

### Programming Languages

Python

### CCXT Version

4.4.26

### Description

Hello,
When I’m running this code in Python, I get the following error:
```
Traceback (most recent call last):
  File "/home/repository/github-repos/python/ccxao/develop_bingx.py", line 58, in <module>
    main(sys.argv[1:])
  File "/home/repository/github-repos/python/ccxao/develop_bingx.py", line 45, in main
    response = __api_client.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/repository/github-repos/python/ccxao/.venv/lib/python3.11/site-packages/ccxt/base/exchange.py", line 4107, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/repository/github-repos/python/ccxao/.venv/lib/python3.11/site-packages/ccxt/base/exchange.py", line 4084, in fetch2
    request = self.sign(path, api, method, params, headers, body)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/repository/github-repos/python/ccxao/.venv/lib/python3.11/site-packages/ccxt/bingx.py", line 5634, in sign
    url = self.implode_hostname(self.urls['api'][type])
                                ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'p'
```

After reviewing the source code, I noticed that in ccxt/bingx.py, the sign function expects the parameter section as a list but receives a string instead.

Thank you very much!

### Code

```
#!/usr/bin/python
import sys
import pprint # pylint: disable=unused-import
import ccxt # pylint: disable=unused-import

def main(argv):
    result = 0

    debug = False

    api_key = 'XXXXXXXXXXXXXXXXXXXXXXXX'

    api_secret = 'YYYYYYYYYYYYYYYYYYYYYYYY'

    ws_url = 'wss://open-api-ws.bingx.com/market?listenKey='

    __api_conn_data = {
        'apiKey': api_key,
        'secret': api_secret,
        'enableRateLimit': True,
        'verbose': debug,
        'options': {
            'defaultType': 'spot'
        }
    }

    __api_client = ccxt.bingx(__api_conn_data)

    __path = 'user/auth/userDataStream'
    __api = 'private'
    __method = 'POST'

    response = None

    response = __api_client.request(
        path=__path,
        api=__api,
        method=__method
    )

    pprint.pprint(response)

    print(f'ws_url: {ws_url}')

    return result

if __name__ == "__main__":
    main(sys.argv[1:])

```

**Comment by carlosmiei** [comment]
Hello @rmalvarezkai,

Why are you calling `.request` ? That's not how ccxt was meant to be used. If you want to call the userDatStream method you can do something like `client.userAuthPrivatePostUserDataStream()` 

You can check all available/callable endpoints here: https://github.com/ccxt/ccxt/blob/master/ts/src/abstract/bingx.ts

**Comment by rmalvarezkai** [comment]
Thanks @carlosmiei 
It work for me
