### ISSUE TITLE
ExchangeNotAvailable when using fetchTrades() on Huobi

### ISSUE THREAD

**Issue by JoshVarty** [ccxt/ccxt#2420]
- OS: Windows 10
- Programming Language version: Python 3.5
- CCXT version: `1.12.10`
- Exchange: Huobi
- Method: `fetchTrades()`

I am trying to use `fetchTrades()` to find all of the trades on Huobi executed over the last minute.

Below is a minimum repro for Python:

```Python
import ccxt
import time 

exchange = getattr(ccxt, "huobi")()

#exchange.apiKey = '' I have tried with and without API Key
#exchange.secret = '' I have tried with and without Secret
exchange.verbose = True

one_minute_Ago = int(time.time() * 1000) - 60000 
print(exchange.has['fetchTrades'])      #Prints True

pair = "BTC/CNY"
trades = exchange.fetch_trades(pair, since = one_minute_Ago)
```

Console Log:

```
Request: GET http://api.huobi.com/staticmarket/detail_btc_json.js {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'} None

Response: GET http://api.huobi.com/staticmarket/detail_btc_json.js 403 {'Content-Length': '162', 'Connection': 'keep-alive', 'Content-Type': 'text/html', 'X-Via-JSL': 'e57f9b2,-', 'Date': 'Sat, 31 Mar 2018 21:51:07 GMT', 'Set-Cookie': '__jsluid=84341119b6b88aba2bf7bd31d0349ac6; max-age=31536000; path=/; HttpOnly', 'X-Cache': 'bypass'} <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

Traceback (most recent call last):
  File "C:\Users\Josh\.conda\envs\josh\lib\site-packages\ccxt\base\exchange.py", line 358, in fetch
    response.raise_for_status()
  File "C:\Users\Josh\.conda\envs\josh\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://api.huobi.com/staticmarket/detail_btc_json.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\git\BitcoinStuff\BitcoinStuff\module1.py", line 15, in <module>
    trades = exchange.fetch_trades(pair, since = one_minute_Ago)
  File "C:\Users\Josh\.conda\envs\josh\lib\site-packages\ccxt\huobi.py", line 165, in fetch_trades
    }, params))
  File "C:\Users\Josh\.conda\envs\josh\lib\site-packages\ccxt\huobi.py", line 236, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Josh\.conda\envs\josh\lib\site-packages\ccxt\base\exchange.py", line 297, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Josh\.conda\envs\josh\lib\site-packages\ccxt\base\exchange.py", line 371, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "C:\Users\Josh\.conda\envs\josh\lib\site-packages\ccxt\base\exchange.py", line 400, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "C:\Users\Josh\.conda\envs\josh\lib\site-packages\ccxt\base\exchange.py", line 282, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: huobi http://api.huobi.com/staticmarket/detail_btc_json.js GET 403 Client Error: Forbidden for url: http://api.huobi.com/staticmarket/detail_btc_json.js <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

It appears to receive a `403` from `http://api.huobi.com/staticmarket/detail_btc_json.js`. I have confirmed that I can't navigate there in my browser either.

Perhaps the Huobi API has changed since this implementation? I was looking at their documentation (https://github.com/huobiapi/API_Docs_en/wiki/REST_Reference)  and it seems like we would want to be using something like `/market/history/` but I'm not very familiar with CCXT internals yet.

**Comment by JoshVarty** [comment]
Out of curiosity, what's the difference between Huobi and HuobiCNY? My understanding is that HuobiPro does not deal in fiat currencies, but I don't understand the distinction between Huobi and HuobiCNY.

When I try using HuobiCNY I see that the API tries to hit: https://be.huobi.com/v1/common/symbols however it times out. I can't visit that URL in my browser either as it just seems to hang.

**Comment by kroitor** [comment]
- Huobi is the implementation of Huobi v1 API, was used for Chinese Huobi websites, until PBoC regulation came out in October 2017
- HuobiCNY was a `.cn`-oriented domestic exchange, now shut down by PBoC (to be removed from ccxt soon)
- HuobiPRO is currenty the only remaining active v3 API for Huobi.

In short, you should use Huobi PRO. Hope it answers your question. Thx!
