### ISSUE TITLE
TE_TRIGGER_INVALID on phemex TakeProfit if LimitIfTouched instead of MarketIfTouched

### ISSUE THREAD

**Issue by egabosh** [ccxt/ccxt#24247]
### Operating System

Debian 12

### Programming Languages

Python

### CCXT Version

4.4.30

### Description

as described/discussed in telegram chat:
https://t.me/ccxt_chat/13204
https://t.me/ccxt_chat/13205
https://t.me/ccxt_chat/13276

I want to create an order with TakeProfit and StopLoss. TakeProfit as LimitIfTouched order instead of MarketIfTouched with:
```
exchange.createOrder(symbol='SOL/USDT:USDT', type='LimitIfTouched', price=333, amount=3, side='buy', params={'marginMode': 'isolated', 'stopLossPrice': '222', 'takeProfitPrice': '444', })
```
Thank you!

### Code

```
Traceback (most recent call last):
  File "/root/fetch-orders.py", line 118, in <module>
    exchange.createOrder(symbol='SOL/USDT:USDT', type='LimitIfTouched', price=333, amount=3, side='buy', params={'marginMode': 'isolated', 'stopLossPrice': '222', 'takeProfitPrice': '444', })
  File "/ccxt/python/ccxt/phemex.py", line 2573, in create_order
    response = self.privatePostGOrders(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 4125, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 4121, in fetch2
    raise e
  File "/ccxt/python/ccxt/base/exchange.py", line 4112, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 612, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/ccxt/python/ccxt/phemex.py", line 4587, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/ccxt/python/ccxt/base/exchange.py", line 4504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: phemex {"code":11038,"msg":"TE_TRIGGER_INVALID","data":null}
```

**Comment by ttodua** [comment]
Thanks for the report.
I'll investigate it and will post an update

**Comment by ttodua** [comment]
Fix is linked, once that PR gets merged, you will be able to use the unified approach:
https://docs.ccxt.com/#/README?id=stoploss-and-takeprofit-orders-attached-to-a-position

so, instead of `limit if touched` inside "type" you'd just run the method with unified arguments like: 
```
exchange.createOrder(symbol='SOL/USDT:USDT', type='limit', price=333, amount=3, side='buy', params=my_params)
```
where `my_params` would need to be like the linked example snippet
