### ISSUE TITLE
Gate.io withdrawal INVALID_PARAM_VALUE

### ISSUE THREAD

**Issue by SilentMagic** [ccxt/ccxt#24257]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.4.25

### Description

incorrect chain name for "NOT"

**>>> gateio.withdraw('NOT', '121.53525', 'EQCA1BI4QRZ8qYmskSRDzJmkucGodYRTZCf_b9hckjla6dZl', '1926384621')**

```
fetch Request: gateio POST https://api.gateio.ws/api/v4/withdrawals RequestHeaders: {'KEY': 'KEY HERE', 'Timestamp': '1731574641', 'SIGN': 'SIGN HERE', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Gate-Channel-Id': 'ccxt'} RequestBody: {"currency":"not","address":"EQCA1BI4QRZ8qYmskSRDzJmkucGodYRTZCf_b9hckjla6dZl","amount":"121.5352","memo":"1926384621","chain":"not"}

fetch Response: gateio POST https://api.gateio.ws/api/v4/withdrawals 400 ResponseHeaders: {'Date': 'Thu, 14 Nov 2024 08:57:22 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Frame-Options': 'SAMEORIGIN', 'X-Powered-By': 'CF ()', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache, must-revalidate', 'Set-Cookie': 'login_notice_check=%2F; path=/; secure; HttpOnly', 'X-Gate-RateLimit-Requests-Remain': '8', 'X-Gate-RateLimit-Limit': '10', 'X-Gate-RateLimit-Reset-Timestamp': '1731574642', 'X-Out-Time': '1731574642157083', 'X-In-Time': '1731574641953947'} ResponseBody: {"label":"INVALID_PARAM_VALUE","message":"Error: NOT invalid chain name"}
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 568, in fetch
    response.raise_for_status()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.gateio.ws/api/v4/withdrawals

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\gate.py", line 3560, in withdraw
    response = self.privateWithdrawalsPostWithdrawals(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 4125, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 4121, in fetch2
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 4112, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 584, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\gate.py", line 7419, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], label, feedback)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ccxt\base\exchange.py", line 4504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: gateio {"label":"INVALID_PARAM_VALUE","message":"Error: NOT invalid chain name"}
```
**>>> gateio.withdraw('NOT', '121.53525', 'EQCA1BI4QRZ8qYmskSRDzJmkucGodYRTZCf_b9hckjla6dZl', '1926384621', params={"chain": "ton"})**

```
fetch Request: gateio POST https://api.gateio.ws/api/v4/withdrawals RequestHeaders: {'KEY': 'KEY HERE', 'Timestamp': '1731574729', 'SIGN': 'SIGN HERE', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Gate-Channel-Id': 'ccxt'} RequestBody: {"currency":"not","address":"EQCA1BI4QRZ8qYmskSRDzJmkucGodYRTZCf_b9hckjla6dZl","amount":"121.5352","memo":"1926384621","chain":"ton"}

fetch Response: gateio POST https://api.gateio.ws/api/v4/withdrawals 400 ResponseHeaders: {'Date': 'Thu, 14 Nov 2024 08:58:49 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Frame-Options': 'SAMEORIGIN', 'X-Powered-By': 'CF ()', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache, must-revalidate', 'Set-Cookie': 'login_notice_check=%2F; path=/; secure; HttpOnly', 'X-Gate-RateLimit-Requests-Remain': '9', 'X-Gate-RateLimit-Limit': '10', 'X-Gate-RateLimit-Reset-Timestamp': '1731574729', 'X-Out-Time': '1731574729693818', 'X-In-Time': '1731574729565451'} ResponseBody: {"label":"INVALID_PARAM_VALUE","message":"Error: You don't have enough balance."}
```

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @SilentMagic,

You should be using `network:"TON"` (uppercase)

**Comment by SilentMagic** [comment]
hi @carlosmiei, it works too with lowercase, on second response, i got {"label":"INVALID_PARAM_VALUE","message":"Error: You don't have enough balance."}
that's mean `chain:"ton"` is valid ✌️

**Comment by SilentMagic** [comment]
@carlosmiei anyway, can you take a look on my issue before #24167 there's no update about this

**Comment by carlosmiei** [comment]
@SilentMagic 

> {"label":"INVALID_PARAM_VALUE","message":"Error: You don't have enough balance."} 

Are you sure you have enough balance to do it?

> @carlosmiei anyway, can you take a look on my issue before https://github.com/ccxt/ccxt/issues/24167 there's no update about this

Ok I will try to check it

**Comment by SilentMagic** [comment]
before i make a real withdrawals, i must try it with 0 balance first and make sure everything is right ✌️

**Comment by carlosmiei** [comment]
@SilentMagic So the gate.io issue is sorted out?

**Comment by SilentMagic** [comment]
@carlosmiei umm definitely yes, but i must add extra params {"chain"}
i tracking this error from the beginning how ccxt get that network chain on withdraw method
```
def withdraw(self, code: str, amount: float, address: str, tag=None, params={}):
        """
        make a withdrawal
        :see: https://www.gate.io/docs/developers/apiv4/en/#withdraw
        :param str code: unified currency code
        :param float amount: the amount to withdraw
        :param str address: the address to withdraw to
        :param str tag:
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `transaction structure <https://docs.ccxt.com/#/?id=transaction-structure>`
        """
        tag, params = self.handle_withdraw_tag_and_params(tag, params)
        self.check_address(address)
        self.load_markets()
        **currency = self.currency(code)**
        request: dict = {
            'currency': currency['id'],  # todo: currencies have network-junctions
            'address': address,
            'amount': self.currency_to_precision(code, amount),
        }
        if tag is not None:
            request['memo'] = tag
        networks = self.safe_value(self.options, 'networks', {})
        network = self.safe_string_upper(params, 'network')  # self line allows the user to specify either ERC20 or ETH
        network = self.safe_string_lower(networks, network, network)  # handle ETH>ERC20 alias
        if network is not None:
            request['chain'] = network
            params = self.omit(params, 'network')
        else:
            request['chain'] = currency['id']  # todo: currencies have network-junctions
        ....
```
most interesting part is _request['chain'] = currency['id']_, and i run command
```
>>> gateio.currency('NOT')
{'id': 'not', 'code': 'NOT', 'info': [{'currency': 'NOT', 'delisted': False, 'withdraw_disabled': False, 'withdraw_delayed': False, 'deposit_disabled': False, 'trade_disabled': False, 'chain': 'TON'}], 'name': None, 'active': True, 'deposit': True, 'withdraw': True, 'fee': None, 'fees': [], 'precision': 0.0001, 'limits': {'leverage': {'min': None, 'max': None}, 'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'networks': {'TON': {'info': {'currency': 'NOT', 'delisted': False, 'withdraw_disabled': False, 'withdraw_delayed': False, 'deposit_disabled': False, 'trade_disabled': False, 'chain': 'TON'}, 'id': 'TON', 'network': 'TON', 'currencyId': 'NOT', 'lowerCaseCurrencyId': 'not', 'deposit': True, 'withdraw': True, 'active': True, 'fee': None, 'precision': 0.0001, 'limits': {'amount': {'min': None, 'max': None}, 'withdraw': {'min': None, 'max': None}, 'deposit': {'min': None, 'max': None}}}}}
``` 
so if user didn't add extra param "chain", that chain will be request['chain'] = _currency['id']_

**Comment by carlosmiei** [comment]
@SilentMagic The unified syntax for the chain is `network` and we're already supporting it. Besides it, it's almost always required.
