### ISSUE TITLE
Paradex refresh token issue

### ISSUE THREAD

**Issue by birkir** [ccxt/ccxt#24259]
### Operating System

macos

### Programming Languages

JavaScript

### CCXT Version

4.4.27

### Description

I get errors when fetching balance after a while. I think the tokens need to be refreshed.

```json
{
  "type": "AuthenticationError",
  "message": "paradex GET https://api.prod.paradex.trade/v1/balance? 401 Unauthorized {\"message\":\"missing or malformed jwt: token is expired by 9.46872137s\"}\n",
  "name": "AuthenticationError"
}
```

### Code

```
      AuthenticationError: paradex GET https://api.prod.paradex.trade/v1/balance? 401 Unauthorized {"message":"missing or malformed jwt: token is expired by 9.46872137s"}

          at paradex.handleHttpStatusCode (node_modules/ccxt/dist/cjs/src/base/Exchange.js:835:19)
          at node_modules/ccxt/dist/cjs/src/base/Exchange.js:737:22
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
          at paradex.fetch2 (node_modules/ccxt/dist/cjs/src/base/Exchange.js:3929:24)
          at paradex.request (node_modules/ccxt/dist/cjs/src/base/Exchange.js:3949:16)
          at paradex.fetchBalance (node_modules/ccxt/dist/cjs/src/paradex.js:1551:26)

```

**Comment by birkir** [comment]
Fantastic. Thanks ❤️

**Comment by carlosmiei** [comment]
@birkir Can you please upgrade and try again? It should be working now
