### ISSUE TITLE
Coinbase Advanced API changes to withdraw ... http 400 error?

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#24333]
### Operating System

ubuntu and mac

### Programming Languages

Python

### CCXT Version

4.4.33, 4.4.31, 4.4.30

### Description

Need help with this error, not sure if ccxt or coinbase-specific exchange.  First I'm seeing it and have been using latest coinbase Advanced API keys for quite some time.  Tried multiple versions of ccxt last known working version 4.4.31.

Trying to withdraw via api, last worked on 11/17 no issues all params same and API keys in good order.   

### Code

```
withdrawal = source_exchange.withdraw(code=USDC, amount=10.0, address=0x##redacted##, tag=None, params={})
Traceback (most recent call last):
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 568, in fetch
    response.raise_for_status()
  File "/home/jtashiro/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError:  400 Client Error: **Bad Request for url:** https://api.coinbase.com/v2/accounts/##redacted#/transactions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./exchange-transfer.py", line 138, in <module>
    withdrawal = source_exchange.withdraw( code=code, amount=amount, address=deposit['address'], tag=deposit['tag'], params=params)
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 3739, in withdraw
    response = self.v2PrivatePostAccountsAccountIdTransactions(self.extend(request, params))
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 4125, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 4121, in fetch2
    raise e
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 4112, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 584, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 4569, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/jtashiro/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 4504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeError: coinbase {"errors":[{"id":"internal_server_error","message":"An internal error has occurred."}]}

  

```

**Comment by jtashiro** [comment]
Resolved:  withdraw (send_money) expect the  'amount' as a string, and I was posting a number ...
