### ISSUE TITLE
Kraken Futures - InsufficientFunds when the exchange is unavailable

### ISSUE THREAD

**Issue by krasnyd** [ccxt/ccxt#24338]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.4.29

### Description

CCXT returns exception `ccxt.base.errors.InsufficientFunds` when it receives `"error":"Unavailable"` from Kraken Futures API. Would it be possible to raise a more suitable exception?

### Code

```
2024-11-21 12:32:01,658 - ERROR - krakenfutures {"result":"error","error":"Unavailable","serverTime":"2024-11-21T11:32:01.634Z"}
Traceback (most recent call last):
  File "...", line 60, in main
    new_symbols = await self.fetch_position_symbols()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...", line 121, in fetch_position_symbols
    positions = await self.api.fetch_positions()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...", line 177, in fetch_positions
    positions = await self.ccxt_client.fetch_positions(params=self.private_endpoint_params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/ccxt_20241031/lib/python3.12/site-packages/ccxt/async_support/krakenfutures.py", line 2173, in fetch_positions
    response = await self.privateGetOpenpositions(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/ccxt_20241031/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 886, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/ccxt_20241031/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 882, in fetch2
    raise e
  File "/home/ubuntu/.conda/envs/ccxt_20241031/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 873, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/ccxt_20241031/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 254, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ubuntu/.conda/envs/ccxt_20241031/lib/python3.12/site-packages/ccxt/async_support/krakenfutures.py", line 2569, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], message, feedback)
  File "/home/ubuntu/.conda/envs/ccxt_20241031/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: krakenfutures {"result":"error","error":"Unavailable","serverTime":"2024-11-21T11:32:01.634Z"}

```

**Comment by sc0Vu** [comment]
@krasnyd Thanks, we'll update this asap.
