### ISSUE TITLE
fetchOpenOrders fails if an open order is a stop order in bitmex

### ISSUE THREAD

**Issue by GonzaloTunez** [ccxt/ccxt#2440]
- OS: Windows 10
- Programming Language version: Python 3.6.4
- CCXT version: 1.12.63
- Exchange: bitmex
- Method: fetchOpenOrders

```Python
cc_bitmex = ccxt.bitmex()
cc_bitmex.load_markets()

cc_bitmex.apiKey = "" #omitted
cc_bitmex.secret = ""

orders = cc_bitmex.fetchOpenOrders(symbol = 'BTC/USD')

```

```
Traceback (most recent call last):
  File "tests.py", line 22, in <module>
    orders = cc_bitmex.fetchOpenOrders(symbol = 'BTC/USD')
  File "C:\Users\Gonzalo\Miniconda3\lib\site-packages\ccxt\bitmex.py", line 241, in fetch_open_orders
    return self.fetch_orders(symbol, since, limit, self.extend(filter_params, params))
  File "C:\Users\Gonzalo\Miniconda3\lib\site-packages\ccxt\bitmex.py", line 237, in fetch_orders
    return self.parse_orders(response, market, since, limit)
  File "C:\Users\Gonzalo\Miniconda3\lib\site-packages\ccxt\base\exchange.py", line 1017, in parse_orders
    array = [self.parse_order(order, market) for order in array]
  File "C:\Users\Gonzalo\Miniconda3\lib\site-packages\ccxt\base\exchange.py", line 1017, in <listcomp>
    array = [self.parse_order(order, market) for order in array]
  File "C:\Users\Gonzalo\Miniconda3\lib\site-packages\ccxt\bitmex.py", line 383, in parse_order
    price = float(order['price'])
TypeError: float() argument must be a string or a number, not 'NoneType'
```

Stop orders are created without a price. This probably causes the issue

**Comment by kroitor** [comment]
Your version of ccxt is not 1.12.63 because

1. We don't have this line 383 there in parse_order (and this has been so for a long time already):
```
File "C:\Users\Gonzalo\Miniconda3\lib\site-packages\ccxt\bitmex.py", line 383, in parse_order
    price = float(order['price'])
```
Here's the link to line 383 in ccxt 1.12.63: https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitmex.py#L383
(↑ it's a completely different line). 

This tells that your `bitmex.py` is different from the one in ccxt 1.12.63. So, you should check your ccxt version first:

```Python
import ccxt
print(ccxt.__version__)
```

2. The actual line that does the price parsing is changed and is now line 404: https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitmex.py#L404
↑ It works whether there is price in the order or not (whatever the order type).

So, to me this looks like a version conflict. Can you verify that your runtime version is actually 1.12.63?
