### ISSUE TITLE
Can not create stoploss order for open position. (phemex)

### ISSUE THREAD

**Issue by egabosh** [ccxt/ccxt#24408]
### Operating System

Debian 12

### Programming Languages

Python

### CCXT Version

4.4.34

### Description

Can not create stoploss order for open position. (phemex)
Getting the following error:

```
Traceback (most recent call last):
  File "/root/fetch-orders.py", line 86, in <module>
    print(exchange.createOrder(symbol='ETH/USDT:USDT', type='Stop', side='sell', amount='0', price='None', params={'posSide': 'Long', 'stopPx': '3400', 'triggerDirection': 'up'}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/phemex.py", line 2608, in create_order
    response = self.privatePostGOrders(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 4236, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 4232, in fetch2
    raise e
  File "/ccxt/python/ccxt/base/exchange.py", line 4223, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccxt/python/ccxt/base/exchange.py", line 624, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/ccxt/python/ccxt/phemex.py", line 4666, in handle_errors
    raise ExchangeError(feedback)  # unknown message
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ccxt.base.errors.ExchangeError: phemex {"code":20004,"msg":"TE_ERR_INCONSISTENT_POS_MODE","data":null}
```
Order is created in OneWay Position Mode and position mode is successfully set with:
`exchange.setPositionMode(hedged=False, symbol='ETH/USDT:USDT'`

### Code

```
exchange.createOrder(symbol='ETH/USDT:USDT', type='Stop', side='sell', amount='0', price='None', params={'posSide': 'Long', 'stopPx': '3400', 'triggerDirection': 'down'
```

**Comment by carlosmiei** [comment]
@egabosh Thanks for reporting it, we will take a look shortly. cc/ @ttodua

**Comment by ttodua** [comment]
I'll post an update shortly

**Comment by egabosh** [comment]
thank you!

**Comment by ttodua** [comment]
question, do you use hedge mode?

**Comment by egabosh** [comment]
no

**Comment by egabosh** [comment]
Order is created in OneWay Position Mode and position mode is successfully set with:
`exchange.setPositionMode(hedged=False, symbol='ETH/USDT:USDT'`

**Comment by ttodua** [comment]
@egabosh can you please confirm, if the code you posted above is full? the `create_order` code line you posted, seems truncated from last part, please confirm.
