### ISSUE TITLE
Fatal error Uncaught ccxt PermissionDenied

### ISSUE THREAD

**Issue by akftes** [ccxt/ccxt#24483]
### Operating System

windows

### Programming Languages

PHP

### CCXT Version

latest

### Description

I Try to write a trader bot with CCXT library with PHP Language.

First attach

`require 'vendor/autoload.php';`
Then

`use ccxt\lbank;`
Continue I create an object Lbank in CCXT By follow code :
```

  date_default_timezone_set('UTC');
//var_dump (\ccxt\Exchange::$exchanges);
$lbank=new \ccxt\lbank();
$id = 'lbank';
$exchange = '\\ccxt\\' . $id;
$lbank_Exchange= new $exchange();
$exchange_id = 'lbank';
$exchange_class = "\\ccxt\\$exchange_id";
$exchange = new $exchange_class(array(
    'apiKey' => 'My api key',
    'secret' => 'My api secret',
));
```
Then load market and retrieve ask and bid and calcute market price By following code :

```
$markets=$exchange->loadMarkets();
$symbol = 'BTC/USDT';
$orderbook = $exchange->fetch_order_book ($symbol);
$bid = count ($orderbook['bids']) ? $orderbook['bids'][0][0] : null;
$ask = count ($orderbook['asks']) ? $orderbook['asks'][0][0] : null;
$marketprice = ($bid + $ask)/2;
print($marketprice);
```
load market and fetch order book is public method in CCXT . Then I try to use `fetch_balance ()` and` create_order ($symbol, $type, $side, $quantity, $price, $params) `method that is private method in CCXT in Following Code :

```
$bal= $exchange->fetch_balance ();
print_r($bal['free']);
echo "test";
//_____________________________ORDER________________________________
$price=NULL;
$price=$marketprice;
$params = array (
    
    // ...
);
$type = 'limit';
$side = 'buy'; 
$quantity=1;
$buy_order = $exchange->create_order ($symbol, $type, $side, $quantity, $price, $params);
        print_r ($buy_order);
```
After Then get Empty Array Output in fetch_balance () method and get Fatal Error in Output Of create_order `($symbol, $type, $side, $quantity, $price, $params); `Method.

OutPut :

```
99336.605 Array ( ) test
Fatal error: Uncaught ccxt\PermissionDenied: Invalid authorization in /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/lbank.php:2995 Stack trace: #0 /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/Exchange.php(1610): ccxt\lbank->handle_errors() #1 /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/Exchange.php(5168): ccxt\Exchange->fetch() #2 /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/Exchange.php(5188): ccxt\Exchange->fetch2() #3 /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/abstract/lbank.php(317): ccxt\Exchange->request() #4 /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/lbank.php(1500): ccxt\abstract\lbank->spotPrivatePostSupplementCreateOrder() #5 /home/robatixi/domains/robatix.ir/public_html/samplecallapi.php(63): ccxt\lbank->create_order() #6 {main} thrown in /home/robatixi/domains/robatix.ir/public_html/vendor/ccxt/ccxt/php/lbank.php on line 2995
```

### Code

```
  

```

**Comment by sc0Vu** [comment]
@akftes Can you check your api key permissions?

**Comment by akftes** [comment]
permission of my api is Trade,Withdraw,Read only,Futures,Transfer     
![Screenshot_2024-12-16_19-04-26](https://github.com/user-attachments/assets/e31ddb7e-d747-48e7-b97e-fa5d21c0a658)

**Comment by akftes** [comment]
@sc0Vu dont have idea?

**Comment by carlosmiei** [comment]
@akftes as you can see here, locally seems to be working:


```
 ph lbank fetchBalance                                      
PHP v8.4.3
CCXT version :4.4.72
lbank->fetchBalance()
Array
(
    [info] => Array
        (
            [result] => true
            [data] => Array
                (
                    [0] => Array
                        (
                            [usableAmt] => 10
                            [assetAmt] => 10
                            [networkList] => Array
                                (
                                    [0] => Array
                                        (
                                            [isDefault] => 
                                            [withdrawFeeRate] => 
                                            [name] => erc20
                                            [withdrawMin] => 1
                                            [minLimit] => 0.0001
                                            [minDeposit] => 5
                                            [feeAssetCode] => usdt
                                            [withdrawFee] => 10
                                            [type] => 1
                                            [coin] => usdt
                                            [network] => eth
                                        )

                                    [1] => Array
                                        (
```

are you using rsa or hmac?

**Comment by kroitor** [comment]
Hello @akftes, closing this during a cleanup — as shown above, `fetch_balance` works on lbank in a clean local run, and your key permissions looked correct, so this isn't a ccxt-side problem. We never got the actual error `fetch_balance` was throwing on your end (the original report cuts off before it), which is what would be needed to tell what differs in your setup.

Common culprits when public calls work but private ones fail with permissions otherwise fine: an IP whitelist attached to the API key, clock skew (sign/recvWindow errors), or the key belonging to a sub-account. If it still fails on a current version, please open a fresh issue with the exact exception message and a verbose log of the `fetch_balance` call. Thanks!
