### ISSUE TITLE
bitmex fetch_funding_rate, fetch_funding_rates, error

### ISSUE THREAD

**Issue by williamyizhu** [ccxt/ccxt#24543]
### Operating System

Ubuntu 22.04.5 LTS

### Programming Languages

Python

### CCXT Version

4.4.39

### Description

```
Traceback (most recent call last):
  File "/home/ubuntu/Documents/workspace/CryptoCTA/script/tg.py", line 9, in <module>
    print(cex.fetch_funding_rates(symbols=["BTC/USDT:USDT", "ETH/USDT:USDT"]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/workspace/CryptoCTA/.venv/lib/python3.12/site-packages/ccxt/bitmex.py", line 2508, in fetch_funding_rates
    result = self.parse_funding_rates(filteredResponse)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/workspace/CryptoCTA/.venv/lib/python3.12/site-packages/ccxt/base/exchange.py", line 5641, in parse_funding_rates
    parsed = self.parse_funding_rate(response[i], market)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/workspace/CryptoCTA/.venv/lib/python3.12/site-packages/ccxt/bitmex.py", line 2526, in parse_funding_rate
    'fundingTimestamp': self.parse_to_numeric(self.iso8601(fundingDatetime)),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/workspace/CryptoCTA/.venv/lib/python3.12/site-packages/ccxt/base/exchange.py", line 2716, in parse_to_numeric
    if stringVersion.find('.') >= 0:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
```

### Code

```
import ccxt

cex = ccxt.bitmex()

cex.load_markets()

cex.verbose = True

print(cex.fetch_funding_rates(symbols=["BTC/USDT:USDT", "ETH/USDT:USDT"]))

# print(cex.fetch_funding_rate(symbol="BTC/USDT:USDT"))


```

**Comment by carlosmiei** [comment]
fixes here: https://github.com/ccxt/ccxt/pull/24545

**Comment by carlosmiei** [comment]
@williamyizhu We will let you know as soon as we release a new version with the fix (in a few hours)

**Comment by carlosmiei** [comment]
@williamyizhu We just released a new version with the fix, can you upgrade and try again?

**Comment by williamyizhu** [comment]
It works now, thank you.
