### ISSUE TITLE
xt, load_markets(), "swap" symbols error, doesn't exist on xt.com

### ISSUE THREAD

**Issue by williamyizhu** [ccxt/ccxt#24566]
### Operating System

Ubuntu 22.04.5 LTS

### Programming Languages

Python

### CCXT Version

4.4.40

### Description

These symbols are labeled as "swap", but they are labeled incorrectly, e.g., 

xt doesn't have SHIB/USDT:USDT usdt-m or coin-m contract , it only has 1000SHIB/USDT:USDT, 

These are what I found so far, maybe more. 

PI/USDT:USDT
1000000PEIPEIUSDT/USDT:USDT
WLD/USD:WLD
DAN/USDT:USDT
CORE/USD:CORE
GALA/USD:GALA
COCOS/USDT:USDT
SHIB/USDT:USDT
FLU/USDT:USDT
GST/USDT:USDT
USDC/USDT:USDT
VET/USD:VET
BEAM/USDT:USDT
HNT/USDT:USDT
10000LADYS/USDT:USDT
DOME/USDT:USDT
ANC/USDT:USDT
1000MUMUUSDT/USDT:USDT
1000NFT/USDT:USDT

### Code

```
import ccxt

cex = ccxt.xt()

cex.load_markets()

cex.verbose = True

for k, v in cex.markets.items():
    if k == "PI/USDT:USDT" and v["type"] == "swap":
        print(v)
        print(cex.fetch_funding_rate(symbol=k))

```

**Comment by carlosmiei** [comment]
Hello @williamyizhu, hum I can see it on my end:

```
p xt market "SHIB/USDT:USDT"                         
Python v3.12.3
CCXT v4.4.40
xt.market(SHIB/USDT:USDT)
{'active': False,
 'base': 'SHIB',
 'baseId': 'shib',
 'contract': True,
 'contractSize': 1000.0,
 'created': None,
 'expiry': None,
 'expiryDatetime': None,
 'future': False,
 'id': 'shib_usdt',
 'index': None,
 'info': {'baseCoin': 'shib',
          'baseCoinDisplayPrecision': '9',
          'baseCoinPrecision': '9',
          'cnDesc': None,
          'cnName': 'SHIBUSDT',
          'cnRemark': None,
          'contractSize': '1000',
          'contractType': 'PERPETUAL',
          'deliveryCompletion': False,
          'deliveryDate': None,
          'deliveryPrice': None,
          'depthPrecisionMerge': '5',
          'enDesc': None,
          'enName': 'SHIBUSDT ',
          'enRemark': None,
          'fastTrackCallbackRate1': '0.01',
          'fastTrackCallbackRate2': '0.02',
          'id': '47',
          'initLeverage': '10',
          'initPositionType': 'CROSSED',
          'isDisplay': False,
          'isOpenApi': False,
          'labels': ['HOT'],
          'latestPriceDeviation': '0.0100',
          'liquidationFee': '0.01',
          'makerFee': '0.0004',
          'marketTakeBound': '0.1',
          'maxEntrusts': '200',
          'maxNotional': '2000000',
          'maxOpenOrders': '200',
          'maxPrice': None,
          'maxTrackCallbackRate': '0.1',
          'minNotional': '5',
          'minPrice': None,
          'minQty': '1',
          'minStepPrice': '0.000000001',
          'minTrackCallbackRate': '0.001',
          'multiplierDown': '0.1',
          'multiplierUp': '0.1',
          'onboardDate': '1657008001000',
          'openSwitch': False,
          'pair': 'shib_usdt',
          'plates': ['1'],
          'predictEventParam': None,
          'predictEventSort': None,
          'predictEventType': None,
          'pricePrecision': '9',
          'productType': 'perpetual',
          'quantityPrecision': '0',
          'quoteCoin': 'usdt',
          'quoteCoinDisplayPrecision': '4',
          'quoteCoinPrecision': '8',
          'spotCoin': 'shib',
          'state': '0',
          'supportEntrustType': 'TAKE_PROFIT,STOP,TAKE_PROFIT_MARKET,STOP_MARKET,TRAILING_STOP_MARKET',
          'supportOrderType': 'LIMIT,MARKET',
          'supportPositionType': 'CROSSED,ISOLATED',
          'supportTimeInForce': 'GTC,FOK,IOC,GTX',
          'symbol': 'shib_usdt',
          'symbolGroupId': '58',
          'takerFee': '0.0006',
          'tradeSwitch': False,
          'underlyingType': 'U_BASED'},
 'inverse': False,
 'limits': {'amount': {'max': None, 'min': 1.0},
            'cost': {'max': 2000000.0, 'min': 5.0},
            'leverage': {'max': None, 'min': 1.0},
            'price': {'max': None, 'min': None}},
 'linear': True,
 'lowercaseId': None,
 'maker': 0.0004,
 'margin': None,
 'marginModes': {'cross': None, 'isolated': None},
 'option': False,
 'optionType': None,
 'percentage': None,
 'precision': {'amount': 1.0,
               'base': 1e-09,
               'cost': None,
               'price': 1e-09,
               'quote': 1e-08},
 'quote': 'USDT',
 'quoteId': 'usdt',
 'settle': 'USDT',
 'settleId': 'shib',
 'spot': False,
 'strike': None,
 'subType': 'linear',
 'swap': True,
 'symbol': 'SHIB/USDT:USDT',
 'taker': 0.0006,
 'tierBased': None,
 'type': 'swap'}
```

**Comment by williamyizhu** [comment]
Error output


`
fetch Request: xt GET https://fapi.xt.com/future/market/v1/public/q/funding-rate?symbol=pi_usdt RequestHeaders: {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: xt GET https://fapi.xt.com/future/market/v1/public/q/funding-rate?symbol=pi_usdt 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Mon, 16 Dec 2024 09:49:56 GMT', 'api-method': 'GET', 'api-path': '/v1/public/q/funding-rate', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Requested-Tokens': '1', 'X-RateLimit-Burst-Capacity': '1', 'X-RateLimit-Replenish-Rate': '1', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 40320435ee6c0ba79ad788a52054783c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'NRT20-P6', 'X-Amz-Cf-Id': 'QZCyYbK3ExCYULWJ5mgBV-DWLxdqFJqqgluC-s5hOk4LmGtFWbS_eA=='} ResponseBody: {"returnCode":0,"msgInfo":"success","error":null,"result":{"symbol":"pi_usdt","fundingRate":null,"nextCollectionTime":null,"collectionInternal":null}}
Traceback (most recent call last):
  File "/home/ubuntu/Documents/workspace/CryptoCTA/script/_github_issue.py", line 12, in <module>
    print(cex.fetch_funding_rate(symbol=k))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/workspace/CryptoCTA/.venv/lib/python3.12/site-packages/ccxt/xt.py", line 4162, in fetch_funding_rate
    return self.parse_funding_rate(result, market)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/workspace/CryptoCTA/.venv/lib/python3.12/site-packages/ccxt/xt.py", line 4195, in parse_funding_rate
    'interval': interval + 'h',
                ~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
`

**Comment by williamyizhu** [comment]
on xt.com, it doesn't have this symbol

![3dfc8603fce7e8a11e0a8d5b2a95c04](https://github.com/user-attachments/assets/6ca9f7f4-7dd0-44b9-be37-78819398e1c3)

**Comment by carlosmiei** [comment]
@williamyizhu I checked and it, and although the UI does not show it, the API returns it but with active=False (probably it was active in the past but not anymore)

```
n xt market "SHIB/USDT:USDT"                                  
2024-12-16T10:19:15.658Z
Node.js: v18.18.0
CCXT v4.4.40
xt.market (SHIB/USDT:USDT)
2024-12-16T10:19:18.758Z iteration 0 passed in 0 ms

{
  id: 'shib_usdt',
  lowercaseId: undefined,
  symbol: 'SHIB/USDT:USDT',
  base: 'SHIB',
  quote: 'USDT',
  settle: 'USDT',
  baseId: 'shib',
  quoteId: 'usdt',
  settleId: 'shib',
  type: 'swap',
  spot: false,
  margin: undefined,
  swap: true,
  future: false,
  option: false,
  index: undefined,
  active: false,
  contract: true,
  linear: true,
  inverse: false,
  subType: 'linear',
  taker: 0.0006,
  maker: 0.0004,
  contractSize: 1000,
  expiry: undefined,
  expiryDatetime: undefined,
  strike: undefined,
  optionType: undefined,
  precision: { price: 1e-9, amount: 1, base: 1e-9, quote: 1e-8 },
  limits: {
    leverage: { min: 1, max: undefined },
    amount: { min: 1, max: undefined },
    price: { min: undefined, max: undefined },
    cost: { min: 5, max: 2000000 }
  },
  marginModes: { cross: undefined, isolated: undefined },
  created: undefined,
  info: {
}
  tierBased: undefined,
  percentage: undefined
}
```

**Comment by carlosmiei** [comment]
@williamyizhu I will fix fetchFundingRate to prevent a crash, but as you can see it returns a null response when the market is not active

```
fetch Request: xt GET https://fapi.xt.com/future/market/v1/public/q/funding-rate?symbol=shib_usdt RequestHeaders: {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: xt GET https://fapi.xt.com/future/market/v1/public/q/funding-rate?symbol=shib_usdt 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Mon, 16 Dec 2024 10:21:50 GMT', 'api-method': 'GET', 'api-path': '/v1/public/q/funding-rate', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Requested-Tokens': '1', 'X-RateLimit-Burst-Capacity': '1', 'X-RateLimit-Replenish-Rate': '1', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 65387a3a4aa9b7fc27436ee51ead063c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MRS52-C1', 'X-Amz-Cf-Id': '69EDdwpzxPRtY17DlGD3VgywoNba7Mtt7-Yfdy8bYBLDgHErAcsUNw=='} ResponseBody: {"returnCode":0,"msgInfo":"success","error":null,"result":{"symbol":"shib_usdt","fundingRate":null,"nextCollectionTime":null,"collectionInternal":null}}
```

**Comment by williamyizhu** [comment]
I see. I should check active=True before fetch_xxx. Thanks.

**Comment by carlosmiei** [comment]
@williamyizhu No problem, will close this issue but let us know if anything!
