### ISSUE TITLE
please help: proxy and ccxt.base.errors.RequestTimeout?

### ISSUE THREAD

**Issue by ydqsbfsyi** [ccxt/ccxt#24565]
### Operating System

windows

### Programming Languages

Python

### CCXT Version

4.4.40

### Description

newbie question please: 
with example code, it's working fine:
````
import asyncio
import os
import sys
import ccxt.async_support as ccxt

async def example():
    myex = ccxt.okx({})
    from_timestamp = myex.milliseconds() - 86400 * 1000  # last 24 hrs
    ohlcv = await myex.fetch_ohlcv('BTC-USDT-SWAP', '1m', from_timestamp, 3, {
        'whatever': 123,
    })
    length = len(ohlcv)
    if length > 0:
        last_price = ohlcv[length - 1][4]
        print('Fetched ', length, ' candles for ', myex.id, ':  last close ', last_price)
    else:
        print('No candles have been fetched')

    await myex.close()


asyncio.run(example())
````
Then I tried adding proxy, this time there seems a problem transmitting proxy params to okx?
````
import asyncio
import os
import sys
import ccxt.async_support as ccxt

proxies = {"http": "http://127.0.0.1:7081","https": "http://127.0.0.1:7081",}

async def example():
    myex = ccxt.okx({'proxies': proxies})
    from_timestamp = myex.milliseconds() - 86400 * 1000  # last 24 hrs
    ohlcv = await myex.fetch_ohlcv('BTC-USDT-SWAP', '1m', from_timestamp, 3, {
        'whatever': 123,
    })
    length = len(ohlcv)
    if length > 0:
        last_price = ohlcv[length - 1][4]
        print('Fetched ', length, ' candles for ', myex.id, ':  last close ', last_price)
    else:
        print('No candles have been fetched')

    await myex.close()


asyncio.run(example())
````
I got:
Traceback (most recent call last):
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 210, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "G:\Python\Python38\lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
  File "G:\Python\Python38\lib\site-packages\aiohttp\client.py", line 682, in _request
    break
  File "G:\Python\Python38\lib\site-packages\aiohttp\helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:/Python/okx/testccxt3.py", line 24, in <module>
    asyncio.run(example())
  File "G:\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "G:\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "g:/Python/okx/testccxt3.py", line 11, in example
    ohlcv = await myex.fetch_ohlcv('BTC-USDT-SWAP', '1m', from_timestamp, 3, {
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\okx.py", line 2355, in fetch_ohlcv
    await self.load_markets()
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 287, in load_markets
    raise e
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 283, in load_markets
    result = await self.markets_loading
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 273, in load_markets_helper
    markets = await self.fetch_markets(params)
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\okx.py", line 1517, in fetch_markets
    promises = await asyncio.gather(*promises)
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\okx.py", line 1681, in fetch_markets_by_type
    response = await self.publicGetPublicInstruments(self.extend(request, params))
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 886, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 882, in fetch2
    raise e
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 873, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "G:\Python\Python38\lib\site-packages\ccxt\async_support\base\exchange.py", line 244, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: okx GET https://www.okx.com/api/v5/public/instruments?instType=FUTURES
okx requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the
end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000000000652FBB0>

One more thing: I'm fetching data of "BTC-USDT-SWAP", but error message said "....../public/instruments?instType=FUTURES". I heard "Perpetual Futures replace Perpetual Swap", so basicly SWAP is in FUTURES type, right?  

Could anybody please enlighten me? something I missed?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @ydqsbfsyi. Can you try the unified way of using proxies by doing:
```
exchange.https_proxy = YOUR PROXY HERE
```

**Comment by ttodua** [comment]
@ydqsbfsyi you can also view other examples here: https://docs.ccxt.com/#/README?id=httpproxy-and-httpsproxy
also, side note, when using CCXT, we advise you used [unified symbol naming](https://docs.ccxt.com/#/README?id=contract-naming-conventions) (eg. BTC/USDT:USDT instead of `BTC-USDT-SWAP`)

**Comment by ydqsbfsyi** [comment]
> Hello @ydqsbfsyi. Can you try the unified way of using proxies by doing:
> 
> ```
> exchange.https_proxy = YOUR PROXY HERE
> ```

Thank you so much.

**Comment by ydqsbfsyi** [comment]
> @ydqsbfsyi you can also view other examples here: https://docs.ccxt.com/#/README?id=httpproxy-and-httpsproxy also, side note, when using CCXT, we advise you used [unified symbol naming](https://docs.ccxt.com/#/README?id=contract-naming-conventions) (eg. BTC/USDT:USDT instead of `BTC-USDT-SWAP`)

Much appreciated!
