### ISSUE TITLE
Kraken Limit Buy Order

### ISSUE THREAD

**Issue by vidur149** [ccxt/ccxt#2467]
- OS: Ubuntu 14.04
- Programming Language version: Javascript/Node
- CCXT version: 1.12.60
- Exchange: Kraken
- Method: createLimitBuyOrder

When I try and place a Limit Buy Order I get the following error message:

kraken {"error":["EGeneral:Invalid arguments:volume"]}

where order_volume = 16.77237171
order_entry_price = 0.00007182
What is the way to get rid of this error?

**Comment by kroitor** [comment]
Can you show your verbose output (without the keys), plz? 

> https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by vidur149** [comment]
error in ccxt limit buy Object.assign: kraken {"error":["EGeneral:Invalid arguments:volume"]}
    at kraken.handleErrors (/home/blackbeard/work/trailingcrypto/node_modules/ccxt/js/kraken.js:212:19)
    at response.text.then (/home/blackbeard/work/trailingcrypto/node_modules/ccxt/js/base/Exchange.js:509:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) InvalidOrder kraken {"error":["EGeneral:Invalid arguments:volume"]}

**Comment by kroitor** [comment]
@vidur149 sorry, but the above output does not tell me a lot about the reasons. Can you please read this carefully https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue and post a minimal snipper of your *code to reproduce the issue* and your *verbose output* of the request-response (set `{'verbose': true}` in exchange constructor)?

**Comment by vidur149** [comment]
Code Snippet 
```function limitBuy (user, order, callback) {
    let userExchange = initUserInstance(user, this);
    order.order_volume = adjustAmountPrecision.call(this, userExchange, order);
    userExchange.createLimitBuyOrder(
        formatPair(order.coin), //symbol:
        order.order_volume, //amount:
        order.entry_price || order.buy_price, //price:
        { 'timeInForce': order.timeInForce || 'IOC' }
    )
        .then(response => {
            console.log('ccxt limit buy', response );
                callback(null, response.id);
                updateOrderBook(order._id, {status: 'CLOSE', comment: 'Order Placed'});
            }
        })
        .catch(err => {
            console.log('error in ccxt limit buy', err, err.constructor.name, err.message);
            //todo retry if network failure
            updateOrderBook(order._id, {status: 'OPEN', comment: parseError(err.message)});
            callback(parseError(err.message));
        });
}```

**Comment by vidur149** [comment]
I have set `{verbose:trure}` and this is all the things that are getting logged in my console.
```
error in ccxt limit buy Object.assign: kraken {"error":["EGeneral:Invalid arguments:volume"]}
at kraken.handleErrors (/home/blackbeard/work/trailingcrypto/node_modules/ccxt/js/kraken.js:212:19)
at response.text.then (/home/blackbeard/work/trailingcrypto/node_modules/ccxt/js/base/Exchange.js:509:18)
at 
at process._tickCallback (internal/process/next_tick.js:160:7) InvalidOrder kraken {"error":["EGeneral:Invalid arguments:volume"]}

**Comment by kroitor** [comment]
Can you change it like so?

```JavaScript
    let userExchange = initUserInstance(user, this);
    order.order_volume = adjustAmountPrecision.call(this, userExchange, order);

    userExchange.verbose = true // ←---------------------- add this before createLimitBuyOrder

    userExchange.createLimitBuyOrder(
        formatPair(order.coin), //symbol:
        order.order_volume, //amount:
        order.entry_price || order.buy_price, //price:
        { 'timeInForce': order.timeInForce || 'IOC' }
    )
        .then(response => {
        ...
```

Does it still output nothing before the error like that?

**Comment by vidur149** [comment]
```
fetch:
 kraken POST https://api.kraken.com/0/private/AddOrder 
```

```
 kraken POST https://api.kraken.com/0/private/AddOrder 200 OK 
Response:
 {Date: "Thu, 05 Apr 2018 14:00:29 GMT", Content-Type: "application/json; charset=utf-8", Transfer-Encoding: "chunked", Connection: "close", Set-Cookie: "__cfduid=df4e330ea7005fcab1fd894a778b9be6815229368…4:00:28 GMT; path=/; domain=.kraken.com; HttpOnly", …}Cf-Ray: "406c8a8879122f05-DEL"Connection: "close"Content-Encoding: "gzip"Content-Type: "application/json; charset=utf-8"Date: "Thu, 05 Apr 2018 14:00:29 GMT"Expect-Ct: "max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct""Server: "cloudflare"Set-Cookie: "__cfduid=df4e330ea7005fcab1fd894a778b9be681522936828; expires=Fri, 05-Apr-19 14:00:28 GMT; path=/; domain=.kraken.com; HttpOnly"Transfer-Encoding: "chunked"Vary: "Accept-Encoding"__proto__: Object 
 {"error":["EGeneral:Invalid arguments:volume"]} 
```

**Comment by kroitor** [comment]
@vidur149 uhm.... I need both the request and the response ))) (without your keys)

**Comment by vidur149** [comment]
This is the request: 
```
fetch:
 kraken POST https://api.kraken.com/0/private/AddOrder 
Request:
 {API-Key: "", API-Sign: "", Content-Type: "application/x-www-form-urlencoded"}API-Key: ""API-Sign: ""Content-Type: "application/x-www-form-urlencoded"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__() 
 nonce=1522936828275&pair=XXRPXXBT&type=buy&ordertype=limit&volume=16.87574534&price=0.00007139&timeInForce=GTC 
```

This is the response
```handleRestResponse:
 kraken POST https://api.kraken.com/0/private/AddOrder 200 OK 
Response:
 {Date: "Thu, 05 Apr 2018 14:00:29 GMT", Content-Type: "application/json; charset=utf-8", Transfer-Encoding: "chunked", Connection: "close", Set-Cookie: "__cfduid=df4e330ea7005fcab1fd894a778b9be6815229368…4:00:28 GMT; path=/; domain=.kraken.com; HttpOnly", …}Cf-Ray: "406c8a8879122f05-DEL"Connection: "close"Content-Encoding: "gzip"Content-Type: "application/json; charset=utf-8"Date: "Thu, 05 Apr 2018 14:00:29 GMT"Expect-Ct: "max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct""Server: "cloudflare"Set-Cookie: "__cfduid=df4e330ea7005fcab1fd894a778b9be681522936828; expires=Fri, 05-Apr-19 14:00:28 GMT; path=/; domain=.kraken.com; HttpOnly"Transfer-Encoding: "chunked"Vary: "Accept-Encoding"__proto__: Object
```

**Comment by kroitor** [comment]
Your amount is too small for XRP, their minimal amount is 30 XRP:

```JavaScript
const ccxt = require ('./ccxt')
const kraken = new ccxt.kraken ()
const symbol = 'XRP/BTC'
;(async () => {
    await kraken.loadMarkets ()
    console.log (symbol, 'min amount is', kraken.markets[symbol]['limits']['amount']['min'])   
}) ()
```

↑ This is documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Let us know if the above does not answer your question. Thx!

**Comment by vidur149** [comment]
Thank you for your quick response :dango:
