### ISSUE TITLE
bitcoincom, watch_order_book, TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by williamyizhu** [ccxt/ccxt#24674]
### Operating System

Ubuntu 22.04.5 LTS

### Programming Languages

Python

### CCXT Version

4.4.43

### Description

`Traceback (most recent call last):
  File "/home/ubuntu/Documents/workspace/CryptoLiveData/test/_github_issue.py", line 26, in <module>
    asyncio.run(task())
  File "/opt/conda/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/workspace/CryptoLiveData/test/_github_issue.py", line 19, in task
    x = await cex.watch_order_book(symbol='BTC/USDT')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/workspace/CryptoLiveData/.venv/lib/python3.12/site-packages/ccxt/pro/hitbtc.py", line 228, in watch_order_book
    orderbook = await self.subscribe_public(name, 'orderbooks', [symbol], self.deep_extend(request, params))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/workspace/CryptoLiveData/.venv/lib/python3.12/site-packages/ccxt/pro/hitbtc.py", line 142, in subscribe_public
    url = self.urls['api']['ws']['public']
          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'`

### Code

```
import asyncio
import ccxt.async_support as ccxt
import ccxt.pro as ccxtpro

cex = ccxtpro.bitcoincom()

async def task():
    await cex.load_markets()

    while True:

        x = await cex.watch_order_book(symbol='BTC/USDT')

        print(x)

        await asyncio.sleep(1)


asyncio.run(task())

```

**Comment by carlosmiei** [comment]
Hello @williamyizhu,

thanks for reporting it, we will take a look asap.

**Comment by carlosmiei** [comment]
@williamyizhu I managed to reproduce the issue, working on a fix right now.

**Comment by carlosmiei** [comment]
@williamyizhu Can you please upgrade and try again?

**Comment by williamyizhu** [comment]
It works now, thanks.
