### ISSUE TITLE
Uncaught ccxt\RequestTimeout

### ISSUE THREAD

**Issue by jckling** [ccxt/ccxt#2473]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:Windows 10
- Programming Language version:PHP7.2.2
- CCXT version:1.12
- Exchange:okex, huobipro
- Method:load_markets()

```
Fatal error: Uncaught ccxt\RequestTimeout: okex GET https://www.okex.com/v2/markets/products.do 28 Connection timed out after 10000 milliseconds in D:\xampp\htdocs\B\New\vendor\ccxt\ccxt\php\Exchange.php:769 Stack trace: 
#0 D:\xampp\htdocs\B\New\vendor\ccxt\ccxt\php\Exchange.php(955): ccxt\Exchange->raise_error('RequestTimeout', 'https://www.oke...', 'GET', 28, 'Connection time...') 
#1 D:\xampp\htdocs\B\New\vendor\ccxt\ccxt\php\Exchange.php(794): ccxt\Exchange->fetch('https://www.oke...', 'GET', Array, NULL) 
#2 D:\xampp\htdocs\B\New\vendor\ccxt\ccxt\php\Exchange.php(798): ccxt\Exchange->fetch2('markets/product...', 'web', 'GET', Array, NULL, NULL) 
#3 [internal function]: ccxt\Exchange->request('markets/product...', 'web', 'GET', Array) 
#4 D:\xampp\htdocs\B\New\vendor\ccxt\ccxt\php\Exchange.php(733): call_user_func(Array, 'markets/product...', 'web', 'GET', Array) 
#5 [internal function]: ccxt\Exchange->ccxt\{closure}() 
#6 D:\xampp\htdocs\B\New\vendor\ccxt\ccxt\php\Exchange.php(1710): call_user_func_array(Object(Closure), A in D:\xampp\htdocs\B\New\vendor\ccxt\ccxt\php\Exchange.php on line 769
```

I have use VPN to access websites and I can use this code

```
$id = 'huobi';
	$exchange = '\\ccxt\\' . $id;
	$huobi = new $exchange ();
	$markets = $huobi->load_markets ();
	var_dump ($huobi->id, $markets);
```

the result is:

```
string(5) "huobi" array(2) { ["BTC/CNY"]=> array(8) { ["precision"]=> array(0) { } ["limits"]=> array(0) { } ["id"]=> string(3) "btc" ["symbol"]=> string(7) "BTC/CNY" ["base"]=> string(3) "BTC" ["quote"]=> string(3) "CNY" ["type"]=> string(12) "staticmarket" ["coinType"]=> int(1) } ["LTC/CNY"]=> array(8) { ["precision"]=> array(0) { } ["limits"]=> array(0) { } ["id"]=> string(3) "ltc" ["symbol"]=> string(7) "LTC/CNY" ["base"]=> string(3) "LTC" ["quote"]=> string(3) "CNY" ["type"]=> string(12) "staticmarket" ["coinType"]=> int(2) } }
```

but if i try

```
$id = 'huobipro';
	$exchange = '\\ccxt\\' . $id;
	$huobipro = new $exchange ();
	$markets = $huobipro->load_markets ();
	var_dump ($huobipro->id, $markets);
```

it will have  Uncaught ccxt\RequestTimeout
The same error occurs when I try to use apiKey&secret
And set timeout bigger have no use to this
I'm wondering if I have missing something in my environment?
Sorry for that I'm new in this and I don't know so much about english

**Comment by jckling** [comment]
When I set timeout to 20000 and use try...catch
it will throw exception like this

```
okex GET https://www.okex.com/v2/markets/products.do 7 Failed to connect to www.okex.com port 443: Timed out
```

**Comment by kroitor** [comment]
What's your version of ccxt?
```Python
import ccxt; print(ccxt.__version__)
```
?

**Comment by jckling** [comment]
I found it in changelog.md
the very first line
`Version 1.10.1 2017-11-06`

**Comment by kroitor** [comment]
Oops, sorry, please ignore my previous message, made a mistake. The changelog itself has an old version number. The actual version is in php/Exchange.php – can you check it?

**Comment by jckling** [comment]
Sorry, I'm not familiar with composer，but I'll try it later.
Thanks!!!!!
