### ISSUE TITLE
Bit-z: fetch_open_orders throws error

### ISSUE THREAD

**Issue by wntsang4** [ccxt/ccxt#2474]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.12.87
- Exchange: Bit-Z
- Method: fetch_open_orders()

After calling fetch_open_orders(), it throws below error
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

Request: POST https://www.bit-z.com/api_v1/openOrders {'Content-type': 'application/x-www-form-urlencoded', 'User-Agent': 'foobar', 'Accept-Encoding': 'gzip, deflate'} api_key=f6c93d1&coin=sphtx_btc&nonce=100001&timestamp=1523002157&sign=988dee

Response: POST https://www.bit-z.com/api_v1/openOrders 200 {'Date': 'Fri, 06 Apr 2018 08:09:22 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Set-Cookie': 'LANG=en; expires=Sat, 07-Apr-2018 08:09:33 GMT; Max-Age=86400; path=/, __jsluid=6ee0f709134d06f1bb90d82925b5b6ad; max-age=31536000; path=/; HttpOnly', 'X-Via-JSL': 'f700a73,-', 'X-Cache': 'bypass', 'Content-Encoding': 'gzip'} 

{"code":0,"msg":"Success","data":[{"id":"227202850","price":"0.00005000","number":"5.0000","numberover":"5.0000","flag":"sale","status":"0","datetime":"2018-04-06 16:09:21"},{"id":"227173638","price":"0.00002752","number":"200.0000","numberover":"200.0000","flag":"buy","status":"0","datetime":"2018-04-06 15:55:45"}]}

Code:
orders = bitz.fetch_open_orders('SPHTX/BTC')

**Comment by wntsang4** [comment]
It throws another exception.



Traceback (most recent call last):
  File "C:\Users\Nam\Desktop\python\test.py", line 66, in <module>
    print (exchange.fetch_open_orders('SPHTX/BTC'))
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitz.py", line 351, in fetch_open_orders
    return self.parse_orders(response['data'], market, since, limit)
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 1103, in parse_orders
    array = [self.parse_order(order, market) for order in array]
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 1103, in <listcomp>
    array = [self.parse_order(order, market) for order in array]
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitz.py", line 296, in parse_order
    timestamp = self.parse8601(order, 'datetime')
TypeError: parse8601() takes 1 positional argument but 2 were given

code:
print (bitz.fetch_open_orders('LTC/BTC'))
