### ISSUE TITLE
lykke error calling fetch_orders()

### ISSUE THREAD

**Issue by justsaid** [ccxt/ccxt#2492]
Hi,

I’m trying to fetch my orders but I get the following error:

```import ccxt 
lykkeExchange = ccxt.lykke({'apiKey': ‘xxxx’})
lykkeExchange.verbose = True

orders = lykkeExchange.fetch_orders()
```
Output:

```
>>> orders = lykkeExchange.fetch_orders()

Request: GET https://hft-api.lykke.com/api/Orders {'api-key': ‘XXXXXXXXXXXXXXXXXXXXXXXXXX’, 'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://hft-api.lykke.com/api/Orders 200 {'Server': 'nginx/1.10.0 (Ubuntu)', 'Date': 'Sat, 07 Apr 2018 16:48:49 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Request-Context': 'appId=cid-v1:43e62950-e4b6-473f-a795-908b111fa2ad', 'X-Rate-Limit-Limit': '1m', 'X-Rate-Limit-Remaining': '297', 'X-Rate-Limit-Reset': '2018-04-07T16:48:53.0889989Z'} [{"Id":"f5447f02-5061-4829-b1ab-388a02964a3d","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-04-07T09:43:28.31Z"},{"Id":"3f91dc34-b9d1-4f9b-881f-9b0157e224b1","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:43:45.111Z"},{"Id":"18c70464-ab19-4f49-8968-76a5f496a790","Status":"InOrderBook","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:43:39.65Z"},{"Id":"6bc7ba58-4cf1-43b0-834c-a873440be003","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:37:48.483Z"},{"Id":"bdf889ea-023d-484d-a767-3204edd1130e","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:36:22.247Z"},{"Id":"3cb1310c-1ddd-4630-9d4c-cdc76651ec1b","Status":"Cancelled","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2500.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:28:46.848Z"},{"Id":"62e56919-b720-4284-8009-19549b3b641b","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:28:36.678Z"},{"Id":"f95d7718-2f51-46fa-9ef4-9d22d5bbb217","Status":"NotEnoughFunds","AssetPairId":"BTCEUR","Volume":1.0,"Price":2500.0,"RemainingVolume":1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:25:43.456Z"}]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/lykke.py", line 280, in fetch_orders
    return self.parse_orders(response, None, since, limit)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1096, in parse_orders
    array = [self.parse_order(order, market) for order in array]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1096, in <listcomp>
    array = [self.parse_order(order, market) for order in array]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/lykke.py", line 243, in parse_order
    timestamp = self.parse8601(order['LastMatchTime'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 692, in parse8601
    match = re.search(regex, timestamp, re.IGNORECASE)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

- OS: MACOS 10
- Programming Language version:
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
- CCXT version: clone 3 weeks ago
- Exchange: Lykke
- Method: fetch_orders()

**Comment by kroitor** [comment]
Fixed in 1.12.109. Thanks!

**Comment by justsaid** [comment]
Thanks Kroitor!

**Comment by justsaid** [comment]
I'm getting another error now:

```lykkeExchange.fetch_orders()```
```
Request: GET https://hft-api.lykke.com/api/Orders {'api-key': 'XXXXXXXX', 'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://hft-api.lykke.com/api/Orders 200 {'Server': 'nginx/1.10.0 (Ubuntu)', 'Date': 'Sun, 08 Apr 2018 00:52:06 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Request-Context': 'appId=cid-v1:43e62950-e4b6-473f-a795-908b111fa2ad', 'X-Rate-Limit-Limit': '1m', 'X-Rate-Limit-Remaining': '299', 'X-Rate-Limit-Reset': '2018-04-08T00:53:06.4160541Z'} [{"Id":"f5447f02-5061-4829-b1ab-388a02964a3d","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-04-07T09:43:28.31Z"},{"Id":"3f91dc34-b9d1-4f9b-881f-9b0157e224b1","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:43:45.111Z"},{"Id":"18c70464-ab19-4f49-8968-76a5f496a790","Status":"InOrderBook","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:43:39.65Z"},{"Id":"6bc7ba58-4cf1-43b0-834c-a873440be003","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:37:48.483Z"},{"Id":"bdf889ea-023d-484d-a767-3204edd1130e","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:36:22.247Z"},{"Id":"3cb1310c-1ddd-4630-9d4c-cdc76651ec1b","Status":"Cancelled","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2500.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:28:46.848Z"},{"Id":"62e56919-b720-4284-8009-19549b3b641b","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:28:36.678Z"},{"Id":"f95d7718-2f51-46fa-9ef4-9d22d5bbb217","Status":"NotEnoughFunds","AssetPairId":"BTCEUR","Volume":1.0,"Price":2500.0,"RemainingVolume":1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:25:43.456Z"}]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/lykke.py", line 283, in fetch_orders
    return self.parse_orders(response, None, since, limit)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1103, in parse_orders
    array = [self.parse_order(order, market) for order in array]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1103, in <listcomp>
    array = [self.parse_order(order, market) for order in array]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/lykke.py", line 237, in parse_order
    if order['AssetPairId'] in self.markets_by_id:
TypeError: argument of type 'NoneType' is not iterable```

**Comment by kroitor** [comment]
@justsaid missed that one leftover, the new fix will arrive in 5-10 minutes in version 1.12.110. Thanks for your feedback!

**Comment by justsaid** [comment]
No prob Kroitor! Thanks a lot for the fast fix and for this awesome project!!!

**Comment by justsaid** [comment]
Thanks Kroitor, fetch_open_orders() works now. But fetch_orders() is still throwing an error:

```exchange.fetch_orders()```
```
Request: GET https://hft-api.lykke.com/api/Orders {'api-key': ‘XXXXXXXXXXXXXXXXX’, 'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://hft-api.lykke.com/api/Orders 200 {'Server': 'nginx/1.10.0 (Ubuntu)', 'Date': 'Sun, 08 Apr 2018 09:23:58 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Request-Context': 'appId=cid-v1:43e62950-e4b6-473f-a795-908b111fa2ad', 'X-Rate-Limit-Limit': '1m', 'X-Rate-Limit-Remaining': '299', 'X-Rate-Limit-Reset': '2018-04-08T09:24:58.4898205Z'} [{"Id":"f5447f02-5061-4829-b1ab-388a02964a3d","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-04-07T09:43:28.31Z"},{"Id":"3f91dc34-b9d1-4f9b-881f-9b0157e224b1","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:43:45.111Z"},{"Id":"18c70464-ab19-4f49-8968-76a5f496a790","Status":"InOrderBook","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:43:39.65Z"},{"Id":"6bc7ba58-4cf1-43b0-834c-a873440be003","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:37:48.483Z"},{"Id":"bdf889ea-023d-484d-a767-3204edd1130e","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:36:22.247Z"},{"Id":"3cb1310c-1ddd-4630-9d4c-cdc76651ec1b","Status":"Cancelled","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2500.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:28:46.848Z"},{"Id":"62e56919-b720-4284-8009-19549b3b641b","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:28:36.678Z"},{"Id":"f95d7718-2f51-46fa-9ef4-9d22d5bbb217","Status":"NotEnoughFunds","AssetPairId":"BTCEUR","Volume":1.0,"Price":2500.0,"RemainingVolume":1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:25:43.456Z"}]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/lykke.py", line 285, in fetch_orders
    return self.parse_orders(response, None, since, limit)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1104, in parse_orders
    array = self.sort_by(array, 'timestamp')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 553, in sort_by
    return sorted(array, key=lambda k: k[key], reverse=descending)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by kroitor** [comment]
@justsaid thx for your feedback! The fetch_orders should be fixed now as of 1.12.113 (will arrive in 5-10 minutes). Let us know if you still have any difficulties with it.

**Comment by justsaid** [comment]
Hi Kroitor, 
getting again this type of error. Maybe somebody overwritten your change ? 
```
>>> print(lykkeExchange.fetch_orders())

Request: GET https://hft-api.lykke.com/api/Orders {'api-key': ‘XXXXXXXXXXXXXXXXXXXX’, 'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://hft-api.lykke.com/api/Orders 200 {'Server': 'nginx/1.10.0 (Ubuntu)', 'Date': 'Wed, 18 Apr 2018 13:19:41 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Request-Context': 'appId=cid-v1:43e62950-e4b6-473f-a795-908b111fa2ad', 'X-Rate-Limit-Limit': '1m', 'X-Rate-Limit-Remaining': '299', 'X-Rate-Limit-Reset': '2018-04-18T13:20:41.9362582Z'} [{"Id":"5ada9a32-ddea-43ab-8b44-3140ac24b2d4","Status":"InOrderBook","AssetPairId":"WAXETH","Volume":-3.0,"Price":0.038999,"RemainingVolume":-3.0,"LastMatchTime":null,"CreatedAt":"2018-04-18T13:18:31.057Z"},{"Id":"4e759719-83db-41ec-b684-91b21ec92bab","Status":"InOrderBook","AssetPairId":"WAXETH","Volume":139.0,"Price":0.00043,"RemainingVolume":139.0,"LastMatchTime":null,"CreatedAt":"2018-04-18T13:18:30.965Z"},{"Id":"778b9689-6c2e-45e0-a039-3f4d04373476","Status":"Cancelled","AssetPairId":"WAXETH","Volume":-3.0,"Price":0.038999,"RemainingVolume":-3.0,"LastMatchTime":null,"CreatedAt":"2018-04-18T11:52:04.628Z"},{"Id":"aa55f960-6804-451f-8e20-e63fb2f3735c","Status":"Cancelled","AssetPairId":"WAXETH","Volume":46.0,"Price":0.00043,"RemainingVolume":46.0,"LastMatchTime":null,"CreatedAt":"2018-04-18T11:52:04.451Z"},{"Id":"f5447f02-5061-4829-b1ab-388a02964a3d","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-04-07T09:43:28.31Z"},{"Id":"3f91dc34-b9d1-4f9b-881f-9b0157e224b1","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:43:45.111Z"},{"Id":"18c70464-ab19-4f49-8968-76a5f496a790","Status":"Cancelled","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2555.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:43:39.65Z"},{"Id":"6bc7ba58-4cf1-43b0-834c-a873440be003","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:37:48.483Z"},{"Id":"bdf889ea-023d-484d-a767-3204edd1130e","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:36:22.247Z"},{"Id":"3cb1310c-1ddd-4630-9d4c-cdc76651ec1b","Status":"Cancelled","AssetPairId":"ETHEUR","Volume":-0.1,"Price":2500.0,"RemainingVolume":-0.1,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:28:46.848Z"},{"Id":"62e56919-b720-4284-8009-19549b3b641b","Status":"NotEnoughFunds","AssetPairId":"ETHEUR","Volume":-1.0,"Price":2500.0,"RemainingVolume":-1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:28:36.678Z"},{"Id":"f95d7718-2f51-46fa-9ef4-9d22d5bbb217","Status":"NotEnoughFunds","AssetPairId":"BTCEUR","Volume":1.0,"Price":2500.0,"RemainingVolume":1.0,"LastMatchTime":null,"CreatedAt":"2018-03-26T13:25:43.456Z"}]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/lykke.py", line 285, in fetch_orders
    return self.parse_orders(response, None, since, limit)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1104, in parse_orders
    array = self.sort_by(array, 'timestamp')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 553, in sort_by
    return sorted(array, key=lambda k: k[key], reverse=descending)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

```

**Comment by justsaid** [comment]
Seems to be working now! Thx a lot!
