### ISSUE TITLE
bitz: anyone having an issue loading markets or fetching ticker in python?

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#2498]
Anyone having problems accessing any information with CCXT on bitz via API?

- OS: OSX El Capitan
- Programming Language version: Python
- CCXT version: latest (as of 5 minutes ago).
- Exchange: BIT-Z. ID = 'bitz'
- Method: bitz.load_markets() , bitz.fetchTicker(). No function works.
Could it be under maintenance?

**Comment by kroitor** [comment]
> No function works.

You have to be much more specific than that )

```Python
import ccxt
from pprint import pprint
bitz = ccxt.bitz({
    'enableRateLimit': True,
    'verbose': True,
})
bitz.load_markets()
symbol = 'ETH/BTC'
ticker = bitz.fetch_ticker(symbol)
pprint(ticker)
```

↑ What's the output?

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by jed057** [comment]
@karlandoh i got the same today, guess it's exchange problem.. same code worked previously.

**Comment by jorijnsmit** [comment]
Same here. Full error:

```
Request: GET https://www.bit-z.com/api_v1/tickerall {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.bit-z.com/api_v1/tickerall 403 {'Date': 'Tue, 10 Apr 2018 06:31:16 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'X-Via-JSL': '9b7b529,-', 'Set-Cookie': '__jsluid=24b6fe0348c31903ec5ab9477ab3ec0c; max-age=31536000; path=/; HttpOnly', 'X-Cache': 'error', 'Content-Encoding': 'gzip'} <!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
body{ background:#fff; font-family: microsoft yahei; color:#969696; font-size:14px;}
.online-desc-con { text-align:center; }
.r-tip01 { color: #333; font-size: 18px; display: block; text-align: center; width: 500px; padding: 0 10px; overflow: hidden; text-overflow: ellipsis; margin: 0 auto 15px; }
.r-tip02 { color: #585858; font-size: 14px; display: block; margin-top: 20px; margin-bottom: 20px; }
#notice-jiasule {
  word-wrap: break-word;
  word-break: normal;
  color:#585858;
  border:1px solid #ddd;
  padding:0px 20px 0px 20px
}
img { border: 0; }
.u-ico{ vertical-align: middle; margin-right: 12px;}
.btn{ padding: 8px 22px; border-radius: 3px; border: 0; display: inline-block;vertical-align: middle;text-decoration: none;}
.btn-g{ background-color: #61b25e; color: #fff;}
.report {color: #858585; text-decoration: none;}
.report:hover {text-decoration: underline; color: #0088CC;}
hr{ border-top: 1px dashed #ddd;}
center{ line-height: 48px; color: #919191;}
</style>
<script type="text/template" id="content_tpl">
    <span class="r-tip01"><%= error_403 %></span>
    <div id='notice-jiasule'>
        <p>å½åç½åï¼<%- url %></p>
        <p>å®¢æ·ç«¯ç¹å¾ï¼<%- user_agent %></p>
        <p>æ¦æªæ¶é´ï¼<%- now %>&nbsp;&nbsp;æ¬æ¬¡äºä»¶ID&nbsp;<%- rule_id %></p>
    </div>
    <span class='r-tip02'>
        <img class='u-ico' alt='' src='/cdn-cgi/image/guest.png' />å¦ææ¨æ¯ç½ç«ç®¡çåï¼è¯·ç»å½ç¥éåå®äºå®å¨&nbsp;
        <a class='btn btn-g' href='http://help.yunaq.com/feedback.html?from=<%- from %>&rule_id=<%- rule_id %>&client_ip=<%- client_ip %>&referrer=<%- ref %>#pus' target='_blank'>æ¥çè¯¦æ</a>
        &nbsp;æè&nbsp;
        <a class='report' href='http://help.yunaq.com/feedback.html?from=<%- from %>&rule_id=<%- rule_id %>&client_ip=<%- client_ip %>&referrer=<%- ref %>#hus' target='_blank'>åé¦è¯¯æ¥</a>
    </span>
</script>
<script type="text/javascript" src="/cdn-cgi/js/underscore_min_1.8.3.js"></script>
</head>
<body>
<div class="online-desc-con" style="width:640px;padding-top:15px;margin:34px auto;">
	<img alt="" style="margin: 0 auto 17px auto;" src="/cdn-cgi/image/protected.png" />
    <div id="content_rendered"></div>
	<hr />
	<center>client: ---.---.---.---, server: 9b7b529, time: 2018-04-10 14:31:16</center>
</div>
<script>
void(function fuckie6(){if(location.hash && /MSIE 6/.test(navigator.userAgent) && !/jsl_sec/.test(location.href)){location.href = location.href.split('#')[0] + '&jsl_sec' + location.hash}})();
var content = _.template(document.getElementById('content_tpl').innerHTML)({
    error_403: '' || 'å½åè®¿é®çä¼¼é»å®¢æ»å»ï¼å·²è¢«ç½ç«ç®¡çåè®¾ç½®ä¸ºæ¦æª',
    url: document.URL.replace(/\</g,"%3C").replace(/\>/g,"%3E"),
    user_agent: navigator.userAgent,
    now: new Date(new Date() - -8 * 3600000).toISOString().substr(0, 19).replace('T', ' '),
    rule_id: parseInt('[80001]'.replace(/\[|\]/g, '')) || '',
    from: encodeURIComponent(document.referrer.substr(0, 1024)),
    client_ip: '---.---.---.---',
    ref: encodeURIComponent(document.URL.substr(0, 1024))
});
document.getElementById('content_rendered').innerHTML = content;
</script>
<div style="display:none;">
    <script>
        var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
        document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Fd7682ab43891c68a00de46e9ce5b76aa' type='text/javascript'%3E%3C/script%3E"));
    </script>
</div>
</body>

</html>

Traceback (most recent call last):
  File "/----------------------/ccxt/base/exchange.py", line 363, in fetch
    response.raise_for_status()
  File "/----------------------/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.bit-z.com/api_v1/tickerall

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Sandbox.py", line 7, in <module>
    bitz.load_markets()
  File "/----------------------/ccxt/base/exchange.py", line 870, in load_markets
    markets = self.fetch_markets()
  File "/----------------------/ccxt/bitz.py", line 137, in fetch_markets
    response = self.publicGetTickerall()
  File "/----------------------/ccxt/bitz.py", line 380, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/----------------------/ccxt/base/exchange.py", line 302, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/----------------------/ccxt/base/exchange.py", line 376, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "/----------------------/ccxt/base/exchange.py", line 405, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/----------------------/ccxt/base/exchange.py", line 287, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: bitz https://www.bit-z.com/api_v1/tickerall GET 403 Client Error: Forbidden for url: https://www.bit-z.com/api_v1/tickerall <!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
body{ background:#fff; font-family: microsoft yahei; color:#969696; font-size:14px;}
.online-desc-con { text-align:center; }
.r-tip01 { color: #333; font-size: 18px; display: block; text-align: center; width: 500px; padding: 0 10px; overflow: hidden; text-overflow: ellipsis; margin: 0 auto 15px; }
.r-tip02 { color: #585858; font-size: 14px; display: block; margin-top: 20px; margin-bottom: 20px; }
#notice-jiasule {
  word-wrap: break-word;
  word-break: normal;
  color:#585858;
  border:1px solid #ddd;
  padding:0px 20px 0px 20px
}
img { border: 0; }
.u-ico{ vertical-align: middle; margin-right: 12px;}
.btn{ padding: 8px 22px; border-radius: 3px; border: 0; display: inline-block;vertical-align: middle;text-decoration: none;}
.btn-g{ background-color: #61b25e; color: #fff;}
.report {color: #858585; text-decoration: none;}
.report:hover {text-decoration: underline; color: #0088CC;}
hr{ border-top: 1px dashed #ddd;}
center{ line-height: 48px; color: #919191;}
</style>
<script type="text/template" id="content_tpl">
    <span class="r-tip01"><%= error_403 %></span>
    <div id='notice-jiasule'>
        <p>å½åç½åï¼<%- url %></p>
        <p>å®¢æ·ç«¯ç¹å¾ï¼<%- user_agent %></p>
        <p>æ¦æªæ¶é´ï¼<%- now %>&nbsp;&nbsp;æ¬æ¬¡äºä»¶ID&nbsp;<%- rule_id %></p>
    </div>
    <span class='r-tip02'>
        <img class='u-ico' alt='' src='/cdn-cgi/image/guest.png' />å¦ææ¨æ¯ç½ç«ç®¡çåï¼è¯·ç»å½ç¥éåå®äºå®å¨&nbsp;
        <a class='btn btn-g' href='http://help.yunaq.com/feedback.html?from=<%- from %>&rule_id=<%- rule_id %>&client_ip=<%- client_ip %>&referrer=<%- ref %>#pus' target='_blank'>æ¥çè¯¦æ</a>
        &nbsp;æè&nbsp;
        <a class='report' href='http://help.yunaq.com/feedback.html?from=<%- from %>&rule_id=<%- rule_id %>&client_ip=<%- client_ip %>&referrer=<%- ref %>#hus' target='_blank'>åé¦è¯¯æ¥</a>
    </span>
</script>
<script type="text/javascript" src="/cdn-cgi/js/underscore_min_1.8.3.js"></script>
</head>
<body>
<div class="online-desc-con" style="width:640px;padding-top:15px;margin:34px auto;">
	<img alt="" style="margin: 0 auto 17px auto;" src="/cdn-cgi/image/protected.png" />
    <div id="content_rendered"></div>
	<hr />
	<center>client: ---.---.---.---, server: 9b7b529, time: 2018-04-10 14:31:16</center>
</div>
<script>
void(function fuckie6(){if(location.hash && /MSIE 6/.test(navigator.userAgent) && !/jsl_sec/.test(location.href)){location.href = location.href.split('#')[0] + '&jsl_sec' + location.hash}})();
var content = _.template(document.getElementById('content_tpl').innerHTML)({
    error_403: '' || 'å½åè®¿é®çä¼¼é»å®¢æ»å»ï¼å·²è¢«ç½ç«ç®¡çåè®¾ç½®ä¸ºæ¦æª',
    url: document.URL.replace(/\</g,"%3C").replace(/\>/g,"%3E"),
    user_agent: navigator.userAgent,
    now: new Date(new Date() - -8 * 3600000).toISOString().substr(0, 19).replace('T', ' '),
    rule_id: parseInt('[80001]'.replace(/\[|\]/g, '')) || '',
    from: encodeURIComponent(document.referrer.substr(0, 1024)),
    client_ip: '---.---.---.---',
    ref: encodeURIComponent(document.URL.substr(0, 1024))
});
document.getElementById('content_rendered').innerHTML = content;
</script>
<div style="display:none;">
    <script>
        var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
        document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Fd7682ab43891c68a00de46e9ce5b76aa' type='text/javascript'%3E%3C/script%3E"));
    </script>
</div>
</body>

</html>
```

**Comment by jed057** [comment]
@kroitor This solves the problem on my side. thx!

**Comment by jorijnsmit** [comment]
Can confirm this solves the problem.

**Comment by karlandoh** [comment]
I still reproduce the same error as @jorijnsmit with a random userAgent added.

**Comment by karlandoh** [comment]
Problem fixed with random userAgent. Thank you so much.
