### ISSUE TITLE
itbit fetchTicker exception

### ISSUE THREAD

**Issue by dmig** [ccxt/ccxt#2507]
- Programming Language version: python 3.6.5
- CCXT version: 1.12.111
- Exchange: itbit
- Method: fetchTicker()

Just got an exception:
```
Traceback (most recent call last):
  File "lib/exchange_utils.py", line 86, in _fetch_wrapper
    response[p] = fetch_func(p)
  File "venv/lib/python3.6/site-packages/ccxt/itbit.py", line 90, in fetch_ticker
    vwap = float(ticker['vwap24h'])
TypeError: float() argument must be a string or a number, not 'NoneType'
```
Better be ready for unexpected values...

**Comment by kroitor** [comment]
Fixed in 1.12.122, thanks for your feedback!
