### ISSUE TITLE
load_markets is throwing an "Max retries exceeded" exception

### ISSUE THREAD

**Issue by dash61** [ccxt/ccxt#2522]
Hello,

This started happening April 7th, and my code has been previously working for 2 months unchanged.
- OS:  Mac Sierra (10.12.6)
- Programming Language version: Python 3.5.1
- CCXT version: 1.12.117 and 1.10.810
- Exchange: Binance
- Method: load_markets

I do:
import ccxt
...
    self.coinExchange = ccxt.binance({ 'verbose': True })  # works
    self.coinMarket = self.coinExchange.load_markets ()   # throws

load_markets throws with this error:
EXCEPTION OCCURRED IN ccxtUtils.py, IN getCoinData FUNCTION - binance https://api.binance.com/api/v1/exchangeInfo GET HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/exchangeInfo (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)'),))

My code pings the exchange to get a price once every 40 seconds. It was doing that for perhaps 9 hours and I noticed it had stopped. When I restarted the app, it had this exception.

This is new behavior, like I said the code (to call load_markets) was working fine for months prior. I tried updating to the latest ccxt version and that didn't help. I've searched online and no luck so far. Perhaps it has to do with pinging the exchange once every 40 seconds; that is something new that I started late last week, and up to Saturday the 7th, it was working fine. 

My code to get the price is:
        symbol = self.coinMarket[symbolString]['id']        # given a symbolString like 'HSRBTC'
        params = {'symbol': symbol}
        res = self.coinExchange.publicGetTickerPrice (params)

I can log into Binance fine, it doesn't report any issues (like it hates me now or anything odd).

Any ideas?
Thanks,
Don

**Comment by kroitor** [comment]
Can you please post the smallest possible, but a complete snippet of code to reproduce the issue?

Does this work ↓ ?

```Python
import ccxt
exchange = ccxt.binance()
markets = exchange.load_markets()
```

↑ This is a complete snippet, you can copypaste it to your python in order to check if it works. If it does not work, I'd expect to see a similar **complete** code snippet from you to reproduce it. Standing by for more info from you...

**Comment by dash61** [comment]
I tried that, it does NOT work, it throws an exception on the load_markets line. Here is the output:

Dons-MacBook-Pro:CoinBot don$ python3
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> exchange = ccxt.binance()
>>> markets = exchange.load_markets()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/exchangeInfo (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 356, in fetch
    proxies=self.proxies
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/exchangeInfo (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 870, in load_markets
    markets = self.fetch_markets()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ccxt/binance.py", line 294, in fetch_markets
    response = self.publicGetExchangeInfo()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 305, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 302, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 380, in fetch
    self.raise_error(ExchangeError, url, method, e, self.last_http_response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ccxt/base/exchange.py", line 287, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: binance https://api.binance.com/api/v1/exchangeInfo GET HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/exchangeInfo (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)'),))
>>>

**Comment by dash61** [comment]
I found a similar issue logged on the python-binance code package 12 days ago, though no one has responded on it yet:

https://github.com/sammchardy/python-binance/issues/227

**Comment by kroitor** [comment]
What's your version of ccxt? You wrote that it's 1.12 or 1.10, but 1.10 is very old... this can make a difference.

```Python
import ccxt
exchange = ccxt.binance({
    'userAgent': 'foobar', # add this and retry
})
markets = exchange.load_markets()
```

↑ Does it work for you with userAgent added?

**Comment by dash61** [comment]
I was using version 1.10 for a long time, but this morning updated to 1.12 to see if that helped the issue, but it did not. 

I tried you latest example and got the same exceptions on calling load_markets.

**Comment by kroitor** [comment]
Will need to debug your OpenSSL... What's your OpenSSL version? Should be > 1.02c.

Does this work from the same machine?

```
curl https://api.binance.com/api/v1/exchangeInfo 
```

**Comment by kroitor** [comment]
Most likely you need to upgrade or re/deinstall pyopenssl.

**Comment by kroitor** [comment]
This isn't a CCXT issue, it's a Python + OpenSSL setup issue. 

- https://github.com/spookylukey/django-paypal/issues/145
- https://github.com/requests/requests/issues/4397
- https://stackoverflow.com/questions/35405092/sslerror-sslv3-alert-handshake-failure
- https://www.google.ru/search?q=python+openssl+SSLV3_ALERT_HANDSHAKE_FAILURE

Does anything of the above help?

**Comment by dash61** [comment]
The curl *does* work fine.
My openssl version is "OpenSSL 0.9.8zh 14 Jan 2016".
I don't think I have pyopenssl installed. I typed "openssl" on the command line and it gave me a prompt.

**Comment by dash61** [comment]
Ok, let me dig into that. I'll let you know.

**Comment by kroitor** [comment]
@dash61 you should upgrade your system-wide openssl to 1.02c+ and make sure you don't have pyopenssl overriding it. Closing it for now, if you don't mind. Feel free to reopen it if needed, or just ask questions, if any.

**Comment by dash61** [comment]
Ok, thanks, I installed pyopenssl and that fixed the problem.

**Comment by kroitor** [comment]
@dash61 thanks for reporting back!
