### ISSUE TITLE
create_order price nonetype

### ISSUE THREAD

**Issue by doctord919** [ccxt/ccxt#2532]
- OS: Win 8.1 64bit
- Programming Language version: python 3.64 64bit
- CCXT version: 1.12.131
- Exchange: wex,exmo ....
- Method: create_order()
example:

```
import ccxt

if __name__ == '__main__':
    exm1 = ccxt.exmo({
        "apiKey": "lala",
        "secret": "lala"
    })
    exm = ccxt.wex({
        "apiKey": "lala",
        "secret": "lala"
    })
    exm.create_limit_sell_order('ZEC/BTC', 0.00001) #0.00001 - for example ...
    exm1.create_limit_sell_order('ZEC/BTC', 0.00001)
Next problems:

C:\Python36_64\python.exe C:/b/alf.py
Traceback (most recent call last):
  File "C:/b/alf.py", line 15, in <module>
    exm.create_limit_sell_order('ZEC/BTC', 0.00001)
  File "C:\Python36_64\lib\site-packages\ccxt\base\exchange.py", line 1222, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Python36_64\lib\site-packages\ccxt\liqui.py", line 364, in create_order
    'rate': self.price_to_precision(symbol, price),
  File "C:\Python36_64\lib\site-packages\ccxt\base\exchange.py", line 820, in price_to_precision
    return ('{:.' + str(self.markets[symbol]['precision']['price']) + 'f}').format(float(price))
TypeError: float() argument must be a string or a number, not 'NoneType'

Process finished with exit code 1
liqui.py: 
   def create_order(self, symbol, type, side, amount, price=None, params={}):
        if type == 'market':
            raise ExchangeError(self.id + ' allows limit orders only')
        self.load_markets()
        market = self.market(symbol)
        request = {
            'pair': market['id'],
            'type': side,
            'amount': self.amount_to_precision(symbol, amount),
            'rate': self.price_to_precision(symbol, price), <---1)  ','(comma) - this need ? 2) price = None
        }

```

**Comment by kroitor** [comment]
@doctord919 a `limit` order should have a price, therefore calling `create_limit_sell_order` with just the symbol and the `amount` is wrong: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders.
Let us know if this does not answer your question.
