### ISSUE TITLE
How to use ccxt in typescript and firebase cloud function?

### ISSUE THREAD

**Issue by aldi11097** [ccxt/ccxt#2549]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: v9.8.0
- CCXT version:^1.12.147

Hi, currently i got issue for calling ccxt.exchange by following the example on the documentation.
with following stack trace : 

`+  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (48.93 KB) for uploading
+  functions: functions folder uploaded successfully
i  functions: updating function api...
!  functions[api]: Deployment error.
Function load error: Code in file lib/index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /user_code/node_modules/ccxt/js/base/Exchange.js:362
                    let partial = async params => this[methodName] (path, type, uppercaseMethod, params || {})
                                        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/ccxt/ccxt.js:33:19)`

node version : v9.8.0
npm version : 5.7.1
language : Typescript
server : Firebase cloud function

**Comment by kroitor** [comment]
You need to make sure that you use proper transpilation for ES6, because Firebase does not like it, it uses the older ES5 syntax apparently. Unfortunately, I cannot really consult you on this apart from the following links:

- https://github.com/ccxt/ccxt/search?q=babel&type=Issues
- https://github.com/ccxt/ccxt/issues/606
- https://github.com/ccxt/ccxt/issues/2285
- https://github.com/ccxt/ccxt/issues/299

Hope it helps... I'm not very familiar with Firebase setup unfortunately.
