### ISSUE TITLE
How to make binance "test" buy market order in python with ccxt?

### ISSUE THREAD

**Issue by XliveStudios** [ccxt/ccxt#2552]
How to make binance "test" buy market order in python with ccxt?

- OS: Wİndows
- Programming Language version: Python 3x
- CCXT version: 
- Exchange: Binance
- Method: Buy Order

**Comment by XliveStudios** [comment]
Anyone know? Please help..

**Comment by kroitor** [comment]
This is done by passing an binance-exchange-specific `{'test': True}` param (not all exchanges support the "test mode").

Documented here: 

- https://github.com/ccxt/ccxt/wiki/Manual#custom-order-params

1. Update to ccxt version 1.12.150 (will be available in 5-10 minutes)
2. See this example (will work with 1.12.150 or later)

https://github.com/ccxt/ccxt/blob/master/examples/py/binance-test-order.py

```Python
# -*- coding: utf-8 -*-

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

symbol = 'BTC/ETH'  
type = 'limit'  # or 'market'
side = 'sell'  # or 'buy'
amount = 1.0
price = 0.060154  # or None

# extra params and overrides if needed
params = {
    'test': True,  # test if it's valid, but don't actually place it
}

order = exchange.create_order(symbol, type, side, amount, price, params)

print(order)
```

**Comment by XliveStudios** [comment]
Thanks a lot thats very helpfull..

**Comment by XliveStudios** [comment]
But it gives error.

`Traceback (most recent call last):
  File "Z:\cc\py\bn_test_order.py", line 25, in <module>
    order = exchange.create_order(symbol, type, side, amount, params)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 606, in create_order
    response = self.privatePostOrder(self.extend(order, params))
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 305, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 302, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 375, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 801, in handle_errors
    raise exceptions[error](self.id + ' ' + body)
ccxt.base.errors.InsufficientFunds: binance {"code":-2010,"msg":"Account has insufficient balance for requested action."}

Z:\cc\py>bn_test_order.py
Traceback (most recent call last):
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 363, in fetch
    response.raise_for_status()
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\cc\py\bn_test_order.py", line 25, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 606, in create_order
    response = self.privatePostOrder(self.extend(order, params))
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 305, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 302, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 375, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 803, in handle_errors
    raise ExchangeError(self.id + ': unknown error code: ' + body + ' ' + error)
ccxt.base.errors.ExchangeError: binance: unknown error code: {"code":-1104,"msg":"Not all sent parameters were read; read '7' parameter(s) but was sent '8'."} -1104`

**Comment by XliveStudios** [comment]
Sorry, i just updated ccxt to 1.12.150. But when i try it gives error below: 
======================
Traceback (most recent call last):
  File "Z:\cc\py\bn_test_order.py", line 22, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 613, in create_order
    return self.parse_order(response)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 565, in parse_order
    raise ExchangeError(self.id + ' malformed order: ' + self.json(order))
ccxt.base.errors.ExchangeError: binance malformed order: {}

**Comment by kroitor** [comment]
@XliveStudios ok, looks like your version was not 1.12.150+. 

You can check that with this:

```Python
import ccxt
print(ccxt.__version__)
```

However, while debugging it, I found a minor leftover in the parsing routine, and fixed it, the fix is ready in 1.12.152, and I would ask you to update to 1.12.152 once again. From there this issue should be resolved. It should return an empty order (with all fields undefined – that means a successful test, as per binance docs). We will be happy if you report back, whether it works normally for you with 1.12.152 or not. Thank you for your involvement!

**Comment by XliveStudios** [comment]
`Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> ccxt.__version__
'1.12.153'
>>>
`

`
Z:\cc\py>Z:\cc\py\bn_test_order.py
Traceback (most recent call last):
  File "Z:\cc\py\bn_test_order.py", line 28, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 621, in create_order
    return self.parse_order(response)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 567, in parse_order
    price = float(order['price'])
KeyError: 'price'

Z:\cc\py>Z:\cc\py\bn_test_order.py
Traceback (most recent call last):
  File "Z:\cc\py\bn_test_order.py", line 28, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 621, in create_order
    return self.parse_order(response)
  File "C:\Users\Q\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 567, in parse_order
    price = float(order['price'])
KeyError: 'price'
`

**Comment by kroitor** [comment]
@XliveStudios got it, uploaded the final fix, finally got time to test it on my side extensively, and, indeed, there was a price parsing bug again, i've tried it locally with 1.12.154, and it works normally for me now.

**Comment by kroitor** [comment]
@XliveStudios thx for your help!

**Comment by kroitor** [comment]
@XliveStudios shame on me ( one more python compatibility fix should finally fix this nasty issue... Can you please try the same code with 1.12.155 ? Really sorry for the inconvenience.

**Comment by XliveStudios** [comment]
It works now, thanks. 

```
Z:\cc\py>bn_test_order.py
{'info': {}, 'id': None, 'timestamp': None, 'datetime': None, 'symbol': None, 'type': None, 'side': None, 'price': None, 'amount': None, 'cost': None, 'filled': 0.0, 'remaining': None, 'status': None, 'fee': None}
```

**Comment by MaxCCC** [comment]
@kroitor 

I just tried (latest version of ccxt)
```
import ccxt 

exchange = ccxt.binance({
	'apiKey': '*******',
	'secret': '*******',
    'enableRateLimit': True,
})

symbol = 'BNB/BTC'  
type = 'limit'  # or 'market'
side = 'sell'  # or 'buy'
amount = 1.0
price = 0.060154  # or None

# extra params and overrides if needed
params = {
    'test': True,  # test if it's valid, but don't actually place it
}

order = exchange.create_order(symbol, type, side, amount, price, params)

print(order)
```

And I got:
```
Traceback (most recent call last):
  File "/Users/name/venv/test/lib/python3.6/site-packages/ccxt/base/exchange.py", line 400, in fetch
    response.raise_for_status()
  File "/Users/name/venv/test/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order/test

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/name/Documents/test/src/helper.py", line 23, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "/Users/name/venv/test/lib/python3.6/site-packages/ccxt/binance.py", line 705, in create_order
    response = getattr(self, method)(self.extend(order, params))
  File "/Users/name/venv/test/lib/python3.6/site-packages/ccxt/binance.py", line 1066, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/name/venv/test/lib/python3.6/site-packages/ccxt/base/exchange.py", line 330, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/name/venv/test/lib/python3.6/site-packages/ccxt/base/exchange.py", line 412, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "/Users/name/venv/test/lib/python3.6/site-packages/ccxt/binance.py", line 1024, in handle_errors
    raise InvalidOrder(self.id + ' order price exceeds allowed price precision or invalid, use self.price_to_precision(symbol, amount) ' + body)
ccxt.base.errors.InvalidOrder: binance order price exceeds allowed price precision or invalid, use self.price_to_precision(symbol, amount) {"code":-1013,"msg":"Filter failure: PRICE_FILTER"}
```

**Comment by MaxCCC** [comment]
@kroitor thanks

I tried:

```
symbol = 'BNB/BTC'  
type = 'limit'  # or 'market'
side = 'buy'  # or 'buy'
amount = 5.0
price = 0.00014761  # or None
```
which seems to fit in the limits?
`ccxt.base.errors.InvalidOrder: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}`

**Comment by kroitor** [comment]
> which seems to fit in the limits?

Yes, but it's a different error now, so you're making progress ;)

> `ccxt.base.errors.InvalidOrder: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}`

It means that you're not respecting minimal cost:

```Python
amount = 5.0
price = 0.00014761
cost = amount * price  # 5 x 0.00014761 = 0.00073805
print('Out of limits!' if exchange.markets['BNB/BTC']['limits']['cost']['min'] <= cost else 'Within limits!')

# 'limits': {'amount': {'max': 90000000.0, 'min': 0.01},
#            'cost': {'max': None, 'min': 0.001}, # ←---------------- min cost 0.001 > 0.00073805
#            'price': {'max': 0.014751, 'min': 0.0001476}},  
```

**Comment by Ravisut** [comment]
`import ccxt

exchange = ccxt.binance({
    'apiKey': '*******',
    'secret': '*******',
    'enableRateLimit': True,
})

symbol = 'XRP/USDT'
type = 'limit'  # or 'market'
side = 'sell'  # or 'buy'
amount = 55.0
price = 0.1960  # or None

# extra params and overrides if needed
params = {
    'test': False,  # test if it's valid, but don't actually place it
}

order = exchange.create_order(symbol, type, side, amount, price, params)

print(order)`

Error

`E:\PycharmProjects\TradingTutorial\venv\Scripts\python.exe E:/PycharmProjects/TradingTutorial/Code/Test.py
Traceback (most recent call last):
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 580, in fetch
    response.raise_for_status()
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/PycharmProjects/TradingTutorial/Code/Test.py", line 20, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\binance.py", line 1257, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 462, in inner
    return entry(_self, **inner_kwargs)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\binance.py", line 1988, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\binance.py", line 1982, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 499, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeError: binance {"code":-1104,"msg":"Not all sent parameters were read; read '10' parameter(s) but was sent '11'."}

Process finished with exit code 1
`

**Comment by kroitor** [comment]
@Ravisut thx for reporting! The fix is on the way, and it should work fine as of version 1.30.1, the new build will arrive in 15 minutes.

**Comment by adam-bhaiji** [comment]
Hi, I still have the same issue using version 1.30.1. It seems like the 'test' key in the params dict is not being popped off before sending it to binance.

**Comment by kroitor** [comment]
@adam-bhaiji will check and will get back to you shortly.

**Comment by kroitor** [comment]
@adam-bhaiji a quick question – are you trying to use spot orders or futures orders? The `test` param won't work with futures (it's only supported by Binance's spot API).

**Comment by adam-bhaiji** [comment]
ahh makes perfect sense, been trying it with futures orders. Thanks for the really quick help!

**Comment by kroitor** [comment]
@adam-bhaiji you can still use the testnet urls, as follows:

```Python
exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
exchange.set_sandbox_mode(True)
```

However, this is different from the "test"-order functionality.

**Comment by fievelk** [comment]
@kroitor I can't seem to find any reference to `set_sandbox_mode` on the wiki. Is it documented somewhere else?

**Comment by kroitor** [comment]
@fievelk it's not documented yet (the Manual is also a work in progress, just like the rest of this lib), we will add it asap.

**Comment by biahoi** [comment]
Hi guys. I understand that Binance only provide test feature on Binance testNet to verify "if the order is correct or not" but It does not provide simulated trading on test Coins - Is it right?
Can we trade on Binance testnet as with Bitmex Testnet?

**Comment by kroitor** [comment]
@biahoi hi! This issue is outdated, Binance already has a testnet and it is supported in CCXT, please check this comment: https://github.com/ccxt/ccxt/issues/2552#issuecomment-643830217
