### ISSUE TITLE
Binance Interval problems

### ISSUE THREAD

**Issue by jckling** [ccxt/ccxt#2554]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows10
- Programming Language version: python
- CCXT version: 1.12.126
- Exchange: InvaildOrder, ExchangeError
- Method: fetch_order_book,fetch_ticker

I uninstall pyopenssl and fix the SSL problem, my OpenSSL is 1.0.2o
I think the SSL error can be caused by having OpenSSL and pyopenssl on my computer in the same time
But I still have the same problem
#2522 

The I still have two other problems
One is Max retries(gateio、okex)
Another is Interval(binance)

And I have used `time.sleep(60)` after I successfully get information, immediately retry after I catch the ExchangeError or RequestTimeout

Is that means I should use `time.sleep()` after catch the error(seems no help) or try to set the interval by something?

```
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 363, in fetch
    response.raise_for_status()
  File "D:\Anaconda3\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v1/depth?symbol=EOSETH&limit=3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/linki/PycharmProjects/Test/apitest.py", line 260, in <module>
    info += getDvalue(poss['1'])
  File "C:/Users/linki/PycharmProjects/Test/apitest.py", line 162, in getDvalue
    min = net_dic[dic[k][1]].fetch_order_book(k, 3)
  File "D:\Anaconda3\lib\site-packages\ccxt\binance.py", line 409, in fetch_order_book
    response = self.publicGetDepth(self.extend(request, params))
  File "D:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 305, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "D:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 302, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 375, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "D:\Anaconda3\lib\site-packages\ccxt\binance.py", line 804, in handle_errors
    raise exceptions[error](self.id + ' ' + body)
ccxt.base.errors.InvalidOrder: binance {"code":-1100,"msg":"Illegal characters found in parameter 'interval'; legal range is '5, 10, 20, 50, 100, 500, 1000'."}
```

I have not set the parameter 'interval' at all, I don't know how this happened

I got the Max retries error and seems it's still the SSL error?
```
2018-04-12 11:28:46,016 - ERROR - Something bad happened
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "D:\Anaconda3\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "D:\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Anaconda3\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "D:\Anaconda3\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "D:\Anaconda3\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "D:\Anaconda3\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.gate.io', port=443): Max retries exceeded with url: /api2/1/ticker/eos_eth (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:833)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 356, in fetch
    proxies=self.proxies
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='data.gate.io', port=443): Max retries exceeded with url: /api2/1/ticker/eos_eth (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:833)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/linki/PycharmProjects/Test/apitest.py", line 252, in <module>
    dic, poss = getTicker(net_lst, coin_lst)
  File "C:/Users/linki/PycharmProjects/Test/apitest.py", line 103, in getTicker
    x = net_dic[n].fetch_ticker(rate)['last']
  File "D:\Anaconda3\lib\site-packages\ccxt\gateio.py", line 217, in fetch_ticker
    }, params))
  File "D:\Anaconda3\lib\site-packages\ccxt\gateio.py", line 318, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "D:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 302, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 380, in fetch
    self.raise_error(ExchangeError, url, method, e, self.last_http_response)
  File "D:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 287, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: gateio https://data.gate.io/api2/1/ticker/eos_eth GET HTTPSConnectionPool(host='data.gate.io', port=443): Max retries exceeded with url: /api2/1/ticker/eos_eth (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:833)'),)) {"result":"true","last":0.0203,"lowestAsk":0.0205,"highestBid":0.0203,"percentChange":39.144150322315,"baseVolume":2775.868,"quoteVolume":155213.181,"high24hr":0.02089,"low24hr":0.01448}
```

**Comment by ewwink** [comment]
read the error message, it write `limit=3` it should be `5, 10, 20, 50, 100, 500, 1000`

**Comment by jckling** [comment]
```
import time
import ccxt

net_lst = ['okex', 'gateio', 'huobipro', 'binance']
coin_lst = ['EOS/ETH']
net_dic = {}

def GetTarget(arr):
    for a in arr:
        net_dic[a] = getattr(ccxt, a)({'options': {'adjustForTimeDifference': True}})
        net_dic[a].apiKey, net_dic[a].secret = api[a], secret[a]

def GetBalance(symbol):
    coin = symbol.split('/')
    s = ''
    for net in net_lst:
        one_minute_Ago = int(time.time() * 1000) - 60000
        s += net + str(net_dic[net].fetch_balance()[coin[0]]) + str(net_dic[net].fetch_balance()[coin[1]])
        trades = net_dic[net].fetch_trades(symbol, since=one_minute_Ago)
        for trade in trades:
            s += str(trade)
    return s

def MaxMin(dic):
    temp = sorted(dic.items(), key=lambda x: x[1], reverse=True)
    return temp[0][1], temp[0][0], temp[-1][1], temp[-1][0]

def getTicker(net, coin):
    possible = {1: {}}
    dic = {}
    for rate in coin:
        dic[rate] = {}
        for n in net:
            x = net_dic[n].fetch_ticker(rate)['last']
            dic[rate][n] = x
        max, maxnet, min, minnet = MaxMin(dic[rate])
        per = round(abs(max - min) / min, 10) * 100
        dic[rate]['percent'] = per
        if (per >= 1 and per < 2):
            possible[1][rate] = [maxnet, minnet]
    dic = sorted(dic.items(), key=lambda x: x[1]['percent'], reverse=True)
    return dic, possible

def MakeOrder(symbol, buy_from, buy_price, sell_to, sell_price):
    buy, buy_depth = net_dic[buy_from].fetch_order_book(symbol, 5)['bids'][0]
    sell, sell_depth = net_dic[sell_to].fetch_order_book(symbol, 5)['asks'][0]
    net_dic[sell_to].createLimitSellOrder(symbol, 0.001, sell_price)
    net_dic[buy_from].createLimitBuyOrder(symbol, 0.001, buy_price)

def getDvalue(dic):
    for k in dic:
        max = net_dic[dic[k][0]].fetch_order_book(k, 5)
        max_s, max_s_depth, max_b, max_b_depth = max['asks'][0], max['bids'][0]
        min = net_dic[dic[k][1]].fetch_order_book(k, 5)
        min_s, min_s_depth, min_b, min_b_depth = min['asks'][0], min['bids'][0]
        if (max_b - min_s > 0):
            GetBalance(k)
            MakeOrder(k, dic[k][1], min_s, dic[k][0], max_b)

if __name__ == '__main__':
    GetTarget(net_lst)
    while True:
        try:
            dic, poss = getTicker(net_lst, coin_lst)
            getDvalue(poss[1])
            print(dic)
            print(poss)
            time.sleep(60)
        except (ccxt.ExchangeError, ccxt.NetworkError, ccxt.RequestTimeout, ccxt.InvalidOrder) as error:
            print(error)
            time.sleep(5)
            continue
```
Interval problems happens when I try to make order, and I have set all fetch_order_book with 5 instead of 3
I haven't try to make order yet, I'm wondering "Max retries" is because I use fetch_order_book too many times in an execution

**Comment by kroitor** [comment]
@jckling you're not using any rate limiting at all and your code actually has more errors than one.
What you are doing is you're issuing too many calls in getTicker, then fetching balances and orderbooks in getDvalue within a very short time, without any limit between the calls... You need to enable the built-in rate limiter (see the examples and you should limit the rate of consecutive calls – read the Manual carefully).

- https://github.com/ccxt/ccxt/tree/master/examples/py
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/search?q=rateLimit&type=Issues

The easiest way to overcome this would be to add `'enableRateLimit': true` to your constructor params:

```Python
def GetTarget(arr):
    for a in arr:
        net_dic[a] = getattr(ccxt, a)({
            'options': {'adjustForTimeDifference': True},
            'enableRateLimit': True,  # ←------------------------ add this
        })
        net_dic[a].apiKey, net_dic[a].secret = api[a], secret[a]
```

Let us know if this does not answer your question.

**Comment by jckling** [comment]
It works the former 20 times and then "max tries" occurred again, I'll try to use async calls and set delays between these calls.
Thanks again!!!
