### ISSUE TITLE
fetch_ohlcv returns incomplete data

### ISSUE THREAD

**Issue by fedecaccia** [ccxt/ccxt#2589]
- OS: ubuntu 16.04
- Programming Language version: python3
- CCXT version: last
- Exchange: bittrex
- Method: fetch_ohlcv

Using:
```
import ccxt, numpy, pandas
b=ccxt.bittrex()
data = b.fetch_ohlcv("XMR/BTC", "1m", limit=10)
data = numpy.array(data)
data = data.transpose()
data = {"time": data[0], "open":data[1], "high":data[2], "low":data[3], "close":data[4], "volume":data[5]}
data = pandas.DataFrame(data)
data["time"] = data["time"].apply(lambda x: datetime.fromtimestamp(x/1000.0))
data = data.set_index("time")
print(data)

```

logs:
```
2018-04-06 15:01:00  0.024973  0.024973  0.024973  0.024973   0.058050
2018-04-06 15:03:00  0.024973  0.024973  0.024973  0.024973   0.072460
2018-04-06 15:04:00  0.024973  0.024973  0.024973  0.024973   0.400431
2018-04-06 15:08:00  0.024974  0.024974  0.024973  0.024973   3.199803
2018-04-06 15:10:00  0.024823  0.024823  0.024823  0.024823   0.393238
2018-04-06 15:14:00  0.024921  0.024921  0.024921  0.024921   0.691595
2018-04-06 15:25:00  0.024974  0.024974  0.024974  0.024974   2.519503
2018-04-06 15:26:00  0.024974  0.024974  0.024974  0.024974   0.091726
2018-04-06 15:31:00  0.024974  0.024974  0.024974  0.024974   1.105637
2018-04-06 15:33:00  0.024974  0.024974  0.024974  0.024974   4.091391
```
which is an incomplete data (missing data on 15:32, for example)

**Comment by fedecaccia** [comment]
It also happens using another exchanges, like bitfinex. Further, using bitfinex I get 2016 values.

**Comment by Calambuuur** [comment]
OS Win32
This code returns an error:
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
======= RESTART: C:/Users/XXX/CCXT/fetch_ohlcv.py =======
Traceback (most recent call last):
  File "C:/Users/XXX/CCXT/fetch_ohlcv.py", line 8, in <module>
    data["time"] = data["time"].apply(lambda x: datetime.fromtimestamp(x/1000.0))
  File "C:\Users\Ivanitskii\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\series.py", line 2551, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/src\inference.pyx", line 1521, in pandas._libs.lib.map_infer
  File "C:/Users/XXX/CCXT/fetch_ohlcv.py", line 8, in <lambda>
    data["time"] = data["time"].apply(lambda x: datetime.fromtimestamp(x/1000.0))
NameError: name 'datetime' is not defined
>>> 
What's  - datetime.fromtimestamp(x/1000.0)?

**Comment by Calambuuur** [comment]
Add:
from datetime import datetime

**Comment by fedecaccia** [comment]
@kroitor any idea on what is happening with the ohlcv requested data?

**Comment by kroitor** [comment]
@fedecaccia yeah, this is called a *sparse array*, some exchanges may return the OHLCV with candles missing (it means "no changes for that period since the previous candle"). I'll add this to the docs and will add a couple of methods to pack/unpack sparse arrays.

**Comment by fedecaccia** [comment]
@kroitor that's great, an sparse array is more efficient to manage resources, I thought it was an incomplete data.
