### ISSUE TITLE
Cobinhood: KeyError: 'is_active' within load_markets()

### ISSUE THREAD

**Issue by wntsang4** [ccxt/ccxt#2620]
- OS: Windows 10
- Programming Language version: Python 3.6.4
- CCXT version: 1.12.178
- Exchange: Cobinhoood
- Method: load_markets()

Request: GET https://api.cobinhood.com/v1/market/trading_pairs {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.cobinhood.com/v1/market/trading_pairs 200 {'Date': 'Thu, 19 Apr 2018 09:11:19 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d1c85db9a19841eeec7de2259369f852e1524129079; expires=Fri, 19-Apr-19 09:11:19 GMT; path=/; domain=.cobinhood.com; HttpOnly; Secure', 'Access-Control-Allow-Origin': '*', 'Via': '1.1 google', 'Alt-Svc': 'clear', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '40de3e37fac7a2de-HKG', 'Content-Encoding': 'gzip'} {"success":true,"result":{"trading_pairs":[{"id":"ABT-BTC","base_currency_id":"ABT","quote_currency_id":"BTC","base_max_size":"1175978.06","base_min_size":"23.519","quote_increment":"0.00000001","margin_enabled":false},{"id":"ABT-ETH","base_currency_id":"ABT","quote_currency_id":"ETH","base_max_size":"1175978.06","base_min_size":"23.519","quote_increment":"0.0000001","margin_enabled":false},{"id":"BAR-BTC","base_currency_id":"BAR","quote_currency_id":"BTC","base_max_size":"161073133.645","base_min_size":"3221.462","quote_increment":"0.00000001","margin_enabled":false},{"id":"BAR-ETH","base_currency_id":"BAR","quote_currency_id":"ETH","base_max_size":"161073133.645","base_min_size":"3221.462","quote_increment":"0.0000001","margin_enabled":false},{"id":"BAT-BTC","base_currency_id":"BAT","quote_currency_id":"BTC","base_max_size":"4294591.82","base_min_size":"85.891","quote_increment":"0.00000001","margin_enabled":false},{"id":"BAT-ETH","base_currency_id":"BAT","quote_currency_id":"ETH","base_max_size":"4294591.82","base_min_size":"85.891","quote_increment":"0.0000001","margin_enabled":false},{"id":"BCH-BTC","base_currency_id":"BCH","quote_currency_id":"BTC","base_max_size":"1364.496","base_min_size":"0.027","quote_increment":"0.00000001","margin_enabled":false},{"id":"BCH-ETH","base_currency_id":"BCH","quote_currency_id":"ETH","base_max_size":"1364.496","base_min_size":"0.027","quote_increment":"0.0000001","margin_enabled":false},{"id":"BCH-USDT","base_currency_id":"BCH","quote_currency_id":"USDT","base_max_size":"1364.496","base_min_size":"0.027","quote_increment":"0.01","margin_enabled":false},{"id":"BDG-BTC","base_currency_id":"BDG","quote_currency_id":"BTC","base_max_size":"28416194.957","base_min_size":"568.323","quote_increment":"0.00000001","margin_enabled":false},{"id":"BDG-ETH","base_currency_id":"BDG","quote_currency_id":"ETH","base_max_size":"28416194.957","base_min_size":"568.323","quote_increment":"0.0000001","margin_enabled":false},{"id":"BDG-USDT","base_currency_id":"BDG","quote_currency_id":"USDT","base_max_size":"28416194.957","base_min_size":"568.323","quote_increment":"0.00001","margin_enabled":false},{"id":"BEE-BTC","base_currency_id":"BEE","quote_currency_id":"BTC","base_max_size":"15426504.276","base_min_size":"308.53","quote_increment":"0.00000001","margin_enabled":false},{"id":"BEE-ETH","base_currency_id":"BEE","quote_currency_id":"ETH","base_max_size":"15426504.276","base_min_size":"308.53","quote_increment":"0.0000001","margin_enabled":false},{"id":"BOT-BTC","base_currency_id":"BOT","quote_currency_id":"BTC","base_max_size":"2829278.505","base_min_size":"56.585","quote_increment":"0.00000001","margin_enabled":false},{"id":"BOT-ETH","base_currency_id":"BOT","quote_currency_id":"ETH","base_max_size":"2829278.505","base_min_size":"56.585","quote_increment":"0.0000001","margin_enabled":false},{"id":"BRD-BTC","base_currency_id":"BRD","quote_currency_id":"BTC","base_max_size":"2077382.498","base_min_size":"41.547","quote_increment":"0.00000001","margin_enabled":false},{"id":"BRD-ETH","base_currency_id":"BRD","quote_currency_id":"ETH","base_max_size":"2077382.498","base_min_size":"41.547","quote_increment":"0.0000001","margin_enabled":false},{"id":"BRD-USDT","base_currency_id":"BRD","quote_currency_id":"USDT","base_max_size":"2077382.498","base_min_size":"41.547","quote_increment":"0.0001","margin_enabled":false},{"id":"BTC-USD","base_currency_id":"BTC","quote_currency_id":"USD","base_max_size":"102.261","base_min_size":"0","quote_increment":"0.1","margin_enabled":false},{"id":"BTC-USDT","base_currency_id":"BTC","quote_currency_id":"USDT","base_max_size":"126.787","base_min_size":"0.002","quote_increment":"0.1","margin_enabled":false},{"id":"CGC-BTC","base_currency_id":"CGC","quote_currency_id":"BTC","base_max_size":"1000000","base_min_size":"20","quote_increment":"0.00000001","margin_enabled":false},{"id":"CGC-ETH","base_currency_id":"CGC","quote_currency_id":"ETH","base_max_size":"1000000","base_min_size":"20","quote_increment":"0.0000001","margin_enabled":false},{"id":"CGC-USDT","base_currency_id":"CGC","quote_currency_id":"USDT","base_max_size":"1000000","base_min_size":"20","quote_increment":"0.0001","margin_enabled":false},{"id":"CMT-BTC","base_currency_id":"CMT","quote_currency_id":"BTC","base_max_size":"9845039.084","base_min_size":"196.9","quote_increment":"0.00000001","margin_enabled":false},{"id":"CMT-COB","base_currency_id":"CMT","quote_currency_id":"COB","base_max_size":"9845039.084","base_min_size":"196.9","quote_increment":"0.0001","margin_enabled":false},{"id":"CMT-ETH","base_currency_id":"CMT","quote_currency_id":"ETH","base_max_size":"9845039.084","base_min_size":"196.9","quote_increment":"0.0000001","margin_enabled":false},{"id":"CMT-USDT","base_currency_id":"CMT","quote_currency_id":"USDT","base_max_size":"9845039.084","base_min_size":"196.9","quote_increment":"0.00001","margin_enabled":false},{"id":"COB-BTC","base_currency_id":"COB","quote_currency_id":"BTC","base_max_size":"12038706.85","base_min_size":"240.774","quote_increment":"0.00000001","margin_enabled":false},{"id":"COB-ETH","base_currency_id":"COB","quote_currency_id":"ETH","base_max_size":"12038706.85","base_min_size":"240.774","quote_increment":"0.0000001","margin_enabled":false},{"id":"COB-USD","base_currency_id":"COB","quote_currency_id":"USD","base_max_size":"6679580.522","base_min_size":"0","quote_increment":"0.001","margin_enabled":false},{"id":"COB-USDT","base_currency_id":"COB","quote_currency_id":"USDT","base_max_size":"12038706.85","base_min_size":"240.774","quote_increment":"0.00001","margin_enabled":false},{"id":"CVC-BTC","base_currency_id":"CVC","quote_currency_id":"BTC","base_max_size":"3502234.425","base_min_size":"70.044","quote_increment":"0.00000001","margin_enabled":false},{"id":"CVC-ETH","base_currency_id":"CVC","quote_currency_id":"ETH","base_max_size":"3502234.425","base_min_size":"70.044","quote_increment":"0.0000001","margin_enabled":false},{"id":"DADI-BTC","base_currency_id":"DADI","quote_currency_id":"BTC","base_max_size":"5211536.256","base_min_size":"104.23","quote_increment":"0.00000001","margin_enabled":false},{"id":"DADI-ETH","base_currency_id":"DADI","quote_currency_id":"ETH","base_max_size":"5211536.256","base_min_size":"104.23","quote_increment":"0.0000001","margin_enabled":false},{"id":"DGD-BTC","base_currency_id":"DGD","quote_currency_id":"BTC","base_max_size":"4233.646","base_min_size":"0.084","quote_increment":"0.00000001","margin_enabled":false},{"id":"DGD-ETH","base_currency_id":"DGD","quote_currency_id":"ETH","base_max_size":"4233.646","base_min_size":"0.084","quote_increment":"0.0000001","margin_enabled":false},{"id":"DRGN-BTC","base_currency_id":"DRGN","quote_currency_id":"BTC","base_max_size":"1151500.635","base_min_size":"23.03","quote_increment":"0.00000001","margin_enabled":false},{"id":"DRGN-ETH","base_currency_id":"DRGN","quote_currency_id":"ETH","base_max_size":"1151500.635","base_min_size":"23.03","quote_increment":"0.0000001","margin_enabled":false},{"id":"DXT-BTC","base_currency_id":"DXT","quote_currency_id":"BTC","base_max_size":"31773972.668","base_min_size":"635.479","quote_increment":"0.00000001","margin_enabled":false},{"id":"DXT-ETH","base_currency_id":"DXT","quote_currency_id":"ETH","base_max_size":"31773972.668","base_min_size":"635.479","quote_increment":"0.0000001","margin_enabled":false},{"id":"DXT-USDT","base_currency_id":"DXT","quote_currency_id":"USDT","base_max_size":"31773972.668","base_min_size":"635.479","quote_increment":"0.00001","margin_enabled":false},{"id":"ENJ-BTC","base_currency_id":"ENJ","quote_currency_id":"BTC","base_max_size":"9031057.807","base_min_size":"180.621","quote_increment":"0.00000001","margin_enabled":false},{"id":"ENJ-ETH","base_currency_id":"ENJ","quote_currency_id":"ETH","base_max_size":"9031057.807","base_min_size":"180.621","quote_increment":"0.0000001","margin_enabled":false},{"id":"ENJ-USDT","base_currency_id":"ENJ","quote_currency_id":"USDT","base_max_size":"9031057.807","base_min_size":"180.621","quote_increment":"0.00001","margin_enabled":false},{"id":"EOS-BTC","base_currency_id":"EOS","quote_currency_id":"BTC","base_max_size":"114746.009","base_min_size":"2.294","quote_increment":"0.00000001","margin_enabled":false},{"id":"EOS-ETH","base_currency_id":"EOS","quote_currency_id":"ETH","base_max_size":"114746.009","base_min_size":"2.294","quote_increment":"0.0000001","margin_enabled":false},{"id":"ETH-BTC","base_currency_id":"ETH","quote_currency_id":"BTC","base_max_size":"2029.356","base_min_size":"0.04","quote_increment":"0.0000001","margin_enabled":false},{"id":"ETHOS-BTC","base_currency_id":"ETHOS","quote_currency_id":"BTC","base_max_size":"431851.65","base_min_size":"8.637","quote_increment":"0.00000001","margin_enabled":false},{"id":"ETHOS-ETH","base_currency_id":"ETHOS","quote_currency_id":"ETH","base_max_size":"431851.65","base_min_size":"8.637","quote_increment":"0.0000001","margin_enabled":false},{"id":"ETH-USD","base_currency_id":"ETH","quote_currency_id":"USD","base_max_size":"1182.139","base_min_size":"0","quote_increment":"0.01","margin_enabled":false},{"id":"ETH-USDT","base_currency_id":"ETH","quote_currency_id":"USDT","base_max_size":"2029.356","base_min_size":"0.04","quote_increment":"0.01","margin_enabled":false},{"id":"FLUZ-BTC","base_currency_id":"FLUZ","quote_currency_id":"BTC","base_max_size":"11788741.044","base_min_size":"235.774","quote_increment":"0.00000001","margin_enabled":false},{"id":"FLUZ-ETH","base_currency_id":"FLUZ","quote_currency_id":"ETH","base_max_size":"11788741.044","base_min_size":"235.774","quote_increment":"0.0000001","margin_enabled":false},{"id":"FSN-BTC","base_currency_id":"FSN","quote_currency_id":"BTC","base_max_size":"247021.537","base_min_size":"4.94","quote_increment":"0.00000001","margin_enabled":false},{"id":"FSN-ETH","base_currency_id":"FSN","quote_currency_id":"ETH","base_max_size":"247021.537","base_min_size":"4.94","quote_increment":"0.0000001","margin_enabled":false},{"id":"GAS-BTC","base_currency_id":"GAS","quote_currency_id":"BTC","base_max_size":"54214.058","base_min_size":"1.084","quote_increment":"0.00000001","margin_enabled":false},{"id":"GAS-ETH","base_currency_id":"GAS","quote_currency_id":"ETH","base_max_size":"54214.058","base_min_size":"1.084","quote_increment":"0.0000001","margin_enabled":false},{"id":"GNT-BTC","base_currency_id":"GNT","quote_currency_id":"BTC","base_max_size":"3335323.409","base_min_size":"66.706","quote_increment":"0.00000001","margin_enabled":false},{"id":"GNT-ETH","base_currency_id":"GNT","quote_currency_id":"ETH","base_max_size":"3335323.409","base_min_size":"66.706","quote_increment":"0.0000001","margin_enabled":false},{"id":"GTC-BTC","base_currency_id":"GTC","quote_currency_id":"BTC","base_max_size":"19134471.324","base_min_size":"382.689","quote_increment":"0.00000001","margin_enabled":false},{"id":"GTC-ETH","base_currency_id":"GTC","quote_currency_id":"ETH","base_max_size":"19134471.324","base_min_size":"382.689","quote_increment":"0.0000001","margin_enabled":false},{"id":"GTO-BTC","base_currency_id":"GTO","quote_currency_id":"BTC","base_max_size":"4471811.933","base_min_size":"89.436","quote_increment":"0.00000001","margin_enabled":false},{"id":"GTO-ETH","base_currency_id":"GTO","quote_currency_id":"ETH","base_max_size":"4471811.933","base_min_size":"89.436","quote_increment":"0.0000001","margin_enabled":false},{"id":"INS-BTC","base_currency_id":"INS","quote_currency_id":"BTC","base_max_size":"791414.732","base_min_size":"15.828","quote_increment":"0.00000001","margin_enabled":false},{"id":"INS-ETH","base_currency_id":"INS","quote_currency_id":"ETH","base_max_size":"791414.732","base_min_size":"15.828","quote_increment":"0.0000001","margin_enabled":false},{"id":"IOST-BTC","base_currency_id":"IOST","quote_currency_id":"BTC","base_max_size":"28467643.676","base_min_size":"569.352","quote_increment":"0.00000001","margin_enabled":false},{"id":"IOST-ETH","base_currency_id":"IOST","quote_currency_id":"ETH","base_max_size":"28467643.676","base_min_size":"569.352","quote_increment":"0.0000001","margin_enabled":false},{"id":"LALA-BTC","base_currency_id":"LALA","quote_currency_id":"BTC","base_max_size":"28534333.937","base_min_size":"570.686","quote_increment":"0.00000001","margin_enabled":false},{"id":"LALA-ETH","base_currency_id":"LALA","quote_currency_id":"ETH","base_max_size":"28534333.937","base_min_size":"570.686","quote_increment":"0.0000001","margin_enabled":false},{"id":"LALA-USDT","base_currency_id":"LALA","quote_currency_id":"USDT","base_max_size":"28534333.937","base_min_size":"570.686","quote_increment":"0.00001","margin_enabled":false},{"id":"LTC-BTC","base_currency_id":"LTC","quote_currency_id":"BTC","base_max_size":"7734.909","base_min_size":"0.154","quote_increment":"0.000001","margin_enabled":false},{"id":"LTC-USDT","base_currency_id":"LTC","quote_currency_id":"USDT","base_max_size":"7734.909","base_min_size":"0.154","quote_increment":"0.01","margin_enabled":false},{"id":"LYM-BTC","base_currency_id":"LYM","quote_currency_id":"BTC","base_max_size":"50164036.399","base_min_size":"1003.28","quote_increment":"0.00000001","margin_enabled":false},{"id":"LYM-ETH","base_currency_id":"LYM","quote_currency_id":"ETH","base_max_size":"50164036.399","base_min_size":"1003.28","quote_increment":"0.0000001","margin_enabled":false},{"id":"LYM-USDT","base_currency_id":"LYM","quote_currency_id":"USDT","base_max_size":"50164036.399","base_min_size":"1003.28","quote_increment":"0.000001","margin_enabled":false},{"id":"MANA-BTC","base_currency_id":"MANA","quote_currency_id":"BTC","base_max_size":"11734830.384","base_min_size":"234.696","quote_increment":"0.00000001","margin_enabled":false},{"id":"MANA-ETH","base_currency_id":"MANA","quote_currency_id":"ETH","base_max_size":"11734830.384","base_min_size":"234.696","quote_increment":"0.0000001","margin_enabled":false},{"id":"MCO-BTC","base_currency_id":"MCO","quote_currency_id":"BTC","base_max_size":"160631.216","base_min_size":"3.212","quote_increment":"0.00000001","margin_enabled":false},{"id":"MCO-ETH","base_currency_id":"MCO","quote_currency_id":"ETH","base_max_size":"160631.216","base_min_size":"3.212","quote_increment":"0.0000001","margin_enabled":false},{"id":"MCO-USDT","base_currency_id":"MCO","quote_currency_id":"USDT","base_max_size":"160631.216","base_min_size":"3.212","quote_increment":"0.001","margin_enabled":false},{"id":"MFG-BTC","base_currency_id":"MFG","quote_currency_id":"BTC","base_max_size":"1000000","base_min_size":"20","quote_increment":"0.00000001","margin_enabled":false},{"id":"MFG-ETH","base_currency_id":"MFG","quote_currency_id":"ETH","base_max_size":"1000000","base_min_size":"20","quote_increment":"0.0000001","margin_enabled":false},{"id":"NEO-BTC","base_currency_id":"NEO","quote_currency_id":"BTC","base_max_size":"15044.403","base_min_size":"0.3","quote_increment":"0.00000001","margin_enabled":false},{"id":"NEO-ETH","base_currency_id":"NEO","quote_currency_id":"ETH","base_max_size":"15044.403","base_min_size":"0.3","quote_increment":"0.0000001","margin_enabled":false},{"id":"NGC-BTC","base_currency_id":"NGC","quote_currency_id":"BTC","base_max_size":"1575646.803","base_min_size":"31.512","quote_increment":"0.00000001","margin_enabled":false},{"id":"NGC-ETH","base_currency_id":"NGC","quote_currency_id":"ETH","base_max_size":"1575646.803","base_min_size":"31.512","quote_increment":"0.0000001","margin_enabled":false},{"id":"NTK-BTC","base_currency_id":"NTK","quote_currency_id":"BTC","base_max_size":"1990691.526","base_min_size":"39.813","quote_increment":"0.00000001","margin_enabled":false},{"id":"NTK-ETH","base_currency_id":"NTK","quote_currency_id":"ETH","base_max_size":"1990691.526","base_min_size":"39.813","quote_increment":"0.0000001","margin_enabled":false},{"id":"OCN-BTC","base_currency_id":"OCN","quote_currency_id":"BTC","base_max_size":"106570383.877","base_min_size":"2131.407","quote_increment":"0.00000001","margin_enabled":false},{"id":"OCN-ETH","base_currency_id":"OCN","quote_currency_id":"ETH","base_max_size":"106570383.877","base_min_size":"2131.407","quote_increment":"0.0000001","margin_enabled":false},{"id":"OMG-BTC","base_currency_id":"OMG","quote_currency_id":"BTC","base_max_size":"83123.446","base_min_size":"1.662","quote_increment":"0.00000001","margin_enabled":false},{"id":"OMG-ETH","base_currency_id":"OMG","quote_currency_id":"ETH","base_max_size":"83123.446","base_min_size":"1.662","quote_increment":"0.0000001","margin_enabled":false},{"id":"PAY-BTC","base_currency_id":"PAY","quote_currency_id":"BTC","base_max_size":"883080.183","base_min_size":"17.661","quote_increment":"0.00000001","margin_enabled":false},{"id":"PAY-ETH","base_currency_id":"PAY","quote_currency_id":"ETH","base_max_size":"883080.183","base_min_size":"17.661","quote_increment":"0.0000001","margin_enabled":false},{"id":"QTUM-BTC","base_currency_id":"QTUM","quote_currency_id":"BTC","base_max_size":"60842.794","base_min_size":"1.216","quote_increment":"0.0000001","margin_enabled":false},{"id":"QTUM-ETH","base_currency_id":"QTUM","quote_currency_id":"ETH","base_max_size":"60842.794","base_min_size":"1.216","quote_increment":"0.000001","margin_enabled":false},{"id":"QTUM-USDT","base_currency_id":"QTUM","quote_currency_id":"USDT","base_max_size":"60842.794","base_min_size":"1.216","quote_increment":"0.01","margin_enabled":false},{"id":"REN-BTC","base_currency_id":"REN","quote_currency_id":"BTC","base_max_size":"22091294.483","base_min_size":"441.825","quote_increment":"0.00000001","margin_enabled":false},{"id":"REN-ETH","base_currency_id":"REN","quote_currency_id":"ETH","base_max_size":"22091294.483","base_min_size":"441.825","quote_increment":"0.0000001","margin_enabled":false},{"id":"REP-BTC","base_currency_id":"REP","quote_currency_id":"BTC","base_max_size":"35851.674","base_min_size":"0.717","quote_increment":"0.00000001","margin_enabled":false},{"id":"REP-ETH","base_currency_id":"REP","quote_currency_id":"ETH","base_max_size":"35851.674","base_min_size":"0.717","quote_increment":"0.0000001","margin_enabled":false},{"id":"RFR-BTC","base_currency_id":"RFR","quote_currency_id":"BTC","base_max_size":"130013989.505","base_min_size":"2600.279","quote_increment":"0.00000001","margin_enabled":false},{"id":"RFR-ETH","base_currency_id":"RFR","quote_currency_id":"ETH","base_max_size":"130013989.505","base_min_size":"2600.279","quote_increment":"0.0000001","margin_enabled":false},{"id":"SHPING-BTC","base_currency_id":"SHPING","quote_currency_id":"BTC","base_max_size":"1000000","base_min_size":"20","quote_increment":"0.00000001","margin_enabled":false},{"id":"SHPING-ETH","base_currency_id":"SHPING","quote_currency_id":"ETH","base_max_size":"1000000","base_min_size":"20","quote_increment":"0.0000001","margin_enabled":false},{"id":"SNT-BTC","base_currency_id":"SNT","quote_currency_id":"BTC","base_max_size":"9266294.779","base_min_size":"185.325","quote_increment":"0.00000001","margin_enabled":false},{"id":"SNT-ETH","base_currency_id":"SNT","quote_currency_id":"ETH","base_max_size":"9266294.779","base_min_size":"185.325","quote_increment":"0.0000001","margin_enabled":false},{"id":"SPHTX-BTC","base_currency_id":"SPHTX","quote_currency_id":"BTC","base_max_size":"4005254.894","base_min_size":"80.105","quote_increment":"0.00000001","margin_enabled":false},{"id":"SPHTX-ETH","base_currency_id":"SPHTX","quote_currency_id":"ETH","base_max_size":"4005254.894","base_min_size":"80.105","quote_increment":"0.0000001","margin_enabled":false},{"id":"STK-BTC","base_currency_id":"STK","quote_currency_id":"BTC","base_max_size":"20658553.364","base_min_size":"413.171","quote_increment":"0.00000001","margin_enabled":false},{"id":"STK-ETH","base_currency_id":"STK","quote_currency_id":"ETH","base_max_size":"20658553.364","base_min_size":"413.171","quote_increment":"0.0000001","margin_enabled":false},{"id":"TBAR-BTC","base_currency_id":"TBAR","quote_currency_id":"BTC","base_max_size":"2105431.592","base_min_size":"42.108","quote_increment":"0.00000001","margin_enabled":false},{"id":"TBAR-ETH","base_currency_id":"TBAR","quote_currency_id":"ETH","base_max_size":"2105431.592","base_min_size":"42.108","quote_increment":"0.0000001","margin_enabled":false},{"id":"TRX-BTC","base_currency_id":"TRX","quote_currency_id":"BTC","base_max_size":"25317737.606","base_min_size":"506.354","quote_increment":"0.00000001","margin_enabled":false},{"id":"TRX-ETH","base_currency_id":"TRX","quote_currency_id":"ETH","base_max_size":"25317737.606","base_min_size":"506.354","quote_increment":"0.0000001","margin_enabled":false},{"id":"UTNP-BTC","base_currency_id":"UTNP","quote_currency_id":"BTC","base_max_size":"32019262.788","base_min_size":"640.385","quote_increment":"0.00000001","margin_enabled":false},{"id":"UTNP-ETH","base_currency_id":"UTNP","quote_currency_id":"ETH","base_max_size":"32019262.788","base_min_size":"640.385","quote_increment":"0.0000001","margin_enabled":false},{"id":"UTNP-USDT","base_currency_id":"UTNP","quote_currency_id":"USDT","base_max_size":"32019262.788","base_min_size":"640.385","quote_increment":"0.00001","margin_enabled":false},{"id":"WTC-BTC","base_currency_id":"WTC","quote_currency_id":"BTC","base_max_size":"92564.309","base_min_size":"1.851","quote_increment":"0.00000001","margin_enabled":false},{"id":"WTC-ETH","base_currency_id":"WTC","quote_currency_id":"ETH","base_max_size":"92564.309","base_min_size":"1.851","quote_increment":"0.0000001","margin_enabled":false},{"id":"ZRX-BTC","base_currency_id":"ZRX","quote_currency_id":"BTC","base_max_size":"1454207.02","base_min_size":"29.084","quote_increment":"0.00000001","margin_enabled":false},{"id":"ZRX-ETH","base_currency_id":"ZRX","quote_currency_id":"ETH","base_max_size":"1454207.02","base_min_size":"29.084","quote_increment":"0.0000001","margin_enabled":false}]}}

Traceback (most recent call last):
  File "test.py", line 73, in <module>
    print(cobinhood.fetch_balance())
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\cobinhood.py", line 357, in fetch_balance
    self.load_markets()
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 870, in load_markets
    markets = self.fetch_markets()
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\cobinhood.py", line 206, in fetch_markets
    'active': market['is_active'],
KeyError: 'is_active'

Code:
cobinhood = ccxt.cobinhood({
    'apiKey': APIKEY,
    'enableRateLimit': True,
    'verbose': True,
})
print(cobinhood.fetch_balance())

**Comment by wntsang4** [comment]
It throws another KeyError after the fix:

Traceback (most recent call last):
  File "sphtx_arb_new.py", line 351, in <module>
    SphtxArb().main()
  File "sphtx_arb_new.py", line 51, in __init__
    self.update_min_qty()                          # to prevent rejection from exchage due to order's size is too small
  File "sphtx_arb_new.py", line 62, in update_min_qty
    obj.exchange.load_markets()
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 874, in load_markets
    currencies = self.fetch_currencies()
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\cobinhood.py", line 141, in fetch_currencies
    fundingNotFrozen = not currency['funding_frozen']
KeyError: 'funding_frozen'
