### ISSUE TITLE
Bitmex Orders not getting placed

### ISSUE THREAD

**Issue by bitsquant** [ccxt/ccxt#2636]
I am using CCXT Javascript cdn library to place an order but i am unable to do so,Though  I am able to fetch my account balance and GET by recent trades. This is my  Code

```
<html>
<head>
 <title>
 </title>
<script type="text/javascript" src="https://unpkg.com/ccxt"></script>
 </style>
</head>
 <body>
  <script type="text/javascript">
var bitmex = new ccxt.bitmex ({
    apiKey: 'xxxxxxxxxxxxxxxx',
    secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
})
console.log (bitmex.id);
var symbol = '.XBT' ;
var type = 'StopLimit'  ;
var side = 'buy'  ;
var amount = 1.0 ;
var price = 7500.0 ;
var params = {
    'stopPx': 7000.0
};
var order = bitmex.create_limit_buy_order(symbol, type, side, amount, price, params)
console.log (order);
</script>

 </body>
</html>
```

error:

```
Exchange.js:316 POST https://www.bitmex.com/api/v1/order?symbol=XBTUSD&side=Buy&orderQty=StopLimit&ordType=Limit&price=buy 403 ()
executeRestRequest @ Exchange.js:316
fetch @ Exchange.js:401
fetch2 @ Exchange.js:410
request @ Exchange.js:414
partial @ Exchange.js:363
createOrder @ bitmex.js:493
async function (async)
createOrder @ bitmex.js:498
createLimitBuyOrder @ Exchange.js:954
(anonymous) @ tweet.html:42
errors.js:54 Uncaught (in promise) Object.assign: bitmex POST https://www.bitmex.com/api/v1/order?symbol=XBTUSD&side=Buy&orderQty=StopLimit&ordType=Limit&price=buy 403   (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at bitmex.defaultErrorHandler (https://unpkg.com/ccxt@1.13.24/build/ccxt.browser.js:2003:15)
    at response.text.then (https://unpkg.com/ccxt@1.13.24/build/ccxt.browser.js:2028:18)
```

Any kind of help is appreciated

**Comment by kroitor** [comment]
Hi! What's your browser and what's the version number of your browser ?

**Comment by kroitor** [comment]
> var symbol = '.XBT' ;

There's no such active symbol with BitMEX... Their dot in `.XBT` means that the symbol is delisted. If you want BTC/USD – you should use symbol = `BTC/USD`.

More about it: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

@bitsquant let us know if this does not answer your question. Thx!

**Comment by kroitor** [comment]
```
mbp:ccxt igorkroitor$ node examples/js/symbols bitmex
Instantiating bitmex exchange

Symbols:

limits          | precision       | tierBased | percentage | taker   | maker    | id          | symbol      | base | quote | active | type   | spot  | swap  | future | prediction | info
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[object Object] | [object Object] |           |            | null    | null     | .ADAXBT     | .ADAXBT     | ADA  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .ADAXBT30M  | .ADAXBT30M  | ADA  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BCHXBT     | .BCHXBT     | BCH  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BCHXBT30M  | .BCHXBT30M  | BCH  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BVOL       | .BVOL       | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BVOL10M    | .BVOL10M    | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BVOL1H     | .BVOL1H     | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BVOL24H    | .BVOL24H    | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BVOL30M    | .BVOL30M    | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BVOL7D     | .BVOL7D     | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BXBT       | .BXBT       | BTC  | USD   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BXBT30M    | .BXBT30M    | BTC  | USD   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BXBTJPY    | .BXBTJPY    | BTC  | JPY   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .BXBTJPY30M | .BXBTJPY30M | BTC  | JPY   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .DASHXBT    | .DASHXBT    | DASH | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .DASHXBT30M | .DASHXBT30M | DASH | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .ETCXBT     | .ETCXBT     | ETC  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .ETCXBT30M  | .ETCXBT30M  | ETC  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .ETHBON     | .ETHBON     | ETH  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .ETHBON2H   | .ETHBON2H   | ETH  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .ETHBON8H   | .ETHBON8H   | ETH  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .ETHXBT     | .ETHXBT     | ETH  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .ETHXBT30M  | .ETHXBT30M  | ETH  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .EVOL7D     | .EVOL7D     | ETH  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .JPYBON     | .JPYBON     | JPY  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .JPYBON2H   | .JPYBON2H   | JPY  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .JPYBON8H   | .JPYBON8H   | JPY  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .KRWBON     | .KRWBON     | KRW  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .KRWBON2H   | .KRWBON2H   | KRW  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .KRWBON8H   | .KRWBON8H   | KRW  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .LTCXBT     | .LTCXBT     | LTC  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .LTCXBT30M  | .LTCXBT30M  | LTC  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .NEOXBT     | .NEOXBT     | NEO  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .NEOXBT30M  | .NEOXBT30M  | NEO  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .USDBON     | .USDBON     | USD  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .USDBON2H   | .USDBON2H   | USD  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .USDBON8H   | .USDBON8H   | USD  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBT        | .XBT        | BTC  | USD   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBT30M     | .XBT30M     | BTC  | USD   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTBON     | .XBTBON     | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTBON2H   | .XBTBON2H   | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTBON8H   | .XBTBON8H   | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTJPY     | .XBTJPY     | BTC  | JPY   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTJPY30M  | .XBTJPY30M  | BTC  | JPY   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTJPYPI   | .XBTJPYPI   | XBJ  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTJPYPI2H | .XBTJPYPI2H | XBJ  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTJPYPI8H | .XBTJPYPI8H | XBJ  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTKRW     | .XBTKRW     | BTC  | KRW   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTKRW30M  | .XBTKRW30M  | BTC  | KRW   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTKRWPI   | .XBTKRWPI   | XBK  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTKRWPI2H | .XBTKRWPI2H | XBK  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTKRWPI8H | .XBTKRWPI8H | XBK  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTUSDPI   | .XBTUSDPI   | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTUSDPI2H | .XBTUSDPI2H | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XBTUSDPI8H | .XBTUSDPI8H | BTC  | XXX   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XLMXBT     | .XLMXBT     | XLM  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XLMXBT30M  | .XLMXBT30M  | XLM  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XMRXBT     | .XMRXBT     | XMR  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XMRXBT30M  | .XMRXBT30M  | XMR  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XRPXBT     | .XRPXBT     | XRP  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .XRPXBT30M  | .XRPXBT30M  | XRP  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .ZECXBT     | .ZECXBT     | ZEC  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | null    | null     | .ZECXBT30M  | .ZECXBT30M  | ZEC  | BTC   | false  | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | 0.0025  | -0.0005  | ADAM18      | ADAM18      | ADA  | BTC   | true   | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | 0.0025  | -0.0005  | BCHM18      | BCHM18      | BCH  | BTC   | true   | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | 0.00075 | -0.00025 | XBTUSD      | BTC/USD     | BTC  | USD   | true   | swap   | false | true  | false  | false      | [object Object]
[object Object] | [object Object] |           |            | 0.0025  | -0.0005  | ETHM18      | ETHM18      | ETH  | BTC   | true   | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | 0.0025  | -0.0005  | LTCM18      | LTCM18      | LTC  | BTC   | true   | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | 0.00075 | -0.00025 | XBTM18      | XBTM18      | BTC  | USD   | true   | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | 0.00075 | -0.00025 | XBTU18      | XBTU18      | BTC  | USD   | true   | future | false | false | true   | false      | [object Object]
[object Object] | [object Object] |           |            | 0.0025  | -0.0005  | XRPM18      | XRPM18      | XRP  | BTC   | true   | future | false | false | true   | false      | [object Object]

---------------------------------------------------------------

Currencies:

id   | code | precision
-----------------------
ADA  | ADA  | 0
BCH  | BCH  | 0
BTC  | BTC  | 16
DASH | DASH |
ETC  | ETC  |
ETH  | ETH  | 0
JPY  | JPY  | 2
KRW  | KRW  | 0
LTC  | LTC  | 0
NEO  | NEO  |
USD  | USD  | 2
XBJ  | XBJ  |
XBK  | XBK  |
XLM  | XLM  |
XMR  | XMR  |
XRP  | XRP  | 0
XXX  | XXX  | 6
ZEC  | ZEC  |

---------------------------------------------------------------
bitmex has 71 symbols and 18 currencies
```

**Comment by bitsquant** [comment]
thank you for the kind reply .I am using Chrome Version 65.0.3325.181 and i have tried with BTC/USD as a symbol also but getting same error.

**Comment by Amarchuk** [comment]
I experienced exactly the same issue using python version of `ccxt`. I really new to field, but can assume that it will be difficult to debug this because `403 Access Forbidden` can be obtained as a result of some bitmex terms violation or account-related (like rate-limiting).

**Comment by bitsquant** [comment]
@kroitor any update?

**Comment by kroitor** [comment]
@bitsquant 

There are errors in your code:

```JavaScript
<html>
<head>
 <title>
 </title>
<script type="text/javascript" src="https://unpkg.com/ccxt"></script>
 </style>
</head>
 <body>
  <script type="text/javascript">
var bitmex = new ccxt.bitmex ({
    apiKey: 'xxxxxxxxxxxxxxxx',
    secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
})
console.log (bitmex.id);
var symbol = '.XBT' ;
var type = 'StopLimit'  ;   // ←------------------------- here, we support 'limit' or 'market'
var side = 'buy'  ;
var amount = 1.0 ;
var price = 7500.0 ;
var params = {
    'stopPx': 7000.0
};

//                                        ↓ and here, you're using the wrong arguments for that method

var order = bitmex.create_limit_buy_order(symbol, type, side, amount, price, params)
console.log (order);
</script>

 </body>
</html>```

The `createLimitBuyOrder` accepts `(symbol, amount, price, params)`, you don't have to specify `type = 'limit'` and `'side = 'buy'`.

If you want to specify those two params, then you should be using

```JavaScript
// see any system here ↓ ?
createOrder (symbol, type, side, amount, price, params)
createLimitOrder (symbol, side, amount, price, params)
createLimitBuyOrder (symbol, amount, price, params)
```
