### ISSUE TITLE
Gate.io: parseOrder not implemented

### ISSUE THREAD

**Issue by ko0f** [ccxt/ccxt#2647]
It seems that `parseOrder` is not implemented in `gateio.js`, but being called when trying to fetchOpenOrders, leading to an exception:
```
TypeError: this.parseOrder is not a function
    at Object.values.map.order (/.../ccxt/js/base/Exchange.js:897:64)
    at Array.map (<anonymous>)
    at gateio.parseOrders (/.../ccxt/js/base/Exchange.js:897:45)
    at gateio.fetchOpenOrders (/.../ccxt/js/gateio.js:134:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

- OS: macOS High Sierra
- Programming Language version: Node.JS
- CCXT version: 1.13.32
- Exchange: Gate.io
- Method: fetchOpenOrders

**Comment by ko0f** [comment]
Nvm, that's my bug. `fetchOpenOrders` is not implemented on the original ccxt source.

**Comment by kroitor** [comment]
@ko0f thx for reporting back! More about it: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

**Comment by kroitor** [comment]
Related: #2673
