### ISSUE TITLE
Check address issue

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2662]
The STEEM currency has shortname as address. Actually I looked through check_address method and it is sort of magic, almost useless checking (except empty\None string)

    > self.check_address(address) .     The only 'address' is not enough for checking it. Maybe we should pass 'currency' variable there? And do hardcoded checking in base class exchange.py?  What do you think? Of course it is shitty-code, but it might be a simple solution.

- Exchange: binance
- Method: withdraw

>>:Traceback (most recent call last):

    return await self._ccxtexchange.withdraw(currency, volume, address, tag, params)
  File "/Users/user/Documents/Bitcoin/ccxt/async/binance.py", line 740, in withdraw
    self.check_address(address)
  File "/Users/user/Documents/Bitcoin/ccxt/base/exchange.py", line 794, in check_address
    self.raise_error(InvalidAddress, details='address is invalid or has less than ' + str(self.minFundingAddressLength) + ' characters: "' + str(address) + '"')
  File "/Users/user/Documents/Bitcoin/ccxt/base/exchange.py", line 288, in raise_error
    raise exception_type(output)
ccxt.base.errors.InvalidAddress: binance address is invalid or has less than 10 characters: "bittrex"

Exception:  ('binance address is invalid or has less than 10 characters: "bittrex"',)

**Comment by kroitor** [comment]
Can you, plz post: `self_.ccxtexchange.verbose = true; return return await self._ccxtexchange.withdraw(currency, volume, address, tag, params)` ?

**Comment by alexsith** [comment]
Thanks for fix.
https://www.binance.com/assetWithdraw/getAllAsset.html here is amazing information about regExp for checking addresses for every coin in binance. it might be usefull for check_address function

**Comment by kroitor** [comment]
@alexsith thx for sharing it!
