### ISSUE TITLE
Btctrade.im Error

### ISSUE THREAD

**Issue by kentwind23** [ccxt/ccxt#2689]
MAC OS
PYTHON 3.6.5
CCXT 1.13.48
BTCTRADE.IM

Hi,I am able to fetch ticker from btctrade.im,but when I tried to place order and fetch balance, it failed.

Code:

import ccxt

bim = ccxt.btctradeim({
    'apiKey': '***
    'secret': '**','','verbose':True,'enableRateLimit': True})

EB = bim.fetch_ticker("LXT/BTC")

order = bim.create_order(symbol='LXT/BTC', type='limit', side='sell', amount=200, price=0.0000023)

bal = bim.fetch_balance()

print(bal)
print(order)

*************************************************************************************

Response: POST https://api.btctrade.im/api/v1/trade_add/btc 500 {'Date': 'Sat, 28 Apr 2018 04:41:16 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d3579b1fa1524890475; expires=Sun, 28-Apr-19 04:41:15 GMT; path=/; domain=.btctrade.im; HttpOnly, lang=zh_CN; expires=Tue, 25-Apr-2028 04:41:16 GMT; Max-Age=315360000; path=/', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4126db023ba3a3f9-PIT'} 
    response.raise_for_status()
  File "/Users/qg/PycharmProjects/cccc/venv/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.btctrade.im/api/v1/trade_add/btc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/qg/PycharmProjects/cccc/venv/btctradeim.py", line 10, in <module>
    order = bim.create_order(symbol='LXT/BTC', type='limit', side='sell', amount=200, price=0.0000023)
  File "/Users/qg/PycharmProjects/cccc/venv/lib/python3.6/site-packages/ccxt/coinegg.py", line 392, in create_order
    }, params))
  File "/Users/qg/PycharmProjects/cccc/venv/lib/python3.6/site-packages/ccxt/btctradeim.py", line 41, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/qg/PycharmProjects/cccc/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 303, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/qg/PycharmProjects/cccc/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 377, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "/Users/qg/PycharmProjects/cccc/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 406, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/Users/qg/PycharmProjects/cccc/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 288, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: btctradeim https://api.btctrade.im/api/v1/trade_add/btc POST 500 Server Error: Internal Server Error for url: https://api.btctrade.im/api/v1/trade_add/btc 

Process finished with exit code 1

**Comment by kroitor** [comment]
Hi! Sorry for a long wait. Can you please post your verbose output with the Request part included (without your keys, of course). For some reason you posted just the Response part. We need both in order to help. Thx!
