### ISSUE TITLE
Kucoin withdrawal API returns "This API Key was disabled", despite being enabled/verified

### ISSUE THREAD

**Issue by dqian** [ccxt/ccxt#2715]
- Programming Language version: Python3.6
- CCXT version: 0.1.11
- Exchange: Kucoin
- Method: `withdraw` / `privatePostAccountCoinWithdrawApply`

 I've tried creating new API credentials and the same issue persists. I've verified and enabled all API keys for Kucoin on my account. This behavior is happening on other Kucoin/Python libraries as well such as [python-kucoin](https://github.com/sammchardy/python-kucoin). The curious thing is that other authenticated calls to the Kucoin API such as checking balance and trading succeed. It's only the withdrawal API request that triggers this error.

I'm wondering if anyone else is experiencing the same issue and if there is some diagnosis or workaround. The issue could possibly be on the exchange side but Kucoin support is unable to provide technical insight into their API.

example:
```
kucoin.withdraw('OMG', 1, '0x80f071b5cec902505c2e8c10f9baa6a340769620')
```

output
```
Request: POST https://api.kucoin.com/v1/account/OMG/withdraw/apply?address=0x80f071b5cec902505c2e8c10f9baa6a340769620&amount=1 {'KC-API-KEY': '5ae...', 'KC-API-NONCE': '1525136737366', 'KC-API-SIGNATURE': '04e11c0ca6d96b4...', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} address=0x80f071b5cec902505c2e8c10f9baa6a340769620&amount=1

Response: POST https://api.kucoin.com/v1/account/OMG/withdraw/apply?address=0x80f071b5cec902505c2e8c10f9baa6a340769620&amount=1 200 {'Date': 'Tue, 01 May 2018 01:05:37 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400'} {"code":"UNAUTH","msg":"This API Key was disabled","success":false,"timestamp":1525136737479}
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ccxt/kucoin.py", line 846, in withdraw
    }, params))
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 306, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 303, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 383, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "/usr/local/lib/python3.6/site-packages/ccxt/kucoin.py", line 925, in handle_errors
    self.throw_exception_on_error(json.loads(body))
  File "/usr/local/lib/python3.6/site-packages/ccxt/kucoin.py", line 904, in throw_exception_on_error
    raise AuthenticationError(feedback)
ccxt.base.errors.AuthenticationError: kucoin {"code":"UNAUTH","msg":"This API Key was disabled","success":false,"timestamp":1525136737479}
```

**Comment by dqian** [comment]
This issue may be related to Kucoin's new KYC policies...

**Comment by crackfoo** [comment]
Their news fee says api withdraw is disabled for upgrading or some such...

**Comment by dqian** [comment]
thanks @crackfoo, do you have a link I could read?

**Comment by frosty00** [comment]
kucoin has the same error atm. It just means they are performing system upgrades.

```
kucoin {"code":"UNAUTH","msg":"This API Key was disabled","success":false,"timestamp":1525166680944}
```

**Comment by kroitor** [comment]
I think the answer of @frosty00 explains it quite well. 
@dqian Closing this for now, if you don't mind. Feel free to reopen it if needed. 
Thanks!
