### ISSUE TITLE
Indodax: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by MrBoba** [ccxt/ccxt#2728]
- OS: Ubuntu 16.04
- Programming Language version: Python 3.6
- CCXT version: 1.13.66
- Exchange: indodax
- Method: .handle_errors()

When we receive non json response, like html (for example, answer from firewall ...), variable "response" is None in line 402, and it hasn't attribute .keys()

```
Traceback (most recent call last):
  ...
  File "/home/.../venv/lib/python3.6/site-packages/ccxt/indodax.py", line 104, in fetch_balance
    response = self.privatePostGetInfo()
  File "/home/.../venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 306, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/.../venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 303, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/.../venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 376, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "/home/.../venv/lib/python3.6/site-packages/ccxt/indodax.py", line 402, in handle_errors
    if not('success' in list(response.keys())):
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by kroitor** [comment]
This is fixed in the most recent version of ccxt. 

```
mbp:ccxt igorkroitor$ python examples/py/symbols.py indodax
Instantiating indodax exchange
indodax has 23 symbols: ['BCH/IDR', 'BTC/IDR', 'BTG/IDR', 'BTS/BTC', 'DASH/BTC', 'DOGE/BTC', 'ETC/IDR', 'ETH/BTC', 'ETH/IDR', 'IGNIS/IDR', 'LTC/BTC', 'LTC/IDR', 'NXT/BTC', 'NXT/IDR', 'TEN/BTC', 'TEN/IDR', 'WAVES/IDR', 'XEM/BTC', 'XLM/BTC', 'XLM/IDR', 'XRP/BTC', 'XRP/IDR', 'XZC/IDR']
{'taker': 0.003, 'baseId': 'bch', 'limits': {'amount': {'max': None, 'min': 0.001}}, 'quote': 'IDR', 'symbol': 'BCH/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'bch_idr', 'fee_loaded': False, 'base': 'BCH', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'btc', 'limits': {'amount': {'max': None, 'min': 0.0001}}, 'quote': 'IDR', 'symbol': 'BTC/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'btc_idr', 'fee_loaded': False, 'base': 'BTC', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'btg', 'limits': {'amount': {'max': None, 'min': 0.01}}, 'quote': 'IDR', 'symbol': 'BTG/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'btg_idr', 'fee_loaded': False, 'base': 'BTG', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'bts', 'limits': {'amount': {'max': None, 'min': 0.01}}, 'quote': 'BTC', 'symbol': 'BTS/BTC', 'tierBased': False, 'precision': {'amount': 8, 'price': 8}, 'id': 'bts_btc', 'fee_loaded': False, 'base': 'BTS', 'quoteId': 'btc', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'drk', 'limits': {'amount': {'max': None, 'min': 0.01}}, 'quote': 'BTC', 'symbol': 'DASH/BTC', 'tierBased': False, 'precision': {'amount': 8, 'price': 6}, 'id': 'drk_btc', 'fee_loaded': False, 'base': 'DASH', 'quoteId': 'btc', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'doge', 'limits': {'amount': {'max': None, 'min': 1}}, 'quote': 'BTC', 'symbol': 'DOGE/BTC', 'tierBased': False, 'precision': {'amount': 8, 'price': 8}, 'id': 'doge_btc', 'fee_loaded': False, 'base': 'DOGE', 'quoteId': 'btc', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'etc', 'limits': {'amount': {'max': None, 'min': 0.1}}, 'quote': 'IDR', 'symbol': 'ETC/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'etc_idr', 'fee_loaded': False, 'base': 'ETC', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'eth', 'limits': {'amount': {'max': None, 'min': 0.001}}, 'quote': 'BTC', 'symbol': 'ETH/BTC', 'tierBased': False, 'precision': {'amount': 8, 'price': 5}, 'id': 'eth_btc', 'fee_loaded': False, 'base': 'ETH', 'quoteId': 'btc', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'eth', 'limits': {'amount': {'max': None, 'min': 0.01}}, 'quote': 'IDR', 'symbol': 'ETH/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'eth_idr', 'fee_loaded': False, 'base': 'ETH', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'ignis', 'limits': {'amount': {'max': None, 'min': 1}}, 'quote': 'IDR', 'symbol': 'IGNIS/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'ignis_idr', 'fee_loaded': False, 'base': 'IGNIS', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'ltc', 'limits': {'amount': {'max': None, 'min': 0.01}}, 'quote': 'BTC', 'symbol': 'LTC/BTC', 'tierBased': False, 'precision': {'amount': 8, 'price': 6}, 'id': 'ltc_btc', 'fee_loaded': False, 'base': 'LTC', 'quoteId': 'btc', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'ltc', 'limits': {'amount': {'max': None, 'min': 0.01}}, 'quote': 'IDR', 'symbol': 'LTC/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'ltc_idr', 'fee_loaded': False, 'base': 'LTC', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'nxt', 'limits': {'amount': {'max': None, 'min': 0.01}}, 'quote': 'BTC', 'symbol': 'NXT/BTC', 'tierBased': False, 'precision': {'amount': 8, 'price': 8}, 'id': 'nxt_btc', 'fee_loaded': False, 'base': 'NXT', 'quoteId': 'btc', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'nxt', 'limits': {'amount': {'max': None, 'min': 5}}, 'quote': 'IDR', 'symbol': 'NXT/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'nxt_idr', 'fee_loaded': False, 'base': 'NXT', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'ten', 'limits': {'amount': {'max': None, 'min': 0.01}}, 'quote': 'BTC', 'symbol': 'TEN/BTC', 'tierBased': False, 'precision': {'amount': 8, 'price': 8}, 'id': 'ten_btc', 'fee_loaded': False, 'base': 'TEN', 'quoteId': 'btc', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'ten', 'limits': {'amount': {'max': None, 'min': 5}}, 'quote': 'IDR', 'symbol': 'TEN/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'ten_idr', 'fee_loaded': False, 'base': 'TEN', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'waves', 'limits': {'amount': {'max': None, 'min': 0.1}}, 'quote': 'IDR', 'symbol': 'WAVES/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'waves_idr', 'fee_loaded': False, 'base': 'WAVES', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'nem', 'limits': {'amount': {'max': None, 'min': 1}}, 'quote': 'BTC', 'symbol': 'XEM/BTC', 'tierBased': False, 'precision': {'amount': 8, 'price': 8}, 'id': 'nem_btc', 'fee_loaded': False, 'base': 'XEM', 'quoteId': 'btc', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'str', 'limits': {'amount': {'max': None, 'min': 0.01}}, 'quote': 'BTC', 'symbol': 'XLM/BTC', 'tierBased': False, 'precision': {'amount': 8, 'price': 8}, 'id': 'str_btc', 'fee_loaded': False, 'base': 'XLM', 'quoteId': 'btc', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'str', 'limits': {'amount': {'max': None, 'min': 20}}, 'quote': 'IDR', 'symbol': 'XLM/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'str_idr', 'fee_loaded': False, 'base': 'XLM', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'xrp', 'limits': {'amount': {'max': None, 'min': 0.01}}, 'quote': 'BTC', 'symbol': 'XRP/BTC', 'tierBased': False, 'precision': {'amount': 8, 'price': 8}, 'id': 'xrp_btc', 'fee_loaded': False, 'base': 'XRP', 'quoteId': 'btc', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'xrp', 'limits': {'amount': {'max': None, 'min': 10}}, 'quote': 'IDR', 'symbol': 'XRP/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'xrp_idr', 'fee_loaded': False, 'base': 'XRP', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
{'taker': 0.003, 'baseId': 'xzc', 'limits': {'amount': {'max': None, 'min': 0.1}}, 'quote': 'IDR', 'symbol': 'XZC/IDR', 'tierBased': False, 'precision': {'amount': 8, 'price': 0}, 'id': 'xzc_idr', 'fee_loaded': False, 'base': 'XZC', 'quoteId': 'idr', 'percentage': True, 'maker': 0}
id              symbol          base            quote
bch_idr         BCH/IDR         BCH             IDR
btc_idr         BTC/IDR         BTC             IDR
btg_idr         BTG/IDR         BTG             IDR
bts_btc         BTS/BTC         BTS             BTC
drk_btc         DASH/BTC        DASH            BTC
doge_btc        DOGE/BTC        DOGE            BTC
etc_idr         ETC/IDR         ETC             IDR
eth_btc         ETH/BTC         ETH             BTC
eth_idr         ETH/IDR         ETH             IDR
ignis_idr       IGNIS/IDR       IGNIS           IDR
ltc_btc         LTC/BTC         LTC             BTC
ltc_idr         LTC/IDR         LTC             IDR
nxt_btc         NXT/BTC         NXT             BTC
nxt_idr         NXT/IDR         NXT             IDR
ten_btc         TEN/BTC         TEN             BTC
ten_idr         TEN/IDR         TEN             IDR
waves_idr       WAVES/IDR       WAVES           IDR
nem_btc         XEM/BTC         XEM             BTC
str_btc         XLM/BTC         XLM             BTC
str_idr         XLM/IDR         XLM             IDR
xrp_btc         XRP/BTC         XRP             BTC
xrp_idr         XRP/IDR         XRP             IDR
xzc_idr         XZC/IDR         XZC             IDR
mbp:ccxt igorkroitor$
```

Thank you!
