### ISSUE TITLE
python async cannot get right response

### ISSUE THREAD

**Issue by JustBbing** [ccxt/ccxt#2770]
- OS:    win10
- Programming Language version:     python 3.6.1
- CCXT version:    1.13.88
- Exchange:     huobipro
- Method:     fetch_balance
when I fetch balance or fetch orderbook，i got some problem，but when i change huobipro to bitumb, the same code works,here is my code，i don't know What went wrong? Thanks in advance.

async def print_exchange_ticker():
    poloniex = ccxt.huobipro(
        {
            'apiKey': "xx",
            'secret': "xx",
            'verbose': True
        }
    )
    print(await poloniex.fetch_balance())
    await poloniex.close()
asyncio.get_event_loop().run_until_complete(print_exchange_ticker())

and hear is the response:

Request: GET https://api.huobipro.com/v1/common/symbols {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):
  File "C:\python\python36\lib\site-packages\ccxt\async\base\exchange.py", line 123, in fetch
    proxy=self.aiohttp_proxy) as response:
  File "C:\python\python36\lib\site-packages\aiohttp\client.py", line 783, in __aenter__
    self._resp = await self._coro
  File "C:\python\python36\lib\site-packages\aiohttp\client.py", line 408, in _request
    break
  File "C:\python\python36\lib\site-packages\aiohttp\helpers.py", line 670, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/pythonpro/py3/four_modules/cct_use/for_use.py", line 77, in <module>
    asyncio.get_event_loop().run_until_complete(print_exchange_ticker())
  File "C:\python\python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:/pythonpro/py3/four_modules/cct_use/for_use.py", line 75, in print_exchange_ticker
    print(await huobi.fetch_balance())
  File "C:\python\python36\lib\site-packages\ccxt\async\huobipro.py", line 464, in fetch_balance
    await self.load_markets()
  File "C:\python\python36\lib\site-packages\ccxt\async\base\exchange.py", line 155, in load_markets
    markets = await self.fetch_markets()
  File "C:\python\python36\lib\site-packages\ccxt\async\huobipro.py", line 188, in fetch_markets
    response = await getattr(self, method)()
  File "C:\python\python36\lib\site-packages\ccxt\async\base\exchange.py", line 102, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\python\python36\lib\site-packages\ccxt\async\base\exchange.py", line 138, in fetch
    self.raise_error(RequestTimeout, method, url, e, None)
  File "C:\python\python36\lib\site-packages\ccxt\base\exchange.py", line 288, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: huobipro GET https://api.huobipro.com/v1/common/symbols 
huobipro requires to release all resources with an explicit call to the .close() coroutine.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000019D33038B70>

add:
when i run code like below, i can get correct  response:
import ccxt
poloniex = ccxt.huobipro(
    {
        'apiKey': "xx",
        'secret': "xx",
        'verbose': True
    }
)
print(poloniex.fetch_balance())

**Comment by kroitor** [comment]
You should add proper exception handling:
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#request-timeout
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Hope this helps.

**Comment by JustBbing** [comment]
Sorry for not replying in time，thanks for your help, I think the problem may caused by windows, i ran the code in linux, i get right response,I used to have a problem with Windows system when I was using a process but Linux was okay.
