### ISSUE TITLE
BITBANK sell and buy order

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#2775]
Hi I can't sell and buy order using bitbank.

- OS:win10
- Programming Language version: python3.6
- CCXT version:latest
- Exchange:bitbank
- Method:

the command line is follow
exchange.create_limit_sell_order('BTC/JPY', 0.001, 1000000)

error target source is follow
exchange.create_limit_buy_order ('BTC/JPY', amount, ask_price)
exchange.create_limit_sell_order ('BTC/JPY', amount, bid_price)

amount is 0.001
ask_price is 1000000
bid_price is 1000000

and I confirmed and  successed accurate order on pgm ,when I bought and sold the order the exchage "BITFLYER" in same pgm.So it seems bitbank's interface problem.

The error occured like that
`OSError: [Errno 22] Invalid argument`

detail

```
Traceback (most recent call last):
  File "C:/pythonfiles//pr2.py", line 80, in <module>
    exchange.create_limit_sell_order(target_currency, amount, bid_price)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 1258, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitbank.py", line 312, in create_order
    order = self.parse_order(response['data'], market)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitbank.py", line 281, in parse_order
    'datetime': self.iso8601(timestamp),
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 669, in iso8601
    utc = datetime.datetime.utcfromtimestamp(int(round(timestamp / 1000)))
OSError: [Errno 22] Invalid argument

Process finished with exit code 1
```

**Comment by kroitor** [comment]
> detail of error

We need the full verbose output without your keys. I don't really understand how you've missed it in that text that says that you should post **verbose output** and you didn't, you just posted the error callstack again (( You see, if it was enough, I wouldn't ask you about **verbose output* in #1252 in the first place. That means that the output you've posted is wrong and there's no need to duplicate it, I need much more of it above the error.

Once again, we need to see the full request and response, not just the error – we need all the verbose output, but without your keys. 

```Python
exchange.verbose = True  # ←-----------  ADD THIS !

exchange.create_limit_buy_order ('BTC/JPY', amount, ask_price)
exchange.create_limit_sell_order ('BTC/JPY', amount, bid_price)
```

↑ Run it in `verbose` mode, then post everything that is printed on screen, except your keys, here.

**Comment by sakurai-youhei** [comment]
@kroitor Unfortunately, someone looks to ask his/her **own** question at teratail as well as here, meaning teratail is not replica of github. teratail is a kind of domestic and standalone Q&A site like stackoverflow and that's why I reached this page when I had been trying to help his/her error.

**Comment by sakurai-youhei** [comment]
Anyway, you can of course ignore my writing noise here; My apologies for bothering you.

**Comment by kroitor** [comment]
@sakurai-youhei got it, no worries, thx!

**Comment by k31ww475** [comment]
Hi.Thanx for your early reply.
I tried to run add the pgm that you teach me "exchange.verbose = True"
But same error occured like that.

target source
```
exchange = eval('ccxt.' + ask_exchange + '()')
exchange.apiKey = exchanges[ask_exchange]["apiKey"]
exchange.secret = exchanges[ask_exchange]["secret"]

exchange.verbose = True  # ←-----------  ADDED
exchange.create_limit_buy_order (target_currency, amount, ask_price)←-----------  FAILURE
```

The error
```
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/xxx/xxx.py", line 115, in <module>
    exchange.create_limit_buy_order (target_currency, amount, ask_price)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 1255, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitbank.py", line 312, in create_order
    order = self.parse_order(response['data'], market)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitbank.py", line 281, in parse_order
    'datetime': self.iso8601(timestamp),
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 669, in iso8601
    utc = datetime.datetime.utcfromtimestamp(int(round(timestamp / 1000)))
OSError: [Errno 22] Invalid argument
```

**Comment by k31ww475** [comment]
Also I could ordered in ""bitflyer"" using follow pgm.It was success.
But ""bitbank's"" result was failure.

bitflyer:SUCCESS
bitbank:NG

the target source orders of market and limit
```
limit_ordered_info = exchange_api.create_order(symbol=target_currency, type='limit', side='BUY', amount=amount, price=500000)
print(json.dumps(limit_ordered_info, indent=True))

market_ordered_info = exchange_api.create_market_buy_order(symbol=target_currency, amount=amount)
print(json.dumps(market_ordered_info, indent=True))
```

**Comment by k31ww475** [comment]
Dear Mr.kroitor

>Once again, we need to see the full request and response, not just the error – we need all the verbose output, but without your keys.

I attached the error follow.Of course I wrote the command like that
exchange_api.verbose = True 

C:\Users\XXX\AppData\Local\Programs\Python\Python36\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port XXXXX --file C:/XXX/pr2.py
pydev debugger: process XXXXX is connecting

Connected to pydev debugger (build 181.4668.75)

Request: POST https://api.bitbank.cc/v1/user/spot/order {'Content-Type': 'application/json', 'ACCESS-KEY': 'XXX', 'ACCESS-NONCE': 'XXX', 'ACCESS-SIGNATURE': 'XXX', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} {"pair":"btc_jpy","amount":"0.001","price":"500000.00000000","side":"BUY","type":"limit"}
Traceback (most recent call last):

  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1068, in run
Response: POST https://api.bitbank.cc/v1/user/spot/order 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '35', 'Connection': 'keep-alive', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, token', 'Access-Control-Allow-Methods': 'POST, GET', 'Content-Security-Policy': "default-src 'none';frame-ancestors 'self';base-uri 'none';form-action 'none'", 'Date': 'Mon, 07 May 2018 10:07:17 GMT', 'ETag': 'W/"XXX"', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Server': 'nginx', 'Strict-Transport-Security': 'max-age=XXX;includeSubDomains;preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 XXX.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': 'XXX'} {"success":0,"data":{"code":40021}}
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/XXX/pr2.py", line 103, in <module>
    limit_ordered_info = exchange_api.create_order(symbol=target_currency, type='limit', side='BUY', amount=amount, price=500000)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitbank.py", line 310, in create_order
    response = self.privatePostUserSpotOrder(self.extend(request, params))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitbank.py", line 496, in request
    raise ErrorClass(message)
ccxt.base.errors.InvalidOrder: The trading classification is invalid

Process finished with exit code 1

Thanks in advance.

**Comment by kroitor** [comment]
@k31ww475 ok, now I see it, thx! Will debug it and will get back to you on this issue soon.

**Comment by kroitor** [comment]
@k31ww475 does fetch_balance work for you?

```Python
import ccxt
exchange = ccxt.bitbank({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
print(exchange.fetch_balance())
```

?

**Comment by k31ww475** [comment]
Exactly.and I set the price in this code like that but the different error still occured.
```
market_ordered_info = exchange.create_market_buy_order(
                         symbol=target_currency,
                         amount=target_amount,
                         price=1000000 >>>>>>>>>> added the line,
                         )
```
**ERROR**
```
 price=1000000,
TypeError: create_market_buy_order() got an unexpected keyword argument 'price'

```

**Comment by kroitor** [comment]
@k31ww475 ok, will debug it further and will get back to you shortly.

**Comment by k31ww475** [comment]
@kroitor Thanx lots.

**Comment by k31ww475** [comment]
@kroitor 
Hi.I seached the bug,when we ordered(buy and sell) in bitbank using ccxt.
After we ordered in bitbank using ccxt,I confirmed these ordered success on website bitbank.
But the error occured follow and PROCESS of pgm is shut down that's why it's seems to bug of ccxt.
OSError: [Errno 22] Invalid argument

    if bid_exchange == "bitbank":
        limit_ordered_info_sold = exchange[2].create_order(
            symbol="BTC/JPY"
            type='limit',
            side='sell',
            amount=0.001,
            price=1500000

**Comment by k31ww475** [comment]
@kroitor 
>>>OSError: [Errno 22] Invalid argument
Also it's some kind of pass setting problem.
And I already confirmed accurate result the other exchange in my wrote program except for bitbank.
```
    if bid_exchange == "bitbank":
        limit_ordered_info_sold = exchange[2].create_order(
            symbol="BTC/JPY"
            type='limit',
            side='sell',
            amount=0.001,
            price=1500000

```

**Comment by k31ww475** [comment]
I changed the target code by python.but it ""different"" error occured.
 
raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: bitbank {"success":0,"data":{"code":60005}}

**Comment by kroitor** [comment]
> I changed the target code by python.but it ""different"" error occured.

Can you please post your code and verbose output again ?

For the code: polease make it a complete shortest possible program to reproduce the issue, don't swallow the lines, we need the entire code (10-20 lines), including the instantiation, but without your keys.

For the output: we need to see the verbose output of both the request and the response.

Whenever you have ANY error or ANY problem, please post your code+verbose output for that error.
