### ISSUE TITLE
zaif RequestTimeout

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#2781]
Hi guys.
let me know how to resolve the way from this error plz.

target source is follow.
limit_ordered_info = exchange_api.create_order(symbol=target_currency, type='limit', side='BUY', 

```
failure parts
exchange_api.verbose = True
limit_ordered_info = exchange_api.create_order(symbol=target_currency, type='limit', side='BUY', amount=amount, price=500000)
print(json.dumps(limit_ordered_info, indent=True))

```
I already successed the follow all command in zaif.

```
success
result = exchange_api.fetch_markets()
print(json.dumps(result, indent=True))

result = exchange_api.fetch_ticker(symbol='BTC/JPY')
print(json.dumps(result, indent=True))

result = exchange_api.fetch_order_book(symbol='BTC/JPY')
print(json.dumps(result, indent=True))

result = exchange_api.fetch_trades(symbol='BTC/JPY', limit=2)
print(json.dumps(result, indent=True))

result = exchange_api.fetch_balance()
print(json.dumps(result, indent=True))
```

error

```
Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.zaif.jp', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 357, in fetch
    proxies=self.proxies
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.zaif.jp', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/xxxxxxxxxx.py", line 112, in <module>
    result = exchange_api.fetch_balance()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\zaif.py", line 145, in fetch_balance
    response = self.privatePostGetInfo()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\zaif.py", line 368, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 303, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 367, in fetch
    self.raise_error(RequestTimeout, method, url, e)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 288, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: zaif POST https://api.zaif.jp/tapi HTTPSConnectionPool(host='api.zaif.jp', port=443): Read timed out. (read timeout=10)

Process finished with exit code 1
```
env
- OS:WIN10
- Programming Language version:
- CCXT version:LATEST
- Exchange:ZAIF

Thanks in advance

**Comment by kroitor** [comment]
The `side` argument should be lowercase, it's either "buy" or "sell", not "BUY", nor "SELL".

Does this work for you:

```Python
import ccxt
exchange = ccxt.zaif({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
exchange.load_markets()

exchange.verbose = True
print(exchange.fetch_balance())
```

↑  What does it say with your apiKey and your secret?

**Comment by k31ww475** [comment]
At first,it didn't work after I rewrite buy from BUY and 
exchange.verbose = True for debug in zaif case.
The error is follow.
```
Traceback (most recent call last):
  File "easyorder2.py", line 29, in <module>
    price=900000
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\zaif.py", line 241, in create_order
    }, params))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\zaif.py", line 370, in request
    raise ExchangeError(self.id + ' ' + response['error'])
ccxt.base.errors.ExchangeError: zaif insufficient funds
```

**Comment by k31ww475** [comment]
Also bitbank is different error
The error is follow.of course I rewrite two parts that I wrote.

**BITBANK**

```
Traceback (most recent call last):
  File "easyorder2.py", line 29, in <module>
    price=900000
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bitbank.py", line 312, in create_order
    order = self.parse_order(response['data'], market)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bitbank.py", line 281, in parse_order
    'datetime': self.iso8601(timestamp),
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 669, in iso8601
    utc = datetime.datetime.utcfromtimestamp(int(round(timestamp / 1000)))
OSError: [Errno 22] Invalid argument
```

**Comment by kroitor** [comment]
@k31ww475 does the fetch_balance snippet posted above work for you?

**Comment by k31ww475** [comment]
This is error case of print(exchange.fetch_balance()) using your source pgm.
**ZAIF**

**Request: POST https://api.zaif.jp/tapi {'Content-Type': 'application/x-www-form-urlencoded', 'Key': 'hoge', 'Sign': 'hoge', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} method=get_info&nonce=hoge

Response: POST https://api.zaif.jp/tapi 502 {'Server': 'awselb/2.0', 'Date': 'Mon, 07 May 2018 23:32:21 GMT', 'Content-Type': 'text/html', 'Content-Length': '138', 'Connection': 'keep-alive'} <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 364, in fetch
    response.raise_for_status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.zaif.jp/tapi

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "easyorder.py", line 9, in <module>
    print(exchange.fetch_balance())
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\zaif.py", line 145, in fetch_balance
    response = self.privatePostGetInfo()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\zaif.py", line 368, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 303, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 377, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 406, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 288, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: zaif https://api.zaif.jp/tapi POST 502 Server Error: Bad Gateway for url: https://api.zaif.jp/tapi <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>**

**Comment by kroitor** [comment]
Ok, then... Does zaif public API work for you?

```Python
import ccxt
print(ccxt.zaif().fetch_ticker('ETH/BTC'))
```

?

**Comment by k31ww475** [comment]
yes.it worked.

{'symbol': 'ETH/BTC', 'timestamp': 1525736377783, 'datetime': '2018-05-07T23:39:38.783Z', 'high': 0.0827, 'low': 0.076, 'bid': 0.0798, 'bidVolume': None, 'ask': 0.0813, 'askVolume': None, 'vwap': 0.0801, 'open': None, 'close': 0.0797, 'last': 0.0797, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': 259.4796, 'quoteVolume': 20.78431596, 'info': {'last': 0.0797, 'high': 0.0827, 'low': 0.076, 'vwap': 0.0801, 'volume': 259.4796, 'bid': 0.0798, 'ask': 0.0813}}

**Comment by kroitor** [comment]
@k31ww475 are you using a new API key from zaif, or it was used previously with some other software?

**Comment by k31ww475** [comment]
I just use latest API.I created the API few weeks ago.

 it was used previously with some other software?
No.I got the apikey on the officeial website except for other software.

**Comment by kroitor** [comment]
Does this work:

```Python
import ccxt
exchange = ccxt.zaif ({
    "apiKey": "580c7232-06c7-4698-8fb7-4cd2a543cea8",
    "secret": "4c529fd6-fb28-4879-b20d-2a8f02c5db47",
})
print(zaif.fetch_balance())
```

?

**Comment by k31ww475** [comment]
yes.it worked.

**Comment by kroitor** [comment]
@k31ww475 this is a problem with your api key – just create a new api key with zaif website and retry the same balance script with your new key:

```Python
import ccxt
exchange = ccxt.zaif ({
    "apiKey": "YOUR_NEW_API_KEY",
    "secret": "YOUR_NEW_SECRET,
})
print(exchange.fetch_balance())
```

Does it work now with a new key?

**Comment by k31ww475** [comment]
What should I set the authority without withdraw ?
info 
 trade 
 withdraw 
 personal_info 
 id_info

**Comment by k31ww475** [comment]
I created new apykey in zaif
it worked only **fetch_balance in zaif**

``
import ccxt
exchange = ccxt.zaif ({
    "apiKey": "hoge"
    "secret": "hoge"
})
print(exchange.fetch_balance())
``

But limit order's same code  that I successed in Bitflyer was failure in zaif

**Comment by k31ww475** [comment]
I recreated the api and change buy from BUY but I couldn't use create_order in zaif.Of course this source can use in bit flyer's web.So It's ccxt's problem.The detail is follow.

ZAIF
**SUCCESSED:**fetch_balance

**FAILURE**:exchange.create_order(symbol="BTC/JPY",type='limit',side='buy',amount=0.001,price=900000)

THE FAILURE CODE
```
import ccxt
import json

# zaif API

exchange = ccxt.zaif()
exchange.apiKey = 'ZZZ'
exchange.secret = 'ZZZ'

limit_ordered_info = exchange.create_order(
                     symbol="BTC/JPY",
                     type='limit',
                     side='buy',
                     amount=0.001,
                     price=900000
                     )
exchange.verbose = True
print(json.dumps(limit_ordered_info, indent=True))

```
**error content**
```
Traceback (most recent call last):
  File "easyorder6.py", line 17, in <module>
    price=900000
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\zaif.py", line 241, in create_order
    }, params))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\zaif.py", line 370, in request
    raise ExchangeError(self.id + ' ' + response['error'])
ccxt.base.errors.ExchangeError: zaif insufficient funds

C:\pythonfiles\price_check\pricecheck04-easyorder>
```

**Comment by kroitor** [comment]
@k31ww475 does this tell you anything:
```
ccxt.base.errors.ExchangeError: zaif insufficient funds
```
? )

**Comment by k31ww475** [comment]
I moved the asset and confirmed to success transaction in zaif.
Anyway how about bitbank's case?

**Comment by k31ww475** [comment]
Also bitbank is different error
The error is follow.of course I rewrite two parts that I wrote.

**BITBANK**

Traceback (most recent call last):
  File "easyorder2.py", line 29, in <module>
    price=900000
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bitbank.py", line 312, in create_order
    order = self.parse_order(response['data'], market)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bitbank.py", line 281, in parse_order
    'datetime': self.iso8601(timestamp),
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 669, in iso8601
    utc = datetime.datetime.utcfromtimestamp(int(round(timestamp / 1000)))
OSError: [Errno 22] Invalid argument

**Comment by k31ww475** [comment]
@kroitor 
The order from zaif and bitflyer successed with error.
Thnx  for kindly support and super speedy advice.

I have a trouble about bitbank's purchase/sell case(market order)
**The source is follow**
```
    market_ordered_info = exchange.create_market_buy_order(
                         symbol= target_currency,
                         amount= target_amount,
                         )
    print(json.dumps(market_ordered_info, indent=True))
```
**The error message** 
```
Traceback (most recent call last):
  File "C:/xxx.py", line 90, in <module>
    amount= target_amount,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 1261, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitbank.py", line 302, in create_order
    raise InvalidOrder(self.id + ' createOrder requires a price argument for both market and limit orders')
ccxt.base.errors.InvalidOrder: bitbank createOrder requires a price argument for both market and limit orders
```
And I search your code of ccxt and I found the target source of error
301
302
```
        if price is None:
            raise InvalidOrder(self.id + ' createOrder requires a price argument for both market and limit orders')

```
https://github.com/ccxt/ccxt/blob/master/python/ccxt/async/bitbank.py

**Tried**
I obeyed the error ,I mean added the source  price= 1300000 like that

```
    market_ordered_info = exchange.create_market_buy_order(
                         symbol= target_currency,
                         amount= target_amount,
                         price= 1300000

```

But the error occured
**ERROR**
`TypeError: create_market_buy_order() got an unexpected keyword argument 'price'`

Thank you in advance

**Comment by kroitor** [comment]
Related: #2775

**Comment by k31ww475** [comment]
Today I got a same error too.
>ccxt.base.errors.InvalidOrder: bitbank createOrder requires a price argument for both market and limit orders

Even if I set a price argument,it occured the error like below.

ERROR
TypeError: create_market_buy_order() got an unexpected keyword argument 'price'

Thanks in advance.

**Comment by kroitor** [comment]
> I obeyed the error ,I mean added the source price= 1300000 like that
```
    market_ordered_info = exchange.create_market_buy_order(
                         symbol= target_currency,
                         amount= target_amount,
                         price= 1300000
```

> But the error occured
> `TypeError: create_market_buy_order() got an unexpected keyword argument 'price'`

You should call:

```
exchange.create_order (target_currency, 'market', 'buy', target_amount, 1300000)
```

The `create_market_buy_order` does not support the `price` argument, therefore you have to use `create_order` with it. Let us know if it does not answer your question. Thx!
