### ISSUE TITLE
we CANNOT order limitorder Zaif and  Bitbank although its super easy source What should I write a code of limit order and market order in Zaif and  Bitbank?

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#2783]
Hi guys.I created the super easy program to limitorder using ccxt and
I successed to limit order only bitflyer using this source.
But I couldn't success to order in Bitbank and Zaif case.
What should I write a code of limit order and market order in Zaif and  Bitbank?
The program is follow.
```
import ccxt
import json

# bitflyer API
exchange_api = ccxt.bitflyer()
exchange_api.apiKey = 'hoge'
exchange_api.secret = 'hoge'

# zaif API
exchange_api = ccxt.zaif()
exchange_api.apiKey = 'hoge'
exchange_api.secret = 'hoge'

# bitbank API
exchange_api = ccxt.bitbank()
exchange_api.apiKey = 'hoge'
exchange_api.secret = 'hoge'

#purchase limit order
limit_ordered_info = exchange_api.create_order(
                     symbol="BTC/JPY",
                     type='limit',
                     side='BUY',
                     amount=0.001,
                     price=900000
                     )
print(json.dumps(limit_ordered_info, indent=True))
```
This is the contents of ERROR each exchanges.

ZAIF ERROR
```
Traceback (most recent call last):
  File "easyorder2.py", line 29, in <module>
    price=900000
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\zaif.py", line 241, in create_order
    }, params))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\zaif.py", line 370, in request
    raise ExchangeError(self.id + ' ' + response['error'])
ccxt.base.errors.ExchangeError: zaif insufficient funds
```

```
BITBANK ERROR
Traceback (most recent call last):
  File "easyorder2.py", line 30, in <module>
    price=900000
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bitbank.py", line 310, in create_order
    response = self.privatePostUserSpotOrder(self.extend(request, params))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bitbank.py", line 496, in request
    raise ErrorClass(message)
ccxt.base.errors.InvalidOrder: The trading classification is invalid

```
What should I write a code of limit order and market order in Zaif and  Bitbank?
Thanks in advance

- OS:win10
- Programming Language version: python3
- CCXT version:latest
- Exchange:wrote

**Comment by kroitor** [comment]
I'd move this discussion to #2781 if you don't mind. Thx!

**Comment by k31ww475** [comment]
ok.thx
