### ISSUE TITLE
Binance amount_to_precision() KeyError  'BCC/USDT'

### ISSUE THREAD

**Issue by Maximilan4** [ccxt/ccxt#2784]
Hi, i am storing binance balance in db. I call amount_to_precision() method on balance value, for storing already rounded value.  Call example:
```python
import ccxt 
bin = ccxt.binance()
bin.load_markets()
bin.amount_to_precision('BCC/USDT', 0.00000)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/maximov/python_projects/stock-exchange/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 823, in amount_to_precision
    return self.truncate(amount, self.markets[symbol]['precision']['amount'])
KeyError: 'BCC/USDT'
```
That is wrong with that market ? It is active on binance.

debian 8, python 3.6, ccxt 1.12.122

**Comment by kroitor** [comment]
It's BCH, not BCC

```Python
import ccxt
binance = ccxt.binance()
binance.load_markets()
print(binance.symbols)
```

https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by Maximilan4** [comment]
@kroitor Thanks.
