### ISSUE TITLE
let partial = async params => this[methodName] (path, type, uppercaseMethod, params || {})  SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by hrandeniya** [ccxt/ccxt#2798]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: OSX
- Programming Language version: JS
- CCXT version: 1.13.105
- Exchange: N/A
- Method: N/A

When compiling, I am getting the below issue:
```.../node_modules/ccxt/js/base/Exchange.js:363
let partial = async params => this[methodName] (path, type, uppercaseMethod, params || {})

SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/himalrandeniya/Dropbox (Personal)/Project Xs/Apps v2/Engine/node_modules/ccxt/ccxt.js:33:19)
    at Module._compile (module.js:573:32)```

**Comment by kroitor** [comment]
Make sure your node is 8+.

```
node --version
```

Earlier versions don't really support the modern ES6 syntax.
