### ISSUE TITLE
binance withdraw throw illegal_address error

### ISSUE THREAD

**Issue by radarxc** [ccxt/ccxt#2897]
- OS: Win10
- Programming Language version: Python 3.5.4
- CCXT version: 1.14.25
- Exchange: binance
- Method: withdraw

When I tested binance withdraw, I got 'illegal_address' response as below:

> ccxt.base.errors.ExchangeError: binance: success value False: {"msg":"illegal_address","success":false}

When I tested binance's own [withdraw api](https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md), it works well.

Attach my testing code below, hope it will help:

    f_m = "binance"
    t_m = "huobipro" 
    currency = "ZEC"

    exchange = getattr(ccxt, f_m)({'apiKey': apiconfig['key'], 'secret': apiconfig['secret'], 'nonce': ccxt.Exchange.milliseconds})
    addresses = get_market_addresses(t_m) #get addresses map
    exchange.load_markets()
    response = exchange.fetch_balance()
    print(response) #fetch balance, worked
    response = exchange.withdraw(currency, 1, addresses[currency]['address'], 'Test withdraw', {})
    print(response) #withdraw, failed

Also attach Traceback:

> Traceback (most recent call last):
  File "testing2.py", line 36, in <module>
    withdraw_test()
  File "testing2.py", line 33, in withdraw_test
    response = exchange.withdraw(currency, 1, addresses[currency]['address'], 'Test withdraw', {})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\ccxt\binance.py", line 764, in withdraw
    response = self.wapiPostWithdraw(self.extend(request, params))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\ccxt\binance.py", line 845, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\ccxt\base\exchange.py", line 303, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\ccxt\base\exchange.py", line 383, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\ccxt\binance.py", line 842, in handle_errors
    raise ExchangeError(self.id + ': success value False: ' + body)
ccxt.base.errors.ExchangeError: binance: success value False: {"msg":"illegal_address","success":false}

**Comment by radarxc** [comment]
The same as [huobipro issue](https://github.com/ccxt/ccxt/issues/2896), when I change withdraw's 'tag' parameter as None, this issue is fixed.

**Comment by kroitor** [comment]
See the answer in the huobipro issue: https://github.com/ccxt/ccxt/issues/2896#issuecomment-390456144
