### ISSUE TITLE
Bitmex create_limit_sell_order() doesn't work, but exchange.fetch_balance() works fine

### ISSUE THREAD

**Issue by so2liu** [ccxt/ccxt#2920]
- OS: Ubuntu 18.04
- Programming Language version: Python 3.6.5
- CCXT version: newest
- Exchange: Bitmex
- Method: create_limit_sell_order()

Hallo, I've tried to get the balance in Bitmex. It works fine. But I can't place orders. Here is my code. The API Key I used has already "Order, Cancel, Read" permissions. Symbol I have used "BTC/USD" and "XBTM18".

```
import time
import ccxt


exchange=ccxt.bitmex({'apiKey':'','secret': ''})

print (exchange.fetch_balance()['BTC'])
time.sleep(2)
exchange.create_limit_sell_order('XBTM18', 100, 10000)
time.sleep(2)
closed_orders=exchange.fetch_closed_orders()
for each in closed_orders:
    print(each['symbol'],each['price'],each['amount'],each['side'],each['datetime'])



Output:

{'free': 0.20350399, 'used': 0.006389670000000014, 'total': 0.20989366}
Traceback (most recent call last):
  File "/home/so2liu/PycharmProjects/ccxt_try/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 365, in fetch
    response.raise_for_status()
  File "/home/so2liu/PycharmProjects/ccxt_try/venv/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.bitmex.com/api/v1/order?symbol=XBTM18&side=Sell&orderQty=100&ordType=Limit&price=10000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/so2liu/PycharmProjects/ccxt_try/demo.py", line 18, in <module>
    exchange.create_limit_sell_order('XBTM18', 100, 10000)
  File "/home/so2liu/PycharmProjects/ccxt_try/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1271, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "/home/so2liu/PycharmProjects/ccxt_try/venv/lib/python3.6/site-packages/ccxt/bitmex.py", line 472, in create_order
    response = self.privatePostOrder(self.extend(request, params))
  File "/home/so2liu/PycharmProjects/ccxt_try/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 307, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/so2liu/PycharmProjects/ccxt_try/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 304, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/so2liu/PycharmProjects/ccxt_try/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 377, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "/home/so2liu/PycharmProjects/ccxt_try/venv/lib/python3.6/site-packages/ccxt/bitmex.py", line 543, in handle_errors
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: bitmex {"error":{"message":"Access Denied","name":"HTTPError"}}```

**Comment by kroitor** [comment]
When you created the API keys, which permission type did you choose `order` or `order_cancel` ?

**Comment by so2liu** [comment]
Yes, this Key has Order, Cancel, Read permissions.

**Comment by kroitor** [comment]
![bitmex](https://user-images.githubusercontent.com/1294454/40358553-4287a12a-5dc8-11e8-998c-822673b783f9.jpg)

**Comment by kroitor** [comment]
Did you choose:
- `order`
or
- `order cancel` ?

**Comment by kroitor** [comment]
You should have chosen `Order` 

(**not `Order Cancel`**)

**Comment by so2liu** [comment]
Oh no, yes, you are right, I made a big mistake. Thanks a lot for your fast reply!!

**Comment by Lynch4u** [comment]
Thanks, I had the same promble, but  i sloved it just now after i met this issue!
