### ISSUE TITLE
how do we work against timeout error ?  Read timed out. (read timeout=10)  During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#2924]
My env is follow
- OS:win10
- Programming Language version:python 3.6
- CCXT version:1.14.37
- Exchangebitflyer and bitbank and zaif:

Hi.I always use your code and the code usually work well.
But sometimes timeout error occured.The frequency of timeout can't ignore.
Of course each exchange have limit of access per minite or 1hour.
But what we use the process of exception  is really important for us.
Because the process and pgm flow suddenly shut down,when the timeout error occured.
What's more we always loop the process to use ccxt.

So may I ask your favor,let me know how should I add exception process against timeout.

For instance,this is the concrete error part that I found today.

Of course every exchange have different environment about limit http access frequency and
I know it.But my pgm always stop within 5 min by timeout that why please let me know the exception process code.and after the timeout error occured and shut down,I can run the process again then it will be success.

thanks in advance.

**the target source**
```
orderbook = exchange_get.fetch_order_book(target_currency) # here
error log
  File "C:/pythonfiles/price_check/pricecheck04-easyorder/arb8.py", line 229, in process_get_price
    orderbook = exchange_get.fetch_order_book(target_currency)
```

And the target error part is follow.including detail parts.

```
 raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.bitflyer.jp', port=443): Read timed out. (read timeout=10)

```

 **error detail**

```
Traceback (most recent call last):
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.bitflyer.jp', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 357, in fetch
    proxies=self.proxies
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.bitflyer.jp', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/pythonfiles/price_check/pricecheck04-easyorder/arb8.py", line 799, in <module>
    arbitrage_decision, ask_exchange, set_ask_volume, best_ask_price, bid_exchange, set_bid_volume, best_bid_price, num, check_profit_price, check_profit_rate, stop_process_no1, stop_process_no2, stop_process_no3, stop_process_no4, stop_process_no5,net_profit_price = process_get_price(num,check_profit_price,check_profit_rate,stop_process_no1,stop_process_no2,stop_process_no3,stop_process_no4,stop_process_no5)
  File "C:/pythonfiles/price_check/pricecheck04-easyorder/arb8.py", line 229, in process_get_price
    orderbook = exchange_get.fetch_order_book(target_currency) # HERE
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitflyer.py", line 155, in fetch_order_book
    }, params))
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 306, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 303, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 367, in fetch
    self.raise_error(RequestTimeout, method, url, e)
  File "C:\Users\hogehoge\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 288, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: bitflyer GET https://api.bitflyer.jp/v1/getboard?product_code=BTC_JPY HTTPSConnectionPool(host='api.bitflyer.jp', port=443): Read timed out. (read timeout=10)

Process finished with exit code 1


```

**Comment by kroitor** [comment]
Hi!

You can catch it and retry after a delay. This is the general strategy for handling RequestTimeouts.
How your program should behave upon a recoverable error – depends on your particular task and the method that is throwing a RequestTimeout. 

Some methods can be retried safely, some require additional logic on your side. Most of these cases are described here:
- https://github.com/ccxt/ccxt/wiki/Manual#request-timeout

See examples on how to catch and handle errors:

- https://github.com/ccxt/ccxt/tree/master/examples

Hope this answers your question. Let us know if not. Thx!

**Comment by k31ww475** [comment]
ok.Kroitor.I'll read and try it.
I'll send you the result with my code,after I tried to add exception code.


2018年5月23日(水) 2:13 Igor Kroitor <notifications@github.com>:
