### ISSUE TITLE
Unable to load ccxt objects after update to 1.14.79

### ISSUE THREAD

**Issue by HornKild** [ccxt/ccxt#2984]
I updated to version 1.14.79 with `pip install ccxt --update` but now I'm unable to load objects, am'I the only one facing this problem ? I have tried uninstalling `ccxt` but it I still have the same issue. Any idea would be much appreciate, tx!

```
In [370]:  import ccxt

In [371]:  ccxt.bittrex()
Traceback (most recent call last):

  File "<ipython-input-711-416616f1276a>", line 1, in <module>
    ccxt.bittrex()

  File "/home/abc/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 219, in __init__
    settings = self.deep_extend(self.describe(), config)

  File "/home/abc/anaconda3/lib/python3.6/site-packages/ccxt/bittrex.py", line 30, in describe
    return self.deep_extend(super(bittrex, self).describe(), {

TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by kroitor** [comment]
Hi!

> I updated to version 1.14.79 with pip install ccxt --update but now I'm unable to load objects, am'I the only one facing this problem ? 

1. First, let's make sure that your version is up to date:

```PHP
import ccxt
print(ccxt.version)  # which one is it?
```

2. Second, what was your previous version before the update? Basically, if one version worked and the other version doesn't work, then the break is obviously somewhere in between.

> I have tried uninstalling ccxt but it I still have the same issue. Any idea would be much appreciate, tx!

I am suspicious on Anaconda python – most users complained about this or that issue with it. However, let's first resolve the first two questions.

**Comment by HornKild** [comment]
> First, let's make sure that your version is up to date:

Apparently there is a problem with my `ccxt` module.

```
In [712]: import ccxt

In [713]: print(ccxt.version)
Traceback (most recent call last):

  File "<ipython-input-713-00a70aefae2c>", line 1, in <module>
    print(ccxt.version)

AttributeError: module 'ccxt' has no attribute 'version'
```

> Second, what was your previous version before the update? 

I don't know what was the previous version but I think it was 4 to 5 weeks old.

**Comment by kroitor** [comment]
> Apparently there is a problem with my ccxt module, this is very strange because installation is just fine.

Sorry, this was a typo in my code snippet, the proper code to check your version is:

```Python
import ccxt
print(ccxt.__version__)  # double underscores added
```

What does it output?

**Comment by HornKild** [comment]
Output is : 
```
print(ccxt.__version__)
1.14.88
```

**Comment by HornKild** [comment]
I did a `pip install ccxt --upgrade` recently to check the output but still the problem remains.

**Comment by kroitor** [comment]
@HornKild ok, so apparently, your version is up to date. Now, let's try something simple like this:

```Python
import ccxt
print(dir(ccxt.bittrex()))
```

Does it work?

**Comment by HornKild** [comment]
No same error : 

```
import ccxt
print(dir(ccxt.bittrex()))

Traceback (most recent call last):

  File "<ipython-input-717-f189db27772a>", line 2, in <module>
    print(dir(ccxt.bittrex()))

  File "/home/abc/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 219, in __init__
    settings = self.deep_extend(self.describe(), config)

  File "/home/abc/anaconda3/lib/python3.6/site-packages/ccxt/bittrex.py", line 30, in describe
    return self.deep_extend(super(bittrex, self).describe(), {

TypeError: super(type, obj): obj must be an instance or subtype of type

```

**Comment by kroitor** [comment]
This is a known, but very annoying issue with Jupyter Python (ipython): https://github.com/jupyter/help/issues/130
Unfortunately, I'm not sure if we can help right away here, yet. What's your version of ipython? When was the last time you upgraded it?

**Comment by kroitor** [comment]
Do you have autoreload in ipython enabled? Can you try with it switched off?

**Comment by HornKild** [comment]
I have iPython 6.2.1 since a couple of months and I just upgrade to 6.4.0. Without restarting Spyder IDE I got an error when trying to `import ccxt` with the new iPython version, but as soon as I started a new session and killed all python process it just works fine :) Thanks so much !

```
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19)
Type "copyright", "credits" or "license" for more information.

IPython 6.4.0 -- An enhanced Interactive Python.

import ccxt

print(dir(ccxt.bittrex()))
['__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'account', 'accountGetBalance', 'accountGetBalances', 'accountGetDepositaddress', 'accountGetDeposithistory', 'accountGetOrder', 'accountGetOrderhistory', 'accountGetOrders', 'accountGetWithdraw', 'accountGetWithdrawalhistory', 'account_get_balance', 'account_get_balances', 'account_get_depositaddress', 'account_get_deposithistory', 'account_get_order', 'account_get_orderhistory', 'account_get_orders', 'account_get_withdraw', 'account_get_withdrawalhistory', 'aggregate', 'aiohttpProxy', 'aiohttp_proxy', 'amountToLots', 'amountToPrecision', 'amountToString', 'amount_to_lots', 'amount_to_precision', 'amount_to_string', 'api', 'apiKey', 'arrayConcat', 'array_concat', 'asyncioLoop', 'asyncio_loop', 'balance', 'base64urlencode', 'binaryConcat', 'binaryToString', 'binary_concat', 'binary_to_string', 'buildOhlcv', 'build_ohlcv', 'calculateFee', 'calculate_fee', 'cancelOrder', 'cancel_order', 'capitalize', 'checkAddress', 'checkRequiredCredentials', 'check_address', 'check_required_credentials', 'commonCurrencies', 'commonCurrencyCode', 'common_currency_code', 'convertOhlcvToTradingView', 'convertTradingViewToOhlcv', 'convert_ohlcv_to_trading_view', 'convert_trading_view_to_ohlcv', 'costToPrecision', 'cost_to_precision', 'countries', 'createLimitBuyOrder', 'createLimitOrder', 'createLimitSellOrder', 'createMarketBuyOrder', 'createMarketOrder', 'createMarketSellOrder', 'createOrder', 'create_limit_buy_order', 'create_limit_order', 'create_limit_sell_order', 'create_market_buy_order', 'create_market_order', 'create_market_sell_order', 'create_order', 'currencies', 'currenciesById', 'currencies_by_id', 'currency', 'currencyId', 'currency_id', 'decimalToPrecision', 'decimal_to_precision', 'decode', 'deepExtend', 'deep_extend', 'defineRestApi', 'define_rest_api', 'describe', 'editLimitBuyOrder', 'editLimitOrder', 'editLimitSellOrder', 'editOrder', 'edit_limit_buy_order', 'edit_limit_order', 'edit_limit_sell_order', 'edit_order', 'enableRateLimit', 'encode', 'encodeUriComponent', 'encode_uri_component', 'exceptions', 'extend', 'extractParams', 'extract_params', 'feeToPrecision', 'fee_to_precision', 'fees', 'fetch', 'fetch2', 'fetchBalance', 'fetchBidsAsks', 'fetchClosedOrders', 'fetchCurrencies', 'fetchDepositAddress', 'fetchFees', 'fetchFreeBalance', 'fetchL2OrderBook', 'fetchMarkets', 'fetchMyTrades', 'fetchOhlcv', 'fetchOpenOrders', 'fetchOrder', 'fetchOrderBook', 'fetchOrderStatus', 'fetchOrderTrades', 'fetchOrders', 'fetchPartialBalance', 'fetchTicker', 'fetchTickers', 'fetchTotalBalance', 'fetchTrades', 'fetchUsedBalance', 'fetch_balance', 'fetch_bids_asks', 'fetch_closed_orders', 'fetch_currencies', 'fetch_deposit_address', 'fetch_fees', 'fetch_free_balance', 'fetch_l2_order_book', 'fetch_markets', 'fetch_my_trades', 'fetch_ohlcv', 'fetch_open_orders', 'fetch_order', 'fetch_order_book', 'fetch_order_status', 'fetch_order_trades', 'fetch_orders', 'fetch_partial_balance', 'fetch_ticker', 'fetch_tickers', 'fetch_total_balance', 'fetch_trades', 'fetch_used_balance', 'filterBy', 'filterByArray', 'filterBySinceLimit', 'filterBySymbol', 'filterBySymbolSinceLimit', 'filter_by', 'filter_by_array', 'filter_by_since_limit', 'filter_by_symbol', 'filter_by_symbol_since_limit', 'findMarket', 'findSymbol', 'find_market', 'find_symbol', 'getOrderIdField', 'get_order_id_field', 'groupBy', 'group_by', 'gzipDeflate', 'gzip_deflate', 'handleErrors', 'handleRestErrors', 'handleRestResponse', 'handle_errors', 'handle_rest_errors', 'handle_rest_response', 'has', 'hash', 'headers', 'hmac', 'id', 'ids', 'implodeParams', 'implode_params', 'inArray', 'in_array', 'indexBy', 'index_by', 'iso8601', 'json', 'jwt', 'keysort', 'lastHttpResponse', 'lastJsonResponse', 'lastResponseHeaders', 'lastRestPollTimestamp', 'lastRestRequestTimestamp', 'last_http_response', 'last_json_response', 'last_response_headers', 'limits', 'loadFees', 'loadMarkets', 'load_fees', 'load_markets', 'logger', 'market', 'marketGetBuylimit', 'marketGetBuymarket', 'marketGetCancel', 'marketGetOpenorders', 'marketGetSelllimit', 'marketGetSellmarket', 'marketId', 'marketIds', 'market_get_buylimit', 'market_get_buymarket', 'market_get_cancel', 'market_get_openorders', 'market_get_selllimit', 'market_get_sellmarket', 'market_id', 'market_ids', 'markets', 'marketsById', 'markets_by_id', 'microseconds', 'milliseconds', 'minFundingAddressLength', 'msec', 'name', 'nonce', 'omit', 'options', 'orderbooks', 'ordered', 'orders', 'origin', 'parse8601', 'parseBalance', 'parseBidAsk', 'parseBidsAsks', 'parseDate', 'parseJsonResponse', 'parseOhlcv', 'parseOhlcvs', 'parseOrder', 'parseOrderBook', 'parseOrders', 'parseSymbol', 'parseTicker', 'parseTimeframe', 'parseTrade', 'parseTrades', 'parse_balance', 'parse_bid_ask', 'parse_bids_asks', 'parse_date', 'parse_ohlcv', 'parse_ohlcvs', 'parse_order', 'parse_order_book', 'parse_orders', 'parse_symbol', 'parse_ticker', 'parse_timeframe', 'parse_trade', 'parse_trades', 'password', 'pluck', 'populateFees', 'populate_fees', 'precision', 'precisionFromString', 'precisionMode', 'precision_from_string', 'prepareRequestHeaders', 'prepare_request_headers', 'priceToPrecision', 'price_to_precision', 'proxies', 'proxy', 'publicGetCurrencies', 'publicGetMarkethistory', 'publicGetMarkets', 'publicGetMarketsummaries', 'publicGetMarketsummary', 'publicGetOrderbook', 'publicGetTicker', 'public_get_currencies', 'public_get_markethistory', 'public_get_markets', 'public_get_marketsummaries', 'public_get_marketsummary', 'public_get_orderbook', 'public_get_ticker', 'purgeCachedOrders', 'purge_cached_orders', 'raiseError', 'raise_error', 'rateLimit', 'rateLimitMaxTokens', 'rateLimitTokens', 'rateLimitUpdateTime', 'rawencode', 'request', 'requiredCredentials', 'restPollerLoopIsRunning', 'restRequestQueue', 'safeFloat', 'safeInteger', 'safeString', 'safeValue', 'safe_float', 'safe_integer', 'safe_string', 'safe_value', 'sec', 'seconds', 'secret', 'session', 'setMarkets', 'set_markets', 'sign', 'sortBy', 'sort_by', 'substituteCommonCurrencyCodes', 'sum', 'symbols', 'throttle', 'tickers', 'timeframes', 'timeout', 'toArray', 'to_array', 'tokenBucket', 'trades', 'truncate', 'truncateToString', 'truncate_to_string', 'twofa', 'uid', 'unique', 'unjson', 'url', 'urlencode', 'urls', 'usec', 'userAgent', 'userAgents', 'uuid', 'v2GetCurrenciesGetBTCPrice', 'v2GetCurrenciesGetbtcprice', 'v2GetMarketGetLatestTick', 'v2GetMarketGetTicks', 'v2GetMarketGetlatesttick', 'v2GetMarketGetticks', 'v2GetMarketsGetMarketSummaries', 'v2GetMarketsGetmarketsummaries', 'v2_get_currencies_getbtcprice', 'v2_get_market_getlatesttick', 'v2_get_market_getticks', 'v2_get_markets_getmarketsummaries', 'verbose', 'version', 'withdraw', 'ymd', 'ymdhms']

```

**Comment by kroitor** [comment]
@HornKild thx for reporting back!

**Comment by HornKild** [comment]
> Does this help?

Sorry I didn't saw your post, I have checked ipython_config.py and it is commenting out, probably since upgrade to iPython 6.4.0.
