### ISSUE TITLE
BTCTurk: API Endpoint Updates

### ISSUE THREAD

**Issue by farukuzun** [ccxt/ccxt#3003]
- OS: Linux
- Programming Language version: python3
- CCXT version: 1.14.104
- Exchange: BTCTurk
- Method: fetch_balance()

```
{"try_balance":0.0,"btc_balance":0.0,"eth_balance":0.0,"try_reserved":0.0,"btc_reserved":0.0,"eth_reserved":0.0,"try_available":0.0,"btc_available":0.0,"eth_available":0.0,"btctry_taker_fee_percentage":0.0021186440000000,"btctry_maker_fee_percentage":0.0012711860000000,"ethtry_taker_fee_percentage":0.0012711860000000,"ethtry_maker_fee_percentage":0.0,"ethbtc_taker_fee_percentage":0.0000000000000000,"ethbtc_maker_fee_percentage":0.0000000000000000}
Traceback (most recent call last):
  File "BTCTurk.py", line 7, in <module>
    print(btcturk.fetch_balance())
  File "/usr/lib/python3.6/site-packages/ccxt/btcturk.py", line 67, in fetch_balance
    'free': response['bitcoin_available'],
KeyError: 'bitcoin_available'
```

Related: https://github.com/BTCTrader/broker-api-docs#account-balance-requires-authentication

**Comment by farukuzun** [comment]
Their main developer says they added `api/balancev2` URL to their API but they didn't mentioned it in their docs. Also they have a typo on `avaiable_balance`. Current API doesn't show XRP balance, so should i add this new api url to ccxt with a new commit, or maybe a btcturkv2.js file?

Example response of request to `api/balancev2`

```
{ "Success": true, "Message": null, "Data": [ { "currency": "TRY", "whole_balance": 198214.48, "avaiable_balance": 171049.45, "reserved_balance": 27165.02, "taker_fee": 0.0030000000000000, "maker_fee": 0.0007000000000000 }, { "currency": "BTC", "whole_balance": 13.06171323, "avaiable_balance": 3.00511429, "reserved_balance": 10.05659894, "taker_fee": 0.0040000000000000, "maker_fee": 0.0010000000000000 }, { "currency": "ETH", "whole_balance": 2.93632776, "avaiable_balance": 2.93632776, "reserved_balance": 0.0, "taker_fee": 0.0030000000000000, "maker_fee": 0.0007000000000000 }, { "currency": "LTC", "whole_balance": 109.30575023, "avaiable_balance": 108.1685, "reserved_balance": 1.13725023, "taker_fee": 0.0030000000000000, "maker_fee": 0.0007000000000000 }, { "currency": "XRP", "whole_balance": 103.4908, "avaiable_balance": 93.4908, "reserved_balance": 10.0, "taker_fee": 0.0030000000000000, "maker_fee": 0.0007000000000000 } ] }
```

Source: https://github.com/BTCTrader/broker-api-docs/issues/47

**Comment by kroitor** [comment]
> Current API doesn't show XRP balance, so should i add this new api url to ccxt with a new commit, or maybe a btcturkv2.js file?

I'd add this as a new API endpoint instead of `...v2.js`... We have other exchanges that do the same, bitfinex+bitfinex2, hitbtc+hitbtc2, bitstamp1+bitstamp, (see those for examples). Thx!
