### ISSUE TITLE
Kraken returns 'EGeneral:Invalid arguments:price' on stop-loss orders

### ISSUE THREAD

**Issue by Kapuca** [ccxt/ccxt#3040]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.14.131
- Exchange: Kraken
- Method: create_order

Kraken returns 'EGeneral:Invalid arguments:price' on stop-loss orders.
I tracked the problem down to the following code in `create_order` :
```
        if type == 'limit':
            order['price'] = self.price_to_precision(symbol, price)
```
at line 618.

My quick fix is changing the condition of if statement to:
`        if type == 'limit' or type == 'stop-loss':`
but this still doesn't account for other order types from Kraken:
```
    take-profit (price = take profit price)
    stop-loss-profit (price = stop loss price, price2 = take profit price)
    stop-loss-profit-limit (price = stop loss price, price2 = take profit price)
    stop-loss-limit (price = stop loss trigger price, price2 = triggered limit price)
    take-profit-limit (price = take profit trigger price, price2 = triggered limit price)
    trailing-stop (price = trailing stop offset)
    trailing-stop-limit (price = trailing stop offset, price2 = triggered limit offset)
    stop-loss-and-limit (price = stop loss price, price2 = limit price)
```
Which all require `price` parameter (and possibly others, but those are presumably passed in `params`)
I guess that
`if type in ['limit', 'stop-loss', 'take-profit', 'stop-loss-profit-limit', 'stop-loss-limit', 'take-profit-limit', 'trailing-stop', 'trailing-stop-limit', 'stop-loss-and-limit']`
would work, but I'll leave it here as an issue for somebody with more insight to decide

**Comment by lemassykoi** [comment]
Hi, I have the same problem on recent version (less than a week), and this error don't happen on dry run mode.

For the moment, I had to set `'stoploss_on_exchange': False`
`'stoploss':` was set to `'limit'`, didn't try with `'market'` option

Thanks

**Comment by kroitor** [comment]
@lemassykoi hi! Please, paste [these details](https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help) here.

**Comment by lemassykoi** [comment]
Sorry. Here it is, tell me if I miss something else, thanks.

- OS: Debian 10
- Programming Language version: Python3
- CCXT version: 1.40.14
- Exchange: Kraken
- Method: create_order (stop_loss)
- Using freqtrade

Logs :

```
2021-01-05 22:54:32,830 - freqtrade.persistence.models - WARNING - Did not find order for {'error': [], 'result': {'count': 1}}.
2021-01-05 22:54:35,824 - freqtrade.exchange.kraken - INFO - stoploss order added for DOT/BTC. stop price: 0.00027658.
2021-01-05 22:54:41,850 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair LINK/BTC (orderid:ZZZZZ-XXXXX-YYYYY) in order to add another one ...
2021-01-05 22:54:44,835 - freqtrade.persistence.models - WARNING - Did not find order for {'error': [], 'result': {'count': 1}}.
2021-01-05 22:54:47,836 - freqtrade.exchange.kraken - INFO - stoploss order added for LINK/BTC. stop price: 0.00041257.
2021-01-05 22:54:59,864 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair LTC/BTC (orderid:ZZZZZ-XXXXX-YYYYY) in order to add another one ...
2021-01-05 22:55:02,843 - freqtrade.persistence.models - WARNING - Did not find order for {'error': [], 'result': {'count': 1}}.
2021-01-05 22:55:05,867 - freqtrade.exchange.kraken - INFO - stoploss order added for LTC/BTC. stop price: 0.004491.
2021-01-05 22:55:12,182 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair ATOM/BTC (orderid:ZZZZZ-XXXXX-YYYYY) in order to add another one ...
2021-01-05 22:55:14,863 - freqtrade.persistence.models - WARNING - Did not find order for {'error': [], 'result': {'count': 1}}.
2021-01-05 22:55:17,865 - freqtrade.exchange.kraken - INFO - stoploss order added for ATOM/BTC. stop price: 0.0001768.
2021-01-05 22:55:23,870 - freqtrade.exchange.common - WARNING - stoploss() returned exception: "Could not place sell order due to ExchangeError. Message: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}"
2021-01-05 22:55:23,870 - freqtrade.exchange.common - WARNING - Giving up retrying: stoploss()
2021-01-05 22:55:23,871 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/freqtrade/exchange/kraken.py", line 103, in stoploss
    amount=amount, price=stop_price, params=params)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/kraken.py", line 939, in create_order
    response = self.privatePostAddOrder(self.extend(request, query))
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 624, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/kraken.py", line 1623, in handle_errors
    raise ExchangeError(message)
ccxt.base.errors.ExchangeError: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtradebot.py", line 914, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/freqtrade/exchange/common.py", line 150, in wrapper
    raise ex
  File "/freqtrade/exchange/common.py", line 135, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/exchange/kraken.py", line 121, in stoploss
    f'Could not place sell order due to {e.__class__.__name__}. Message: {e}') from e
freqtrade.exceptions.TemporaryError: Could not place sell order due to ExchangeError. Message: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}
2021-01-05 22:55:29,878 - freqtrade.exchange.common - WARNING - stoploss() returned exception: "Could not place sell order due to ExchangeError. Message: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}"
2021-01-05 22:55:29,878 - freqtrade.exchange.common - WARNING - Giving up retrying: stoploss()
2021-01-05 22:55:29,878 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/freqtrade/exchange/kraken.py", line 103, in stoploss
    amount=amount, price=stop_price, params=params)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/kraken.py", line 939, in create_order
    response = self.privatePostAddOrder(self.extend(request, query))
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 624, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/kraken.py", line 1623, in handle_errors
    raise ExchangeError(message)
ccxt.base.errors.ExchangeError: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtradebot.py", line 914, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/freqtrade/exchange/common.py", line 150, in wrapper
    raise ex
  File "/freqtrade/exchange/common.py", line 135, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/exchange/kraken.py", line 121, in stoploss
    f'Could not place sell order due to {e.__class__.__name__}. Message: {e}') from e
freqtrade.exceptions.TemporaryError: Could not place sell order due to ExchangeError. Message: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}
2021-01-05 22:55:32,759 - freqtrade.worker - INFO - Bot heartbeat. PID=1425, version='develop-cce4d7e4', state='RUNNING'
2021-01-05 22:55:59,989 - freqtrade.rpc.telegram - INFO - Executing handler: _reload_config for chat_id: XXXXXXXXX
2021-01-05 22:57:08,988 - freqtrade.exchange.common - WARNING - stoploss() returned exception: "Could not place sell order due to ExchangeError. Message: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}"
2021-01-05 22:57:08,988 - freqtrade.exchange.common - WARNING - Giving up retrying: stoploss()
2021-01-05 22:57:08,988 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/freqtrade/exchange/kraken.py", line 103, in stoploss
    amount=amount, price=stop_price, params=params)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/kraken.py", line 939, in create_order
    response = self.privatePostAddOrder(self.extend(request, query))
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 624, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/kraken.py", line 1623, in handle_errors
    raise ExchangeError(message)
ccxt.base.errors.ExchangeError: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtradebot.py", line 914, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/freqtrade/exchange/common.py", line 150, in wrapper
    raise ex
  File "/freqtrade/exchange/common.py", line 135, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/exchange/kraken.py", line 121, in stoploss
    f'Could not place sell order due to {e.__class__.__name__}. Message: {e}') from e
freqtrade.exceptions.TemporaryError: Could not place sell order due to ExchangeError. Message: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}
2021-01-05 22:57:14,993 - freqtrade.exchange.common - WARNING - stoploss() returned exception: "Could not place sell order due to ExchangeError. Message: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}"
2021-01-05 22:57:14,993 - freqtrade.exchange.common - WARNING - Giving up retrying: stoploss()
2021-01-05 22:57:14,993 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/freqtrade/exchange/kraken.py", line 103, in stoploss
    amount=amount, price=stop_price, params=params)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/kraken.py", line 939, in create_order
    response = self.privatePostAddOrder(self.extend(request, query))
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 624, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/freqtrade/.env/lib/python3.7/site-packages/ccxt/kraken.py", line 1623, in handle_errors
    raise ExchangeError(message)
ccxt.base.errors.ExchangeError: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtradebot.py", line 914, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/freqtrade/exchange/common.py", line 150, in wrapper
    raise ex
  File "/freqtrade/exchange/common.py", line 135, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/exchange/kraken.py", line 121, in stoploss
    f'Could not place sell order due to {e.__class__.__name__}. Message: {e}') from e
freqtrade.exceptions.TemporaryError: Could not place sell order due to ExchangeError. Message: kraken {"error":["EOrder:Invalid price:Invalid secondary price argument."]}
2021-01-05 22:57:17,861 - freqtrade.worker - INFO - Bot heartbeat. PID=1425, version='develop-cce4d7e4', state='RUNNING'
2021-01-05 22:57:17,861 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'reload_config'}
2021-01-05 22:57:17,935 - freqtrade.worker - INFO - Changing state to: RELOAD_CONFIG
2021-01-05 22:57:17,935 - freqtrade.worker - INFO - Bot heartbeat. PID=1425, version='develop-cce4d7e4', state='RELOAD_CONFIG'
2021-01-05 22:57:17,935 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
```

**Comment by kroitor** [comment]
@lemassykoi unfortunately, we can't use the above info containing just the error callstack, since it is missing a few essential things listed here https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help:

- your minimal code snippet to reproduce the issue with ccxt (cause we need to see how you instantiate the exchange and which params you use, except that we don't need your keys)
- your verbose output from ccxt (you've pasted the output from `freqtrade` instead, so i'd suggest to post it on the freqtrade repository, if you are not using ccxt directly)

The question is which params are being set by `freqtrade` upon creating the order, and i suggest asking here: https://github.com/freqtrade/freqtrade. If it turns out to be a bug in CCXT – we will address it quickly.

**Comment by lemassykoi** [comment]
Thank you very much for your kind answer. I will do what you suggest and will come back to you if necessary.

**Comment by kroitor** [comment]
@lemassykoi just in case, a quickfix in `freqtrade` would be to place the stop-loss orders with Kraken like so:

```Python
order = exchange.create_order(symbol, 'stop-loss', side, amount, price)
```
