### ISSUE TITLE
ref: #3006 - coinbase sign method exception when using Python 3

### ISSUE THREAD

**Issue by bendemott** [ccxt/ccxt#3050]
- OS: linux (ubuntu 18)
- programming version: python 3.6
- CCXT version: 1.14.140
- Exchange: coinbase
- Method: fetchMarkets

If you provide a apikey and secret keys as a string object in Python, you'll get the following error:

```
Traceback (most recent call last):
  File "ccxt-coinbase.py", line 12, in <module>
    pprint(coinbase.fetchBalance())
  File "/usr/local/lib/python3.6/dist-packages/ccxt/coinbase.py", line 159, in fetch_balance
    balances = self.privateGetAccounts()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 308, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 304, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/coinbase.py", line 188, in sign
    signature = self.hmac(self.encode(what), self.secret)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 736, in hmac
    h = hmac.new(secret, request, algorithm)
  File "/usr/lib/python3.6/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.6/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
```
If you provide apikey and secret keys as a bytes object in Python3 you'll get the following error:

Traceback (most recent call last):
  File "ccxt-coinbase.py", line 12, in <module>
    pprint(coinbase.fetchBalance())
  File "/usr/local/lib/python3.6/dist-packages/ccxt/coinbase.py", line 159, in fetch_balance
    balances = self.privateGetAccounts()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 308, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 304, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/coinbase.py", line 191, in sign
    'CB-ACCESS-SIGN': self.decode(signature),
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 785, in decode
    return string.decode()
AttributeError: 'str' object has no attribute 'decode'

**I'm working on a patch now**

**Comment by kroitor** [comment]
> I'm working on a patch now

Thx! Just make sure to read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by cloudseasail** [comment]
I see this issue in Exchange: cointiger as well.
Could you kindly provide a guide or patch,  to workaround it to unblock my test, please?

**Comment by cloudseasail** [comment]
@kroitor  Could you please help to check how to port your fix into cointiger, please?  Thanks!

> C:\ProgramData\Miniconda3\lib\site-packages\ccxt\cointiger.py in sign(self, path, api, method, params, headers, body)
>     527                 'time': timestamp,
>     528             }, urlParams)))
> --> 529             url += '&sign=' + self.decode(signature)
>     530             if method == 'POST':
>     531                 body = self.urlencode(query)
> 
> C:\ProgramData\Miniconda3\lib\site-packages\ccxt\base\exchange.py in decode(string)
>     783     @staticmethod
>     784     def decode(string):
> --> 785         return string.decode()
>     786 
>     787     @staticmethod
> 
> AttributeError: 'str' object has no attribute 'decode'

**Comment by kroitor** [comment]
@cloudseasail done! The fix is available as of CCXT version 1.14.152. Thx for reporting!
