### ISSUE TITLE
ref: #3050 - Other Python transpiling issues, add support for fetchCurrencies() and fetchTciker()

### ISSUE THREAD

**Issue by bendemott** [ccxt/ccxt#3062]
OS: linux (ubuntu 18)
programming version: python 3.6
CCXT version: 1.14.146
Exchange: coinbase
Method: fetchBalance

### Decoding the return of hmac not necessary 

```
            headers = this.extend ({
                'CB-ACCESS-KEY': this.apiKey,
                'CB-ACCESS-SIGN': signature,
                'CB-ACCESS-TIMESTAMP': nonce,
                'Content-Type': 'application/json',
            }, headers);
        }
```

```
Traceback (most recent call last):
  File "ccxt-coinbase.py", line 14, in <module>
    pprint(coinbase.fetch_balance())
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.14.124-py3.6.egg/ccxt/coinbase.py", line 244, in fetch_balance
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.14.124-py3.6.egg/ccxt/base/exchange.py", line 308, in request
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.14.124-py3.6.egg/ccxt/base/exchange.py", line 304, in fetch2
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.14.124-py3.6.egg/ccxt/coinbase.py", line 277, in sign
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.14.124-py3.6.egg/ccxt/base/exchange.py", line 785, in decode
AttributeError: 'str' object has no attribute 'decode'
```

### Accessing elements as properties does not transpile in Python correctly

```
Traceback (most recent call last):
  File "ccxt-coinbase.py", line 14, in <module>
    pprint(coinbase.fetch_balance())
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.14.124-py3.6.egg/ccxt/coinbase.py", line 246, in fetch_balance
AttributeError: 'dict' object has no attribute 'data'
```

**Comment by bendemott** [comment]
Pull Request: #3063
