### ISSUE TITLE
coinbase sign method - headers is undefined

### ISSUE THREAD

**Issue by bendemott** [ccxt/ccxt#3066]
OS: linux (ubuntu 18)
programming version: python 3.6
CCXT version: 1.14.148
Exchange: coinbase
Method: sign

### In Python you cannot call this.extend() on a null or undefined

```
Traceback (most recent call last):
  File "ccxt-coinbase.py", line 14, in <module>
    pprint(coinbase.fetch_balance())
  File "/usr/local/lib/python3.6/dist-packages/ccxt/coinbase.py", line 243, in fetch_balance
    response = self.privateGetAccounts()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 308, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 304, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/coinbase.py", line 280, in sign
    }, headers)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 498, in extend
    result.update(arg)
TypeError: 'NoneType' object is not iterable
```

### Caused By Line 
https://github.com/ccxt/ccxt/blob/master/js/coinbase.js#L274

**Was it intentional to leave this commented out?**
`        // headers = this.options['defaultHeaders'];`

```
            headers = this.extend ({
                'CB-ACCESS-KEY': this.apiKey,
                'CB-ACCESS-SIGN': signature,
                'CB-ACCESS-TIMESTAMP': nonce,
                'Content-Type': 'application/json',
            }, headers);
```

**Comment by kroitor** [comment]
One sec will fix this shortly... A leftover...
