### ISSUE TITLE
How to create a Stop-Loss Order on Binance?

### ISSUE THREAD

**Issue by alexgpark** [ccxt/ccxt#3139]
- OS: Mac OS High Sierra
- Programming Language version: Javascript (node)
- CCXT version: ccxt@1.14.196
- Exchange: Binance
- Method:

I am trying to create a Stop Loss order but after several attempts, I can't seem to figure out how to do it successfully as I keep error messages like these:

`
error selling asset [InvalidOrder] binance {"code":-1100,"msg":"Illegal characters found in parameter 'type'; legal range is '^[a-zA-Z_]{1,20}$'."}
                        at handleErrors   ccxt/js/binance.js:919             throw new exceptions[error] (this.id + ' ' + body);
                        at then           ccxt/js/base/Exchange.js:568       this.handleErrors (...args)
                        at _tickCallback  internal/process/next_tick.js:188
`

`error selling asset [ExchangeError] binance: unknown error code: {"code":-1116,"msg":"Invalid orderType."} -1116
                        at handleErrors   ccxt/js/binance.js:911             throw new ExchangeError (this.id + ': unknown error code: ' + body + ' ' + erro…
                        at then           ccxt/js/base/Exchange.js:568       this.handleErrors (...args)
                        at _tickCallback  internal/process/next_tick.js:188
`

I have tried:

`lowestPriceExchange.exchange.createLimitSellOrder (coinPair, quantity, limitPrice, { 'type': 'stop-loss', 'stopPrice': stopPrice })`

as well as:

`lowestPriceExchange.exchange.createOrder(coinPair, 'limit', 'sell', quantity, limitPrice, { 'stop': 'loss', 'stop_price': stopPrice })`

This is after looking through:
https://github.com/ccxt/ccxt/issues/1524
https://github.com/ccxt/ccxt/issues/1557

Does anyone have an example of a working code for creating a stop-loss order?
What is the right combination of parameters and variables and what is the right syntax?

**Comment by alexgpark** [comment]
Thank you @kroitor !

**Comment by Flipper89** [comment]
i'm probably using the old API i guess, i'll take a look at the new ones within the link you sent.
Thanks for your help.

**Comment by kkaiser0** [comment]
If you are looking for another option, check out Signal.

Our trading tool is fast, secure, and easy to use.

Some key features include:
- Setting a stop loss and up to 5 take profits at the same time
- Trailing stop loss
- Laddered buys
- SMS alerts

Sign up at:
https://signalgroups.com/

**Comment by kkaiser0** [comment]
If you are looking for another option, check out Signal.

Our trading tool is fast, secure, and easy to use.

Some key features include:
- Setting a stop loss and up to 5 take profits at the same time
- Trailing stop loss
- Laddered buys
- SMS alerts

Sign up at

**Comment by Princeton007** [comment]
Can someone help me please.. I'm stuck with Binance, it throws me an error: 

ccxt.base.errors.ExchangeError: binance {"code":-1104,"msg":"Not all sent parameters were read; read '10' parameter(s) but was sent '12'."}

when I try to place a Stop Limit Order with:

```python
params = { 'stop': 'loss', 'stop_price': stop_price }
order =  exchange.createOrder(symbol, type, side, amount, limit_price, params)
````

**Comment by kroitor** [comment]
@Princeton007 sure! First of, make sure your version of CCXT is up to date (1.23.69)

Then, try this:

```Python
params = { 'stopPrice': stop_price }
order =  exchange.createOrder(symbol, 'STOP_LOSS', side, amount, limit_price, params)
```

↑ If it does not work, do this:

```Python
exchange.load_markets()
exchange.verbose = True
params = { 'stopPrice': stop_price }
order =  exchange.createOrder(symbol, 'STOP_LOSS', side, amount, limit_price, params)
```

↑ and paste your output here (without your keys).

**Comment by Princeton007** [comment]
thanks @kroitor 
I updated CCXT to the latest version but the error was still the same. 
Then I tried your proposal, it returned a different error as you can see below:

CCXT version: 1.23.76
Traceback (most recent call last):
  File "E:/Pycharm-RTB/binance.py", line 129, in <module>
    order =  exchange.createOrder(symbol, 'STOP_LOSS', side, amount, limit_price, params)
  File "C:\ProgramData\Anaconda3\envs\Pycharm-RTB\lib\site-packages\ccxt\binance.py", line 1032, in create_order
    raise InvalidOrder(self.id + ' ' + type + ' is not a valid order type in ' + market['type'] + ' market ' + symbol)
ccxt.base.errors.InvalidOrder: binance STOP_LOSS is not a valid order type in spot market BTC/USDT

**Comment by kroitor** [comment]
@Princeton007 you can see which types are available for BTC/USDT with that spot and futures pair on Binance:

```Python
# spot
from pprint import pprint
import ccxt
exchange = ccxt.binance({enableRateLimit: True})
exchange.load_markets()
pprint(exchange.market['BTC/USDT'])
```

```Python
# futures
from pprint import pprint
import ccxt
exchange = ccxt.binance({enableRateLimit: True, 'options': {'defaultType': 'future'}})
exchange.load_markets()
pprint(exchange.market['BTC/USDT'])
```

That is the `info` from the exchange first-hand, basically. It depends on which type of Binance markets you're trading. In fact, I can't find `STOP_LOSS` on any market, so Binance could disable this type, despite that it is mentioned in the docs. If that is the case, you might want to pick a different type of order, depending on whether you're trading futures or spot markets. Let me know if that does not help.

**Comment by Princeton007** [comment]
Thanks, @kroitor I found out how it works:
````python
params = { 'stopPrice': stop_price }
order =  exchange.createOrder(symbol, 'STOP_LOSS_LIMIT', side, amount, limit_price, params)
````

**Comment by MyStyleAlways** [comment]
Just mention that, we cannot use  'STOP_LOSS_LIMIT' anymore. USE -> 'STOP'. That's it!

check order types below!

          'orderTypes': ['LIMIT',
                         'MARKET',
                         'STOP',
                         'STOP_MARKET',
                         'TAKE_PROFIT',
                         'TAKE_PROFIT_MARKET',
                         'TRAILING_STOP_MARKET'],

**Comment by kroitor** [comment]
@Princeton007 to clarify: https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L2624

```JavaScript
        //
        // spot/margin
        //
        //     LIMIT                timeInForce, quantity, price
        //     MARKET               quantity or quoteOrderQty
        //     STOP_LOSS            quantity, stopPrice
        //     STOP_LOSS_LIMIT      timeInForce, quantity, price, stopPrice
        //     TAKE_PROFIT          quantity, stopPrice
        //     TAKE_PROFIT_LIMIT    timeInForce, quantity, price, stopPrice
        //     LIMIT_MAKER          quantity, price
        //
        // futures
        //
        //     LIMIT                timeInForce, quantity, price
        //     MARKET               quantity
        //     STOP/TAKE_PROFIT     quantity, price, stopPrice
        //     STOP_MARKET          stopPrice
        //     TAKE_PROFIT_MARKET   stopPrice
        //     TRAILING_STOP_MARKET callbackRate
        //
```

**Comment by sirpawulo** [comment]
Hi Kroito, have you succeeded in creating the code for stop loss??

**Comment by barresoft** [comment]
For binance, you can read the actual program code at
https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L2624

I use it for 'SANDBUSD' pair, based on market price.
Coins is the total coins, in this case, the total SAND coins

Futures code for LONG:
`params = { 'stopPrice': stop_price_here }` #lower than actual price
`order =  exchange.createOrder('SANDBUSD', 'MARKET', 'buy', coins, None, params)`

Futures code for SHORT:
`params = { 'stopPrice': stop_price_here  }` #higher than actual price
`order =  exchange.createOrder('SANDBUSD', 'MARKET', 'sell', coins, None, params)`
