### ISSUE TITLE
SSLError when running in multiple processes

### ISSUE THREAD

**Issue by mizuto** [ccxt/ccxt#3189]
Hi all, I've been facing a SSL issue and I'm unsure whether its my setup or the ccxt itself.
The full error code is: 
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2217)

I get this whenever I run calls in Proccesses.
Here is a psudocode:
for exchange in exchanges:
     exchange.load_markets(True)

for exchange in exchanges:
    process = Process(target=exchange.buy)
    process.start()

for process in allProcesses:
    process.join()

for exchange in exchanges:
    process = Process(target=exchange.sell)
    process.start()

I've been testing with only one exchange, bittrex, and it still happens.
The error occurs around the 3rd time whenever it tries to call bittrex.
i.e. if i let the buy to go through successfully, it errors out inside sell (load_markets, create_order in buy, and get_balance in sell)
However, if I retry buy on purpose, it will error out on the first retry(load_markets, create_order, create_order).

Please advice (see below for stacktrace)

- OS: Linux
- Programming Language version: Python
- CCXT version: 1.14.228
- Exchange: bittrex
- Method:

raceback (most recent call last):
  File "/home/jit015/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/jit015/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/jit015/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2217)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jit015/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/jit015/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jit015/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bittrex.com', port=443): Max retries exceeded with url: /api/v2.0/pub/Markets/GetMarketSummaries (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2217)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jit015/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 359, in fetch
    proxies=self.proxies
  File "/home/jit015/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jit015/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/jit015/.local/lib/python3.6/site-packages/requests/adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='bittrex.com', port=443): Max retries exceeded with url: /api/v2.0/pub/Markets/GetMarketSummaries (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2217)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BuySellTest.py", line 58, in <module>
    entry.exchange.load_markets(True)
  File "/home/jit015/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 919, in load_markets
    markets = self.fetch_markets()
  File "/home/jit015/.local/lib/python3.6/site-packages/ccxt/bittrex.py", line 185, in fetch_markets
    response = self.v2GetMarketsGetMarketSummaries()
  File "/home/jit015/.local/lib/python3.6/site-packages/ccxt/bittrex.py", line 742, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/jit015/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/jit015/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 383, in fetch
    self.raise_error(ExchangeError, url, method, e, self.last_http_response)
  File "/home/jit015/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 290, in raise_error
    raise exception_type(output)

**Comment by kroitor** [comment]
Possible solutions:

1. For concurrency in Python 3.5, the asyncio version of CCXT is highly recommended instead of the synchronous one.

2. The rule of thumb with concurrency is to stay with one exchange instance per thread (don't share/mix exchanges instances across multiple different threads) – instantiate the exchange in a thread and do everything with it there, exposing just the necessary thread intercom methods (depending on your own needs). Once the thread is done – destroy it. Also save the markets and initialize the exchange with presaved markets to avoid loading them in every thread.

3. Worth reading:

- https://stackoverflow.com/questions/45948028/what-is-the-recommended-way-of-sharing-a-http-connection-pool-between-threads-wi (a possible solution is to use a separate `urllib3.ConnectionPool` per thread)
- https://stackoverflow.com/questions/18188044/is-the-session-object-from-pythons-requests-library-thread-safe (a possible solution would be to use one `requests.Session` object per thread, this will require a few very small overrides of the exchange.session to decouple it)

Let us know if this does not answer your question.

**Comment by thornycrackers** [comment]
I also had this exact same issue with running in multiple processes. I just switched away from running multiple processes and the problem went away so thanks @kroitor for your insight :+1:
