### ISSUE TITLE
minimum amount limits are too low as listed

### ISSUE THREAD

**Issue by benediamond** [ccxt/ccxt#3221]
hi @kroitor, on bibox and huobipro, the listed limits are often too small. For example,
```python
>>> huobi.markets['WAX/ETH']['limits']
{'amount': {'min': 0.0001, 'max': 10000.0}, 'price': {'min': 1e-06, 'max': None}, 'cost': {'min': 0, 'max': None}}
```
and yet,
```python
>>> huobi.create_limit_buy_order('WAX/ETH', 0.01, 0.000238)
{'info': {'status': 'ok', 'data': '6336531606'}, 'id': '6336531606', 'timestamp': 1529683491146, 'datetime': '2018-06-22T16:04:51.146Z', 'lastTradeTimestamp': None, 'status': None, 'symbol': 'WAX/ETH', 'type': 'limit', 'side': 'buy', 'price': 0.000238, 'amount': 0.01, 'filled': None, 'remaining': None, 'cost': None, 'trades': None, 'fee': None}
>>> huobi.create_limit_buy_order('WAX/ETH', 0.009, 0.000238)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1313, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "/usr/local/lib/python3.6/site-packages/ccxt/huobipro.py", line 586, in create_order
    response = getattr(self, method)(self.extend(order, params))
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 308, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 385, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "/usr/local/lib/python3.6/site-packages/ccxt/huobipro.py", line 719, in handle_errors
    raise exceptions[code](feedback)
ccxt.base.errors.InvalidOrder: huobipro {"status":"error","err-code":"order-limitorder-amount-min-error","err-msg":"limit order amount error, min: `0.01`","data":null}
```
I'm not sure if there is a good fix other than hardcoding. This limit appears to exist for various currencies though, and something similar happens on Bibox. Perhaps we can use this place to collect examples, before changing the code?

**Comment by benediamond** [comment]
here's another instance.
```python
>>> bittrex.load_markets()['BLT/ETH']['limits']
{'amount': {'min': 1e-08, 'max': None}, 'price': {'min': 1e-08, 'max': None}}
>>> bittrex.create_limit_sell_order('BLT/ETH', 1.0, 0.00045256)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1316, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/bittrex.py", line 462, in create_order
    response = getattr(self, method)(self.extend(order, params))
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/bittrex.py", line 743, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 385, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/bittrex.py", line 712, in handle_errors
    raise InvalidOrder(self.id + ' order cost should be over 50k satoshi ' + self.json(response))
ccxt.base.errors.InvalidOrder: bittrex order cost should be over 50k satoshi {"success":false,"message":"DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT","result":null}
```
not sure what's going on here. perhaps this is a failure upstream, of bittrex's reporting? maybe there's nothing we can do?

**Comment by bohdanz1997** [comment]
New limits listed here: https://huobiglobal.zendesk.com/hc/en-us/articles/360000400491-Trade-Limits
It can be great to parse them from this page like in kraken implemented

**Comment by kroitor** [comment]
@benediamond yep, we've been lacking that info from their API, but, thx to @bohdanz1997 for the hint and for the link, we'll add a parser for their trading rule asap.

**Comment by bohdanz1997** [comment]
@kroitor thx, i will be waiting with trepidation, this release:grinning:

**Comment by kroitor** [comment]
Feel free to reopen it, if you have this issue with the most recent version of CCXT.
