### ISSUE TITLE
Bitstamp fetchDepositAddress for BTC: invalid or has less than 1 characters

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#3256]
- OS: Mac OS 10.13.5
- Programming Language version: Node JS 8.11.3
- CCXT version: 1.14.272
- Exchange: bitstamp
- Method: fetchDepositAddress

To reproduce:

```
let bitstamp = new ccxt.bitstamp(mykey)
await bitstamp.fetchDepositAddress('BTC')
```

I get:

```
Error: bitstamp address is invalid or has less than 1 characters: "[object Object]"
    at bitstamp.checkAddress (/Users/firepol/myapp/node_modules/ccxt/js/base/Exchange.js:344:19)
    at bitstamp.fetchDepositAddress (/Users/firepol/myapp/node_modules/ccxt/js/bitstamp.js:570:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I tried with another cryptocurrency, e.g. `XRP` it works.

Only for bitcoin it doesn't work. My bitcoin address begins with `3BQ` (created in Sep 2017) can this be the issue? Segwit address not supported by ccxt?

**Comment by kroitor** [comment]
> Only for bitcoin it doesn't work. 

Can you please post your **verbose request and response** (without your keys), as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ? We will be able to fix it quickly, then.

```JavaScript
let bitstamp = new ccxt.bitstamp(mykey)
await bitstamp.loadMarkets()
bitstamp.verbose = true
await bitstamp.fetchDepositAddress('BTC')
```

> My bitcoin address begins with 3BQ (created in Sep 2017) can this be the issue?

Nope. The reason is with a broken parser (fixable).

> Segwit address not supported by ccxt?

All of them should be supported.

**Comment by firepol** [comment]
```
fetch:
 bitstamp POST https://www.bitstamp.net/api/bitcoin_deposit_address/ 
Request:
 { 'Content-Type': 'application/x-www-form-urlencoded' } 
 key=&signature=mysig&nonce=mynonce 

[17:57:23.288] [debug] Balances fetched.
handleRestResponse:
 bitstamp POST https://www.bitstamp.net/api/bitcoin_deposit_address/ 200 OK 
Response:
 { 'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control',
  'Access-Control-Allow-Methods': 'POST, GET',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'max-age=0',
  'Content-Language': 'en',
  'Content-Type': 'application/json',
  Date: 'Tue, 26 Jun 2018 14:57:23 GMT',
  Expires: 'Tue, 26 Jun 2018 14:57:23 GMT',
  'Last-Modified': 'Tue, 26 Jun 2018 14:57:23 GMT',
  Server: 'Apache',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains',
  Vary: 'Authorization,Accept-Language',
  'X-Frame-Options': 'SAMEORIGIN',
  'Transfer-Encoding': 'chunked',
  Connection: 'Close',
  'Set-Cookie': 'incap_ses_878_99025=FWogCtbQUi3QFTOXuEgvDFJUMlsAAAAAG5lnp5AJs7qkJNqpNU3WAA==; path=/; Domain=.bitstamp.net',
  'X-Iinfo': '11-2629361-2629418 NNNN CT(3 1 0) RT(1530025042541 192) q(0 0 0 -1) r(0 0) U6',
  'X-Cdn': 'Incapsula',
  'Content-Encoding': 'gzip' } 
 {"error": "No permission found"} 

[17:57:23.672] [debug] Error: bitstamp address is invalid or has less than 1 characters: "[object Object]"
    at bitstamp.checkAddress (/Users/firepol/myapp/node_modules/ccxt/js/base/Exchange.js:344:19)
    at bitstamp.fetchDepositAddress (/Users/firepol/myapp/node_modules/ccxt/js/bitstamp.js:570:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Now it's clear why I got that: ` {"error": "No permission found"} `

In fact I checked and my api key hasn't permission for that. I guess the fix should make the error appear...
