### ISSUE TITLE
Tidebit fetch_balance() issues 

### ISSUE THREAD

**Issue by araa47** [ccxt/ccxt#3259]
- OS: macOS Sierra
- Programming Language version: Python 3.6.5
- CCXT version: 1.14.272
- Exchange: Tidebit 
- Method: fetch_balance()

I am running into errors trying to get balance from tidebit. My code is attached below and the access_key and signature have been changed to ** in the error message. 

```
import ccxt 
import pprint 

exchange = ccxt.tidebit({'apiKey': 'test',
 						'secret': 'test'})

exchange.verbose = True 

balance = exchange.fetch_balance()
pprint.pprint(balance)

```

```
Request: GET https://www.tidebit.com/api/v2/markets.json {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.tidebit.com/api/v2/markets.json 200 {'Date': 'Tue, 26 Jun 2018 11:49:14 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d4c9465d3c2f970650d2e876155c866811530013754; expires=Wed, 26-Jun-19 11:49:14 GMT; path=/; domain=.tidebit.com; HttpOnly; Secure', 'Status': '200 OK', 'Cache-Control': 'max-age=0, private, must-revalidate', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000, max-age=63072000; includeSubDomains', 'X-Request-Id': 'e4b8ea7c-c68b-4135-a2aa-21e0157c9d94', 'ETag': 'W/"e4c81943be111d0bbe88064618ddbcfb"', 'X-Runtime': '0.008687', 'X-Powered-By': 'Phusion Passenger 5.3.2', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '430f730b5c9484ae-HKG', 'Content-Encoding': 'gzip'} [{"id":"btchkd","name":"BTC/HKD","bid_fixed":2,"ask_fixed":3,"price_group_fixed":null},{"id":"ethhkd","name":"ETH/HKD","bid_fixed":2,"ask_fixed":3,"price_group_fixed":null},{"id":"btcusd","name":"BTC/USD","bid_fixed":2,"ask_fixed":3,"price_group_fixed":null},{"id":"ethusd","name":"ETH/USD","bid_fixed":2,"ask_fixed":3,"price_group_fixed":null},{"id":"hkxhkd","name":"HKX/HKD","bid_fixed":4,"ask_fixed":4,"price_group_fixed":4},{"id":"eoshkd","name":"EOS/HKD","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"xpaeth","name":"XPA/ETH","bid_fixed":8,"ask_fixed":2,"price_group_fixed":8},{"id":"neohkd","name":"NEO/HKD","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"usxusd","name":"USX/USD","bid_fixed":4,"ask_fixed":4,"price_group_fixed":4},{"id":"usxhkx","name":"USX/HKX","bid_fixed":4,"ask_fixed":4,"price_group_fixed":4},{"id":"btchkx","name":"BTC/HKX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"ethhkx","name":"ETH/HKX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"xpahkx","name":"XPA/HKX","bid_fixed":4,"ask_fixed":4,"price_group_fixed":null},{"id":"cbthkx","name":"CBT/HKX","bid_fixed":4,"ask_fixed":4,"price_group_fixed":null},{"id":"eoshkx","name":"EOS/HKX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"eosusx","name":"EOS/USX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"btcusx","name":"BTC/USX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"likehkx","name":"LIKE/HKX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"cbteth","name":"CBT/ETH","bid_fixed":8,"ask_fixed":4,"price_group_fixed":8},{"id":"ethusx","name":"ETH/USX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"xpausx","name":"XPA/USX","bid_fixed":4,"ask_fixed":4,"price_group_fixed":null},{"id":"cbtusx","name":"CBT/USX","bid_fixed":4,"ask_fixed":4,"price_group_fixed":null}]

Request: GET https://www.tidebit.com/api/v2/deposits.json?access_key=**&tonce=1530013754463&signature=** {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.tidebit.com/api/v2/deposits.json?access_key=**&tonce=1530013754463&signature=** 404 {'Date': 'Tue, 26 Jun 2018 11:49:14 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d4c9465d3c2f970650d2e876155c866811530013754; expires=Wed, 26-Jun-19 11:49:14 GMT; path=/; domain=.tidebit.com; HttpOnly; Secure', 'Status': '404 Not Found', 'Cache-Control': 'no-cache', 'Strict-Transport-Security': 'max-age=31536000', 'X-Request-Id': '28b85dfb-7160-4eee-b525-0ed90b6135d8', 'X-Runtime': '0.001085', 'X-Powered-By': 'Phusion Passenger 5.3.2', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '430f730d7d4584ae-HKG', 'Content-Encoding': 'gzip'} Not Found
Traceback (most recent call last):
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 366, in fetch
    response.raise_for_status()
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.tidebit.com/api/v2/deposits.json?access_key=**&tonce=1530013754463&signature=**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "balance.py", line 74, in <module>
    balance = exchange.fetch_balance()
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/tidebit.py", line 138, in fetch_balance
    response = self.privateGetV2Deposits()
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 308, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 379, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 408, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 290, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: tidebit https://www.tidebit.com/api/v2/deposits.json?access_key=**&tonce=1530013754463&signature=** GET 404 Client Error: Not Found for url: https://www.tidebit.com/api/v2/deposits.json?access_key=6c4d1d4e56704601a72b09d6672e0175&tonce=1530013754463&signature=83aba3d421a489e1464ef9f2f3c78c63666c6603085be0f4ad6ef8ba52a693ee Not Found
```

After looking through the API documentation for Tidebit https://www.tidebit.com/swagger , this doesn't seem to be the correct URL to get the users balance. A better way would be using the /api/v2/members/me.json url. 

I have tested out using the members URL using GET request and seems to show my balance without any issues. How would i go about in changing the internal URL ccxt uses for the time being?

**Comment by araa47** [comment]
@kroitor , how do I install the latest version with this change in effect? Will a pip uninstall and install reflect these changes on python version of ccxt?

**Comment by kroitor** [comment]
@araa47 

> @kroitor , how do I install the latest version with this change in effect? 

https://packaging.python.org/tutorials/installing-packages/#upgrading-packages

> Will a pip uninstall and install reflect these changes on python version of ccxt?

Yep )

**Comment by araa47** [comment]
@kroitor thanks for the quick response. Just upgraded and re-tried. Still running into issues. I had tons of issues initially with using Tidebit related to the signature even with my own code. 

```

Request: GET https://www.tidebit.com/api/v2/markets.json {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.tidebit.com/api/v2/markets.json 200 {'Date': 'Tue, 26 Jun 2018 15:37:02 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d82b134562fab8afab8c87cfe2e65897b1530027422; expires=Wed, 26-Jun-19 15:37:02 GMT; path=/; domain=.tidebit.com; HttpOnly; Secure', 'Status': '200 OK', 'Cache-Control': 'max-age=0, private, must-revalidate', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000, max-age=63072000; includeSubDomains', 'X-Request-Id': '89ce8bb8-3bff-4b5f-817b-577c02f5e3ba', 'ETag': 'W/"e4c81943be111d0bbe88064618ddbcfb"', 'X-Runtime': '0.009205', 'X-Powered-By': 'Phusion Passenger 5.3.2', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4310c0bbbc30a2c0-HKG', 'Content-Encoding': 'gzip'} [{"id":"btchkd","name":"BTC/HKD","bid_fixed":2,"ask_fixed":3,"price_group_fixed":null},{"id":"ethhkd","name":"ETH/HKD","bid_fixed":2,"ask_fixed":3,"price_group_fixed":null},{"id":"btcusd","name":"BTC/USD","bid_fixed":2,"ask_fixed":3,"price_group_fixed":null},{"id":"ethusd","name":"ETH/USD","bid_fixed":2,"ask_fixed":3,"price_group_fixed":null},{"id":"hkxhkd","name":"HKX/HKD","bid_fixed":4,"ask_fixed":4,"price_group_fixed":4},{"id":"eoshkd","name":"EOS/HKD","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"xpaeth","name":"XPA/ETH","bid_fixed":8,"ask_fixed":2,"price_group_fixed":8},{"id":"neohkd","name":"NEO/HKD","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"usxusd","name":"USX/USD","bid_fixed":4,"ask_fixed":4,"price_group_fixed":4},{"id":"usxhkx","name":"USX/HKX","bid_fixed":4,"ask_fixed":4,"price_group_fixed":4},{"id":"btchkx","name":"BTC/HKX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"ethhkx","name":"ETH/HKX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"xpahkx","name":"XPA/HKX","bid_fixed":4,"ask_fixed":4,"price_group_fixed":null},{"id":"cbthkx","name":"CBT/HKX","bid_fixed":4,"ask_fixed":4,"price_group_fixed":null},{"id":"eoshkx","name":"EOS/HKX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"eosusx","name":"EOS/USX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"btcusx","name":"BTC/USX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"likehkx","name":"LIKE/HKX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"cbteth","name":"CBT/ETH","bid_fixed":8,"ask_fixed":4,"price_group_fixed":8},{"id":"ethusx","name":"ETH/USX","bid_fixed":2,"ask_fixed":4,"price_group_fixed":null},{"id":"xpausx","name":"XPA/USX","bid_fixed":4,"ask_fixed":4,"price_group_fixed":null},{"id":"cbtusx","name":"CBT/USX","bid_fixed":4,"ask_fixed":4,"price_group_fixed":null}]

Request: GET https://www.tidebit.com/api/v2/members/me.json?access_key=**&tonce=1530027422119&signature=** {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.tidebit.com/api/v2/members/me.json?access_key=**&tonce=1530027422119&signature=** 401 {'Date': 'Tue, 26 Jun 2018 15:37:02 GMT', 'Content-Type': 'application/json', 'Content-Length': '412', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d82b134562fab8afab8c87cfe2e65897b1530027422; expires=Wed, 26-Jun-19 15:37:02 GMT; path=/; domain=.tidebit.com; HttpOnly; Secure', 'Status': '401 Unauthorized', 'Cache-Control': 'no-cache', 'Strict-Transport-Security': 'max-age=31536000', 'X-Request-Id': '4938dc73-a858-435d-ba91-9adfd02863f9', 'X-Runtime': '0.006278', 'X-Powered-By': 'Phusion Passenger 5.3.2', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4310c0bc4c7ea2c0-HKG'} {"error":{"code":2005,"message":[{"en-US":"Signature ** is incorrect.","zh-CN":"签名 ** 不正确","zh-TW":"簽名 ** 不正確","zh-HK":"簽名 ** 不正確"}]}}
Traceback (most recent call last):
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 366, in fetch
    response.raise_for_status()
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.tidebit.com/api/v2/members/me.json?access_key=**&tonce=1530027422119&signature=**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "balance.py", line 72, in <module>
    balance()
  File "balance.py", line 49, in balance
    bal = exchange.fetch_balance()
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/tidebit.py", line 138, in fetch_balance
    response = self.privateGetV2MembersMe()
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 308, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 379, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 408, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/Users/Akshay/.local/share/virtualenvs/Scraping-2w5LtXA4/lib/python3.6/site-packages/ccxt/base/exchange.py", line 290, in raise_error
    raise exception_type(output)
ccxt.base.errors.AuthenticationError: tidebit https://www.tidebit.com/api/v2/members/me.json?access_key=**&tonce=1530027422119&signature=** GET 401 Client Error: Unauthorized for url: https://www.tidebit.com/api/v2/members/me.json?access_key=**&tonce=1530027422119&signature=** {"error":{"code":2005,"message":[{"en-US":"Signature ** is incorrect.","zh-CN":"签名 ** 不正确","zh-TW":"簽名 ** 不正確","zh-HK":"簽名 ** 不正確"}]}}
```

I double checked the URL with my code that successfully sends authenticated requests to tidebit, the problem might be in how the signature is obtained. 
I have attached a snippet of my python code that works in generating a signature that the API doesn't complain about. 

```

class Tidebit():
    # set keys and api url 
    def __init__(self, access_key, secret_key):
        self.access_key = access_key
        self.secret_key = (secret_key).encode('utf8')
        self.base_url = 'https://www.tidebit.com/'
    # get time signature 
    def get_tonce(self):
        current_milli_time = int(round(time.time()*1000))
        tonce = str(current_milli_time)
        return tonce
    # sign, had to change this around in order for the API not to complain about signatures 
    def sign(self,msg):
        signature = hmac.new(self.secret_key, msg=msg.encode('utf-8'), digestmod=hashlib.sha256).hexdigest()
        return signature

    # get balances + user details 
    def get_members(self):
            print('Get Members')
            members_url = '/api/v2/members/me.json'
            tonce = self.get_tonce()
            msg = 'GET|' + members_url + '|access_key=' + self.access_key + '&tonce=' + tonce
            signature = self.sign(msg)
            url = self.base_url + members_url + '?access_key=' + self.access_key + '&tonce=' + tonce +'&signature=' + signature
            print(url)
            response = request_get(url)
            return response
```

**Comment by kroitor** [comment]
@araa47 thx! I've uploaded another fix for it, please, update to 1.14.277 and let me know if it solves the issue for you. If not, we will be happy if you help us debugging it and finding the difference between your code, their github code and this implementation: https://github.com/ccxt/ccxt/blob/master/python/ccxt/tidebit.py#L357

Unfortunately, can't test it on my side right now as they won't allow me to generate the api keys until I'm verified with them. You help would be appreciated.

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by araa47** [comment]
@kroitor just tried out the latest release. Still having the same issue. Currently trying to work out the exact difference, will get back to you once I figure it out.

**Comment by kroitor** [comment]
@araa47 thank you! Will look forward to getting a followup from you!

**Comment by araa47** [comment]
@kroitor  The only difference I'm able to identify till now is the .encode in line 373 where the secret is being encoded. This seems to be the only difference between my code and the library.

In order to test this so I don't waste your time, in my understanding I would first clone the repository, then modify the tidebit.py file. What I am not sure is how I would go about installing this modified latest version to my pipenv (python environment) after modifying the tidebit.py.

**Comment by kroitor** [comment]
@araa47 you would:

1. `cd ccxt_cloned_repo_directory/python`
2. `pip uninstall ccxt`
3. `pip install -e .` in that same python folder to install it from that folder (don't forget to uninstall the local copy later after fixing it and switching back to the master pypi-version)

https://stackoverflow.com/questions/15031694/installing-python-packages-from-local-file-system-folder-to-virtualenv-with-pip

**Comment by araa47** [comment]
Hey found the fix, basically tidebit required '/api/' as part of the payload that was being used to create the signature and ccxt was missing this. Line 372 tidebit.py and line 372 on async/tidebit.py

Before :
```
payload = method + '|' +  request + '|' + query
```
Fix: 
```
payload = method + '|' + '/api/' + request + '|' + query
```

I have made the changes but not sure on how to commit these changes. I have created a new branch but I can't seem to push the branch.

**Comment by kroitor** [comment]
https://help.github.com/articles/pushing-to-a-remote/

```
git push origin YOUR_BRANCH_NAME
```

**Comment by araa47** [comment]
This is the issue I was referring to while trying to push a commit. 

```
MacBook-Pro-4:ccxt A$ git push origin TidebitFetchBalanceFix
remote: Permission to ccxt/ccxt.git denied to araa47.
fatal: unable to access 'https://github.com/ccxt/ccxt/': The requested URL returned error: 403
MacBook-Pro-4:ccxt A$ 
```

**Comment by kroitor** [comment]
@araa47 No worries, I've already added the proper fix. We should only push source version files as described in the CONTRIBUTING doc linked above. The fixed version 1.14.278 should arrive in 5-10 minutes.

For the future, the usual procedure for making changes to any github project is to fork it under your github account – this will create a copy of it in your dashboard, then clone your forked repo to your local folder, do the edit there, commit & push it to the origin (back to your forked repo in your account) and once this is done you can send the "pull request", so that your changes get added to the master repository.

**Comment by araa47** [comment]
@kroitor Thanks for the help. Will note this down for future updates and contributions to this repo. I have tested 1.14.278, fetch_balance() works perfectly now :)
