### ISSUE TITLE
SyntaxError on importing async in Python 3.7

### ISSUE THREAD

**Issue by wardbradt** [ccxt/ccxt#3282]
- OS: macOS High Sierra 10.13.5
- Programming Language version: Python 3.7.0
- CCXT version: 1.14.289
- Exchange: N/A
- Method: N/A

Previously, when using Python 3.6.3, the following code worked perfectly to import `async`:
```
import ccxt.async as ccxt
```
However, it does not work in Python 3.7 because `async` is now a reserved keyword. See [here](https://docs.python.org/3.7/whatsnew/3.7.html). (Do CTRL + F "async", it is the first result.)

This is the stack trace:
```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/wardbradt/MEGAsync/CS/tenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/wardbradt/MEGAsync/CS/tenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/wardbradt/MEGAsync/CS/tenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 216, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/wardbradt/MEGAsync/CS/tenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/wardbradt/MEGAsync/CS/peregrine_logging/management/commands/scan_opps.py", line 1
    import ccxt.async as ccxt
                    ^
SyntaxError: invalid syntax
```

**Comment by kroitor** [comment]
Fixed in #3281

**Comment by andrei15** [comment]
When it gets into the release?  In 1.15.7 its not renamed.

**Comment by kroitor** [comment]
@andrei15 hope to have time to merge it today or tomorrow.
