### ISSUE TITLE
(Python) GateIO unified fetchDepositAddress() - XRP

### ISSUE THREAD

**Issue by Jmalinza** [ccxt/ccxt#3286]
When trying to fetch my deposit address/generate new address for XRP, an index error is raised. Issue is exclusively for XRP.

My code:
```
import ccxt
import json

with open('config.json') as json_data_file:
    data = json.load(json_data_file)

gateio = ccxt.gateio({'apiKey': data["gateIO"]["apiKey"],'secret': data["gateIO"]["secretKey"]})
markets = gateio.loadMarkets() #avoid large verbose
gateio.verbose = True
res = gateio.fetchDepositAddress("XRP")
```
the output:
```
Request: POST https://data.gate.io/api2/1/private/depositAddress {'Key': '2BDB1BD9-33AC-479C-8AD8-917327CABE4C', 'Sign': 'cdf69c87720ad6dc2b8446a2a27d35befb28ac7babdde57da92bb7c9b571a4729bb7494e90e3cf8e6c47c9c1605cce021e500d3fa256ae05875c08c57a6fa56c', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} nonce=1530225887&currency=XRP

Response: POST https://data.gate.io/api2/1/private/depositAddress 200 {'Date': 'Thu, 28 Jun 2018 22:44:48 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty/1.13.6.1', 'X-Frame-Options': 'SAMEORIGIN', 'X-Powered-By': 'CF ()', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache, must-revalidate', 'Content-Encoding': 'gzip'} {"result":"true","addr":"rHcFoo6a9qT5NHiVn1THQRhsEGcxtYCV4d 242585636","message":"Sucess","code":0}
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    res = gateio.fetchDepositAddress("XRP")
  File "/Users/malinza/Environments/bot/lib/python3.6/site-packages/ccxt/gateio.py", line 477, in fetch_deposit_address
    return self.query_deposit_address('Deposit', code, params)
  File "/Users/malinza/Environments/bot/lib/python3.6/site-packages/ccxt/gateio.py", line 465, in query_deposit_address
    tag = parts[1]
IndexError: list index out of range
```

Easy fix (ccxt/python/ccxt/gateio.py, line 463)
old code:
```
parts = address.split('/', 2)
```
fixed:
```
parts = address.split()
```
- OS: High Sierra 10.13.5 (17F77)
- Programming Language version: Python 3.6.2
- CCXT version: 1.14.277 
- Exchange: gateio
- Method: fetchDepositAddress()

**Comment by Jmalinza** [comment]
would make the pull request myself, but honestly I have no clue how and dont have enough time to learn now
