### ISSUE TITLE
Illegal parameter when fetching OHLC at LBank

### ISSUE THREAD

**Issue by HornKild** [ccxt/ccxt#3294]
Hello,

I would like to report this error I have with LBank when fetching OHLC data : 

```
ccxt.lbank().fetch_ohlcv('ETH/BTC', '1d', limit=2500)
Traceback (most recent call last):

  File "<ipython-input-757-a37ccb4b4886>", line 1, in <module>
    ccxt.lbank().fetch_ohlcv('ETH/BTC', '1d', limit=2500)

  File "/home/xx
/anaconda3/lib/python3.6/site-packages/ccxt/lbank.py", line 253, in fetch_ohlcv
    response = self.publicGetKline(self.extend(request, params))

  File "/home/xx/anaconda3/lib/python3.6/site-packages/ccxt/lbank.py", line 449, in request
    raise ErrorClass(message)

ExchangeError: Illegal parameters
```
Same error occurs without the `limit` parameter. 
Is it something from my side a an error with LBank ?

Looks like the LBank API has a lot of problem.

Thanks

**Comment by kroitor** [comment]
Hi! Can you show your **verbose request/response** plz?

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Related: https://github.com/ccxt/ccxt/search?q=lbank+ohlcv&type=Issues

**Comment by HornKild** [comment]
Sure, here it is : 

```
lbank.fetch_ohlcv('ETH/BTC', '1d', limit=2500)

Request: GET https://api.lbank.info/v1/currencyPairs.do {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.lbank.info/v1/currencyPairs.do 200 {'Server': 'Tengine', 'Date': 'Fri, 29 Jun 2018 17:22:13 GMT', 'Content-Type': 'text/plain;charset=ISO-8859-1', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Encoding': 'gzip'} ["bfdt_eth","pch_usdt","dax_usdt","btc_usdt","eth_usdt","bch_usdt","neo_usdt","vet_usdt","qtum_usdt","zec_usdt","pch_btc","pnt_btc","dax_btc","eth_btc","bch_btc","ltc_btc","neo_btc","dash_btc","vet_btc","etc_btc","qtum_btc","btg_btc","zec_btc","sc_btc","bts_btc","bcd_btc","cmt_btc","abt_btc","cpx_btc","xwc_btc","sbtc_btc","fil6_btc","fil12_btc","fil36_btc","btf_btc","her_eth","luc_eth","ptt_eth","wicc_eth","tac_eth","qkc_eth","afc_eth","idhub_eth","sead_eth","ssc_eth","skm_eth","pch_eth","iic_eth","ply_eth","ext_eth","dax_eth","bch_eth","eos_eth","trx_eth","vet_eth","qtum_eth","zec_eth","bts_eth","btm_eth","mith_eth","nas_eth","man_eth","cmt_eth","dbc_eth","bto_eth","abt_eth","ddd_eth","cpx_eth","cs_eth","iht_eth","ink_eth","tky_eth","ocn_eth","dct_eth","yoyow_eth","zsc_eth","zpt_eth","eko_eth","mda_eth","pst_eth","xwc_eth","put_eth","tgc_eth","pnt_eth","aac_eth","fil6_eth","fil12_eth","fil36_eth","uip_eth","lch_eth","seer_eth","bsb_eth","cdc_eth","grams_eth","ddm_eth","eai_eth","inc_eth","ply_qtum","mith_qtum","ink_qtum","bot_qtum","qbt_qtum","put_qtum","ent_qtum","chat_qtum","aac_qtum","yoyow_bts","seer_bts","bnb_usdt","ht_usdt","sead_usdt"]

Request: GET https://api.lbank.info/v1/kline.do?symbol=eth_btc&type=day1&size=2500 {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.lbank.info/v1/kline.do?symbol=eth_btc&type=day1&size=2500 200 {'Server': 'Tengine', 'Date': 'Fri, 29 Jun 2018 17:22:13 GMT', 'Content-Type': 'text/plain;charset=ISO-8859-1', 'Content-Length': '37', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN'} {"result":"false","error_code":10003}
Traceback (most recent call last):

  File "<ipython-input-765-a9922c2cdb2c>", line 1, in <module>
    lbank.fetch_ohlcv('ETH/BTC', '1d', limit=2500)

  File "/home/xx/anaconda3/lib/python3.6/site-packages/ccxt/lbank.py", line 253, in fetch_ohlcv
    response = self.publicGetKline(self.extend(request, params))

  File "/home/xx/anaconda3/lib/python3.6/site-packages/ccxt/lbank.py", line 449, in request
    raise ErrorClass(message)

ExchangeError: Illegal parameters
```

**Comment by kroitor** [comment]
First of, you should update your version of CCXT.
Secondly, they will require a `since` argument, does the following work for you?

```
since = lbank.parse8601('2018-01-01T00:00:00Z')
lbank.fetch_ohlcv('ETH/BTC', '1d', since, limit=2500)
```

?

**Comment by HornKild** [comment]
I updated to the lateste version and it looks like now it download the data but for some reason `lb` remains empty. 

```
In [11]: lb = lbank.fetch_ohlcv('ETH/BTC', '1d', since, limit=2500)

Request: GET https://api.lbank.info/v1/kline.do?symbol=eth_btc&type=day1&size=2500&time=1514764800 {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.lbank.info/v1/kline.do?symbol=eth_btc&type=day1&size=2500&time=1514764800 200 {'Server': 'Tengine', 'Date': 'Fri, 29 Jun 2018 17:53:50 GMT', 'Content-Type': 'text/plain;charset=ISO-8859-1', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Frame-Options': 'SAMEORIGIN'} [[1514736000,0.05442407,0.05688305,0.05218843,0.05642938,522.40710000],[1514822400,0.05642938,0.06687141,0.05628500,0.06414800,279.59430000],[1514908800,0.06414800,0.06357935,0.05380226,0.05870250,764.35460000],[1514995200,0.05870250,0.06950000,0.05841379,0.06796387,625.35079999],[1515081600,0.06796387,0.06934050,0.05965244,0.06132000,790.14719999],[1515168000,0.06132000,0.06225143,0.05387392,0.06076234,992.94010000],[1515254400,0.06076234,0.06619975,0.05850490,0.06536583,419.26580000],[1515340800,0.06536583,0.07843457,0.05891700,0.07605108,426.31260000],[1515427200,0.07605108,0.08352007,0.06682880,0.08202386,685.75710000],[1515513600,0.08202386,0.10061269,0.08100949,0.09418778,662.53560000],[1515600000,0.09418778,0.09422043,0.08310884,0.08766020,415.74580000],[1515686400,0.08766020,0.09370385,0.08537284,0.09069871,520.71730000],[1515772800,0.09069871,0.09600000,0.09047129,0.09553214,461.72090000],[1515859200,0.09553214,0.10000000,0.09555555,0.09769870,668.20520000],[1515945600,0.09769870,0.10213501,0.09089433,0.09471533,572.60680000],[1516032000,0.09471533,0.09700000,0.08745872,0.09382183,759.92110000],[1516118400,0.09382183,0.09558099,0.08291943,0.08387291,514.05170000],[1516204800,0.08387291,0.09281166,0.08382957,0.09201004,484.74400000],[1516291200,0.09201004,0.09383542,0.09002507,0.09207271,501.83629999],[1516377600,0.09207271,0.09263157,0.08814425,0.09104353,419.12010000],[1516464000,0.09104353,0.09341848,0.09010000,0.09180878,508.73580000],[1516550400,0.09180878,0.09365864,0.09049431,0.09345989,423.27900000],[1516636800,0.09345989,0.09415843,0.09068440,0.09226068,406.20310000],[1516723200,0.09226068,0.09361440,0.09010000,0.09266825,440.72420000],[1516809600,0.09266825,0.09719440,0.09175653,0.09423008,410.19610000],[1516896000,0.09423008,0.09900703,0.09230200,0.09675207,436.82600000],[1516982400,0.09675207,0.09864817,0.09424360,0.09572408,444.28560000],[1517068800,0.09572408,0.10827076,0.09524438,0.10525121,405.05560000],[1517155200,0.10525121,0.10828786,0.10336296,0.10658069,387.28909999],[1517241600,0.10658069,0.10975919,0.10421343,0.10799644,232.52870000],[1517328000,0.10799644,0.11231303,0.10520666,0.11050821,418.23910000],[1517414400,0.11050821,0.12311212,0.10835000,0.11553485,450.36590000],[1517500800,0.11553485,0.12001607,0.09850000,0.10759862,421.62630000],[1517587200,0.10759862,0.10864585,0.10201365,0.10462141,397.50970000],[1517673600,0.10462141,0.10689394,0.10065983,0.10357910,403.66160000],[1517760000,0.10357910,0.10515699,0.09876543,0.09945166,400.39670000],[1517846400,0.09945166,0.10294026,0.09476100,0.10251432,395.34640000],[1517932800,0.10251432,0.10317826,0.09865139,0.10011302,402.91670000],[1518019200,0.10011302,0.10274236,0.09670398,0.09784336,441.70489999],[1518105600,0.09784336,0.10200000,0.09647170,0.10170387,401.27690000],[1518192000,0.10170387,0.10200000,0.09833669,0.10076138,386.19600000],[1518278400,0.10076138,0.10289860,0.09894846,0.10198237,377.17360000],[1518364800,0.10198237,0.10251805,0.09977699,0.10001856,248.86370000],[1518451200,0.10001856,0.10210972,0.09573900,0.09924603,263.39910000],[1518537600,0.09924603,0.10267620,0.09653976,0.09760151,389.40400000],[1518624000,0.09760151,0.10015998,0.09573900,0.09614598,393.56890000],[1518710400,0.09614598,0.09628071,0.09160403,0.09352378,422.00540000],[1518796800,0.09352378,0.09593679,0.08888946,0.08993615,401.41340000],[1518883200,0.08993615,0.09139241,0.08446786,0.08845406,440.91740000],[1518969600,0.08845406,0.08985069,0.08541158,0.08592745,378.35080000],[1519056000,0.08592745,0.08613553,0.08165970,0.08192651,415.21120000],[1519142400,0.08192651,0.08279087,0.07799280,0.07936719,399.62480000],[1519228800,0.07936719,0.08183668,0.07852387,0.08125386,424.58110000],[1519315200,0.08125386,0.08616098,0.08060323,0.08425462,405.09550000],[1519401600,0.08425462,0.08670146,0.08128920,0.08573032,412.94390000],[1519488000,0.08573032,0.08879101,0.08442121,0.08833785,377.73699999],[1519574400,0.08833785,0.09053781,0.08373310,0.08524142,433.91189999],[1519660800,0.08524142,0.08626009,0.08162372,0.08293952,413.67229999],[1519747200,0.08293952,0.08427936,0.08013946,0.08306006,413.36770000],[1519833600,0.08306006,0.08402474,0.08052101,0.08136353,413.81510000],[1519920000,0.08136353,0.08323997,0.07674689,0.07949387,778.16680000],[1520006400,0.07949387,0.08222721,0.07500002,0.07565664,1337.80190000],[1520092800,0.07565664,0.07886705,0.07251197,0.07700330,1323.47930000],[1520179200,0.07700330,0.07837931,0.07260959,0.07346535,1320.46310000],[1520265600,0.07346535,0.07865208,0.07208955,0.07555457,7097.44440000],[1520352000,0.07555457,0.07825144,0.07200001,0.07374220,12981.97290000],[1520438400,0.07386615,0.07853224,0.07305125,0.07652074,12631.28209999],[1520524800,0.07652074,0.07954862,0.07315778,0.07767764,12528.66579999],[1520611200,0.07767764,0.07977083,0.07439075,0.07843693,12845.53189999],[1520697600,0.07843693,0.07959875,0.07386609,0.07799948,12566.09140000],[1520784000,0.07799948,0.07831357,0.07321763,0.07585313,12711.10460000],[1520870400,0.07585313,0.07852368,0.07489086,0.07639573,12930.03320000],[1520956800,0.07639573,0.07768580,0.07423317,0.07544611,12702.86190000],[1521043200,0.07544611,0.07601151,0.07351873,0.07439866,11674.19290000],[1521129600,0.07439866,0.07536077,0.07171107,0.07303656,12692.71619999],[1521216000,0.07303656,0.07489270,0.07170367,0.07391434,12775.78440000],[1521302400,0.07391434,0.07435034,0.06206094,0.06266636,12858.01720000],[1521388800,0.06273813,0.07135201,0.06204161,0.06426658,12870.83700000],[1521475200,0.06426658,0.07386481,0.06204911,0.06303276,12619.63020000],[1521561600,0.06303276,0.06942268,0.06180657,0.06364840,12138.15210000],[1521648000,0.06364840,0.06451956,0.06117896,0.06183468,12969.69359999],[1521734400,0.06183468,0.06324526,0.06112144,0.06184356,9376.41379999],[1521820800,0.06184356,0.06927054,0.05469445,0.06021862,9894.97890000],[1521907200,0.06021862,0.06219688,0.05657261,0.06099297,13017.40880000],[1521993600,0.06099297,0.06305606,0.05445021,0.06030025,12809.37870000],[1522080000,0.05991752,0.06093566,0.05352420,0.05835342,12844.57680000],[1522166400,0.05835342,0.05924263,0.05328465,0.05670408,12865.62950000],[1522252800,0.05682881,0.05770940,0.05236124,0.05460138,12741.86080000],[1522339200,0.05466638,0.05771712,0.05250208,0.05604895,12728.67039999],[1522425600,0.05604895,0.05951930,0.05320042,0.05735305,12771.80269999],[1522512000,0.05735305,0.05767151,0.05267893,0.05606473,12792.56360000],[1522598400,0.05606473,0.05679509,0.05244548,0.05636732,11110.13220000],[1522684800,0.05636732,0.05673249,0.05225017,0.05467751,4787.97160000],[1522771200,0.05467751,0.05657995,0.05376265,0.05497797,17238.97490000],[1522857600,0.05482113,0.05655398,0.05468774,0.05585443,19946.68420000],[1522944000,0.05585443,0.05684073,0.05539222,0.05558828,24187.72500000],[1523030400,0.05558828,0.05653769,0.05524245,0.05553261,25120.59660000],[1523116800,0.05553261,0.05807587,0.05525106,0.05788395,25560.10100000],[1523203200,0.05788395,0.06050129,0.05642686,0.05916367,25315.66200000],[1523289600,0.05916367,0.06032423,0.05693636,0.05912583,25790.35850000],[1523376000,0.05912583,0.06208086,0.05872458,0.06099999,22171.06250000],[1523462400,0.06099999,0.06361873,0.05846400,0.06120339,19868.01990000],[1523548800,0.06120339,0.06540000,0.05758901,0.06420461,25852.26410000],[1523635200,0.06420461,0.06490617,0.06137957,0.06227017,25218.26780000],[1523721600,0.06211367,0.06498621,0.06182370,0.06350123,25059.16410000],[1523808000,0.06350123,0.06603395,0.06298518,0.06345129,25486.09439999],[1523894400,0.06345129,0.06520722,0.06275676,0.06384163,25549.73560000],[1523980800,0.06384163,0.06536795,0.06338011,0.06369930,25234.68960000],[1524067200,0.06369930,0.06685495,0.06331415,0.06591577,25019.78330000],[1524153600,0.06592058,0.07487248,0.06528184,0.06913775,25519.07390000],[1524240000,0.06913775,0.07132157,0.06650977,0.06885501,25584.78170000],[1524326400,0.06885501,0.07182657,0.06623363,0.07110842,25148.07079999],[1524412800,0.07093761,0.07368974,0.07042844,0.07279995,24447.99190000],[1524499200,0.07279995,0.07615965,0.07188234,0.07531069,26088.27360000],[1524585600,0.07531069,0.07562882,0.06590271,0.06967861,25017.99820000],[1524672000,0.06967861,0.07228335,0.06863980,0.07162319,25256.38719999],[1524758400,0.07162319,0.07422674,0.07067238,0.07314664,25506.12640000],[1524844800,0.07314664,0.07533936,0.06825350,0.07348892,25822.41460000],[1524931200,0.07348892,0.07516552,0.07144645,0.07367132,18710.15949999],[1525017600,0.07367132,0.07629232,0.07257339,0.07316832,9911.78240000],[1525104000,0.07316832,0.07480031,0.07043306,0.07307000,4715.68230000],[1525190400,0.07307000,0.07636754,0.07178394,0.07468908,1249.94710000],[1525276800,0.07468908,0.08130378,0.07400000,0.07916437,19704.19610000],[1525363200,0.07916437,0.08427399,0.07818887,0.08071763,25358.56730000],[1525449600,0.08071763,0.08557072,0.07982785,0.08302997,25698.39060000],[1525536000,0.08302997,0.08585083,0.08032624,0.08151671,24640.11360000],[1525622400,0.08151671,0.08326546,0.07598086,0.07840438,25445.54269999],[1525708800,0.07840438,0.08237580,0.07745000,0.08012802,24628.63750000],[1525795200,0.08034000,0.08205539,0.07921000,0.08118388,25770.99129999],[1525881600,0.08118388,0.08320000,0.08048000,0.08222664,25186.67549999],[1525968000,0.08222664,0.08318000,0.07819687,0.07973924,25235.67450000],[1526054400,0.07973924,0.08192511,0.07803000,0.07975893,12234.50689999],[1526140800,0.07975893,0.08403510,0.07907000,0.08402794,58.30160000],[1526227200,0.08402794,0.08495244,0.07955450,0.08408334,2274.18570000],[1526313600,0.08408334,0.08562558,0.08000000,0.08385039,19577.44310000],[1526400000,0.08392773,0.08601399,0.08251467,0.08432264,23634.20260000],[1526486400,0.08432264,0.08619121,0.08408000,0.08516421,25292.30019999],[1526572800,0.08516421,0.08584807,0.08257000,0.08385873,25083.68780000],[1526659200,0.08385873,0.08607310,0.08301000,0.08517081,25731.78030000],[1526745600,0.08517850,0.08693449,0.08421247,0.08568195,25018.35910000],[1526832000,0.08568195,0.08590705,0.08297000,0.08392552,25196.94790000],[1526918400,0.08392341,0.08640000,0.08250966,0.08287159,25551.87829999],[1527004800,0.08287159,0.08650000,0.07591953,0.07901319,25352.70629999],[1527091200,0.07901319,0.08641999,0.07479001,0.07794722,17065.76350000],[1527177600,0.07794722,0.08099871,0.07607300,0.08019807,19601.22679999],[1527264000,0.08019807,0.08091376,0.07618450,0.08020232,25494.34339999],[1527350400,0.08020232,0.08099509,0.07800013,0.07831010,25582.20919999],[1527436800,0.07831010,0.07869324,0.06670807,0.07403441,25373.60220000],[1527523200,0.07403441,0.07514075,0.07200002,0.07436838,20848.67820000],[1527609600,0.07436838,0.07865477,0.06592566,0.07531977,23142.11530000],[1527696000,0.07533517,0.07730776,0.07467287,0.07642662,24304.10160000],[1527782400,0.07642662,0.07823579,0.07518042,0.07753797,24902.51050000],[1527868800,0.07753797,0.07858094,0.07642919,0.07767594,24734.30690000],[1527955200,0.07767594,0.08229995,0.07681106,0.08065294,24591.68090000],[1528041600,0.08052441,0.08152624,0.07703001,0.07838712,25020.28710000],[1528128000,0.07838712,0.08038751,0.07778944,0.07955188,24544.65400000],[1528214400,0.07955188,0.08052000,0.07824133,0.07965803,37096.97450000],[1528300800,0.07965803,0.07991344,0.07896000,0.07937428,38450.28800000],[1528387200,0.07937428,0.08003000,0.07848361,0.07854000,18966.68430000],[1528473600,0.07854000,0.08003000,0.07849000,0.07899717,46281.78800000],[1528560000,0.07898346,0.07992599,0.07802000,0.07852734,45663.39130000],[1528646400,0.07852734,0.08003000,0.07558051,0.07712243,44037.54519999],[1528732800,0.07708147,0.08009697,0.07600994,0.07889503,47537.64900000],[1528819200,0.07889503,0.08052000,0.06587322,0.07339834,46486.86950000],[1528905600,0.07339834,0.07596000,0.06023698,0.07326500,41741.78300000],[1528992000,0.07326500,0.07909685,0.07301721,0.07703298,47001.90700000],[1529078400,0.07703298,0.07809997,0.07575188,0.07672238,48533.16350000],[1529164800,0.07680103,0.07806000,0.07641577,0.07709501,45624.56500000],[1529251200,0.07709501,0.07732966,0.07653300,0.07704645,31906.37700000],[1529337600,0.07704645,0.08051000,0.07654300,0.07961988,27019.64179999],[1529424000,0.07961988,0.08126985,0.07833000,0.07917000,20739.45540000],[1529510400,0.07917000,0.08105000,0.07851086,0.07899029,18456.23010000],[1529596800,0.07888901,0.07903500,0.07546855,0.07704066,26705.69330000],[1529683200,0.07704486,0.07732688,0.07575793,0.07665905,26878.83510000],[1529769600,0.07664978,0.07748471,0.07277737,0.07292653,20160.04759999],[1529856000,0.07292653,0.07566201,0.07265000,0.07400499,26430.80200000],[1529942400,0.07399871,0.07464589,0.06925415,0.07213261,26939.24470000],[1530028800,0.07213261,0.07352318,0.06930985,0.07072695,28157.70780000],[1530115200,0.07072695,0.07372257,0.06985879,0.07134341,27180.04780000],[1530201600,0.07134341,0.07363249,0.06750994,0.07021547,27387.12460000],[1530288000,0.07021547,0.07082611,0.06788179,0.06996781,2209.99170000]]

In [12]: lb
Out [12]: []
```

**Comment by HornKild** [comment]
When there is only `since` I have the same result (`lb` remains empty) and when only `limit` is provided it throws `ExchangeError: Illegal parameters`.

But aren't `limit` and `since` two exclusive options ?

**Comment by kroitor** [comment]
@HornKild looks like you did not update your ccxt, because anaconda has its own version of pip.

```
import ccxt
print(ccxt.__version__)
```

What's your current version number?

**Comment by kroitor** [comment]
Anaconda is known for this odd behaviour... 

- https://github.com/ccxt/ccxt/issues/2824
- https://github.com/ccxt/ccxt/issues/2747 (your own post)
- https://github.com/ccxt/ccxt/issues/2459

```Python
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> lbank = ccxt.lbank({'enableRateLimit': True})
>>> since = lbank.parse8601('2018-01-01T00:00:00Z')
>>> lb = lbank.fetch_ohlcv('ETH/BTC', '1d', since, 2500)
>>> len(lb)
180
>>> ccxt.__version__
'1.14.298'
>>>
```

**Comment by kroitor** [comment]
@HornKild does the snippet from my previous post above help?

**Comment by HornKild** [comment]
You were right and my package wasn't updated. 

```
$ conda update ccxt

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /home/bragar/anaconda3
  package name: ccxt

```
So I used : 

`$ sudo pip install ccxt --upgrade`

But it don't updage my package.

**Comment by HornKild** [comment]
Last time I updated `ccxt` without problem but today I'm facing an issue. If I try to install `ccxt` with `conda` it can't find the package from the current channels : 

```
$ conda install ccxt
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ccxt

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by HornKild** [comment]
@kroitor my current version is 1.14.88 but I'm unable to update with anaconda package manager.

**Comment by kroitor** [comment]
@HornKild does this help?

- https://stackoverflow.com/questions/48493505/packagesnotfounderror-the-following-packages-are-not-available-from-current-cha
- https://www.google.ru/search?q=conda+The+following+packages+are+not+available+from+current+channels

**Comment by kroitor** [comment]
@HornKild basically, from the above it follows that this isn't an issue with ccxt, but more like an issue with your local conda configuration. Moreover, google and stackoverflow both give quite a lot of search results, this indicates that the problem you're having is common to a lot of other users of conda, and you will most likely find your answer there. This is often resolved by reinstalling / reconfiguring the environment properly (in some specific order that conda will be satisfied with, go figure). I'd close this for now if you don't mind. Let us know if nothing of the above, neither google nor stackoverflow helps. You might want to report this to the anaconda repository issues.

**Comment by HornKild** [comment]
@kroitor thanks, my mistake was to use `sudo` to run `pip install ccxt --upgrade` because it updated the `ccxt` package for Python 2.7 and my anaconda point to Python 3.6. So with `$ pip install ccxt --upgrade` it works just fine :-)
