### ISSUE TITLE
binance 'param error' when fetching deposit address

### ISSUE THREAD

**Issue by benediamond** [ccxt/ccxt#3322]
- OS: Mac OS
- Programming Language version: Python 3.6.3
- CCXT version: '1.14.261'
- Exchange: binance
- Method: fetch_deposit_address

There is an _intermittent_ error on binance:
```python
>>> binance = ccxt.binance({'apiKey': xxxxx, 'secret': xxxx})
>>> binance.fetch_deposit_address("ETH")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/binance.py", line 761, in fetch_deposit_address
    }, params))
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/binance.py", line 892, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 385, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/binance.py", line 889, in handle_errors
    raise ExchangeError(self.id + ': success value False: ' + body)
ccxt.base.errors.ExchangeError: binance: success value False: {"msg":"param_error","success":false}
```
I noticed that in the [api docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md), there is a mandatory timestamp parameter. and yet we also have:
```python
>>> binance.wapiGetDepositAddress(binance.extend({'asset': "ETH", 'timestamp': binance.nonce()}, {}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/binance.py", line 892, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/base/exchange.py", line 385, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "/Users/benjamindiamond/anaconda/envs/arb/lib/python3.6/site-packages/ccxt/binance.py", line 889, in handle_errors
    raise ExchangeError(self.id + ': success value False: ' + body)
ccxt.base.errors.ExchangeError: binance: success value False: {"msg":"param_error","success":false}
```
This might be hard to reproduce because it goes on and off. maybe we should contact binance. I know they've been having some issues recently.

Feel free to close if this stops or you can't reproduce it.

**Comment by JSRossiter** [comment]
I've also been having this issue since the downtime yesterday, I haven't had a chance to look into it further yet.

**Comment by kroitor** [comment]
@benediamond could this be a nonce conflict? I mean, which particular timestamp is being sent in the request before the error compared to the request that triggers the error? Your verbose output would be helpful.

**Comment by J85Y** [comment]
Does Exchange generate new receiving address for each user with API ? like if we use any exchange api do they provide multiple addresses to user can send funds direct to that exchange and start trading
