### ISSUE TITLE
Coinfalcon fetchFreeBalance()

### ISSUE THREAD

**Issue by markhorner123** [ccxt/ccxt#3346]
Hey

Firstly to say thanks for your hard work - this is an awesome project you have. I've started looking at using CoinFalcon and come across an issue when trying to call the fetchFreeBalance method within Python;
- OS: W10
- Programming Language version: Python 3.6
- CCXT version: ccxt==1.15.2
- Exchange: Coin Falcon
- Method: fetchFreeBalance()

Other methods such as fetch trades etc don't seem to run into the same issue so I am hoping you'll be able to identify the cause without too much difficulty!

```Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 1081, in fetch_free_balance
    return self.fetch_partial_balance('free', params)
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 1077, in fetch_partial_balance
    balance = self.fetch_balance(params)
  File "Back_env\lib\site-packages\ccxt\coinfalcon.py", line 194, in fetch_balance
    response = self.privateGetUserAccounts(params)
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 308, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 304, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "Back_env\lib\site-packages\ccxt\coinfalcon.py", line 305, in sign
    payload = '|'.join([seconds, method, requestPath])
TypeError: sequence item 0: expected str instance, int found
```

When I tried to fix this issue itself by changing the line to join(map(str, [seconds, method, requestPath])) it then hit me with a further error relating to the header;

```Traceback (most recent call last):
  File "Back_env\lib\site-packages\requests\utils.py", line 940, in check_header_validity
    if not pat.match(value):
TypeError: expected string or bytes-like object
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 359, in fetch
    proxies=self.proxies
  File "Back_env\lib\site-packages\requests\sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "Back_env\lib\site-packages\requests\sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "Back_env\lib\site-packages\requests\models.py", line 310, in prepare
    self.prepare_headers(headers)
  File "Back_env\lib\site-packages\requests\models.py", line 444, in prepare_headers
    check_header_validity(header)
  File "Back_env\lib\site-packages\requests\utils.py", line 944, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
requests.exceptions.InvalidHeader: Value for header {CF-API-TIMESTAMP: 1531143418} must be of type str or bytes, not <class 'int'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 1081, in fetch_free_balance
    return self.fetch_partial_balance('free', params)
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 1077, in fetch_partial_balance
    balance = self.fetch_balance(params)
  File "Back_env\lib\site-packages\ccxt\coinfalcon.py", line 194, in fetch_balance
    response = self.privateGetUserAccounts(params)
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 308, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 383, in fetch
    self.raise_error(ExchangeError, url, method, e, self.last_http_response)
  File "Back_env\lib\site-packages\ccxt\base\exchange.py", line 290, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: coinfalcon https://coinfalcon.com/api/v1/user/accounts? GET Value for header {CF-API-TIMESTAMP: 1531143418} must be of type str or bytes, not <class 'int'> {"data":[{"name":"IOT-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.40200037","last_price":"0.0001912","change_in_24h":"24.54","size_precision":8,"price_precision":8},{"name":"ETH-BTC","precision":5,"min_volume":"0.00000001","min_price":"0.00001","volume":"0.21546","last_price":"0.06911","change_in_24h":"-2.66","size_precision":8,"price_precision":5}..... rest of markets]}```

**Comment by markhorner123** [comment]
Update - the same issue gets raised when trying to place orders with CCXT too!
