### ISSUE TITLE
fetch_open_orders() (Bitstamp) reuses nonce after fetch_balance()

### ISSUE THREAD

**Issue by simplyhugo** [ccxt/ccxt#3354]
- OS: MacOS 10.13.3
- Programming Language version: Python 3.6.3
- CCXT version: 1.15.31
- Exchange: Bitstamp
- Method: fetch_open_orders()

If bitstamp.fetch_open_orders() is called after fetch_balance() it will frequently (although not always) reuse its nonce, which will result in the following error:
```ccxt.base.errors.ExchangeError: bitstamp {"status": "error", "reason": "Invalid nonce", "code": "API0004"}```
I have not been able to reproduce the error if fetch_open_orders() was executed after public methods, but I have not tried it with other private ones.

In order to reproduce, run the following code several times:
```
import ccxt

exchange = ccxt.bitstamp()
exchange.verbose = True
exchange.apiKey = 'xxxx'
exchange.secret = 'xxxx'
exchange.uid = 'xxxx'

exchange.fetch_balance()
exchange.fetch_open_orders()
```

May be related to: https://github.com/ccxt/ccxt/issues/1902
Full console output in a comment below.

**Comment by simplyhugo** [comment]
```Request: GET https://www.bitstamp.net/api/v2/trading-pairs-info/ {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.bitstamp.net/api/v2/trading-pairs-info/ 200 {'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'Access-Control-Allow-Methods': 'POST, GET', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'max-age=0', 'Content-Language': 'en', 'Content-Type': 'application/json', 'Date': 'Tue, 10 Jul 2018 11:56:19 GMT', 'Expires': 'Tue, 10 Jul 2018 11:56:19 GMT', 'Last-Modified': 'Tue, 10 Jul 2018 11:56:19 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Vary': 'Authorization,Accept-Language', 'X-Frame-Options':'SAMEORIGIN', 'transfer-encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'visid_incap_99025=h+jcezqKQJWuaSbTox3whOOeRFsAAAAAQUIPAAAAAADt490HG4iy0t+u+qINMs9s; expires=Wed, 10 Jul 2019 11:26:19 GMT; path=/; Domain=.bitstamp.net, nlbi_99025=6BQUPkEZsVf2lzq98F1n9AAAAACztM8nT/q+MHDFCVtr5JvS; path=/; Domain=.bitstamp.net, incap_ses_533_99025=4Dp/a90hwkjlcPOuYpllB+OeRFsAAAAAfXwiLWoe/yCtDmtwcbvatw==; path=/; Domain=.bitstamp.net, ___utmvmyaumyLc=jGXnpglyQAQ; path=/; Max-Age=900, ___utmvayaumyLc=kyb\x01zAKf; path=/; Max-Age=900, ___utmvbyaumyLc=yZn\r\n    XtUOvalI: AtW; path=/; Max-Age=900', 'X-Iinfo': '7-8805650-8793878 PNNN RT(1531223778597 1125) q(0 0 0 -1) r(0 0) U2', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip'} [{"base_decimals": 8, "minimum_order": "5.0 USD", "name": "LTC/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ltcusd", "description": "Litecoin / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "ETH/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ethusd", "description": "Ether / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "XRP/EUR", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "xrpeur", "description": "XRP / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "BCH/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "bchusd", "description": "Bitcoin Cash / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "BCH/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "bcheur", "description": "Bitcoin Cash / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "BTC/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "btceur", "description": "Bitcoin / Euro"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "XRP/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "xrpbtc", "description": "XRP / Bitcoin"}, {"base_decimals": 5, "minimum_order": "5.0 USD", "name": "EUR/USD", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "eurusd", "description": "Euro / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "BCH/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "bchbtc", "description": "Bitcoin Cash / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "LTC/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ltceur", "description": "Litecoin / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "BTC/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "btcusd", "description": "Bitcoin / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "LTC/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "ltcbtc", "description": "Litecoin / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "XRP/USD", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "xrpusd", "description": "XRP / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "ETH/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "ethbtc", "description": "Ether / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "ETH/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "etheur", "description": "Ether / Euro"}]

Request: POST https://www.bitstamp.net/api/v2/balance/ {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} key=4WuoIpt0NgBGAuqbrjovaXWam5uh9raE&signature=A41865E44A928BD0BBF5D59D496A0F96332B513B2DDD4AF8E5A534458EB70D31&nonce=1531223780

Response: POST https://www.bitstamp.net/api/v2/balance/ 200 {'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'Access-Control-Allow-Methods': 'POST, GET', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'max-age=0', 'Content-Language': 'en', 'Content-Type': 'application/json', 'Date': 'Tue, 10 Jul 2018 11:56:20 GMT', 'Expires': 'Tue, 10 Jul 2018 11:56:20 GMT', 'Last-Modified': 'Tue, 10 Jul 2018 11:56:20 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Vary': 'Authorization,Accept-Language', 'X-Frame-Options': 'SAMEORIGIN', 'transfer-encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'visid_incap_99025=MQenbqVNR9yiaVxtJsJ8K+SeRFsAAAAAQUIPAAAAAAAKjCNdAJcBl0TVLbKbQU3p; expires=Wed, 10 Jul 2019 11:26:19 GMT; path=/; Domain=.bitstamp.net, incap_ses_533_99025=f6FdS+6STlsZcvOuYpllB+SeRFsAAAAAEOJaJ+1PGcmNsTLRtgP6iQ==; path=/; Domain=.bitstamp.net, ___utmvmyaumyLc=RqTTfVIZrOs; path=/; Max-Age=900, ___utmvayaumyLc=jTC\x01biAp; path=/; Max-Age=900, ___utmvbyaumyLc=SZg\r\n    XhdObalw: ztV; path=/; Max-Age=900', 'X-Iinfo': '7-8805650-8805983 NNNN CT(1 2 0) RT(1531223778597 1642) q(0 0 0 -1) r(0 0) U6', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip'} {"bch_available": "0.00000000", "bch_balance": "0.00000000", "bch_reserved": "0.00000000", "bchbtc_fee": "0.25", "bcheur_fee": "0.25", "bchusd_fee": "0.25", "btc_available": "0.00250000", "btc_balance": "0.00250000", "btc_reserved": "0.00000000", "btceur_fee": "0.25", "btcusd_fee": "0.25", "eth_available": "0.00000000", "eth_balance": "0.00000000", "eth_reserved": "0.00000000", "ethbtc_fee": "0.25", "etheur_fee": "0.25", "ethusd_fee": "0.25", "eur_available": "0.00", "eur_balance": "0.00", "eur_reserved": "0.00", "eurusd_fee": "0.25", "ltc_available": "0.00000000", "ltc_balance": "0.00000000", "ltc_reserved": "0.00000000", "ltcbtc_fee": "0.25", "ltceur_fee": "0.25", "ltcusd_fee": "0.25", "usd_available": "0.00", "usd_balance": "0.00", "usd_reserved": "0.00", "xrp_available": "0.00000000", "xrp_balance": "0.00000000", "xrp_reserved": "0.00000000", "xrpbtc_fee": "0.25", "xrpeur_fee": "0.25", "xrpusd_fee": "0.25"}

Request: POST https://www.bitstamp.net/api/v2/open_orders/all/ {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} key=4WuoIpt0NgBGAuqbrjovaXWam5uh9raE&signature=A41865E44A928BD0BBF5D59D496A0F96332B513B2DDD4AF8E5A534458EB70D31&nonce=1531223780

Response: POST https://www.bitstamp.net/api/v2/open_orders/all/ 403 {'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'Access-Control-Allow-Methods': 'POST, GET', 'Access-Control-Allow-Origin': '*', 'Content-Language': 'en', 'Content-Type': 'application/json', 'Date': 'Tue, 10 Jul 2018 11:56:21 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Vary': 'Authorization,Accept-Language', 'X-Frame-Options': 'SAMEORIGIN', 'transfer-encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'visid_incap_99025=+vTeDPXxTWaCipK7692k8uSeRFsAAAAAQUIPAAAAAABww7dB0vbevXdMTd86hfq8; expires=Wed, 10 Jul 2019 11:26:19 GMT; path=/; Domain=.bitstamp.net, incap_ses_533_99025=8Qr4fYNf/0USc/OuYpllB+SeRFsAAAAAis7cX7bu3842YEAxT07Yxg==; path=/; Domain=.bitstamp.net, ___utmvmyaumyLc=jRyHQzxfmlg; path=/; Max-Age=900, ___utmvayaumyLc=uSF\x01aJVO; path=/; Max-Age=900, ___utmvbyaumyLc=wZq\r\n    XdJOMalQ: ItL; path=/; Max-Age=900', 'X-Iinfo': '7-8805650-8805983 SNNN RT(1531223778597 2261) q(0 0 0 -1) r(0 0) U6', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip'} {"status": "error", "reason": "Invalid nonce", "code": "API0004"}
Traceback (most recent call last):
  File "/Users/Hugo/.pyenv/versions/mercury-3-6-3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 366, in fetch
    response.raise_for_status()
  File "/Users/Hugo/.pyenv/versions/mercury-3-6-3/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Authentication Failed for url: https://www.bitstamp.net/api/v2/open_orders/all/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ccxtTest.py", line 14, in <module>
    exchange.fetch_open_orders()
  File "/Users/Hugo/.pyenv/versions/mercury-3-6-3/lib/python3.6/site-packages/ccxt/bitstamp.py", line 520, in fetch_open_orders
    orders = self.privatePostOpenOrdersAll()
  File "/Users/Hugo/.pyenv/versions/mercury-3-6-3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 308, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Users/Hugo/.pyenv/versions/mercury-3-6-3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/Hugo/.pyenv/versions/mercury-3-6-3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 378, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "/Users/Hugo/.pyenv/versions/mercury-3-6-3/lib/python3.6/site-packages/ccxt/bitstamp.py", line 623, in handle_errors
    raise ExchangeError(self.id + ' ' + body)
ccxt.base.errors.ExchangeError: bitstamp {"status": "error", "reason": "Invalid nonce", "code": "API0004"}```

**Comment by kroitor** [comment]
@simplyhugo are you using any rate-limiting? Asking this because you're required to enable either the built-in rate limiter or to implement your own to avoid nonce conflicts. 

Documented in the Manual: 
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#authentication

Let us know if adding `ccxt.bitstamp ({'enableRateLimit': True}) does not solve your issue or does not help.

**Comment by simplyhugo** [comment]
That did solve my issue, thank you!
