### ISSUE TITLE
如何创建实例调用实例没有思路 求解答

### ISSUE THREAD

**Issue by Zyn0423** [ccxt/ccxt#3447]
import ccxt

bitfinex = ccxt.bitz ({
    'apiKey': '4FlEDtxDl35gdEiobnfZ72vJeZteE4Bb7JdvqzjIjHq',
    'secret': 'D4DXM8DZdHuAq9YptUsb42aWT1XBnGlIJgLi8a7tzFH',
})

print(bitfinex.fetch_balance())

**Comment by kroitor** [comment]
`bitfinex = ccxt.bitz ({` ?

Let us know if this does not help: 
- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
Just create a new keypair, your old keys are screwed by some other software:
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#invalidnonce

```
>>> b = ccxt.bitfinex({'apiKey': '4FlEDtxDl35gdEiobnfZ72vJeZteE4Bb7JdvqzjIjHq', 'secret': 'D4DXM8DZdHuAq9YptUsb42aWT1XBnGlIJgLi8a7tzFH'})
>>> b.fetch_balance()
Traceback (most recent call last):
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 373, in fetch
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitfinex.com/v1/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/igorkroitor/ccxt/python/ccxt/bitfinex.py", line 476, in fetch_balance
    balances = self.privatePostBalances()
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 315, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 312, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 385, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "/Users/igorkroitor/ccxt/python/ccxt/bitfinex.py", line 868, in handle_errors
    raise exact[message](feedback)
ccxt.base.errors.InvalidNonce: bitfinex {"message":"Nonce is too small."}
>>>

```

You should create a new keypair and try with it and make sure you don't confuse `bitz` with `bitfinex`.

**Comment by Zyn0423** [comment]
thank you
