### ISSUE TITLE
set proxy can't work

### ISSUE THREAD

**Issue by zhoujinhai** [ccxt/ccxt#3521]
hello, I am follow your [tips](https://github.com/ccxt/ccxt/blob/master/examples/py/proxy-asyncio-aiohttp-python-3.py) to set proxy , but it can't work! 

my  code:
![image](https://user-images.githubusercontent.com/20365125/43389493-71b5f3de-941e-11e8-8910-858717078d8a.png)

show this error after runed.
```
{'http': 'http://103.110.88.67:8080', 'https': 'https://103.110.88.67:8080'}
Traceback (most recent call last):
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\urllib3\connection.py", line 294, in connect
    self._tunnel()
  File "C:\Users\SXY004\Anaconda3\lib\http\client.py", line 914, in _tunnel
    (version, code, message) = response._read_status()
  File "C:\Users\SXY004\Anaconda3\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\SXY004\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /v2/spot/markets/products (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 378, in fetch
    proxies=self.proxies
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\requests\adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /v2/spot/markets/products (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/python3/ProxyPool-master/test.py", line 35, in <module>
    main()
  File "E:/python3/ProxyPool-master/test.py", line 31, in main
    symbols = okex.load_markets().keys()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 978, in load_markets
    markets = self.fetch_markets()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\okex.py", line 60, in fetch_markets
    markets = super(okex, self).fetch_markets()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\okcoinusd.py", line 186, in fetch_markets
    response = self.webGetSpotMarketsProducts()
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 327, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 324, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 402, in fetch
    self.raise_error(ExchangeError, url, method, e)
  File "C:\Users\SXY004\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 309, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: okex https://www.okex.com/v2/spot/markets/products GET HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /v2/spot/markets/products (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

Process finished with exit code 1
```

**Comment by kroitor** [comment]
This has something to do with your proxy (a closed port or some other issue with it). Not related to CCXT, apparently:

> ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

https://docs.microsoft.com/en-us/windows/desktop/winsock/windows-sockets-error-codes-2

```
WSAECONNRESET 10054 | Connection reset by peer.An existing connection was forcibly closed by the remote host. This normally results if the peer application on the remote host is suddenly stopped, the host is rebooted, the host or remote network interface is disabled, or the remote host uses a hard close (see [setsockopt](/windows/desktop/api/winsock/nf-winsock-setsockopt) for more information on the SO_LINGER option on the remote socket). This error may also result if a connection was broken due to keep-alive activity detecting a failure while one or more operations are in progress. Operations that were in progress fail with WSAENETRESET. Subsequent operations fail with WSAECONNRESET.
```

See the config for your proxy server, a proxy usually doesn't listen for both HTTP and HTTPS on the same port. You should use https most likely. Hope this helps.
