### ISSUE TITLE
exx.py fetch_balance response  HTTP Error 403

### ISSUE THREAD

**Issue by xycfree** [ccxt/ccxt#3613]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: win10
- Programming Language version:
- CCXT version: 
- Exchange: exx.py
- Method: get

Traceback (most recent call last):
  File "D:\tools\python36\venv1\lib\site-packages\ccxt\base\exchange.py", line 366, in fetch
    response.raise_for_status()
  File "D:\tools\python36\venv1\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://trade.exx.com/api/getBalance?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/gits/coinplatform/app/coins/exx.py", line 399, in <module>
    res = exx.fetch_balance()
  File "D:/gits/coinplatform/app/coins/exx.py", line 244, in fetch_balance
    balances = self.privateGetGetBalance(params)
  File "D:\tools\python36\venv1\lib\site-packages\ccxt\base\exchange.py", line 308, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "D:\tools\python36\venv1\lib\site-packages\ccxt\base\exchange.py", line 305, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\tools\python36\venv1\lib\site-packages\ccxt\base\exchange.py", line 379, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "D:\tools\python36\venv1\lib\site-packages\ccxt\base\exchange.py", line 408, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "D:\tools\python36\venv1\lib\site-packages\ccxt\base\exchange.py", line 290, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: exx https://trade.exx.com/api/getBalance?accesskey=

 GET 403 Client Error: Forbidden for url: https://trade.exx.com/api/getBalance?accesskey=

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>HTTP Error 403</title>
<style>

</style>
<script>
var error_403 = '';
if(error_403 == '') {
	error_403 = 'Request denied';
}
</script>
</head>
<body>

<h1>HTTP Error 403</h1>
<span class="r-tip01"><script>document.write(error_403);</script></span>

<hr>
<p> 119.57.115.187/cb634c7 [80001] </p>
<p> 2018-08-10 11:27:26 </p>
</body>
</html>

**Comment by kroitor** [comment]
@xycfree can you please post your code to reproduce the issue and your verbose response and request?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue 
- https://github.com/ccxt/ccxt/wiki/FAQ

Does any public call work?
