### ISSUE TITLE
Error: dlopen failed.. Scrypt.node has bad ELF Magic [React-Native][Node.js][CCXT]

### ISSUE THREAD

**Issue by abrarum** [ccxt/ccxt#3734]
- OS: Windows 10
- Programming Language version: Javascript (React Native)
- CCXT version: Latest to date
- Exchange: -
- Method: importing ccxt library

I'm integrating CCXT library in my React Native app. I've also setup the Node.js environment via "Nodejs-mobile-react-native". Now, upon importing ccxt library, my app crashes without warning. Upon looking at adb logcat, I found this hidden error:

`08-25 13:33:47.612 6966-7264/com.cryptoapp E/NODEJS-MOBILE: module.js:653
      return process.dlopen(module, path._makeLong(filename));
    Error: dlopen failed: "/data/data/com.cryptoapp/files/nodejs-project/node_modules/scrypt/build/Release/scrypt.node" has bad ELF magic
        at Object.Module._extensions..node (module.js:653:18)
        at Module.load (module.js:545:32)
        at tryModuleLoad (module.js:508:12)
        at Function.Module._load (module.js:500:3)
        at Module.require (module.js:568:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/data/data/com.cryptoapp/files/nodejs-project/node_modules/scrypt/index.js:3:20)
        at Module._compile (module.js:624:30)
        at Object.Module._extensions..js (module.js:635:10)
        at Module.load (module.js:545:32)
`

It only happens when I try to import cxxt library. The error is relevant to the non-coherence of library with the device architecture. My relevant devices are Windows 10 and Android 7.1.2 N2G47H.

**Comment by kroitor** [comment]
Looks like you've built the CCXT library for the host system, and trying to link it with the android, therefore it fails. This is a common issue with wrong compilation settings, however, it is outside of the scope of the library. 

A quick googling of the subject yields quite a lot of similar results, that indicates that this isn't the issue with the library itself, it is more an issue with your project compilation setup.

Let us know if this does not help: https://www.google.com/search?q=Error%3A+dlopen+failed+has+bad+ELF+magic
