### ISSUE TITLE
Deribit - fetchOrder does not work properly

### ISSUE THREAD

**Issue by icehacker33** [ccxt/ccxt#3782]
the fetchOrder method does not work properly in Deribit.

I have tried calling the function with and without the market parameter

**Example 1**
`deribit.fetchOrder("7135970079")`

**Example 2**
`deribit.fetchOrder("7135970079","BTC-PERPETUAL")`

**Error:**
```
TypeError: Cannot read property 'instrument' of undefined
    at deribit.parseOrder (/home/red/.node-red/node_modules/ccxt/js/deribit.js:313:28)
    at deribit.fetchOrder (/home/red/.node-red/node_modules/ccxt/js/deribit.js:330:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

OS: Linux
Programming Language version: JavaScript
CCXT version: 1.17.221
Exchange: Deribit
Method: createOrder

**Comment by icehacker33** [comment]
@kroitor I get the following verbose error. 

I can see the order in my dashboard and also using Deribit´s API web client, but not with CCXT as I´m getting this error.

```
fetch:
 deribit GET https://www.deribit.com/api/v1/private/orderstate
Request:
 { 'Content-Type': 'application/x-www-form-urlencoded',
  'x-deribit-sig': '4JgsEWp3gajMW.1535877098535.+73/+wCAgKAhPCpCNm/bedUAKoKK+brhRsnEfF18L8c=' }
 orderId=7136979305

handleRestResponse:
 deribit GET https://www.deribit.com/api/v1/private/orderstate 200 OK
Response:
 { Server: 'nginx/1.15.2',
  Date: 'Sun, 02 Sep 2018 08:31:38 GMT',
  'Content-Type': 'application/json',
  'Content-Length': '138',
  Connection: 'close',
  'Strict-Transport-Security': 'max-age=15768000',
  'X-Frame-Options': 'SAMEORIGIN' }
 {"usOut":1535877098645376,"usIn":1535877098643364,"usDiff":2012,"testnet":false,"success":false,"message":"order_not_found","error":10004}

TypeError: Cannot read property 'instrument' of undefined
    at deribit.parseOrder (/home/red/.node-red/node_modules/ccxt/js/deribit.js:313:28)
    at deribit.fetchOrder (/home/red/.node-red/node_modules/ccxt/js/deribit.js:330:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by kroitor** [comment]
@icehacker33 ok, will look into it further and will get back to you on this asap.

**Comment by icehacker33** [comment]
@kroitor many thanks, much appreciated.

**Comment by mkolbusz** [comment]
@kroitor The same here. Is it fixed?

**Comment by kroitor** [comment]
@mkolbusz what's your CCXT version?

**Comment by fonzmeister** [comment]
I have a similar problem using the latest version of ccxt. Note that I am using the test enviroment api

deribit.fetchOrder(id) results in output:
```
Traceback (most recent call last):

  File "<ipython-input-121-a6f51332e46c>", line 1, in <module>
    deribit.fetchOrder('2099223846')

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\deribit.py", line 310, in fetch_order
    return self.parse_order(response['result'])

KeyError: 'result'
```

verbose output:
```
Request: GET https://test.deribit.com/api/v1/private/orderstate {'x-deribit-sig': 'HwVuaBHjPDva.1548421641371.ZMYEDmkyxGTdgeygdB8zB35mU57cfdtp2AYaGuFiIC8=', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://test.deribit.com/api/v1/private/orderstate 200 {'Server': 'nginx/1.10.3', 'Date': 'Fri, 25 Jan 2019 13:07:21 GMT', 'Content-Type': 'application/json', 'Content-Length': '136', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=15768000', 'X-Frame-Options': 'SAMEORIGIN'} {"usOut":1548421641413870,"usIn":1548421641413304,"usDiff":566,"testnet":true,"success":false,"message":"order_not_found","error":10004}
```

**Comment by kroitor** [comment]
> File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\deribit.py", line 310, in fetch_order
> return self.parse_order(response['result'])

Looks like your version is not the latest? What's the exact version number?

**Comment by fonzmeister** [comment]
@kroitor sorry you're correct. Updated my wrong virtual env. Sorry about that.

This is the output I have with the updated version
```
ccxt.__version__
'1.18.152'
```

deribit.fetchMyTrades('BTC-PERPETUAL')
``` 
d.fetchMyTrades('BTC-PERPETUAL')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\deribit.py", line 429, in fetch_my_trades
    response = self.privateGetTradehistory(self.extend(request, params))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 373, in inner
    return entry(_self, **inner_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 402, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 398, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 501, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\deribit.py", line 469, in handle_errors
    raise exceptions[error](feedback)
ccxt.base.errors.ExchangeError: deribit {"usOut":1548500284588398,"usIn":1548500284588391,"usDiff":7,"testnet":true,"success":false,"message":"invalid_or_unsupported_instrument","error":10020}
```

verbose output:
```
Request: GET https://test.deribit.com/api/v1/private/tradehistory {'x-deribit-sig': 'HwVuaBHjPDva.1548500311691.Zh+smWKWutpHnXCxA4nE+PvGz+12DOqc5RJ5Z6SBm9A=', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://test.deribit.com/api/v1/private/tradehistory 200 {'Server': 'nginx/1.10.3', 'Date': 'Sat, 26 Jan 2019 10:58:31 GMT', 'Content-Type': 'application/json', 'Content-Length': '152', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=15768000', 'X-Frame-Options': 'SAMEORIGIN'} {"usOut":1548500311725755,"usIn":1548500311725747,"usDiff":8,"testnet":true,"success":false,"message":"invalid_or_unsupported_instrument","error":10020}
```

deribit.fetchOrder(id) & deribit.fetchOrder(id, 'BTC-PERPETUAL') (have same output)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\deribit.py", line 367, in fetch_order
    response = self.privateGetOrderstate({'orderId': id})
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 373, in inner
    return entry(_self, **inner_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 402, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 398, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 501, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\deribit.py", line 469, in handle_errors
    raise exceptions[error](feedback)
ccxt.base.errors.OrderNotFound: deribit {"usOut":1548500423108195,"usIn":1548500423107696,"usDiff":499,"testnet":true,"success":false,"message":"order_not_found","error":10004}
```

verbose output:
```
Request: GET https://test.deribit.com/api/v1/private/orderstate {'x-deribit-sig': 'HwVuaBHjPDva.1548500423074.Okt/pCR1RiQxWlD5IRs1mmJJkIdHvNWToDTNcwHQsck=', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://test.deribit.com/api/v1/private/orderstate 200 {'Server': 'nginx/1.10.3', 'Date': 'Sat, 26 Jan 2019 11:00:23 GMT', 'Content-Type': 'application/json', 'Content-Length': '136', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=15768000', 'X-Frame-Options': 'SAMEORIGIN'} {"usOut":1548500423108195,"usIn":1548500423107696,"usDiff":499,"testnet":true,"success":false,"message":"order_not_found","error":10004}
```

**Comment by furryboffin** [comment]
does anyone have a fix for this?

**Comment by furryboffin** [comment]
I made a simple script to get a know order id.

the verbose messaged returned is
I'm simply calling fetchOrder(id) with a known order id. I'm using Python.

Request: GET https://www.deribit.com/api/v1/private/orderstate {'x-deribit-sig': '5XoCJgbkVDiYL.1554972954071.8Tl2bZa3EzaQLhgeQhExBNH2HmrVYwm2jtg3BDTjiXY=', 'Accept-Encoding': 'gzip, deflate'} None

it looks to me as if the query string is not on the url, shouldn't there be a ?orderID=blah on there?

ideas?

**Comment by furryboffin** [comment]
So, I debugged it myself and I found the problem... here is a snapshot of the change I made to the code. The problem was that the sign() method did not handle the case when you have a GET request with a query param on the url.  This may not be completely fantastic, but it works for me.

 def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        query = '/' + 'api/' + self.version + '/' + api + '/' + path
        url = self.urls['api'] + query
        if api == 'public':
            if params:
                url += '?' + self.urlencode(params)
        else:
            self.check_required_credentials()
            nonce = str(self.nonce())
            auth = '_=' + nonce + '&_ackey=' + self.apiKey + '&_acsec=' + self.secret + '&_action=' + query
            if method == 'POST':
                params = self.keysort(params)
                auth += '&' + self.urlencode(params)
            elif method == 'GET':
                if params:
                    auth += '&' + self.urlencode(params)
                    url += '?' + self.urlencode(params)

            hash = self.hash(self.encode(auth), 'sha256', 'base64')
            signature = self.apiKey + '.' + nonce + '.' + self.decode(hash)
            headers = {
                'x-deribit-sig': signature,
            }
            if method != 'GET':
                headers['Content-Type'] = 'application/x-www-form-urlencoded'
                body = self.urlencode(params)

        return {'url': url, 'method': method, 'body': body, 'headers': headers}

**Comment by kroitor** [comment]
@furryboffin thx so much for reporting back! Really appreciate your help! Your PRs and contributions are welcome! https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
