### ISSUE TITLE
Bit-Z .createLimitBuyOrder() error: this.privatePostTradeAdd is not a function

### ISSUE THREAD

**Issue by xogoc** [ccxt/ccxt#3789]
- OS: Ubuntu 16.04.5
- Programming Language version: Node.js v8.11.3
- CCXT version: 1.17.224
- Exchange: Bit-Z
- Method: createLimitBuyOrder

My code:
```
const ccxt = require('ccxt');
const exchange = new ccxt.bitz({
    apiKey: "********",
    secret: "********",
    password: "********",
    verbose: true
});
exchange.createLimitBuyOrder("POK/BTC", 10, 0.00000100);
```
Output:
```
fetch:
 bitz GET https://apiv2.bitz.com/Market/symbolList
Request:
 { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36' }
 undefined

handleRestResponse:
 bitz GET https://apiv2.bitz.com/Market/symbolList 200 OK
Response:
 { Date: 'Mon, 03 Sep 2018 18:45:13 GMT',
  'Content-Type': 'text/html; charset=utf-8',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  Server: 'nginx',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'content-type',
  'Access-Control-Request-Method': 'GET,POST',
  'Content-Encoding': 'gzip' }
 {"status":200,"msg":"","data":{ ... markets data ... },"time":1536000313,"microtime":"0.95307500 1536000313","source":"api"}

(node:10698) UnhandledPromiseRejectionWarning: TypeError: this.privatePostTradeAdd is not a function
    at bitz.createOrder (/var/www/node/dev/node_modules/ccxt/js/bitz.js:778:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:10698) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10698) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
@xogoc fixed in 1.17.225, duplicate: https://github.com/ccxt/ccxt/issues/3650#issuecomment-418177548
