### ISSUE TITLE
Request timeout after one day of running

### ISSUE THREAD

**Issue by thomas-leeee** [ccxt/ccxt#3904]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: MacOS
- Programming Language version: python
- CCXT version: 1.17.212
- Exchange: bittrex (also binance)
- Method: not sure

I am trying the following code
```
client = getattr(ccxt, exchange)(params)
reload_markets = False
count = 1
while True:
        logger.info('Starting cycle number %s.', count)
        # reload market everyday
        while (client.markets is None) or (reload_markets == True):
            markets = client.load_markets(True)
            logger.info('Successully (re)load %s markets.', len(markets))
        # DO WORK
```
and it runs fine after one day, but then break with error
```
2018-09-26 14:05:10,549 - Starting cycle number 1594.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 381, in fetch
    proxies=self.proxies
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bittrex_sync.py", line 474, in <module>
    start_monitoring(EXCHANGE)
  File "bittrex_sync.py", line 396, in start_monitoring
    tickers = client.fetch_tickers()
  File "/usr/lib/python3.6/site-packages/ccxt/bittrex.py", line 365, in fetch_tickers
    response = self.publicGetMarketsummaries(params)
  File "/usr/lib/python3.6/site-packages/ccxt/bittrex.py", line 761, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 327, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 391, in fetch
    self.raise_error(RequestTimeout, method, url, e)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 312, in raise_error
    raise exception_type(output)
ccxt.base.errors.RequestTimeout: bittrex GET https://bittrex.com/api/v1.1/public/getmarketsummaries HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=2)
```

Note that my code never set reload_markets = True (yet to be implemented). I want to let this run unattended for long time. What is breaking here?

**Comment by blutooth** [comment]
Hi Thomas, sorry I can't answer your question, but doing a survey on exchange tech. What are your biggest problems with trading multiple exchanges? Have you found it difficult operating on multiple exchanges? Is shorting ever an issue? Thanks :)

**Comment by thomas-leeee** [comment]
@blutooth , for your questions:

What are your biggest problems with trading multiple exchanges? Have you found it difficult operating on multiple exchanges?
---> non-unified responses (e.g. json)
Is shorting ever an issue?
---> yes, you cant short altcoins in most normal exchanges

**Comment by kroitor** [comment]
> EDIT: I set RATELIMIT to 100 but I dont think this is the reason it break my code (synchronous), never got ban from bittrex or binance.

You don't want to really set it to 100 until you understand completely what it does. The `rateLimit` is the delay in milliseconds between your consequent requests, so if you set it to 100 and try polling with 100ms delay, you will get banned by binance (and bittrex most likely). It is set to a safe default, which is beyond one second. Tweaking it to a very low value may be a reason for getting banned in the first place, as explained in the Manual. However, neither Bittrex nor Binance ban you for long, unless you're too aggressive on their system.

I suggest to try the very basic thing first (also, please, always post complete programs to reproduce your issue, because you don't show the linking and your instantiation params, which may be the key to your issue):

```Python
import ccxt
import sys
id = 'bittrex'
params = {
    'enableRateLimit': True,  #  ←--------- REQUIRED, as described in the Manual
}
exchange = getattr(ccxt, id)(params)
count = 1
while True:
    try:
        print(exchange.iso8601(exchange.milliseconds()), 'Starting cycle number', count)
        count += 1
        markets = exchange.load_markets(True)
        print(exchange.iso8601(exchange.milliseconds()), 'Successully (re)load markets', len(markets))
    except ccxt.RequestTimeout as e:
        # recoverable error, do nothing and retry later
        print(type(e).__name__, str(e))
    except ccxt.DDoSProtection as e:
        # recoverable error, you might want to sleep a bit here and retry later
        print(type(e).__name__, str(e))
    except ccxt.ExchangeNotAvailable as e:
        # recoverable error, do nothing and retry later
        print(type(e).__name__, str(e))
    except ccxt.NetworkError as e:
        # do nothing and retry later...
        print(type(e).__name__, str(e))
    except Exception as e:
        # panic and halt the execution in case of any other error
        print(type(e).__name__, str(e))
        sys.exit()
```

↑ This is an example of complete program you can copypaste it to your python and run it without editing and this is the way we'd expect the code from you. 

Questions on the above code snippet are:
- does it hang?
- is the hanging repeatable?
- is it persistent and repeating after encountering it for the first time?

Also, have you read this? ↓

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
