### ISSUE TITLE
Having trouble installing CCXT

### ISSUE THREAD

**Issue by alexgpark** [ccxt/ccxt#3923]
- OS: Ubuntu NodeJS 6.12.3 on 16.04 
- Programming Language version: Javascript
- CCXT version: 1.17.361
- Exchange: N/A
- Method: N/A

Here is the error:

```
root@pilot2:~# npm i ccxt
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> sha3@1.2.2 install /root/node_modules/ethereumjs-abi/node_modules/sha3
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-109-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/ethereumjs-abi/node_modules/sha3
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-01T00_41_58_872Z-debug.log

**Comment by kroitor** [comment]
@alexgpark 

> gyp ERR! stack Error: not found: make

Do you have a `make` command on your system? Most Linux systems come with `make` preinstalled. 
Try `whereis make` or use the `find` command to locate it on your system. If you do not have it, you should install it and make sure it's accessible from your PATH env variable. See instructions on how to install packages for your distribution. Let us know if the issue persists after installing `make` and retrying to install ccxt after that.

**Comment by kroitor** [comment]
See also: 

- https://stackoverflow.com/questions/14772508/npm-failed-to-install-time-with-make-not-found-error
- https://www.google.ru/search?q=ubuntu+gyp+ERR!+stack+Error%3A+not+found%3A+make

**Comment by alexgpark** [comment]
Thanks very much and sorry for the duplicate issue!

https://stackoverflow.com/questions/14772508/npm-failed-to-install-time-with-make-not-found-error

^ That did the trick

**Comment by kroitor** [comment]
@alexgpark thx for reporting back!
