### ISSUE TITLE
Potential Issues with Kucoin

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#3930]
This issue arises when I fetch balances, deposit addresses, initiate trades, etc.

- OS: Puppy Linux
- Programming Language version: Python
- CCXT version: Latest
- Exchange: Kucoin
- Method: All Private Methods (Will use fetch balance as an example).

```
kucoin.fetchBalance()

Request: GET https://api.kucoin.com/v1/account/balance {'KC-API-KEY': 'INTENTIONALLY OMITTED', 'KC-API-NONCE': 'INTENTIONALLY OMMITED', 'KC-API-SIGNATURE': 'INTENTIONALLY OMITTED', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.kucoin.com/v1/account/balance 200 {'Date': 'Tue, 02 Oct 2018 04:24:06 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dcc8dd35a964e1fa654fbee0a209259b51538454246; expires=Wed, 02-Oct-19 04:24:06 GMT; path=/; domain=.kucoin.com; HttpOnly; Secure', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*', 'Access-Control-Allow-Methods': 'GET,PUT,DELETE,POST', 'Access-Control-Max-Age': '86400', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '463465be7c69ab84-YYZ', 'Content-Encoding': 'gzip'} {"code":"UNAUTH","msg":"Invalid nonce","success":false,"timestamp":1538454246242}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/kucoin.py", line 640, in fetch_balance
    }, params))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 362, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 359, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 457, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, http_response)
  File "/usr/local/lib/python3.7/site-packages/ccxt/kucoin.py", line 1302, in handle_errors
    self.throw_exception_on_error(json.loads(body))
  File "/usr/local/lib/python3.7/site-packages/ccxt/kucoin.py", line 1278, in throw_exception_on_error
    raise InvalidNonce(feedback)
ccxt.base.errors.InvalidNonce: kucoin {"code":"UNAUTH","msg":"Invalid nonce","success":false,"timestamp":1538454246242}
```
Thanks.

**Comment by karlandoh** [comment]
This problem was solved on its own. Save yourself some time. Take care.
