### ISSUE TITLE
bifinex KeyError: 'BTC/USD'

### ISSUE THREAD

**Issue by terrorizers** [ccxt/ccxt#3934]
- OS: ubuntu
- Programming Language version: python3
- CCXT version: 1.17.356
- Exchange: bifinex
- Method: create order

```
api_key= 'LtHrR1oAmpiVUCwOrKsttHs0hs'
api_secret='CorCJVUaYSDxIvnBwwhIt'
bitfinex = ccxt.bitfinex({'apiKey': api_key, 'secret': api_secret, 'enableRateLimit': True,})
order = bitfinex.create_order('BTC/USD', 'Market', 'buy', 1, None, {})
print(order)
```

```
Traceback (most recent call last):
  File "arbiter.py", line 14, in <module>
    order = bitfinex.create_order('BTC/USD', 'Market', 'buy', 1, None, {})
  File "/usr/local/lib/python3.5/dist-packages/ccxt/bitfinex.py", line 627, in create_order
    amount = self.amount_to_precision(symbol, amount)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 1036, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode)
KeyError: 'BTC/USD'
```

oh oh https://github.com/ccxt/ccxt/issues/3914 this time seems it's not working XD

**Comment by kroitor** [comment]
Answered here:

- https://github.com/ccxt/ccxt/issues/2851

Have you tried launching the symbols example to see the full list of bitfinex market ids and symbols yourself? Because if you did, you would get the answer right away.

- https://github.com/ccxt/ccxt/blob/master/examples/py/symbols.py

```
id              symbol          base            quote
ABSETH          ABYSS/ETH       ABYSS           ETH
ABSUSD          ABYSS/USDT      ABYSS           USDT
AGIBTC          AGI/BTC         AGI             BTC
AGIETH          AGI/ETH         AGI             ETH
AGIUSD          AGI/USDT        AGI             USDT
AIDBTC          AID/BTC         AID             BTC
AIDETH          AID/ETH         AID             ETH
AIDUSD          AID/USDT        AID             USDT
AIOBTC          AION/BTC        AION            BTC
AIOETH          AION/ETH        AION            ETH
AIOUSD          AION/USDT       AION            USDT
ANTBTC          ANT/BTC         ANT             BTC
ANTETH          ANT/ETH         ANT             ETH
ANTUSD          ANT/USDT        ANT             USDT
ATMBTC          ATMI/BTC        ATMI            BTC
ATMETH          ATMI/ETH        ATMI            ETH
ATMUSD          ATMI/USDT       ATMI            USDT
AUCBTC          AUC/BTC         AUC             BTC
AUCETH          AUC/ETH         AUC             ETH
AUCUSD          AUC/USDT        AUC             USDT
AVTBTC          AVT/BTC         AVT             BTC
AVTETH          AVT/ETH         AVT             ETH
AVTUSD          AVT/USDT        AVT             USDT
BATBTC          BAT/BTC         BAT             BTC
BATETH          BAT/ETH         BAT             ETH
BATUSD          BAT/USDT        BAT             USDT
BBNETH          BBN/ETH         BBN             ETH
BBNUSD          BBN/USDT        BBN             USDT
BCHBTC          BCH/BTC         BCH             BTC
BCHETH          BCH/ETH         BCH             ETH
BCHUSD          BCH/USDT        BCH             USDT
BCIBTC          BCI/BTC         BCI             BTC
BCIUSD          BCI/USDT        BCI             USDT
BFTBTC          BFT/BTC         BFT             BTC
BFTETH          BFT/ETH         BFT             ETH
BFTUSD          BFT/USDT        BFT             USDT
BNTBTC          BNT/BTC         BNT             BTC
BNTETH          BNT/ETH         BNT             ETH
BNTUSD          BNT/USDT        BNT             USDT
BOXETH          BOX/ETH         BOX             ETH
BOXUSD          BOX/USDT        BOX             USDT
BTCEUR          BTC/EUR         BTC             EUR
BTCGBP          BTC/GBP         BTC             GBP
BTCJPY          BTC/JPY         BTC             JPY
BTCUSD          BTC/USDT        BTC             USDT  #  ←-------- BTC/USDT (not BTC/USD)
BTGBTC          BTG/BTC         BTG             BTC
BTGUSD          BTG/USDT        BTG             USDT
CBTBTC          CBT/BTC         CBT             BTC
CBTETH          CBT/ETH         CBT             ETH
CBTUSD          CBT/USDT        CBT             USDT
CFIBTC          CFI/BTC         CFI             BTC
CFIETH          CFI/ETH         CFI             ETH
CFIUSD          CFI/USDT        CFI             USDT
CNDBTC          CND/BTC         CND             BTC
CNDETH          CND/ETH         CND             ETH
CNDUSD          CND/USDT        CND             USDT
CNNETH          CNN/ETH         CNN             ETH
CNNUSD          CNN/USDT        CNN             USDT
CTXBTC          CTXC/BTC        CTXC            BTC
CTXETH          CTXC/ETH        CTXC            ETH
CTXUSD          CTXC/USDT       CTXC            USDT
DADBTC          DADI/BTC        DADI            BTC
DADETH          DADI/ETH        DADI            ETH
DADUSD          DADI/USDT       DADI            USDT
DAIBTC          DAI/BTC         DAI             BTC
DAIETH          DAI/ETH         DAI             ETH
DAIUSD          DAI/USDT        DAI             USDT
DSHBTC          DASH/BTC        DASH            BTC
DSHUSD          DASH/USDT       DASH            USDT
DATBTC          DATA/BTC        DATA            BTC
DATETH          DATA/ETH        DATA            ETH
DATUSD          DATA/USDT       DATA            USDT
DGXETH          DGX/ETH         DGX             ETH
DGXUSD          DGX/USDT        DGX             USDT
DTABTC          DTA/BTC         DTA             BTC
DTAETH          DTA/ETH         DTA             ETH
DTAUSD          DTA/USDT        DTA             USDT
DTHBTC          DTH/BTC         DTH             BTC
DTHETH          DTH/ETH         DTH             ETH
DTHUSD          DTH/USDT        DTH             USDT
EDOBTC          EDO/BTC         EDO             BTC
EDOETH          EDO/ETH         EDO             ETH
EDOUSD          EDO/USDT        EDO             USDT
ELFBTC          ELF/BTC         ELF             BTC
ELFETH          ELF/ETH         ELF             ETH
ELFUSD          ELF/USDT        ELF             USDT
EOSBTC          EOS/BTC         EOS             BTC
EOSETH          EOS/ETH         EOS             ETH
EOSEUR          EOS/EUR         EOS             EUR
EOSGBP          EOS/GBP         EOS             GBP
EOSJPY          EOS/JPY         EOS             JPY
EOSUSD          EOS/USDT        EOS             USDT
ESSBTC          ESS/BTC         ESS             BTC
ESSETH          ESS/ETH         ESS             ETH
ESSUSD          ESS/USDT        ESS             USDT
ETCBTC          ETC/BTC         ETC             BTC
ETCUSD          ETC/USDT        ETC             USDT
ETHBTC          ETH/BTC         ETH             BTC
ETHEUR          ETH/EUR         ETH             EUR
ETHGBP          ETH/GBP         ETH             GBP
ETHJPY          ETH/JPY         ETH             JPY
ETHUSD          ETH/USDT        ETH             USDT
ETPBTC          ETP/BTC         ETP             BTC
ETPETH          ETP/ETH         ETP             ETH
ETPUSD          ETP/USDT        ETP             USDT
FSNBTC          FSN/BTC         FSN             BTC
FSNETH          FSN/ETH         FSN             ETH
FSNUSD          FSN/USDT        FSN             USDT
FUNBTC          FUN/BTC         FUN             BTC
FUNETH          FUN/ETH         FUN             ETH
FUNUSD          FUN/USDT        FUN             USDT
GNTBTC          GNT/BTC         GNT             BTC
GNTETH          GNT/ETH         GNT             ETH
GNTUSD          GNT/USDT        GNT             USDT
GOTETH          GOT/ETH         GOT             ETH
GOTEUR          GOT/EUR         GOT             EUR
GOTUSD          GOT/USDT        GOT             USDT
HOTBTC          Hydro Protocol/BTC Hydro Protocol  BTC
HOTETH          Hydro Protocol/ETH Hydro Protocol  ETH
HOTUSD          Hydro Protocol/USDT Hydro Protocol  USDT
IOSBTC          IOST/BTC        IOST            BTC
IOSETH          IOST/ETH        IOST            ETH
IOSUSD          IOST/USDT       IOST            USDT
IOTBTC          IOTA/BTC        IOTA            BTC
IOTETH          IOTA/ETH        IOTA            ETH
IOTEUR          IOTA/EUR        IOTA            EUR
IOTGBP          IOTA/GBP        IOTA            GBP
IOTJPY          IOTA/JPY        IOTA            JPY
IOTUSD          IOTA/USDT       IOTA            USDT
IQXBTC          IQ/BTC          IQ              BTC
IQXEOS          IQ/EOS          IQ              EOS
IQXUSD          IQ/USDT         IQ              USDT
KNCBTC          KNC/BTC         KNC             BTC
KNCETH          KNC/ETH         KNC             ETH
KNCUSD          KNC/USDT        KNC             USDT
LRCBTC          LRC/BTC         LRC             BTC
LRCETH          LRC/ETH         LRC             ETH
LRCUSD          LRC/USDT        LRC             USDT
LTCBTC          LTC/BTC         LTC             BTC
LTCUSD          LTC/USDT        LTC             USDT
LYMBTC          LYM/BTC         LYM             BTC
LYMETH          LYM/ETH         LYM             ETH
LYMUSD          LYM/USDT        LYM             USDT
MANETH          MAN/ETH         MAN             ETH
MANUSD          MAN/USDT        MAN             USDT
MNABTC          MANA/BTC        MANA            BTC
MNAETH          MANA/ETH        MANA            ETH
MNAUSD          MANA/USDT       MANA            USDT
MITBTC          MITH/BTC        MITH            BTC
MITETH          MITH/ETH        MITH            ETH
MITUSD          MITH/USDT       MITH            USDT
MKRBTC          MKR/BTC         MKR             BTC
MKRETH          MKR/ETH         MKR             ETH
MKRUSD          MKR/USDT        MKR             USDT
MTNBTC          MTN/BTC         MTN             BTC
MTNETH          MTN/ETH         MTN             ETH
MTNUSD          MTN/USDT        MTN             USDT
NCABTC          NCASH/BTC       NCASH           BTC
NCAETH          NCASH/ETH       NCASH           ETH
NCAUSD          NCASH/USDT      NCASH           USDT
NEOBTC          NEO/BTC         NEO             BTC
NEOETH          NEO/ETH         NEO             ETH
NEOEUR          NEO/EUR         NEO             EUR
NEOGBP          NEO/GBP         NEO             GBP
NEOJPY          NEO/JPY         NEO             JPY
NEOUSD          NEO/USDT        NEO             USDT
NIOETH          NIO/ETH         NIO             ETH
NIOUSD          NIO/USDT        NIO             USDT
ODEBTC          ODE/BTC         ODE             BTC
ODEETH          ODE/ETH         ODE             ETH
ODEUSD          ODE/USDT        ODE             USDT
OMGBTC          OMG/BTC         OMG             BTC
OMGETH          OMG/ETH         OMG             ETH
OMGUSD          OMG/USDT        OMG             USDT
ORSBTC          ORS Group/BTC   ORS Group       BTC
ORSETH          ORS Group/ETH   ORS Group       ETH
ORSUSD          ORS Group/USDT  ORS Group       USDT
PAIBTC          PAI/BTC         PAI             BTC
PAIUSD          PAI/USDT        PAI             USDT
POABTC          POA/BTC         POA             BTC
POAETH          POA/ETH         POA             ETH
POAUSD          POA/USDT        POA             USDT
POYBTC          POLY/BTC        POLY            BTC
POYETH          POLY/ETH        POLY            ETH
POYUSD          POLY/USDT       POLY            USDT
QSHBTC          QASH/BTC        QASH            BTC
QSHETH          QASH/ETH        QASH            ETH
QSHUSD          QASH/USDT       QASH            USDT
QTMBTC          QTUM/BTC        QTUM            BTC
QTMETH          QTUM/ETH        QTUM            ETH
QTMUSD          QTUM/USDT       QTUM            USDT
RCNBTC          RCN/BTC         RCN             BTC
RCNETH          RCN/ETH         RCN             ETH
RCNUSD          RCN/USDT        RCN             USDT
RDNBTC          RDN/BTC         RDN             BTC
RDNETH          RDN/ETH         RDN             ETH
RDNUSD          RDN/USDT        RDN             USDT
REPBTC          REP/BTC         REP             BTC
REPETH          REP/ETH         REP             ETH
REPUSD          REP/USDT        REP             USDT
REQBTC          REQ/BTC         REQ             BTC
REQETH          REQ/ETH         REQ             ETH
REQUSD          REQ/USDT        REQ             USDT
RLCBTC          RLC/BTC         RLC             BTC
RLCETH          RLC/ETH         RLC             ETH
RLCUSD          RLC/USDT        RLC             USDT
RRTBTC          RRT/BTC         RRT             BTC
RRTUSD          RRT/USDT        RRT             USDT
SANBTC          SAN/BTC         SAN             BTC
SANETH          SAN/ETH         SAN             ETH
SANUSD          SAN/USDT        SAN             USDT
SEEBTC          SEER/BTC        SEER            BTC
SEEETH          SEER/ETH        SEER            ETH
SEEUSD          SEER/USDT       SEER            USDT
SENBTC          SEN/BTC         SEN             BTC
SENETH          SEN/ETH         SEN             ETH
SENUSD          SEN/USDT        SEN             USDT
SNGBTC          SNGLS/BTC       SNGLS           BTC
SNGETH          SNGLS/ETH       SNGLS           ETH
SNGUSD          SNGLS/USDT      SNGLS           USDT
SNTBTC          SNT/BTC         SNT             BTC
SNTETH          SNT/ETH         SNT             ETH
SNTUSD          SNT/USDT        SNT             USDT
SPKBTC          SPANK/BTC       SPANK           BTC
SPKETH          SPANK/ETH       SPANK           ETH
SPKUSD          SPANK/USDT      SPANK           USDT
STJBTC          STORJ/BTC       STORJ           BTC
STJETH          STORJ/ETH       STORJ           ETH
STJUSD          STORJ/USDT      STORJ           USDT
TKNETH          TKN/ETH         TKN             ETH
TKNUSD          TKN/USDT        TKN             USDT
TNBBTC          TNB/BTC         TNB             BTC
TNBETH          TNB/ETH         TNB             ETH
TNBUSD          TNB/USDT        TNB             USDT
TRXBTC          TRX/BTC         TRX             BTC
TRXETH          TRX/ETH         TRX             ETH
TRXUSD          TRX/USDT        TRX             USDT
UTKBTC          UTK/BTC         UTK             BTC
UTKETH          UTK/ETH         UTK             ETH
UTKUSD          UTK/USDT        UTK             USDT
UTNETH          UTNP/ETH        UTNP            ETH
UTNUSD          UTNP/USDT       UTNP            USDT
VEEBTC          VEE/BTC         VEE             BTC
VEEETH          VEE/ETH         VEE             ETH
VEEUSD          VEE/USDT        VEE             USDT
VETBTC          VET/BTC         VET             BTC
VETETH          VET/ETH         VET             ETH
VETUSD          VET/USDT        VET             USDT
WAXBTC          WAX/BTC         WAX             BTC
WAXETH          WAX/ETH         WAX             ETH
WAXUSD          WAX/USDT        WAX             USDT
WPRBTC          WPR/BTC         WPR             BTC
WPRETH          WPR/ETH         WPR             ETH
WPRUSD          WPR/USDT        WPR             USDT
XLMBTC          XLM/BTC         XLM             BTC
XLMETH          XLM/ETH         XLM             ETH
XLMEUR          XLM/EUR         XLM             EUR
XLMGBP          XLM/GBP         XLM             GBP
XLMJPY          XLM/JPY         XLM             JPY
XLMUSD          XLM/USDT        XLM             USDT
XMRBTC          XMR/BTC         XMR             BTC
XMRUSD          XMR/USDT        XMR             USDT
XRAETH          XRA/ETH         XRA             ETH
XRAUSD          XRA/USDT        XRA             USDT
XRPBTC          XRP/BTC         XRP             BTC
XRPUSD          XRP/USDT        XRP             USDT
XTZBTC          XTZ/BTC         XTZ             BTC
XTZUSD          XTZ/USDT        XTZ             USDT
XVGBTC          XVG/BTC         XVG             BTC
XVGETH          XVG/ETH         XVG             ETH
XVGEUR          XVG/EUR         XVG             EUR
XVGGBP          XVG/GBP         XVG             GBP
XVGJPY          XVG/JPY         XVG             JPY
XVGUSD          XVG/USDT        XVG             USDT
YYWBTC          YOYOW/BTC       YOYOW           BTC
YYWETH          YOYOW/ETH       YOYOW           ETH
YYWUSD          YOYOW/USDT      YOYOW           USDT
ZCNBTC          ZCN/BTC         ZCN             BTC
ZCNETH          ZCN/ETH         ZCN             ETH
ZCNUSD          ZCN/USDT        ZCN             USDT
ZECBTC          ZEC/BTC         ZEC             BTC
ZECUSD          ZEC/USDT        ZEC             USDT
ZILBTC          ZIL/BTC         ZIL             BTC
ZILETH          ZIL/ETH         ZIL             ETH
ZILUSD          ZIL/USDT        ZIL             USDT
ZRXBTC          ZRX/BTC         ZRX             BTC
ZRXETH          ZRX/ETH         ZRX             ETH
ZRXUSD          ZRX/USDT        ZRX             USDT
mbp:ccxt igorkroitor$ python3 examples/py/symbols.py bitfinex
```

**Comment by terrorizers** [comment]
I dont know of that, I will try to pull request a modification of the error like `KeyError: 'BTC/USD, reference: symbols.py'

but anyway doesn't works:

```
Traceback (most recent call last):
  File "arbiter.py", line 14, in <module>
    order = bitfinex.create_order('BTC/USDT', 'Market', 'buy', 0.002, None, {})
  File "/usr/local/lib/python3.5/dist-packages/ccxt/bitfinex.py", line 640, in create_order
    order['price'] = self.price_to_precision(symbol, price)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 1033, in price_to_precision
    return self.decimal_to_precision(price, ROUND, self.markets[symbol]['precision']['price'], self.precisionMode)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/decimal_to_precision.py", line 43, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by kroitor** [comment]
> bitfinex.create_order('BTC/USDT', 'Market', 'buy', 0.002, None, {})

First, if you read the Manual carefully, there's no `Market` type of order, it's `market`.

**Comment by kroitor** [comment]
In other words, if you do the above two edits to your call, it should look like this:

```Python
bitfinex.create_order('BTC/USDT', 'market', 'buy', 0.002, None, {})
```

**Comment by terrorizers** [comment]
mmmm, ok then this is not in line with BitMEX: https://github.com/ccxt/ccxt/commit/f50942bd1af6dd6b2488cdbf0634bd465b18a751 also others are all Capitalized ('Stop' or 'StopLimit') so it feels right capitalized as it works for BitMEX, anyway you choose, and thanks a lot! But how can I run strategy on margin account? (Promise last question :D, I hope XD)

**Comment by kroitor** [comment]
> then this is not in line with BitMEX: f50942b also others are all Capitalized ('Stop' or 'StopLimit') so it feels right capitalized as it works for BitMEX

First of, you should really stick to the Manual. In short, the Manual says something like: *we support either `market` or `limit` because we have unified spot trading, but for other types of trading like margin trading it may require exchange-specific overrides (positional trading is not unified yet)*. 

From it you should carry the following: the two values `market` and `limit` work everywhere, other values don't go in there in most cases, however, in some cases, like that of BitMEX, other types of orders may work as well (this is exchange-specific and may require additional code or handling from you).

> But how can I run strategy on margin account?

By reading the Manual from top to bottom at least once and sticking to it (as this question is covered there) ;) So, if you want to do some margin trading, you will have to override some unified params or use implicit methods or both:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

But first, rtfm, really. That would help save a ton of your time (and mine). There's also a magic **Search** button on every GitHub page, that you can use to search within issues and code in this repo. Try using it together with the following keywords: `bitfinex margin trading`, `bitfinex position`, etc (what else comes to mind?). Think this way: you're probably not the very first user of this lib, so, maybe, just maybe, someone else has already asked exactly the same question and got the answer ;)

**Comment by terrorizers** [comment]
Sorry bro I get your feeling, problem is I come here just to avoid read manuals XD but I know I should and I'll do now!

**Comment by slidenerd** [comment]
Curious question, why does Hydro Protocol/BTC and ORS Group/BTC show as a pair in your output , shouldnt it be HOT/BTC and ORS/BTC

**Comment by kroitor** [comment]
@slidenerd 

- https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#notes-on-naming-consistency
- https://github.com/ccxt/ccxt/search?q=HOT+Hydro&type=Issues
- https://github.com/ccxt/ccxt/search?q=ors&unscoped_q=ors&type=Issues
- https://github.com/ccxt/ccxt/issues/3230
