### ISSUE TITLE
coinfalcon.py seems broken for me in version .365

### ISSUE THREAD

**Issue by rhythem** [ccxt/ccxt#3936]
- OS: Amazon Linux - RHEL
- Programming Language version: Python 2.7.14
- CCXT version: ccxt==1.17.365
- Exchange: coinfalcon
- Method: fetchTickers.
```
('\nRequest:', 'GET', 'https://coinfalcon.com/api/v1/markets', {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.19.1'}, None)
('\nResponse:', 'GET', 'https://coinfalcon.com/api/v1/markets', '200', '{\'Expect-CT\': \'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"\', \'X-Request-Id\': \'88ebade4-9cf9-4cf8-a5d6-2c94b48c3f7c\', \'Content-Security-Policy\': "frame-ancestors \'self\'", \'Transfer-Encoding\': \'chunked\', \'Version\': \'HTTP/1.1\', \'Cf-Visitor\': \'{"scheme":"https"}\', \'X-Frame-Options\': \'SAMEORIGIN\', \'User-Agent\': \'python-requests/2.19.1\', \'X-Runtime\': \'0.045967\', \'ETag\': \'W/"bb43e5d84abac0fb38eb40c7897fc95e"\', \'X-Forwarded-Port\': \'80\', \'Date\': \'Wed, 03 Oct 2018 06:50:53 GMT\', \'CF-RAY\': \'463d7a264c62c1ea-IAD\', \'Cf-Ipcountry\': \'US\', \'Cf-Connecting-Ip\': \'54.89.242.34\', \'Accept-Encoding\': \'gzip\', \'Set-Cookie\': \'__cfduid=d17f1cffe9728bb1dc455f76fbce2d9d31538549453; expires=Thu, 03-Oct-19 06:50:53 GMT; path=/; domain=.coinfalcon.com; HttpOnly; Secure\', \'Strict-Transport-Security\': \'max-age=15552000\', \'Server\': \'cloudflare\', \'Connection\': \'keep-alive\', \'X-Real-Ip\': \'54.89.242.34\', \'X-Nginx-Proxy\': \'true\', \'Content-Encoding\': \'gzip\', \'X-Forwarded-For\': \'54.89.242.34, 172.68.65.237, 54.89.242.34\', \'Vary\': \'Origin\', \'Accept\': \'*/*\', \'X-Forwarded-Proto\': \'https\', \'Cache-Control\': \'max-age=0, private, must-revalidate\', \'Referrer-Policy\': \'strict-origin-when-cross-origin\', \'Content-Type\': \'application/json;charset=utf-8\'}', u'{"data":[{"name":"IOT-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.04742026","last_price":"0.00008451","change_in_24h":"0.45","size_precision":8,"price_precision":8},{"name":"ETH-BTC","precision":5,"min_volume":"0.00000001","min_price":"0.00001","volume":"0.46454","last_price":"0.03369","change_in_24h":"-3.44","size_precision":8,"price_precision":5},{"name":"LTC-BTC","precision":5,"min_volume":"0.00000001","min_price":"0.00001","volume":"0.03766","last_price":"0.00895","change_in_24h":"-2.93","size_precision":8,"price_precision":5},{"name":"BTC-EUR","precision":2,"min_volume":"0.00000001","min_price":"0.01","volume":"23948.07","last_price":"5660.0","change_in_24h":"-1.05","size_precision":8,"price_precision":2},{"name":"NANO-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.014327","last_price":"0.00033","change_in_24h":"-5.43","size_precision":8,"price_precision":8},{"name":"BCH-BTC","precision":5,"min_volume":"0.00000001","min_price":"0.00001","volume":"0.0805","last_price":"0.08055","change_in_24h":"-0.56","size_precision":8,"price_precision":5},{"name":"KIN-BTC","precision":10,"min_volume":"1.0","min_price":"0.0000000001","volume":"0.0624052719","last_price":"0.0000000109","change_in_24h":"4.81","size_precision":0,"price_precision":10},{"name":"KIN-ETH","precision":8,"min_volume":"1.0","min_price":"0.00000001","volume":"0.6666766","last_price":"0.0000003","change_in_24h":"3.45","size_precision":0,"price_precision":8},{"name":"TRX-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.16269815","last_price":"0.00000335","change_in_24h":"-2.05","size_precision":8,"price_precision":8},{"name":"CRPT-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.02088924","last_price":"0.00006049","change_in_24h":"9.42","size_precision":8,"price_precision":8},{"name":"GRLC-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.10001298","last_price":"0.00000112","change_in_24h":"-5.88","size_precision":8,"price_precision":8},{"name":"ECA-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.00876571","last_price":"0.00000009","change_in_24h":"12.5","size_precision":8,"price_precision":8},{"name":"ECA-ETH","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.41469613","last_price":"0.00000295","change_in_24h":"0.68","size_precision":8,"price_precision":8},{"name":"XRP-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.31006304","last_price":"0.00007871","change_in_24h":"-13.26","size_precision":8,"price_precision":8},{"name":"ADA-BTC","precision":8,"min_volume":"0.000001","min_price":"0.00000001","volume":"0.08599023","last_price":"0.00001256","change_in_24h":"4.49","size_precision":6,"price_precision":8},{"name":"ADA-ETH","precision":8,"min_volume":"0.000001","min_price":"0.00000001","volume":"0.0","last_price":"0.00037","change_in_24h":"0.0","size_precision":6,"price_precision":8},{"name":"DOGE-BTC","precision":8,"min_volume":"0.00001","min_price":"0.00000001","volume":"0.39770422","last_price":"0.0000009","change_in_24h":"1.12","size_precision":5,"price_precision":8},{"name":"STQ-BTC","precision":8,"min_volume":"0.01","min_price":"0.00000001","volume":"0.00048231","last_price":"0.00000039","change_in_24h":"5.41","size_precision":2,"price_precision":8},{"name":"IOT-EUR","precision":4,"min_volume":"0.00001","min_price":"0.0001","volume":"4888.448","last_price":"0.498","change_in_24h":"-2.24","size_precision":5,"price_precision":4},{"name":"DASC-BTC","precision":8,"min_volume":"0.00001","min_price":"0.00000001","volume":"9.51311821","last_price":"0.0000043","change_in_24h":"-5.49","size_precision":5,"price_precision":8},{"name":"DASC-ETH","precision":8,"min_volume":"0.00001","min_price":"0.00000001","volume":"0.28183118","last_price":"0.00009911","change_in_24h":"-31.62","size_precision":5,"price_precision":8},{"name":"DASC-EUR","precision":4,"min_volume":"0.00001","min_price":"0.0001","volume":"4203.0632","last_price":"0.0263","change_in_24h":"-5.05","size_precision":5,"price_precision":4},{"name":"NANO-EUR","precision":4,"min_volume":"0.0001","min_price":"0.0001","volume":"234.5899","last_price":"1.95","change_in_24h":"-1.52","size_precision":4,"price_precision":4},{"name":"BTC-USDT","precision":2,"min_volume":"0.00000001","min_price":"0.01","volume":"1.02","last_price":"6586.5","change_in_24h":"-0.64","size_precision":8,"price_precision":2},{"name":"EOS-USDT","precision":2,"min_volume":"0.0001","min_price":"0.01","volume":"0.0","last_price":"4.16","change_in_24h":"0.0","size_precision":4,"price_precision":2},{"name":"DTX-BTC","precision":8,"min_volume":"0.01","min_price":"0.00000001","volume":"0.0265198","last_price":"0.00000337","change_in_24h":"-3.16","size_precision":2,"price_precision":8}]}')
Traceback (most recent call last):
  File "exchange.py", line 106, in <module>
    test.info(e.test_ticker("coinfalcon"))
  File "exchange.py", line 22, in test_ticker
    return exchange.fetch_tickers()
  File "/home/ec2-user/.local/lib/python2.7/site-packages/ccxt/coinfalcon.py", line 151, in fetch_tickers
    ticker = self.parse_ticker(tickers[i])
  File "/home/ec2-user/.local/lib/python2.7/site-packages/ccxt/coinfalcon.py", line 114, in parse_ticker
    market = self.marketsById[marketId]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by rhythem** [comment]
@kroitor  i am still facing an issue, different this time though. 
OS: Amazon Linux - RHEL
Programming Language version: Python 2.7.14
CCXT version: ccxt==1.17.369
Exchange: coinfalcon
Method: fetchTickers.
```
('\nRequest:', 'GET', 'https://coinfalcon.com/api/v1/markets', {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.19.1'}, None)
('\nResponse:', 'GET', 'https://coinfalcon.com/api/v1/markets', '200', '{\'Expect-CT\': \'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"\', \'X-Request-Id\': \'4b37c305-2665-4e5c-8cb5-e4cf46be76c8\', \'Content-Security-Policy\': "frame-ancestors \'self\'", \'Transfer-Encoding\': \'chunked\', \'Version\': \'HTTP/1.1\', \'Cf-Visitor\': \'{"scheme":"https"}\', \'X-Frame-Options\': \'SAMEORIGIN\', \'User-Agent\': \'python-requests/2.19.1\', \'X-Runtime\': \'0.079522\', \'ETag\': \'W/"6026955df5c06a862ceaf7a789117385"\', \'X-Forwarded-Port\': \'80\', \'Date\': \'Fri, 05 Oct 2018 08:19:08 GMT\', \'CF-RAY\': \'464e76275c39c1bd-IAD\', \'Cf-Ipcountry\': \'US\', \'Cf-Connecting-Ip\': \'54.89.242.34\', \'Accept-Encoding\': \'gzip\', \'Set-Cookie\': \'__cfduid=da16560be18e688633cf3230b6a7cdcb81538727548; expires=Sat, 05-Oct-19 08:19:08 GMT; path=/; domain=.coinfalcon.com; HttpOnly; Secure\', \'Strict-Transport-Security\': \'max-age=15552000\', \'Server\': \'cloudflare\', \'Connection\': \'keep-alive\', \'X-Real-Ip\': \'54.89.242.34\', \'X-Nginx-Proxy\': \'true\', \'Content-Encoding\': \'gzip\', \'X-Forwarded-For\': \'54.89.242.34, 172.68.65.205, 54.89.242.34\', \'Vary\': \'Origin\', \'Accept\': \'*/*\', \'X-Forwarded-Proto\': \'https\', \'Cache-Control\': \'max-age=0, private, must-revalidate\', \'Referrer-Policy\': \'strict-origin-when-cross-origin\', \'Content-Type\': \'application/json;charset=utf-8\'}', u'{"data":[{"name":"IOT-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.1021341","last_price":"0.00008516","change_in_24h":"1.55","size_precision":8,"price_precision":8},{"name":"ETH-BTC","precision":5,"min_volume":"0.00000001","min_price":"0.00001","volume":"0.30824","last_price":"0.03389","change_in_24h":"-0.35","size_precision":8,"price_precision":5},{"name":"LTC-BTC","precision":5,"min_volume":"0.00000001","min_price":"0.00001","volume":"0.05322","last_price":"0.00891","change_in_24h":"0.11","size_precision":8,"price_precision":5},{"name":"BTC-EUR","precision":2,"min_volume":"0.00000001","min_price":"0.01","volume":"3727.24","last_price":"5718.0","change_in_24h":"-0.38","size_precision":8,"price_precision":2},{"name":"NANO-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.05522003","last_price":"0.00034899","change_in_24h":"9.01","size_precision":8,"price_precision":8},{"name":"BCH-BTC","precision":5,"min_volume":"0.00000001","min_price":"0.00001","volume":"0.00002","last_price":"0.07803","change_in_24h":"-2.65","size_precision":8,"price_precision":5},{"name":"KIN-BTC","precision":10,"min_volume":"1.0","min_price":"0.0000000001","volume":"0.1824434458","last_price":"0.0000000109","change_in_24h":"3.81","size_precision":0,"price_precision":10},{"name":"KIN-ETH","precision":8,"min_volume":"1.0","min_price":"0.00000001","volume":"5.47506646","last_price":"0.00000028","change_in_24h":"-15.15","size_precision":0,"price_precision":8},{"name":"TRX-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.2930306","last_price":"0.00000346","change_in_24h":"1.17","size_precision":8,"price_precision":8},{"name":"CRPT-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.10526195","last_price":"0.00005018","change_in_24h":"-15.05","size_precision":8,"price_precision":8},{"name":"GRLC-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.04198173","last_price":"0.00000093","change_in_24h":"-9.71","size_precision":8,"price_precision":8},{"name":"ECA-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.01633445","last_price":"0.00000008","change_in_24h":"-11.11","size_precision":8,"price_precision":8},{"name":"ECA-ETH","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.17575521","last_price":"0.0000029","change_in_24h":"36.15","size_precision":8,"price_precision":8},{"name":"XRP-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.07065336","last_price":"0.00008","change_in_24h":"-1.3","size_precision":8,"price_precision":8},{"name":"ADA-BTC","precision":8,"min_volume":"0.000001","min_price":"0.00000001","volume":"0.003","last_price":"0.0000127","change_in_24h":"0.0","size_precision":6,"price_precision":8},{"name":"ADA-ETH","precision":8,"min_volume":"0.000001","min_price":"0.00000001","volume":"0.0","last_price":"0.00037","change_in_24h":"0.0","size_precision":6,"price_precision":8},{"name":"DOGE-BTC","precision":8,"min_volume":"0.00001","min_price":"0.00000001","volume":"0.30692221","last_price":"0.00000087","change_in_24h":"0.0","size_precision":5,"price_precision":8},{"name":"STQ-BTC","precision":8,"min_volume":"0.01","min_price":"0.00000001","volume":"0.0016933","last_price":"0.00000041","change_in_24h":"-2.38","size_precision":2,"price_precision":8},{"name":"IOT-EUR","precision":4,"min_volume":"0.00001","min_price":"0.0001","volume":"1247.6863","last_price":"0.5046","change_in_24h":"-0.94","size_precision":5,"price_precision":4},{"name":"DASC-BTC","precision":8,"min_volume":"0.00001","min_price":"0.00000001","volume":"10.95737774","last_price":"0.00000441","change_in_24h":"3.52","size_precision":5,"price_precision":8},{"name":"DASC-ETH","precision":8,"min_volume":"0.00001","min_price":"0.00000001","volume":"2.16921515","last_price":"0.00009008","change_in_24h":"-9.94","size_precision":5,"price_precision":8},{"name":"DASC-EUR","precision":4,"min_volume":"0.00001","min_price":"0.0001","volume":"2147.0795","last_price":"0.0262","change_in_24h":"5.22","size_precision":5,"price_precision":4},{"name":"NANO-EUR","precision":4,"min_volume":"0.0001","min_price":"0.0001","volume":"0.0","last_price":"1.95","change_in_24h":"0.0","size_precision":4,"price_precision":4},{"name":"BTC-USDT","precision":2,"min_volume":"0.00000001","min_price":"0.01","volume":"0.0","last_price":"6523.02","change_in_24h":"0.0","size_precision":8,"price_precision":2},{"name":"EOS-USDT","precision":2,"min_volume":"0.0001","min_price":"0.01","volume":"0.0","last_price":"4.16","change_in_24h":"0.0","size_precision":4,"price_precision":2},{"name":"DTX-BTC","precision":8,"min_volume":"0.01","min_price":"0.00000001","volume":"0.07493667","last_price":"0.0000031","change_in_24h":"-3.13","size_precision":2,"price_precision":8}]}')
Traceback (most recent call last):
  File "exchange.py", line 109, in <module>
    e.test()
  File "exchange.py", line 18, in test
    print(exchange.fetchTickers())
  File "/home/ec2-user/.local/lib/python2.7/site-packages/ccxt/coinfalcon.py", line 153, in fetch_tickers
    ticker = self.parse_ticker(tickers[i])
  File "/home/ec2-user/.local/lib/python2.7/site-packages/ccxt/coinfalcon.py", line 114, in parse_ticker
    market = self.safe_value(self.markets_by_id, marketId, market)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/ccxt/base/exchange.py", line 517, in safe_value
    return dictionary[key] if key is not None and (key in dictionary) and dictionary[key] is not None else default_value
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kroitor** [comment]
@rhythem got it, i'll check it and will get back to you with a fix for it, shortly.
