### ISSUE TITLE
Coinbasepro request timestamp expired

### ISSUE THREAD

**Issue by IMikhelson** [ccxt/ccxt#3951]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.17.369
- Exchange: Coinbase Pro
- Method: fetch_balance()

When I set the "nonce" property in the client declaration to "ccxt.Exchange.milliseconds" for Coinbase Pro, private calls fail with the error "request timestamp expired".  If I don't set it, everything works fine.  For comparison, this works fine with Binance.  The code and output are pasted below.

Code:
```
import ccxt

key = my_key
sec = my_sec
phrase = my_phrase

exchange_class = getattr(ccxt, 'coinbasepro')
client = exchange_class({
    'apiKey': key,
    'secret': sec,
    'password': phrase,
    'nonce': ccxt.Exchange.milliseconds,
    'enableRateLimit': True,
    'ratelimit': 100,
    'verbose': True
})

client.load_markets()

bal = client.fetch_balance()
```

Output:
```
Request: GET https://api.pro.coinbase.com/accounts {'CB-ACCESS-KEY': 'my_key', 'CB-ACCESS-SIGN': 'not_sure_if_this_is_private_but_removed_just_in_case', 'CB-ACCESS-TIMESTAMP': '1538750877326', 'CB-ACCESS-PASSPHRASE': 'my_phrase', 'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Traceback (most recent call last):
  File "C:\Users\Ilya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 434, in fetch
    response.raise_for_status()
Response: GET https://api.pro.coinbase.com/accounts 400 {'Date': 'Fri, 05 Oct 2018 14:47:57 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '39', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d71eb6cadba4f0079490f50bee6762c631538750877; expires=Sat, 05-Oct-19 14:47:57 GMT; path=/; domain=.pro.coinbase.com; HttpOnly', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'ETag': 'W/"27-5gfaY4hUyUD0vAkskiqW7HlQcrs"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4650afb77f8f9200-EWR'} {"message":"request timestamp expired"}
  File "C:\Users\Ilya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.pro.coinbase.com/accounts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Ilya/Documents/PyCharm Projects/ccxt_issue1.py", line 20, in <module>
    bal = client.fetch_balance()
  File "C:\Users\Ilya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\gdax.py", line 191, in fetch_balance
    balances = self.privateGetAccounts()
  File "C:\Users\Ilya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\gdax.py", line 678, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Ilya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 359, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Ilya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 446, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response)
  File "C:\Users\Ilya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\gdax.py", line 674, in handle_errors
    raise ExchangeError(self.id + ' ' + message)
ccxt.base.errors.ExchangeError: coinbasepro request timestamp expired

Process finished with exit code 1
```

**Comment by TechupBusiness** [comment]
I have the same issue... maybe the nonce control should be implemented for each exchange individually (allowing more than 1 call per sec :-) ).

**Comment by IMikhelson** [comment]
This is not a duplicate (if you are referring to issue #788).  There, the problem was potentially the system clock, and further the user was not using CCXT.  My issue is not with creating a custom nonce, but rather that it would be nice if the same command could translate to all exchanges, or if it didn't, then to include a list of the ones that have to be created manually.

**Comment by TechupBusiness** [comment]
I totally agree with you. But according to https://github.com/ccxt/ccxt/issues/788 seconds should work. I would suggest to mention this issue with some exchanges and milliseconds at least in the docs (there it sounds like milliseconds is the best solution to have more than 1 call per second, for coinbasepro this "rule" doesn't apply - see below).

I couldn't find any information in the docs regarding the nonce except of https://docs.pro.coinbase.com/#selecting-a-timestamp and if you combine the information with https://github.com/coinbase/gdax-node/blob/9a59db269857d10cb449c44cd6a0f51c630abd5c/lib/request_signer.js#L15 its getting obvious that the nonce needs to be a unix timestamp in seconds for gdax/coinbasepro. It doesn't need to be unique. So again: I would suggest to change the wiki regarding the nonce and milliseconds.

**Comment by kroitor** [comment]
@IMikhelson basically, if the exchange does not allow to specify nonce in milliseconds and only accepts seconds – there's little we can do – overriding the nonce "for all exchanges" is discouraged, you only want to override it if/where needed, specifically.

@TechupBusiness thx for answering the issue!
