### ISSUE TITLE
Bitmex 403 error 

### ISSUE THREAD

**Issue by lliypuk** [ccxt/ccxt#3987]
- OS: Ubuntu 16.04
- Programming Language version: PHP 7.2
- CCXT version: 1.14.62
- Exchange: Bitmex
- Method: fetch_balance 

Hi! I have problem with Bitmex, I think, maybe they have made Ban IP address server, becouse when I make request on local machine it's working fine. I wrote to support and they asked me, that a error I get and I don't know, how I can explain situation 

This my code:

`$api_keys['Key']= "***";`
`$api_keys['Secret']="***";`
`$exchange  = new \ccxt\bitmex (array(`
`                                'enableRateLimit'=> true,`
`                                'apiKey' => trim($api_keys['Key']),`
`                                'secret'=>trim($api_keys['Secret']))`
`                                );`
`print_r($exchange->fetch_balance());`
and this that I receive: 

Fatal error: Uncaught ccxt\ExchangeNotAvailable: bitmex GET https://www.bitmex.com/api/v1/instrument/activeAndIndices 403 <html> <head><title>403 Forbidden</title></head> <body bgcolor="white"> <center><h1>403 Forbidden</h1></center> </body> </html> in /var/www/example.com/public_html/vendor/ccxt/ccxt/php/Exchange.php:786 Stack trace: #0 /var/www/example.com/public_html/vendor/ccxt/ccxt/php/Exchange.php(1038): ccxt\Exchange->raise_error('ExchangeNotAvai...', 'https://www.bit...', 'GET', 403, '<html>\r\n<head><...', '(possible reaso...') #1 /var/www/example.com/public_html/vendor/ccxt/ccxt/php/Exchange.php(811): ccxt\Exchange->fetch('https://www.bit...', 'GET', Array, NULL) #2 /var/www/example.com/public_html/vendor/ccxt/ccxt/php/Exchange.php(815): ccxt\Exchange->fetch2('instrument/acti...', 'public', 'GET', Array, NULL, NULL) #3 [internal function]: ccxt\Exchange->request('instrument/acti...', 'public', 'GET', Array) #4 /var/www/example.com/public_html/vendor/ccxt/ccxt/php/Exchange.php(750): call_user_func(Array, ' in /var/www/example.com/public_html/vendor/ccxt/ccxt/php/Exchange.php on line 786

I answered: 403 error, but it not enought... How I can undestand what happening?

**Comment by lliypuk** [comment]
Here is the support answer about error 403:
Yes, however if you implement generic error handling, it will help you understand why you receive this error.
