### ISSUE TITLE
some advice on error handling in JS

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3988]
Could you add some examples to the manual that show how to detect what the cause of an exception is?  

I'm seeing some errors being thrown and in the stack i see things like `[Function: OrderNotFound]` and `[Function: RequestTimeout]`.  It would be nice to be able to trap these in order to respond to them appropriately.  How do you do this in javascript?

**Comment by npomfret** [comment]
@kroitor perfect, thanks

**Comment by npomfret** [comment]
@kroitor FYI using `if (e instanceof ccxt.OrderNotFound)` does not work (at least in node 8).  I had to use `e.constructor.name === 'OrderNotFound'`.

**Comment by kroitor** [comment]
@npomfret that's interesting, https://node.green/ says it should work with node8 as well... because `instanceof` clause is a part of es2015 standard... Will look into it further.

**Comment by npomfret** [comment]
I couldn't understand why it wasn't working, but I'm no JS expert.  I was trying to cancel already closed orders - which I think (according to the code) should result in the OrderNotFound error.  But the catch implemented suggested didn't catch it.

**Comment by kroitor** [comment]
@npomfret can you show a bit more code, plz? I gotta fix it, if it doesn't work, but I need something to work with, initially, for that, we have to ensure no errors on the client-side first.

**Comment by npomfret** [comment]
Some more info:

I'm trying to edit a partially filled order and catching the error with the following code:

```
} catch (e) {
            console.log(`${orderId} cannot be updated: ${e.constructor.name}`, (e instanceof ccxt.OrderNotFound), (e instanceof ccxt.InvalidOrder));
```
The output is this:

`528710636 cannot be updated: ExchangeError false false`

**Comment by kroitor** [comment]
> I think cancelling an already cancelled order isn't an error. But editing a partially filled order results in a 422.

Yeah, but with most other exchanges, canceling an already-closed order is an error, so we throw an exception, but I made it optional for liquid, see `liquid.options['cancelOrderException']`. Also fixed the error handler, so you should see those errors properly handled now. These modifications will be available in 5-10 minutes starting from 1.17.418. Let me know if you still have issues with it after updating.

**Comment by npomfret** [comment]
ok, i'll try it.  Does this also fix the problem that the InvalidOrder is not being thrown when you get a 429 by trying to edit a partially filled order?

**Comment by kroitor** [comment]
> Does this also fix the problem that the InvalidOrder is not being thrown when you get a 429 by trying to edit a partially filled order?

Yep, it does.

**Comment by npomfret** [comment]
@kroitor Some more below data using the new code.  In summary the `instanceof` technique isn't working still (on node v8.11.3).

Editing what I believe is a partially filled order, with the following catch block:

```
        } catch (e) {
            if(e.message.indexOf("Can not update non-live order") >= 0 || e.message.indexOf("Can not update partially filled order")) {
                console.log(`${orderId} cannot be updated: ${e.constructor.name}`, (e instanceof ccxt.OrderNotFound), (e instanceof ccxt.InvalidOrder), (e.message), e);

```

I get this output:

```

529455429 cannot be updated: InvalidOrder false false liquid {"errors":{"order":["Can not update partially filled order"]}} { Error: liquid {"errors":{"order":["Can not update partially filled order"]}}
    at liquid.handleErrors (/Users/nickpomfret/projects/CrypPro-marketdata/gae-services/ticking-orderbook-service/node_modules/ccxt/js/liquid.js:687:31)
    at response.text.then (/Users/nickpomfret/projects/CrypPro-marketdata/gae-services/ticking-orderbook-service/node_modules/ccxt/js/base/Exchange.js:648:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidOrder] }
```

**Comment by kroitor** [comment]
@npomfret also, can you make it a short, but complete snippet (without your keys) ? Need to see the entire code, plz, cut it to 10-20 lines, and post it here plz, so that we could see the instantiation, imports, all that... in other words, something like that:

```
'use strict';

const ccxt = require ('ccxt')
const exchange = new ccxt.liquid({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': true, // required according to the Manual
})

;(async () => {
    await exchange.loadMarkets()
    const filledOrderId = '529455429'
    const symbol = 'ETH/BTC'
    const amount = 1 // ←-- CHANGE FOR YOUR VALUE
    const price = 0.031 // ←-- CHANGE FOR YOUR VALUE
    const type = 'limit'
    const side = 'sell' // ←-- CHANGE FOR YOUR VALUE
    try {
        const response = await exchange.editOrder(id, symbol, type, side, amount, price);
    } catch (e) {
        console.log ({
            'e.constructor.name': e.constructor.name,
            'is ExchangeError': e instanceof ccxt.ExchangeError, 
            'is NetworkError': e instanceof ccxt.NetworkError,
            'is InvalidOrder': e instanceof ccxt.InvalidOrder,
            'exception itself': e,
        })
    }
}) ()

**Comment by npomfret** [comment]
Looks good now. Using your code above with the latest ccxt code:

```
{ 'e.constructor.name': 'InvalidOrder',
  'is ExchangeError': true,
  'is NetworkError': false,
  'is InvalidOrder': true,
  'exception itself': { Error: liquid {"errors":{"order":["Can not update partially filled order","Can not update non-live order"]}}
    at liquid.handleErrors (/Users/crypro/projects/CrypPro-marketdata/exchange-connectivity/node_modules/ccxt/js/liquid.js:687:31)
    at response.text.then (/Users/crypro/projects/CrypPro-marketdata/exchange-connectivity/node_modules/ccxt/js/base/Exchange.js:648:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidOrder] } }

```

**Comment by npomfret** [comment]
What's harder to test is editing an open order that's partially filled.  If it happens ill do my best to capture the output.

**Comment by npomfret** [comment]
Ok, my system tried to edit a partially filled order just now.  I had your logging in place:
```
{ orderId: '536076653',
  'e.constructor.name': 'InvalidOrder',
  'is ExchangeError': false,
  'is NetworkError': false,
  'is InvalidOrder': false,
  'exception itself': { Error: liquid {"errors":{"order":["Can not update partially filled order"]}}
    at liquid.handleErrors (/Users/nickpomfret/projects/CrypPro-marketdata/gae-services/ticking-orderbook-service/node_modules/ccxt/js/liquid.js:687:31)
    at response.text.then (/Users/nickpomfret/projects/CrypPro-marketdata/gae-services/ticking-orderbook-service/node_modules/ccxt/js/base/Exchange.js:648:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidOrder] } }
```

**Comment by kroitor** [comment]
@npomfret That doesn't seem to be an issue with the handler though... We will need to see your imports for ccxt and need to see your actual runtime version of ccxt as well:

```
const ccxt = require ('ccxt')
console.log (ccxt.version)
```

Basically, at this point, the method for debugging such a case is to start stripping parts of code from your system until you're left with just 10-20 lines that reproduce the issue in essence, we need the bug to manifest itself somehow.

**Comment by kroitor** [comment]
@npomfret just in case, adding these lines before the call to `editOrder` might help figure this out or shed some light on this at the very least:

```JavaScript

       // -------------------------------------------------------
       // ADD THESE LINES ↓

       const { InvalidOrder } = require ('ccxt')

       console.log ({
            'InvalidOrder class reference': ccxt.InvalidOrder,
            'ccxt version': ccxt.version,
            'InvalidOrder': InvalidOrder,
            "require ('ccxt').InvalidOrder": (require ('ccxt')).InvalidOrder,
            "require ('ccxt').version": (require ('ccxt')).version,
       })

       // ↑ ADD THESE LINES
       // -------------------------------------------------------
        
        const response = await exchange.editOrder(id, symbol, type, side, amount, price)
```
