### ISSUE TITLE
Base field doesn't match with baseid

### ISSUE THREAD

**Issue by kosmodromov** [ccxt/ccxt#3990]
- OS: MacOS 10.13
- Programming Language version: Python 3.6.4
- CCXT version: 1.17.379
- Exchange: Yobit
- Method: fetch_markets()

fetch_market returns incorrect base field for PUTIN coin :)

```
{
    'id': 'putin_btc',
    'symbol': 'PUT/BTC',
    'base': 'PUT',
    'quote': 'BTC',
    'baseId': 'putin',
    'quoteId': 'btc',
    'active': True,
    'taker': 0.002,
    'precision': {
        'amount': 8,
        'price': 8
    },
    'limits': {
        'amount': {
            'min': 0.0001,
            'max': None
        },
        'price': {
            'min': 1e-08,
            'max': 10000.0
        },
        'cost': {
            'min': 0.0001
        }
    },
    'info': {
        'decimal_places': 8,
        'min_price': 1e-08,
        'max_price': 10000,
        'min_amount': 0.0001,
        'min_total': 0.0001,
        'hidden': 0,
        'fee': 0.2,
        'fee_buyer': 0.2,
        'fee_seller': 0.2
    }
}
```

However fetch_ticker returns correct value

```
ccxt.yobit().fetch_ticker('PUTIN/BTC')

{'ask': 1.35e-06,
 'average': 1.42e-06,
 'baseVolume': 225502.3743145,
 'bid': 1.3e-06,
 'change': None,
 'close': None,
 'datetime': '2018-10-13T19:18:30.000Z',
 'first': None,
 'high': 1.58e-06,
 'info': {'avg': 1.42e-06,
  'buy': 1.3e-06,
  'high': 1.58e-06,
  'last': 1.35e-06,
  'low': 1.27e-06,
  'sell': 1.35e-06,
  'updated': 1539458310,
  'vol': 0.30774271,
  'vol_cur': 225502.3743145},
 'last': 1.35e-06,
 'low': 1.27e-06,
 'open': None,
 'percentage': None,
 'quoteVolume': 0.30774271,
 'symbol': 'PUTIN/BTC',
 'timestamp': 1539458310000,
 'vwap': None}
```

**Comment by kroitor** [comment]
PutinCoin's "official" token symbol is `PUT`, according to CoinMarketCap: https://coinmarketcap.com/currencies/putincoin/ and the Manual: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency

So, we use PUT everywhere, and if you attempt to fetch PUTIN/BTC ticker from yobit it should complain with an error:

```Python
mbp:ccxt igorkroitor$ python examples/py/cli.py yobit fetch_ticker PUTIN/BTC
Traceback (most recent call last):
  File "examples/py/cli.py", line 124, in <module>
    result = method(*args)
  File "/Users/igorkroitor/ccxt/python/ccxt/liqui.py", line 329, in fetch_ticker
    tickers = self.fetch_tickers([symbol], params)
  File "/Users/igorkroitor/ccxt/python/ccxt/liqui.py", line 310, in fetch_tickers
    ids = self.market_ids(symbols)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 1410, in market_ids
    return [self.market_id(symbol) for symbol in symbols]
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 1413, in market_id
    market = self.market(symbol)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 1407, in market
    self.raise_error(ExchangeError, details='No market symbol ' + str(symbol))
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 344, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: yobit No market symbol PUTIN/BTC
```

If, however, you use `PUT/BTC`, then it's all fine and consistent:

```
mbp:ccxt igorkroitor$ python examples/py/cli.py yobit fetch_ticker PUT/BTC
{'ask': 1.29e-06,
 'askVolume': None,
 'average': 1.27e-06,
 'baseVolume': 21209.87490056,
 'bid': 1.26e-06,
 'bidVolume': None,
 'change': None,
 'close': 1.29e-06,
 'datetime': '2018-10-27T19:24:02.000Z',
 'high': 1.3e-06,
 'info': {u'avg': 1.27e-06,
          u'buy': 1.26e-06,
          u'high': 1.3e-06,
          u'last': 1.29e-06,
          u'low': 1.25e-06,
          u'sell': 1.29e-06,
          u'updated': 1540668242,
          u'vol': 0.02679539,
          u'vol_cur': 21209.87490056},
 'last': 1.29e-06,
 'low': 1.25e-06,
 'open': None,
 'percentage': None,
 'previousClose': None,
 'quoteVolume': 0.02679539,
 'symbol': u'PUT/BTC',
 'timestamp': 1540668242000,
 'vwap': None}
mbp:ccxt igorkroitor$
```

The above behaviour is correct, and you should get an error with `PUTIN/BTC` from yobit as well. If you don't have that error, make sure your version of CCXT is up to date (not by checking your pip list, but by actually running the following snippet of code in your actual python interpreter that you use for ccxt code):

```Python
import ccxt
print(ccxt.__version__)
```

Related: 

- https://github.com/ccxt/ccxt/issues/3163
- https://github.com/ccxt/ccxt/issues/2604
- https://github.com/ccxt/ccxt/search?q=putincoin&type=Issues

Let us know if the above does not answer your question.
