### ISSUE TITLE
ACX privateGetOrders method in Python

### ISSUE THREAD

**Issue by stevexiong77** [ccxt/ccxt#4069]
OS: Windows 10 pro 64bit
Programming Language version: Python v3.7
CCXT version: 1.17.436
Exchange: ACX
Method: privateGetOrders

Having trouble to use the privateGetOrders method.

import ccxt

exchange = ccxt.acx ({
'enableRateLimit': True,
'apiKey': '[API key]',
'secret': '[Secret key]',
})

orders = exchange.privateGetOrders()
print(orders)

**Get the following error:**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "CCXT_ACX_Test.py", line 115, in 
orders = exchange.privateGetOrders()
File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 362, in request
return self.fetch2(path, api, method, params, headers, body)
File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 359, in fetch2
return self.fetch(request['url'], request['method'], request['headers'], request['body'])
File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 447, in fetch
self.handle_rest_errors(e, response.status_code, http_response, url, method)
File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 469, in handle_rest_errors
self.raise_error(error, url, method, exception if exception else http_status_code, response)
File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 344, in raise_error
raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: acx https://acx.io/api/api/v2/orders.json?access_key=[]&tonce=1540962516822&signature=[] GET 400 Client Error: Bad Request for url: https://acx.io/api/api/v2/orders.json?access_key=[]&tonce=1540962516822&signature=[] {"error":{"code":1001,"message":"market is missing, market does not have a valid value"}}

Also, tried the following code:

import ccxt

exchange = ccxt.acx ({
'enableRateLimit': True,
'apiKey': '[API key]',
'secret': '[Secret key]',
})

symbol = 'BTC/AUD'
orders = exchange.privateGetOrders(symbol)
print(orders)

**Get the following error:**

Traceback (most recent call last):
File "CCXT_ACX_Test.py", line 115, in 
orders = exchange.privateGetOrders(symbol)
File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 362, in request
return self.fetch2(path, api, method, params, headers, body)
File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 358, in fetch2
request = self.sign(path, api, method, params, headers, body)
File "C:\Program Files\Python37\lib\site-packages\ccxt\acx.py", line 373, in sign
request = '/api' + '/' + self.version + '/' + self.implode_params(path, params)
File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 667, in implode_params
string = string.replace('{' + key + '}', str(params[key]))
TypeError: string indices must be integers

**Comment by kroitor** [comment]
Answered and explained here: https://github.com/ccxt/ccxt/issues/4068#issuecomment-434565157
