### ISSUE TITLE
Hitbtc Fetch Trades (List Index out of Range) 

### ISSUE THREAD

**Issue by araa47** [ccxt/ccxt#4079]
- OS: MacOs Mojave
- Programming Language version: python 3.6.4
- CCXT version: 1.17.444 
- Exchange: hitbtc
- Method: fetch_trades()

Code

```
import ccxt 
hitbtc = ccxt.hitbtc()
hitbtc.fetch_trades('BTC/USDT')
```

Exception

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/akshay/.local/share/virtualenvs/market-data-FSV7ciM8/lib/python3.6/site-packages/ccxt/hitbtc.py", line 713, in fetch_trades
    return self.parse_trades(response['trades'], market, since, limit)
  File "/Users/akshay/.local/share/virtualenvs/market-data-FSV7ciM8/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1313, in parse_trades
    array = [self.parse_trade(trade, market) for trade in array]
  File "/Users/akshay/.local/share/virtualenvs/market-data-FSV7ciM8/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1313, in <listcomp>
    array = [self.parse_trade(trade, market) for trade in array]
  File "/Users/akshay/.local/share/virtualenvs/market-data-FSV7ciM8/lib/python3.6/site-packages/ccxt/hitbtc.py", line 639, in parse_trade
    return self.parse_public_trade(trade, market)
  File "/Users/akshay/.local/share/virtualenvs/market-data-FSV7ciM8/lib/python3.6/site-packages/ccxt/hitbtc.py", line 653, in parse_public_trade
    'side': trade[4],
IndexError: list index out of range

```

**Comment by kroitor** [comment]
The reported issue is fixed as of version 1.17.445. Please, update your CCXT and retry (the new build will be available for downloading in 10-15 minutes).

Please, note, however, their v1 api is deprecated, use `hitbtc2` instead:

```Python
# change this
hitbtc = ccxt.hitbtc()
# to this
hitbtc = ccxt.hitbtc2()
```

Hope this answers your question.

**Comment by araa47** [comment]
Thanks for the instant fix @kroitor , my boss Evgeni says if you are ever in Hong Kong he will take you out for drinks

**Comment by kroitor** [comment]
@araa47 that's awesome! Please let Evgeni know if he is ever in Moscow we'd take him out as well, but better stay inside during the winter here ))) We don't really drink a lot, despite the stereotypes, but we're still friendly and open ) Cheers!
