### ISSUE TITLE
Kraken has wrong base for Tezos in loadMarkets: TZ instead of XTZ

### ISSUE THREAD

**Issue by fonzmeister** [ccxt/ccxt#4080]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows
- Programming Language version: python 3.4
- CCXT version: 1.17.445
- Exchange: kraken
- Method: Loadmarkets

``` 
k = ccxt.kraken()
x = k.loadMarkets()
```
x['XTZ/BTC'] gives keyerror

x['TZ/BTC'] works gives output:
```
{'fee_loaded': False,
 'percentage': True,
 'tierBased': True,
 'taker': 0.0026,
 'maker': 0.0016,
 'tiers': {'taker': [[0, 0.0026],
   [50000, 0.0024],
   [100000, 0.0022],
   [250000, 0.002],
   [500000, 0.0018],
   [1000000, 0.0016],
   [2500000, 0.0014],
   [5000000, 0.0012],
   [10000000, 0.0001]],
  'maker': [[0, 0.0016],
   [50000, 0.0014],
   [100000, 0.0012],
   [250000, 0.001],
   [500000, 0.0008],
   [1000000, 0.0006],
   [2500000, 0.0004],
   [5000000, 0.0002],
   [10000000, 0.0]]},
 'precision': {'amount': 8, 'price': 7},
 'limits': {'amount': {'min': 1e-08, 'max': 100000000.0},
  'price': {'min': 1e-07, 'max': None},
  'cost': {'min': 0, 'max': None}},
 'id': 'XTZXBT',
 'symbol': 'TZ/BTC',
 'base': 'TZ',
 'quote': 'BTC',
 'baseId': 'XTZ',
 'quoteId': 'XXBT',
 'darkpool': False,
 'info': {'altname': 'XTZXBT',
  'aclass_base': 'currency',
  'base': 'XTZ',
  'aclass_quote': 'currency',
  'quote': 'XXBT',
  'lot': 'unit',
  'pair_decimals': 7,
  'lot_decimals': 8,
  'lot_multiplier': 1,
  'leverage_buy': [],
  'leverage_sell': [],
  'fees': [[0, 0.26],
   [50000, 0.24],
   [100000, 0.22],
   [250000, 0.2],
   [500000, 0.18],
   [1000000, 0.16],
   [2500000, 0.14],
   [5000000, 0.12],
   [10000000, 0.1]],
  'fees_maker': [[0, 0.16],
   [50000, 0.14],
   [100000, 0.12],
   [250000, 0.1],
   [500000, 0.08],
   [1000000, 0.06],
   [2500000, 0.04],
   [5000000, 0.02],
   [10000000, 0]],
  'fee_volume_currency': 'ZUSD',
  'margin_call': 80,
  'margin_stop': 40},
 'altname': 'XTZXBT',
 'active': True}
```

**Comment by fonzmeister** [comment]
I think this fix broke the function. I now get the following output

```
Traceback (most recent call last):

  File "<ipython-input-6-2ea762f4145b>", line 1, in <module>
    kraken.loadMarkets()

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1019, in load_markets
    markets = self.fetch_markets()

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\kraken.py", line 273, in fetch_markets
    if len((base) > 3) and((base[0] == 'X') or (base[0] == 'Z')):

TypeError: '>' not supported between instances of 'str' and 'int'
```


and verbose output

```
Response: GET https://support.kraken.com/hc/en-us/articles//205893708-What-is-the-minimum-order-size- 200 {'Date': 'Thu, 01 Nov 2018 11:53:55 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d353a7cc39d16ea6419b2825c69fcd3441541073235; expires=Fri, 01-Nov-19 11:53:55 GMT; path=/; domain=.support.kraken.com; HttpOnly, __cfruid=1487747139c04f8116068858230d556c07e80745-1541073235; path=/; domain=.support.kraken.com; HttpOnly', 'Status': '200 OK', 'X-UA-Compatible': 'IE=edge', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'ETag': 'W/"8b9e103bd47405d115d733056243c28e"', 'Cache-Control': 'max-age=0, public, s-maxage=180, stale-while-revalidate=60, stale-if-error=10800', 'Strict-Transport-Security': 'max-age=31536000;', 'X-Zendesk-User-Id': '', 'X-Zendesk-Origin-Server': 'hcapp6.pod8.sac1.zdsys.com', 'X-Request-Id': '471ef3843e09a423-SJC', 'X-Runtime': '0.204454', 'X-Content-Type-Options': 'nosniff', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'HIT', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '472e29e7db8e2bdc-AMS'} <!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta charset="utf-8" />
  <!-- v14891 -->

  <title>What is the minimum order size (volume)? &ndash; Kraken</title>

  <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="BcVMEZT+mgFU14KVDTD9rpPk/daaCG1S8wyMsgQsRo90dOYILgV7GfTg7lnED3EObaF+VdnjqpHmAWsjPay1cg==" />
  <meta name="description" content="The minimum order size goes by base currency. The base currency is the left currency in each pair. For example, XBT is the base currency..." /><meta property="og:image" content="https://theme.zdassets.com/theme_assets/371365/59181d0643a1d76edd2a160225a584fa5556bcbc.png" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="Kraken" />
<meta property="og:title" content="What is the minimum order size (volume)?" />
<meta property="og:description" content="The minimum order size goes by base currency. The base currency is the left currency in each pair. For example, XBT is the base currency in the pair XBT/USD. 
For more details, see the Price &amp; ..." />
<meta property="og:url" content="http://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-volume-" />
<link rel="canonical" href="https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-volume-" />
<link rel="alternate" hreflang="en" href="https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-volume-" />
<link rel="alternate" hreflang="ja" href="https://support.kraken.com/hc/ja/articles/205893708-%E6%9C%80%E5%B0%8F%E6%B3%A8%E6%96%87%E3%82%B5%E3%82%A4%E3%82%BA" />

  <!-- Entypo pictograms by Daniel Bruce — www.entypo.com -->
  <link rel="stylesheet" media="all" href="//static.zdassets.com/hc/assets/application-6229f1ebd2f90b23df13e8c12bfd8ab1.css" id="stylesheet" />
  <link rel="stylesheet" type="text/css" href="//p8.zdassets.com/hc/theming_assets/371365/1186036/style.css?digest=360019983886" />

  <link rel="shortcut icon" type="image/x-icon" href="//theme.zdassets.com/theme_assets/371365/dc97eae99ecd8de3210177ecd147e20c87448df5.ico" />

  <!--[if lt IE 9]>
  <script>
    //Enable HTML5 elements for <IE9
    'abbr article aside audio bdi canvas data datalist details dialog \
    figcaption figure footer header hgroup main mark meter nav output \
    progress section summary template time video'.replace(/\w+/g,function(n){document.createElement(n)});
  </script>
<![endif]-->

  <script src="//static.zdassets.com/hc/assets/jquery-b60ddb79ff2563b75442a6bac88b00b5.js"></script>
  <script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-45972273-3', 'auto');
ga('send', 'pageview');

</script>

  <script type="text/javascript">
  window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
  d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
  _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
  $.src='//v2.zopim.com/?2Cr1LVznA1q7hHP3ZJSLM7Sih5xNC0LD';z.t=+new Date;$.
  type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>

  

  <meta name="google-site-verification" content="8o-3QSEtDBW4rSx-w6MHnVw7zPmnuaMVs669P7tIARM" />
<meta property="og:image" content="https://theme.zdassets.com/theme_assets/371365/80c7ddc9273ddbb67adc3f53d4f62266854a8f94.png">
<script src="https://assets.zendesk.com/assets/apps/conditional_fields/latest/helpcenter.js"></script>
<script>var cfaRules = [{"fieldType":"tagger","field":23673033,"value":"other","select":[360000024646,81556808,81556748,81162747,81162727,360000062563],"formId":360000007643,"requireds":[81162727,81162747,81556748,81556808,360000024646,360000062563]},{"fieldType":"tagger","field":360000062563,"value":"no_access","select":[360000061006,360000062583,360000062603],"formId":360000007643,"requireds":[360000061006,360000062583,360000062603]},{"fieldType":"tagger","field":360000062563,"value":"yes_access","select":[360000061026,360000061006,360000062603,360000062583],"formId":360000007643,"requireds":[360000061006,360000061026,360000062583,360000062603]},{"fieldType":"tagger","field":81084087,"value":"1248_bank","select":[81084047],"formId":859607,"requireds":[81084047]},{"fieldType":"tagger","field":81084147,"value":"304","select":[360000003246],"formId":859607,"requireds":[360000003246]},{"fieldType":"tagger","field":81094987,"value":"1963","select":[81475708],"formId":859607,"requireds":[81475708]},{"fieldType":"tagger","field":81162747,"value":"business_account","select":[81111787,81111807,81111927,81111967,81112027,81112107,81112087,81112127,81112147,81112167,81112227,81112267,81112347,81112367,81112387,81112427,81507368,81507388,81507468,81507548,81507508,81507568,81507748,81507768,81507788,81507828,81507848,81507868,81508028,81508068,81508108,81508188,81508208,81508048,81084107,81084127,81084087,81094987,81084027,81084067,81475668],"formId":859607,"requireds":[81084067,81084087,81084107,81084127,81094987,81111787,81111807,81111927,81111967,81112027,81112087,81112167,81112227,81112267,81112347,81112367,81112387,81112427,81507368,81507388,81507468,81507508,81507548,81507568,81507748,81507768,81507788,81507848,81507868,81508028,81508048,81508068,81508108,81508188,81508208]},{"fieldType":"tagger","field":81162747,"value":"business_account","select":[81112167,81162967,81508108,81508188,81556768,81556828],"formId":360000007643,"requireds":[81112167,81162967,81508108,81508188,81556768,81556828]},{"fieldType":"tagger","field":81162747,"value":"business_account","select":[81112167,81508108,81508188,81556828,81162967,81556768],"formId":979988,"requireds":[81112167,81162967,81508108,81508188,81556828]},{"fieldType":"tagger","field":81162747,"value":"individual_account","select":[81084807,81084827,81094987,81084027,81084087,81084107,81084127,81084147,81084587,81475688,81475668,81475728,81475748,81476428,81476448,81476468,81084067],"formId":859607,"requireds":[81084067,81084087,81084107,81084127,81084147,81084807,81084827,81094987,81475688,81475728,81475748]},{"fieldType":"tagger","field":81162747,"value":"individual_account","select":[81111787,81112367,81112427,81162967,81556768,81556828],"formId":360000007643,"requireds":[81111787,81112367,81112427,81162967,81556768,81556828]},{"fieldType":"tagger","field":81162747,"value":"individual_account","select":[81111787,81112427,81162967,81556768,81556828,360000066166],"formId":979988,"requireds":[81111787,81112427,81162967,81556768,81556828,360000066166]},{"fieldType":"tagger","field":81162767,"value":"yes_t3","select":[81162787,81162947,81556788,360000017586],"formId":360000007643,"requireds":[81162787,81162947,81556788,360000017586]},{"fieldType":"tagger","field":81162767,"value":"yes_t3","select":[360000017586,81556788,81162947,81162787],"formId":979988,"requireds":[81162787,81162947,81556788,360000017586]},{"fieldType":"tagger","field":81507508,"value":"yes_2nd_accessor","select":[81507408,81507588,81507608,81507628,81507688,81508168,81508128,81508088,81112327,81111867,81111827,81507488,81507528],"formId":859607,"requireds":[81111827,81111867,81112327,81507408,81507488,81507528,81507588,81507608,81507628,81507688,81508088,81508128,81508168]},{"fieldType":"tagger","field":81507528,"value":"yes_3rd_accessor","select":[81111847,81111887,81111907,81111947,81112047,81112287,81112307,81112407,81507428,81507448,81507648,81508148],"formId":859607,"requireds":[81111847,81111887,81111907,81111947,81112047,81112287,81112307,81112407,81507428,81507448,81507648,81508148]},{"fieldType":"tagger","field":81556768,"value":"yes_t2","select":[81162987,81162767,81111927,81556888,81556908],"formId":360000007643,"requireds":[81111927,81162767,81162987,81556888,81556908]},{"fieldType":"tagger","field":81556768,"value":"yes_t2","select":[81556888,81556908,81162987,81162767,81111927],"formId":979988,"requireds":[81111927,81162767,81162987,81556888,81556908]}];</script>
  <script type="text/javascript" src="//p8.zdassets.com/hc/theming_assets/371365/1186036/script.js?digest=360019983886"></script>
</head>
<body class="">
  
  


  


  <header class="header">
  <div class="header-inner">
    <div class="logo"><a title="Home" href="/hc/en-us">
      <img src="//theme.zdassets.com/theme_assets/371365/59181d0643a1d76edd2a160225a584fa5556bcbc.png" alt="Logo">
    </a></div>
    <nav class="user-nav">
      
        <div class="dropdown language-selector" aria-haspopup="true">
          <a class="dropdown-toggle">
            English (US)
          </a>
          <span class="dropdown-menu dropdown-menu-end" role="menu">
            
              <a href="/hc/change_language/ja?return_to=%2Fhc%2Fja%2Farticles%2F205893708-%25E6%259C%2580%25E5%25B0%258F%25E6%25B3%25A8%25E6%2596%2587%25E3%2582%25B5%25E3%2582%25A4%25E3%2582%25BA" dir="ltr" rel="nofollow" role="menuitem">
                日本語
              </a>
            
          </span>
        </div>
      
      <a class="submit-a-request" href="/hc/en-us/requests/new">Submit a request</a>
        <a class="login" data-auth-action="signin" role="button" href="/hc/en-us/signin?return_to=https%3A%2F%2Fsupport.kraken.com%2Fhc%2Fen-us%2Farticles%2F205893708-What-is-the-minimum-order-size-&amp;locale=1">Sign in</a>

    </nav>
  </div>
</header>

  <main role="main">
    <nav class="sub-nav">
  <ol class="breadcrumbs">
  
    <li title="Kraken">
      
        <a href="/hc/en-us">Kraken</a>
      
    </li>
  
    <li title="Trading">
      
        <a href="/hc/en-us/categories/200187143-Trading">Trading</a>
      
    </li>
  
    <li title="Trading: Basics">
      
        <a href="/hc/en-us/sections/200331493-Trading-Basics">Trading: Basics</a>
      
    </li>
  
</ol>

  <form role="search" class="search" data-search="" action="/hc/en-us/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" /><input type="search" name="query" id="query" placeholder="Search" aria-label="Search" />
<input type="submit" name="commit" value="Search" /></form>
</nav>

<article class="main-column">

  <header class="article-header">
    <h1> What is the minimum order size (volume)?</h1>
  </header>

  <div class="article-body">
    <p>The minimum order size goes by <strong>base currency</strong>. The base currency is the left currency in each pair. <em>For example, XBT is the base currency in the pair XBT/USD. </em></p>
<p>For more details, see the <a href="https://support.kraken.com/hc/en-us/articles/360001389366-Price-and-volume-decimal-precision">Price &amp; Volume Decimal Precision</a> article.</p>
<table>
<tbody>
<tr>
<td><strong>Base currency</strong></td>
<td class="wysiwyg-text-align-right"><strong>Order minimum</strong></td>
</tr>
<tr>
<td>Augur</td>
<td class="wysiwyg-text-align-right">0.3 REP</td>
</tr>
<tr>
<td>Bitcoin</td>
<td class="wysiwyg-text-align-right">0.002 XBT</td>
</tr>
<tr>
<td>Bitcoin Cash</td>
<td class="wysiwyg-text-align-right">0.002 BCH</td>
</tr>
<tr>
<td>Cardano</td>
<td class="wysiwyg-text-align-right">1 ADA</td>
</tr>
<tr>
<td>Dash</td>
<td class="wysiwyg-text-align-right">0.03 DASH</td>
</tr>
<tr>
<td>Dogecoin</td>
<td class="wysiwyg-text-align-right">3000 XDG</td>
</tr>
<tr>
<td>EOS</td>
<td class="wysiwyg-text-align-right">3 EOS</td>
</tr>
<tr>
<td>Ethereum</td>
<td class="wysiwyg-text-align-right">0.02 ETH</td>
</tr>
<tr>
<td>Ethereum Classic</td>
<td class="wysiwyg-text-align-right">0.3 ETC</td>
</tr>
<tr>
<td>Gnosis</td>
<td class="wysiwyg-text-align-right">0.03 GNO</td>
</tr>
<tr>
<td>Iconomi</td>
<td class="wysiwyg-text-align-right">2 ICN</td>
</tr>
<tr>
<td>Litecoin</td>
<td class="wysiwyg-text-align-right">0.1 LTC</td>
</tr>
<tr>
<td>Melon</td>
<td class="wysiwyg-text-align-right">0.1 MLN</td>
</tr>
<tr>
<td>Monero</td>
<td class="wysiwyg-text-align-right">0.1 XMR</td>
</tr>
<tr>
<td>Quantum</td>
<td class="wysiwyg-text-align-right">0.1 QTUM</td>
</tr>
<tr>
<td>Ripple</td>
<td class="wysiwyg-text-align-right">30 XRP</td>
</tr>
<tr>
<td>Stellar Lumens</td>
<td class="wysiwyg-text-align-right">30 XLM</td>
</tr>
<tr>
<td>Tether</td>
<td class="wysiwyg-text-align-right">5 USDT</td>
</tr>
<tr>
<td>Tezos</td>
<td class="wysiwyg-text-align-right">1 XTZ</td>
</tr>
<tr>
<td>Zcash</td>
<td class="wysiwyg-text-align-right">0.03 ZEC</td>
</tr>
</tbody>
</table>
<p> </p>
<p><strong>Examples</strong></p>
<p><em>If you are trading XBT, the volume of the order must be at least 0.002 XBT or larger. </em></p>
<p><em>If you are trading ETH, the volume of the order must be at least 0.02 ETH or larger. </em></p>
  </div>
  
<section class="article-comments">
    
    
    
  </section>
  
</article>

<aside class="article-sidebar side-column">
  <div data-recent-articles></div>
  
  <section class="related-articles">
    <h3>Related articles</h3>
    <ul>
      
        <li>
          <a href="/hc/en-us/related/click?data=BAh7CjobZGVzdGluYXRpb25fYXJ0aWNsZV9pZGkE6KYIDDoYcmVmZXJyZXJfYXJ0aWNsZV9pZGkETLBFDDoLbG9jYWxlSSIKZW4tdXMGOgZFVDoIdXJsSSJPL2hjL2VuLXVzL2FydGljbGVzLzIwMTg5MzYwOC1EaWdpdGFsLWFzc2V0cy1jcnlwdG9jdXJyZW5jeS13aXRoZHJhd2FsLWZlZXMGOwhUOglyYW5raQY%3D--04f20ab3201cc8550e309d9332318bc9906c1d4c">Digital assets/cryptocurrency withdrawal fees</a>
        </li>
      
        <li>
          <a href="/hc/en-us/related/click?data=BAh7CjobZGVzdGluYXRpb25fYXJ0aWNsZV9pZGkEA7t4DDoYcmVmZXJyZXJfYXJ0aWNsZV9pZGkETLBFDDoLbG9jYWxlSSIKZW4tdXMGOgZFVDoIdXJsSSI2L2hjL2VuLXVzL2FydGljbGVzLzIwOTIzODc4Ny1NYXJnaW4tYm9ycm93LWxpbWl0cwY7CFQ6CXJhbmtpBw%3D%3D--633257b55f5a0d9ee9a53569a2171881e83a7571">Margin borrow limits</a>
        </li>
      
        <li>
          <a href="/hc/en-us/related/click?data=BAh7CjobZGVzdGluYXRpb25fYXJ0aWNsZV9pZGkEY38eDDoYcmVmZXJyZXJfYXJ0aWNsZV9pZGkETLBFDDoLbG9jYWxlSSIKZW4tdXMGOgZFVDoIdXJsSSJaL2hjL2VuLXVzL2FydGljbGVzLzIwMzMyNTI4My1Ib3ctbG9uZy1kby1kaWdpdGFsLWFzc2V0cy1jcnlwdG9jdXJyZW5jeS1kZXBvc2l0cy10YWtlLQY7CFQ6CXJhbmtpCA%3D%3D--ed3c13a50f221961e3155fa952842ddc4d0ea88b">How long do digital assets/cryptocurrency deposits take?</a>
        </li>
      
        <li>
          <a href="/hc/en-us/related/click?data=BAh7CjobZGVzdGluYXRpb25fYXJ0aWNsZV9pZGkEVrkJDToYcmVmZXJyZXJfYXJ0aWNsZV9pZGkETLBFDDoLbG9jYWxlSSIKZW4tdXMGOgZFVDoIdXJsSSJRL2hjL2VuLXVzL2FydGljbGVzLzIxODc0MTA3OC1XaGF0LWlzLXNldHRsaW5nLWEtcG9zaXRpb24tYW5kLWhvdy1kby1JLWRvLWl0LQY7CFQ6CXJhbmtpCQ%3D%3D--313da8a2bebbb53ea21eac379aa550b35851f634">What is settling a position and how do I do it?</a>
        </li>
      
        <li>
          <a href="/hc/en-us/related/click?data=BAh7CjobZGVzdGluYXRpb25fYXJ0aWNsZV9pZGkEAB%2BVDToYcmVmZXJyZXJfYXJ0aWNsZV9pZGkETLBFDDoLbG9jYWxlSSIKZW4tdXMGOgZFVDoIdXJsSSJNL2hjL2VuLXVzL2FydGljbGVzLzIyNzg3NjYwOC1XaGljaC1jdXJyZW5jeS1wYWlycy1jYW4tSS10cmFkZS1vbi1tYXJnaW4tBjsIVDoJcmFua2kK--4b92e0fd96732c04213c496e350256b32238ca85">Which currency pairs can I trade on margin?</a>
        </li>
      
    </ul>
  </section>


</aside>
  </main>

  <footer class="footer">
  <div class="footer-inner">
    <!-- Footer content -->
  </div>
</footer>


  <!-- / -->

  <script type="text/javascript" src="//static.zdassets.com/hc/assets/locales/en-us-3d4abef49badc2dd07cfd08d524a66c3.js"></script>
  <script src="https://kraken.zendesk.com/auth/v2/host.js" data-brand-id="1186036" data-return-to="https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-" data-theme="hc" data-locale="1" data-auth-origin="1186036,true,true"></script>
  <script type="text/javascript" src="https://p8.zdassets.com/assets/zendesk_pci_hc.v4.js"></script>

  <script type="text/javascript">
  /*

    Greetings sourcecode lurker!

    This is for internal Zendesk and legacy usage,
    we don't support or guarantee any of these values
    so please don't build stuff on top of them.

  */

  HelpCenter = {};
  HelpCenter.account = {"subdomain":"kraken","environment":"production","name":"Kraken Support"};
  HelpCenter.user = {"identifier":"da39a3ee5e6b4b0d3255bfef95601890afd80709","email":null,"name":null,"role":"anonymous","avatar_url":"https://assets.zendesk.com/hc/assets/default_avatar.png","is_admin":false,"organizations":[],"groups":[]};
  HelpCenter.internal = {"asset_url":"//static.zdassets.com/hc/assets/","web_widget_asset_composer_url":"https://static.zdassets.com/ekr/snippet.js","current_session":{"locale":"en-us","csrf_token":"Kl77Pj2ROqhLXbV2l6+vI5YrB26cZLF6EeESUtRKmFBb71Enh2rbsOtq2bpekCODaG6E7d+PdrkE7PXD7cprrQ==","shared_csrf_token":null},"settings":{"zopim_enabled":true,"spam_filter_enabled":false},"current_record_id":"205893708","current_record_url":"/hc/en-us/articles/205893708-What-is-the-minimum-order-size-volume-","current_record_title":"What is the minimum order size (volume)?","search_results_count":null,"current_text_direction":"ltr","current_brand_url":"https://kraken.zendesk.com","current_host_mapping":"support.kraken.com","current_path":"/hc/en-us/articles/205893708-What-is-the-minimum-order-size-volume-","authentication_domain":"https://kraken.zendesk.com","show_autocomplete_breadcrumbs":true,"rollbar_config":null,"user_info_changing_enabled":false,"has_user_profiles_enabled":false,"has_anonymous_kb_voting":false,"has_professional_upsell":false,"has_multi_language_help_center":true,"mobile_device":false,"mobile_site_enabled":false,"show_at_mentions":false,"has_copied_content":false,"embeddables_config":{"embeddables_web_widget":false,"embeddables_connect_ipms":false},"base_domain":"zendesk.com","answer_bot_subdomain":"static","plans_url":"https://support.kraken.com/hc/admin/plan?locale=en-us","manage_content_url":"https://support.kraken.com/hc/en-us","arrange_content_url":"https://support.kraken.com/hc/admin/arrange_contents?locale=en-us","general_settings_url":"https://support.kraken.com/hc/admin/general_settings?locale=en-us","user_segments_url":"https://kraken.zendesk.com/knowledge/user_segments?brand_id=1186036","import_articles_url":"https://support.kraken.com/hc/admin/import_articles?locale=en-us","has_community_enabled":false,"has_groups":true,"has_internal_sections":true,"has_organizations":true,"has_tag_restrictions":true,"has_answer_bot_web_form_enabled":false,"has_close_the_loop_enabled":false,"billing_url":"/access/return_to?return_to=https://kraken.zendesk.com/agent/admin/subscription","has_answer_bot":true,"has_block_answer_bot_embeddable":false,"has_guide_docs_importer":true,"has_guide_permission_groups":true,"answer_bot_management_url":"https://support.kraken.com/hc/admin/answer_bot?locale=en-us","is_account_owner":false,"has_theming_templates":true,"theming_center_url":"https://support.kraken.com/theming","theming_cookie_key":"hc-da39a3ee5e6b4b0d3255bfef95601890afd80709-preview","is_preview":false,"permission_groups_url":"https://kraken.zendesk.com/knowledge/permissions?brand_id=1186036","has_guide_user_segments_search":false,"has_guide_user_segments_v2":true,"has_alternate_templates":false};
</script>

  <script src="//static.zdassets.com/hc/assets/hc_enduser-8d4f93021497ff3dda0e5188ba380668.js"></script>

  <script type="text/javascript">
    (function() {
  var Tracker = {};

  Tracker.track = function(eventName, data) {
    var url = "https://support.kraken.com/hc/tracking/events?locale=en-us";

    var payload = {
      "event": eventName,
      "data": data,
      "referrer": document.referrer
    };

    var xhr = new XMLHttpRequest();

    xhr.open("POST", url, true);
    xhr.setRequestHeader("Content-Type", "application/json; charset=UTF-8");
    xhr.send(JSON.stringify(payload));
  };

    Tracker.track("article_viewed", "BAh7CDoLbG9jYWxlSSIKZW4tdXMGOgZFVDoPYXJ0aWNsZV9pZGkETLBFDDoKX21ldGF7CzoPYWNjb3VudF9pZGkDpaoFOhNoZWxwX2NlbnRlcl9pZGkEpszrCzoNYnJhbmRfaWRpA/QYEjoMdXNlcl9pZDA6DnVzZXJfcm9sZUkiDmFub255bW91cwY7BlQ7AEkiCmVuLXVzBjsGVA==--ff58dbaa4545ec0680e1b5604bd356f702c13b39");
})();

  </script>
</body>
</html>
```

**Comment by kroitor** [comment]
@fonzmeister pardon, that was a small transpiler issue, tested it in js, but didn't pay necessary attention to generated py, my bad, added a refix to it, so it should be ok in 10 minutes.
