### ISSUE TITLE
[Bitfinex] Closing Position doesn't work

### ISSUE THREAD

**Issue by Andi1990** [ccxt/ccxt#4084]
When trying to close an open short position with 
`        data = self.exchange.private_post_position_close({'position_id': positionid})
`
I get the following Error message:

```Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 434, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.bitfinex.com/v1/position/close

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/trader.py", line 148, in close_margin_short_position
    data = self.exchange.private_post_position_close({'position_id': positionid})
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 362, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 359, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 447, in fetch
    self.handle_rest_errors(e, response.status_code, http_response, url, method)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 469, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 344, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: bitfinex https://api.bitfinex.com/v1/position/close POST 404 Client Error: Not Found for url: https://api.bitfinex.com/v1/position/close 
```

The error is quite new. A few days ago, this method worked fine. So from my point of view there might be some changes on Bitfinex api?

- Programming Language version: python 3.6.6
- CCXT version: 1.17.449
- Exchange: Bitfinex
- Method: private_post_position_close

**Comment by kroitor** [comment]
@Andi1990 can you post your code to reproduce the issue? (without your keys, according to the following guides precisely: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by kroitor** [comment]
@Andi1990 let us know if this does not answer your question: 

- https://github.com/ccxt/ccxt/issues/2640
- https://github.com/ccxt/ccxt/issues/2640#issuecomment-427824309
- https://github.com/ccxt/ccxt/issues/2640#issuecomment-427834252

Feel free to reopen this or just ask further questions, if any.
