### ISSUE TITLE
Liquid: incorrect rate limit error?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4123]
Liquid exchange returns a 429 when you exceed the rate limit.  Currently the error message thrown reads:

```Error: liquid POST https://api.liquid.com/orders 429  offline, on maintenance or unreachable from this location at the moment
```

**Comment by npomfret** [comment]
@kroitor - i'm still not seeing the error i would expect when i exceed the rate limit: 

```
fetch:
 liquid GET https://api.liquid.com/transactions?limit=100&page=1&currency=TTU&transaction_type=withdrawal 
Request:
 { 'X-Quoine-API-Version': '2',
  'Content-Type': 'application/json',
  'X-Quoine-Auth': 'hidden' } 
 undefined 

requesting GET https://api.liquid.com/transactions?limit=100&page=1&currency=TTU&transaction_type=withdrawal { remaining: -1, used: '100%' }
parseJson:
 liquid GET https://api.liquid.com/transactions?limit=100&page=1&currency=TTU&transaction_type=withdrawal 429 error SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at liquid.parseJson (/Users/nickpomfret/Documents/github/crypto-trader-prototype/gae-services/ticking-orderbook-service/node_modules/ccxt/js/base/Exchange.js:533:53)
    at response.text.then (/Users/nickpomfret/Documents/github/crypto-trader-prototype/gae-services/ticking-orderbook-service/node_modules/ccxt/js/base/Exchange.js:631:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) response body:
'API rate limit exceeded. Please retry after 300s'
```

**Comment by npomfret** [comment]
@kroitor is saw #b0aaab6 just now.  Was wondering why we don't just test for the 429 status code?

**Comment by kroitor** [comment]
@npomfret we can, of course. To me it was just faster to add one line rather than two or three ) But feel free to change this if you want, your PRs are always welcome.
