### ISSUE TITLE
coinbase - fetchTrades gives error while paginating through trades.

### ISSUE THREAD

**Issue by msrpcoder** [ccxt/ccxt#4174]
- Ubuntu 16.04
- Node: python 3.6
- CCXT version: 1.17.480
- Exchange: coinbase
- Method: fetchTrades

**fetchTrades** support has been added in ccxt in https://github.com/ccxt/ccxt/pull/4092. But it has issue in pagination. I am trying to paginate through `fetchMyTrades` based on id, as per the recommendation of https://developers.coinbase.com/api/v2?python#pagination. But  I am getting following errors :-

```Traceback (most recent call last):
  File "/home/dell/.virtualenvs/ccxt_exploration/lib/python3.6/site-packages/ccxt/base/exchange.py", line 435, in fetch
    response.raise_for_status()
  File "/home/dell/.virtualenvs/ccxt_exploration/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coinbase.com/v2/accounts/61c6714f-836d-5385-a0e8-c3e6c128ff6c/sells?limit=100&order=asc&starting_after=0ac6f718-ad59-53eb-b2e7-8567119bfe5a

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dell/work/python/ccxt_exploration/src/coinbase_exchange.py", line 133, in <module>
    fetch_for_symbol(symbol)
  File "/home/dell/work/python/ccxt_exploration/src/coinbase_exchange.py", line 116, in fetch_for_symbol
    count = fetch_using_pagination(exchange.fetch_my_trades, symbol, account['id'])
  File "/home/dell/work/python/ccxt_exploration/src/coinbase_exchange.py", line 93, in fetch_using_pagination
    params=params)
  File "/home/dell/.virtualenvs/ccxt_exploration/lib/python3.6/site-packages/ccxt/coinbase.py", line 205, in fetch_my_trades
    }, query))
  File "/home/dell/.virtualenvs/ccxt_exploration/lib/python3.6/site-packages/ccxt/base/exchange.py", line 362, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/dell/.virtualenvs/ccxt_exploration/lib/python3.6/site-packages/ccxt/base/exchange.py", line 359, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/dell/.virtualenvs/ccxt_exploration/lib/python3.6/site-packages/ccxt/base/exchange.py", line 447, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response)
  File "/home/dell/.virtualenvs/ccxt_exploration/lib/python3.6/site-packages/ccxt/coinbase.py", line 582, in handle_errors
    raise exceptions[errorCode](feedback)
ccxt.base.errors.ExchangeError: coinbase {"errors":[{"id":"invalid_request","message":"Invalid `after` parameter for pagination, no object found with id"}]}
```
My code for pagination is 

```
def fetch_using_pagination1(exchange, account_id):
    last_id = 0
    limit = 100

    while True:

        params = {'accountId': account_id, 'limit': limit, 'order': 'asc'}

        if last_id:
            params['starting_after'] = last_id

        out = exchange.fetch_my_trades(symbol=None, since=None, limit=limit,
                     params=params)
        if not out:
            break

        ls_out.extend(out)
        print("last object is", out[-1])
        last_id = out[-1]['id']

    return ls_out
```
The logs are 

```
https://api.coinbase.com/v2/accounts/61c6714f-836d-5385-a0e8-c3e6c128ff6c/buys?limit=100&order=asc {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'CB-ACCESS-KEY': 'PjirTNpLE2Cjfjfz', 'CB-ACCESS-SIGN': '17207730276f5024610b232651b14392621fa08ea3a32466771b9cbd167303f7', 'CB-ACCESS-TIMESTAMP': '1542306669', 'Content-Type': 'application/json', 'CB-VERSION': '2018-05-30'}
https://api.coinbase.com/v2/accounts/61c6714f-836d-5385-a0e8-c3e6c128ff6c/sells?limit=100&order=asc {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'CB-ACCESS-KEY': 'PjirTNpLE2Cjfjfz', 'CB-ACCESS-SIGN': '1b27c2c3042add4157836b2e3df4baadf2ba6de263ad1415babe4790660e37be', 'CB-ACCESS-TIMESTAMP': '1542306670', 'Content-Type': 'application/json', 'CB-VERSION': '2018-05-30'}
last object is {'info': {'id': '0ac6f718-ad59-53eb-b2e7-8567119bfe5a', 'status': 'completed', 'payment_method': {'id': '987bcf8e-ba49-576d-a0e0-b8ea2137e987', 'resource': 'payment_method', 'resource_path': '/v2/payment-methods/987bcf8e-ba49-576d-a0e0-b8ea2137e987'}, 'transaction': {'id': '8362f0ab-2f25-575a-9593-c30670e0883e', 'resource': 'transaction', 'resource_path': '/v2/accounts/61c6714f-836d-5385-a0e8-c3e6c128ff6c/transactions/8362f0ab-2f25-575a-9593-c30670e0883e'}, 'user_reference': 'LDDJCRCM', 'created_at': '2018-02-13T22:43:50Z', 'updated_at': '2018-02-13T22:43:54Z', 'resource': 'buy', 'resource_path': '/v2/accounts/61c6714f-836d-5385-a0e8-c3e6c128ff6c/buys/0ac6f718-ad59-53eb-b2e7-8567119bfe5a', 'committed': True, 'payout_at': '2018-02-13T22:43:48Z', 'instant': True, 'fee': {'amount': '0.99', 'currency': 'USD'}, 'amount': {'amount': '0.00475975', 'currency': 'ETH'}, 'total': {'amount': '5.00', 'currency': 'USD'}, 'subtotal': {'amount': '4.01', 'currency': 'USD'}, 'hold_until': None, 'hold_days': 0, 'is_first_buy': False, 'requires_completion_step': False}, 'id': '0ac6f718-ad59-53eb-b2e7-8567119bfe5a', 'order': None, 'timestamp': 1518561830000, 'datetime': '2018-02-13T22:43:50.000Z', 'symbol': 'USD/ETH', 'type': None, 'side': 'buy', 'price': 842.4812227532958, 'amount': 0.00475975, 'cost': 4.01, 'fee': {'cost': 0.99, 'currency': 'USD'}}
https://api.coinbase.com/v2/accounts/61c6714f-836d-5385-a0e8-c3e6c128ff6c/buys?limit=100&order=asc&starting_after=0ac6f718-ad59-53eb-b2e7-8567119bfe5a {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'CB-ACCESS-KEY': 'PjirTNpLE2Cjfjfz', 'CB-ACCESS-SIGN': '6727cc065e909ef4ef5b61dd794cb7ed93e03769834125a5a70adf698113b013', 'CB-ACCESS-TIMESTAMP': '1542306670', 'Content-Type': 'application/json', 'CB-VERSION': '2018-05-30'}
Traceback (most recent call last):
  File "/home/dell/.virtualenvs/ccxt_exploration/lib/python3.6/site-packages/ccxt/base/exchange.py", line 435, in fetch
    response.raise_for_status()
  File "/home/dell/.virtualenvs/ccxt_exploration/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coinbase.com/v2/accounts/61c6714f-836d-5385-a0e8-c3e6c128ff6c/sells?limit=100&order=asc&starting_after=0ac6f718-ad59-53eb-b2e7-8567119bfe5a
```
Is this the side-effect of unifying **buys** and **sells** in **coinbase** and abstracting as a single method ?

**Comment by msrpcoder** [comment]
From my analysis, I have found that current implementation [fetchTrades](https://github.com/ccxt/ccxt/blob/master/js/coinbase.js#L187) fails at unifying transactions for `buy` and `sell` and thus id-based pagination as recommended by [coinbase docs](https://developers.coinbase.com/api/v2?python#pagination) doesn't work and we are getting above error. In this case, last transaction id belongs to `buy` and since we are passing it to `fetchMyTrades`, it uses it for both `buy` and `sell` and thus `sell` gives error.

Current implementation have to be modified to accept pagination params for `buy` and `sell` separately.

**Comment by milesalex** [comment]
@kroitor Ran into this issue. Thoughts?

**Comment by milesalex** [comment]
Would us suggest adding a `type` param to the function?

```js
async fetchMyTrades (type, symbol = undefined, since = undefined, limit = undefined, params = {}) {}

fetchMyTrades ('buys')
fetchMyTrades ('sells')
```

**Comment by kroitor** [comment]
@milesalex well, we got several options: we could either split it into two: fetchMyBuys and fetchMySells or we could add one morekey to params-overrides and then omit it from the request inside the implementation, but I'm pretty sure that changing the signature of the unified method to a non-standard one will confuse other users.

**Comment by milesalex** [comment]
@kroitor Are you saying you recommend implementing the latter approach? We can also include error handling to specify a type to include.

**Comment by kroitor** [comment]
@milesalex yep, if we want to keep it unified, i'd do that with separate params-overrides:

```JavaScript
fetchMyTrades (symbol = undefined, since = undefined, limit = undefined, params = {}) {
    let buysParams = this.safeValue (params, 'buys', {});
    let sellsParams = this.safeValue (params, 'sells', {});
    let request = {
        // common stuff
    };
    buys = await this.privateXXX (this.extend (request, buysParams));
    sells = await this.privateYYY (this.extend (request, sellsParams));
    ...
```

**Comment by milesalex** [comment]
Is it common to separate the endpoints into `fetchMySells` and `fetchMyBuys`? I do like how clear having one function per endpoint is @kroitor
