### ISSUE TITLE
OKEX-contract fetchOpenOrders problem

### ISSUE THREAD

**Issue by gavin369** [ccxt/ccxt#4206]
Hello, how to use fetchOpenOrders for OKEX order inquiry, how to transmit reference?

```
async function main1(){
    //msg = await GetOpenOrders({contract_type:StrategySettings.ContractType} )
    msg = await exchanges(0).fetchOpenOrders("EOS/USD",1000,1,{status:"1",order_id:"-1",contract_type:"quarter"})
    console.log(msg);
}
main1();
```
The result of coming out：
```
(node:28272) UnhandledPromiseRejectionWarning: Error: okex {"result":false,"error_code":20024}
    at okex.handleErrors (C:\Users\ADNIN2\AppData\Local\BotQuant\app-1.0.5\resources\app\node_modules\ccxt\js\okcoinusd.js:974:27)
    at response.text.then (C:\Users\ADNIN2\AppData\Local\BotQuant\app-1.0.5\resources\app\node_modules\ccxt\js\base\Exchange.js:648:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Although the 20024 mistake is that the API signature is incorrect, I make sure API is not wrong.Or trouble, please mention okex's fetchOpenOrders.

**Comment by kroitor** [comment]
@gavin369 does `fetchBalance()` work normally in your case?

**Comment by gavin369** [comment]
fetchBalance()   Can work！

**Comment by gavin369** [comment]
In addition, XUC of okex is no longer available. Please change XUC to XRP.

```
'options': {
                'marketBuyPrice': false,
                'defaultContractType': 'this_week', // next_week, quarter
                'warnOnFetchOHLCVLimitArgument': true,
                'fiats': [ 'USD', 'CNY' ],
                'futures': {
                    'BCH': true,
                    'BTC': true,
                    'BTG': true,
                    'EOS': true,
                    'ETC': true,
                    'ETH': true,
                    'LTC': true,
                    'NEO': true,
                    'QTUM': true,
                    'USDT': true,
                    'XUC': true,
                },
            },
```
