### ISSUE TITLE
Different Results fetchTickers()

### ISSUE THREAD

**Issue by DeveloperOnCall** [ccxt/ccxt#4231]
There seems to be a large difference when calling ``` fetchTickers() ``` from Poloniex over Binance as well as others.

I thought it was my work until I ran this example
``` https://github.com/ccxt/ccxt/blob/master/examples/js/live-tickers.js ```

Binance Returns (a row)
```js
binance 2018-11-26T12:32:39.977Z
Fetched 408 tickers:
     symbol |         price |                 datetime
------------------------------------------------------
   BTC/USDT | 4046.46000000 | 2018-11-26T12:32:40.875Z


```
But Poloniex returns

```js
poloniex 2018-11-26T12:32:27.581Z
Fetched 118 tickers:
symbol |         price |                 datetime
-------------------------------------------------
       | 4052.82370258 | 2018-11-26T12:32:27.581Z

```
The Poloniex results are not showing the symbol - how do we get the symbol from (when used in a loop together) both exchanges?

- OS:
- Programming Language version:
- CCXT version: latest
- Exchange: poloniex vs binance

- Method:

**Comment by DeveloperOnCall** [comment]
That was a speedy response and thanks for the fix -- working great... However, I am now experiencing a similar issue with Bitlish

```
/ccxt/examples/js/live-tickers.js bitlish
```

I am getting the following...

```js
Instantiating bitlish exchange
(node:6860) UnhandledPromiseRejectionWarning: ReferenceError: symbol is not defined
    at bitlish.fetchTickers (/node_modules/ccxt/js/bitlish.js:186:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by DeveloperOnCall** [comment]
Sorry -- I am not entirely sure what more I can give - I am new to .js development..

Here is the full call and result received.

```js
node /root/streamfeeder/node_modules/ccxt/examples/js/live-tickers.js bitlish
Instantiating bitlish exchange
--------------------------------------------------------
bitlish 2018-11-29T08:36:08.121Z
Fetched 71 tickers:
   symbol |           price |                 datetime
------------------------------------------------------
IOTA/USDT |      0.45450000 | 2018-11-29T08:36:08.119Z
  BCH/BTC |      0.04430000 | 2018-11-29T08:36:08.118Z
  BCH/GBP |    220.00000000 | 2018-11-29T08:36:08.119Z
 BCH/USDT |    180.00000000 | 2018-11-29T08:36:08.119Z
  BTC/EUR |   3700.77000000 | 2018-11-29T08:36:08.119Z
  BTC/GBP |   3554.69000000 | 2018-11-29T08:36:08.119Z
  BTC/JPY | 426000.00000000 | 2018-11-29T08:36:08.119Z
  BTC/RUB | 272416.00000000 | 2018-11-29T08:36:08.119Z
 BTC/USDT |   4999.00000000 | 2018-11-29T08:36:08.119Z
  BTC/USD |   4187.00000000 | 2018-11-29T08:36:08.119Z
  BTG/BTC |      0.00491000 | 2018-11-29T08:36:08.119Z
  BTG/EUR |     17.00000000 | 2018-11-29T08:36:08.119Z
  BTG/GBP |      0.00000000 | 2018-11-29T08:36:08.119Z
 BTG/USDT |      0.01000000 | 2018-11-29T08:36:08.119Z
          |      0.02328000 | 2018-11-29T08:36:08.119Z
          |     74.60000000 | 2018-11-29T08:36:08.119Z
          |      0.00000000 | 2018-11-29T08:36:08.119Z
          |   6918.00000000 | 2018-11-29T08:36:08.119Z
          |      0.00000000 | 2018-11-29T08:36:08.119Z
          |     98.70000000 | 2018-11-29T08:36:08.119Z
--------------------------------------------------------
bitlish 2018-11-29T08:36:09.531Z
Fetched 71 tickers:
   symbol |           price |                 datetime
------------------------------------------------------
IOTA/USDT |      0.45450000 | 2018-11-29T08:36:09.530Z
  BCH/BTC |      0.04430000 | 2018-11-29T08:36:09.529Z
```
