### ISSUE TITLE
Bitmex permissions {"error":{"message":"Access Denied","name":"HTTPError"}}

### ISSUE THREAD

**Issue by honeyligo** [ccxt/ccxt#4329]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:Win10
- Programming Language version:js
- CCXT version:1.18.27
- Exchange:bitmex
- Method:create_order 

I try to call the create_order method after apiKey and secret are set, but it was denied, anyone help:

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.bitmex.com/api/v1/order?symbol=XBTZ18&side=Sell&orderQty=1.0&ordType=StopLimit&price=6500.0&stopPx=6000.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/coin/ccxt/examples/py/bitmex-create-order.py", line 29, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "G:\coin\ccxt\venv\lib\site-packages\ccxt\bitmex.py", line 498, in create_order
    response = self.privatePostOrder(self.extend(request, params))
  File "G:\coin\ccxt\venv\lib\site-packages\ccxt\base\exchange.py", line 364, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "G:\coin\ccxt\venv\lib\site-packages\ccxt\base\exchange.py", line 361, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "G:\coin\ccxt\venv\lib\site-packages\ccxt\base\exchange.py", line 452, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response)
  File "G:\coin\ccxt\venv\lib\site-packages\ccxt\bitmex.py", line 568, in handle_errors
    raise exact[message](feedback)
ccxt.base.errors.PermissionDenied: bitmex {"error":{"message":"Access Denied","name":"HTTPError"}}

**Comment by honeyligo** [comment]
thanks, the reason is as 2920 descripted Bing Lee 邮箱：wookonghair@gmail.com 签名由 网易邮箱大师 定制 On 12/14/2018 02:24, Igor Kroitor wrote: Duplicate: #2920 (comment) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
