### ISSUE TITLE
zb fetch_balance() {"code":3006,"message":"无效的IP或与绑定的IP不一致"}

### ISSUE THREAD

**Issue by jackingyang** [ccxt/ccxt#4345]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:mac
- Programming Language version:python3
- CCXT version:1.17.565
- Exchange:zb
- Method:fetch_balance()

zb = ccxt.zb({
    'enableRateLimit': True,
    'apiKey': '',  # 36 characters
    'secret': '',  # 36 characters
})
d=zb.fetch_balance()
print(d)

Traceback (most recent call last):
  File "/Users/jacking 1/Desktop/test.py", line 18, in <module>
    d=zb.fetch_balance()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ccxt/zb.py", line 228, in fetch_balance
    response = self.privateGetGetAccountInfo(params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ccxt/base/exchange.py", line 364, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ccxt/base/exchange.py", line 361, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ccxt/base/exchange.py", line 463, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ccxt/zb.py", line 583, in handle_errors
    raise ExceptionClass(feedback)
ccxt.base.errors.AuthenticationError: zb {"code":3006,"message":"\u65e0\u6548\u7684IP\u6216\u4e0e\u7ed1\u5b9a\u7684IP\u4e0d\u4e00\u81f4"}

A few days ago, running normally, I suddenly failed today. help

**Comment by kroitor** [comment]
```
{"code":3006,"message":"\u65e0\u6548\u7684IP\u6216\u4e0e\u7ed1\u5b9a\u7684IP\u4e0d\u4e00\u81f4"}
```

means

```
无效的IP或与绑定的IP不一致
```

Have you checked the IP address linked to that API Key?

**Comment by kroitor** [comment]
Closing it until we have a followup from you, feel free to reopen it if needed or just ask further questions, if any.
