### ISSUE TITLE
Bitmex Invalid Header Nonce Type.

### ISSUE THREAD

**Issue by naborshem** [ccxt/ccxt#4348]
- OS: Windows 10
- Programming Language version: Python 3.7.1
- CCXT version: 1.18.41
- Exchange: Bitmex
- Method: fetch_balance

Greetings,

While trying to resolve another issue I have decided to upgrade CCXT to the latest version and whenever I try to use any method on Bitmex that requires sending a Nonce I receive the following error:

```
Request: GET https://www.bitmex.com/api/v1/user/margin?currency=all {'Content-Type': 'application/json', 'api-key': '<REMOVED>', 'api-nonce': 1545157060260, 'api-signature': '<REMOVED>', 'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\requests\utils.py", line 940, in check_header_validity
    if not pat.match(value):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 427, in fetch
    proxies=self.proxies
  File "C:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "C:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Program Files\Python37\lib\site-packages\requests\models.py", line 310, in prepare
    self.prepare_headers(headers)
  File "C:\Program Files\Python37\lib\site-packages\requests\models.py", line 444, in prepare_headers
    check_header_validity(header)
  File "C:\Program Files\Python37\lib\site-packages\requests\utils.py", line 944, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
requests.exceptions.InvalidHeader: Value for header {api-nonce: 1545157060260} must be of type str or bytes, not <class 'int'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\ccxt\bitmex.py", line 227, in fetch_balance
    response = self.privateGetUserMargin({'currency': 'all'})
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 366, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 363, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 463, in fetch
    self.raise_error(ExchangeError, url, method, e)
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 348, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: bitmex https://www.bitmex.com/api/v1/user/margin?currency=all GET Value for header {api-nonce: 1545157060260} must be of type str or bytes, not <class 'int'>

```

Does not seem to appear on Binance though and was not present on the previous version I used which was 1.18.5.

**Comment by kroitor** [comment]
Hi! Thx for reporting! This was a minor bug due to changes introduced in #4307, there was a minor leftover, so I fixed it and it should be resolved if you upgrade to version 1.18.42 in 5-10 minutes. Let us know if that does not help.
