### ISSUE TITLE
InsufficientFunds: bitmex {"error":{"message":"Account has insufficient Available Balance, 21251123 XBt required","name":"ValidationError"}}

### ISSUE THREAD

**Issue by jins81c** [ccxt/ccxt#4383]
everytime different error.
anytime it's good but sometimes it's problem

  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 363, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 454, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)

  File "C:\Anaconda3\lib\site-packages\ccxt\bitmex.py", line 573, in handle_errors
    raise broad[broadKey](feedback)

InsufficientFunds: bitmex {"error":{"message":"Account has insufficient Available Balance, 21251123 XBt required","name":"ValidationError"}}

================================================================================================
 File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 445, in fetch
    self.raise_error(RequestTimeout, method, url, e)

  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 348, in raise_error
    raise exception_type(output)

=================================================================================================

Traceback (most recent call last):

  File "<ipython-input-1-31270a1919f8>", line 1, in <module>
    runfile('D:/bitmex/bitmex/main_jin2.py', wdir='D:/bitmex/bitmex')

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/bitmex/bitmex/main_jin2.py", line 109, in <module>
    chc2 = nowc()

  File "D:/bitmex/bitmex/main_jin2.py", line 72, in nowc
    if nowprice > enterprice + ab :

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by kroitor** [comment]
Do you understand how to handle the errors, namely, have you read the section of the Manual on error handling? https://github.com/ccxt/ccxt/wiki/Manual#error-handling ?

**Comment by kroitor** [comment]
Closing this for now until we have a followup from you. Feel free to reopen this if needed or just ask further questions if any.
