### ISSUE TITLE
Allcoin module has issues fetching previous trades

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#4415]
- OS: Linux
- Programming Language version: Python 3.7
- CCXT version: Latest
- Exchange: AllCoin
- Method: ```allcoin.fetchTrades('ETH/BTC')```

```
Request: GET https://www.allcoin.com/Home/MarketOverViewDetail/ {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.allcoin.com/Home/MarketOverViewDetail/ 200 {'Date': 'Tue, 01 Jan 2019 05:37:04 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'X-Via-JSL': '6514119,-', 'Set-Cookie': '__jsluid=d52db21e142a611f54462b9c872fed24; max-age=31536000; path=/; HttpOnly', 'X-Cache': 'bypass', 'Content-Encoding': 'gzip'} <html xmlns="http://www.w3.org/1999/xhtml">
                <head>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <meta http-equiv="refresh" content="2;url=https://www.allcoin.com">
                <title>页面出错</title>
                <style>
                .report{ width:440px; position:fixed; left:50%; top:50%; margin-left:-180px; margin-top:-160px;}
                .report h1{ font-family:"微软雅黑"; font-weight:normal; margin-bottom:20px; font-size:24px; background:url(images/logo.png) left top no-repeat; height:31px; padding-left:45px; line-height:31px; color:#f60; padding-top:3px;}
                .report h1,.report h2,.report p{ font-family:"微软雅黑";}
                .report h2{ font-size:18px; color:#333; line-height:30px; font-weight:normal;}
                .report p{ text-align:right; font-size:14px; color:#999;}
                </style>
                </head>
                <body>
                <div class="report">

					<img src="/images/errors.png" />
                    <h2>页面出错啦，正在为您跳转到首页，2秒后自动跳转</h2>
                </div>
                </body>
                </html>
				
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/okcoinusd.py", line 525, in fetch_trades
    self.load_markets()
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1028, in load_markets
    markets = self.fetch_markets(params)
  File "/usr/local/lib/python3.7/site-packages/ccxt/allcoin.py", line 63, in fetch_markets
    coins = response['marketCoins']
TypeError: string indices must be integers
```

**Comment by kroitor** [comment]
Dupe (they have changed their API): https://github.com/ccxt/ccxt/issues/2962#issuecomment-392320417
