### ISSUE TITLE
Exmo exchange not available 

### ISSUE THREAD

**Issue by ASAllon** [ccxt/ccxt#4546]
Hello.

I have a code that i had run last time in 21/01/2019 and today I had updated to ccxt 1.18.152 but it won't work and I'm not sure why....

- OS: Win 10
- Programming Language version: Python
- CCXT version: 1.18.152
- Exchange: Exmo (also run on kraken but no problems there)
- Method: loadMarkets()

This is my code:
```
def init_exchange(exchange_id, enableRateLimit=True):
    ## intiate the api class to send to the function
    exchange_class = getattr(ccxt, exchange_id)
    exchange = exchange_class({'enableRateLimit': enableRateLimit, })
    return exchange

exchange2_id = 'exmo'
exchange2 = init_exchange(exchange2_id, enableRateLimit=False)
loop2 = asyncio.get_event_loop()
markets2 = loop2.run_until_complete(exchange2.loadMarkets())
```

This is the Error:

> Traceback (most recent call last):
>   File "C:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 924, in _wrap_create_connection
>     await self._loop.create_connection(*args, **kwargs))
>   File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 959, in create_connection
>     raise exceptions[0]
>   File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 946, in create_connection
>     await self.sock_connect(sock, address)
>   File "C:\Program Files\Python37\lib\asyncio\selector_events.py", line 464, in sock_connect
>     return await fut
>   File "C:\Program Files\Python37\lib\asyncio\selector_events.py", line 494, in _sock_connect_cb
>     raise OSError(err, f'Connect call failed {address}')
> TimeoutError: [Errno 10060] Connect call failed ('185.104.211.27', 443)
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "C:\Program Files\Python37\lib\site-packages\ccxt\async_support\base\exchange.py", line 138, in fetch
>     proxy=self.aiohttp_proxy) as response:
>   File "C:\Program Files\Python37\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
>     self._resp = await self._coro
>   File "C:\Program Files\Python37\lib\site-packages\aiohttp\client.py", line 476, in _request
>     timeout=real_timeout
>   File "C:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 522, in connect
>     proto = await self._create_connection(req, traces, timeout)
>   File "C:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
>     req, traces, timeout)
>   File "C:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 992, in _create_direct_connection
>     raise last_exc
>   File "C:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 974, in _create_direct_connection
>     req=req, client_error=client_error)
>   File "C:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 931, in _wrap_create_connection
>     raise client_error(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host exmo.me:443 ssl:None [Connect call failed ('185.104.211.27', 443)]
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "C:\Program Files\Python37\lib\site-packages\ccxt\async_support\base\exchange.py", line 176, in load_markets
>     markets = await self.fetch_markets(params)
>   File "C:\Program Files\Python37\lib\site-packages\ccxt\async_support\exmo.py", line 329, in fetch_markets
>     fees = await self.fetch_trading_fees()
>   File "C:\Program Files\Python37\lib\site-packages\ccxt\async_support\exmo.py", line 129, in fetch_trading_fees
>     response = await self.webGetEnDocsFees(params)
>   File "C:\Program Files\Python37\lib\site-packages\ccxt\async_support\base\exchange.py", line 116, in fetch2
>     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "C:\Program Files\Python37\lib\site-packages\ccxt\async_support\base\exchange.py", line 159, in fetch
>     self.raise_error(ExchangeNotAvailable, url, method, e, None)
>   File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 383, in raise_error
>     raise exception_type(output)
> ccxt.base.errors.ExchangeNotAvailable: exmo https://exmo.me/en/docs/fees GET Cannot connect to host exmo.me:443 ssl:None [Connect call failed ('185.104.211.27', 443)]

**Comment by kroitor** [comment]
> I had updated to ccxt 1.18.152 but it won't work and I'm not sure why....

Do you recall what was your previous version number?

Does it work like so? ↓

```Python
import ccxt.async_support as ccxt
from pprint import pprint

exchange = ccxt.exmo ({
    'enableRateLimit': enableRateLimit,
    'api': {                                           
        'www': 'https://exmo.com',
    },
})

loop = asyncio.get_event_loop()
markets = loop.run_until_complete(exchange.load_markets())
pprint(markets)
```

**Comment by ASAllon** [comment]
Hey!
I think I run before version 1.18.144

I tried what you asked and got this error:

> Traceback (most recent call last):
>   File "<input>", line 7, in <module>
>   File "C:\Program Files\Python37\lib\site-packages\ccxt\async_support\base\exchange.py", line 56, in __init__
>     super(Exchange, self).__init__(config)
>   File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 285, in __init__
>     self.define_rest_api(self.api, 'request')
>   File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 339, in define_rest_api
>     for http_method, urls in methods.items():
> AttributeError: 'str' object has no attribute 'items'

**Comment by kroitor** [comment]
@ASAllon pardon there was a typo in the snippet I posted above, should be this:

```Python
import ccxt.async_support as ccxt
from pprint import pprint

exchange = ccxt.exmo ({
    'enableRateLimit': enableRateLimit,
    'urls': {
        'api': {                                           
            'www': 'https://exmo.com',
        },
    },
})

loop = asyncio.get_event_loop()
markets = loop.run_until_complete(exchange.load_markets())
pprint(markets)
```

Apologies, my bad, I was rushing with my answer, can you please retry with this one again?

**Comment by DmitryVil** [comment]
Good morning,
I have the same problem with exmo.
I run your code:
import ccxt.async_support as ccxt
from pprint import pprint

exchange = ccxt.exmo ({
    'enableRateLimit': enableRateLimit,
    'urls': {
        'api': {                                           
            'www': 'https://exmo.com',
        },
    },
})

loop = asyncio.get_event_loop()
markets = loop.run_until_complete(exchange.load_markets())
pprint(markets)

And got:
"C:\Users\Vilensky Dmitry\AppData\Local\Programs\Python\Python37\python.exe" "C:/Users/Vilensky Dmitry/Google Drive/PythonProjects/CryptoTrade/EXMO_loadmarket_problem.py"
Traceback (most recent call last):
  File "C:/Users/Vilensky Dmitry/Google Drive/PythonProjects/CryptoTrade/EXMO_loadmarket_problem.py", line 15, in <module>
    markets = loop.run_until_complete(exchange.load_markets())
  File "C:\Users\Vilensky Dmitry\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\Vilensky Dmitry\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\async_support\base\exchange.py", line 156, in load_markets
    markets = await self.fetch_markets()
  File "C:\Users\Vilensky Dmitry\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\async_support\exmo.py", line 130, in fetch_markets
    markets = await self.publicGetPairSettings()
  File "C:\Users\Vilensky Dmitry\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\async_support\base\exchange.py", line 101, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "C:\Users\Vilensky Dmitry\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\async_support\exmo.py", line 578, in sign
    url = self.urls['api'] + '/' + self.version + '/' + path
TypeError: unsupported operand type(s) for +: 'dict' and 'str'
exmo requires to release all resources with an explicit call to the .close() coroutine.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000189E7774F98>

Thank you in advance,
Dmitry

**Comment by kroitor** [comment]
@DmitryVil hey!) Looks like your version of CCXT is old. Apart from that, I made another typo there, which I edited in place. However, we need to make sure that your runtime version of ccxt is up to date:

```Python
import ccxt.async_support as ccxt
print('CCXT version', ccxt.__version__)
```

**Comment by DmitryVil** [comment]
![image](https://user-images.githubusercontent.com/35109659/51800091-2d49d280-2233-11e9-9088-12935b8e2544.png)

**Comment by DmitryVil** [comment]
in version 1.18.154 exmo also doesn't work

**Comment by ASAllon** [comment]
Hey @kroitor !
I tried  your last code on a computer with ccxt 1.18.144 and got this error:

The code i run:

```
import asyncio
import ccxt.async_support as ccxt
from pprint import pprint

exchange = ccxt.exmo ({
    'enableRateLimit': True,
    'urls': {
        'api': {                                           
            'web': 'https://exmo.com',
        },
    },
})

loop = asyncio.get_event_loop()
markets = loop.run_until_complete(exchange.load_markets())
pprint(markets)
```


> Traceback (most recent call last):
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\base\exchange.py", line 138, in fetch
>     proxy=self.aiohttp_proxy) as response:
>   File "C:\Program Files\Python\lib\site-packages\aiohttp\client.py", line 932, in __aenter__
>     self._resp = await self._coro
>   File "C:\Program Files\Python\lib\site-packages\aiohttp\client.py", line 424, in _request
>     await resp.start(conn)
>   File "C:\Program Files\Python\lib\site-packages\aiohttp\client_reqrep.py", line 831, in start
>     self._continue = None
>   File "C:\Program Files\Python\lib\site-packages\aiohttp\helpers.py", line 567, in __exit__
>     raise asyncio.TimeoutError from None
> concurrent.futures._base.TimeoutError
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "<input>", line 14, in <module>
>   File "C:\Program Files\Python\lib\asyncio\base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\base\exchange.py", line 179, in load_markets
>     currencies = await self.fetch_currencies()
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\exmo.py", line 268, in fetch_currencies
>     fees = await self.fetch_funding_fees(params)
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\exmo.py", line 160, in fetch_funding_fees
>     response = await self.webGetCtrlFeesAndLimits(params)
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\base\exchange.py", line 116, in fetch2
>     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\base\exchange.py", line 156, in fetch
>     self.raise_error(RequestTimeout, method, url, e, None)
>   File "C:\Program Files\Python\lib\site-packages\ccxt\base\exchange.py", line 372, in raise_error
>     raise exception_type(output)
> ccxt.base.errors.RequestTimeout: exmo GET https://exmo.com/ctrl/feesAndLimits 


Than updated to ccxt 1.18.154
and got this error:


> Traceback (most recent call last):
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\base\exchange.py", line 138, in fetch
>     proxy=self.aiohttp_proxy) as response:
>   File "C:\Program Files\Python\lib\site-packages\aiohttp\client.py", line 932, in __aenter__
>     self._resp = await self._coro
>   File "C:\Program Files\Python\lib\site-packages\aiohttp\client.py", line 502, in _request
>     break
>   File "C:\Program Files\Python\lib\site-packages\aiohttp\helpers.py", line 567, in __exit__
>     raise asyncio.TimeoutError from None
> concurrent.futures._base.TimeoutError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/Users/Kitchen/Desktop/scratch1.py", line 15, in <module>
>     markets = loop.run_until_complete(exchange.load_markets())
>   File "C:\Program Files\Python\lib\asyncio\base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\base\exchange.py", line 176, in load_markets
>     markets = await self.fetch_markets(params)
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\exmo.py", line 329, in fetch_markets
>     fees = await self.fetch_trading_fees()
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\exmo.py", line 129, in fetch_trading_fees
>     response = await self.webGetEnDocsFees(params)
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\base\exchange.py", line 116, in fetch2
>     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "C:\Program Files\Python\lib\site-packages\ccxt\async_support\base\exchange.py", line 156, in fetch
>     self.raise_error(RequestTimeout, method, url, e, None)
>   File "C:\Program Files\Python\lib\site-packages\ccxt\base\exchange.py", line 383, in raise_error
>     raise exception_type(output)
> ccxt.base.errors.RequestTimeout: exmo GET https://exmo.com/en/docs/fees

**Comment by kroitor** [comment]
@ASAllon if it isn't a secret, what's your location or country? Exmo has two mirrors, `exmo.me` and `exmo.com`, both of them being available in just a half of the world... So, it can make a difference. I can open `exmo.com` with a VPN, but I can't access it without a VPN. WIth `exmo.me` it's the opposite.

**Comment by ASAllon** [comment]
I'm in Israel
The strange thing is that I used this for more than a month without any problems...

**Comment by kroitor** [comment]
@ASAllon that's right, there were changes in December and January in `exmo.js`: https://github.com/ccxt/ccxt/commits/master/js/exmo.js related to that, since problems with accessing those have started to appear. Apparently, `exmo.com` doesn't work for you (both versions timed out). 

Is this URL accessible with your browser? https://exmo.me/en/docs/fees

**Comment by DmitryVil** [comment]
I am working from the USA. 
From here access to exmo also closed.
There is one more observation about exmo:
During 2-3 last months,  time of response  of fetch2OrderBook() is very very unstable.

**Comment by ndubel** [comment]
also not works from Belarus and Russia

**Comment by Raxort** [comment]
I have CCXT v. 1.18.196

When I try to fetchTickers I receive the following error:

`[Network Error] exmo GET https://exmo.me/en/docs/fees 28 Connection timed out after 10000 milliseconds`

When I set 'verbose' => true, I see following:

`Request: Array ( [0] => GET [1] => https://exmo.me/en/docs/fees [2] => Array ( ) [3] => ) Response: Array ( [0] => GET [1] => https://exmo.me/en/docs/fees [2] => 0 [3] => Connection timed out after 10001 milliseconds [4] => Array ( ) [5] => ) [Network Error] exmo GET https://exmo.me/en/docs/fees 28 Connection timed out after 10001 milliseconds`

**Comment by salmin7a** [comment]
Hello , Function load_markets () does not work

**Comment by xpl** [comment]
The fix is coming. Had to hard-code the fees until we figure how to fetch `https://exmo.me/en/docs/fees` programmatically. Their web front end seems to ban our requests, and it is not clear yet why exactly (I tried setting various browser-ish headers, but no luck).

**Comment by ASAllon** [comment]
So is it fixed?
