### ISSUE TITLE
Error with BCH withdrawal from Bitfinex

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#457]
Hi, @kroitor.

I tried to make a BCH withdrawal from Bitfinex using ccxt library, but unsuccessfully. Then I made manually on my account and it worked fine. I don't know what is happening. May you take a look at this restriction, please?

This is the verbose output from raised error:

```
Connected to pydev debugger (build 172.3544.46)
https://api.bitfinex.com/v1/symbols_details GET https://api.bitfinex.com/v1/symbols_details 
Request: {'User-Agent': 'ccxt/1.9.341 (+https://github.com/ccxt-dev/ccxt) Python/3.6.2', 'Accept-Encoding': 'gzip, deflate'} None
GET https://api.bitfinex.com/v1/symbols_details 
Response: Date: Fri, 03 Nov 2017 15:13:59 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Set-Cookie: __cfduid=de9bb58012c1653ce1eb0e9cf8577be271509722037; expires=Sat, 03-Nov-18 15:13:57 GMT; path=/; domain=.bitfinex.com; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Vary: Accept-Encoding
Content-Encoding: gzip
ETag: "7f9ce0b4f1fe78a7e9dd49715cd93e29"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: c0c6f77d-a8cf-4401-8ae8-1f3390fbbd3f
X-Runtime: 0.119667
X-Frame-Options: SAMEORIGIN
Server: cloudflare-nginx
CF-RAY: 3b8047cd0ca84a7e-GRU

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/myuser/mycode.py", line 79, in <module>
    x = bitfinex.withdraw("BCH", 0.01, 'myaddress')
  File "C:\Users\myuser\AppData\Roaming\Python\Python36\site-packages\ccxt\bitfinex.py", line 373, in withdraw
    name = self.getCurrencyName(currency)
  File "C:\Users\myuser\AppData\Roaming\Python\Python36\site-packages\ccxt\bitfinex.py", line 355, in get_currency_name
    raise NotSupported(self.id + ' ' + currency + ' not supported for withdrawal')
ccxt.base.errors.NotSupported: bitfinex BCH not supported for withdrawal

Process finished with exit code 1
```

**Comment by kroitor** [comment]
Hi, @Felipe-Mangueira ! Looks like they don't support BCH withdrawals at all. Here's a list of currencies you can withdraw:

```
    def get_currency_name(self, currency):
        if currency == 'BTC':
            return 'bitcoin'
        elif currency == 'LTC':
            return 'litecoin'
        elif currency == 'ETH':
            return 'ethereum'
        elif currency == 'ETC':
            return 'ethereumc'
        elif currency == 'OMNI':
            return 'mastercoin'  # ???
        elif currency == 'ZEC':
            return 'zcash'
        elif currency == 'XMR':
            return 'monero'
        elif currency == 'USD':
            return 'wire'
        elif currency == 'DASH':
            return 'dash'
        elif currency == 'XRP':
            return 'ripple'
        elif currency == 'EOS':
            return 'eos'
        raise NotSupported(self.id + ' ' + currency + ' not supported for withdrawal')
```

**Comment by kroitor** [comment]
I'll try to add it now, we'll see if it works.

**Comment by Felipe-Mangueira** [comment]
Ok, thank you @kroitor.

**Comment by kroitor** [comment]
@Felipe-Mangueira can you please update to version 1.9.355 and retry the same code with BCH now? Standing by for your reply.

**Comment by Felipe-Mangueira** [comment]
Sure, I'll do it and I'll reply you soon. Thanks again, @kroitor.

**Comment by Felipe-Mangueira** [comment]
It worked, @kroitor. Thx again.
