### ISSUE TITLE
Bitstamp createOrder failure

### ISSUE THREAD

**Issue by gRittyKitty** [ccxt/ccxt#4629]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Mac + linux
- Programming Language version: node 11.6
- CCXT version: ccxt@1.18.210
- Exchange: Bitstamp
- Method:  createOrder

I'm sending in an order to Bitstamp and it fails.
Here is what I send:
`exchange.createOrder ('BTC/USD', 'limit', 'buy', 0.5, 25)`

And I get back:
```
(node:14204) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at bitstamp.parseOrder (/Users/ari/dev/ccxt/js/bitstamp.js:708:29)
    at bitstamp.createOrder (/Users/ari/dev/ccxt/js/bitstamp.js:457:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

Taking a look at the response from Bitstamp, which is:
```
{ price: '25.00',
  amount: '0.50000000',
  type: '0',
  id: '2847050507',
  datetime: '2019-02-08 16:21:14.326176' }
```

and comparing to code:
createOrder:
  ```
let response = await this[method] (this.extend (request, params));
let order = this.parseOrder (response, market);
```

parseOrder (lines 706-707):
```
  let marketId = this.safeString (order, 'currency_pair');
  marketId = marketId.replace ('/', '');
```

The line number is off by one because I added a diagnostic console.log to my local copy. Clearly there is no key 'currency_pair' in the response object.

I'm going to work on a solution. Please lmk if there already is one or I have something incorrect.

**Comment by gRittyKitty** [comment]
Ok. Should be easy fix.

in createOrder simply add 
`response['currency_pair']=symbol;`
as line 456 in Bitstamp.js

**Comment by gRittyKitty** [comment]
confirmed. This works.
I will commit fix and send pull request.
