### ISSUE TITLE
HuobiPro: privatePostMarginOrdersIdRepay return Signature not valid

### ISSUE THREAD

**Issue by screenzebra** [ccxt/ccxt#4751]
- OS: Ubuntu linux
- Programming Language version: Python 3.6
- CCXT version: ccxt-1.18.296
- Exchange: HuobiPro
- Method: POST

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/virtualenv/core/lib/python3.6/site-packages/ccxt/base/exchange.py", line 385, in inner
    return entry(_self, **inner_kwargs)
  File "/opt/virtualenv/core/lib/python3.6/site-packages/ccxt/base/exchange.py", line 414, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/opt/virtualenv/core/lib/python3.6/site-packages/ccxt/base/exchange.py", line 410, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/opt/virtualenv/core/lib/python3.6/site-packages/ccxt/base/exchange.py", line 513, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/opt/virtualenv/core/lib/python3.6/site-packages/ccxt/huobipro.py", line 899, in handle_errors
    raise exceptions[code](feedback)
ccxt.base.errors.AuthenticationError: huobipro {"status":"error","err-code":"api-signature-not-valid","err-msg":"Signature not valid: Verification failure [\u6821....]","data":null}

**Comment by kroitor** [comment]
I guess, you have resolved it yourself? We will be happy if you report back )
