### ISSUE TITLE
fcoin error ""status":40003,"msg":"invalid symbol"

### ISSUE THREAD

**Issue by Paddy888** [ccxt/ccxt#4837]
- OS: Ubuntu
- Programming Language version: JS
- CCXT version: ccxt@1.18.367
- Exchange: fcoin
- Method: 

Using the arbitrage-pairs.js example I receive the following error as it cycles through the markets when trying to use fcoin. node arbitrage-pairs.js binance fcoin for example. 

{ Error: fcoin {"status":40003,"msg":"invalid symbol"}
    at fcoin.handleErrors (ccxt/examples/js/node_modules/ccxt/js/fcoin.js:565:23)
    at response.text.then (ccxt/examples/js/node_modules/ccxt/js/base/Exchange.js:704:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) constructor: [Function: ExchangeError] }

It worked some months ago, but not any longer.

**Comment by kroitor** [comment]
Just checked and it works on my side:

```
mbp:ccxt igorkroitor$ node examples/js/arbitrage-pairs.js binance fcoin
binance, fcoin
binance loaded 480 markets
fcoin loaded 484 markets
Loaded all markets
symbol    | binance | fcoin
---------------------------
ADA/BTC   | binance | fcoin
ADA/ETH   | binance | fcoin
ADA/USDT  | binance | fcoin
ADX/ETH   | binance | fcoin
AE/ETH    | binance | fcoin
AGI/ETH   | binance | fcoin
AION/ETH  | binance | fcoin
APPC/ETH  | binance | fcoin
ARN/ETH   | binance | fcoin
AST/ETH   | binance | fcoin
BAT/ETH   | binance | fcoin
BCH/BTC   | binance | fcoin
BCH/USDT  | binance | fcoin
BCPT/ETH  | binance | fcoin
BLZ/ETH   | binance | fcoin
BNB/USDT  | binance | fcoin
BQX/ETH   | binance | fcoin
BRD/ETH   | binance | fcoin
BSV/BTC   | binance | fcoin
BSV/USDT  | binance | fcoin
BTC/USDT  | binance | fcoin
CDT/ETH   | binance | fcoin
CHAT/ETH  | binance | fcoin
CMT/ETH   | binance | fcoin
CVC/ETH   | binance | fcoin
DASH/ETH  | binance | fcoin
DENT/ETH  | binance | fcoin
DLT/ETH   | binance | fcoin
EDO/ETH   | binance | fcoin
ELF/ETH   | binance | fcoin
ENG/ETH   | binance | fcoin
ENJ/ETH   | binance | fcoin
EOS/BTC   | binance | fcoin
EOS/ETH   | binance | fcoin
EOS/USDT  | binance | fcoin
ETC/BTC   | binance | fcoin
ETC/ETH   | binance | fcoin
ETC/USDT  | binance | fcoin
ETH/BTC   | binance | fcoin
ETH/USDT  | binance | fcoin
EVX/ETH   | binance | fcoin
FUEL/ETH  | binance | fcoin
FUN/ETH   | binance | fcoin
GTO/ETH   | binance | fcoin
GVT/ETH   | binance | fcoin
HOT/ETH   | binance | fcoin
ICN/ETH   | binance | fcoin
ICX/ETH   | binance | fcoin
INS/ETH   | binance | fcoin
IOST/ETH  | binance | fcoin
IOTA/BTC  | binance | fcoin
IOTA/ETH  | binance | fcoin
IOTA/USDT | binance | fcoin
IOTX/ETH  | binance | fcoin
KEY/ETH   | binance | fcoin
KNC/ETH   | binance | fcoin
LEND/ETH  | binance | fcoin
LINK/ETH  | binance | fcoin
LINK/USDT | binance | fcoin
LOOM/ETH  | binance | fcoin
LRC/ETH   | binance | fcoin
LTC/BTC   | binance | fcoin
LTC/ETH   | binance | fcoin
LTC/USDT  | binance | fcoin
LUN/ETH   | binance | fcoin
MANA/ETH  | binance | fcoin
MCO/ETH   | binance | fcoin
MDA/ETH   | binance | fcoin
MOD/ETH   | binance | fcoin
MTH/ETH   | binance | fcoin
MTL/ETH   | binance | fcoin
NCASH/ETH | binance | fcoin
NPXS/ETH  | binance | fcoin
OAX/ETH   | binance | fcoin
OMG/ETH   | binance | fcoin
OST/ETH   | binance | fcoin
PAX/USDT  | binance | fcoin
POA/ETH   | binance | fcoin
POE/ETH   | binance | fcoin
POWR/ETH  | binance | fcoin
PPT/ETH   | binance | fcoin
QKC/ETH   | binance | fcoin
QSP/ETH   | binance | fcoin
RCN/ETH   | binance | fcoin
RDN/ETH   | binance | fcoin
REP/ETH   | binance | fcoin
REQ/ETH   | binance | fcoin
RLC/ETH   | binance | fcoin
SALT/ETH  | binance | fcoin
SNGLS/ETH | binance | fcoin
SNT/ETH   | binance | fcoin
STORM/ETH | binance | fcoin
SUB/ETH   | binance | fcoin
THETA/ETH | binance | fcoin
TNB/ETH   | binance | fcoin
TRX/BTC   | binance | fcoin
TRX/ETH   | binance | fcoin
TRX/USDT  | binance | fcoin
TUSD/USDT | binance | fcoin
USDC/USDT | binance | fcoin
VET/ETH   | binance | fcoin
VET/USDT  | binance | fcoin
VIB/ETH   | binance | fcoin
VIBE/ETH  | binance | fcoin
WABI/ETH  | binance | fcoin
WTC/ETH   | binance | fcoin
XLM/BTC   | binance | fcoin
XLM/ETH   | binance | fcoin
XLM/USDT  | binance | fcoin
XRP/BTC   | binance | fcoin
XRP/ETH   | binance | fcoin
XRP/USDT  | binance | fcoin
ZEC/ETH   | binance | fcoin
ZIL/ETH   | binance | fcoin
ZRX/ETH   | binance | fcoin
mbp:ccxt igorkroitor$
```

Is your repo up to date?

**Comment by Paddy888** [comment]
I ran npm update in the examples directory. Is there something else I need to do to keep it updated?

**Comment by kroitor** [comment]
> I ran npm update in the examples directory. Is there something else I need to do to keep it updated?

You should `git pull` at least ) 
`npm update` is a completely different thing and should not be run in that folder at all.

**Comment by kroitor** [comment]
- https://stackoverflow.com/questions/1443210/updating-a-local-repository-with-changes-from-a-github-repository
- http://rogerdudler.github.io/git-guide/
- https://www.gitbook.com/

Let us know if that doesn't answer your questions.
