### ISSUE TITLE
negociecoins: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by agemaniac82** [ccxt/ccxt#4855]
- OS: Windows
- CCXT version: 1.8.375
- Exchange: negociecoins
- Method: fetch_balance

I get the following error then trying to fetch_balance()

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    print(neg.fetch_balance())
  File "/home/user/.local/lib/python3.5/site-packages/ccxt/negociecoins.py", line 174, in fetch_balance
    balances = self.privateGetUserBalance(params)
  File "/home/user/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 388, in inner
    return entry(_self, **inner_kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 417, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/user/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 412, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/home/user/.local/lib/python3.5/site-packages/ccxt/negociecoins.py", line 316, in sign
    signature = self.hmac(self.encode(payload), self.encode(secret), hashlib.sha256, 'base64')
  File "/home/user/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 962, in encode
    return string.encode()
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by kroitor** [comment]
@RobsonIto let us know if upgrading to version 1.18.376 helps resolve the issue. It will be available for downloading in 5-10 minutes. We will be happy if you report back whether it helped or not. Thx!

**Comment by agemaniac82** [comment]
Hi @kroitor.

Im getting the following error with the new version (im new to all of this, so sorry if its a newbie error):

```
Request: GET https://broker.negociecoins.com.br/tradeapi/v1/user/balance {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.21.0', 'Authorization': 'amx ca101a18126b4cf7a071e860b841b4ee:1whNyMO/82FBqOhFPFy3dqTvVRas+rKTkYhaja3sYYE=:1552998124817:1552998124'} 

Response: GET https://broker.negociecoins.com.br/tradeapi/v1/user/balance 200 {'Server': 'cloudflare', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Transfer-Encoding': 'chunked', 'Date': 'Tue, 19 Mar 2019 12:22:05 GMT', 'x-frame-options': 'SAMEORIGIN', 'X-Powered-By': 'ASP.NET', 'Set-Cookie': '__cfduid=d1beaf94fa50ec2efbeddc2fd6203ce1a1552998124; expires=Wed, 18-Mar-20 12:22:04 GMT; path=/; domain=.negociecoins.com.br; HttpOnly', 'CF-RAY': '4b9f68e83981c1a9-IAD', 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-cache', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Content-Encoding': 'gzip', 'Expires': '-1'} {"coins":[{"name":"BRL","available":0.0,"openOrders":0.0,"withdraw":0.0,"total":0.0},{"name":"BTC","available":0.0,"openOrders":0.0,"withdraw":0.0,"total":0.0},{"name":"BCH","available":0.0,"openOrders":0.0,"withdraw":0.0,"total":0.0},{"name":"BTG","available":0.0,"openOrders":0.0,"withdraw":0.0,"total":0.0},{"name":"Dash","available":0.0,"openOrders":0.0,"withdraw":0.0,"total":0.0},{"name":"DOGE","available":0.0,"openOrders":0.0,"withdraw":0.0,"total":0.0},{"name":"LEAX","available":0.0,"openOrders":0.0,"withdraw":0.0,"total":0.0},{"name":"LTC","available":0.0,"openOrders":0.0,"withdraw":0.0,"total":0.0},{"name":"B2X","available":0.0,"openOrders":0.0,"withdraw":0.0,"total":0.0}]}
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    print(neg.fetch_balance())
  File "/home/user/.local/lib/python3.5/site-packages/ccxt/negociecoins.py", line 182, in fetch_balance
    'free': float(balance['total']),
TypeError: list indices must be integers or slices, not str
```

**Comment by kroitor** [comment]
Ok, looks like they've changed their `fetchBalance` response format, I've uploaded a fix for that as well, so, i suggest that we do one more round. So, again, please, update to version 1.18.378 (will arrive in 5-10 minutes) and report back, please. Thanks for your help debugging this!

**Comment by agemaniac82** [comment]
@kroitor fetch_balance() now works. Thanks a lot.
It seens that they changed a lot of things: fetch_orders doesnt seen to be working also, but maybe im missing something.

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    orders = neg.fetch_orders()
  File "/home/user/.local/lib/python3.5/site-packages/ccxt/negociecoins.py", line 276, in fetch_orders
    market = self.market(symbol)
  File "/home/user/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 1504, in market
    self.raise_error(ExchangeError, details='No market symbol ' + str(symbol))
  File "/home/user/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 398, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: negociecoins No market symbol None
```

**Comment by kroitor** [comment]
> fetch_orders doesnt seen to be working also, but maybe im missing something.

It requires a symbol argument (first positional argument to fetchOrders), more about it here: https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
