### ISSUE TITLE
Binance - fetch_my_trades - binance requires `apiKey`

### ISSUE THREAD

**Issue by florent8000** [ccxt/ccxt#4936]
- OS: Mac OS
- Programming Language version: Python 3.6
- CCXT version: latest
- Exchange: Binance
- Method: fetch_my_trades

Hi there,

I'm getting a "binance requires `apiKey`" authentification error each time I try to use fetch_my_trade on Binance. Please see log trace below:

Traceback (most recent call last):
  File "/Users/florent/PycharmProjects/light/exchanges/binance.py", line 94, in fetch_my_trades
    my_trades = self.ccxt.fetch_my_trades(symbol, since=rounded, limit=None)
  File "/Users/florent/venvlight/lib/python3.7/site-packages/ccxt/binance.py", line 822, in fetch_my_trades
    response = self.privateGetMyTrades(self.extend(request, params))
  File "/Users/florent/venvlight/lib/python3.7/site-packages/ccxt/base/exchange.py", line 362, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/florent/venvlight/lib/python3.7/site-packages/ccxt/binance.py", line 1129, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/florent/venvlight/lib/python3.7/site-packages/ccxt/base/exchange.py", line 386, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/Users/florent/venvlight/lib/python3.7/site-packages/ccxt/binance.py", line 1056, in sign
    self.check_required_credentials()
  File "/Users/florent/venvlight/lib/python3.7/site-packages/ccxt/base/exchange.py", line 954, in check_required_credentials
    self.raise_error(AuthenticationError, details='requires `' + key + '`')
  File "/Users/florent/venvlight/lib/python3.7/site-packages/ccxt/base/exchange.py", line 372, in raise_error
    raise exception_type(output)
ccxt.base.errors.AuthenticationError: binance requires `apiKey`

I'm fairly certain my apikeys are valid as I'm sending an order that gets executed a second before this. Is this a known issue? 

Thanks in anticipation
Florent

**Comment by kroitor** [comment]
Make sure you have no typos in the names of the options (should be `apiKey`, not `apikey` nor `api_key`):

```
import ccxt
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # as required by the Manual
})
```

- https://github.com/ccxt/ccxt/wiki/Manual#authentication

Let us know if that doesn't help.

**Comment by florent8000** [comment]
I double checked but "apiKey" is correctly typed.

My code is already using private methods (like cancel_order or create_limit_buy_order) before using fetch_my_trade, so it sounds like it's specific to that method but can't figure out why...

Thanks

**Comment by kroitor** [comment]
@florent8000 can you show any code to reproduce it? (without your actual keys, of course)

**Comment by kroitor** [comment]
```Python
print('apiKey:', self.ccxt['apiKey'])
print('secret:', self.ccxt['secret'])
my_trades = self.ccxt.fetch_my_trades(symbol, since=rounded, limit=None)
```

↑ What does it say for `apiKey` and `secret` before the call to `fetch_my_trades`? Are they None or defined?

**Comment by florent8000** [comment]
Hi Kroitor,

See below:

if self.should_login: 
        binance = ccxt.binance({
                    ‘apiKey’: self.settings.get(‘auth’).get(‘pubKey’), 
                    ‘secret’: self.settings.get(‘auth’).get(‘privKey’),
                     }) 
And this is how I call the ccxt function:

    def fetch_my_trades(self, symbol, period_seconds, retry_count=0):
        if self.ccxt is None:
            self.set_exchange_object()

        time_now_seconds = time()
        delta = time_now_seconds - period_seconds
        # convert to milisecond and round
        rounded = round(delta) * 1000
        try:
            my_trades = self.ccxt.fetch_my_trades(symbol, since=rounded)
        except Exception as E:
            self.logger.error('Error fetching my trades! %s %s' % (symbol, E))
            if retry_count == 3:
                raise ValueError('Error fetching my trades after 3 retries! %s' % str(traceback.format_exc()))
            else:
                sleep(0.05)
                retry_count += 1
                return self.fetch_my_trades(symbol, period_seconds, retry_count=retry_count)
        return my_trades

**Comment by florent8000** [comment]
Providing more details on the login part:

    def set_exchange_object(self):
        """
            Login to binance exchange, set binance attr
        """
        super().get_settings(self.exchange_name)
        self.settings = self.get_settings(self.exchange_name)
        if self.should_login:
            binance = ccxt.binance({
                'apiKey': self.settings.get('auth').get('pubKey'),
                'secret': self.settings.get('auth').get('privKey'),
        })
            self.logger.info('logged in, balances: %s', binance.fetch_balance())
        else:
            binance = ccxt.binance()

        self.ccxt = binance

**Comment by kroitor** [comment]
@florent8000 please, do this: https://github.com/ccxt/ccxt/issues/4936#issuecomment-479725159 to check your credentials before `fetch_my_trades`.

**Comment by florent8000** [comment]
Thanks, I ran the code and got this error:

2019-04-05 07:12:26,372 - INFO - odin - Risk - Order '136525300' has been partially filled
2019-04-05 07:12:26,372 - ERROR - binance - Error fetching my trades! XRP/BTC 'binance' object is not subscriptable
2019-04-05 07:12:26,428 - ERROR - binance - Error fetching my trades! XRP/BTC 'binance' object is not subscriptable
2019-04-05 07:12:26,489 - ERROR - binance - Error fetching my trades! XRP/BTC 'binance' object is not subscriptable
2019-04-05 07:12:26,544 - ERROR - binance - Error fetching my trades! XRP/BTC 'binance' object is not subscriptable
2019-04-05 07:12:26,548 - ERROR - odin - Error in quote engine! Error fetching my trades after 3 retries! Traceback (most recent call last):
  File "/Users/florent/PycharmProjects/light/exchanges/binance.py", line 94, in fetch_my_trades
    print('apiKey:', self.ccxt['apiKey'])
TypeError: 'binance' object is not subscriptable

**Comment by kroitor** [comment]
@florent8000 sorry there's a typo in it, can you please redo this slightly changed test again? ↓

```Python
print('apiKey:', self.ccxt.apiKey)  # slightly edited these lines
print('secret:', self.ccxt.secret)  # slightly edited these lines
my_trades = self.ccxt.fetch_my_trades(symbol, since=rounded, limit=None)
```

**Comment by florent8000** [comment]
I've ran again with the edit and you're right the keys are None:

2019-04-05 11:35:02,407 - INFO - odin - Risk - Order '136593644' has been fully filled
apiKey: 
secret: 
2019-04-05 11:35:02,408 - ERROR - binance - Error fetching my trades! XRP/BTC binance requires `apiKey`
apiKey: 
secret: 
2019-04-05 11:35:02,459 - ERROR - binance - Error fetching my trades! XRP/BTC binance requires `apiKey`
apiKey: 
secret: 
2019-04-05 11:35:02,515 - ERROR - binance - Error fetching my trades! XRP/BTC binance requires `apiKey`
apiKey: 
secret: 
2019-04-05 11:35:02,570 - ERROR - binance - Error fetching my trades! XRP/BTC binance requires `apiKey`

Any idea why this happens for this method and not the others?

thanks

**Comment by kroitor** [comment]
> Any idea why this happens for this method and not the others?

Yes this has something to do with the way you initialize and reinitialize the exchange. In other words, some part of your code is either redefining the values in runtime, but it's hard to tell without actually diving into your code... If you can make a short snippet of 10-20 lines to reproduce the issue (a short but a complete program) – i'd be able to tell the exact cause and fix...

**Comment by florent8000** [comment]
ok will look into this and post the solution here when found. Thanks the help!

**Comment by florent8000** [comment]
The issue was really specific to my code, I have a middleware layer that connects to the exchange and the fetch_my_trade function wasn't called via the middleware...

Sorry for wasting your time and thanks a lot for the help!

**Comment by kroitor** [comment]
@florent8000 no worries, let us know if you notice anything suspicious! Thx for reporting back, appreciate that!

**Comment by franklinchukwu** [comment]
@kroitor pls help
import ccxt
import xxxx

bybit1 = ccxt.bybit({
    'enableRateLimit':True,
    'apikey':xxxx.bybit_key,
    'secret':xxxx.bybit_secret
})
print(bybit1.fetch_balance())



Traceback (most recent call last):
  File "c:\Users\Franklin\Documents\#####ALL MIGHTY CODE######\######PYTHON PROJECTS######\IQ OPTION BOT 1\python\test2.py", line 9, in <module>
    print(bybit1.fetch_balance())
  File "C:\Users\Franklin\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 3025, in fetch_balance
    enableUnifiedMargin = self.is_unified_margin_enabled()
  File "C:\Users\Franklin\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 845, in is_unified_margin_enabled
    response = self.privateGetUserV3PrivateQueryApi(params)
  File "C:\Users\Franklin\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 501, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Franklin\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2759, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\Franklin\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2755, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "C:\Users\Franklin\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\bybit.py", line 6625, in sign
    self.check_required_credentials()
  File "C:\Users\Franklin\AppData\Local\Programs\Python\Python310\lib\site-packages\ccxt\base\exchange.py", line 2902, in check_required_credentials
    raise AuthenticationError(self.id + ' requires "' + key + '" credential')
ccxt.base.errors.AuthenticationError: bybit requires "apiKey" credential
