### ISSUE TITLE
Error while fetching Bitz tickers

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#4958]
- OS: Linux Ubuntu 18.04.2 LTS
- Programming Language version: Python 3.6.4
- CCXT version: 1.18.443
- Exchange: Bitz
- Method: fetch_tickers()

Hello,

I'm facing an error with Bitz where it works just fine with other exchanges:

```
bitz = getattr(ccxt, 'bitz')
bitz().fetch_tickers()
```

What could be the reason? 

Thank you,

**Comment by kroitor** [comment]
Hi! Without enough information from you it will be hard to help you:

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

We need to see the error and your verbose request/response as described there ↑

**Comment by Kinzowa** [comment]
Hi Igor,

Please find the verbose output :+1: 
```
bitz.verbose
Out[195]: True

bitz().fetch_tickers()

Request: GET https://apiv2.bitz.com/Market/symbolList {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):

  File "<ipython-input-196-78c9b3b88076>", line 1, in <module>
    bitz().fetch_tickers()

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/ccxt/bitz.py", line 448, in fetch_tickers
    self.load_markets()

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1082, in load_markets
    markets = self.fetch_markets(params)

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/ccxt/bitz.py", line 221, in fetch_markets
    response = self.marketGetSymbolList()

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 388, in inner
    return entry(_self, **inner_kwargs)

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 417, in request
    return self.fetch2(path, api, method, params, headers, body)

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 413, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 514, in fetch
    self.raise_error(ExchangeError, url, method, e)

  File "/home/bragar/anaconda3/lib/python3.6/site-packages/ccxt/base/exchange.py", line 398, in raise_error
    raise exception_type(output)

ExchangeError: bitz https://apiv2.bitz.com/Market/symbolList GET HTTPSConnectionPool(host='apiv2.bitz.com', port=443): Max retries exceeded with url: /Market/symbolList (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feccc825908>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

**Comment by Kinzowa** [comment]
Hi Igor, I confirm `apiv2.bitz.com` has connection issue from time to time but I've found several API servers for Bitz and some others are responding better :

```
API Available domain name
https://apiv2.bitz.com
https://apiv2.bit-z.pro
https://api.bitzapi.com
https://api.bitzoverseas.com
https://api.bitzspeed.com
```

**Comment by kroitor** [comment]
@Kinzowa we will test those as well, thx so much for the feedback!
