### ISSUE TITLE
CEX cancelOrder

### ISSUE THREAD

**Issue by ekfn** [ccxt/ccxt#5011]
- OS: `ubuntu 16`
- Programming Language version: `node v11.6.0`
- CCXT version: `1.18.482`
- Exchange: `cex`
- Method: `cancelOrder`

```
fetch:
 cex POST https://cex.io/api/cancel_order/ 
Request:
 { 'Content-Type': 'application/x-www-form-urlencoded' } 
handleRestResponse:
 cex POST https://cex.io/api/cancel_order/ 200 OK 
Response:
 { Date: 'Sun, 21 Apr 2019 10:03:00 GMT',
  'Content-Type': 'text/json',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'X-Frame-Options': 'DENY',
  Vary: 'Accept-Encoding' } 
 true 

TypeError: Cannot use 'in' operator to search for 'e' in true
    at cex.request (.../ccxt/js/cex.js:533:24)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by kroitor** [comment]
@ekfn can you please post your verbose request/response? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by ekfn** [comment]
Sorry I didn't do it right away.

**Comment by ekfn** [comment]
```
        let response = await this.fetch2 (path, api, method, params, headers, body);

        if (!response) {
            throw new NullResponse (this.id + ' returned ' + this.json (response));
        } else if (response === true) {
            return response;
        } else if ('e' in response) {
```

Problem is that `response` in this case is string "true" and not boolean `true`
