### ISSUE TITLE
JS setSandboxMode UnhandledPromiseRejectionWarning: Error: bitmex GET [object Object]/api/v1/XXX  only absolute urls are supported

### ISSUE THREAD

**Issue by justinchou** [ccxt/ccxt#5041]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Linux And MacOS
- Programming Language version: JS
- CCXT version: ccxt@1.18.439
- Exchange: bitmex
- Method: setSandboxMode

After I Use `setSandboxMode` to set the sanbox mode, the process crashed, and throw out the following message：

```
(node:17760) UnhandledPromiseRejectionWarning: Error: bitmex GET [object Object]/api/v1/instrument/activeAndIndices  only absolute urls are supported
    at fetchImplementation.catch.e (/home/dev/projects/quant-ccxt/node_modules/ccxt/js/base/Exchange.js:472:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:17760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I check the code and find the `close` function in `js/base/Exchange.js` line 487 and 488 maybe not a good solution.

```js
    setSandboxMode (enabled) {
        if (!!enabled) {
            if (this.urls['test']) {
                this.urls['api_backup'] = `${this.urls['api']}`
                this.urls['api'] = `${this.urls['test']}`
            } else {
                throw new NotSupported (this.id + ' does not have a sandbox URL')
            }
        } else if ('api_backup' in this.urls) {
            this.urls['api'] = `${this.urls['api_backup'])}`
        }
    }
```

Maybe this solve the problem.

**Comment by kroitor** [comment]
Hi! Thanks for reporting! Answered on your PR here: https://github.com/ccxt/ccxt/pull/5042#issuecomment-487785550
