### ISSUE TITLE
Mercado FetchOHLCV dict object has no attribute id 

### ISSUE THREAD

**Issue by ahmedbodi** [ccxt/ccxt#5057]
- OS: Ubuntu 18.04 (WSL)
- Programming Language version: Python 2.7
- CCXT version: 1.18.497
- Exchange: Mercado
- Method: fetchOHLCV

```
ERROR:exchange.ohlcv:'dict' object has no attribute 'id'
Traceback (most recent call last):
  File "/mnt/d/apache/contrib/exchange/ohlcv.py", line 26, in _run
    ohlcv = getattr(self.client, self.METHOD)(market, timeframe)
  File "/home/ahmedbodi/.local/lib/python2.7/site-packages/ccxt/base/exchange.py", line 1301, in fetchOHLCV
    return self.fetch_ohlcv(symbol, timeframe, since, limit, params)
  File "/home/ahmedbodi/.local/lib/python2.7/site-packages/ccxt/mercado.py", line 395, in fetch_ohlcv
    'coin': market.id.lower(),
AttributeError: 'dict' object has no attribute 'id'
```

**Comment by kroitor** [comment]
@ahmedbodi thx for reporting! Appreciate your help!
