### ISSUE TITLE
BitMEX editOrder Error

### ISSUE THREAD

**Issue by Tezeug** [ccxt/ccxt#5193]
- OS: iOS 12.3.1 (iPad)
- Programming Language version: Python 3.7
- CCXT version: 1.18.575
- Exchange: BitMEX
- Method: editOrder

Hello.
I have tried to edit an order on BitMEX but got this error. I am not exactly sure what it could be cause by but the same code has worked for the DeriBit exchange (I know that the code is a bit different for every exchange but according to the bitmex.py it should be there). Check it out below, please. Thank you very much.

EditOrderBuy1 = Exchange.editLimitBuyOrder(BIDL[0], Symbol, OA1, PB1)

(All variables are correctly defined.)

Traceback (most recent call last):
  File "Documents/modules/ccxt/base/exchange.py", line 511, in fetch
    response.raise_for_status()
  File "Pyto.app/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Documents/Ver3MEX.py", line 183, in <module>
    EditOrderBuy1 = Exchange.editLimitBuyOrder(BIDL[0], Symbol, OA1, PB1)
  File "Documents/modules/ccxt/base/exchange.py", line 1523, in edit_limit_buy_order
    return self.edit_limit_order(id, symbol, 'buy', *args)
  File "Documents/modules/ccxt/base/exchange.py", line 1529, in edit_limit_order
    return self.edit_order(id, symbol, 'limit', *args)
  File "Documents/modules/ccxt/bitmex.py", line 860, in edit_order
    response = self.privatePutOrder(self.extend(request, params))
  File "Documents/modules/ccxt/base/exchange.py", line 406, in inner
    return entry(_self, **inner_kwargs)
  File "Documents/modules/ccxt/base/exchange.py", line 435, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "Documents/modules/ccxt/base/exchange.py", line 431, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "Documents/modules/ccxt/base/exchange.py", line 523, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "Documents/modules/ccxt/bitmex.py", line 920, in handle_errors
    raise BadRequest(feedback)
ccxt.base.errors.BadRequest: bitmex {"error":{"message":"Invalid ordStatus","name":"HTTPError"}}

**Comment by Tezeug** [comment]
But it really looks like there is not such option on BitMEX to edit the order. (On the site and even in the REST API Explorer but I can be looking wrong.)

**Comment by brandsimon** [comment]
In the REST API Explorer there should be a put method to edit the order. It works for me on the real bitmex exchange.

**Comment by Tezeug** [comment]
Thank you, I’ll try it.

**Comment by kroitor** [comment]
@Tezeug can you please paste the [verbose request and verbose response](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) for it?

**Comment by Tezeug** [comment]
EditOrderBuy1 = Exchange.privatePutOrder(id=BIDL, symbol=Symbol, type="limit", side="buy", amount=55, price=PB1, params={})

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/F9A7FA6C-C645-49D1-9B23-19D317A5DEBA/Pythonista3/Documents/NewLogicBetter/Untitled.py", line 10, in <module>
    EditOrderBuy1 = Exchange.privatePutOrder(id=BIDL, symbol=Symbol, type="limit", side="buy", amount=55, price=PB1, params={})
TypeError: inner() got an unexpected keyword argument 'id'
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/F9A7FA6C-C645-49D1-9B23-19D317A5DEBA/Pythonista3/Documents/NewLogicBetter/Untitled.py", line 10, in <module>
    EditOrderBuy1 = Exchange.privatePutOrder(id=BIDL, symbol=Symbol, type="limit", side="buy", amount=55, price=PB1, params={})
TypeError: inner() got an unexpected keyword argument 'id'

**Comment by Tezeug** [comment]
The verbose output is extremely long. Basically I have placed one limit order at some price, then put the ID into a variable and then tried to update it this way but it has just placed another order with the same price as the first one.

**Comment by kroitor** [comment]
@Tezeug 

> EditOrderBuy1 = Exchange.privatePutOrder(id=BIDL, symbol=Symbol, type="limit", side="buy", amount=55, price=PB1, params={})

↑ This is incorrect, you're using the `privatePutOrder`[implicit method](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods), but instead of passing the exchange-specific params, you're passing arguments for a unified `editOrder` method.

Make sure `.verbose = True` is done after `load_markets()`.

Let's do this:

```Python
import ccxt
from pprint import pprint

exchange = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

exchange.load_markets ()  #  add this

exchange.verbose = True  # add this

# and then:

order_id = YOUR_ORDER_ID
symbol = YOUR_SYMBOL
type = 'limit'
side = 'buy'
amount = 55
price = YOUR_PRICE

order = exchange.edit_order (id, symbol, type, side, amount, price)
print(order)
```

↑ And paste the output here.

**Comment by Tezeug** [comment]
This has placed just the first order and has not edited it.

Request: POST https://testnet.bitmex.com/api/v1/order {'Content-Type': 'application/json', 'api-key': 'thMNbVMWH9lH7MMuRMe1aYSo', 'api-expires': '1558990287', 'api-signature': '854fbcd6ad04ca0bea4d83fee8559a6ed4090f09e198767dd87f5925616c39a3', 'Accept-Encoding': 'gzip, deflate'} {"symbol":"XBTUSD","side":"Buy","orderQty":55,"ordType":"Limit","price":8500}

Response: POST https://testnet.bitmex.com/api/v1/order 200 {'Date': 'Mon, 27 May 2019 20:51:22 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '702', 'Connection': 'keep-alive', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '59', 'X-RateLimit-Reset': '1558990283', 'X-Powered-By': 'Profit', 'ETag': 'W/"2be-9pm/Es5yNXAejcruHKONML3UNU0"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'} {"orderID":"5d1f10f9-8162-f886-ed16-37681e13b2fa","clOrdID":"","clOrdLinkID":"","account":200924,"symbol":"XBTUSD","side":"Buy","simpleOrderQty":null,"orderQty":55,"price":8500,"displayQty":null,"stopPx":null,"pegOffsetValue":null,"pegPriceType":"","currency":"USD","settlCurrency":"XBt","ordType":"Limit","timeInForce":"GoodTillCancel","execInst":"","contingencyType":"","exDestination":"XBME","ordStatus":"New","triggered":"","workingIndicator":true,"ordRejReason":"","simpleLeavesQty":null,"leavesQty":55,"simpleCumQty":null,"cumQty":0,"avgPx":null,"multiLegReportingType":"SingleSecurity","text":"Submitted via API.","transactTime":"2019-05-27T20:51:22.295Z","timestamp":"2019-05-27T20:51:22.295Z"}
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/F9A7FA6C-C645-49D1-9B23-19D317A5DEBA/Pythonista3/Documents/NewLogicBetter/Untitled.py", line 24, in <module>
    order = Exchange.edit_order (id, symbol, type, side, amount, price)
  File "/private/var/mobile/Containers/Shared/AppGroup/F9A7FA6C-C645-49D1-9B23-19D317A5DEBA/Pythonista3/Documents/site-packages-3/ccxt/bitmex.py", line 860, in edit_order
    response = self.privatePutOrder(self.extend(request, params))
  File "/private/var/mobile/Containers/Shared/AppGroup/F9A7FA6C-C645-49D1-9B23-19D317A5DEBA/Pythonista3/Documents/site-packages-3/ccxt/base/exchange.py", line 406, in inner
    return entry(_self, **inner_kwargs)
  File "/private/var/mobile/Containers/Shared/AppGroup/F9A7FA6C-C645-49D1-9B23-19D317A5DEBA/Pythonista3/Documents/site-packages-3/ccxt/base/exchange.py", line 435, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/private/var/mobile/Containers/Shared/AppGroup/F9A7FA6C-C645-49D1-9B23-19D317A5DEBA/Pythonista3/Documents/site-packages-3/ccxt/base/exchange.py", line 430, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/private/var/mobile/Containers/Shared/AppGroup/F9A7FA6C-C645-49D1-9B23-19D317A5DEBA/Pythonista3/Documents/site-packages-3/ccxt/bitmex.py", line 951, in sign
    body = self.json(params)
  File "/private/var/mobile/Containers/Shared/AppGroup/F9A7FA6C-C645-49D1-9B23-19D317A5DEBA/Pythonista3/Documents/site-packages-3/ccxt/base/exchange.py", line 970, in json
    return json.dumps(data, separators=(',', ':'))
  File "/var/containers/Bundle/Application/C6C275FD-4F6C-4E12-99DC-E2D5A6E37715/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/json/__init__.py", line 239, in dumps
    **kw).encode(obj)
  File "/var/containers/Bundle/Application/C6C275FD-4F6C-4E12-99DC-E2D5A6E37715/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/var/containers/Bundle/Application/C6C275FD-4F6C-4E12-99DC-E2D5A6E37715/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
  File "/var/containers/Bundle/Application/C6C275FD-4F6C-4E12-99DC-E2D5A6E37715/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/json/encoder.py", line 181, in default
    o.__class__.__name__)
TypeError: Object of type 'builtin_function_or_method' is not JSON serializable

**Comment by Tezeug** [comment]
OrderBuy1 = Exchange.createOrder(symbol="BTC/USD", type="limit", side="buy", amount=55, price=8500, params={})
idd = OrderBuy1["id"]

from pprint import pprint


Exchange.load_markets ()  #  add this

Exchange.verbose = True  # add this

# and then:

order_id = idd
symbol = "BTC/USD"
type = 'limit'
side = 'buy'
amount = 55
price = 8554

order = Exchange.edit_order (id, symbol, type, side, amount, price)
print(order)

**Comment by Tezeug** [comment]
BitMEX TESTNET exchange.

**Comment by kroitor** [comment]
@Tezeug ok, but plz use the [markdown](https://guides.github.com/features/mastering-markdown/) for readability next time as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue )

&#096;&#096;&#096;Python
your code
&#096;&#096;&#096;

or 

&#096;&#096;&#096;
your output
&#096;&#096;&#096;

I will need some time to check on my iPad with Python3.7 and Pythonista... Do you have a Windows or a MacOS host somewhere around you to check if you can reproduce the issue there as well? That would help narrow it down.

**Comment by Tezeug** [comment]
I was currently testing it on the Pythonista 3 latest beta version with Python 3.6.1 libraries and the newest ccxt pip module installed through the StaSh. I do not have any Windows PC but I have a classic ultrabook with Kubuntu 19.04 64-bit. I will try it there tomorrow and post the results. But everything should work the same on the iPad.

**Comment by Tezeug** [comment]
Just search for Pythonista 3 TestFlight, there should be an official link on the creator`s Twitter account where you can download the latest version for free and test it. Otherwise there is an official release in the App Store for about 9.99 $ but it has been updated for quite a long time and I guess it will not be optimized for the new iPads and iPads Pro but I will probably buy it as well to support the developer. It is a very good application and IDE.

**Comment by Tezeug** [comment]
Just some news: works well in the latest version. You've done a great job.

**Comment by kroitor** [comment]
@Tezeug thx for the followup, we appreciate all feedback!
