### ISSUE TITLE
Error creating order in DX with Python2

### ISSUE THREAD

**Issue by magoarcano** [ccxt/ccxt#5329]
In Python 2 I get the error:
```
exchange.py", line 605, in safe_integer
    if isinstance(value, Number) or (isinstance(value, basestring) and value.isnumeric()):
AttributeError: 'str' object has no attribute 'isnumeric'
```
For Python 2 I can fix it doing `unicode(value).isnumeric()`, but I'm not sure how does it affect to Python3 implementation

- OS: OS X
- Programming Language version: Python
- CCXT version: 1.18.723
- Exchange: DX
- Method: create_order()

**Comment by kroitor** [comment]
@magoarcano hi! Can you please paste the entire call stack for this error?

**Comment by magoarcano** [comment]
Thanks @kroitor I'm using Python 2.7

```
>>> order = dx.create_order('ETH/BTC', 'limit', 'sell', 0.035, 0.025540)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arcano/startups/pyramidenv/lib/python2.7/site-packages/ccxt/dx.py", line 431, in create_order
    'quantity': self.number_to_object(amount),
  File "/Users/arcano/startups/pyramidenv/lib/python2.7/site-packages/ccxt/dx.py", line 163, in number_to_object
    'value': self.safe_integer({'a': valueStr}, 'a', None),
  File "/Users/arcano/startups/pyramidenv/lib/python2.7/site-packages/ccxt/base/exchange.py", line 605, in safe_integer
    if isinstance(value, Number) or (isinstance(value, basestring) and value.isnumeric()):
AttributeError: 'str' object has no attribute 'isnumeric'
>>> dx.verbose=True
>>> order = dx.create_order('ETH/BTC', 'limit', 'sell', 0.035, 0.025540)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arcano/startups/pyramidenv/lib/python2.7/site-packages/ccxt/dx.py", line 431, in create_order
    'quantity': self.number_to_object(amount),
  File "/Users/arcano/startups/pyramidenv/lib/python2.7/site-packages/ccxt/dx.py", line 163, in number_to_object
    'value': self.safe_integer({'a': valueStr}, 'a', None),
  File "/Users/arcano/startups/pyramidenv/lib/python2.7/site-packages/ccxt/base/exchange.py", line 605, in safe_integer
    if isinstance(value, Number) or (isinstance(value, basestring) and value.isnumeric()):
AttributeError: 'str' object has no attribute 'isnumeric'

```

**Comment by ttodua** [comment]
This exchange is no longer a part of CCXT. Closing the issue.
