### ISSUE TITLE
oceanex TypeError: key: expected bytes or bytearray, but got 'str' with JWT in Python3

### ISSUE THREAD

**Issue by vxnuke** [ccxt/ccxt#5342]
Private calls don't work.

'''
Traceback (most recent call last):
  File "china_oceanex.py", line 107, in <module>
    balances = exchange.fetch_balance()
  File "/usr/local/lib/python3.7/dist-packages/ccxt/oceanex.py", line 442, in fetch_balance
    response = self.privateGetMembersMe(params)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 421, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 450, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 445, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/oceanex.py", line 621, in sign
    jwt_token = self.jwt(request, self.secret, 'RS256')
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 981, in jwt
    signature = Exchange.rsa(token, secret, alg)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 995, in rsa
    priv_key = load_pem_private_key(Exchange.encode(secret), None, backends.default_backend())
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 1014, in encode
    return string.encode()
AttributeError: 'bytes' object has no attribute 'encode'
'''

Same issue as https://github.com/ccxt/ccxt/issues/5340

**Comment by kroitor** [comment]
This is fixed in the most recent version, just update your CCXT and it should work. Let us know if not.

**Comment by developerBO** [comment]
File "P:\ccxt\example1\venv\lib\site-packages\ccxt\base\exchange.py", line 456, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "P:\ccxt\example1\venv\lib\site-packages\ccxt\oceanex.py", line 620, in sign
    jwt_token = self.jwt(request, self.encode(self.secret), 'RS256')
  File "P:\ccxt\example1\venv\lib\site-packages\ccxt\base\exchange.py", line 1025, in encode
    return string.encode()
AttributeError: 'bytes' object has no attribute 'encode'

changing 
jwt_token = self.jwt(request, self.encode(self.secret), 'RS256') 
to 
jwt_token = self.jwt(request, self.secret, 'RS256')
in oceanex.py (ccxt version is 1.18.840)
works for me. I'm loading the pem key using "with open" and assign it to exchange.secret

**Comment by kroitor** [comment]
@developerBO the lib expects a string `secret`, however, so, for the purposes of unification, you need to convert it to a string after reading from file.

**Comment by vxnuke** [comment]
I have been using
```
with open("auth/oceanex/private.pem", "rb") as private_file:
    exchange.secret = private_file.read()
```
Is that good or should i be doing something else? I had to change code to  `
jwt_token = self.jwt(request, self.secret, 'RS256')` in ccxt lib to make it work.

**Comment by kroitor** [comment]
@vxnuke If you add `decode` it should work without editing your 

```Python
with open("auth/oceanex/private.pem", "rb") as private_file:
    exchange.secret = private_file.read().decode()
```

More about `bytes` vs `str` in Python: https://stackoverflow.com/questions/22677217/what-is-the-difference-between-a-unicode-and-binary-string

**Comment by vxnuke** [comment]
@kroitor .decode() sorted it cheers :)
