### ISSUE TITLE
okex authentication error in latest version 

### ISSUE THREAD

**Issue by yurenji** [ccxt/ccxt#5405]
- OS: mac/ubuntu
- Programming Language version: python 3.6.5
- CCXT version: latest
- Exchange: okex
- Method: 
```
okex = ccxt.okex({
    'apiKey': '',
    'secret': '',
})
result = okex.createMarketBuyOrder('ETH/USDT', 0.01, {'cost':3})
```
error: 
```
Traceback (most recent call last):
  File "test-okex-rest.py", line 20, in <module>
    result = okex.createMarketBuyOrder('ETH/USDT', 0.01, {'cost':3})
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1621, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/okcoinusd.py", line 765, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/base/exchange.py", line 433, in inner
    return entry(_self, **inner_kwargs)
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/base/exchange.py", line 462, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/base/exchange.py", line 458, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/base/exchange.py", line 562, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/okcoinusd.py", line 1031, in handle_errors
    raise ExceptionClass(message)
ccxt.base.errors.AuthenticationError: okex {"result":false,"error_code":10007}
```

My app is using an older version ccxt==1.18.478 in production, which doesn't have this problem. Hope you can look into this ASAP, I'd like to integrate with the latest version, which enables okex v3 api.

**Comment by kroitor** [comment]
Can you paste your verbose request/response (without your keys)?

```Python
okex = ccxt.okex({
    'apiKey': '',
    'secret': '',
})
okex.load_markets()
okex.verbose = True
result = okex.createMarketBuyOrder('ETH/USDT', 0.01, {'cost':3})
```

> I'd like to integrate with the latest version

Which particular version number do you mean? The latest is 1.18.856 (released an hour ago for KuCoin edits), and the OKEX implementation does not differ from 1.18.855 to 1.18.856.

> which enables okex v3 api.

To use okex3 you just need to 

```Python
exchange = ccxt.okex3({  # ← okex3 here
    'apiKey': '',
    'secret': '',
})
```

**Comment by yurenji** [comment]
sorry for the confusion, the old version is 1.18.478.

**Comment by kroitor** [comment]
@yurenji no worries ) It would be great if you could paste your verbose request+response with version 1.18.478 and your verbose request+response with version 1.18.855 here. That would help fix it quicker.

**Comment by yurenji** [comment]
1.18.855
```
Request: POST https://www.okex.com/api/v1/trade.do {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} amount=0.01&api_key=xxx&price=3.0&symbol=eth_usdt&type=buy_market&sign=7BCE6BA59E139D41BCBDB387FE089F4C

Response: POST https://www.okex.com/api/v1/trade.do 200 {'Content-Type': 'application/json', 'Content-Length': '35', 'Connection': 'keep-alive', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Set-Cookie': 'locale=en_US; Max-Age=604800; Expires=Mon, 08-Jul-2019 06:16:37 GMT; Path=/', 'X-RateLimit-Limit': '100', 'X-RateLimit-Remaining': '99', 'X-RateLimit-Used': '1', 'X-RateLimit-Reset': '1561961799541', 'Date': 'Mon, 01 Jul 2019 06:16:37 GMT', 'X-Kong-Upstream-Latency': '29', 'X-Kong-Proxy-Latency': '0', 'Via': 'kong/0.12.3'} {"result":false,"error_code":10007}
Traceback (most recent call last):
  File "test-okex.py", line 22, in <module>
    result = okex.createMarketBuyOrder('ETH/USDT', 0.01, {'cost':3})
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1621, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/okcoinusd.py", line 765, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/base/exchange.py", line 433, in inner
    return entry(_self, **inner_kwargs)
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/base/exchange.py", line 462, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/base/exchange.py", line 458, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/base/exchange.py", line 562, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/root/.pyenv/versions/test-okex/lib/python3.6/site-packages/ccxt/okcoinusd.py", line 1031, in handle_errors
    raise ExceptionClass(message)
ccxt.base.errors.AuthenticationError: okex {"result":false,"error_code":10007}
```

**Comment by yurenji** [comment]
1.18.478
```
Request: POST https://www.okex.com/api/v1/trade.do {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} amount=0.01&api_key=xxx&symbol=eth_usdt&type=sell_market&sign=40AD7861A60251A90641465A661E3FD5

Response: POST https://www.okex.com/api/v1/trade.do 200 {'Content-Type': 'application/json', 'Content-Length': '43', 'Connection': 'keep-alive', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Set-Cookie': 'locale=en_US; Max-Age=604800; Expires=Mon, 08-Jul-2019 06:19:52 GMT; Path=/', 'X-RateLimit-Limit': '100', 'X-RateLimit-Remaining': '99', 'X-RateLimit-Used': '1', 'X-RateLimit-Reset': '1561961994521', 'Date': 'Mon, 01 Jul 2019 06:19:51 GMT', 'X-Kong-Upstream-Latency': '16', 'X-Kong-Proxy-Latency': '0', 'Via': 'kong/0.12.3'} {"result":true,"order_id":3095002646256640}
```

**Comment by kroitor** [comment]
@yurenji for some reason you've posted sell market for 1.18.478, can you please post a buy-market verbose request+response for it?

**Comment by yurenji** [comment]
1.18.478  delete the buy one and updated with a sell example: 
```
Request: POST https://www.okex.com/api/v1/trade.do {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} api_key=xxx&price=3.0&symbol=eth_usdt&type=buy_market&sign=9771DB83F99DCE4B6679907F6ECD6C47

Response: POST https://www.okex.com/api/v1/trade.do 200 {'Content-Type': 'application/json', 'Content-Length': '43', 'Connection': 'keep-alive', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Set-Cookie': 'locale=en_US; Max-Age=604800; Expires=Mon, 08-Jul-2019 07:05:14 GMT; Path=/', 'X-RateLimit-Limit': '100', 'X-RateLimit-Remaining': '99', 'X-RateLimit-Used': '1', 'X-RateLimit-Reset': '1561964716539', 'Date': 'Mon, 01 Jul 2019 07:05:13 GMT', 'X-Kong-Upstream-Latency': '42', 'X-Kong-Proxy-Latency': '0', 'Via': 'kong/0.12.3'} {"result":true,"order_id":3095181036494848}
```

**Comment by kroitor** [comment]
@yurenji This issue with OKEX v1 createMarketBuyOrder is fixed in version 1.18.859+. It will arrive in 15 minutes as soon as the automatic build finishes. Let us know if you have any difficulties with it after updating to 1.18.859. We will be happy if you report back whether it did resolve the issue for you or not. Thanks for your involvement!

**Comment by yurenji** [comment]
Thanks for the quick response! I can confirm the issue is fixed.

**Comment by kroitor** [comment]
@yurenji fantastic! Thx so much for reporting!
