### ISSUE TITLE
okex fetch_ohlcv symbol error in latest version 

### ISSUE THREAD

**Issue by yurenji** [ccxt/ccxt#5410]
- OS: mac/ubuntu 16.04
- Programming Language version: python
- CCXT version: latest
- Exchange: okex
- Method: fetch_ohlcv() 

```
okex = ccxt.okex({
    'apiKey': '',
    'secret': '',
})

result = okex.fetch_ohlcv('ETH/USD', 1561708800000, None, '15m', {'contract_type': 'this_week'})
```
The above code works for 1.18.478, but throws error for 1.18.859

```
Traceback (most recent call last):
  File "test_okex.py", line 10, in <module>
    result = okex.fetch_ohlcv('ETH/USD', since=1561708800000, timeframe='15m', params={'contract_type': 'this_week'})
  File "/home/ubuntu/.pyenv/versions/bricks/lib/python3.6/site-packages/ccxt/okcoinusd.py", line 700, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/ubuntu/.pyenv/versions/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1573, in market
    self.raise_error(ExchangeError, details='No market symbol ' + str(symbol))
  File "/home/ubuntu/.pyenv/versions/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 443, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: okex No market symbol ETH/USD
```

**Comment by yurenji** [comment]
1.18.859 verbose info

```
Request: GET https://www.okex.com/v2/spot/markets/products {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'}
None

Response: GET https://www.okex.com/v2/spot/markets/products 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Co
nnection': 'keep-alive', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Con
trol': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Set-Cookie':
'locale=en_US; Max-Age=604800; Expires=Mon, 08-Jul-2019 10:03:33 GMT; Path=/', 'Date': 'Mon, 01 Jul 2019 10:03:32 GMT', 'X-Kong-Upstream
-Latency': '10', 'X-Kong-Proxy-Latency': '0', 'Via': 'kong/0.12.3', 'Content-Encoding': 'gzip'} {"code":0,"data":[{"baseCurrency":0,"bro
kerId":0,"callAuctionOrCallNoCancelAuction":false,"callNoCancelSwitchTime":1559463000000,"collect":"0","continuousSwitchTime":1559463600
000,"groupId":1,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":1005,"maxMarginLeverage":0,
"maxPriceDigit":1,"maxSizeDigit":8,"mergeTypes":"0.1,1,10","minTradeSize":0.00100000,"online":1,"productId":905,"quoteCurrency":1063,"qu
oteIncrement":"0.1","quotePrecision":2,"sort":30000,"symbol":"btc_usdk","tradingMode":3},{"baseCurrency":0,"brokerId":0,"callAuctionOrCa
llNoCancelAuction":false,"callNoCancelSwitchTime":{},"collect":"0","continuousSwitchTime":{},"groupId":1,"isMarginOpen":true,"listDispla
y":0,"marginRiskPreRatio":1.2,"marginRiskRatio":1.1,"marketFrom":118,"maxMarginLeverage":5,"maxPriceDigit":1,"maxSizeDigit":8,"mergeType
s":"0.1,1,10","minTradeSize":0.00100000,"online":1,"productId":20,"quoteCurrency":7,"quoteIncrement":"0.1","quotePrecision":2,"sort":300
38,"symbol":"btc_usdt","tradingMode":3},{"baseCurrency":1,"brokerId":0,"callAuctionOrCallNoCancelAuction":false,"callNoCancelSwitchTime"
:1559463000000,"collect":"0","continuousSwitchTime":1559463600000,"groupId":1,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":
0,"marginRiskRatio":0,"marketFrom":1009,"maxMarginLeverage":0,"maxPriceDigit":2,"maxSizeDigit":6,"mergeTypes":"0.01,0.1,1","minTradeSize
":0.00100000,"online":1,"productId":909,"quoteCurrency":1063,"quoteIncrement":"0.01","quotePrecision":2,"sort":30000,"symbol":"ltc_usdk"
,"tradingMode":3},{"baseCurrency":1,"brokerId":0,"callAuctionOrCallNoCancelAuction":false,"callNoCancelSwitchTime":{},"collect":"0","con
tinuousSwitchTime":{},"groupId":1,"isMarginOpen":true,"listDisplay":0,"marginRiskPreRatio":1.2,"marginRiskRatio":1.1,"marketFrom":96,"ma
xMarginLeverage":5,"maxPriceDigit":2,"maxSizeDigit":6,"mergeTypes":"0.01,0.1,1","minTradeSize":0.00100000,"online":1,"productId":25,"quo
teCurrency":7,"quoteIncrement":"0.01","quotePrecision":2,"sort":30044,"symbol":"ltc_usdt","tradingMode":3}, ........
rrency":"usd","nativeCurrencyMark":"$","contractSymbol":0,"unitAmount":10.00,"symbolMark":"BSV","symbolDesc":"BSV"}]}
Traceback (most recent call last):
  File "test_okex.py", line 11, in <module>
    result = okex.fetch_ohlcv('ETH/USD', since=1561708800000, limit=1, timeframe='15m', params={'contract_type': 'this_week'})
  File "/home/ubuntu/.pyenv/versions/bricks/lib/python3.6/site-packages/ccxt/okcoinusd.py", line 700, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/ubuntu/.pyenv/versions/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1573, in market
    self.raise_error(ExchangeError, details='No market symbol ' + str(symbol))
  File "/home/ubuntu/.pyenv/versions/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 443, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: okex No market symbol ETH/USD
```

**Comment by kroitor** [comment]
You have to use their proper futures markets symbols:

```Python
# mbp:python igorkroitor$ python3
# Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
# [Clang 6.0 (clang-600.0.57)] on darwin
# Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> exchange = ccxt.okex()
>>> markets = exchange.load_markets()
>>> pprint([symbol for symbol in exchange.symbols if 'ETH' in symbol and 'USD' in symbol ])
['ETH-USD-190705', 'ETH-USD-190712', 'ETH-USD-190927', 'ETH/USDK', 'ETH/USDT']
# ↑ you need this  or this ↑  or this        ↑
```

**Comment by kroitor** [comment]
@yurenji found another bug with Futures OHLCV there, will upload the fix in a few moments. The new version 1.18.860 won't have that bug and will arrive in 15 minutes.

**Comment by yurenji** [comment]
tested with 1.18.860 , works fine.

**Comment by kroitor** [comment]
@yurenji thx again for your help!
