### ISSUE TITLE
help with okex v3 spot cancel_batch_orders 

### ISSUE THREAD

**Issue by yurenji** [ccxt/ccxt#5481]
- OS: mac/ubuntu 16.04
- Programming Language version: python
- CCXT version: latest
- Exchange: okex v3
- Method: spot_post_cancel_batch_orders

```
import ccxt

ex = ccxt.okex3({
    'apiKey': '',
    'secret': '',
    'password': ''
})

result = ex.spot_post_cancel_batch_orders(
    params={
        'instrument_id': 'BTC-USDT',
        'order_ids': ['3135975779928064', '3135975777510400']
    }
)
```
The above code gives me error: 

```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/yurenji/bricks/okex-cancel-batch.py", line 11, in <module>
    'order_ids': ['3135975779928064', '3135975777510400']}
  File "/home/ubuntu/.pyenv/versions/3.6.5/envs/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 433, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ubuntu/.pyenv/versions/3.6.5/envs/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 462, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/ubuntu/.pyenv/versions/3.6.5/envs/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 458, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ubuntu/.pyenv/versions/3.6.5/envs/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 551, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/ubuntu/.pyenv/versions/3.6.5/envs/bricks/lib/python3.6/site-packages/ccxt/okex3.py", line 2615, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: okex3 {"message":"Invalid JSON format"}
```
 I am not sure am I using the api correctly, or there is a bug with the api. Can you help me a bit here?

**Comment by yurenji** [comment]
FYI, I was able to make it work for future orders: 

```
result = ex.futures_post_cancel_batch_orders_instrument_id(                                            
    params={'instrument_id': 'BTC-USD-190719', 'order_ids': ['3136012835693568', '3136012838714368']}  
)        
```

**Comment by yurenji** [comment]
![image](https://user-images.githubusercontent.com/5565266/60809589-9c9df800-a1bd-11e9-9b73-67f8bdcb0460.png)

Noticing the okex rest api accepts 'list' object in the body, I also tried: 
```
result = ex.spot_post_cancel_batch_orders(                               
    params=[{'instrument_id': 'BTC-USDT',                                
            'order_ids': ['3135975779928064', '3135975777510400']}]      
)                                                                                                                                                 
```
It gives me another error: 

```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/yurenji/bricks/okex-cancel-batch.py", line 11, in <module>
    'order_ids': ['3135975779928064', '3135975777510400']}]
  File "/home/ubuntu/.pyenv/versions/3.6.5/envs/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 433, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ubuntu/.pyenv/versions/3.6.5/envs/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 462, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/ubuntu/.pyenv/versions/3.6.5/envs/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 457, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/home/ubuntu/.pyenv/versions/3.6.5/envs/bricks/lib/python3.6/site-packages/ccxt/okex3.py", line 2560, in sign
    request = '/api' + '/' + api + '/' + self.version + '/' + self.implode_params(path, params)
  File "/home/ubuntu/.pyenv/versions/3.6.5/envs/bricks/lib/python3.6/site-packages/ccxt/base/exchange.py", line 774, in implode_params
    string = string.replace('{' + key + '}', str(params[key]))
TypeError: must be str, not dict
```

**Comment by frosty00** [comment]
you need to wrap the params in a list like so:

```
result = ex.spot_post_cancel_batch_orders(
    params=[{
        'instrument_id': 'BTC-USDT',
        'order_ids': ['3135975779928064', '3135975777510400']
    }]
)
```

the format has to match exactly the format as specified by the api docs - https://www.okex.com/docs/en/#spot-repeal

**Comment by kroitor** [comment]
@frosty00 the problem is with lists in `implodeParams`:

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> ex = ccxt.okex3()
>>> result = ex.spot_post_cancel_batch_orders(
...     params=[{
...         'instrument_id': 'BTC-USDT',
...         'order_ids': ['3135975779928064', '3135975777510400']
...     }]
... )
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 432, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 455, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 450, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/Users/igorkroitor/ccxt/python/ccxt/okex3.py", line 2538, in sign
    request = '/api' + '/' + api + '/' + self.version + '/' + self.implode_params(path, params)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 770, in implode_params
    string = string.replace('{' + key + '}', str(params[key]))
TypeError: can only concatenate str (not "dict") to str
>>>
```

**Comment by kroitor** [comment]
@yurenji it was a bug with handling arrays in params, and it should be fixed as of 1.18.912 (the new build will arrive in 10 minutes). Tested it on my side – and now it reports a proper error:

Python:

```
mbp:ccxt igorkroitor$ python examples/py/cli.py --verbose okex3 spot_post_cancel_batch_orders '[{ "instrument_id": "BTC-USDT", "order_ids": ["3135975779928064", "3135975777510400"] }]'
```

```
('\nRequest:', 'POST', 'https://www.okex.com/api/spot/v3/cancel_batch_orders', {'Accept-Encoding': 'gzip, deflate', 'OK-ACCESS-SIGN': u'Qv+wy8UmMhn8iWSjGZWozPOssCe+z/GYJbXs+r2jtKQ=', 'OK-ACCESS-KEY': u'a24364b3-2c7d-43c1-bd04-c247f911a6c4', 'OK-ACCESS-PASSPHRASE': u'7KUcc8YzQhnxBE3K', 'User-Agent': 'python-requests/2.18.4', 'Content-Type': 'application/json', 'OK-ACCESS-TIMESTAMP': '2019-07-08T19:40:26.956Z'}, '[{"instrument_id":"BTC-USDT","order_ids":["3135975779928064","3135975777510400"]}]')
('\nResponse:', 'POST', 'https://www.okex.com/api/spot/v3/cancel_batch_orders', 400, {'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Content-Length': '47', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Kong-Proxy-Latency': '0', 'Set-Cookie': '__cfduid=ddbb01e6d5f1733330454f73a87f630b31562614826; expires=Tue, 07-Jul-20 19:40:26 GMT; path=/; domain=.okex.com; HttpOnly, locale=en_US; Max-Age=604800; Expires=Mon, 15-Jul-2019 19:40:27 GMT; Path=/', 'Expires': '0', 'Server': 'cloudflare', 'Connection': 'keep-alive', 'Via': 'kong/0.12.3', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Date': 'Mon, 08 Jul 2019 19:40:27 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'CF-RAY': '4f3487ac88e14ec4-DME', 'X-Kong-Upstream-Latency': '12'}, u'{"code":33014,"message":"Order does not exist"}')
Traceback (most recent call last):
  File "examples/py/cli.py", line 126, in <module>
    result = method(*args)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 432, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 455, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 451, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 547, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response)
  File "/Users/igorkroitor/ccxt/python/ccxt/okex3.py", line 2584, in handle_errors
    raise exact[errorCode](feedback)
ccxt.base.errors.OrderNotFound: okex3 {"code":33014,"message":"Order does not exist"}
mbp:ccxt igorkroitor$
```

JavaScript:

```
mbp:ccxt igorkroitor$ node examples/js/cli okex3 spot_post_cancel_batch_orders '[{ "instrument_id": "BTC-USDT", "order_ids": ["3135975779928064", "3135975777510400"] }]'
```

```
okex3.spot_post_cancel_batch_orders ([object Object])
OrderNotFound okex3 {"code":33014,"message":"Order does not exist"}
```

PHP:

```
mbp:ccxt igorkroitor$ php -f examples/php/cli.php okex3 spot_post_cancel_batch_orders '[{ "instrument_id": "BTC-USDT", "order_ids": ["3135975779928064", "3135975777510400"] }]'
```

```
okex3->spot_post_cancel_batch_orders (Array)
ccxt\OrderNotFound: okex3 {"code":33014,"message":"Order does not exist"}
```

Let us know if you still have difficulties with it after upgrading to 1.18.912. Thx for reporting!

**Comment by yurenji** [comment]
I can confirm the fix works.

**Comment by codemonkeyno1** [comment]
Can this fix be applied to okex futures batch send orders as well?

exchange.futures_post_orders(params={[{'instrument_id':'BTC-USDT-SWAP','type':'1','price':'30000','size':'0.001'}]})

Getting this error in Python: 
TypeError: unhashable type: 'list'

**Comment by codemonkeyno1** [comment]
@kroitor

**Comment by kroitor** [comment]
@codemonkeyno1 i'm receiving and reading all the messages, no worries, will handle it asap.

**Comment by robzer** [comment]
ccxt  2.2.1

``
okx_trades.verbose=True
okx_trades.cancel_orders(live_order_ids, 'BTC-USDT')
``

with 

``
batch_order_ids = [{'instId': 'BTC-USDT', 'ordId': '520392143614476289'},
                 {'instId': 'BTC-USDT', 'ordId': '520392143614476288'},
                 {'instId': 'BTC-USDT', 'ordId': '520386152940404736'},
                 {'instId': 'BTC-USDT', 'ordId': '520386145889779713'},
                 {'instId': 'BTC-USDT', 'ordId': '520386145889779712'}]
``
works fine

here is what i see in the verbose

``
RequestBody: [{"ordId":"520392143614476289","instId":"BTC-USDT"},{"ordId":"520392143614476288","instId":"BTC-USDT"},{"ordId":"520386152940404736","instId":"BTC-USDT"},{"ordId":"520386145889779713","instId":"BTC-USDT"},{"ordId":"520386145889779712","instId":"BTC-USDT"}]
``

HOWEVER

``
okx_trades.private_post_trade_cancel_batch_orders({batch_order_ids})
``

gives me 

``
TypeError: unhashable type: 'list'
``

just like codemonkey - any ideas why?
