### ISSUE TITLE
Making request from CCXT gives incapsula request unsuccessful while it works with curl

### ISSUE THREAD

**Issue by xCuri0** [ccxt/ccxt#5515]
- OS: Arch Linux
- Programming Language version: Python 3.7
- CCXT version: latest from git
- Exchange: coinexchange
- Method: all private methods

I'm working on adding unofficial trading support for coinexchange in CCXT. When try to make a buy order request by adding support for that in CCXT I get ```Request unsuccessful. Incapsula incident ID: [redacted]```. But if I send the exact same request that CCXT shows in verbose log with curl it succeeds

**Comment by kroitor** [comment]
@xCuri0 have you tried comparing the headers? It is often due to one of the headers missing:

- `exchange.headers = { 'Accept': 'application/json' }` (or set it per request)
- `exchange.userAgent = exchange.userAgents['chrome']` (or set it with headers per request)

Does that help?

**Comment by xCuri0** [comment]
@kroitor the headers and everything are exactly the same. it works fine in curl even if i use the python requests user agent

**Comment by kroitor** [comment]
@xCuri0 need something to reproduce it, can you post more details? A complete snippet of 10-20 lines with instantiation along with a curl sample – would definitely help shed light on it.

**Comment by xCuri0** [comment]
Exchange code
```
    sign (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
        let url = this.urls['api'][api];
        url += '/' + path;
        if (api === 'public') {
            if (Object.keys (params).length) {
                url += '?' + this.urlencode (params);
            }
        } else {
            headers = {
                'Cookie': 'PHPSESSID=' + this.apiKey,
            };
            body = params;
        }
        return { 'url': url, 'method': method, 'body': body, 'headers': headers };
    }

    async createOrder (symbol, type, side, amount, price = undefined, params = {}) {
        if (type === 'market') {
            throw new ExchangeError (this.id + ' allows limit orders only');
        }
        await this.loadMarkets ();
        const market = this.market (symbol);
        const orderType = (side === 'buy') ? '1' : '0';
        const request = 'market_id=' + market['id'] + '&type=' + orderType + '&amount=' + this.amountToPrecision (symbol, amount) + '&price=' + this.priceToPrecision (symbol, price) + '&form_token=[redacted]';
        const response = await this.privatePostAddMarketOrder (request);
        const timestamp = this.milliseconds ();
        const order = this.parseOrder (this.extend ({
            'timestamp': timestamp,
            'status': 'open',
            'type': type,
            'side': side,
            'price': price,
            'amount': amount,
        }, response), market);
        const id = order['id'];
        this.orders[id] = order;
        return this.extend ({ 'info': response }, order);
    }
};
```

In CCXT verbose log
```
Request: POST https://www.coinexchange.io/add/market/order {'Cookie': 'PHPSESSID=[redacted]', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} market_id=21&type=0&amount=500&price=0.0000003&form_token=[redacted]

Response: POST https://www.coinexchange.io/add/market/order 200 {'Content-Type': 'text/html', 'Cache-Control': 'no-cache', 'Connection': 'close', 'Content-Length': '830', 'X-Iinfo': '13-5468401-0 0NNN RT(1563249022965 2545) q(0 -1 -1 -1) r(0 -1) B12(11,48708,0) U18', 'X-Iejgwucgyu': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload'} <html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?SWUDNSAI=29&xinfo=13-5468401-0%200NNN%20RT%281563249022965%202545%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B12%2811%2c48708%2c0%29%20U18&incident_id=[redacted]edet=12&cinfo=0b000000" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: [redacted]</iframe></body></html>
```
cURL command that works
```
curl "https://www.coinexchange.io/add/market/order" -H "Cookie: PHPSESSID=[redacted]" -H "User-Agent: python-requests/2.22.0" -H "Accept-Encoding: gzip, deflate" --compressed --data "market_id=21&type=0&amount=500&price=0.0000003&form_token=[redacted]"
```

**Comment by kroitor** [comment]
@xCuri0 have you tried

```
sign (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
        let url = this.urls['api'][api];
        url += '/' + path;
        if (api === 'public') {
            if (Object.keys (params).length) {
                url += '?' + this.urlencode (params);
            }
        } else {
            headers = {
                'Cookie': 'PHPSESSID=' + this.apiKey,
                'Content-Type': 'application/x-www-form-urlencoded',
            };
            body = this.urlencode (params);
        }
        return { 'url': url, 'method': method, 'body': body, 'headers': headers };
    }

    async createOrder (symbol, type, side, amount, price = undefined, params = {}) {
        if (type === 'market') {
            throw new ExchangeError (this.id + ' allows limit orders only');
        }
        await this.loadMarkets ();
        const market = this.market (symbol);
        const orderType = (side === 'buy') ? '1' : '0';
        const request = {
            'market_id': market['id'],
            'type': orderType,
            'amount': this.amountToPrecision (symbol, amount),
            'price': this.priceToPrecision (symbol, price),
            'form_token': YOUR_FORM_TOKEN,
        }
        const response = await this.privatePostAddMarketOrder (request);
        const timestamp = this.milliseconds ();
        const order = this.parseOrder (this.extend ({
            'timestamp': timestamp,
            'status': 'open',
            'type': type,
            'side': side,
            'price': price,
            'amount': amount,
        }, response), market);
        const id = order['id'];
        this.orders[id] = order;
        return this.extend ({ 'info': response }, order);
    }
```

↑ The body has to be urlencoded and the request must have a proper content-type. Does that help?

**Comment by xCuri0** [comment]
@kroitor It still gives the same error. It seems like its related to the way python-requests is sending it's requests since i changed the code so it doesn't make any other API calls (in case its because the DDOS protection thinks its automated) but it still gives the same error. Being able to check for differences using Wireshark would be useful but Python doesn't support SSLKEYLOGFILE

**Comment by kroitor** [comment]
@xCuri0 can you check if it works in JS?

**Comment by xCuri0** [comment]
@kroiter js gives a different error probably because the js for coinexchange is broken
```
fetch:
 coinexchange GET https://www.coinexchange.io/api/v1/getcurrencies 
Request:
 {} 
 undefined 

(node:6265) UnhandledPromiseRejectionWarning: ExchangeNotAvailable: coinexchange GET https://www.coinexchange.io/api/v1/getcurrencies system request to https://www.coinexchange.io/api/v1/getcurrencies failed, reason: Parse Error
    at fetchImplementation.catch (/media/storage/Documents/src/ccxt/js/base/Exchange.js:410:35)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:6265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6265) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
@xCuri0 which node version is it?

>  probably because the js for coinexchange is broken

Depends on the NodeJS version, maybe related to this: https://github.com/ccxt/ccxt/issues/5149#issuecomment-511616901

**Comment by xCuri0** [comment]
@kroitor regarding the problem i'm facing with python. i found out that cURL seems to add some incapsula related cookies when sending the request. here's verbose cURL output
```
curl "https://www.coinexchange.io/add/market/order" -H "Cookie: PHPSESSID=" -H "Content-Type: application/x-www-form-urlencoded" -H "User-Agent: python-requests/2.22.0" -H "Accept-Encoding: gzip, deflate" --compressed --data "market_id=21&type=0&amount=500&price=0.0000003&form_token=foo" --verbose

*   Trying 45.60.48.219:443...
* TCP_NODELAY set
* Connected to www.coinexchange.io (45.60.48.219) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Delaware; L=Dover; O=Incapsula Inc; CN=incapsula.com
*  start date: Jul  5 06:11:30 2019 GMT
*  expire date: Jul  5 06:11:30 2020 GMT
*  subjectAltName: host "www.coinexchange.io" matched cert's "*.coinexchange.io"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign CloudSSL CA - SHA256 - G3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x559800e32e60)
> POST /add/market/order HTTP/2
> Host: www.coinexchange.io
> Accept: */*
> Cookie: PHPSESSID=
> Content-Type: application/x-www-form-urlencoded
> User-Agent: python-requests/2.22.0
> Accept-Encoding: gzip, deflate
> Content-Length: 61
> 
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 302 
< server: nginx
< date: Tue, 16 Jul 2019 15:35:22 GMT
< content-type: text/html; charset=UTF-8
< content-length: 376
< x-frame-options: SAMEORIGIN
< cache-control: no-cache
< location: https://www.coinexchange.io/login
< set-cookie: visid_incap_1322663=o83sFS+IQs6eHJ639NUh6LnuLV0AAAAAQUIPAAAAAADYteiuipoD5nPd+1pI4JmH; expires=Wed, 15 Jul 2020 08:33:38 GMT; path=/; Domain=.coinexchange.io
< set-cookie: incap_ses_969_1322663=Q3SqZHwm4Tavf4WUMZVyDbnuLV0AAAAAIuUKTKDtVwt09tdX7L3WSA==; path=/; Domain=.coinexchange.io
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-iinfo: 14-15517782-15517783 NNNN CT(0 0 0) RT(1563291321379 0) q(0 0 0 -1) r(2 2) U6
< x-cdn: Incapsula
< 
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=https://www.coinexchange.io/login" />

        <title>Redirecting to https://www.coinexchange.io/login</title>
    </head>
    <body>
        Redirecting to <a href="https://www.coinexchange.io/login">https://www.coinexchange.io/login</a>.
    </body>
* Connection #0 to host www.coinexchange.io left intact
</html>
```

**Comment by kroitor** [comment]
@xCuri0 if you're not passing some of required cookies, like `incap_ses_969_1322663`, then this issue is beyond the scope of the lib, unfortunately. Web scraping can be easily broken if they introduce a slight change on the exchange website. How can we help you on this issue further?

**Comment by xCuri0** [comment]
@kroitor i don't get why it doesnt work in ccxt but if i send the exact same request in curl it succeeds. does cURL have any handling for the cookies or something ?

**Comment by kroitor** [comment]
@xCuri0 well, python `requests` does not support http/2. The other thing is that it's hard to tell the exact cause, because the code you posted does not really show the bug in Python.

I suggest that you post a minimal but a complete Python script to reproduce the issue, something like:

```Python
import ccxt
exchange = ccxt.coinexchange()
exchange.verbose = True
headers = {

    'Content-Type': 'application/x-www-form-urlencoded',
    'Accept-Encoding': 'gzip, deflate',

    'Cookie': 'PHPSESSID=',  # you're sending it without a value in CURL...

    # add all required headers here, i don't know which ones are required
    # use curl in verbose mode to figure our which parameters are being sent on each step
}

body = exchange.urlencode ({
    'market_id': market['id'],
    'type': orderType,
    'amount': this.amountToPrecision (symbol, amount),
    'price': this.priceToPrecision (symbol, price),
    #  don't know if it's required
    # also, don't know if it requires any other fields...
    'form_token': YOUR_FORM_TOKEN, 
})

exchange.fetch('https://www.coinexchange.io/add/market/order', 'POST', headers, body)
```

If you can ↑ please edit the above according to your request, and paste the verbose output from Python and from curl here? We need to compare verbose info against curl.

I can't really debug it blindly and remotely without having the credentials and the exact same setup as you have...

**Comment by xCuri0** [comment]
@kroitor tried that code (after a few changes) and it also fails with incapsula request unsuccessful. btw you don't need login cookies and form token to test it. use blank for the phpsessid and foo for the form_token if your request it successful it will return a login page (doing the request in curl without credentials does this).

output of that program
```
Request: POST https://www.coinexchange.io/add/market/order {'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Encoding': 'gzip, deflate', 'Cookie': 'PHPSESSID=', 'User-Agent': 'python-requests/2.22.0'} market_id=21&type=0&amount=500&price=3e-07&form_token=foo

Response: POST https://www.coinexchange.io/add/market/order 200 {'Content-Type': 'text/html', 'Cache-Control': 'no-cache', 'Connection': 'close', 'Content-Length': '828', 'X-Iinfo': '6-4131179-0 0NNN RT(1563293642365 392) q(0 -1 -1 -1) r(0 -1) B12(11,48708,0) U18', 'X-Iejgwucgyu': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload'} <html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?SWUDNSAI=29&xinfo=6-4131179-0%200NNN%20RT%281563293642365%20392%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B12%2811%2c48708%2c0%29%20U18&incident_id=redacted&edet=12&cinfo=0b000000" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 969000910016074522-18708383683642806</iframe></body></html>
<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?SWUDNSAI=29&xinfo=6-4131179-0%200NNN%20RT%281563293642365%20392%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B12%2811%2c48708%2c0%29%20U18&incident_id=redacted&edet=12&cinfo=0b000000" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: redacted</iframe></body></html>
```
the error is probably because its not using http/2 because otherwise the request is identical afaik

**Comment by kroitor** [comment]
@xCuri0 try `hyper`:

https://hyper.readthedocs.io/en/latest/

```Python
import ccxt
import requests
from hyper.contrib import HTTP20Adapter
session = requests.Session()
session.mount('https://www.coinexchange.io', HTTP20Adapter())
exchange = ccxt.coinexchange({
    'session': session
})
exchange.verbose = True
headers = {

    'Content-Type': 'application/x-www-form-urlencoded',
    'Accept-Encoding': 'gzip, deflate',

    'Cookie': 'PHPSESSID=',  # you're sending it without a value in CURL...

    # add all required headers here, i don't know which ones are required
    # use curl in verbose mode to figure our which parameters are being sent on each step
}

body = exchange.urlencode ({
    'market_id': market['id'],
    'type': orderType,
    'amount': this.amountToPrecision (symbol, amount),
    'price': this.priceToPrecision (symbol, price),
    #  don't know if it's required
    # also, don't know if it requires any other fields...
    'form_token': YOUR_FORM_TOKEN, 
})

print(exchange.fetch('https://www.coinexchange.io/add/market/order', 'POST', headers, body))
```

Does it work? Does any of the `hyper` samples work from here https://hyper.readthedocs.io/en/latest/quickstart.html?

**Comment by xCuri0** [comment]
@kroitor yes it works

**Comment by kroitor** [comment]
@xCuri0 issue solved? )

**Comment by xCuri0** [comment]
@kroitor yeah its solved and the createorder method works too but this is more of a hack. hopefully in the future ccxt will support http/2

**Comment by kroitor** [comment]
> hopefully in the future ccxt will support http/2

We will look into adding that, however, that would still be done with `hyper` or something similar internally. So far we haven't seen a http/2 "official" API, their websites can change their endpoints and markup, so we would not rely on that.

In general, to support http/2 in ccxt you would simply do:

```Python
import ccxt
import requests
from hyper.contrib import HTTP20Adapter
session = requests.Session()
session.mount('https://www.coinexchange.io', HTTP20Adapter())
exchange = ccxt.coinexchange({
    'session': session
})
```

I don't think the above is too hacky, but we will also consider making it even more simple and maybe fully automatic.

**Comment by xCuri0** [comment]
@kroitor do you know how i should do the form_token saving. how it works is that a new form token is returned after each request (to get the first one you can scrape the website but imo its easier to just make a request with an invalid one and it will return a correct one) so it would have to be stored for the next use but idk how i can do that in ccxt as no other exchanges store a variable and use it later afaik

**Comment by frosty00** [comment]
>  no other exchanges store a variable and use it later afaik

Actually many exchanges require an `access_token`. The way to do this in a ccxt compatible way would be to make it an option, like so:

```
'options': {
    'form_token': undefined,
}
```

and then add some code in `request` or whatever derived method that manages the `form_token`

**Comment by xCuri0** [comment]
@frosty00 thanks i've got trading fully working now
