### ISSUE TITLE
Unable to fecth deposit address huobipro?

### ISSUE THREAD

**Issue by SauravKanchan** [ccxt/ccxt#5516]
- OS: Any
- Programming Language version: python3.6
- CCXT version: 1.18.817
- Exchange: huobipro
- Method: fetchDepositAddress

```bash
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/saurav/projects/computeex_django/env/lib/python3.6/site-packages/ccxt/huobipro.py", line 823, in fetch_deposit_address
    response = getattr(self, method)(self.extend(request, params))
  File "/home/saurav/projects/computeex_django/env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 423, in inner
    return entry(_self, **inner_kwargs)
  File "/home/saurav/projects/computeex_django/env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 452, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/saurav/projects/computeex_django/env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 448, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/saurav/projects/computeex_django/env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 551, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/saurav/projects/computeex_django/env/lib/python3.6/site-packages/ccxt/huobipro.py", line 948, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: huobipro {"status":"error","err-code":"login-required","err-msg":"The account is not logged in, please log in and try again.","data":null}
```
Methods working:
huobipro.loadAccounts() 
huobipro.fetchBalance()

huobipro.fetchDepositAddress("XRP") is giving login-required error.

**Comment by frosty00** [comment]
Please update CCXT, huobipro's `fetchDepositAddress` has been depreciated and they do not provide an API endpoint. The old code used an endpoint that was accessible from the browser but it now requires a session cookie (i.e. to be logged in).

**Comment by SauravKanchan** [comment]
Ok
Thanks for info
