### ISSUE TITLE
bithumb.fetch_balance() returns 400 Bad Request / 5100 Error Code 

### ISSUE THREAD

**Issue by crypt2** [ccxt/ccxt#552]
```
import ccxt
import time

bithumb = ccxt.bithumb({
    "apiKey": "xxx",
    "secret": "xxx",
    "verbose": True,
})

print(bithumb.fetch_balance())
```

Returns error : 
cxt.base.errors.ExchangeNotAvailable: bithumb POST https://api.bithumb.com/info/balance 400 Bad Request  {"status":"5100","message":"Bad Request.(Request Time:reqTimexxxxxx....)

**Comment by kroitor** [comment]
Hi, @crypt2 !

Can you post full verbose output, plz? (without the keys)

**Comment by crypt2** [comment]
<class 'ccxt.base.errors.NetworkError'>
https://api.bithumb.com/info/balance POST https://api.bithumb.com/info/balance 
Request: {'Api-Key': 'xxx', 'Api-Sign': b'xxx=', 'Api-Nonce': 'zzz', 'User-Agent': 'ccxt/1.10.79 (+https://github.com/ccxt-dev/ccxt) Python/3.6.0', 'Accept-Encoding': 'gzip, deflate'} endpoint=%2Finfo%2Fbalance&currency=ALL
Traceback (most recent call last):
  File "/xxx/ccxt/ccxt/python/ccxt/base/exchange.py", line 300, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1000))
  File "/xxx/ENTER/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/xxx/ENTER/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/xxx/ENTER/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/xxx/ENTER/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/xxx/ENTER/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test-bithumb.py", line 10, in <module>
    print(bithumb.fetch_balance())
  File "/xxx/ccxt/ccxt/python/ccxt/bithumb.py", line 77, in fetch_balance
    }, params))
  File "/xxx/ccxt/ccxt/python/ccxt/bithumb.py", line 233, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/xxx/ccxt/ccxt/python/ccxt/base/exchange.py", line 259, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File “/xxx/ccxt/ccxt/python/ccxt/base/exchange.py", line 316, in fetch
    self.handle_rest_errors(e, e.code, message if message else text, url, method)
  File “/xxx/ccxt/ccxt/python/ccxt/base/exchange.py", line 344, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File “/xxx/ccxt/python/ccxt/base/exchange.py", line 241, in raise_error
    details,
ccxt.base.errors.ExchangeNotAvailable: bithumb POST https://api.bithumb.com/info/balance 400 Bad Request  {"status":"5100","message":"Bad Request.(Request `Time:reqTime1510607362413\/nowTime1510607322```

**Comment by kroitor** [comment]
You shouldn't have removed the nonce %))) Anyway, I think I can see the reason now, will upload the fix shortly, thx!

**Comment by kroitor** [comment]
@crypt2 can you please update to version 1.10.84+ and retry the same code again, but this time, if it does not work, please paste full verbose output with nonce (it isn't a big secret, most people use seconds or milliseconds). Thx!

**Comment by crypt2** [comment]
I get the same error with  'Api-Nonce': '1510616584'

**Comment by kroitor** [comment]
@crypt2 can you post full verbose output of it?

**Comment by crypt2** [comment]
https://api.bithumb.com/info/balance POST https://api.bithumb.com/info/balance 
Request: {'Api-Key': 'XXX', 'Api-Sign': 'XXX', 'Api-Nonce': '1510616584', 'User-Agent': 'ccxt/1.10.87 (+https://github.com/ccxt-dev/ccxt) Python/3.6.0', 'Accept-Encoding': 'gzip, deflate'} endpoint=%2Finfo%2Fbalance&currency=ALL
Traceback (most recent call last):
  File "/Users/xxx/Desktop/Crypto/scripts/trading/ccxt2/ccxt/python/ccxt/base/exchange.py", line 300, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1000))
  File "/Users/xxx/ENTER/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Users/xxx/ENTER/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/xxx/ENTER/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Users/xxx/ENTER/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/xxx/ENTER/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test-bithumb.py", line 10, in <module>
    print(bithumb.fetch_balance())
  File "/Users/xxx/Desktop/Crypto/scripts/trading/ccxt2/ccxt/python/ccxt/bithumb.py", line 77, in fetch_balance
    }, params))
  File "/Users/xxx/Desktop/Crypto/scripts/trading/ccxt2/ccxt/python/ccxt/bithumb.py", line 234, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/xxx/Desktop/Crypto/scripts/trading/ccxt2/ccxt/python/ccxt/base/exchange.py", line 259, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/xxx/Desktop/Crypto/scripts/trading/ccxt2/ccxt/python/ccxt/base/exchange.py", line 316, in fetch
    self.handle_rest_errors(e, e.code, message if message else text, url, method)
  File "/Users/xxx/Desktop/Crypto/scripts/trading/ccxt2/ccxt/python/ccxt/base/exchange.py", line 344, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/Users/xxx/Desktop/Crypto/scripts/trading/ccxt2/ccxt/python/ccxt/base/exchange.py", line 241, in raise_error
    details,
ccxt.base.errors.ExchangeNotAvailable: bithumb POST https://api.bithumb.com/info/balance 400 Bad Request  {"status":"5100","message":"Bad Request.(Request Time:reqTime1510616584\/nowTime1510616543496)"}

**Comment by kroitor** [comment]
@crypt2 Is your system time synchronized? Looks like a discrepancy of 40 seconds.

**Comment by tercel** [comment]
nonce issue;  we can use 'new Date().getTime()' in javascript instead of usecTime function

**Comment by kroitor** [comment]
@tercel https://github.com/ccxt/ccxt/wiki/Manual#working-with-datetimes-and-timestamps
