### ISSUE TITLE
Kucoin New v2 API (ccxt.kucoin2()) still using v1 api for transfering funds between accounts.

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#5571]
- OS: Linux
- Programming Language version: Python 3
- CCXT version: 1.18.965
- Exchange: kucoin2
- Method: ```kucoin2.privatePostAccountsInnerTransfer({'clientOid': 12345, 'currency': 'BTC', 'from': 'trade', 'to': 'main', 'amount': 0.01})```

```
Request: POST https://openapi-v2.kucoin.com/api/v1/accounts/inner-transfer {'KC-API-KEY': 'BLOCKED', 'KC-API-TIMESTAMP': '1563780129764', 'KC-API-PASSPHRASE': 'BLOCKED', 'Content-Type': 'application/json', 'KC-API-SIGN': 'm8zlaGtO2kuOPCTpFxAuKWYtJK5Fl0iSPpOkkvGkWtE=', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} {"clientOid":12345,"currency":"BTC","from":"trade","to":"main","amount":0.01}

Response: POST https://openapi-v2.kucoin.com/api/v1/accounts/inner-transfer 200 {'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Mon, 22 Jul 2019 07:22:12 GMT', 'Set-Cookie': 'AWSALB=R0nneaM2lSuhkMfzRdbB8rpYtYQ37WUxpbtsqD0mmcChT6HwvsrXoMaHZREgN5xDphcPNjmvygdXiiA9y9xWKf2TJFBxgKlXqe5NTMpoDRgA8PARmsySij9cFtC4; Expires=Mon, 29 Jul 2019 07:22:12 GMT; Path=/, JSESSIONID=026092200DB628C77F9D1C0C0E40769E; Max-Age=604800; Expires=Mon, 29-Jul-2019 07:22:12 GMT; Path=/; Secure; HttpOnly, X-TRACE=eS4YgGjBUddIH/5cTyzKJusMKmI5gWaitP40DAUMqGQ=; Path=/; HttpOnly', 'Server': 'nginx', 'code': '4001', 'X-TRACE-ID': '18226b4561424e15', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Strict-Transport-Security': 'max-age=9800; includeSubDomains; preload', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 90afcdb26518f969b68e124515efb74c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'YUL62-C1', 'X-Amz-Cf-Id': '62BB-jLUpAxNo1y_YgLyChAUpbGySeH1t2L-i7_MAP5W6I6cms2TlQ=='} {"code":"400100","msg":"payAccountId can not be empty"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 432, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 455, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 451, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 558, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response)
  File "/usr/local/lib/python3.7/site-packages/ccxt/kucoin.py", line 1436, in handle_errors
    raise ExceptionClass(self.id + ' ' + message)
ccxt.base.errors.BadRequest: kucoin2 payAccountId can not be empty
```
It seems like it is still using parameters from the v1 api. I have pasted the link from the original Kucoin v2 document that addresses this, to save time. 
https://docs.kucoin.com/#inner-transfer

Thank you!

**Comment by karlandoh** [comment]
Apologizes for the amateur question, but it seems like the commit is in javascript. Is there a way that someone can address this from a pythonic standpoint?

**Comment by frosty00** [comment]
Hi @karlandoh,

Thanks for creating the issue and using the verbose mode and posting the link to the new API, it is really helpful.

I have added support to specify the API version of the endpoint. So the new version can be used as such:

```
kucoin.privatePostAccountsInnerTransfer({'clientOid': 12345, 'currency': 'BTC', 'from': 'trade', 'to': 'main', 'amount': 0.01, 'version': 'v2'})
```

---

but the old API still remains accessible until it is discontinued on the 29th:

```
kucoin.privatePostAccountsInnerTransfer({'clientOid': 12345, 'currency': 'BTC', 'payAccountId': 'id', 'recAccountId': 'id', 'amount': 0.01})
```

Thanks again for using CCXT )

**Comment by karlandoh** [comment]
Oh beautiful! Thanks!

**Comment by frosty00** [comment]
@karlandoh don't worry about the question, I too was a noob not so long ago. The python and php are transpiled using regexes.

Read more about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
