### ISSUE TITLE
Mandalaex website isn't working (API too)

### ISSUE THREAD

**Issue by Matoran** [ccxt/ccxt#5582]
https://trade.mandalaex.com/

- OS: linux mint 19.1
- Programming Language version: python3.7
- CCXT version: 1.18.975
- Exchange: mandalaex
- Method:
```python
import ccxt

tickers = {}
e = ccxt.mandala()
e.load_markets()
e.enableRateLimit = True
print(e.fetch_tickers())
```

```
Traceback (most recent call last):
  File ".venv3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 535, in fetch
    response.raise_for_status()
  File ".venv3.7/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://zapi.mandalaex.com/api/CurrencySettings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/Mandalaex.py", line 5, in <module>
    e.load_markets()
  File ".venv3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1146, in load_markets
    currencies = self.fetch_currencies()
  File ".venv3.7/lib/python3.7/site-packages/ccxt/mandala.py", line 295, in fetch_currencies
    response = self.fetch_currencies_from_cache(params)
  File ".venv3.7/lib/python3.7/site-packages/ccxt/mandala.py", line 287, in fetch_currencies_from_cache
    response = self.settingsGetCurrencySettings(params)
  File ".venv3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 432, in inner
    return entry(_self, **inner_kwargs)
  File ".venv3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 455, in request
    return self.fetch2(path, api, method, params, headers, body)
  File ".venv3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 451, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File ".venv3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 548, in fetch
    self.handle_rest_errors(http_status_code, http_status_text, http_response, url, method)
  File ".venv3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 573, in handle_rest_errors
    raise error(' '.join([method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: GET https://zapi.mandalaex.com/api/CurrencySettings 403 Forbidden <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>403 - Forbidden: Access is denied.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>403 - Forbidden: Access is denied.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>

```

**Comment by kroitor** [comment]
@Matoran the website now says it's on maintenance...

<img width="934" alt="Screen Shot 2019-07-23 at 18 38 07" src="https://user-images.githubusercontent.com/1294454/61725750-09e28900-ad79-11e9-8e46-7696a5ad7943.png">

How do you suggest to handle it?

**Comment by kroitor** [comment]
@Matoran we've reached out to the Mandala exchange, and it is going to be back online ASAP. Let us know if that doesn't answer it. Closing this for now if you don't mind.

**Comment by Matoran** [comment]
Hehe I didn't have this maintenance page. Mandala is back :).
