### ISSUE TITLE
How to use use asyncio coroutines with threads in Python?

### ISSUE THREAD

**Issue by WoutervDijk** [ccxt/ccxt#5678]
OS: Windows 10 x64
Programming language: Python 3.7.4
CCXT Version: 1.18.1045
Binance exchange

Hey Guys.
I am trying to get asyncio working in ccxt and I seem to continuously get the following error: ```Timeout context manager should be used inside a task```

Here are two pieces of code, which both reproduce the problem:

```
import ccxt.async_support as ccxt
import asyncio

binance = ccxt.binance({"apiKey": "Key",
                        "secret": "secret",
                        "verbose": True})
async def getBalance():
    balance = await binance.fetch_balance()
    print(balance)
async def main():
    await getBalance()
asyncio.run(main())
```
Resulting error:
```
Request: GET https://api.binance.com/api/v1/exchangeInfo None None
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 2060, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Documents/Python/BinanceSellTool/test.py", line 12, in <module>
    asyncio.run(main())
  File "C:\Python37\Lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Python37\Lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:/Documents/Python/BinanceSellTool/test.py", line 11, in main
    await getBalance()
  File "C:/Documents/Python/BinanceSellTool/test.py", line 8, in getBalance
    balance = await binance.fetch_balance()
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\binance.py", line 310, in fetch_balance
    await self.load_markets()
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\base\exchange.py", line 184, in load_markets
    markets = await self.fetch_markets(params)
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\binance.py", line 213, in fetch_markets
    response = await self.publicGetExchangeInfo(params)
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\binance.py", line 1219, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\base\exchange.py", line 117, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\base\exchange.py", line 140, in fetch
    proxy=self.aiohttp_proxy) as response:
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\aiohttp\client.py", line 417, in _request
    with timer:
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\aiohttp\helpers.py", line 568, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000017EABE43D08>
````

Second version, this case I am running it in a separate thread from main. Which I need for my program:
```
import ccxt.async_support as ccxt
import asyncio
import threading
binance = ccxt.binance({"apiKey": "Key",
                        "secret": "secret",
                        "verbose": True})
async def getBalance():
    balance = await binance.fetch_balance()
    print(balance)
async def main():
    await getBalance()
def functionInNewThread():
    asyncio.set_event_loop(asyncio.new_event_loop())
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())

thread = threading.Thread(target=functionInNewThread)
thread.start()
thread.join()
```
This results in the same error:
```
Request: GET https://api.binance.com/api/v1/exchangeInfo None None
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Python37\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python37\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Documents/Python/BinanceSellTool/test.py", line 15, in functionInNewThread
    loop.run_until_complete(main())
  File "C:\Python37\Lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:/Documents/Python/BinanceSellTool/test.py", line 11, in main
    await getBalance()
  File "C:/Documents/Python/BinanceSellTool/test.py", line 8, in getBalance
    balance = await binance.fetch_balance()
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\binance.py", line 310, in fetch_balance
    await self.load_markets()
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\base\exchange.py", line 184, in load_markets
    markets = await self.fetch_markets(params)
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\binance.py", line 213, in fetch_markets
    response = await self.publicGetExchangeInfo(params)
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\binance.py", line 1219, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\base\exchange.py", line 117, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\ccxt\async_support\base\exchange.py", line 140, in fetch
    proxy=self.aiohttp_proxy) as response:
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\aiohttp\client.py", line 417, in _request
    with timer:
  File "C:\Users\wouter\.virtualenvs\BinanceSellTool-8SG2lztG\lib\site-packages\aiohttp\helpers.py", line 568, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task

binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018791D21E48>
```

My problem is that I need to call this code in a separate thread from main. Which for some gives a run-time error by aiohttp.
Note that calling
```asyncio.get_event_loop().run_until_complete(main())```
 works, but only in the main thread, which is not what we want. Not to consider that the code also DOESN'T work with asyncio.run in the main thread.

**Comment by kroitor** [comment]
Hi!

Does this help? ↓

- https://www.google.com/search?q=how+to+asyncio+threads
- https://hackernoon.com/threaded-asynchronous-magic-and-how-to-wield-it-bba9ed602c32
- https://pymotw.com/3/asyncio/executors.html
- https://stackoverflow.com/questions/28492103/how-to-combine-python-asyncio-with-threads
- https://gist.github.com/lars-tiede/01e5f5a551f29a5f300e

```Python
from threading import Thread
import asynciodef start_loop(loop):
    asyncio.set_event_loop(loop)
    loop.run_forever()new_loop = asyncio.new_event_loop()
t = Thread(target=start_loop, args=(new_loop,))
t.start()
```

<img width="910" alt="Screen Shot 2019-08-13 at 22 32 11" src="https://user-images.githubusercontent.com/1294454/62971338-38a0cc00-be1a-11e9-8687-b0817a9de944.png">

**Comment by kroitor** [comment]
@WoutervDijk see this example:

- https://github.com/ccxt/ccxt/blob/master/examples/py/async-with-threads.py

```Python
# -*- coding: utf-8 -*-

import asyncio
import threading
import os
import sys
import ccxt.async_support as ccxt


async def test(loop):
    bittrex = ccxt.bittrex({
        'asyncio_loop': loop,  # ←---------------------------- ADDED THIS
    })
    print(await bittrex.fetch_ticker('ETH/BTC'))
    await bittrex.close()  # ←---------------------------- ADDED THIS


def functionInNewThread():
    asyncio.set_event_loop(asyncio.new_event_loop())
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test(loop))

thread = threading.Thread(target=functionInNewThread)
thread.start()
thread.join()
```

**Comment by WoutervDijk** [comment]
Thanks for the response @kroitor! The second response is very useful. It seems to work for now. I'll check it out in detail tomorrow. I would like to note, that I can not find the asyncio_loop: loop in the documentation. Would probably be good to add that in the docs!
As a side note, could you please explain why this has to be added? I am very curious!

**Comment by kroitor** [comment]
> As a side note, could you please explain why this has to be added? I am very curious!

The default loop created in your main thread by asyncio can't be used in a child thread, and the exchange implementation requires a loop to execute on. If you don't specify it, it will use the default loop created by asyncio and that is supposed to be used from the main thread. Therefore you have to specify a new threaded loop to a new threaded exchange, if you want to execute async exchange calls from a child thread. In short, asyncio module is one type of concurrency and it wants to manage everything, and the threads module is a different type of concurrency and it also wants to manage everything, so they inevitably conflict. To be honest, combining the two is not the best idea. Everything you would need `threads` for – can be done with pure asyncio.

> Besides, one more "problem" is that asyncio.run still doesn't work in this case. Which doesn't matter now since we got a workaround. But the python docs really push to use asyncio.run instead of the lower lever loop stuff (which we use now). Maybe consider a way to get it fixed?

Will look into that as well.

**Comment by frosty00** [comment]
```
import asyncio
import aiohttp

loop = asyncio.get_event_loop()
loop.set_debug(True)
async def wat():
    async with aiohttp.ClientSession() as session:
        async with session.get('https://www.youtube.com/') as response:
            print(await response.text())
asyncio.run(wat())
```

^ this works

```
import asyncio
import aiohttp

loop = asyncio.get_event_loop()
loop.set_debug(True)
async def wat():
    async with aiohttp.ClientSession(loop=loop) as session:
        async with session.get('https://www.youtube.com/') as response:
            print(await response.text())
asyncio.run(wat())
```

this breaks 0:

**Comment by frosty00** [comment]
asyncio.run creates a new event loop, which is kinda _homoerotic_

**Comment by frosty00** [comment]
```
async def wat():
    loop = asyncio.get_event_loop()
    async with aiohttp.ClientSession(loop=loop) as session:
        async with session.get('https://www.youtube.com/') as response:
            print(await response.text())
asyncio.run(wat())
```

this works (note how the loop is gotten after asyncio.run is called. will try fix this in ccxt...)

**Comment by frosty00** [comment]
```
async def wat():
    loop = asyncio.get_event_loop()
    binance = ccxt.binance({'loop': loop})
    print(await binance.load_markets())
    print(await binance.fetch_order_book('ETH/BTC'))
    await binance.close()
asyncio.run(wat())
```

^ this code will work. Note you have to instantiate either binance or the loop inside a coroutine for the correct event loop to be selected )

**Comment by WoutervDijk** [comment]
Thanks for the response! This is has been great help. Have a good day!

**Comment by kroitor** [comment]
@frosty00

```Python
binance = ccxt.binance({'asyncio_loop': loop})  # it has to be asyncio_loop here ;)
```
