### ISSUE TITLE
Cannot find module './../../static_dependencies/elliptic'

### ISSUE THREAD

**Issue by anwar-github** [ccxt/ccxt#5685]
Error: Cannot find module './../../static_dependencies/elliptic'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/anwar/Public/honestmining/back-end/backup/mnbegeneral/node_modules/ccxt/js/base/functions/crypto.js:9:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/anwar/Public/honestmining/back-end/backup/mnbegeneral/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/anwar/Public/honestmining/back-end/backup/mnbegeneral/node_modules/ccxt/js/base/functions.js:22:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/anwar/Public/honestmining/back-end/backup/mnbegeneral/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by anwar-github** [comment]
thanks @kroitor

**Comment by kroitor** [comment]
@anwar-github thx to you for reporting and to @frosty00 for fixing it! )
