### ISSUE TITLE
ItBit placing order and other errors

### ISSUE THREAD

**Issue by evgen-y2k** [ccxt/ccxt#5699]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu 18.04
- Programming Language version: Python 2.7
- CCXT version:1.18.1038
- Exchange: ItBit
- Method: all based on create order

I try to place limit order but have errors.
First example:
res = mk.create_limit_sell_order("XBTUSD", {
            "amount": amount,
            "price": price,
            "postOnly": True
        })

Output:
Traceback (most recent call last):
  File "/home/jo/uwork/arbitrage/bot/bot.py", line 567, in <module>
    itbit.limit_sell(14000, 0.001)
  File "/home/jo/uwork/arbitrage/bot/bot.py", line 111, in limit_sell
    "postOnly": True
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1665, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/itbit.py", line 461, in create_order
    raise ExchangeError(self.id + ' createOrder requires a walletId parameter')
ccxt.base.errors.ExchangeError: itbit createOrder requires a walletId parameter

Second variant:

res = mk.private_post_wallets_walletid_orders({
            "side": "buy",
            "type": "limit",
            "currency": "XBT",
            "amount": amount,
            "display": amount,
            "price": price,
            "instrument": "XBTUSD",
            "postOnly": True
        })

Output:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 535, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.itbit.com/v1/wallets/%7BwalletId%7D/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jo/uwork/arbitrage/bot/bot.py", line 566, in <module>
    itbit.limit_buy(8000, 0.001)
  File "/home/jo/uwork/arbitrage/bot/bot.py", line 103, in limit_buy
    "postOnly": True
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 432, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/itbit.py", line 526, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 451, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 548, in fetch
    self.handle_rest_errors(http_status_code, http_status_text, http_response, url, method)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 573, in handle_rest_errors
    raise error(' '.join([method, url, string_code, http_status_text, body]))
ccxt.base.errors.AuthenticationError: POST https://api.itbit.com/v1/wallets/{walletId}/orders 401 Unauthorized {"code":10002,"description":"Your request lacked a valid signature, and could not be authenticated.","requestId":"d24dce58-e13e-4e01-9c36-bce13b51ba14"}

Also there is error in mk.fetch_orders("XBTUSD"). Output:

Traceback (most recent call last):
  File "/home/jo/uwork/arbitrage/bot/bot.py", line 575, in <module>
    itbit.get_orders()
  File "/home/jo/uwork/arbitrage/bot/bot.py", line 89, in get_orders
    res = self.mk.fetch_orders(self.PAIR)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/itbit.py", line 412, in fetch_orders
    raise ExchangeError(self.id + ' fetchOrders requires a walletId parameter')
ccxt.base.errors.ExchangeError: itbit fetchOrders requires a walletId parameter

Help me please

P.S. fetch_balance() works correctly, I see all balances, auth works.

**Comment by kroitor** [comment]
@evgen-y2k 

```
ccxt.base.errors.ExchangeError: itbit createOrder requires a walletId parameter
```

↑ This line says that the method you're trying to call requires an extra `walletId` param. You would pass the wallet id in the same way you would override any other params with unified calls, as described in the Manual, here: 

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```Python
res = mk.create_limit_sell_order("XBTUSD", {
    "amount": amount,
    "price": price,
    "postOnly": True,
    "walletId": YOUR_WALLET_ID,  # you can use fetchWallets to get the wallet id
})
```

Let us know if the above does not help.

**Comment by evgen-y2k** [comment]
Thank you. But your example not working with "XBTUSD", need change it to "BTC/USD" and it is strange because original symbol on ItBit is "XBTUSD".

**Comment by kroitor** [comment]
@evgen-y2k 

> But your example not working with "XBTUSD", need change it to "BTC/USD"

You're right, i didn't pay attention to the symbol, just copied from your code above.

> and it is strange because original symbol on ItBit is "XBTUSD".

It is not strange, if you consider this: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
