### ISSUE TITLE
AttributeError while fetching order by id on livecoin

### ISSUE THREAD

**Issue by fan-tom** [ccxt/ccxt#5746]
- CCXT version:
1.18.977
- Exchange:
livecoin
- Method:
find_broadly_matched_key

```python
    def find_broadly_matched_key(self, broad, string):
        """A helper method for matching error strings exactly vs broadly"""
        keys = list(broad.keys())
        for i in range(0, len(keys)):
            key = keys[i]
            if string.find(key) >= 0:
                return key
        return None
```
Here if string is None, `string.find` will throw `AttributeError: 'NoneType' object has no attribute 'find'`

Logs with verbose=true

```
 Request: GET https://api.livecoin.net/exchange/order?orderId=51672290651 {'Api-Key': <key>, 'Sign': <sign>, 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

 Response: GET https://api.livecoin.net/exchange/order?orderId=51672290651 200 <CIMultiDictProxy('Server': 'nginx', 'Date': 'Thu, 29 Aug 2019 06:08:25 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000', 'Content-Encoding': 'gzip')> {"success":false,"exception":"ORDER [51672290651] NOT FOUND","errorMessage":"ORDER [51672290651] NOT FOUND"}
 Exception while getting order 51672290651: 'NoneType' object has no attribute 'find'
 Traceback (most recent call last):
   File <my code>, line 501, in get_order
     order = await self.api.fetch_order(id=order_id)
   File "/usr/local/lib/python3.7/site-packages/ccxt/async_support/livecoin.py", line 514, in fetch_order
     response = await self.privateGetExchangeOrder(self.extend(request, params))
   File "/usr/local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 117, in fetch2
     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
   File "/usr/local/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 168, in fetch
     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response)
   File "/usr/local/lib/python3.7/site-packages/ccxt/async_support/livecoin.py", line 838, in handle_errors
     broadKey = self.findBroadlyMatchedKey(broad, message)
   File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 472, in find_broadly_matched_key
     if string.find(key) >= 0:
 AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by kroitor** [comment]
@fan-tom can you please post your verbose request+response that triggered the error? 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by fan-tom** [comment]
Updated issue with verbose logs
