### ISSUE TITLE
Transpilation Error

### ISSUE THREAD

**Issue by ahmedbodi** [ccxt/ccxt#5771]
```
npm run transpile

> ccxt@1.18.1115 transpile /root/ccxt
> node build/transpile

/root/ccxt/build/transpile.js:1020
        [ /module\.exports = [^\;]+\;\n/s, '' ],
          ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.18.1115 transpile: `node build/transpile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ccxt@1.18.1115 transpile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`` `

**Comment by kroitor** [comment]
What's your version of Node.js?

**Comment by ahmedbodi** [comment]
Was caused by Node v8. Upgraded and all fixed
