### ISSUE TITLE
Python3 ValueError: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by ahmedbodi** [ccxt/ccxt#5779]
OS: Ubuntu 18
Language: Python3
Branch: #4817 (but not using the changes from there in this case)
Error: ValueError: dictionary update sequence element #0 has length 1; 2 is required
Traceback
`>>> tasks.fetchExchangeWallets(3)
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/root/dev/paymecoins/exchange_manager/tasks.py", line 105, in fetchExchangeWallets
    balances = client.fetchBalance(symbol)
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.18.1115-py3.6.egg/ccxt/yobit.py", line 200, in fetch_balance
    response = self.privatePostGetInfo(params)
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.18.1115-py3.6.egg/ccxt/base/exchange.py", line 435, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.18.1115-py3.6.egg/ccxt/base/exchange.py", line 458, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.18.1115-py3.6.egg/ccxt/base/exchange.py", line 453, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.18.1115-py3.6.egg/ccxt/yobit.py", line 779, in sign
    }, query))
  File "/usr/local/lib/python3.6/dist-packages/ccxt-1.18.1115-py3.6.egg/ccxt/base/exchange.py", line 746, in extend
    result.update(arg)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
``
```

**Comment by kroitor** [comment]
Plz paste your verbose output:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by frosty00** [comment]
can be closed...
