### ISSUE TITLE
OceanEx Response Parser breaks on certain endpoints

### ISSUE THREAD

**Issue by OliverNChalk** [ccxt/ccxt#5795]
Hello CCXT team, it appears your response parser for OceanEx is not handling certain endpoints properly. These orders execute successfully but throw an error upon attempting to parse the result. This seems like it should hopefully be an easy fix but it renders ccxt.oceanex temporarily unusable.

If you are too busy to address this issue can you point me to where you are handling OceanEx REST responses and I'll take a look myself?

- OS: Ubuntu 18.04
- Programming Language version: Nodejs v10.8.0
- CCXT version: 1.18.1132
- Exchange: OceanEx
- Method: OceanEx.cancelOrders(), OceanEx.cancel_all_orders(), probably all non standard APIs

CODE:
```
let oceanExAPI = new ccxt.oceanex(
    {
        "apiKey": process.env.OCEANEX_UID,
        "secret": fs.readFileSync("./key.pem").toString(),
        "enableRateLimit": true
    }
);
oceanExAPI.verbose = true;
let targetIDs = [403750860, 403750741];  // Strings vs numbers makes no difference here
oceanExAPI.cancelOrders(targetIDs).then(console.info).catch(console.error);
```

RESULT:
```
fetch:
 oceanex POST https://api.oceanex.pro/v1/order/delete/multi?user_jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJJRDRCMUFGNEQ3N0YiLCJkYXRhIjp
7ImlkcyI6WzQwMzc1MDg2MCw0MDM3NTA3NDFdfX0.FKYSWjB4SxRpG6rlQsd-M7tfU0WkwmqhUmSY3ya9qYTCL4zxALK1LeEEGb2IHcs1wGwDtCsV4FYLt0OzFbiTCy2xn0ME0IUHzPxNDP2m
ms4HSZsVeS8Dr4LrIwVK6qeiKGSqNfxQIZ1r2VOMeu9rNtKwA6LKv7tLSPl_tJNHbUyP2lY7XuC7t4_Jpnr4hCcL-6DQwQ8ZhOUBUe9w4RCjIvXDRj1CuEM8J9nu-3vV1g53Uh5tOCbmXLkcr
LHRQJhzxTWXO6zGu4ANzw7tsZ6KjmpW3mukOx6PAJgPIAtAdW3bENPDudSPB7mImqoOVhhVfYiCiRQjzOr8fplzAQgh8g
Request:
 { 'Content-Type': 'application/json' }
 undefined
handleRestResponse:
 oceanex POST https://api.oceanex.pro/v1/order/delete/multi?user_jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJJRDRCMUFGNEQ3N0YiLCJkYXRhIjp
7ImlkcyI6WzQwMzc1MDg2MCw0MDM3NTA3NDFdfX0.FKYSWjB4SxRpG6rlQsd-M7tfU0WkwmqhUmSY3ya9qYTCL4zxALK1LeEEGb2IHcs1wGwDtCsV4FYLt0OzFbiTCy2xn0ME0IUHzPxNDP2m
ms4HSZsVeS8Dr4LrIwVK6qeiKGSqNfxQIZ1r2VOMeu9rNtKwA6LKv7tLSPl_tJNHbUyP2lY7XuC7t4_Jpnr4hCcL-6DQwQ8ZhOUBUe9w4RCjIvXDRj1CuEM8J9nu-3vV1g53Uh5tOCbmXLkcr
LHRQJhzxTWXO6zGu4ANzw7tsZ6KjmpW3mukOx6PAJgPIAtAdW3bENPDudSPB7mImqoOVhhVfYiCiRQjzOr8fplzAQgh8g 201 Created
Response:
 { Accept: '*/*',
  'Accept-Encoding': 'gzip',
  'Access-Control-Allow-Credentials': 'true',
  'Access-Control-Allow-Headers':
   'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization',
  'Access-Control-Allow-Methods': 'GET, PUT, POST, DELETE, PATCH, OPTIONS',
  'Access-Control-Allow-Origin': 'https://oceanex.pro',
  'Cache-Control': 'max-age=0, private, must-revalidate',
  'Cdn-Loop': 'cloudflare',
  'Cf-Connecting-Ip': '134.209.149.243',
  'Cf-Ipcountry': 'IN',
  'Cf-Ray': '51503651dcf9df47-BOM',
  'Cf-Visitor': '{"scheme":"https"}',
  Connection: 'close',
  'Content-Length': '578',
  'Content-Security-Policy':
   'default-src \'self\';style-src \'self\' \'unsafe-inline\';style-src-elem \'self\' \'unsafe-inline\' translate.googleapis.com fonts.googleapis
.com;script-src \'self\' \'unsafe-inline\' \'unsafe-eval\' *.identitymind.com *.cdnwidget.com *.cdnbasket.net *.polyfill.io *.google-analytics.co
m *.pusher.com ssl.captcha.qq.com *.recaptcha.net recaptcha.net www.gstatic.com *.gstatic.cn www.google-analytics.com;script-src-elem \'self\' \'
unsafe-inline\' *.oceanex.pro *.identitymind.com *.polyfill.io *.cdnwidget.com www.gstatic.com *.recaptcha.net recaptcha.net ssl.captcha.qq.com w
ww.google.com *.google-analytics.com *.pusher.com *.gstatic.cn translate.googleapis.com translate.google.com;font-src \'self\' data: *;img-src da
ta: blob: \'self\' *;form-action \'self\';connect-src \'self\' *.oceanex.pro *.cdnwidget.com ws://ws-slanger.oceanex.pro wss://ws-slanger.oceanex
.pro wss://ws-slanger.oceanex.pro:443 *.cdnbasket.net *.sentry.io *.google-analytics.com *.pusher.com *.doubleclick.net sentry.io translate.googl
eapis.com;frame-ancestors \'self\';frame-src \'self\' ssl.captcha.qq.com www.google.com recaptcha.net;object-src \'none\';report-uri https://sent
ry.io/api/1504690/security/?sentry_key=98071b02061b46fa9a78c4960265ecc5',
  'Content-Type': 'application/json',
  Date: 'Thu, 12 Sep 2019 07:36:45 GMT',
  Etag: 'W/"b740f8111d7184a7dad19ad834d3fe8f"',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Host: 'api.oceanex.pro',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=d2241222e7a6d0e062b2a8416d18b942f1568273805; expires=Fri, 11-Sep-20 07:36:45 GMT; path=/; domain=.oceanex.pro; HttpOnly; Secure',
  'Strict-Transport-Security': 'max-age=15724800; includeSubDomains',
  'User-Agent': 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)',
  Vary: 'Origin',
  Version: 'HTTP/1.1',
  'X-Forwarded-For': '134.209.149.243',
  'X-Forwarded-Host': 'api.oceanex.pro',
  'X-Forwarded-Port': '443',
  'X-Forwarded-Proto': 'https',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Original-Forwarded-For': '134.209.149.243',
  'X-Original-Uri':
   '/v1/order/delete/multi?user_jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJJRDRCMUFGNEQ3N0YiLCJkYXRhIjp7ImlkcyI6WzQwMzc1MDg2MCw0MDM3NTA3NDFdfX0.FKYSWjB4SxRpG6rlQsd-M7tfU0WkwmqhUmSY3ya9qYTCL4zxALK1LeEEGb2IHcs1wGwDtCsV4FYLt0OzFbiTCy2xn0ME0IUHzPxNDP2mms4HSZsVeS8Dr4LrIwVK6qeiKGSqNfxQIZ1r2VOMeu9rNtKwA6LKv7tLSPl_tJNHbUyP2lY7XuC7t4_Jpnr4hCcL-6DQwQ8ZhOUBUe9w4RCjIvXDRj1CuEM8J9nu-3vV1g53Uh5tOCbmXLkcrLHRQJhzxTWXO6zGu4ANzw7tsZ6KjmpW3mukOx6PAJgPIAtAdW3bENPDudSPB7mImqoOVhhVfYiCiRQjzOr8fplzAQgh8g',
  'X-Real-Ip': '134.209.149.243',
  'X-Request-Id': '838a178140928c6946fe4bebe998f910',
  'X-Robots-Tag': 'noindex',
  'X-Runtime': '0.072032',
  'X-Scheme': 'https' }
 {"code":0,"message":"Operation successful","data":[{"id":403750741,"side":"buy","ord_type":"limit","price":"0.014","avg_price":"0.0","state":"cancelling","market":"ethbtc","created_at":"2019-09-12T07:33:39Z","created_on":1568273619,"volume":"0.1","remaining_volume":"0.1","executed_volume":"0.0","trades_count":0},{"id":403750860,"side":"buy","ord_type":"limit","price":"0.014","avg_price":"0.0","state":"cancelling","market":"ethbtc","created_at":"2019-09-12T07:33:43Z","created_on":1568273623,"volume":"0.1","remaining_volume":"0.1","executed_volume":"0.0","trades_count":0}]}

TypeError: Cannot use 'in' operator to search for 'ethbtc' in undefined
    at oceanex.parseOrder (/root/cryptology/kludgebot-3000/node_modules/ccxt/js/oceanex.js:549:26)
    at Object.values.map.order (/root/cryptology/kludgebot-3000/node_modules/ccxt/js/base/Exchange.js:1167:77)
    at Array.map (<anonymous>)
    at oceanex.parseOrders (/root/cryptology/kludgebot-3000/node_modules/ccxt/js/base/Exchange.js:1167:45)
    at oceanex.cancelOrders (/root/cryptology/kludgebot-3000/node_modules/ccxt/js/oceanex.js:617:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by kroitor** [comment]
@OliverNChalk hi! Thx for reporting! I've uploaded a fix for it, and it should arrive in version 1.18.1134 in 15 minutes. We will be happy if you let us know whether it resolves the issue for you or not.
