### ISSUE TITLE
IDEX cancel Order - invalid literal for int() with base 10

### ISSUE THREAD

**Issue by arenstar** [ccxt/ccxt#5816]
I am trying to cancel an IDEX order and recieving the following error.

```
exchange.cancelOrder(orderId='0x813dc1ca9828978e280120c5ff529dfde6d385c683e450c1eef33c7858ecbc8a', symbol='SWM/ETH', params={})
```

invalid literal for int() with base 10: '0x813dc1ca9828978e280120c5ff529dfde6d385c683e450c1eef33c7858ecbc8a'

Diving into the code gets quite confusing..
Any help would be appreciated

**Comment by frosty00** [comment]
You are passing a txhash instead of an order id. These are not the same thing. For example this is the output of `fetchMyTrades`:

```
{'amount': 0.0001,
 'cost': 0.16,
 'datetime': '2019-08-27T21:50:27.000Z',
 'fee': {'cost': 1e-07, 'currency': 'IDEX', 'rate': 0.0009999999999999998},
 'id': '4503201',
 'info': {'amount': '0.0001',
          'buyerFee': '0.0000001',
          'date': '2019-08-27 21:50:27',
          'gasFee': '0.00068',
          'maker': '0x0ab991497116f7f5532a4c2f4f7b1784488628e1',
          'orderHash': '0xd0a46ce284a8e2274457bdc4b35b248ae3a72f0865a1f3cf0fe21d02486a299e',
          'price': '1600',
          'sellerFee': '0.00032',
          'taker': '0x1a961bc2e0d619d101f5f92a6be752132d7606e6',
          'tid': 4503201,
          'timestamp': 1566942627,
          'tokenBuy': '0xb705268213d593b8fd88d3fdeff93aff5cbdcfae',
          'tokenSell': '0x0000000000000000000000000000000000000000',
          'total': '0.16',
          'transactionHash': '0xe68fcfb140a013e0be28904c7fa126e3f8de3265073e5c688a8a17cac7060568',
          'type': 'buy',
          'usdValue': '29.6096602297659136',
          'uuid': 'ae321f00-c914-11e9-9e17-6374e709900a'},
 'order': '0xd0a46ce284a8e2274457bdc4b35b248ae3a72f0865a1f3cf0fe21d02486a299e',
 'price': 1600.0,
 'side': 'buy',
 'symbol': 'IDEX/ETH',
 'takerOrMaker': 'maker',
 'timestamp': 1566942627000,
 'type': 'limit'}
```

^ note that id is a number

**Comment by arenstar** [comment]
@frosty00 yes that precisely what i was thinking too -
Is the following commit a fix for python too?

https://github.com/frosty00/ccxt/commit/bf1998ee60f7280eada77e9ff1a4d4cbc970ab67

**Comment by kroitor** [comment]
@arenstar yep, this is going to be fixed shortly.

**Comment by arenstar** [comment]
@kroitor thanks for the fix however im now recieving this from idex
`idex Order no longer available.`

**Comment by kroitor** [comment]
@arenstar can you paste the code to reproduce it?

**Comment by arenstar** [comment]
sure 
```
2019-09-25 00:20:42,030 - INFO - run.py - Cancelling order: 2275823960
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 540, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.idex.market/cancel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 ......
    self.cancel_all_open_orders()
  File "/app/bots/market_maker/libs.py", line 483, in cancel_all_open_orders
    ourOrders = self.exchange.cancelOrder(x['id'], symbol=self.trading_symbol)
  File "/usr/local/lib/python3.6/site-packages/ccxt/idex.py", line 495, in cancel_order
    response = self.privatePostCancel(self.extend(request, signature))
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 436, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 459, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 455, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 552, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/idex.py", line 977, in handle_errors
    raise self.exceptions[response['error']](self.id + ' ' + response['error'])
ccxt.base.errors.InvalidOrder: idex Order no longer available.
```

**Comment by kroitor** [comment]
@arenstar sorry, but that's not the code to reproduce the error – that's an error stacktrace. We need to see how you generate that error – for that we need to see a short but a complete snippet of code that triggers the error. And we need the **verbose request/response** as decribed here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

> ccxt.base.errors.InvalidOrder: idex Order no longer available.

Are you sure that the order is available for canceling (still open, not closed yet) ?

**Comment by arenstar** [comment]
Sure.. 2 mins ill have you some code ^^

Yes the order is still open on the webui

**Comment by arenstar** [comment]
```
import ccxt 
exchange = getattr(ccxt, 'idex')({
    'apiKey': 'api:MYKEY,
    'privateKey': '1234567780',
    'walletAddress': '0xc....',
    'enableRateLimit': True,
    #'verbose': True,
})

trading_symbol = "SWM/ETH"

orders = exchange.fetchOpenOrders(symbol = trading_symbol)
for x in orders:
    exchange.cancelOrder(x['id'], symbol = trading_symbol)
