### ISSUE TITLE
Python ECDSA TypeError

### ISSUE THREAD

**Issue by heckad** [ccxt/ccxt#5852]
- OS: docker image op python3.7.4
- Programming Language version: python3.7.4
- CCXT version:  1.18.1127
- Exchange: any
- Method: start aihttp app

Sometimes when start aihttp app start using gunicorn fail with stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/worker.py", line 52, in init_process
    super().init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/app/order_crud/app.py", line 24, in <module>
    from order_crud.routes import setup_routes
  File "/home/app/order_crud/routes.py", line 9, in <module>
    from order_crud.controllers.order_manager import OrderView
  File "/home/app/order_crud/controllers/order_manager.py", line 4, in <module>
    from integrations_with_exchanges.models.orders import SmartOrder
  File "/usr/local/lib/python3.7/site-packages/integrations_with_exchanges/__init__.py", line 1, in <module>
    from .rest_clients import BinanceRestClient
  File "/usr/local/lib/python3.7/site-packages/integrations_with_exchanges/rest_clients.py", line 4, in <module>
    from ccxt.async_support import binance
  File "/usr/local/lib/python3.7/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 39, in <module>
    from static_dependencies import ecdsa
  File "/usr/local/lib/python3.7/site-packages/static_dependencies/ecdsa/__init__.py", line 6, in <module>
    __version__ = get_versions()['version']
  File "/usr/local/lib/python3.7/site-packages/static_dependencies/ecdsa/_version.py", line 507, in get_versions
    pieces = git_pieces_from_vcs(cfg.tag_prefix, root, verbose)
  File "/usr/local/lib/python3.7/site-packages/static_dependencies/ecdsa/_version.py", line 298, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by kroitor** [comment]
@heckad for some reason this path is wrong:

- `"/usr/local/lib/python3.7/site-packages/static_dependencies/ecdsa/__init__.py"`

↑ It should be `site-packages/ccxt/python/static_dependencies/ecdsa/__init__.py`...

How did you install CCXT? Did you install any additional packages along with CCXT?

**Comment by kroitor** [comment]
@heckad Also, does this happen with the most recent version of CCXT?

**Comment by heckad** [comment]
I have added the library to common subproject in our microservices app and add it to dependencies in our service by git repo in pipfile. And install it by `pipenv install`

**Comment by kroitor** [comment]
> I have added the library to common subproject in our microservices app and add it to dependencies in our service by git repo in pipfile.

Then this issue is not related to CCXT and is related to the way you install and configure packages with your envinroment, I guess. The dependency in our ccxt/python/static_dependencies is not the same `ecdsa` package that gets installed by pip – those differ in some ways. So, they're not interchangeable. Let me know if that does not answer the question.

**Comment by heckad** [comment]
Hot to right to add ccxt to another lib? I created `setup.py` and added to `install_requires` ccxt.

**Comment by kroitor** [comment]
> I created setup.py and added to install_requires ccxt.

That should be the way to go.

**Comment by heckad** [comment]
But this doesn't work.

**Comment by kroitor** [comment]
@heckad 

- https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires
- https://www.samueldowling.com/2019/03/12/how-to-set-up-a-python-project-and-development-environment/
- https://stackoverflow.com/questions/54475042/python-dependency-hell-a-compromise-between-virtualenv-and-global-dependencies
- https://www.google.com/search?q=how%20to%20add%20python%20dependencies%20requirements%20setup.py%20virtualenv
- ...

**Comment by kroitor** [comment]
> Are you sure that the path is just that? I now install through the pip on a clean python ccxt not contain static_dependencies. It in another dir.

You're right on that, however, it is still not interchangeable with the standard `ecdsa`...

**Comment by heckad** [comment]
Why, in general, is it fond of the number of commits and why did it decide that he would find them in the package installed through pip?

**Comment by kroitor** [comment]
@heckad we will investigate and will get back to you on this issue asap.

**Comment by heckad** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/worker.py", line 52, in init_process
    super().init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/app/order_crud/app.py", line 24, in <module>
    from order_crud.routes import setup_routes
  File "/home/app/order_crud/routes.py", line 9, in <module>
    from order_crud.controllers.order_manager import OrderView
  File "/home/app/order_crud/controllers/order_manager.py", line 5, in <module>
    from integrations_with_exchanges.models.orders import SmartOrder
  File "/usr/local/lib/python3.7/site-packages/integrations_with_exchanges/__init__.py", line 1, in <module>
    from .rest_clients import BinanceRestClient
  File "/usr/local/lib/python3.7/site-packages/integrations_with_exchanges/rest_clients.py", line 4, in <module>
    from ccxt.async_support import binance
  File "/usr/local/lib/python3.7/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 39, in <module>
    from ccxt.static_dependencies import ecdsa
  File "/usr/local/lib/python3.7/site-packages/ccxt/static_dependencies/ecdsa/__init__.py", line 6, in <module>
    __version__ = get_versions()['version']
  File "/usr/local/lib/python3.7/site-packages/ccxt/static_dependencies/ecdsa/_version.py", line 507, in get_versions
    pieces = git_pieces_from_vcs(cfg.tag_prefix, root, verbose)
  File "/usr/local/lib/python3.7/site-packages/ccxt/static_dependencies/ecdsa/_version.py", line 298, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
ValueError: invalid literal for int() with base 10: ''
```
What did you expect from moving the project to another folder? What did you expect from moving the project to another folder? That it will stop looking for `.git` which should not contain in the folder.

**Comment by kroitor** [comment]
@heckad moving the statis_deps inside ccxt is a solution to a different issue, we will debug the `ValueError` and will fix it as well.
