### ISSUE TITLE
Parameter error occur in coinone

### ISSUE THREAD

**Issue by anbukarasi1** [ccxt/ccxt#5873]
Hi team,
Parameter error occur while placing order in coinone site. 
This is my coding.

var coinoneplace = new ccxt.coinone({
  apiKey: '****',
  secret:'****',
  timeout: 15000,
  'adjustForTimeDifference': true,

  disableBeautification: false,
  handleDrift: true,

  enableRateLimit: true

});
coinoneplace.createOrder('BTC/KRW', 'limit', 'buy', 1, 20)

But i get this error,
(node:798) UnhandledPromiseRejectionWarning: ExchangeError: coinone {"errorCode":"107","errorMsg":"Parameter error","result":"error"}
    at coinone.handleErrors (/var/www/html/tradenbot/backend/node_modules/ccxt/js/coinone.js:527:27)
    at response.text.then (/var/www/html/tradenbot/backend/node_modules/ccxt/js/base/Exchange.js:649:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:798) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:798) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Please give me some solution for this issue.
Thank you.

**Comment by kroitor** [comment]
Hello @anbukarasi1, closing this during a cleanup — this report is from the v1 era of the coinone api and the integration has since been rewritten against coinone's v2 and v2.1 surfaces, so the parameter handling you hit no longer exists in the current code. If order placement misbehaves on a current version, a fresh issue with a verbose log would be very welcome. Thanks for the report back then!
