### ISSUE TITLE
Okex3 authentication error

### ISSUE THREAD

**Issue by Burpre** [ccxt/ccxt#5976]
I am trying to access my latest balances on OKEx. This is the code used:

import ccxt
exchange_id = 'okex3'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': 'my_apiKey',
    'secret': 'my_secret',
    'password' : 'my_password',
    'timeout': 30000,
    'enableRateLimit': True,
    'rateLimit': 10000,
    'options': {
        'adjustForTimeDifference': True,  # exchange-specific option
    }
})
okex3 = ccxt.okex3 ()
markets = okex3.load_markets ()
print (okex3.fetch_balance ())

this is the error I received:

Traceback (most recent call last):
  File "c:\Users\USER\Documents\Trading\tempCodeRunnerFile.py", line 22, in <module>
    print (okex3.fetch_balance ())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\okex3.py", line 1305, in fetch_balance
    response = getattr(self, method)(query)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 436, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 459, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 454, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\okex3.py", line 2549, in sign
    self.check_required_credentials()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 1133, in check_required_credentials
    raise AuthenticationError('requires `' + key + '`')
ccxt.base.errors.AuthenticationError: requires `apiKey`

please help

**Comment by kroitor** [comment]
@Burpre your code has an error in it, for some reason you're creating the exchange instance twice and the second time overwrites your api credentials with empty values:

```Python
import ccxt
exchange_id = 'okex3'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({ # ←------- you're instantiating the exchange here once
    'apiKey': 'my_apiKey',
    'secret': 'my_secret',
    'password' : 'my_password',
    'timeout': 30000,
    'enableRateLimit': True,
    'rateLimit': 10000,
    'options': {
        'adjustForTimeDifference': True,  # exchange-specific option
    }
})

# --------------------------------------------------------------------

# no need to instantiate it the second time:
okex3 = ccxt.okex3 ()  # ←-------------------------- DELETE THIS LINE

markets = exchange.load_markets ()  # ←-------------- change these lines
print (exchange.fetch_balance ())  # ←-------------- change these lines
```

**Comment by Burpre** [comment]
Thank you kroitor, I am taking you advice and learning more Python basics. I did implement the changes you suggested:

import ccxt

exchange_id = 'okex3'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({ 

    'apiKey': 'my_apiKey',
    'secret': 'my_secret',
    'password' : 'my_password',
    'timeout': 30000,
    'enableRateLimit': True,
    'rateLimit': 10000,
    'options': {
        'adjustForTimeDifference': True,  
    }

})

markets = exchange.load_markets () 
print (exchange.fetch_balance ())  

And now I am getting this error:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 540, in fetch
    response.raise_for_status()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://www.okex.com/api/spot/v3/accounts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\USER\Documents\Python Scripts\tempCodeRunnerFile.py", line 20, in <module>
    print (exchange.fetch_balance ())  
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\okex3.py", line 1305, in fetch_balance
    response = getattr(self, method)(query)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 436, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 459, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 455, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 552, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\okex3.py", line 2589, in handle_errors
    raise exact[errorCode](feedback)
ccxt.base.errors.AuthenticationError: okex3 {"code":30015,"message":"Invalid OK_ACCESS_PASSPHRASE"}

Can you please help?

**Comment by kroitor** [comment]
@Burpre the password you specified in the password field must be your trading password, not your login password. Make sure that you specified your trading password there correctly.

**Comment by Burpre** [comment]
@kroitor the password required was the passphrase linked to the api. Not the login password nor the trading password.
Don't know if it will help to specify it in the documentation for future users.
Thank you for your help, really appreciate it.

**Comment by Burpre** [comment]
just to be clear it was supposed to be this:
import ccxt

exchange_id = 'okex3'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({

'apiKey': 'my_apiKey',
'secret': 'my_secret',
'password' : 'MY_PASSPHRASE',
'timeout': 30000,
'enableRateLimit': True,
'rateLimit': 10000,
'options': {
    'adjustForTimeDifference': True,  
}
})
