### ISSUE TITLE
Many BigONE methods dysfunctional.

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#6044]
- OS: Linux
- Programming Language version: Python3
- CCXT version: Latest
- Exchange: ccxt.bigone()
- Method: Error has been reproduced on ```withdraw```,  ```createLimitOrder``` and ```fetchBalance```. Will be using ```createLimitBuyOrder``` as example.

```
 bigone.createLimitBuyOrder('XRP/BTC',771.1,3.295e-05)

Request: POST https://big.one/api/v2/viewer/orders {'Authorization': 'PERSONALLY OMITTED', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} {"market_id":"XRP-BTC","side":"BID","amount":"771.1","price":"0.00003295"}

Response: POST https://big.one/api/v2/viewer/orders 404 {'Date': 'Sun, 27 Oct 2019 05:28:57 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '41', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dd6382a829f0eee47be5ec62e1e7c58cf1572154137; expires=Mon, 26-Oct-20 05:28:57 GMT; path=/; domain=.big.one; HttpOnly; Secure', 'X-Frame-Options': 'SAMEORIGIN', 'cache-control': 'max-age=0, private, must-revalidate', 'x-request-id': '2n8mjmu1nieno25odo361i62', 'Via': '1.1 google', 'Alt-Svc': 'clear', 'CF-Cache-Status': 'DYNAMIC', 'Strict-Transport-Security': 'max-age=2592000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '52c244febf3927e4-YYZ'} {"errors":[{"message":"Page not found"}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 539, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://big.one/api/v2/viewer/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1735, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "/usr/local/lib/python3.7/site-packages/ccxt/bigone.py", line 446, in create_order
    response = self.privatePostOrders(self.extend(request, params))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 435, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 458, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 454, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 551, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/bigone.py", line 658, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: bigone {"errors":[{"message":"Page not found"}]}
```
Thanks for viewing.

**Comment by kroitor** [comment]
@karlandoh BigOne v2 API is deprecated, see this PR for more details on v3:  https://github.com/ccxt/ccxt/pull/5951
