### ISSUE TITLE
Liquid Withdrawal Issue

### ISSUE THREAD

**Issue by NescienceSoftware** [ccxt/ccxt#6085]
Having an issue when trying to withdraw cryptocurrency from the Liquid exchange.

When attempting to do so, I get a verification error. (Python, newest CCXT version)

```
client = ccxt.liquid({'apiKey': 'KEY', 'secret': 'SECRET', 'enableRateLimit': True, 'verbose': True})

eth_withdraw = .02
code = "ETH"
amount = eth_withdraw
address = 'ADDRESSHERE'
tag = None
withdrawal = client.withdraw(code, amount, address, tag)
```
Verbose Request:
```
Request: POST https://api.liquid.com/crypto_withdrawals {'X-Quoine-API-Version': '2', 'Content-Type': 'application/json', 'X-Quoine-Auth': 'AUTHREDACTED?', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} {"currency":"ETH","address":"ADDRESS","amount":"0.02"}
```
Response:

```
Response: POST https://api.liquid.com/crypto_withdrawals 422 {'Date': 'Tue, 05 Nov 2019 02:36:54 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '59', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d21e5640397c1435f3fbf97e1b0decfed1572921414; expires=Wed, 04-Nov-20 02:36:54 GMT; path=/; domain=.liquid.com; HttpOnly; Secure, _vax_session=BAh7CDoJbGFuZzoHZW5JIhl3YXJkZW4udXNlci51c2VyLmtleQY6BkVUWwdbBmkDm%2FAKSSIiJDJhJDEwJEw0STcxNnlvMG9CYlJwd3RnYnJiYU8GOwdUSSIPc2Vzc2lvbl9pZAY7B1RJIiUwNjVmMDNhYzUxYWY5ZWRjM2IxYTU1YjY0ZmEwOTMwYgY7B1Q%3D--0731b34abe4f0259a0ea37657cd5cf1fa59d340a; path=/; secure; HttpOnly', 'Cache-Control': 'no-cache', 'Content-Encoding': 'gzip', 'Status': '422 Unprocessable Entity', 'Strict-Transport-Security': 'max-age=2592000', 'Vary': 'Accept-Encoding', 'Via': '1.1 spaces-router (d458a6f05c96)', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Powered-By': 'Phusion Passenger 5.1.2', 'X-Rack-Cache': 'invalidate, pass', 'X-Request-Id': '323b648d-9849-0678-ddbf-a0f55cc8fc51', 'X-Runtime': '0.033336', 'X-Ua-Compatible': 'IE=Edge,chrome=1', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '530b715998f5577b-IAD'} {"message":"Verification Failed"}
Traceback (most recent call last):
  File "C:\Users\Julian\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 539, in fetch
    response.raise_for_status()
  File "C:\Users\Julian\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.liquid.com/crypto_withdrawals
```

Any help is appreciated as always

**Comment by kroitor** [comment]
Have you checked out the Liquid API documentation? 

- https://developers.liquid.com/#create-crypto-withdrawal

It says:

> NO-TOUCH MODE
> Creating a crypto withdrawal requires user to interactively input 2FA code and confirm via email. This can be a problem if user is trying to build a fully automated system.
> No-touch mode allows human interaction (auth token and email confirmation) to be omitted. No-touch mode can be enabled by adding at least one confirmed Whitelist IP.

↑ Have you enabled it?

**Comment by NescienceSoftware** [comment]
Well, I had not initially, but I saw that page, added whitelisted addresses/tried again for ~10 mins right before making this post last night and going to bed.

But at this point in time, ive tried it again and everything is working as it should. Im assuming there was just a bit of time necessary for their system to accept the whitelisted addresses.

Gracias yet again

**Comment by kroitor** [comment]
@NescienceSoftware ok, thx for the feedback! Hope it helps other users as well.
