### ISSUE TITLE
Coinbase Pro fails to fetch Deposit Addresses.

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#6091]
- Programming Language version: Python3
- CCXT version: Latest
- Exchange: ccxt.coinbasepro()
- Method: ```fetchDepositAddress```

```
coinbasepro.fetchDepositAddress('BTC')

Request: GET https://api.pro.coinbase.com/coinbase-accounts/PERSONALLY_OMITTED/addresses {'CB-ACCESS-KEY': 'PERSONALLY OMITTED', 'CB-ACCESS-SIGN': 'PERSONALLY OMITTED', 'CB-ACCESS-TIMESTAMP': '1573002811', 'CB-ACCESS-PASSPHRASE': 'e5lb6uf9vxd', 'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.pro.coinbase.com/coinbase-accounts/a0b3f9d8-8d9a-5cfb-927e-43eb7182d2b5/addresses 404 {'Date': 'Wed, 06 Nov 2019 01:13:31 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '29', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=ddd6994b5fe04578c5f909a4cb4d7f3421573002811; expires=Thu, 05-Nov-20 01:13:31 GMT; path=/; domain=.pro.coinbase.com; HttpOnly', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'Cache-Control': 'no-store', 'ETag': 'W/"1d-F5hzZtsPyxiCcAo2WNqzlKw+mXk"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'CF-Cache-Status': 'MISS', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '531334939c5baba0-YYZ'} {"message":"Route not found"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 539, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.pro.coinbase.com/coinbase-accounts/a0b3f9d8-8d9a-5cfb-927e-43eb7182d2b5/addresses

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/coinbasepro.py", line 738, in fetch_deposit_address
    response = self.privateGetCoinbaseAccountsIdAddresses(self.extend(request, params))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 435, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/site-packages/ccxt/coinbasepro.py", line 790, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 454, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 551, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/coinbasepro.py", line 786, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: coinbasepro Route not found
```
Thanks for viewing.

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/5843 (I suggest to move this discussion there)

**Comment by karlandoh** [comment]
Alright great, thanks.
