### ISSUE TITLE
BigONE private requests

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#6135]
- CCXT version: 1.19.21
- Exchange: BigONE
- Method: fetchBalance() and others

On all  private requests I got this error:

```
fetch:
 bigone GET https://big.one/api/v2/markets
Request:
 {}
 undefined

handleRestResponse:
 bigone GET https://big.one/api/v2/markets 200 OK
Response:
 { 'Alt-Svc': 'clear',
  'Cache-Control': 'max-age=0, private, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '535343cdcecd97e4-FRA',
  Connection: 'close',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Wed, 13 Nov 2019 19:48:44 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=dc070abd44f8b4612c2b4c5bd674095551573674523; expires=Thu, 12-Nov-20 19:48:43 GMT; path=/; domain=.big.one; HttpOnly; Secure',
  'Strict-Transport-Security': 'max-age=2592000; includeSubDomains',
  'Transfer-Encoding': 'chunked',
  Via: '1.1 google',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Request-Id': '2nbd192gpuu43scvs04vtmm2' }
 {"data":[{"uuid":"01e48809-b42f-4a38-96b1-c4c547365db1","quoteScale":7,"quoteAsset":{"uuid":"0df9c3c3-255a-46d7-ab82-dedae169fba9","symbol":"BTC","name":"Bitcoin"},"name":"PCX-BTC","baseScale":3,"baseAsset":{"uuid":"405484f7-4b03-4378-a9c1-2bd718ecab51","symbol":"PCX","name":"ChainX"}},......,"name":"EOS-USDT","baseScale":2,"baseAsset":{"uuid":"b2708373-f732-4ccf-a8e8-e4f860a7e64a","symbol":"EOS","name":"EOS"}}]}

fetch:
 bigone GET https://big.one/api/v2/viewer/accounts
Request:
 { Authorization: 'Bearer eyJhbGciO.............4ox74ri7o' }

 undefined

handleRestResponse:
 bigone GET https://big.one/api/v2/viewer/accounts 404 Not Found
Response:
 { 'Alt-Svc': 'clear',
  'Cache-Control': 'max-age=0, private, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '535343da0e8b972a-FRA',
  Connection: 'close',
  'Content-Length': '41',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Wed, 13 Nov 2019 19:48:46 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=df2f76739603721367bfd35da88c059881573674525; expires=Thu, 12-Nov-20 19:48:45 GMT; path=/; domain=.big.one; HttpOnly; Secure',
  'Strict-Transport-Security': 'max-age=2592000; includeSubDomains',
  Via: '1.1 google',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Request-Id': '2nbd1964dv7nj527f84he8k3' }
 {"errors":[{"message":"Page not found"}]}

{ ExchangeError: bigone {"errors":[{"message":"Page not found"}]}
    at bigone.handleErrors (/var/www/node/bot/test/node_modules/ccxt/js/bigone.js:703:23)
    at response.text.then (/var/www/node/bot/test/node_modules/ccxt/js/base/Exchange.js:630:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  constructor: [Function: ExchangeError],
  name: 'ExchangeError' }

```

But public requests work fine. Exchange problem? Or may be authorization?

**Comment by kroitor** [comment]
> But public requests work fine. Exchange problem? Or may be authorization?

BigONE v2 is deprecated and not working anymore:

- https://github.com/ccxt/ccxt/issues/5301
- https://github.com/ccxt/ccxt/pull/5835
- https://github.com/ccxt/ccxt/pull/5951

**Comment by karlandoh** [comment]
Sounds good, thanks! Seems people are waiting on the v3 integration.
