### ISSUE TITLE
Bitmart Limit Orders contain invalid XPM signature.

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#6175]
- OS: Linux
- Programming Language version: Python3
- CCXT version: Latest
- Exchange: ccxt.bitmart()
- Method: ```createLimitOrder``` Will be using WAVES/BTC as an example.

```
bitmart.createLimitSellOrder('WAVES/BTC','151',0.00007)

Request: POST https://openapi.bitmart.com/v2/orders?symbol=WAVES_BTC&side=sell&amount=151.0&price=7e-05 {'Content-Type': 'application/json', 'X-BM-TIMESTAMP': '1574518031205', 'X-BM-AUTHORIZATION': 'Bearer LyB0onEIC0mQ7/OFKJH1ZHjYL3MqS8rpb2eOgojwXPKPjp7yAoGTTHZ+ZHH2+te6AdekG7QSFQQ15o9gQNUGq+wY2Ggn4IQ8GO/7jJHYAdtfLxswqbKxlnqPwWZQUN9q1HXVHEecMAwijDAiOkdFbzdOhzKHmarlkNvzGV+XgWuyU1I+sFP/TgIGpKkl4qzuUo7oEqD4HoTPzGhHgxPUgGhqmjhOEIzd6ojSZfDbhjgzzJfdqjukeBIZa7lkbi7kfOge/LArhjWP8Ri/ljZA8XuW3d+8WaIx6Z4Icrr0UvuKzo1ZG2ksMA+da/F9jiSp', 'X-BM-SIGNATURE': '58d675256878aa0cbe371306f066f788861d8d45b32d7c6b9c558509e6960a3b', 'User-Agent': 'python-requests/2.20.0', 'Accept-Encoding': 'gzip, deflate'} {"amount":151.0,"price":7e-05,"side":"sell","symbol":"WAVES_BTC"}

Response: POST https://openapi.bitmart.com/v2/orders?symbol=WAVES_BTC&side=sell&amount=151.0&price=7e-05 400 {'Date': 'Sat, 23 Nov 2019 14:07:10 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '36', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d2f0dca4082ace14f2def0d62da5bf8b31574518030; expires=Mon, 23-Dec-19 14:07:10 GMT; path=/; domain=.bitmart.com; HttpOnly; Secure', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, DELETE', 'Access-Control-Max-Age': '3600', 'Access-Control-Allow-Headers': 'x-requested-with', 'Access-Control-Allow-Credentials': 'true', 'Via': '1.1 google', 'Alt-Svc': 'clear', 'CF-Cache-Status': 'DYNAMIC', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '53a3b53aade9cab4-YYZ'} {"message":"Invalid X-BM-SIGNATURE"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 539, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://openapi.bitmart.com/v2/orders?symbol=WAVES_BTC&side=sell&amount=151.0&price=7e-05

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1740, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "/usr/local/lib/python3.7/site-packages/ccxt/bitmart.py", line 669, in create_order
    response = self.privatePostOrders(self.extend(request, params))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 435, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 458, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 454, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 551, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/bitmart.py", line 844, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bitmart {"message":"Invalid X-BM-SIGNATURE"}
```

Fetching balances work fine, however. Thanks for viewing.

**Comment by ndubel** [comment]
I have the same on JS but not on all pairs. WAVES works fine for me. I don't know the reason

**Comment by kroitor** [comment]
One of the probable causes is the value formatting `&price=7e-05` – the exchange may complain about that...

**Comment by kroitor** [comment]
Let me know if you still have the same issues with Bitmart. Closing this for now. Feel free to reopen it, or just ask further questions, if any.
