### ISSUE TITLE
UPBIT: Cannot cancel open order using ccxt API

### ISSUE THREAD

**Issue by coinaisseur** [ccxt/ccxt#6194]
- OS: Windows 10 Enterprise LTSC v. 1809
- Programming Language version: Javascript
- CCXT version: 1.19.94
- Exchange: UPBIT
- Method: exchange.fetchOpenOrders(<market>)

Good afternoon, I'm trying to cancel an order on Upbit exchange using ccxt, but I'm getting  the following error:

```
Request: DELETE "https://sg-api.upbit.com/v1/order" {'Authorization': 'Bearer <authorization token>'} body: "{"uuid":"3efae1ab-583a-4b2a-aea9-9783ada85aad"}"

Response: "{"error":{"name":"V1::Exceptions::InvalidQueryPayload","message":"Failed to verify the query of Jwt.","dialog":"client"}}"
```

My guess is that the API endpoint is incorrect, but so far I haven't found a solution.

Thanks for helping me out.

**Comment by kroitor** [comment]
Hi!

Does `fetchBalance` work for you?

Check out this issue and let us know if that does not help: https://github.com/ccxt/ccxt/issues/6094

**Comment by coinaisseur** [comment]
Hi @kroitor 

I checked issue #6094 and changed hostname to sg-api.upbit.com. Everything works except for fetchOpenOrders() and cancelOrder() functions. I managed to solve the problem with fetchOpenOrders by changing hostname to "ccxsg.upbit.com/api", but it didn't work with cancelOrder.

Sorry for not pasting code and verbose response, here it is:

Code snippet (I tried to make it as simple as possible):
```
"use strict";
var ccxt = require('ccxt');

var exchange = new ccxt.upbit({
    apiKey: '<api_key>',
    secret: '<secret>',
    hostname: 'sg-api.upbit.com',
    verbose: true
})

async function main() {

    await exchange.loadMarkets()
        .then(async function () {
            var response = await exchange.cancelOrder('333b5521-dbc6-4e99-a2c7-ced299fdc763')
            console.log(response)
        })
        .catch(function (err) {
            console.log(err)
        })
}

main();
````
Verbose response: 

```
fetch:
 upbit DELETE https://sg-api.upbit.com/v1/order
Request:
 {
  Authorization: 'Bearer <authorization_token>',
  'Content-Type': 'application/json'
}
 {"uuid":"333b5521-dbc6-4e99-a2c7-ced299fdc763"}

handleRestResponse:
 upbit DELETE https://sg-api.upbit.com/v1/order 401 Unauthorized
Response:
 {
  'Access-Control-Allow-Headers': 'Authorization, Content-Type, Accept, *',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache',
  Connection: 'close',
  'Content-Encoding': 'gzip',
  'Content-Language': 'en',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Wed, 27 Nov 2019 16:46:16 GMT',
  'Remaining-Req': 'group=default; min=899; sec=29',
  Server: 'Finatra',
  'Transfer-Encoding': 'chunked',
  Vary: 'Origin',
  Via: 'kong/1.3.0',
  'X-Kong-Proxy-Latency': '4',
  'X-Kong-Upstream-Latency': '16',
  'X-Request-Id': '8e97969c-44e9-4fa2-98a2-991aed281330',
  'X-Runtime': '0.009126'
}
 {"error":{"name":"V1::Exceptions::InvalidQueryPayload","message":"Failed to verify the query of Jwt.","dialog":"client"}}
```

Thanks for your help

**Comment by kroitor** [comment]
@coinaisseur hi! I'll debug that and will get back to you soon.

**Comment by coinaisseur** [comment]
Thanks @kroitor

**Comment by kroitor** [comment]
@coinaisseur ok, found it and added a fix, should be ok in version 1.19.99, the new build will arrive in 15 minutes. I'll be happy if you report back whether it resolved the issue for you or not. Thx!

**Comment by coinaisseur** [comment]
Hi @kroitor 

I've tested ccxt's new version, but I'm still getting an error. Here's the verbose response:

```
fetch:
 upbit DELETE https://sg-api.upbit.com/v1/order
Request:
 {
  Authorization: 'Bearer <authorization_token>'
}
 undefined

handleRestResponse:
 upbit DELETE https://sg-api.upbit.com/v1/order 400 Bad Request
Response:
 {
  'Access-Control-Allow-Headers': 'Authorization, Content-Type, Accept, *',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache',
  Connection: 'close',
  'Content-Encoding': 'gzip',
  'Content-Language': 'en',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Wed, 27 Nov 2019 17:51:50 GMT',
  'Remaining-Req': 'group=default; min=899; sec=29',
  Server: 'Finatra',
  'Transfer-Encoding': 'chunked',
  Vary: 'Origin',
  Via: 'kong/1.3.0',
  'X-Kong-Proxy-Latency': '1',
  'X-Kong-Upstream-Latency': '16',
  'X-Request-Id': 'e20f0349-8d40-4284-a2e2-b3f061e1fc07',
  'X-Runtime': '0.010378'
}
 {"error":{"name":"validation_error","message":"uuid is missing"}}
```

Thanks for your help.

**Comment by kroitor** [comment]
@coinaisseur I will check for that and will report back again shortly, pardon for the inconvenience.

**Comment by coinaisseur** [comment]
No problem @kroitor, thanks in advance for your help.

**Comment by kroitor** [comment]
@coinaisseur ok, that was a minor leftover, tested it on my side and it should work for you as of version 1.20.2. Let me know if anything. Thx again.

**Comment by coinaisseur** [comment]
Hi @kroitor 

Just tested ccxt's new version, and I can't make the closeOrder function work yet. Here's my verbose response:

```
fetch:
 upbit DELETE https://sg-api.upbit.com/v1/order?uuid=333b5521-dbc6-4e99-a2c7-ced299fdc763
Request:
 {
  Authorization: 'Bearer <authorization_token>',
  'Content-Type': 'application/json'
}
 {"uuid":"333b5521-dbc6-4e99-a2c7-ced299fdc763"}

handleRestResponse:
 upbit DELETE https://sg-api.upbit.com/v1/order?uuid=333b5521-dbc6-4e99-a2c7-ced299fdc763 401 Unauthorized
Response:
 {
  'Access-Control-Allow-Headers': 'Authorization, Content-Type, Accept, *',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache',
  Connection: 'close',
  'Content-Encoding': 'gzip',
  'Content-Language': 'en',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Wed, 27 Nov 2019 20:01:20 GMT',
  'Remaining-Req': 'group=default; min=899; sec=29',
  Server: 'Finatra',
  'Transfer-Encoding': 'chunked',
  Vary: 'Origin',
  Via: 'kong/1.3.0',
  'X-Kong-Proxy-Latency': '1',
  'X-Kong-Upstream-Latency': '16',
  'X-Request-Id': '46bb455b-4f57-4e1f-86cd-cd6c08ba9a57',
  'X-Runtime': '0.009915'
}
 {"error":{"name":"V1::Exceptions::InvalidQueryPayload","message":"Failed to verify the query of Jwt.","dialog":"client"}}
```

Thanks again for your help.

**Comment by kroitor** [comment]
@coinaisseur that's weird, but I've added another fix that should finally nail it... Terribly sorry for the confusion. Let me know if you still have difficulties with it, plz.

**Comment by coinaisseur** [comment]
Hi @kroitor 

I've tried again to cancel order after updating ccxt, still to no avail. Here's the verbose:

```
fetch:
 upbit DELETE https://sg-api.upbit.com/v1/order?uuid=333b5521-dbc6-4e99-a2c7-ced299fdc763
Request:
 {
  Authorization: 'Bearer <authorization_token>',
  'Content-Type': 'application/json'
}
 {"uuid":"333b5521-dbc6-4e99-a2c7-ced299fdc763"}

handleRestResponse:
 upbit DELETE https://sg-api.upbit.com/v1/order?uuid=333b5521-dbc6-4e99-a2c7-ced299fdc763 401 Unauthorized
Response:
 {
  'Access-Control-Allow-Headers': 'Authorization, Content-Type, Accept, *',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache',
  Connection: 'close',
  'Content-Encoding': 'gzip',
  'Content-Language': 'en',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Wed, 27 Nov 2019 22:26:15 GMT',
  'Remaining-Req': 'group=default; min=899; sec=29',
  Server: 'Finatra',
  'Transfer-Encoding': 'chunked',
  Vary: 'Origin',
  Via: 'kong/1.3.0',
  'X-Kong-Proxy-Latency': '4',
  'X-Kong-Upstream-Latency': '23',
  'X-Request-Id': 'd073886c-7b51-4c8a-88d7-fd3c446aabf7',
  'X-Runtime': '0.010736'
}
 {"error":{"name":"V1::Exceptions::InvalidQueryPayload","message":"Failed to verify the query of Jwt.","dialog":"client"}}

ExchangeError: upbit {"error":{"name":"V1::Exceptions::InvalidQueryPayload","message":"Failed to verify the query of Jwt.","dialog":"client"}}
    at upbit.handleErrors (C:\Users\Administrator\Documents\Node.js\TEST\node_modules\ccxt\js\upbit.js:1522:19)
    at C:\Users\Administrator\Documents\Node.js\TEST\node_modules\ccxt\js\base\Exchange.js:635:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timeout (C:\Users\Administrator\Documents\Node.js\TEST\node_modules\ccxt\js\base\functions\time.js:176:24)
    at async upbit.cancelOrder (C:\Users\Administrator\Documents\Node.js\TEST\node_modules\ccxt\js\upbit.js:902:26)
    at async C:\Users\Administrator\Documents\Node.js\TEST\test.js.js:15:28
    at async main (C:\Users\Administrator\Documents\Node.js\TEST\test.js.js:13:5) {
  constructor: [Function: ExchangeError],
  name: 'ExchangeError'
}
```
For some reason, there's a problem with the JSON construct ccxt is sending to the exchange. In the case of fetchOpenOrders, I managed to make it work by changing hostname to ccxsg.upbit.com/api. This didn't work with cancelOrder though.

I also tested this script on a fresh new Windows server install with latest node.js version (12.13.1) and with latest libraries installed, but it didn't work.

Thanks for your help.

**Comment by kroitor** [comment]
@coinaisseur 

> I managed to make it work by changing hostname to ccxsg.upbit.com/api

It's not very clear why you would change it to that particular URL which isn't really mentioned anywhere...

Does this snippet from Upbit's website work for you (need to edit the string literals in it before running it):

```JavaScript
const request = require('request')
const uuidv4 = require("uuid/v4")
const crypto = require('crypto')
const sign = require('jsonwebtoken').sign
const queryEncode = require("querystring").encode

const access_key = process.env.UPBIT_OPEN_API_ACCESS_KEY
const secret_key = process.env.UPBIT_OPEN_API_SECRET_KEY
const server_url = process.env.UPBIT_OPEN_API_SERVER_URL // https://sg-api.upbit.com

const body = {
    uuid: 'cdd92199-2897-4e14-9448-f923320408ad'
}

const query = queryEncode(body)

const hash = crypto.createHash('sha512')
const queryHash = hash.update(query, 'utf-8').digest('hex')

const payload = {
    access_key: access_key,
    nonce: uuidv4(),
    query_hash: queryHash,
    query_hash_alg: 'SHA512',
}

const token = sign(payload, secret_key)

const options = {
    method: "DELETE",
    url: server_url + "/v1/order?" + query,
    headers: {Authorization: `Bearer ${token}`},
    json: body
}

request(options, (error, response, body) => {
    if (error) throw new Error(error)
    console.log(body)
})
```

?

**Comment by coinaisseur** [comment]
Hi @kroitor 

Yes, this code actually works for me.

**Comment by kroitor** [comment]
@coinaisseur can you plz try again with CCXT 1.20.4 now? (make sure to update your version)

**Comment by kroitor** [comment]
@coinaisseur 

```JavaScript
"use strict";
const ccxt = require('ccxt')

const exchange = new ccxt.upbit({
    apiKey: '<api_key>',
    secret: '<secret>',
    hostname: 'sg-api.upbit.com',
    enableRateLimit: true, // ←----------- required
})

;(async function main() {

    await exchange.loadMarkets()
    exchange.verbose = true
    const response = await exchange.cancelOrder('333b5521-dbc6-4e99-a2c7-ced299fdc763')
    console.log (response)
}) ()
```

**Comment by coinaisseur** [comment]
Hi @kroitor 

I managed to solve my problem by changin a little bit the sign function in the upbit library. Instead of sending query in plain text, I changed the code to send its hashed form instead:

```
if (Object.keys(query).length) {
  const hash = crypto.createHash('sha512')
  const queryHash = hash.update(this.urlencode(query), 'utf-8').digest('hex')
  request['query_hash'] = queryHash
}
```

This is not the most elegant solution, but it works for me for the time being.

Thanks for your help.

**Comment by kroitor** [comment]
@coinaisseur i've added the necessary edits to the sign() implementation in CCXT, it would be great if you could try version 1.20.7 without your customization and report back whether it works for you as is or not. Thank you again!

**Comment by coinaisseur** [comment]
Hi @kroitor 

Thanks for the latest update. Now the fetchOpenOrders and cancelOrder functions work as expected.

Thanks again for all your help and time spent fixing this issue.

**Comment by kroitor** [comment]
@coinaisseur thx for your help debugging it, appreciate your involvement!
