### ISSUE TITLE
coinmarketcap publicGetTicker returns error

### ISSUE THREAD

**Issue by vladcostea** [ccxt/ccxt#6203]
`fetchCurrencies` fails for coinmarketcap with certificate error

- OS:
MacOS Mojave, 10.14.1 (also tested on ubuntu 18.04)

- Programming Language version:
node v10.x

- CCXT version:
1.20.7

- Exchange:
coinmarketcap

- Method:
publicGetTicker

Whenever I try to call any fetch methods on the coinmarketcap exchange I get the following error:
```
fetch:
 coinmarketcap GET https://api.coinmarketcap.com/v1/ticker/?limit=0
Request:
 {}
 undefined

{ ExchangeNotAvailable: coinmarketcap GET https://api.coinmarketcap.com/v1/ticker/?limit=0 system request to https://api.coinmarketcap.com/v1/ticker/?limit=0 failed, reason: unable to verify the first certificate
    at fetchImplementation.catch (/usr/local/lib/node_modules/ccxt/js/base/Exchange.js:410:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  constructor: [Function: ExchangeNotAvailable],
  name: 'ExchangeNotAvailable' }
```

this is the test code I use:

```js
const ccxt = require('ccxt');

(async function cmc() {
	try {
  		let ex = new ccxt['coinmarketcap']();
  		ex.verbose = true;
  		await ex.fetchCurrencies();
	} catch (err) {
		console.log(err);
	}
})();
```

The issue started happening as of 2019-11-27, maybe the api response changed?

Normal get requests seem to work:
```
curl -v https://api.coinmarketcap.com/v1/ticker/?limit=0
```

**Comment by kroitor** [comment]
It does not respond to me either...

```
mbp:ccxt igorkroitor$ node examples/js/cli coinmarketcap currencies --table
[RequestTimeout] coinmarketcap GET https://api.coinmarketcap.com/v1/ticker/?limit=0 request timed out (30000 ms)

    at                  js/base/Exchange.js:414  throw new RequestTimeout (this.id + ' ' + method + ' ' + url + ' request timed …
    at request          js/coinmarketcap.js:316  const response = await this.fetch2 (path, api, method, params, headers, body);
    at fetchCurrencies  js/coinmarketcap.js:264  const response = await this.publicGetTicker (this.extend (request, params));
    at loadMarkets      js/base/Exchange.js:692  currencies = await this.fetchCurrencies ()
    at async main       examples/js/cli.js:243   await exchange.loadMarkets ()

coinmarketcap GET https://api.coinmarketcap.com/v1/ticker/?limit=0 request timed out (30000 ms)
```

- https://api.coinmarketcap.com/v1/ticker/?limit=0

```
coinmarketcap GET https://api.coinmarketcap.com/v1/ticker/?limit=0 request timed out (30000 ms)
mbp:ccxt igorkroitor$ curl -v https://api.coinmarketcap.com/v1/ticker/?limit=0
*   Trying 159.203.105.104...
* TCP_NODELAY set
* Connected to api.coinmarketcap.com (159.203.105.104) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.coinmarketcap.com:443
* stopped the pause stream!
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.coinmarketcap.com:443
mbp:ccxt igorkroitor$
```

Looks like they have switched their free v1 off as promised here: 

- https://github.com/ccxt/ccxt/issues/3899
- https://pro.coinmarketcap.com/migrate

I suggest that we wait for it to self-resolve and if it doesn't we will see if we can fix it quickly with some workaround. This may also be a traffic surge: https://twitter.com/CoinMarketCap/status/1197760960875900928

Let me know if the above does not answer the question.

**Comment by vladcostea** [comment]
Thanks for the quick reply

Your answers do indeed answer my question, thank you.

What's weird is that I get a 200 response with curl

```
curl -v https://api.coinmarketcap.com/v1/ticker/\?limit\=0 > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 159.203.105.104...
* TCP_NODELAY set
* Connected to api.coinmarketcap.com (159.203.105.104) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [227 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [98 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1655 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=EssentialSSL Wildcard; CN=*.coinmarketcap.com
*  start date: Dec 18 00:00:00 2018 GMT
*  expire date: Dec 28 23:59:59 2019 GMT
*  subjectAltName: host "api.coinmarketcap.com" matched cert's "*.coinmarketcap.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f9ea2006600)
> GET /v1/ticker/?limit=0 HTTP/2
> Host: api.coinmarketcap.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0< HTTP/2 200
< server: nginx/1.10.3 (Ubuntu)
< date: Thu, 28 Nov 2019 18:43:13 GMT
< content-type: application/json
< content-length: 54828
< access-control-allow-origin: *
<
{ [8086 bytes data]
100 54828  100 54828    0     0   4975      0  0:00:11  0:00:11 --:--:-- 15510
* Connection #0 to host api.coinmarketcap.com left intact
```

If i don't `> /dev/null` i even get data :)

Not sure why you get an error. Maybe they haven't switched it off in my region?

**Comment by kroitor** [comment]
Followup here: https://github.com/ccxt/ccxt/issues/6580
