### ISSUE TITLE
Bibox raising JSON decode errors.

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#6212]
- OS: Linux
- Programming Language version: Python3
- CCXT version: Latest
- Exchange: ccxt.bibox()
- Method: ```fetchDepositAddress```
```
Request: POST https://api.bibox.com/v1/transfer {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} {"cmds":"[{\"cmd\":\"transfer/transferIn\",\"body\":{\"coin_symbol\":\"BTC\"}}]","apikey":"PERSONALLY OMITTED","sign":"PERSONALLY OMITTED"}

Response: POST https://api.bibox.com/v1/transfer 200 {'Server': 'Tengine', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '88', 'Access-Control-Allow-Origin': 'undefined', 'Access-Control-Allow-Methods': 'POST, GET, OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type, Accept, x-access-token, X-Requested-With', 'Access-Control-Max-Age': '172800', 'X-Ca-Request-Id': '7510CAA9-FAD0-493C-ABD8-B137CE4315FF', 'X-Powered-By': 'Express', 'Access-Control-Allow-Credentials': 'true', 'ETag': 'W/"58-hrfCYwBSTuz9Ds6Ugf0zHH7GGek"', 'Date': 'Sun, 01 Dec 2019 23:51:00 GMT', 'Connection': 'keep-alive'} {"result":[{"result":"14a9B1LtdG3S7kAu852joejSMKE2eRQnx4","cmd":"transfer/transferIn"}]}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/bibox.py", line 774, in fetch_deposit_address
    result = json.loads(self.safe_string(response, 'result'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
```
BTC raises this error. However, another currency such as EOSDAC, does not.

Thanks for viewing.

**Comment by kroitor** [comment]
@karlandoh tbh this one is quite hard to debug, unless you help us determine which particular data in that JSON is _"extra"_... Can you dump the length and the contents of `exchange.last_http_response` upon catching an exception and paste it here, plz?
