### ISSUE TITLE
cex.py cancel_order(id) raises NullResponse

### ISSUE THREAD

**Issue by 7iW** [ccxt/ccxt#6226]
- OS: MacOS
- Programming Language version: CPython 3.8.0
- CCXT version: 1.20.35
- Exchange: CEX.IO
- Method: cex.cancel_order(id)

When calling the `cancel_order` method of the `cex` exchange, the order is successfully cancelled on the exchange, but ccxt raises a `NullResponse` error.

```
Request: POST https://cex.io/api/cancel_order/ {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} {"key":"CENSORED","signature":"CENSORED","nonce":"1575571819217","id":"11044048941"}

Response: POST https://cex.io/api/cancel_order/ 200 <CIMultiDictProxy('Date': 'Thu, 05 Dec 2019 18:50:19 GMT', 'Content-Type': 'text/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Security-Policy-Report-Only': "default-src 'self';connect-src 'self' https://maps.googleapis.com https://cex.io wss://ws.cex.io/ws;frame-src 'self' * ext.cex.io;font-src 'self' data: 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com https://static.cex.io;img-src 'self' data: https://static.cex.io;style-src 'self' 'unsafe-inline' https://*.googleapis.com https://code.jquery.com https://static.cex.io;script-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.cex.io;report-uri https://cex.io/cspr;", 'X-Frame-Options': 'DENY', 'Vary': 'Accept-Encoding', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5408347e2867e20e-ORD')> true
2019-12-05 12:50:19,362 - orchestrate.py:177 Exception caught while cancelling orders!
Traceback (most recent call last):
  File "/Users/7iW/arb/src/private_ccxt/orchestrate.py", line 173, in handle_placed_orders
    cancelled_orders = await asyncio.gather(
  File "/Users/7iW/.pyenv/versions/arb/lib/python3.8/site-packages/ccxt/async_support/cex.py", line 558, in cancel_order
    return await self.privatePostCancelOrder(self.extend(request, params))
  File "/Users/7iW/.pyenv/versions/arb/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 116, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/7iW/.pyenv/versions/arb/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 169, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/7iW/.pyenv/versions/arb/lib/python3.8/site-packages/ccxt/async_support/cex.py", line 1100, in handle_errors
    raise NullResponse(self.id + ' returned ' + self.json(response))
ccxt.base.errors.NullResponse: cex returned null
```

**Comment by 7iW** [comment]
Thanks your help, @kroitor. Ccxt is an impressive product.

**Comment by kroitor** [comment]
@7iW thx for the feedback, really appreciate it! Let us know if you find anything else.
