### ISSUE TITLE
Bitz using offline API V2 domain + Personally fixed by me!

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#6274]
- OS: Linux
- Programming Language version: Python3
- CCXT version: Latest
- Exchange: ccxt.bitz()
- Method: ```load_markets```

Issue is as shown.
```
bitz.load_markets()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f2e30e73a20>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='apiv2.bit-z.pro', port=443): Max retries exceeded with url: /Market/symbolList (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2e30e73a20>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 531, in fetch
    verify=self.verify
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='apiv2.bit-z.pro', port=443): Max retries exceeded with url: /Market/symbolList (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2e30e73a20>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1258, in load_markets
    markets = self.fetch_markets(params)
  File "/usr/local/lib/python3.7/site-packages/ccxt/bitz.py", line 220, in fetch_markets
    response = self.marketGetSymbolList(params)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 435, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 458, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 454, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 569, in fetch
    raise ExchangeError(method + ' ' + url)
ccxt.base.errors.ExchangeError: GET https://apiv2.bit-z.pro/Market/symbolList
```
 I have successfully fixed it, and would love some guidance on how to 'commit' the code to the bitz.py .

Thanks for viewing.

**Comment by karlandoh** [comment]
I've updated my ccxt, and it turns out that it has been fixed already. False alarm

**Comment by kroitor** [comment]
@karlandoh yep, just today: https://github.com/ccxt/ccxt/issues/6271 but thanks anyways )
