### ISSUE TITLE
fetchMyTrades not working in Kraken

### ISSUE THREAD

**Issue by aking7** [ccxt/ccxt#628]
This was working fine before but has stopped after pulling some new commits.
```
Traceback (most recent call last):

  File "<ipython-input-45-1e4138f4f4ab>", line 1, in <module>
    runfile('C:/Users/kinga/Documents/GitHub/DangerCrypt/test_king.py', wdir='C:/Users/kinga/Documents/GitHub/DangerCrypt')

  File "C:\Users\kinga\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\kinga\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/kinga/Documents/GitHub/DangerCrypt/test_king.py", line 27, in <module>
    trades = exchange.fetchMyTrades()

  File "c:\users\kinga\documents\github\dangercrypt\ccxt\python\ccxt\kraken.py", line 489, in fetch_my_trades
    return self.parse_trades(trades)

  File "c:\users\kinga\documents\github\dangercrypt\ccxt\python\ccxt\base\exchange.py", line 827, in parse_trades
    return [self.parse_trade(trade, market) for trade in array]

  File "c:\users\kinga\documents\github\dangercrypt\ccxt\python\ccxt\base\exchange.py", line 827, in <listcomp>
    return [self.parse_trade(trade, market) for trade in array]

  File "c:\users\kinga\documents\github\dangercrypt\ccxt\python\ccxt\kraken.py", line 322, in parse_trade
    'currency': market['quote'],

TypeError: 'NoneType' object is not subscriptable
```

**Comment by aking7** [comment]
v1.10.157 seems to be the broken release

**Comment by kroitor** [comment]
This is now fixed in current version, don't forget to update and thanks for reporting!
