### ISSUE TITLE
Parameter 'quoteOrderQty' sent when not  required.

### ISSUE THREAD

**Issue by fibo** [ccxt/ccxt#6396]
# Parameter 'quoteOrderQty' sent when not  required.

- OS: Linux
- Programming Language version: node v10.18.0
- CCXT version: 1.21.77
- Exchange: Binance
- Method: `createOrder(currencyPair, 'market', 'buy', baseAmount, last)`

It was working few hours ago, then suddenly it started to raise this error:

```
{"code":-1106,"msg":"Parameter 'quoteOrderQty' sent when not required."}
    at binance.handleErrors (/usr/lib/node_modules/gg-bot/node_modules/ccxt/js/binance.js:1805:27)
    at response.text.then (/usr/lib/node_modules/gg-bot/node_modules/ccxt/js/base/Exchange.js:627:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  constructor: [Function: ExchangeError],
  name: 'ExchangeError' }
```

Can you help please?

could it be related to currency? For instance it is:

- symbol=QTUM/USDT
- amount=5.717
- price=1.924

where I use 

```js
const baseAmount = decimalToPrecision(quoteAmount / last, ROUND, precision.amount, DECIMAL_PLACES)
```

same happened with

- symbol=ETC/USDT
- amount=0.07181
- price=167.1

it is really strange cause I got no error few hours ago.

Thansk in advance

**Comment by kroitor** [comment]
See this issue for an explanation:

- https://github.com/ccxt/ccxt/issues/6391

It was updated a few hours ago. In general you should not specify a price for a market order, unless you want to send quoteOrderQty. Can you post your verbose request/response for this call?

```JavaScript
await exchange.loadMarkets ()
exchange.verbose = true
exchange.createOrder (...
```

**Comment by kroitor** [comment]
@fibo actually, nevermind, i think i found the bug that is causing it and it was introduced today. I've uploaded a fixup for it and it should work fine as of version 1.21.78 (it will arrive in 15 minutes). Pardon for the inconvenience and thx for reporting it! Let us know if you still have any difficulties after upgrading. We will be happy if you report back whether it did resolve the issue for you or not. If you don't want to send `quoteOrderQty` – make sure to omit the price.

**Comment by fibo** [comment]
@kroitor many thanks, I am more then happy using your product. I am building a multi strategy multi exchange trading website and as soon as I am stable and profitable I will sponsor you. By now let me contribute with informations

I am running this code I wrote just now to test

```js
const ccxt = require('ccxt')

async function testCreateOrder () {
  const exchangeId = 'binance'
  const currencyPair = 'BTC/USDT'
  const quoteAmount = 11


  const ExchangeClass = ccxt[exchangeId]

  const binance = new ExchangeClass({
    apiKey: process.env.BINANCE_APIKEY,
    secret: process.env.BINANCE_APISECRET,
    timeout: 30000,
    enableRateLimit: true,
    options: {
      adjustForTimeDifference: true,
      createMarketBuyOrderRequiresPrice: false
    }
  })

  binance.verbose = true

  await binance.loadMarkets()

  const { decimalToPrecision, ROUND, DECIMAL_PLACES } = binance
  const { precision } = binance.markets[currencyPair]

  const ticker = await binance.fetchTicker(currencyPair)
  const { last, percentage } = ticker

  const baseAmount = decimalToPrecision(quoteAmount / last, ROUND, precision.amount, DECIMAL_PLACES)

  const buyTransaction = await binance.createOrder(currencyPair, 'market', 'buy', baseAmount, last)
}

testCreateOrder()
```

and I got this output

```
fetch:
 binance GET https://api.binance.com/api/v3/exchangeInfo 
Request:
 {} 
 undefined 

handleRestResponse:
 binance GET https://api.binance.com/api/v3/exchangeInfo 200 OK 
Response:
 {
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=utf-8',
  Date: 'Mon, 20 Jan 2020 21:52:01 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  'Transfer-Encoding': 'chunked',
  Via: '1.1 5427b6f9e99013a38c36e041a855ef66.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'QS0TFXqCneOP9b1gNQ2mDD0ddJm66FGvyc-1HhEcDr-0Ot8aU3ZHOA==',
  'X-Amz-Cf-Pop': 'MXP64-C3',
  'X-Cache': 'Miss from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Mbx-Used-Weight': '1',
  'X-Mbx-Used-Weight-1m': '1',
  'X-Mbx-Uuid': 'b79511bd-780b-45c1-a98e-92175033c338',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
} 

.... LOT OF STUFF ....


fetch:
 binance GET https://api.binance.com/api/v3/time 
Request:
 {} 
 undefined 

handleRestResponse:
 binance GET https://api.binance.com/api/v3/time 200 OK 
Response:
 {
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=utf-8',
  Date: 'Mon, 20 Jan 2020 21:52:02 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  Via: '1.1 5427b6f9e99013a38c36e041a855ef66.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'RnCnlM9OGS_d1HdOftvZBM0m-hChFqQmBze683CZPBa9J2CRW0CZAg==',
  'X-Amz-Cf-Pop': 'MXP64-C3',
  'X-Cache': 'Miss from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Mbx-Used-Weight': '2',
  'X-Mbx-Used-Weight-1m': '2',
  'X-Mbx-Uuid': '356257b0-4708-4c74-9a40-2ee21aff4960',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
} 
 {"serverTime":1579557122253} 

fetch:
 binance GET https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT 
Request:
 {} 
 undefined 

handleRestResponse:
 binance GET https://api.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT 200 OK 
Response:
 {
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=utf-8',
  Date: 'Mon, 20 Jan 2020 21:52:02 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  'Transfer-Encoding': 'chunked',
  Via: '1.1 5427b6f9e99013a38c36e041a855ef66.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'tvbvZB_C0fH3GLL_mnyVIwD0da8ynIGSgiC4KoSeDqKgAMJX7-anNg==',
  'X-Amz-Cf-Pop': 'MXP64-C3',
  'X-Cache': 'Miss from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Mbx-Used-Weight': '3',
  'X-Mbx-Used-Weight-1m': '3',
  'X-Mbx-Uuid': '8dedb323-dae9-4b80-8123-a9a10d8efe4c',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
} 
 {"symbol":"BTCUSDT","priceChange":"-44.19000000","priceChangePercent":"-0.507","weightedAvgPrice":"8642.97873946","prevClosePrice":"8716.24000000","lastPrice":"8672.15000000","lastQty":"0.12150400","bidPrice":"8672.14000000","bidQty":"0.00000300","askPrice":"8672.18000000","askQty":"0.28827900","openPrice":"8716.34000000","highPrice":"8752.00000000","lowPrice":"8466.00000000","volume":"42617.50087200","quoteVolume":"368342153.96579121","openTime":1579470722729,"closeTime":1579557122729,"firstId":232160692,"lastId":232568637,"count":407946} 

fetch:
 binance POST https://api.binance.com/api/v3/order 
Request:
 {
  'X-MBX-APIKEY': 'vv****************wez2fLi****************f18r5vDtRBM************kjxAC1VTkx7tVzVT************dN4xF********',
  'Content-Type': 'application/x-www-form-urlencoded'
} 
 timestamp=1579557122959&recvWindow=5000&symbol=BTCUSDT&quantity=0.001268&type=MARKET&side=BUY&quoteOrderQty=11&newOrderRespType=FULL&signature=8067400ec19689331eb3fdcc2051a8cc27f70fb97abfa8100d558db316c90d15 

handleRestResponse:
 binance POST https://api.binance.com/api/v3/order 400 Bad Request 
Response:
 {
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=utf-8',
  Date: 'Mon, 20 Jan 2020 21:52:03 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  'Transfer-Encoding': 'chunked',
  Via: '1.1 5427b6f9e99013a38c36e041a855ef66.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': '-Y8e5UhF-gORT7QIwH_iizP3249R9NSVd8TtKyduZPi8tF3q16hyYw==',
  'X-Amz-Cf-Pop': 'MXP64-C3',
  'X-Cache': 'Error from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Mbx-Used-Weight': '4',
  'X-Mbx-Used-Weight-1m': '4',
  'X-Mbx-Uuid': '27e823a7-c09d-4a46-ac71-20cc19e5b296',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
} 
 {"code":-1106,"msg":"Parameter 'quoteOrderQty' sent when not required."} 


```

**Comment by fibo** [comment]
On the other hand, if I remove `last` as you suggested it seems to work

```diff
- const baseAmount = decimalToPrecision(quoteAmount / last, ROUND, precision.amount, DECIMAL_PLACES, last)
+ const baseAmount = decimalToPrecision(quoteAmount / last, ROUND, precision.amount, DECIMAL_PLACES)
```

<img width="677" alt="Screenshot 2020-01-20 at 22 59 43" src="https://user-images.githubusercontent.com/176730/72760339-b9899e00-3bd8-11ea-8b31-61cc87b312a1.png">

**Comment by kroitor** [comment]
@fibo yep, apparently, that was a bug, see my comment above ) https://github.com/ccxt/ccxt/issues/6396#issuecomment-576439554

But the bug is fixed now, please, update to 1.21.78. It should work fine from there. Let me know if not.

On a sidenote, market orders work with Binance in the following way:

- if you do not submit a `price` and specify just the `amount` only – it will try to sell/buy that amount – will send the `quantity`
- if you also specify a `price` – it will try to spend the total `cost` (where the cost is equal to price * amount) buying or sell up to that `cost` (will send `quoteOrderQty`).

Feel free to ask questions, if you have more.

**Comment by kroitor** [comment]
@fibo also, for the future, if you switch these two lines there will be a lot less garbage on the screen and you will see just the useful stuff:

```JavaScript
  binance.verbose = true
  await binance.loadMarkets() // it prints a lot of output in verbose mode
```

↓

```JavaScript
  await binance.loadMarkets() // do not print excessive output – enable verbose after
  binance.verbose = true
```

**Comment by fibo** [comment]
Thank you very much, now I am using this snippet

```js
const baseAmount = decimalToPrecision(quoteAmount / last, ROUND, precision.amount, DECIMAL_PLACES)
```
and I confirm that with latest `v1.21.78` is working as expected.

(eheheh I have a lot of crypto bots waiting for it :^)

**Comment by kroitor** [comment]
> and I confirm that with latest v1.21.78 is working as expected.

Thanks a lot for the feedback, appreciate it very much!

> (eheheh I have a lot of crypto bots waiting for it :^)

)) Make sure you fully understand the precautions on market orders and the difference between spending an amount and spending the cost from here:

https://github.com/ccxt/ccxt/issues/6396#issuecomment-576443066

**Comment by kroitor** [comment]
@fibo in your case you could simplify it like so:

```JavaScript
  await binance.loadMarkets()
  const quoteAmount = 11
  const params = {
     quoteOrderQty: binance.cost_to_precision (currencyPair, quoteAmount),
  }
  const buyTransaction = await binance.createOrder(currencyPair, 'market', 'buy', undefined, undefined, params)
```

↑ This is a much more efficient way of doing the same thing you do, since it does not involve a call to fetchTicker – it does spend your quoteAmount straight away and you don't have to recalculate it into the baseAmount with the current price – all of that is done on the exchange side.
