### ISSUE TITLE
Exception "Cannot read property 'inactiveCurrencies' of undefined" while fetching historic trades from Kraken 

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [ccxt/ccxt#6425]
While trying to fetch historical trades from Kraken, in the same way that works for other exchanges, I get this exception.

**Cannot read property 'inactiveCurrencies' of undefined**

- OS: Windows 10 Home
- Programming Language version: λ javascript node -v v8.11.4
- CCXT version: "ccxt": "^1.21.82"
- Exchange: Kraken
- Method: fetchTrades()

```
fetch:
 kraken GET https://api.kraken.com/0/public/Assets
Request:
 {}
 undefined

handleRestResponse:
 kraken GET https://api.kraken.com/0/public/Assets 200 OK
Response:
 { 'Cache-Control': 'public,max-age=60,smaxage=60',
  'Cf-Cache-Status': 'EXPIRED',
  'Cf-Ray': '55c3f5c3ff72d413-BUD',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Tue, 28 Jan 2020 15:22:07 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=df33865410cff2f7f1cf3f9aaa74d29ca1580224927; expires=Thu, 27-Feb-20 15:22:07 GMT; path=/; domain=.kraken.com; HttpOnly; SameSite=Lax',
  'Strict-Transport-Security': 'max-age=15768000',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding' }
 {"error":[],"result":{"ADA":{"aclass":"currency","altname":"ADA","decimals":8,"display_decimals":6},"ALGO":{"aclass":"currency","altname":"ALGO","decimals":8,"display_decimals":5},"ATOM":{"aclass":"currency","altname":"ATOM","decimals":8,"display_decimals":6},"BAT":{"aclass":"currency","altname":"BAT","decimals":10,"display_decimals":5},"BCH":{"aclass":"currency","altname":"BCH","decimals":10,"display_decimals":5},"BSV":{"aclass":"currency","altname":"BSV","decimals":10,"display_decimals":5},"CHF":{"aclass":"currency","altname":"CHF","decimals":4,"display_decimals":2},"DAI":{"aclass":"currency","altname":"DAI","decimals":10,"display_decimals":5},"DASH":{"aclass":"currency","altname":"DASH","decimals":10,"display_decimals":5},"EOS":{"aclass":"currency","altname":"EOS","decimals":10,"display_decimals":5},"GNO":{"aclass":"currency","altname":"GNO","decimals":10,"display_decimals":5},"ICX":{"aclass":"currency","altname":"ICX","decimals":10,"display_decimals":5},"KFEE":{"aclass":"currency","altname":"FEE","decimals":2,"display_decimals":2},"LINK":{"aclass":"currency","altname":"LINK","decimals":10,"display_decimals":5},"LSK":{"aclass":"currency","altname":"LSK","decimals":10,"display_decimals":5},"NANO":{"aclass":"currency","altname":"NANO","decimals":10,"display_decimals":5},"OMG":{"aclass":"currency","altname":"OMG","decimals":10,"display_decimals":5},"PAXG":{"aclass":"currency","altname":"PAXG","decimals":10,"display_decimals":5},"QTUM":{"aclass":"currency","altname":"QTUM","decimals":10,"display_decimals":6},"SC":{"aclass":"currency","altname":"SC","decimals":10,"display_decimals":5},"USDC":{"aclass":"currency","altname":"USDC","decimals":8,"display_decimals":4},"USDT":{"aclass":"currency","altname":"USDT","decimals":8,"display_decimals":4},"WAVES":{"aclass":"currency","altname":"WAVES","decimals":10,"display_decimals":5},"XETC":{"aclass":"currency","altname":"ETC","decimals":10,"display_decimals":5},"XETH":{"aclass":"currency","altname":"ETH","decimals":10,"display_decimals":5},"XLTC":{"aclass":"currency","altname":"LTC","decimals":10,"display_decimals":5},"XMLN":{"aclass":"currency","altname":"MLN","decimals":10,"display_decimals":5},"XREP":{"aclass":"currency","altname":"REP","decimals":10,"display_decimals":5},"XTZ":{"aclass":"currency","altname":"XTZ","decimals":8,"display_decimals":6},"XTZ.S":{"aclass":"currency","altname":"XTZ.S","decimals":8,"display_decimals":6},"XXBT":{"aclass":"currency","altname":"XBT","decimals":10,"display_decimals":5},"XXDG":{"aclass":"currency","altname":"XDG","decimals":8,"display_decimals":2},"XXLM":{"aclass":"currency","altname":"XLM","decimals":8,"display_decimals":5},"XXMR":{"aclass":"currency","altname":"XMR","decimals":10,"display_decimals":5},"XXRP":{"aclass":"currency","altname":"XRP","decimals":8,"display_decimals":5},"XZEC":{"aclass":"currency","altname":"ZEC","decimals":10,"display_decimals":5},"ZCAD":{"aclass":"currency","altname":"CAD","decimals":4,"display_decimals":2},"ZEUR":{"aclass":"currency","altname":"EUR","decimals":4,"display_decimals":2},"ZGBP":{"aclass":"currency","altname":"GBP","decimals":4,"display_decimals":2},"ZJPY":{"aclass":"currency","altname":"JPY","decimals":2,"display_decimals":0},"ZUSD":{"aclass":"currency","altname":"USD","decimals":4,"display_decimals":2}}}

*********** ['2020-01-28T15:22:06.298Z',296,'User Bot','[ERROR] start -> getTrades -> err = TypeError: Cannot read property 'inactiveCurrencies' of undefined
    at kraken.fetchCurrencies (C:\Users\Luis\source\repos\AAMasters\TaskServer\node_modules\ccxt\js\kraken.js:381:61)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)'] @ AAMasters-AACharly-Historic-Trades
```

**Comment by kroitor** [comment]
@Luis-Fernando-Molina can you please paste your code to reproduce it?

**Comment by Luis-Fernando-Molina** [comment]
yes, here it is. There might be missing some variables declarations that are coming from elsewhere, but essentially is this:

``` 
            if (key === "undefined") { key = undefined }
            if (secret === "undefined") { secret = undefined }

            const limit = 1000
            const exchangeClass = ccxt[exchangeId]
            const exchangeConstructorParams = {
                'apiKey': key,
                'secret': secret,
                'timeout': 30000,
                'enableRateLimit': true,
                verbose: false,
                options: undefined
            }
 
            const exchange = new exchangeClass(exchangeConstructorParams)
            const trades = await exchange.fetchTrades(symbol, since, limit, undefined)

```

**Comment by kroitor** [comment]
@Luis-Fernando-Molina you should not set `options` to undefined.

```JavaScript
            const exchangeConstructorParams = {
                'apiKey': key,
                'secret': secret,
                'timeout': 30000,
                'enableRateLimit': true,
                verbose: false,
                options: undefined // ←-THIS IS ILLEGAL, REMOVE THIS OR REPLACE WITH {}
            }
```

Hope it helps, let us know if not.

**Comment by Luis-Fernando-Molina** [comment]
Indeed. That was the problem. Thanks!
