### ISSUE TITLE
Binance simple market order no longer works.

### ISSUE THREAD

**Issue by eckozen84** [ccxt/ccxt#6450]
Binance market orders used to work fine until I updated ccxt for the first time in a few months and now a simple market order no longer works. I suspect it has something to do with ```quoteOrderQty``` parameter. Ideally I want to place a market order using only the amount, I don't care about the cost. I want my order to get filled on the exact amount I specify (either market buy or sell).

```
  const ccxt = require('ccxt')
  const BNC = new ccxt.binance({
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  });

  try {
    var order = await BNC.createMarketSellOrder('BNB/BTC', 1)
  } catch (e) {
    console.log(e)
  }
```
I get the following error

```
{ ExchangeError: binance {"code":-1106,"msg":"Parameter 'quantity' sent when not required."}
    at binance.handleErrors (/home/ubuntu/Dropbox/CryptoArb/node_modules/ccxt/js/binance.js:1833:27)
    at response.text.then (/home/ubuntu/Dropbox/CryptoArb/node_modules/ccxt/js/base/Exchange.js:628:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  constructor: [Function: ExchangeError],
  name: 'ExchangeError' }
```

- OS: Ubuntu 18.04
- Programming Language version: Node JS v10.18.1
- CCXT version:  1.22.35
- Exchange:  Binance
- Method:

**Comment by eckozen84** [comment]
If I add in the order price (to allow the library to calculate the cost internally) I get the following error

```
  const ccxt = require('ccxt')
  const BNC = new ccxt.binance({
    apiKey: 'jufGHBmVGjSdBHMPgBVRTgRzXcge2z9GVYUozE4UZzCikfcRLgi9SvuQunJcKoZT',
    secret: 'ubDLaJ8NIB0gSocIL8WKRVbNqa68IYxzo5z1DTlLvZN5fOlT6FhrtJYmJpe7tatg',
  });


  try {
    var order = await BNC.createOrder('BNB/BTC', 'market', 'sell', 0.00000001, 0.00000001)
  } catch (e) {
    console.log(e)
  }
```

```
{ InvalidOrder: binance {"code":-1013,"msg":"Quote order qty market orders are not support for this symbol."}
    at binance.throwExactlyMatchedException (/home/ubuntu/Dropbox/CryptoArb/node_modules/ccxt/js/base/Exchange.js:533:19)
    at binance.handleErrors (/home/ubuntu/Dropbox/CryptoArb/node_modules/ccxt/js/binance.js:1832:26)
    at response.text.then (/home/ubuntu/Dropbox/CryptoArb/node_modules/ccxt/js/base/Exchange.js:628:18)
    at process._tickCallback (internal/process/next_tick.js:68:7) constructor: [Function: InvalidOrder], name: 'InvalidOrder' }
```

The forced implementation of ```quoteOrderQty``` is a mistake in my opinion, at least in the case of Binance which allows both types of market orders. In any case, Binance doesn't officially support it on most currency pairs anyway.

**Comment by eckozen84** [comment]
Apologies, looks like I was using an invalid quantity, appears to be working now.
