### ISSUE TITLE
Upbit create deposit address Error

### ISSUE THREAD

**Issue by doo393** [ccxt/ccxt#6452]
- OS:Windows 10 
- Programming Language version:Python
- CCXT version:1.22.35
- Exchange:Upbit
- Method:createDepositAddress

ccxt.base.errors.ExchangeError: upbit {"error": {"message": "Could not find cryptocurrency wallet information", "name": "coin_address_not_found"}}

I wonder what this error means

**Comment by kroitor** [comment]
Hi @doo393 ! Can you plz paste your verbose request/response for the above error?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kookOh** [comment]
ERROR : 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ccxt/base/exchange.py", line 539, in fetch
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: **https://api.upbit.com/v1/deposits/coin_address?currency=ETH**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "upbit_address.py", line 41, in <module>
    address = upbit.create_deposit_address('ETH')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ccxt/upbit.py", line 1324, in create_deposit_address
    response = self.fetch_deposit_address(code, self.extend(request, params))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ccxt/upbit.py", line 1306, in fetch_deposit_address
    response = self.privateGetDepositsCoinAddress(self.extend({
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ccxt/base/exchange.py", line 435, in inner
    return entry(_self, **inner_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ccxt/base/exchange.py", line 458, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ccxt/base/exchange.py", line 454, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ccxt/base/exchange.py", line 551, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ccxt/upbit.py", line 1444, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: upbit {"error":{"message":"\uc554\ud638\ud654\ud3d0 \uc9c0\uac11\uc815\ubcf4\ub97c \ucc3e\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4.","name":"coin_address_not_found"}}
geondeuljimasioui-iMac:nhbot a123$

.

ref. code  below.

**line #1325 in upbit.py** 
 response = self.fetch_deposit_address(code, self.extend(request, params))

and  **line #1304 in upbit.py**  

 def fetch_deposit_address(self, code, params={}):
        self.load_markets()
        currency = self.currency(code)
        response = self.privateGetDepositsCoinAddress(self.extend({
            'currency': currency['id'],
        }, params))
        #
        #     {
        #         "currency": "BTC",
        #         "deposit_address": "3EusRwybuZUhVDeHL7gh3HSLmbhLcy7NqD",
        #         "secondary_address": null
        #     }
        #
        return self.parse_deposit_address(response)


Hi !
I think that this error is caused by URLs.
for creating deposit address, it should be 'https://api.upbit.com/v1/deposits/generate_coin_address'
and method POST with body params such like
' query = {
    'currency': 'BTC',
}'


can you please check it ?

**Comment by kroitor** [comment]
Thanks for your report @kookOh !

I've uploaded a fix to it, so it should work as documented in the Manual now. If you call `createDepositAddress` it will send a request to a correct endpoint, and then, if the address is not ready – it will throw a standard `AddressPending` exception to indicate that you should attempt to retrieve the address with a second call to `createDepositAddress` or `fetchDepositAddress` a bit later. The fix will arrive in version 1.22.69 in 15 minutes. We will be happy if you report back, whether it does resolve the issue for you or not. Thx again!

**Comment by kookOh** [comment]
Hi. 
thanks for reacting right away!
but i got another error, here.

Traceback (most recent call last):
  File "upbit_address2.py", line 9, in <module>
    addresses2=upbit.create_deposit_address('ETH')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ccxt/upbit.py", line 1327, in create_deposit_address
    response = self.privatePostDepositsGenerateCoinAddress(code, self.extend(request, params))
TypeError: inner() takes from 1 to 2 positional arguments but 3 were given

I don't know how to deal with .
I think that it may be caused by parameter "code" in privatePostDepositsGenerateCoinAddress, cuz it doesn't need a query string, but only body params. It's not sure. 
or If it caused by my mistake , I really hope that you give me a solution to resolve the issue.

Thanks !

**Comment by kroitor** [comment]
@kookOh pardon for the inconvenience, that `code` a minor leftover from the previous version. I've uploaded another fix to it and tested on my side – should be ok now in 1.22.75 (will arrive in 15 minutes). Let us know if helps or not. Thank you for reporting!
