### ISSUE TITLE
idex {"error":"Invalid withdrawal signature. Please try again."}

### ISSUE THREAD

**Issue by mustapha1509** [ccxt/ccxt#6465]
Hello

- OS: macOS
- Programming Language version: PHP 7.3.9
- CCXT version: 1.21.22
- Exchange: IDEX
- Method: Private (POST)

```
ccxt\ExchangeError  : idex {"error":"Invalid withdrawal signature. Please try again."}

  at /var/www/vhosts/xxxxxxx/xxxxxxxx/vendor/ccxt/ccxt/php/idex.php:1079
    1075|         if (is_array($response) && array_key_exists('error', $response)) {
    1076|             if (is_array($this->exceptions) && array_key_exists($response['error'], $this->exceptions)) {
    1077|                 throw new $this->exceptions[$response['error']]($this->id . ' ' . $response['error']);
    1078|             }
  > 1079|             throw new ExchangeError($this->id . ' ' . $body);
    1080|         }
    1081|     }
    1082| }
    1083| 

  Exception trace:

  1   ccxt\idex::handle_errors()
      /var/www/vhosts/xxxxxxx/xxxxxxxxx/vendor/ccxt/ccxt/php/base/Exchange.php:1398

  2   ccxt\Exchange::fetch()
      /var/www/vhosts/xxxxxxx/xxxxxxxxx/vendor/ccxt/ccxt/php/base/Exchange.php:1175
```

**Comment by kroitor** [comment]
@mustapha1509 hi! Can you plz post your verbose request/response as described here? ↓

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by mustapha1509** [comment]
```
Request:
Array
(
    [0] => POST
    [1] => https://api.idex.market/withdraw
    [2] => Array
        (
            [0] => Content-Type: application/json
            [1] => Accept: application/json
            [2] => API-Key: api:Q4jG2ByIkEQbj8UQ3JqrL
            [3] => Origin: *
        )

    [3] => {"address":"myaddress","amount":2366700000000,"token":"0x0f02e27745e3b6e9e1310d19469e2b5d7b5ec99a","nonce":5,"r":"0x28eb1a99a8f1889120c190f99232695907af02b7b95e696b7762ec5ead33ad23","s":"0x62dc7766d9fcfa51527944b44ed37391e31b71cc31f8d5f954c1a31d793d608d","v":28}
)

Response:
Array
(
    [0] => POST
    [1] => https://api.idex.market/withdraw
    [2] => 400
    [3] => 
    [4] => Array
        (
            [connection] => Array
                (
                    [0] => keep-alive
                )

            [x-request-url] => Array
                (
                    [0] => https://api.idex.market/withdraw
                )

            [date] => Array
                (
                    [0] => Mon, 10 Feb 2020 23:06:41 GMT
                )

            [content-type] => Array
                (
                    [0] => application/json
                )

            [transfer-encoding] => Array
                (
                    [0] => chunked
                )

            [access-control-allow-origin] => Array
                (
                    [0] => *
                )

            [access-control-expose-headers] => Array
                (
                    [0] => date,content-type,transfer-encoding,connection,access-control-allow-origin,access-control-expose-headers,content-encoding,vary,cf-cache-status,expect-ct,strict-transport-security,x-content-type-options,server,cf-ray,x-final-url
                )

            [content-encoding] => Array
                (
                    [0] => gzip
                )

            [vary] => Array
                (
                    [0] => origin
                )

            [cf-cache-status] => Array
                (
                    [0] => DYNAMIC
                )

            [expect-ct] => Array
                (
                    [0] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
                )

            [strict-transport-security] => Array
                (
                    [0] => max-age=15552000; preload
                )

            [x-content-type-options] => Array
                (
                    [0] => nosniff
                )

            [server] => Array
                (
                    [0] => cloudflare
                )

            [cf-ray] => Array
                (
                    [0] => 5631bc2b0d71296d-DUB
                )

            [x-final-url] => Array
                (
                    [0] => https://api.idex.market/withdraw
                )

            [via] => Array
                (
                    [0] => 1.1 vegur
                )

        )

    [5] => {"error":"Invalid withdrawal signature. Please try again."}
)

   ccxt\ExchangeError  : idex {"error":"Invalid withdrawal signature. Please try again."}

  at /var/www/vhosts/xxxxxx/xxxxxxx/vendor/ccxt/ccxt/php/idex.php:1079
    1075|         if (is_array($response) && array_key_exists('error', $response)) {
    1076|             if (is_array($this->exceptions) && array_key_exists($response['error'], $this->exceptions)) {
    1077|                 throw new $this->exceptions[$response['error']]($this->id . ' ' . $response['error']);
    1078|             }
  > 1079|             throw new ExchangeError($this->id . ' ' . $body);
    1080|         }
    1081|     }
    1082| }
    1083| 

  Exception trace:
```

**Comment by mustapha1509** [comment]
Any idea

**Comment by kroitor** [comment]
@mustapha1509 not yet, but we are in the process of investigating it. Will report back with our findings. Thx for reporting!

**Comment by mustapha1509** [comment]
@kroitor thank you, but the php version have many bug also can't make a idex market order

**Comment by ndubel** [comment]
The same, but `Invalid cancel signature`

```
fetch:
 idex POST https://api.idex.market/returnNextNonce
Request:
 { 'Content-Type': 'application/json', Accept: 'application/json' }
 {"address":"0x9a5c0xxxxxxxeb44c6009a"}

handleRestResponse:
 idex POST https://api.idex.market/returnNextNonce 200 OK
Response:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': 'x-WAW',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Thu, 27 Feb 2020 19:30:21 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=x; expires=Sat, 28-Mar-20 19:30:21 GMT; path=/; domain=.idex.market; HttpOnly; SameSite=Lax; Secure',
  'Strict-Transport-Security': 'max-age=15552000; preload',
  'Transfer-Encoding': 'chunked',
  'X-Content-Type-Options': 'nosniff'
}
 {"nonce":769469}

fetch:
 idex POST https://api.idex.market/cancel
Request:
 {
  'Content-Type': 'application/json',
  Accept: 'application/json',
  'API-Key': 'xxxxxxxx'
}
 {"orderHash":"xxxx","address":"xxx","nonce":769469,"r":"xxxx","s":"xxxx","v":27}

handleRestResponse:
 idex POST https://api.idex.market/cancel 400 Bad Request
Response:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': 'x-WAW',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Thu, 27 Feb 2020 19:30:23 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=xxx; expires=Sat, 28-Mar-20 19:30:22 GMT; path=/; domain=.idex.market; HttpOnly; SameSite=Lax; Secure',
  'Strict-Transport-Security': 'max-age=15552000; preload',
  'Transfer-Encoding': 'chunked',
  'X-Content-Type-Options': 'nosniff'
}
 {"error":"Invalid cancel signature. Please try again."}

ExchangeError: idex {"error":"Invalid cancel signature. Please try again."}
    at idex.handleErrors (/var/www/node/bot/test/node_modules/ccxt/js/idex.js:1078:19)
    at /var/www/node/bot/test/node_modules/ccxt/js/base/Exchange.js:616:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timeout (/var/www/node/bot/test/node_modules/ccxt/js/base/functions/time.js:178:24)
    at async idex.cancelOrder (/var/www/node/bot/test/node_modules/ccxt/js/idex.js:519:26)
    at async test (/var/www/node/bot/test/test.js:169:23) {
  constructor: [Function: ExchangeError],
  name: 'ExchangeError'
}
```

**Comment by Sebdevar** [comment]
@kroitor
I recently had issues with a POST request working correctly when using curl, but returning errors when using ccxt. I ended earching a bit deeper and found that the issue is related to the requests package.

It is a current issue over here: https://github.com/psf/requests/issues/5003

Perhaps, that's the issue here as well?

**Comment by Sebdevar** [comment]
For reference:

My issue ended up being caused by the encoding of the body in the fetch method (lines 528 & 529 in exchange.py)
```python
request_body = body
if body:
    body = body.encode()
```
Removing the body encoding allowed the post request to function properly.

**Comment by kroitor** [comment]
@Sebdevar when you run it with `.encode()` – does that error happen to all requests or to just one specific endpoint?

**Comment by Sebdevar** [comment]
I couldn't test with any other ones as the first POST request I need to make is to get an access_token.

**Comment by kroitor** [comment]
> I couldn't test with any other ones as the first POST request I need to make is to get an access_token.

Sorry, didn't quite get this one. You create the API Key with IDEX website once and then use and reuse it with CCXT, right? If that is the case, which particular method have you tried calling with CCXT? Or does it break with all methods? If it does break on all methods, what's your version of Python?

**Comment by Sebdevar** [comment]
Oh, my case isn't with IDEX in particular, I just ened up finding this problem with a different one I'm wrapping and I was simply sharing, in cas it could help with this issue that seemed related

**Comment by kroitor** [comment]
@Sebdevar ah, this is a different issue then. It would be great if you can open a new issue on your case and post the details there, as described here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help. We need the code to reproduce it and the verbose request/response.

**Comment by ndubel** [comment]
> The same, but `Invalid cancel signature`

Still can't cancel order via API. Strange for certified exchange :)

**Comment by frosty00** [comment]
yeah i will investigate this now. it was working when we integrated the v1 originally, but i guess something has changed on one of our ends.

**Comment by kroitor** [comment]
@ndubel the IDEX v1 API is now deprecated, the v2 API will be launched on the mainnet on Oct 20: https://idex.io

**Comment by ttodua** [comment]
Idex now uses v3 Api in CCXT, so this issue should be closed.
