### ISSUE TITLE
Bitstamp Authentication Error on Withdrawing BTCs

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#6617]
- OS: Windows 10/ Linux
- Programming Language version: Python 3.6
- CCXT version: 1.24.7
- Exchange: Bitstamp
- Method: withdraw

Hi, @kroitor,

I've been facing troubles on withdrawing BTC from my wallet, by using this ccxt version. I'm getting the Authentication Error.
Please, take a look at the code below:
```
import ccxt
import time
bitstamp = getattr(ccxt, 'bitstamp')({'nonce': lambda: int(time.time() * 1000)})
bitstamp.uid = "myuid"
bitstamp.apiKey = "apiKey"
bitstamp.secret = "secret"
bitstamp.password = "password"
response = bitstamp.withdraw('BTC', 0.05, "address")
print(response)
```
And at the response:
```
Traceback (most recent call last):
  File "C:/Users/MANGUEIRA/PycharmProjects/Bots Projects/Support and Tests/Auxiliar.py", line 8, in <module>
    response = bitstamp.withdraw('BTC', 0.05, "address")
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\bitstamp.py", line 1002, in withdraw
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\base\exchange.py", line 444, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\base\exchange.py", line 467, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\base\exchange.py", line 463, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\base\exchange.py", line 580, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\bitstamp.py", line 1094, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], value, feedback)
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\base\exchange.py", line 481, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: bitstamp {"error": "Missing key, signature and nonce parameters"}
```
I'm pretty sure my keys are correct, as my orders are placed smoothly.
It seems there is a correlation with the #6456, updated to your library days ago.

Can you help to solve it?

**Comment by kroitor** [comment]
Hi, @Felipe-Mangueira !

> Can you help to solve it?

Sure, but I need to do the following:

1. First of, never paste your keys in public, otherwise you might lose your funds
2. Output the CCXT version number actually used in your runtime
3. Paste verbose output of the withdraw call here, without your keys, of course.

```Python
import ccxt
import time
bitstamp = getattr(ccxt, 'bitstamp')({'nonce': lambda: int(time.time() * 1000)})
bitstamp.uid = "myuid"
bitstamp.apiKey = "apiKey"
bitstamp.secret = "secret"
bitstamp.password = "password"

bitstamp.load_markets()  # preload them first to avoid too much output
print(ccxt.__version__)  # print CCXT version
bitstamp.verbose = True  # enable verbose mode before the withdraw call

response = bitstamp.withdraw('BTC', 0.05, "address")
print(response)
```

↑ Paste your entire verbose output, including the request part and the response part here, plz.

**Comment by Felipe-Mangueira** [comment]
Thank for the advice. The keys were erased .
This is the request part:
```
import ccxt
import time
bitstamp = getattr(ccxt, 'bitstamp')({'nonce': lambda: int(time.time() * 1000)})
bitstamp.uid = "uid"
bitstamp.apiKey = "apiKey"
bitstamp.secret = "secret"
bitstamp.password = "password"

bitstamp.load_markets()
print(ccxt.__version__)
bitstamp.verbose = True

response = bitstamp.withdraw('BTC', 0.05, "adress")
print(response)
```
This is the verbose output:
```
1.24.7

Request: POST https://www.bitstamp.net/api/bitcoin_withdrawal/ {'X-Auth': 'BITSTAMP apiKey', 'X-Auth-Nonce': '6ff69857-6bd4-4c20-b628-b5cc6127a5bf', 'X-Auth-Timestamp': '1584127662620', 'X-Auth-Version': 'v2', 'Content-Type': 'application/x-www-form-urlencoded', 'X-Auth-Signature': b'0cbf688c1dca4c4f606fc3018aab4528ede86dbaeddfd02da7a207eeaf665d36', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} amount=0.05&address=address
Traceback (most recent call last):

  File "C:/Users/MANGUEIRA/PycharmProjects/Bots Projects/Support and Tests/Auxiliar.py", line 13, in <module>
    response = bitstamp.withdraw('BTC', 0.05, "address")
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\bitstamp.py", line 1002, in withdraw
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\base\exchange.py", line 444, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\base\exchange.py", line 467, in request
Response: POST https://www.bitstamp.net/api/bitcoin_withdrawal/ 200 {'Date': 'Fri, 13 Mar 2020 19:27:42 GMT', 'Content-Type': 'application/json', 'Content-Length': '56', 'Connection': 'keep-alive', 'Server': 'Apache', 'X-XSS-Protection': '1; mode=block', 'Content-Language': 'en', 'Expires': 'Fri, 13 Mar 2020 19:27:42 GMT', 'Vary': 'Authorization,Accept-Language,Cookie', 'Content-Security-Policy-Report-Only': "default-src 'self' 'report-sample'; connect-src 'self' wss://ws.pusherapp.com wss://ws.bitstamp.net *.pusher.com *.trackjs.com *.google-analytics.com stats.g.doubleclick.net ; font-src 'self' data: assets.bitstamp.net fonts.gstatic.com www.google.com ; frame-ancestors 'self'; frame-src 'self' pixel-a.basis.net 8720977.fls.doubleclick.net *.ledgerwallet.com *.google.com www.googletagmanager.com pixel.sitescout.com ctpe.net ; img-src * data: blob:; report-uri /api/report-csp/; script-src 'self' 'unsafe-eval' assets.bitstamp.net js-agent.newrelic.com *.google-analytics.com *.pusher.com d3dy5gmtp8yhk7.cloudfront.net www.googleadservices.com www.googletagmanager.com www.gstatic.com www.recaptcha.net code.highcharts.com/stock/highstock.js bam.nr-data.net 'nonce-NjI3MzA4OTY4NjM3MDQ2ODE1OTYyNzQ4MTkzMTM2NzE0NDczNDE='; style-src 'self' 'unsafe-inline' assets.bitstamp.net fonts.googleapis.com", 'Cache-Control': 'max-age=0', 'X-Frame-Options': 'SAMEORIGIN', 'Set-Cookie': 'stmpdid=Q970OtKNPiFVW2vKLJtcqmFdE3I5kKMdoZeaArMJugYqkp7AXVbOD_T70O-Yz_dVCFYzNyIKVVpSa6xKA-pAS44; expires=Fri, 12-Mar-2027 19:27:42 GMT; httponly; Max-Age=220752000; Path=/; secure, visid_incap_99025=X9UpeBGwSlGravHlA1QAc67ea14AAAAAQUIPAAAAAAA00GIJ7RAYciS9xuZe4DpO; expires=Sat, 13 Mar 2021 16:34:15 GMT; HttpOnly; path=/; Domain=.bitstamp.net, nlbi_99025=II4LfdklBErlvoqOL9q5pgAAAAAT76sNHLHlHDveib6shrkA; path=/; Domain=.bitstamp.net, incap_ses_788_99025=d9DeKJn1tmM/HXSLBovvCq7ea14AAAAA4Z0R4178NybQzsdrLxaCjQ==; path=/; Domain=.bitstamp.net', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Last-Modified': 'Fri, 13 Mar 2020 19:27:42 GMT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'POST, GET', 'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'X-CDN': 'Incapsula', 'X-Iinfo': '14-23929125-23918973 PNNy RT(1584127662047 503) q(0 0 0 -1) r(2 2) U6'} {"error": "Missing key, signature and nonce parameters"}
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\base\exchange.py", line 463, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\base\exchange.py", line 580, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\bitstamp.py", line 1094, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], value, feedback)
  File "C:\Users\MANGUEIRA\PycharmProjects\venv\lib\site-packages\ccxt\base\exchange.py", line 481, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: bitstamp {"error": "Missing key, signature and nonce parameters"}
```
Thank you for the support.

**Comment by kroitor** [comment]
@Felipe-Mangueira alright, i've uploaded a fix for it and it should work normally as of CCXT 1.24.8+. Let me know if the problem is resolved on your side or not. Thx for reporting!

> The keys were erased

You should delete them in your API section and create new keys, because there's several hundred people watching this repository, so just deleting them from the GitHub comment won't really help.

**Comment by Felipe-Mangueira** [comment]
@kroitor, I'll test it on my side and will report back to you.

> You should delete them in your API section and create new keys, because there's several hundred people watching this repository, so just deleting them from the GitHub comment won't really help.

Thanks for your concern. I also deleted them in my API section right after the comment.

**Comment by Felipe-Mangueira** [comment]
Hi @kroitor,

Just reporting back to you: the withdraws of BTC from Bitstamp are working out again.
Thanks for your support.

**Comment by kroitor** [comment]
@Felipe-Mangueira awesome, thank you!
