### ISSUE TITLE
Upbit withdraw error

### ISSUE THREAD

**Issue by coincoin94** [ccxt/ccxt#6621]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: WINDOW10
- Programming Language version: Python 3.7
- CCXT version:1.24.5
- Exchange:UPBIT
- Method:

![20200315_100357](https://user-images.githubusercontent.com/62192611/76693185-63028280-66a4-11ea-8787-8a33deaca237.png)

Hello. I got an error while using CCXT on UPBIT exchange.

I registered my address on the whitelist and applied for withdrawal, but I keep getting errors.

Here is the code I used:

```
import ccxt

upbit1 = ccxt.upbit({
    'apiKey': 'upbit apikey',  
    'secret': 'upbit secret apikey', 
})

print(upbit1.withdraw("EOS", 1, "binancecleos", tag=100841115))
```

And the error is this.

```
Traceback (most recent call last):
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\base\exchange.py", line 553, in fetch
    response.raise_for_status()
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\requests\models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.upbit.com/v1/withdraws/coin

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/coco1/PycharmProjects/untitled/테스트.py", line 8, in <module>
    print(upbit1.withdraw("EOS", 1, "binancecleos", tag=100841115))
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\upbit.py", line 1367, in withdraw
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\base\exchange.py", line 440, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\base\exchange.py", line 463, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\base\exchange.py", line 459, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\base\exchange.py", line 565, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\upbit.py", line 1440, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: upbit {"error":{"message":"등록된 출금 주소가 아닙니다.","name":"withdraw_address_not_registered"}}

Process finished with exit code 1

```

I know I need to register a whitelist to withdraw and I have registered.

upbit {"error":{"message":"등록된 출금 주소가 아닙니다.","name":"withdraw_address_not_registered"}} means that the address is not registered on the whitelist.

However, it is clear that there is a problem when it is said that it is not a registered address.

I'm sorry, can you confirm this error?

**Comment by kroitor** [comment]
@coincoin94 can you plz post the verbose request/response for the withdraw call? (without your keys)

```Python
import ccxt

upbit1 = ccxt.upbit({
    'apiKey': 'upbit apikey',  
    'secret': 'upbit secret apikey', 
})


upbit1.load_markets()
upbit1.verbose = True
print('CCXT Version:', ccxt.__version__)


print(upbit1.withdraw("EOS", 1, "binancecleos", tag=100841115))
```

**Comment by coincoin94** [comment]
```
CCXT Version: 1.22.52

Request: POST https://api.upbit.com/v1/withdraws/coin {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiWTN5eUJweHJidGVpcnZBeXdjNWJ4TjQ1SUgwb0VzMk9BYkF6Wk9FRyIsIm5vbmNlIjoxNTg0MjM1NTYyNTI1LCJxdWVyeV9oYXNoIjoiY2FkMTk0YjRmZmUyNDFlMjQ5YWE2NTNjNThmMDkxNjhjODJmZTgwYmRkY2E5ZjRiODZkNDJhYjI0MDQ0NmM0Njc0Zjg1OGJlMWE4YTgyNDc5NzllOTNjMzkyNWY1MmExYmFkMDA0MTQ1MmE2NjlkZDQ3MGE2MjMyNWMyMzQ1YzIiLCJxdWVyeV9oYXNoX2FsZyI6IlNIQTUxMiJ9.MhTrBx6NKy13zY-INWCTp8G77DMqp8mDhdg54a053Qk', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.10.0', 'Accept-Encoding': 'gzip, deflate'} {"amount":1,"currency":"EOS","address":"binancecleos","secondary_address":100841115}
Traceback (most recent call last):
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\base\exchange.py", line 553, in fetch
    response.raise_for_status()
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\requests\models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.upbit.com/v1/withdraws/coin

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/coco1/PycharmProjects/untitled/테스트.py", line 12, in <module>
    print(upbit1.withdraw("EOS", 1, "binancecleos", tag=100841115))
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\upbit.py", line 1367, in withdraw
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\base\exchange.py", line 440, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\base\exchange.py", line 463, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\base\exchange.py", line 459, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\base\exchange.py", line 565, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\coco1\PycharmProjects\untitled\venv\lib\site-packages\ccxt\upbit.py", line 1440, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: upbit {"error":{"message":"등록된 출금 주소가 아닙니다.","name":"withdraw_address_not_registered"}}

Response: POST https://api.upbit.com/v1/withdraws/coin 400 {'Date': 'Sun, 15 Mar 2020 01:26:02 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Remaining-Req': 'group=default; min=899; sec=29', 'Content-Language': 'ko', 'Cache-Control': 'no-cache', 'X-Request-Id': 'd585cf4a-dabb-4c33-9d04-53a069ad05a4', 'Vary': 'Origin'} {"error":{"message":"등록된 출금 주소가 아닙니다.","name":"withdraw_address_not_registered"}}
```

Can I do this?

**Comment by kroitor** [comment]
The `tag` should be a string. Does this work if you change it to a string ↓ ?

```Python
print(upbit1.withdraw("EOS", 1, "binancecleos", tag='100841115'))
```

**Comment by kroitor** [comment]
@coincoin94 let me know if the above syntax with a string tag as shown in my previous comment https://github.com/ccxt/ccxt/issues/6621#issuecomment-599155642 works on your side or not:

```Python
#                              string tag in quotes here ↓
print(upbit1.withdraw("EOS", 1, "binancecleos", tag='100841115'))
```

Feel free to reopen this or just ask further questions if any. We will be happy if you report back whether the issue is resolved.

**Comment by coincoin94** [comment]
```
print(upbit1.withdraw("EOS", 1, "binancecleos", tag="100841115"))
```
I changed the tag to a string, but the same error occurs.

Also, I tried to send to the ETH and BTC addresses registered in the whitelist to see if there was a problem with the tag, but the same problem occurs.

**Comment by coincoin94** [comment]
I just solved this problem. This was my mistake. Whitelist registration is Open API management, not Favorite withdrawal address.

https://upbit.com/mypage/open_api_management

Thank you very much for your kind response, Sorry for wasting your busy time. :(

**Comment by kroitor** [comment]
@coincoin94 thank you for reporting back, we appreciate it a lot! I'm sure this will be helpful to other users!

**Comment by alsano3** [comment]
> I just solved this problem. This was my mistake. Whitelist registration is Open API management, not Favorite withdrawal address.
> 
> https://upbit.com/mypage/open_api_management
> 
> Thank you very much for your kind response, Sorry for wasting your busy time. :(

What exactly did you do?
I'm in the same situation.

**Comment by kroitor** [comment]
@alsano3 as far as I understand, you have to go to the exchange website and add your withdrawal address to the whitelist.
