### ISSUE TITLE
okex createOrder method mistakenly throws out an ExchangeError

### ISSUE THREAD

**Issue by icytrader** [ccxt/ccxt#6652]
Hi,

when I call createOrder method of Okex, it throws out an exchange error while the exchange reponse actually confirms that order has been submitted succesfully.

I can confirm that other private methods (like fetchBalance) of Okex works fine and createOrder method with Binance works fine.  Below is the code:

MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windwos
- Programming Language version: NodeJS
- CCXT version:  Pro 0.0.83

```
(async()=>{
    // console.log(await oxPro.fetchBalance())

    // console.log(await bnPro.createOrder('BTC/USDT','limit','buy',0.01,5200))
    console.log(await oxPro.createOrder('BTC/USDT','limit','buy',0.001,5200))
})()
```

```
(node:6692) UnhandledPromiseRejectionWarning: ExchangeError: okex {"client_oid":"","error_code":"0","error_message":"","order_id":"4584976330398720","result":true}
    at okex.throwExactlyMatchedException (C:\Users\Administrator\WebstormProjects\untitled4\ccxt.pro\node_modules\ccxt\js\base\ExchangeOriginal.js:523:19)
    at okex.handleErrors (C:\Users\Administrator\WebstormProjects\untitled4\ccxt.pro\node_modules\ccxt\js\okex.js:3008:14)
    at C:\Users\Administrator\WebstormProjects\untitled4\ccxt.pro\node_modules\ccxt\js\base\ExchangeOriginal.js:618:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timeout (C:\Users\Administrator\WebstormProjects\untitled4\ccxt.pro\node_modules\ccxt\js\base\functions\time.js:178:24)
    at async okex.createOrder (C:\Users\Administrator\WebstormProjects\untitled4\ccxt.pro\node_modules\ccxt\js\okex.js:1833:26)
    at async C:\Users\Administrator\WebstormProjects\untitled4\test2.js:89:17
(node:6692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
@icytrader fixed this bug, please update to 1.24.67 in 15 minutes. It will be great if you report whether it is resolved or not on your side (it does for me). Thx for your feedback!
