### ISSUE TITLE
Binance watchOrderBook TypeError: Cannot read property 'cache' of undefined 

### ISSUE THREAD

**Issue by ChenLi0830** [ccxt/ccxt#6672]
- OS:
Linux/centos 7
- Programming Language version:
NodeJS
- CCXT version:
ccxt.version 1.22.55
ccxtpro.version 0.1.9

I am running two independent scripts on the same machine as follows
```
// script 1
try {
// business logic...
await this.exchange.watchOrderBook("BTC/USDT", 10)
// business logic...
} catch(error) {
// handle the error
}


// script 2
try {
// business logic...
await this.exchange.watchOrderBook("ETH/USDT", 10)
// business logic...
} catch(error) {
// handle the error
}
```
Error:
```
/node_modules/ccxt.pro/js/binance.js:225
            orderbook.cache.push (message);
                      ^

TypeError: Cannot read property 'cache' of undefined
    at binance.handleOrderBook (/myProjectName/node_modules/ccxt.pro/js/binance.js:225:23)
    at binance.handleMessage (/myProjectName/node_modules/ccxt.pro/js/binance.js:801:27)
    at WsClient.onMessage (/myProjectName/node_modules/ccxt.pro/js/base/Client.js:265:14)
    at WebSocket.onMessage (/myProjectName/node_modules/ccxt.pro/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:311:20)
    at WebSocket.EventEmitter.emit (domain.js:482:12)
    at Receiver.receiverOnMessage (/myProjectName/node_modules/ccxt.pro/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.EventEmitter.emit (domain.js:482:12)
    at Receiver.dataMessage (/myProjectName/node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:436:14)                      
```
I've been running the script for a week, and it never happened before. However, it has happened twice today. 

I can't seem to repeat the error, it happened after running the scripts for a while. It is worth noting that both of the scripts, which operate on different binance accounts, have that error at pretty much the same time. I might be wrong but I think it might be caused because some abnormal behaviors from Binance Future websocket were not handled properly.

**Comment by kroitor** [comment]
Thank you for reporting! We will investigate and will get back to you with our findings.

**Comment by ChenLi0830** [comment]
@kroitor Thank you for your quick response! Are you going to release a new version for the bug fix?

**Comment by kroitor** [comment]
@ChenLi0830 yes, it takes approximately 15 minutes for the automatic build to finish, so it will arrive shortly. From what I see, it appears that Binance sends an orderbook update before the subscription confirmation, so I've added a workaround for it and it should behave normally in 0.1.10+. Let me know if you have further difficulties with it. Thx again for your feedback!

**Comment by ChenLi0830** [comment]
@kroitor sounds good, thank you!
