### ISSUE TITLE
Unable to resolve module './js/btcchina.js'

### ISSUE THREAD

**Issue by marcelcure** [ccxt/ccxt#6674]
- OS: Debian 10 android apk 29
- Programming Language version: react-native 0.61.5
- CCXT version: 1.24.96

```
Simply put var ccxt = require('ccxt'); into any module
```

```
[Wed Mar 25 2020 11:31:13.196]  BUNDLE  ./index.js 

error: Error: Unable to resolve module `./js/btcchina.js` from `node_modules/ccxt/ccxt.js`: 

None of these files exist:
  * node_modules/ccxt/js/btcchina.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/ccxt/js/btcchina.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/home/marcel/ReactNative/FusionCommerce/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/home/marcel/ReactNative/FusionCommerce/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/home/marcel/ReactNative/FusionCommerce/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/home/marcel/ReactNative/FusionCommerce/node_modules/@react-native-community/cli/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at dependencies.map.result (/home/marcel/ReactNative/FusionCommerce/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/marcel/ReactNative/FusionCommerce/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /home/marcel/ReactNative/FusionCommerce/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/marcel/ReactNative/FusionCommerce/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

**Comment by kroitor** [comment]
@marcelcure Let me know if you still have the same issue with version 1.24.97, it will arrive in 15 minutes. It will be great if you report back whether it is helped or not. Also, you might want to rebuild your framework bundles to make sure that your version is up to date. Looking forward to hearing back from you! Thanks!

**Comment by marcelcure** [comment]
I updated to 1.24.97 and to begin with I had the exact same error, so I deleted node_modules and rebuilt and now it is working perfectly. Thank you. Good job - very fast.

**Comment by kroitor** [comment]
@marcelcure thanks for your feedback! Appreciate it!
