### ISSUE TITLE
Kraken What-is-the-minimum-order-size- 403 Forbidden

### ISSUE THREAD

**Issue by mycase** [ccxt/ccxt#6701]
- OS: Linux Fedora 31, kernel 5.4.10-200.fc31.x86_64
- Programming Language version: Python 3.8.1
- CCXT version: ccxt==1.23.86

```
import ccxt
kraken = ccxt.kraken()
kraken.fetchTicker('USDT/USD')
```

```
Traceback (most recent call last):
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/ccxt/base/exchange.py", line 555, in fetch
    response.raise_for_status()
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dev/kraken/KrakenPriceFeedErrorDemo.py", line 3, in <module>
    kraken.fetchTicker('USDT/USD')
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/ccxt/kraken.py", line 514, in fetch_ticker
    self.load_markets()
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1272, in load_markets
    markets = self.fetch_markets(params)
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/ccxt/kraken.py", line 281, in fetch_markets
    limits = self.fetch_min_order_amounts()
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/ccxt/kraken.py", line 259, in fetch_min_order_amounts
    html = self.zendeskGet205893708WhatIsTheMinimumOrderSize()
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/ccxt/base/exchange.py", line 442, in inner
    return entry(_self, **inner_kwargs)
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/ccxt/base/exchange.py", line 465, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/ccxt/base/exchange.py", line 461, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/ccxt/base/exchange.py", line 568, in fetch
    self.handle_rest_errors(http_status_code, http_status_text, http_response, url, method)
  File "/home/user/projects/project_X7/venv/project_X7/lib/python3.8/site-packages/ccxt/base/exchange.py", line 595, in handle_rest_errors
    raise error(' '.join([method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: GET https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- 403 Forbidden <!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <title>Security check</title>
  <style>body{background:#03363d;color:#fff;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen-Sans,Ubuntu,Cantarell,Helvetica Neue,Arial,sans-serif;font-size:14px;font-style:normal;font-variant:normal;line-height:1.6;margin:1.6rem}h1{font-size:22px;line-height:1.4em;margin-top:0;padding-top:0}article,h1,p{margin:0}:link,:visited{color:#fff}.l-max-readable-width{max-width:40em}.l-centered{margin-left:auto;margin-right:auto}.l-v-padded{padding-bottom:.8rem}.l-top-padded,.l-v-padded{padding-top:.8rem}.l-padded-bottom{margin-bottom:.8rem}.err__page-heading{font-size:1rem;font-weight:400;padding-bottom:1.6rem}@media screen and (min-width:400px){.err__page-heading{font-size:1.6rem;font-weight:300}}@media screen and (min-width:520px){.err__page-heading{font-size:2rem}}.err__container{background:#fff;border-radius:.2rem;color:#012b30;padding:1.2rem 1.6rem}.err__container :link,.err__container :visited{color:#1f73b7}.err__additional-translation:before{background:#56777a;content:"";display:block;height:.4rem;margin:.8rem 0;overflow:hidden;width:2.4rem}.err__details-content h1{font-size:1em;font-weight:600;line-height:inherit}.err__details-content ul{margin-bottom:0;margin-top:0}.c-btn{-moz-user-select:none;-ms-user-select:none;-webkit-font-smoothing:subpixel-antialiased;-webkit-touch-callout:none;-webkit-user-select:none;background-color:transparent;border:1px solid #5293c7;border-radius:4px;box-sizing:border-box;color:#1f73b7;cursor:pointer;display:inline-block;font-family:inherit;font-size:14px;font-weight:400;line-height:38px;margin:0;min-width:8.57143em;overflow:hidden;padding:0 1.92857em;text-align:center;text-decoration:none;text-overflow:ellipsis;transition:border-color .25s ease-in-out,box-shadow .1s ease-in-out,background-color .25s ease-in-out,color .25s ease-in-out;user-select:none;vertical-align:middle;white-space:nowrap}.c-btn.c-btn--primary{background-color:#1f73b7;border-color:transparent}.c-btn.c-btn--primary{color:#fff}.c-btn.is-hovered.is-hovered,.c-btn:hover:hover{background-color:#5293c7;border-color:transparent;color:#fff;text-decoration:none}.c-btn.is-focused,.c-btn:focus:focus{box-shadow:0 0 0 3px rgba(31,115,183,.35);outline:none}.c-btn.is-active.is-active,.c-btn:active:active{background-color:#144a75;border-color:transparent;color:#fff;text-decoration:none;transition:border-color .1s ease-in-out,background-color .1s ease-in-out,color .1s ease-in-out}.u-fine-print-on-white{color:#2d5e64;font-size:.785rem}.u-centered{text-align:center}</style>
  <meta name="viewport" content="width=device-width">
</head>

<body>
  
  <article class="l-max-readable-width l-centered">

    <h1 class="err__page-heading">
      Complete the security check to access this page
    </h1>

    <div class="err__container l-padded-bottom">
      <div class="l-top-padded err__details-content">
        <form class="challenge-form" id="challenge-form" action="/hc/en-us/articles/205893708-What-is-the-minimum-order-size-?__cf_chl_captcha_tk__=8e6ce2b815da68ce877154b8f740c95d6fc2510d-1585574487-0-AbAc-0Z4q8Nv5e8NQs6nvjKgE59Tu-pXyULktcXWCnFdYYH2B64j0BD8OEa_aG1_wK5Hp__yOa9VcjofRXd2DLPAAnme-Mu1AtKSRS1OcB17YHyrbL_BUczHKUP4Aea809z-Bq6vtHQSyhdTCfekQAGl87oQDW7EWHkFJo8KhJC9XURvQRbKSAeO9wozd5O1EpmyG1MQvzY064Kf9P9JfxGFB8vZGlnTMSyCc9q3kETKCtFjDyDBVqzn5OP-z2LfJLfdU2UgMUQJQg-TmUku6-BX_CQWhziqZmYnTSDzZGDXWkB-gxWU22SVDLubgipZtFBgx-A4i9fD46LVGhLivYW5_BD2XGwXSOzeGa8cRAU6X_rSGMkiRLFRHkKQdmGO7Ep8Y0OxmX9R2A-OT8vCwzZReZRsihH27E8NptTPQ6XSqOtIChL3TyKi7tCeLiOYlQdCIwxv1ucCoaNH48REcABv-SYnF8omhxTGBaf5dfwqA-73h9Ip8z37H3TSrrpjq57-vF8RPXy-uJHrARdnNddcGcjRRnt581fMXo9Nvn-hhkN25WKwGi95wFozxNiaaZlEZJWVRllBdCPNTUulO-BuMtuyzppBeXc8SC6PZSTVybzpR59zL0UZuNriDcdvtg" method="POST" enctype="application/x-www-form-urlencoded">
  <input type="hidden" name="r" value="aac902a8a41025eb575d912c40217ddd49645d41-1585574487-0-AWjMPDrAtpXRPh3nzp2YoCfc+ake/CiyEUCVxQmMPlGA2Uxd+CydcCw9ketu9+f7wArAtEnDIyDDfn62MIkOhrXIFrHgE6MCxhnJIBUbtMyqzHUSuts/YvuQM44bvkJ1GC6/crqZ3NWBzAuRjpzTnNfsjukFn3whHCZHY/27HiWbOVnei2ZxmFa7ySUAZOzTz6ROei7CWrVOl8HjiJC33NMAqTWZC6IAH5KoHYnI//m8/Vpcprp27jrQwGDD4EvgaT3ZVjWlXbSDHByIxuSkBuCWpNg7ZKf8zuys8SNFUTuX+8BJl8cFJGWe8QFeTSbEIt/8kfzgP0bh9BLBq1stOjdzJHYHOy3705NNVxsOSFBaooShiPrCzatzDWMMAUhqJETPlrtQKQH0QHyIBovx44EIYAAVxKlRWG+iFz8IuSWgQMME05WfKxwRj5A4Sq5KvJ0tt0Wgc5e8Zv0aTuMssa/mjnsQotLN8d6nafzCyUTW9ZPxCmRAkppgTCShJQxWs1XJ4XY9l9FlJTYOYIstQnxg7vpV8tjgbC5BBsJlWuN5Q8YoHLx2B8CgkFp3to5OR4Yi5Dq6hmUM55ZCDpPY2wqf+/XTy0DNGX1SmtGnwdp4fQb3rbze5OY/15hdNvXBLWMmS7Jvw8IzuXerNKX2WS532uLmKanzQER5p7JaNHxTohvKRFpUF6+j1h/0+n6QtElbekxYUSB2qPeVWQGEinMdoClX9IV+H+cmF6m/zko5qNyma+3hSyZIZVL8eAUdvIUbGTlYFBjwpg08zQ1QCEyYiEgVCA96EEED2Lg+ksDReZin/UhsZ/7K7OM9c211NARRtuTlK1kcBEvGvRpBf+QlemHm8iQtEERiBctLP6NDYHjJFxwj4TIOBld/ZN+mIlBD0lBP9M3/6V9V/kGmuR0OE8N9y5XZFjiTVdzBqzQV9A6cO+UnsQGJeYPc96hiDflui5WaPL9Az1cFTfu9Tappuam1RIRkdv5Rtwx0+q4RaOkclUuYYk+p24ndi1uzmVZh6MwsUBFiZaDlvgUvl74F1K+squ2ZghpCHDZyI8G8D4m9IaNY0kKXdxKm00Bmgxw6ZeclYiXVS4P1zpYgxyoIRdt84EMdfnoDqFkoenOZ2PevkI9Ivnbdt/iYqxAhLWI6414/2G281yrayLDelMm/8mcTn0bbCKKxzavKGxdL131kAzEABspUjjOFL+Nd01gVxxHTj48lS+GpPevlkb7n4v66ctM1w4zbSRzgNg3ytEmE6blLHMdTjNyrMY8cuURfO6OyUZ33sUk7RYjJwlHtZXOFEmjfj9rXwsEnuoBE+dIaYOorydM5T/vdGiWmGFbrAlbSlpWAg6wbM09jf4747qYVjmP5ZsnjP4FRJVKN">
  <input type="hidden" name="cf_captcha_kind" value="h">
  <script type="text/javascript" src="/cdn-cgi/scripts/hcaptcha.challenge.js" data-type="normal"  data-ray="57c22243ce79fa20" async data-sitekey="33f96e6a-38cd-421b-bb68-7806e1764460"></script>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
  <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=57c22243ce79fa20')"></div>
</form>

        <hr>
      </div>
      <p>
        Completing a CAPTCHA proves you are a human and gives you temporary access to this page.
        <br>
        Make sure your home and work devices are regularly scanned for malware to reduce the need to complete the CAPTCHA.
        <hr>
        RayID: 57c22243ce79fa20
        <br>
        IP: 62.163.247.13
      </p>
    </div>

    <div class="l-v-padded">
      <div lang="pt-br" class="err__additional-translation">
        <h3>
          Conclua essa verificação de segurança para acessar essa página
        </h3>
        <p class="l-top-padded">
          Completar o CAPTCHA comprova que você é humano e fornece acesso temporário à página. Verifique regularmente seus dispositivos domésticos e comerciais quanto a infecções de malware para reduzir a necessidade de conclusão do CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="es-419" class="err__additional-translation">
        <h3>
          Complete la verificación de seguridad para tener acceso a esta página
        </h3>
        <p class="l-top-padded">
          La verificación CAPTCHA se encarga de comprobar que usted es un ser humano, y le da acceso temporal a esta página. Asegúrese de analizar regularmente sus dispositivos personales y de trabajo en busca de malware para reducir la necesidad de una verificación CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="de" class="err__additional-translation">
        <h3>
          Sicherheitsprüfung zum Zugriff auf diese Seite erforderlich
        </h3>
        <p class="l-top-padded">
          Die CAPTCHA-Prüfung beweist, dass es sich bei Ihnen um einen echten Menschen handelt, und gibt Ihnen vorübergehend Zugriff auf diese Seite. Achten Sie darauf, dass Ihre Geräte zuhause und im Büro regelmäßig auf Malware geprüft werden, damit CAPTCHA nur in Ausnahmefällen erforderlich ist.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="fr" class="err__additional-translation">
        <h3>
          Veuillez effectuer la vérification de sécurité pour accéder à cette page
        </h3>
        <p class="l-top-padded">
          Une vérification CAPTCHA nous permet de nous assurer que vous êtes une personne réelle afin de vous donner un accès temporaire à cette page. Vérifiez régulièrement l’absence de logiciels malveillants sur vos appareils personnels et professionnels pour réduire la nécessité d’effectuer une vérification CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="nl" class="err__additional-translation">
        <h3>
          Voltooi de beveiligingscontrole om toegang tot deze pagina te krijgen
        </h3>
        <p class="l-top-padded">
          Door een CAPTCHA in te vullen, bewijst u dat u een mens bent en krijgt u tijdelijk toegang tot deze pagina. Zorg ervoor dat uw apparaten voor persoonlijk en zakelijk gebruik regelmatig worden gescand op malware. Zo wordt het invullen van een CAPTCHA minder noodzakelijk.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="ru" class="err__additional-translation">
        <h3>
          Для доступа к этой странице необходимо пройти проверку безопасности
        </h3>
        <p class="l-top-padded">
          Успешное прохождение теста CAPTCHA доказывает, что вы человек, и дает вам временный доступ к этой странице. Чтобы не проходить тест CAPTCHA слишком часто, регулярно проверяйте свои устройства дома и на работе на отсутствие вредоносных программ.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="ja" class="err__additional-translation">
        <h3>
          このページにアクセスするには、セキュリティチェックを完了してください
        </h3>
        <p class="l-top-padded">
          CAPTCHAを正しく入力すると人間による入力であることが証明され、このページへの一時的なアクセスが提供されます。CAPTCHAを入力する必要性を減らすには、マルウェアが存在しないか自宅と職場の機器を定期的にスキャンするようにしてください。
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="it" class="err__additional-translation">
        <h3>
          Completa il controllo di sicurezza per accedere a questa pagina
        </h3>
        <p class="l-top-padded">
          Il superamento del test CAPTCHA dimostra che sei un essere umano e ti concede l’accesso temporaneo a questa pagina. Assicurati di sottoporre a scansione i dispositivi che usi a casa e al lavoro per escludere la presenza di malware e ridurre la necessità di eseguire il test CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="ar" class="err__additional-translation">
        <h3 dir="rtl">
          أكمل الفحص الأمني للوصول إلى هذه الصفحة
        </h3>
        <p class="l-top-padded" dir="rtl">
          يثبت إكمال اختبار CAPTCHA أنك إنسان ويمنحك وصولاً مؤقتًا لهذه الصفحة. تأكد من إجراء مسح دوري على أجهزة منزلك وعملك لاستكشاف البرامج المضرة لتقليل الحاجة إلى إكمال اختبار   CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="zh-cn" class="err__additional-translation">
        <h3>
          完成安全检查以访问此页面
        </h3>
        <p class="l-top-padded">
          完成 CAPTCHA 可证明您是真人，将为您提供对此页面的临时访问权限。请确保您的家庭和工作设备定期进行恶意软件扫描，以降低需要完成 CAPTCHA 的频率。
        </p>
      </div>
    </div>
  </article>
</body>
</html>
```

**Comment by kroitor** [comment]
Addressed here: https://github.com/ccxt/ccxt/issues/6700
