### ISSUE TITLE
Error connecting to OKEX v3 - name resolution failed

### ISSUE THREAD

**Issue by azharuniverse** [ccxt/ccxt#6722]
- OS: ALL
- Programming Language version: JS
- CCXT version: "^1.23.22"

```
fetchTickers()
```

```
Error Fetching tickers for okex3 { ExchangeError: okex3 {"message":"name resolution failed"}
    at okex3.handleErrors (C:\Users\azhar\Documents\Projects\MarsTrade\node_modules\ccxt\js\okex3.js:2706:19)
    at response.text.then (C:\Users\azhar\Documents\Projects\MarsTrade\node_modules\ccxt\js\base\Exchange.js:616:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  constructor: [Function: ExchangeError],
  name: 'ExchangeError' }
```

**Comment by kroitor** [comment]
OKEX is down for maintenance, since 8.30 to 10.00 UTC and they should be back up by this time, but not yet...

> https://t.me/OKExOfficial_English/156875
> Scheduled Upgrade: Spot & Margin Trading Will Be Temporarily Unavailable
> We will carry out a scheduled system upgrade of our spot trading system :alarm_clock:on April 2, 2020 from 8:30-10:00 (UTC).
> OKEX

Let us know if that does not answer the question.
