### ISSUE TITLE
okex切换子交易所

### ISSUE THREAD

**Issue by 317459062** [ccxt/ccxt#6746]
OS: Linux (Ubuntu 18.04)
Programming Language version: Python 3.7
CCXT version: 1.25.41
Hi,我不能使用okex3,之前使用ccxt.okex3(ccxt version 1.18)能切换到使用ok的子交易所，如：https://www.vvcoin.com ,https://www.99ex.com  现在无法使用okex链接到上面两个交易所，我该如何解决。之前的代码：
exchange=ccxt.okex({'apiKey':accesskey,'secret':secretkey,'password':Passphrase,'urls':{'api':'https://www.99ex.com'}})

现在的代码：exchange=ccxt.okex({'apiKey':accesskey,'secret':secretkey,'password':Passphrase,'urls':{'api':'https://www.99ex.com'}})

Traceback (most recent call last):
  File "E:/workfile/qbtc/otherEx/99ex/99ex_hdcc_usdt.py", line 158, in <module>
    exchange.create_order(side='sell', symbol=symbol, price=0.004, amount=10, type='limit')
  File "D:\Python\Python36\lib\site-packages\ccxt\okex.py", line 1749, in create_order
    self.load_markets()
  File "D:\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 1286, in load_markets
    markets = self.fetch_markets(params)
  File "D:\Python\Python36\lib\site-packages\ccxt\okex.py", line 697, in fetch_markets
    markets = self.fetch_markets_by_type(types[i], params)
  File "D:\Python\Python36\lib\site-packages\ccxt\okex.py", line 885, in fetch_markets_by_type
    response = getattr(self, method)(params)
  File "D:\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 446, in inner
    return entry(_self, **inner_kwargs)
  File "D:\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 469, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "D:\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 464, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "D:\Python\Python36\lib\site-packages\ccxt\okex.py", line 3024, in sign
    url = self.implode_params(self.urls['api']['rest'], {'hostname': self.hostname}) + request
TypeError: string indices must be integers

**Comment by 317459062** [comment]
thanks   解决了问题

exchange=ccxt.okex({'apiKey':accesskey,'secret':secretkey,'password':Passphrase,'urls':{'api':{‘rest’:'https://www.99ex.com'}}})

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/6623#issuecomment-599218303

**Comment by 317459062** [comment]
no   just https://www.99ex.com  sub exchange of okex

**Comment by 317459062** [comment]
yes
