### ISSUE TITLE
bithumb cancelOrder method not working

### ISSUE THREAD

**Issue by p1004x** [ccxt/ccxt#6771]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: window10
- Programming Language version: Node.js 12.16.1
- CCXT version: 1.25.91

 
```

    let bithumb    = new ccxt.bithumb ({
        apiKey: 'xxxxxxxxxxxxxx',
        secret: 'xxxxxxxxxxxxxxxxxxxx',
    })


            try {
            let buyOrder = await bithumb.createLimitBuyOrder ('BTC/KRW',0.1, 4000000); 
            let id = buyOrder.info.order_id;

            await bithumb.cancelOrder(id, 'BTC/KRW' ,params = {'side':'buy', 'currency':'BTC'});
 
        } catch (error) {
            console.error(error);
        }
})
();


BadRequest: bithumb {"status":"5500","message":"Invalid Parameter"}
    at bithumb.handleErrors (C:\Users\GLADOS\dev\bot\node_modules\ccxt\js\bithumb.js:436:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (C:\Users\GLADOS\dev\bot\node_modules\ccxt\js\base\functions\time.js:178:24)
    at async bithumb.request (C:\Users\GLADOS\dev\bot\node_modules\ccxt\js\bithumb.js:443:26)
    at async bithumb.cancelOrder (C:\Users\GLADOS\dev\bot\node_modules\ccxt\js\bithumb.js:361:16)
    at async C:\Users\GLADOS\dev\bot\src\index.js:26:13 {
  constructor: [Function: BadRequest],
  name: 'BadRequest'
}


````

Why is the parameter invalid? Thanks for your help

**Comment by kroitor** [comment]
@p1004x looks like they have changed their API param names.

```
        try {

            await bithumb.loadMarkets()
            bithumb.verbose = true

            let buyOrder = await bithumb.createLimitBuyOrder ('BTC/KRW',0.1, 4000000); 
            
            // let id = buyOrder.info.order_id;

            await bithumb.cancelOrder(buyOrder.id, 'BTC/KRW', {'side':'buy', 'currency':'BTC'});
 
        } catch (error) {
            console.error(error);
        }
```

↑ Can you plz post your verbose request/response? I'll add a fix to ti shortly.

**Comment by kroitor** [comment]
@p1004x plz check if you have issues with it after upgrading to 1.26.1+ (the new build will arrive in 15 minutes). It would be great if you let us know whether it works on your side or not. Thx for the feebdack!

**Comment by p1004x** [comment]
this is bithumb.js file
 ``` 
 async cancelOrder (id, symbol = undefined, params = {}) {
        const side_in_params = ('side' in params);
        if (!side_in_params) {
            throw new ExchangeError (this.id + ' cancelOrder requires a `symbol` argument and a `side` parameter (sell or buy)');
        }
        if (symbol === undefined) {
            throw new ExchangeError (this.id + ' cancelOrder requires a `symbol` argument and a `side` parameter (sell or buy)');
        }
        const market = this.market (symbol);
        const side = (params['side'] === 'buy') ? 'bid' : 'ask';
        params = this.omit (params, [ 'side', 'currency' ]);
        const request = {
            'order_id': id,
            'type': side,
            'order_currency': market['baseId'],
            'payment_currency': market['quoteId'],
        };
        return await this.privatePostTradeCancel (this.extend (request, params));
    }

````

        const request = {
            'order_id': id,
            'type': side,
            'order_currency': market['baseId'],
            'payment_currency': market['quoteId'],
        };

````

        const request = {
            'order_id': id,
            'type': side,
            'order_currency': market['base'],
            'payment_currency': market['quote'],
        };

````
If you modify it, it works well.
