### ISSUE TITLE
CreateOrder and CancelOrder in foxbit don't work

### ISSUE THREAD

**Issue by pabloapdz** [ccxt/ccxt#6778]
Ps: I found [this](https://github.com/ccxt/ccxt/issues/638) old issue but it talked about the general function and blinktrade, so I don't know if it would be right to open a new one or comment there, but, as I will be listing two problems, I decided to open a new one.

Any mistake I'm sorry

- OS: Windows
- Programming Language version: Python 3.8
- CCXT version: 1.26.5

```
from ccxt.foxbit import foxbit

fox = foxbit({
    'apiKey': API_key,
    'secret': API_Secret
})
test_one = fox.create_order('BTC/BRL', 'limit', 'buy', 1, 1000)
test_two = fox.cancel_order(0, 'BTC/BRL')
```

**test_one result this error:**
```
Traceback (most recent call last):
  File "C:\Users\criptoph\Desktop\Requests nas API's\foxbit\principal.py", line 177, in <module>
    teste = fox.create_order('BTC/BRL', 'limit', 'buy', 1, 1000)
  File "C:\python34\lib\site-packages\ccxt\foxbit.py", line 196, in create_order
    response = self.privatePostD(self.extend(request, params))
  File "C:\python34\lib\site-packages\ccxt\base\exchange.py", line 446, in inner
    return entry(_self, **inner_kwargs)
  File "C:\python34\lib\site-packages\ccxt\foxbit.py", line 233, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: foxbit {"Status":500,"Description":"Invalid value tag(ClOrdID)=1586621325","Result":{}}
```
**test_two result this error:**
```
Traceback (most recent call last):
  File "C:\Users\criptoph\Desktop\Requests nas API's\foxbit\principal.py", line 178, in <module>
    teste = fox.cancel_order(0, 'BTC/BRL')
  File "C:\python34\lib\site-packages\ccxt\foxbit.py", line 206, in cancel_order
    return self.privatePostF(self.extend({
  File "C:\python34\lib\site-packages\ccxt\base\exchange.py", line 446, in inner
    return entry(_self, **inner_kwargs)
  File "C:\python34\lib\site-packages\ccxt\foxbit.py", line 233, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: foxbit {"Status":500,"Description":"Invalid value tag(ClOrdID)=0","Result":{}}
```

**Comment by pabloapdz** [comment]
I'm still waiting

**Comment by kroitor** [comment]
@pabloapdz see this issue for details, I suggest to move this discussion there: https://github.com/ccxt/ccxt/issues/3534
