### ISSUE TITLE
Liquid critical bug

### ISSUE THREAD

**Issue by ivanzhelyazkov** [ccxt/ccxt#6794]
- OS: MacOS Catalina
- Programming Language version: Node.js v12.14.1
- CCXT version: 1.26.16

```
const ccxt = require('ccxt');
require('dotenv').config();
const e = process.env;

const liquid = new ccxt.liquid({
    apiKey: e.LIQUID_ID,
    secret: e.LIQUID_SECRET
});

liquid.fetchClosedOrders().then(console.log).catch(console.log);
```

```
TypeError: Cannot read property 'symbol' of undefined
    at liquid.parseTrade (/Users/izhelyazkov/Work/liquid/node_modules/ccxt/js/liquid.js:429:29)
    at /Users/izhelyazkov/Work/liquid/node_modules/ccxt/js/base/Exchange.js:1110:85
    at Array.map (<anonymous>)
    at liquid.parseTrades (/Users/izhelyazkov/Work/liquid/node_modules/ccxt/js/base/Exchange.js:1110:51)
    at liquid.parseOrder (/Users/izhelyazkov/Work/liquid/node_modules/ccxt/js/liquid.js:626:29)
    at /Users/izhelyazkov/Work/liquid/node_modules/ccxt/js/base/Exchange.js:1150:77
    at Array.map (<anonymous>)
    at liquid.parseOrders (/Users/izhelyazkov/Work/liquid/node_modules/ccxt/js/base/Exchange.js:1150:45)
    at liquid.fetchOrders (/Users/izhelyazkov/Work/liquid/node_modules/ccxt/js/liquid.js:741:21)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

Error was caused by making a Perpetual order. After creating one order of each type (Spot, Margin, Infinity and Perpetual) on Liquid exchange, all of them worked, but the last - perpetual order - crashed the entire response from ccxt.

**Comment by kroitor** [comment]
Please, paste your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ivanzhelyazkov** [comment]
[verbose.txt](https://github.com/ccxt/ccxt/files/4474775/verbose.txt)

**Comment by kroitor** [comment]
@ivanzhelyazkov liquid has introduced perpetual markets not so long ago, and those were not supported in CCXT. I've added the necessary workarounds, and now they should work fine in CCXT 1.26.16+. We will be happy if you report whether the issue is resolved on your side or not, after upgrading to the most recent version of CCXT. It will arrive in 15 minutes. Thanks for the feedback!

**Comment by ivanzhelyazkov** [comment]
Resolved on my side.

**Comment by kroitor** [comment]
@ivanzhelyazkov awesome, thank you!
