### ISSUE TITLE
OKEX FetchDepositAddress Bug (with Solution!)

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#6844]
- OS: Linux
- Programming Language version: Python 3.7
- CCXT version: Latest

Method: ```okex.fetchDepositAddress()```

```
Request: GET https://www.okex.com/api/account/v3/deposit/address?currency=BTC {PARAMS HAVE BEEN OMITTED} 

Response: GET https://www.okex.com/api/account/v3/deposit/address?currency=BTC 200 {'Date': 'Thu, 23 Apr 2020 19:26:56 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=db54f33fc9662b54c5af301e3b28807171587670016; expires=Sat, 23-May-20 19:26:56 GMT; path=/; domain=.okex.com; HttpOnly; SameSite=Lax, locale=en_US; Max-Age=604800; Expires=Thu, 30-Apr-2020 19:26:56 GMT; Path=/', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'X-RateLimit-Remaining-second': '29', 'X-RateLimit-Limit-second': '30', 'X-BrokerID': '0', 'X-Kong-Upstream-Latency': '7', 'X-Kong-Proxy-Latency': '0', 'Via': 'kong/1.4.3', 'Strict-Transport-Security': 'max-age=63072000; includeSubdomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5889faa1de42f995-YYZ', 'Content-Encoding': 'gzip', 'cf-request-id': '024a1af9240000f9956fb85200000001'} [{"address":"3Je1DZNSZn4hpMcCp6aVc9ReGsEM8vpbvC","currency":"btc","to":6}]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/okex.py", line 2260, in fetch_deposit_address
    return addresses[0]
KeyError: 0
```
The issue -> the addresses variable has been changed from a **list** to a **dict**.

Some potential fixes would be:

**Line 2260**
```
return addresses[code]
return addresses[currency['id']]
```

**Comment by karlandoh** [comment]
Would love to add this as a commit to save time for you guys. Im looking into it... did I need to post this in pull requests instead?
