### ISSUE TITLE
Timex loadMarkets problem

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#6878]
Looks like Timex don't give `withdrawalFee` anymore

```
fetch:
 timex GET https://plasma-relay-backend.timex.io/public/currencies
Request:
 {}
 undefined

handleRestResponse:
 timex GET https://plasma-relay-backend.timex.io/public/currencies 200 OK
Response:
 {
  'Access-Control-Allow-Credentials': 'true',
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Sat, 02 May 2020 10:42:42 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'cloudflare',
  'Transfer-Encoding': 'chunked',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Xss-Protection': '1; mode=block'
}
 [{"symbol":"XRP","name":"Ripple","address":"0x0dc8882914f3ddeebf4cec6dc20edb99df3def6c","decimals":6,"tradeDecimals":16,"depositEnabled":true,"withdrawalEnabled":true,"transferEnabled":true,"active":true},{"symbol":"USDC","name":"USD Coin","address":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48","decimals":6,"tradeDecimals":16,"depositEnabled":true,"withdrawalEnabled":true,"transferEnabled":true,"active":true},{"symbol":"BTC","name":"Bitcoin","address":"0x8370fbc6ddec1e18b4e41e72ed943e238458487c","decimals":8,"tradeDecimals":20,"depositEnabled":true,"withdrawalEnabled":true,"transferEnabled":true,"active":true},{"symbol":"USDT","name":"Tether USD","address":"0xdac17f958d2ee523a2206206994597c13d831ec7","decimals":6,"tradeDecimals":16,"depositEnabled":true,"withdrawalEnabled":true,"transferEnabled":true,"active":true},{"symbol":"TPT","name":"Toilet paper token","address":"0x5a07cde9c49c348de727a8ebafdb8851c4e9b5e3","decimals":18,"tradeDecimals":32,"depositEnabled":false,"withdrawalEnabled":false,"transferEnabled":false,"active":false},{"symbol":"AUDT","name":"Australian Dollar","address":"0xd7e0f80fb28233bdde0006c50568606a8feb964c","decimals":6,"tradeDecimals":16,"depositEnabled":true,"withdrawalEnabled":true,"transferEnabled":true,"active":true},{"symbol":"SAI","name":"Sai Stablecoin","address":"0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359","decimals":18,"tradeDecimals":32,"depositEnabled":true,"withdrawalEnabled":true,"transferEnabled":true,"active":true},{"symbol":"ETH","name":"Ethereum","address":"0x45932db54b38af1f5a57136302eeba66a5975c15","decimals":18,"tradeDecimals":32,"depositEnabled":true,"withdrawalEnabled":true,"transferEnabled":true,"active":true},{"symbol":"TIME","name":"TIME Token","address":"0x6531f133e6deebe7f2dce5a0441aa7ef330b4e53","decimals":8,"tradeDecimals":20,"depositEnabled":true,"withdrawalEnabled":true,"transferEnabled":true,"active":true},{"symbol":"LTC","name":"Litecoin","address":"0x2a5cf1cf897c14513d880491c39d402fb9385fc7","decimals":8,"tradeDecimals":20,"depositEnabled":true,"withdrawalEnabled":true,"transferEnabled":true,"active":true},{"symbol":"DAI","name":"DAI stablecoin","address":"0x6b175474e89094c44da98b954eedeac495271d0f","decimals":18,"tradeDecimals":32,"depositEnabled":true,"withdrawalEnabled":true,"transferEnabled":true,"active":true}]

TypeError: Cannot read property 'length' of undefined
    at timex.parseCurrency (/var/*/node_modules/ccxt/js/timex.js:904:40)
    at timex.fetchCurrencies (/var/*/node_modules/ccxt/js/timex.js:251:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timex.loadMarketsHelper (/var/*/node_modules/ccxt/js/base/Exchange.js:700:26)
    at async test (/var/www/node/bot/test/test.js:149:26)
```

**Comment by ndubel** [comment]
They change response for some reason:
https://plasma-relay-backend.timex.io/swagger-ui.html?urls.primaryName=Relay#/Public/listCurrenciesUsingGET
