### ISSUE TITLE
Kraken replies with Captcha for fetch_order_book() method

### ISSUE THREAD

**Issue by deon4e** [ccxt/ccxt#6896]
Hi,

After having seen the captcha error occur in a previous question, I followed all the workarounds but Kraken still returns a captcha for fetch_order_book(). This happens even as fetchMinOrderAmounts is set to false upon instantiation.

- OS: MacOS 10.14
- Programming Language version: Python 3 
- CCXT version: 1.27.29

```
exchange_id = "kraken"
    exchange_class = getattr(ccxt, exchange_id)
    exchange = exchange_class({
        'apiKey': '#',
        'secret': '#,
        'timeout': 30000,
        'enableRateLimit': True,
        'options':{
            'fetchMinOrderAmounts': False
        }})
    print(exchange.fetch_order_book("BTC"))
```

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 557, in fetch
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    print(exchange.fetch_order_book("BTC"))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/kraken.py", line 441, in fetch_order_book
    self.load_markets()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1278, in load_markets
    markets = self.fetch_markets(params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/kraken.py", line 281, in fetch_markets
    limits = self.fetch_min_order_amounts()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/kraken.py", line 259, in fetch_min_order_amounts
    html = self.zendeskGet205893708WhatIsTheMinimumOrderSize()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 444, in inner
    return entry(_self, **inner_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 467, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 463, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 570, in fetch
    self.handle_rest_errors(http_status_code, http_status_text, http_response, url, method)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 597, in handle_rest_errors
    raise error(' '.join([method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: GET https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- 403 Forbidden <!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <title>Security check</title>
  <style>body{background:#03363d;color:#fff;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen-Sans,Ubuntu,Cantarell,Helvetica Neue,Arial,sans-serif;font-size:14px;font-style:normal;font-variant:normal;line-height:1.6;margin:1.6rem}h1{font-size:22px;line-height:1.4em;margin-top:0;padding-top:0}article,h1,p{margin:0}:link,:visited{color:#fff}.l-max-readable-width{max-width:40em}.l-centered{margin-left:auto;margin-right:auto}.l-v-padded{padding-bottom:.8rem}.l-top-padded,.l-v-padded{padding-top:.8rem}.l-padded-bottom{margin-bottom:.8rem}.err__page-heading{font-size:1rem;font-weight:400;padding-bottom:1.6rem}@media screen and (min-width:400px){.err__page-heading{font-size:1.6rem;font-weight:300}}@media screen and (min-width:520px){.err__page-heading{font-size:2rem}}.err__container{background:#fff;border-radius:.2rem;color:#012b30;padding:1.2rem 1.6rem}.err__container :link,.err__container :visited{color:#1f73b7}.err__additional-translation:before{background:#56777a;content:"";display:block;height:.4rem;margin:.8rem 0;overflow:hidden;width:2.4rem}.err__details-content h1{font-size:1em;font-weight:600;line-height:inherit}.err__details-content ul{margin-bottom:0;margin-top:0}.c-btn{-moz-user-select:none;-ms-user-select:none;-webkit-font-smoothing:subpixel-antialiased;-webkit-touch-callout:none;-webkit-user-select:none;background-color:transparent;border:1px solid #5293c7;border-radius:4px;box-sizing:border-box;color:#1f73b7;cursor:pointer;display:inline-block;font-family:inherit;font-size:14px;font-weight:400;line-height:38px;margin:0;min-width:8.57143em;overflow:hidden;padding:0 1.92857em;text-align:center;text-decoration:none;text-overflow:ellipsis;transition:border-color .25s ease-in-out,box-shadow .1s ease-in-out,background-color .25s ease-in-out,color .25s ease-in-out;user-select:none;vertical-align:middle;white-space:nowrap}.c-btn.c-btn--primary{background-color:#1f73b7;border-color:transparent}.c-btn.c-btn--primary{color:#fff}.c-btn.is-hovered.is-hovered,.c-btn:hover:hover{background-color:#5293c7;border-color:transparent;color:#fff;text-decoration:none}.c-btn.is-focused,.c-btn:focus:focus{box-shadow:0 0 0 3px rgba(31,115,183,.35);outline:none}.c-btn.is-active.is-active,.c-btn:active:active{background-color:#144a75;border-color:transparent;color:#fff;text-decoration:none;transition:border-color .1s ease-in-out,background-color .1s ease-in-out,color .1s ease-in-out}.u-fine-print-on-white{color:#2d5e64;font-size:.785rem}.u-centered{text-align:center}</style>
  <meta name="viewport" content="width=device-width">
</head>

<body>
  
  <article class="l-max-readable-width l-centered">

    <h1 class="err__page-heading">
      Complete the security check to access this page
    </h1>

    <div class="err__container l-padded-bottom">
      <div class="l-top-padded err__details-content">
        <form class="challenge-form" id="challenge-form" action="/hc/en-us/articles/205893708-What-is-the-minimum-order-size-?__cf_chl_captcha_tk__=ce03d25660ac1a1261d563168d0f43bbbdd19987-1588761177-0-Ae-B-BaCa021ZytrTipHlCk7X1JUVoTQpx_dWcv0-GwMcixNRPyov9I-eQIuK-R0TbDVX5pfNth0t7bozqTElNF-Gt-aFWynR5QT8uorLkmUWKDO6bIyeS3uA9hUSJJbN5cWuLTLZa4thgJI4OyTWV7Rabdkjl3nT9HQgOxfnTCB5dI6t88cDjqIiEaOHzv57l-z_En5qgVazsLHpKsM0rZuXumszWgxA6NpC1YW7wuwnkOeoZBACBfCi8azGPQwKRnHREiv_6krRfBgZxWt3icXCyvRgVbcYAgxlT3zD3pmWMlu87KcJLLkZmzx_hWCs35aZOoCwPVx4HcBdilJGISl0UKgoEcDW9jYQZhVwGxUGcr3XH-xLO38BW5q5Dh1OQHhs_i-EANOCEBaN92n1GvlWp9SLkPCf35BIajLf_6x0oKMuKIcY5Sv9hB6JFcj8_-M5KqLzFmKv_2HQ4WUdCDNZ4p2K-Nn1WEVIVvn8lQDS2LdNga8iRTV4XNTskAlG_VoMh3eN-LbFow54wHUFln3kSTY8BwCJE5szA7I7fuMHaETSL91a_IQWooocfHJioUuYttOwVB4wt40KzExN8uZbQnWRNa8hOS-Vlfzd-d3xkfxyVQQ3FhJ_3hCOHV45Q" method="POST" enctype="application/x-www-form-urlencoded">
  <input type="hidden" name="r" value="971cefdb1fce49c5840907b25010539db3e1dcb9-1588761177-0-ASB7r+j+d4yJ3MUEM2wAEeZkke7T/LJN5LkqUv2tz5xVtuD19+sIIIn/4zTh1XgekAu/WMGClKZE2ChhjXyz75mRsWRgVL4DLwfKUmPgeGmW6Ewrhyy8YK72hb442pLLJ/7kdeviY13i+d+UEO2KGBw6z7TwWi01AtQMXarx4iTs6DPARYoFwTdkt4PNWwHnD6d/aiHF6DA5WU/hwS3j7L1N/AcmBUzEek30y1IMAFmvbile32tHwZGOalthbcl1YWhTG0cNAlrvLvKPHNukyBL713VV50Csdz4Foigc8G9eQ8Y3rwP+ppC80L9Ffb52DyqY9gajx1Gz01E6YXzHtd6RNxqNMpyg10kAtgYrXs4F/ecMj6DVURpDSbONwttnOv/ROsxI3SkCuLX4idrAa5XqTFsnatnAWl0n0JoMDh8en7BLv6g3pKzauv3B4XuLivhNvM8EbpCNgIMzjCwTWCKecKPkYwYJDNzh3LRN3ww9kF9NhD9U7PIYJEaN8htUS2XIMKLKZWAPU/ZWJP3ngZVsPxBimdiohfrOX3iDDsGrbP0Rj37YQmXwgEXAUJx9igT+v3Ty0McXNWEuwSkCbGfHNTO+ieuEi3ugX7QpFFAjRRc3ZeSJpx6E4EQPjsvZMrApfJPm/H+kNRCAEB2TNZtKnA3EnHUVjBNmRFznIdXAkRgfPtG3nFQRCKI0G2gem4n9VrR1qb8eDvC7J5jn6uasZvT7SwFXOgiLyzzR/1PboVobxtNMx3Td2KRJPIivO+d+jFT5LkmQeHVReMVf5NjGR230X8iryk3q2nYyJ7+w/GVyTjdt/gYS+4ET38HstCST/W3CX7asZxBfZX8Nc/jP6h40Bn4dvrFR++dk1IX/c1W3ItGtXW+U99VXB7uWLItNPP8QtGLve++1+3GNDIlF7MvbUwx1nTPNBTNTQfPQN8J5OkZH6OI3OiMHkdQcLNJBVs5ksJVLY5NjKH4/TyJTx7lsYmv907NkSqbmnpk+zLLvh+/uuwnK4gwVgM3lt7tF4TqbwkcyIru63r1Hv+Y8Sw2MmHux/UT12yuucddzkQdXm7z0EFeaT91H1zIHUiQUkD1GR0FSG+6DSYQJZ0UgjcT864sjOvoRsXHgmrhOUAjlUDz2Tc/4+us70l2HrPgGImAOkR3MD2TxawyjLzEON4eiNRsIOpK+ctZdCJYI">
  <input type="hidden" name="cf_captcha_kind" value="h">
  <script type="text/javascript" src="/cdn-cgi/scripts/hcaptcha.challenge.js" data-type="normal"  data-ray="58f20a521f3ff48a" async data-sitekey="33f96e6a-38cd-421b-bb68-7806e1764460"></script>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
  <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=58f20a521f3ff48a')"></div>
</form>

        <hr>
      </div>
      <p>
        Completing a CAPTCHA proves you are a human and gives you temporary access to this page.
        <br>
        Make sure your home and work devices are regularly scanned for malware to reduce the need to complete the CAPTCHA.
        <hr>
        RayID: 58f20a521f3ff48a
        <br>
        IP: 102.177.152.55
      </p>
    </div>

    <div class="l-v-padded">
      <div lang="pt-br" class="err__additional-translation">
        <h3>
          Conclua essa verificação de segurança para acessar essa página
        </h3>
        <p class="l-top-padded">
          Completar o CAPTCHA comprova que você é humano e fornece acesso temporário à página. Verifique regularmente seus dispositivos domésticos e comerciais quanto a infecções de malware para reduzir a necessidade de conclusão do CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="es-419" class="err__additional-translation">
        <h3>
          Complete la verificación de seguridad para tener acceso a esta página
        </h3>
        <p class="l-top-padded">
          La verificación CAPTCHA se encarga de comprobar que usted es un ser humano, y le da acceso temporal a esta página. Asegúrese de analizar regularmente sus dispositivos personales y de trabajo en busca de malware para reducir la necesidad de una verificación CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="de" class="err__additional-translation">
        <h3>
          Sicherheitsprüfung zum Zugriff auf diese Seite erforderlich
        </h3>
        <p class="l-top-padded">
          Die CAPTCHA-Prüfung beweist, dass es sich bei Ihnen um einen echten Menschen handelt, und gibt Ihnen vorübergehend Zugriff auf diese Seite. Achten Sie darauf, dass Ihre Geräte zuhause und im Büro regelmäßig auf Malware geprüft werden, damit CAPTCHA nur in Ausnahmefällen erforderlich ist.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="fr" class="err__additional-translation">
        <h3>
          Veuillez effectuer la vérification de sécurité pour accéder à cette page
        </h3>
        <p class="l-top-padded">
          Une vérification CAPTCHA nous permet de nous assurer que vous êtes une personne réelle afin de vous donner un accès temporaire à cette page. Vérifiez régulièrement l’absence de logiciels malveillants sur vos appareils personnels et professionnels pour réduire la nécessité d’effectuer une vérification CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="nl" class="err__additional-translation">
        <h3>
          Voltooi de beveiligingscontrole om toegang tot deze pagina te krijgen
        </h3>
        <p class="l-top-padded">
          Door een CAPTCHA in te vullen, bewijst u dat u een mens bent en krijgt u tijdelijk toegang tot deze pagina. Zorg ervoor dat uw apparaten voor persoonlijk en zakelijk gebruik regelmatig worden gescand op malware. Zo wordt het invullen van een CAPTCHA minder noodzakelijk.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="ru" class="err__additional-translation">
        <h3>
          Для доступа к этой странице необходимо пройти проверку безопасности
        </h3>
        <p class="l-top-padded">
          Успешное прохождение теста CAPTCHA доказывает, что вы человек, и дает вам временный доступ к этой странице. Чтобы не проходить тест CAPTCHA слишком часто, регулярно проверяйте свои устройства дома и на работе на отсутствие вредоносных программ.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="ja" class="err__additional-translation">
        <h3>
          このページにアクセスするには、セキュリティチェックを完了してください
        </h3>
        <p class="l-top-padded">
          CAPTCHAを正しく入力すると人間による入力であることが証明され、このページへの一時的なアクセスが提供されます。CAPTCHAを入力する必要性を減らすには、マルウェアが存在しないか自宅と職場の機器を定期的にスキャンするようにしてください。
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="it" class="err__additional-translation">
        <h3>
          Completa il controllo di sicurezza per accedere a questa pagina
        </h3>
        <p class="l-top-padded">
          Il superamento del test CAPTCHA dimostra che sei un essere umano e ti concede l’accesso temporaneo a questa pagina. Assicurati di sottoporre a scansione i dispositivi che usi a casa e al lavoro per escludere la presenza di malware e ridurre la necessità di eseguire il test CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="ar" class="err__additional-translation">
        <h3 dir="rtl">
          أكمل الفحص الأمني للوصول إلى هذه الصفحة
        </h3>
        <p class="l-top-padded" dir="rtl">
          يثبت إكمال اختبار CAPTCHA أنك إنسان ويمنحك وصولاً مؤقتًا لهذه الصفحة. تأكد من إجراء مسح دوري على أجهزة منزلك وعملك لاستكشاف البرامج المضرة لتقليل الحاجة إلى إكمال اختبار   CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="zh-cn" class="err__additional-translation">
        <h3>
          完成安全检查以访问此页面
        </h3>
        <p class="l-top-padded">
          完成 CAPTCHA 可证明您是真人，将为您提供对此页面的临时访问权限。请确保您的家庭和工作设备定期进行恶意软件扫描，以降低需要完成 CAPTCHA 的频率。
        </p>
      </div>
    </div>
  </article>
</body>
</html>

```
I know this issue lies with the Kraken API.
Any suggestions? 

Love the work done on ccxt btw ;)

**Comment by kroitor** [comment]
Hi!

> https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

This URL is from an old version of the lib.

I suggest to first make sure that you have the most recent version of CCXT in runtime:

```Python
import ccxt
exchange_id = "kraken"
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': '#',
    'secret': '#,
    'timeout': 30000,
    'enableRateLimit': True,
    'options':{
        'fetchMinOrderAmounts': False
    }
})
print('CCXT Version:', ccxt.__version__)  # ←----------- ADD THIS
print(exchange.fetch_order_book("BTC"))
```

Let us know if your runtime version is up to date and you're still having the same problem. 

If your version is outdated, you need to update it on your system properly, but that depends on how you install it and your system as well.

**Comment by kroitor** [comment]
@deon4e feel free to reopen it or just ask further questions if any.
