### ISSUE TITLE
exchange.proxies & exchange.agent don't work

### ISSUE THREAD

**Issue by mortezae** [ccxt/ccxt#6989]
- OS: Linux 64
- Programming Language version: Node.js v12.14.1
- CCXT version: 1.28.13

```javascript
const ccxt       = require('ccxt')
const proxyAgent = require('socks-proxy-agent')

const ip_port = '127.0.0.1:1080'
const agent   = new proxyAgent(`socks://${ip_port}`)

const exchangeOptions = {
  agent,
  /* proxies: {
    http:  `socks5://${ip_port}`,
    https: `socks5://${ip_port}`
  },*/
  apiKey: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
  secret: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
}

void async function () {
  try {
    exchange = new ccxt['binance'](exchangeOptions)
    await exchange.loadMarkets()
    console.log('* Markets loaded')
  } catch(err) { console.log(err) }
} ()

```
```
ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo  The "options.agent" property must be one of type Agent-like Object, undefined, or false. Received type object
    at /home/morteza/node/futures/node_modules/ccxt/js/base/Exchange.js:403:35
    at async timeout (/home/morteza/node/futures/node_modules/ccxt/js/base/functions/time.js:183:24) {
  constructor: [Function: ExchangeNotAvailable],
  name: 'ExchangeNotAvailable'
}
```
I don't know whats wrong with my agent.
Then I uncommented `proxies` option -as an alternative- and tested it rather `agent`, but it seems has no effect, as script runs successfully and prints `* Markets loaded` even if nothing runs on port 1080.

**Comment by kroitor** [comment]
> I don't know whats wrong with my agent.

This question is not about CCXT, though.
Node.js requires the agent to be `Agent-like object`.
However, `socks-proxy-agent` is returning an agent of type `object` which differs from the Agent type.

You want that object to be Agent-like, this is an issue with the 3rd-party `socks-proxy-agent`.

Here's how to verify:

```JavaScript
const ccxt       = require('ccxt')
const proxyAgent = require('socks-proxy-agent')
const https = require ('https')

const ip_port = '127.0.0.1:1080'
const agent   = new proxyAgent(`socks://${ip_port}`)
const httpsAgent = new https.Agent ()
console.log (agent)
console.log (httpsAgent)
```

**Comment by kroitor** [comment]
This will work:

```
npm i @luminati-io/socksv5
```

```JavaScript
const ccxt = require('./ccxt')
const socks = require('@luminati-io/socksv5')

const agent = new socks.HttpsAgent ({
    proxyHost: '127.0.0.1',
    proxyPort: 1080,
    auths: [ socks.auth.None () ]
})

const exchangeOptions = {
  agent,
  apiKey: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
  secret: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
}

void async function () {
  try {
    exchange = new ccxt['binance'](exchangeOptions)
    await exchange.loadMarkets()
    console.log('* Markets loaded')
  } catch(err) { console.log(err) }
} ()
```

Let us know if that does not answer your question.

**Comment by HartS** [comment]
For anyone discovering this issue now, the `socks-proxy-agent` package now referenced by @mortezae does work with ccxt now

**Comment by YuecanFan** [comment]
can you provide an example use socks-proxy-agent package to set up proxy?

**Comment by HartS** [comment]
@YuecanFan I basically did this:

```
import { SocksProxyAgent } from 'socks-proxy-agent';

const binanceClient = new ccxt.binance({
  agent: new SocksProxyAgent(`socks://${HOST}:${PORT}`)
});
```
