### ISSUE TITLE
How do I handle OSError("(10054, 'WSAECONNRESET')

### ISSUE THREAD

**Issue by heyjae41** [ccxt/ccxt#7081]
Hi, 
I needs current price value to decide order or not 
whenever run code failed with OSError("(10054, 'WSAECONNRESET')
for some time, it works fine but finally failed with 10054 network error

I just wonder I can change socket option(ex, SO_LINGER) 
If not, could check below code. 
I added try except code to reconnect after 60seconds. 

additionally consider watchdog for watching the process and restarting 

Thansk ahead.

- OS: Windows10 64bit
- Programming Language version:Python 3.7.6 32bit
- CCXT version:1.28.11

``` error code 
while True:
    cols = ['date','open','high','low','close','volume']
    ohlcvs = exchange.fetch_ohlcv(symbol,'15m',limit=1) #get current price, so limit 1
    for ohlc in ohlcvs:
          ohlc[0] = datetime.datetime.fromtimestamp(ohlc[0]/1000).strftime('%Y%m%d%H%M')
          df = pd.DataFrame(ohlcvs, columns=cols)
          return df
    time.sleep (exchange.rateLimit / 1000) # time.sleep wants seconds
```

``` error message
Traceback (most recent call last):
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Z\anaconda3\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Users\Z\anaconda3\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Z\anaconda3\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Z\anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 328, in recv_into
    return self.recv_into(*args, **kwargs)
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
OSError: (10054, 'WSAECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Z\anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Z\anaconda3\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "C:\Users\Z\anaconda3\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Z\anaconda3\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Z\anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 328, in recv_into
    return self.recv_into(*args, **kwargs)
  File "C:\Users\Z\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Z\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 548, in fetch
    verify=self.verify
  File "C:\Users\Z\anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Z\anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Z\anaconda3\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "grid.py", line 305, in <module>
    main()
  File "C:\Users\Z\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Z\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\Z\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Z\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "grid.py", line 221, in main
    ohlcv = get_ohlcv(symbol, exchange)
  File "grid.py", line 298, in get_ohlcv
    ohlcvs = exchange.fetch_ohlcv(symbol,'15m',limit=1) #get current price, so limit 1
  File "C:\Users\Z\anaconda3\lib\site-packages\ccxt\binance.py", line 770, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\Z\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 449, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Z\anaconda3\lib\site-packages\ccxt\binance.py", line 1869, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Z\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 468, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Z\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 584, in fetch
    raise NetworkError(method + ' ' + url + ' ' + error_string)
ccxt.base.errors.NetworkError: GET https://fapi.binance.com/fapi/v1/klines?symbol=BTCUSDT&interval=15m&limit=1 ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))
```

**Comment by kroitor** [comment]
Hi!

In general, that error means that the exchange has closed the HTTPS / REST connection.

- https://www.google.com/search?q=binance+WSAECONNRESET

Handling it should be done with a `try/except` clause for `ccxt.NetworkError` as explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

If you can paste the code you use to initialize the exchange (without your keys, of course), that might shed some light on the cause of the trouble:

```Python

# ↑↑↑↑↑↑↑↑↑↑↑ WHAT IS HERE?

while True:
    cols = ['date','open','high','low','close','volume']
    ohlcvs = exchange.fetch_ohlcv(symbol,'15m',limit=1) #get current price, so limit 1
    for ohlc in ohlcvs:
          ohlc[0] = datetime.datetime.fromtimestamp(ohlc[0]/1000).strftime('%Y%m%d%H%M')
          df = pd.DataFrame(ohlcvs, columns=cols)
          return df
    time.sleep (exchange.rateLimit / 1000) # time.sleep wants seconds

# ↓↓↓↓↓↓↓↓↓↓↓ WHAT IS HERE?
```

↑ Please, make it as short as possible, remove everything irrelevant from it, until you're left with the smallest piece of code that reproduces the issue.

Also, please provide info on the following questions:

1. Do you use proxies?
2. Does it succeed when you retry after a failure?

**Comment by heyjae41** [comment]
Handled it with a try/except clause for ccxt.NetworkError as explained above.
Thansk.
