### ISSUE TITLE
[braziliex] TypeError: argument of type 'EmptyStreamReader' is not iterable

### ISSUE THREAD

**Issue by Herklos** [ccxt/ccxt#7162]
- OS: Windows
- Programming Language version: python3.7
- CCXT version: 1.30.2

```
- Install [OctoBot v4 alpha version](https://github.com/Drakkar-Software/OctoBot/wiki/OctoBot-0.4)
- Configure it to use braziliex exchange
```

```
Traceback (most recent call last):
  File "octobot_trading\producers\recent_trade_updater.py", line 66, in octobot_trading.producers.recent_trade_updater.RecentTradeUpdater.start_update_loop
  File "octobot_trading\exchanges\rest_exchange.py", line 182, in octobot_trading.exchanges.rest_exchange.RestExchange.get_recent_trades
  File "C:\Program Files\Python37\lib\site-packages\ccxt\async_support\braziliex.py", line 387, in fetch_trades
    response = await self.publicGetTradehistoryMarket(self.extend(request, params))
  File "C:\Program Files\Python37\lib\site-packages\ccxt\async_support\braziliex.py", line 580, in request
    if 'success' in response:
TypeError: argument of type 'EmptyStreamReader' is not iterable
```
Hello,
A user of my project OctoBot got an issue with ccxt on braziliex. Do you have an idea of how to fix it in ccxt ?
Thanks !

**Comment by kroitor** [comment]
Hi!

Can you please paste the code to reproduce it and your verbose request/response, precisely as described here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

&#096;&#096;&#096;Python
# YOUR SHORT CODE SNIPPET, INCLUDING INSTANTIATION
&#096;&#096;&#096;

&#096;&#096;&#096;
# YOUR VERBOSE OUTPUT
&#096;&#096;&#096;

**Comment by Herklos** [comment]
Hi @kroitor ! Thanks for your reply.

```
from ccxt import braziliex
e = braziliex()
e.load_markets()
e.verbose = True
r = e.fetch_trades("ETH/USDT")
Request: GET https://braziliex.com/api/v1/public/tradehistory/eth_usdt {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None
Response: GET https://braziliex.com/api/v1/public/tradehistory/eth_usdt 200 {'Date': 'Sat, 20 Jun 2020 12:59:55 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d109d679f5535d03174236e247b3b09681592657994; expires=Mon, 20-Jul-20 12:59:54 GMT; path=/; domain=.braziliex.com; HttpOnly; SameSite=Lax, connect.sid=s%3Awc8qt3kvEdbd9k3CTssyQqeAGazExJV9.W3ANSQk0bY4kKA2AUw69a7CtZvifb%2BPey%2FaN%2B1sWXDY; Path=/; HttpOnly', 'X-Powered-By': 'Express', 'Expires': 'Sat, 20 Jun 2020 13:03:55 GMT', 'Cache-Control': 'max-age=240, public, s-maxage=240', 'Access-Control-Allow-Origin': '*', 'X-Proxy-Cache': 'EXPIRED', 'CF-Cache-Status': 'BYPASS', 'Accept-Ranges': 'bytes', 'cf-request-id': '0373697c660000cd9ffeb60200000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '5a65ab73daa8cd9f-CDG'} 
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/dev/DrakkarSoftware/OctoBot-Backtesting/venv/lib/python3.7/site-packages/ccxt/braziliex.py", line 387, in fetch_trades
    response = self.publicGetTradehistoryMarket(self.extend(request, params))
  File "/home/user/dev/DrakkarSoftware/OctoBot-Backtesting/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 435, in inner
    return entry(_self, **inner_kwargs)
  File "/home/user/dev/DrakkarSoftware/OctoBot-Backtesting/venv/lib/python3.7/site-packages/ccxt/braziliex.py", line 577, in request
    raise ExchangeError(self.id + ' returned empty response')
ccxt.base.errors.ExchangeError: braziliex returned empty response
```

**Comment by kroitor** [comment]
@Herklos 

```Python
from ccxt import braziliex
exchange = braziliex({
   'enableRateLimit': True,  # required by the Manual
})
exchange.load_markets()
symbol = 'ETH/USDT'
m = exchange.market(symbol)
print(exchange.id, symbol, 'market active status is:', m['active'])
```

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

![Screen-Shot-2020-06-20-at-16 11 20](https://user-images.githubusercontent.com/1294454/85202687-d3a6e400-b310-11ea-857d-253628baa2d8.jpg)

Why it is inactive – you should probably ask Braziliex.
Let us know if the above does not answer your question.

**Comment by Herklos** [comment]
Thanks @kroitor ! Didn't notice this attribute before
