### ISSUE TITLE
It is recommended to add USDT perpetual order operation for bybit exchange.

### ISSUE THREAD

**Issue by xkyykx** [ccxt/ccxt#7172]
The bybit exchange has entered into a usdt perpetual contract in March 2020, but today I failed to try to place an order for BTCUSDT on this exchange.
Order code:

```
import ccxt

bybit = ccxt.bybit({
    'enableRateLimit': True,
    'options': {
        'adjustForTimeDifference': True,
    },
    'apiKey': '***',
    'secret': '***',
    'urls': {
        'api': 'https://api.bybit-cn.com',
    }
})
symbol = 'BTC/USDT'
order = bybit.create_limit_sell_order(symbol, 1, 9500)
```
The code fails to execute, and the returned information is as follows:
```
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/demo1/program/mybybit.py", line 17, in <module>
    order = bybit.create_limit_sell_order(symbol, 1, 9500)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 1795, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\ccxt\bybit.py", line 1205, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 462, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 485, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 603, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\ccxt\bybit.py", line 2013, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bybit {"ret_code":10001,"ret_msg":"Param validation for 'close_on_trigger' failed on the 'exists' tag","ext_code":"","ext_info":"","result":null,"time_now":"1592816952.772152","rate_limit_status":99,"rate_limit_reset_ms":1592816952769,"rate_limit":100}
```
Please tell me how to place BTC/USDT order on this exchange, thank you!

**Comment by kroitor** [comment]
Hi!

First of all, please do not duplicate issues, we can see your question here: 

- https://github.com/ccxt/ccxt/issues/7164#issuecomment-647334574

Secondly, please, always read the error carefully and try to understand it.

The exchange says:

```
"ret_msg":"Param validation for 'close_on_trigger' failed on the 'exists' tag"
```

That error is explained by the ByBit exchange here: https://help.bybit.com/hc/en-us/articles/900000065323-The-reason-why-conditional-orders-are-triggered-but-not-successfully-executed

If that does not answer your question, I'd recommend to reach out to the ByBit support for an explanation. 

Let us know if that does not help.
