### ISSUE TITLE
wavesexchange fetch_open_order broken.

### ISSUE THREAD

**Issue by blaaaaaaa** [ccxt/ccxt#7194]
python3.8 win10 ccxt-1.30.47

at least fetch open orders broken, maybe more.

Traceback (most recent call last):
  File "C:/Users/admin/IdeaProjects/py/ccxt_trading_bot/ccxt_wavesexchange_maker_bot.py", line 191, in <module>
    main()
  File "C:/Users/admin/IdeaProjects/py/ccxt_trading_bot/ccxt_wavesexchange_maker_bot.py", line 180, in main
    a = wavesexchange_maker_bot.mkr_ex.fetch_open_orders("ZEC/ETH")
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\wavesexchange.py", line 980, in fetch_open_orders
    return self.parse_orders(response, market, since, limit)
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\base\exchange.py", line 1676, in parse_orders
    array = [self.extend(self.parse_order(order, market), params) for order in array]
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\base\exchange.py", line 1676, in <listcomp>
    array = [self.extend(self.parse_order(order, market), params) for order in array]
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\wavesexchange.py", line 1047, in parse_order
    amount = self.currency_from_precision(amountCurrency, amount)
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\wavesexchange.py", line 774, in currency_from_precision
    return self.from_wei(amount, self.currencies[currency]['precision'])
KeyError: 'F81SDFZBZR5CE8JARRWLPJEDG1V8YT257OHBCHK75YCP'

self.currencies has these keys: dict_keys(['BCH', 'BSV', 'BTC', 'DASH', 'ETH', 'LTC', 'TN', 'USDN', 'USDT', 'WAVES', 'WEST', 'XMR', 'ZEC'])

so somewhere goes something wrong with the asset id from waves and ccxt symbol for it.

**Comment by kroitor** [comment]
@blaaaaaaa we will investigate and fix asap, thx for your feedback!

**Comment by frosty00** [comment]
hi, it is working on my end. Are you sure that your secret is your privateKey and the apiKey is your publicKey

**Comment by blaaaaaaa** [comment]
Hi, open orders worked now, but I get error for an order:

Request: POST http://matcher.waves.exchange/matcher/orderbook {'content-type': 'application/json', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} {"senderPublicKey":"xxx","matcherPublicKey":"xxx","assetPair":{"amountAsset":"","priceAsset":"8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS"},"orderType":"buy","price":10000,"amount":200000000,"timestamp":1593453692242,"expiration":1595872892242,"matcherFee":56,"matcherFeeAssetId":"WAVES","signature":"xxx","version":3}
Traceback (most recent call last):
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\base\exchange.py", line 581, in fetch
    response.raise_for_status()
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://matcher.waves.exchange/matcher/orderbook

During handling of the above exception, another exception occurred:

mkr_ex.create_order("WAVES/BTC","limit","buy",2,0.000110000)

Traceback (most recent call last):
  File "C:/Users/admin/IdeaProjects/py/ccxt_trading_bot/ccxt_wavesexchange_maker_bot.py", line 195, in <module>
    main()
  File "C:/Users/admin/IdeaProjects/py/ccxt_trading_bot/ccxt_wavesexchange_maker_bot.py", line 182, in main
    b = wavesexchange_maker_bot.mkr_ex.create_order("WAVES/BTC","limit","buy",2,0.00010000)
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\wavesexchange.py", line 854, in create_order
    response = self.matcherPostMatcherOrderbook(body)
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\base\exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\base\exchange.py", line 486, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\base\exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\base\exchange.py", line 593, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\wavesexchange.py", line 1318, in handle_errors
    raise Exception(self.id + ' ' + message)
ccxt.base.errors.InvalidOrder: wavesexchange Required one of the following fee asset: 474jTeYx2r2Va35794tCScAXWJG9hU2HcgxzMowaZUnu, 8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS, WAVES, BrjUWjndUanm5VsJkbUip8VRYy6LWJePtxya3FNv4TQa, 34N9YcEETLWn93qYQ64EsP1x89tSruJU44RrEMSXXEPJ, HZk1mbfuJpmxU1Fs4AX5MWLVYtctsNcg6e2C6VKqK8zk, 62LyMjcr2DtiyF5yVXFhoQ2q414VPPJXjsNYp72SuDCH, 4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8, B3uGHFRpSUuGEDWjqB9LWWxafQj8VTvpMucEyoxzws5H, 5WvPKSJXzVE2orvbkJ8wsQmmQKqTv9sGBPksV4adViw3, DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p, zMFqXuoyrn5w17PFurTqxB7GsS71fp9dfk6XFwxbPCy. But given "WAVES" as Base58 string. Remove this field if you want to specify WAVES in JSON


so I think error comes from matcherFeeAssetId":"WAVES" which we use WAVES string, but it should be base58 asset id of waves.

**Comment by frosty00** [comment]
yep ive fixed it now

**Comment by kroitor** [comment]
Thanks @frosty00 !

@blaaaaaaa will merge https://github.com/ccxt/ccxt/pull/7200 in a sec.
