### ISSUE TITLE
[Kucoin] How to create limit order

### ISSUE THREAD

**Issue by Ravisut** [ccxt/ccxt#7199]
Code
```
def createOrder(symbol,side,amount,price):
    symbol = 'BNB/USDT'
    type = 'limit'  # or 'market'
    side = 'sell'  # or 'buy'
    amount = 0.001
    price = 18.00  # or None #

    # extra params and overrides if needed
    params = {
        'test': True,  
        'recvWindow': 10000
    }
    order = exchange.create_order(symbol, type, side, amount ,price , params)
    return order
```
Error

```
E:\PycharmProjects\TradingTutorial\venv\Scripts\python.exe E:/PycharmProjects/TradingTutorial/Code/TestFuntion.py
Traceback (most recent call last):
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 580, in fetch
    response.raise_for_status()
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://openapi-v2.kucoin.com/api/v1/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/PycharmProjects/TradingTutorial/Code/TestFuntion.py", line 27, in <module>
    infooder = callFuntion.re('BNB/USDT', 'sell', 0.001, 18.00)
  File "E:\PycharmProjects\TradingTutorial\Code\callFuntion.py", line 165, in re
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\kucoin.py", line 787, in create_order
    response = self.privatePostOrders(self.extend(request, params))
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 462, in inner
    return entry(_self, **inner_kwargs)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 485, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\kucoin.py", line 1702, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, message)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 499, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: Access denied, require more permission.

Process finished with exit code 1
```

**Comment by kroitor** [comment]
> ccxt.base.errors.AuthenticationError: Access denied, require more permission.

↑ Do you have a question on this message?

**Comment by kroitor** [comment]
```Python
import ccxt
from pprint import pprint

exchange = ccxt.kucoin({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_API_PASSWORD'
})

symbol = 'BNB/USDT'
type = 'limit'  # or 'market'
side = 'sell'  # or 'buy'
amount = 0.001
price = 18.00  # or None

order = exchange.create_order(symbol, type, side, amount, price, params)
pprint(order)
```

Let us know if the above does not answer your question.

**Comment by Ravisut** [comment]
```
import ccxt

exchange = ccxt.kucoin({
    'apiKey': '**********',
    'secret': '**********',
    'password': '******',
    'enableRateLimit': True,
})

symbol = 'BNB/USDT'
type = 'limit'  # or 'market'
side = 'sell'  # or 'buy'
amount = 0.001
price = 18.00  # or None

params = {
    'test': True,  
    'recvWindow': 10000
}

order = exchange.create_order(symbol, type, side, amount, price, params)
print(order)
```

Error
```
E:\PycharmProjects\TradingTutorial\venv\Scripts\python.exe E:/PycharmProjects/TradingTutorial/Code/Test4.py
Traceback (most recent call last):
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 580, in fetch
    response.raise_for_status()
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://openapi-v2.kucoin.com/api/v1/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/PycharmProjects/TradingTutorial/Code/Test4.py", line 24, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\kucoin.py", line 787, in create_order
    response = self.privatePostOrders(self.extend(request, params))
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 462, in inner
    return entry(_self, **inner_kwargs)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 485, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\kucoin.py", line 1702, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, message)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 499, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: Access denied, require more permission.

Process finished with exit code 1
```

**Comment by Ravisut** [comment]
hahaha am so stupid Now out put done No error 
just setting API
Permission: General ☑️ Trade☑️
