### ISSUE TITLE
[Deribit] AuthenticationError

### ISSUE THREAD

**Issue by Ravisut** [ccxt/ccxt#7238]
i try to test api with https://test.deribit.com/ 

![1](https://user-images.githubusercontent.com/33305346/86851584-6d2a1000-c0dd-11ea-8830-711b7b8ab22a.png)

```
import ccxt

exchange = ccxt.deribit({
    'apiKey': 'JNxdbf37',
    'secret': 'Wp3cWsqgdLcFa-t5rr2aH-yon4AulOGTaDneVtzLJfM',
    'enableRateLimit': True,
})

print(exchange.fetch_balance())
```

Error

```
E:\PycharmProjects\TradingTutorial\venv\Scripts\python.exe E:/PycharmProjects/TradingTutorial/Code/Futures/Test.py
Traceback (most recent call last):
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 581, in fetch
    response.raise_for_status()
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.deribit.com/api/v2/private/get_account_summary?currency=BTC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/PycharmProjects/TradingTutorial/Code/Futures/Test.py", line 9, in <module>
    print(exchange.fetch_balance())
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\deribit.py", line 488, in fetch_balance
    response = self.privateGetGetAccountSummary(self.extend(request, params))
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 486, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 593, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\deribit.py", line 1638, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, errorCode, feedback)
  File "E:\PycharmProjects\TradingTutorial\venv\lib\site-packages\ccxt\base\exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: deribit {"jsonrpc":"2.0","error":{"message":"invalid_credentials","code":13004},"testnet":false,"usIn":1594160982506813,"usOut":1594160982506828,"usDiff":15}

Process finished with exit code 1
```

**Comment by kroitor** [comment]
You have to switch to the deribit sandbox/testnet to work with testnet API keys. 
If you don't switch to the sandbox/testnet, then it will simply attempt to access the production API with your testkeys which obviously wouldn't work...

```Python
import ccxt

exchange = ccxt.deribit({
    'apiKey': 'JNxdbf37',
    'secret': 'Wp3cWsqgdLcFa-t5rr2aH-yon4AulOGTaDneVtzLJfM',
    'enableRateLimit': True,
})

exchange.set_sandbox_mode(True)  # ←------------------ ADD THIS

print(exchange.fetch_balance())
```

Let us know if that does not answer your question.
