### ISSUE TITLE
cant Create order on BYBIT

### ISSUE THREAD

**Issue by liuyynn** [ccxt/ccxt#7285]
hi, 
I'm experiencing this issue with creating order request to bybit testnet. this problem starts recently， before that the code works fine.

code:

BybitAPI.create_market_buy_order('BTC/USD',1 )
```

output:

Traceback (most recent call last):
  File "C:/Users/yuliu/PycharmProjects/tradingbot testnet/settings.py", line 11, in <module>
    BybitAPI.create_market_buy_order('BTC/USD',1 )
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 1802, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\bybit.py", line 1205, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 486, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 604, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\bybit.py", line 2013, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bybit {"ret_code":10001,"ret_msg":"bind error:json: cannot unmarshal string into Go struct field CreateOrderReq.qty of type int64","ext_code":"","ext_info":"","result":null,"time_now":"1594901977.525607","rate_limit_status":98,"rate_limit_reset_ms":1594901977524,"rate_limit":100}

**Comment by kroitor** [comment]
@liuyynn can you please paste your verbose output as explained in the FAQ here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
BybitAPI.load_markets()
BybitAPI.verbose = True
BybitAPI.create_market_buy_order('BTC/USD',1 )
```
?

**Comment by liuyynn** [comment]
@kroitor 

Request: POST https://api.bybit.com/v2/private/order/create {'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate'} {"side":"Buy","symbol":"BTCUSD","order_type":"Market","qty":"1","time_in_force":"GoodTillCancel","api_key":"iktpBj27eLba1De0Je","recv_window":5000,"timestamp":1594905620192,"sign":"874953b594e4cbb1f3cb2586df181271435c33393a02632bbeb298f6a48f6f1b"}
Traceback (most recent call last):
  File "C:/Users/yuliu/PycharmProjects/tradingbot testnet/settings.py", line 11, in <module>
    BybitAPI.create_market_buy_order('BTC/USD',1 )
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 1802, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\bybit.py", line 1205, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 486, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 604, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\bybit.py", line 2013, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bybit {"ret_code":10003,"ret_msg":"invalid api_key","ext_code":"","ext_info":"","result":null,"time_now":"1594905620.097809"}

Response: POST https://api.bybit.com/v2/private/order/create 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '119', 'Expires': 'Thu, 16 Jul 2020 13:20:20 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 16 Jul 2020 13:20:20 GMT', 'Connection': 'keep-alive'} {"ret_code":10003,"ret_msg":"invalid api_key","ext_code":"","ext_info":"","result":null,"time_now":"1594905620.097809"}

Process finished with exit code 1

**Comment by liuyynn** [comment]
im using windows10 and python3.8 with ccxt1.31.40

**Comment by liuyynn** [comment]
@kroitor 


Request: POST https://api-testnet.bybit.com/v2/private/order/create {'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate'} {"side":"Buy","symbol":"BTCUSD","order_type":"Market","qty":"1","time_in_force":"GoodTillCancel","api_key":"iktpBj27eLba1De0Je","recv_window":5000,"timestamp":1594906104401,"sign":"8beed97758bb4d380b436437380c2c804093ba8bb5dc741bbd82182b49200990"}

Response: POST https://api-testnet.bybit.com/v2/private/order/create 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '274', 'Expires': 'Thu, 16 Jul 2020 13:28:24 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 16 Jul 2020 13:28:24 GMT', 'Connection': 'keep-alive'} {"ret_code":10001,"ret_msg":"bind error:json: cannot unmarshal string into Go struct field CreateOrderReq.qty of type int64","ext_code":"","ext_info":"","result":null,"time_now":"1594906104.211156","rate_limit_status":97,"rate_limit_reset_ms":1594906104209,"rate_limit":100}
Traceback (most recent call last):
  File "C:/Users/yuliu/PycharmProjects/tradingbot testnet/settings.py", line 12, in <module>
    BybitAPI.create_market_buy_order('BTC/USD',1 )
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 1802, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\bybit.py", line 1205, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 486, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\base\exchange.py", line 604, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\yuliu\AppData\Roaming\Python\Python38\site-packages\ccxt\bybit.py", line 2013, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bybit {"ret_code":10001,"ret_msg":"bind error:json: cannot unmarshal string into Go struct field CreateOrderReq.qty of type int64","ext_code":"","ext_info":"","result":null,"time_now":"1594906104.211156","rate_limit_status":97,"rate_limit_reset_ms":1594906104209,"rate_limit":100}

Process finished with exit code 1

**Comment by kroitor** [comment]
@liuyynn does this work for you:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.bybit({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

exchange.load_markets()
exchange.verbose = True

symbol = 'BTC/USD'
type = 'market'
side = 'buy'
amount = 1
price = None

order = exchange.create_order(symbol, type, side, amount, price, {
    'qty': amount
})

pprint(order)
```

?

**Comment by liuyynn** [comment]
hi that works perfectly fine 
with this parameter added
{
    'qty' : amount
} 

thx a lot

**Comment by kroitor** [comment]
@liuyynn i'll add a fix to it shortly so that you won't have to override it with params. Thx for reporting it!

**Comment by Daz007X** [comment]
I have used your code and my money on spot position it's still got error 
like 

`import ccxt
from pprint import pprint
exchange = ccxt.bybit({
    'enableRateLimit': True,
    'apiKey': 'API',
    'secret': 'SEC',
})

exchange.load_markets()
exchange.verbose = True

symbol = 'XRP/USDT'
type = 'market'
side = 'buy'
amount = 6
price = None

order = exchange.create_order(symbol, type, side, amount, price, {
    'qty': amount
})

pprint(order)`

`raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bybit {"ret_code":130001,"ret_msg":"position idx not match position mode","result":{},"ext_code":"","ext_info":"","time_now":"1674459641.827183","rate_limit_status":99,"rate_limit":100,"rate_limit_reset_ms":1674459641825}`



![image](https://user-images.githubusercontent.com/101831331/213988342-dd2731b5-c8e6-4a13-91e5-05bef162e851.png)
