### ISSUE TITLE
import ccxt with python 2.7.17 throws error

### ISSUE THREAD

**Issue by kostanjsek** [ccxt/ccxt#7393]
- OS: Ubuntu 18.04.3 LTS
- Programming Language version: Python 2.7.17
- CCXT version: ccxt==1.32.34

```
import ccxt
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 532
    def print(self, *args):
            ^
SyntaxError: invalid syntax

```

**Comment by kroitor** [comment]
Python 2.7 is deprecated and is not supported since Jan 1, 2020:

- https://python3statement.org/

CCXT requires Python 3+. Let us know if that does not answer your question.
