### ISSUE TITLE
decimal.InvalidOperation with okex.create_order()

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#7415]
- OS: Linux
- Programming Language version: Python 3.6
- CCXT version:ccxt==1.27.54

Hello, I'm facing an error with OKEx when trying to create a new order. Here is my code and the error message, I'm very curious to know what could be the reason since I did many tries and I can't find a solution.

Thank you,

```
import ccxt
ok = ccxt.okex()
ok.secret = ''
ok.apiKey = ''
ok.password = ''
args = {'amount': 18, 'side': 'sell', 'symbol': 'ETH-USDT-SWAP', 'type': 'market'}
ok.options['defaultType'] = 'swap'
ok.create_order(**args)
```

```
---------------------------------------------------------------------------
InvalidOperation                          Traceback (most recent call last)
<ipython-input-42-58965134a2db> in <module>
      1 args = {'amount': 18, 'side': 'sell', 'symbol': 'ETH-USDT-SWAP', 'type': 'market'}
      2 ok.options['defaultType'] = 'swap'
----> 3 ok.create_order(**args)

~/python/envdev/lib/python3.6/site-packages/ccxt/okex.py in create_order(self, symbol, type, side, amount, price, params)
   1766                 'type': type,  # 1:open long 2:open short 3:close long 4:close short for futures
   1767                 'size': size,
-> 1768                 'price': self.price_to_precision(symbol, price),
   1769                 # 'match_price': '0',  # Order at best counter party price?(0:no 1:yes). The default is 0. If it is set as 1, the price parameter will be ignored. When posting orders at best bid price, order_type can only be 0(regular order).
   1770             })

~/python/envdev/lib/python3.6/site-packages/ccxt/base/exchange.py in price_to_precision(self, symbol, price)
   1219 
   1220     def price_to_precision(self, symbol, price):
-> 1221         return self.decimal_to_precision(price, ROUND, self.markets[symbol]['precision']['price'], self.precisionMode)
   1222 
   1223     def amount_to_precision(self, symbol, amount):

~/python/envdev/lib/python3.6/site-packages/ccxt/base/decimal_to_precision.py in decimal_to_precision(n, rounding_mode, precision, counting_mode, padding_mode)
     53     context.rounding = decimal.ROUND_HALF_UP  # rounds 0.5 away from zero
     54 
---> 55     dec = decimal.Decimal(str(n))
     56     precision_dec = decimal.Decimal(str(precision))
     57     string = '{:f}'.format(dec)  # convert to string using .format to avoid engineering notation

InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by kroitor** [comment]
Do you have the same issue with the most recent version of CCXT 1.32.55+ ?
Your version 1.27.54 is too old.

**Comment by Kinzowa** [comment]
Hi Igor, yes same issue with the latest release.

```
pip freeze | grep ccx
ccxt==1.32.55
```
I also tried with `create_market_buy_order` but it's still the same.
```
args = dict(
  symbol=symbol,
  amount=float(amount)
)
if side == 'buy':
  client.create_market_buy_order(**args)
elif side == 'sell':
  client.create_market_sell_order(**args)
```

**Comment by kroitor** [comment]
@Kinzowa ok, please, update to 1.32.56 (it will arrive in 15 minutes), and let me know if this does not work:

```Python
import ccxt
exchange = ccxt.okex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'password': 'YOUR_API_PASSWORD',
    'enableRateLimit': True,  # required by the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'swap',
    },
})
exchange.load_markets()
args = {'amount': 18, 'side': 'sell', 'symbol': 'ETH-USDT-SWAP', 'type': 'market'}
exchange.verbose = True  # ←------------------------- POST YOUR VERBOSE REQUEST+RESPONSE IF IT DOES NOT WORK
exchange.create_order(**args)
```

**Comment by Kinzowa** [comment]
Thanks it works like a charm now :)

**Comment by Kinzowa** [comment]
Oh Igor there is one thing I thought was caused by my code but now I have doubt. It throws an error `InvalidOrder: okex {"error_message":"Invalid order type","result":"true","error_code":"35040","order_id":"-1"}`.

```
args = {'amount': 18, 'symbol': 'ETH-USDT-SWAP'}
ok.options['defaultType'] = 'swap'
ok.create_market_buy_order(**args)


---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/python/envdev/lib/python3.6/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    580             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 581             response.raise_for_status()
    582 

~/python/envdev/lib/python3.6/site-packages/requests/models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 400 Client Error:  for url: https://www.okex.com/api/swap/v3/order

During handling of the above exception, another exception occurred:

InvalidOrder                              Traceback (most recent call last)
<ipython-input-5-f6f3f31e90a2> in <module>
      1 args = {'amount': 18, 'symbol': 'ETH-USDT-SWAP'}
      2 ok.options['defaultType'] = 'swap'
----> 3 ok.create_market_buy_order(**args)

~/python/envdev/lib/python3.6/site-packages/ccxt/base/exchange.py in create_market_buy_order(self, symbol, amount, params)
   1800 
   1801     def create_market_buy_order(self, symbol, amount, params={}):
-> 1802         return self.create_order(symbol, 'market', 'buy', amount, None, params)
   1803 
   1804     def create_market_sell_order(self, symbol, amount, params={}):

~/python/envdev/lib/python3.6/site-packages/ccxt/okex.py in create_order(self, symbol, type, side, amount, price, params)
   1820                     request['size'] = self.amount_to_precision(symbol, amount)
   1821             method = 'marginPostOrders' if (marginTrading == '2') else 'spotPostOrders'
-> 1822         response = getattr(self, method)(self.extend(request, params))
   1823         #
   1824         #     {

~/python/envdev/lib/python3.6/site-packages/ccxt/base/exchange.py in inner(_self, params)
    461                             if params is not None:
    462                                 inner_kwargs['params'] = params
--> 463                             return entry(_self, **inner_kwargs)
    464                         return inner
    465                     to_bind = partialer()

~/python/envdev/lib/python3.6/site-packages/ccxt/base/exchange.py in request(self, path, api, method, params, headers, body)
    484     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
    485         """Exchange.request is the entry point for all generated methods"""
--> 486         return self.fetch2(path, api, method, params, headers, body)
    487 
    488     @staticmethod

~/python/envdev/lib/python3.6/site-packages/ccxt/base/exchange.py in fetch2(self, path, api, method, params, headers, body)
    480         self.lastRestRequestTimestamp = self.milliseconds()
    481         request = self.sign(path, api, method, params, headers, body)
--> 482         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    483 
    484     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

~/python/envdev/lib/python3.6/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    591 
    592         except HTTPError as e:
--> 593             self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    594             self.handle_rest_errors(http_status_code, http_status_text, http_response, url, method)
    595             raise ExchangeError(method + ' ' + url)

~/python/envdev/lib/python3.6/site-packages/ccxt/okex.py in handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   3108             self.throw_broadly_matched_exception(self.exceptions['broad'], message, feedback)
   3109         if nonZeroErrorCode:
-> 3110             self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
   3111         if nonZeroErrorCode or nonEmptyMessage:
   3112             raise ExchangeError(feedback)  # unknown message

~/python/envdev/lib/python3.6/site-packages/ccxt/base/exchange.py in throw_exactly_matched_exception(self, exact, string, message)
    498     def throw_exactly_matched_exception(self, exact, string, message):
    499         if string in exact:
--> 500             raise exact[string](message)
    501 
    502     def throw_broadly_matched_exception(self, broad, string, message):

InvalidOrder: okex {"error_message":"Invalid order type","result":"true","error_code":"35040","order_id":"-1"}
```

**Comment by kroitor** [comment]
@Kinzowa please, paste your verbose output:

```Python
ok.options['defaultType'] = 'swap'
ok.load_markets()
ok.verbose = True
amount = 18
symbol = 'ETH-USDT-SWAP'
side = 'buy'
# order type 1:open long 2:open short 3:close long 4:close short
type = '1'
ok.create_order(symbol, type, side, amount)
```

**Comment by Kinzowa** [comment]
This code sample you just provided still generates a ConversionSyntax and no verbose output is displayed. Please find bellow the code sample that generates `Invalid order type` error.

```
ok.options['defaultType'] = 'swap'
ok.load_markets()
ok.verbose = True
amount = 18
symbol = 'ETH-USDT-SWAP'
side = 'buy'
type = '1'
ok.create_order(symbol, type, side, amount)

---------------------------------------------------------------------------
InvalidOperation                          Traceback (most recent call last)
<ipython-input-9-e31bb2390fae> in <module>
      6 side = 'buy'
      7 typeo = '1'
----> 8 ok.create_order(symbol, typeo, side, amount)

~/python/envdev/lib/python3.6/site-packages/ccxt/okex.py in create_order(self, symbol, type, side, amount, price, params)
   1788                 request['match_price'] = '1'
   1789             else:
-> 1790                 request['price'] = self.price_to_precision(symbol, price)
   1791             if market['futures']:
   1792                 request['leverage'] = '10'  # or '20'

~/python/envdev/lib/python3.6/site-packages/ccxt/base/exchange.py in price_to_precision(self, symbol, price)
   1255 
   1256     def price_to_precision(self, symbol, price):
-> 1257         return self.decimal_to_precision(price, ROUND, self.markets[symbol]['precision']['price'], self.precisionMode)
   1258 
   1259     def amount_to_precision(self, symbol, amount):

~/python/envdev/lib/python3.6/site-packages/ccxt/base/decimal_to_precision.py in decimal_to_precision(n, rounding_mode, precision, counting_mode, padding_mode)
     53     context.rounding = decimal.ROUND_HALF_UP  # rounds 0.5 away from zero
     54 
---> 55     dec = decimal.Decimal(str(n))
     56     precision_dec = decimal.Decimal(str(precision))
     57     string = '{:f}'.format(dec)  # convert to string using .format to avoid engineering notation

InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

This is how I generate the `Invalid order type` error :

```
args = {'amount': 18, 'symbol': 'ETH-USDT-SWAP'}
ok.options['defaultType'] = 'swap'
ok.create_market_buy_order(**args)

Request: POST https://www.okex.com/api/swap/v3/order {'OK-ACCESS-KEY': 'myAPYKEY', 'OK-ACCESS-PASSPHRASE': 'myPASSWORD', 'OK-ACCESS-TIMESTAMP': '2020-08-06T13:10:55.961Z', 'Content-Type': 'application/json', 'OK-ACCESS-SIGN': 'myACCESSSIGN/Q2u7oszWGHrfw=', 'User-Agent': 'python-requests/2.20.1', 'Accept-Encoding': 'gzip, deflate'} {"instrument_id":"ETH-USDT-SWAP","type":"market","size":"18","match_price":"1"}

Response: POST https://www.okex.com/api/swap/v3/order 400 {'Date': 'Thu, 06 Aug 2020 13:10:56 GMT', 'Content-Type': 'application/json', 'Content-Length': '91', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d511db131908862a6cebf6b744857c6a41596719456; expires=Sat, 05-Sep-20 13:10:56 GMT; path=/; domain=.okex.com; HttpOnly; SameSite=Lax, locale=en_US; Max-Age=604800; Expires=Thu, 13-Aug-2020 13:10:56 GMT; Path=/', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'X-BrokerID': '0', 'X-Kong-Upstream-Latency': '23', 'X-Kong-Proxy-Latency': '0', 'Via': 'kong/1.4.3', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '04657e77460000cc5a23ac6200000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5be900387a8dcc5a-ZRH'} {"error_message":"Invalid order type","result":"true","error_code":"35040","order_id":"-1"}
```

**Comment by kroitor** [comment]
@Kinzowa 

This should work:

```Python
ok.options['defaultType'] = 'swap'
ok.load_markets()
ok.verbose = True
amount = 18
symbol = 'ETH-USDT-SWAP'
side = 'buy'
type = '1'  #  1:open long 2:open short 3:close long 4:close short
params = { 'order_type': '4' }  # order_type = 4 means a market order with okex swap / futures
price = None
ok.create_order(symbol, type, side, amount, price, params)
```

Let me know if you still have difficulties with it.

**Comment by Kinzowa** [comment]
Yes it's works thanks! `type = '1'` is specific to OKEx and it's `limit` or `market` for other platforms am'I right?

**Comment by kroitor** [comment]
@Kinzowa yes, this aspect is still subject to change, we're working on a unification schema for it.

**Comment by sf7com** [comment]
> @Kinzowa please, paste your verbose output:
> 
> * https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
> 
> ```python
> ok.options['defaultType'] = 'swap'
> ok.load_markets()
> ok.verbose = True
> amount = 18
> symbol = 'ETH-USDT-SWAP'
> side = 'buy'
> # order type 1:open long 2:open short 3:close long 4:close short
> type = '1'
> ok.create_order(symbol, type, side, amount)
> ```
Hi~

Order_create is not executed in the same way on OKEX V5.

Which part should I correct?


client = ccxt.okex5(config={
    'api_key' : config.API_KEY,
    'secret': config.API_SECRET,
    'password' : config.API_PASS,
    'enableRateLimit':True,
    'options':{
        'defaultType': 'swap',
    }
})
client.load_markets()
symbol = "BTC-USDT-SWAP"
client.verbose = True
side = 'buy'
amount = 1
type = '1'
params = {'order_type':'4'}
price = None
res = client.create_order(symbol, type, side, amount, price, params)

**Comment by kroitor** [comment]
@sf7com 

> Which part should I correct?

Remove the `params` overrides, since those are exchange-version-specific. OKEX v5 does not have an `order_type` param.

**Comment by sf7com** [comment]
> @sf7com
> 
> > Which part should I correct?
> 
> Remove the `params` overrides, since those are exchange-version-specific. OKEX v5 does not have an `order_type` param.

Thank you for your reply.
I deleted 'params' and ran it, but the error came out as below. Please help me.

Traceback (most recent call last):
  File "C:/Users/KJT/PycharmProjects/OKEX/order.py", line 116, in <module>
    res = client.create_order(symbol, type, side, amount, price)
  File "C:\Anaconda3\lib\site-packages\ccxt\okex.py", line 1358, in create_order
    request['px'] = self.price_to_precision(symbol, price)
  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1302, in price_to_precision
    return self.decimal_to_precision(price, ROUND, self.markets[symbol]['precision']['price'], self.precisionMode, self.paddingMode)
  File "C:\Anaconda3\lib\site-packages\ccxt\base\decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by kroitor** [comment]
@sf7com 

> Which part should I correct?

Assuming you have the most recent version of CCXT (1.55.16+)

```Python
exchange = ccxt.okex5({
    'api_key' : config.API_KEY,
    'secret': config.API_SECRET,
    'password' : config.API_PASS,
    'options':{
        'defaultType': 'swap',
    }
})
markets = await exchange.load_markets()
client.verbose = True
symbol = 'BTC-USDT-SWAP'
type = 'market'
side = 'buy'
amount = 1
price = None
response = client.create_order(symbol, type, side, amount, price)
```

**Comment by sf7com** [comment]
> @sf7com
> 
> > Which part should I correct?
> 
> Assuming you have the most recent version of CCXT (1.55.16+)
> 
> ```python
> exchange = ccxt.okex5({
>     'api_key' : config.API_KEY,
>     'secret': config.API_SECRET,
>     'password' : config.API_PASS,
>     'options':{
>         'defaultType': 'swap',
>     }
> })
> markets = await exchange.load_markets()
> client.verbose = True
> symbol = 'BTC-USDT-SWAP'
> type = 'market'
> side = 'buy'
> amount = 1
> price = None
> response = client.create_order(symbol, type, side, amount, price)
> ```

I got your reply and upgraded to ccxt.. (1.55.17)

Error when using 'await'.
============================================
  File "C:/Users/KJT/PycharmProjects/OKEX/order_test.py", line 12
    markets = await client.load_markets()
              ^
SyntaxError: 'await' outside function



Error when 'await' is not used.
============================================
Traceback (most recent call last):
  File "C:/Users/KJT/PycharmProjects/OKEX/order_test.py", line 19, in <module>
    res = client.create_order(symbol, type, side, amount, price)
  File "C:\Anaconda3\lib\site-packages\ccxt\okex.py", line 1371, in create_order
    raise InvalidOrder(self.id + " createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply a price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False and supply the total cost value in the 'amount' argument or in the 'sz' extra parameter(the exchange-specific behaviour)")
ccxt.base.errors.InvalidOrder: okex5 createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply a price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False and supply the total cost value in the 'amount' argument or in the 'sz' extra parameter(the exchange-specific behaviour)


I always appreciate your help.

**Comment by kroitor** [comment]
@sf7com this error message explains itself:

> ccxt.base.errors.InvalidOrder: okex5 createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply a price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False and supply the total cost value in the 'amount' argument or in the 'sz' extra parameter(the exchange-specific behaviour)

Documented here: https://ccxt.readthedocs.io/en/latest/manual.html#market-buys

**Comment by supermanlovegithub** [comment]
got it.
