### ISSUE TITLE
FTX.us fails to auth

### ISSUE THREAD

**Issue by fqlx** [ccxt/ccxt#7461]
- OS: Linux
- Programming Language version: Python3
- CCXT version: 1.32.39

```
import ccxt
api = { 'apiKey': 'MyAPIKey', 'secret': 'MySecret' }
ftx = ccxt.ftx(api)
ftx.fetch_balance()
```

Returns error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 581, in fetch
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://ftx.us/api/wallet/balances
```

I've also modified the hostname in `python3.7/site-packages/ccxt/ftx.py` to ftx.us.  

```
'hostname': 'ftx.us',  # or ftx.us
```

I've also verified the date/time is accurate and the API keys are from ftx.us.

I think the hmac signing is broken in ccxt?  Can you verify?

**Comment by kroitor** [comment]
@fqlx hi! 

> I've also modified the hostname in python3.7/site-packages/ccxt/ftx.py to ftx.us.

No need for that, do this instead:

```Python
import ccxt
exchange = ccxt.ftx ({
    'enableRateLimit': True,  # required! https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'hostname': 'ftx.us',
})
exchange.load_markets()
exchange.verbose = True
print(exchange.fetch_balance())
```

> I've also verified the date/time is accurate

Can you elaborate on what you've tried exactly to make sure that the timestamp is in sync?

**Comment by fqlx** [comment]
Still seeing unauthorized with the above code. Can you verify on ftx.us site by generating api keys?

To verify the date - I check my local system date and it's accurate.
```
$ date
Thu Aug 13 12:23:55 CDT 2020
```

```
Request: GET https://ftx.us/api/wallet/balances {'FTX-KEY': '<redacted>', 'FTX-TS': '1597339311956', 'FTX-SIGN': '<redacted>', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://ftx.us/api/wallet/balances 401 {'Date': 'Thu, 13 Aug 2020 17:21:52 GMT', 'Content-Type': 'application/json', 'Content-Length': '42', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=<redacted>; expires=Sat, 12-Sep-20 17:21:51 GMT; path=/; domain=.ftx.us; HttpOnly; SameSite=Lax; Secure', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': 'None', 'Vary': 'Origin, Accept-Encoding', 'CF-Cache-Status': 'MISS', 'cf-request-id': '<redacted>', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '<redacted>, 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400'} {"error":"Not logged in","success":false}

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 581, in fetch
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://ftx.us/api/wallet/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ftxus.py", line 10, in <module>
    print(exchange.fetch_balance())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/ftx.py", line 784, in fetch_balance
    response = self.privateGetWalletBalances(params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 486, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 593, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/ftx.py", line 1454, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: ftx {"error":"Not logged in","success":false}
```

**Comment by fqlx** [comment]
@kroitor 

Proposed fix:
https://github.com/ccxt/ccxt/pull/7462

**Comment by kroitor** [comment]
@fqlx i'll port it shortly: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
