### ISSUE TITLE
phemex decimal issue watch_order_book

### ISSUE THREAD

**Issue by jaseisen105** [ccxt/ccxt#7469]
- OS: macOS 10.13.6
- Programming Language version: 3.6.0
- CCXT version: ccxt 1.33.15 | ccxtpro 0.3.43

```
client = ccxtpro.phemex()
while True:
    ccxt_orderbook = await client.watch_order_book(
        "ETH/USD",
        params={}
    )
```

```
Traceback (most recent call last):
  File "execution.py", line 1669, in subscribe_book
    params={}
  File "python3.6/site-packages/ccxtpro/phemex.py", line 280, in watch_order_book
    await self.load_markets()
  File "python3.6/site-packages/ccxt/async_support/base/exchange.py", line 180, in load_markets
    raise e
  File "python3.6/site-packages/ccxt/async_support/base/exchange.py", line 176, in load_markets
    result = await self.markets_loading
  File "python3.6/site-packages/ccxt/async_support/base/exchange.py", line 165, in load_markets_helper
    currencies = await self.fetch_currencies()
  File "python3.6/site-packages/ccxt/async_support/phemex.py", line 692, in fetch_currencies
    maxAmount = float(self.decimal_to_precision(maxValueEv * precision, ROUND, 0.00000001, self.precisionMode))
  File "python3.6/site-packages/ccxt/base/decimal_to_precision.py", line 74, in decimal_to_precision
    missing = abs(dec) % precision_dec
decimal.InvalidOperation: [<class 'decimal.DivisionImpossible'>]
```

**Comment by kroitor** [comment]
@jaseisen105 does this work on your side?

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.phemex({
    'enableRateLimit': True,
})

exchange.verbose = True

exchange.load_markets()
```

**Comment by jaseisen105** [comment]
@kroitor - unfortunately no, getting the same error

**Comment by kroitor** [comment]
I don't have this issue in Python 3.6.9 and Python 3.7.2.

```
ubuntu@ccxt:~/$ python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> exchange = ccxt.phemex({'enableRateLimit': True})
>>> exchange.load_markets()
{'BTC/USD': {'percentage': True, 'tierBased': False, 'taker': 0.0075, 'maker': -0...
>>> ccxt.__version__
'1.33.17'
```

I think it may be related to your Python version (3.6.0).
Do you have the same issue if you upgrade to a newer Python version? Let us know if you can upgrade it to rule out version conflicts. In the meantime I will try to reproduce it on my side with 3.6.0.

**Comment by jaseisen105** [comment]
@kroitor that worked, thanks!
