### ISSUE TITLE
Error: a lot of coin pairs does not exist for okex exchange

### ISSUE THREAD

**Issue by lfzCarlosC** [ccxt/ccxt#7478]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: Python
- CCXT version: 1.33.21

```
ccxt.okex().fetchOHLCV('XTZ/USDT', timeframe='1d')
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 586, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://www.okex.com/api/spot/v3/instruments/XTZ-USDT/history/candles?granularity=86400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/okex.py", line 1382, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 491, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 598, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/okex.py", line 3161, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadSymbol: okex {"error_message":"The currency pair does not exist","code":30032,"error_code":"30032","message":"The currency pair does not exist"}
```

1. In the old ccxt version,  this problem doesn't exist.
2. This problem does not happen on main stream coin pairs, e.g. BTC/USDT, BCH/USDT, ETH/USDT. But coin pairs, like OMG/USDT, GRIN/USDT all have this issue.

**Comment by lfzCarlosC** [comment]
Also tried with `ccxt.okcoin().fetchOHLCV('XTZ/USDT', timeframe='1d')`, the same issue.

**Comment by lfzCarlosC** [comment]
https://github.com/ccxt/ccxt/commit/b3846652939e550ac93a6e2c10aa0cbb8ec1120a
I don't understand why this PR add `history` as the endpont in the doc https://www.okex.com/docs/en/#spot-line always have no `history`

**Comment by lfzCarlosC** [comment]
I could fix that if you agree.

**Comment by kroitor** [comment]
@lfzCarlosC no worries, i'm uploading a fix, thx for reporting!
