### ISSUE TITLE
Error with continuous ohlcv fetching poloniex

### ISSUE THREAD

**Issue by sdroy101** [ccxt/ccxt#7498]
- 

- OS: macOS 10.13.6
- Programming Language version: 3.7.6
- CCXT version: 1.30.52
I was trying to pull ohlcv data for 5m candles from poloniex. In my code, I'm firstly put my system on wait till nearest 5min and then putting another stopper till 5mins more so that a coin entering XX:45:00 completes its 5min trade cycle by XX:50:00 and I also put a 10 seconds buffer in case if poloniex gets delayed. So right now, if my code starts at xx:37:yy time, it will wait till xx:40:00, then since will be xx:39:49, again it will wait for 5mins 10 secs i.e, xx:45:10, and ideally it should give me candle at xx:40:00 but at the very first pull, it was showing some exchange error as below:
```
import ccxt
import numpy as np
import pandas as pd
import time

exchange = ccxt.poloniex({'enableRateLimit': True})
exchange.load_markets()
##rounding up to nearest 5th mins
def ceil_dt(dt, delta):
    return (dt + (datetime.min - dt) % delta)
now = datetime.strptime((datetime.fromtimestamp(exchange.milliseconds()/1000).strftime('%Y-%m-%d %H:%M:%S')), '%Y-%m-%d %H:%M:%S')
b=ceil_dt(now, timedelta(minutes=5))
a=exchange.milliseconds()/1000
if int(datetime.timestamp(b)-a)>0:
    time.sleep(float(datetime.timestamp(b)-a))

since=exchange.milliseconds()-1*1000

t_end=exchange.milliseconds()+60*15*1000 
all_c=[]
while t_end > exchange.milliseconds():
    
    try:
        time.sleep(300+10) #giving buffer 
        print('---------------------------------------------------------------')
        print('Fetching ohlcvs since', exchange.iso8601(since))
        
        candles = exchange.fetch_ohlcv('BTC/USDT', '5m', since, 1000)
        all_c+=candles
        since=candles[0][0]+1000*60*5
       
    except ccxt.NetworkError as e:
        print(e)
        break
    except ccxt.ExchangeError as e:
        print(e)
        break
       
```
Error:
```
GET https://poloniex.com/public?command=returnChartData&currencyPair=USDT_BTC&period=300&start=1598062499&end=1598362499
```

**Comment by sdroy101** [comment]
![Screen Shot 2020-08-24 at 7 22 50 PM](https://user-images.githubusercontent.com/32267008/91052703-747e8c00-e63f-11ea-9c60-c60201f4596d.png)
![Screen Shot 2020-08-24 at 7 22 21 PM](https://user-images.githubusercontent.com/32267008/91052722-79dbd680-e63f-11ea-854c-e478c3a74837.png)

This is the entire error I got from running it in spyder console

**Comment by sdroy101** [comment]
@kroitor Please look into it!

**Comment by sdroy101** [comment]
Hey @kroitor ! any update on this?

**Comment by kroitor** [comment]
@sdroy101 on your screenshots it says about the RequestTimeout. You are running only one instance of the above script, right? Or do you run multiple instances of the same exchange instance in parallel?

**Comment by sdroy101** [comment]
Only just one coin for only one exchange in this case, though I'm actually planning to implement on 20 coins parallelly in future.

**Comment by kroitor** [comment]
@sdroy101 alright, let's start with this simple script for debugging purposes to test your connectivity and rule out the RequestTimeout:

```Python
import ccxt

print('CCXT version:', ccxt.__version__)
exchange = ccxt.poloniex({'enableRateLimit': True})
exchange.load_markets()
exchange.verbose = True
symbol = 'BTC/USDT'
timeframe = '5m'
since = exchange.milliseconds() - exchange.parse_timeframe(timeframe) * 1000
limit = 1000
print(exchange.iso8601(since))
candles = exchange.fetch_ohlcv(symbol, timeframe, since, limit)
for candle in candles:
    print(exchange.iso8601(candle[0]) + ' '.join([str(c) for c in candle[1:]]))
```

↑ Does this script work on your side? Please, paste all of your output here.

Please, do not paste text as screenshots! (read this carefully: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help). Instead copy and paste text, output and code as text, otherwise other users won't be able to find this issue using the search. Use [GitHub markdown](https://guides.github.com/features/mastering-markdown/) for readability and padding, surround your code and/or output with triple backticks (&#096;&#096;&#096;), like shown below:

&#096;&#096;&#096;Python
put your code here, don't paste one line of code, paste your full short complete code snippet
&#096;&#096;&#096;

&#096;&#096;&#096;
your output here
&#096;&#096;&#096;

**Comment by sdroy101** [comment]
```
CCXT version: 1.33.31
2020-08-26T21:49:11.035Z

Request: GET https://poloniex.com/public?command=returnChartData&currencyPair=USDT_BTC&period=300&start=1598478551&end=1598778551 {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://poloniex.com/public?command=returnChartData&currencyPair=USDT_BTC&period=300&start=1598478551&end=1598778551 200 {'Date': 'Wed, 26 Aug 2020 21:54:11 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d679c6658ca3ea8de473630adc198d8d91598478851; expires=Fri, 25-Sep-20 21:54:11 GMT; path=/; domain=.poloniex.com; HttpOnly; SameSite=Lax; Secure', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '04ce5cb5480000dc85a00a0200000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5c90ca35491edc85-MAA'} [{"date":1598478551,"high":11466.99999999,"low":11466.99999999,"open":11466.99999999,"close":11466.99999999,"volume":0,"quoteVolume":0,"weightedAverage":11466.99999999},{"date":1598478600,"high":11470.52891396,"low":11466.99999999,"open":11466.99999999,"close":11470.16561947,"volume":177.51795082,"quoteVolume":0.01547703,"weightedAverage":11469.76847785}]
2020-08-26T21:50:00.000Z11466.99999999 11470.52891396 11466.99999999 11470.16561947 0.01547703
```


This is the entire output I got after running the code you mentioned  @kroitor

**Comment by kroitor** [comment]
@sdroy101 yep, that looks correct, i'll post another example here that does what you described in your initial post. Will get back to you shortly.

**Comment by sdroy101** [comment]
Okay @kroitor !

**Comment by sdroy101** [comment]
@kroitor  is it something wrong with the approach or with the exchange medium?

**Comment by kroitor** [comment]
@sdroy101 please, check this example script:

- https://github.com/ccxt/ccxt/tree/master/examples/py/poloniex-fetch-ohlcv-continuously.py

```Python
import asyncio
from pprint import pprint
import ccxt.async_support as ccxt


# this example shows how to fetch OHLCVs continuously, see issue #7498
# https://github.com/ccxt/ccxt/issues/7498


async def fetch_ohlcvs_continuously(exchange, timeframe, symbol, fetching_time):
    print(exchange.id, timeframe, symbol, 'starting')
    all_ohlcvs = []
    limit = 1
    duration_in_seconds = exchange.parse_timeframe(timeframe)
    duration_in_milliseconds = duration_in_seconds * 1000
    now = exchange.milliseconds()
    end_time = now + fetching_time
    while now < end_time:
        since = int(now / duration_in_milliseconds) * duration_in_milliseconds
        time_to_wait = duration_in_milliseconds - now % duration_in_milliseconds + 10000  # +10 seconds buffer
        print(exchange.id, timeframe, symbol, 'time now is', exchange.iso8601(now))
        print(exchange.id, timeframe, symbol, 'time to wait is', time_to_wait / 1000, 'seconds')
        print(exchange.id, timeframe, symbol, 'sleeping till', exchange.iso8601(now + time_to_wait))
        await exchange.sleep(time_to_wait)
        print(exchange.id, timeframe, symbol, 'done sleeping at', exchange.iso8601(exchange.milliseconds()))
        while True:
            try:
                ohlcvs = await exchange.fetch_ohlcv(symbol, timeframe, since, limit)
                break
            except Exception as e:
                print(type(e).__name__, e.args, str(e))  # comment if not needed
                # break  # uncomment to break it
                # pass   # uncomment to do nothing and just retry again on next iteration
                # or add your own reaction according to the purpose of your app
        print(exchange.id, timeframe, symbol, 'fetched', len(ohlcvs), 'candle(s), time now is', exchange.iso8601(exchange.milliseconds()))
        print(exchange.id, timeframe, symbol, 'all candles:')
        all_ohlcvs += ohlcvs
        for ohlcv in all_ohlcvs:
            print('    ', exchange.iso8601(ohlcv[0]), ohlcv[1:])
        now = exchange.milliseconds()
    return {symbol: all_ohlcvs}


async def fetch_all_ohlcvs_continuously(loop, exchange_id, timeframe, symbols, fetching_time):
    exchange_class = getattr(ccxt, exchange_id)
    exchange = exchange_class({'enableRateLimit': True, 'asyncio_loop': loop})
    input_coroutines = [fetch_ohlcvs_continuously(exchange, timeframe, symbol, fetching_time) for symbol in symbols]
    results = await asyncio.gather(*input_coroutines, return_exceptions=True)
    await exchange.close()
    return exchange.extend(*results)


print('CCXT version:', ccxt.__version__)

exchange_id = 'poloniex'
symbols = [ 'ETH/BTC', 'BTC/USDT' ]
timeframe = '5m'
fetching_time = 15 * 60 * 1000  # stop after 15 minutes (approximately 4 iterations)
loop = asyncio.get_event_loop()
coroutine = fetch_all_ohlcvs_continuously(loop, exchange_id, timeframe, symbols, fetching_time)
results = loop.run_until_complete(coroutine)
pprint(results)
# results  # if you run this code in Jupyter then uncomment thisline to see the output result
```

My output:

```
mbp:ccxt igorkroitor$ python3 examples/py/poloniex-fetch-ohlcv-continuously.py
CCXT version: 1.33.67
poloniex 5m ETH/BTC starting
poloniex 5m ETH/BTC time now is 2020-08-29T21:02:05.623Z
poloniex 5m ETH/BTC time to wait is 184.377 seconds
poloniex 5m ETH/BTC sleeping till 2020-08-29T21:05:10.000Z
poloniex 5m BTC/USDT starting
poloniex 5m BTC/USDT time now is 2020-08-29T21:02:05.626Z
poloniex 5m BTC/USDT time to wait is 184.374 seconds
poloniex 5m BTC/USDT sleeping till 2020-08-29T21:05:10.000Z
poloniex 5m BTC/USDT done sleeping at 2020-08-29T21:05:10.002Z
poloniex 5m ETH/BTC done sleeping at 2020-08-29T21:05:10.004Z
poloniex 5m BTC/USDT fetched 1 candle(s), time now is 2020-08-29T21:05:11.140Z
poloniex 5m BTC/USDT all candles:
     2020-08-29T21:00:00.000Z [11513.52039079, 11517.68556586, 11513.52039079, 11515.00000001, 1.49795764]
poloniex 5m BTC/USDT time now is 2020-08-29T21:05:11.140Z
poloniex 5m BTC/USDT time to wait is 298.86 seconds
poloniex 5m BTC/USDT sleeping till 2020-08-29T21:10:10.000Z
poloniex 5m ETH/BTC fetched 1 candle(s), time now is 2020-08-29T21:05:12.193Z
poloniex 5m ETH/BTC all candles:
     2020-08-29T21:00:00.000Z [0.03519014, 0.03519014, 0.0351682, 0.03517801, 194.66391103]
poloniex 5m ETH/BTC time now is 2020-08-29T21:05:12.193Z
poloniex 5m ETH/BTC time to wait is 297.807 seconds
poloniex 5m ETH/BTC sleeping till 2020-08-29T21:10:10.000Z
poloniex 5m ETH/BTC done sleeping at 2020-08-29T21:10:09.994Z
poloniex 5m BTC/USDT done sleeping at 2020-08-29T21:10:09.994Z
poloniex 5m ETH/BTC fetched 1 candle(s), time now is 2020-08-29T21:10:10.300Z
poloniex 5m ETH/BTC all candles:
     2020-08-29T21:00:00.000Z [0.03519014, 0.03519014, 0.0351682, 0.03517801, 194.66391103]
     2020-08-29T21:05:00.000Z [0.035175, 0.035175, 0.03515016, 0.0351698, 56.89366917]
poloniex 5m ETH/BTC time now is 2020-08-29T21:10:10.300Z
poloniex 5m ETH/BTC time to wait is 299.7 seconds
poloniex 5m ETH/BTC sleeping till 2020-08-29T21:15:10.000Z
poloniex 5m BTC/USDT fetched 1 candle(s), time now is 2020-08-29T21:10:10.328Z
poloniex 5m BTC/USDT all candles:
     2020-08-29T21:00:00.000Z [11513.52039079, 11517.68556586, 11513.52039079, 11515.00000001, 1.49795764]
     2020-08-29T21:05:00.000Z [11514.27128015, 11514.27128015, 11494.50001001, 11497.78239369, 0.8303728]
poloniex 5m BTC/USDT time now is 2020-08-29T21:10:10.329Z
poloniex 5m BTC/USDT time to wait is 299.671 seconds
poloniex 5m BTC/USDT sleeping till 2020-08-29T21:15:10.000Z
poloniex 5m BTC/USDT done sleeping at 2020-08-29T21:15:09.997Z
poloniex 5m ETH/BTC done sleeping at 2020-08-29T21:15:09.998Z
poloniex 5m ETH/BTC fetched 1 candle(s), time now is 2020-08-29T21:15:10.291Z
poloniex 5m ETH/BTC all candles:
     2020-08-29T21:00:00.000Z [0.03519014, 0.03519014, 0.0351682, 0.03517801, 194.66391103]
     2020-08-29T21:05:00.000Z [0.035175, 0.035175, 0.03515016, 0.0351698, 56.89366917]
     2020-08-29T21:10:00.000Z [0.03512595, 0.03513803, 0.03512595, 0.03512628, 2.00730228]
poloniex 5m ETH/BTC time now is 2020-08-29T21:15:10.292Z
poloniex 5m ETH/BTC time to wait is 299.708 seconds
poloniex 5m ETH/BTC sleeping till 2020-08-29T21:20:10.000Z
poloniex 5m BTC/USDT fetched 1 candle(s), time now is 2020-08-29T21:15:10.405Z
poloniex 5m BTC/USDT all candles:
     2020-08-29T21:00:00.000Z [11513.52039079, 11517.68556586, 11513.52039079, 11515.00000001, 1.49795764]
     2020-08-29T21:05:00.000Z [11514.27128015, 11514.27128015, 11494.50001001, 11497.78239369, 0.8303728]
     2020-08-29T21:10:00.000Z [11494.90708718, 11500.23644886, 11493.10000001, 11500.23644886, 2.07385943]
poloniex 5m BTC/USDT time now is 2020-08-29T21:15:10.407Z
poloniex 5m BTC/USDT time to wait is 299.593 seconds
poloniex 5m BTC/USDT sleeping till 2020-08-29T21:20:10.000Z
poloniex 5m BTC/USDT done sleeping at 2020-08-29T21:20:09.998Z
poloniex 5m ETH/BTC done sleeping at 2020-08-29T21:20:10.005Z
poloniex 5m ETH/BTC fetched 1 candle(s), time now is 2020-08-29T21:20:10.280Z
poloniex 5m ETH/BTC all candles:
     2020-08-29T21:00:00.000Z [0.03519014, 0.03519014, 0.0351682, 0.03517801, 194.66391103]
     2020-08-29T21:05:00.000Z [0.035175, 0.035175, 0.03515016, 0.0351698, 56.89366917]
     2020-08-29T21:10:00.000Z [0.03512595, 0.03513803, 0.03512595, 0.03512628, 2.00730228]
     2020-08-29T21:15:00.000Z [0.03515295, 0.03515295, 0.03512595, 0.03512595, 8.30604314]
poloniex 5m BTC/USDT fetched 1 candle(s), time now is 2020-08-29T21:20:10.289Z
poloniex 5m BTC/USDT all candles:
     2020-08-29T21:00:00.000Z [11513.52039079, 11517.68556586, 11513.52039079, 11515.00000001, 1.49795764]
     2020-08-29T21:05:00.000Z [11514.27128015, 11514.27128015, 11494.50001001, 11497.78239369, 0.8303728]
     2020-08-29T21:10:00.000Z [11494.90708718, 11500.23644886, 11493.10000001, 11500.23644886, 2.07385943]
     2020-08-29T21:15:00.000Z [11507.33607952, 11509.08365859, 11500.32629936, 11500.32629936, 0.99574578]
{'BTC/USDT': [[1598734800000,
               11513.52039079,
               11517.68556586,
               11513.52039079,
               11515.00000001,
               1.49795764],
              [1598735100000,
               11514.27128015,
               11514.27128015,
               11494.50001001,
               11497.78239369,
               0.8303728],
              [1598735400000,
               11494.90708718,
               11500.23644886,
               11493.10000001,
               11500.23644886,
               2.07385943],
              [1598735700000,
               11507.33607952,
               11509.08365859,
               11500.32629936,
               11500.32629936,
               0.99574578]],
 'ETH/BTC': [[1598734800000,
              0.03519014,
              0.03519014,
              0.0351682,
              0.03517801,
              194.66391103],
             [1598735100000,
              0.035175,
              0.035175,
              0.03515016,
              0.0351698,
              56.89366917],
             [1598735400000,
              0.03512595,
              0.03513803,
              0.03512595,
              0.03512628,
              2.00730228],
             [1598735700000,
              0.03515295,
              0.03515295,
              0.03512595,
              0.03512595,
              8.30604314]]}
```

Let us know if that does not help. Feel free to reopen this issue or just ask further questions if any.

**Comment by sdroy101** [comment]
```

runcell(0, '/Users/soumyadeeproy/SMA_EMA/untitled4.py')
CCXT version: 1.33.31
Traceback (most recent call last):

  File "/Users/soumyadeeproy/SMA_EMA/untitled4.py", line 65, in <module>
    results = loop.run_until_complete(coroutine)

  File "/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()

  File "/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running

poloniex 5m ETH/BTC starting
poloniex 5m ETH/BTC time now is 2020-08-29T23:36:33.049Z
poloniex 5m ETH/BTC time to wait is 216.951 seconds
poloniex 5m ETH/BTC sleeping till 2020-08-29T23:40:10.000Z
poloniex 5m BTC/USDT starting
poloniex 5m BTC/USDT time now is 2020-08-29T23:36:33.050Z
poloniex 5m BTC/USDT time to wait is 216.95 seconds
poloniex 5m BTC/USDT sleeping till `2020-08-29T23:40:10.000Z
```


@kroitor  I just got this runtime error when I tried running it on spyder

**Comment by sdroy101** [comment]
It's sorted now! Thanks as usual! @kroitor
