### ISSUE TITLE
[Binance]amount to precision function error - InvalidOperation

### ISSUE THREAD

**Issue by mooneral** [ccxt/ccxt#7533]
Hi, I'm trying to create an order to sell altcoin on the market price but keep getting this error I have tried changing the type to `decimal.Decimal` or `str` but the error is the same. it is fine when I market buy altcoin using `params['quoteOrderQty']`! but when using `params["quantity"]` this error appears.

- OS: macOS Catalina 
- Programming Language version: python 3.8
- CCXT version:1.33.64

```python
amount = None
price = None
pair = f"MANA/USDT"
params["quantity"] = 133.0 # type float  and in base
response = self._submit_order(pair, amount, price, params)

```

```shell
Traceback (most recent call last):
  File "engine.py", line 637, in <module>
    engine.execute_order(sequence)
  File "engine.py", line 469, in execute_order
    response = self.create_order(order)
  File "engine.py", line 325, in create_order
    response = self._submit_order(pair, amount, price, params)
  File "engine.py", line 35, in wrapper_request_binance
    return func(*args, **kwargs)
  File "engine.py", line 354, in _submit_order
    return self.binance.create_order(pair, 'market', 'buy', amount, price, params=params)
  File "/Users/guru/.local/share/virtualenvs/trader_bot-uFZBMIxR/lib/python3.8/site-packages/ccxt/binance.py", line 1388, in create_order
    request['quantity'] = self.amount_to_precision(symbol, amount)
  File "/Users/guru/.local/share/virtualenvs/trader_bot-uFZBMIxR/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1264, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode)
  File "/Users/guru/.local/share/virtualenvs/trader_bot-uFZBMIxR/lib/python3.8/site-packages/ccxt/base/decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by kroitor** [comment]
Hi! The `amount` argument is mandatory as documented in the Manual, cannot be `None`:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/wiki/Manual#market-orders
- https://github.com/ccxt/ccxt/wiki/Manual#limit-orders

Instead of setting `params['quantity'] = 133.0` just set `amount = 133.0`.

```Python
import ccxt
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
amount = 133.0
price = None  # price is required for limit orders!
symbol = "MANA/USDT"
type = 'market'   # or 'limit'
side = 'sell'  # or 'buy'
response = exchange.create_order(symbol, type, side, amount, price)
print(response)
```

Let us know if the above does not answer your question.

**Comment by mooneral** [comment]
Thanks, @kroitor using the amount solved the issue.
