### ISSUE TITLE
marketOrder on BINANCE - InsufficientFunds

### ISSUE THREAD

**Issue by BHruska** [ccxt/ccxt#7559]
Trying to close a position on BINANCE with a Market Order, and I get a message indicating InsufficientFunds.  
The size is exactly my balance of that coin.  Not sure what I could be doing wrong.  Suggestions would be appreciated.

Thanks,
Brian

MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version:  Python
- CCXT version:  ccxt-1.30.22

```
       ret = self.exchange.createMarketSellOrder(symbol, size, *parms)

```

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/PythonProjects/ccxt/tradeClosePosition.py", line 40, in <module>
    main()
  File "c:/PythonProjects/ccxt/tradeClosePosition.py", line 37, in main
    tradeClosePosition()
  File "c:/PythonProjects/ccxt/tradeClosePosition.py", line 14, in tradeClosePosition
    exchange.closePosition(coin, coins)
  File "c:\PythonProjects\ccxt\EXCHANGE.py", line 518, in closePosition
    self.sellMarket(pair, coins)
  File "c:\PythonProjects\ccxt\EXCHANGE.py", line 488, in sellMarket
    ret = self.exchange.createMarketSellOrder(symbol, size, *parms)
  File "C:\Python36\lib\site-packages\ccxt\base\exchange.py", line 1810, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)
  File "C:\Python36\lib\site-packages\ccxt\binance.py", line 1402, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Python36\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Python36\lib\site-packages\ccxt\binance.py", line 2142, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Python36\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python36\lib\site-packages\ccxt\base\exchange.py", line 597, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Python36\lib\site-packages\ccxt\binance.py", line 2123, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "C:\Python36\lib\site-packages\ccxt\base\exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.
```

**Comment by kroitor** [comment]
1. First update to the most recent version of CCXT 1.33.97+
2. Then try this snippet:

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'spot',  # 'margin', 'future', etc...
    },
})

markets = exchange.load_markets()


pprint('-------------------------------------------------------')
print('Spot balance:')
spot_balance = exchange.fetch_balance({'type':'spot'})
pprint(spot_balance)

pprint('-------------------------------------------------------')
print('Margin balance:')
margin_balance = exchange.fetch_balance({'type':'margin'})
pprint(margin_balance)

pprint('-------------------------------------------------------')
print('Future balance:')
future_balance = exchange.fetch_balance({'type':'future'})
pprint(future_balance)

pprint('-------------------------------------------------------')

symbol = 'BTC/USDT'  # YOUR SYMBOL HERE
amount = 123.45  # YOUR AMOUNT HERE

exchange.verbose = True

order = exchange.create_market_sell_order(symbol, amount)
pprint(order)
```

Let us know if the above does not answer your question. If you still have issues with it, please, paste your entire verbose request+response output from the above snippet. Feel free to reopen this issue or just ask further questions, if any.
