### ISSUE TITLE
Huobi Pro createOrder Error

### ISSUE THREAD

**Issue by homerbong** [ccxt/ccxt#7611]
- OS: Linux 5.4.28-gentoo x86_64 
- Programming Language version: typescript 3.8.3
- CCXT version: 1.28.11
- Exchange: Huobi Pro
- Markets: `ETH/BTC`, `LTC/BTC`

Further Details after the code snippets.

```
...
const orderSide = ORDER_SIDE.ASK;
let amountDifference = currentAmount - neededAmount;
try {
  const ticker = await exchange.ccxt.fetchTicker(market);
  let price = orderSide === ORDER_SIDE.ASK ? ticker.ask : ticker.bid;
  const pricePrecision = exchange.getPricePrecision(market);
  price = toFixedTruncated(price, pricePrecision);
  const amount = this.getSafeAmount(exchange, market, amountDifference);
  const distributionOrder = await exchange.ccxt.createOrder(market, ORDER_TYPE.MARKET, orderSide, Math.abs(amount), price);
  return distributionOrder;
} catch (error) {
  console.log(`Error Code: ${ERRORS.ORDER_ERROR}`);
  console.log(error);
}
...
public getPricePrecision(market: string): number {
  let marketPrecision = this.ccxt.markets[market].precision.price;
  if(marketPrecision !== undefined && marketPrecision !== 0) {
    if(!Number.isInteger(marketPrecision)) {
      let decimalPlace = 1;
      let firstDecimalFound = false;
      while (!firstDecimalFound) {
        const precision = Math.pow(10, -decimalPlace);
        if (marketPrecision >= precision) {
          marketPrecision = decimalPlace;
          firstDecimalFound = true;
        }
        decimalPlace++;
      }
    }
  } else {
    marketPrecision = 0;
  }
  return marketPrecision;
}
...
export const toFixedTruncated = (num: number, fixed: number): number => {
  const re = new RegExp('^-?\\d+(?:\.\\d{0,' + (fixed || -1) + '})?');
  let regexResult = num.toString().match(re);
  let result = 0;
  if (regexResult) {
    result = parseFloat(regexResult[0]);
  }
  return result;
}
...
protected getSafeAmount(exchange: Exchange, market: string, calculatedAmount: number): number {
  const marketPrecision = exchange.getAmountPrecision(market);
  let amount = toFixedTruncated(calculatedAmount, marketPrecision);
  const minAmountLimit = exchange.getMarketTradeLimit(market, LIMIT_TYPE.AMOUNT, LIMIT_EXTREMES.MIN);
  const maxAmountLimit = exchange.getMarketTradeLimit(market, LIMIT_TYPE.AMOUNT, LIMIT_EXTREMES.MAX);
  if (Math.abs(amount) < minAmountLimit) {
    throw Error(`${ERRORS.MINIMUM_AMOUNT_LIMIT_ERROR}: ${exchange.getExchangeId()} - ${market} - ${calculatedAmount} - ${amount} - ${marketPrecision}`);
  }
  if (Math.abs(amount) > maxAmountLimit) {
    amount = amount > 0 ? maxAmountLimit : -maxAmountLimit;
  }
  return amount;
}
```

```
{"status":"error","err-code":"order-orderamount-precision-error","err-msg":"order amount precision error, scale: `4`","data":null}
```

I've been getting this error while trying to execute two orders on the following markets: `ETH/BTC` `LTC/BTC`
Although I realize that I'm handling some issues that are actually handled inside the ccxt library, I also understand the nature of the issue especially after seeing the code inside `huobipro.js` which in my version is the following: 
```
...
if ((type === 'market') && (side === 'buy')) {
  if (this.options['createMarketBuyOrderRequiresPrice']) {
    if (price === undefined) {
      throw new InvalidOrder (this.id + " market buy order requires price argument to calculate cost (total amount of quote currency to spend for buying, amount * price). To switch off this warning exception and specify cost in the amount argument, set .options['createMarketBuyOrderRequiresPrice'] = false. Make sure you know what you're doing.");
    } else {
      // despite that cost = amount * price is in quote currency and should have quote precision
      // the exchange API requires the cost supplied in 'amount' to be of base precision
      // more about it here: https://github.com/ccxt/ccxt/pull/4395
      // we use priceToPrecision instead of amountToPrecision here
      // because in this case the amount is in the quote currency
      request['amount'] = this.costToPrecision (symbol, parseFloat (amount) * parseFloat (price));
    }
  } else {
    request['amount'] = this.costToPrecision (symbol, amount);
  }
} else {
  request['amount'] = this.amountToPrecision (symbol, amount);
}
...
```
Now In order to complete the orders I ignored the comment and changed the following lines
```
...
request['amount'] = this.costToPrecision (symbol, parseFloat (amount) * parseFloat (price));
...
request['amount'] = this.costToPrecision (symbol, amount);
```
to
```
...
request['amount'] = this.amountToPrecision (symbol, parseFloat (amount) * parseFloat (price));
...
request['amount'] = this.amountToPrecision (symbol, amount);
```
This solved the issue with `ETH/BTC` and `LTC/BTC` but started to throwing errors while trying to execute market orders on other markets such as `XRP/BTC` or `EOS/BTC`. Is this a bug or am I doing something wrong? Let me know if you need further information or more details about the enums that I'm using. From what I understand it seems that the exchange is either having a different behaviour with these two markets or I'm missing some other error that. This happened on the official exchange, haven't tried it on the testnet.

**Comment by kroitor** [comment]
@homerbong with **unchanged** code of CCXT 1.34.39, please, paste the full verbose request+response that corresponds to this error:

```
{"status":"error","err-code":"order-orderamount-precision-error","err-msg":"order amount precision error, scale: `4`","data":null}
```

```JavaScript
const ccxt = require ('ccxt')

console.log ('CCXT Version:', ccxt.version)

;(async () {

    const exchange = new ccxt.huobipro ({
        'enableRateLimit': True,
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
    })

    await exchange.loadMarkets()

    exchange.verbose = true

    const symbol = 'ETH/BTC'
    const type = 'market'
    const side = 'buy'
    const amount = YOUR_AMOUNT
    const price = YOUR_PRICE // market buy cost in BTC = amount * price

    console.log (symbol, type, side, amount, price)
    const order = await exchange.createOrder (symbol, type, side, amount, price)
    console.log (order)

}) ()
```

Or change your code as shown below:

```TypeScript
  console.log ('CCXT Version:', ccxt.version)
  exchange.verbose = true
  console.log (market, ORDER_TYPE.MARKET, orderSide, Math.abs(amount), price)
  const distributionOrder = await exchange.ccxt.createOrder(market, ORDER_TYPE.MARKET, orderSide, Math.abs(amount), price);
```

**Comment by homerbong** [comment]
Hello I've updated the version of ccxt in order to be the latest available on npm as you can see from the log below. With verbose set to true I get the following output.
```
CCXT version:
1.34.40
ETH/BTC market buy 0.1473 0.032664
fetch:
 huobipro POST https://api.huobi.pro/v1/order/orders/place?AccessKeyId=Api-Key&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2020-09-21T14%3A01%3A42&Signature=FD2GAkCb1BFnloK3XBls8bLxqWgWaYuSx6H%2FWynEdh4%3D 
Request:
Object {User-Agent: "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/53…", Content-Type: "application/json"}
Exchange.js:462
Content-Type:"application/json"
User-Agent:"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}
{"account-id":15393147,"symbol":"ethbtc","type":"buy-market","amount":"0.004811"} 
Exchange.js:462
handleRestResponse:
 huobipro POST https://api.huobi.pro/v1/order/orders/place?AccessKeyId=Api-Key&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2020-09-21T14%3A01%3A42&Signature=FD2GAkCb1BFnloK3XBls8bLxqWgWaYuSx6H%2FWynEdh4%3D 200 OK 
Response:
Object {Cf-Cache-Status: "DYNAMIC", Cf-Ray: "5d6451dab947a644-LIM", Cf-Request-Id: "0552917cb50000a6446f2fb200000001", Connection: "keep-alive", Content-Encoding: "gzip", …}
Exchange.js:462
Cf-Cache-Status:"DYNAMIC"
Cf-Ray:"5d6451dab947a644-LIM"
Cf-Request-Id:"0552917cb50000a6446f2fb200000001"
Connection:"keep-alive"
Content-Encoding:"gzip"
Content-Type:"application/json;charset=UTF-8"
Date:"Mon, 21 Sep 2020 14:01:43 GMT"
Expect-Ct:"max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct""
Request-Id:"9806c8b0ffe563c162519f6f1173fc9c"
Server:"cloudflare"
Set-Cookie:"__cfduid=dc2793bc2ee71a9fcfd004c64db1ec1ba1600696902; expires=Wed, 21-Oct-20 14:01:42 GMT; path=/; domain=.huobi.pro; HttpOnly; SameSite=Lax; Secure"
Transfer-Encoding:"chunked"
Vary:"Accept-Encoding"
X-Application-Context:"mulan-broker-pro:default,prd:8080"
X-Hb-Ratelimit-Requests-Expire:"1600696904974"
X-Hb-Ratelimit-Requests-Remain:"99"
X-Request-Id:"65e83d7bb999bd400811be6b1878ac90"
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}

 {"status":"error","err-code":"order-orderamount-precision-error","err-msg":"order amount precision error, scale: `4`","data":null} 
Error Code: INVERSE_DISTRIBUTION_ORDER_ERROR
orders.controller.ts:398
ExchangeError: huobipro {"status":"error","err-code":"order-orderamount-precision-error","err-msg":"order amount precision error, scale: `4`","data":null}
orders.controller.ts:399
constructor:class extends BaseClass { … }
message:"huobipro {"status":"error","err-code":"order-orderamount-precision-error","err-msg":"order amount precision error, scale: `4`","data":null}"
name:"ExchangeError"
stack:"ExchangeError: huobipro {"status":"error","err-code":"order-orderamount-precision-error","err-msg":"order amount precision error, scale: `4`","data":null}
    at huobipro.handleErrors (/home/alex/Desktop/arbitrage/bot/node_modules/ccxt/js/huobipro.js:1501:23)
    at /home/alex/Desktop/arbitrage/bot/node_modules/ccxt/js/base/Exchange.js:598:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (/home/alex/Desktop/arbitrage/bot/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async huobipro.createOrder (/home/alex/Desktop/arbitrage/bot/node_modules/ccxt/js/huobipro.js:1165:26)"
__proto__:Object.assign {constructor: }
fetch:
huobipro GET https://api.huobi.pro/market/detail/merged?symbol=btcusdt 
Request:
Exchange.js:462
Object {User-Agent: "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/53…"}
Exchange.js:462
User-Agent:"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}

 undefined 
Exchange.js:462
handleRestResponse:
 huobipro GET https://api.huobi.pro/market/detail/merged?symbol=btcusdt 200 OK 
Response:
Object {Cf-Cache-Status: "DYNAMIC", Cf-Ray: "5d6451e72acca644-LIM", Cf-Request-Id: "05529184760000a6446f35f200000001", Connection: "keep-alive", Content-Encoding: "gzip", …}
Exchange.js:462
Cf-Cache-Status:"DYNAMIC"
Cf-Ray:"5d6451e72acca644-LIM"
Cf-Request-Id:"05529184760000a6446f35f200000001"
Connection:"keep-alive"
Content-Encoding:"gzip"
Content-Type:"application/json; charset=utf-8"
Date:"Mon, 21 Sep 2020 14:01:45 GMT"
Expect-Ct:"max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct""
Request-Id:"98db9c9b2fd5a185819fdf41498e3c76"
Server:"cloudflare"
Set-Cookie:"__cfduid=db4f08e099abdd06864481f2329dd61bc1600696904; expires=Wed, 21-Oct-20 14:01:44 GMT; path=/; domain=.huobi.pro; HttpOnly; SameSite=Lax; Secure"
Transfer-Encoding:"chunked"
Vary:"Accept-Encoding"
X-Request-Id:"fa842f0bb2b058053bba8a29b0732bf5"
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}

 {"status":"ok","ch":"market.btcusdt.detail.merged","ts":1600696905677,"tick":{"amount":30605.401415757602,"open":10867.61,"close":10600.03,"high":10987.32,"id":225629592746,"count":374337,"low":10505.4,"version":225629592746,"ask":[10600.03,0.061104],"vol":3.2950776457956415E8,"bid":[10600.02,0.55561]}} 
```

**Comment by kroitor** [comment]
@homerbong hi! Please, update to version 1.34.42+, we've uploaded a refix related to #4395, the new build should arrive within 20 minutes. Thx for reporting this bug! Let us know if you have further difficulties with it after upgrading to the most recent version of CCXT.

**Comment by homerbong** [comment]
Thank you very much. I will surely be testing it tomorrow. Any problem I will let you know.

**Comment by homerbong** [comment]
Hi @kroitor 
Sorry to bother you again but I've noticed that the issue started to occur again but in different markets this time. These are the details of the issue:
OS: Linux 5.4.28-gentoo x86_64
Programming Language version: typescript 3.8.3
CCXT version: 1.28.11
Exchange: Huobi Pro

The affected markets are the following: `XRP/BTC`, `EOS/BTC`, `ADA/BTC`, `LINK/BTC`
The code snippet where the error occurs is the following and most of the functions haven't changed:
```
    protected async placeInverseDistributionOrder(
        exchangeId: EXCHANGES, market: string, coinDistributionInformation: DistributionInformation
    ): Promise<Order | undefined> {
        const { currentAmount, neededAmount } = coinDistributionInformation;
        const exchange = this.exchanges[exchangeId];
        let amountDifference = currentAmount - neededAmount;
        const amountDifferencePercentage = amountDifference / currentAmount * 100;
        if (Math.abs(amountDifferencePercentage) < BALANCE_CONSTRAINT_EPSILON) {
            amountDifference = 0;
        }
        const orderSide = amountDifference > 0 ? ORDER_SIDE.BID : ORDER_SIDE.ASK;
        if (amountDifference) {
            try {
                const ticker = await exchange.ccxt.fetchTicker(market);
                let price = orderSide === ORDER_SIDE.ASK ? ticker.ask : ticker.bid;
                const pricePrecision = exchange.getPricePrecision(market);
                price = toFixedTruncated(price, pricePrecision);
                const amount = this.getSafeAmount(exchange, market, amountDifference);
                const distributionOrder = await exchange.ccxt.createOrder(market, ORDER_TYPE.MARKET, orderSide, Math.abs(amount), price);
                return distributionOrder;
            } catch (error) {
                console.log(`Error Code: ${ERRORS.INVERSE_DISTRIBUTION_ORDER_ERROR}`);
                console.log(`Exchange: ${exchangeId} - Market: ${market} - Amount: ${amountDifference} - Side: ${orderSide}`);
                console.log(error);
            }
        }
        return undefined;
    }
```
I've managed to intercept the parameters passed to the `createOrder` function before sending it and they were as following:
`market = EOS/BTC, ORDER_TYPE.MARKET = market, orderSide = buy, Math.abs(amount) = 23.56, price = 0.0002343`
And finally the verbose output (although I forgot to expand some of the objects so it might not be complete is the following:
```

fetch:
 huobipro POST https://api.huobi.pro/v1/order/orders/place?AccessKeyId=68c033cf-8e10c66b-411faea7-fr2wer5t6y&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2020-10-02T21%3A54%3A58&Signature=rKzXuciupZtc%2BMPl3DVc5Yj3HFjFn%2FBmlxJ%2BCKi6%2FdE%3D 
Request:
Exchange.js:462
Object {User-Agent: "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/53…", Content-Type: "application/json"}
Exchange.js:462

 {"account-id":15393147,"symbol":"eosbtc","type":"buy-market","amount":"0"} 
Exchange.js:462
handleRestResponse:
 huobipro POST https://api.huobi.pro/v1/order/orders/place?AccessKeyId=68c033cf-8e10c66b-411faea7-fr2wer5t6y&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2020-10-02T21%3A54%3A58&Signature=rKzXuciupZtc%2BMPl3DVc5Yj3HFjFn%2FBmlxJ%2BCKi6%2FdE%3D 200 OK 
Response:
Exchange.js:462
Object {Cf-Cache-Status: "DYNAMIC", Cf-Ray: "5dc1aa3b78e1971c-LIM", Cf-Request-Id: "058ce8b92c0000971c93b1d200000001", Connection: "keep-alive", Content-Encoding: "gzip", …}
Exchange.js:462

 {"status":"error","err-code":"invalid-amount","err-msg":"Parameter `amount` is invalid.","data":null} 
```
By the way managed to solve the issue by changing once again to the `costPrecision` inside `huobipro.js`.

**Comment by kroitor** [comment]
@homerbong hey! What's the value of the `amount` and the `symbol` before the `createOrder` call in your code?

**Comment by homerbong** [comment]
> @homerbong hey! What's the value of the `amount` and the `symbol` before the `createOrder` call in your code?

The function has been called with the following parameters:
`exchange.ccxt.createOrder('EOS/BTC', 'market', 'buy', 23.56, 0.0002343)`

I've noticed similar problems with the following markets as well: `XRP/BTC`, `ADA/BTC`, `LINK/BTC`.

Let me know if you need anything else.

**Comment by kroitor** [comment]
@homerbong plz let me know if you have the same issue with CCXT 1.35.77+, the new build will arrive in 20 minutes. Thx for your feedback!
