### ISSUE TITLE
phemex trailingstoploss not working

### ISSUE THREAD

**Issue by jndennis** [ccxt/ccxt#7624]
i am trying to set a market position with a trailing stop loss, but it dont quite seems to work out here.
im following the parameters here: https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md

- OS: debian 10
- Programming Language version: python3.7.3
- CCXT version: 1.34.37

```
  stop_params = {
      'pegOffsetValueEp': stop_loss*10000,
      'pegPriceType': 'TrailingStopPeg'
    }
  exchange.verbose = True
  order = exchange.create_order('BTC/USD', 'Market', 'buy', contracts, None, stop_params) # open initial position with the 1.1 % stop loss
```

```
Request: POST https://api.phemex.com/orders {'x-phemex-access-token': 'd1648bbe-b983-451d-9df0-5e04a73c52f1', 'x-phemex-request-expiry': '1600875125', 'Content-Type': 'application/json', 'x-phemex-request-signature': 'd3f8a1e1341a06604a08c013bccc401b579dcf34ac560cc10f1bbbb80f74efed', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} {"symbol":"BTCUSD","side":"Buy","ordType":"Market","orderQty":9,"pegOffsetValueEp":103410000,"pegPriceType":"TrailingTakeProfitPeg"}

Response: POST https://api.phemex.com/orders 200 {'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Wed, 23 Sep 2020 15:31:05 GMT', 'Server': 'nginx', 'Vary': 'Accept-Encoding', 'x-phemex-request-tracing': 'f70fa5f0-a306-491d-88c4-0803ca271fd1', 'X-RateLimit-Remaining-CONTRACT': '493', 'X-RateLimit-Capacity-CONTRACT': '500', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'X-XSS-Protection': '1 ; mode=block, 1; mode=block', 'Referrer-Policy': 'no-referrer, origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 efc12fd327e76ab48012cf50cecfdff8.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ARN1-C1', 'X-Amz-Cf-Id': 'h1eTlxyqTYSq77BlN36GPa6UzTUCFGXH2SmDkDLd9XDzWheU7fZ7-g=='} {"code":0,"msg":"","data":{"bizError":0,"orderID":"bd2967f4-a018-4c00-bb82-7023c2cde21d","clOrdID":"","symbol":"BTCUSD","side":"Buy","actionTimeNs":1600875065707401956,"transactTimeNs":0,"orderType":"Market","priceEp":105635000,"price":10563.50000000,"orderQty":9,"displayQty":0,"timeInForce":"ImmediateOrCancel","reduceOnly":false,"closedPnlEv":0,"closedPnl":0E-8,"closedSize":0,"cumQty":0,"cumValueEv":0,"cumValue":0E-8,"leavesQty":9,"leavesValueEv":85199,"leavesValue":0.00085199,"stopDirection":"UNSPECIFIED","stopPxEp":0,"stopPx":0E-8,"trigger":"UNSPECIFIED","pegOffsetValueEp":103410000,"execStatus":"PendingNew","pegPriceType":"TrailingTakeProfitPeg","ordStatus":"Created"}}
jndennis@backup-23044122-debian-2gb-hel1-1:/environments/jn.dennis.btc-trading-bot$ sudo python3 buy.py

Request: POST https://api.phemex.com/orders {'x-phemex-access-token': 'd1648bbe-b983-451d-9df0-5e04a73c52f1', 'x-phemex-request-expiry': '1600875149', 'Content-Type': 'application/json', 'x-phemex-request-signature': '005104a78fc9321caab82fe1ad91176e8bb1afb0c9a137c79c10d594e2b8434a', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} {"symbol":"BTCUSD","side":"Buy","ordType":"Market","orderQty":9,"pegOffsetValueEp":103410000,"pegPriceType":"TrailingStopLossPeg"}

Response: POST https://api.phemex.com/orders 200 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '55', 'Connection': 'keep-alive', 'Date': 'Wed, 23 Sep 2020 15:31:29 GMT', 'Server': 'nginx', 'x-phemex-request-tracing': '70bae466-4a4e-4f39-9fa5-4acc56d9096f', 'X-RateLimit-Remaining-CONTRACT': '482', 'X-RateLimit-Capacity-CONTRACT': '500', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'X-XSS-Protection': '1 ; mode=block, 1; mode=block', 'Referrer-Policy': 'no-referrer, origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 3529bf84e9522012233c3dd2a59fdfe9.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ARN1-C1', 'X-Amz-Cf-Id': 'hu1L7sDE45yzEDDCPJNKceM3ycwl0GbvwmFZngn-HZoGQYCv8lSPSQ=='} {"code":39999,"msg":"Error in place order","data":null}
Traceback (most recent call last):
  File "buy.py", line 34, in <module>
    buy()
  File "/environments/jn.dennis.btc-trading-bot/main.py", line 137, in buy
    order = exchange.create_order('BTC/USD', 'Market', 'buy', contracts, None, stop_params) # open initial position with the 1.1 % stop loss
  File "/usr/local/lib/python3.7/dist-packages/ccxt/phemex.py", line 1725, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/phemex.py", line 2126, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: phemex {"code":39999,"msg":"Error in place order","data":null}

```

**Comment by kroitor** [comment]
@jndennis i think you have to specify the trigger price to it (`stopPxEp`), let me know if this does not help:

```Python
exchange.load_markets()
symbol = 'BTC/USD'
market = exchange.market(symbol)
type = 'market'
side = 'buy'
stop_price = YOUR_STOP_PRICE_HERE  # ←-----------
stop_params = {
    'stopPxEp': exchange.toEp (stop_price, market),
    'pegOffsetValueEp': stop_loss*10000,
    'pegPriceType': 'TrailingStopPeg'
}
exchange.verbose = True
order = exchange.create_order(symbol, type, side, contracts, None, stop_params) # open initial position with the 1.1 % stop loss
```

**Comment by kroitor** [comment]
Let us know if the above does not answer your question. Feel free to reopen this issue or just ask further questions if any.

**Comment by olakemp** [comment]
Hi, I have the same problem, have been trying all variations i can think of but cant create the trailing sl. Here is the response I get from API **/orders/create**
`{"code":0,"msg":"","data":{"bizError":0,"orderID":"863e3594-ced5-4ed1-ba14-4caed33291d9","clOrdID":"4EAAB8A6B0CFFB009524E16C77239CFE","symbol":"ETHUSD","side":"Buy","actionTimeNs":1643496990324801667,"transactTimeNs":1643496990324801667,"orderType":"Market","priceEp":26763500,"price":2676.35000000,"orderQty":1,"displayQty":0,"timeInForce":"ImmediateOrCancel","reduceOnly":false,"closedPnlEv":0,"closedPnl":0E-8,"closedSize":0,"cumQty":0,"cumValueEv":0,"cumValue":0E-8,"leavesQty":1,"leavesValueEv":133817,"leavesValue":13.38170000,"stopDirection":"UNSPECIFIED","stopPxEp":25974500,"stopPx":2597.45000000,"trigger":"ByLastPrice","pegOffsetValueEp":-519500,"execStatus":"PendingNew","pegPriceType":"TrailingStopPeg","ordStatus":"Created"}}`

The query I PUT is following:
`?clOrdID=4EAAB8A6B0CFFB009524E16C77239CFE&symbol=ETHUSD&side=Buy&orderQty=1&ordType=Market&stopPxEp=25974500&triggerType=ByLastPrice&takeProfitEp=29871250&stopLossEp=25455500&slTrigger=ByLastPrice&tpTrigger=ByLastPrice&pegPriceType=TrailingStopPeg&pegOffsetValueEp=-519500`

The order is accepted but no Trailing SL
Here is a screencap of the above order in UI
![image](https://user-images.githubusercontent.com/98640373/151680322-b7164952-9b8c-469c-981b-30eab4f08e43.png)

**Comment by kroitor** [comment]
@olakemp please, paste the following info here, including your ccxt version, your complete short code snippet and your verbose request-response output (enable verbose mode):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by danschumann** [comment]
The API says negative values when the position is long.  Perhaps you're posting a positive number?  Or maybe it's not scaled (EP)?
