### ISSUE TITLE
Bithumb "fetch_balance()" does not work.

### ISSUE THREAD

**Issue by Eavan0103** [ccxt/ccxt#7687]
After upgrade 1.35.24.....
Bithumb "fetch_balance()" does not work.
bithumb.fetch_balance()
Traceback (most recent call last):

  File "<ipython-input-2-11990f3665fa>", line 1, in <module>
    bithumb.fetch_balance()

  File "C:\Anaconda3\lib\site-packages\ccxt\bithumb.py", line 164, in fetch_balance
    response = self.privatePostInfoBalance(self.extend(request, params))

  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Anaconda3\lib\site-packages\ccxt\bithumb.py", line 744, in request
    response = self.fetch2(path, api, method, params, headers, body)

  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 597, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\Anaconda3\lib\site-packages\ccxt\bithumb.py", line 740, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, feedback)

  File "C:\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)

AuthenticationError: bithumb {"status":"5100","message":"Bad Request.(Auth Data)"}

**Comment by kroitor** [comment]
Please, update to 1.35.25 in 20 minutes, this is a minor leftover after the recent update. Let us know if you have further difficulties after that. Thanks for your feedback!

**Comment by Eavan0103** [comment]
> Please, update to 1.35.25 in 20 minutes, this is a minor leftover after the recent update. Let us know if you have further difficulties after that. Thanks for your feedback!

Thank you to you for making use of this great module.

**Comment by Eavan0103** [comment]
> Please, update to 1.35.25 in 20 minutes, this is a minor leftover after the recent update. Let us know if you have further difficulties after that. Thanks for your feedback!

Thank you for making great ccxt.
