### ISSUE TITLE
[bittrex] watchOrderBook

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7691]
Calling `watchOrderBook` on bittrex results in the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:293:9)
    at Object.inflate64 (node_modules/ccxt.pro/js/base/functions.js:10:28)
    at bittrex.inflate64 (node_modules/ccxt.pro/js/base/Exchange.js:19:26)
    at bittrex.handleExchangeState (node_modules/ccxt.pro/js/bittrex.js:910:31)
    at bittrex.handleSubscriptionStatus (node_modules/ccxt.pro/js/bittrex.js:1017:20)
    at bittrex.handleMessage (node_modules/ccxt.pro/js/bittrex.js:1064:18)
```

I trapped the problematic message:

```
{
  I: '1601977997791',
  E: "There was an error invoking Hub method 'c2.QueryExchangeState'."
}
```

I'm calling it with these  'ADA/BTC' and this:

        const exchange = new ccxtpro[exchangeId]({
            enableRateLimit: true,
            timeout: 60 * 1000
        });

(will try to narrow the problem down)

**Comment by kroitor** [comment]
It is temporarily broken after it was updated to v3, the WS implementation still hits v2, the work on Bittrex WS v3 is done by 90% at this point and we will most likely merge it today.

**Comment by npomfret** [comment]
ah I see, thanks

**Comment by npomfret** [comment]
ah I see, thanks

**Comment by kroitor** [comment]
Upgraded to v3 in CCXT Pro 0.4.1+. Thanks for your feedback!
