### ISSUE TITLE
TypeError: parse_transaction() takes 2 positional arguments but 3 were given while fetching deposits

### ISSUE THREAD

**Issue by optima66** [ccxt/ccxt#7744]
Last version of ccxt and python

```
        exchange_id = 'ftx'
        exchange_class = getattr(ccxt, exchange_id)
        ccxt_exchange= exchange_class({
             'apiKey': 'YOUR_API_KEY',
             'secret': 'YOUR_SECRET',
             'timeout': 30000,
            'enableRateLimit': True,
         })

deposits = ccxt_exchange.fetch_deposits( )

```
This gives me an error:

```
   File "/usr/local/lib/python3.6/dist-packages/ccxt/ftx.py", line 1391, in fetch_deposits
    return self.parse_transactions(result)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1672, in parse_transactions
    array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1672, in <listcomp>
    array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]
TypeError: parse_transaction() takes 2 positional arguments but 3 were given
```

Screenshot with more info:
https://prnt.sc/uwa48n

**Comment by kroitor** [comment]
@optima66 please always paste your verbose request+response and specific version numbers!

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help (read this very carefully)

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange_id = 'ftx'
exchange_class = getattr(ccxt, exchange_id)
exchange= exchange_class({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

exchange.load_markets()

exchange.verbose = True

deposits = exchange.fetch_deposits( )
pprint(deposits)
```

↑ Paste the entire output, plz.

**Comment by optima66** [comment]
```
Request: GET https://ftx.com/api/wallet/deposits {'FTX-KEY': 'J3i-CaPsdfdsfdsQRoEdfdd0UtOL', 'FTX-TS': '1602270370029', 'FTX-SIGN': '124ed2dssdf4bdsfdsf64f1a796dsfdsfds907e8e4977ddc4', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://ftx.com/api/wallet/deposits 200 {'Date': 'Fri, 09 Oct 2020 19:06:10 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dea2afbdc4361cdff6f0f6d7562b369931602270370; expires=Sun, 08-Nov-20 19:06:10 GMT; path=/; domain=.ftx.com; HttpOnly; SameSite=Lax; Secure', 'Vary': 'Accept-Encoding, Origin', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': '4741135', 'ETag': 'W/"4043cc9e7e283015e2eb482e3934250e"', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'MISS', 'cf-request-id': '05b05ab10300007b77093e1200000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '5dfa6094d92c7b77-DME', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400'} {"result":[{"coin":"USD","id":366463,"notes":"Goodwill distribution","size":5.0,"status":"complete","time":"2020-09-04T19:53:53.451391+00:00"},{"address":{"address":"TDHNn5RvH3jmcefgsVd9fXfit1fFAaUTUG","tag":null},"coin":"USDT","confirmations":28,"confirmedTime":"2020-09-03T19:07:50.807247+00:00","fee":0.0,"id":314465,"sentTime":"2020-09-03T19:06:06+00:00","size":1200.0,"status":"confirmed","time":"2020-09-03T19:07:50.807247+00:00","txid":"8d4d723803ab043a58ae471743458e0539357b2dcee389ccbd1a6b2d72bd5f73"},{"address":{"address":"TDHNn5RvH3jmcefgsVd9fXfit1fFAaUTUG","tag":null},"coin":"USDT","confirmations":32,"confirmedTime":"2020-09-02T11:30:47.353142+00:00","fee":0.0,"id":306975,"sentTime":"2020-09-02T11:28:45+00:00","size":1200.0,"status":"confirmed","time":"2020-09-02T11:30:47.353142+00:00","txid":"ad22f43113637a3076df881117e38fa4aafb48d173446e1771731f4dd7e4c7a7"},{"address":{"address":"TDHNn5RvH3jmcefgsVd9fXfit1fFAaUTUG","tag":null},"coin":"USDT","confirmations":38,"confirmedTime":"2020-08-31T19:11:40.707210+00:00","fee":0.0,"id":297465,"sentTime":"2020-08-31T19:09:39+00:00","size":1000.0,"status":"confirmed","time":"2020-08-31T19:11:40.707210+00:00","txid":"2ae62d91cf42721f96c0a6be2e4f0ac192aa8577522bff2c261ae5b82fa75f71"},{"address":{"address":"TDHNn5RvH3jmcefgsVd9fXfit1fFAaUTUG","tag":null},"coin":"USDT","confirmations":23,"confirmedTime":"2020-08-26T20:23:07.298761+00:00","fee":0.0,"id":281117,"sentTime":"2020-08-26T20:21:51+00:00","size":1261.67364,"status":"confirmed","time":"2020-08-26T20:23:07.298761+00:00","txid":"b862979c3611bbfcaec3df5b30b6155c4d9337ad48978f7d600356daba32fcd8"},{"address":{"address":"TDHNn5RvH3jmcefgsVd9fXfit1fFAaUTUG","tag":null},"coin":"USDT","confirmations":24,"confirmedTime":"2020-08-26T19:41:07.604413+00:00","fee":0.0,"id":281067,"sentTime":"2020-08-26T19:39:42+00:00","size":100.0,"status":"confirmed","time":"2020-08-26T19:41:07.604413+00:00","txid":"acb135b6a5f6d489f447b97c2e86f53ec6bc8ac2c4c6f61b3b8d9d608a6b59f8"}],"success":true}

```
```
Internal Server Error: /get_exchange_data
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/coins/coins_new/coins_new2/main_app/other_models/exchange.py", line 101, in ccxt_binance
    deposits = exchange.fetch_deposits( )
  File "/usr/local/lib/python3.6/dist-packages/ccxt/ftx.py", line 1391, in fetch_deposits
    return self.parse_transactions(result)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1672, in parse_transactions
    array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1672, in <listcomp>
    array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]
TypeError: parse_transaction() takes 2 positional arguments but 3 were given
```

**Comment by kroitor** [comment]
@optima66 please, update to the most recent version of CCXT and let us know if you still have the same issue with the most recent version of the lib.

**Comment by optima66** [comment]
It works thanks!
no deposit history on bitmex yet btw?

**Comment by kroitor** [comment]
@optima66 

> It works thanks!

Yep! Updating to the most recent version is the first step of the troubleshooting sequence, regardless of the issue:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

This lib is updated frequently, so I'd recommend to keep your version up to date.

> no deposit history on bitmex yet btw?

BitMEX does not have fetchTransactions, fetchDeposits or fetchWithdrawals, but it has fetchLedger instead.

- https://github.com/ccxt/ccxt/wiki/Manual#ledger
