### ISSUE TITLE
CCXT Pro installation issue

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#7747]
Hello,

I subscribed to the CCXT Pro version and made a payment but didn't received the licence.

Also I followed the documentation to install the package but I received the following error:

```
(envdev) xxx@fff-lenovo-ideapad-710s-13isk:~/python/app$ pip3 install git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python
Collecting git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python
  Cloning https://github.com/kroitor/ccxt.pro.git to /tmp/pip-req-build-n9bqc1l0
Username for 'https://github.com': Kinzowa
Password for 'https://Kinzowa@github.com': 
ERROR: Command errored out with exit status 128: git clone -q https://github.com/kroitor/ccxt.pro.git /tmp/pip-req-build-n9bqc1l0 Check the logs for full command output.

```

Thank you,

**Comment by kroitor** [comment]
Hi!

> I subscribed to the CCXT Pro version and made a payment but didn't received the licence.

The license is given to your GitHub account automatically, it's not a standalone entity.

> Also I followed the documentation to install the package but I received the following error:
> `pip3 install git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python`

Do you have your `git` configured over SSH? 

> Check the logs for full command output.

What's in the log file?

```
pip3 install git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python --log YOUR_LOGFILE
```

**Comment by kroitor** [comment]
Is it a Windows OS machine?

If you're signed in to GitHub as `Kinzowa`, you should be able to access the repository via GitHub at https://github.com/kroitor/ccxt.pro – do you see it, can you access it? As far as we see, you have accepted the invitation to the repo already.

**Comment by Kinzowa** [comment]
Hi Igor,

It's a linux machine with Python environement. Please find the result of the log file:

```
pip3 install git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python --log git.log

2020-10-10T10:47:52,148 Using pip 20.2.3 from /home/xxx/python/envdev/lib/python3.6/site-packages/pip (python 3.6)
2020-10-10T10:47:52,148 Non-user install because user site-packages disabled
2020-10-10T10:47:52,303 Created temporary directory: /tmp/pip-ephem-wheel-cache-olbo9nit
2020-10-10T10:47:52,303 Created temporary directory: /tmp/pip-req-tracker-co_5mdy1
2020-10-10T10:47:52,303 Initialized build tracking at /tmp/pip-req-tracker-co_5mdy1
2020-10-10T10:47:52,303 Created build tracker: /tmp/pip-req-tracker-co_5mdy1
2020-10-10T10:47:52,303 Entered build tracker: /tmp/pip-req-tracker-co_5mdy1
2020-10-10T10:47:52,304 Created temporary directory: /tmp/pip-install-cnny2avg
2020-10-10T10:47:52,306 Collecting git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python
2020-10-10T10:47:52,307   Created temporary directory: /tmp/pip-req-build-35mffqjq
2020-10-10T10:47:52,307   Cloning https://github.com/kroitor/ccxt.pro.git to /tmp/pip-req-build-35mffqjq
2020-10-10T10:48:09,522 ERROR: Command errored out with exit status 128: git clone -q https://github.com/kroitor/ccxt.pro.git /tmp/pip-req-build-35mffqjq Check t
he logs for full command output.
2020-10-10T10:48:09,522 Exception information:
2020-10-10T10:48:09,522 Traceback (most recent call last):
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
2020-10-10T10:48:09,522     status = self.run(options, args)
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
2020-10-10T10:48:09,522     return func(self, options, args)
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 324, in run
2020-10-10T10:48:09,522     reqs, check_supported_wheels=not options.target_dir
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
2020-10-10T10:48:09,522     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
2020-10-10T10:48:09,522     abstract_dist = self._get_abstract_dist_for(req_to_install)
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_d
ist_for
2020-10-10T10:48:09,522     abstract_dist = self.preparer.prepare_linked_requirement(req)
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 469, in prepare_linked_requirem
ent
2020-10-10T10:48:09,522     hashes=self._get_linked_req_hashes(req)
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 239, in unpack_url
2020-10-10T10:48:09,522     unpack_vcs_link(link, location)
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 99, in unpack_vcs_link
2020-10-10T10:48:09,522     vcs_backend.unpack(location, url=hide_url(link.url))
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/vcs/versioncontrol.py", line 733, in unpack
2020-10-10T10:48:09,522     self.obtain(location, url=url)
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/vcs/versioncontrol.py", line 641, in obtain
2020-10-10T10:48:09,522     self.fetch_new(dest, url, rev_options)
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/vcs/git.py", line 230, in fetch_new
2020-10-10T10:48:09,522     self.run_command(make_command('clone', '-q', url, dest))
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/vcs/versioncontrol.py", line 774, in run_command
2020-10-10T10:48:09,522     log_failed_cmd=log_failed_cmd)
2020-10-10T10:48:09,522   File "/home/xxx/python/envdev/lib/python3.6/site-packages/pip/_internal/vcs/versioncontrol.py", line 166, in call_subprocess
2020-10-10T10:48:09,522     raise SubProcessError(exc_msg)
2020-10-10T10:48:09,522 pip._internal.exceptions.SubProcessError: Command errored out with exit status 128: git clone -q https://github.com/kroitor/ccxt.pro.git 
/tmp/pip-req-build-35mffqjq Check the logs for full command output.
2020-10-10T10:48:09,583 Removed build tracker: '/tmp/pip-req-tracker-co_5mdy1'
```

**Comment by Kinzowa** [comment]
Oh, I found the issue it was an authentication problem

**Comment by kroitor** [comment]
@Kinzowa thx for reporting back! Let me know if you have any further difficulties with it.
