### ISSUE TITLE
Coinfalcon fetchOpenOrders issue

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#7749]
Trying to get all open orders:

```
fetch:
 coinfalcon GET https://coinfalcon.com/api/v1/markets

 {"data":[{"name":"IOT-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.00033481","last_price":"0.0000245","highest_bid":"0.00002261","lowest_ask":"0.00002461","change_in_24h":"0.0","size_precision":8,"price_precision":8},{"name":"ETH-BTC","precision":6,"min_volume":"0.00000001","min_price":"0.000001","volume":"0.050931","last_price":"0.033364","highest_bid":"0.032179","lowest_ask":"0.033149","change_in_24h":"2.66","size_precision":8,"price_precision":6},{"name":"LTC-BTC","precision":5,"min_volume":"0.00000001","min_price":"0.00001","volume":"0.18394","last_price":"0.0044","highest_bid":"0.00429","lowest_ask":"0.0044","change_in_24h":"3.04","size_precision":8,"price_precision":5},{"name":"BTC-EUR","precision":2,"min_volume":"0.00000001","min_price":"0.01","volume":"18969.49","last_price":"9649.9","highest_bid":"9559.91","lowest_ask":"9680.77","change_in_24h":"2.66","size_precision":8,"price_precision":2},{"name":"BCH-BTC","precision":5,"min_volume":"0.00000001","min_price":"0.00001","volume":"0.01422","last_price":"0.0215","highest_bid":"0.02151","lowest_ask":"0.02259","change_in_24h":"-0.69","size_precision":8,"price_precision":5},{"name":"TRX-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.02938606","last_price":"0.00000238","highest_bid":"0.00000235","lowest_ask":"0.00000249","change_in_24h":"-0.42","size_precision":8,"price_precision":8},{"name":"ECA-BTC","precision":9,"min_volume":"1.0","min_price":"0.000000001","volume":"0.12387082","last_price":"0.000000016","highest_bid":"0.000000015","lowest_ask":"0.000000016","change_in_24h":"0.0","size_precision":0,"price_precision":9},{"name":"ECA-ETH","precision":7,"min_volume":"1.0","min_price":"0.0000001","volume":"0.0613402","last_price":"0.0000005","highest_bid":"0.0000004","lowest_ask":"0.0000006","change_in_24h":"0.0","size_precision":0,"price_precision":7},{"name":"XRP-BTC","precision":8,"min_volume":"0.00000001","min_price":"0.00000001","volume":"0.14939994","last_price":"0.00002245","highest_bid":"0.00001871","lowest_ask":"0.00002303","change_in_24h":"-3.27","size_precision":8,"price_precision":8},{"name":"ADA-BTC","precision":8,"min_volume":"0.000001","min_price":"0.00000001","volume":"0.05202867","last_price":"0.00000941","highest_bid":"0.00000904","lowest_ask":"0.00000971","change_in_24h":"12.97","size_precision":6,"price_precision":8},{"name":"ADA-ETH","precision":8,"min_volume":"0.000001","min_price":"0.00000001","volume":"0.29803495","last_price":"0.000268","highest_bid":"0.0002555","lowest_ask":"0.00027199","change_in_24h":"2.26","size_precision":6,"price_precision":8},{"name":"DOGE-BTC","precision":8,"min_volume":"0.00001","min_price":"0.00000001","volume":"0.07835685","last_price":"0.00000025","highest_bid":"0.00000024","lowest_ask":"0.00000025","change_in_24h":"0.0","size_precision":5,"price_precision":8},{"name":"IOT-EUR","precision":4,"min_volume":"0.00001","min_price":"0.0001","volume":"109.6078","last_price":"0.232","highest_bid":"0.2248","lowest_ask":"0.232","change_in_24h":"-0.17","size_precision":5,"price_precision":4},{"name":"BTC-USDT","precision":2,"min_volume":"0.00000001","min_price":"0.01","volume":"792.48","last_price":"9800.03","highest_bid":"9800.02","lowest_ask":"10999.97","change_in_24h":"-12.67","size_precision":8,"price_precision":2},{"name":"ETH-USDT","precision":2,"min_volume":"0.00001","min_price":"0.01","volume":"11.25","last_price":"375.0","highest_bid":"290.02","lowest_ask":"374.99","change_in_24h":"9.97","size_precision":5,"price_precision":2},{"name":"GRN-USDT","precision":7,"min_volume":"1.0","min_price":"0.0000001","volume":"17.656731","last_price":"0.006456","highest_bid":"0.006275","lowest_ask":"0.006456","change_in_24h":"-48.41","size_precision":0,"price_precision":7}]}

fetch:
 coinfalcon GET https://coinfalcon.com/api/v1/user/orders

 coinfalcon GET https://coinfalcon.com/api/v1/user/orders 200 OK
Response:

 {"data":[{............................},{"id":"8311dc97-ffd4-487b-8ff3-0544c8b53d6f","market":"GRN-ETH","price":"0.00000573","size":"4336.10855","size_filled":"0.0","fee":"0.0","fee_currency_code":"eth","funds":"4336.10855","status":"canceled","order_type":"sell","post_only":false,"operation_type":"limit_order","created_at":"2020-08-23T23:23:44.413591Z"}]}

TypeError: Cannot read property 'precision' of undefined
    at coinfalcon.amountToPrecision (/var/www/*/node_modules/ccxt/js/base/Exchange.js:1286:75)
    at coinfalcon.parseOrder (/var/www/*/node_modules/ccxt/js/coinfalcon.js:312:46)
    at /var/www/*/node_modules/ccxt/js/base/Exchange.js:1148:79
    at Array.map (<anonymous>)
    at coinfalcon.parseOrders (/var/www/*/node_modules/ccxt/js/base/Exchange.js:1148:45)
    at coinfalcon.fetchOpenOrders (/var/www/*/node_modules/ccxt/js/coinfalcon.js:401:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async test (/var/www/*/test.js:171:24)
```

It happens because Coinfalcon had already removed this market `GRN/ETH` so `this.markets` doesn't know it. But they still give this market in this query. What the best way to avoid this situation?

**Comment by kroitor** [comment]
> What the best way to avoid this situation?

The `symbol` itself is parsed by `safeSymbol` or `safeMarket`, as for the values in `cost` and `remaining` - those can't be rounded to precision, since the precision info is missing in this case. I've removed the client-side formatting from there (not sure if really belongs there), so it should work as of next build. Let me know if that does not help.

**Comment by ndubel** [comment]
but now we have some `canceled` orders together with `open`. We need to filter them by status

**Comment by ndubel** [comment]
I see comment: 
`// TODO: test status=all if it works for closed orders too`
Looks like yes. With `all` it gives `open`, `closed` and `canceled` (100 records) and if we leave it blanced it gives `open` orders and sometimes a few strange `canceled` orders.
So it's possible to create `fetchOrders` and `fetchClosedOrders`

**Comment by kroitor** [comment]
@ndubel hope to get to it asap, your help is very much appreciated!
