### ISSUE TITLE
Issues with since in bybit.js fetchOHLCV

### ISSUE THREAD

**Issue by bigcountry-scav** [ccxt/ccxt#7755]
Receiving the below error message when fetching ohlcv data on Bybit if since is undefined. I am also seeing a truncated since when it is specified (https://api.bybit.com/v2/public/kline/list?symbol=BTCUSD&interval=60&from=1601756&limit=200) .

- OS: Windows 10
- Programming Language version: JS
- CCXT version: 1.36.2

```
var ccxt = require("ccxt");

const exchangeID = "bybit"
const exchangeClass = ccxt[exchangeID];
exchange = new exchangeClass({
  "apiKey": "",
  "secret": "",
  "timeout": 5000,
  "enableRateLimit": true,
  "verbose": true
});

(async function () {
  let markets, ohlcvData;

  // load markets
  markets = await exchange.fetchMarkets();

  // console.log(markets);

  ohlcvData = await exchange.fetchOHLCV("BTC/USD", 60, null, 200);

  console.log(ohlcvData);

  ohlcvData = await exchange.fetchOHLCV("BTC/USD", 60, 1601756857, 200);

  console.log(ohlcvData);
}) ();
```

```
(node:414) UnhandledPromiseRejectionWarning: TypeError: timeframe.slice is not a function
    at bybit.parseTimeframe (/home/runner/StainedAuthorizedAmoeba/node_modules/ccxt/js/base/functions/misc.js:10:30)
    at bybit.fetchOHLCV (/home/runner/StainedAuthorizedAmoeba/node_modules/ccxt/js/bybit.js:699:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/runner/StainedAuthorizedAmoeba/index.js:21:15
(node:414) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:414) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
@bigcountry-scav you're using wrong params for the `timeframe` and for the `since` params.

- https://github.com/ccxt/ccxt/blob/master/js/bybit.js#L45
- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

The `since` argument must be a timestamp in milliseconds (not seconds as in your code)!
The `timeframe` must be a unified timeframe string like `'1m'`, `'5m'`, `'1h'`, `'1d'`, etc:

```JavaScript
const ccxt = require('./ccxt');

(async () => {
    const exchange = new ccxt.bybit({
        'enableRateLimit': true,  // required by the Manual
    })

    console.log('Supported timeframes:', exchange.timeframes)

    const symbol = 'BTC/USD'
    const timeframe = '1m'
    const since = exchange.parse8601('2020-03-03T01:02:03Z')

    ohlcv = await exchange.fetchOHLCV(symbol, timeframe, since)
    console.log(ohlcv.map(o => [ exchange.iso8601(o[0]), ... o.slice (1) ]))

}) ()
```

Let us know if the above does not answer the question. In general, I'd recommend to read the entire Manual from top to bottom and always follow the documented argument formats precisely.

**Comment by bigcountry-scav** [comment]
Sorry was late when I typed up the replication code yes I was using the supported timeframes just not in replicated code and the issue appears the from sent to bybit is 0 when running debug. Millis conversion fixed the truncation issue as expected.

```
var ccxt = require("ccxt");

const exchangeID = "bybit"
const exchangeClass = ccxt[exchangeID];
exchange = new exchangeClass({
  "apiKey": "",
  "secret": "",
  "timeout": 5000,
  "enableRateLimit": true,
  "verbose": true
});

(async function () {
  let markets, ohlcvData, since;

  // load markets
  markets = await exchange.fetchMarkets();

  // console.log(markets);

  ohlcvData = await exchange.fetchOHLCV("BTC/USD", "1h", null, 200);

  console.log(ohlcvData);
}) ();
```

```
fetch:
 bybit GET https://api.bybit.com/v2/public/kline/list?symbol=BTCUSD&interval=60&from=0&limit=200 
Request:
 {} 
 undefined 

handleRestResponse:
 bybit GET https://api.bybit.com/v2/public/kline/list?symbol=BTCUSD&interval=60&from=0&limit=200 200 OK 
Response:
 {
  'Cache-Control': 'max-age=0, no-cache, no-store',
  Connection: 'keep-alive',
  'Content-Length': '160',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Mon, 12 Oct 2020 12:51:22 GMT',
  Expires: 'Mon, 12 Oct 2020 12:51:22 GMT',
  Pragma: 'no-cache'
} 
 {"ret_code":10001,"ret_msg":"Param validation for 'from' failed on the 'required' tag","ext_code":"","ext_info":"","result":null,"time_now":"1602507082.736607"} 

(node:129) UnhandledPromiseRejectionWarning: BadRequest: bybit {"ret_code":10001,"ret_msg":"Param validation for 'from' failed on the 'required' tag","ext_code":"","ext_info":"","result":null,"time_now":"1602507082.736607"}
    at bybit.throwExactlyMatchedException (/home/runner/StainedAuthorizedAmoeba/node_modules/ccxt/js/base/Exchange.js:532:19)
    at bybit.handleErrors (/home/runner/StainedAuthorizedAmoeba/node_modules/ccxt/js/bybit.js:2147:18)
    at /home/runner/StainedAuthorizedAmoeba/node_modules/ccxt/js/base/Exchange.js:603:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (/home/runner/StainedAuthorizedAmoeba/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async bybit.fetchOHLCV (/home/runner/StainedAuthorizedAmoeba/node_modules/ccxt/js/bybit.js:716:26)
    at async /home/runner/StainedAuthorizedAmoeba/index.js:21:15
(node:129) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:129) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bigcountry-scav** [comment]
Actually found the issue and it is because I am sending null for since instead of undefined.

**Comment by kroitor** [comment]
@bigcountry-scav thx for reporting back!
