### ISSUE TITLE
ZB order can be parsed buy orders can't

### ISSUE THREAD

**Issue by monk-after-90s** [ccxt/ccxt#7757]
Hi, bug for ZB.
```python
import ccxt
ccxt.__version__
```
```
'1.36.2'
```
```python
zb=ccxt.zb({"apiKey": "dhflawfhauiewfhiwefhbiae","secret": "o328u708eyroquy239r8y23ruodh" })
open_orders=zb.fetch_open_orders('UFO/QC')
print(open_orders)
```
```python
[]
```
```python
raw_open_orders=zb.private_get_getunfinishedordersignoretradetype(params={'currency':'ufo_qc'})
print(raw_open_orders)
```
```
[{'total_amount': 50.0, 'id': '2020101210865115', 'price': 2.0, 'trade_date': 1602490586485, 'st...
```
```python
zb.parse_order(raw_open_orders[0])
```
```
{'info': {'total_amount': 50.0, 'id': '2020101210865115', 'price': 2.0, 'trade_date': 1602490586485, 'status': 3, 'trade_money': 0.0, 'acctType': 0, 'trade_amount': 0.0, 'type': 1, 'currency': 'ufo_qc'}, 'id': '2020101210865115', 'clientOrderId': None, 'tim...
```
```python
zb.parse_orders(raw_open_orders)
```
```
[]
```
To conclude, the method fetch_open_orders returns empty list, however the right private method could get the raw list.
And the method parse_order could correctly parse single one raw order, the method parse_orders would return empty list however.
Similar phenomenon arise when testing other fetch methods.
So Iguess the method parse_orders has bugs inside for ZB.

**Comment by kroitor** [comment]
Hi @monk-after-90s !

I'm getting this with your code, looks like the above key does not work anymore:

```
>>> raw_open_orders=zb.private_get_getunfinishedordersignoretradetype(params={'currency':'ufo_qc'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 618, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/igorkroitor/ccxt/python/ccxt/zb.py", line 590, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, code, feedback)
  File "/Users/igorkroitor/ccxt/python/ccxt/base/exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: zb {"code":3005,"message":"Invalid Arguments"}
```

Please, paste your full verbose output unedited:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange=ccxt.zb({
    "apiKey": "dhflawfhauiewfhiwefhbiae",
    "secret": "o328u708eyroquy239r8y23ruodh",
    "enableRateLimit": True,  # as required by the Manual! https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

exchange.load_markets()
exchange.verbose = True  # ←------------ add verbose mode after loading the markets

open_orders=exchange.fetch_open_orders('UFO/QC')
print(open_orders)
```

**Comment by monk-after-90s** [comment]
@kroitor Ah, I notice that the version has a rollback from 1.36.2 to 1.36.10, and the bug disappears.
