### ISSUE TITLE
Bitmart Sell Orders throw error

### ISSUE THREAD

**Issue by adeel94mirza** [ccxt/ccxt#7786]
Hey! I am getting this error for sell order with bitmart. Buy orders work flawlessly but no sell orders are getting placed and it seems that CCXT is returning the mentioned error. Awaiting response as this is crucial for my project, TIA!

- OS: Linux
- Programming Language version: Nodejs
- CCXT version: 1.35.65

```
const sellOrder = await bitmart.createOrder(parsedSymbol, 'market', 'sell', amount, price)
```

```
Error: TICK_SIZE cant be used with negative or zero numPrecisionDigits
    at decimalToPrecision (C:\Node\CP\trading-bot\node_modules\ccxt\js\base\functions\number.js:101:19)
    at MyBitmart.amountToPrecision (C:\Node\CP\trading-bot\node_modules\ccxt\js\base\Exchange.js:1277:16)
    at MyBitmart.createOrder (C:\Node\CP\trading-bot\node_modules\ccxt\js\bitmart.js:1685:44)
    at async Timeout._onTimeout (C:\Node\CP\trading-bot\app\Commands\VolumeBitmart.js:66:27)
```

**Comment by kroitor** [comment]
Hi! Please, paste your verbose output!

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

```JavaScript
console.log ('CCXT Version', ccxt.version)
await bitmart.loadMarkets ()
bitmart.verbose = true  // enable verbose mode after loading the markets to avoid too much output
const sellOrder = await bitmart.createOrder(parsedSymbol, 'market', 'sell', amount, price)
```

↑ Please, paste your full output here.

**Comment by adeel94mirza** [comment]
`CCXT Version 1.35.65
{
  parsedSymbol: 'ETH/USDT',
  type: 'market',
  side: 'sell',
  amount: 0.026215755669157164,
  price: 381.45
}
Error: TICK_SIZE cant be used with negative or zero numPrecisionDigits
    at decimalToPrecision (C:\Node\CP\trading-bot\node_modules\ccxt\js\base\functions\number.js:101:19)
    at MyBitmart.amountToPrecision (C:\Node\CP\trading-bot\node_modules\ccxt\js\base\Exchange.js:1276:16)
    at MyBitmart.createOrder (C:\Node\CP\trading-bot\node_modules\ccxt\js\bitmart.js:1685:44)
    at async Timeout._onTimeout (C:\Node\CP\trading-bot\app\Commands\VolumeBitmart.js:74:27)`

**Comment by adeel94mirza** [comment]
Here you go

`
CCXT Version 1.35.65

{
  parsedSymbol: 'ETH/USDT',
  type: 'market',
  side: 'sell',
  amount: 0.026215755669157164,
  price: 381.45
}

Error: TICK_SIZE cant be used with negative or zero numPrecisionDigits
    at decimalToPrecision (C:\Node\CP\trading-bot\node_modules\ccxt\js\base\functions\number.js:101:19)
    at MyBitmart.amountToPrecision (C:\Node\CP\trading-bot\node_modules\ccxt\js\base\Exchange.js:1276:16)
    at MyBitmart.createOrder (C:\Node\CP\trading-bot\node_modules\ccxt\js\bitmart.js:1685:44)
    at async Timeout._onTimeout (C:\Node\CP\trading-bot\app\Commands\VolumeBitmart.js:74:27)
`

**Comment by adeel94mirza** [comment]
I am fiddling around and found that if I change **this.markets[symbol].precision.amount** to **this.markets[symbol].precision.price** in _amountToPrecision_ function in Exchange.js then sell order is placed

**Comment by adeel94mirza** [comment]
Hey @kroitor , Need to re-open as the issue still persists!

**Comment by kroitor** [comment]
@adeel94mirza please, update to version 1.36.32+ (it will arrive within 15 minutes) and let us know if you still have issues with it.

**Comment by adeel94mirza** [comment]
I updated already, will wait and let you know.

**Comment by kroitor** [comment]
@adeel94mirza make sure your version of CCXT is 1.36.32+ (it has arrived) and try this snippet with the new version:

```JavaScript
console.log ('CCXT Version', ccxt.version)
await bitmart.loadMarkets ()
bitmart.verbose = true  // enable verbose mode after loading the markets to avoid too much output

console.log ({ parsedSymbol, type: 'market', side: 'sell', amount, price })

const sellOrder = await bitmart.createOrder(parsedSymbol, 'market', 'sell', amount, price)
```
