### ISSUE TITLE
Subscription to several markets

### ISSUE THREAD

**Issue by Avarong** [ccxt/ccxt#7886]
- OS: windows10
- Programming Language version:python 3.7
- CCXT version:last

```
exchange=ccxtpro.idex({'enableRateLimit':True})
async def orderbooks(inst):
    while True:
        market=inst['market']
        orderbook=await exchange.watch_order_book(market+'/ETH')
        print(orderbook)
def upd():

    for inst in start.instruments:
        asyncio.ensure_future(orderbooks(inst))
 
upd()
```

```
Task exception was never retrieved
future: <Task finished coro=<main.<locals>.orderbooks() done, defined at D:/1/pycharmccxt/IDEXbot.py:123> exception=InvalidNonce('idex failed to synchronize WebSocket feed with the snapshot for symbol QNT/ETH after 10000 milliseconds')>
Traceback (most recent call last):
  File "D:/1/pycharmccxt/IDEXbot.py", line 133, in orderbooks
    orderbook=await exchange.watch_order_book(market+'/ETH')
  File "D:\1\pycharmccxt\ccxtpro\idex.py", line 376, in watch_order_book
    return await self.after(future, self.limit_order_book, symbol, limit)
  File "D:\1\pycharmccxt\ccxtpro\base\exchange.py", line 81, in after
    return method(await future, *args)
  File "D:\1\pycharmccxt\ccxtpro\idex.py", line 59, in subscribe
    return await self.watch(url, messageHash, request, messageHash, subscription)
  File "D:\1\pycharmccxt\ccxtpro\idex.py", line 354, in fetch_order_book_snapshot
    raise InvalidNonce(self.id + ' failed to synchronize WebSocket feed with the snapshot for symbol ' + symbol + endpart)
ccxt.base.errors.InvalidNonce: idex failed to synchronize WebSocket feed with the snapshot for symbol QNT/ETH after 10000 milliseconds
```

**Comment by kroitor** [comment]
> `raise InvalidNonce(self.id + ' failed to synchronize WebSocket feed with the snapshot for symbol ' + symbol + endpart)`

Basically, this message says that there were no WS updates for the market in question for a long time, making it impossible to synchronize it with the orderbook snapshot.

If you add some basic error handling and repeat your attempt, it will eventually succeed when there's some activity on the market.

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

```Python
while True:
    market=inst['market']
    symbol = market+'/ETH'
    try:
        orderbook=await exchange.watch_order_book(symbol)
        print(orderbook)
    except ccxt.InvalidNonce as e:
        print(symbol, type(e).__name__, e.args)
        # repeat after a while
        await exchange.sleep(10000)
```

On liquidity – you might want to contact the IDEX tech support directly.
Let us know if that does not answer your question.
