### ISSUE TITLE
CCXT Pro IDEX fetchBalance object has no attribute 'privateGetBalances'

### ISSUE THREAD

**Issue by Avarong** [ccxt/ccxt#7903]
- OS: windows10
- Programming Language version: python 3.7
- CCXT version: 28.10.2020

```
    client = ccxtpro.idex({'enableRateLimit': True,
        'apiKey': api_key,
        'secret': secret,
        'walletAddress': address,
        'privateKey': private_key,
        'verbose': True,
    })
    balances=await client.fetch_balance()
```

```
Traceback (most recent call last):
  File "D:/1/pycharmccxt/IDEXbot.py", line 354, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Roman\miniconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "D:/1/pycharmccxt/IDEXbot.py", line 123, in main
    balances=await client.fetch_balance()
  File "D:\1\pycharmccxt\ccxt\async_support\idex.py", line 558, in fetch_balance
    raise e
  File "D:\1\pycharmccxt\ccxt\async_support\idex.py", line 551, in fetch_balance
    response = await self.privateGetBalances(extendedRequest)
AttributeError: 'idex' object has no attribute 'privateGetBalances'
idex requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000026852627D08>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000026852628518>, 110825.921)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000026850CDF588>
```

**Comment by kroitor** [comment]
@Avarong This issue is fixed in CCXT Pro version 0.4.53+. Thank you for reporting it!
