### ISSUE TITLE
How to create a derivative order with leverage on Bitfinex?

### ISSUE THREAD

**Issue by chatchaw74** [ccxt/ccxt#7915]
- OS: ubuntu
- Programming Language version: Python3.6
- CCXT version: 1.37.14
- Method : create_order()
Hello,
I am trying to create an Bitfinex derivative order of 0.001 BTC  using 2X leverage on BTC/USDT
I have 10USDT in my derivative wallet and the market price for BTC is 13674.0USDT
I use the following code:

```
order = bitfinex.create_order(symbol="BTC/USDT", type="market", side="buy", amount=0.001, params={ 'lev':'2'})
```
The following is the return
```
  File "/home/user/miniconda3/envs/bottrade/lib/python3.6/site-packages/ccxt/base/exchange.py", line 585, in fetch
    response.raise_for_status()
  File "/home/user/miniconda3/envs/bottrade/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitfinex.com/v1/order/new

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myexchange.py", line 391, in <module>
    order = bitfinex.create_order(symbol="BTC/USDT", type="market", side="buy", amount=0.001, params={'lev': '2'})
  File "/home/user/miniconda3/envs/bottrade/lib/python3.6/site-packages/ccxt/bitfinex.py", line 777, in create_order
    response = self.privatePostOrderNew(self.extend(request, params))
  File "/home/user/miniconda3/envs/bottrade/lib/python3.6/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/home/user/miniconda3/envs/bottrade/lib/python3.6/site-packages/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/user/miniconda3/envs/bottrade/lib/python3.6/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/user/miniconda3/envs/bottrade/lib/python3.6/site-packages/ccxt/base/exchange.py", line 597, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/user/miniconda3/envs/bottrade/lib/python3.6/site-packages/ccxt/bitfinex.py", line 1153, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], message, feedback)
  File "/home/user/miniconda3/envs/bottrade/lib/python3.6/site-packages/ccxt/base/exchange.py", line 509, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.InsufficientFunds: bitfinex {"message":"Invalid order: not enough exchange balance for 0.001 BTCUST at 13674.0"}
```

From my calculation 0.001 BTC costs 13.674USDT which 2X leverage of 10USDT is adequate to open a position. However, I got the return of insufficient fund. I've been trying to find a implicit api method but I could not find one. Please guide me to make a problem command

**Comment by chatchaw74** [comment]
Got it. The answer is the symbol is incorrect. The correct one is "BTCF0/USTF0"
