### ISSUE TITLE
southxchange cancelOrder() -  Error "Invalid API key or nonce" or do Nothing

### ISSUE THREAD

**Issue by deathmorlock** [ccxt/ccxt#7939]
Placing orders, balances - work fine. Api key has all permissions, tried to made new api keys. nothing help.  
Error or just code passed and nothing happens with orders.
createOrder() returns ID but cancelOrder give me error
```
ord = await exchange.createOrder("USD/BTC","limit","sell",1,0.01);
await exchange.cancelOrder(ord.id);
>>southxchange POST https://www.southxchange.com/api/cancelOrder 400 Invalid API key or nonce "Invalid API key or nonce"
```

**Comment by kroitor** [comment]
@deathmorlock how do you initialize the exchange instance?

Please, paste the full code and your verbose request+response (without your keys)

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by deathmorlock** [comment]
Nodejs v10.13.0
code:
```
var ccxt = require ('ccxt');
let exchange = new ccxt.southxchange ({ 
    apiKey: 'MY_api',
    secret: 'MY_secret',
});
exchange.verbose=true;
async function test() 
{
    await exchange.loadMarkets ();
    ord = await exchange.createOrder("BTC/USD","limit","sell",0.001,19500);
    console.log("ORDRED ID = " + ord.id);
    await exchange.cancelOrder(ord.id);

}

test();
```
Log: 

```
fetch:
 southxchange GET https://www.southxchange.com/api/markets
Request:
 {}
 undefined

handleRestResponse:
 southxchange GET https://www.southxchange.com/api/markets 200 OK
Response:
 { Age: '3086',
  'Cache-Control': 'max-age=14400',
  'Cf-Cache-Status': 'HIT',
  'Cf-Ray': '5ede558ccaa4d875-CPH',
  'Cf-Request-Id': '063ed3cbfc0000d8752d942000000001',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Fri, 06 Nov 2020 11:04:31 GMT',
  Etag: '"e4006ce7-7573-42a2-9f13-a297ea84ec95"',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '-1',
  'Last-Modified': 'Fri, 06 Nov 2020 10:13:05 GMT',
  Nel: '{"report_to":"cf-nel","max_age":604800}',
  Pragma: 'no-cache',
  'Report-To':
   '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report?s=bqCLqQ%2B0p%2FvELzbJzclf1dcBb0yqwDG7XnaIdYlnunAt5LrbDuF4%2F2xeCPb4Y6CpxwOfM3gpPrcxbWeXaKejX1hUC1HIa1ZmSvd5gxcHB5Q3eHekfQ%3D%3D"}],"group":"cf-nel","max_age":604800}',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=ddc255d2a63f85c0462e85353cec422cb1604660671; expires=Sun, 06-Dec-20 11:04:31 GMT; path=/; domain=.southxchange.com; HttpOnly; SameSite=Lax',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Aspnet-Version': '4.0.30319',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'sameorigin',
  'X-Powered-By': 'ASP.NET',
  'X-Xss-Protection': '1; mode=block' }
 [["DASH","BTC"],["LTC","BTC"],["DOGE","BTC"],["BSD","BTC"],["NMC","BTC"],["PTC","BTC"],["VTC","BTC"],["MANNA","BTC"],["BTC","USNBT"],["MINT","BTC"],["XVG","BTC"],["USNBT","USD"],["BTA","BTC"],["BTC","USD"],["PPC","BTC"],["LTC","USD"],["MANNA","USD"],["NXT","BTC"],["ETH","BTC"],["ETH","USD"],["XMR","BTC"],["XMR","USD"],["STRAT","BTC"],["STRAT","USD"],["ICE","BTC"],["ICE","USD"],["BCH","BTC"],["BCH","USD"],["DASH","USD"],["MSR","BTC"],["MSR","USD"],["CHA","BTC"],["XGOX","BTC"],["XGOX","LTC"],["RESTORE","BTC"],["RESTORE","LTC"],["RESTORE","USD"],["STAR","BTC"],["ETH","USNBT"],["XGOX","USD"],["INXT","BTC"],["INXT","USD"],["BTG","USD"],["BTG","BTC"],["NSR","BTC"],["NSR","USNBT"],["SMS","BTC"],["SMS","USD"],["EGOLD","BTC"],["MTC","BTC"],["MTC","USD"],["ETH","BCH"],["DASH","BCH"],["XMR","BCH"],["XVG","BCH"],["XVG","USD"],["CHA","BCH"],["LTC","BCH"],["BCH","USNBT"],["MLM","BTC"],["MLM","LTC"],["MLM","USD"],["GCN","LTC"],["GCN","BTC"],["POLIS","BTC"],["POLIS","LTC"],["POLIS","BCH"],["POLIS","USD"],["DOGE","USD"],["WCO","BTC"],["WCO","LTC"],["WCO","USD"],["WCO","BCH"],["STEEP","BTC"],["STEEP","LTC"],["STEEP","USD"],["STEEP","BCH"],["PNX","BTC"],["PNX","LTC"],["PNX","USD"],["PNX","BCH"],["SMT","BTC"],["SMT","USD"],["SMT","LTC"],["SMT","BCH"],["RPT","BTC"],["RPT","LTC"],["RPT","USD"],["RPT","BCH"],["DGM","BTC"],["CBS","BTC"],["TUN","BTC"],["BART","BTC"],["BART","USD"],["JS","BTC"],["JS","USD"],["ICC","BTC"],["ICC","USD"],["RAP","BTC"],["SAROS","BTC"],["SAROS","USD"],["XSH","BTC"],["XSH","USD"],["D","BTC"],["D","USD"],["D","LTC"],["D","BCH"],["SPK","BTC"],["SPK","USD"],["VEGI","USD"],["VEGI","BTC"],["BHD","BTC"],["BHD","USD"],["GPA","BTC"],["GPA","USD"],["BBP","USD"],["BBP","BTC"],["ERZ","USD"],["ERZ","BTC"],["FXC","BTC"],["FXC","USD"],["DIN","USD"],["DIN","BTC"],["BTC","CNNBT"],["ETH","CNNBT"],["BCH","CNNBT"],["NYX","USD"],["NYX","BTC"],["XSG","USD"],["XSG","BTC"],["OMEGA","BTC"],["OMEGA","USD"],["WHITE","USD"],["WHITE","BTC"],["WHITE","LTC"],["WHITE","BCH"],["EXUS","BTC"],["EXUS","USD"],["RC","USD"],["RC","BTC"],["RACE","USD"],["RACE","BTC"],["PBS","BTC"],["PBS","USD"],["LCC","BTC"],["LCC","USD"],["LCC","LTC"],["LCC","BCH"],["USDT","USD"],["BART","DASH"],["BBP","DASH"],["BHD","DASH"],["BSD","DASH"],["BTA","DASH"],["CBS","DASH"],["CHA","DASH"],["DGM","DASH"],["DIN","DASH"],["D","DASH"],["DOGE","DASH"],["DVLP","DASH"],["EGOLD","DASH"],["ERZ","DASH"],["EXUS","DASH"],["FXC","DASH"],["GCN","DASH"],["GPA","DASH"],["ICC","DASH"],["ICE","DASH"],["INXT","DASH"],["JS","DASH"],["LCC","DASH"],["MANNA","DASH"],["MINT","DASH"],["MLM","DASH"],["MSR","DASH"],["MTC","DASH"],["NMC","DASH"],["NXT","DASH"],["NYX","DASH"],["OMEGA","DASH"],["PBS","DASH"],["PNX","DASH"],["POLIS","DASH"],["PPC","DASH"],["PTC","DASH"],["RACE","DASH"],["RAP","DASH"],["RC","DASH"],["RESTORE","DASH"],["RPT","DASH"],["SAROS","DASH"],["SMS","DASH"],["SMT","DASH"],["XSG","DASH"],["SPK","DASH"],["STAR","DASH"],["STEEP","DASH"],["STRAT","DASH"],["TUN","DASH"],["VEGI","DASH"],["VTC","DASH"],["WCO","DASH"],["WHITE","DASH"],["XGOX","DASH"],["XMR","DASH"],["XSH","DASH"],["XVG","DASH"],["VTAR","BTC"],["VTAR","USD"],["PINK","USD"],["PINK","BTC"],["TIMEC","BTC"],["TIMEC","USD"],["SMLY","BTC"],["SMLY","USD"],["BTCF","BTC"],["BTCF","USD"],["ROE","USD"],["ROE","BTC"],["ZACA","BTC"],["ZACA","USD"],["TUSD","USD"],["BTC","TUSD"],["DERO","USD"],["DERO","BTC"],["STAK","USD"],["STAK","BTC"],["FTO","BTC"],["FTO","USD"],["LTC","TUSD"],["ETH","TUSD"],["BCH","TUSD"],["KREDS","BTC"],["EPC","BTC"],["BTCX","LTC"],["CARE","BTC"],["BKS","BTC"],["XHV","BTC"],["RABBIT","BTC"],["SNBL","BTC"],["BUEN","BTC"],["BLAST","BTC"],["NPW","BTC"],["LPC","BTC"],["SWAP","BTC"],["SPRK","BTC"],["SMLY","LTC"],["IVI","BTC"],["IVI","LTC"],["IVI","USD"],["IVI","BCH"],["IVI","DASH"],["THUG","LTC"],["STB","BTC"],["STB","USD"],["STB","TUSD"],["SFCP","BTC"],["SFCP","LTC"],["GRC","BTC"],["GRC","USD"],["GRC","BCH"],["ONION","BTC"],["TELOS","BTC"],["BEET","BTC"],["BEET","DASH"],["BEET","USD"],["SNOVA","BTC"],["BRAZ","BTC"],["COMP","LTC"],["SNOVA","USD"],["SNOVA","TUSD"],["BLTG","BTC"],["ETC","BTC"],["ETC","USD"],["ETC","TUSD"],["BTC","PAX"],["LTC","PAX"],["DASH","PAX"],["ETH","PAX"],["ETC","PAX"],["BCH","PAX"],["PAX","USD"],["BLTG","USD"],["SNOVA","DASH"],["BTC","USDC"],["USDC","USD"],["LTC","USDC"],["DASH","USDC"],["ETH","USDC"],["BCH","USDC"],["ETC","USDC"],["PLUS1","BTC"],["LIQ","BTC"],["BSV","BTC"],["BSV","DASH"],["BSV","USD"],["BSV","TUSD"],["BSV","PAX"],["BSV","USDC"],["BSV","BCH"],["SBTCT","BTC"],["ATO","BTC"],["JAN","BTC"],["BITH","BTC"],["ATO","USD"],["ATO","BCH"],["ATO","LTC"],["ATO","DASH"],["ALC","BTC"],["WBTC","BTC"],["GUN","BTC"],["GUN","LTC"],["XSR","BTC"],["XSR","DASH"],["XSR","LTC"],["XSR","USD"],["XSR","BCH"],["MCM","BTC"],["MCM","LTC"],["AGVC","BTC"],["AGVC","LTC"],["DVLP","LTC"],["XAX","BTC"],["XAX","DASH"],["XAX","LTC"],["XAX","USD"],["BTCX","DOGE"],["DVRS","DOGE"],["COMP","DOGE"],["GCN","DOGE"],["THUG","DOGE"],["ICC","LTC"],["MTC","LTC"],["BTCF","LTC"],["BRAZ","LTC"],["BTCF","DOGE"],["DOGE","LTC"],["ZACA","LTC"],["XGOX","DOGE"],["SMLY","DOGE"],["MANNA","LTC"],["MANNA","DOGE"],["PBS","LTC"],["PBS","DOGE"],["MLM","DOGE"],["GRC","LTC"],["ONION","LTC"],["GUN","DOGE"],["PINK","LTC"],["PINK","DOGE"],["ATO","DOGE"],["XAX","DOGE"],["OMEGA","LTC"],["OMEGA","DOGE"],["ERZ","LTC"],["ERZ","DOGE"],["RABBIT","DASH"],["RABBIT","LTC"],["RABBIT","DOGE"],["NSR","LTC"],["NSR","DOGE"],["EXUS","LTC"],["EXUS","DOGE"],["BBP","LTC"],["BBP","DOGE"],["AGVC","USD"],["AGVC","TUSD"],["DASH","LTC"],["VTAR","LTC"],["VTAR","DOGE"],["CCA","BTC"],["CCA","USD"],["DASH","TUSD"],["AGVC","DASH"],["BAT","BTC"],["BAT","DASH"],["BAT","LTC"],["BAT","USD"],["BAT","BCH"],["BAT","TUSD"],["BAT","PAX"],["BAT","USDC"],["SC","BTC"],["SC","DASH"],["SC","LTC"],["SC","DOGE"],["SC","USD"],["SC","BCH"],["SC","TUSD"],["SC","PAX"],["SC","USDC"],["BTC","DAI"],["DASH","DAI"],["LTC","DAI"],["DOGE","DAI"],["BCH","DAI"],["BSV","DAI"],["IOTA","BTC"],["IOTA","DASH"],["IOTA","LTC"],["IOTA","DOGE"],["IOTA","USD"],["IOTA","BCH"],["IOTA","TUSD"],["IOTA","PAX"],["IOTA","USDC"],["IOTA","DAI"],["MANNA","DAI"],["PPC","LTC"],["PPC","DOGE"],["PPC","USD"],["PMC","BTC"],["PMC","LTC"],["PMC","DOGE"],["MANNA","BCH"],["SCP","BTC"],["SCP","LTC"],["SCP","DOGE"],["SCP","USD"],["DVT","BTC"],["DVT","LTC"],["DVT","USD"],["DVT","BCH"],["BCHC","BTC"],["BCHC","DASH"],["BCHC","LTC"],["BCHC","USD"],["PRIM","BTC"],["PRIM","LTC"],["PRIM","DOGE"],["PRIM","USD"],["XST","BTC"],["XST","DASH"],["XST","LTC"],["XST","USD"],["XST","TUSD"],["RADS","BTC"],["RADS","USD"],["USNBT","TUSD"],["SPE","BTC"],["SPE","DASH"],["SPE","LTC"],["ERI","BTC"],["ERI","LTC"],["CCXX","BTC"],["CCXX","USD"],["CCXX","LTC"],["CCXX","DASH"],["CCXX","CCU"],["CCXX","CCE"],["BTC","CCU"],["CCU","USD"],["LTC","CCU"],["DASH","CCU"],["CCA","CCU"],["BTC","CCE"],["CCE","USD"],["LTC","CCE"],["DASH","CCE"],["CCA","CCE"],["SXCC","BTC"],["XSL","BTC"],["XSL","LTC"],["TTN","BTC"],["TTN","LTC"],["TTN","DOGE"],["TRC","BTC"],["TRC","LTC"],["ESTX","BTC"],["ESTX","DASH"],["ESTX","LTC"],["CSO","BTC"],["CELC","LTC"],["CELC","DOGE"],["CELC","DASH"],["CELC","BTC"],["XPM","BTC"],["XPM","LTC"],["BAZA","BTC"],["BAZA","LTC"],["BAZA","DASH"],["BAZA","DOGE"],["BAZA","BCH"],["BAZA","TUSD"],["CSO","LTC"],["SSTC","BTC"],["SSTC","DASH"],["SSTC","DOGE"],["SSTC","TUSD"],["SSTC","PAX"],["CSO","TUSD"],["MON","BTC"],["MON","LTC"],["NTRS","BTC"],["NTRS","LTC"],["CASH2","BTC"],["CASH2","LTC"],["CASH2","TUSD"],["XBC","BTC"],["XBC","LTC"],["TNR","BTC"],["TNR","LTC"],["TRC","DASH"],["IBH","BTC"],["SCAP","BTC"],["SINS","BTC"],["IVI","DOGE"],["NTRS","DOGE"],["VSYS","BTC"],["VSYS","LTC"],["NAV","BTC"],["NAV","LTC"],["TNR","DASH"],["NTRS","DASH"],["RIC","BTC"],["RIC","LTC"],["MMO","BTC"],["MMO","LTC"],["MINT","LTC"],["SCC","BTC"],["SCC","LTC"],["SCC","TUSD"],["IBH","LTC"],["IBH","DOGE"],["ZCR","BTC"],["ZCR","LTC"],["NYC","BTC"],["NYC","LTC"],["NYC","DOGE"],["ESBC","BTC"],["ESBC","LTC"],["XOS","BTC"],["XOS","TUSD"],["ALIAS","BTC"],["PBC","BTC"],["PBC","DASH"],["PBC","LTC"],["PBC","DOGE"],["PBC","BCH"],["PBC","TUSD"],["ZCR","TUSD"],["EUPC","BTC"],["EUPC","LTC"],["MW","BTC"],["TRX","BTC"],["TRX","DASH"],["TRX","LTC"],["TRX","USD"],["TRX","DOGE"],["SVC","BTC"],["BTT","BTC"],["BRAZ","DAI"],["ZCRT","BTC"],["ZCRT","USD"],["ZCRT","USDC"],["HLIX","BTC"],["BTC","USDT"],["LTC","USDT"],["XSH","LTC"],["XSH","BCH"],["XSH","USDT"],["TNR","DOGE"],["GHOST","BTC"],["GHOST","USDT"],["SCC","USDT"],["PAWS","BTC"],["SVC","USD"],["MNMC","BTC"],["NOBL","BTC"],["FNT","BTC"],["FNT","USDT"],["BTCS","BTC"],["HYP","BTC"],["HYP","DOGE"],["LAVA","BTC"],["DAI","USD"],["UCA","BTC"],["UCA","USDT"],["LMY","BTC"],["LMY","USDT"],["MODIC","BTC"],["DIN","DAI"],["DVT","DAI"],["RADAR","BTC"],["CRW","BTC"],["CRW","DAI"],["DCNTR","BTC"],["VAULT","BTC"],["CRW","TUSD"],["BIGO","BTC"],["ICC","DOGE"],["BITH","LTC"],["XAB","BTC"],["PAXG","BTC"],["PAXG","USD"],["YFI","BTC"],["YFI","USD"],["TRUMP","BTC"],["OBIC","BTC"],["BCT","BTC"],["AITRA","BTC"],["SWITC","BTC"],["BCHN","BTC"],["BCHABC","BTC"],["BCHABC","BCHN"],["ICOL","BTC"],["BCHN","BCH"],["BCHABC","BCH"],["SCOL","BTC"],["BIGO","LTC"],["EBG","BTC"],["STEAK","BTC"],["STEAK","ETH"],["AGVC","ETH"],["LMY","ETH"],["YFX","BTC"],["YFX","ETH"],["G999","BTC"],["LRA","BTC"],["BALL","BTC"],["KONJ","BTC"],["KONJ","LTC"],["KONJ","DOGE"],["KONJ","ETH"],["NEWS","BTC"],["NEWS","USDT"],["ESMT","BTC"],["ESMT","DASH"],["ESMT","LTC"],["SFD","BTC"]]

fetch:
 southxchange POST https://www.southxchange.com/api/placeOrder
Request:
 { 'Content-Type': 'application/json',
  Hash:
   '97191d3621d7a7c510d537f5765f89b5592a0e06762571ddc9adabbc1180e86af1ad3e59a3add109a5fbb7e627527334d60f630e62af4d10f2e719634269adaa' }
 {"key":"My_api","nonce":1604660669,"listingCurrency":"BTC","referenceCurrency":"USD","type":"sell","amount":0.001,"limitPrice":19500}

handleRestResponse:
 southxchange POST https://www.southxchange.com/api/placeOrder 200 OK
Response:
 { 'Cache-Control': 'no-cache',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '5ede558d9c23d875-CPH',
  'Cf-Request-Id': '063ed3cc7d0000d8756c91a000000001',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Length': '131',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Fri, 06 Nov 2020 11:04:31 GMT',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '-1',
  Nel: '{"report_to":"cf-nel","max_age":604800}',
  Pragma: 'no-cache',
  'Report-To':
   '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report?s=C5WZD8A%2Fp%2FmyBLvEBgAqfxNCL6fSCKyp33qXiL26EJUfUcB5CZuIcHSkeFxFeYXNtnJu5p6FGyhnnbNE6QKPBy5Blw4gvAofx7d4ifA4P%2BU%2B%2BsUt6g%3D%3D"}],"group":"cf-nel","max_age":604800}',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=ddc255d2a63f85c0462e85353cec422cb1604660671; expires=Sun, 06-Dec-20 11:04:31 GMT; path=/; domain=.southxchange.com; HttpOnly; SameSite=Lax',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  Vary: 'Accept-Encoding',
  'X-Aspnet-Version': '4.0.30319',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'sameorigin',
  'X-Powered-By': 'ASP.NET',
  'X-Xss-Protection': '1; mode=block' }
 "89308695"

ORDRED ID = "89308695"
fetch:
 southxchange POST https://www.southxchange.com/api/cancelOrder
Request:
 { 'Content-Type': 'application/json',
  Hash:
   'ad6b99f78da463aa1fa65cdcb1f072508f19533f4777f236bf33dfbb65bf6e0f946d4ec4ba85cb7b3bde03ca57b9861a4d04047a7580e755a118fd63d45220e6' }
 {"key":"l9JdalDw5lJoliZc4RP7JIkGUSISWt","nonce":1604660669,"orderCode":"\"89308695\""}

handleRestResponse:
 southxchange POST https://www.southxchange.com/api/cancelOrder 400 Invalid API key or nonce
Response:
 { 'Cache-Control': 'no-cache',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '5ede558f4debd875-CPH',
  'Cf-Request-Id': '063ed3cd8c0000d87575082000000001',
  Connection: 'keep-alive',
  'Content-Length': '26',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Fri, 06 Nov 2020 11:04:32 GMT',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '-1',
  Nel: '{"report_to":"cf-nel","max_age":604800}',
  Pragma: 'no-cache',
  'Report-To':
   '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report?s=apkDxAbAlzuPNAlzUz2KeYWkrozZPTVw8h9biuNMHRnMFYqdKATH6VL85%2B3XlQ5fIH4bDJDZrt9tG96Orc7HDacp7LHVe8Ax1MrUlu0ZzjqdozQ1DA%3D%3D"}],"group":"cf-nel","max_age":604800}',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=ddc255d2a63f85c0462e85353cec422cb1604660671; expires=Sun, 06-Dec-20 11:04:31 GMT; path=/; domain=.southxchange.com; HttpOnly; SameSite=Lax',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  'X-Aspnet-Version': '4.0.30319',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'sameorigin',
  'X-Powered-By': 'ASP.NET',
  'X-Xss-Protection': '1; mode=block' }
 "Invalid API key or nonce"

(node:16472) UnhandledPromiseRejectionWarning: ExchangeNotAvailable: southxchange POST https://www.southxchange.com/api/cancelOrder 400 Invalid API key or nonce "Invalid API key or nonce"
    at southxchange.handleHttpStatusCode (E:\py_app\crex24v2_js\node_modules\ccxt\js\base\Exchange.js:563:19)
    at response.text.then (E:\py_app\crex24v2_js\node_modules\ccxt\js\base\Exchange.js:601:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
@deathmorlock it looks like you're ignoring the rate-limiting rules, this is documented in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit. You have to either add a manual delay, or enable the built-in rate-limiter as described in the Manual.

Do you have the same problem with this snippet? ↓

```JavaScript
'use strict';

const ccxt = require ('ccxt');

console.log ('CCXT Version:', ccxt.version)

async function test() {
    let exchange = new ccxt.southxchange ({ 
        apiKey: 'MY_api',
        secret: 'MY_secret',
        enableRateLimit: true, // ←-------------- required!
    });
    await exchange.loadMarkets ();
    exchange.verbose = true
    ord = await exchange.createOrder("BTC/USD","limit","sell",0.001,19500);
    console.log("ORDRED ID = " + ord.id);
    await exchange.cancelOrder(ord.id);
}

test();
```

↑ Please paste your output.

**Comment by deathmorlock** [comment]
Thanks for answer.. i tried all from Manual...  Here is result with build in rate limiter
i also added sleep 10 sec between create and cancel.
`CCXT Version: 1.37.27
fetch:
 southxchange POST https://www.southxchange.com/api/placeOrder
Request:
 { 'Content-Type': 'application/json',
  Hash:
   '379a19db3795198d7f00aceeedf5066e4b57b0a49a7335f8cce2eab90979b12afac7c1405f813d586ffcda96f6be2eb46fb666f52442e5139ba9680ee7a9b84c' }
 {"key":"MY_api","nonce":1604698846,"listingCurrency":"BTC","referenceCurrency":"USD","type":"sell","amount":0.001,"limitPrice":19500}

handleRestResponse:
 southxchange POST https://www.southxchange.com/api/placeOrder 200 OK
Response:
 { 'Cache-Control': 'no-cache',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '5ee1f98dff5cd881-CPH',
  'Cf-Request-Id': '06411a4cbe0000d881af1f4000000001',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Length': '131',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Fri, 06 Nov 2020 21:40:46 GMT',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '-1',
  Nel: '{"report_to":"cf-nel","max_age":604800}',
  Pragma: 'no-cache',
  'Report-To':
   '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report?s=NySpD0aL%2F6INu%2FapYud1IiJgWHpKVQo5bYCpWmncVI4XfmP8TI0H9etHCtKX8KqmpRhHs9zylYWhQrFwsXs1IFfj3YyFwrwG6pKYLq0ghq4OmBRKwQ%3D%3D"}],"group":"cf-nel","max_age":604800}',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=d7144e7befc846055a29f1277a00559c81604698846; expires=Sun, 06-Dec-20 21:40:46 GMT; path=/; domain=.southxchange.com; HttpOnly; SameSite=Lax',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  Vary: 'Accept-Encoding',
  'X-Aspnet-Version': '4.0.30319',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'sameorigin',
  'X-Powered-By': 'ASP.NET',
  'X-Xss-Protection': '1; mode=block' }
 "89366389"

ORDRED ID = "89366389"
WAIT... 10 seconds
fetch:
 southxchange POST https://www.southxchange.com/api/cancelOrder
Request:
 { 'Content-Type': 'application/json',
  Hash:
   '2ea568ca28bfbb6673a076bed5a94d543632bb7dea6c1872db871c92e35c63e5ebb078c0861cc6581a1718be334cb78c9a77937ecf1219352fe2cceab2573c32' }
 {"key":"MY_api","nonce":1604698856,"orderCode":"\"89366389\""}

handleRestResponse:
 southxchange POST https://www.southxchange.com/api/cancelOrder 204 No Content
Response:
 { 'Cache-Control': 'no-cache',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '5ee1f9ce4817d881-CPH',
  'Cf-Request-Id': '06411a74eb0000d881d3333000000001',
  Connection: 'keep-alive',
  Date: 'Fri, 06 Nov 2020 21:40:57 GMT',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '-1',
  Nel: '{"report_to":"cf-nel","max_age":604800}',
  Pragma: 'no-cache',
  'Report-To':
   '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report?s=Io4NeGlPKe5YytIki%2F3JetzqmvsjzoMuDQnJ6U3DYlAUZi56yCV3bOyKlERFubh9is%2FPLqj9u%2B%2B1q1YHgGdbvV4kmOQtxEnFmEfOkhCdi2y%2F1Gh0qA%3D%3D"}],"group":"cf-nel","max_age":604800}',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=db0ee058fdd63371741c23daedef5fc3e1604698856; expires=Sun, 06-Dec-20 21:40:56 GMT; path=/; domain=.southxchange.com; HttpOnly; SameSite=Lax',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  'X-Aspnet-Version': '4.0.30319',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'sameorigin',
  'X-Powered-By': 'ASP.NET',
  'X-Xss-Protection': '1; mode=block' }`

**Comment by kroitor** [comment]
@deathmorlock from your output it looks like the cancel call succeeded, right?

**Comment by deathmorlock** [comment]
No sir..
southxchange POST https://www.southxchange.com/api/cancelOrder 204 No Content
and order is open on exchange

**Comment by kroitor** [comment]
@deathmorlock ok, i think i've located the cause of it, i've pushed the fix, the new CCXT version 1.37.30 will arrive in 20 minutes or so, please, update to it and let me know if that solves the issue for you (using my last snippet).

**Comment by deathmorlock** [comment]
Now works fine, Even without rateLimits and pauses!
Good Job bro!

**Comment by kroitor** [comment]
@deathmorlock thx for reporting it!
