### ISSUE TITLE
Using the 'quoteOrderQty' parameter to make orders on Binance

### ISSUE THREAD

**Issue by thomas192** [ccxt/ccxt#7963]
- OS: Window 10
- Programming Language version: Python 3
- CCXT version: 1.37.61

Hello, 
I'm trying to execute market and limit orders using the 'quoteOrderQty' parameter on Binance. I have followed what has been said here #6391 #5465 #2707 #2547 but my code doesn't work most of the time. I guess I'm doing something wrong but I can't figure out what.

Here are is my code:
```python
# Market order
order = self.binance.create_order(symbol, "market", side, amount=None, price=None, params={"quoteOrderQty": quote_order_quantity})
# Limit order
# Variation 1
order = self.binance.create_order(symbol, "limit", side, amount=None, price=limit_price, params={"quoteOrderQty": quote_order_quantity})
# Variation 2
order = self.binance.create_order(symbol, "limit", side, amount=0, price=limit_price params={"amount": None, "quoteOrderQty": quote_order_quantity})
```

The market order query only seems to be working when there are bids and asks in the order book otherwise the order is not created (it should be with its status set to expired) and I get the following:
```
File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\binance.py", line 1651, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\binance.py", line 2403, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 604, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\binance.py", line 2362, in handle_errors
    raise InvalidOrder(self.id + ' order amount should be evenly divisible by lot size ' + body)
ccxt.base.errors.InvalidOrder: binance order amount should be evenly divisible by lot size {"code":-2010,"msg":"Filter failure: LOT_SIZE"}

Process finished with exit code 1
```

The limit order query never works and I get the following error for the first variation:
```
File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\binance.py", line 1637, in create_order
    request['quantity'] = self.amount_to_precision(symbol, amount)
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 1288, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode, self.paddingMode)
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

Process finished with exit code 1
```

The error I get with the second variation says that only 11 of the 12 parameters have been read.

Thank you!

**Comment by kroitor** [comment]
In order to be able to help you quickly, we need you to follow these:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Please, try this snippet and paste your complete verbose output:

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

markets = exchange.load_markets()

exchange.verbose = True  # comment/uncomment for debugging purposes

symbol = 'BTC/USDT'
type = 'market'
side = 'buy'  # or 'sell'
amount = 123.45  # in quote currency, how much USDT you want to spend for buying BTC
price = None
params = {
    'quoteOrderQty': amount,
}
order = exchange.create_order(symbol, type, side, amount, price, params)
pprint(order)
```

**Comment by thomas192** [comment]
I added this:
```python
exchange.set_sandbox_mode(True)
```
as I'm experimenting on the Spot Test Network.

I get this:
```
Request: POST https://testnet.binance.vision/api/v3/order {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1605189516703&recvWindow=5000&symbol=BTCUSDT&type=MARKET&side=BUY&newOrderRespType=FULL&quoteOrderQty=123.45&signature=aaff7cf375e614cff71e081b3438acbc898a5011cea2389314ce3b833577997f

Response: POST https://testnet.binance.vision/api/v3/order 400 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '47', 'Connection': 'keep-alive', 'Date': 'Thu, 12 Nov 2020 13:58:37 GMT', 'Server': 'nginx', 'x-mbx-uuid': '141cc9ca-be15-4289-ad88-47531e3b7733', 'x-mbx-used-weight': '11', 'x-mbx-used-weight-1m': '11', 'x-mbx-order-count-10s': '1', 'x-mbx-order-count-1d': '21', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 524f30fc42ae138c5b6185cefbec064b.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'CDG50-C1', 'X-Amz-Cf-Id': 'zC1PkOFsU1MtajHEtQ4i80UBE2gY7wMCmpN_aGH5XxNbzpciQ7KZXg=='} {"code":-2010,"msg":"Filter failure: LOT_SIZE"}
```

As well as the same error I mentionned earlier:
```
ccxt.base.errors.InvalidOrder: binance order amount should be evenly divisible by lot size {"code":-2010,"msg":"Filter failure: LOT_SIZE"}
```

**Comment by kroitor** [comment]
@thomas192 

> I added this:

Can you please paste the full snippet of code to reproduce it (without your keys)?
We need to see the entire output, including the version numbers.

**Comment by thomas192** [comment]
My bad, here is sample of my code and the entire output:
```python
import ccxt
from pprint import pprint


def get_order_status(exchange, symbol, order_id):
    status = exchange.fetch_order_status(order_id, symbol)
    return status


def create_limit_quote_order(exchange, symbol, side, limit_price, quote_order_quantity):
    order = exchange.create_order(symbol, "limit", side, amount=None, price=limit_price,
                                      params={"quoteOrderQty": quote_order_quantity})
    return order["id"]


def create_market_quote_order(exchange, symbol, side, quote_order_quantity):
    order = exchange.create_order(symbol, "market", side, amount=quote_order_quantity, price=None,
                                      params={"quoteOrderQty": quote_order_quantity})
    return order["id"]


print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
})
exchange.set_sandbox_mode(True)
markets = exchange.load_markets()
exchange.verbose = True  # comment/uncomment for debugging purposes

symbol = 'BTC/USDT'
amount = 123.45  # in quote currency, how much USDT you want to spend for buying BTC

order_id = create_market_quote_order(exchange, symbol, "buy", amount)

pprint(order_id)

status = get_order_status(exchange, symbol, order_id)

pprint(status)

```
```
C:\Users\masth\AppData\Local\Programs\Python\Python39\python.exe C:/Users/masth/OneDrive/Documents/PyCharmProjects/TradingBot/issue.py
CCXT Version: 1.37.61

Request: POST https://testnet.binance.vision/api/v3/order {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1605193248713&recvWindow=5000&symbol=BTCUSDT&type=MARKET&side=BUY&newOrderRespType=FULL&quoteOrderQty=123.45&signature=7f1a00e876e5eb8b4fc3477890032cc60cc70f13a1cef0b5c7a8eda5a26e13e1

Response: POST https://testnet.binance.vision/api/v3/order 400 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '47', 'Connection': 'keep-alive', 'Date': 'Thu, 12 Nov 2020 15:00:49 GMT', 'Server': 'nginx', 'x-mbx-uuid': '141cc9ca-be15-4289-ad88-47531e3b7733', 'x-mbx-used-weight': '2', 'x-mbx-used-weight-1m': '2', 'x-mbx-order-count-10s': '1', 'x-mbx-order-count-1d': '25', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 e225339d299ad31ad0818dbdb8c65826.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'CDG50-C1', 'X-Amz-Cf-Id': 'FrjRBPA8FLFpY4SOQx5c8TlIURs4uEADWarsrtqFolvBG0DdeigavA=='} {"code":-2010,"msg":"Filter failure: LOT_SIZE"}
Traceback (most recent call last):
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 588, in fetch
    response.raise_for_status()
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://testnet.binance.vision/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\masth\OneDrive\Documents\PyCharmProjects\TradingBot\issue.py", line 42, in <module>
    order_id = create_market_quote_order(exchange, symbol, "buy", amount)
  File "C:\Users\masth\OneDrive\Documents\PyCharmProjects\TradingBot\issue.py", line 22, in create_market_quote_order
    order = exchange.create_order(symbol, "market", side, amount=quote_order_quantity, price=None,
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\binance.py", line 1651, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\binance.py", line 2453, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 604, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\binance.py", line 2412, in handle_errors
    raise InvalidOrder(self.id + ' order amount should be evenly divisible by lot size ' + body)
ccxt.base.errors.InvalidOrder: binance order amount should be evenly divisible by lot size {"code":-2010,"msg":"Filter failure: LOT_SIZE"}

Process finished with exit code 1
```

**Comment by kroitor** [comment]
@thomas192 we will have to raise this to Binance, cause we are not breaking any rules about the LOT_SIZE here. The verbose request looks totally correct to me. I suspect a bug on the testnet sandbox.

**Comment by thomas192** [comment]
Thank you for your time @kroitor. I'll close the thread then.

**Comment by kroitor** [comment]
@thomas192 i've escalated this to Binance tech support, will keep you updated on my findings.

**Comment by kroitor** [comment]
@thomas192 ok, here's the answer to your question:

----------------------

Igor Kroitor, [12.11.20 18:22]
Hello!

Can anyone of the admins here clarify what's wrong with this request:

https://gist.github.com/kroitor/adf80cc106dc52eb053b19d6ea84ece9

↑ A proper set of request arguments according to the docs was sent to the testnet to place a quoteOrderQty MARKET order, and it replies with a Filter failure: LOT_SIZE error. Does the testnet support quoteOrderQty?

--------------

MadWard, [12.11.20 18:58]
[In reply to Igor Kroitor]
Your request seems fine, this might be a problem with testnet. Testnet does support quoteOrderQty according to https://testnet.binance.vision/api/v3/exchangeInfo
Did you get a chance to capture what the price of the lowest ask was at that time? The only thing that would make sense is if your market buy hit a price so high $123 wasn't enough to buy 0.001 BTC, the minQty of LOT_SIZE filter.

--------------
Igor Kroitor, [12.11.20 18:59]
@MadWard it happens consistently in a repeatable fashion, regardless of the price i think.
I don't think that $123 is not enough to cover the LOT_SIZE with BTC/USDT at around $16000
that's 123 / 16000 = 0,0076875

--------------

MadWard, [12.11.20 19:02]
[In reply to Igor Kroitor]
$16000 is live spot price, but testnet doesn't have the same prices as live, which is why I was asking whether you managed to see what the lowest ask in the order book was.

--------------

Igor Kroitor, [12.11.20 19:03]
You can try placing the same request rn – it will fail.
here's the response
from the ticker endpoint
```
{             symbol: "BTCUSDT",
                          priceChange: "545.02000000",
                   priceChangePercent: "3.516",
                     weightedAvgPrice: "3607.51311445",
                       prevClosePrice: "20000.00000000",
                            lastPrice: "16044.02000000",
                              lastQty: "0.00300000",
                             bidPrice: "16044.02000000",
                               bidQty: "0.05047900",
                             askPrice: "0.00000000",
                               askQty: "0.00000000",
                            openPrice: "15499.00000000",
                            highPrice: "16044.02000000",
                             lowPrice: "2000.00000000",
                               volume: "3.70089900",
                          quoteVolume: "13351.04167774",
                             openTime:  1605105765877,
                            closeTime:  1605192165877,
                              firstId:  341,
                               lastId:  405,
                                count:  65               } }
```

↑ the askPrice and askQty is zero, meaning an empty ask side
So I guess there is not enough ask-orders on the testnet (the BTC/USDT orderbook is empty on the ask side) and that triggers a LOT_SIZE filter error incorrectly.
Reporting Filter failure: LOT_SIZE in that case is very confusing.
Something like this would be better: *market order is not fillable, because the ask side is empty*

--------------

MadWard, [12.11.20 19:07]
While it is true LOT_SIZE is confusing in this case, the situation is only a thought experiment that wouldn't occur in live trading.

--------------

Igor Kroitor, [12.11.20 19:08]
Yep, thanks for the clarifications

-------------------------------------------------------

@thomas192 let me know if that does not resolve the issue.

**Comment by thomas192** [comment]
@kroitor that was quick thanks! As I understand it, it explains the market order error but not the one I get from a limit order:
```python
import ccxt
from pprint import pprint


def get_order_status(exchange, symbol, order_id):
    # Query
    status = exchange.fetch_order_status(order_id, symbol)
    # Return
    return status


def create_limit_quote_order(exchange, symbol, side, limit_price, quote_order_quantity):
    # Query
    order = exchange.create_order(symbol, "limit", side, amount=None, price=limit_price,
                                      params={"quoteOrderQty": quote_order_quantity})
    # Return
    return order["id"]


print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
})
exchange.set_sandbox_mode(True)
markets = exchange.load_markets()
exchange.verbose = True  # comment/uncomment for debugging purposes

symbol = 'BTC/USDT'
amount = 123.45  # in quote currency, how much USDT you want to spend for buying BTC

order_id = create_limit_quote_order(exchange, symbol, "buy", 10597, amount)

pprint(order_id)

status = get_order_status(exchange, symbol, order_id)

pprint(status)
```
```
C:\Users\masth\AppData\Local\Programs\Python\Python39\python.exe C:/Users/masth/OneDrive/Documents/PyCharmProjects/TradingBot/issue.py
CCXT Version: 1.37.61
Traceback (most recent call last):
  File "C:\Users\masth\OneDrive\Documents\PyCharmProjects\TradingBot\issue.py", line 42, in <module>
    order_id = create_limit_quote_order(exchange, symbol, "buy", 10597, amount)
  File "C:\Users\masth\OneDrive\Documents\PyCharmProjects\TradingBot\issue.py", line 14, in create_limit_quote_order
    order = exchange.create_order(symbol, "limit", side, amount=None, price=limit_price,
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\binance.py", line 1637, in create_order
    request['quantity'] = self.amount_to_precision(symbol, amount)
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 1288, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode, self.paddingMode)
  File "C:\Users\masth\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

Process finished with exit code 1
````

**Comment by kroitor** [comment]
@thomas192 Binance only supports `quoteOrderQty` for market orders, you have to specify both the amount and the price (without `params`) for a regular limit order. Let me know if that does not answer your question.

**Comment by thomas192** [comment]
@kroitor oh right, all good thanks again.

**Comment by kroitor** [comment]
A closure from Binance:

> CS Arvin (Binance)
> Nov 13, 2020, 19:05 GMT+8
> 
> Dear user,
> 
> Thanks for sharing, that makes sense.
> 
> We got the relevant team update, if the market liquidity is too low (no ask/bid order in the order book), the market order will fail, this won't happen in the product environment.
> 
> Sorry for the error message confused you, we forward it to the tech team, hope they can modify the error message to make it more clear for the users.
> 
> Thanks again for your waiting and understanding, if you have any questions in the future, please do come back to us, we will try our best to help you.
> 
> At last, we hope you have a good journey in Binance. 
> 
> Best Regards, 
> Binance Support Team

**Comment by gschurck** [comment]
Hello, is it possible to set only the total of USDT quote amount I want to spend, without giving a specific price ? So the base amount could be calculated directly on Binance.

**Comment by kroitor** [comment]
@gschurck yes, check these duplicates:

- https://github.com/ccxt/ccxt/search?q=binance+quoteOrderQty&type=issues

**Comment by gschurck** [comment]
> @gschurck yes, check these duplicates:
> 
> * https://github.com/ccxt/ccxt/search?q=binance+quoteOrderQty&type=issues

Ok I found it, thanks

**Comment by gschurck** [comment]
But as I understand `quoteOrderQty` is only for Binance. Which exchanges also have an equivalent API feature ?

**Comment by kroitor** [comment]
@gschurck it depends on the side of the order and this is exchange-specific, in many cases it will work with market-buy orders only, but with Binance it works for both market buys and market sells. Search through the repo files for `createMarketBuyOrderRequiresPrice`:

<img width="359" alt="Screenshot 2021-03-18 at 03 19 37" src="https://user-images.githubusercontent.com/1294454/111555144-d39d1d00-8798-11eb-862c-be9ea2ac1971.png">

Check the logic here: https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1906
