### ISSUE TITLE
BTCTurk cancel_order does not work

### ISSUE THREAD

**Issue by yusufilker** [ccxt/ccxt#7975]
hello, 
my setup is:
Windows10, python 3.9, ccxt1.37.14
exchange: btcturk

The api has changed so i try to update the code locally, code is attached:
[btcturk.zip](https://github.com/ccxt/ccxt/files/5540444/btcturk.zip)

most functions work but cancel order() & fetch_all_orders() does not work.
REST api endpoint has changed  from  POST "CancelOrder" to  DELETE  "order".

```
    def cancel_order(self, id, params={}):
        request = {
            'id': id,
        }
        return self.privateDeleteOrder(self.extend(request, params))
```

print (btcturk.cancel_order(674400185)) command yields below error. I tried str and int parameters. 
Api reference: https://docs.btcturk.com/#cancel-order 

```
DEBUG:ccxt.base.exchange:DELETE https://api.btcturk.com/api/v1/order, Request: {'X-PCK': 'a7ed8d90-3a00-45eb-91e9-22693d76360c', 'X-Stamp': '1605348725490', 'X-Signature': 'F/iSph+ucb+CYtAZTsRuX0KWuuZh2rQc9YnEXcNlszY=', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} {"id":674400185}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.btcturk.com:443
DEBUG:urllib3.connectionpool:https://api.btcturk.com:443 "DELETE /api/v1/order HTTP/1.1" 400 None
DEBUG:ccxt.base.exchange:DELETE https://api.btcturk.com/api/v1/order, Response: 400 {'Date': 'Sat, 14 Nov 2020 10:12:07 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d6660254eeb0298fb2261ef9a1a8295b31605348727; expires=Mon, 14-Dec-20 10:12:07 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax, __cfruid=aa83fe987cd3668e0819496a8117d84afe125711-1605348727; path=/; domain=.btcturk.com; HttpOnly; Secure; SameSite=None', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'content-language': 'tr-TR', 'vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-xss-protection': '1; mode=block', 'x-build-id': '14674', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'cf-client-ip': '94.54.52.87', 'api-supported-versions': '1.0, 2.0', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '0667d6af6b0000d8b55524f000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5f1ff3c57f11d8b5-AMS'} {"success":false,"message":"NO_ORDER_MATCHES_YOUR_REQUEST","code":1052}
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 588, in fetch
    response.raise_for_status()
  File "C:\Python39\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.btcturk.com/api/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yusuf\python\trader\ccxt\ilk.py", line 40, in <module>
    print (btcturk.cancel_order(674400185))                                      # çalışmıyor
  File "C:\Python39\lib\site-packages\ccxt\btcturk.py", line 299, in cancel_order
    return self.privateDeleteOrder(self.extend(request, params))
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 605, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 636, in handle_http_status_code
    raise Exception(' '.join([self.id, method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: btcturk DELETE https://api.btcturk.com/api/v1/order 400 Bad Request {"success":false,"message":"NO_ORDER_MATCHES_YOUR_REQUEST","code":1052}
```

**Comment by kroitor** [comment]
> {"success":false,"message":"NO_ORDER_MATCHES_YOUR_REQUEST","code":1052}

This error says that there is no order that matches your request. That means that the order with that id is not open.

Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions if any.
We hope to update the BTCTurk API implementation asap: https://github.com/ccxt/ccxt/pull/7825

**Comment by kroitor** [comment]
P.S. You will also have to change the `sign()` function in order to send the DELETE-request params in the URL-query, like with GET-requests.

**Comment by yusufilker** [comment]
Thanks you for the quick response. The "id" passed  is correct, i check it fetch_open_orders(),  but İ don't think i am passing it correctly.  I tried to pass as str and  as int. no luck.
Even though id was wrong. debug message should contain id whatsoever like below:

DEBUG:ccxt.base.exchange:DELETE https://api.btcturk.com/api/v1/order, Response: 400
should be :
DEBUG:ccxt.base.exchange:DELETE https://api.btcturk.com/api/v1/order?id:674400185, Response: 200

 I don't know ccxt internals.  so as you said sign() function might be the problem.  I will look into that. thanks

**Comment by kroitor** [comment]
@yusufilker you can take the outdated `sign()` function that looks like this:

```Python
    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        if self.id == 'btctrader':
            raise ExchangeError(self.id + ' is an abstract base API for BTCExchange, BTCTurk')
        url = self.urls['api'] + '/' + path
        if api == 'public':
            if params:
                url += '?' + self.urlencode(params)
        else:
            self.check_required_credentials()
            nonce = str(self.nonce())
            body = self.urlencode(params)
            secret = self.base64_to_binary(self.secret)
            auth = self.apiKey + nonce
            headers = {
                'X-PCK': self.apiKey,
                'X-Stamp': nonce,
                'X-Signature': self.hmac(self.encode(auth), secret, hashlib.sha256, 'base64'),
                'Content-Type': 'application/x-www-form-urlencoded',
            }
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
```

And modify it like so to add support for DELETE requests:

```Python
    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        if self.id == 'btctrader':
            raise ExchangeError(self.id + ' is an abstract base API for BTCExchange, BTCTurk')
        url = self.urls['api'] + '/' + path
        if api == 'public':
            if params:
                url += '?' + self.urlencode(params)
        else:
            self.check_required_credentials()
            nonce = str(self.nonce())
            body = self.urlencode(params)
            secret = self.base64_to_binary(self.secret)
            auth = self.apiKey + nonce
            headers = {
                'X-PCK': self.apiKey,
                'X-Stamp': nonce,
                'X-Signature': self.hmac(self.encode(auth), secret, hashlib.sha256, 'base64'),
            }
            if method === 'POST' or method === 'PUT':
                headers['Content-Type'] = 'application/x-www-form-urlencoded'
                body = self.urlencode(params)
            else:  # GET or DELETE
                url += '?' + self.urlencode(params)
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

**Comment by yusufilker** [comment]
thank you very much.  That fixed. working like a charm. Other functions are also perfect.
