### ISSUE TITLE
How solve the ccxt.base.errors.ExchangeError: internal error

### ISSUE THREAD

**Issue by jedipython** [ccxt/ccxt#7987]
Hello, i have exception for Fetch in Kucoin.

- Ubuntu 18.04
- Python 3.7
- CCXT 1.22.44

**my code**

```
`def ticker_fetch():
    """Fetch tickers from exchanges"""
    with Redis.from_url(current_app.config['REDIS_EXCHANGES_TICKER_URI']) as redis:
        for exchange_name in current_app.config['ACTIVE_EXCHANGES']:
            try:
                exchange = getattr(ccxt, exchange_name)()
                exchange.load_markets()
                if exchange.has['fetchTickers']:
                    tickers = exchange.fetchTickers()
                    tickers = {k: str(v['close']) for k, v in tickers.items()}
                elif exchange.has['fetchTicker']:
                    tickers = {}
                    for symbol in exchange.symbols:
                        ticker = exchange.fetchTicker(symbol)
                        tickers[symbol] = str(ticker['close'])
                else:
                    logger.warning('{} not have fetchTickers/fetchTicker'.format(exchange_name))
                    continue
                redis.set(exchange_name, json.dumps(tickers), ex=int(current_app.config['TICKER_CACHE_TTL'].total_seconds()))
            except Exception:
            	
                logger.exception('{} error fetchTickers/fetchTicker'.format(exchange_name))
```

**My errors log**
```
[2020-11-17 11:00:00,425: ERROR/ForkPoolWorker-1] singlebuy.task.ticker_fetch[e2aa3745-b2d1-44e2-bd7b-08c1ce230994]: kucoin error fetchTickers/fetchTicker
Traceback (most recent call last):
  File "/app/singlebuy/task/exchange.py", line 18, in ticker_fetch
    exchange.load_markets()
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 1268, in load_markets
    currencies = self.fetch_currencies()
  File "/usr/local/lib/python3.7/dist-packages/ccxt/kucoin.py", line 297, in fetch_currencies
    response = self.publicGetCurrencies(params)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 440, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 463, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 459, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 576, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/kucoin.py", line 1553, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, message)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 477, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeError: internal error
```
How can slove this problem? What is it? Thanks

**Comment by kroitor** [comment]
> How can slove this problem? What is it? Thanks

It's a 3-in-1 problem:

1. You should always make sure that your version of CCXT is up to date, as described in the troubleshooting sequence in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting – your version of the lib is really old, there's a ton of changes since then.
2. You should always respect the rate limits, as documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
3. You should add the error handling to locate the failing call, as documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#error-handling

In other words, you should really follow the Manual )

First and foremost we need to isolate the failing exchange+call, we can then debug it further here.

Try this:

```Python
def ticker_fetch():
    """Fetch tickers from exchanges"""
    with Redis.from_url(current_app.config['REDIS_EXCHANGES_TICKER_URI']) as redis:
        for exchange_name in current_app.config['ACTIVE_EXCHANGES']:
            exchange = getattr(ccxt, exchange_name)({'enableRateLimit': True})
            try:
                exchange.load_markets()
            except Exception as e:
                logger.exception(exchange_name + ' failed to load markets, the exchange replied with ' + type(e).__name__ + ' ' + str(e)[0:200])
            if exchange.has['fetchTickers']:
                try:
                    tickers = exchange.fetchTickers()
                    tickers = {k: str(v['close']) for k, v in tickers.items()}
                    redis.set(exchange_name, json.dumps(tickers), ex=int(current_app.config['TICKER_CACHE_TTL'].total_seconds()))
                except Exception:
                    logger.exception(exchange_name + ' failed to fetch all tickers at once')
            elif exchange.has['fetchTicker']:
                try:
                    tickers = {}
                    for symbol in exchange.symbols:
                        try:
                            ticker = exchange.fetchTicker(symbol)
                            tickers[symbol] = str(ticker['close'])
                        except Exception as e:
                            logger.exception(exchange_name + ' failed to fetch ' + symbol + ' ticker')
                            raise e
                    redis.set(exchange_name, json.dumps(tickers), ex=int(current_app.config['TICKER_CACHE_TTL'].total_seconds()))
                except Exception as e:
                    pass
            else:
                logger.warning('{} not have fetchTickers/fetchTicker'.format(exchange_name))
                continue
```

↑ The error description (_"internal_error"_) is a string that comes from the exchange API itself, it means some kind of internal error happened on the exchange side. Please, execute steps 1-3, and retry the edited version and paste the log here.

**Comment by kroitor** [comment]
P.S. We have received reports form the other users on Kucoin's intermittent _internal_error_ with `load_markets()`, could be a problem on the exchange side or it may be undergoing some maintenance.
