### ISSUE TITLE
Amount to precision bug - python3.8 (binance futures)

### ISSUE THREAD

**Issue by JanssensKobe** [ccxt/ccxt#8016]
Hello,
I'm getting a " TypeError: 'NoneType' " error when I'm using the 'amount_to_precision' function for binance (futures).

- OS: Manjaro
- Programming Language version: Python 3.8.6
- CCXT version: latest

```python
import ccxt

exchange = ccxt.binance({
    'apiKey': 'xxx',
    'secret': 'xxx',
    'enableRateLimit': True
})

exchange.options['defaultType'] = 'future'

market = 'LINK/USDT'
balance = 10.45744367

amount = exchange.amount_to_precision(market, balance)

print(amount)
```

```
Traceback (most recent call last):
  File "testAmount.py", line 14, in <module>
    amount = exchange.amount_to_precision(market, balance)
  File "/home/kobej/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1288, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode, self.paddingMode)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by frosty00** [comment]
you need to call `exchange.load_markets` first
