### ISSUE TITLE
The fetch_withdrawals method fails with CoinEx

### ISSUE THREAD

**Issue by xenohunter** [ccxt/ccxt#8055]
- OS: Arch Linux
- Programming Language version: Python 3.8.5
- CCXT version: 1.38.48 (initially was found in 1.37.34)

When requesting withdrawals from CoinEx, the code raises an exception in [the `Exchange.to_array` method link](https://github.com/ccxt/ccxt/blob/578050855ddefb4655f2daf1b1e5a24773595d49/python/ccxt/base/exchange.py#L1232) because that method assumes its argument to be of a certain format.

While debugging, I've found that a dict of the following format is passed to the `Exchange.to_array` method which causes it to fail:
```
{
  'has_next': True,
  'curr_page': 1,
  'count': 10,
  'data': [
    {
      'coin_withdraw_id': ***,
      'create_time': ***,
      'actual_amount': '***',
      'actual_amount_display': '***',
      'amount': '***',
      'amount_display': '***',
      'coin_address': '***',
      'app_coin_address_display': '***',
      'coin_address_display': '***',
      'add_explorer': '***',
      'coin_type': '***',
      'confirmations': 10,
      'explorer': '***',
      'fee': '***',
      'remark': '',
      'smart_contract_name': '***',
      'status': 'finish',
      'status_display': 'finish',
      'transfer_method': 'onchain',
      'tx_fee': '***',
      'tx_id': '***'
    },
    /* more transactions */
  ],
  'total': ***,
  'total_page': ***
}
```

Code to reproduce:
```
import ccxt

exchange = ccxt.coinex({
    "apiKey": key,
    "secret": secret,
    "timeout": 10000,
    "enableRateLimit": False
})

exchange.verbose = True
exchange.fetch_withdrawals(code="BTC")
```

Full output:
```
Request: GET https://api.coinex.com/v1/market/info {'User-Agent': 'python-requests/
2.25.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.coinex.com/v1/market/info 200 {'Date': 'Thu, 26 Nov 2020 
16:40:47 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 
'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=*******************************
************; expires=Sat, 26-Dec-20 16:40:47 GMT; path=/; domain=.coinex.com; Http
Only; SameSite=Lax; Secure', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '******
**************************', 'Expect-CT': 'max-age=604800, report-uri="https://repo
rt-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY':
 '********************', 'Content-Encoding': 'gzip'} {"code": 0, "data": {"CFXUSDT"
: {"name": "CFXUSDT", "min_amount": "10", "maker_fee_rate": "0.002", "taker_fee_rat
e": "0.002", "pricing_name": "USDT", "pricing_decimal": 6, "trading_name": "CFX", "
trading_decimal": 8}, /* many more tokens */ }, "message": "OK"}

Request: GET https://api.coinex.com/v1/balance/coin/withdraw?access_id=************
********************&coin_type=BTC&tonce=************* {'Authorization': '*********
***********************', 'Content-Type': 'application/json', 'User-Agent': 'python
-requests/2.25.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.coinex.com/v1/balance/coin/withdraw?access_id=***********
*********************&coin_type=BTC&tonce=************* 200 {'Date': 'Thu, 26 Nov 2
020 16:40:48 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunke
d', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=***************************
****************; expires=Sat, 26-Dec-20 16:40:47 GMT; path=/; domain=.coinex.com; 
HttpOnly; SameSite=Lax; Secure', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '**
******************************', 'Expect-CT': 'max-age=604800, report-uri="https://
report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-R
AY': '********************', 'Content-Encoding': 'gzip'} {"code": 0, "data": {"has_
next": true, "curr_page": 1, "count": 10, "data": [{"coin_withdraw_id": *******, "c
reate_time": **********, "actual_amount": "***", "actual_amount_display": "***", "a
mount": "******", "amount_display": "******", "coin_address": "********************
**********************", "app_coin_address_display": "**********", "coin_address_di
splay": "****************", "add_explorer": "https://explorer.viawallet.com/btc/add
ress/******************************************", "coin_type": "BTC", "confirmation
s": 6, "explorer": "https://explorer.viawallet.com/btc/tx/*************************
***************************************", "fee": "0", "remark": "", "smart_contract
_name": "BTC", "status": "finish", "status_display": "finish", "transfer_method": "
onchain", "tx_fee": "******", "tx_id": "*******************************************
*********************"}, /* many more data points */ ], "total": ***, "total_page":
***}, "message": "Success"}

Traceback (most recent call last):
  File "/home/xenohunter/***/***.py", line 116, in ***
    exchange.fetch_withdrawals(code="BTC")
  File "/home/xenohunter/.local/share/anaconda3/envs/cg/lib/python3.8/site-packages/ccxt/coinex.py", line 800, in fetch_withdrawals
    return self.parse_transactions(data, currency, since, limit)
  File "/home/xenohunter/.local/share/anaconda3/envs/cg/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1701, in parse_transactions
    array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]
  File "/home/xenohunter/.local/share/anaconda3/envs/cg/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1701, in <listcomp>
    array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]
  File "/home/xenohunter/.local/share/anaconda3/envs/cg/lib/python3.8/site-packages/ccxt/coinex.py", line 705, in parse_transaction
    id = self.safe_string_2(transaction, 'coin_withdraw_id', 'coin_deposit_id')
  File "/home/xenohunter/.local/share/anaconda3/envs/cg/lib/python3.8/site-packages/ccxt/base/exchange.py", line 725, in safe_string_2
    return Exchange.safe_either(Exchange.safe_string, dictionary, key1, key2, default_value)
  File "/home/xenohunter/.local/share/anaconda3/envs/cg/lib/python3.8/site-packages/ccxt/base/exchange.py", line 755, in safe_either
    value = method(dictionary, key1)
  File "/home/xenohunter/.local/share/anaconda3/envs/cg/lib/python3.8/site-packages/ccxt/base/exchange.py", line 675, in safe_string
    return str(dictionary[key]) if Exchange.key_exists(dictionary, key) else default_value
  File "/home/xenohunter/.local/share/anaconda3/envs/cg/lib/python3.8/site-packages/ccxt/base/exchange.py", line 659, in key_exists
    if key in dictionary:
TypeError: argument of type 'bool' is not iterable
```
P.S. It seems to me that [this JavaScript method](https://github.com/ccxt/ccxt/blob/748335bb49c46d2a04e862689484e08c3d14acdf/js/base/functions/generic.js#L34) is translated into the Python one mentioned above but I'm not perfectly sure.

**Comment by xenohunter** [comment]
Wow, that was really quick. Thanks, @kroitor!

**Comment by kroitor** [comment]
@xenohunter thx for reporting it, appreciate your feedback!
