### ISSUE TITLE
Kucoin ExchangeError

### ISSUE THREAD

**Issue by jedipython** [ccxt/ccxt#8097]
Hello, i have this probllems with Kucoin.  Stopped shopping through api.

ССXT version 1.22.44
Python 3.7

My error log:

```
Traceback (most recent call last):
  File "/app/singlebuy/task/trade.py", line 95, in pre_buy
    balances = exchange.fetchBalance()
  File "/usr/local/lib/python3.7/dist-packages/ccxt/kucoin.py", line 1355, in fetch_balance
    response = self.privateGetAccounts(self.extend(request, params))
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 440, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 463, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 459, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 574, in fetch
    raise ExchangeError(method + ' ' + url)
ccxt.base.errors.ExchangeError: GET https://openapi-v2.kucoin.com/api/v1/accounts
```

My function:

```
def pre_buy(self, buytask_id):
	"""Prepare buy: fetch task data, price and balance before"""
	try:
		buy_task = db.session.query(BuyTask.pair.label('pair'), BuyTask.amount.label('amount'),
									Exchange.exchange_id.label('exchange_id'), Exchange.user_id.label('user_id'),
									Exchange.name.label('exchange_name'), Exchange.key.label('key'),
									Exchange.secret.label('secret'), Exchange.password.label('password')).\
			select_from(BuyTask).\
			join(Exchange, BuyTask.exchange_id == Exchange.exchange_id).\
			filter(BuyTask.buytask_id == buytask_id, BuyTask.valid == True, Exchange.valid == True).\
			one()
	except NoResultFound:
		return
	except SQLAlchemyError as e:
		logger.exception('Retrive BuyTask')
		raise self.retry(exc=e)
 
	with Redis.from_url(current_app.config['REDIS_EXCHANGES_TICKER_URI']) as redis:
		tickers = redis.get(buy_task.exchange_name)
	if tickers is None:
		logger.warning('Not have ticker for exchange')
		raise self.retry()
	tickers = json.loads(tickers.decode())
	price = tickers.get(buy_task.pair, None)
	if price is None:
		logger.warning('Not have price for pair')
		raise self.retry()
   
	decoded_secret = fernet.decrypt(buy_task.secret.encode()).decode()  # Tryna decrypt all this stuff
	exchange = getattr(ccxt, buy_task.exchange_name)({'apiKey': buy_task.key,
													  'secret': decoded_secret,
													  'password': buy_task.password})
	try:
		balances = exchange.fetchBalance()
	except ccxt.AuthenticationError:
		invalid_text = 'Authentication error'
		signature('singlebuy.task.invalidate_exchange', app=self.app).delay(buy_task.exchange_id, invalid_text)
		return
	except Exception as e:
		logger.exception('Retrive balance')
		raise self.retry(exc=e)
	quote_name, base_name = buy_task.pair.split('/')
	quote = str(balances.get(quote_name, {}).get('total', 0.0))
	base = str(balances.get(base_name, {}).get('total', 0.0))
	actual_base = buy_task.amount
	signature('singlebuy.task.buy', app=self.app).delay(buytask_id, buy_task.user_id, buy_task.exchange_id,
														buy_task.exchange_name, buy_task.pair,
														buy_task.key, decoded_secret, buy_task.password,
														buy_task.amount, price, quote, base, actual_base)
```

Please help. Thanks

**Comment by kroitor** [comment]
Hi! Please, paste your code to reproduce it and your verbose request+response.

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by jedipython** [comment]
updated

**Comment by kroitor** [comment]
@jedipython your version of CCXT is outdated: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting, do you have the same issue with the most recent version of CCXT ?

**Comment by jedipython** [comment]
i see the problem. Kuckoin updated API from v1 to v2. 
`To reinforce the security of the API, KuCoin upgraded the API key and currently it has been upgraded to version 2.0. Please upgrade your API before 00:00, May 1, 2021 (UTC+8), the old one will expire after this time. How to upgrade: Delete the API key of version 1.0—>create a new API key of version 2.0—>verify through API 2.0. For more information, please check the API document.@Yuehui Zhang(Arthur)`

CCXT updated this Kucoin v2?

**Comment by kroitor** [comment]
@jedipython 

> Did CCXT update this Kucoin v2?

Yes, please update to the most recent version of CCXT.
Let us know if that does not help. Feel free to reopen this issue or just ask further questions if any.

**Comment by rdbr** [comment]
Check out this commit in the Kucoin API docs: https://github.com/Kucoin/kucoin-api-docs/commit/a76cb94a5d2ec93a8a46fb9ab298209263950640
So while CCXT does support v2 of the API, it doesn't support v2 of the API Key.
v2 needs a new header: `KC-API-KEY-VERSION`

**Comment by kroitor** [comment]
@rdbr will get to it asap, thx!

**Comment by rdbr** [comment]
Maybe this issue was forgotten because it was closed already? Just a friendly reminder. Thanks! :+1:

**Comment by kroitor** [comment]
Before CCXT version 0.39.93:

```Python
exchange = ccxt.kucoin({
    'headers': {
        'KC-API-KEY-VERSION': '2',
    },
    # ... other constructor params
})
```

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

Starting from CCXT version 0.39.93 that header is set by default.
Thanks for your feedback and your patience! Let us know if you further issues with it.

**Comment by kroitor** [comment]
Apparently, there's still [a bug there](https://github.com/ccxt/ccxt/issues/8187), will refix it shortly.

**Comment by kroitor** [comment]
As of CCXT 1.39.95:

If you are using a **v1 apiKey**:

```Python
import ccxt
exchange = ccxt.kucoin({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'password': 'YOUR_API_PASSWORD',
    'headers': {
        'KC-API-KEY-VERSION': '1',
    },
    },
})
```

If you are using a **v2 apiKey**:

```Python
import ccxt
exchange = ccxt.kucoin({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'password': 'YOUR_API_PASSWORD',
    },
})
```
