### ISSUE TITLE
OKEX Client Returning SSLCertVerificationError when connecting via websockets

### ISSUE THREAD

**Issue by YoussefV** [ccxt/ccxt#8117]
- OS: MacOS Big Sur
- Programming Language version: Python 3.9
- CCXT version: 1.39.37

### Problem

Trying to connect to OKEX via websocket and for some reason this code is not working:

It used to work earlier in the year, but I think something changed between ccxt-1.21 and now? Has the OKEX API changed? Why is this not verifying properly anymore?

```
import ccxt
import websockets
import asyncio


async def connect():
    await websockets.connect("wss://real.okex.com:8443/ws/v3")


client_kwargs = {'apiKey': apikey,
                         'secretKey': secretkey,
                         'password': password,
                         'enableRateLimit': True}
client = ccxt.okex(client_kwargs)
asyncio.run(connect())
```

This is what i get:

```
Traceback (most recent call last):
  File "Desktop/Python/websockets/isolate.py", line 16, in <module>
    asyncio.run(connect())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Desktop/Python/websockets/isolate.py", line 7, in connect
    await websockets.connect("wss://real.okex.com:8443/ws/v3")
  File "Desktop/Python/websockets/env/lib/python3.9/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
```

I tried adding `"verify":False` in the constructor but it didn't help

**Comment by kroitor** [comment]
@YoussefV CCXT does not support websockets, because CCXT is REST-only. Your code above uses the `websockets` package that has nothing to do with CCXT or CCXT Pro. So, if you have difficulties using the `websockets` package, i'd recommend to forward your questions to the authors of the `websockets` package: https://github.com/aaugustin/websockets.

In general, this line means that you have a connectivity issue between your machine and OKEX, this may be related to the intermediary proxies and firewalls, or it may be related to your SSL initialization config

- https://www.google.com/search?q=websockets+ssl.SSLCertVerificationError%3A+%5BSSL%3A+CERTIFICATE_VERIFY_FAILED%5D+certificate+verify+failed%3A+unable+to+get+local+issuer+certificate&oq=websockets+ssl.SSLCertVerificationError%3A+%5BSSL%3A+CERTIFICATE_VERIFY_FAILED%5D+certificate+verify+failed%3A+unable+to+get+local+issuer+certificate

CCXT Pro (https://ccxt.pro) uses the aiohttp websocket client, and it does not have the above issue. I've just tested it with CCXT Pro on my side and it does work with OKEX. So, I'd recommend to investigate your `websockets` issue on Google, or just switch to CCXT Pro. 

This `websockets` issue is beyond the scope of the CCXT library (not relevant to ccxt). You can reproduce it without CCXT and that means it's not inside CCXT:

```Python
### CCXT IS NOT USED IN THIS CODE:

import websockets
import asyncio


async def connect():
    await websockets.connect("wss://real.okex.com:8443/ws/v3")


asyncio.run(connect())
```

Hope that answers your question.
