### ISSUE TITLE
Mercado Bitcoin: issues to cancel and edit order

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#817]
Hey, @kroitor.

I am having problems to edit and cancel existing orders from Mercado Bitcoin exchange ('mercado'). I cannot cancel and edit any order because the error 205 is ever returned.

Can you see what's going on, please? I imagine this is just a little issue with 'coin-pair' parameter.

Please, take a look into error report:

To cancel order:

```
Connected to pydev debugger (build 172.3544.46)
https://www.mercadobitcoin.net/tapi/v3/ POST https://www.mercadobitcoin.net/tapi/v3/ 
Request: {'Content-Type': 'application/x-www-form-urlencoded', 'TAPI-ID': 'TAPI-ID', 'TAPI-MAC': 'TAPI-MAC', 'User-Agent': 'ccxt/1.10.344 (+https://github.com/ccxt/ccxt) Python/3.6.2', 'Accept-Encoding': 'gzip, deflate'} tapi_method=cancel_order&tapi_nonce=1512913951781&order_id=45829588
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1599, in <module>
POST https://www.mercadobitcoin.net/tapi/v3/ 
Response: Date: Sun, 10 Dec 2017 13:52:28 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Server: Apache
Vary: Cookie
X-Frame-Options: SAMEORIGIN
Set-Cookie: visid_incap_619276=/vCHs4JERX+Wuy1bFOMiGxw8LVoAAAAAQUIPAAAAAACv/t5erRkVr75hfUqTLPDc; expires=Mon, 10 Dec 2018 13:02:50 GMT; path=/; Domain=.mercadobitcoin.net
Set-Cookie: nlbi_619276=Fbc9RyepXSpW4nzV2TZ0lAAAAADNTnCo1Z1HaTwLSDYDurz5; path=/; Domain=.mercadobitcoin.net
Set-Cookie: incap_ses_785_619276=zoAHF+vslXvA7LaHfOHkChw8LVoAAAAAJzZ1pLkvfSsQYbitJQ0k3A==; path=/; Domain=.mercadobitcoin.net
Set-Cookie: ___utmvmmzulzpm=iNbAHALAWvQ; path=/; Max-Age=900
Set-Cookie: ___utmvamzulzpm=RemWawB; path=/; Max-Age=900
Set-Cookie: ___utmvbmzulzpm=rZP
    XTBOQaln: Atm; path=/; Max-Age=900
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Iinfo: 14-77125514-77125530 NNNN CT(183 186 0) RT(1512913948060 55) q(0 0 3 -1) r(6 6) U6
X-CDN: Incapsula
Content-Encoding: gzip

 {"status_code": 205, "error_message": "Valor do *coin_pair* inv\u00e1lido.", "server_unix_timestamp": "1512913948"}
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/MANGUEIRA/PycharmProjects/Bots Projects/Support and Tests/Teste de Stop-loss.py", line 21, in <module>
    z = mercado.cancel_order('45829588')
  File "C:\Program Files\Python36\lib\site-packages\ccxt\mercado.py", line 161, in cancel_order
    }, params))
  File "C:\Program Files\Python36\lib\site-packages\ccxt\mercado.py", line 207, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: mercado {"status_code":205,"error_message":"Valor do *coin_pair* inv\u00e1lido.","server_unix_timestamp":"1512913948"}

Process finished with exit code 1
```

To edit order:

```
Connected to pydev debugger (build 172.3544.46)
pydev debugger: process 8616 is connecting

https://www.mercadobitcoin.net/tapi/v3/ POST https://www.mercadobitcoin.net/tapi/v3/ 
Request: {'Content-Type': 'application/x-www-form-urlencoded', 'TAPI-ID': 'TAPI-ID', 'TAPI-MAC': 'TAPI-MAC', 'User-Agent': 'ccxt/1.10.344 (+https://github.com/ccxt/ccxt) Python/3.6.2', 'Accept-Encoding': 'gzip, deflate'} tapi_method=cancel_order&tapi_nonce=1512914198990&order_id=45829588
POST https://www.mercadobitcoin.net/tapi/v3/ 
Response: Date: Sun, 10 Dec 2017 13:56:36 GMT
Content-Type: application/json
Connection: close
Server: Apache
Vary: Cookie
X-Frame-Options: SAMEORIGIN
Set-Cookie: visid_incap_619276=GwaUNqucTgmhhV6dEK6NkBQ9LVoAAAAAQUIPAAAAAABQPgO/SsDsigyhKdNBoLfk; expires=Mon, 10 Dec 2018 13:02:50 GMT; path=/; Domain=.mercadobitcoin.net
Set-Cookie: nlbi_619276=3VKXR5L8cgmOd6YD2TZ0lAAAAADGqIQM2oiHommqIns145GD; path=/; Domain=.mercadobitcoin.net
Set-Cookie: incap_ses_785_619276=ELjabMk34hy/RLeHfOHkChQ9LVoAAAAABeDc9UXvPBu8RuCzc6Odkw==; path=/; Domain=.mercadobitcoin.net
Set-Cookie: ___utmvmmzulzpm=fopbQkCQiwq; path=/; Max-Age=900
Traceback (most recent call last):
Set-Cookie: ___utmvamzulzpm=GqqNzcN; path=/; Max-Age=900
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1599, in <module>
Set-Cookie: ___utmvbmzulzpm=JZG
    XlZORalO: Ntu; path=/; Max-Age=900
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Iinfo: 13-61229194-61229215 NNNN CT(184 185 0) RT(1512914195271 95) q(0 0 4 -1) r(14 14) U6
X-CDN: Incapsula
Content-Encoding: gzip
Transfer-Encoding: chunked

 {"status_code": 205, "error_message": "Valor do *coin_pair* inv\u00e1lido.", "server_unix_timestamp": "1512914196"}
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/MANGUEIRA/PycharmProjects/Bots Projects/Support and Tests/Teste de Stop-loss.py", line 22, in <module>
    z = mercado.edit_order('45829588', 'BTC/BRL')
  File "C:\Program Files\Python36\lib\site-packages\ccxt\base\exchange.py", line 950, in edit_order
    self.cancel_order(id, symbol)
  File "C:\Program Files\Python36\lib\site-packages\ccxt\mercado.py", line 161, in cancel_order
    }, params))
  File "C:\Program Files\Python36\lib\site-packages\ccxt\mercado.py", line 207, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: mercado {"status_code":205,"error_message":"Valor do *coin_pair* inv\u00e1lido.","server_unix_timestamp":"1512914196"}

Process finished with exit code 1
```

**Comment by kroitor** [comment]
Hi, @Felipe-Mangueira ! Will look into it asap.

**Comment by kroitor** [comment]
This is fixed in 1.10.345. Thanks for reporting! Let us know if you have any difficulties with it after updating (tested it, should work normally).

**Comment by Felipe-Mangueira** [comment]
Thank you @kroitor.

If I have any issue, I contact you!

**Comment by Felipe-Mangueira** [comment]
@kroitor. Just to inform you, it's working pretty fine. Thanks, again!!

**Comment by kroitor** [comment]
@Felipe-Mangueira thanks for reporting back! Check the update on fetchOrder (https://github.com/ccxt/ccxt/issues/818) as well!
