### ISSUE TITLE
Time in milliseconds is not being calculated properly in PHP, causing authentication to fail (with Bittrex)

### ISSUE THREAD

**Issue by 9rj** [ccxt/ccxt#8195]
- OS: Raspbian GNU/Linux 10 (buster)
- Programming Language version: PHP 7.3.19-1~deb10u1
- CCXT version: 1.40.3

The milliseconds() function in PHP is not correctly calculating the time in milliseconds. This leads to Authentication failing on Bittrex. 
ccxt/php/base/Exchange.php (line no. 642)
`return (int) ($sec . substr($msec, 2, 3));`
Gives the output as: `2147483647`
Whereas the correct timestamp is: `1609580306417`

If this line is replaced with 
`return round(microtime(true) * 1000);`
It returns the correct timestamp and also succeeds when authenticating with Bittrex.

Test Code:-
```
$bittrex = new \ccxt\bittrex(array(
	'apiKey' => '#################',
	'secret' => '##################',
	'enableRateLimit' => true));
$bittrex->fetch_balance();
```

Output (I have left out a part the verbose response as it is very large and seems unnecessary.):
```
Array
(
    [0] => Request:
    [1] => GET
    [2] => https://api.bittrex.com/v3/balances
    [3] => Array
        (
            [Api-Key] => #################
            [Api-Timestamp] => 2147483647
            [Api-Content-Hash] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
            [Api-Signature] => 5cba978a2285d6aaa44a58334e8f214ddaec1cd3d529f08878b27ec427a6cdfe040537a24f4059cfc53112bf74a02e8379ec4b5972cbb56b62776867ec608384
        )

    [4] => 
)
Array
(
    [0] => Response:
    [1] => GET
    [2] => https://api.bittrex.com/v3/balances
    [3] => 401
    [4] => 
    [5] => Array
        (
            [Date] => Sat, 02 Jan 2021 09:51:59 GMT
            [Content-Type] => application/json; charset=utf-8
            [Content-Length] => 28
            [Set-Cookie] => __cfduid=da61b34a672ea8b79c16bbd35941ef5221609581119; expires=Mon, 01-Feb-21 09:51:59 GMT; path=/; domain=.bittrex.com; HttpOnly; SameSite=Lax; Secure
            [Request-Id] => ead94585-a298-433c-836f-315b49c914e3
            [Strict-Transport-Security] => max-age=15768000
            [X-Xss-Protection] => 1; mode=block
            [X-Content-Type-Options] => nosniff
            [X-Download-Options] => noopen
            [Cf-Cache-Status] => DYNAMIC
            [Cf-Request-Id] => 07641be148000031bd8419d000000001
            [Expect-Ct] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
            [Server] => cloudflare
            [Cf-Ray] => 60b395aed92131bd-BOM
        )

    [6] => {"code":"INVALID_TIMESTAMP"}
)
PHP Fatal error:  Uncaught ccxt\AuthenticationError: bittrex https://api.bittrex.com/v3/balances GET 401 {"code":"INVALID_TIMESTAMP"} in /var/www/html/ccxt/vendor/ccxt/ccxt/php/base/Exchange.php:1499
Stack trace:
#0 /var/www/html/ccxt/vendor/ccxt/ccxt/php/base/Exchange.php(1487): ccxt\Exchange->handle_http_status_code(401, '', 'https://api.bit...', 'GET', '{"code":"INVALI...')
#1 /var/www/html/ccxt/vendor/ccxt/ccxt/php/base/Exchange.php(1233): ccxt\Exchange->fetch('https://api.bit...', 'GET', Array, NULL)
#2 /var/www/html/ccxt/vendor/ccxt/ccxt/php/base/Exchange.php(1237): ccxt\Exchange->fetch2('balances', 'private', 'GET', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('balances', 'private', 'GET', Array)
#4 /var/www/html/ccxt/vendor/ccxt/ccxt/php/base/Exchange.php(2483): call_user_func_array(Array, Array)
#5 /var/www/html/ccxt/vendor/ccxt/ccxt/php/bittrex.php(308): ccxt\Exchange->__call('privateGetBalan...', Array)
#6 /var/www/html/ccxt/test.php(8): ccxt\bittrex->fetch_balance()
#7 {main}
  thrown in /var/www/html/ccxt/vendor/ccxt/ccxt/php/base/Exchange.php on line 1499

```

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/5978
