### ISSUE TITLE
There was an API change due to the addition of Bithumb's BTC market.

### ISSUE THREAD

**Issue by Eavan0103** [ccxt/ccxt#8216]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: win10 64bit
- Programming Language version:
- CCXT version: 1.40.23

First of all, thank you for allowing me to use the CCXT.

There was an API change due to the addition of Bithumb's BTC market.

So, it is not a trading order.

Thank you.

LimitOrder1 = bithumb.createLimitBuyOrder('BTC/KRW", size, price) 
-----------------------------------------------------------------------------

ERROR:root:Traceback (most recent call last):
  File "E:/Code/Test.py", line 1434, in <module>
LimitOrder1 = bithumb.createLimitBuyOrder('BTC/KRW", size, price) 
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1860, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bithumb.py", line 528, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bithumb.py", line 882, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 624, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bithumb.py", line 878, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, feedback)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: bithumb {"status":"5500","message":"Invalid Parameter"}

**Comment by kroitor** [comment]
Hi! Please, help us help you – paste your code (without the keys) and your complete output in verbose mode (not just the error callstack):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bithumb({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()

exchange.verbose = True

amount = YOUR_AMOUNT
price = YOUR_PRICE
order = exchange.createLimitBuyOrder('BTC/KRW', amount, price)
pprint(order)
```

**Comment by Eavan0103** [comment]
> Hi! Please, help us help you – paste your code (without the keys) and your complete output in verbose mode (not just the error callstack):
> 
> * https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
> 
> ```python
> import ccxt
> 
> print('CCXT Version:', ccxt.__version__)
> 
> exchange = ccxt.bithumb({
>     'enableRateLimit': True,
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
> })
> 
> markets = exchange.load_markets()
> 
> exchange.verbose = True
> 
> amount = YOUR_AMOUNT
> price = YOUR_PRICE
> order = exchange.createLimitBuyOrder('BTC/KRW', amount, price)
> pprint(order)
> ```

Request: POST https://api.bithumb.com/trade/place {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded', 'Api-Key': '10fc08ee80f02bccae0136c7a69eee38', 'Api-Sign': 'YjFiZDA4ODI3MjEzYjUxOGU2MzcyNGZkMGUzMzg5N2M0MmMyYjM2YWUyMzZlYjYyZDRjOTdjZWIzNmVlM2M1MTUwNGVmMjgzNDg2ZDJlODAxNzM2NTYwZDRjYWUzZmI3ZDk4OTRmMDY3MDgyNmY3OTY3Mjg2MDE2NTUwZGY0ZmE=', 'Api-Nonce': '1609968853315', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} endpoint=%2Ftrade%2Fplace&order_currency=BTC&Payment_currency=KRW&units=0.005&price=39850000&type=bid

Response: POST https://api.bithumb.com/trade/place 200 {'Date': 'Wed, 06 Jan 2021 21:34:13 GMT', 'Content-Type': 'application/json', 'Content-Length': '47', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d3c5c0ea19fc47ddae103784b9e2d41c11609968853; expires=Fri, 05-Feb-21 21:34:13 GMT; path=/; domain=.bithumb.com; HttpOnly; SameSite=Lax, WMONID=j0fbLiPckPf; expires=Thu, 06-Jan-2022 21:34:12 GMT; Max-Age=31536000; path=/', 'requestId': '1609968852_9a31a', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Allow-Headers': '*', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '077b3839770000ef92f7adf000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '60d88fd58e08ef92-NRT'} {"status":"5500","message":"Invalid Parameter"}
Traceback (most recent call last):

  File "<ipython-input-1-bdd8ca43c427>", line 1, in <module>
    runfile('E:/Code/05_SetExchangesKRWMarket+BinanceBKRW/untitled0.py', wdir='E:/Code/05_SetExchangesKRWMarket+BinanceBKRW')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Code/05_SetExchangesKRWMarket+BinanceBKRW/untitled0.py", line 17, in <module>
    order = exchange.createLimitBuyOrder('BTC/KRW', amount, price)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1860, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bithumb.py", line 528, in create_order
    response = getattr(self, method)(self.extend(request, params))

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bithumb.py", line 882, in request
    response = self.fetch2(path, api, method, params, headers, body)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 624, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bithumb.py", line 878, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, feedback)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: bithumb {"status":"5500","message":"Invalid Parameter"}

**Comment by kroitor** [comment]
@Eavan0103 thx, we will investigate and will get back to you asap!

**Comment by Eavan0103** [comment]
> @Eavan0103 thx, we will investigate and will get back to you asap!

Thank you. Thank you

**Comment by Eavan0103** [comment]
> @Eavan0103 thx, we will investigate and will get back to you asap!

I always use the program with gratitude.
I respect you.
