### ISSUE TITLE
Bitmart Internal Server Error for url: https://api-cloud.bitmart.com/spot/v1/submit_order

### ISSUE THREAD

**Issue by mapapuche** [ccxt/ccxt#8218]
Hello,

I got error when i try to create_order with bitmart.

- OS: Windows 10 - Ubuntu 16
- Programming Language version: python 3.8
- CCXT version: 1.40.11

Error :
```
Traceback (most recent call last):
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 588, in fetch
    response.raise_for_status()
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api-cloud.bitmart.com/spot/v1/submit_order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main2.py", line 447, in <module>
    trade(info['exchange_buy'], info['exchange_sell'], info['order_book_buy'], info['order_book_sell'], 0)
  File "main2.py", line 260, in trade
    trade(exchange_to_buy, exchange_to_sell, to_buy_order_book, to_sell_order_book, position)
  File "main2.py", line 251, in trade
    order = sell(exchange_to_sell, to_sell_order_book['bids'][0][0], ALL_CRYPTO[cpt], order_filled)
  File "main2.py", line 213, in sell
    order = exchange.create_limit_sell_order(
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1863, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/bitmart.py", line 1638, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 604, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/bitmart.py", line 2246, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeError: bitmart {"message":"Internal Server Error [bitmartEnabled false]","code":59002,"trace":"ebd7e29f-42fa-48d6-a2bb-63f714c7f36e","data":{}}
```

How i initialize bitmart:
```
    exchange_class = getattr(ccxt, 'bitmart')
    bitmart = exchange_class({
        'apiKey': 'MY API KEY',
        'secret': 'MY SERCRET CODE',
        'timeout': 30000,
        'uid': 'MY UID',
        'enableRateLimit': True,
    })
```

The line where the error appear:
`            order = exchange.create_limit_sell_order(
                'ETH/BTC',
                size,
                price
               )
`

I'm not sure to understand if it's a bug or if it's me doing something wrong ?
In error "bitmartEnabled false" make  me think something is wrong with api maybe, but i don't see :(

**Comment by kroitor** [comment]
Hi!

Please, paste your verbose output (without your keys):

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange_class = getattr(ccxt, 'bitmart')
bitmart = exchange_class({
    'apiKey': 'MY API KEY',
    'secret': 'MY SERCRET CODE',
    'timeout': 30000,
    'uid': 'MY UID',
    'enableRateLimit': True,
})

markets = bitmart.load_markets()

bitmart.verbose = True  # ←------------------ add this after loading the markets, before creating the order

symbol = 'ETH/BTC'
size = 123.45  # edit for your values
price = 54.321  # edit for your values
order = exchange.create_limit_sell_order(symbol, size, price )
```
