### ISSUE TITLE
binance - oco-order does not work for me (python)

### ISSUE THREAD

**Issue by Defqon51** [ccxt/ccxt#8241]
Hello guys!

I am trying to get oco-orders (binance) to work for several hours now, but without any success. I also looked up closed issues with similar problems like this https://github.com/ccxt/ccxt/issues/5966 but it didn't help me neither.

- OS: Windows 10x64 running PyCharm 2020.3.2
- Programming Language version: python 3.8
- CCXT version: 1.40.30

```
Here is my code

def placeOco():
    exchange = ccxt.binance({
        'apiKey': "xxx",
        'secret': "xxx",
        'enableRateLimit': True,
        # 'options': {'adjustForTimeDifference': True}
    })

    precision = 8

    thePrice = 0.00002000
    thePrice_str = '{:0.0{}f}'.format(thePrice, precision)

    stopPrice = 0.00001600
    stopPrice_str = '{:0.0{}f}'.format(stopPrice, precision)

    stopLimitPrice = 0.00001500
    stopLimitPrice_str = '{:0.0{}f}'.format(stopLimitPrice, precision)


    symbol = 'SCRT/BTC'
    type = 'limit'  # or 'market'
    side = 'sell'  # or 'buy'
    amount = 26
    price = thePrice_str  # or None


    # extra params and overrides if needed
    params = {
        'test': True,  # test if it's valid, but don't actually place it
        'stopPrice': stopPrice_str,
        'stopLimitPrice': stopLimitPrice_str,
        'stopLimitTimeInForce': "GTC",
    }

    order = exchange.create_order(symbol, type, side, amount, price, params)
    print(order)

placeOco()
```

```
This is my error message

Traceback (most recent call last):
  File "C:/Users/xxx/PycharmProjects/xxx/xxx.py", line 72, in <module>
    placeOco()
  File "C:/Users/xxx/PycharmProjects/xxx/xxx.py", line 69, in placeOco
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "C:\Users\xxx\PycharmProjects\xxx\venv\lib\site-packages\ccxt\binance.py", line 1665, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\xxx\PycharmProjects\xxx\venv\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\xxx\PycharmProjects\xxx\venv\lib\site-packages\ccxt\binance.py", line 2473, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\xxx\PycharmProjects\xxx\venv\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\xxx\PycharmProjects\xxx\venv\lib\site-packages\ccxt\base\exchange.py", line 604, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\xxx\PycharmProjects\xxx\venv\lib\site-packages\ccxt\binance.py", line 2467, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "C:\Users\xxx\PycharmProjects\xxx\venv\lib\site-packages\ccxt\base\exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1104,"msg":"Not all sent parameters were read; read '11' parameter(s) but was sent '13'."}
```

Thanks in advance for your time and help!

**Comment by kroitor** [comment]
CCXT currently does not support Binance's OCO orders with the `create_order` call, however you can place your OCO order with CCXT using the implicit API methods: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://binance-docs.github.io/apidocs/spot/en/#new-oco-trade

Let us know if this example does not answer your question:

- https://github.com/ccxt/ccxt/tree/master/examples/py/binance-create-oco-order-with-implicit-methods.py

```Python
# -*- coding: utf-8 -*-
import ccxt


exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
    # 'options': {'adjustForTimeDifference': True}
})

symbol = 'SCRT/BTC'
market = exchange.market(symbol)
amount = 26
price = 0.00002
stop_price = 0.000016
stop_limit_price = 0.000015

response = exchange.private_post_order_oco({
    'symbol': market['id'],
    'side': 'SELL',  # SELL, BUY
    'quantity': exchange.amount_to_precision(symbol, amount),
    'price': exchange.price_to_precision(symbol, price),
    'stopPrice': exchange.price_to_precision(symbol, stop_price),
    'stopLimitPrice': exchange.price_to_precision(symbol, stop_limit_price),  # If provided, stopLimitTimeInForce is required
    'stopLimitTimeInForce': 'GTC',  # GTC, FOK, IOC
    # 'listClientOrderId': exchange.uuid(),  # A unique Id for the entire orderList
    # 'limitClientOrderId': exchange.uuid(),  # A unique Id for the limit order
    # 'limitIcebergQty': exchangea.amount_to_precision(symbol, limit_iceberg_quantity),
    # 'stopClientOrderId': exchange.uuid()  # A unique Id for the stop loss/stop loss limit leg
    # 'stopIcebergQty': exchange.amount_to_precision(symbol, stop_iceberg_quantity),
    # 'newOrderRespType': 'ACK',  # ACK, RESULT, FULL
})
print(response)
```

**Comment by Defqon51** [comment]
ty @kroitor now it's working fine! have a nice day!

**Comment by mlkb** [comment]
Im trying to make an oco for binance and I keep getting this error:
` binance {"code":-1013,"msg":"The relationship of the prices for the orders is not correct."}`

Here is the code:
`client.private_post_order_oco({
    'symbol': market['id'],
    'side': 'buy',
    'quantity': binanceClient.amount_to_precision(symbol, amount),
    'price': binanceClient.price_to_precision(symbol, price),
    'stopPrice': binanceClient.price_to_precision(symbol, stop_price),
    'stopLimitPrice': binanceClient.price_to_precision(symbol, stop_limit_price), 
    'stopLimitTimeInForce': 'GTC' , 
    })`

I tried other types of order with `create_order()` and it worked fine but oco, i cant find anything to solve my problem

**Comment by kroitor** [comment]
@mlkb when you're placing a stop-limit sell, you `stopPrice` must be higher than the current `price`.

**Comment by don-mao** [comment]
@kroitor thank you for your quick response. 
I tried too it doesnt work.

```
amount = 1
price = 2400.00
stop_price = 2600.00
stop_limit_price = 2300.00
```

**Comment by kroitor** [comment]
@don-mao you also have to check the current price of the asset in question:

- https://binance-docs.github.io/apidocs/spot/en/#new-oco-trade

<img width="888" alt="Screenshot 2021-04-05 at 23 44 44" src="https://user-images.githubusercontent.com/1294454/113624961-f40a1a00-9668-11eb-924b-18d5324142ae.png">

Let us know if that does not help.

**Comment by don-mao** [comment]
I am aware of the price restrictions and since it doesnt work I literally tried every combination possible.
Nothing worked and Im trying to keep the prices close to the current market. 

I am for now on the sandboxmode for testing.

**Comment by kroitor** [comment]
@don-mao can you paste your complete request+response in `exchange.verbose` mode ? https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by don-mao** [comment]
```

Request: POST https://testnet.binance.vision/api/v3/order/oco {'X-MBX-APIKEY': 'uKSVAFISL3Z72XTC1h1vJHlGMnnlXbpPCueXTHEJhKJJ7M0zG3eIRQZInzHc1ivX', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1617656453107&recvWindow=5000&symbol=ETHBUSD&side=sell&quantity=1&price=2104&stopPrice=2105&stopLimitPrice=2105&stopLimitTimeInForce=FOK&signature=e796d7d038a8f7f99178394f8a4ceed1b72312a37bf1ffb9a12f972df800564a

Response: POST https://testnet.binance.vision/api/v3/order/oco 400 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '84', 'Connection': 'keep-alive', 'Date': 'Mon, 05 Apr 2021 21:00:53 GMT', 'Server': 'nginx', 'x-mbx-uuid': '01ac5a2f-7261-4b5e-abdc-770d849de7ed', 'x-mbx-used-weight': '2', 'x-mbx-used-weight-1m': '2', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 01ec1718bcc130455b377ec6b38ad50d.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ZRH50-C1', 'X-Amz-Cf-Id': 'MgWTxp3qngVAf3RQ5r6dZixFDBftxWAebQ1z336rQScpRX8LgEm1rQ=='} {"code":-1013,"msg":"The relationship of the prices for the orders is not correct."}
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    601             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 602             response.raise_for_status()
    603 

~\Anaconda3\lib\site-packages\requests\models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 400 Client Error: Bad Request for url: https://testnet.binance.vision/api/v3/order/oco

During handling of the above exception, another exception occurred:

InvalidOrder                              Traceback (most recent call last)
<ipython-input-201-9d9fd13fe814> in async-def-wrapper()
     19 resp

<ipython-input-201-9d9fd13fe814> in response()
     15     })
     16     return resp
---> 17 
     18 resp = await response()
     19 resp

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in inner(_self, params)
    468                             if params is not None:
    469                                 inner_kwargs['params'] = params
--> 470                             return entry(_self, **inner_kwargs)
    471                         return inner
    472                     to_bind = partialer()

~\Anaconda3\lib\site-packages\ccxt\binance.py in request(self, path, api, method, params, headers, body)
   2889 
   2890     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
-> 2891         response = self.fetch2(path, api, method, params, headers, body)
   2892         # a workaround for {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
   2893         if (api == 'private') or (api == 'wapi'):

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch2(self, path, api, method, params, headers, body)
    489         self.lastRestRequestTimestamp = self.milliseconds()
    490         request = self.sign(path, api, method, params, headers, body)
--> 491         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    492 
    493     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    616         except HTTPError as e:
    617             details = ' '.join([self.id, method, url])
--> 618             self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    619             self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
    620             raise ExchangeError(details) from e

~\Anaconda3\lib\site-packages\ccxt\binance.py in handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   2883                 raise DDoSProtection(self.id + ' temporary banned: ' + body)
   2884             feedback = self.id + ' ' + body
-> 2885             self.throw_exactly_matched_exception(self.exceptions, error, feedback)
   2886             raise ExchangeError(feedback)
   2887         if not success:

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in throw_exactly_matched_exception(self, exact, string, message)
    507     def throw_exactly_matched_exception(self, exact, string, message):
    508         if string in exact:
--> 509             raise exact[string](message)
    510 
    511     def throw_broadly_matched_exception(self, broad, string, message):

InvalidOrder: binance {"code":-1013,"msg":"The relationship of the prices for the orders is not correct."}
```

**Comment by don-mao** [comment]
```

Request: POST https://testnet.binance.vision/api/v3/order/oco {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1617656453107&recvWindow=5000&symbol=ETHBUSD&side=sell&quantity=1&price=2104&stopPrice=2105&stopLimitPrice=2105&stopLimitTimeInForce=FOK&signature=e796d7d038a8f7f99178394f8a4ceed1b72312a37bf1ffb9a12f972df800564a

Response: POST https://testnet.binance.vision/api/v3/order/oco 400 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '84', 'Connection': 'keep-alive', 'Date': 'Mon, 05 Apr 2021 21:00:53 GMT', 'Server': 'nginx', 'x-mbx-uuid': '01ac5a2f-7261-4b5e-abdc-770d849de7ed', 'x-mbx-used-weight': '2', 'x-mbx-used-weight-1m': '2', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 01ec1718bcc130455b377ec6b38ad50d.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ZRH50-C1', 'X-Amz-Cf-Id': 'MgWTxp3qngVAf3RQ5r6dZixFDBftxWAebQ1z336rQScpRX8LgEm1rQ=='} {"code":-1013,"msg":"The relationship of the prices for the orders is not correct."}
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    601             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 602             response.raise_for_status()
    603 

~\Anaconda3\lib\site-packages\requests\models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 400 Client Error: Bad Request for url: https://testnet.binance.vision/api/v3/order/oco

During handling of the above exception, another exception occurred:

InvalidOrder                              Traceback (most recent call last)
<ipython-input-201-9d9fd13fe814> in async-def-wrapper()
     19 resp

<ipython-input-201-9d9fd13fe814> in response()
     15     })
     16     return resp
---> 17 
     18 resp = await response()
     19 resp

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in inner(_self, params)
    468                             if params is not None:
    469                                 inner_kwargs['params'] = params
--> 470                             return entry(_self, **inner_kwargs)
    471                         return inner
    472                     to_bind = partialer()

~\Anaconda3\lib\site-packages\ccxt\binance.py in request(self, path, api, method, params, headers, body)
   2889 
   2890     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
-> 2891         response = self.fetch2(path, api, method, params, headers, body)
   2892         # a workaround for {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
   2893         if (api == 'private') or (api == 'wapi'):

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch2(self, path, api, method, params, headers, body)
    489         self.lastRestRequestTimestamp = self.milliseconds()
    490         request = self.sign(path, api, method, params, headers, body)
--> 491         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    492 
    493     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    616         except HTTPError as e:
    617             details = ' '.join([self.id, method, url])
--> 618             self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    619             self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
    620             raise ExchangeError(details) from e

~\Anaconda3\lib\site-packages\ccxt\binance.py in handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   2883                 raise DDoSProtection(self.id + ' temporary banned: ' + body)
   2884             feedback = self.id + ' ' + body
-> 2885             self.throw_exactly_matched_exception(self.exceptions, error, feedback)
   2886             raise ExchangeError(feedback)
   2887         if not success:

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in throw_exactly_matched_exception(self, exact, string, message)
    507     def throw_exactly_matched_exception(self, exact, string, message):
    508         if string in exact:
--> 509             raise exact[string](message)
    510 
    511     def throw_broadly_matched_exception(self, broad, string, message):

InvalidOrder: binance {"code":-1013,"msg":"The relationship of the prices for the orders is not correct."}
```

**Comment by don-mao** [comment]
```
Request: POST https://testnet.binance.vision/api/v3/order/oco {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1617656453107&recvWindow=5000&symbol=ETHBUSD&side=sell&quantity=1&price=2104&stopPrice=2105&stopLimitPrice=2105&stopLimitTimeInForce=FOK&signature=

Response: POST https://testnet.binance.vision/api/v3/order/oco 400 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '84', 'Connection': 'keep-alive', 'Date': 'Mon, 05 Apr 2021 21:00:53 GMT', 'Server': 'nginx', 'x-mbx-uuid': '01ac5a2f-7261-4b5e-abdc-770d849de7ed', 'x-mbx-used-weight': '2', 'x-mbx-used-weight-1m': '2', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 01ec1718bcc130455b377ec6b38ad50d.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ZRH50-C1', 'X-Amz-Cf-Id': 'MgWTxp3qngVAf3RQ5r6dZixFDBftxWAebQ1z336rQScpRX8LgEm1rQ=='} {"code":-1013,"msg":"The relationship of the prices for the orders is not correct."}
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    601             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 602             response.raise_for_status()
    603 

~\Anaconda3\lib\site-packages\requests\models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 400 Client Error: Bad Request for url: https://testnet.binance.vision/api/v3/order/oco

During handling of the above exception, another exception occurred:

InvalidOrder                              Traceback (most recent call last)
<ipython-input-201-9d9fd13fe814> in async-def-wrapper()
     19 resp

<ipython-input-201-9d9fd13fe814> in response()
     15     })
     16     return resp
---> 17 
     18 resp = await response()
     19 resp

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in inner(_self, params)
    468                             if params is not None:
    469                                 inner_kwargs['params'] = params
--> 470                             return entry(_self, **inner_kwargs)
    471                         return inner
    472                     to_bind = partialer()

~\Anaconda3\lib\site-packages\ccxt\binance.py in request(self, path, api, method, params, headers, body)
   2889 
   2890     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
-> 2891         response = self.fetch2(path, api, method, params, headers, body)
   2892         # a workaround for {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
   2893         if (api == 'private') or (api == 'wapi'):

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch2(self, path, api, method, params, headers, body)
    489         self.lastRestRequestTimestamp = self.milliseconds()
    490         request = self.sign(path, api, method, params, headers, body)
--> 491         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    492 
    493     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    616         except HTTPError as e:
    617             details = ' '.join([self.id, method, url])
--> 618             self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    619             self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
    620             raise ExchangeError(details) from e

~\Anaconda3\lib\site-packages\ccxt\binance.py in handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   2883                 raise DDoSProtection(self.id + ' temporary banned: ' + body)
   2884             feedback = self.id + ' ' + body
-> 2885             self.throw_exactly_matched_exception(self.exceptions, error, feedback)
   2886             raise ExchangeError(feedback)
   2887         if not success:

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in throw_exactly_matched_exception(self, exact, string, message)
    507     def throw_exactly_matched_exception(self, exact, string, message):
    508         if string in exact:
--> 509             raise exact[string](message)
    510 
    511     def throw_broadly_matched_exception(self, broad, string, message):

InvalidOrder: binance {"code":-1013,"msg":"The relationship of the prices for the orders is not correct."}
```

**Comment by kroitor** [comment]
@don-mao in your request we see price=2104&stopPrice=2105&stopLimitPrice=2105
And Binance says that your limit `price` must be > `stopPrice` for a sell order.
Also, the limit price has to be greater than the last price.
And the last price has to be greater than the stopPrice.

**Comment by don-mao** [comment]
`Request: POST https://testnet.binance.vision/api/v3/order/oco {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1617657213751&recvWindow=5000&symbol=ETHBUSD&side=sell&quantity=1&price=2104&stopPrice=2105&stopLimitPrice=2106.5&stopLimitTimeInForce=FOK&signature=`


`Request: POST https://testnet.binance.vision/api/v3/order/oco {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1617657308152&recvWindow=5000&symbol=ETHBUSD&side=sell&quantity=1&price=2109&stopPrice=2107&stopLimitPrice=2108&stopLimitTimeInForce=FOK&signature=`


`Request: POST https://testnet.binance.vision/api/v3/order/oco {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1617657511811&recvWindow=5000&symbol=ETHBUSD&side=sell&quantity=1&price=2113&stopPrice=2112&stopLimitPrice=2111&stopLimitTimeInForce=FOK&signature=`



I tried them all

**Comment by kroitor** [comment]
@don-mao the last price of ETHBUSD is floating all the time, and your `price` has to be > `last price`, while your `stopPrice` has to be < `last price`, which makes your range very-very narrow which in its turn yields your error. You just have to use a wider range so that `price` > `last price` > `stopPrice`.

**Comment by don-mao** [comment]
Ok... I completely misunderstood this. 
I finally understand why now. The price needs to be like 5% higher or lower otherwise the order wont pass.... 

Anyway, thank you so much for the help and quick responses.

Cheers

**Comment by mnm7** [comment]
Hi All,

Is it possible to place an OCO order at the market price rather than by setting the price? @kroitor

current code from examples: - is it possible to add 'type' : 'market'?

```
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
    # 'options': {'adjustForTimeDifference': True}
})

symbol = 'SCRT/BTC'
market = exchange.market(symbol)
amount = 26
price = 0.00002   # **INSTEAD OF THIS, IS IT POSSIBLE TO ADD 'type': 'market'?**
stop_price = 0.000016
stop_limit_price = 0.000015

response = exchange.private_post_order_oco({
    'symbol': market['id'],
    'side': 'SELL',  # SELL, BUY
    'quantity': exchange.amount_to_precision(symbol, amount),
    'price': exchange.price_to_precision(symbol, price),
    'stopPrice': exchange.price_to_precision(symbol, stop_price),
    'stopLimitPrice': exchange.price_to_precision(symbol, stop_limit_price),  # If provided, stopLimitTimeInForce is required
    'stopLimitTimeInForce': 'GTC',  # GTC, FOK, IOC
    # 'listClientOrderId': exchange.uuid(),  # A unique Id for the entire orderList
    # 'limitClientOrderId': exchange.uuid(),  # A unique Id for the limit order
    # 'limitIcebergQty': exchangea.amount_to_precision(symbol, limit_iceberg_quantity),
    # 'stopClientOrderId': exchange.uuid()  # A unique Id for the stop loss/stop loss limit leg
    # 'stopIcebergQty': exchange.amount_to_precision(symbol, stop_iceberg_quantity),
    # 'newOrderRespType': 'ACK',  # ACK, RESULT, FULL
})
print(response)
© 2021 GitHub, Inc.
```

**Comment by kroitor** [comment]
@mnm7 hi! No, according to Binance's docs, they don't support that, the `price` is required: https://binance-docs.github.io/apidocs/spot/en/#new-oco-trade

**Comment by mnm7** [comment]
@kroitor Thanks for the response. In that case I thought I'd ask you:

When I create Take Profit Market orders such as the one below:

`exchange.create_order(asset, 'take_profit_market', opp_action, TP1_tradesize, None, params={'stopPrice':TP1,'reduceOnly': True})`

The Stop Limit Orders which I create do not expire when these TPs get filled (Stop Limit Order shown below)

'exchange.create_order(asset, 'STOP', opp_action, tradesize, SL_execute, params={'stopPrice':SL,'reduceOnly': True})'

What would be the best way to cancel the stop limit orders (such as the one above) if the Take Profit Market orders are filled?

Thanks for the feedback!

**Comment by kroitor** [comment]
@mnm7 you get the order id from create_order, and you can later cancel that order by its id:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/wiki/Manual#order-structure

However, in case of trigger orders you might also have to use the implicit api:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

**Comment by pixiedust57** [comment]
@kroitor Hi sir, can you please let me know how to create an OCO order in ccxt, i am trying to create a limit order with tp and sl and been stuck for a long time.
please help.
thank you.

**Comment by pixiedust57** [comment]
HI @kroitor, when i try to execute this, 'symbol': market['id'],
KeyError: 'id'
i get this error. please help

**Comment by SirZoX** [comment]
Hi @kroitor 

I have been several days testing the possible combinations and I am not able to put an oco order.

Basically, after adjusting the quantities to meet the MIN_NOTIONAL, STEP_SIZE and similar filters for testing, it all boils down to this:

Test Variables 1:
`side=SELL, stopPrice=1.619, price=1.535, stopLimitPrice=1.629, stopLimitTimeInForce=GTC.
`
Error obtained:
`binance.exceptions.BinanceAPIException: APIError(code=-1013): The relationship of the prices for the orders is not correct.
`

Variables test 2:
`side=SELL, stopPrice=1.629, price=1.535, stopLimitPrice=1.619, stopLimitTimeInForce=GTC.
`
Error obtained:
`binance.exceptions.BinanceAPIException: APIError(code=-1013): The relationship of the prices for the orders is not correct.
`

I do not understand the reason for the error, if I am complying with the [parameters indicated here](https://binance-docs.github.io/apidocs/spot/en/#new-oco-trade). 
```
Price Restrictions:
SELL: Limit Price > Last Price > Stop Price
BUY: Limit Price < Last Price < Stop Price
```

Can you, or someone, help me? What am I ignoring?

**Comment by KonstantinMB** [comment]
I have the exact same question and issue like @SirZoX ... tried every combo, but nothing has worked. Can anyone help?
