### ISSUE TITLE
Phemex - unsupported operand type in fetch_deposits

### ISSUE THREAD

**Issue by docek** [ccxt/ccxt#8251]
- OS: Linux on ChromeOS
- Programming Language version: Python 3.8
- CCXT version: 1.40.35

```
import ccxt

e = ccxt.phemex({
    'enableRateLimit': True,
    'testnet': True,
    #'verbose': True
})

e.apiKey = 'xxx'
e.secret = 'xxx'
e.urls['api'] = e.urls['test']
e.fetch_deposits('BTC')
```

```
Traceback (most recent call last):
  File "/home/tomasmarada/Honeybadger/honeybadger/temp.py", line 94, in <module>
    e.fetch_deposits('BTC')
  File "/opt/minconda3/lib/python3.8/site-packages/ccxt/phemex.py", line 2144, in fetch_deposits
    return self.parse_transactions(data, currency, since, limit)
  File "/opt/minconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1701, in parse_transactions
    array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]
  File "/opt/minconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1701, in <listcomp>
    array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]
  File "/opt/minconda3/lib/python3.8/site-packages/ccxt/phemex.py", line 2227, in parse_transaction
    feeCost = self.from_en(self.safe_float(transaction, 'feeEv'), currency['valueScale'], currency['precision'])
  File "/opt/minconda3/lib/python3.8/site-packages/ccxt/phemex.py", line 814, in from_en
    return float(self.decimal_to_precision(en * math.pow(10, -scale), ROUND, precision, precisionMode))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

**Comment by kroitor** [comment]
Thx for your feedback! Will fix it shortly.

**Comment by zeffmichael65** [comment]
- [ ] **[]()**
