### ISSUE TITLE
Binance Futures fetchBalance timestamp NaN

### ISSUE THREAD

**Issue by bigcountry-scav** [ccxt/ccxt#8305]
- OS: Windows 10
- Programming Language version: Node
- CCXT version: 1.40.73

```
const ccxt = require("ccxt");

(async () => {
  // --------------------------- Variable Information ----------------------------
  exchangeName = "binance";
  symbol = 'ETH/USDT';

  // --------------------------- Exchange Information ----------------------------

  const exchangeID = exchangeName;
  const exchangeClass = ccxt[exchangeID];
  exchange = new exchangeClass({
      "apiKey": apiKey,
      "secret": secret,
      "enableRateLimit": true,
      "verbose": true
  });

  exchange.options = {
    "defaultType": "future"
  }

  exchange.urls["api"] = exchange.urls["test"];

  // --------------------------- Testing Information ---------------------------- 

  // get markets test
  markets = await exchange.loadMarkets();
  // console.log({markets});

  // get ohlcv test
  ohlcv = await exchange.fetchOHLCV(symbol, "1h", undefined, 200);
  // console.log({ohlcv});

  // get balance test
  let balance = await exchange.fetchBalance();
  console.log({balance})
})()

```

```
handleRestResponse:
 binance GET https://testnet.binancefuture.com/fapi/v2/account?timestamp=NaN&recvWindow=5000&signature=c18d5b02c1f35efdf8f4a08360c57aa1528d3fbf40f8017d67fa1096ad44cca4 400 Bad Request 
Response:
 {
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  Connection: 'keep-alive',
  'Content-Length': '98',
  'Content-Type': 'application/json',
  Date: 'Sun, 17 Jan 2021 18:34:03 GMT',
  Server: 'Bengine',
  Via: '1.1 80f77e0263ce0a0c768ad3f176f2720c.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'Ty3Q6LpHnxaIGLtywvCM30lfONoa-QjXZJe_u3HM1l4UIE1tr4Efdw==',
  'X-Amz-Cf-Pop': 'ORD50-C1',
  'X-Cache': 'Error from cloudfront',
  'X-Mbx-Used-Weight-1m': '8',
  'X-Response-Time': '0ms'
} 
 {"code":-1102,"msg":"Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed."} 

(node:105) UnhandledPromiseRejectionWarning: BadRequest: binance {"code":-1102,"msg":"Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed."}
    at binance.throwExactlyMatchedException (/home/runner/exchange-testing/node_modules/ccxt/js/base/Exchange.js:532:19)
    at binance.handleErrors (/home/runner/exchange-testing/node_modules/ccxt/js/binance.js:2625:18)
    at /home/runner/exchange-testing/node_modules/ccxt/js/base/Exchange.js:602:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (/home/runner/exchange-testing/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async binance.request (/home/runner/exchange-testing/node_modules/ccxt/js/binance.js:2634:26)
    at async binance.fetchBalance (/home/runner/exchange-testing/node_modules/ccxt/js/binance.js:854:26)
    at async /home/runner/exchange-testing/index.js:40:17
(node:105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bigcountry-scav** [comment]
Possible solution would be to add request['timestamp'] = this.milliseconds() to all methods.

**Comment by kroitor** [comment]
@bigcountry-scav that is done around here: https://github.com/ccxt/ccxt/blob/master/js/binance.js#L2523

**Comment by bigcountry-scav** [comment]
Ah yes still I can get the methods working if I pass timestamp as a param but otherwise it is NaN. Thanks for looking at it.

**Comment by kroitor** [comment]
@bigcountry-scav somehow, i cannot reproduce it... This script works for me, does it work for you? ↓

```JavaScript
'use strict';

const ccxt = require ('./ccxt');

console.log ('CCXT Version:', ccxt.version)

(async () => {


    const exchange = new ccxt.binance ({
        "apiKey": "16db8b4176457d63fdc0fd8b2c9418f669237cc9620c8c04c3b8973c7e0c39b3",
        "secret": "a0d07130b34f3debfcfe29d9faf5d2fcf6bdc3b83566d03a0a973a6bc4ab90a4",
        "enableRateLimit": true,
        'options': {
            "defaultType": "future"
        },
    });

    exchange.setSandboxMode (true);

    const markets = await exchange.loadMarkets();
    console.log ('Loaded markets')

    exchange.verbose = true

    const ohlcv = await exchange.fetchOHLCV('ETH/USDT', "1h", undefined, 200);
    console.log ('Fetched ohlcv')

    // get balance test
    const balance = await exchange.fetchBalance();
    console.log({balance})
})()
```

**Comment by bigcountry-scav** [comment]
same result

```
fetch:
 binance GET https://testnet.binancefuture.com/fapi/v2/account?timestamp=NaN&recvWindow=5000&signature=c0b79eca3da8eb7c4a6dd240932314158c3e57fc2770be8f494c6de0c7768ccb 
Request:
 {
  'X-MBX-APIKEY': '16db8b4176457d63fdc0fd8b2c9418f669237cc9620c8c04c3b8973c7e0c39b3'
} 
 undefined 

handleRestResponse:
 binance GET https://testnet.binancefuture.com/fapi/v2/account?timestamp=NaN&recvWindow=5000&signature=c0b79eca3da8eb7c4a6dd240932314158c3e57fc2770be8f494c6de0c7768ccb 400 Bad Request 
Response:
 {
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  Connection: 'keep-alive',
  'Content-Length': '98',
  'Content-Type': 'application/json',
  Date: 'Mon, 18 Jan 2021 04:44:54 GMT',
  Server: 'Bengine',
  Via: '1.1 3d12ddc7e394a996971d3d1a5c985674.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'BwhUSaQRqSa0oidKZLKZlqJZ2J4BnjcLvIeypJFci_5Jy_rRUVO9cw==',
  'X-Amz-Cf-Pop': 'ORD51-C1',
  'X-Cache': 'Error from cloudfront',
  'X-Mbx-Used-Weight-1m': '8',
  'X-Response-Time': '0ms'
} 
 {"code":-1102,"msg":"Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed."} 

(node:332) UnhandledPromiseRejectionWarning: BadRequest: binance {"code":-1102,"msg":"Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed."}
    at binance.throwExactlyMatchedException (/home/runner/LemonchiffonBigheartedKnowledge/node_modules/ccxt/js/base/Exchange.js:532:19)
    at binance.handleErrors (/home/runner/LemonchiffonBigheartedKnowledge/node_modules/ccxt/js/binance.js:2625:18)
    at /home/runner/LemonchiffonBigheartedKnowledge/node_modules/ccxt/js/base/Exchange.js:602:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (/home/runner/LemonchiffonBigheartedKnowledge/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async binance.request (/home/runner/LemonchiffonBigheartedKnowledge/node_modules/ccxt/js/binance.js:2634:26)
    at async binance.fetchBalance (/home/runner/LemonchiffonBigheartedKnowledge/node_modules/ccxt/js/binance.js:854:26)
    at async /home/runner/LemonchiffonBigheartedKnowledge/index.js:30:21
(node:332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by bigcountry-scav** [comment]
So it appears that this.options["timeDifference"] is undefined in the nonce method. Seeing this on repl.it as well as local dev machine.

```
millis 1610945433982
timeDifference undefined
nonce: NaN
```

**Comment by bigcountry-scav** [comment]
Found the issue it is because of setting exchange.options overwrites all the normal options.

**Comment by kroitor** [comment]
@bigcountry-scav you're right, thx for your help! To fix it change your code like so:

```JavaScript
  const exchangeID = exchangeName;
  const exchangeClass = ccxt[exchangeID];
  exchange = new exchangeClass({
      "apiKey": apiKey,
      "secret": secret,
      "enableRateLimit": true,
      "verbose": true,
      "options": {
          'defaultType': 'future',
      }
  });
```

or like so:

```JavaScript
  const exchangeID = exchangeName;
  const exchangeClass = ccxt[exchangeID];
  exchange = new exchangeClass({
      "apiKey": apiKey,
      "secret": secret,
      "enableRateLimit": true,
      "verbose": true
  });

  exchange.options['defaultType'] = 'future'
```

Let me know if that does not resolve the issue.
