### ISSUE TITLE
Bitfinex API V2 Margin MARKET order fails / decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

### ISSUE THREAD

**Issue by Princeton007** [ccxt/ccxt#8312]
- OS: Windows
- Programming Language version: Python 3.8
- CCXT version: 1.40.81

I think this is a bug: 

Line 913 in bitfinex2.py is 
if type != 'market':
But I think it should be  
if type.lower() != 'market':

Because type is UPPERCASE in API v2 (If I use lowercase it results in an exchange order)

```
order = exchange.create_order('BTC/USD', 'MARKET', 'buy', 0.0002, None, {})
```
results in:
```
Response: GET https://api.bitfinex.com/v1/symbols_details 200 {'Date': 'Wed, 20 Jan 2021 16:59:06 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=de7b826120ddc9c6a949fcfccbff855141611161946; expires=Fri, 19-Feb-21 16:59:06 GMT; path=/; domain=.bitfinex.com; HttpOnly; SameSite=Lax', 'Vary': 'Accept-Encoding', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'ETag': 'W/"17787b2d440428e45bc95ca703380c8e"', 'Cache-Control': 'max-age=0, private, must-revalidate', 'X-Request-Id': 'e3a1f250-07e9-4111-8d12-0a24b4826118', 'X-Runtime': '0.010700', 'Referrer-Policy': 'same-origin', 'X-Download-Options': 'noopen', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains;', 'X-Permitted-Cross-Domain-Policies': 'none', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'HIT', 'Age': '1', 'cf-request-id': '07c255616b0000cda7e9a6e000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '614a58157d2bcda7-CDG'} [{"pair":"btcusd","price_precision":5,"initial_margin":"20.0","minimum_margin":"10.0","maximum_order_size":"2000.0","minimum_order_size":"0.0002","expiration":"NA","margin":true},

.....


Traceback (most recent call last):
  File "C:/Users/Rolf/OneDrive/Pycharm-RTB/Bitfinex _place_orders.py", line 34, in <module>
    order = exchange.create_order('BTC/USD', 'MARKET', 'buy', 0.0002, None, {})
  File "C:\Users\Rolf\Anaconda3\envs\Pycharm-RTB2\lib\site-packages\ccxt\bitfinex2.py", line 915, in create_order
    request['price'] = self.number_to_string(price)
  File "C:\Users\Rolf\Anaconda3\envs\Pycharm-RTB2\lib\site-packages\ccxt\base\decimal_to_precision.py", line 167, in number_to_string
    d = decimal.Decimal(str(x))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by jank3** [comment]
Please let me know how to solve it in margin trading!
