### ISSUE TITLE
I want to load some historical data before I watch ?

### ISSUE THREAD

**Issue by MiaoXingGua** [ccxt/ccxt#8343]
- OS: MacOS
- Programming Language version: node.js 14.x
- CCXT version: 0.5.41

```
// Download historical data
const records = await exchange.fetchOHLCV(symbol, period, LIMIT)

// Save the data inside the CCXT
if (!exchange.ohlcvs[symbol]) {
exchange.ohlcvs[symbol] = {}
}
exchange.ohlcvs[symbol][period] = records


// Watch for data updates
await exchange.watchOHLCV(symbol, period)
```

```
TypeError: stored.append is not a function (uncaughtException throw 1 times on pid:867)
at binance.handleOHLCV (/home/leanengine/app/node_modules/ccxt.pro/js/binance.js:503:20)
at binance.handleMessage (/home/leanengine/app/node_modules/ccxt.pro/js/binance.js:821:27)
at WsClient.onMessage (/home/leanengine/app/node_modules/ccxt.pro/js/base/Client.js:277:14)
at WebSocket.onMessage (/home/leanengine/app/node_modules/ws/lib/event-target.js:132:16)
at WebSocket.emit (events.js:315:20)
at Receiver.receiverOnMessage (/home/leanengine/app/node_modules/ws/lib/websocket.js:825:20)
at Receiver.emit (events.js:315:20)
at Receiver.dataMessage (/home/leanengine/app/node_modules/ws/lib/receiver.js:437:14)
at /home/leanengine/app/node_modules/ws/lib/receiver.js:394:23
at /home/leanengine/app/node_modules/ws/lib/permessage-deflate.js:308:9
at /home/leanengine/app/node_modules/ws/lib/permessage-deflate.js:387:7
at afterWrite (internal/streams/writable.js:466:5)
at onwrite (internal/streams/writable.js:446:7)
at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
at Zlib.processCallback (zlib.js:587:8)
```

**Comment by kroitor** [comment]
Please, do not overwrite exchange.ohlcvs this way, cause it will break the inner workings of the lib. It's a complex object, that has a cache inside, as documented in the Manual.

Instead, do this:

```JavaScript
const ccxt = require ('ccxt.pro')

async function main () {

    const exchange = new ccxt.binance({
        'enableRateLimit': true,
    })
    
    const timeframe = '1m'
    const symbol = 'ETH/BTC'
    
    // Download historical data
    const historical = await exchange.fetchOHLCV(symbol, timeframe)
    
    while (true) {
        try {
            const ohlcvs = await exchange.watchOHLCV(symbol, timeframe)
            // append ohlcvs
            
            for (const ohlcv of ohlcvs) {
                const lastCandle = historical[historical.length - 1]
                if (ohlcv[0] > lastCandle[0]) {
                    historical.push (ohlcv)
                } else if (ohlcv[0] === lastCandle[0]) {
                    historical[historical.length - 1] = ohlcv
                }
            }

            console.log('\n===============================================================================')
            console.log('Current time:', exchange.iso8601(exchange.milliseconds ()), symbol, timeframe)
            console.log('-------------------------------------------------------------------------------')
            console.log('Most recent candles:')
            console.log(historical.slice (-5).map (o => exchange.iso8601 (o[0]) + '\t' + o.slice (1).map (x => x.toFixed (8)).join ('\t')).join ("\n"))

        } catch (e) {
            console.log (e.constructor.name, e.message)
            process.exit ()
        }
    }
}

main ()
```

Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions if any.

**Comment by Roh-codeur** [comment]
@kroitor. 
thanks for the response. I am trying to do something similar. Quick ques: say the fetchOHLCV has a timeframe of 5 secs, and the call takes longer than 5 sec, say 10 secs. 

`await exchange.fetchOHLCV(symbol, timeframe)`

Now, when I watchOHLCV, I could have missed one bar, while I was fetching the result. is there someway to avoid this please? 

` const ohlcvs = await exchange.watchOHLCV(symbol, timeframe)`

1. I am doing this for multiple symbols at a time
2. say, I start with a list of symbols and then at a later stage, I want to update the original list of symbols. How could I do that? if I call watchOhlcv with new symbols does it automatically handle removing subscriptions?

thanks a lot mate
