### ISSUE TITLE
[wavesexchange] Problems with Rate Limiter

### ISSUE THREAD

**Issue by Maxximiliann** [ccxt/ccxt#8355]
- OS: Ubuntu 20.04.1 LTS
- Programming Language version: Python 3.8.2
- CCXT version: 1.40.3

```
#sandbox.py

import ccxt
import datetime

def main():

    waves_exchange = ccxt.wavesexchange({
        'rateLimit': 1000,
        'enableRateLimit': True,
        'apiKey': 'API_KEY',
        'secret': 'PRIVATE_KEY',
    })

    print('-----------------------------------------------------------')
    print(datetime.datetime.now())
    print('First call:')
    begin_time = datetime.datetime.now()
    balances = waves_exchange.fetchBalance()
    print(datetime.datetime.now() - begin_time)

    while True:
        print('-----------------------------------------------------------')
        print(datetime.datetime.now())
        print('Subsequent call:')
        begin_time = datetime.datetime.now()
        balances = waves_exchange.fetchBalance()
        print(datetime.datetime.now() - begin_time)

if __name__ == '__main__':
    main()

```

```
$ python3 sandbox.py 
-----------------------------------------------------------
2021-01-26 14:12:39.115128
First call:
0:00:04.459241
-----------------------------------------------------------
2021-01-26 14:12:43.574517
Subsequent call:
0:00:02.926449
-----------------------------------------------------------
2021-01-26 14:12:46.501095
Subsequent call:
0:00:02.816256
-----------------------------------------------------------
2021-01-26 14:12:49.317475
Subsequent call:
0:00:03.274282
-----------------------------------------------------------
2021-01-26 14:12:52.591881
Subsequent call:
0:00:02.718729
-----------------------------------------------------------
2021-01-26 14:12:55.310731
Subsequent call:
0:00:02.998748
-----------------------------------------------------------
2021-01-26 14:12:58.309597
Subsequent call:
0:00:02.995877
-----------------------------------------------------------
2021-01-26 14:13:01.305601
Subsequent call:
0:00:03.356364
-----------------------------------------------------------
2021-01-26 14:13:04.662076
Subsequent call:
Traceback (most recent call last):
  File "/home/maxximiliann/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 588, in fetch
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://matcher.waves.exchange/matcher/balance/reserved/###PUBLIC_KEY###

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sandbox.py", line 29, in <module>
    main()
  File "sandbox.py", line 25, in main
    balances = waves_exchange.fetchBalance()
  File "/home/maxximiliann/.local/lib/python3.8/site-packages/ccxt/wavesexchange.py", line 1307, in fetch_balance
    reservedBalance = self.matcherGetMatcherBalanceReservedPublicKey(matcherRequest)
  File "/home/maxximiliann/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/home/maxximiliann/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/maxximiliann/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/maxximiliann/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 604, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/maxximiliann/.local/lib/python3.8/site-packages/ccxt/wavesexchange.py", line 1459, in handle_errors
    raise Exception(self.id + ' ' + message)
ccxt.base.errors.AuthenticationError: wavesexchange The request has an invalid signature

```
As you can see, the rate limit is set to one second but results are generated every +/- three seconds instead. What went wrong? 

Also, why the sudden errors after running perfectly fine for less than a minute?

**Comment by Maxximiliann** [comment]
Any updates on this?

**Comment by ttodua** [comment]
first, you don't have to re-define ratelimiter yourself, unless it's inexistent in ccxt for that particular exchange.
second, it doesnt matter what value is set to ratelimiter if your request-response cycle takes second or few seconds. so, it's not the ratelimiter, but it's time  before you get response back, If you check [wavesexchange's fetchBalance method](https://github.com/ccxt/ccxt/blob/master/js/wavesexchange.js#L1751), you will find out that it's making around 4-5 api calls (`await this.getWavesAddress, await this.nodeGetAssetsBalanceAddress, await this.matcherGetMatcherBalanceReservedPublicKey ...etc...`) in sum. that's probably why it's taking several seconds. if you are critically dependent on particular api-request (from those 5 api calls) then you might use only that implicit api method, however then you will need to manually do other things ourself to convert those responses into balance (which is what ccxt does with the `fetchBalance` method).

If you have any issue, let us know.
