### ISSUE TITLE
InvalidOrder code:-1013 msg: Filter failure: PERCENT_PRICE

### ISSUE THREAD

**Issue by wonderfuldaniel** [ccxt/ccxt#8408]
Hi sorry @kroitor you seem to be the man to go to for help. I've just started working with ccxt and i was following some of the examples but I keep getting the same error when trying to place orders. Just wondering if you could point me in the right direction?

- OS: 10.15 Catalina
- Programming Language version: js
- CCXT version: 

**CODE:**
```
'use strict';
const ccxt = require ('ccxt');

// ----------------------------------------------------------------------------

const tryToCreateOrder = async function (exchange, symbol, type, side, amount, price, params) {

    try {

        const order = await exchange.createOrder (symbol, type, side, amount, price, params)
        return order

    } catch (e) {

        console.log (e.constructor.name, e.message)

        if (e instanceof ccxt.NetworkError) {

            // retry on networking errors
            return false

        } else {

            throw e // break on all other exceptions
        }
    }
}

// ----------------------------------------------------------------------------

const exchange = new ccxt.binance ({
    'apiKey': ' ', // edit here
    'secret': ' ',  // edit here
    'enableRateLimit': true,  // required by the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

const symbol = 'DOGE/USDT' // edit here
const type = 'limit'     // edit here
const side = 'sell'       // edit here
const amount = 1         // edit here
const price = 1.10       // edit here
const params = {}        // edit here

;(async () => {
    let order = false
    while (true) {
        order = await tryToCreateOrder (exchange, symbol, type, side, amount, price, params)
        if (order !== false) {
            break
        }
    }
    console.log (order)
}) ()
```

**OUTPUT:**

```
InvalidOrder binance {"code":-1013,"msg":"Filter failure: PERCENT_PRICE"}
/Users/daniel/Documents/Personal Misc/BiBot/node_modules/ccxt/js/base/Exchange.js:532
            throw new exact[string] (message)
                  ^

InvalidOrder: binance {"code":-1013,"msg":"Filter failure: PERCENT_PRICE"}
    at binance.throwExactlyMatchedException (/Users/daniel/Documents/Personal Misc/BiBot/node_modules/ccxt/js/base/Exchange.js:532:19)
    at binance.handleErrors (/Users/daniel/Documents/Personal Misc/BiBot/node_modules/ccxt/js/binance.js:2700:18)
    at /Users/daniel/Documents/Personal Misc/BiBot/node_modules/ccxt/js/base/Exchange.js:602:18
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async timeout (/Users/daniel/Documents/Personal Misc/BiBot/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async binance.request (/Users/daniel/Documents/Personal Misc/BiBot/node_modules/ccxt/js/binance.js:2709:26)
    at async binance.createOrder (/Users/daniel/Documents/Personal Misc/BiBot/node_modules/ccxt/js/binance.js:1796:26)
    at async tryToCreateOrder (/Users/daniel/Documents/Personal Misc/BiBot/node_modules/ccxt/test.js:10:23)
    at async /Users/daniel/Documents/Personal Misc/BiBot/node_modules/ccxt/test.js:47:17 {
  constructor: [class InvalidOrder extends ExchangeError]
}
```

**Comment by kroitor** [comment]
Hi @wonderfuldaniel !

In short, each exchange has limits on min/max price and precision, please, check these sections of the Manual

- https://github.com/ccxt/ccxt/wiki/Manual#markets
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Specific limit values will depend on the trading pair/symbol in question.

Also, please, check this issue:

- https://github.com/ccxt/ccxt/issues/8322

Use `verbose` mode for debugging:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting


```
~/ccxt $ node examples/js/cli binance market DOGE/USDT
Node.js: v14.15.4
CCXT v1.41.86
binance.market (DOGE/USDT)
{      limits: { amount: { min: 1, max: 90000000 },
                  price: { min: 1e-7, max: 1000 },
                   cost: { min: 10, max: undefined },
                 market: { min: 0, max: 15187187.87083333 } },
    precision: { base: 8, quote: 8, amount: 0, price: 7 },
    tierBased:    false,
   percentage:    true,
        taker:    0.001,
        maker:    0.001,
           id:   "DOGEUSDT",
  lowercaseId:   "dogeusdt",
       symbol:   "DOGE/USDT",
         base:   "DOGE",
        quote:   "USDT",
       baseId:   "DOGE",
      quoteId:   "USDT",
         info: {                     symbol:   "DOGEUSDT",
                                     status:   "TRADING",
                                  baseAsset:   "DOGE",
                         baseAssetPrecision:    8,
                                 quoteAsset:   "USDT",
                             quotePrecision:    8,
                        quoteAssetPrecision:    8,
                    baseCommissionPrecision:    8,
                   quoteCommissionPrecision:    8,
                                 orderTypes: [ "LIMIT",
                                               "LIMIT_MAKER",
                                               "MARKET",
                                               "STOP_LOSS_LIMIT",
                                               "TAKE_PROFIT_LIMIT" ],
                             icebergAllowed:    true,
                                 ocoAllowed:    true,
                 quoteOrderQtyMarketAllowed:    true,
                       isSpotTradingAllowed:    true,
                     isMarginTradingAllowed:    true,
                                    filters: [ { filterType: "PRICE_FILTER",
                                                   minPrice: "0.00000010",
                                                   maxPrice: "1000.00000000",
                                                   tickSize: "0.00000010"     },
                                               {     filterType: "PERCENT_PRICE",
                                                   multiplierUp: "5",
                                                 multiplierDown: "0.2",
                                                   avgPriceMins:  5               },
                                               { filterType: "LOT_SIZE",
                                                     minQty: "1.00000000",
                                                     maxQty: "90000000.00000000",
                                                   stepSize: "1.00000000"         },
                                               {    filterType: "MIN_NOTIONAL",
                                                   minNotional: "10.00000000",
                                                 applyToMarket:  true,
                                                  avgPriceMins:  5              },
                                               { filterType: "ICEBERG_PARTS", limit: 10 },
                                               { filterType: "MARKET_LOT_SIZE",
                                                     minQty: "0.00000000",
                                                     maxQty: "15187187.87083333",
                                                   stepSize: "0.00000000"         },
                                               {   filterType: "MAX_NUM_ORDERS",
                                                 maxNumOrders:  200              },
                                               {       filterType: "MAX_NUM_ALGO_ORDERS",
                                                 maxNumAlgoOrders:  5                     } ],
                                permissions: ["SPOT", "MARGIN"]                                },
         type:   "spot",
         spot:    true,
       margin:    true,
       future:    false,
     delivery:    false,
       active:    true                                                                            }
~/ccxt $
```

↑ See `filters` above. They're explained in-depth here: https://binance-docs.github.io/apidocs/spot/en/#filters

Let us know if the above does not help.

**Comment by kroitor** [comment]
P.S. The PERCENT_PRICE filter error means your price is too far away from the currently traded range of prices (beyond the up/down multiplier).

**Comment by kroitor** [comment]
@naserkaka you price must be lower than 5 * 1.07 and higher than 0.2 * 1.07, and it should also satisfy the other price filters. All rules are combined here: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance()
markets = exchange.load_markets()
market = exchange.market('XRP/USDT')
pprint(market)
```
