### ISSUE TITLE
Coinbase BadRequest https://api.coinbase.com/v2/exchange-rates

### ISSUE THREAD

**Issue by chiwalfrm** [ccxt/ccxt#8443]
This just happened even though I did not change any of my code.  All I am calling is a fetchbalance().
I did upgrade to the latest ccxt version 1.41.81 but it didn't fix the issue.

```
vmware@ubuntu20041a:~/extra$ python3 ccoinbase.py
Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 589, in fetch
    response.raise_for_status()
  File "/home/vmware/.local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coinbase.com/v2/exchange-rates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ccoinbase.py", line 5, in <module>
    pp.pprint(coinbase.fetchBalance())
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 688, in fetch_balance
    self.load_markets()
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1354, in load_markets
    currencies = self.fetch_currencies()
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 575, in fetch_currencies
    response = self.fetch_currencies_from_cache(params)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 566, in fetch_currencies_from_cache
    exchangeRates = self.publicGetExchangeRates(params)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 491, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 605, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 1145, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeError: coinbase {"errors":[{"id":"invalid_request","message":"Invalid currency (USD)"}]}
```

**Comment by kroitor** [comment]
@chiwalfrm please, paste your code (without your keys) and your verbose output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by chiwalfrm** [comment]
it's just 3 lines

```
import ccxt
coinbase1 = ccxt.coinbase({'apiKey': '<myapikey>', 'secret': '<mysecret>', 'enableRateLimit': True})
print(coinbase1.fetchBalance())
```

**Comment by kroitor** [comment]
@chiwalfrm please, paste your verbose output and your runtime version number:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
coinbase = ccxt.coinbase({
    'apiKey': '<myapikey>',
    'secret': '<mysecret>',
    'enableRateLimit': True,
    'verbose': True,
})
print(coinbase1.fetchBalance())
```

**Comment by chiwalfrm** [comment]
here yo go:  thanks!

```
vmware@ubuntu20041a:~/extra$ python3 a.py
CCXT Version: 1.41.81

Request: GET https://api.coinbase.com/v2/currencies {'CB-VERSION': '2018-05-30', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.coinbase.com/v2/currencies 200 {'Date': 'Thu, 11 Feb 2021 07:02:47 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=db2a7384eae15de5037dcb3190e8fe0451613026967; expires=Sat, 13-Mar-21 07:02:47 GMT; path=/; domain=.coinbase.com; HttpOnly; SameSite=Lax; Secure, __cf_bm=60f1d2c32a4e6d312fe9d770bcce698f36baebee-1613026967-1800-ATx/GGrvMyeSFZA+4E/Z10dfB5ZEHGKxqdqYfjqwiJT41Nt9OiUZM82q/rweD6ahO/s7dqB9mwY+XB/zs6FUHS4=; path=/; expires=Thu, 11-Feb-21 07:32:47 GMT; domain=.coinbase.com; HttpOnly; Secure', 'Cache-Control': 'max-age=86400, public, s-maxage=86400', 'content-disposition': 'attachment; filename=response.json', 'ETag': 'W/"a2b324227ce55c2f09a335e4d32aa49f"', 'X-Request-Id': '2cb646f5-5e61-436f-a5d2-e9e66af8ace8', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Vary': 'Origin,Accept-Encoding', 'X-Powered-By': 'Proof-of-Work', 'Expect-CT': 'enforce, max-age=86400, report-uri="https://coinbase.report-uri.io/r/default/ct/reportOnly"', 'Content-Security-Policy': "default-src 'self' https://www.coinbase.com; child-src 'self' https://www.coinbase.com https://fast.wistia.net https://*.online-metrix.net https://*.wpstn.com https://netverify.com https://platform.twitter.com https://www.google.com/recaptcha/ https://cdn.plaid.com/link/ https://*.doubleclick.net/ blob:; connect-src 'self' https://www.coinbase.com https://api.coinbase.com https://*.online-metrix.net https://api.cloudinary.com https://ott9.wpstn.com/live https://api.amplitude.com/ https://api2.amplitude.com/ https://d3907m2cqladbn.cloudfront.net/ https://exceptions.coinbase.com https://assets.coinbase.com/ https://sessions.coinbase.com/ https://dynamic-assets.coinbase.com/ https://events-service.coinbase.com/amp static.coinbase.com wss://ws.coinbase.com wss://ws.coinbase.com:443 https://www.coinbase.com/api; font-src 'self' https://www.coinbase.com https://assets.coinbase.com/ https://card.coinbase.com/ static.coinbase.com; img-src 'self' data: https://www.coinbase.com https://images.coinbase.com https://d3907m2cqladbn.cloudfront.net/ https://static-assets.coinbase.com/ https://dynamic-assets.coinbase.com/ https://exceptions.coinbase.com https://coinbase-uploads.s3.amazonaws.com https://s3.amazonaws.com/app-public/ https://maps.gstatic.com https://ssl.google-analytics.com https://www.google.com https://maps.googleapis.com https://csi.gstatic.com https://www.google-analytics.com https://res.cloudinary.com https://secure.gravatar.com https://i2.wp.com https://*.online-metrix.net https://assets.coinbase.com/ https://hexagon-analytics.com https://cb-brand.s3.amazonaws.com https://googleads.g.doubleclick.net https://stats.g.doubleclick.net/r/collect https://card.coinbase.com/ blob: static.coinbase.com https://www.facebook.com/tr; media-src 'self' https://www.coinbase.com blob:; object-src 'self' data: blob: https://www.coinbase.com https://cdn.siftscience.com https://*.online-metrix.net https://www.gstatic.com https://www.google.com/recaptcha/api/; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.coinbase.com https://fast.wistia.com/assets/external/E-v1.js https://cdn.siftscience.com https://*.google-analytics.com https://www.google.com https://www.gstatic.com https://*.online-metrix.net https://code.jquery.com https://chart.googleapis.com https://maps.googleapis.com https://maps.gstatic.com https://netverify.com https://ajax.cloudflare.com https://cdn.plaid.com/link/v2/stable/ https://www.googletagmanager.com/gtag/js https://www.googletagmanager.com/gtm.js https://www.googleadservices.com https://googleads.g.doubleclick.net https://assets.coinbase.com/ https://card.coinbase.com/ static.coinbase.com; style-src 'self' 'unsafe-inline' https://www.coinbase.com https://assets.coinbase.com/ https://card.coinbase.com/ static.coinbase.com; report-uri /csp-report", 'Referrer-Policy': 'strict-origin-when-cross-origin', 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'DENY', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '1; mode=block', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '08317f55e000000eca14a20000000001', 'Server': 'cloudflare', 'CF-RAY': '61fc34cfcd190eca-DFW'} {"data":[{"id":"AED","name":"United Arab Emirates Dirham","min_size":"0.01000000"},{"id":"AFN","name":"Afghan Afghani","min_size":"0.01000000"},{"id":"ALL","name":"Albanian Lek","min_size":"0.01000000"},{"id":"AMD","name":"Armenian Dram","min_size":"0.01000000"},{"id":"ANG","name":"Netherlands Antillean Gulden","min_size":"0.01000000"},{"id":"AOA","name":"Angolan Kwanza","min_size":"0.01000000"},{"id":"ARS","name":"Argentine Peso","min_size":"0.01000000"},{"id":"AUD","name":"Australian Dollar","min_size":"0.01000000"},{"id":"AWG","name":"Aruban Florin","min_size":"0.01000000"},{"id":"AZN","name":"Azerbaijani Manat","min_size":"0.01000000"},{"id":"BAM","name":"Bosnia and Herzegovina Convertible Mark","min_size":"0.01000000"},{"id":"BBD","name":"Barbadian Dollar","min_size":"0.01000000"},{"id":"BDT","name":"Bangladeshi Taka","min_size":"0.01000000"},{"id":"BGN","name":"Bulgarian Lev","min_size":"0.01000000"},{"id":"BHD","name":"Bahraini Dinar","min_size":"0.00100000"},{"id":"BIF","name":"Burundian Franc","min_size":"1.00000000"},{"id":"BMD","name":"Bermudian Dollar","min_size":"0.01000000"},{"id":"BND","name":"Brunei Dollar","min_size":"0.01000000"},{"id":"BOB","name":"Bolivian Boliviano","min_size":"0.01000000"},{"id":"BRL","name":"Brazilian Real","min_size":"0.01000000"},{"id":"BSD","name":"Bahamian Dollar","min_size":"0.01000000"},{"id":"BTN","name":"Bhutanese Ngultrum","min_size":"0.01000000"},{"id":"BWP","name":"Botswana Pula","min_size":"0.01000000"},{"id":"BYN","name":"Belarusian Ruble","min_size":"0.01000000"},{"id":"BYR","name":"Belarusian Ruble","min_size":"1.00000000"},{"id":"BZD","name":"Belize Dollar","min_size":"0.01000000"},{"id":"CAD","name":"Canadian Dollar","min_size":"0.01000000"},{"id":"CDF","name":"Congolese Franc","min_size":"0.01000000"},{"id":"CHF","name":"Swiss Franc","min_size":"0.01000000"},{"id":"CLF","name":"Unidad de Fomento","min_size":"0.00010000"},{"id":"CLP","name":"Chilean Peso","min_size":"1.00000000"},{"id":"CNH","name":"Chinese Renminbi Yuan Offshore","min_size":"0.01000000"},{"id":"CNY","name":"Chinese Renminbi Yuan","min_size":"0.01000000"},{"id":"COP","name":"Colombian Peso","min_size":"0.01000000"},{"id":"CRC","name":"Costa Rican Colón","min_size":"0.01000000"},{"id":"CUC","name":"Cuban Convertible Peso","min_size":"0.01000000"},{"id":"CVE","name":"Cape Verdean Escudo","min_size":"0.01000000"},{"id":"CZK","name":"Czech Koruna","min_size":"0.01000000"},{"id":"DJF","name":"Djiboutian Franc","min_size":"1.00000000"},{"id":"DKK","name":"Danish Krone","min_size":"0.01000000"},{"id":"DOP","name":"Dominican Peso","min_size":"0.01000000"},{"id":"DZD","name":"Algerian Dinar","min_size":"0.01000000"},{"id":"EGP","name":"Egyptian Pound","min_size":"0.01000000"},{"id":"ERN","name":"Eritrean Nakfa","min_size":"0.01000000"},{"id":"ETB","name":"Ethiopian Birr","min_size":"0.01000000"},{"id":"EUR","name":"Euro","min_size":"0.01000000"},{"id":"FJD","name":"Fijian Dollar","min_size":"0.01000000"},{"id":"FKP","name":"Falkland Pound","min_size":"0.01000000"},{"id":"GBP","name":"British Pound","min_size":"0.01000000"},{"id":"GEL","name":"Georgian Lari","min_size":"0.01000000"},{"id":"GGP","name":"Guernsey Pound","min_size":"0.01000000"},{"id":"GHS","name":"Ghanaian Cedi","min_size":"0.01000000"},{"id":"GIP","name":"Gibraltar Pound","min_size":"0.01000000"},{"id":"GMD","name":"Gambian Dalasi","min_size":"0.01000000"},{"id":"GNF","name":"Guinean Franc","min_size":"1.00000000"},{"id":"GTQ","name":"Guatemalan Quetzal","min_size":"0.01000000"},{"id":"GYD","name":"Guyanese Dollar","min_size":"0.01000000"},{"id":"HKD","name":"Hong Kong Dollar","min_size":"0.01000000"},{"id":"HNL","name":"Honduran Lempira","min_size":"0.01000000"},{"id":"HRK","name":"Croatian Kuna","min_size":"0.01000000"},{"id":"HTG","name":"Haitian Gourde","min_size":"0.01000000"},{"id":"HUF","name":"Hungarian Forint","min_size":"1.00000000"},{"id":"IDR","name":"Indonesian Rupiah","min_size":"0.01000000"},{"id":"ILS","name":"Israeli New Sheqel","min_size":"0.01000000"},{"id":"IMP","name":"Isle of Man Pound","min_size":"0.01000000"},{"id":"INR","name":"Indian Rupee","min_size":"0.01000000"},{"id":"IQD","name":"Iraqi Dinar","min_size":"0.00100000"},{"id":"ISK","name":"Icelandic Króna","min_size":"1.00000000"},{"id":"JEP","name":"Jersey Pound","min_size":"0.01000000"},{"id":"JMD","name":"Jamaican Dollar","min_size":"0.01000000"},{"id":"JOD","name":"Jordanian Dinar","min_size":"0.00100000"},{"id":"JPY","name":"Japanese Yen","min_size":"1.00000000"},{"id":"KES","name":"Kenyan Shilling","min_size":"0.01000000"},{"id":"KGS","name":"Kyrgyzstani Som","min_size":"0.01000000"},{"id":"KHR","name":"Cambodian Riel","min_size":"0.01000000"},{"id":"KMF","name":"Comorian Franc","min_size":"1.00000000"},{"id":"KRW","name":"South Korean Won","min_size":"1.00000000"},{"id":"KWD","name":"Kuwaiti Dinar","min_size":"0.00100000"},{"id":"KYD","name":"Cayman Islands Dollar","min_size":"0.01000000"},{"id":"KZT","name":"Kazakhstani Tenge","min_size":"0.01000000"},{"id":"LAK","name":"Lao Kip","min_size":"0.01000000"},{"id":"LBP","name":"Lebanese Pound","min_size":"0.01000000"},{"id":"LKR","name":"Sri Lankan Rupee","min_size":"0.01000000"},{"id":"LRD","name":"Liberian Dollar","min_size":"0.01000000"},{"id":"LSL","name":"Lesotho Loti","min_size":"0.01000000"},{"id":"LYD","name":"Libyan Dinar","min_size":"0.00100000"},{"id":"MAD","name":"Moroccan Dirham","min_size":"0.01000000"},{"id":"MDL","name":"Moldovan Leu","min_size":"0.01000000"},{"id":"MGA","name":"Malagasy Ariary","min_size":"0.20000000"},{"id":"MKD","name":"Macedonian Denar","min_size":"0.01000000"},{"id":"MMK","name":"Myanmar Kyat","min_size":"0.01000000"},{"id":"MNT","name":"Mongolian Tögrög","min_size":"0.01000000"},{"id":"MOP","name":"Macanese Pataca","min_size":"0.01000000"},{"id":"MRO","name":"Mauritanian Ouguiya","min_size":"0.20000000"},{"id":"MUR","name":"Mauritian Rupee","min_size":"0.01000000"},{"id":"MVR","name":"Maldivian Rufiyaa","min_size":"0.01000000"},{"id":"MWK","name":"Malawian Kwacha","min_size":"0.01000000"},{"id":"MXN","name":"Mexican Peso","min_size":"0.01000000"},{"id":"MYR","name":"Malaysian Ringgit","min_size":"0.01000000"},{"id":"MZN","name":"Mozambican Metical","min_size":"0.01000000"},{"id":"NAD","name":"Namibian Dollar","min_size":"0.01000000"},{"id":"NGN","name":"Nigerian Naira","min_size":"0.01000000"},{"id":"NIO","name":"Nicaraguan Córdoba","min_size":"0.01000000"},{"id":"NOK","name":"Norwegian Krone","min_size":"0.01000000"},{"id":"NPR","name":"Nepalese Rupee","min_size":"0.01000000"},{"id":"NZD","name":"New Zealand Dollar","min_size":"0.01000000"},{"id":"OMR","name":"Omani Rial","min_size":"0.00100000"},{"id":"PAB","name":"Panamanian Balboa","min_size":"0.01000000"},{"id":"PEN","name":"Peruvian Sol","min_size":"0.01000000"},{"id":"PGK","name":"Papua New Guinean Kina","min_size":"0.01000000"},{"id":"PHP","name":"Philippine Peso","min_size":"0.01000000"},{"id":"PKR","name":"Pakistani Rupee","min_size":"0.01000000"},{"id":"PLN","name":"Polish Złoty","min_size":"0.01000000"},{"id":"PYG","name":"Paraguayan Guaraní","min_size":"1.00000000"},{"id":"QAR","name":"Qatari Riyal","min_size":"0.01000000"},{"id":"RON","name":"Romanian Leu","min_size":"0.01000000"},{"id":"RSD","name":"Serbian Dinar","min_size":"0.01000000"},{"id":"RUB","name":"Russian Ruble","min_size":"0.01000000"},{"id":"RWF","name":"Rwandan Franc","min_size":"1.00000000"},{"id":"SAR","name":"Saudi Riyal","min_size":"0.01000000"},{"id":"SBD","name":"Solomon Islands Dollar","min_size":"0.01000000"},{"id":"SCR","name":"Seychellois Rupee","min_size":"0.01000000"},{"id":"SEK","name":"Swedish Krona","min_size":"0.01000000"},{"id":"SGD","name":"Singapore Dollar","min_size":"0.01000000"},{"id":"SHP","name":"Saint Helenian Pound","min_size":"0.01000000"},{"id":"SLL","name":"Sierra Leonean Leone","min_size":"0.01000000"},{"id":"SOS","name":"Somali Shilling","min_size":"0.01000000"},{"id":"SRD","name":"Surinamese Dollar","min_size":"0.01000000"},{"id":"SSP","name":"South Sudanese Pound","min_size":"0.01000000"},{"id":"STD","name":"São Tomé and Príncipe Dobra","min_size":"0.01000000"},{"id":"SVC","name":"Salvadoran Colón","min_size":"0.01000000"},{"id":"SZL","name":"Swazi Lilangeni","min_size":"0.01000000"},{"id":"THB","name":"Thai Baht","min_size":"0.01000000"},{"id":"TJS","name":"Tajikistani Somoni","min_size":"0.01000000"},{"id":"TMT","name":"Turkmenistani Manat","min_size":"0.01000000"},{"id":"TND","name":"Tunisian Dinar","min_size":"0.00100000"},{"id":"TOP","name":"Tongan Paʻanga","min_size":"0.01000000"},{"id":"TRY","name":"Turkish Lira","min_size":"0.01000000"},{"id":"TTD","name":"Trinidad and Tobago Dollar","min_size":"0.01000000"},{"id":"TWD","name":"New Taiwan Dollar","min_size":"0.01000000"},{"id":"TZS","name":"Tanzanian Shilling","min_size":"0.01000000"},{"id":"UAH","name":"Ukrainian Hryvnia","min_size":"0.01000000"},{"id":"UGX","name":"Ugandan Shilling","min_size":"1.00000000"},{"id":"USD","name":"US Dollar","min_size":"0.01000000"},{"id":"UYU","name":"Uruguayan Peso","min_size":"0.01000000"},{"id":"UZS","name":"Uzbekistan Som","min_size":"0.01000000"},{"id":"VEF","name":"Venezuelan Bolívar","min_size":"0.01000000"},{"id":"VES","name":"Venezuelan Bolívar Soberano","min_size":"0.01000000"},{"id":"VND","name":"Vietnamese Đồng","min_size":"1.00000000"},{"id":"VUV","name":"Vanuatu Vatu","min_size":"1.00000000"},{"id":"WST","name":"Samoan Tala","min_size":"0.01000000"},{"id":"XAF","name":"Central African Cfa Franc","min_size":"1.00000000"},{"id":"XAG","name":"Silver (Troy Ounce)","min_size":"1.00000000"},{"id":"XAU","name":"Gold (Troy Ounce)","min_size":"1.00000000"},{"id":"XCD","name":"East Caribbean Dollar","min_size":"0.01000000"},{"id":"XDR","name":"Special Drawing Rights","min_size":"1.00000000"},{"id":"XOF","name":"West African Cfa Franc","min_size":"1.00000000"},{"id":"XPD","name":"Palladium","min_size":"1.00000000"},{"id":"XPF","name":"Cfp Franc","min_size":"1.00000000"},{"id":"XPT","name":"Platinum","min_size":"1.00000000"},{"id":"YER","name":"Yemeni Rial","min_size":"0.01000000"},{"id":"ZAR","name":"South African Rand","min_size":"0.01000000"},{"id":"ZMW","name":"Zambian Kwacha","min_size":"0.01000000"},{"id":"ZWL","name":"Zimbabwean Dollar","min_size":"0.01000000"}]}

Request: GET https://api.coinbase.com/v2/exchange-rates {'CB-VERSION': '2018-05-30', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.coinbase.com/v2/exchange-rates 400 {'Date': 'Thu, 11 Feb 2021 07:02:47 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=db2a7384eae15de5037dcb3190e8fe0451613026967; expires=Sat, 13-Mar-21 07:02:47 GMT; path=/; domain=.coinbase.com; HttpOnly; SameSite=Lax; Secure, __cf_bm=bb3ed30eb25e3dfdf5676a76b21a8b65f3727e9c-1613026967-1800-AYzmmQKK2kold+gog+Q1XYor1SVPmnEkkJY16m2s7uJJtapD+Jon7UgeIJdIjv1ywzNRWuvd5E7+YUiQrw5vC+4=; path=/; expires=Thu, 11-Feb-21 07:32:47 GMT; domain=.coinbase.com; HttpOnly; Secure', 'Cache-Control': 'max-age=30, public, s-maxage=30', 'content-disposition': 'attachment; filename=response.json', 'X-Request-Id': 'dfe8540a-36af-4da6-8045-e58013b53c7d', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Vary': 'Origin,Accept-Encoding', 'X-Powered-By': 'Proof-of-Work', 'Expect-CT': 'enforce, max-age=86400, report-uri="https://coinbase.report-uri.io/r/default/ct/reportOnly"', 'Content-Security-Policy': "default-src 'self' https://www.coinbase.com; child-src 'self' https://www.coinbase.com https://fast.wistia.net https://*.online-metrix.net https://*.wpstn.com https://netverify.com https://platform.twitter.com https://www.google.com/recaptcha/ https://cdn.plaid.com/link/ https://*.doubleclick.net/ blob:; connect-src 'self' https://www.coinbase.com https://api.coinbase.com https://*.online-metrix.net https://api.cloudinary.com https://ott9.wpstn.com/live https://api.amplitude.com/ https://api2.amplitude.com/ https://d3907m2cqladbn.cloudfront.net/ https://exceptions.coinbase.com https://assets.coinbase.com/ https://sessions.coinbase.com/ https://dynamic-assets.coinbase.com/ https://events-service.coinbase.com/amp static.coinbase.com wss://ws.coinbase.com wss://ws.coinbase.com:443 https://www.coinbase.com/api; font-src 'self' https://www.coinbase.com https://assets.coinbase.com/ https://card.coinbase.com/ static.coinbase.com; img-src 'self' data: https://www.coinbase.com https://images.coinbase.com https://d3907m2cqladbn.cloudfront.net/ https://static-assets.coinbase.com/ https://dynamic-assets.coinbase.com/ https://exceptions.coinbase.com https://coinbase-uploads.s3.amazonaws.com https://s3.amazonaws.com/app-public/ https://maps.gstatic.com https://ssl.google-analytics.com https://www.google.com https://maps.googleapis.com https://csi.gstatic.com https://www.google-analytics.com https://res.cloudinary.com https://secure.gravatar.com https://i2.wp.com https://*.online-metrix.net https://assets.coinbase.com/ https://hexagon-analytics.com https://cb-brand.s3.amazonaws.com https://googleads.g.doubleclick.net https://stats.g.doubleclick.net/r/collect https://card.coinbase.com/ blob: static.coinbase.com https://www.facebook.com/tr; media-src 'self' https://www.coinbase.com blob:; object-src 'self' data: blob: https://www.coinbase.com https://cdn.siftscience.com https://*.online-metrix.net https://www.gstatic.com https://www.google.com/recaptcha/api/; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.coinbase.com https://fast.wistia.com/assets/external/E-v1.js https://cdn.siftscience.com https://*.google-analytics.com https://www.google.com https://www.gstatic.com https://*.online-metrix.net https://code.jquery.com https://chart.googleapis.com https://maps.googleapis.com https://maps.gstatic.com https://netverify.com https://ajax.cloudflare.com https://cdn.plaid.com/link/v2/stable/ https://www.googletagmanager.com/gtag/js https://www.googletagmanager.com/gtm.js https://www.googleadservices.com https://googleads.g.doubleclick.net https://assets.coinbase.com/ https://card.coinbase.com/ static.coinbase.com; style-src 'self' 'unsafe-inline' https://www.coinbase.com https://assets.coinbase.com/ https://card.coinbase.com/ static.coinbase.com; report-uri /csp-report", 'Referrer-Policy': 'strict-origin-when-cross-origin', 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'DENY', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '1; mode=block', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'HIT', 'Age': '23', 'cf-request-id': '08317f572900000eca1c3ff000000001', 'Server': 'cloudflare', 'CF-RAY': '61fc34d1d84f0eca-DFW'} {"errors":[{"id":"invalid_request","message":"Invalid currency (USD)"}]}
Traceback (most recent call last):
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 589, in fetch
    response.raise_for_status()
  File "/home/vmware/.local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coinbase.com/v2/exchange-rates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 9, in <module>
    print(exchange.fetch_balance())
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 688, in fetch_balance
    self.load_markets()
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1354, in load_markets
    currencies = self.fetch_currencies()
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 575, in fetch_currencies
    response = self.fetch_currencies_from_cache(params)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 566, in fetch_currencies_from_cache
    exchangeRates = self.publicGetExchangeRates(params)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 491, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 605, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/coinbase.py", line 1145, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/vmware/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeError: coinbase {"errors":[{"id":"invalid_request","message":"Invalid currency (USD)"}]}
vmware@ubuntu20041a:~/extra$

```

**Comment by kroitor** [comment]
Another endpoint for currencies is broken... Doesn't work for me either. 

Try this with curl or with your browser: curl https://api.coinbase.com/v2/exchange-rates

Docs: https://developers.coinbase.com/api/v2#exchange-rates

If it does not work for you without CCXT, then this is not an issue inside CCXT – looks like a problem at Coinbase or smth.

**Comment by chiwalfrm** [comment]
it's fixed!  must be coinbase messing around...  closing this issue.
