### ISSUE TITLE
kucoin fetch_my_trades causes error when since (miliseconds) is no integer

### ISSUE THREAD

**Issue by r4VP4** [ccxt/ccxt#8468]
- OS: WIN 10
- Programming Language version: python 3.8.7
- CCXT version: 1.41.93

```
import ccxt

kucoin = ccxt.kucoin({
    'apiKey': 'blablabla',
    'secret': 'blablabla',
    'password': 'blablabla',
    'verbose': True})

trades = kucoin.fetch_my_trades()
# --> works

since = 1613453676299
trades = kucoin.fetch_my_trades(since=since)
# --> works

since = 1613453916819.7798
trades = kucoin.fetch_my_trades(since=since)
# ccxt.base.errors.BadSymbol: Bad Request
```

```
Traceback (most recent call last):
  File "C:/Users/Tobias Wolff/PycharmProjects/ccxtpostgres/playground/ccxt_issue.py", line 19, in <module>
    trades = kucoin.fetch_my_trades(since=since)
  File "C:\Users\Tobias Wolff\.virtualenvs\ccxtpostgres\lib\site-packages\ccxt\kucoin.py", line 1040, in fetch_my_trades
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\Tobias Wolff\.virtualenvs\ccxtpostgres\lib\site-packages\ccxt\base\exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Tobias Wolff\.virtualenvs\ccxtpostgres\lib\site-packages\ccxt\base\exchange.py", line 491, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Tobias Wolff\.virtualenvs\ccxtpostgres\lib\site-packages\ccxt\base\exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Tobias Wolff\.virtualenvs\ccxtpostgres\lib\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Tobias Wolff\.virtualenvs\ccxtpostgres\lib\site-packages\ccxt\kucoin.py", line 1717, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, message)
  File "C:\Users\Tobias Wolff\.virtualenvs\ccxtpostgres\lib\site-packages\ccxt\base\exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadSymbol: Bad Request
```

Using an noninteger since-value (which is often the case if you do calculations like (time.time()- 60 * 60 * 10)*1000 )
causes the above error.

**Comment by kroitor** [comment]
The value you pass in the `since` argument is expected to be an integer in millisecond (this is documented throughout the Manual).

Do this:

```Python
trades = kucoin.fetch_my_trades(since=int(since))
```
