### ISSUE TITLE
Getting timeout but with curl there is no issue

### ISSUE THREAD

**Issue by unrelenting-d1x** [ccxt/ccxt#8500]
- OS: MacOSX 10.15.7
- Programming Language version: JavaScript
- CCXT version: 1.42.15

Code to reproduce:
```
(async () => {
    var ccxt = require ('ccxt')
    console.log(ccxt.version)

    let binance = new ccxt.binance({
        // 'enableRateLimit': true,
        'options': { 'defaultType': 'future' },
    })

    let b_markets = binance.load_markets()

    const b_f_rate = await binance.fapiPublicGetFundingRate()
    console.log (b_f_rate)

})()
```

Error from the code

```
                            throw new ExchangeNotAvailable ([ this.id, method, url, e.type, e.message ].join (' '))
                                  ^

ExchangeNotAvailable: binance GET https://fapi.binance.com/fapi/v1/fundingRate system request to https://fapi.binance.com/fapi/v1/fundingRate failed, reason: read ECONNRESET
    at /Users/xxx/Documents/repo/farb/node_modules/ccxt/js/base/Exchange.js:395:35
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async timeout (/Users/xxx/Documents/repo/farb/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async binance.request (/Users/xxx/Documents/repo/farb/node_modules/ccxt/js/binance.js:2870:26)
    at async /Users/xxx/Documents/repo/farb/index.js:24:22 {
  constructor: [class ExchangeNotAvailable extends NetworkError]
}

                    throw new RequestTimeout (this.id + ' ' + method + ' ' + url + ' request timed out (' + this.timeout + ' ms)')
                          ^

RequestTimeout: binance GET https://fapi.binance.com/fapi/v1/fundingRate request timed out (10000 ms)
    at /Users/xxx/Documents/repo/farb/node_modules/ccxt/js/base/Exchange.js:403:27
    at runNextTicks (node:internal/process/task_queues:58:5)
    at listOnTimeout (node:internal/timers:525:9)
    at processTimers (node:internal/timers:499:7)
    at async binance.request (/Users/xxx/Documents/repo/farb/node_modules/ccxt/js/binance.js:2870:26)
    at async /Users/xxx/Documents/repo/farb/index.js:24:22 {
  constructor: [class RequestTimeout extends NetworkError]
}
```

I keep getting error either RequestTimeout or ECONNRESET but when I use curl to request the url anything works fine. Any clue why this is happening?

**Comment by kroitor** [comment]
@unrelenting-d1x hi! Do you still have the same issue? Binance had intermittent issues due to high loads recently, that could explain the above results...

**Comment by unrelenting-d1x** [comment]
Now it happens much less frequent. I will close this ticket for now. Thanks for the response!

**Comment by kroitor** [comment]
@unrelenting-d1x ok, thx for your feedback, feel free to reopen it if anything or just ask further questions if any.
