### ISSUE TITLE
Digifinex request timestamp is invalid(python library, nonce timestamp in miliseconds)

### ISSUE THREAD

**Issue by garry-1990** [ccxt/ccxt#8504]
**Actual result:** When I do request fetch_balance or create_order error shown:
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    mm_bot = MarketMakerBot(settings, storage)
  File "/home/ivan/WORK/market-maker/bot.py", line 36, in __init__
    fetch_balance = self._exchange.fetch_balance()
  File "/home/ivan/.local/lib/python3.6/site-packages/ccxt/digifinex.py", line 452, in fetch_balance
    response = getattr(self, method)(params)
  File "/home/ivan/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ivan/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 493, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/ivan/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 489, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ivan/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 631, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ivan/.local/lib/python3.6/site-packages/ccxt/digifinex.py", line 1454, in handle_errors
    raise ExceptionClass(message)
ccxt.base.errors.InvalidNonce: Timestamp for self request is invalid, timestamp must within 1 minute

**Expected result:** When I do request fetch_balance or create_order error must be missing and server response must be successful.

**Comment by kroitor** [comment]
@garry-1990 make sure you system clock is sync with UTC:

- https://github.com/ccxt/ccxt/wiki/Manual#invalidnonce

If that does not help, please, paste your verbose output (just the error stacktrace is not enough, add `exchange.verbose = True` before fetching the balance):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Feel free to reopen this issue or just ask further questions if any.

**Comment by NeoSephiroth** [comment]
having the same error right now

**Comment by garry-1990** [comment]
I don't know, can not check this error now. If I get this error I will write you.
