### ISSUE TITLE
OrderNotFound Error - Trying to fetch an order

### ISSUE THREAD

**Issue by JanssensKobe** [ccxt/ccxt#8509]
I'm trying to fetch an order from binance futures but I get an OrderNotFound Error. When I download the order history I see that the order is actually in there (last row). The order has been cancelled but this shouldn't be a problem right? 

Code:
```python
import ccxt

binance = getattr(ccxt, 'binance')({'apiKey': 'xxx', 'secret': 'xxx', 'enableRateLimit': True})

binance.options['defaultType'] = 'future'

openOrder = binance.fetchOrder(11405693328, 'LINK/USDT')

print(openOrder)
```

Error:
```
Traceback (most recent call last):
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 592, in fetch
    response.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order?timestamp=1614122831059&recvWindow=5000&symbol=LINKUSDT&orderId=11405693328&signature=fbcae97625e970950631ee8c217a4904fb0d407fab4e7422a531e78a73cbe88e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/kobej/B204D33B04D300F1/Work/trabro2/test/fetchOrder.py", line 9, in <module>
    openOrder = binance.fetchOrder(11405693328, 'LINK/USDT')
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1901, in fetch_order
    response = getattr(self, method)(self.extend(request, query))
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2702, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2696, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}
```

Order History:
![image](https://user-images.githubusercontent.com/42657049/108923606-6b479980-7639-11eb-9940-1ee4cca412d1.png)

**Comment by JanssensKobe** [comment]
This issue is related to https://github.com/ccxt/ccxt/issues/8507 I assume?

**Comment by kroitor** [comment]
@JanssensKobe yes, this is all related, I'd suggest to move this discussion to issue 8507 if you don't mind.

**Comment by JanssensKobe** [comment]
No problem
