### ISSUE TITLE
400 Client Error: Bad Request for url when creating a Binance Future Order

### ISSUE THREAD

**Issue by kadnan** [ccxt/ccxt#8517]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: MacOS Catalina
- Programming Language version: Python 3.7
- CCXT version: 1.42.25

I am trying to use Binance Futures API and creating an order. Below are the details

```
import ccxt
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id) exchange = ccxt.binance({
        'apiKey': API_KEY_FUTURE,
        'secret': SECRET_FUTURE,
        'enableRateLimit': True,
    })
params = {
        'test': True,  # test if it's valid, but don't actually place it
    }

    symbol = 'BTC/USDT'
    type = 'limit'  # or 'market'
    side = 'sell'  # or 'buy'
    amount = 1.0
    price = 0.060154  # or None

    exchange.options = {'defaultType': 'future', 'adjustForTimeDifference': True,'defaultTimeInForce':False}
    exchange.set_sandbox_mode(enabled=True)

    order = exchange.create_order(symbol, type, side, amount, price, params)

    print(order)
```

```
Traceback (most recent call last):
  File "/Users/Me/Data/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py", line 592, in fetch
    response.raise_for_status()
  File "/Users/Me/Data/anaconda3/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://testnet.binancefuture.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Me/Data/You/Missy/BillionX/python/trading/test_ccxt.py", line 44, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "/Users/Me/Data/anaconda3/lib/python3.7/site-packages/ccxt/binance.py", line 1875, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/Users/Me/Data/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/Me/Data/anaconda3/lib/python3.7/site-packages/ccxt/binance.py", line 2702, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/Me/Data/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/Me/Data/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/Me/Data/anaconda3/lib/python3.7/site-packages/ccxt/binance.py", line 2696, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/Users/Me/Data/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1115,"msg":"Invalid timeInForce."}
```

**Comment by kroitor** [comment]
@kadnan timeInForce is required for limit orders, you should remove the `'defaultTimeInForce': False` override.
Let us know if that does not help.

**Comment by kadnan** [comment]
Resolved. Actually, the issue seems of the price which I did not notice. I had set `price = 0.060154 `. I set it around 48K and it worked first time. When I ran the code again and now I get the error:

```
ccxt.base.errors.ExchangeNotAvailable: binance {"code":-1016,"msg":"This service is no longer available."}
```
