### ISSUE TITLE
_ssl.c:1091

### ISSUE THREAD

**Issue by mitchell-dream** [ccxt/ccxt#8529]
Hello,

Before I introduce my problem, I would like to make a short preview about how the problem happened. Recently I have come to China. I know there is a firewall in this country, so I bought a VPN to help me deal with the banning problem. After I applied the method of using proxy IP, it raised the error as below. I have checked out many issues, but I found the error responses are different. And I cannot solve the problem. Please lead me to solve the problem. Thanks~
 - OS: windows 10
 - Programming Language version: python 3.7
 - CCXT version: 1.33.16
 - VPN: Pandas

```
proxy_msg = {
    'proxies': {
        'http': 'http://127.0.0.1:41091',
        'https': 'https://127.0.0.1:41091',
    },
}
exchange = ccxt.binance(proxy_msg)
market = exchange.load_markets()
print(markets)```

```
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.8/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.8/site-packages/urllib3/connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "/Library/Python/3.8/site-packages/urllib3/connection.py", line 496, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "/Library/Python/3.8/site-packages/urllib3/util/ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/Library/Python/3.8/site-packages/urllib3/util/ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1091: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Library/Python/3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Library/Python/3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1091: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/ccxt/base/exchange.py", line 566, in fetch
    response = self.session.request(
  File "/Library/Python/3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.8/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1091: The handshake operation timed out')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xx/Desktop/cn/DIGICCY/Code/MitProgram/MitGetBinanceSpotHistoryData.py", line 187, in <module>
    getDataForHistory(begin=begin_date,end=end_date, path=path);
  File "/Users/xx/Desktop/cn/DIGICCY/Code/MitProgram/MitGetBinanceSpotHistoryData.py", line 174, in getDataForHistory
    getDataForEveryDay(start=day, path=path)
  File "/Users/xx/Desktop/cn/DIGICCY/Code/MitProgram/MitGetBinanceSpotHistoryData.py", line 141, in getDataForEveryDay
    market = exchange.load_markets()
  File "/Library/Python/3.8/site-packages/ccxt/base/exchange.py", line 1358, in load_markets
    markets = self.fetch_markets(params)
  File "/Library/Python/3.8/site-packages/ccxt/binance.py", line 755, in fetch_markets
    response = getattr(self, method)(query)
  File "/Library/Python/3.8/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/Library/Python/3.8/site-packages/ccxt/binance.py", line 2703, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Library/Python/3.8/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Python/3.8/site-packages/ccxt/base/exchange.py", line 618, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo```

**Comment by kroitor** [comment]
Hi! I think your issue is cause by using wrong proxy addresses:

```
        'http': 'http://127.0.0.1:41091',
        'https': 'https://127.0.0.1:41091',
```

those are the addresses of your machine (127.0.0.1 = localhost), instead it should be the address of the proxy VPN (they should have it somewhere in their docs), like so:

```
        'http': 'http://address_of_vpn_here:41091',
        'https': 'https://address_of_vpn_here:41091',
```

Also, most often http and https proxies use different port numbers (should also be documented on the website of your VPN).

Let us know if that does not help.

**Comment by kroitor** [comment]
In general, when using VPN you don't have to set up any proxies at all. You should only use proxies if you bought a proxy (not a VPN). If you bought a VPN, then your code will work like so after connecting your system to the VPN:

```
exchange = ccxt.binance({'enableRateLimit':True})
market = exchange.load_markets()
print(markets)
```

How to connect to your VPN – should be documented on the website you bought it from.

Feel free to reopen this issue or just ask further questions if any.
