### ISSUE TITLE
Unable to use all my funds on FTX futures

### ISSUE THREAD

**Issue by Gladi-iwnl** [ccxt/ccxt#8534]
I'm unable to place a leveraged trade on FTX. I'm trying to change the leverage and then open a limit order. When I try this I get an InsufficientFunds Error. But when I try to open the same amount at the same price on FTX itself it goes through. Maybe my max leverage didn't change?

Code:
```python
import ccxt
import pandas as pd

connection = ccxt.ftx({'apiKey': 'xxx', 'secret': 'xxx', 'enableRateLimit': True, 'options' : {'defaultType': 'future'}})

market = 'AAVE/USD'
baseCurrency = 'USD'
reduceAmount = 0.295 # Only use 70.5% of capital
leverage = 3
limitPrice = 300

balance = connection.fetch_balance()['total'][baseCurrency]

connection.private_post_account_leverage({'leverage': leverage})
amount = float(connection.amount_to_precision(market, balance * (1 - reduceAmount) * leverage / limitPrice))

print(amount)

limitOrder = connection.create_order(market, 'limit', 'buy', amount, limitPrice, {'PostOnly': True})
```

Traceback:
```
0.14
Traceback (most recent call last):
  File "C:\Users\Gladi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch        
    response.raise_for_status()
  File "C:\Users\Gladi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: https://ftx.com/api/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\trabro2\test\fetchBalance.py", line 19, in <module>
    limitOrder = connection.create_order(market, 'limit', 'buy', amount, limitPrice, {'PostOnly': True})
  File "C:\Users\Gladi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\ftx.py", line 1084, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\Gladi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Gladi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 491, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Gladi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Gladi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Gladi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\ftx.py", line 1741, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Users\Gladi\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: ftx {"error":"Not enough balances","success":false}
```

**Comment by JanssensKobe** [comment]
I'm also having this issue.

**Comment by kroitor** [comment]
@JanssensKobe @Gladi-iwnl paste your verbose output:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)

exchange = ccxt.ftx({
    'apiKey': 'xxx',
    'secret': 'xxx',
    'enableRateLimit': True
})

markets = exchange.load_markets()

exchange.verbose = True

balance = exchange.fetch_total_balance()

print('----------------------------------------------------------------')
pprint(balance)
print('----------------------------------------------------------------')

connection.private_post_account_leverage({'leverage': leverage})

print('----------------------------------------------------------------')

amount = float(connection.amount_to_precision(market, balance * (1 - reduceAmount) * leverage / limitPrice))
print(amount)

print('----------------------------------------------------------------')

limitOrder = connection.create_order(market, 'limit', 'buy', amount, limitPrice, {'postOnly': True})
```

@Gladi-iwnl `PostOnly` with capital P is not a valid flag for FTX. The proper flag is `postOnly`.

**Comment by JanssensKobe** [comment]
Verbose output:
```
CCXT Version: 1.42.47

Request: GET https://ftx.com/api/wallet/balances {'FTX-KEY': 'N6jInGgoxbOrsLBPUcYQSycWnFZWju4ymckmQVn5', 'FTX-TS': '1614634258638', 'FTX-SIGN': 'f1fb79057e794623661bec490e02a0909776a4d11d8b61b61ea17583e08ff897', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://ftx.com/api/wallet/balances 200 {'Date': 'Mon, 01 Mar 2021 21:30:59 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d0e54d83ddddb2abc55eed145ce9ac3a31614634259; expires=Wed, 31-Mar-21 21:30:59 GMT; path=/; domain=.ftx.com; HttpOnly; SameSite=Lax; Secure', 'Vary': 'Accept-Encoding, 
Origin', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': '14595372', 'ETag': 'W/"b9e3c9e9bb154ed24af1adfeeb782798"', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'MISS', 'cf-request-id': '08914caa6b0000f969ff170000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '62957d570e09f969-BRU', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400'} {"result":[{"availableWithoutBorrow":20.00868537,"coin":"USD","free":20.00868537,"spotBorrow":0.0,"total":20.00868537,"usdValue":20.00868537},{"availableWithoutBorrow":0.0,"coin":"USDT","free":0.0,"spotBorrow":0.0,"total":0.0,"usdValue":0.0}],"success":true}
----------------------------------------------------------------
{'USD': 20.00868537, 'USDT': 0.0}
----------------------------------------------------------------

Request: POST https://ftx.com/api/account/leverage {'Content-Type': 'application/json', 'FTX-KEY': 'N6jInGgoxbOrsLBPUcYQSycWnFZWju4ymckmQVn5', 'FTX-TS': '1614634259045', 'FTX-SIGN': '09b2b40bfa01d0d5f7630245dcadd7ed733a868e66946c1b3f1a7d2c37f738e8', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} {"leverage":3}

Response: POST https://ftx.com/api/account/leverage 200 {'Date': 'Mon, 01 Mar 2021 21:30:59 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d0e54d83ddddb2abc55eed145ce9ac3a31614634259; expires=Wed, 31-Mar-21 21:30:59 GMT; path=/; domain=.ftx.com; HttpOnly; SameSite=Lax; Secure', 'Vary': 'Accept-Encoding, Origin', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': '14595372', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '08914cabfe0000f9690f97e000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '62957d599a5ff969-BRU', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400'} {"result":null,"success":true}
----------------------------------------------------------------
0.14
----------------------------------------------------------------

Request: POST https://ftx.com/api/orders {'Content-Type': 'application/json', 'FTX-KEY': 'N6jInGgoxbOrsLBPUcYQSycWnFZWju4ymckmQVn5', 'FTX-TS': '1614634259439', 'FTX-SIGN': '8413e7ffec9cb7d53e384cfaca2404a62c2654787eff6579582b42c684256cbc', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} {"market":"AAVE/USD","side":"buy","type":"limit","size":0.14,"price":300.0,"postOnly":true}

Response: POST https://ftx.com/api/orders 400 {'Date': 'Mon, 01 Mar 2021 21:31:00 GMT', 'Content-Type': 'application/json', 'Content-Length': '48', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d0e54d83ddddb2abc55eed145ce9ac3a31614634259; expires=Wed, 31-Mar-21 21:30:59 GMT; path=/; domain=.ftx.com; HttpOnly; SameSite=Lax; Secure', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': '14595372', 'Vary': 'Origin', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '08914cad880000f9694b0cc000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '62957d5c0f53f969-BRU', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400'} {"error":"Not enough balances","success":false}
Traceback (most recent call last):
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    response.raise_for_status()
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: https://ftx.com/api/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\trabro2\test\testPostOnly.py", line 38, in <module>
    limitOrder = connection.create_order(market, 'limit', 'buy', amount, limitPrice, {'postOnly': True})
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\ftx.py", line 1084, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 491, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\ftx.py", line 1741, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: ftx {"error":"Not enough balances","success":false}
```

**Comment by JanssensKobe** [comment]
In the web interface I'm able to place this order with the same leverage, amount and at the same price.
![image](https://user-images.githubusercontent.com/42657049/109563372-f6b0a700-7adf-11eb-8499-0ac72b1e90c9.png)

**Comment by kroitor** [comment]
@JanssensKobe the code I posted above is for AAVE/USD, which is a spot market. I don't think you can trade spot markets with leverage on FTX. However, on your screen you're showing AAVE-PERP, which is a different market (a perpetual contract). If you replace AAVE/USD with AAVE/PERP in the code above  (as on your screenshot) – do you have the same issue?

**Comment by JanssensKobe** [comment]
Yeah thanks, it works for me. I tried `AAVE/PERP` before which give me a KeyError, but `AAVE-PERP` works. It was pretty confusing because most markets in ccxt uses a slash instead of a dash.

**Comment by kroitor** [comment]
@Gladi-iwnl as far as I see, the above should also answer your question as well.

Closing this for now. Feel free to reopen it or just ask further questions if any.
