### ISSUE TITLE
Binance Quarterly Futures BTCUSD incorrectly sent to exchange

### ISSUE THREAD

**Issue by CryptoGnome** [ccxt/ccxt#8538]
CCXT version: 1.42.49
- Windows
- Python

This is a new issue for me that I am just getting to now since Quarterly Contracts were added to Binance Futures, I Have read the other posts and they don't seem to solve my issue.
#8387 
#8398 

Sending this:
```
binance.create_market_buy_order('BTC/USDT', self.order_size, params)
```
Getting this:
```
{'info': {'orderId': 76977833, 'symbol': 'BTCUSDT_210326', 'status': 'NEW', 'clientOrderId': 'x-40PTWbMIFVQ84TL', 'price': '0', 'avgPrice': '0.0000', 'origQty': '0.004', 'executedQty': '0', 'cumQty': '0', 'cumQuote': '0', 'timeInForce': 'GTC', 'type': 'MARKET', 'reduceOnly': False, 'closePosition': False, 'side': 'BUY', 'positionSide': 'BOTH', 'stopPrice': '0', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType': 'MARKET', 'updateTime': 1614719854940}, 'id': '76977833', 'clientOrderId': 'x-40PTWbMIFVQ84TL', 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'symbol': 'BTC/USDT', 'type': 'market', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': 0.0, 'stopPrice': 0.0, 'amount': 0.004, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 0.004, 'status': 'open', 'fee': None, 'trades': None}
```
Opens the incorrect Contract shown Here:
https://ibb.co/0sq4Y7N

for reference this is how I have always loaded binance futures in this script
```
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
binance = exchange_class({
    'apiKey': settings['key'],
    'secret': settings['secret'],
    'timeout': 30000,
    'enableRateLimit': True,
    'option': {'defaultMarket': 'futures'},
    'urls': {
        'api': {
            'public': 'https://fapi.binance.com/fapi/v1',
            'private': 'https://fapi.binance.com/fapi/v1',
        }, }
})
```

Also Thanks in advance @kroitor you are a beast

**Comment by kroitor** [comment]
@CryptoGnome please, upgrade to the most recent version, this issue has been fixed before:

- https://github.com/ccxt/ccxt/issues/8404

**Comment by CryptoGnome** [comment]
Updated Again still the same issue.

```
{'info': {'orderId': 79729640, 'symbol': 'BTCUSDT_210326', 'status': 'NEW', 'clientOrderId': 'x-40PTWbMIXF5Z3HR', 'price': '0', 'avgPrice': '0.0000', 'origQty': '0.011', 'executedQty': '0', 'cumQty': '0', 'cumQuote': '0', 'timeInForce': 'GTC', 'type': 'MARKET', 'reduceOnly': False, 'closePosition': False, 'side': 'SELL', 'positionSide': 'BOTH', 'stopPrice': '0', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType': 'MARKET', 'updateTime': 1614778002303}, 'id': '79729640', 'clientOrderId': 'x-40PTWbMIXF5Z3HR', 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'symbol': 'BTC/USDT', 'type': 'market', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'sell', 'price': 0.0, 'stopPrice': 0.0, 'amount': 0.011, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 0.011, 'status': 'open', 'fee': None, 'trades': None}```

**Comment by kroitor** [comment]
@CryptoGnome paste your runtime version number (do not trust `pip`):

```Python
import ccxt
pinrt(ccxt.__version__)
```

**Comment by kroitor** [comment]
@CryptoGnome please, paste your complete verbose output using this snippet (make sure there's no other code to rule out any interference):

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
    'option': {'defaultTypet': 'future'},
})

markets = exchange.load_markets()

exchange.verbose = True

symbol = 'BTC/USDT'
order = exchange.create_market_buy_order('BTC/USDT', '0.001')
pprint(order)
```

**Comment by kroitor** [comment]
@CryptoGnome pardon, fixed a few typos above.

**Comment by CryptoGnome** [comment]
```
CCXT Version: 1.42.51

Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': 'i2HYQIXfRfpCsqeArk1Bz9utICyOL56QW3DqgixFsR6ABdl5KdU9Q1GC6HuL5X1p', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1614779148578&recvWindow=5000&symbol=BTCUSDT&type=MARKET&side=BUY&newClientOrderId=x-R4BD3S82cadb18c9d91b4b92b88724&newOrderRespType=FULL&quantity=0.001&signature=10c057a7e72f687d4931aabc34ad84223a0200af98301cfc24f4fe7e22e4ed09

Response: POST https://api.binance.com/api/v3/order 400 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '77', 'Connection': 'keep-alive', 'Date': 'Wed, 03 Mar 2021 13:45:48 GMT', 'Server': 'nginx', 'x-mbx-uuid': '72177691-412c-4ad8-9aa7-e4dc13c6d262', 'x-mbx-used-weight': '2', 'x-mbx-used-weight-1m': '2', 'x-mbx-order-count-10s': '1', 'x-mbx-order-count-1d': '5', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 a43adfa647c3142c7ee45d9cf52469fd.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ATL56-C1', 'X-Amz-Cf-Id': '_9xNwt-PqaB8giYaZMox0aAgA-TPK7weELXq7eyNBS5V4RH43rLFzw=='} {"code":-2010,"msg":"Account has insufficient balance for requested action."}
Traceback (most recent call last):
  File "C:\Users\oimap\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    response.raise_for_status()
  File "C:\Users\oimap\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/oimap/Desktop/LickHunterPro2/test.py", line 18, in <module>
    order = exchange.create_market_buy_order('BTC/USDT', 0.001)
  File "C:\Users\oimap\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 1877, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "C:\Users\oimap\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\binance.py", line 1876, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\oimap\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\oimap\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\binance.py", line 2703, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\oimap\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\oimap\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\oimap\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\binance.py", line 2683, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "C:\Users\oimap\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.```

**Comment by CryptoGnome** [comment]
![image](https://user-images.githubusercontent.com/33667144/109814929-0c67be80-7bfd-11eb-8343-87ab3531f89f.png)

**Comment by kroitor** [comment]
@CryptoGnome pardon, more typos above, this will work, let me know if not:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
    'options': {'defaultType': 'future'},
})

markets = exchange.load_markets()

exchange.verbose = True

symbol = 'BTC/USDT'
order = exchange.create_market_buy_order('BTC/USDT', 0.001)
pprint(order)
```

**Comment by CryptoGnome** [comment]
```
CCXT Version: 1.42.51

Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'i2HYQIXfRfpCsqeArk1Bz9utICyOL56QW3DqgixFsR6ABdl5KdU9Q1GC6HuL5X1p', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1614779476332&recvWindow=5000&symbol=BTCUSDT&type=MARKET&side=BUY&newClientOrderId=x-xcKtGhcue00ff5fa54f72b754e08bb&quantity=0.001&signature=7029d543fb73011625da8405f9e754002074fa623c2d4fce96f251be6187d20f

Response: POST https://fapi.binance.com/fapi/v1/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Wed, 03 Mar 2021 13:51:16 GMT', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '1', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '4ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 5c42606592ccd5dbe3b02deff8a08eda.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ATL56-C1', 'X-Amz-Cf-Id': 'QuIN6vG8uuNlQPUePlwDxshjaf-B4T8hthtz_TQPr0ed-rFYkExN_Q=='} {"orderId":15353038647,"symbol":"BTCUSDT","status":"NEW","clientOrderId":"x-xcKtGhcue00ff5fa54f72b754e08bb","price":"0","avgPrice":"0.00000","origQty":"0.001","executedQty":"0","cumQty":"0","cumQuote":"0","timeInForce":"GTC","type":"MARKET","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"MARKET","updateTime":1614779476329}
{'amount': 0.001,
 'average': None,
 'clientOrderId': 'x-xcKtGhcue00ff5fa54f72b754e08bb',
 'cost': 0.0,
 'datetime': None,
 'fee': None,
 'filled': 0.0,
 'id': '15353038647',
 'info': {'avgPrice': '0.00000',
          'clientOrderId': 'x-xcKtGhcue00ff5fa54f72b754e08bb',
          'closePosition': False,
          'cumQty': '0',
          'cumQuote': '0',
          'executedQty': '0',
          'orderId': 15353038647,
          'origQty': '0.001',
          'origType': 'MARKET',
          'positionSide': 'BOTH',
          'price': '0',
          'priceProtect': False,
          'reduceOnly': False,
          'side': 'BUY',
          'status': 'NEW',
          'stopPrice': '0',
          'symbol': 'BTCUSDT',
          'timeInForce': 'GTC',
          'type': 'MARKET',
          'updateTime': 1614779476329,
          'workingType': 'CONTRACT_PRICE'},
 'lastTradeTimestamp': None,
 'postOnly': False,
 'price': 0.0,
 'remaining': 0.001,
 'side': 'buy',
 'status': 'open',
 'stopPrice': 0.0,
 'symbol': 'BTC/USDT',
 'timeInForce': 'GTC',
 'timestamp': None,
 'trades': None,
 'type': 'market'}

**Comment by CryptoGnome** [comment]
My Hero, it was because i was using the old API it seems:

```
    'urls': {
        'api': {
            'public': 'https://fapi.binance.com/fapi/v1',
            'private': 'https://fapi.binance.com/fapi/v1',
        }, }

**Comment by kroitor** [comment]
@CryptoGnome thx for the feedback!
