### ISSUE TITLE
Cancel conditional order on FTX

### ISSUE THREAD

**Issue by JanssensKobe** [ccxt/ccxt#8547]
I'm trying to cancel a conditional order on FTX.

Method 1:
```python
connection.private_delete_conditional_orders_order_id({'id': slOrder['id'], 'market': 'AAVE-PERP'})
```

Traceback:
```
Traceback (most recent call last):
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    response.raise_for_status()
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://ftx.com/api/conditional_orders/%7Border_id%7D?id=26047373&market=AAVE-PERP

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\kobej\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\kobej\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\kobej\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\trabro2\test\testFtxCancelSl.py", line 13, in <module>
    connection.private_delete_conditional_orders_order_id({'id': slOrder['id'], 'market': 'AAVE-PERP'})
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 491, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\ftx.py", line 1742, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 510, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.BadRequest: ftx {"error":"404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.","success":false}
```

Based on issue https://github.com/ccxt/ccxt/issues/8498 I've also tried another method but nothing worked for me. 
Code:
```python
connection.cancel_order(slOrder['id'], 'AAVE-PERP', {'conditionalOrdersOnly': True})
```

But then I got an `OrderNotFound` error:
```
Traceback (most recent call last):
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    response.raise_for_status()
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://ftx.com/api/orders/26048320?conditionalOrdersOnly=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\kobej\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\kobej\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\kobej\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\trabro2\test\testFtxCancelSl.py", line 13, in <module>
    connection.cancel_order(slOrder['id'], 'AAVE-PERP', {'conditionalOrdersOnly': True})
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\ftx.py", line 1248, in cancel_order
    response = getattr(self, method)(self.extend(request, query))
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 491, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\ftx.py", line 1742, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.OrderNotFound: ftx {"error":"Order not found","success":false}
```

**Comment by kroitor** [comment]
@JanssensKobe `conditionalOrdersOnly` is for `cancelAllOrders` only.

Use the exchange options to control the behavior of cancelOrder: 

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/ftx.py#L264

```Python
connection.options['cancelOrder']['method'] = 'privateDeleteConditionalOrdersOrderId';
connection.cancel_order(slOrder['id'], 'AAVE-PERP')
```

Let us know if the above does not answer your question. We will also add the support for params overrides with cancelOrder and other methods.
