### ISSUE TITLE
Error: kraken HTML page markup has changed

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#8565]
- OS: CentOS
- Programming Language version: JavaScript (in Web browser via ccxt-browser.js)
- CCXT version: latest ccxt-browser.js

I finally have my proxy server running and am able to use the code below (only with binance as the exchange) to pull close data. With kraken it's throwing an error. Which is confusing as I'm obviously checking if 'fetchTicker' is supported.

```
<script type="text/javascript">
const kraken = new ccxt.kraken({'enableRateLimit': true})
kraken.proxy = 'https://xxxxxxxxxx.com:8080/'

if (kraken.has['fetchTicker']) {
    kraken.fetchTicker ('BTC/USD')
    .then(function(data) {
      var btc = data.last;
      console.log(btc);
      console.log(data);
      return btc;
    })
}
</script>
```
ERROR (in JS console):

ccxt.browser.js:4893 Uncaught (in promise) NotSupported: kraken fetchMinOrderAmounts HTML page markup has changed: https://kraken.zendesk.com/api/v2/help_center/en-us/articles/205893708
    at kraken.fetchMinOrderAmounts (https://cdn.jsdelivr.net/npm/ccxt@1.29.75/dist/ccxt.browser.js:72651:19)
    at async kraken.fetchMarkets (https://cdn.jsdelivr.net/npm/ccxt@1.29.75/dist/ccxt.browser.js:72723:22)
    at async kraken.loadMarketsHelper (https://cdn.jsdelivr.net/npm/ccxt@1.29.75/dist/ccxt.browser.js:4032:25)
    at async kraken.fetchTicker (https://cdn.jsdelivr.net/npm/ccxt@1.29.75/dist/ccxt.browser.js:73011:9)

**Comment by mmehrle** [comment]
@kroitor I'm using the browser library mentioned in the tutorial:

https://cdn.jsdelivr.net/npm/ccxt@1.29.75/dist/ccxt.browser.js

Where can I find the latest version? Because I don't see it in Github. I just see a version that is used to compile it. Thanks in advance.

**Comment by mmehrle** [comment]
Perfect - thanks. It's working now and the Kraken fetchTicker() request succeeds.

**Comment by kroitor** [comment]
@mmehrle alternatively, you can use this URL which always points to the most recent version: https://cdn.jsdelivr.net/npm/ccxt/dist/ccxt.browser.js (you won't have to edit the version numbers manually this way, and it will stay up to date).

**Comment by mmehrle** [comment]
Awesome - even better. FYI - along with setting up my own corsproxy instance on my server and figuring all this out it feels like I just gave birth! But seeing it actually running inside my page as part of the dynamic Javascript is pure magic. Well done - I'll be having a lot of fun with this.
