### ISSUE TITLE
Binance fetching balance error -1021

### ISSUE THREAD

**Issue by Trikos** [ccxt/ccxt#8616]
- OS: Windows 10
- Programming Language version: Python 3.9.2
- CCXT version: 1.43.1

```
import ccxt
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': '',
    'secret': '',
    'timeout': 30000,
    'enableRateLimit': True,
})
print(exchange.fetch_balance())
```

```
Traceback (most recent call last):
  File "C:\Users\sk8te\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 592, in fetch
    response.raise_for_status()
  File "C:\Users\sk8te\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/account?timestamp=1615657459466&recvWindow=5000&signature=14505bd9d22f597afe5b68ca4e677eb3c314c30788dc13fba0d4f4e02a045910

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sk8te\Documenti\team\testCCXT.py", line 48, in <module>
    print(exchange.fetch_balance())
  File "C:\Users\sk8te\AppData\Roaming\Python\Python39\site-packages\ccxt\binance.py", line 1035, in fetch_balance
    response = getattr(self, method)(query)
  File "C:\Users\sk8te\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\sk8te\AppData\Roaming\Python\Python39\site-packages\ccxt\binance.py", line 2747, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\sk8te\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\sk8te\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\sk8te\AppData\Roaming\Python\Python39\site-packages\ccxt\binance.py", line 2741, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "C:\Users\sk8te\AppData\Roaming\Python\Python39\site-packages\ccxt\base\exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
```

**Comment by frosty00** [comment]
Hi @Trikos, you need to make sure that your computer time is synced.

Alternatively you can do this:

```
binance.options['adjustForTimeDifference'] = true
```

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/search?q=Timestamp+for+this+request+was+1000ms&type=issues
