### ISSUE TITLE
fetch_ticker failed with Quadrigacx, access denied by cloudflare

### ISSUE THREAD

**Issue by HanYangZhao** [ccxt/ccxt#869]
ccxt.base.errors.DDoSProtection: quadrigacx GET https://api.quadrigacx.com/v2/ticker?book=btc_cad 403 Forbidden 
The owner of this website (api.quadrigacx.com) has banned your access based on your browser's signature 
- OS: Debian
- Language: Python 
- CCXT version: 1.10.394
- Exchange: quadrigacx
- Method: fetch_ticker

```
 print quad.fetch_ticker('BTC/CAD')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ccxt/quadrigacx.py", line 94, in fetch_ticker
    }, params))
  File "/usr/local/lib/python2.7/dist-packages/ccxt/quadrigacx.py", line 201, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 282, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 340, in fetch
    self.handle_rest_errors(e, e.code, message if message else text, url, method)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 368, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 264, in raise_error
    details,
ccxt.base.errors.DDoSProtection: quadrigacx GET https://api.quadrigacx.com/v2/ticker?book=btc_cad 403 Forbidden  <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | api.quadrigacx.com used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1010</span>
          <small class="heading-ray-id">Ray ID: 3ce637f0da520fab &bull; 2017-12-17 01:48:09 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">Access denied</h2>
      </div><!-- /.header -->

      <section></section><!-- spacer -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>The owner of this website (api.quadrigacx.com) has banned your access based on your browser's signature (3ce637f0da520fab-ua48).</p>
          </div>


        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>3ce637f0da520fab</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: REMOVED</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};


</script>

</body>
</html>
```

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/868
