### ISSUE TITLE
Bittrex - Websocket watchOrders fault

### ISSUE THREAD

**Issue by mpainenz** [ccxt/ccxt#8698]
- OS: Windows 10
- Programming Language version: Python 3.7
- CCXT version: Latest Master Branches

Hi kroitor,

When I use the watchOrder method on Bittrex, I get an error with the following code.

```
    async def generate_watch_orders_loop(self, symbol):
        while True:
            try:
                orders = await self.ccxt_exchange.watch_orders(symbol)
                #self._order_book_cache[symbol] = order_book
                print(orders)

            except Exception as e:
                print(e)

```

The error is:
```
Exception in callback FastClient.receive_loop.<locals>.handler() at C:\Solus\Projects\Eleanor\ccxtpro\python\ccxtpro\base\fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at C:\Solus\Projects\Eleanor\ccxtpro\python\ccxtpro\base\fast_client.py:20>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Solus\Projects\Eleanor\ccxtpro\python\ccxtpro\base\fast_client.py", line 25, in handler
    self.handle_message(message)
  File "C:\Solus\Projects\Eleanor\ccxtpro\python\ccxtpro\base\aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "C:\Solus\Projects\Eleanor\ccxtpro\python\ccxtpro\base\aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "C:\Solus\Projects\Eleanor\ccxtpro\python\ccxtpro\bittrex.py", line 719, in handle_message
    self.handle_subscription_status(client, message)
  File "C:\Solus\Projects\Eleanor\ccxtpro\python\ccxtpro\bittrex.py", line 633, in handle_subscription_status
    subscriptionsById = self.index_by(client.subscriptions, 'id')
  File "C:\Solus\Projects\Eleanor\ccxt\python\ccxt\base\exchange.py", line 873, in index_by
    if ((is_int_key and (key < len(element))) or (key in element)) and (element[key] is not None):
RuntimeError: await wasn't used with future
```

When I debug, the following places stick out:

```
  File "C:\Solus\Projects\Eleanor\ccxtpro\python\ccxtpro\bittrex.py", line 633, in handle_subscription_status
    subscriptionsById = self.index_by(client.subscriptions, 'id')
  File "C:\Solus\Projects\Eleanor\ccxt\python\ccxt\base\exchange.py", line 873, in index_by
    if ((is_int_key and (key < len(element))) or (key in element)) and (element[key] is not None):
```

Looking at the exchange.py file, if I modify the following function:

```
    @staticmethod
    def index_by(array, key):
        result = {}
        if type(array) is dict:
            array = Exchange.keysort(array).values()
        is_int_key = isinstance(key, int)

        for element in array:
              if ((is_int_key and (key < len(element))) or (key in element)) and (element[key] is not None):
                  k = element[key]
                  result[k] = element
        return result
```

Andd add the following check

```
if (not asyncio.isfuture(element)):
```

It fixes the issue. It appears that the client.subscriptions object contains an element that is a future, and the sort function doesn't handle that situation.  I hope this makes sense.

**Comment by frosty00** [comment]
I cannot replicate the error
