### ISSUE TITLE
Poloniex nonce error

### ISSUE THREAD

**Issue by mcandar** [ccxt/ccxt#8767]
Hi,

I use the following versions:
* ccxt: 1.45.67
* python: 3.6.9
* ubuntu: 18.04

I am trying to fetch balances with the following code block:

```
import ccxt

venue_poloniex = ccxt.poloniex(
    {
    "apiKey": poloniex_api_key,
    "secret": poloniex_api_secret
    }
)
venue_poloniex.enableRateLimit = True
balance_poloniex = venue_poloniex.fetch_balance()
```

And I encounter the following error:

```
Traceback (most recent call last):
  File "/home/candar/Studies/crypto_data/alt/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 602, in fetch
    response.raise_for_status()
  File "/home/candar/Studies/crypto_data/alt/venv/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error:  for url: https://poloniex.com/tradingApi

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "two_way.py", line 71, in <module>
    balance_poloniex = venue_poloniex.fetch_balance()
  File "/home/candar/Studies/crypto_data/alt/venv/lib/python3.6/site-packages/ccxt/poloniex.py", line 336, in fetch_balance
    response = self.privatePostReturnCompleteBalances(self.extend(request, params))
  File "/home/candar/Studies/crypto_data/alt/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 470, in inner
    return entry(_self, **inner_kwargs)
  File "/home/candar/Studies/crypto_data/alt/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 495, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/candar/Studies/crypto_data/alt/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 491, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/candar/Studies/crypto_data/alt/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 618, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/candar/Studies/crypto_data/alt/venv/lib/python3.6/site-packages/ccxt/poloniex.py", line 1378, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], message, feedback)
  File "/home/candar/Studies/crypto_data/alt/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 514, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.InvalidNonce: poloniex {"error":"Nonce must be greater than 1617263586447000. You provided 1617263596284."}
```

I tried several times and figured out that there is a 10^3 difference between the timestamps shown in the error message. Seems like is compares microseconds with milliseconds. If they were both in the same unit, the condition would met and there should not be an error message like this.

What am I missing here?

**Comment by kroitor** [comment]
Hi

Looks like your API key was previously used by some other software. Sometimes that software screws the nonce number on your key too high, making it unusable with the other software. So, in order to solve this, create a new keypair. Let us know if that does not help.

**Comment by mcandar** [comment]
I tried several different key/secret pairs and they did not work. However, I just found the solution at [this](https://stackoverflow.com/questions/45964187/nonce-override-in-python-ccxt) stackoverflow answer.

Basically

```
class poloniex2(ccxt.poloniex):
    def nonce(self):
        return self.microseconds ()
```

and used `poloniex2` class to create the exchange object.

This way it worked!
