### ISSUE TITLE
Bybit returns Param validation for 'symbol' failed on the 'symbol' 

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#8868]
Hello,

I noticed a strange behavior from Bybit on several symbols: DOT/USDT, ADA/USDT, UNI/USDT.
```
b = ccxt.bybit()
since = b.parse8601('2020-03-03T01:02:03Z')
m = b.fetchOHLCV('DOT/USDT', '1h', since)

ExchangeError: bybit {"ret_code":10001,"ret_msg":"Param validation for 'symbol' failed on the 'symbol' tag","ext_code":"","ext_info":"","result":null,"time_now":"1617831187.859557"}
```

It works for other symbols.

Best,
Kinzowa

**Comment by AurelReb** [comment]
Hi, any news about this issue?

**Comment by AlgoQ** [comment]
@kroitor I'm getting the same error for AAVE/USDT, however the pair is included when I fetch the markets. But I don't get the error anymore for DOT/USDT. 

Fetching markets:
```python
for i in exchange.fetch_markets():
    print(i['symbol'])
```

```
BTC/USD
ETH/USD
EOS/USD
XRP/USD
BTC/USDT
BCH/USDT
ETH/USDT
LTC/USDT
LINK/USDT
XTZ/USDT
ADA/USDT
DOT/USDT
UNI/USDT
XRP/USDT
XEM/USDT
SUSHI/USDT
AAVE/USDT
BTCUSDU21
BTCUSDM21
ETHUSDU21
ETHUSDM21
```

Error traceback:
```
Traceback (most recent call last):
  File "/run/media/kobej/D/feda/main.py", line 5, in <module>
    ohlcv = datamanager.fetchDatafeed() # Fetch klines and output them into given file
  File "/run/media/kobej/D/feda/feda.py", line 76, in fetchDatafeed
    fullOhlcv = self.exchange.fetch_ohlcv(symbol=self.pair, limit=self.limit, timeframe='1m', since=startSince)
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/bybit.py", line 713, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 486, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 634, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/bybit.py", line 2190, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/home/kobej/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: bybit {"ret_code":10001,"ret_msg":"Param validation for 'symbol' failed on the 'symbol' tag","ext_code":"","ext_info":"","result":null,"time_now":"1622561676.820050"}
```

**Comment by kroitor** [comment]
Will get this resolved asap, thx for reporting!

**Comment by justiceorjustus** [comment]
I am also experiencing this issue when calling bybit.fetch_orders()

**Comment by Gabriele-Sabatino** [comment]
Hi, any news about this issue?

**Comment by devlucem** [comment]
This is not an error actually, You missed a key point in identifying your symbol. 
Before you fetch the API, you should load the markets first so that you can know the ID of the symbol to use. 
I noticed this is happening whenever I miss something on my symbol name. Here is how your code should look

```
b = ccxt.bybit()
since = b.parse8601('2020-03-03T01:02:03Z')
b.loadMarkets()
symbol = b.market('DOT/USDT').id
m = b.fetchOHLCV(symbol, '1h', since)
```

**Comment by 9808us** [comment]
@devlucem I'm not sure that is the error.
When I use BTC/USDT I do not have issue.
If I use BTC/USD then I have the issue.
So it's not about loading markets first, it has to do with something else
Can you try with inverse perpetual on bybit? Your example is for the default linear perpetual where ccxt works out of the box

**Comment by tfmertz** [comment]
Omg derp, I was on the wrong API docs tab. I was getting this error for the `XRPUSDT` symbol when `XRPUSD` was working perfectly because I wasn't calling the endpoints on the USDT Perpetual tab.
![api-tabs](https://user-images.githubusercontent.com/3745225/164349956-3ef1c418-f83e-4d3c-8b3c-bc6d05d3e3b2.jpg)

Not working call = `/v2/private/order/list`
Working calls = `/private/linear/order/list`

Hopefully this saves someone some time.

**Comment by ttodua** [comment]
Since the last post in this topi, ccxt has updated bybit. Please try the new version. 
beside it, note, that you will need to set `defaultType` to `spot` if you want spot market:
```
const bb = new ccxt.bybit();
bb.options['defaultType'] = 'spot';
const candles = await bb.fetchOHLCV ('UNI/USDT', '1h');
```
Let us know if you face any issues in CCXT.
