### ISSUE TITLE
python2.7 centos7 import ccxt error SyntaxError

### ISSUE THREAD

**Issue by yunweizhe11** [ccxt/ccxt#8893]
>>> import ccxt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/usr/lib/python2.7/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/usr/lib/python2.7/site-packages/ccxt/base/exchange.py", line 518
    def print(self, *args):
            ^
SyntaxError: invalid syntax

version: ccxt==1.45.98 1.28.65  1.28.65  1.47.8

**Comment by kroitor** [comment]
Python 2.7 is officially deprecated since January 2020. Please, upgrade to Python3.

- https://python3statement.org/
