### ISSUE TITLE
Coinbasepro watch_orders() fails with TypeError: 'Unicode-objects must be encoded before hashing'

### ISSUE THREAD

**Issue by nanaknihal** [ccxt/ccxt#8921]
I'm having this problem only with coinbasepro and only in watch_orders(). It works with ftx, and both watch_orderbook and watch_orders work with coinbasepro. My keys and passphrase are stored as strings, and they are being converted to bytes at some point before reaching hmac()

 
- OS: macOS Catalina
- Programming Language version: Python 3.8.6
- CCXT version :ccxt==1.45.74, ccxtpro==0.6.33
-

```
def listen(self, callback=(lambda x: None)):
        loop = asyncio.get_event_loop()
        loop.create_task(self.watch_orderbook(callback))
        loop.create_task(self.watch_orders(callback))
        loop.create_task(self.slowly_watch_balance())

```
I also modified the hmac method for some debugging output, which indicates the string and request are bytes
```
@staticmethod
    def hmac(request, secret, algorithm=hashlib.sha256, digest='hex'):
        print('SECRET IS ' + str(secret))
        print('REQUEST IS ' + str(request))
        print('ALGORITHM IS ' + str(algorithm))
        h = hmac.new(secret, request, algorithm)
        binary = h.digest()
        if digest == 'hex':
            return Exchange.binary_to_base16(binary)
        elif digest == 'base64':
            return Exchange.binary_to_base64(binary)
        return binary
```

```
SECRET IS b'\xd3\xe1!...omitted...x9a'
REQUEST IS b'16...omitted...86GET/accounts'
ALGORITHM IS <built-in function openssl_sha256>
```

The traceback for the error is:
```
Traceback (most recent call last):
  File "/Users/nnsk/Desktop/scrypto/addthistowrappers.py", line 130, in watch_orders
    self.orders = await self.client.watch_orders(symbol=self.symbol, limit=200)
  File "/usr/local/lib/python3.8/site-packages/ccxtpro/coinbasepro.py", line 101, in watch_orders
    authentication = self.authenticate()
  File "/usr/local/lib/python3.8/site-packages/ccxtpro/coinbasepro.py", line 46, in authenticate
    signature = self.hmac(payload, self.base64_to_binary(self.secret), hashlib.sha256, 'base64')
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1112, in hmac
    h = hmac.new(secret, request, algorithm)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/hmac.py", line 88, in __init__
    self.update(msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/hmac.py", line 96, in update
    self.inner.update(msg)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by frosty00** [comment]
you need to update to the latest version of ccxtpro, this error has already been fixed

**Comment by frosty00** [comment]
my current version is `0.6.47`

**Comment by kroitor** [comment]
@nanaknihal please, let us know if you have the same issue with the most recent version of CCXT + CCXT Pro. Feel free to reopen it or just ask further questions if any.

**Comment by nanaknihal** [comment]
Thanks, it worked after updating

**Comment by kroitor** [comment]
@nanaknihal thx for reporting back!
