### ISSUE TITLE
FTX spot_margin/offers - Missing parameter coin

### ISSUE THREAD

**Issue by DaddyAG** [ccxt/ccxt#8956]
- OS: Synology DSM
- Programming Language version: Node.js v12.20.1
- CCXT version: 1.47.61

```
const test1 = await exchange.private_post_spot_margin_offers ("USD", 5.0, 0.000001)
console.log (test1)
```

```
(node:30638) UnhandledPromiseRejectionWarning: ExchangeError: ftx {"success":false,"error":"Missing parameter coin"}

    at ftx.handleErrors (/_mypath_/node_modules/ccxt/js/ftx.js:1860:19)
    at /_mypath_/node_modules/ccxt/js/base/Exchange.js:600:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (/_mypath_/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async main (/_mypath_/test2.js:34:16)
(node:30638) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30638) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also tested with different 2nd (5 or 5.12345) and 3rd (1e-6) parameters.

Maybe I'm using exchange.private_post_spot_margin_offers incorrectly, but couldn't find any examples out there.

https://docs.ftx.com/#submit-lending-offer
Manual at FTX clearly defines those, I just copied them for testing in same order.

Please point me in right dirrection.

P.S. Verbose:
```
fetch:
 ftx POST https://ftx.com/api/spot_margin/offers
Request:
 {
  'Content-Type': 'application/json',
  'FTX-KEY': 'xxx',
  'FTX-TS': 'xxx',
  'FTX-SIGN': 'xxx'
}
 {"0":"U","1":"S","2":"D"}

handleRestResponse:
 ftx POST https://ftx.com/api/spot_margin/offers 400 BAD REQUEST
Response:
 {
  'Account-Id': 'xxx',
  'Alt-Svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400',
  'Cache-Control': 'private, max-age=0, no-cache',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '63f49f5c5f66d8b5-AMS',
  'Cf-Request-Id': '096cc1edbb0000d8b5cfa1d000000001',
  Connection: 'keep-alive',
  'Content-Length': '51',
  'Content-Type': 'application/json',
  Date: 'Tue, 13 Apr 2021 12:15:54 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=d9bdfd97513bad865f51782a06fb7908a1618316154; expires=Thu, 13-May-21 12:15:54 GMT; path=/; domain=.ftx.com; HttpOnly; SameSite=Lax; Secure',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  Vary: 'Origin',
  'X-Content-Type-Options': 'nosniff'
}
 {"success":false,"error":"Missing parameter coin"}
```

**Comment by DaddyAG** [comment]
Maybe I'm wrong, but comparing CCXT output to FTX spec, it seams like a bug.

Output:
{"0":"U","1":"S","2":"D"}

Spec:
{
  "coin": "USD",
  "size": 10.0,
  "rate": 1e-6
}

**Comment by kroitor** [comment]
@DaddyAG you should pass the params as a dictionary, as explained in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

```Python
await exchange.private_post_spot_margin_offers ({
    'param1': 'value2', 
    'param2': 'value2', 
    'param3': 'value3', 
})
```

Check the value of the supported params here: https://docs.ftx.com/#submit-lending-offer

I'd recommend reading the entire Manual from top to bottom, it will really save your time.

Let us know if that does not answer your question. Feel free to reopen this or just ask further questions if any.

**Comment by DaddyAG** [comment]
Thank you.
I was searching manual (CTRL+F) for key words around private exchage API, but didn't run into that.
