### ISSUE TITLE
{"code":-2014,"msg":"API-key format invalid."} HELP ME PLEASE

### ISSUE THREAD

**Issue by zonegh** [ccxt/ccxt#8973]
- OS: macOS Big Sur Version 11.2.3
- Programming Language version: Python 3.8.9
- CCXT version: 1.47.38

WHEN I TEST WITH MY API AND MY SECRET KEY, EVERYTHING OK
BUT WHEN  TRY TO create_limit_buy_order CANNOT
ERROR CODE {"code":-2014,"msg":"API-key format invalid."} 
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

I HAVE 99 USDT IN MY SPOT

I NEED TO MAKE AUTO REBALANCE BOT API BINANCE PAIR USDT WITH ANY
SET FIX 50%

**MY INPUT**

import ccxt
from pprint import pprint

# print(ccxt.exchanges)

api_key = ''
secret_key = ''
bi = ccxt.binance({'apiKey': api_key, 'secret': secret_key, 'enableRateLimit': True, })

price = bi.fetch_tickers('BNB/USDT')['BNB/USDT']['last']  # เรียกราคา
balance = bi.fetch_balance()  # เรียก balance ทั้งหทดในพอร์ต

USD = balance['USDT']['free']
BNB = balance['BNB']['free']

bnb_value = price*BNB

fix = 50
   
    # SELL
if bnb_value > fix:
    amount = bnb_value - fix
    bi.create_limit_sell_order('BNB/USDT', str(amount), str(price))
    print('Sell BNB')
 
   # BUY
elif bnb_value < fix:
    amount = fix - bnb_value
    bi.create_limit_buy_order('BNB/USDT', str(amount), str(price))
    print('Buy BNB')

else:
    print('Do nothing')
```

```
**MY OUTPUT_ERROR**

/Users/macbookpro/Desktop/AR/venv/bin/python "/Users/macbookpro/Desktop/AR/AR BINANCE.py"
Traceback (most recent call last):
  File "/Users/macbookpro/Desktop/AR/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 603, in fetch
    response.raise_for_status()
  File "/Users/macbookpro/Desktop/AR/venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbookpro/Desktop/AR/AR BINANCE.py", line 82, in <module>
    bi.create_limit_buy_order('BNB/USDT', str(amount), str(price))
  File "/Users/macbookpro/Desktop/AR/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1951, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', amount, price, params)
  File "/Users/macbookpro/Desktop/AR/venv/lib/python3.8/site-packages/ccxt/binance.py", line 1912, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/Users/macbookpro/Desktop/AR/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 471, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/macbookpro/Desktop/AR/venv/lib/python3.8/site-packages/ccxt/binance.py", line 2908, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/macbookpro/Desktop/AR/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 492, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/macbookpro/Desktop/AR/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 619, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/macbookpro/Desktop/AR/venv/lib/python3.8/site-packages/ccxt/binance.py", line 2888, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/Users/macbookpro/Desktop/AR/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 510, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

Process finished with exit code 1

**Comment by zonegh** [comment]
IM OUT

**Comment by Momnadar1** [comment]
> IM OUT

did you resolve it? I facing same error?
