### ISSUE TITLE
Bittrex [SSL: CERTIFICATE_VERIFY_FAILED] error (works with web browser)

### ISSUE THREAD

**Issue by hexdump2002** [ccxt/ccxt#904]
Just trying to get markets from bittrex as per example gives me that excepton on Python.

- OS: OSX
- Language: Python
- CCXT version: 1.10.416
- Exchange: Bittrex
- Method: load_markets()

it works correctly on firefox using https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries 

```
COPYPASTE_YOUR_CODE_TO_REPRODUCE_THE_BUG_HERE
DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```
import ccxt

'''bitrex api keys'''
bitrexApiKey='My ApiKey'
bitrexSecretKey='My Secret Key'

bittrex=ccxt.bittrex({'apiKey':bitrexApiKey, 'secret':bitrexSecretKey})
bittrex.verbose=True
markets=bittrex.load_markets()
```
/Users/hexdump/Developing/Python/arbitragebot/venv/bin/python /Users/hexdump/Developing/Python/arbitragebot/main.py
https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries GET https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries 
Request: {'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hexdump/Developing/Python/arbitragebot/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 325, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1000))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hexdump/Developing/Python/arbitragebot/main.py", line 9, in <module>
    markets=bittrex.load_markets()
  File "/Users/hexdump/Developing/Python/arbitragebot/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 792, in load_markets
    markets = self.fetch_markets()
  File "/Users/hexdump/Developing/Python/arbitragebot/venv/lib/python3.6/site-packages/ccxt/bittrex.py", line 160, in fetch_markets
    response = self.v2GetMarketsGetMarketSummaries()
  File "/Users/hexdump/Developing/Python/arbitragebot/venv/lib/python3.6/site-packages/ccxt/bittrex.py", line 609, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/hexdump/Developing/Python/arbitragebot/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 283, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/hexdump/Developing/Python/arbitragebot/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 344, in fetch
    self.raise_error(ExchangeNotAvailable, url, method, e)
  File "/Users/hexdump/Developing/Python/arbitragebot/venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 265, in raise_error
    details,
ccxt.base.errors.ExchangeNotAvailable: bittrex GET https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)> 

```

**Comment by hexdump2002** [comment]
I forgot to say that I renewed api keys too. The method called is public though

**Comment by kroitor** [comment]
Ref: https://github.com/ccxt/ccxt/issues/882
