### ISSUE TITLE
Strange watchOrderBook bug(?) while debugging with DevTools (JS)

### ISSUE THREAD

**Issue by frzsombor** [ccxt/ccxt#9044]
I've found a very strange thing that keeps happening to me.
This time I have no idea if this is a real bug in this library or somewhere else deeper, but decided to report anyway.

I'm not pasting code here, because I'm simply using the [one-exchange-many-streams-2.js](https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/js/one-exchange-many-streams-2.js) example and this strange thing can be reproduced with it.

Steps to reproduce ([video](https://streamable.com/0gvmh0)):

1. Write a code to watch orderbooks (of one or more symbol) like in the example above
2. _Open dedicated DevTools for Node_ from chrome://inspect/#devices in Chrome Browser
3. Start your NodeJs app with the inspect flag (eg: `node --inspect yourApp`)
4. Make sure the debugger is attached.
5. While the orderbook watcher is running, open "Console" and start typing anything
6. Exception "1" or "2" is thrown, sometimes the watcher stops immediately, sometimes later

Exception 1 thrown:
```
onMessage JSON.parse EvalError: Possible side-effect in debug-evaluate
    at emitInitNative (internal/async_hooks.js:197:5)
    at emitInitScript (internal/async_hooks.js:467:3)
    at process.nextTick (internal/process/task_queues.js:131:5)
    at maybeReadMore (internal/streams/readable.js:596:13)
    at addChunk (internal/streams/readable.js:321:3)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at InflateRaw.Readable.push (internal/streams/readable.js:223:10)
    at InflateRaw.Transform.push (internal/streams/transform.js:166:32)
    at Zlib.processCallback (zlib.js:539:10)
    at Zlib.callbackTrampoline (internal/async_hooks.js:131:14)
```

Exception 2 thrown:
```
ExchangeError: binance handleOrderBook received an out-of-order nonce
  at binance.handleOrderBook (/path/to/project/node_modules/ccxt.pro/js/binance.js:286:35)
  at binance.handleMessage (/path/to/project/node_modules/ccxt.pro/js/binance.js:1322:27)
  at WsClient.onMessage (/path/to/project/node_modules/ccxt.pro/js/base/Client.js:275:14)
  at WebSocket.onMessage (/path/to/project/node_modules/ccxt.pro/node_modules/ws/lib/event-target.js:132:16)
  at WebSocket.emit (events.js:315:20)
  at Receiver.receiverOnMessage (/path/to/project/node_modules/ccxt.pro/node_modules/ws/lib/websocket.js:825:20)
  at Receiver.emit (events.js:315:20)
  at Receiver.dataMessage (/path/to/project/node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:437:14)
  at /path/to/project/node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:394:23
  at /path/to/project/node_modules/ccxt.pro/node_modules/ws/lib/permessage-deflate.js:308:9
```

Exception is getting caught here:

![image](https://user-images.githubusercontent.com/7306657/115590330-1dfe4600-a2d1-11eb-95fc-785bc27c2605.png)

However, `message` looks valid, parseable, so I don't understand why this happens.
I guess this is a really edge-case bug.

---

Programming Language version: Node.Js v14.15.5
CCXT version: v1.44.51
CCXT Pro version: v0.6.39

**Comment by kroitor** [comment]
That exception is caught, since you have enabled pausing on all exceptions. CCXT Pro will utilize the exception mechanism for control flow. Since the underlying node app uses sockets to communicate, blocking its execution will cause out-of-order messages in the websocket feed. Therefore you should not stop execution on all exceptions. That alone may be enough to answer your question and resolve this issue. Let us know if that does not help.

**Comment by frzsombor** [comment]
I see, thanks, that is understandable for me with the _Pause on exceptions_ feature enabled, but this happens with that feature disabled too. Please check [this short video](https://streamable.com/0gvmh0). This happens every time when I have _watchOrderBook_ running in the background and start typing anything in the console while trying to debug my app.
