### ISSUE TITLE
Question on Binance L2 orderbook limits

### ISSUE THREAD

**Issue by beursdummy** [ccxt/ccxt#9076]
- OS: Ubuntu 16.04
- Programming Language version: Python 
- CCXT version: 1.47.61

I have always called for L2 orderbook with a limit of 10000 (even though 5000 is the max) 

orderbook = ccxt.binance().fetch_l2_order_book('BTC/USDT', 10000)

since this morning using the 10.000 limit gives weird numbers

All I would like to understand is if something has changed in CCXT which caused the 10000 not to work anymore so I can understand what's going on.

**Comment by kroitor** [comment]
@beursdummy there's been a number of updates from Binance on the spot API recently, you might want to check the history of announcements here: 

- https://t.me/binance_api_announcements
- https://t.me/binance_api_english

You can verify what exactly is happening in verbose mode:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
exchange = ccxt.binance({
    'enableRateLimit': True,  # required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

exchange.load_markets()

exchange.verbose = True

orderbook = exchange.fetch_l2_order_book('BTC/USDT', 10000)
```

Let us know if that does not answer your question.

**Comment by beursdummy** [comment]
Tnx @kroitor 

it seems they do a specific check on the limit now.

Traceback (most recent call last):
  File "./bots/test.py", line 13, in <module>
    orderbook = binance_futures.fetch_l2_order_book('BTC/USDT', 10000)
  File "/home/cryptocoinz/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 1518, in fetch_l2_order_book
    orderbook = self.fetch_order_book(symbol, limit, params)
  File "/home/cryptocoinz/.local/lib/python3.5/site-packages/ccxt/binance.py", line 1265, in fetch_order_book
    response = getattr(self, method)(self.extend(request, params))
  File "/home/cryptocoinz/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 474, in inner
    return entry(_self, **inner_kwargs)
  File "/home/cryptocoinz/.local/lib/python3.5/site-packages/ccxt/binance.py", line 2908, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/cryptocoinz/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 495, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/cryptocoinz/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 622, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/cryptocoinz/.local/lib/python3.5/site-packages/ccxt/binance.py", line 2902, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/home/cryptocoinz/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 513, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1130,"msg":"Data sent for parameter 'limit' is not valid."}

**Comment by kroitor** [comment]
@beursdummy as you understand, it is not something we impose in CCXT – it's on the exchange side, so, i would close it at this point, if you don't mind?

**Comment by beursdummy** [comment]
ofcourse no problem. Like I said it was just a question and I have my answer. Tnx for the help!
