### ISSUE TITLE
Used api for BTCTURK deprecated.

### ISSUE THREAD

**Issue by mertdogan** [ccxt/ccxt#9077]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows
- Programming Language version: python 3.8
- CCXT version: latest

```
As you can see at https://github.com/BTCTrader/broker-api-docs page, this api is deprecated and no longer used for connected to exchange. It must upgraded to new api as explained at https://github.com/BTCTrader/broker-api-docs/blob/master/README-pro.md
```

```
 2021-04-27 00:25:06,955 ERROR    CCXTExchange[btcturk] initialization impossible: btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com
 2021-04-27 00:25:06,961 ERROR    ExchangeManager      Failed to load exchange symbols or time frames
 2021-04-27 00:25:06,964 ERROR    root                   File "octobot_trading\exchanges\exchange_manager.py", line 174, in octobot_trading.exchanges.exchange_manager.ExchangeManager._raise_exchange_load_error
NoneType: None
 2021-04-27 00:25:06,973 ERROR    root                 <class 'Exception'>: <octobot_trading.exchanges.implementations.default_spot_ccxt_exchange.DefaultCCXTSpotExchange object at 0x00000273AAE50670> - Failed to load exchange instances
NoneType: None
Exception ignored in: 'octobot_trading.exchanges.exchange_manager.ExchangeManager._load_config_symbols_and_time_frames'
Traceback (most recent call last):
  File "octobot_trading\exchanges\exchange_manager.py", line 174, in octobot_trading.exchanges.exchange_manager.ExchangeManager._raise_exchange_load_error
Exception: <octobot_trading.exchanges.implementations.default_spot_ccxt_exchange.DefaultCCXTSpotExchange object at 0x00000273AAE50670> - Failed to load exchange instances
 2021-04-27 00:25:06,993 ERROR    ExchangeConfig       btcturk is not supporting the BTC/USDT trading pair.
 2021-04-27 00:25:06,997 ERROR    ExchangeConfig       btcturk is not supporting any Bitcoin trading pair from the current configuration.
 2021-04-27 00:25:07,009 DEBUG    OHLCVUpdater[btcturk] Pausing...
 2021-04-27 00:25:07,011 DEBUG    OrderBookUpdater[btcturk] Pausing...
 2021-04-27 00:25:07,013 DEBUG    RecentTradeUpdater[btcturk] Pausing...
 2021-04-27 00:25:07,021 DEBUG    TickerUpdater[btcturk] Pausing...
 2021-04-27 00:25:07,024 DEBUG    KlineUpdater[btcturk] Pausing...
 2021-04-27 00:25:07,028 DEBUG    MarkPriceUpdater[btcturk] Pausing...
 2021-04-27 00:25:07,030 DEBUG    FundingUpdater[btcturk] Pausing...
 2021-04-27 00:25:07,037 DEBUG    OrdersUpdaterSimulator[btcturk] Pausing...
 2021-04-27 00:25:07,038 DEBUG    BalanceProfitabilityUpdater Pausing...
 2021-04-27 00:25:07,043 DEBUG    PositionsUpdaterSimulator[btcturk] Pausing...
 2021-04-27 00:25:07,046 DEBUG    SpotPortfolioSimulator[btcturk] Portfolio updated | Current Portfolio : {'BTC': {'available': 10.0, 'total': 10.0}, 'USDT': {'available': 1000.0, 'total': 1000.0}}
 2021-04-27 00:25:07,051 INFO     PortfolioManager     Current Portfolio : {'BTC': {'available': 10.0, 'total': 10.0}, 'USDT': {'available': 1000.0, 'total': 1000.0}}
 2021-04-27 00:25:07,057 DEBUG    TraderSimulator[btcturk] Enabled on btcturk
 2021-04-27 00:25:07,061 INFO     CCXTExchange[btcturk] Closing connection.
 2021-04-27 00:25:07,067 INFO     CCXTExchange[btcturk] Connection closed.
 2021-04-27 00:25:07,069 ERROR    OctoBotChannelTradingConsumer Error when initializing trading mode, btcturk exchange connection is closed to increase performances: As non symbol-wildcard trading mode, DailyTradingMode requires at least one exchange trading pair to be initialized. None of the required pairs are available on btcturk.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000273A4C56040>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000273A4C56040>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
 2021-04-27 00:27:29,716 ERROR    WebConfigurationModel btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com
Traceback (most recent call last):
  File "ccxt\base\exchange.py", line 602, in fetch
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: https://www.btcturk.com/api/ticker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Yüklenenler\tentacles\Services\Interfaces\web_interface\models\configuration.py", line 521, in get_symbol_list
    inst.load_markets()
  File "ccxt\base\exchange.py", line 1374, in load_markets
  File "ccxt\btcturk.py", line 71, in fetch_markets
  File "ccxt\base\exchange.py", line 470, in inner
  File "ccxt\base\exchange.py", line 495, in request
  File "ccxt\base\exchange.py", line 491, in fetch2
  File "ccxt\base\exchange.py", line 619, in fetch
  File "ccxt\base\exchange.py", line 655, in handle_http_status_code
ccxt.base.errors.ExchangeNotAvailable: btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com
 2021-04-27 00:27:29,745 ERROR    WebConfigurationModel error when loading symbol list for btcturk: btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com (ExchangeNotAvailable)
 2021-04-27 00:55:39,158 ERROR    WebConfigurationModel btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com
Traceback (most recent call last):
  File "ccxt\base\exchange.py", line 602, in fetch
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: https://www.btcturk.com/api/ticker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Yüklenenler\tentacles\Services\Interfaces\web_interface\models\configuration.py", line 521, in get_symbol_list
    inst.load_markets()
  File "ccxt\base\exchange.py", line 1374, in load_markets
  File "ccxt\btcturk.py", line 71, in fetch_markets
  File "ccxt\base\exchange.py", line 470, in inner
  File "ccxt\base\exchange.py", line 495, in request
  File "ccxt\base\exchange.py", line 491, in fetch2
  File "ccxt\base\exchange.py", line 619, in fetch
  File "ccxt\base\exchange.py", line 655, in handle_http_status_code
ccxt.base.errors.ExchangeNotAvailable: btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com
 2021-04-27 00:55:39,169 ERROR    WebConfigurationModel error when loading symbol list for btcturk: btcturk GET https://www.btcturk.com/api/ticker 405 Not Allowed Method not supported anymore. Please refer to https://docs.btcturk.com (ExchangeNotAvailable)
```

**Comment by kroitor** [comment]
@mertdogan hi! What is your version of CCXT? We have just updated BTCTurk recently!

**Comment by mertdogan** [comment]
> @mertdogan hi! What is your version of CCXT? We have just updated BTCTurk recently!

Hi. Thank you for your reply. I don't know version used for. I installed latest version of OctoBot. I reported this issue there and they wrote me "this is not related OctoBot, this is related cctx": https://github.com/Drakkar-Software/OctoBot/issues/1666

I don't know are there a way to see version of cctx that running.

**Comment by kroitor** [comment]
@mertdogan please upgrade your version of CCXT to the most recent one.

```
pip3 install -U ccxt
```

If you are installing a precompiled binary from a 3rd-party developer, then, please, ask the developer of your bot to upgrade CCXT and provide a fresh build of the executable. Let us know if that does not answer your question.
