### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by mrschneebly** [ccxt/ccxt#9100]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- OS: WIN 10
- Programming Language version: Python 3.9.4
- CCXT version: 1.49.17

I am running into some ugly problems after upgrading to Python 3.9

pip -list 
Package           Version
----------------- -----------
aiodns            2.0.0
aiohttp           3.7.4.post0
async-timeout     3.0.1
attrs             20.3.0
**ccxt              1.49.17**
certifi           2020.12.5
cffi              1.14.5
chardet           4.0.0
cryptography      3.4.7
future            0.18.2
idna              2.10
multidict         5.1.0
numpy             1.20.2
pip               21.1
pycares           3.1.1
pycparser         2.20
python-ctapi      0.3.0
PyYAML            5.4.1
requests          2.25.1
setuptools        56.0.0
typing-extensions 3.7.4.3
urllib3           1.26.4
yarl              1.6.3

```
import ccxt
```

```
"C:\Program Files\Python39\python.exe" "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.1\plugins\python-ce\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 50454 --file "-MYPATH-\main.py"
Connected to pydev debugger (build 211.7142.13)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Program Files\Python39\lib\site-packages\ccxt\__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "C:\Program Files\Python39\lib\site-packages\ccxt\base\__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "C:\Program Files\Python39\lib\site-packages\ccxt\base\exchange.py", line 41, in <module>
    from ccxt.static_dependencies import ecdsa
  File "C:\Program Files\Python39\lib\site-packages\ccxt\static_dependencies\ecdsa\__init__.py", line 1, in <module>
    from .keys import SigningKey, VerifyingKey, BadSignatureError, BadDigestError
  File "C:\Program Files\Python39\lib\site-packages\ccxt\static_dependencies\ecdsa\keys.py", line 3, in <module>
    from . import ecdsa
  File "C:\Program Files\Python39\lib\site-packages\ccxt\static_dependencies\ecdsa\ecdsa.py", line 56, in <module>
    from six import int2byte, b
ModuleNotFoundError: No module named 'six'
python-BaseException

Process finished with exit code -1

```

All the other modules seem to work fine. What am I doing wrong?

**Comment by mrschneebly** [comment]
Even if I go back to Python 3.7 I get this error now. WTF did I do wrong? Can someone help? I tried for hours. Reinstalling Pycharm and Python Interpreter.

**Comment by mrschneebly** [comment]
I installed the package "six". Now it works. Python 2 and 3 compatibility utilities. still wonder how this could happen and if this package is legit.

**Comment by kroitor** [comment]
> still wonder how this could happen 

The support for Python2 was dropped: https://python3statement.org/

> and if this package is legit.

Yes it is legit, and it may be necessary if you have multiple version of Python installed.

Let us know if that does not answer your question.
