### ISSUE TITLE
Deribit get_position call unauthorized

### ISSUE THREAD

**Issue by gancarani** [ccxt/ccxt#9133]
- OS: Mac OS
- Programming Language version: Python 3
- CCXT version: 1.0.0

exchange = ccxt.deribit({
    'apiKey': 'key',
    'secret': 'secret',
    'enableRateLimit': True, # required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'future',
    },
})

size = exchange.privateGetGetPosition()

I'm trying to get the position from Deribit and the method is calling the get API https://www.deribit.com/api/v2/private/get_position 

but I get this error:

{"jsonrpc":"2.0","error":{"message":"unauthorized","code":13009},"testnet":false,"usIn":1620162727414410,"usOut":1620162727414499,"usDiff":89}

**Comment by kroitor** [comment]
@gancarani 

1. what is your version of CCXT? 
2. have you tried a fresh new keypair?
3. can you paste the output in verbose mode?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by gancarani** [comment]
Hi @kroitor, thanks for the quick reply:

1. what is your version of CCXT? --> CCXTVersion: 1.47.60
2. have you tried a fresh new keypair? --> yes
3. can you paste the output in verbose mode? --> See below

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 606, in fetch
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.deribit.com/api/v2/private/get_position

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gian/PycharmProjects/test_deribit/main.py", line 44, in <module>
    size = exchangeDeribit.privateGetGetPosition() #https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 474, in inner
    return entry(_self, **inner_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 499, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 495, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 622, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/deribit.py", line 1709, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, errorCode, feedback)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 513, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: deribit {"jsonrpc":"2.0","error":{"message":"Invalid params","data":{"reason":"value required","param":"instrument_name"},"code":-32602},"testnet":false,"usIn":1620328656643241,"usOut":1620328656644086,"usDiff":845}
