### ISSUE TITLE
Bybit testnet issue with create_order, "ret_code":10004

### ISSUE THREAD

**Issue by speed-up-website** [ccxt/ccxt#9149]
- OS: CENTOS 7.9
- Programming Language version: PHP 7.4.18
- CCXT version: 1.49.61

**My code:**
```
require __DIR__ . '/../vendor/autoload.php';
$exchange = new \ccxt\bybit(array(
    'apiKey' => 'key-here',
    'secret' => 'secret-here',
    'timeout' => 30000,
    'enableRateLimit' => true,
));
$exchange->set_sandbox_mode(true);
echo "CCXT version: " . \ccxt\Exchange::VERSION . "<br />";
$markets = $exchange->load_markets(); // load all markets
$exchange->verbose = true;

$order = $exchange->create_order('XRP/USD', 'limit', 'buy', 3, 1.5274);
```

**Output:**
```
CCXT version: 1.49.61

Array
(
    [0] => Request:
    [1] => POST
    [2] => https://api-testnet.bybit.com/v2/private/order/create
    [3] => Array
        (
            [Content-Type] => application/json
        )

    [4] => {"side":"Buy","symbol":"XRPUSD","order_type":"Limit","qty":3,"time_in_force":"GoodTillCancel","price":1.52740000000000009094947017729282379150390625,"api_key":"key-here","recv_window":5000,"timestamp":1620479666458,"sign":"ce9b6f2631bba02f56a1d0bfe625e3c2d0cbcbc087fd1daf4cabe26333f244de"}
)
Array
(
    [0] => Response:
    [1] => POST
    [2] => https://api-testnet.bybit.com/v2/private/order/create
    [3] => 200
    [4] => 
    [5] => Array
        (
            [Content-Type] => application/json; charset=utf-8
            [Content-Length] => 366
            [Expires] => Sat, 08 May 2021 13:14:26 GMT
            [Cache-Control] => max-age=0, no-cache, no-store
            [Pragma] => no-cache
            [Date] => Sat, 08 May 2021 13:14:26 GMT
            [Connection] => keep-alive
        )

    [6] => {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=key-here\u0026order_type=Limit\u0026price=1.52740000000000009094947017729282379150390625\u0026qty=3\u0026recv_window=5000\u0026side=Buy\u0026symbol=XRPUSD\u0026time_in_force=GoodTillCancel\u0026timestamp=1620479666458]","ext_code":"","ext_info":"","result":null,"time_now":"1620479666.560160"}
)


Fatal error:  Uncaught ccxt\AuthenticationError: bybit {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=key-here\u0026order_type=Limit\u0026price=1.52740000000000009094947017729282379150390625\u0026qty=3\u0026recv_window=5000\u0026side=Buy\u0026symbol=XRPUSD\u0026time_in_force=GoodTillCancel\u0026timestamp=1620479666458]","ext_code":"","ext_info":"","result":null,"time_now":"1620479666.560160"} in /home/username/public_html/trading/app/vendor/ccxt/ccxt/php/Exchange.php:1391
Stack trace:
#0 /home/username/public_html/trading/app/vendor/ccxt/ccxt/php/bybit.php(2297): ccxt\Exchange->throw_exactly_matched_exception(Array, '10004', 'bybit {"ret_cod...')
#1 /home/username/public_html/trading/app/vendor/ccxt/ccxt/php/Exchange.php(1626): ccxt\bybit->handle_errors(200, 'OK', 'https://api-tes...', 'POST', Array, '{"ret_code":100...', Array, Array, '{"side":"Buy","...')
#2 /home/username/public_html/trading/app/vendor/ccxt/ccxt/php/Exchange.php(1382): ccxt\Exchange->fetch('https://api-tes...', 'POST', Array, ' in /home/username/public_html/trading/app/vendor/ccxt/ccxt/php/Exchange.php on line 1391

```
Please look at this part- "price":1.52740000000000009094947017729282379150390625
I provided the price value: 1.5274

**Comment by kroitor** [comment]
@speed-up-website thx for reporting, we will investigate and will be back you asap.

**Comment by shoemoney** [comment]
Xrp always gives errors.   its not ccxt

**Comment by alesha1488** [comment]
CCXT version: 1.51.92

Array
(
    [0] => Request:
    [1] => POST
    [2] => https://api-testnet.bybit.com/private/linear/order/create
    [3] => Array
        (
            [Content-Type] => application/json
        )

    [4] => {"side":"Sell","symbol":"BTCUSDT","order_type":"Limit",**"qty":0.010000000000000002**,"time_in_force":"GoodTillCancel","price":50000,"reduce_only":true,"close_on_trigger":true,"api_key":"R6ITMkjBpN9z3S87qC","recv_window":5000,"timestamp":1624448347507,"sign":"d52c83da1b6fc5811fc3bd0d0b4691ce1cff1686702a3933e17065271c7f7dba"}
)
Array
(
    [0] => Response:
    [1] => POST
    [2] => https://api-testnet.bybit.com/private/linear/order/create
    [3] => 200
    [4] => 
    [5] => Array
        (
            [Content-Type] => application/json; charset=utf-8
            [Content-Length] => 395
            [Expires] => Wed, 23 Jun 2021 11:39:07 GMT
            [Cache-Control] => max-age=0, no-cache, no-store
            [Pragma] => no-cache
            [Date] => Wed, 23 Jun 2021 11:39:07 GMT
            [Connection] => keep-alive
        )

    [6] => {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=R6ITMkjBpN9z3S87qC\u0026close_on_trigger=true\u0026order_type=Limit\u0026price=50000\u0026**qty=0.010000000000000002**\u0026recv_window=5000\u0026reduce_only=true\u0026side=Sell\u0026symbol=BTCUSDT\u0026time_in_force=GoodTillCancel\u0026timestamp=1624448347507]","ext_code":"","ext_info":"","r
esult":null,"time_now":"1624448347.624089"}

**Comment by alesha1488** [comment]
Why closed? Problem not solved yet.

**Comment by alesha1488** [comment]
Any updates?

**Comment by kroitor** [comment]
@alesha1488 do you have the same issue with the most recent version of the lib 1.54.40+?

**Comment by alesha1488** [comment]
[Exchange Error] bybit {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=R6ITMkjBpN9z3S87qC\u0026close_on_trigger=false\u0026order_type=Limit\u0026price=3290\u0026qty=0.089999999999999997\u0026recv_window=5000\u0026reduce_only=false\u0026side=Buy\u0026symbol=ETHUSDT\u0026time_in_force=GoodTillCancel\u0026timestamp=1631631843280]","ext_code":"","ext_info":"","result":null,"time_now":"1631631843.413867"}

in request qty=0.089999999999999997

#0 /ccxt/ccxt/php/bybit.php(2413): ccxt\Exchange->throw_exactly_matched_exception(Array, '10004', 'bybit {"ret_cod...')
#1 /ccxt/ccxt/php/Exchange.php(1671): ccxt\bybit->handle_errors(200, 'OK', 'https://api-tes...', 'POST', Array, '{"ret_code":100...', Array, Array, '{"side":"Buy","...')
#2 /ccxt/ccxt/php/Exchange.php(1427): ccxt\Exchange->fetch('https://api-tes...', 'POST', Array, '{"side":"Buy","...')
#3 /ccxt/ccxt/php/Exchange.php(1431): ccxt\Exchange->fetch2('order/create', Array, 'POST', Array, NULL, NULL, Array, Array)
#4 [internal function]: ccxt\Exchange->request('order/create', Array, 'POST', Array, NULL, NULL, Array, Array)
#5 /ccxt/ccxt/php/Exchange.php(2555): call_user_func_array(Array, Array)
#6 /ccxt/ccxt/php/bybit.php(1425): ccxt\Exchange->__call('privateLinearPo...', Array)
#7 ccxt\bybit->create_order('ETH/USDT', 'limit', 'buy', 0.09, '3290', Array)

**Comment by alesha1488** [comment]
The bug exists for more than a year.

```
echo 'CCXT v' . \ccxt\Exchange::VERSION . "\n";

$exchange = new \ccxt\bybit(array(
    'apiKey' => $API_key,
    'secret' => $API_secret,
    // 'verbose' => true, // uncomment if debug output is needed
));
$exchange->set_sandbox_mode(true);

try {
        $order = $exchange->create_order('BTC/USDT:USDT', 'limit', 'buy', '0.007', 29527.6);
        print_r ($order);

} catch (\ccxt\NetworkError $e) {
        echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
        echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
        echo '[Error] ' . $e->getMessage () . "\n";
}
```


CCXT v1.84.75
[Exchange Error] bybit {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=R6ITMkjBpN9z3S87qC\u0026close_on_trigger=false\u0026order_type=Limit\u0026price=29527.5\u0026qty=0.0070000000000000001\u0026r
ecv_window=5000\u0026reduce_only=false\u0026side=Buy\u0026symbol=BTCUSDT\u0026time_in_force=GoodTillCancel\u0026timestamp=1654328054844]","ext_code":"","ext_info":"","result":null,"time_now":"1654328055.031369"}

**Comment by ttodua** [comment]
This seems a bit old topic, but a while ago, CCXT released new Bybit upgrade, and now, when I check your issues, the are no longer happening. 
Please let us know if you have any issues.

**Comment by alesha1488** [comment]
CCXT v1.90.99
[Exchange Error] bybit {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=R6ITMkjBpN9z3S87qC\u0026close_on_trigger=false\u0026order_type=Limit\u0026price=29527.5\u0026qty=0.0070000000000000001\u0026r
ecv_window=5000\u0026reduce_only=false\u0026side=Buy\u0026symbol=BTCUSDT\u0026time_in_force=GoodTillCancel\u0026timestamp=1658336245629]","ext_code":"","ext_info":"","result":null,"time_now":"1658336246.117306"}

I am checking 1-2 times per week...

**Comment by carlosmiei** [comment]
Hey @alesha1488, can you elaborate a bit more? Are you 100% sure the API keys are valid and don't have any restrictions in place?

**Comment by ttodua** [comment]
@carlosmiei i doubt that problem might be in `qty` value being abnormal and that causes the issue imho. But how that value is being generated? if he uses `price` argument, then we are `to-precision`-ing it already and such value should not be generated. 

@alesha1488 on first place, why you provide the `'0.007'` (or whatever) in string form? try to pass a numeric , not string, and let me know.

**Comment by alesha1488** [comment]
`
echo 'CCXT v' . \ccxt\Exchange::VERSION . "\n";

$exchange = new \ccxt\bybit(array(
    'apiKey' => $API_key,
    'secret' => $API_secret,
    // 'verbose' => true, // uncomment if debug output is needed
));
$exchange->options['defaultType'] = 'swap';
$exchange->set_sandbox_mode(true);
$markets = $exchange->load_markets();


try {
        $order = $exchange->create_order('BTC/USDT:USDT', 'limit', 'buy', '0.007', 29527.6);
        print_r ($order);

} catch (\ccxt\NetworkError $e) {
        echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
        echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
        echo '[Error] ' . $e->getMessage () . "\n";
}
`

yes, my api are valid. working on spot markets well

**Comment by ttodua** [comment]
ok, thanks for report, I am checking it again.

**Comment by carlosmiei** [comment]
@alesha1488 I ran the exact same script and worked just fine
![image](https://user-images.githubusercontent.com/43336371/180187350-5b1ccb09-42dc-4be0-a499-f390b45a7f16.png)

**Comment by carlosmiei** [comment]
@alesha1488 PHP 7.4.30

**Comment by ttodua** [comment]
I've digged into this issue and couldnt anyhow reproduce the issue. I think there is some misconfiguration on user side. @alesha1488 can you trace, how `0.007` turns into `0.0070000000000000001` ? that is the problem as I said above .

**Comment by ttodua** [comment]
@alesha1488 can you please provide your thoughts? which PHP version do you use, or if you can trace how your `0.007` turns into  `0.0070000000000000001`, as we couldn't reproduce, nor guess in which line that incorrect transformation happens.  Do you use something other config which is not shown in your provided snippet?

**Comment by ttodua** [comment]
we didnt hear any further feedback on this, so closing this for now. if anyone experiences similar, would be re-reviewed
