### ISSUE TITLE
Bittrex watchOrderBook undefined orderbook.cache

### ISSUE THREAD

**Issue by tuloski** [ccxt/ccxt#9160]
When subscribing to lots of orderbooks (150+) this happens:

```
/node_modules/ccxt.pro/js/bittrex.js:627
            orderbook.cache.push (message);
                            ^

TypeError: Cannot read property 'push' of undefined
    at bittrex.handleOrderBook (/node_modules/ccxt.pro/js/bittrex.js:627:29)
    at bittrex.handleMessage (/node_modules/ccxt.pro/js/bittrex.js:772:32)
    at WsClient.onMessage (/node_modules/ccxt.pro/js/base/Client.js:279:14)
    at WebSocket.onMessage (/node_modules/ccxt.pro/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/node_modules/ccxt.pro/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:143:22)
```

- OS: Ubuntu 18.04
- Programming Language version: JS
- CCXT version: Latest

I'm using the snippet provided in the example:
```
const loop = async (symbol) => {
  while (true) {
    try {
	    const orderbook = await this.bittrex.watchOrderBook (symbol, 25);
	    console.log (new Date (), symbol, orderbook['asks'][0], orderbook['bids'][0])
    } catch (e) {
	    console.log (symbol, e)
	    // do nothing and retry on next loop iteration
	    // throw e // uncomment to break all loops in case of an error in any one of them
	    // break // you can also break just this one loop if it fails
    }
  }
}
await Promise.all (symbols.map (symbol => loop (symbol)));
```

**Comment by ttodua** [comment]
I remind this same issue [here](https://github.com/ccxt/ccxt/issues/10533) and it was fixed in [this PR](https://github.com/kroitor/ccxt.pro/pull/351).

Let us know if you will experience any issue anymore.
