### ISSUE TITLE
Error fetching balance

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#920]
Error fetching balance

- OS: Windows & linux
- Language: Python 3.6 sync & async
- CCXT version: 1.10.437
- Exchange: cryptopia, bittrex, probably others
- Method: fetch_balance()
- With and without proxies

```
import ccxt
import test_config as config


def main():
    exchange = 'cryptopia'
    e = ccxt.cryptopia()
    e.verbose = True
    e.apiKey = config.exchange_keys[exchange]['key']
    e.secret = config.exchange_keys[exchange]['secret']
    print(e.fetch_balance())


if __name__ == "__main__":
    main()
```

```
_test/test_sync.py
GET https://www.cryptopia.co.nz/api/GetTradePairs 
Request: {'Accept-Encoding': 'gzip, deflate'} None
GET https://www.cryptopia.co.nz/api/GetTradePairs 
Response: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'Date': 'Thu, 21 Dec 2017 18:37:01 GMT', 'Set-Cookie': 'visid_incap_<snip>; expires=Fri, 21 Dec 2018 11:44:16 GMT; path=/; Domain=.cryptopia.co.nz, <snip>; path=/; Domain=.cryptopia.co.nz, incap_ses<snip>; path=/; Domain=.cryptopia.co.nz', 'Strict-Transport-Security': 'max-age=31536000', 'X-Iinfo': '<snip>', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked'} {"Success":true,<snip JSON looks good>
GET https://www.cryptopia.co.nz/api/GetCurrencies 
Request: {'Accept-Encoding': 'gzip, deflate'} None
GET https://www.cryptopia.co.nz/api/GetCurrencies 
Response: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'Date': 'Thu, 21 Dec 2017 18:37:02 GMT', 'Set-Cookie': 'visid_incap_<snip>; expires=Fri, 21 Dec 2018 11:44:16 GMT; path=/; Domain=.cryptopia.co.nz, <snip>; path=/; Domain=.cryptopia.co.nz', 'Strict-Transport-Security': 'max-age=31536000', 'X-Iinfo': '<snip>', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked'} {"Success":true,<snip JSON looks good>
Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/test/_test/test_sync.py", line 16, in <module>
    main()
  File "C:/Users/gaardiolor/PycharmProjects/test/_test/test_sync.py", line 12, in main
    pprint(e.fetch_balance())
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\cryptopia.py", line 330, in fetch_balance
    response = self.privatePostGetBalance()
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\cryptopia.py", line 554, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 288, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\cryptopia.py", line 541, in sign
    secret = base64.b64decode(self.secret)
  File "C:\Users\gaardiolor\Anaconda3\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

Process finished with exit code 1
```

**Comment by kroitor** [comment]
Can you show your verbose output?

```Python
import ccxt
from pprint import pprint


def main():
    exchange = 'cryptopia'
    e = getattr(ccxt, exchange)()
    e.apiKey = config.exchange_keys[exchange]['key']
    e.secret = config.exchange_keys[exchange]['secret']
    e.verbose = true
    pprint(e.fetch_balance())
```

**Comment by kroitor** [comment]
The cryptopia key has a '=' base64 terminator sign in the end of its string, make sure you are not losing/missing the last symbol when copy-pasting.

**Comment by gaardiolor** [comment]
Sorry for wasting your time. The cryptopia api secret field is very small and doesn't show the whole key, I must have doubleclicked it to copy which doesn't select the '='. Hope this helps someone else :)

**Comment by Zachteberm** [comment]
Very nice, this probably saved me at least a couple of hours trying to find out what is wrong :D
