### ISSUE TITLE
okex error fetch_balance

### ISSUE THREAD

**Issue by jaseisen105** [ccxt/ccxt#9259]
- OS: mac 11.2.3
- Programming Language version: python 3.6
- CCXT version: 1.50.37 | 0.6.97

Just trying to get balances from the new okex v5, seeing this error

The account I'm trying to get has only a small amount of BTC in it, less than 0.05

```python
await client.fetch_balance()
```

```
Traceback (most recent call last):
  File "/holdings.py", line 49, in refresh
    self.response = await self.client.fetch_balance()
  File "/lib/python3.6/site-packages/ccxt/async_support/okex5.py", line 1165, in fetch_balance
    return self.parse_balance(result, False)
  File "/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1563, in parse_balance
    balance[currency]['used'] = Precise.string_sub(balance[currency]['total'], balance[currency]['free'])
  File "/lib/python3.6/site-packages/ccxt/base/precise.py", line 132, in string_sub
    return str(Precise(string1).sub(Precise(string2)))
  File "/lib/python3.6/site-packages/ccxt/base/precise.py", line 34, in __init__
    self.integer = int(integer_string)
```

**Comment by kroitor** [comment]
Please, paste your verbose output:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.okex5({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_TRADE_PASSWORD',
})
markets = exchange.load_markets()
exchange.verbose = True
balance = exchange.fetch_balance()
pprint(balance)
```

**Comment by jaseisen105** [comment]
@kroitor emailed it to you

**Comment by kroitor** [comment]
@jaseisen105 in your output, there's this line: `Backend TkAgg is interactive backend. Turning interactive mode on.` – where does it come from?

I can't reproduce it on my side:

```
~/ccxt $ python3 examples/py/cli.py okex5 fetch_balance --verbose
Python v3.8.2
CCXT v1.50.40

Request: GET https://www.okex.com/api/v5/account/balance {'OK-ACCESS-KEY': '591b5a40-3e74-4c70-aeb6-54fec8e51572', 'OK-ACCESS-PASSPHRASE': '7KUcc8YzQhnxBE3K', 'OK-ACCESS-TIMESTAMP': '2021-05-26T16:21:52.732Z', 'OK-ACCESS-SIGN': 'oVTCAQmNoY2fChLDDkayoOFgoR67yUyZt8pIR7+qt80=', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.okex.com/api/v5/account/balance 200 {'Date': 'Wed, 26 May 2021 16:21:53 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Set-Cookie': 'locale=en_US; Max-Age=604800; Expires=Wed, 02-Jun-2021 16:21:53 GMT; Path=/', 'X-BrokerID': '0', 'Strict-Transport-Security': 'max-age=63072000; includeSubdomains; preload', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '0a4b14944900007b3341b34000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '655856cd48827b33-DME'} {"code":"0","data":[{"adjEq":"","details":[{"availBal":"","availEq":"0.007525467","cashBal":"0.007525467","ccy":"ETH","crossLiab":"","disEq":"20.949823986219","eq":"0.007525467","eqUsd":"20.949823986219","frozenBal":"0","interest":"","isoEq":"0","isoLiab":"","liab":"","maxLoan":"","mgnRatio":"","notionalLever":"0","ordFrozen":"0","twap":"0","uTime":"1621927314996","upl":"0","uplLiab":""},{"availBal":"","availEq":"8.21009913","cashBal":"8.21009913","ccy":"USDT","crossLiab":"","disEq":"8.219951248956","eq":"8.21009913","eqUsd":"8.219951248956","frozenBal":"0","interest":"","isoEq":"0","isoLiab":"","liab":"","maxLoan":"","mgnRatio":"","notionalLever":"0","ordFrozen":"0","twap":"0","uTime":"1621927314996","upl":"0","uplLiab":""}],"imr":"","isoEq":"0","mgnRatio":"","mmr":"","notionalUsd":"","ordFroz":"","totalEq":"29.169775235175","uTime":"1622046113055"}],"msg":""}
{'ETH': {'free': 0.007525467, 'total': 0.007525467, 'used': 0.0},
 'USDT': {'free': 8.21009913, 'total': 8.21009913, 'used': 0.0},
 'datetime': '2021-05-26T16:21:53.055Z',
 'free': {'ETH': 0.007525467, 'USDT': 8.21009913},
 'info': {'code': '0',
          'data': [{'adjEq': '',
                    'details': [{'availBal': '',
                                 'availEq': '0.007525467',
                                 'cashBal': '0.007525467',
                                 'ccy': 'ETH',
                                 'crossLiab': '',
                                 'disEq': '20.949823986219',
                                 'eq': '0.007525467',
                                 'eqUsd': '20.949823986219',
                                 'frozenBal': '0',
                                 'interest': '',
                                 'isoEq': '0',
                                 'isoLiab': '',
                                 'liab': '',
                                 'maxLoan': '',
                                 'mgnRatio': '',
                                 'notionalLever': '0',
                                 'ordFrozen': '0',
                                 'twap': '0',
                                 'uTime': '1621927314996',
                                 'upl': '0',
                                 'uplLiab': ''},
                                {'availBal': '',
                                 'availEq': '8.21009913',
                                 'cashBal': '8.21009913',
                                 'ccy': 'USDT',
                                 'crossLiab': '',
                                 'disEq': '8.219951248956',
                                 'eq': '8.21009913',
                                 'eqUsd': '8.219951248956',
                                 'frozenBal': '0',
                                 'interest': '',
                                 'isoEq': '0',
                                 'isoLiab': '',
                                 'liab': '',
                                 'maxLoan': '',
                                 'mgnRatio': '',
                                 'notionalLever': '0',
                                 'ordFrozen': '0',
                                 'twap': '0',
                                 'uTime': '1621927314996',
                                 'upl': '0',
                                 'uplLiab': ''}],
                    'imr': '',
                    'isoEq': '0',
                    'mgnRatio': '',
                    'mmr': '',
                    'notionalUsd': '',
                    'ordFroz': '',
                    'totalEq': '29.169775235175',
                    'uTime': '1622046113055'}],
          'msg': ''},
 'timestamp': 1622046113055,
 'total': {'ETH': 0.007525467, 'USDT': 8.21009913},
 'used': {'ETH': 0.0, 'USDT': 0.0}}
```

**Comment by kroitor** [comment]
@jaseisen105 i think the tkAgg message comes from your PyCharm IDE:
- https://www.google.com/search?q=tkagg+is+interactive+backend

**Comment by kroitor** [comment]
@jaseisen105 ok, looks like we know where the problem is, will push some fixes shortly.

**Comment by kroitor** [comment]
@jaseisen105 a quick question: do you use the Classic Account or the Unified Account?

**Comment by kroitor** [comment]
@jaseisen105 let us know if you still have this issue with CCXT 1.50.42

**Comment by jaseisen105** [comment]
@kroitor I'm on the unified account

Confirmed it's working after the update.  Thanks!
