### ISSUE TITLE
binance async_support RequestTimeout

### ISSUE THREAD

**Issue by X-Mars** [ccxt/ccxt#9263]
Dear friends:

I got **RequestTimeout** when i use **async_support** in binance.
Can anyone help me?
Thank for your help.
Have a nice day.

- OS: Windows
- Programming Language version: Python 3.9
- CCXT version: 1.50.34

```python
import json, asyncio, os, sys
import ccxt.async_support as ccxt
from Mario.models import Orders, ApiKeys
from Mario.serializers import OrdersSerializers
from asgiref.sync import async_to_sync, sync_to_async

async def binance_runner(apikey):
    # print('binance_entry')
    # apikeys_list = ApiKeys.objects.filter(exchange_name='binance').values()
    orders_list_all = []
    # for apikey in apikeys_list:
    print(apikey)
    orders_list = []
    binance = ccxt.binance({
        'apiKey': apikey['apiKey'],
        'secret': apikey['secret'],
    })
    print('here')
    binance.options["warnOnFetchOpenOrdersWithoutSymbol"] = False
    print('here')
    print(await binance.fetch_time())

def binance_entry():
    print('binance_entry')
    apikeys_list = ApiKeys.objects.filter(exchange_name='binance').values()

    for apikey in apikeys_list:
        print(apikey)
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        loop.run_until_complete(binance_runner(apikey))
        loop.close()
    loop = asyncio.new_event_loop()
    # [asyncio.ensure_future(binance_runner(apikey)) for apikey in apikeys_list]
    # pending = asyncio.Task.all_tasks()
    # loop = asyncio.new_event_loop()
    # asyncio.set_event_loop(loop)
    # loop.run_until_complete(asyncio.gather(*pending))
```

```logs
Internal Server Error: /refresh_orders/
Traceback (most recent call last):
  File "G:\env\Mipha\lib\site-packages\ccxt-1.50.34-py3.9.egg\ccxt\async_support\base\exchange.py", line 117, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "G:\env\Mipha\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "G:\env\Mipha\lib\site-packages\aiohttp\client.py", line 619, in _request
    break
  File "G:\env\Mipha\lib\site-packages\aiohttp\helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "G:\env\Mipha\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "G:\env\Mipha\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\weiyun\dev\PycharmProjects\Mipha\Mario\views.py", line 15, in refresh_orders
    orders_list = binance_entry()
  File "G:\weiyun\dev\PycharmProjects\Mipha\Mario\binance.py", line 59, in binance_entry
    loop.run_until_complete(binance_runner(apikey))
  File "C:\Users\X-Mars\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "G:\weiyun\dev\PycharmProjects\Mipha\Mario\binance.py", line 27, in binance_runner
    print(await binance.fetch_time())
  File "G:\env\Mipha\lib\site-packages\ccxt-1.50.34-py3.9.egg\ccxt\async_support\binance.py", line 680, in fetch_time
    response = await getattr(self, method)(params)
  File "G:\env\Mipha\lib\site-packages\ccxt-1.50.34-py3.9.egg\ccxt\async_support\binance.py", line 2930, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "G:\env\Mipha\lib\site-packages\ccxt-1.50.34-py3.9.egg\ccxt\async_support\base\exchange.py", line 96, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "G:\env\Mipha\lib\site-packages\ccxt-1.50.34-py3.9.egg\ccxt\async_support\base\exchange.py", line 151, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v3/time
```

**Comment by kroitor** [comment]
Hi!

Does this work for you:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance()
time = exchange.fetch_time()
print(exchange.iso8601(time))
```

**Comment by X-Mars** [comment]
Hi !
**fetch_time** is just a test.
My demand is to count the orders of different exchanges through asyncio.
```python

    symbols_list = await binance.sapiGetCapitalConfigGetall()
    print(symbols_list)
```
I got same **RequestTimeout** error.
```
Internal Server Error: /refresh_orders/
Traceback (most recent call last):
  File "G:\env\Mipha\lib\site-packages\ccxt-1.50.34-py3.9.egg\ccxt\async_support\base\exchange.py", line 117, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "G:\env\Mipha\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "G:\env\Mipha\lib\site-packages\aiohttp\client.py", line 619, in _request
    break
  File "G:\env\Mipha\lib\site-packages\aiohttp\helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "G:\env\Mipha\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "G:\env\Mipha\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\weiyun\dev\PycharmProjects\Mipha\Mario\views.py", line 15, in refresh_orders
    orders_list = binance_entry()
  File "G:\weiyun\dev\PycharmProjects\Mipha\Mario\binance.py", line 59, in binance_entry
    loop.run_until_complete(binance_runner(apikey))
  File "C:\Users\X-Mars\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "G:\weiyun\dev\PycharmProjects\Mipha\Mario\binance.py", line 28, in binance_runner
    symbols_list = await binance.sapiGetCapitalConfigGetall()
  File "G:\env\Mipha\lib\site-packages\ccxt-1.50.34-py3.9.egg\ccxt\async_support\binance.py", line 2930, in request
    response = await self.fetch2(path, api, method, params, headers, body)
  File "G:\env\Mipha\lib\site-packages\ccxt-1.50.34-py3.9.egg\ccxt\async_support\base\exchange.py", line 96, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "G:\env\Mipha\lib\site-packages\ccxt-1.50.34-py3.9.egg\ccxt\async_support\base\exchange.py", line 151, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1622033777479&recvWindow=5000&signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[26/May/2021 20:56:28] "GET /refresh_orders/ HTTP/1.1" 500 133456
```

**Comment by kroitor** [comment]
@X-Mars does my snippet above work for you, though?

**Comment by kroitor** [comment]
@X-Mars sure, no problem, we will keep it open, waiting for an update from you.

**Comment by X-Mars** [comment]
It's workering better in my new computer.
Something wrong with my network.
I'll close this issue.
Thanks for your job.
Best wish for you.

**Comment by kroitor** [comment]
@X-Mars thx for reporting back!
