### ISSUE TITLE
How add 'api url' to ccxt by python.

### ISSUE THREAD

**Issue by X-Mars** [ccxt/ccxt#9282]
Hi .
Sometime I want add 'new api url' to ccxt by python.
I can edit exchange file (like Binance.py) to support it.
Do you have anyidea like this

```python
from ccxt import binance

binance.add_url('private/api/order/orders')
binance.privateApiOrderOrders(params)
```
Thx for your job.

- OS: macOS Biig Sur
- Programming Language version: python 3.9
- CCXT version: 1.50.64

**Comment by X-Mars** [comment]
Can **define_rest_api**  do it ?

```python
import json

import ccxt

okex5 = ccxt.okex5()
print(okex5.api)
okex5.define_rest_api(api='https://www.okex.com/api/v5', method_name='publicGetPublicUnderlying', paths='public/underlying')
```

```error
Traceback (most recent call last):
  File "G:/weiyun/dev/PycharmProjects/ccxt/python/main.py", line 5, in <module>
    ccxt.okex5.define_rest_api(api='https://www.okex.com/api/v5', method_name='publicGetPublicUnderlying', paths='public/underlying')
  File "G:\weiyun\dev\PycharmProjects\ccxt\python\ccxt\base\exchange.py", line 422, in define_rest_api
    entry = getattr(cls, method_name)  # returns a function (instead of a bound method)
AttributeError: type object 'okex5' has no attribute 'publicGetPublicUnderlying'
```

**Comment by X-Mars** [comment]
It's working now !
Theee is codes.
```python
import json
import ccxt

okex5 = ccxt.okex5()
okex5.api['public']['get'].append('public/underlying')
new_api = okex5.api.copy()
print(new_api)
okex5.define_rest_api(api=new_api, method_name='request', paths=[])
a = okex5.publicGetPublicUnderlying({'instType': 'SWAP'})
print(json.dumps(a))
```

```log
{"code": "0", "data": [["MANA-USDT", "CHZ-USDT", "EOS-USD", "DOT-USDT", "KNC-USD", "KNC-USDT", "EOS-USDT", "XTZ-USDT", "MIR-USDT", "KSM-USD", "CVC-USDT", "LUNA-USDT", "GRT-USDT", "GRT-USD", "XRP-USD", "LTC-USD", "RVN-USDT", "XEM-USDT", "IOST-USDT", "REN-USDT", "ANC-USDT", "IOTA-USDT", "KSM-USDT", "ATOM-USD", "ONT-USD", "ICP-USDT", "IOST-USD", "ETH-USDT", "BTT-USD", "STORJ-USDT", "THETA-USD", "QTUM-USDT", "1INCH-USD", "BSV-USDT", "CSPR-USDT", "BTC-USDT", "XMR-USDT", "FIL-USD", "CONV-USDT", "ZEN-USDT", "UNI-USD", "OMG-USDT", "ETC-USDT", "XLM-USD", "BADGER-USDT", "DORA-USDT", "SUN-USD", "DASH-USD", "FTM-USDT", "BCH-USDT", "BAL-USDT", "ZIL-USDT", "CRV-USD", "ETH-USD", "COMP-USDT", "SWRV-USDT", "ALGO-USDT", "WAVES-USDT", "YFI-USD", "DOT-USD", "TRX-USDT", "YFII-USD", "BSV-USD", "LRC-USDT", "XTZ-USD", "DASH-USDT", "SAND-USDT", "LAT-USDT", "ADA-USDT", "BCH-USD", "ALPHA-USDT", "SHIB-USDT", "SUN-USDT", "ENJ-USDT", "CRO-USDT", "FLM-USDT", "CFX-USDT", "SRM-USDT", "SOL-USDT", "ZRX-USDT", "YFI-USDT", "TESTE-USD", "SC-USDT", "UNI-USDT", "XCH-USDT", "FIL-USDT", "SUSHI-USD", "RSR-USDT", "BTM-USDT", "DOGE-USD", "JST-USDT", "ETC-USD", "AAVE-USDT", "TORN-USDT", "1INCH-USDT", "PERP-USDT", "LON-USDT", "BTC-USD", "XMR-USD", "TRB-USDT", "MATIC-USDT", "DOGE-USDT", "YFII-USDT", "ONT-USDT", "THETA-USDT", "NEAR-USDT", "QTUM-USD", "ADA-USD", "ANT-USDT", "NEO-USD", "UMA-USDT", "LINK-USD", "WNXM-USDT", "XRP-USDT", "BTT-USDT", "ZEC-USDT", "LPT-USDT", "TRX-USD", "SUSHI-USDT", "MKR-USDT", "LTC-USDT", "ZEC-USD", "CRV-USDT", "BAND-USDT", "AVAX-USDT", "XLM-USDT", "SNX-USDT", "LINK-USDT", "MASK-USDT", "EGLD-USDT", "IOTA-USD", "ALGO-USD", "NEO-USDT", "ATOM-USDT", "BAT-USDT", "BNT-USDT"]], "msg": ""}

```

Thx for your  job.
Clossing this issue.

**Comment by kroitor** [comment]
@X-Mars thx for reporting back!
