### ISSUE TITLE
Isn't `Pipenv` supported?

### ISSUE THREAD

**Issue by bambrozio** [ccxt/ccxt#9292]
Hi,
Isn't `Pipenv` supported?

I'm trying: `pipenv install ccxt` but no success. Check it out:

> Note 1: I already have `libffi--3.3_3.big_sur.bottle.tar.gz` installed on my Mac.
> Note 2: I managed to install `ccxt` in a conda environment, but I want to use `pipenv` instead.

```
$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.9"
```

```
Copying cffi.egg-info to build/bdist.macosx-11-x86_64/wheel/cffi-1.14.5-py3.9.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/py/sj4b7y1d3m7_4566n57shb040000gn/T/pip-wheel-ojxjnhxj/cffi/setup.py", line 175, in <module>
          setup(
        File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 328, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
        File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 252, in get_tag
          plat_name = get_platform(self.bdist_dir)
        File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 48, in get_platform
          result = calculate_macosx_platform_tag(archive_root, result)
        File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 356, in calculate_macosx_platform_tag
          assert len(base_version) == 2
      AssertionError
      ----------------------------------------
      ERROR: Failed building wheel for cffi
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/py/sj4b7y1d3m7_4566n57shb040000gn/T/tmp_t09c6hf', '--quiet', 'cffi>=1.5.0']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/py/sj4b7y1d3m7_4566n57shb040000gn/T/pip-install-yvld_onz/pycares/setup.py", line 16, in <module>
        setup(name             = 'pycares',
      File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/pkg_resources/__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/Users/bambrozi/.local/share/virtualenvs/cambio-qHg9sz3o/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/py/sj4b7y1d3m7_4566n57shb040000gn/T/tmp_t09c6hf', '--quiet', 'cffi>=1.5.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This is likely caused by a bug in ccxt. Report this to its maintainers.
✘ Installation Failed 
```

**Comment by peedrr** [comment]
I can confirm that ccxt is working with Pipenv on both mac and ubuntu.

One thought though: [installing Pipenv via homebrew is discouraged](https://pipenv.pypa.io/en/latest/install/#homebrew-installation-of-pipenv-discouraged) by the authors of Pipenv. If this was your method, maybe try installing Pipenv with pip instead.

**Comment by ttodua** [comment]
I assume above reply was the answer for the issue. If anyone has any issues with CCXT, let us know.
