### ISSUE TITLE
BadRequest: binanceus {"code":-1100,"msg":"Illegal characters found in a parameter."}

### ISSUE THREAD

**Issue by smallham1** [ccxt/ccxt#9320]
I am trying to use the withdraw feature for binance and get the following an error regarding illegal characters. 
OS: Windows 10
Programming Language version: Python 3.9
CCXT version: 1.50.84
Code:

from pprint import pprint

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

def get_positive_accounts(balance):
    result = {}
    currencies = list(balance.keys())
    for currency in currencies:
        if balance[currency] and balance[currency] > 0:
            result[currency] = balance[currency]
    return result

exchange = ccxt.binanceus({
    'apiKey': '***',
    'secret': '***',
    'enableRateLimit': True,
    "verbose" : True,
    'has' : {'fetchWithdrawals': True,'withdraw': True}
})

trading_balance = exchange.fetch_balance()
account_balance = exchange.fetch_balance({'type': 'account'})

pprint('Trading balance:')
pprint(get_positive_accounts(trading_balance['total']))
pprint('Account balance:')
pprint(get_positive_accounts(account_balance['total']))

code1 = 'XLM'
amount1 = 30
address1 = 'GB3RMPTL47E4ULVANHBNCXSXM2ZA5JFY5ISDRERPCXNJUDEO73QFZUNK'
addressTag1 = '2916292059745568'

print(exchange.requiredCredentials)  # prints required credentials
exchange.checkRequiredCredentials()  # raises AuthenticationError

depositaddy = exchange.fetch_deposit_address('XLM')

print(depositaddy)
withdraw1 = exchange.withdraw(code1, amount1, address1, addressTag1)

pprint('Withdraw:')
pprint(withdraw1)

returns:

Traceback (most recent call last):
File "C:\Users\Harry\PycharmProjects\ArbitrageCAlc\venv\lib\site-packages\ccxt\base\exchange.py", line 593, in fetch
response.raise_for_status()
File "C:\Users\Harry\PycharmProjects\ArbitrageCAlc\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: for url: https://api.binance.us/sapi/v1/capital/withdraw/apply

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Harry\PycharmProjects\ArbitrageCAlc\okex.py", line 52, in
withdraw1 = exchange.withdraw(code1, amount1, address1, addressTag1)
File "C:\Users\Harry\PycharmProjects\ArbitrageCAlc\venv\lib\site-packages\ccxt\binance.py", line 2811, in withdraw
response = self.sapiPostCapitalWithdrawApply(self.extend(request, params))
File "C:\Users\Harry\PycharmProjects\ArbitrageCAlc\venv\lib\site-packages\ccxt\base\exchange.py", line 461, in inner
return entry(_self, **inner_kwargs)
File "C:\Users\Harry\PycharmProjects\ArbitrageCAlc\venv\lib\site-packages\ccxt\binance.py", line 3433, in request
response = self.fetch2(path, api, method, params, headers, body)
File "C:\Users\Harry\PycharmProjects\ArbitrageCAlc\venv\lib\site-packages\ccxt\base\exchange.py", line 482, in fetch2
return self.fetch(request['url'], request['method'], request['headers'], request['body'])
File "C:\Users\Harry\PycharmProjects\ArbitrageCAlc\venv\lib\site-packages\ccxt\base\exchange.py", line 609, in fetch
self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
File "C:\Users\Harry\PycharmProjects\ArbitrageCAlc\venv\lib\site-packages\ccxt\binance.py", line 3427, in handle_errors
self.throw_exactly_matched_exception(self.exceptions, error, feedback)
File "C:\Users\Harry\PycharmProjects\ArbitrageCAlc\venv\lib\site-packages\ccxt\base\exchange.py", line 500, in throw_exactly_matched_exception
raise exactstring
ccxt.base.errors.BadRequest: binanceus {"code":-1100,"msg":"Illegal characters found in a parameter."}

**Comment by kroitor** [comment]
Dupliate: https://github.com/ccxt/ccxt/issues/9308
