### ISSUE TITLE
Unable to fetch tickers from coinmarketcap

### ISSUE THREAD

**Issue by AlgoQ** [ccxt/ccxt#9360]
Unable to fetch tickers from coinmarketcap.

Code:
```python
import ccxt

cmc = ccxt.coinmarketcap()
print(cmc.fetch_tickers())
```

Traceback:
```
Traceback (most recent call last):
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 593, in fetch
    response.raise_for_status()
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://api.coinmarketcap.com/v1/ticker/?limit=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\trabro2\test\fetchTickersCmc.py", line 4, in <module>
    print(cmc.fetch_tickers())
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\coinmarketcap.py", line 238, in fetch_tickers
    self.load_markets()
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 1364, in load_markets
    currencies = self.fetch_currencies()
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\coinmarketcap.py", line 273, in fetch_currencies
    response = self.publicGetTicker(self.extend(request, params))
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\coinmarketcap.py", line 321, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 610, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 646, in handle_http_status_code
    raise Exception(' '.join([self.id, method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: coinmarketcap GET https://api.coinmarketcap.com/v1/ticker/?limit=0 503 Service Temporarily Unavailable <!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}
    p, .attribution, {text-align: center;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 32px;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }
    a:hover{color: #f4a15d}
    .attribution{font-size: 16px; line-height: 1.5;}
    .ray_id{display: block; margin-top: 8px;}
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
  </style>

      <meta http-equiv="refresh" content="12">
  <script type="text/javascript">
    //<![CDATA[
    (function(){

      window._cf_chl_opt={
        cvId: "2",
        cType: "non-interactive",
        cNounce: "98240",
        cRay: "65dbaf4ecae6d4b4",
        cHash: "0903b9c149973d7",
        cFPWv: "g",
        cTTimeMs: "4000",
        cRq: {
          ru: "aHR0cHM6Ly9hcGkuY29pbm1hcmtldGNhcC5jb20vdjEvdGlja2VyLz9saW1pdD0w",
          ra: "cHl0aG9uLXJlcXVlc3RzLzIuMjUuMQ==",
          rm: "R0VU",
          d: "lr/ttSM6fvf6Zu2XfrQ4xqFvSH4UmI6/+YrXqkain6YBJVaT0DDdcsmjSY0YpchfICbRDjlZuKw0oLV7ta8gtavCoEFHDjUsIlPBy0XX1CzH4wElrpQpmGoDcy6bC47AsuldSVGzOrq9UyO864KQ9JJdSaSYX+rUxCeaiGJtFbrQ2ddYFTJMHeKv9UBY1BBoii8rAUC5RTFDGYKGSLobNf70vISrDdPzUjGF1+TGGRiccfxyWf+tdBfRCR4+9X6By9x0x+RazBFJ33wd0fDiwrMp3TRH08nrHTk95b3TUoiRWm7Hpix1XeygUVXtDbcxcLWmGqu+2MvnquS9AknQTjIOFTQnYAJ3+FCrIzm0ZpwwWHtk04u5Nkagaz4IYrF9gRJtA57jDY8nnufpEtE7ZxTdCqfhJhCveMFIeyHoK+fTX29vfswbJgUkWiwHIxp0IjmHlWNHhy6xUWhMXevoM0mCQZL+iF954FNJDaOj18m+5iRWFWsOHW1hUunWLj2Wdi8ZFxJkQyFa9O4APHw1z13rUAMCPgTC+jQo8IDFvzMB/T74yzvdx638FPL62f6h4FZYpOch2qTxv5sr96e8wznZUF8ULaZhzeDzHnJxxHSmvzwYqmnHV/8XsJlr93CWMjQ3hOfxvUkUN/oXe0DOKIlK3oCOQKw9W5Ee/Pa6w/Z8kZic4EhjgYh+5aLsnvwV6eeakUUrHRq42rboV04scuOqSDsIwPSysfTi1eHqkG8=",
          t: "MTYyMzQyMzM3Mi42MjgwMDA=",
          m: "Ov1Rmt4RlY/CUqNNWlfSOZRXeHtDXLTjz3K54kXTVIk=",
          i1: "dWBwqR8tJym4ZfvDocIqMg==",
          i2: "R6NK3pti29saMTtwD0TitA==",
          zh: "nrzM7ZnEb3jNq0hJ2IE7JcyVzdy79MJ/53h//WD30LI=",
          uh: "5GU+jYv2xJ+bCaE/ARmi/DORbiS/v56CW7E0TH4XWQk=",
          hh: "AdryjcIGeH8eVeD8vPZimvbm4wwU0OaOtNmKmgjS5II=",
        }
      }
      window._cf_chl_enter = function(){window._cf_chl_opt.p=1};

    })();
    //]]>
  </script>


</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript>
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="cf-content" style="display:none">

    <div id="cf-bubbles">
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> coinmarketcap.com.</h1>

    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs" >Please allow up to 5 seconds&hellip;</p>
    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting&hellip;</p>
  </div>

  <form class="challenge-form" id="challenge-form" action="/v1/ticker/?limit=0&amp;__cf_chl_jschl_tk__=889b1d3660032e8d162848d0188c7d34ca3e2d0b-1623423372-0-AamzVHmDNyARI_DeZACZEwP5u1V45xrz2m8vvf9OVWDlV45e6Fwm6vCElVIeNTQR17KbMMiU5kHMQ-LiC7V-1eudVCkt5INDiKxswXcXj7m8kvDQ3VRKCi62UyUHIRsrTy4JBaXuJPVW6rnzalg0vhjqzI5oLh9KJXF9fDXJgkIye-BTP9H0bSoVI3H4kasSS7Za8-hGV7_GoBvy9S6wJ6vx9kQk1ZPM-dV0RsObINPFFdisiGFffbhxeiVVY5LW8TOXMth_oHgqCtWdhIOr9ariAbNklKWBcJ4ORfFR1tnh2ur8fwJtXyGYenMGHEmGJ6DdlIpd56KoHMXRlyF1H_RIb6b-d1537IFRV40Ch3ZPWYapO5IN5aKN9o3jGizW1mrE1UKYYgn72cKnZIFA7139G0MOR0UH9c38Rl3J6yah7ngdqX4zNe0O8dt3-o4cD2E_NGu4ZJdfg7EY5Mw5vocehMTxPKhQorc5AEZRbLcM" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="r" value="f939ba03f0907e8d7bbc570899b2d0327fed649d-1623423372-0-ATnWhpFWJZfXK6vxjwZRF8HUHNLH5l4nn9LcKw4xxBp5MH25RdRfcjodKT6UVKTHS3HKHhN7Nqfuxu+BmAGQbGc7WLrZZmFNy00Ud9/ymrxWHS2DRVfoUTwivP4hE8f1n4ATLGYU+Ex0tvM8FrFhZqA0PsBIMAEnINHnxAoXTVP7uDNY9M5jKzpg1VSPfAcuN8AJ9FreH3KxS7MGuqCjmA8kDm4pg3psko3u5CwY01HC0LW7ifWtTumP9hd3Mdgu+IuyUoX4LkUzc/cD6dprbXABX3wOOYW6qJrQGrXyGEnT4hm5g06u7vUh0VaieOFmTF07bx+0onmNSc2Thyttz4NW3IyQ7HHOXo18WohbNgcfzVgTnePxUSX40DsvBy40T+CZjPB0i8ldpkB9SdCXriQEcShR8ijBnk8jQcB6T6Xa9jD+Z6Rb4oNrAbRddq/3xSGYyS46ENAycLXEncW6cMqCVGQSHwzM+qEJugnqfTdRd01WarI/PkioiM92ZJUz+RBWETM2Drq2lcpPg8hlPxPNXN1CrRcQkSQRV/8xh9+suPRqtS7gCAfQUG0Qag2vrobxDTyWF2+g5m/Zl6aCOLfOo1lFsMIBTVckli1f8gexCtQ0zsvPPi7JmWCsiQ6rpviCEJ4iWyWbvXS2ciab5+hcaVAjxmSRwD3DaaTMbuiEbLOuf2dsS7/rVTN2VJ3gTFy44xQzvJy1/FIqXyW38zmymIdBjxQBnPTbhPfimhkNc0v61HwtHD7UCl0hWOrHFcPcNyRSQbbMkFG1oeH46vuLJQxJOSEtzMrK97uCrjXL1vNfqNj4ZgHkxmfiYggTI1yaMm5+Z5mM0BCIIJS9uNB/9BuHrcA6W/Ttb5fkZdN+9qX+bT3df20HobrHuaPP6LruQnj6Whx7yzdsMHV59i4xOXwJ9HczfwJDG4yh6yu5F+HDRUWRuWku/yJH3+xlOOmVtgSUwlTSzllkZOoy4X1Zu8yEA+AMMZLSrcaaM1aOk1Ff4vx6LbWz2PiCHSTdk1CqsprzBi0flhJu4IAAErCSeXIZCq4bRvHoayDYXDyXU8BzHtyBEzL8g+3yw2B8+IP/62kg/Zrr1TT+L+zpcFCFf9f4x/dtlNJroLqJpjLt6s5izgNZTDhvhcCi7CDGOhINxGK5SeDSW/8XRRi2IjwJViYhRTP6gtexQhgBdQn4ym5zVlKFp+450uZAGioefucucbO0N7Za6PW2e6WnnfaFYH+z9nBQM/3KmTduiLH3ih5rosohgDko3cd+tp5gclIlS0oA17JcLZzI19cGrg6DPjyQsGMTwIIypl+LjnElTEiJQA2KQ6IUTEr+kMwKOIFbzgzI0u+ehHbT3L3iKm3yUaMYZDnPSc3SuQrME9xUU4uKgCUMqi1AetfgqHhXlKTVfckpNVNwJeFlSuX5IOdWx3Rwyriby79NK/tX/D7KnV1w+TCbZ9J+3QO6WX7VCF7cREhU5x3GGOmn3OqQatWDn5/Z+IBddp5MKMnUMjUaiLuKhvh+MurodKgQuXDDrJ66fdQX8ZzmUgNwOI0YjvtzgXnL9nEQ9IdWrRft9ZvYAOLzsWXcrJpgGRXTpBdaHvo0yPSRDPGPnkDPhiVVuB0rv8DqBu97Gd5ZyNLokfk9/u1SQM1aoPLFT2mZaqOLwv4P77NJJi6jFCrYfNG4Lx+Ym46jqb973a/19s7zzfprFV99+QMTC8NoJnjLtk5UmFzgfy1/NUMametaTxCDIZEEEx0QM92CvITtXBcAr4xh"/>
    <input type="hidden" value="9abe8580952dc86a57622d97307003e1" id="jschl-vc" name="jschl_vc"/>
    <!-- <input type="hidden" value="" id="jschl-vc" name="jschl_vc"/> -->
    <input type="hidden" name="pass" value="1623423376.628-mRwiDCEAGL"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>

    <script type="text/javascript">
      //<![CDATA[
      (function(){
          var a = document.getElementById('cf-content');
          a.style.display = 'block';
          var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
          var trkjs = isIE ? new Image() : document.createElement('img');
          trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=65dbaf4ecae6d4b4");
          trkjs.id = "trk_jschal_js";
          trkjs.setAttribute("alt", "");
          document.body.appendChild(trkjs);
          var cpo=document.createElement('script');
          cpo.type='text/javascript';
          cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=65dbaf4ecae6d4b4";
          document.getElementsByTagName('head')[0].appendChild(cpo);
        }());
      //]]>
    </script>



  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=65dbaf4ecae6d4b4')"> </div>
</div>


          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br />
            <span class="ray_id">Ray ID: <code>65dbaf4ecae6d4b4</code></span>
          </div>
      </td>

    </tr>
  </table>
</body>
</html>
```

ccxt version: 1.51.2
system: windows 10
python version: 3.9.4

**Comment by kroitor** [comment]
CoinMarketCap has deprecated their free v1 API, and now their API is mostly paid:

- https://github.com/ccxt/ccxt/issues/6580
