### ISSUE TITLE
Quote Order Quantity Error 1104

### ISSUE THREAD

**Issue by Moustardd** [ccxt/ccxt#9428]
- OS: Ubuntu
- Programming Language version: Python 3.8
- CCXT version: Using binance

I am trying to buy EOS with all my available USDT, with the code below, but keep running into the same error. I have defined the variables inside the create_order function, and outside, to no avail. 

I followed #7963 as closely as I could but still getting the error.

I also realise that this is assuming I want to use all available USDT to trade with (fine for the timebeing). 

```
def buy_new():
    balance = float(client.get_asset_balance(asset="USDT").get("free"))

    order = client.create_order(
        symbol="EOSUSDT",
        side="BUY",
        type="MARKET",
        quantity=balance,
        price=None,
        params={"quoteOrderQty": balance}
    )
```

```
Traceback (most recent call last):
  File "/home/seb/PycharmProjects/Main_Trading/order_commands.py", line 74, in <module>
    buy_new()
  File "/home/seb/PycharmProjects/Main_Trading/order_commands.py", line 59, in buy_new
    order = client.create_order(
  File "/home/seb/PycharmProjects/Main_Trading/venv/lib/python3.8/site-packages/binance/client.py", line 1387, in create_order
    return self._post('order', True, data=params)
  File "/home/seb/PycharmProjects/Main_Trading/venv/lib/python3.8/site-packages/binance/client.py", line 374, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/seb/PycharmProjects/Main_Trading/venv/lib/python3.8/site-packages/binance/client.py", line 334, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/seb/PycharmProjects/Main_Trading/venv/lib/python3.8/site-packages/binance/client.py", line 315, in _request
    return self._handle_response(self.response)
  File "/home/seb/PycharmProjects/Main_Trading/venv/lib/python3.8/site-packages/binance/client.py", line 324, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1104): Not all sent parameters were read; read '6' parameter(s) but was sent '7'.

```
 

Any help is greatly apprecaited.

**Comment by frosty00** [comment]
@Moustardd try this instead:

```
def buy_new():
    balance = float(client.get_asset_balance(asset="USDT").get("free"))

    order = client.create_order(
        symbol="EOS/USDT",  # use the unified ccxt symbol here
        side="BUY",
        type="MARKET",
        quantity=None,  # change this line
        price=None,
        params={"quoteOrderQty": balance}
    )
 ```

**Comment by Moustardd** [comment]
@frosty00 

I added the / to the symbol and got an illegal symbol error, Im not using the ccxt library, just the python-binance library and api so Im guessing that would be why. 

I also changed the quantity to None and still running into the same issue as before, except 

`binance.exceptions.BinanceAPIException: APIError(code=-1104): Not all sent parameters were read; read '6' parameter(s) but was sent '7'.`

is now

`binance.exceptions.BinanceAPIException: APIError(code=-1104): Not all sent parameters were read; read '5' parameter(s) but was sent '6'.`
