### ISSUE TITLE
Binance ccxt.base.errors.BadRequest: binance {"code":-1101,"msg":"Too many parameters; expected '3' and received '4'."}

### ISSUE THREAD

**Issue by rafalsza** [ccxt/ccxt#9449]
- OS:Ubuntu
- Programming Language version:Python 3.9
- CCXT version:ccxt-1.51.98

Hi!
How can I fetch_balance for specific asset from binance and with response that contains only free balance?

```
exchange = ccxt.binance({
    "apiKey": config.BINANCE_API_KEY2,
    "secret": config.BINANCE_SECRET_KEY2,
    "timeout": 30000,
    'enableRateLimit': True
})


open = exchange.fetch_open_orders('ETH/USDT')
if not open:
       print("empty list")

balance = exchange.fetch_balance({'currency': 'ETH'})
print(balance)

```

response:
```
Traceback (most recent call last):
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\ccxt\base\exchange.py", line 593, in fetch
    response.raise_for_status()
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/account?timestamp=1624633797603&recvWindow=5000&currency=ETH&signature=8fa067452bb70226c19b6524fade684e3d8aa641f33d22b8bc0f0634beff2362

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\supertrend-crypto-bot-main\new2.py", line 17, in <module>
    balance = exchange.fetch_balance({'currency': 'ETH'})
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\ccxt\binance.py", line 1183, in fetch_balance
    response = getattr(self, method)(query)
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\ccxt\base\exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\ccxt\binance.py", line 3846, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\ccxt\base\exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\ccxt\base\exchange.py", line 609, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\ccxt\binance.py", line 3840, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "C:\supertrend-crypto-bot-main\venv\lib\site-packages\ccxt\base\exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1101,"msg":"Too many parameters; expected '3' and received '4'."}
```

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#account-balance

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    "apiKey": 'YOUR_API_KEY',
    "secret": 'YOUR_SECRET',
})

balance = exchange.fetch_balance()

print('----------------------------------')
print(balance['ETH'])

print('----------------------------------')
print(balance['ETH']['free'])

print('----------------------------------')
print(balance['free'])

print('----------------------------------')
print(balance['free']['ETH'])

print('==================================')
pprint(balance)
```
