### ISSUE TITLE
FTX Stop  order error - decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

### ISSUE THREAD

**Issue by nickpagz** [ccxt/ccxt#9455]
For the life of me I can't figure out why I can't set a stop loss order through FTX.com in this code snippet. My initial `base_order` (market order) executes just fine, and so does my `tp_order` (limit order). But my stop loss order keeps kicking out the error shown below. It looks like the ccxt library doesn't like the "amount" value (as `order_size`) I'm giving it, even though both the regular market and limit create orders execute just fine. 

I've tried several iterations of the `stop_order` format, from leaving out the "limit", putting the order_size in params, etc. Nothing works.

- OS:  MAC OS 10.15.7
- Programming Language version: Python 3.9.5
- CCXT version: 1.52.2

Code/function snippet:
```
def create_bull_order_set(pair, price):
    precision = len(price) - price.find('.') - 1
    order_size = round((float(config.ORDER_SIZE)/float(price)),4) #need a better way to adjust precision here for order size
    base_order = ftx.create_order(pair, "market", "buy", order_size)
    tp_price = round(float(price) + (float(price) * float(config.TAKE_PROFIT)), precision)
    stop_price = round(float(price) - (float(price) * float(config.STOP_LOSS)), precision)
    print(f'Order Size: {order_size}')
    print(f'Take Profit: {tp_price}')
    print(f'Stop Loss: {stop_price}')
    tp_order = ftx.create_order(pair, "limit", "sell", order_size, tp_price, {"reduceOnly": True})
    stop_order = ftx.create_order(pair, "limit", "sell", order_size, {"triggerPrice":stop_price, "type":"stop", "reduceOnly": True})
```
**pair** and **price** are passed as strings. For the sake of the last test, the pair was **PUNDIX-PERP**, and these values were used to create the orders:

```
Order Size: 12.8205
Take Profit: 0.83
Stop Loss: 0.76
```

```
Traceback (most recent call last):
  File "/Users/nickp/Documents/Python Volatility Bot/PyVol.py", line 131, in <module>
    orders_set = create_bull_order_set(highest_pair, highest_pair_value)
  File "/Users/nickp/Documents/Python Volatility Bot/PyVol.py", line 124, in create_bull_order_set
    stop_order = ftx.create_order(pair, "limit", "sell", order_size, {"triggerPrice":stop_price, "type":"stop", "reduceOnly": True})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/ftx.py", line 1121, in create_order
    request['price'] = float(self.price_to_precision(symbol, price))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1300, in price_to_precision
    return self.decimal_to_precision(price, ROUND, self.markets[symbol]['precision']['price'], self.precisionMode, self.paddingMode)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

PS. I noticed in the traceback it looks like your code is rounding/truncating based on the symbol/pair actual precision, which I was planning to later implement but using a rudimentary system for now, and hence I don't think I need to use any `round()` statements in my own code. Is that correct?

**Comment by nickpagz** [comment]
I've continued to play with this with further permutations of the stop order format, but still nothing. I stripped away all my code and manually set the orders, but still the same. What the heck am I doing wrong? Here's the full code, and the verbose output:

```
import ccxt
import time
import config

ftx = ccxt.ftx({
    'apiKey': config.API_KEY,
    'secret': config.SECRET_KEY,
    'headers': {'FTX-SUBACCOUNT': config.SUB_ACCOUNT}
})

ftx.verbose = True

base_order = ftx.create_order("PUNDIX-PERP", "market", "buy", 12.8)
print("Base Order:")
print(base_order)
tp_order = ftx.create_order("PUNDIX-PERP", "limit", "sell", 12.8, 0.8080, {"reduceOnly": True})
print("TP Order:")
print(tp_order)
stop_order = ftx.create_order("PUNDIX-PERP", 12.8, 0.756, {"market":"UNDIX-PERP","side":"sell","triggerPrice":0.7560, "size":12.8, "type":"stop", "reduceOnly": False})
print("Stop Order:")
print(stop_order)

```


Output:

```
Request: GET https://ftx.com/api/coins {'FTX-SUBACCOUNT': 'Python-Volatility', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://ftx.com/api/coins 200 {'Date': 'Sun, 27 Jun 2021 18:46:58 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding, Accept-Encoding, Origin', 'Cache-Control': 'public, max-age=15', 'ETag': 'W/"c163d793201ca448f6f1b234be9c13e6"', 'Content-Encoding': 'gzip', 'X-Cache-Status': 'EXPIRED', 'CF-Cache-Status': 'HIT', 'Age': '3', 'cf-request-id': '0af064e97d00006674c41c1000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '6660d7557faf6674-PTY', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400'} 

Request: GET https://ftx.com/api/markets {'FTX-SUBACCOUNT': 'Python-Volatility', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://ftx.com/api/markets 200 {'Date': 'Sun, 27 Jun 2021 18:46:58 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding, Accept-Encoding, Origin, Origin', 'Cache-Control': 'public, max-age=2', 'ETag': 'W/"0f19a761f4597ad2c74c821ccd2c0972"', 'Content-Encoding': 'gzip', 'X-Cache-Status': 'HIT', 'CF-Cache-Status': 'HIT', 'Age': '0', 'cf-request-id': '0af064ec8d00006674bdaab000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '6660d75a7d256674-PTY', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400'} 

Request: POST https://ftx.com/api/orders {'Content-Type': 'application/json', 'FTX-KEY': 'hidden', 'FTX-TS': '1624819621386', 'FTX-SIGN': '957471aecb13152a17869c239f24cdfea621f85186626a1e4de5e62ea6b57ebc', 'FTX-SUBACCOUNT': 'Python-Volatility', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} {"market":"PUNDIX-PERP","side":"buy","type":"market","size":12.8,"price":null}

Response: POST https://ftx.com/api/orders 200 {'Date': 'Sun, 27 Jun 2021 18:47:01 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding, Accept-Encoding, Origin', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': '30049596', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '0af064f6f200006674c0a66000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '6660d76b1c836674-PTY', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400'} {"success":true,"result":{"id":60564045945,"clientId":null,"market":"PUNDIX-PERP","type":"market","side":"buy","price":null,"size":12.8,"status":"new","filledSize":0.0,"remainingSize":12.8,"reduceOnly":false,"liquidation":null,"avgFillPrice":null,"postOnly":false,"ioc":true,"createdAt":"2021-06-27T18:47:01.806461+00:00","future":"PUNDIX-PERP"}}
Base Order:
{'info': {'id': '60564045945', 'clientId': None, 'market': 'PUNDIX-PERP', 'type': 'market', 'side': 'buy', 'price': None, 'size': '12.8', 'status': 'new', 'filledSize': '0.0', 'remainingSize': '12.8', 'reduceOnly': False, 'liquidation': None, 'avgFillPrice': None, 'postOnly': False, 'ioc': True, 'createdAt': '2021-06-27T18:47:01.806461+00:00', 'future': 'PUNDIX-PERP'}, 'id': '60564045945', 'clientOrderId': None, 'timestamp': 1624819621806, 'datetime': '2021-06-27T18:47:01.806Z', 'lastTradeTimestamp': None, 'symbol': 'PUNDIX-PERP', 'type': 'market', 'timeInForce': None, 'postOnly': False, 'side': 'buy', 'price': None, 'stopPrice': None, 'amount': 12.8, 'cost': None, 'average': None, 'filled': 0.0, 'remaining': 12.8, 'status': 'open', 'fee': None, 'trades': None}

Request: POST https://ftx.com/api/orders {'Content-Type': 'application/json', 'FTX-KEY': 'hidden', 'FTX-TS': '1624819622402', 'FTX-SIGN': 'bd11066baecc7d38a71ee3aeb33e2484490f61cf3d41a1fb2c453f8ab2357d56', 'FTX-SUBACCOUNT': 'Python-Volatility', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} {"market":"PUNDIX-PERP","side":"sell","type":"limit","size":12.8,"price":0.808,"reduceOnly":true}

Response: POST https://ftx.com/api/orders 200 {'Date': 'Sun, 27 Jun 2021 18:47:04 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding, Accept-Encoding, Origin', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': '30049596', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '0af064fe5b00006674bd823000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '6660d776ffc06674-PTY', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400'} {"success":true,"result":{"id":60564051124,"clientId":null,"market":"PUNDIX-PERP","type":"limit","side":"sell","price":0.808,"size":12.8,"status":"new","filledSize":0.0,"remainingSize":12.8,"reduceOnly":true,"liquidation":null,"avgFillPrice":null,"postOnly":false,"ioc":false,"createdAt":"2021-06-27T18:47:03.904945+00:00","future":"PUNDIX-PERP"}}
TP Order:
{'info': {'id': '60564051124', 'clientId': None, 'market': 'PUNDIX-PERP', 'type': 'limit', 'side': 'sell', 'price': '0.808', 'size': '12.8', 'status': 'new', 'filledSize': '0.0', 'remainingSize': '12.8', 'reduceOnly': True, 'liquidation': None, 'avgFillPrice': None, 'postOnly': False, 'ioc': False, 'createdAt': '2021-06-27T18:47:03.904945+00:00', 'future': 'PUNDIX-PERP'}, 'id': '60564051124', 'clientOrderId': None, 'timestamp': 1624819623904, 'datetime': '2021-06-27T18:47:03.904Z', 'lastTradeTimestamp': None, 'symbol': 'PUNDIX-PERP', 'type': 'limit', 'timeInForce': None, 'postOnly': False, 'side': 'sell', 'price': 0.808, 'stopPrice': None, 'amount': 12.8, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 12.8, 'status': 'open', 'fee': None, 'trades': None}
```

Traceback:
```
Traceback (most recent call last):
  File "/Users/nickp/Documents/Python Volatility Bot/PyVoltest.py", line 145, in <module>
    stop_order = ftx.create_order("PUNDIX-PERP", 12.8, 0.756, {"market":"UNDIX-PERP","side":"sell","triggerPrice":0.7560, "size":12.8, "type":"stop", "reduceOnly": False})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/ftx.py", line 1108, in create_order
    'size': float(self.amount_to_precision(symbol, amount)),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1303, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode, self.paddingMode)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by kroitor** [comment]
You must specify all arguments for the `create_order` call to work:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

```Python
type = 'stop'
side = 'sell'
stop_order = ftx.create_order("PUNDIX-PERP", 'stop', 'sell', 12.8, 0.756, {"triggerPrice":0.7560})
print("Stop Order:")
print(stop_order)
```
Let us know if that does not answer your question.

**Comment by nickpagz** [comment]
Aha! So it was me ;-) (it works now, thanks!)

Ok, but the documentation on this is a bit confusing. It reads only `market` and `limit` types, [here](https://github.com/ccxt/ccxt/wiki/Manual#other-order-types). Based on that, `'stop'` is not a permissible type and had to be in the [params overrides](https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params) section of the `create_order`. Or did I mis-read how that works?

In any case, thanks for the quick help. This was a show stopper, but working now!

**Comment by kroitor** [comment]
@nickpagz you're right on the docs – we will have to update the docs. Thanks for pointing it out! Basically, order types other than `limit` and `market` are not unified but may still be supported with this or that exchange (it's a work in progress). Some exchanges may support that via params, others may support a `stop` order type, there may be other exchange-specific cases as well. The easiest way to figure that at this time is to go straight to the `create_order` source for the exchange in question: https://github.com/ccxt/ccxt/blob/master/python/ccxt/ftx.py#L1125 We will add more to the docs and to the unification of order types. Your help and PRs are very much appreciated!

**Comment by nickpagz** [comment]
@kroitor I did have a secondary question in my OP, but it was easy to miss. 

```
PS. I noticed in the traceback it looks like your code is rounding/truncating based on the symbol/pair actual precision, which I was planning to later implement but using a rudimentary system for now, and hence I don't think I need to use any round() statements in my own code. Is that correct?
```

Is it fair to say ccxt handles the rounding/truncating? It looks like the line `File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1303, in amount_to_precision return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode, self.paddingMode)` is grabbing the minimum trade amount and step value from ftx and making the adjustments in the submitted order?

**Comment by kroitor** [comment]
@nickpagz 

> Is it fair to say ccxt handles the rounding/truncating?

Amounts are truncated, prices are rounded to precision of the exchange. But it will not do other adjustments. Suppose the market amount precision is 3, and your amount is 0.000987654321 – that will be truncated down to 0.000 (3 decimals). If your amounts truncates to 0 with exchange-specific precision, CCXT will send the zero as is. Hope that answers your question:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals

**Comment by nickpagz** [comment]
It does, thank you!

**Comment by nickpagz** [comment]
@kroitor Sorry, I have one more question, I'm struggling to create a market stop order. 
Based on what you showed [above](https://github.com/ccxt/ccxt/issues/9455#issuecomment-869210257):
`stop_order = ftx.create_order("PUNDIX-PERP", 'stop', 'sell', 12.8, 0.756, {"triggerPrice":0.7560})`
...this creates a limit stop order, based on the [info provided by ftx](https://docs.ftx.com/?python#place-trigger-order), since we're providing both a trigger and order price. I tried to go through the [code](https://github.com/ccxt/ccxt/blob/2df9dc77e761a2d7025d28c651455a6ba0e75fa8/python/ccxt/ftx.py#L1126), but it wasn't clear on how to create just a market stop.
I tried both `stop_order = ftx.create_order("PUNDIX-PERP", 'stop', 'sell', 12.8, {"triggerPrice":0.7560})` and `stop_order = ftx.create_order("PUNDIX-PERP", 'stop', 'sell', 12.8, 0.756`, hoping it would work, but in all cases I get [the error](https://github.com/ccxt/ccxt/blob/2df9dc77e761a2d7025d28c651455a6ba0e75fa8/python/ccxt/ftx.py#L1130) `ccxt.base.errors.ArgumentsRequired: ftx createOrder() requires a stopPrice parameter or a triggerPrice parameter for stop orders`.

Any thoughts on how to get a trigger order that is a market sell, instead of a limit sell?

**Comment by kroitor** [comment]
@nickpagz for market-stops you should not skip the price argument, just set it to None:

```Python
symbol = 'PUNDIX-PERP'
type = 'stop'
side = 'sell'
amount = 12.8
price = None  # --------------------------------------------+
params = {"triggerPrice":0.7560}  #                         V
stop_order = ftx.create_order(symbol, type, side, amount, price, params)
```

**Comment by nickpagz** [comment]
Thank you!
