### ISSUE TITLE
Cannot place MARKET order with CoinbasePro

### ISSUE THREAD

**Issue by nghovi** [ccxt/ccxt#9478]
I can place LIMIT order with my apikey/secret but cannot do it with MARKET order. It shows coinbasepro Limit only mode. Is there anything wrong with my coinbasepro acc or apikey/secret ?

- OS: MAC
- Programming Language version: PHP 7.4
- CCXT version: 1.52

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
 coinbasepro Limit only mode  #0 /Users/vietnguyen/projects/cryptohero-server/vendor/ccxt/ccxt/php/Exchange.php(1626): ccxt\coinbasepro->handle_errors(400, NULL, 'https://api.pro...', 'POST', Array, '{"message":"Lim...', Array, Array, '{"type":"market...')
#1 /Users/vietnguyen/projects/cryptohero-server/vendor/ccxt/ccxt/php/Exchange.php(1382): ccxt\Exchange->fetch('https://api.pro...', 'POST', Array, '{"type":"market...')
#2 /Users/vietnguyen/projects/cryptohero-server/vendor/ccxt/ccxt/php/coinbasepro.php(1199): ccxt\Exchange->fetch2('orders', 'private', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\coinbasepro->request('orders', 'private', 'POST', Array)
#4 /Users/vietnguyen/projects/cryptohero-server/vendor/ccxt/ccxt/php/Exchange.php(2492): call_user_func_array(Array, Array)
#5 /Users/vietnguyen/projects/cryptohero-server/vendor/ccxt/ccxt/php/coinbasepro.php(891): ccxt\Exchange->__call('privatePostOrde...', Array)
```

**Comment by kroitor** [comment]
@nghovi please, paste your code and your verbose output without your keys: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
