### ISSUE TITLE
Question: When posting COIN-M position -> can't recognize assets. Cross Balance insufficient

### ISSUE THREAD

**Issue by Salz0** [ccxt/ccxt#9502]
- OS: W10
- Programming Language version: python 3.9.2
- CCXT version: '1.52.35'

executed an order for BTCUSD_PERP.

My balance is 
```py
("~~~~~~~~!~~~~~~~~ TOTAL ~{'BTC': 0.0007551, 'ADA': 0.0, 'LINK': 0.0, 'DOGE': "
 "0.0, 'ETH': 0.0, 'BNB': 0.0, 'TRX': 0.0, 'DOT': 0.0, 'UNI': 0.0, 'THETA': "
 "0.0, 'EOS': 0.0, 'XLM': 0.0, 'LTC': 0.0, 'BCH': 0.0, 'XRP': 0.0, 'ETC': 0.0, "
 "'FIL': 0.0, 'EGLD': 0.0}~ ~~~~~~~~!~~~~~~~~")
```

MY settings (Isolated for BTC_PERP, x5 leverage)
```py
ADAUSD_211231  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 250000  | cross    | 0.00000000 | false | BOTH | 0 | 0
EOSUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 30000   | cross    | 0.00000000 | false | BOTH | 0 | 0
LTCUSD_210924  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 2500    | cross    | 0.00000000 | false | BOTH | 0 | 0
FILUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 5000    | cross    | 0.00000000 | false | BOTH | 0 | 0
LTCUSD_211231  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 2500    | cross    | 0.00000000 | false | BOTH | 0 | 0
XRPUSD_210924  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 500000  | cross    | 0.00000000 | false | BOTH | 0 | 0
THETAUSD_PERP  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 10000   | cross    | 0.00000000 | false | BOTH | 0 | 0
BCHUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 500     | cross    | 0.00000000 | false | BOTH | 0 | 0
LINKUSD_PERP   | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 10000   | cross    | 0.00000000 | false | BOTH | 0 | 0
BTCUSD_PERP    | 0 | 0.00000000 | 35518.71980960 | 0.00000000 | 0 | 5  | 200     | isolated | 0.00000000 | false | BOTH | 0 | 0
XLMUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 200000  | cross    | 0.00000000 | false | BOTH | 0 | 0
BCHUSD_211231  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 500     | cross    | 0.00000000 | false | BOTH | 0 | 0
ETCUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 25000   | cross    | 0.00000000 | false | BOTH | 0 | 0
UNIUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 10000   | cross    | 0.00000000 | false | BOTH | 0 | 0
XRPUSD_211231  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 500000  | cross    | 0.00000000 | false | BOTH | 0 | 0
XRPUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 500000  | cross    | 0.00000000 | false | BOTH | 0 | 0
EGLDUSD_PERP   | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 500     | cross    | 0.00000000 | false | BOTH | 0 | 0
LTCUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 2500    | cross    | 0.00000000 | false | BOTH | 0 | 0
BNBUSD_211231  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 1000    | cross    | 0.00000000 | false | BOTH | 0 | 0
DOTUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 25000   | cross    | 0.00000000 | false | BOTH | 0 | 0
ETHUSD_210924  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 250     | cross    | 0.00000000 | false | BOTH | 0 | 0
ETHUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 500     | cross    | 0.00000000 | false | BOTH | 0 | 0
ETHUSD_211231  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 250     | cross    | 0.00000000 | false | BOTH | 0 | 0
ADAUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 250000  | cross    | 0.00000000 | false | BOTH | 0 | 0
BCHUSD_210924  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 500     | cross    | 0.00000000 | false | BOTH | 0 | 0
BTCUSD_210924  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 30      | cross    | 0.00000000 | false | BOTH | 0 | 0
BNBUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 2000    | cross    | 0.00000000 | false | BOTH | 0 | 0
TRXUSD_PERP    | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 5000000 | cross    | 0.00000000 | false | BOTH | 0 | 0
ADAUSD_210924  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 250000  | cross    | 0.00000000 | false | BOTH | 0 | 0
LINKUSD_211231 | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 10000   | cross    | 0.00000000 | false | BOTH | 0 | 0
DOGEUSD_PERP   | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 2500000 | cross    | 0.00000000 | false | BOTH | 0 | 0
BTCUSD_211231  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 30      | cross    | 0.00000000 | false | BOTH | 0 | 0
DOTUSD_210924  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 25000   | cross    | 0.00000000 | false | BOTH | 0 | 0
BNBUSD_210924  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 1000    | cross    | 0.00000000 | false | BOTH | 0 | 0
DOTUSD_211231  | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 25000   | cross    | 0.00000000 | false | BOTH | 0 | 0
LINKUSD_210924 | 0 | 0.00000000 | 0.00000000     | 0.00000000 | 0 | 20 | 10000   | cross    | 0.00000000 | false | BOTH | 0 | 0
```
{'symbol': 'BTCUSD_PERP', 'amount': 3, 'positionSide': 'BOTH', 'type': 1}

```py
market = exchange.market('BTC/USD')
await self.account.exchange.dapiPrivate_post_positionmargin({  # noqa: unresolved
                                'symbol': market['id'],
                                'amount': 3,
                                'positionSide': _positionSide, # BOTH for One-way positions, LONG/SHORT for Hedge Mode # noqa
                                'type': _side,  # 1 = add position margin, 2 = reduce position margin # noqa
})


Traceback (most recent call last):

  File "C:\Users\korol\PycharmProjects\TS\curly-barnacle\app.py", line 382, in <module>
    uvicorn.run(app, host="0.0.0.0", port=8000)  # noqa: expectation
    │       │   └ <fastapi.applications.FastAPI object at 0x000002E955C3DD30>
    │       └ <function run at 0x000002E957D0A820>
    └ <module 'uvicorn' from 'C:\\Users\\korol\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\ts-bot-4iVuk_MM-py3.9\\lib\\site-pack...

  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\uvicorn\main.py", line 393, in run
    server.run()
    │      └ <function Server.run at 0x000002E957D0ACA0>
    └ <uvicorn.server.Server object at 0x000002E9573BBB50>

  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\uvicorn\server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x000002E957D0AD30>
    │    │                  └ <uvicorn.server.Server object at 0x000002E9573BBB50>
    │    └ <function BaseEventLoop.run_until_complete at 0x000002E955B78280>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\korol\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x000002E955B781F0>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\korol\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002E955B79D30>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "C:\Users\korol\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002E955B0D940>
    └ <Handle <TaskWakeupMethWrapper object at 0x000002E9582D10A0>(<Future finished result=None>)>

  File "C:\Users\korol\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x000002E9582D10A0>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x000002E9582D10A0>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x000002E9582D10A0>(<Future finished result=None>)>

  File "C:\Users\korol\PycharmProjects\TS\curly-barnacle\app.py", line 376, in assembled_order
    return await _order.orderAssembler()
                 │      └ <function Order.orderAssembler at 0x000002E9581BAEE0>
                 └ <wallet.Order object at 0x000002E9582D11F0>

> File "C:\Users\korol\PycharmProjects\TS\curly-barnacle\wallet.py", line 396, in orderAssembler
    response = await self.account.exchange.dapiPrivate_post_positionmargin({  # noqa: unresolved
                     │    │       │        └ <function binance.request at 0x000002E958E62430>
                     │    │       └ ccxt.async_support.binancecoinm()
                     │    └ <wallet.BinanceAccount object at 0x000002E958291940>
                     └ <wallet.Order object at 0x000002E9582D11F0>

  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\ccxt\async_support\binance.py", line 3858, in request
    response = await self.fetch2(path, api, method, params, headers, body)
                     │    │      │     │    │       │       │        └ None
                     │    │      │     │    │       │       └ None
                     │    │      │     │    │       └ {'symbol': 'BTCUSD_PERP', 'amount': 3, 'positionSide': 'BOTH', 'type': 1}
                     │    │      │     │    └ 'POST'
                     │    │      │     └ 'dapiPrivate'
                     │    │      └ 'positionMargin'
                     │    └ <function Exchange.fetch2 at 0x000002E956FA2790>
                     └ ccxt.async_support.binancecoinm()

  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\ccxt\async_support\base\exchange.py", line 96, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
                 │    │     │               │                  │                   └ {'url': 'https://dapi.binance.com/dapi/v1/positionMargin', 'method': 'POST', 'body': 'timestamp=1625388997540&recvWindow=5000...
                 │    │     │               │                  └ {'url': 'https://dapi.binance.com/dapi/v1/positionMargin', 'method': 'POST', 'body': 'timestamp=1625388997540&recvWindow=5000...
                 │    │     │               └ {'url': 'https://dapi.binance.com/dapi/v1/positionMargin', 'method': 'POST', 'body': 'timestamp=1625388997540&recvWindow=5000...
                 │    │     └ {'url': 'https://dapi.binance.com/dapi/v1/positionMargin', 'method': 'POST', 'body': 'timestamp=1625388997540&recvWindow=5000...
                 │    └ <function Exchange.fetch at 0x000002E956FA2820>
                 └ ccxt.async_support.binancecoinm()

  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\ccxt\async_support\base\exchange.py", line 161, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    │    │             │                 │                 │    │       │        │              │              │                └ 'timestamp=1625388997540&recvWindow=5000&symbol=BTCUSD_PERP&amount=3&positionSide=BOTH&type=1&signature=a82a891aaa1db7b05ecca...
    │    │             │                 │                 │    │       │        │              │              └ {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-...
    │    │             │                 │                 │    │       │        │              └ {'code': '-4050', 'msg': 'Cross balance insufficient.'}
    │    │             │                 │                 │    │       │        └ '{"code":-4050,"msg":"Cross balance insufficient."}'
    │    │             │                 │                 │    │       └ {'Content-Type': 'application/json', 'Content-Length': '50', 'Connection': 'keep-alive', 'Date': 'Sun, 04 Jul 2021 08:56:39 G...
    │    │             │                 │                 │    └ 'POST'
    │    │             │                 │                 └ 'https://dapi.binance.com/dapi/v1/positionMargin'
    │    │             │                 └ 'Bad Request'
    │    │             └ 400
    │    └ <function binance.handle_errors at 0x000002E956FFA790>
    └ ccxt.async_support.binancecoinm()

  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\ccxt\async_support\binance.py", line 3853, in handle_errors
    raise ExchangeError(feedback)
          │             └ 'binancecoinm {"code":-4050,"msg":"Cross balance insufficient."}'
          └ <class 'ccxt.base.errors.ExchangeError'>

ccxt.base.errors.ExchangeError: binancecoinm {"code":-4050,"msg":"Cross balance insufficient."}
```

Please help with this issue, everything should be sufficient. 
Doesn't it see 
`BTCUSD_PERP    | 0 | 0.00000000 | 35518.71980960 | 0.00000000 | 0 | 5  | 200     | isolated | 0.00000000 | false | BOTH | 0 | 0`?
Maybe I'm executing the wrong thing. I've got ``` 'BTC': 0.0007551 ```

**Comment by kroitor** [comment]
Will reply here: https://github.com/ccxt/ccxt/issues/9500
