### ISSUE TITLE
Can I retrieve prices in binance every second working 24/7?

### ISSUE THREAD

**Issue by administer03** [ccxt/ccxt#9532]
I fetch the data in the following way
```
bi = ccxt.binance({'apiKey': api_key,
                    'secret': secret_key,
                    })
data = bi.fetch_ohlcv(coin_symbol, time_frame, None, length_candle)
```
I fetch the data this way in a true while loop. After all the operations are done, I gave the program sleep 1 second, after which it executes the next cycle.

And after the program has been running for about 1 day, the problem is as follows.
```
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/tanad_s/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 573, in fetch
    verify=self.verify
  File "/home/tanad_s/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tanad_s/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/tanad_s/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "bot.py", line 34, in <module>
    main()
  File "bot.py", line 31, in main
    bot(run_time, delay_fetch_data, bi, coin_symbol, time_frame , cutloss, target_sell)
  File "/home/tanad_s/bot_strategy/functions.py", line 207, in bot
    data = bi.fetch_ohlcv(coin_symbol, time_frame, None, length_candle)
  File "/home/tanad_s/.local/lib/python3.6/site-packages/ccxt/binance.py", line 1603, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))
  File "/home/tanad_s/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 460, in inner
    return entry(_self, **inner_kwargs)
  File "/home/tanad_s/.local/lib/python3.6/site-packages/ccxt/binance.py", line 3859, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/tanad_s/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/tanad_s/.local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 618, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=15m&limit=500
```
I've tried adjusting the fetch duration from fetching every 1s to 5s, I've encountered the same problem. Please suggest me the correct one.

P.S. I run this python script on google cloud using VM instance

**Comment by kroitor** [comment]
> I fetch the data this way in a true while loop.

Please, paste the code that contains the loop, cause the answer depends on how your loop is structured.

**Comment by administer03** [comment]
this is my while loop.
```
def bot(run_time, delay_time_frame, bi, coin_symbol, time_frame, cutloss, target_sell,
        EMA_S, EMA_M, EMA_L, MACD_S, MACD_L, MACD_Len, RSI_Len, length_candle = 500,):
    # timeout = hr_to_seconds(run_time)   # [seconds]
    # timeout_start = time.time()
    # while time.time() < timeout_start + timeout:
    while True:

        global_variable.decide_state_buy = 0 # if > 2 in 3 -> buy
        global_variable.decide_state_sell = 0 # if > 2 in 3 -> sell
        data = bi.fetch_ohlcv(coin_symbol, time_frame, None, length_candle)
        header = ['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']
        df = pd.DataFrame(data, columns=header)

        last_price = df['Close'].to_list()[-1]

        EMA_Short_last = cal_last_EMA(EMA_S, df, length_candle)
        EMA_Mid_last = cal_last_EMA(EMA_M, df, length_candle)
        EMA_Long_last = cal_last_EMA(EMA_L, df, length_candle)

        macd, signal = cal_last_MACD(MACD_S, MACD_L, MACD_Len, df)

        RSI_last = cal_last_RSI(RSI_Len, df, length_candle)

        RSI(RSI_last)
        MACD(macd, signal)
        EMA(EMA_Short_last, EMA_Mid_last, EMA_Long_last, last_price)
        action, diff_chg = decide_processing(last_price, cutloss, target_sell)
        global_variable.count_state += 1
        display_bot_processing(action, diff_chg, last_price, change_price(global_variable.bought_price, last_price), time_now())

        time.sleep(delay_time_frame)  # set delay on seconds
```

**Comment by kroitor** [comment]
@administer03 what is your version of CCXT? https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by administer03** [comment]
It's ccxt 1.52.59  on google cloud.

**Comment by kroitor** [comment]
You can mitigate it by just adding at least some basic error handling as documented in the Manual in a request-fail-retry fashion:

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

```Python
def bot(run_time, delay_time_frame, bi, coin_symbol, time_frame, cutloss, target_sell,
        EMA_S, EMA_M, EMA_L, MACD_S, MACD_L, MACD_Len, RSI_Len, length_candle = 500,):
    # timeout = hr_to_seconds(run_time)   # [seconds]
    # timeout_start = time.time()
    # while time.time() < timeout_start + timeout:
    while True:

        global_variable.decide_state_buy = 0 # if > 2 in 3 -> buy
        global_variable.decide_state_sell = 0 # if > 2 in 3 -> sell
        try:
            data = bi.fetch_ohlcv(coin_symbol, time_frame, None, length_candle)
            header = ['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']
            df = pd.DataFrame(data, columns=header)
            last_price = df['Close'].to_list()[-1]
            EMA_Short_last = cal_last_EMA(EMA_S, df, length_candle)
            EMA_Mid_last = cal_last_EMA(EMA_M, df, length_candle)
            EMA_Long_last = cal_last_EMA(EMA_L, df, length_candle)
            macd, signal = cal_last_MACD(MACD_S, MACD_L, MACD_Len, df)
            RSI_last = cal_last_RSI(RSI_Len, df, length_candle)
            RSI(RSI_last)
            MACD(macd, signal)
            EMA(EMA_Short_last, EMA_Mid_last, EMA_Long_last, last_price)
            action, diff_chg = decide_processing(last_price, cutloss, target_sell)
            global_variable.count_state += 1
            display_bot_processing(action, diff_chg, last_price, change_price(global_variable.bought_price, last_price), time_now())
        except Exception as e:
            print(type(e).__name__, str(e))  # print the error, then repeat the iteration
        time.sleep(delay_time_frame)  # set delay on seconds
```

Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by administer03** [comment]
Ok, thank you so much for your kind support.
