### ISSUE TITLE
ccxt.base.errors.NetworkError: binanceusdm / ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#9547]
- OS: Ubuntu 20.04.2 LTS
- Programming Language version: Python 3.8.10
- CCXT version: ccxt==1.52.60

-----------

Once in a while I am getting following error message `An exception of type NetworkError occurred`. What may be the reason of this error and how could I prevent it?

Please note that, in parallel another independent Python code was running and making requests in each 15 seconds checking open positions using `ccxt.binanceusdm()` module. I am not sure, since two Python daemons running independent `exchange` object, they might conflict due to time difference requests and make over-requests.

If this is the case, would it be a good idea to create single `exhange` object and do all the operations from it using threads.

Code:
```
ops = {"apiKey": api_key, "secret": api_secret, "options": {"adustForTimeDifference": True}}
self.exchange_future = ccxt.binanceusdm(ops)
future_positions = bot.exchange_future.fetch_positions()  # <= Error Occurs here.
```

Error log:

```
E: An exception of type NetworkError occurred. Arguments:
('binanceusdm GET https://fapi.binance.com/fapi/v1/account?timestamp=...&recvWindow=5000&signature=...',)
Traceback (most recent call last):
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alper/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/alper/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 566, in fetch
    response = self.session.request(
  File "/home/alper/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alper/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/alper/venv/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./app.py", line 126, in webhook
    trade_func(data_msg)
  File "./app.py", line 89, in trade_func
    future_positions = bot.exchange_future.fetch_positions()
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/binance.py", line 3629, in fetch_positions
    account = getattr(self, method)(query)
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 460, in inner
    return entry(_self, **inner_kwargs)
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/binance.py", line 3861, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 618, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binanceusdm GET https://fapi.binance.com/fapi/v1/account?timestamp=....&recvWindow=5000&signature=...
```

**Comment by kroitor** [comment]
> lease note that, in parallel another independent Python code was running and making requests in each 15 seconds checking open positions using ccxt.binanceusdm() module. I am not sure, since two Python daemons running independent exchange object, they might conflict due to time difference requests and make over-requests.

Are you restarting the entire script, including the exchange instantiation, every 15 seconds? If yes, that violates this guide: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

**Comment by avatar-lavventura** [comment]
Sorry if I am not clear. 

> Are you restarting the entire script,

No the `exhange` instance remains as it is.  I just create it only one time when the Pyhon daemon starts and I keep use the same object. But there is another Pyhton script also is running, which does the similar stuff.

Base example:

```python
import time
class Strategy:
    def __init__(self, data_msg, is_print=True):
        ops = {"apiKey": api_key, "secret": api_secret, "options": {"adustForTimeDifference": True}}
        self.exchange_future = ccxt.binanceusdm(ops)
        self.exchange_spot = ccxt.binance(ops)

strategy = Strategy("")

while True:
    strategy.exchange_future.fetch_positions() 
    time.sleep(15)
```

**Comment by avatar-lavventura** [comment]
@kroitor It will be also interesting to experiment in Python using [`pickle`](https://docs.python.org/3/library/pickle.html) to load the single time created exhange object.

Using `pickle.dump()` the single time created `exhange` object and re-using the same exchange object via `picle.save()` in different scripts and parallel. 

Honestly, I am not sure this will trick the exhanges.
