### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by rafalsza** [ccxt/ccxt#9555]
- OS:Ubuntu
- Programming Language version:Python 3.8
- CCXT version: ccxt-1.52.82

Hi I have a problem wih gettng  an error always after 4th iteration:;
```
[5 rows x 8 columns]
Fetching new bars for 2021-07-12T01:14:53.086946
Traceback (most recent call last):
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 566, in fetch
    response = self.session.request(
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "binance_bot_bnb.py", line 145, in <module>
    schedule.run_pending()
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/schedule/__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "binance_bot_bnb.py", line 103, in run_bot
    bars = exchange.fetch_ohlcv(symbol1, timeframe='30m', limit=200)
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/ccxt/binance.py", line 1606, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 460, in inner
    return entry(_self, **inner_kwargs)
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/ccxt/binance.py", line 3862, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/r_szataniak/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 618, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/klines?symbol=BNBUSDT&interval=30m&limit=200
```

code:

```exchange = ccxt.binance({
    "apiKey": config.BINANCE_API_KEY2,
    "secret": config.BINANCE_SECRET_KEY2,
    "timeout": 30000,
    "enableRateLimit": True
})
def run_bot():
    print(f"Fetching new bars for {datetime.now().isoformat()}")
    bars = exchange.fetch_ohlcv(symbol1, timeframe='30m', limit=200)
    df = pd.DataFrame(bars[:-1], columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    df = df.set_index(pd.DatetimeIndex(df['timestamp'].values))

schedule.every(60).seconds.do(run_bot)
while True:
    schedule.run_pending()
    time.sleep(1)
```

**Comment by nickpagz** [comment]
I'm going to piggy back on this issue, mine is very similar, and mostly because [this issue is already closed](https://github.com/freqtrade/freqtrade/issues/4148#issuecomment-756185809).
The difference being this is happening with ftx.com, and it's random.
I have two scripts running on a VM on google cloud using tmux to keep them going, both poll ftx for market data and open positions. One script polls every minute, the other every 10 minutes. Only the script that polls every minute gives the error. It's pretty random, sometimes oncer per day, sometimes two or three. As soon as I notice it fails, I run the script and all is good again. 

Based on issue 4148 comments, this is not necessarily a ccxt issue, and I do believe it's ftx. However, I'm looking for a way to cleanly catch this error and have my script continue trying to run, but so far I'm struggling to get that to work. 

For what it's worth, this is the code that it always fails on:
```
def get_markets():
    all_markets = ftx.load_markets(True)
    return all_markets
```
It's the same code used in both scripts. 

I've tried:
```
def get_markets():
    trycnt = 3
    while trycnt > 0:
        try:
            all_markets = ftx.load_markets(True)
            trycnt = 0
        except ConnectionError:
            print("Connection error, trying again...")
            trycnt -= 1
            time.sleep(3)
        else:
            return all_markets
```
...and a few iterations of it, but no luck in successfully keeping the script running. 

Is there a good way to capture this cleanly and keep my script running?

Here's my stack trace for reference:
```

  File "/home/npagazani/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/npagazani/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/npagazani/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/npagazani/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/npagazani/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 566, in fetch
    response = self.session.request(
  File "/home/npagazani/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/npagazani/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/npagazani/.local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/npagazani/3commas/Py3c_triggers.py", line 259, in <module>
    markets = get_markets()
  File "/home/npagazani/3commas/Py3c_triggers.py", line 42, in get_markets
    all_markets = ftx.load_markets(True)
  File "/home/npagazani/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1365, in load_markets
    currencies = self.fetch_currencies()
  File "/home/npagazani/.local/lib/python3.9/site-packages/ccxt/ftx.py", line 304, in fetch_currencies
    response = self.publicGetCoins(params)
  File "/home/npagazani/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 460, in inner
    return entry(_self, **inner_kwargs)
  File "/home/npagazani/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 485, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/npagazani/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/npagazani/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 618, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: ftx GET https://ftx.com/api/coins
```

TIA!

**Comment by nickpagz** [comment]
FWIW, the code above is working to catch the error, and so far it's catching it on the second attempt every time.

**Comment by rafalsza** [comment]
thank you
