### ISSUE TITLE
Error when I run code with ccxt in it Python.

### ISSUE THREAD

**Issue by fuvser** [ccxt/ccxt#9583]
When I comment out the ccxt code it gives me no error
- OS: Windows 10 Pro 64 bit 20H2
- Programming Language version: Python 3.9.6
- CCXT version: Latest

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```
import ccxt
binance = ccxt.binanceusdm({
     'apiKey': api_key,
     'secret': api_secret,
 })
```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```
Exception ignored in: <function Exchange.__del__ at 0x000002B3A7DAA5E0>
Traceback (most recent call last):
  File "C:\Users\Scoala\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 397, in __del__ 
  File "C:\Users\Scoala\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 747, in close
  File "C:\Users\Scoala\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 325, in close    
  File "C:\Users\Scoala\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\poolmanager.py", line 222, in clear  
  File "C:\Users\Scoala\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\_collections.py", line 95, in clear  
TypeError: 'NoneType' object is not callable

**Comment by frosty00** [comment]
what version of ccxt are you using? how did you install ccxt?

**Comment by fuvser** [comment]
> what version of ccxt are you using? how did you install ccxt?

I'm using the 1.52.31 version of ccxt and I installed it with pip install ccxt

**Comment by kroitor** [comment]
@fuvser make sure you are not trying to create and delete the exchange instance more than once, do not create it upon receiving each new web request, otherwise you violate this rule: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter. We need to see the complete code to reproduce it to be able to help. 

Feel free to reopen this issue or just ask further questions. If anything, please, always paste as much info as you can:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
