### ISSUE TITLE
Order status fetch / process failure after BUY/SELL to ByBit

### ISSUE THREAD

**Issue by rvleij** [ccxt/ccxt#9585]
My Environment:

- OS: MacOS
- Programming Language version: Python 3.9.0
- CCXT version: '1.53.8'

I'm running with bt-ccxt around ccxt with the following config:
```
store = CCXTStore(exchange='bybit', currency=COIN_REFER, config=broker_config, sandbox=True, retries=10, debug=DEBUG)
```
The setup currently works with Binance. I'm trying to buy/sell BTC/USDT futures (I know that in Binance I need to set that with a param, in ByBit not). The problem seems that the order is actually processed and the data is there, but somehow we expect some different output in the "get orders" request, as I will paste below.

First the order I send in:
```
self.sell_order = self.sell(exectype=bt.Order.Limit, price=self.data0.close[0] * 0.99, transmit=True, size=self.stake_size, valid=(dt.datetime.now() + dt.timedelta(minutes=5)))
```
Resulting in the following POST (yeah, I'll have to figure out why the valid= didn't get passed along, but that's not the main issue here):
```
Request: POST https://api-testnet.bybit.com/private/linear/order/create {'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate'} {"side":"Sell","symbol":"BTCUSDT","order_type":"Limit","qty":0.4,"time_in_force":"GoodTillCancel","price":30988.5,"reduce_only":false,"close_on_trigger":false,"api_key":"<my_key>","recv_window":5000,"timestamp":"1626370620780","sign":"<some_signature>"}
```

Which in turn generates the response:

```
Response: POST https://api-testnet.bybit.com/private/linear/order/create 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '675', 'Expires': 'Thu, 15 Jul 2021 17:37:03 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 15 Jul 2021 17:37:03 GMT', 'Connection': 'keep-alive'} {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"order_id":"<order-id>","user_id":<uid>,"symbol":"BTCUSDT","side":"Sell","order_type":"Limit","price":30988.5,"qty":0.4,"time_in_force":"GoodTillCancel","order_status":"Created","last_exec_price":0,"cum_exec_qty":0,"cum_exec_value":0,"cum_exec_fee":0,"reduce_only":false,"close_on_trigger":false,"order_link_id":"","created_time":"2021-07-15T17:37:03Z","updated_time":"2021-07-15T17:37:03Z","take_profit":0,"stop_loss":0,"tp_trigger_by":"UNKNOWN","sl_trigger_by":"UNKNOWN"},"time_now":"1626370623.113564","rate_limit_status":99,"rate_limit_reset_ms":1626370623101,"rate_limit":100}
```

It's followed by another get order status thingy sequence:

```
Request: GET https://api-testnet.bybit.com/private/linear/order/search?api_key=<my_key>&order_id=<order-id>&recv_window=5000&symbol=BTCUSDT&timestamp=1626370621081&sign=<sign stuff> {'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api-testnet.bybit.com/private/linear/order/search?api_key=<my_key>&order_id=<order-id>&recv_window=5000&symbol=BTCUSDT&timestamp=1626370621081&sign=<sign_stuff> 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '692', 'Expires': 'Thu, 15 Jul 2021 17:37:03 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 15 Jul 2021 17:37:03 GMT', 'Connection': 'keep-alive'} {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"order_id":"<order-id>","user_id":<uid>,"symbol":"BTCUSDT","side":"Sell","order_type":"Limit","price":30988.5,"qty":0.4,"time_in_force":"GoodTillCancel","order_status":"Filled","last_exec_price":31303,"cum_exec_qty":0.4,"cum_exec_value":12521.2,"cum_exec_fee":9.3909,"order_link_id":"","reduce_only":false,"close_on_trigger":false,"created_time":"2021-07-15T17:37:03Z","updated_time":"2021-07-15T17:37:03Z","take_profit":0,"stop_loss":0,"tp_trigger_by":"UNKNOWN","sl_trigger_by":"UNKNOWN"},"time_now":"1626370623.412319","rate_limit_status":599,"rate_limit_reset_ms":1626370623406,"rate_limit":600}
```

Followed by another one...

```
Request: GET https://api-testnet.bybit.com/private/linear/order/search?api_key=<my_key>&order_id=<order-id>&recv_window=5000&symbol=BTCUSDT&timestamp=1626370621752&sign=<sign stuff> {'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api-testnet.bybit.com/private/linear/order/search?api_key=<key>&order_id=<order-id>&recv_window=5000&symbol=BTCUSDT&timestamp=1626370621752&sign=<sign> 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '692', 'Expires': 'Thu, 15 Jul 2021 17:37:04 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 15 Jul 2021 17:37:04 GMT', 'Connection': 'keep-alive'} {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"order_id":"<order-id>","user_id":<uid>,"symbol":"BTCUSDT","side":"Sell","order_type":"Limit","price":30988.5,"qty":0.4,"time_in_force":"GoodTillCancel","order_status":"Filled","last_exec_price":31303,"cum_exec_qty":0.4,"cum_exec_value":12521.2,"cum_exec_fee":9.3909,"order_link_id":"","reduce_only":false,"close_on_trigger":false,"created_time":"2021-07-15T17:37:03Z","updated_time":"2021-07-15T17:37:03Z","take_profit":0,"stop_loss":0,"tp_trigger_by":"UNKNOWN","sl_trigger_by":"UNKNOWN"},"time_now":"1626370624.101577","rate_limit_status":598,"rate_limit_reset_ms":1626370624088,"rate_limit":600}
```

I would say, as a noob, that this looks good: order is filled (verified in the console) and I get responses with this info. But instead I get a traceback right after it:

```
Finished with error:  'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/robin/Development/CryptoBot/bybit-bot/./main.py", line 222, in <module>
    main()
  File "/Users/robin/Development/CryptoBot/bybit-bot/./main.py", line 176, in main
    result = cerebro.run()
  File "/Users/robin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/backtrader/cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "/Users/robin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/backtrader/cerebro.py", line 1298, in runstrategies
    self._runnext(runstrats)
  File "/Users/robin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/backtrader/cerebro.py", line 1623, in _runnext
    self._brokernotify()
  File "/Users/robin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/backtrader/cerebro.py", line 1360, in _brokernotify
    self._broker.next()
  File "/Users/robin/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ccxtbt/ccxtbroker.py", line 199, in next
    for fill in ccxt_order['trades']:
TypeError: 'NoneType' object is not iterable
```

Any ideas? I tried quite some stuff and also googled in others using Bybit. I'm using bracket orders with trailing stop, which I enter in one go for Binance, which doesn't seem to be possible. But in this test example I'm really just sending in a single LIMIT order to start with. It's the same effect with a MARKET order. So basically, it's basic order flow, I'm wondering what I can do wrong or if this is a buy in handling the response from Bybit?

**Comment by rvleij** [comment]
I found the issue and it doesn't seem related to ccxt itself. It's related to a bug in the bt-ccxt wrapper, specifically this bug:

https://github.com/Dave-Vallance/bt-ccxt-store/issues/38

I've patched the ccxtbroker.py and now it works, so I'll close this issue. Nothing to see here, please move along. :) Hopefully others find it quicker than I did by this report ending up in Google.

**Comment by kroitor** [comment]
@rvleij thanks for reporting and for letting us know! Appreciate your feedback!
