### ISSUE TITLE
[OKEX v5] fetch_balance() throwing TypeError 

### ISSUE THREAD

**Issue by mparry27** [ccxt/ccxt#9588]
I'm getting a TypeError:  string indices must be integers when I ran fetch_balance(). I saw [this issue]( https://github.com/ccxt/ccxt/issues/9572 ) and thought it may be related but I'm on the latest version of ccxt so I'm not sure what it could be.

- OS: MacOS 10.15.7
- Programming Language version: Python 3.7.7
- CCXT version: 1.53.3

```
from ccxt import okex5

okex5 = okex5({'apiKey': '<API KEY HERE>',
                   'secret': '<SECRET HERE>',
                   'password': '<PASSWORD HERE>'})

okex5.verbose = True
okex5.fetch_balance()
```

```
Traceback (most recent call last):
  File "sandbox_personal.py", line 20, in <module>
    okex5.fetch_balance()
  File "/usr/local/lib/python3.7/site-packages/ccxt/okex5.py", line 1108, in fetch_balance
    type = self.safe_string(options, 'type', defaultType)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 684, in safe_string
    return str(dictionary[key]) if Exchange.key_exists(dictionary, key) else default_value
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 669, in key_exists
    return dictionary[key] is not None
TypeError: string indices must be integers
```

**Comment by frosty00** [comment]
you need to update your version of ccxt this issue has been fixed

let us know if you still have any troubles

**Comment by mparry27** [comment]
I'm still getting the error even after updating to the latest version. 
```
from ccxt import okex5, __version__
okex5 = okex5({'apiKey': '<API KEY HERE>',
               'secret': '<SECRET HERE>',
               'password': '<PASSWORD HERE>'})

print('CCXT VERSION: '+__version__)
okex5.fetch_balance()
```

```
CCXT VERSION: 1.53.8
Traceback (most recent call last):
  File "sandbox_personal.py", line 20, in <module>
    okex5.fetch_balance()
  File "/usr/local/lib/python3.7/site-packages/ccxt/okex5.py", line 1108, in fetch_balance
    type = self.safe_string(options, 'type', defaultType)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 684, in safe_string
    return str(dictionary[key]) if Exchange.key_exists(dictionary, key) else default_value
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 669, in key_exists
    return dictionary[key] is not None
TypeError: string indices must be integers
```

**Comment by kroitor** [comment]
@mparry27 it is fixed in 1.53.9, the auto build takes ~20 minutes to arrive, and it has just arrived now. Let us know if you have this issue with CCXT 1.53.9.

**Comment by mparry27** [comment]
@kroitor Ok its fixed now. I should have been more patient. Thank you!

**Comment by kroitor** [comment]
@mparry27 thanks for your involvement!
