### ISSUE TITLE
 'crossMargin': balances[code]['crossMargin'], KeyError: None

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#9591]
- OS: `Ubuntu 20.04.2 LTS`
- Programming Language version:  `Python 3.8.10`
- CCXT version: `ccxt==1.52.60`

I keep having following error for the related function: 

```
class Exchange:
    def __init__(self):
        ops = {
            "apiKey": api_key,
            "secret": api_secret,
            "options": {"adustForTimeDifference": True},
            # 'verbose': True,  # for debug output
        }
        self.future = ccxt.binanceusdm(ops)
        self.spot = ccxt.binance(ops)


exchange = Exchange()
future_positions = await exchange.future.fetch_positions()  # error is generates for this line
```

I was not getting this error for the previous version, what may be the cause of this and how can I fix it?

----------

```
Traceback (most recent call last):
  File "/home/alper/trade_bot/bot/app_async.py", line 71, in webhook
    try:
  File "/home/alper/trade_bot/bot/trade_async.py", line 537, in trade_main
    output = await self.check_on_going_positions(strategy)
  File "/home/alper/trade_bot/bot/trade_async.py", line 485, in check_on_going_positions
    usdt_open_position_size = await self.get_usdt_open_position_count()
  File "/home/alper/trade_bot/bot/trade_async.py", line 166, in get_usdt_open_position_count
    future_positions = await helper.exchange.future.fetch_positions()
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py", line 3630, in fetch_positions
    result = self.parse_account_positions(account)
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py", line 3284, in parse_account_positions
    'crossMargin': balances[code]['crossMargin'],
KeyError: None
```

**Comment by frosty00** [comment]
@avatar-lavventura we will check it out

**Comment by avatar-lavventura** [comment]
Please let me now if you require any additional information.

**Comment by tsferro2** [comment]
I am also now getting the same error when calling:

`exchange.fetch_positions() `

**Comment by frosty00** [comment]
please update to the latest version of ccxt, we are unable to reproduce this issue.

**Comment by frosty00** [comment]
also please provide the verbose response, otherwise this issue can be closed

**Comment by avatar-lavventura** [comment]
No problem, the issue could be closed.

Please not that the issue occured one time and I am not able to generate again now. 

I keep running the same function every 10 seconds, keeping the  verbose responses. If I face with the same issue again, I can update my issue.

**Comment by avatar-lavventura** [comment]
I experienced the same error again. It occurs if I make too many requests over time. And if the error is catched it keeps repeat itself over and over until the program is terminated.

```
Traceback (most recent call last):
  File "./binance_balance.py", line 147, in main
    await _main()
  File "./binance_balance.py", line 89, in _main
    future_positions = await helper.exchange.future.fetch_positions()
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py", line 3672, in fetch_positions
    result = self.parse_account_positions(account)
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py", line 3325, in parse_account_positions
    'crossMargin': balances[code]['crossMargin'],
KeyError: None
 * 2021-07-28 10:54:56 | Futures=759.31695235
[binance_balance.py:147 "await _main()"] WHERE=events.py:81
E: An exception of type KeyError occurred. Arguments:
(None,)
Traceback (most recent call last):
  File "./binance_balance.py", line 147, in main
    await _main()
  File "./binance_balance.py", line 89, in _main
    future_positions = await helper.exchange.future.fetch_positions()
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py", line 3672, in fetch_positions
    result = self.parse_account_positions(account)
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py", line 3325, in parse_account_positions
    'crossMargin': balances[code]['crossMargin'],
KeyError: None
```

When I restart the on-going python-program it is resolved. Maybe there could be an option to restart the exchange object.

**Comment by frosty00** [comment]
can you post the verbose response of the exchange when this error happens?

**Comment by tsferro2** [comment]
I am also getting the same error again, and I updated ccxt last week:

    opn_pos_raw = exchange.fetch_positions()

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\binance.py", line
3631, in fetch_positions
    result = self.parse_account_positions(account)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\binance.py", line
3285, in parse_account_positions
    'crossMargin': balances[code]['crossMargin'],

KeyError: None

**Comment by kroitor** [comment]
@avatar-lavventura @tsferro2 please, paste your verbose request+response output as explained here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
