### ISSUE TITLE
Gateio4 order failed

### ISSUE THREAD

**Issue by xkyykx** [ccxt/ccxt#9597]
- OS:win7
- Programming Language version:python 3.7
- CCXT version:1.53.20

```
import ccxt
gate = ccxt.gateio4()
gate.apiKey='***'
gate.secret = '***'
gate.symbol = 'GT/USDT'
print(gate.create_limit_buy_order('GT/USDT',amount=1,price=2))
```

```
Traceback (most recent call last):
  File "E:/wwwroot/lianghua/demo2/main.py", line 52, in <module>
    print(gateGrid.create_limit_buy_order('GT/USDT',amount=1,price=2))
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 1988, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', amount, price, params)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\gateio4.py", line 999, in create_order
    response = self.privateSpotPostOrders(self.extend(request, params))
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 460, in inner
    return entry(_self, **inner_kwargs)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 485, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 480, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\gateio4.py", line 1195, in sign
    payload = '\n'.join(payloadArray)
TypeError: sequence item 4: expected str instance, int found

Process finished with exit code 1
```

**Comment by frosty00** [comment]
will debug this now

**Comment by xkyykx** [comment]
Failed to query single order：

I make sure the order is successful, order_id: 63097554913

```
print(gateGrid.fetch_order(id='63097554913',symbol='GT/USDT'))
```

```
Traceback (most recent call last):
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    response.raise_for_status()
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.gateio.ws/api/v4/spot/orders/63097554913

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/wwwroot/lianghua/demo2/main.py", line 74, in <module>
    print(gateGrid.fetch_order(id='63097554913',symbol='GT/USDT'))
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\gateio4.py", line 1092, in fetch_order
    response = self.privateSpotGetOrdersOrderId(self.extend(request, params))
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 460, in inner
    return entry(_self, **inner_kwargs)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 485, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\gateio4.py", line 1211, in handle_errors
    raise Error(self.id + ' ' + message)
ccxt.base.errors.OrderNotFound: gateio4 Order with ID 63097554913 not found

Process finished with exit code 1

```

**Comment by xkyykx** [comment]
I've tried a different way of writing, and the problem remains unsolved.
```
print(gateGrid.fetch_order(id='63097554913',params={'currency_pair': 'GT/USDT',}))
```
```
Traceback (most recent call last):
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    response.raise_for_status()
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.gateio.ws/api/v4/spot/orders/63097554913?currency_pair=GT%2FUSDT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/wwwroot/lianghua/demo2/main.py", line 83, in <module>
    print(gateGrid.fetch_order(id='63097554913',params={'currency_pair': 'GT/USDT',}))
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\gateio4.py", line 1092, in fetch_order
    response = self.privateSpotGetOrdersOrderId(self.extend(request, params))
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 460, in inner
    return entry(_self, **inner_kwargs)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 485, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\gateio4.py", line 1211, in handle_errors
    raise Error(self.id + ' ' + message)
ccxt.base.errors.AuthenticationError: gateio4 Signature mismatch
```

**Comment by kroitor** [comment]
@xkyykx please, upgrade to version 1.53.22 and let us know if you still have this issue.

To make sure that your runtime version is up to date:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
```

**Comment by xkyykx** [comment]
CCXT version:1.53.22. 
It's the latest version, the problem remains.

**Comment by kroitor** [comment]
@xkyykx try this:

```Python
import ccxt
from pprint import pprint

print("CCXT Version:', ccxt.__version__)

exchange = ccxt.gateio4({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()

exchange.verbose = True
symbol = 'GT/USDT'
order = exchange.fetch_order('63097554913', symbol)
pprint(order)
```

↑ If that does not work, please, paste your verbose output here.

**Comment by xkyykx** [comment]
```
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.gateio4({
    'apiKey': '***',
    'secret': '***',
})

markets = exchange.load_markets()

exchange.verbose = True
symbol = 'GT/USDT'
order = exchange.fetch_order('63097554913', symbol)
pprint(order)
```
```
E:\wwwroot\ENVS\ENV01\Scripts\python.exe E:/wwwroot/lianghua/demo2/test.py
CCXT Version: 1.53.22

Request: GET https://api.gateio.ws/api/v4/spot/orders/63097554913 {'KEY': '***', 'Timestamp': '1626608779', 'SIGN': '19c61ea23f655326db4306bfa7da839df2b75aa951b2b848f6aea6cdfaefe7934deb33b8e0de94d157036ea218eabd26770ec4212cac0651bfedf22768602462', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    response.raise_for_status()
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\requests\models.py", line 941, in raise_for_status

Response: GET https://api.gateio.ws/api/v4/spot/orders/63097554913 404 {'Date': 'Sun, 18 Jul 2021 11:46:21 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[557fe482-1095376587]', 'Content-Encoding': 'gzip'} {"label":"ORDER_NOT_FOUND","message":"Order with ID 63097554913 not found"}
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.gateio.ws/api/v4/spot/orders/63097554913

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/wwwroot/lianghua/demo2/test.py", line 15, in <module>
    order = exchange.fetch_order('63097554913', symbol)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\gateio4.py", line 1092, in fetch_order
    response = self.privateSpotGetOrdersOrderId(self.extend(request, params))
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 460, in inner
    return entry(_self, **inner_kwargs)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 485, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\gateio4.py", line 1211, in handle_errors
    raise Error(self.id + ' ' + message)
ccxt.base.errors.OrderNotFound: gateio4 Order with ID 63097554913 not found

Process finished with exit code 1

```

**Comment by kroitor** [comment]
@xkyykx do you actually have that order on that account? Can you see the order with that id on the website? Is it open? Closed? Missing?

**Comment by xkyykx** [comment]
```
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.gateio4({
    'apiKey': '9f517c007cc1bef73326f2e7a7040b3d',
    'secret': '28fe4e6a5135a5a781501ee1cb91275ae4444a80a54feb6de8053bf4508be3e7',
})

markets = exchange.load_markets()

exchange.verbose = True
symbol = 'GT/USDT'
info = exchange.create_limit_buy_order(symbol,amount=1,price=2)
print(info)
order_id = info['id']
order = exchange.fetch_order(order_id, symbol)
pprint(order)
```
```
E:\wwwroot\ENVS\ENV01\Scripts\python.exe E:/wwwroot/lianghua/demo2/test.py
CCXT Version: 1.53.22

Request: POST https://api.gateio.ws/api/v4/spot/orders {'KEY': '9f517c007cc1bef73326f2e7a7040b3d', 'Timestamp': '1626609641', 'SIGN': '5d4e168e7b2101f94f5263eb97fe4972a46b7ccc59324cfa3c043b4da1ff584d9e870476f0b23a9a474b72fea2ff37826f8bc2c840b68d088cb095df3291f01f', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} {"currency_pair":"GT_USDT","amount":"1","price":"2","side":"buy"}

Response: POST https://api.gateio.ws/api/v4/spot/orders 200 {'Date': 'Sun, 18 Jul 2021 12:00:43 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[2f05db58-1098353599]', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Access-Control-Max-Age': '1728000', 'Vary': 'Origin', 'Content-Encoding': 'gzip'} {"id":"63109037634","text":"apiv4","create_time":"1626609643","update_time":"1626609643","create_time_ms":1626609643465,"update_time_ms":1626609643465,"status":"open","currency_pair":"GT_USDT","type":"limit","account":"spot","side":"buy","amount":"1","price":"2","time_in_force":"gtc","iceberg":"0","left":"1","fill_price":"0","filled_total":"0","fee":"0","fee_currency":"GT","point_fee":"0","gt_fee":"0","gt_discount":false,"rebated_fee":"0","rebated_fee_currency":"USDT"}
{'id': '63109037634', 'clientOrderId': '63109037634', 'timestamp': 1626609643465, 'datetime': '2021-07-18T12:00:43.465Z', 'lastTradeTimestamp': 1626609643465, 'status': 'open', 'symbol': 'GT/USDT', 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': None, 'side': 'buy', 'price': 2.0, 'stopPrice': None, 'average': None, 'amount': 1.0, 'cost': 0.0, 'filled': 0.0, 'remaining': 1.0, 'fee': None, 'fees': [{'currency': 'GT', 'cost': 0.0}, {'currency': 'GT', 'cost': 0.0}, {'currency': 'USDT', 'cost': 0.0}], 'trades': None, 'info': {'id': '63109037634', 'text': 'apiv4', 'create_time': '1626609643', 'update_time': '1626609643', 'create_time_ms': '1626609643465', 'update_time_ms': '1626609643465', 'status': 'open', 'currency_pair': 'GT_USDT', 'type': 'limit', 'account': 'spot', 'side': 'buy', 'amount': '1', 'price': '2', 'time_in_force': 'gtc', 'iceberg': '0', 'left': '1', 'fill_price': '0', 'filled_total': '0', 'fee': '0', 'fee_currency': 'GT', 'point_fee': '0', 'gt_fee': '0', 'gt_discount': False, 'rebated_fee': '0', 'rebated_fee_currency': 'USDT'}}

Request: GET https://api.gateio.ws/api/v4/spot/orders/63109037634 {'KEY': '9f517c007cc1bef73326f2e7a7040b3d', 'Timestamp': '1626609642', 'SIGN': '1bba6838b099a82121098aa36a8ec303ee01804605c059a49b4761e43ab453c80e6d5dcb800287b2023ee941a564a47badb1f20f8989c41f1a069e11b2ea549e', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.gateio.ws/api/v4/spot/orders/63109037634 404 {'Date': 'Sun, 18 Jul 2021 12:00:44 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[ab6ce78a-1098357324]', 'Content-Encoding': 'gzip'} {"label":"ORDER_NOT_FOUND","message":"Order with ID 63109037634 not found"}
Traceback (most recent call last):
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 592, in fetch
    response.raise_for_status()
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.gateio.ws/api/v4/spot/orders/63109037634

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/wwwroot/lianghua/demo2/test.py", line 18, in <module>
    order = exchange.fetch_order(order_id, symbol)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\gateio4.py", line 1092, in fetch_order
    response = self.privateSpotGetOrdersOrderId(self.extend(request, params))
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 460, in inner
    return entry(_self, **inner_kwargs)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 485, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 481, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\base\exchange.py", line 608, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "E:\wwwroot\ENVS\ENV01\lib\site-packages\ccxt\gateio4.py", line 1211, in handle_errors
    raise Error(self.id + ' ' + message)
ccxt.base.errors.OrderNotFound: gateio4 Order with ID 63109037634 not found

Process finished with exit code 1
```

**Comment by kroitor** [comment]
@xkyykx try a higher price, I suspect that gateio4 will not allow fetch_order for non-open orders:

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.gateio4({
    'apiKey': '***',
    'secret': '****',
})

markets = exchange.load_markets()

exchange.verbose = True
symbol = 'GT/USDT'
info = exchange.create_limit_buy_order(symbol,amount=1,price=3.5)
print(info)
order_id = info['id']
order = exchange.fetch_order(order_id, symbol)
pprint(order)
```

**Comment by xkyykx** [comment]
Another way to write it is successful.

```
print(gateGrid.fetch_order(id='63097554913',params={'currency_pair': 'GT_USDT',}))
```
```
E:\wwwroot\ENVS\ENV01\Scripts\python.exe E:/wwwroot/lianghua/demo2/main.py
CCXT Version: 1.53.22

Request: GET https://api.gateio.ws/api/v4/spot/orders/63097554913?currency_pair=GT_USDT {'KEY': '9f517c007cc1bef73326f2e7a7040b3d', 'Timestamp': '1626609953', 'SIGN': '3e246d8dc194d353fd4d85049c057bdbf9bdf27da1b6e53ccdb3e9c0054611bdf368332c7414e6d3b386057b83c13005c07d98a32ee5c1bd1b571bf8e9b26e6c', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.gateio.ws/api/v4/spot/orders/63097554913?currency_pair=GT_USDT 200 {'Date': 'Sun, 18 Jul 2021 12:05:56 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[ad67875e-1100017586]', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Access-Control-Max-Age': '1728000', 'Vary': 'Origin', 'Content-Encoding': 'gzip'} {"id":"63097554913","text":"apiv4","create_time":"1626605327","update_time":"1626605327","create_time_ms":1626605327119,"update_time_ms":1626605327119,"status":"open","currency_pair":"GT_USDT","type":"limit","account":"spot","side":"buy","amount":"1","price":"2","time_in_force":"gtc","iceberg":"0","left":"1","fill_price":"0","filled_total":"0","fee":"0","fee_currency":"GT","point_fee":"0","gt_fee":"0","gt_discount":false,"rebated_fee":"0","rebated_fee_currency":"USDT"}
{'id': '63097554913', 'clientOrderId': '63097554913', 'timestamp': 1626605327119, 'datetime': '2021-07-18T10:48:47.119Z', 'lastTradeTimestamp': 1626605327119, 'status': 'open', 'symbol': 'GT/USDT', 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': None, 'side': 'buy', 'price': 2.0, 'stopPrice': None, 'average': None, 'amount': 1.0, 'cost': 0.0, 'filled': 0.0, 'remaining': 1.0, 'fee': None, 'fees': [{'currency': 'GT', 'cost': 0.0}, {'currency': 'GT', 'cost': 0.0}, {'currency': 'USDT', 'cost': 0.0}], 'trades': None, 'info': {'id': '63097554913', 'text': 'apiv4', 'create_time': '1626605327', 'update_time': '1626605327', 'create_time_ms': '1626605327119', 'update_time_ms': '1626605327119', 'status': 'open', 'currency_pair': 'GT_USDT', 'type': 'limit', 'account': 'spot', 'side': 'buy', 'amount': '1', 'price': '2', 'time_in_force': 'gtc', 'iceberg': '0', 'left': '1', 'fill_price': '0', 'filled_total': '0', 'fee': '0', 'fee_currency': 'GT', 'point_fee': '0', 'gt_fee': '0', 'gt_discount': False, 'rebated_fee': '0', 'rebated_fee_currency': 'USDT'}}

Process finished with exit code 0
```

**Comment by kroitor** [comment]
@xkyykx 

> Another way to write it is successful.

That looks like a bug in CCXT< will push a fix in a minute.

**Comment by kroitor** [comment]
If you upgrade to 1.53.24 (the new auto build will arrive in ~20 minutes), this should work:

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.gateio4({
    'apiKey': '***',
    'secret': '****',
})

markets = exchange.load_markets()

exchange.verbose = True
symbol = 'GT/USDT'
info = exchange.create_limit_buy_order(symbol,amount=1,price=3.5)
print(info)
order_id = info['id']
order = exchange.fetch_order(order_id, symbol)
pprint(order)
```

Thanks for your feedback, we really appreciate it!

**Comment by xkyykx** [comment]
I should say thank you, thank you!
