### ISSUE TITLE
createmarketsellorder expects a price

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#960]
create_market_sell_order seems to expect a price. Maybe this is work-in-progress, but not sure if this is on your radar.

Note: 
- Below order is very small, it should raise an exception stating that this is below minimum order.
- I know market orders are dangerous, just testing. 

- OS: Windows
- Programming Language: Python sync, asymc
- CCXT version: ccxt-1.10.475
- Exchange: cryptopia
- Method: create_market_sell_order

```
import ccxt
import test2_config as config

e = ccxt.cryptopia()
e.verbose = True
e.apiKey = config.exchange_keys['cryptopia']['key']
e.secret = config.exchange_keys['cryptopia']['secret']
e.create_market_sell_order('DOGE/BTC', 136.26531580)



C:\Users\gaardiolor\Anaconda3\python.exe C:/Users/gaardiolor/PycharmProjects/test2/_test/pruts123.py
GET https://www.cryptopia.co.nz/api/GetTradePairs 
Request: {'Accept-Encoding': 'gzip, deflate'} None
GET https://www.cryptopia.co.nz/api/GetTradePairs 
Response: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'Date': 'Mon, 25 Dec 2017 14:16:47 GMT', 'Set-Cookie': '<snip>; expires=Tue, 25 Dec 2018 11:44:20 GMT; path=/; Domain=.cryptopia.co.nz, nlbi_<snip> = <snip>; path=/; Domain=.cryptopia.co.nz, incap_ses_<snip> = <snip>; path=/; Domain=.cryptopia.co.nz, <snip>; path=/; Max-Age=900, ___utmva<snip>=<snip>; path=/; Max-Age=900, ___utm<snip>=<snip>    XbyOnalr: itv; path=/; Max-Age=900', 'Strict-Transport-Security': 'max-age=31536000', 'X-Iinfo': '<snip>', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked'} {"Success":true,"Message":null,"Data"<snip looks good>
GET https://www.cryptopia.co.nz/api/GetCurrencies 
Request: {'Accept-Encoding': 'gzip, deflate'} None
GET https://www.cryptopia.co.nz/api/GetCurrencies 
Response: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'Date': 'Mon, 25 Dec 2017 14:16:48 GMT', 'Set-Cookie': 'visid_incap_<snip>=<snip>; expires=Tue, 25 Dec 2018 11:44:20 GMT; path=/; Domain=.cryptopia.co.nz, incap_ses_<snip>=<snip>; path=/; Domain=.cryptopia.co.nz, ___utm<snip>=<snip>; path=/; Max-Age=900, ___utmva<snip>=<snip>; path=/; Max-Age=900, ___utm<snip>=<snip>\r\n    XOkOAalQ: wtV; path=/; Max-Age=900', 'Strict-Transport-Security': 'max-age=31536000', 'X-Iinfo': '<snip>', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked'} {"Success":true,"Message":null,"Data":[<snip looks good>
Traceback (most recent call last):
  File "C:/Users/gaardiolor/PycharmProjects/test2/_test/pruts123.py", line 9, in <module>
    e.create_market_sell_order('DOGE/BTC', 136.26531580)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1041, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)
  File "C:\Users\gaardiolor\Anaconda3\lib\site-packages\ccxt\cryptopia.py", line 349, in create_order
    price = float(price)
TypeError: float() argument must be a string or a number, not 'NoneType'

Process finished with exit code 1

```

**Comment by kroitor** [comment]
Hi! They allow limit orders only (via API). Added a check for the order type + exception to handle this. Thank you for reporting!
