### ISSUE TITLE
Bittrex: Connection closed by remote server

### ISSUE THREAD

**Issue by brandsimon** [ccxt/ccxt#9602]
I use websockets for some exchanges, but only with bittrex there is the following error: 
```
ERROR - Connection closed by remote server, closing code 1000
Traceback (most recent call last):
  File ".venv/src/ccxtpro/python/ccxtpro/bittrex.py", line 467, in watch_order_book
    orderbook = await self.subscribe_to_order_book(negotiation, symbol, limit, params)
  File ".venv/src/ccxtpro/python/ccxtpro/bittrex.py", line 482, in subscribe_to_order_book
    return await self.send_request_to_subscribe(negotiation, messageHash, subscription)
  File ".venv/src/ccxtpro/python/ccxtpro/bittrex.py", line 96, in send_request_to_subscribe
    return await self.watch(url, messageHash, request, messageHash, subscription)
ccxt.base.errors.NetworkError: Connection closed by remote server, closing code 1000
```
Sometimes the code works for hours, sometimes the error occurs after a few minutes. Is there a way to prevent it or recover?

**Comment by brandsimon** [comment]
Anything new?
I think, the same happened with poloniex.

**Comment by omnigolp** [comment]
Some exchanges work flawless, but some have this issue.
How can I handle the error properly?

**Comment by kroitor** [comment]
@brandsimon @omnigolp we're investigating it, looking for a fix, will post our findings here.

**Comment by omnigolp** [comment]
How is the investigation going?

**Comment by ttodua** [comment]
bittrex is closed.
