### ISSUE TITLE
ValueError gmp_init(): Argument #1 ($num) is not an integer string

### ISSUE THREAD

**Issue by spondec** [ccxt/ccxt#9669]
- OS: Windows 10
- Programming Language version: PHP 8.0.7
- CCXT version: 1.53.73

```
new Precise('000977725');
```

```
 ValueError

  gmp_init(): Argument #1 ($num) is not an integer string

  at C:\laragon\www\trader\vendor\ccxt\ccxt\php\Precise.php:21
     17▕             }
     18▕             $decimalIndex = strpos($number, '.');
     19▕             $this->decimals = ($decimalIndex > -1) ? strlen($number) - $decimalIndex - 1 : 0;
     20▕             $integerString = str_replace('.', '', $number);
  ➜  21▕             $this->integer = gmp_init($integerString);
     22▕             $this->decimals = $this->decimals - $modifier;
     23▕         } else {
     24▕             $this->integer = $number;
     25▕             $this->decimals = $decimals;

  1   C:\laragon\www\trader\vendor\ccxt\ccxt\php\Precise.php:21
      gmp_init("000977725")

  2   C:\laragon\www\trader\app\Console\Commands\Trader.php:49
      ccxt\Precise::__construct("000977725")
```

**Comment by frosty00** [comment]
hello, @milkymeda this issue has been fixed in the latest version of ccxt, please upgrade to 1.53.73 )

**Comment by frosty00** [comment]
https://github.com/ccxt/ccxt/pull/9664

**Comment by frosty00** [comment]
actually it looks like the travis build failed so the new build hasn't been pushed to composer yet..., should be fixed today once @kroitor comes back online

**Comment by kroitor** [comment]
@milkymeda This bug should be fixed in CCXT 1.53.74+. Please let us know if you still have this issue after upgrading! Feel free to reopen this issue or just ask further questions, if any. Thanks for your feedback!

**Comment by aFluxx** [comment]
Hi there,

I'm running version `"version": "1.77.62",` of ccxt and I'm still running into this issue:

```
ValueError: gmp_init(): Argument #1 ($num) is not an integer string in file /home/forge/user/vendor/ccxt/ccxt/php/Precise.php on line 21

#0 /home/forge/user/vendor/ccxt/ccxt/php/Precise.php(21): gmp_init()
#1 /home/forge/user/vendor/ccxt/ccxt/php/Precise.php(164): ccxt\Precise->__construct()
#2 /home/forge/user/vendor/ccxt/ccxt/php/bitmart.php(706): ccxt\Precise::string_mul()
#3 /home/forge/user/vendor/ccxt/ccxt/php/bitmart.php(806): ccxt\bitmart->parse_ticker()
#4 /home/forge/user/app/Http/Controllers/Bitmart/PriceFetchController.php(19): ccxt\bitmart->fetch_ticker()
#5 /home/forge/user/app/Http/Controllers/Bitmart/MarketController.php(38): App\Http\Controllers\Bitmart\PriceFetchController->fetch()
#6 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Bitmart\MarketController->fetchFirstContentful()
#7 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#8 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch()
#9 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#10 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#11 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#14 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest()
#16 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\Routing\Middleware\ThrottleRequests->handleRequestUsingNamedLimiter()
#17 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#18 /home/forge/user/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->Laravel\Sanctum\Http\Middleware\{closure}()
#20 /home/forge/user/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#22 /home/forge/user/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /home/forge/user/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#24 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#25 /home/forge/user/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#27 /home/forge/user/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#29 /home/forge/user/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->Laravel\Sanctum\Http\Middleware\{closure}()
#31 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /home/forge/user/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\Pipeline\Pipeline->then()
#33 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->handle()
#34 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\Pipeline\Pipeline->then()
#36 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\Routing\Router->runRouteWithinStack()
#37 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Router.php(666): Illuminate\Routing\Router->runRoute()
#38 /home/forge/user/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Routing\Router->dispatchToRoute()
#39 /home/forge/user/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
#40 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#41 /home/forge/user/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /home/forge/user/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#43 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#44 /home/forge/user/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /home/forge/user/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#46 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#47 /home/forge/user/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#49 /home/forge/user/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#51 /home/forge/user/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\Cors\HandleCors->handle()
#53 /home/forge/user/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#55 /home/forge/user/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 /home/forge/user/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#57 /home/forge/user/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#58 /home/forge/user/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#59 {main}
```

**Comment by ttodua** [comment]
let us know if you still experience any issue with latest ccxt version.
