### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function ccxt\gmp_init() in ccxt/php/Precise.php:21

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9708]
After cloning current version and then `npm run build`, when executing i.e.:

`new ccxt\gateio()`  and then `load_markets()` it leads to that issue.
```
Uncaught Error: Call to undefined function ccxt\gmp_init() in  ccxt/php/Precise.php:21
Stack trace:
#0 ccxt/php/Precise.php(177): ccxt\Precise->__construct()
#1 ccxt/php/Exchange.php(3039): ccxt\Precise::string_neg()
#2 ccxt/php/gateio.php(455): ccxt\Exchange->parse_precision()
#3 ccxt/php/Exchange.php(1726): ccxt\gateio->fetch_markets()
#4  ... ccxt\Exchange->load_markets()
```

**Comment by ttodua** [comment]
Well, seems it needs a separate php extension to be installed and enabled...

**Comment by ttodua** [comment]
For docker, only this helped me https://stackoverflow.com/a/64445115/2377343.
