### ISSUE TITLE
Okex v5 Implicit Method 'privatePostAssetTransfer' Not Working

### ISSUE THREAD

**Issue by drsavant-pub** [ccxt/ccxt#9761]
### Okex5 Transfers are not working.

- OS: win 8.1
- Programming Language version:  node v14.15.4
- CCXT version: 1.54.48

**Code:**
I'm using the API parameters from [this page](https://www.okex.com/docs-v5/en/#rest-api-funding-funds-transfer) on okex.com
_Also, the code doesn't show it but I'm using okex5.js_ 

```
async function run(exchange, coin, amount, destination = 'wallet' ){
  exName = exchange.id
  exchange.verbose = true
    //  1: SPOT 6: FUNDING 
    if ( destination == 'spot' ){
      from = 6
      to = 1
    } else if ( destination = 'wallet' ){
      from = 1
      to = 6
    }
    try {
      //  Transfer type: 0: transfer within account
      results = await exchange.privatePostAssetTransfer({ccy: coin, amt: amount, type: 0, to: to, from: from})
      // console.log(results)
      return results
    }catch (err){
      // console.log('error:', err)
      return {successful: false, error: true, err_msg: err}

  }
}

let ex1 = require('../../objects/arb-exchanges')
let exName = 'okex'
let coin = 'USDT'
let amount = 0.01
let destination = 'spot'    //  spot or wallet only       

let exchange = new ex1[exName].ccxt_exchange
    exchange.apiKey = ex1[exName].apiKey
    exchange.secret = ex1[exName].secret
    if ( ex1[exName].password !== undefined ){
        exchange.password = ex1[exName].password
    }

run(exchange, coin, amount, destination ).then( (results)=>{
    console.log('results came back =>', results)
})
```

**Output/Results:**
```
fetch:
 okex5 POST https://www.okex.com/api/v5/asset/transfer
Request:
 {
  'OK-ACCESS-KEY': '',
  'OK-ACCESS-PASSPHRASE': ,
  'OK-ACCESS-TIMESTAMP': '2021-08-05T22:27:42.677Z',
  'Content-Type': 'application/json',
  'OK-ACCESS-SIGN': ''
}
 {"ccy":"USDT","amt":0.01,"type":0,"to":1,"from":6}

handleRestResponse:
 okex5 POST https://www.okex.com/api/v5/asset/transfer 400 Bad Request
Response:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '67a374367c330eb3-FRA',
  Connection: 'keep-alive',
  'Content-Length': '54',
  'Content-Type': 'application/json',
  Date: 'Thu, 05 Aug 2021 22:27:38 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'cloudflare',
  'Set-Cookie': 'locale=en_US; Max-Age=604800; Expires=Thu, 12-Aug-2021 22:27:38 GMT; Path=/',
  'X-Brokerid': '0',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Xss-Protection': '1; mode=block'
}
 {"code":"51000","data":[],"msg":"Parameter to  error"}

results came back => {
  successful: false,
  error: true,
  err_msg: BadRequest: okex5 {"code":"51000","data":[],"msg":"Parameter to  error"}
      at okex5.throwExactlyMatchedException (C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\base\Exchange.js:540:19)
      at okex5.handleErrors (C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\okex.js:2741:18)
      at C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\base\Exchange.js:602:18
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async timeout (C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\base\functions\time.js:195:24)
      at async run (C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\lib\misc\tests\test-trans-okex.js:15:17) {
    constructor: [class BadRequest extends ExchangeError]
  }
}
```

**Comment by kroitor** [comment]
@drsavant-pub all params must be strings, including the `to` and `from` numerals – those should be numeric string literals. Let us know if that does not help.

**Comment by drsavant-pub** [comment]
ccxt version:  1.54.74

I turned all parameters into strings as you can see here: {"ccy":"USDT","amt":"0.01","type":"0","to":"1","from":"6"}.
I even tried the password as a string and a number, but neither way worked.  I am still getting this error:

What's next?

_It looks like the same error to me:_
```

fetch:
 okex5 POST https://www.okex.com/api/v5/asset/transfer
Request:
 {
  'OK-ACCESS-KEY': '',
  'OK-ACCESS-PASSPHRASE': '',
  'OK-ACCESS-TIMESTAMP': '2021-08-11T20:31:09.615Z',
  'Content-Type': 'application/json',
  'OK-ACCESS-SIGN': ''
}
 {"ccy":"USDT","amt":"0.01","type":"0","to":"1","from":"6"}

handleRestResponse:
 okex5 POST https://www.okex.com/api/v5/asset/transfer 400 Bad Request
Response:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '67d439da1c404e7f-FRA',
  Connection: 'keep-alive',
  'Content-Length': '54',
  'Content-Type': 'application/json',
  Date: 'Wed, 11 Aug 2021 20:31:10 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'cloudflare',
  'Set-Cookie': 'locale=en_US; Max-Age=604800; Expires=Wed, 18-Aug-2021 20:31:10 GMT; Path=/',
  'X-Brokerid': '0',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Xss-Protection': '1; mode=block'
}
 {"code":"51000","data":[],"msg":"Parameter to  error"}

results came back => {
  successful: false,
  error: true,
  err_msg: BadRequest: okex5 {"code":"51000","data":[],"msg":"Parameter to  error"}
      at okex5.throwExactlyMatchedException (C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\base\Exchange.js:540:19)
      at okex5.handleErrors (C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\okex.js:2741:18)
      at C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\base\Exchange.js:602:18
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async timeout (C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\base\functions\time.js:195:24)
      at async run (C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\lib\misc\tests\test-okex5-trans.js:15:17) {
    constructor: [class BadRequest extends ExchangeError]
  }
}
```

**Comment by drsavant-pub** [comment]
ccxt version:  1.54.74

I turned all parameters into strings as you can see here:
{"ccy":"USDT","amt":"0.01","type":"0","to":"1","from":"6"}.
I even tried the password as a string and a number, but neither way
worked.  I am still getting this error:

What's next?

_It looks like the same error to me:_
```

fetch:
 okex5 POST https://www.okex.com/api/v5/asset/transfer
Request:
 {
  'OK-ACCESS-KEY': '',
  'OK-ACCESS-PASSPHRASE': '',
  'OK-ACCESS-TIMESTAMP': '2021-08-11T20:31:09.615Z',
  'Content-Type': 'application/json',
  'OK-ACCESS-SIGN': ''
}
 {"ccy":"USDT","amt":"0.01","type":"0","to":"1","from":"6"}

handleRestResponse:
 okex5 POST https://www.okex.com/api/v5/asset/transfer 400 Bad Request
Response:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '67d439da1c404e7f-FRA',
  Connection: 'keep-alive',
  'Content-Length': '54',
  'Content-Type': 'application/json',
  Date: 'Wed, 11 Aug 2021 20:31:10 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="
https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'cloudflare',
  'Set-Cookie': 'locale=en_US; Max-Age=604800; Expires=Wed, 18-Aug-2021
20:31:10 GMT; Path=/',
  'X-Brokerid': '0',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Xss-Protection': '1; mode=block'
}
 {"code":"51000","data":[],"msg":"Parameter to  error"}

results came back => {
  successful: false,
  error: true,
  err_msg: BadRequest: okex5 {"code":"51000","data":[],"msg":"Parameter to
 error"}
      at okex5.throwExactlyMatchedException
(C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\base\Exchange.js:540:19)
      at okex5.handleErrors
(C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\okex.js:2741:18)
      at
C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\base\Exchange.js:602:18
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async timeout
(C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\node_modules\ccxt\js\base\functions\time.js:195:24)
      at async run
(C:\_a-temp\nodejs\cc-arbitration\ccxt-ot3\lib\misc\tests\test-okex5-trans.js:15:17)
{
    constructor: [class BadRequest extends ExchangeError]
  }
}
```
Rex
801.915.7975
