### ISSUE TITLE
Error using quoteOrderQty in Binance Futures

### ISSUE THREAD

**Issue by priyanshudon** [ccxt/ccxt#9785]
I'm unable to override the 'quantity' and 'price' parameters using `quoteOrderQty` for `create_order` in Binance Futures. Kindly help!

**Code:**
```python3
import ccxt

exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'API_KEY',
    'secret': 'API_SECRET',
    'options': {
        'defaultType': 'future'
    }
})

params = {
    'quoteOrderQty': 5,
    'test': True 
}

amount = None
price = None
order = exchange.create_order('BTC/USDT', 'market', 'buy', amount, price, params)

print(order)
```

**Error:**  
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 593, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try.py", line 19, in <module>
    order = exchange.create_order('BTC/USDT', 'market', 'buy', amount, price, params)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/binance.py", line 1992, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/binance.py", line 2975, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 609, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/binance.py", line 2969, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."}
```

**Comment by kroitor** [comment]
Binance futures API does not support quoteOrderQty on the server side: https://binance-docs.github.io/apidocs/futures/en/#new-order-trade you have to specify the `amount` in contracts:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

Hope that answers your question. Let us know if not.

**Comment by kroitor** [comment]
> In order to open a short position, we need to send positionSide as 'short' and side as 'sell', right?

It depends on whether you want to open a short position in one-way mode (the default) or in a hedged mode. The positionSide param is only necessary for hedged positions. If you just want to stick to defaults, simply sell the contracts you want – that will open a short position if it's not open before. If you had an already-open short position, the size of it will increase, if it was a long position, your sell will decrease it.
