### ISSUE TITLE
Call to undefined function ccxt\gmp_init() in Precise.php

### ISSUE THREAD

**Issue by koala974** [ccxt/ccxt#9801]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: PHP
- CCXT version:1.54.72

```
**$exchange->fetchBalance();
The script run right on navigator manually but when i want to run in crontask its crash with the error. Dont  understand why ? Any ideas ?**
```

```
PHP Fatal error:  **Uncaught Error: Call to undefined function ccxt\gmp_init()** in /volume1/web/cron/crypto/bot/ccxt/php/Precise.php:21
Stack trace:
#0 /volume1/web/cron/crypto/bot/ccxt/php/Precise.php(191): ccxt\Precise->__construct('100.37673635')
#1 /volume1/web/cron/crypto/bot/ccxt/php/Exchange.php(1829): ccxt\Precise::string_sub('100.37673635', '70.81913635')
#2 /volume1/web/cron/crypto/bot/ccxt/php/ftx.php(985): ccxt\Exchange->parse_balance(Array)
#3 /volume1/web/cron/crypto/mywallet.php(29): ccxt\ftx->fetch_balance()
#4 /volume1/web/cron/crypto/mywallet.php(71): getBalance('ftx')
#5 {main}
  thrown in /volume1/web/cron/crypto/bot/ccxt/php/Precise.php on line 21
```

**Comment by koala974** [comment]
solved
