### ISSUE TITLE
gate.io calculate fee not working for taker fees

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#9808]
- OS: linux
- Programming Language version: python
- CCXT version: 1.54.88

`get_calculate_fee` seems to fail for gate.io when using maker fees (while taker-fees do work).

I'm not sure i fully understand the cause of this, as both taker and maker fees seem properly defined, but load_markets seems to fail loading the "maker" fee.
https://github.com/ccxt/ccxt/blob/89543573487d682adc3a1c6a9175527c5162f988/js/gateio.js#L284-L285

```
import ccxt
exchange = ccxt.gateio()
lm = exchange.load_markets()
pair = "ETH/USDT"
# This call fails
exchange.calculate_fee(pair, 'limit', 'buy', 1, 1, 'maker')


exchange.calculate_fee(pair, 'limit', 'buy', 1, 1, 'taker')
print(lm['ETH/USDT'])
> 
```

```
TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-ecf6f10e8f43> in <module>
----> 1 exchange.calculate_fee(pair, 'limit', 'buy', 1, 1, 'maker')

~/.pyenv/versions/3.9.2/envs/trade_392/lib/python3.9/site-packages/ccxt/base/exchange.py in calculate_fee(self, symbol, type, side, amount, price, takerOrMaker, params)
   1956         rate = market[takerOrMaker]
   1957         if cost is not None:
-> 1958             cost *= rate
   1959         return {
   1960             'type': takerOrMaker,

TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'
```

```
> lm['ETH/USDT']

{'percentage': True,
 'tierBased': True,
 'feeSide': 'get',
 'maker': None,       ## Why is this None ... ? 
 'taker': 0.2,
 'tiers': {'maker': [[0.0, 0.002],
   [1.5, 0.00185],
   [3.0, 0.00175],
   [6.0, 0.00165],
   [12.5, 0.00155],
   [25.0, 0.00145],
   [75.0, 0.00135],
   [200.0, 0.00125],
   [500.0, 0.00115],
   [1250.0, 0.00105],
   [2500.0, 0.00095],
   [3000.0, 0.00085],
   [6000.0, 0.00075],
   [11000.0, 0.00065],
   [20000.0, 0.00055],
   [40000.0, 0.00055],
   [75000.0, 0.00055]],
  'taker': [[0.0, 0.002],
   [1.5, 0.00195],
   [3.0, 0.00185],
```

**Comment by xmatthias** [comment]
Great, thanks! :+1:

**Comment by engmajo** [comment]
I'm still having this issue in calculating fees 

2021-08-15 15:54:30,182 - freqtrade.wallets - INFO - Wallets synced.
2021-08-15 15:54:31,676 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for VET/USDT with stake_amount: 123.75 ...
2021-08-15 15:54:32,024 - uvicorn.access - INFO - 172.28.0.1:33918 - "POST /api/v1/forcebuy HTTP/1.1" 500
2021-08-15 15:54:32,024 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 81, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 77, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 124, in forcebuy
    trade = rpc._rpc_forcebuy(payload.pair, payload.price)
  File "/freqtrade/freqtrade/rpc/rpc.py", line 616, in _rpc_forcebuy
    if self._freqtrade.execute_buy(pair, stakeamount, price, forcebuy=True):
  File "/freqtrade/freqtrade/freqtradebot.py", line 517, in execute_buy
    order = self.exchange.create_order(pair=pair, ordertype=order_type, side="buy",
  File "/freqtrade/freqtrade/exchange/exchange.py", line 706, in create_order
    dry_order = self.create_dry_run_order(pair, ordertype, side, amount, rate)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 598, in create_dry_run_order
    dry_order = self.check_dry_limit_order_filled(dry_order)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 682, in check_dry_limit_order_filled
    self.add_dry_order_fee(pair, order)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 608, in add_dry_order_fee
    'cost': dry_order['cost'] * self.get_fee(pair),
  File "/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1110, in get_fee
    return self._api.calculate_fee(symbol=symbol, type=type, side=side, amount=amount,
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1958, in calculate_fee
    cost *= rate
TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'

**Comment by kroitor** [comment]
@engmajo have you updated your versions?
@xmatthias we might need a CCXT version bump in Freqtrade...

**Comment by engmajo** [comment]
@kroitor @xmatthias, yes we have to update Freqtrade because the current version is still 1.54.74

**Comment by xmatthias** [comment]
@engmajo you can update ccxt independently with `pip install -U ccxt`.

While this fix does provide us some steps forward, i have my doubts gate.io will work flawlessly, so i've not version-bumped it intentionally so far as i want to perform some more tests. 
I only version-bump manually if it's impacting an already working/supported exchange - gate.io will still need quite some more tests.
