### ISSUE TITLE
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url

### ISSUE THREAD

**Issue by Maxximiliann** [ccxt/ccxt#9827]
Ubuntu 20.04.2 LTS
Python 3.9.6
ccxt 1.55.12

```
#waves_exchange_config.py
import os
import ccxt
from loguru import logger


@logger.catch
def connection():
    wallet_id = os.environ.get('WALLET_ID')
    wallet_key = os.environ.get('WALLET_KEY')

    waves_exch = ccxt.wavesexchange({
        'apiKey': wallet_id,
        'secret': wallet_key,
    })
    return waves_exch


if __name__ == '__connection__':
    connection()
```

```
#WAVESDEX_exchange_status.py
from loguru import logger
import waves_exchange_config as we


@logger.catch
def log_exch_down_status():
    waves_exch = we.connection()

    exch_status = waves_exch.fetchStatus()
    if exch_status['status'] != 'ok':
        exch_status_report = f'Exchange status: {exch_status}'
        logger.error(exch_status_report)


if __name__ == '__log_exch_down_status__':
    log_exch_down_status()
```

```
#wallet_balances_stream.py
import sys
import time
import simplejson as json
from loguru import logger
import waves_exchange_config as we
from erlastic import Atom as atom
from erlastic import port_connection
from requests.exceptions import HTTPError
from WAVESDEX_exchange_status import log_exch_down_status
from ccxt.base.errors import RequestTimeout, NetworkError


logger.add('Logs/wallet_balances_stream.py_error_log_{time}.log',
           format="{time:HH:mm:ss!UTC} {message}",
           rotation="100 MB")


_mailbox, port = port_connection()
waves_exch = we.connection()


@logger.catch
def send_updated_wallet_balances(updated_balances_json):
    try:
        port.send((atom('ok'), updated_balances_json))
    except (BrokenPipeError) as error:
        logger.error(error)
        sys.exit()


@logger.catch
def get_balance():
    try:
        balances = waves_exch.fetchBalance()
    except (RequestTimeout, NetworkError, HTTPError):
        get_balance()
    else:
        updated_balances_json = json.dumps(balances)
        send_updated_wallet_balances(updated_balances_json)


@logger.catch
def main():
    log_exch_down_status()
    get_balance()
    time.sleep(.5)
    main()


if __name__ == '__main__':
    main()
```

`wallet_balances_stream.get_balance() `operates properly for about 15 mins or so and then this happens:

```
20:36:25 An error has been caught in function 'main', process 'MainProcess' (770542), thread 'MainThread' (139959444714112):
Traceback (most recent call last):

  File "/home/maxximiliann/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/base/exchange.py", line 592, in fetch
    response.raise_for_status()
    │        └ <function Response.raise_for_status at 0x7f4ad75d41f0>
    └ <Response [400]>
  File "/home/maxximiliann/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
          │         │                        └ <Response [400]>
          │         └ '400 Client Error: Bad Request for url: http://matcher.waves.exchange/matcher/balance/reserved/67fXaEkvDbdW4SxE1XyT61tnHLsVoG...
          └ <class 'requests.exceptions.HTTPError'>

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://matcher.waves.exchange/matcher/balance/reserved/67fXaEkvDbdW4SxE1XyT61tnHLsVoGimGoo2KdqVgp7q
```

What's causing this error and how can it be avoided?

**Comment by ttodua** [comment]
the issue was stale and can not be confirmed now by me. if anyone would still experience any similar issue, let us know again
