### ISSUE TITLE
Binance fetch_ticker 

### ISSUE THREAD

**Issue by Iorek69** [ccxt/ccxt#984]
PASTE_YOUR_TEXT_DESCRIPTION_HERE

- OS: Windows 7
- Programming Language: Python
- CCXT version:  1.10.299
- Exchange: Binance
- Method: fetch_ticker()

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

MUST_READ_THIS https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

REPLACE_WITH_YOUR_CODE_TO_REPRODUCE_THE_BUG_HERE

exchange = ccxt.binance()
exchange.verbose = True
exchange.fetch_ticker('XRP/BTC')

ALSO

exchange = ccxt.binance()
exchange.verbose = True
exchange.fetch_ticker('BTC/USDT')

REPLACE_WITH_YOUR_VERBOSE_OUTPUT_HERE

Traceback (most recent call last):
  File "C:/Users/Documents/WinPython-64bit-3.5.3.1Qt5/Project101/GDAX websocket v2.py", line 126, in collecMarket
    c = exchange.fetch_ticker(tick)
  File "C:\Users\Documents\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\ccxt\binance.py", line 315, in fetch_ticker
    self.load_markets()
  File "C:\Users\Documents\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\ccxt\base\exchange.py", line 783, in load_markets
    markets = self.fetch_markets()
  File "C:\Users\Documents\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\ccxt\binance.py", line 195, in fetch_markets
    'price': market['quoteAssetPrecision'],
KeyError: 'quoteAssetPrecision'

↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

**Comment by kroitor** [comment]
This is fixed, update to most recent version, please.

**Comment by Iorek69** [comment]
thx
