### ISSUE TITLE
bybit v2PublicGetSymbols method not found

### ISSUE THREAD

**Issue by alesha1488** [ccxt/ccxt#9861]
- FreeBSD 12.2-RELEASE-p4:
- PHP v7.3.29:
- CCXT v1.55.43:
```
[Exchange Error] v2PublicGetSymbols method not found, try underscore_notation instead of camelCase for the method being called

#0 /vendor/ccxt/ccxt/php/bybit.php(406): ccxt\Exchange->__call('v2PublicGetSymb...', Array)
#1 /vendor/ccxt/ccxt/php/Exchange.php(1754): ccxt\bybit->fetch_markets(Array)
#2 /vendor/ccxt/ccxt/php/bybit.php(588): ccxt\Exchange->load_markets()
```

**Comment by kroitor** [comment]
Fixed in 1.55.47, the new build 1.55.47 will arrive in ~20 minutes, thanks for the feedback!
