### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int' in watch_orders

### ISSUE THREAD

**Issue by diwenshi61** [ccxt/ccxt#9890]
Ubuntu Server 20.04 LTS
Python 3.8.10
ccxt==1.55.26
ccxtpro==0.8.19

Have seen this bug a few times across multiple ccxtpro versions.
Generally the failure continues to propagate every time watch_orders is called so the program is not able to recover.

```
Traceback (most recent call last):
...
File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxtpro/kraken.py", line 609, in watch_orders
return await self.watch_private('openOrders', symbol, since, limit, params)
File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxtpro/kraken.py", line 465, in watch_private
return self.filter_by_symbol_since_limit(result, symbol, since, limit, True)
File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1872, in filter_by_symbol_since_limit
return self.filter_by_value_since_limit(array, 'symbol', symbol, since, limit, 'timestamp', tail)
File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1866, in filter_by_value_since_limit
array = [entry for entry in array if entry[key] >= since]
File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1866, in <listcomp>
array = [entry for entry in array if entry[key] >= since]
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

Slightly earlier this error was encountered which may have caused the above error:

```
Exception in callback FastClient.receive_loop.<locals>.handler() at /home/ubuntu/.local/lib/python3.8/site-packages/ccxtpro/base/fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at /home/ubuntu/.local/lib/python3.8/site-packages/ccxtpro/base/fast_client.py:20>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxtpro/base/fast_client.py", line 25, in handler
    self.handle_message(message)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxtpro/base/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxtpro/base/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxtpro/kraken.py", line 904, in handle_message
    return method(client, message, subscription)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxtpro/kraken.py", line 731, in handle_orders
    messageHash = name + ':' + keys[i]
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by ttodua** [comment]
this issue had been stale, i can no longer reproduce this too. 
if anyone has relevant issues, let us know again
