### ISSUE TITLE
[wavesexchange] RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Maxximiliann** [ccxt/ccxt#9895]
OS: Ubuntu 20.04.2 LTS
    Programming Language version: Python 3.9.6
    CCXT version: ccxt 1.55.12

```
#waves_exchange_config.py
import os
import ccxt
from loguru import logger


@logger.catch
def connection():
    wallet_id = os.environ.get('WALLET_ID')
    wallet_key = os.environ.get('WALLET_KEY')

    waves_exch = ccxt.wavesexchange({
        'apiKey': wallet_id,
        'secret': wallet_key,
    })
    return waves_exch


if __name__ == '__connection__':
    connection()



#wallet_balances_stream.py
import sys
import time
import simplejson as json
from loguru import logger
import waves_exchange_config as we
from erlastic import Atom as atom
from erlastic import port_connection
from requests.exceptions import HTTPError
from ccxt.base.errors import RequestTimeout, NetworkError, AuthenticationError


logger.add('Logs/wallet_balances_stream.py_error_log_{time}.log',
           format="{time:HH:mm:ss!UTC} {message}",
           rotation="100 MB")

_mailbox, port = port_connection()


@logger.catch
def submit_report(success_status, report):
    full_report_json = json.dumps(report)
    try:
        port.send((atom(success_status), (full_report_json)))
    except (BrokenPipeError) as error:
        logger.exception(error)
        sys.exit()


@logger.catch
def get_balances():
    waves_exch = we.connection()
    try:
        balances = waves_exch.fetchBalance()
    except (RequestTimeout, NetworkError, HTTPError, AuthenticationError) as error:
        logger.exception(error)
        submit_report('error', {'error': str(error)})
    except Exception as crash_report:
        logger.exception(crash_report)
        submit_report('fatal_error', {'fatal_error': str(crash_report)})
    else:
        submit_report('ok', balances)


@logger.catch
def main():
    get_balances()
    time.sleep(.5)
    main()


if __name__ == '__main__':
    main()

```

```
13:09:12 maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):

  File "/home/bob/Desktop/Foo/lib/Python/Foo/wallet_balances_stream.py", line 54, in <module>
    main()
    └ <function main at 0x7f6885ab2af0>

  File "/home/bob/Desktop/Foo/lib/Python/Foo/wallet_balances_stream.py", line 50, in main
    main()
    └ <function main at 0x7f6885ab2af0>

  File "/home/bob/Desktop/Foo/lib/Python/Foo/wallet_balances_stream.py", line 50, in main
    main()
    └ <function main at 0x7f6885ab2af0>

  File "/home/bob/Desktop/Foo/lib/Python/Foo/wallet_balances_stream.py", line 50, in main
    main()
    └ <function main at 0x7f6885ab2af0>
  [Previous line repeated 481 more times]

  File "/home/bob/Desktop/Foo/lib/Python/Foo/wallet_balances_stream.py", line 48, in main
    get_balances()
    └ <function get_balances at 0x7f6885ab2790>

> File "/home/bob/Desktop/Foo/lib/Python/Foo/wallet_balances_stream.py", line 34, in get_balances
    balances = waves_exch.fetchBalance()
               │          └ <function wavesexchange.fetch_balance at 0x7f6885aee9d0>
               └ ccxt.wavesexchange()

  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 1284, in fetch_balance
    self.load_markets()
    │    └ <function Exchange.load_markets at 0x7f688603f550>
    └ ccxt.wavesexchange()
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1367, in load_markets
    markets = self.fetch_markets(params)
              │    │             └ {}
              │    └ <function wavesexchange.fetch_markets at 0x7f6885ae78b0>
              └ ccxt.wavesexchange()
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 363, in fetch_markets
    response = self.marketGetTickers()
               │    └ <function Exchange.request at 0x7f6885acf0d0>
               └ ccxt.wavesexchange()
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/base/exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
           │     │        └ {'path': 'tickers', 'api': 'market', 'method': 'GET'}
           │     └ ccxt.wavesexchange()
           └ <function Exchange.request at 0x7f688603a700>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
           │    │      │     │    │       │       │        └ None
           │    │      │     │    │       │       └ None
           │    │      │     │    │       └ {}
           │    │      │     │    └ 'GET'
           │    │      │     └ 'market'
           │    │      └ 'tickers'
           │    └ <function Exchange.fetch2 at 0x7f688603a670>
           └ ccxt.wavesexchange()
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           │    │     │               │                  │                   └ {'url': 'https://waves.exchange/api/v1/forward/marketdata/api/v1/tickers', 'method': 'GET', 'body': None, 'headers': {'conten...
           │    │     │               │                  └ {'url': 'https://waves.exchange/api/v1/forward/marketdata/api/v1/tickers', 'method': 'GET', 'body': None, 'headers': {'conten...
           │    │     │               └ {'url': 'https://waves.exchange/api/v1/forward/marketdata/api/v1/tickers', 'method': 'GET', 'body': None, 'headers': {'conten...
           │    │     └ {'url': 'https://waves.exchange/api/v1/forward/marketdata/api/v1/tickers', 'method': 'GET', 'body': None, 'headers': {'conten...
           │    └ <function Exchange.fetch at 0x7f688603ad30>
           └ ccxt.wavesexchange()
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/base/exchange.py", line 571, in fetch
    response = self.session.request(
               │    │       └ <function Session.request at 0x7f6886085c10>
               │    └ <requests.sessions.Session object at 0x7f688731d4c0>
               └ ccxt.wavesexchange()
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 10, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7f68860860d0>
           └ <requests.sessions.Session object at 0x7f688731d4c0>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'timeout': 10, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7f6886085550>
        └ <requests.adapters.HTTPAdapter object at 0x7f6887322310>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7f688642bc10>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f6885a682b0>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7f688642b9d0>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f6885a682b0>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
    │   └ <function raise_from at 0x7f68864e20d0>
    └ <module 'urllib3.packages.six' from '/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/urllib3/packa...
  File "<string>", line 3, in raise_from
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
                       │    └ <function HTTPConnection.getresponse at 0x7f68864b1550>
                       └ <urllib3.connection.HTTPSConnection object at 0x7f6885ad2a60>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
    │        └ <function HTTPResponse.begin at 0x7f68864af8b0>
    └ <http.client.HTTPResponse object at 0x7f68867328b0>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/http/client.py", line 335, in begin
    self.headers = self.msg = parse_headers(self.fp)
    │    │         │    │     │             │    └ None
    │    │         │    │     │             └ <http.client.HTTPResponse object at 0x7f68867328b0>
    │    │         │    │     └ <function parse_headers at 0x7f68864af670>
    │    │         │    └ None
    │    │         └ <http.client.HTTPResponse object at 0x7f68867328b0>
    │    └ None
    └ <http.client.HTTPResponse object at 0x7f68867328b0>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/http/client.py", line 234, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
           │     │      │             │                └ 'Date: Mon, 30 Aug 2021 13:09:12 GMT\r\nContent-Type: application/json; charset=utf-8\r\nTransfer-Encoding: chunked\r\nConnec...
           │     │      │             └ <class 'http.client.HTTPMessage'>
           │     │      └ <class 'email.parser.Parser'>
           │     └ <module 'email.parser' from '/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/parser.py'>
           └ <module 'email' from '/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/__init__.py'>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
           │    │     │        │                  └ False
           │    │     │        └ 'Date: Mon, 30 Aug 2021 13:09:12 GMT\r\nContent-Type: application/json; charset=utf-8\r\nTransfer-Encoding: chunked\r\nConnec...
           │    │     └ <class '_io.StringIO'>
           │    └ <function Parser.parse at 0x7f68864e2e50>
           └ <email.parser.Parser object at 0x7f6886732910>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/parser.py", line 56, in parse
    feedparser.feed(data)
    │          │    └ 'Date: Mon, 30 Aug 2021 13:09:12 GMT\r\nContent-Type: application/json; charset=utf-8\r\nTransfer-Encoding: chunked\r\nConnec...
    │          └ <function FeedParser.feed at 0x7f68864918b0>
    └ <email.feedparser.FeedParser object at 0x7f6886732850>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/feedparser.py", line 176, in feed
    self._call_parse()
    │    └ <function FeedParser._call_parse at 0x7f6886491940>
    └ <email.feedparser.FeedParser object at 0x7f6886732850>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/feedparser.py", line 180, in _call_parse
    self._parse()
    │    └ <method-wrapper '__next__' of generator object at 0x7f68873d0970>
    └ <email.feedparser.FeedParser object at 0x7f6886732850>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/feedparser.py", line 295, in _parsegen
    if self._cur.get_content_maintype() == 'message':
       │    │    └ <function Message.get_content_maintype at 0x7f68864acee0>
       │    └ <http.client.HTTPMessage object at 0x7f6886732400>
       └ <email.feedparser.FeedParser object at 0x7f6886732850>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/message.py", line 594, in get_content_maintype
    ctype = self.get_content_type()
            │    └ <function Message.get_content_type at 0x7f68864ace50>
            └ <http.client.HTTPMessage object at 0x7f6886732400>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
            │    │                   └ <object object at 0x7f6886568920>
            │    └ <function Message.get at 0x7f68864acaf0>
            └ <http.client.HTTPMessage object at 0x7f6886732400>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
           │    │      │                  │  └ 'application/json; charset=utf-8'
           │    │      │                  └ 'Content-Type'
           │    │      └ <function Compat32.header_fetch_parse at 0x7f6886490f70>
           │    └ Compat32()
           └ <http.client.HTTPMessage object at 0x7f6886732400>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
           │    │                │     └ 'application/json; charset=utf-8'
           │    │                └ 'Content-Type'
           │    └ <function Compat32._sanitize_header at 0x7f6886490dc0>
           └ Compat32()
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
       │               └ 'application/json; charset=utf-8'
       └ <function _has_surrogates at 0x7f6886566dc0>
  File "/home/bob/.asdf/installs/python/3.9.6/lib/python3.9/email/utils.py", line 57, in _has_surrogates
    s.encode()
    │ └ <method 'encode' of 'str' objects>
    └ 'application/json; charset=utf-8'

RecursionError: maximum recursion depth exceeded while calling a Python object

```

**Comment by ttodua** [comment]
Late reply, though I'll add notes:
1) At first, you are doing it wrong when you are initializing exchange in a loop. Instead, you should initialize exchange-object (`waves_exch`) once out of loop, and use that  exchange-object inside loop.
2) Second, I've tested that script (but with removed parts of your custom packages/imports) and it seems to work quite fine. I think you should check out the latest CCXT version (there have been also some updated in waves-exchange class too, idk if related or unrelated, but try it).

feel free to reopen the topic if issue still there.
