### ISSUE TITLE
[Binance] Do a "sell all" like "buy all"

### ISSUE THREAD

**Issue by NicolasWent** [ccxt/ccxt#9920]
Hello,

I've seen this way in order to do a "buy all": https://github.com/ccxt/ccxt/issues/6391#issuecomment-576247330

What I mean by buy all, is to use all your crypto in the trade.

For example, here I convert all of my bitcoin to ethereum:

```python
import ccxt
exchange = ccxt.binance({
    'apiKey': 'API KEY',
    'secret': 'API SECRET',
    'enableRateLimit': True
})

def get_crypto_amount(crypto):
    balance = exchange.fetch_balance()
    return balance['free'][crypto]

symbol = 'ETH/BTC'
params = {
    'quoteOrderQty': get_crypto_amount('BTC')
}

exchange.create_order(symbol, 'market', 'buy', None, None, params)
```

It works fine, all my bitcoin has been converted into ethereum

But now, I want to sell all my ethereum into bitcoin, doing the same by just replacing 'buy' with sell, does the following output:

```
Traceback (most recent call last):
  File "/home/nicolas/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 593, in fetch
    response.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://testnet.binance.vision/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nicolas/.local/lib/python3.9/site-packages/ccxt/binance.py", line 2011, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/home/nicolas/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "/home/nicolas/.local/lib/python3.9/site-packages/ccxt/binance.py", line 3571, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/nicolas/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/nicolas/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 609, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/nicolas/.local/lib/python3.9/site-packages/ccxt/binance.py", line 3530, in handle_errors
    raise InvalidOrder(self.id + ' order amount should be evenly divisible by lot size ' + body)
ccxt.base.errors.InvalidOrder: binance order amount should be evenly divisible by lot size {"code":-2010,"msg":"Filter failure: LOT_SIZE"}
```

code used:

```python
import ccxt
exchange = ccxt.binance({
    'apiKey': 'API KEY',
    'secret': 'API SECRET',
    'enableRateLimit': True
})

def get_crypto_amount(crypto):
    balance = exchange.fetch_balance()
    return balance['free'][crypto]

symbol = 'ETH/BTC'
params = {
    'quoteOrderQty': get_crypto_amount('ETH')
}

exchange.create_order(symbol, 'market', 'sell', None, None, params)
```

I have tried several ways of achieving this, but unsuccessfuly.

**Comment by NicolasWent** [comment]
Hello,

So I already had the solution to my problem but it was not working on their test environment :'(

First of all, 'quoteOrderQty', only specify the amount of the 'left' coin, in my example, when I put 12 in my 'quoteOrderQty', it means that I want to sell bitcoin until I have 12 ETH (the reverse of what I want to do :-1: )

So the solution is simpler:

```python
# Required because I don't specify the price
exchange.options['createMarketBuyOrderRequiresPrice'] = False
exchange.create_market_sell_order('ETH/BTC', get_crypto_amount('ETH'))
```

Using the code above in test environment puts the status of the order to 'expired' thats why I thought it was not working, but in prod environment it is working fine.

Sorry for this inconvenience.

**Comment by kroitor** [comment]
@NicolasWent thanks for your feedback, we appreciate it!
