### ISSUE TITLE
Occasionally calls to fetch_balance() cause a TypeError, occurring with multiple exchanges

### ISSUE THREAD

**Issue by rxall** [ccxt/ccxt#9957]
- OS: Ubuntu 20.04
- Programming Language version: PHP 8.0.10 
- CCXT version: 1.55.92

```
$balances = $exchange->fetch_balance();
```

```
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /home/error-test/vendor/ccxt/ccxt/php/bitfinex2.php:587
Stack trace:
#0 /home/error-test/vendor/ccxt/ccxt/php/bitfinex2.php(587): count()
#1 /home/error-test/fetch-balance.php(85): ccxt\bitfinex2->fetch_balance()
#2 {main}
  thrown in /home/error-test/vendor/ccxt/ccxt/php/bitfinex2.php on line 587

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /home/error-test/vendor/ccxt/ccxt/php/bitfinex2.php:587
```

**Comment by kroitor** [comment]
@rxall please, always provide your code, including the instantiation (but without your keys), and your verbose request+response output precisely as documented here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```PHP
<?php

// ...

date_default_timezone_set('UTC');

echo 'PHP v' . PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION . '.' . PHP_RELEASE_VERSION . "\n";
echo 'CCXT v' . \ccxt\Exchange::VERSION . "\n";

$exchange_id = 'bitfinex2';
$exchange_class = '\\ccxt\\' . $exchange_id;
$exchange = new $exchange(array(
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
));
$markets = $exchange->load_markets();
$exchange->verbose = true; // uncomment for debugging purposes if necessary
$balance = $exchange->fetch_balance();
```

**Comment by kroitor** [comment]
@rxall the timeout itself is ok, i mean, getting them occasionally is ok, but it should not throw a TypeError of course,. It should throw a documented exception instead: https://github.com/ccxt/ccxt/wiki/Manual#error-handling. I will investigate and will be back to you asap.

**Comment by kroitor** [comment]
@rxall pardon for the delay on my side, will do my best to get to it this week.
