### ISSUE TITLE
Illegal characters found in parameter 'price'

### ISSUE THREAD

**Issue by lnguyen** [ccxt/ccxt#996]
Illegal characters found in parameter 'price' for binance XVG - ETH. Not sure if api changed, this worked yesterday

Not getting this in BTC trades.
- OS: linux
- Programming Language: nodejs
- CCXT version: 1.10.508
- Exchange: binance
- Method:  

```
[ { size: '5397.74659822',
    orig_size: '5397.74659822',
    remaining_size: '5397.74659822',
    orig_price: '0.00020651',
    cancel_after: 'day',
    product_id: 'XVG-ETH',
    type: 'limit',
    side: 'buy',
    post_only: true } ]
An error occurred { Error: binance {"code":-1100,"msg":"Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'."}
    at binance.handleErrors (/app/node_modules/ccxt/js/binance.js:752:27)
    at response.text.then.text (/app/node_modules/ccxt/js/base/Exchange.js:433:18)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeError] }
```

**Comment by kroitor** [comment]
Can you show a minimal but a complete snippet of code to reproduce the problem and the **verbose** output (set .verbose = true on the exchange)?

**Comment by lnguyen** [comment]
I'm using zenbot let me see if I can turn on verbose,

```
      var order = {}
      client.createOrder(joinProduct(opts.product_id), opts.type, opts.side, this.roundToNearest(opts.size, opts), opts.price, args).then(result => {
        if (result && result.message === 'Insufficient funds') {
          order = {
            status: 'rejected',
            reject_reason: 'balance'
          }
          return cb(null, order)
        }
        order = {
          id: result ? result.id : null,
          status: 'open',
          price: opts.price,
          size: this.roundToNearest(opts.size, opts),
          post_only: !!opts.post_only,
          created_at: new Date().getTime(),
          filled_size: '0',
          ordertype: opts.order_type
        }
        orders['~' + result.id] = order
        cb(null, order)
      }).catch(function (error) {
        console.error('An error occurred', error)
        return retry('buy', func_args)
      })
```

**Comment by kroitor** [comment]
```JavaScript
      var order = {}

      client.verbose = true // ←------------- ADD THIS LINE HERE

      client.createOrder(joinProduct(opts.product_id), opts.type, opts.side, this.roundToNearest(opts.size, opts), opts.price, args).then(result => {
        if (result && result.message === 'Insufficient funds') {
          order = {
            status: 'rejected',
            reject_reason: 'balance'
          }
          return cb(null, order)
        }
        order = {
          id: result ? result.id : null,
          status: 'open',
          price: opts.price,
          size: this.roundToNearest(opts.size, opts),
          post_only: !!opts.post_only,
          created_at: new Date().getTime(),
          filled_size: '0',
          ordertype: opts.order_type
        }
        orders['~' + result.id] = order
        cb(null, order)
      }).catch(function (error) {
        console.error('An error occurred', error)
        return retry('buy', func_args)
      })
```

**Comment by lnguyen** [comment]
Interesting the post is getting a null value for price. Let me see if I can trace that down.

**Comment by lnguyen** [comment]
Closing for now, I was running code that caused this issue and need to see what difference is between updated code and old code
