### ISSUE TITLE
Huobi marketorder cannot be created

### ISSUE THREAD

**Issue by thebottoken** [ccxt/ccxt#9964]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: linux
- Programming Language version: nodejs
- CCXT version:    1.56.18

```
this.exchange.createMarketOrder(pair, side, amount); // user huobi pro account to create marketorder
```

```
(node:476942) UnhandledPromiseRejectionWarning: ExchangeError: huobipro {"status":"error","err-code":"invalid-type","err-msg":"Parameter `type` is invalid.","data":null}
    at huobipro.handleErrors (/home/aaa/bb/node_modules/ccxt/js/huobi.js:1592:23)
    at /home/aaa/bbb/node_modules/ccxt/js/base/Exchange.js:657:18
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async timeout (/home/aaa/bbb/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async huobipro.createOrder (/home/aaa/bbb/node_modules/ccxt/js/huobi.js:1195:26)
    at async BulkTradeMO.run (/home/aaa/bbb/strategy/BulkTradeMO.ts:101:22)
    at async main (/home/aaa/bbb/strategy/SlowTrade.ts:66:11)
```

**Comment by kroitor** [comment]
@thebottoken please, paste your code and your request+response output with verbose mode enabled, including the exchange instantiation code, but without your keys:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by thebottoken** [comment]
```
fetch:
 huobipro POST https://api.huobi.pro/v1/order/orders/place?AccessKeyId=****&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2021-09-09T22%3A33%3A06&Signature=xxxx
Request:
 {
  'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36',
  'Content-Type': 'application/json'
} 
 {"account-id":"xxx","symbol":"ttusdt","type":"BUY-market","client-order-id":"xx","amount":"7658"} 

handleRestResponse:
 huobipro POST https://api.huobi.pro/v1/order/orders/place?AccessKeyId=****&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2021-09-09T22%3A33%3A06&Signature=xxxx
Response:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '68c3e057fce534e1-NRT',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json; charset=UTF-8',
  Date: 'Thu, 09 Sep 2021 22:33:06 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  'Request-Id': '6fca59ad5b6d8bc68721ad9a7a41be74',
  Server: 'cloudflare',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
  'X-Hb-Ratelimit-Requests-Expire': '1631226788568',
  'X-Hb-Ratelimit-Requests-Remain': '99',
  'X-Request-Id': '531d6a9f83f122c38018cf2016825236'
} 
 {"status":"error","err-code":"invalid-type","err-msg":"Parameter `type` is invalid.","data":null} 

```

**Comment by thebottoken** [comment]
is it good enough?

**Comment by kroitor** [comment]
@thebottoken looks like you are passing an uppercase-side to `createMarketOrder()`. It must be lowercase, according to CCXT docs: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
Let us know if that does not answer your question or does not help.

**Comment by thebottoken** [comment]
@kroitor  yes, i passed uppercase to createMarketOrder. The docs also requires uppercase, right? 

I tried lowercase. I cannot fetch price or trade.

**Comment by kroitor** [comment]
@thebottoken 

>  The docs also requires uppercase, right?

Nope. The docs say that the side must be in lower case:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

**Comment by kroitor** [comment]
```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.huobi({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET'
})

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes if necessary

order = exchange.create_market_order('TT/USDT', 'buy', 7658)
pprint(order)
```

**Comment by thebottoken** [comment]
Ok. Thanks. I thought it was the symbol which should be lowercased. 

I just switched to lower case for `side`. it worked.

**Comment by kroitor** [comment]
@thebottoken good to know you figured it out, thanks for the feedback!
