### ISSUE TITLE
Node.js: Not all sent parameters were read; read '11' parameter(s) but was sent '13'

### ISSUE THREAD

**Issue by GianniKoch** [ccxt/ccxt#9971]
Hi,
Thanks for this amazing lib! 

I got this error and don't know what to do, is there something obvious that I missed?
Thank you in advance!

Kind Regards

- OS: Windows 10
- Programming Language version: Node.js v14.15.3
- CCXT version: 1.56.29

```
await this.client.createOrder('BTCUSDT', 'limit', 'buy', amount, limit, { 'stop': 'loss', 'stop_price': stop })
```

```
BadRequest: binance {"code":-1104,"msg":"Not all sent parameters were read; read '11' parameter(s) but was sent '13'."}
    at binance.throwExactlyMatchedException ( location... \node_modules\ccxt\js\base\Exchange.js:595:19)
    at binance.handleErrors ( location... \node_modules\ccxt\js\binance.js:4384:18)
    at  location... \node_modules\ccxt\js\base\Exchange.js:657:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timeout ( location... \node_modules\ccxt\js\base\functions\time.js:195:24)
    at async binance.request ( location... \node_modules\ccxt\js\binance.js:4411:26)
    at async binance.createOrder ( location... \node_modules\ccxt\js\binance.js:2310:26)
    at async binanceClient.buyTrade ( location...\lib\binanceClient.js:284:13) {
  constructor: [class BadRequest extends ExchangeError]
}
```

**Comment by kroitor** [comment]
Hi! 

In your `params` you're passing `stop` and `stop_loss`. Binance does not support those. As noted in the CCXT Manual, params-overrides are mostly exchange-specific and must conform to the underlying exchanges' API docs:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://binance-docs.github.io/apidocs/spot/en/#margin-account-new-order-trade
- https://binance-docs.github.io/apidocs/futures/en/#new-order-trade
- https://binance-docs.github.io/apidocs/delivery/en/#new-order-trade

Are you trying to place a spot-margin stop order, or a usdt/coinm stop?

**Comment by GianniKoch** [comment]
Hi,
Thank you for your quick response :D

I'm fairly new with you lib so what I try to do is make a trade order like this with the target and stop.
What would be the correct setup for the function? I got the current setup from this issue: https://github.com/ccxt/ccxt/issues/1557

Thank you in advance!

![image](https://user-images.githubusercontent.com/36133967/133041067-c5c3bf5d-8ae7-403b-9430-1c67988484a9.png)

**Comment by kroitor** [comment]
> I'm fairly new with your lib, so what I try to do is make a trade order like this (image) with the target and stop.
> What would be the correct setup for the function?

To answer your question precisely, we need to know if you are trying to place a BTC/USDT margin order or a BTC/USDT perpetual order (USDT-margined) with Binance? Those are different types of orders.

**Comment by GianniKoch** [comment]
Hi,

I'm thinking of a margined order.

Thank you in advance!

**Comment by kroitor** [comment]
@GianniKoch try the following example, edit it for your keys and amounts/prices, if it does not help, please, uncomment the verbose line and paste your verbose output here:

- https://github.com/ccxt/ccxt/blob/master/examples/js/binance-margin-stop-order.js

```JavaScript
"use strict";

const ccxt = require ('../../ccxt.js')

console.log ('CCXT Version:', ccxt.version)

async function main () {

    const exchange = new ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_API_SECRET',
        'options': {
            'defaultType': 'margin',
        },
    })

    const markets = await exchange.loadMarkets ()

    exchange.verbose = true // uncomment for debugging purposes if necessary

    const symbol = 'BTC/USDT'
    const type = 'limit'
    const side = 'buy'
    const amount = YOUR_AMOUNT_HERE
    const price = YOUR_PRICE_HERE
    const params = {
        'stopPrice': YOUR_STOP_PRICE_HERE,
    }

    try {
        const order = await exchange.createOrder (symbol, type, side, amount, price, params)
        console.log (order)
    } catch (e) {
        console.log (e.constructor.name, e.message)
    }
}

main ()

```

**Comment by GianniKoch** [comment]
Hi @kroitor ,

I'm getting an other error :(

Thank you in advance!

```
fetch:
 binance POST https://api.binance.com/api/v3/order
Request:
 {
  'X-MBX-APIKEY': 'q1mWWrN6HwpsAvZluTpGqyT1G4AWXnCYJATzEcD64pYfnHvEglldEblUMHyAxayX',
  'Content-Type': 'application/x-www-form-urlencoded'
}
 timestamp=1631525013059&recvWindow=5000&symbol=BTCUSDT&type=LIMIT&side=SELL&newClientOrderId=x-R4BD3S824b21b24077ad4c299e70f0&newOrderRespType=FULL&quantity=0.2231&price=44311.74&timeInForce=GTC&stopPrice=44436.63&signature=c7b3c110d09068d2775eed65de
e87d07526355a55f3b3e04052f546b8fad7278

handleRestResponse:
 binance POST https://api.binance.com/api/v3/order 400 Bad Request
Response:
 {
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Length': '68',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Mon, 13 Sep 2021 09:23:33 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  Via: '1.1 a6f1f6a7cb5a93f6f494d1d5945d867c.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'J_mj4si1_BoPLCAPhU3f368qyBIdkSbv0PmDtbmYas3Nr1ej2mZKbA==',
  'X-Amz-Cf-Pop': 'MAD50-C1',
  'X-Cache': 'Error from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Mbx-Used-Weight': '22',
  'X-Mbx-Used-Weight-1m': '22',
  'X-Mbx-Uuid': '05b63eb1-75fc-4857-ac8f-f91b4339ae48',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
}
 {"code":-1106,"msg":"Parameter 'stopPrice' sent when not required."}
```
```
BadRequest: binance {"code":-1106,"msg":"Parameter 'stopPrice' sent when not required."}
    at binance.throwExactlyMatchedException (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\base\Exchange.js:595:19)
    at binance.handleErrors (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\binance.js:4384:18)
    at E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\base\Exchange.js:657:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timeout (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\base\functions\time.js:195:24)
    at async binance.request (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\binance.js:4411:26)
    at async binance.createOrder (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\binance.js:2310:26)
    at async binanceClient.sellTrade (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\lib\binanceClient.js:307:27) {
  constructor: [class BadRequest extends ExchangeError]

```

**Comment by kroitor** [comment]
@GianniKoch i've added some edits, do you have the same issue with this edited version of the snippet? ↓

```JavaScript
"use strict";

const ccxt = require ('../../ccxt.js')

console.log ('CCXT Version:', ccxt.version)

async function main () {

    const exchange = new ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_API_SECRET',
        'options': {
            'defaultType': 'margin',
        },
    })

    const markets = await exchange.loadMarkets ()

    exchange.verbose = true // uncomment for debugging purposes if necessary

    const symbol = 'BTC/USDT'
    const type = 'STOP_LOSS_LIMIT'
    const side = 'buy'
    const amount = YOUR_AMOUNT_HERE
    const price = YOUR_PRICE_HERE
    const params = {
        'stopPrice': YOUR_STOP_PRICE_HERE,
        'timeInForce': 'GTC',
    }

    try {
        const order = await exchange.createOrder (symbol, type, side, amount, price, params)
        console.log (order)
    } catch (e) {
        console.log (e.constructor.name, e.message)
    }
}

main ()
```

**Comment by GianniKoch** [comment]
Hi @kroitor,
I now have an other error as shown below
Thanks in advance!

```
fetch:
 binance POST https://api.binance.com/sapi/v1/margin/order
Request:
 {
  'X-MBX-APIKEY': 'q1mWWrN6HwpsAvZluTpGqyT1G4AWXnCYJATzEcD64pYfnHvEglldEblUMHyAxayX',
  'Content-Type': 'application/x-www-form-urlencoded'
}
 timestamp=1631527887884&recvWindow=5000&symbol=BTCUSDT&type=STOP_LOSS_LIMIT&side=BUY&newClientOrderId=x-R4BD3S822e32e93753be4370919357&newOrderRespType=RESULT&quantity=0&price=44656.33&timeInForce=GTC&stopPrice=44547.4&signature=da353421e2fa988450449
4ec103d26ea0de186424c72b5fbb3172d144b701586

handleRestResponse:
 binance POST https://api.binance.com/sapi/v1/margin/order 400 Bad Request
Response:
 {
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Length': '97',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Mon, 13 Sep 2021 10:11:27 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  Via: '1.1 d8c266ed74a4ecc05eeffe79fa473f7e.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': '0Mq9OMPThk5AInmF89iAAlxNGrOysELdMxfe_Ihdd29HtlB-n4Je5g==',
  'X-Amz-Cf-Pop': 'MAD50-C1',
  'X-Cache': 'Error from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Sapi-Used-Ip-Weight-1m': '1',
  'X-Sapi-Used-Uid-Weight-1m': '6',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
}
 {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or malformed."}

BadRequest: binance {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or malformed."}
    at binance.throwExactlyMatchedException (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\base\Exchange.js:595:19)
    at binance.handleErrors (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\binance.js:4384:18)
    at E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\base\Exchange.js:657:18
BadRequest: binance {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or mal
formed."}
    at binance.throwExactlyMatchedException (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\Tra
deBot\node_modules\ccxt\js\base\Exchange.js:595:19)
    at binance.handleErrors (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modul
es\ccxt\js\binance.js:4384:18)
    at E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\base\Exchange.js:657:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timeout (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\base\functions\time.js:195:24)
    at async binance.request (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\binance.js:4411:26)
    at async binance.createOrder (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\node_modules\ccxt\js\binance.js:2310:26)
    at async binanceClient.buyTrade (E:\OneDrive - Koch Business Solutions\Projecten\0 Projecten\TradeBot\lib\binanceClient.js:292:27) {
  constructor: [class BadRequest extends ExchangeError]
}

```
```
            const params = {
                'stopPrice': stop,
                'timeInForce': 'GTC',
            }

            const order = await this.client.createOrder('BTC/USDT', 'STOP_LOSS_LIMIT', 'buy', amount, limit, params)
```

**Comment by kroitor** [comment]
@GianniKoch ok, so the code is correct, but now it looks like your `amount` is lower than the minimum:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

```JavaScript
const ccxt = require ('ccxt')

async function main () {
    const exchange = new ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_API_SECRET',
        'options': {
            'defaultType': 'margin',
        },
    })
    
    const markets = await exchange.loadMarkets ()
    
    const market = exchange.market('BTC/USDT')
    
    console.log (markets)
    console.log ('----------------------------------------------------------------')
    console.log ('The minimal amount for', symbol, 'is', market['limits']['amount']['min'])
}

main ()
```

**Comment by GianniKoch** [comment]
Oh, my bad, I see it now.
Well if it works now, thanks for your time and effort!
I appreciate it <3

**Comment by GianniKoch** [comment]
Hi @kroitor I didn't want to make a new issue but I have this issue where it throws an error "binance stop price would trigger immediately but... it shouldn't? I'm not that aware of how the limit-stop works though.

this is my function:

await this.client.createOrder('BTC/USDT', 'STOP_LOSS_LIMIT', 'buy', amount, limit, params)

where amount is X :p
limit = 44533 (1:1.75 risk)
and stop = 44458 (= candle open price in the image)

![image](https://user-images.githubusercontent.com/36133967/133132357-16e3dd33-d24c-45e1-bd92-4efd52dfbaad.png)

But I get the stop price trigger immediatly error. I hope you understand my question and maybe can help me with it since it's kinda driving me insane xD

Thank you in advance!

**Comment by kroitor** [comment]
@GianniKoch the _"Stop price would trigger immediately"_ is covered here:

- https://github.com/ccxt/ccxt/issues/8194
- https://github.com/ccxt/ccxt/issues/3097
- https://github.com/ccxt/ccxt/search?q=Stop+price+would+trigger+immediately&type=issues
